### ISSUE TITLE
Auto-exclude 'local.demandforce' from external JS concatenation

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1008]
From this ticket support => https://secure.helpscout.net/conversation/588293924/69450/?folderId=273768

The script from "local.demandforce" has to be excluded from the JS concatenation.

**Comment by Tabrisrp** [comment]
Do you think it will still apply with the new combine that will integrate 3rd party scripts?

**Comment by GeekPress** [comment]
Yes. Our external excluded scripts is used for JS files which needs to stay at the same place for several reason:
- the location is important. Like aweber JS form. If you want to have your form in the sidebar we have to put the JS into the sidebar too
- JS in-line script issue. Which could be fixed by the new option. 

But in our list, we can’t remember which JS file is excluded for which reason I explained

**Comment by Tabrisrp** [comment]
This will be auto-excluded by default in 3.1 with combined JS because it doesn't have a .js extension
