### ISSUE TITLE
Create compatibility with Ultimate GDPR Compliance plugin

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1009]
Plugin: https://codecanyon.net/item/ultimate-gdpr-compliance-toolkit-for-wordpress/21704224
(available in our account)
I think it just needs a mandatory cookie set:  ct-ultimate-gdpr-cookie

Setting the mandatory cookie works for me on my own site, waiting for customer confirmation here: 
https://secure.helpscout.net/conversation/590253277/69835?folderId=377611

HS tag: `ultimate gdpr compliance toolkit for wordpress`

**Comment by webtrainingwheels** [comment]
Got confirmation from the customer mentioned above, that the mandatory cookie fix worked for him.

**Comment by arunbasillal** [comment]
Related tickets: 
- https://secure.helpscout.net/conversation/599474285/71282/

**Comment by arunbasillal** [comment]
Ultimate GDPR now includes compatibility at their end. Details here - https://secure.helpscout.net/conversation/755464014/93163/#thread-2107984124

**Comment by arunbasillal** [comment]
Closing this because of:
- https://github.com/wp-media/wp-rocket/issues/1009#issuecomment-456131710
- The plugin has ` 5,459 Sales` as per code canyon. Not big enough to do compatibility and maintenance at our end.
