### ISSUE TITLE
EU Cookie Law 3.0.1: Cookie message does not go away

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#1010]
- WordPress 4.9.6
- WP Rocket 3.0.5-beta1
- EU Cookie Law 3.0.1

EU Cookie Law set up with default settings, only checked the _Activate_ option.

Cookie message gets added on the front-end; **should go away after a click on the _Ok_ button, but doesn’t.**

Activating the _Auto Block_ option in EU Cookie Law fixes the issue. However, since we say WP Rocket supports this third-party plugin, we should fix this on our end.

**Comment by piotrbak** [comment]
Tested with `EU Cookie Law 3.1.6` and WP Rocket 3.10.6, the message goes away correctly.
