### ISSUE TITLE
No styles on settings page, because page hook doesn’t fire

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#1013]
**WP Rocket Version:** 3.5.0.1

## Issue reported by customer

No styles loaded on WP Rocket settings page.

_(Reference: [Support ticket](https://secure.helpscout.net/conversation/595794160/70511?folderId=714999))_

## Analysis

The page hook firing on the settings page was not `settings_page_{slug}` as hard-coded in our plugin [[1](https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/admin/ui/enqueue.php#L20), [2](https://github.com/wp-media/wp-rocket/blob/v3.0.5.1/inc/admin/ui/enqueue.php#L85), [3](https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/classes/admin/settings/class-page.php#L110)], but `admin_page_{slug}`. 

That behaviour seemed connected to either one of these plugins:

- Gravity Forms
- Nav Menu Manager
- User Role Editor
- WP Media folder

I did not find out what exactly caused the page hook to be renamed, but the behaviour stopped when I deactivated these 4 plugins, and it reappeared when I activated any one of them again.

Curiously, _Gravity Forms_ is a very popular plugin, but we have not heard about styles missing on our settings page from other customers.

## Proposed solution

Detect settings page hook name dynamically instead of hardcoding it.

**Comment by Tabrisrp** [comment]
No other report of this has been added since the opening of the issue, so closing this as a one-off.

https://github.com/wp-media/wp-rocket/pull/1014#issuecomment-569694871
