### ISSUE TITLE
Notice in CDN Tab when Cloudflare add-on is active

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1024]
Some users are confused if they should enable the CDN in the CDN tab of WP Rocket when they are using Cloudflare. Its a valid confusion because Cloudflare is also a CDN. 

It would be handy to show a notice in the CDN tab saying that the CDN tab need not be configured while using Cloudflare.

**Comment by arunbasillal** [comment]
Related tickets: 

- https://secure.helpscout.net/conversation/604500562/71928?folderId=273761

**Comment by Tabrisrp** [comment]
The copywriting for the notice needs to be prepared

**Comment by Tabrisrp** [comment]
The notice will have to be inside the grey field instead of outside, but I believe it's ok

**Comment by Tabrisrp** [comment]
The current design and markup doesn't allow for that unfortunately

**Comment by GeekPress** [comment]
The best will be to have one single sentence for X add-ons like: 

Cloudflare, Sucuri are currently enabled...

And

Cloudflare is currently enabled...

**Comment by Tabrisrp** [comment]
I updated the notice code to match with this, I think it looks way better
