### ISSUE TITLE
Minification is not applied for other languages when using TLD in WPML

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1026]
When the WPML option "A different domain per language" is enable, pages are cache but minification is not applied on the other domains.

**Comment by KTJ-Media** [comment]
Something tells me that it has something to do with the domain WP rocket reads before optimization.

I tried to define WP_HOME and WP_SITEURL like this in wp-config.php

if($_SERVER['HTTP_HOST'] == 'domain.dk'){
define( 'WP_HOME', 'https://domain.dk' );
define( 'WP_SITEURL', 'https://domain.dk' );
}

if($_SERVER['HTTP_HOST'] == 'domain.com'){
define( 'WP_HOME', 'https://domain.com' );
define( 'WP_SITEURL', 'https://domain.com' );
}

And logged in to wordpress on the domain where it did not work, and saved the wp rocket settings. Now both domains work

**Comment by webtrainingwheels** [comment]
related HS tags: `wpml``domain per language` (probably missing some older ones that may simply fall under `wpml`)

**Comment by webtrainingwheels** [comment]
https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/250924/conversations/19731797575

**Comment by piotrbak** [comment]
Another ticket:
https://secure.helpscout.net/conversation/709698240/86582?folderId=2415573

**Comment by arunbasillal** [comment]
User reported that its working perfectly in the `3.2.4` beta - https://secure.helpscout.net/conversation/749306632/92332/
