### ISSUE TITLE
Wrong license details shown in WP Rocket Dashboard page

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#1028]
Some users have a problem as they see wrong license data in WP Rocket Settings page, in Dashboard. Although their license is Infinite for example, they see Plus with expired date (01/01/1970).

Example ticket - https://secure.helpscout.net/conversation/591457727/69989/?folderId=343180

User - [sia+wprocket@imaseo.co](https://wp-rocket.me/wp-admin/user-edit.php?user_id=62830&wp_http_referer=%2Fwp-admin%2Fusers.php%3Fs%3Dsia%252Bwprocket%2540imaseo.co%26action%3D-1%26new_role%26paged%3D1%26action2%3D-1%26new_role2)

I tested their license on my site, and the issue can be replicated.

We checked (Jonathan and me) with Postman app and it was everything ok with the license. Details are visible in license-data.php as well.

**Comment by Tabrisrp** [comment]
The email needs to be URL encoded to prevent any issue with some characters, making the value invalid when sending the POST request.
