### ISSUE TITLE
Filter request: Allow Lazyload on account-pages while DONOTROCKETOPTIMIZE is defined.

### ISSUE THREAD

**Issue by superjunky** [wp-media/wp-rocket#1032]
While having private photo-galleries on account pages (for several photography-plugins), it is useful to not remove the lazyload-functionality on those account pages.

This can be done by adding a simple filter.

Please review the pull request:

- https://github.com/wp-media/wp-rocket/pull/742

If not possible, let me know what changes are needed. I'm open for discussion.

Thank you!

**Comment by superjunky** [comment]
While having this filter-hook requested 6 months ago (https://github.com/wp-media/wp-rocket/pull/742), I haven't received any reply yet.

Would it be possible for anyone to review the pull request?
I'm a happy wp-rocket user, and as a developer I really hope to see you consider requests for implementation of a very basic (but useful) hook.

**Comment by GeekPress** [comment]
This could be a part of this feature request:
https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/13-enable-optimizations-on-uncached-pages

@superjunky You are free to vote for this feature on our new roadmap ;)
