### ISSUE TITLE
Problem deactivate Polylang

### ISSUE THREAD

**Issue by NicolasKulka** [wp-media/wp-rocket#1038]
Hello, j'ai un petit beug.

Impossible de désactiver polylang, lorsque j'ai WP Rocket d'activé.

PHP Fatal error:  Call to undefined function pll_languages_list() in /home/clients/nicolask/prod/nicolas2/wp-content/plugins/wp-rocket/inc/functions/i18n.php on line 183

Version Polylang : 2.3.7
 Version WP Rocket : 3.0.5.1

**Comment by Tabrisrp** [comment]
I can't replicate the issue on a default test installation.

Is it happening on a multisite?

**Comment by NicolasKulka** [comment]
single site

**Comment by arunbasillal** [comment]
@Tabrisrp Wouldn't it be safer to just check `function_exists` for `pll_languages_list()` instead of checking if the plugins are active? Wouldn't that do the same thing while avoiding cases like this?

**Comment by Tabrisrp** [comment]
Is it still an issue?

**Comment by GeekPress** [comment]
Hi @NicolasKulka  🤚

We haven't back from you since @Tabrisrp asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best
