### ISSUE TITLE
Changing currency with WPML + WooCommerce is not detected

### ISSUE THREAD

**Issue by dgwatkins** [wp-media/wp-rocket#1039]
This is David from the WPML compatibility team.

We've had an issue for some time with the multiple currencies feature that WPML adds to WooCommerce (with the help of WooCommerce Multilingual plugin).

The problem is that selecting a different currency doesn't have any effect on cached pages.

We made a filter available in WooCommerce Multilingual that you can use to overcome this:

```
add_filter( 'wcml_is_cache_enabled_for_switching_currency', '__return_true' );
```

Adding that line somewhere should take care of it.
I will send a MR next.

**Comment by emlebrun** [comment]
➤ Arun Basil Lal commented:

This was tested in our main-mega-site/product/woo-single-2/ and works fine. :)
