### ISSUE TITLE
3.1 Alpha - 2 PHP Warning errors

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1041]
No need to have options turned on to get these warnings

Warning:  array_fill(): Number of elements must be positive in ../inc/classes/optimization/class-remove-query-string.php on line 81
Warning:  array_map(): Argument #3 should be an array in ../inc/classes/optimization/class-remove-query-string.php on line 82

**Comment by Tabrisrp** [comment]
Thanks, I was not able to reproduce that locally, but I see why it could happen, so a fix is ready
