### ISSUE TITLE
3.1 Alpha - Combine JS Files - 3rd party files aren't included into the concatenated file

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1043]
I tried to add a 3rd party script manually in the header like this:

![%20d%E2%80%99e%CC%81cran%202018-06-28%20a%CC%80%2011.45.25.png?X-CloudApp-Visitor-Id=461ff95ab5b3eabcbda6b07d2bc4a569&amp;v=37b58568 image](https://d3vv6lp55qjaqc.cloudfront.net/items/1K1g3k2S2p1Y2c2V0b3u/Capture)

The file isn't inserted into the concatenated JS file

**Comment by Tabrisrp** [comment]
`cdn.jsdelivr.net` is included in the list of external domains to not combine, which explain why it doesn't work for this test.

The list is based on what we previously had in the plugin + what autoptimize is using. Possibly some could be removed for exclusion. If you want to review the current list:

https://github.com/wp-media/wp-rocket/blob/branch-3.1/inc/classes/optimization/JS/class-combine.php#L320

**Comment by GeekPress** [comment]
Indeed.

Now I'm wondering if we have to still continue to exclude `cdnjs.cloudflare.com`and `cdn.jsdelivr.net`

from these libraries:

- https://cdnjs.com/
- https://www.jsdelivr.com/

These files are a CDN version of some popular JS scripts and don't necessary use jQuery.

I don't remember exactly which file from these libraries caused an issue with JS concatenation before. As we excluded the entire domain, it could now causes new issue:
- if file from one of these services is used and need jQuery, we will have a jQuery error issue

**Comment by Tabrisrp** [comment]
We can remove those domains from the default exclusion, and we'll add them back if there is the need

**Comment by GeekPress** [comment]
Ok, let's go like that
