### ISSUE TITLE
3.1 Alpha - Combine JS Files - Local script are inserted into the concatenated file

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1044]
We decided to not insert inline script which are added by wp_localize_script().

By checking the concatenated file, we can notice that all inline scripts has been added into it.

**Comment by Tabrisrp** [comment]
We indeed defined that initially. But after some R&D on Autoptimize, they are not excluding those from their combine (except the one with an excluded pattern).

The only way to reliably exclude inline scripts from `wp_localize_script()` is to exclude anything with `CDATA` in it as it's automatically added by WordPress, but this might also exclude unrelated inline scripts which uses this.

It's easy to add, but there also doesn't seem to have any downside to combining `wp_localize_script()` content in fact.

What do you think?

**Comment by GeekPress** [comment]
Good question!

Maybe @Screenfeed will have also a feedback to share about that ^^

**Comment by Screenfeed** [comment]
Folks,

I can see the benefits of combining them.
I don't know the cons of combining them.
I don't know the benefits of excluding them.
I don't know the cons of excluding them.
I don't know the technology used by Remy, so I don't know what can be done or not, what is easy to do or not, what is able to fail or not.

So, sorry but I'll pass.

**Comment by Tabrisrp** [comment]
Ok so in my opinion combining them is safe, as autoptimize is doing it by default since quite some time.

I propose we start like that, and if we run into too much troubles, it will be easy to exclude them with one change in the exclusion array.
