### ISSUE TITLE
3.1 Alpha - Combine Google Fonts stops to work

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1047]
The issue in video:
https://cl.ly/473S3R2b2A2n

**Comment by Tabrisrp** [comment]
It's working for me on my test, can you give me the same sample of fonts you use to replicate the test setup?

**Comment by GeekPress** [comment]
I tried with the new version and now it works. https://media1.giphy.com/media/12NUbkX6p4xOO4/giphy.gif
