### ISSUE TITLE
3.1 Alpha-2 - ga-local.js not removed on Clear Cache

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1056]
When using the Clear Cache link from the admin toolbar, the ga-local.js file is not removed. 
gtm-local.js is correctly removed
Neither file is removed after the add-on has been switched off. To clarify, the option is correctly deactivated on the front end of the site, but the files remain on the server. 
(tester=Lucy)

**Comment by Tabrisrp** [comment]
I tested it again on my local installation and it's removed correctly on cache clearing

**Comment by webtrainingwheels** [comment]
I can still reproduce this issue on beta-6. 
Clear Cache does not remove ga-local.js. 
Cache files are correctly removed from other folders. 
Quick vid: https://jumpshare.com/v/5lSmwtznQ4pwtDHNbt6Q

ga-local.js not being inserted into the cache file either: 
https://jmp.sh/0Lfw5Oa

Nothing in debug log.
Ping me if you want access.
