### ISSUE TITLE
3.1 Alpha-2 - analytics.js still loaded when using default Analytics code

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1057]
I took the default tracking code from Analytics and when it's inserted in the site either manually (directly in header.php), or by using a plugin like Insert Headers and Footers, gtm-local.js is used but [https://www.google-analytics.com/](https://www.google-analytics.com/analytics.js)analytics.js is still loaded and flagged by PageSpeed. 

I see this may be intended from the field guide: _Note that if both analytics and tag manager are present in the HTML (which is not supposed to happen, but we never know), only the analytics one will be optimized._

But considering this is the default Analytics code, from the user's standpoint, it would be expected that both files would be replaced with local versions. 

This is the code I used, taken directly from Analytics account (UA edited for privacy)

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxx-x"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-xxxxxxxx-x');
</script>

(tester=Lucy)

**Comment by Tabrisrp** [comment]
In fact what is happening in this case is that the analytics URL is loaded from the gtm-local.js file, where it's not replace because we're copying the content of the file without changes
