### ISSUE TITLE
3.1 Alpha-2 - deferred JS not skipping files with async attribute

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1058]
update: I don't think it's specific to Deferred JS option being active. can replicate when other file optimization options  are active, without Deferred JS. 

May not turn out to be a real issue, just not sure if it's expected or not:

In 3.0.5.1 this file is not changed by our defer option:
`<script type='text/javascript' src='https://stats.wp.com/e-201828.js' async='async' defer='defer'></script>`
It looks like this with and without our defer option.

In 3.1 when our defer is active, _defer='defer'_ is replaced with our _defer_ tag, like this: 
`<script type="text/javascript" src="https://stats.wp.com/e-201828.js" async="async" defer>`

Tested with another file: 

* No problem if only the async tag is present, the file is untouched.
* If defer='defer' is also present, it behaves the same as above example. 
* Nothing breaks since it's still a defer attribute after all, but should it be happening or is something else going on?

(tester=Lucy)

**Comment by Tabrisrp** [comment]
It's not really an issue since they are interpreted the same way by browsers
