### ISSUE TITLE
3rd Party Scripts cannot be excluded from the administration

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1062]
We cannot exclude 3rd party JS files in the option" Excluded JavaScript files". Since we combine them, we should be able to exclude them from the admin. 

For example for: 

https://cdnjs.cloudflare.com/ajax/libs/Base64/0.3.0/base64.min.js

We should exclude the full script URL. 

Currently this is the exclusion which is incorrect: 

/ajax/libs/Base64/0.3.0/base64.min.js

**Comment by Tabrisrp** [comment]
While I agree on the idea, that would require more changes that we're able to do in the time left until release, because the current sanitize on this field is designed only for internal URLs
