### ISSUE TITLE
3.1 Alpha-2: Inline script not combined on this Avada theme

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1063]
Can be spotted on our mega-site/avada/
Look for this in the source:

```
<script type="text/javascript">jQuery( document ).ready( function() {
var ajaxurl = 'http://mega.wp-rocket.me/avada/wp-admin/admin-ajax.php';
if ( 0 < jQuery( '.fusion-login-nonce' ).length ) {
        jQuery.get( ajaxurl, { 'action': 'fusion_login_nonce' }, function( response ) {
jQuery( '.fusion-login-nonce' ).html( response );
});
}
});</script>
```

(tested by Arun)

**Comment by Tabrisrp** [comment]
it's because of the nonce in the inline script, it's one of the excluded keyword

**Comment by arunbasillal** [comment]
I see it now. Thanks!

For the benefit of someone else: https://github.com/wp-media/wp-rocket/blob/52d0122371f85094c0f0ba5ad66f064d837244e3/inc/classes/optimization/JS/class-combine.php#L297-L317
