### ISSUE TITLE
3.1 Alpha-2: Console errors (TypeError) with Bridge theme

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1064]
You can see it our-mega-site/bridge/
Only WP Rocket is enabled as a plugin.

**Comment by Tabrisrp** [comment]
I don't see the error currently on the test site

**Comment by arunbasillal** [comment]
Please recheck now, the Uncode Visual Composer plugin that was required to render the theme was deactivated. 

These are the console errors I see now:

`TypeError: currentRow is null`
`ReferenceError: Waypoint is not defined`

**Comment by arunbasillal** [comment]
Happiness! I don't see them either. :+1: 
I am wondering if I confused this with another theme (just like I did today).

**Comment by emlebrun** [comment]
➤ Arun Basil Lal commented:

The above comment was meant for uncode theme: https://github.com/wp-media/wp-rocket/issues/1066#issuecomment-405595466
