### ISSUE TITLE
3.1 Alpha-2: Console errors for Ninja form

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1070]
Options in file optimization tab throwing multiple console errors. Can be seen in our-mega-site/genesis/ninja-form/

Combining Google fonts or Remove Query strings or Minify CSS or Minify JS: Error: An "el" .nf-form-layout must exist in DOM

Combining JS: SyntaxError: expected expression, got '<'

**Comment by Tabrisrp** [comment]
This is caused because we're combining script tags that are meant to be template tags with type="text/template". Also DOMDocument doesn't like HTML in script tags, so it's stripping closing tags, breaking the layout.
