### ISSUE TITLE
3.1 Alpha-3: Slider Revolution fails silently with file optimization

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1071]
Test setup here: main-mega-site/slider-revolution-test/

Options that break the slider: 
- Remove query strings ( ReferenceError: jQuery is not defined )
- Combine JS files (No console error, slider did not show up in Firefox)

**Comment by arunbasillal** [comment]
This turns out to be a false alarm. I tested this on a fresh install with alpha-3 and everything went well. :rocket:
