### ISSUE TITLE
Google Tag Manager code not replaced with local file

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1072]
Doesn't work using the Insert Headers and Footers plugin to add the tag manager code like this: https://jmp.sh/ZKmmTr0
No local file is created or used on the site.

Doesn't work with https://wordpress.org/plugins/duracelltomi-google-tag-manager/ either

(tester=Lucy)

**Comment by Tabrisrp** [comment]
Indeed those 2 ways of adding the tracking code have not been considered when implementing the feature

**Comment by ernee** [comment]
+1 on consideration for compatibility with this way. Using Google Tag Manager's tag for Universal Analytics leads to the analytics.js file being loaded and detected in PSI (along with the Google Tag Manager platform script) :

![screen shot 2018-07-19 at 12 03 35 am](https://user-images.githubusercontent.com/8108643/42948382-35f5f4a0-8b24-11e8-8fb5-7b1394f0c431.png)

(I used the duracellomi plugin for integration)

**Comment by remyperona** [comment]
Closing this issue as Google tracking add-on will be removed in WP Rocket 3.9.
