### ISSUE TITLE
Fatal error when activating WPS Hide Login

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1073]
WP Rocket version: 3.1-alpha3 (customer tested with 3.0.5.1)
WPS Hide login version: 1.4.2

```
Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Class 'WPS_Hide_Login' not found in /wp-content/plugins/wp-rocket/inc/3rd-party/plugins/security/wps-hide-login.php:20 Stack trace: #0 /wp-includes/class-wp-hook.php(286): rocket_exlude_wps_hide_login_page(Array) #1 /wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /wp-content/plugins/wp-rocket/inc/functions/options.php(190): apply_filters('rocket_cache_re...', Array) #3 /wp-content/plugins/wp-rocket/inc/functions/htaccess.php(233): get_rocket_cache_reject_uri() #4 /wp-content/plugins/wp-rocket/inc/functions/htaccess.php(118): get_rocket_htaccess_mod_rewrite() #5 /wp-content/plugins/wp-rocket/inc/functions/htaccess.php(42): get_rocket_htaccess_marker() #6 /wp-content/plugins/wp-rocket/inc/3rd-party/plugins/security/wps-hide-login.php(35): flush_rocket_htaccess() #7 /wp-includes/class-wp-hook.php(286): rock in /wp-content/plugins/wp-rocket/inc/3rd-party/plugins/security/wps-hide-login.php on line 20
```

Activating WPS Hide login first and then activating WP Rocket works. 

This is likely the source of the issue (#notetoself): https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/3rd-party/plugins/security/wps-hide-login.php#L32

Interim fix: Deactivate WP Rocket, activate WPS Hide Login and then reactivate WP Rocket. 

Related ticket: https://secure.helpscout.net/conversation/622929033/74307?folderId=273761

**Comment by Tabrisrp** [comment]
WPS_Hide_Login now uses namespacing, which explains why the class is no longer found

**Comment by carlosnpz** [comment]
Won't you publish the fix in the Wordpress plugin page?!
