### ISSUE TITLE
Compatibility with Assets addon for Offload S3?

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#108]
When customer uses assets addon for Offload S3 plugin, minification doesn't work. Is it possible to become compatible?

Link to download Offload S3: 
https://wp-media.slack.com/files/lucyb/F1MTAUYGH/wp-offload-s3-1.1.4.zip

Link to download Assets Add-on: 
https://wp-media.slack.com/files/lucyb/F1MSTS64U/wp-offload-s3-assets-1.1.2.zip

DeliciousBrains Account: 
https://deliciousbrains.com/signin/

Login in 1Password.

Note: I have provided DeliciousBrains with a copy of WP Rocket, so if the fix needs to come from their side, I can follow up with them.

**Comment by GeekPress** [comment]
@Tabrisrp Can we close this issue?

**Comment by Tabrisrp** [comment]
This is a `wontfix` as the new assets addon doesn't minify/concatenate anymore and we should not have any issue with it.
