### ISSUE TITLE
UI Improvement: Inline documentation for textareas to say "one per line"

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1081]
I had a couple of customers ask this directly on how to use these text areas. Whether its comma's or one below the other ([eg](https://secure.helpscout.net/conversation/622976486/74314?folderId=273766)) and I just logged into a customer website and saw this:

![01](https://user-images.githubusercontent.com/5751474/42948829-fbd64120-8b8d-11e8-9736-8cfb0748ad12.png)

Maybe even have the placeholder show to lines so that its intuitive? 
The advanced rules tab already says "(one per line)".

**Comment by Tabrisrp** [comment]
Done in 3.1.3
