### ISSUE TITLE
Managing mandatory/dynamic cookies with server-side cache

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1088]
With hosts such as Kinsta and others that provide a server-side cache not controlled by us, this can cause issues with mandatory and dynamic cookies. For example, when a mandatory cookie is required for compatibility, an unoptimized state (i.e no Rocket optimizations) can be cached by the server. 

Sample tickets: 

- https://secure.helpscout.net/conversation/620545316/73960?folderId=2008123
- https://secure.helpscout.net/conversation/623215516/74358?folderId=377611

related: https://wp-media.slack.com/archives/C43T1AYMQ/p1532539064000099?thread_ts=1532055364.000113&cid=C43T1AYMQ

**Comment by arunbasillal** [comment]
Helper plugin to remove all mandatory cookies: https://www.dropbox.com/s/yg7u9eksowbpn5e/wp-rocket-remove-all-mandatory-cookies.zip?dl=1

Install the helper plugin, clear WP Rocket cache and the hosting specific cache.
