### ISSUE TITLE
Rewrite rules still added if WP Rocket is activated after activating plugins that cannot function with them

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1089]
We have a potential problem in regards to how WP Rocket adds rewrite rules to the .htaccess on WP Rocket activation.

As you know the file `3rd-party.php` is loaded on the `plugins_loaded` hook. 

But the .htaccess is generated with `register_activation_hook` which I believe is fired before `plugins_loaded`. 
This means if WP Rocket is installed after installing Polylang or for example EU Cookie Law, then the rewrite rules will be written to the .htaccess

Simple test: 
- Enable EU Cookie law
- Enable WP Rocket 
- Check .htaccess, rewrite rules will be there. 
- Disable EU Cookie law, enable it again
- No rewrite rules. 

I think one reason why this doesn't come up much is because users generally change WP Rocket settings and this regenerates the .htaccess without the rewrite rules this time. Documenting this nevertheless.

**Comment by Tabrisrp** [comment]
I'm not able to reproduce this. I did tests with Polylang and EU Cookie law, and in both cases, the rewrite rules were not added when activating WP Rocket after one of them.

**Comment by webtrainingwheels** [comment]
I experienced this on a site using Aelia (https://secure.helpscout.net/conversation/1023367191/135160?folderId=377611). The rewrites remained in the htaccess file even after deactivating / reactivating WP Rocket. Enabling separate cache file for mobile option finally removed them. And then they did not get added back after deactivating that option (as expected with Aelia present).

**Comment by piotrbak** [comment]
@Tabrisrp is this still accurate with the new architecture? 🤔
