### ISSUE TITLE
When two plugins that remove WP Rocket .htaccess rewrite rules are installed and one is deactivated, the rewrite rules return

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1090]
In all our 3rd party compatibility plugins where we remove filters with `remove_filter( 'rocket_htaccess_mod_rewrite' , '__return_false' );` filter, since we do not have a priority set, all the filters added even by other compatibility files will be removed. 

For instance, deactivating Polylang will put back the rewrite rules, but if the same user also has EU Cookie Law then the rewrite rules should not be there.

Confirmatory test: 
- WP Rocket + 2 plugins for which we have 3rd party compatibility where we remove the rewrite rules using `rocket_htaccess_mod_rewrite`
- Example: WP Rocket + Polylang + EU Cookie Law
- Check .htaccess, our rewrite rules will be absent no matter what order the plugins are activated.
- Deactivate Polylang or EU Cookie Law. 
- Check .htaccess and the rewrite rules will be back. This will create an issue for EU Cookie Law.

**Comment by Tabrisrp** [comment]
To fix this we can set different priority on the filters for each compatibility using the same ones, that way when doing `remove_filter()` it won't remove all of them.

**Comment by arunbasillal** [comment]
I tried this with Polylang and EU Cookie Law and can confirm that it is resolved :)
