### ISSUE TITLE
3.0.5.1 - Empty Script tag in page header and PHP Notice thrown

### ISSUE THREAD

**Issue by calvineidt** [wp-media/wp-rocket#1091]
On a couple of sites that we have recently updated, we noticed that there was an empty script tag in the header of the page. This seemed unusual as by design all of the scripts were being loaded into the footer of the page on virtually the entire site. With WordPress Debug mode enabled, we were also seeing the error below in our logs.

> PHP Notice:  Undefined index: header in /var/www/domain.com/public_html/wp-content/plugins/wp-rocket/inc/functions/minify.php on line 145

Looking into this I found that it appears that the script is assuming that there will always be at least one  JS file called in the header, and at least one in the footer. On our site I have updated the affected code block to add some checks to prevent any empty tags from being printed or errors thrown. Link to my commit is below.

https://github.com/calvineidt/wp-rocket/commit/6dcee062fc5e64d4502cc32b36d284e7e70a49d7

**Comment by Tabrisrp** [comment]
The combine for javascript is changing completely in 3.1, and this will not be an issue anymore as there will be only one combined file instead of two.
