### ISSUE TITLE
PERMISSIONS ERROR

### ISSUE THREAD

**Issue by ElRicki** [wp-media/wp-rocket#1093]
any one can say me what is the error

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix>[Usuario]</Prefix>
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix>[VIP]</Prefix>
      <Suffix />
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>Russia</Id>
      <DisplayName>Russia</DisplayName>
      <Prefix />
      <Suffix>[Russia]</Suffix>
      <Color>#FE2E2E</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.RusRecluta</Permission>
        <Permission Cooldown="0">essentials.command.warp.RussiaBase</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>USA</Id>
      <DisplayName>USA</DisplayName>
      <Prefix />
      <Suffix>[UUEE]</Suffix>
      <Color>#013ADF</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.USARecluta</Permission>
        <Permission Cooldown="0">essentials.command.warp.USABase</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>MOD</Id>
      <DisplayName>MOD</DisplayName>
      <Prefix>[MOD]</Prefix>
      <Suffix />
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="1">heal</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">essentials.command.tp</Permission>
        <Permission Cooldown="0">essentials.command.jump</Permission>
        <Permission Cooldown="0">essentials.command.back</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by Tabrisrp** [comment]
This doesn't seem to belong here
