### ISSUE TITLE
Main style.css not minified and concatenated

### ISSUE THREAD

**Issue by Keomoniroath** [wp-media/wp-rocket#1095]
WP ROCKET Version 3.0.5.1

Hello,

Minification / Concatenation work for all stylesheet but not main style.css : 
<link rel='stylesheet' href='/wp-content/themes/ms-exp01/style.css' type='text/css' media='all' />

Any idea ?

Thanks

**Comment by Volnus** [comment]
If your main stylesheet properly enqueued or linked into the header in which case it might not be minified by WPRocket also check your plugin settings, to make sure its not enqueued.

**Comment by webtrainingwheels** [comment]
@Keomoniroath Github is for bug reports. Please open a support ticket for your question.
