### ISSUE TITLE
When WP Rocket is enabled on the network of a multisite installation, it can't be disabled.

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#1100]
When WP Rocket is enabled on the network of a multisite installation, it can't be disabled anymore.
No errors show up, no warnings.

Tested on:
WP Rocket 3.0.5.1
WordPress 4.9

Related ticket: [https://secure.helpscout.net/conversation/633923446/75823?folderId=1050088](https://secure.helpscout.net/conversation/633923446/75823?folderId=1050088
)

**Comment by Screenfeed** [comment]
Reproduced. The survey doesn't show and prevent deactivation.

**Comment by Screenfeed** [comment]
Fix:
In `\WP_Rocket\Admin\Deactivation\Deactivation_Intent::insert_deactivation_intent_form()`:
```php
if ( 'plugins' !== $current_screen->id && 'plugins-network' !== $current_screen->id ) {
```

**Comment by Tabrisrp** [comment]
@Screenfeed 👌 you can do the fix and send the PR for 3.1.1

**Comment by Screenfeed** [comment]
Damn, I've been spotted 😄

**Comment by Screenfeed** [comment]
Notice the irony btw, fixing the stuff I hate so much ^^'
