### ISSUE TITLE
Wrong wp-rocket-config file name

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#112]
The wp-rocket-config folder contained 2 files: www.magbag.nl.all and www.magbag.nl.nl.php
The file name is not correct: it's www.magbag.nl.nl.php instead of www.magbag.nl.php

Reference ticket: https://secure.helpscout.net/conversation/228032275/18375/?folderId=628132

**Comment by arunbasillal** [comment]
@Tabrisrp Any idea if this is something that can be replicated?

**Comment by Tabrisrp** [comment]
No idea, I believe it could have been multilingual related. I'm not sure either if we had other cases like this, or if it's still a valid concern.

**Comment by arunbasillal** [comment]
Thanks for the answer. 

Since the issue is 4 years old and since we do not have a clear way to reproduce it or have other similar issues reported, I suggest we close this for now and re-open it if the current situation changes.
