### ISSUE TITLE
The function of deleting the version of files includes the function of minification

### ISSUE THREAD

**Issue by ezekutor** [wp-media/wp-rocket#1125]
If I enable this option, I disable the minification of styles and scripts after saving the settings and clearing the cache. The css, js files change the destination directory and it looks like this /wp-content/cache/busting/1/wp-content/themes/hueman/assets/front/css/main.min-1534164305.css, I do not know why it is necessary but because of these problems I can not normally use http / 2 server push on nginx, I have to disable the function of deleting the version of files ...
tested on nginx 15.2 / litespeed / apache2
php 7.2
wp 4.9.8
wp rocket 3.1.1.1

**Comment by Tabrisrp** [comment]
The remove query strings option does not delete the version of the file, it uses the version in the file name.

`main.min.css?ver=1534164305` will be transformed into `main.min-1534164305.css`

We do that to ensure browser cache busting works correctly when a new version of the file is available.

**Comment by ezekutor** [comment]
Ok
