### ISSUE TITLE
Exclude Inline JS from UI

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1127]
In 3.1+ there are numerous tickets related to Inline JS. 

Excluding via a helper plugin is a bit laborious both for customers and for support. 
Being able to exclude Inline JS from the admin UI would be preferred. 

An additional issue is that pattern matching is not that easy to understand for the average user. Is there a more user-friendly way to do this?

**Comment by Volnus** [comment]
i am going to give my own 2 cents here as well. When I add the plugin to a client site or one of my own it is a bit laborious for me as well to have to go through, add a helper plugin and if something else is broken having to make several changes in an unnecessary fashion. 

But, I will add that this same case could also be made for excluding js files from defer via a ui menu as there are times when the same task needs to be done but for deferred JS.
