### ISSUE TITLE
Compatibility with CDN and custom images in Elementor image carousel

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1129]
When using a custom image size in Elementor's image carousel, WP Rocket does not correctly rewrite the URLs and so the custom image size is not applied, causing display issues. 

![elementor_image_carousel_-_custom_size](https://user-images.githubusercontent.com/1043076/44181568-3f85e900-a0b7-11e8-8e72-5ca05967a08e.jpg)

The URLs that Elementor creates when using this option look like this: 
`https://www.wpthemes.dev.cc/wp-content/uploads/elementor/thumbs/Grumpy-Cat-NO-6-ni3s2l9dy3bixtekaqlp574npg4eeciz94658k8ukm.jpg`

When WP Rocket's Image CDN function is active, the original is used: 
`https://cdn.lucy.net/wp-content/uploads/2017/11/Grumpy-Cat-NO-6.jpg`

**Comment by Tabrisrp** [comment]
Do you have a test site available?

**Comment by arunbasillal** [comment]
I just came across this again - https://secure.helpscout.net/conversation/826535990/104146/

I have left a note with the details and access. Thanks.

**Comment by Tabrisrp** [comment]
`remove_filter( 'wp_get_attachment_url',  'rocket_cdn_file', PHP_INT_MAX );`
`remove_filter( 'wp_get_attachment_image_src', 'rocket_cdn_attachment_image_src', PHP_INT_MAX );`

This fixes the issue
