### ISSUE TITLE
Add sub-option for optimizing inline and external js

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1131]
Including inline and external JS in _Combine JS_ by default is creating a lot of issues. 
[This proposition](https://github.com/wp-media/wp-rocket/issues/1127) partially addresses it by making exclusions easier. 

But often these issues are hard to debug, for both support staff and customers, so having an all or nothing approach (i.e. Combine everything or nothing) isn't really desirable.

**Comment by arunbasillal** [comment]
For now, here is a hack / workaround - https://www.dropbox.com/s/f2nf8mn8yvng7k5/wp-rocket-static-exclude-inline-js.zip?dl=1

Using more generic exclusion pattern here ;)

```
$pattern[] = ';';
$pattern[] = ',';
$pattern[] = '=';
```

**Comment by arunbasillal** [comment]
We have put in a lot of effort into making this work out of the box. So adding this option right now is not desirable. 

With #1127 and using the [hack](https://github.com/wp-media/wp-rocket/issues/1131#issuecomment-413873879), this is still possible.

Also, we have a more comprehensive proposal to do this and automatically avoid these issues. 

Closing this. @webtrainingwheels If you feel strongly against it, please feel free to reopen.
