### ISSUE TITLE
Combine JS consumes too much disk space by creating excessive number of files

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#1132]
This seems to be mainly due to Inline JS, but can also involve external scripts (like ad services).

Essentially, it appears that many of the files being created are near-duplicates of each other, with only some minor variations (perhaps a unique-per-page ID or tracking pixel, for example).

We have **a lot** of tickets about this right now, so I'm only providing a few examples here:
* https://secure.helpscout.net/conversation/640498592/76798
* https://secure.helpscout.net/conversation/641289202/76923
* https://secure.helpscout.net/conversation/641190116/76909

**Comment by webtrainingwheels** [comment]
HS tag: `cache dir size`
