### ISSUE TITLE
Seemingly random URIs not cached due to incorrect use of trim()

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#1136]
https://github.com/wp-media/wp-rocket/blob/db711919bde7dcca153653cf5f56ddc2fd70f7c9/inc/front/process.php#L57

While `explode()` takes a string (here: `'%2F'`) as the separator argument [`trim()` does not](http://php.net/manual/en/function.trim.php)—it takes a character list.

As a consequence, each of the characters `%` and `2` and `F` get filtered out, and not only when they appear as the unique string `%2F`. This can result in problems with URIs beginning or ending with these characters.

For example:
```php
// Gets cached
$path = 'https://example.com/v1/';

// Does not get cached
$path = 'https://example.com/v2/';
```

## Suggested solution

Replace line 57 with:
```php
$path = explode( '%2F', rawurlencode( trim( $path ), '/' ) );
```

A [customer](https://secure.helpscout.net/conversation/642735268/77117?folderId=714999) tested this on their site, and said it seemed to work. Further tests required, of course.

**Comment by arunbasillal** [comment]
Duplicate of #914

**Comment by glueckpress** [comment]
Ha, missed that one, thanks @arunbasillal!
