### ISSUE TITLE
mod_deflate rules conflict with video in Safari

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#114]
Customers report that they have a background video (.mp4, .webm) which disappears only in Safari when WP Rocket is active. 

The solution is: 
add_filter('rocket_htaccess_mod_deflate', '__return_false');

Examples: 
https://secure.helpscout.net/conversation/228782404/18480/?folderId=377611
https://secure.helpscout.net/conversation/226153355/18034/?folderId=273766

In both cases the customers also have Cloudflare active, not sure if that's a factor or not.

**Comment by MarcinKilarski** [comment]
Unfortunately, `add_filter('rocket_htaccess_mod_deflate', '__return_false');` didn't solve the issue for me. The site on which I experienced this issue does not use any CDN.

It seems like every time we save WP Rocket settings in any tab, the video works in Safari for a few minutes.

When it works in Safari the server responds with the 200 status code in the file header when inspected using CURL.
`curl -i https://mysite.com/my-video.mp4`

When it does not work, the status code is the 206 Partial Content.

@laurentdebricon Could you give a bit more details on how you solve this issue? I still experience this issue :(

**Comment by laurentdebricon** [comment]
sudo a2enmod headers
sudo service nginx restart
