### ISSUE TITLE
Auto-Exclude Inline JS related to GA Enhanced Ecommerce

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1155]
Related to: `cache dir size` issue.

When using Google Analytics Enhanced Ecommerce tracking, unique Inline JS is created per page because the products etc are different per page. 

Here's an example of the inline JS that we should exclude: 
http://snippi.com/s/ko2g9ca

Further example from the same combined file as above: 
https://www.diffchecker.com/tiVfVAMP

Example cases:
https://secure.helpscout.net/conversation/642843027/77135?folderId=377611
https://secure.helpscout.net/conversation/641388349/76934/?folderId=2273852

**Comment by Tabrisrp** [comment]
This case is a complicated one:
- the inline JS can be excluded, but they're using jQuery
- With combined JS, jQuery will be combined too, so it will be loaded after the inline script, generating an error
- That means jQuery would also need to be excluded from combine here for everything to work
