### ISSUE TITLE
File optimizations don’t work anymore with SuperCacher enabled on Siteground

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1161]
On SiteGround, and have their Dynamic Cache enabled, that actually takes precedence over WP Rocket's own caching -- which is only used as a fallback in the event that SiteGround's caching fails.

WP Rocket should still be able to apply its other optimizations to pages -- however, there's an issue whereby the check for the `$_GET` superglobal content is failing due to how the server is processing the GET request:

We expected the GET request to be empty, or to contain some specific keys that are allowed to be served the cache version and apply the other optimizations (minification, lazyload, etc).

The `$_GET` with SuperCacher includes the path to the page requested as a key, so it's stopping the process.

Tickets: 
[https://secure.helpscout.net/conversation/642981293/77153?folderId=1213662](https://secure.helpscout.net/conversation/642981293/77153?folderId=1213662)
[https://secure.helpscout.net/conversation/639305587/76592/?folderId=273764](https://secure.helpscout.net/conversation/639305587/76592/?folderId=273764)

**Comment by GeekPress** [comment]
I'm closing this one after checked with @WordPresseur. We don't have the issue anymore.
