### ISSUE TITLE
Auto-Exclude Inline JS from EDD Free Downloads add-on

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1165]
https://easydigitaldownloads.com/downloads/free-downloads/
sample script: http://snippi.com/s/6gdlgd7

`mobile_url`is the dynamic part

ticket: https://secure.helpscout.net/conversation/647889202/77811?folderId=377611

**Comment by Tabrisrp** [comment]
This will be automatically done with the exclusion of scripts from `wp_localize_script()` in 3.1.3.

You can recognize them because they are wrapped by `CDATA` and it starts with `var variable_name = {}`
