### ISSUE TITLE
Enable preload for cookie-specific cache files

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1167]
When using a plugin with which  WP Rocket provides dynamic cookie-based compatibility, (Cookie Notice etc) customers want to be able to preload all versions of the cache, for maximum performance.

Currently we can only preload the default cache file _or_ the [specific cookie version](http://snippi.com/s/8ya67zd), but not both.

Ideally we could preload both, either by filter, or by UI option. 
e.g. We could detect active plugins with WPR cookie compatibility and offer a checkbox to enable cookie-specific preloading

We could consider making it default behaviour only if:
- it can also be disabled
- it won't cause CPU or other server issues
- it won't cause further problems for [very large sitemaps](https://github.com/wp-media/wp-rocket/issues/973)

**Comment by arunbasillal** [comment]
Set cookies for compatibility with Cookie Notice plugin during WP Rocket preload - http://snippi.com/raw/4zt6mje

Set cookies for compatibility with WeePie Cookie Allow during WP Rocket preload - http://snippi.com/raw/4ps4q89

**Comment by alfonso100** [comment]
A customer is asking for this feature too: 
https://secure.helpscout.net/conversation/948999713/121930?folderId=273761

**Comment by mastmaster** [comment]
Hello,

That's exactly what I want.

So, I can add this code on my functions.php and enable filters after defaut preloader ends so i can warm my 2nd version of caches?

Is there any hook to disable purging when preloader runs for 2nd time? So, it can cache only pages that don't exist on the cache folder.

**Comment by mastmaster** [comment]
Any news for this feature?

**Comment by arunbasillal** [comment]
@mastmaster This is just a suggestion at the moment and isn't being worked on, or planned for any future version. In fact, we are working on revamping our current preload module and we will have to see how that works out before we add new features. Preload is one area that causes a lot of support issues.

**Comment by NataliaDrause** [comment]
Related request: https://secure.helpscout.net/conversation/1568992555/278868/

**Comment by camilamadronero-zz** [comment]
Request https://secure.helpscout.net/conversation/1612639108/290193?folderId=2675957

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1985693825/363231?folderId=3864735
@piotrbak will the new preload support preload multiple values of the same cookie? https://docs.wp-rocket.me/article/1676-preload-custom-cookie

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1993136632/364868/

**Comment by piotrbak** [comment]
Closing as it was fixed by introducing this advanced helper:
https://github.com/wp-media/wp-rocket-helpers/tree/master/preload/wp-rocket-preload-dynamic-cookies
