### ISSUE TITLE
Regenerate critical path CSS post types individually 

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1173]
**Is your feature request related to a problem? Please describe.**
A possible solution to issue outlined here:

https://github.com/wp-media/criticalpath-css-generator/issues/103

**Describe the solution you'd like**
The ability to regenerate critical CSS post types individually, especially if there is a failure in the generation of some but not others.

**Comment by arunbasillal** [comment]
Thinking out loud. 

For some of these errors, the solution (at least for now) is to try again later. Maybe we could use a cron job and queue these failed attempts and try again later. The number of retry attempts should be limited, if not it would end up with an infinite loop if the generation fails every single time.

**Comment by webtrainingwheels** [comment]
I have a use-case for this as well: https://secure.helpscout.net/conversation/708886218/86433?folderId=377611
We're providing a non-specific error on the particular URL we're accessing : "An error prevents the generator from retrieving its contents"
But other URLs in the same content type are accessible to the tool. So would be nice to specify a different URL to use for this content type.

**Comment by arunbasillal** [comment]
@webtrainingwheels I believe we have improved our CPCSS error messages right? And ever since the server update, we see very few errors related to failures, right? 

Shall we close this one?

**Comment by webtrainingwheels** [comment]
Yes, I think we can close this one.
