### ISSUE TITLE
Query strings not removed on multisites using WordPress MU Domain Mapping

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1174]
**Describe the bug**

On a multisite that uses "WordPress MU Domain Mapping", the CSS/JS URL's of a sub-site are treated as external domain.

Turns out the $hosts array in here never has the mapped domain (but only the root domain): https://github.com/wp-media/wp-rocket/blob/430a0691df2c27947f8cb4ba4b4db4c9ab58f319/inc/classes/optimization/class-abstract-optimization.php#L40-L54

**Additional context**

Related ticket: https://secure.helpscout.net/conversation/643973656/77288?folderId=1724284
Slack conversation: https://wp-media.slack.com/archives/C43T1AYMQ/p1535462982000100

**Comment by arunbasillal** [comment]
Another related issue. Minification and combination also failed for the same reason. 

Basically `rocket_url_to_path` returned false because the path determined was incorrect. [`$root_url`](https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/functions/formatting.php#L317) was determined as the sub-domain instead of the mapped domain.

Details are added as a note here to protect identity of the customer - https://secure.helpscout.net/conversation/714216697/87395/#thread-2014460212

**Comment by hao1362002** [comment]
Hello,

I uses "Domain Mapping" from wpultimo.com not WPMU Dev btw.

Please feedback to me soon! when finished.

**Comment by hao1362002** [comment]
Hello,

Are you there?

Do you fix finished?

Best regards,
Hao1362002@gmail.com

**Comment by hao1362002** [comment]
Hello,

Do you fix finished?

**Comment by arunbasillal** [comment]
@hao1362002 As mentioned in my reply on the ticket, this is not going to take a while. 

When its being worked on you will see updates on this issue here. Until then, sadly there is no solution. Please be patient.

**Comment by hao1362002** [comment]
Ok, I will wait you fix it

**Comment by hao1362002** [comment]
Hello,
I have not seen you update and fix this!
When do you fix finished?

**Comment by hao1362002** [comment]
@arunbasillal 

Please update?

**Comment by hao1362002** [comment]
Hello, @arunbasillal 

When do you fix finished?

Please update

**Comment by hao1362002** [comment]
Hello, @arunbasillal 

When do you fix finished?

Please update

**Comment by hao1362002** [comment]
@Tabrisrp

**Comment by hao1362002** [comment]
Hello, @arunbasillal 
@Tabrisrp 
@girlie 
@nicomollet 

When do you fix finished?

Please update

**Comment by GeekPress** [comment]
I'm closing this issue as this option will be removed in 3.6
