### ISSUE TITLE
Some tagDiv block images are not Lazyloaded in Newspaper theme

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1177]
Images in some blocks of Newspaper theme are not being lazyloaded. The blocks are not present when we try to replace images with placeholders in [here](https://github.com/wp-media/wp-rocket/blob/43e38fa045420ca94cc8ecbc02694ccaabe2de18/inc/front/lazyload.php#L145). 

The same blocks are LazyLoad on the homepage though. It seems to be handled differently by the theme. 

- Reproduced in http://mega.wp-rocket.me/newspaper/
- Related ticket: https://secure.helpscout.net/conversation/652491257/78424?folderId=1724284
- Here is a screenshare (excuse the audio quality) - https://youtu.be/Qru8TzPnPk0
- Chat with Remy - https://wp-media.slack.com/archives/C43T1AYMQ/p1536227902000100

**Comment by piotrbak** [comment]
Looks like everything works correctly with 8.1.2 version of Newspaper theme
