### ISSUE TITLE
PHP notice when saving a term with Polylang active

### ISSUE THREAD

**Issue by Chouby** [wp-media/wp-rocket#1180]
Using Polylang 2.3.10 + WP Rocket 3.1.2, saving a term fires a PHP notice. For example here for a menu:
```
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/polylang-pro/include/links.php on line 34
PHP Stack trace:
PHP   1. {main}() /wp-admin/nav-menus.php:0
PHP   2. wp_nav_menu_update_menu_items() /wp-admin/nav-menus.php:368
PHP   3. do_action() /wp-admin/includes/nav-menu.php:1083
PHP   4. WP_Hook->do_action() /wp-includes/plugin.php:453
PHP   5. WP_Hook->apply_filters() /wp-includes/class-wp-hook.php:310
PHP   6. call_user_func_array() /wp-includes/class-wp-hook.php:286
PHP   7. rocket_clean_domain() /wp-includes/class-wp-hook.php:286
PHP   8. get_rocket_i18n_home_url() /wp-content/plugins/wp-rocket/inc/functions/files.php:659
PHP   9. pll_home_url() /wp-content/plugins/wp-rocket/inc/functions/i18n.php:361
PHP  10. PLL_Links->get_home_url() /wp-content/plugins/polylang-pro/include/api.php:98
```

**To Reproduce**
*Activate Polylang and WP Rocket
*Go to Appearance > Menus
*Create a menu
*Save the menu
*Check your debug.log

When saving a term, WP fires the action [edited_terms](https://github.com/WordPress/WordPress/blob/4.9.8/wp-includes/taxonomy.php#L2785-L2793) with the term_id as first parameter.
`rocket_clean_domain` is [hooked](https://github.com/wp-media/wp-rocket/blob/v3.1.2/inc/common/purge.php#L15) to `edited_terms` and receives this term_id and [passes it to get_rocket_i18n_home_url](https://github.com/wp-media/wp-rocket/blob/v3.1.2/inc/functions/files.php#L659) which expects a language code instead. [This function passes this term_id to Polylang pll_home_url()](https://github.com/wp-media/wp-rocket/blob/v3.1.2/inc/functions/i18n.php#L361) which also expects a valid language code. An internal method of Polylang doesn't recognize the term_id as valid language code which ends up firing the notice.

**Comment by Tabrisrp** [comment]
Yes we need to change the callback function for these hooks as it can create this can of issues.

**Comment by arunbasillal** [comment]
Since `edited_terms` pass an `int` we could probably check for it's type in `rocket_clean_domain` before passing it onto `get_rocket_i18n_home_url`

`pll_home_url` expects `string`. 

Will that solve the issue?

**Comment by Tabrisrp** [comment]
It works as a temporary fix to prevent the notice
