### ISSUE TITLE
Video / Iframe Lazy Load Does Nothing For Non-YouTube Elements

### ISSUE THREAD

**Issue by Volnus** [wp-media/wp-rocket#1184]
So I have realized something, when using Vimeo and enabling the video lazy load option you don't actually receive any performance improvements. 

So here is an example below is the original unmodified by WPRocket Code. 
`<iframe src="https://player.vimeo.com/video/286740784" width="640" height="483" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

Now you can grab any video you want I just grabbed that one because it was the first one under staff picks. 

So now below is what WPRocket shows on my actual live site. 
`<iframe src="https://player.vimeo.com/video/286740784" width="640" height="483" frameborder="0" allowfullscreen="allowfullscreen" data-rocket-lazyload="fitvidscompatible" data-lazy-src="https://player.vimeo.com/video/286740784"></iframe><noscript><iframe src="https://player.vimeo.com/video/286740784" width="640" height="483" frameborder="0" allowfullscreen="allowfullscreen"></iframe></noscript>`

The error is in the first line the iframe src is unmodified. Because the IFrame source isn't modified it's still loading the player onload regardless of how long the page is, where the video is, etc it's loading it as is so you're essentially not gaining any performance benefit from lazy loading videos. I propose we either load the default base64 encoded 1x1gif or we add a preview image (or possibly both). But, as is there is no performance benefit when using video lazy loading / iframe lazy loading with Vimeo. I am going to tinker and see if it's something I can resolve relatively easily.

**Comment by Volnus** [comment]
Also I created a live page if someone wanted to see it live
https://www.sertmedia.com/example-vimeo-video/

**Comment by Volnus** [comment]
Another note, the filter rocket_lazyload_iframe_html does not exist and yet we have an apply filters being added for it. 

/**
		 * Filter the LazyLoad HTML output on iframes
		 *
		 * @since 2.11
		 *
		 * @param array $html Output that will be printed.
		 */
		$iframe_lazyload  = apply_filters( 'rocket_lazyload_iframe_html', $iframe_lazyload );
		$iframe_lazyload .= $iframe_noscript;

		$html = str_replace( $iframe[0], $iframe_lazyload, $html );
	}


there is no filter this is like why the code is not actually being lazy loaded it would seem that the code to do the manipulation simply does not exist.

**Comment by Tabrisrp** [comment]
I see on your test page there is this element inside the iframe, which might be breaking the regex values expected `<span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">﻿</span>`.

The resulting HTML transformation gives this `<iframe src="https://player.vimeo.com/video/286740784" width="640" height="483" frameborder="0" allowfullscreen="allowfullscreen"><span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">﻿</span data-rocket-lazyload="fitvidscompatible" data-lazy-src="https://player.vimeo.com/video/286740784">`

The data attributes are applied to the closing `span` instead of the iframe element

**Comment by Volnus** [comment]
I replaced the code and it's still not doing it. Nor is it doing to the google map below. The src element should be replaced but its not.

**Comment by Volnus** [comment]
I am going to provide an update this appears to be a very common trend with many of my client sites as well I tested using the A3 Lazy Load plugin and it handles the iframe like I expect. So I run A3 only for the iframes not the images and let rocket handle the images. Something is off about the regex.

**Comment by Tabrisrp** [comment]
Yes there is a bug in the code indeed, it's not in the regex but later on. We'll fix that in the next version, thank you for reporting it!

**Comment by webtrainingwheels** [comment]
related? https://github.com/wp-media/wp-rocket/issues/770

**Comment by Slapbox** [comment]
What about non-iframe videos? It doesn't seem to do anything?
