### ISSUE TITLE
Jquery Safe Mode - exclude common externally hosted jquery

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1196]
Safe mode for Deferred JS doesn't work if the site is using an externally hosted version of jquery instead of the default WordPress file. 

Could we also automatically exclude the most common versions of externally hosted jquery so that we don't have to use a helper plugin? 

e.g. https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js?ver=1.12.4

**Comment by webtrainingwheels** [comment]
Adding Jetpack's Site Accelerator to the list that it would be cool to automatically make safe mode compatible with.
Currently it looks like they use: https://c0.wp.com/
https://github.com/Automattic/jetpack/blob/49dda1a6e4f0f55ed93f81bd9e7d558e551bf0ae/modules/photon-cdn.php

**Comment by markonikolic985** [comment]
Path of this file is different per WP version so it looks like this:

```.
.
https://c0.wp.com/c/5.0.2/wp-includes/js/jquery/jquery.js
https://c0.wp.com/c/5.0.3/wp-includes/js/jquery/jquery.js
.
.```

So if you use WP Rocket addon [by following this guide](https://docs.wp-rocket.me/article/976-exclude-files-from-defer-js), you will have to update the code after every WP update.

You can use the attached addon to exclude these dynamically, so there is no need to update it.
[wp-rocket-exclude-defer-js-jetpack.zip](https://github.com/wp-media/wp-rocket/files/2760030/wp-rocket-exclude-defer-js-jetpack.zip)

**Comment by arunbasillal** [comment]
One more ticket with the same issue - https://secure.helpscout.net/conversation/764626133/94437/

**Comment by ernee** [comment]
Another ticket (helper above resolved): https://secure.helpscout.net/conversation/836623631/105564?folderId=1391600
