### ISSUE TITLE
PHP Fatal Error: Composer Autoloader Cannot declare class

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1199]
Over the last few days we have been seeing a PHP fatal error when WP Rocket is activated on some hosts. 

`
Fatal error: Cannot declare class ComposerAutoloaderInit92972d118ced8ff642fe76cb6658cf52, because the name is already in use in /wp-content/plugins/wp-rocket/vendor/composer/autoload_real.php on line 5
`

- https://wp-media.slack.com/archives/C43T1AYMQ/p1537456207000100
- We have seen this on multiple hosts, so it doesn't look like a host related problem.
- When I manually rename `ComposerAutoloaderInit92972d118ced8ff642fe76cb6658cf52` to something else, the error is gone. Which is strange because it suggests that someo other theme or plugin that is using composer has the same class name. (Very unlucky if that is the case)

Helpscout tags: `autoloader error` and `php fatal error`

**Comment by Tabrisrp** [comment]
This is caused by the inclusion of composer autoloader in `advanced-cache.php`, which is loaded everywhere, and happens when moving the directory, for example during a staging copy.

In `advanced-cache.php` the file path referenced for the autoloader is still the old path, but the one in `main.php` is referencing the new path, so the autoloader is loaded twice from 2 different paths.

To resolve that, instead of using the composer autoloader, we can use a custom autoloader for monolog files only, since it's the only thing we need at that point.

**Comment by arunbasillal** [comment]
@Tabrisrp 👏 

Why now though? Did something change in the recent update in what we add to the `advanced-cache.php`?

**Comment by stevethebartender** [comment]
@Tabrisrp I just moved from a staging copy and get this error. Are you able how I can fix it so that I can enable WP Rocket again?

**Comment by vmanthos** [comment]
@stevethebartender Remove the following line (line 12) from the advanced-cache.php file:
`include 'path/wp-content/plugins/wp-rocket/vendor/autoload.php';`

This should work for you.

**Comment by stevethebartender** [comment]
Unfortunately not @vmanthos - there is no reference to this autoload.php

See here: http://prntscr.com/l5k31p

Any other ideas to fix?

**Comment by Tabrisrp** [comment]
Please look in `wp-content/advanced-cache.php` instead, this is the file mentioned by Vasilis

**Comment by stevethebartender** [comment]
Thanks for the quick responses! All fixed :)

**Comment by chill986** [comment]
include 'path/wp-content/plugins/wp-rocket/vendor/autoload.php'; 

is not referenced in my advanced-cache.php file on line 5, however this is:

require_once __DIR__ . '/composer/autoload_real.php';

Should I delete that line?

I am unable to enable wp-rocket, because I'm getting the same error:

Fatal error: Cannot declare class ComposerAutoloaderInit92972d118ced8ff642fe76cb6658cf52, because the name is already in use in /home/sitename/public_html/dev/wp-content/plugins/wp-rocket/vendor/composer/autoload_real.php on line 5

**Comment by sangemaru** [comment]
We're seeing a PHP Fatal Error that may be related to the issue @Tabrisrp described:
> This is caused by the inclusion of composer autoloader in `advanced-cache.php`, which is loaded everywhere, and happens when moving the directory, for example during a staging copy.
> 
> In `advanced-cache.php` the file path referenced for the autoloader is still the old path, but the one in `main.php` is referencing the new path, so the autoloader is loaded twice from 2 different paths.
> 
> To resolve that, instead of using the composer autoloader, we can use a custom autoloader for monolog files only, since it's the only thing we need at that point.

```PHP message: PHP Fatal error:  Cannot redeclare get_rocket_cdn_cnames() (previously declared in /srv/www/tstprep.com/releases/20191130191049/web/app/plugins/wp-rocket/inc/functions/api.php:39) in /srv/www/tstprep.com/releases/20191130191049/web/app/plugins/wp-rocket/inc/functions/api.php on line 39" while reading response header from upstream, client: 162.158.18.175, server: staging.tstprep.com, request: "POST /wp/wp-admin/admin-ajax.php?_fs_blog_admin=true HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "staging.tstprep.com", referrer: "https://staging.tstprep.com/wp/wp-admin/options-general.php?page=wprocket"
2019/11/30 19:13:10 [error] 18781#18781: *5107 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare get_rocket_cdn_cnames() (previously declared in /srv/www/tstprep.com/releases/20191130191049/web/app/plugins/wp-rocket/inc/functions/api.php:39) in /srv/www/tstprep.com/releases/20191130191049/web/app/plugins/wp-rocket/inc/functions/api.php on line 39" while reading response header from upstream, client: 162.158.18.175, server: staging.tstprep.com, request: "GET /wp/wp-admin/options-general.php?page=wprocket HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "staging.tstprep.com"
2019/11/30 19:23:17 [error] 18781#18781: *5112 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare get_rocket_cdn_cnames() (previously declared in /srv/www/tstprep.com/releases/20191130191049/web/app/plugins/wp-rocket/inc/functions/api.php:39) in /srv/www/tstprep.com/releases/20191130191049/web/app/plugins/wp-rocket/inc/functions/api.php on line 39" while reading response header from upstream, client: 162.158.18.145, server: staging.tstprep.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "staging.tstprep.com"
```

Unfortunately, that release path is the latest path, not an older deploy.
