### ISSUE TITLE
Update UI text re: excluding from Combine JS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1202]
Current text: _3rd Party: Use URL full path, including domain name, to exclude external JS. More info_

Suggested change: _3rd Party: Use either the full URL path or only the domain name, to exclude external JS. More info_
(I'm working on updating the doc currently).

@ernee Please could you provide your insight/suggestions on the wording ^  :)

**Comment by ernee** [comment]
Looks good to me @webtrainingwheels !
