### ISSUE TITLE
Block plugin updates for sites appearing (but not authorized) on my account dashboard

### ISSUE THREAD

**Issue by slomeli79** [wp-media/wp-rocket#1206]
When a thief, or ex-client, or anyone else who may have copies of the WP Rocket plugin zip (with my email address in the license files) activates the plugin, they are receiving plugin updates despite my repeated removal of their site from my account's list of authorized sites.

Why can a site simply de-activate and then re-activate their plugin, and continue getting free updates using the license I'm paying for?

**Comment by maximejobin** [comment]
That is a good question and a feature I'd like to have. We've dealt with similar situations. 😞

**Comment by GeekPress** [comment]
We are actually working on our new website design and we plan to add a « ban » feature. When a website will be banned, it won't receive updates anymore.

For your information, since 3.5, the license-data.php file is deleted after the first activation. It dramatically reduces the chance for someone else to get the plugin folder to install it on another website.

**Comment by maximejobin** [comment]
Unfortunately, it looks like we have people that backed up the file. I keep "removing" the site and it comes back.

**Comment by maximejobin** [comment]
> For your information, since 3.5, the license-data.php file is deleted after the first activation. It dramatically reduces the chance for someone else to get the plugin folder to install it on another website.

Do you confirm this? At the rate 2 site owners add their websites back in my account, I have doubts about this statement.

**Comment by Tabrisrp** [comment]
Hi Maxime 👋 ,

Yes confirmed, as long as the version is 3.5 or above, the file should be deleted either on installation or update.

It's even causing our dev team some issues, as you an see here #2572

**Comment by serg-pervushin** [comment]
It would be great if could block domains in the user's personal account. I'm looking forward to this feature.

The license file is indeed deleted when the plugin is activated, this is true, but sometimes you need to block the domains on which I installed the plugin myself, for example, when cooperation with the client ends and it should no longer receive updates, and there is no access to the site, so I can manually delete the plugin.
