### ISSUE TITLE
LazyLoad placeholder improvement

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#1209]
From the customer.

> Your plugin should take the aspect ratio into consideration when using placeholders for lazy load to avoid unnecessary redraw lag.

The related ticket is [here](https://secure.helpscout.net/conversation/668671611/0/?folderId=273761).

**Comment by xpd** [comment]
When imagemagick is installed this can be used for creating a placeholder `convert -size 4x5 xc:transparent gif:- | base64`

**Comment by dev4press** [comment]
Most images on my websites are rectangle shaped, so I generated 3x2 transparent GIF and used the filter in WP Rocket to replace default 1x1 pixel.

Settings regarding the use of white or transparent GIF would be great, and maybe the inclusion of several different GIF sizes to try and match the size of the image that is replaced.

**Comment by GeekPress** [comment]
@Tabrisrp Does fix issue is now fixed since we are applying the width / height on the SVG placeholder?

**Comment by Tabrisrp** [comment]
For images that have the width and height attributes yes

**Comment by GeekPress** [comment]
Can we consider this issue fixed? 😅

**Comment by Tabrisrp** [comment]
Yes we can't do more than that
