### ISSUE TITLE
Logger class not detected in process.php - Page Cache doesn't work

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1215]
**Describe the bug**
The cache isn't generated and served because in process.php the Logger class isn't detected.

**To Reproduce**
As to test on a specific customer website. Ask me the credentials.

**Screenshots**
https://cl.ly/0805c0f197c3

The echo isn't printed.

**Comment by Tabrisrp** [comment]
Logger class loading is updated in 3.2, so we will need to test with the new process

**Comment by Screenfeed** [comment]
It works.
