### ISSUE TITLE
An Astra Inline JS is deleted instead of being added into the concatenated JS file.

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1216]
**Describe the bug**
An inline JS from Astra is totally removed and causes a JS error (astra not defined).

Instead of being into the concatenated JS file, for an unknown reason the Inline JS is deleted.

`<script type='text/javascript'>/* <![CDATA[ */ ( typeof window.CustomEvent === "function" ) || document.write( '<script src="https://xxxxxx.com/wp-content/themes/astra/assets/js/minified/custom-events-polyfill.min.js"></scr' + 'ipt>' );
var astra = {"break_point":"921","isRtl":""}; /* ]]> */</script>` 

**To Reproduce**
Activate Combine JS option and put the same inline JS in your theme.

**Expected behavior**
The inline JS should be excluded. The pattern document.write match with our auto-exclusion.

**Comment by Tabrisrp** [comment]
I added this inline JS in my test site, it was not deleted, and correctly excluded from combine JS
