### ISSUE TITLE
Even when the mobile cache options are Off, a mobile cache file is generated.

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1217]
- WP Rocket 3.1.4

Even if the Mobile Cache options are Off, a mobile cache file is generated like the 2 options would be ON. The separate mobile cache file is also generated even if the **Separate cache files for mobile devices** option has not been enabled.

**To Reproduce**
1. Go to Cache tab and disable the 2 Mobile Cache options
2. Click on Save settings (cache is automatically purged)
3. Visit your website on mobile
4. A mobile cache files is generated (index-mobile.html & its gziped version) 

**Expected behavior**
Only index.html should be available

**Screenshots**
![capture d ecran 2018-10-02 a 14 13 56](https://user-images.githubusercontent.com/11939512/46348135-3e505180-c64e-11e8-87db-4bca3016f5c1.png)

**Comment by Tabrisrp** [comment]
This doesn't happen on 3.2, so let's consider it fixed 😅
