### ISSUE TITLE
Unable to install via composer.json as dependency version is wrong ("a5hleyrich/wp-background-processing": "1.1 as 1.0")

### ISSUE THREAD

**Issue by tulbox** [wp-media/wp-rocket#1226]
**Describe the bug**
wp-media/wp-rocket 3.1.4 requires a5hleyrich/wp-background-processing 1.1 as 1.0 -> no matching package found.

Latest version of dependency https://github.com/A5hleyRich/wp-background-processing is 1.0.1.

**To Reproduce**
1. composer require wp-media/wp-rocket
2. "Your requirements could not be resolved to an installable set of packages"

**Comment by Tabrisrp** [comment]
You can see the reason and the solution for this on #741

Note that in 3.2, this should not happen anymore.

**Comment by tulbox** [comment]
Thanks! I swear I searched first!

**Comment by smilingpeanut** [comment]
@Tabrisrp It still happens when trying to require 3.2.0.1.

**Comment by tulbox** [comment]
Still happens as of 3.2.2.

**Comment by dpurnam** [comment]
Same problem on multiple servers with latest release of 3.2.3, unable to compose require and hence install the package. Is there a possibility of sharing a .zip of the plugin on GitHub so we can automate/bypass plugin installation/update on multiple servers?
