### ISSUE TITLE
Beaver builder parallax CDN compatibility

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#1227]
**Describe the bug**
CDN function does not modify beaver builder parallax image url

**Expected behavior**
 parallax HTML would use a CDN URL

**Screenshots**

**Code sample to fix**
```
if ( function_exists( 'get_rocket_cdn_url' ) ) {
	add_filter( 'fl_builder_row_attributes', function ( $attrs ) {
		if ( isset( $attrs['data-parallax-image'] ) ) {
			$attrs['data-parallax-image'] = get_rocket_cdn_url( $attrs['data-parallax-image'] );
		}

		return $attrs;
	} );
}
```

**Comment by webtrainingwheels** [comment]
Example ticket: https://secure.helpscout.net/conversation/680682540/82339?folderId=377611
