### ISSUE TITLE
Auto-exclude acf.post_id Inline JS & input.min.js file from Combine JS option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1229]
When the combine JS option is turned on, it causes an issue with a specific field of ACF plugin.

To fix the issue, we need to exclude:
acf.post_id
/wp-content/plugins/advanced-custom-fields-4.4.12.1/js/input.min.js

It will fix the issue with the combine JS option but not with the deferred JS option.

**Comment by piotrbak** [comment]
Closing it as we don't have any feedback from our customers related to this problem. It's been 4 years without any ticket.
