### ISSUE TITLE
3.2-alpha: Activate Preload & Sitemap Preload not enabled after update when Yoast XML sitemap is enabled previously

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1238]
When updating from 3.1.4 to 3.2-alpha2,  "Activate Preload" and "Activate sitemap-based cache preloading" are not enabled when the Yoast SEO XML sitemap preloading has been configured for preloading in the previous version. The XML sitemap option is checked, but preloading subsequently is disabled without "Activate Preload" and "Activate sitemap-based cache preloading" enabled (this option is checked when Activate Preload is enabled but inactive until saved).

![screen shot 2018-10-12 at 10 51 23 pm](https://user-images.githubusercontent.com/8108643/46901976-e39acf00-ce71-11e8-8d7b-da9edb7b9153.png)

Also, Yoast XML sitemap should be hidden/inactive when "Activate Preload" is unchecked.

**Comment by arunbasillal** [comment]
Tested with alpha3, issue persists: https://jmp.sh/yD1AGQ5

**Comment by arunbasillal** [comment]
Tested with alpha5, issue persists: https://jmp.sh/IOOt1OP
Continued here: https://jmp.sh/rdPP2MS

**Comment by Tabrisrp** [comment]
The UI was not planned to handle multiple levels for sub-fields. I can't fix that currently, it needs more advanced work on the HTML/CSS/JS part of the UI to support that.
