### ISSUE TITLE
3.2-alpha: Screenshot on Image Optimization is too much optimized + make it distant.

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1240]
The screenshot in the Image Optimization tab is too much optimized. We can notice the degradation of the image without needed to zoom.

Also, to avoid deploying a new WP Rocket version because of we would like to update the Imagify screenshot for any reasons, this image must be saved in the WP Rocket website.

For example, if we want to promote a special offer, we will be able to do it by just updating the image from our website, and not from a new WP Rocket version.

**Comment by GeekPress** [comment]
The image seems to be still over optimized. I cleared my browser cache a couple of time.

Also, to avoid browser caching issue, a random query string on the image will be helpful.

**Comment by Tabrisrp** [comment]
I saved it at 100% quality in Photoshop from the PSD, I can't do better than that 😕

I'll add the query string though.
