### ISSUE TITLE
Avada favicon CDN compatibility

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#1245]
Add CDN compatibility with avada favicon and device icons.

use hooks `avada_setting_get_favicon[url]` `avada_setting_get_iphone_icon[url]` `avada_setting_get_iphone_icon_retina[url]` `avada_setting_get_ipad_icon[url]` `avada_setting_get_ipad_icon_retina[url]`  to filter with `rocket_cdn_file`

**Comment by pcfreak30** [comment]
Also apply a filter `add_filter( 'option_' . \Avada_Settings::get_option_name(), 'some_function' );` on `after_setup_theme` and filter `$settings['logo']['url']` element though get_rocket_cdn_url.

**Comment by Tabrisrp** [comment]
the PR #1225 should cover this and all other favicons and touch icons by using the `rocket_buffer` filter directly. Coming in 3.2 soon.

**Comment by Tabrisrp** [comment]
This should be handled automatically now with the changes made on CDN in the last couple major versions of the plugin.
