### ISSUE TITLE
3.2-alpha2: Disabling "Activate Preloading" does not disable sitemap preload completely

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1249]
Disabling "Activate Preloading" does not minimize the UI completely

See it here: https://jmp.sh/BklmyHm

- "Activate Preloading" in unchecked. 
- "Yoast SEO XML sitemap" is still visible
- The "Preload cache" button in the admin bar is still visible
- Clicking the "Preload cache" button from the admin bar launches the preload. 
- "Start cache preloading" in the quick actions is still visible. 
- "Start cache preloading" in quick actions launches the preload.

**Comment by Tabrisrp** [comment]
Already reported in #1238 and fixed for the next alpha
