### ISSUE TITLE
3.2-alpha2: Preload homepage on WP Rocket activation for new users

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1251]
This is a topic that was discussed here but never reached a conclusion - https://hub.wp-media.me/wp-rocket/plugin/wp-rocket-3-2-field-guide/#comment-1822

For new installs since 3.2:
- "Activate prelading" is enabled by default
- When any option is saved, the entire cache is deleted and homepage is preloaded

But during initial activation, nothing is preloaded. So if the user simply activates WP Rocket and does a test, the website is still slow. 

Why not simply preload the homepage during initial activation. This will cover all cases.

**Comment by arunbasillal** [comment]
@Tabrisrp Homepage and the URLs found from the homepage are preloaded. Is this the expected result?

**Comment by Tabrisrp** [comment]
No, only the homepage

**Comment by arunbasillal** [comment]
@webtrainingwheels / @Tabrisrp 

Right now, the homepage and the urls found from the homepage are preloaded on plugin activation (alpha6)

Should we do something about it? or just leave it as such?

**Comment by arunbasillal** [comment]
Lol, master of preload. If things go wrong, I am looking at a lot of heat now. 

My only concern is efficiency / waste of effort. 

A good share of people would want to at least change one WP Rocket setting I hope. At which point we would delete everything and start over. 

But this is in alignment with #1248 and I am fan of consistency. Consistency is also easier for the support team to remember as well. If preload is enabled, we preload everything, during activation and when we change setting. 

And consistency is greater than minor waste of resources in my book (which is not based on data anyways). 

So I would say, lets keep it the way it is.
