### ISSUE TITLE
Design suggestion - Automatically detected sitemaps to be listed under "Sitemaps for preloading"

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1252]
Right now, the sitemaps that we automatically detect are listed as a separate section. I think it would make better sense to list then under "Sitemaps for preloading"

This is how we do it now: 

<img width="398" alt="01" src="https://user-images.githubusercontent.com/5751474/47100102-0c86df80-d237-11e8-8655-977c3746b0df.PNG">

**Suggested** 

(Activate sitemap-based cache preloading option is missing, but you get the idea)

<img width="367" alt="02" src="https://user-images.githubusercontent.com/5751474/47100160-29bbae00-d237-11e8-9468-9bc24e036f5b.PNG">

**Comment by Tabrisrp** [comment]
We can't do that with the current frontend code

**Comment by kevin25** [comment]
Yes, this feature should be available. We need to choose which sitemap will be preloaded first.

**Comment by arunbasillal** [comment]
This won't be relevant with the new updates that we have in mind for the preload module.
