### ISSUE TITLE
3.2-alpha3: Sucuri cache is not purged

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1256]
- Verified with the headers that Sucuri is caching the site
- Updated content on the site. 
- Verified that the WP Rocket cache was cleared
- but the site did not update with the new content. 
- Timestamp on the cache file (displayed in browser) was the old one, Last-modified was not updated.
- I also tested clearing the entire cache using admin toolbar link but that did not work either. 
- The new content was only displayed when I used the clear cache function from the Sucuri account itself. 
- nothing in debug log
- tested with the same result on 2 different sites.

**Comment by webtrainingwheels** [comment]
Forgot to add - access info in [wrike card ](https://www.wrike.com/open.htm?id=276348413)if needed

**Comment by webtrainingwheels** [comment]
This works now 👍

**Comment by Screenfeed** [comment]
![on56qsr](https://user-images.githubusercontent.com/1878479/47324312-8c5de100-d65f-11e8-9b58-cde18d55051d.gif)
