### ISSUE TITLE
Cloudways - Varnish cache is not cleared when the Varnish add-on is enabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1257]
**Describe the bug**
On Cloudways, Varnish cache is not purged when WP Rocket's cache is cleared (Varnish add-on is enabled). 

This leads to 404 on minified files.

**Steps to reproduce the issue**
1. Use a Cloudways-hosted website where Varnish is enabled.  We don't have one currently, so we should create it from scratch.
2. Enable the Varnish add-on.
3. Make a change to a post.
4. Clear WP Rocket's cache.
5. Check, in an incognito browser window, for the updated post.

**Related Ticket**
https://secure.helpscout.net/conversation/686147105/83005/?folderId=2135277

**Comment by arunbasillal** [comment]
Possibly related ticket: https://secure.helpscout.net/conversation/718924487/88376/

**Comment by webtrainingwheels** [comment]
This needs further testing to validate.  

I just had a similar case and it was solved by using this helper:
https://docs.wp-rocket.me/article/891-purge-varnish-when-using-a-proxy

on this site: https://bitcoin-casino-no-deposit-bonus.com
Cloudways + Varnish + Cloudflare.
Varnish `Age` header was reset to 0 after WP Rocket cache purge.

**Comment by arunbasillal** [comment]
@webtrainingwheels What is the IP you used in the proxy? I tried with `127.0.0.1` and ports `8080 and 6082`. No luck.

**Comment by webtrainingwheels** [comment]
Did not have to change the IP - left it as `localhost`
Only set the domain here: https://github.com/wp-media/wp-rocket-helpers/blob/master/compatibility/wp-rocket-compat-varnish-ip-proxy/wp-rocket-compat-varnish-ip-proxy.php#L22

**Comment by piotrbak** [comment]
Cloudways provides an API to clear Varnish. That's probably the most reliable way to handle it:
https://www.cloudways.com/blog/automatically-purging-varnish-cache-using-cloudways-api/

**Comment by piotrbak** [comment]
> @webtrainingwheels What is the IP you used in the proxy? I tried with `127.0.0.1` and ports `8080 and 6082`. No luck.

Setting custom Varnish IP to `127.0.0.1:8080` resolved the problem for me.

**Comment by Netzlichter** [comment]
I had no success to use WP Rocket with CLoudways and varnish. I tried the helper plugin and filled in: 
127.0.0.1:8080 fpr varnish ip. But the varnish cache isn't cleared when I clear the wp rocket cache... so I cannot use WP Rocket along with cloudways and varnish?

**Comment by alfonso100** [comment]
Another case here:
https://secure.helpscout.net/conversation/1037049553/137432?folderId=2683093

In this case, using the following helper solved the issue:
https://github.com/wp-media/wp-rocket-helpers/blob/master/compatibility/wp-rocket-compat-varnish-ip-proxy/wp-rocket-compat-varnish-ip-proxy.php

I had to set​ a custom varnish host: **subdomain.domain.com**, 
​And also a custom varnish IP and port: **127.0.0.1:8080**

I've noticed a difference between WP Rocket Varnish function and Breeze's Varnish function, specifically in the parameters we use at the **wp_remote_request()**. So I left a note with some additional comments on the ticket. Just in case it helps.

**Comment by Tabrisrp** [comment]
Could we get a direct line with Cloudways about this?

Looking at the history, different solutions seem to have worked at different times, so it's hard for the dev team to determine the one solution to go with.

Looking at the Breeze plugin, when they perform the Varnish cache purge, the default value for the host is `127.0.0.1`. So some clarifications would be really helpful for us.

**Comment by GeekPress** [comment]
@Tabrisrp Contact in progress => https://twitter.com/wp_rocket/status/1247786849763856386

**Comment by GeekPress** [comment]
@Tabrisrp Cloudways replied to the tweet with an email to contact. Could you please contact them?

**Comment by Tabrisrp** [comment]
Message sent

**Comment by Tabrisrp** [comment]
Received everything we need to work on this

**Scope a solution** ✅ 
- Create a compatibility class: `WP_Rocket\ThirdParty\Hostings\Cloudways`
- We can use the `$_SERVER['cw_allowed_ip']` variable to identify that we are on Cloudways
- Auto-enable Varnish + display custom message on Varnish add-on, like we do for Flywheel for example
- Cloudways Varnish uses `http://127.0.0.1:8080` for its URL, filter `rocket_varnish_ip`

**Effort** ✅ 
Effort `[S]`
