### ISSUE TITLE
Sitemap Preload + All In One SEO Pack fails often

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1259]
**Describe the bug**
When using All In One SEO and sitemap preload is attempted, `rocket_process_sitemap()` returns here: 

https://github.com/wp-media/wp-rocket/blob/33578f0dd568819d3e5912e38cafb9d51d5964d7/inc/functions/bots.php#L225-L228

**To Reproduce**
1. WP Rocket + All In One SEO Pack
2. Enable Sitemap preload. Choose the sitemap
3. Click Preload Cache. The admin says `Sitemap preload: 0 uncached pages have now been preloaded. (refresh to see progress)`

**Additional context**
@WordPresseur said: _It works unless the `Enable Sitemap Indexes` option is enable_
https://wp-media.slack.com/archives/C08N8J6VC/p1539872700000100
For me it still failed.

**Comment by Tabrisrp** [comment]
I tested on my installation with the current 3.2.

It worked without issue, but the `Enable Sitemap Indexes` is not compatible with it, because it creates `xml.gz` files instead of regular xml, so the xml parser can't read them.

**Comment by Tabrisrp** [comment]
Ok after further investigation, they removed the possibility to save the filename in the settings at some point, using a filter instead.

In our code we try to fetch the filename from the options, and the corresponding index doesn't exist so the URL is incomplete.

Working solution is to use their filter instead.
