### ISSUE TITLE
Facebook files not locally saved when using GTM

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1260]
Google Tag Manager is also one of Facebook's recommended implementations: 
![facebook_pixel](https://user-images.githubusercontent.com/1043076/47171722-5666d880-d2be-11e8-919e-0aa211b7ab13.jpg)
But we don't currently detect/replace the FB files when loaded using Google Tag Manager

**Comment by Screenfeed** [comment]
@webtrainingwheels I have no idea of what you're talking about :|
I never used GTM, I don't even know what it does or the relation with FB here :/

**Comment by webtrainingwheels** [comment]
It's a question of scope, user experience and how we define this feature. 
In reality, there are numerous ways that a user can add the Facebook pixel to their site. 
The central question is, will the customer expect our feature to work no matter which method they use, particularly if it's a method supported/highlighted by Facebook itself?

**Comment by webtrainingwheels** [comment]
Just to say that this doesn't work in Alpha-6 at all, but I don't really think it's expected under the current scope.

**Comment by GeekPress** [comment]
Closing this issue as Facebook Pixels add-on will be removed in WP Rocket 3.9
