### ISSUE TITLE
3.2-alpha3: Custom cache folder edge cases and issues

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1261]
Few possible edge cases that I noticed. 

If I understand correctly, to use custom cache folders, all that is needed is to define `WP_ROCKET_CACHE_ROOT_PATH` and `WP_ROCKET_CACHE_ROOT_URL` in wp-config.php

Issue 1 - The rewrite rules in .htaccess are not updated until the WP Rocket settings are updated again. If the customer never updates WP Rocket settings, the rewrite rules would mean nothing. 

Issue 2 - Old cache files are not deleted once the new constants are defined. Trying to delete from UI deletes the new cache folders now and not the old ones. 

The easiest solution here would be to educate the customer about these potential issues and make the custom cache folder part of a helper plugin. On helper plugin activation / deactivation:
- Delete entire cache folder
- Flush .htaccess
- Regenerate Critical Path CSS

**Comment by webtrainingwheels** [comment]
Couldn't WP Rocket detect when the defines have been set and perform these 2 actions automatically?

**Comment by Tabrisrp** [comment]
The cache path is not saved anywhere, so we don't have a way to detect automatically if it changed.

Documentation + helper plugin seems the way to go, this should be used only by advanced users anyway.

**Comment by Tabrisrp** [comment]
@Screenfeed do you see another solution than that?

**Comment by arunbasillal** [comment]
@Screenfeed We get these questions already for our current helpers and some people hate the idea of having more plugins even when its just a filter in a file. 

Helper plugins do reduce support ticket though. Because it cannot go wrong. And anyone else who knows whats happening with have a reference to the code. So less questions in total.

**Comment by arunbasillal** [comment]
The helper plugin turned out to be a bit complicated than expected because:
- old constants are already defined by the time the plugin is loaded 
- during uninstall, custom constants are already defined

@Tabrisrp / @Screenfeed - Some tests are still pending, but here is a working helper. Please let me know if you see room for improvement or what I could have done differently - https://github.com/wp-media/wp-rocket-helpers/blob/master/cache/wp-rocket-cache-custom-folders/wp-rocket-cache-custom-folders.php

**Comment by webtrainingwheels** [comment]
Pardon my ignorance... but just to clarify for documentation purposes, if you use the helper, do you still define your paths in wp-config.php, or would that no longer be needed ?

**Comment by arunbasillal** [comment]
@webtrainingwheels only the helper is required and nothing else. 

Actually it is mandatory not to define it anywhere else while using the helper. Otherwise you will get a php notice saying the constant is already declared.

**Comment by webtrainingwheels** [comment]
Word. Thanks @arunbasillal!

**Comment by arunbasillal** [comment]
Since we decided to go with documentation + helper plugin

- Documentation - https://docs.wp-rocket.me/article/1118-specify-a-custom-cache-folder
- Helper plugin - https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-custom-folders

Closing issue.
