### ISSUE TITLE
How to handle fbclid query string

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1262]
This is a feature request from a customer: 
https://secure.helpscout.net/conversation/688390671/83274?folderId=273761

> It appears that Facebook has started automatically attaching the fbclid query string to links shared on the platform.

> Here's more info: http://thisinterestsme.com/facebook-fbclid-parameter/

> Since, the string is unique to each user, adding the parameter to the 'query strings to cache' box is a bad idea as a new cache file will be created for each user.

> This is a big problem for sites with a lot of Facebook traffic.

> I would suggest treating this query string in the same way that WP Rocket currently treats Google Analytics parameters and use the main cache file for this query.

> Alternately you could ensure that all parameters added to the 'query strings to cache' box use the main cache file rather than creating a new cache file for each string.

**Comment by Tabrisrp** [comment]
We can ignore it the same way we ignore `gclid`

**Comment by vmanthos** [comment]
Another related ticket here:
https://secure.helpscout.net/conversation/700764310/84919/
