### ISSUE TITLE
3.2-Alpha-3 GDPR compatibility not working

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1264]
Per @WordPresseur this isn't working: https://github.com/wp-media/wp-rocket/pull/1210
>No cache file served even when everything is approved.

[Wrike card](https://www.wrike.com/open.htm?id=276349128)

**Comment by jroddington** [comment]
Update from Romain about this:  

For the GDPR plugin, it works better now with the scenario given but the plugin has a nonce issue which leads to an acceptation issue (This occurs even if WP Rocket is disabled)

So the scenario was a little bit different : 1st load w/o cache > close the notification > 2nd load w/ cache. But in this scenario, the cookie notification is back even if the page is cached.

**Comment by Tabrisrp** [comment]
I can't reproduce this, on my testing:
- First load without cache
- Close notification by clicking "I agree"
- Second load with cache, no notification anymore
