### ISSUE TITLE
If more than one mandatory cookie is defined, the cache will be served when one of them is set

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#127]
How should we handle this case?

Currently, if one of the mandatory cookies defined in the config file is set, the cache file is served. 

But should we serve it only when all of them are set?

Or should we have a way to say either AND or OR?

**Comment by GeekPress** [comment]
I'm going to close this one as we don't seem to have the need to handle this case since this issues has been opened. We could re-open it we will have customer requests.
