### ISSUE TITLE
3.2-Alpha5: Sucuri add-on text

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1271]
Typo: 
![wp_rocket_ _wordpress_themes_ _wordpress](https://user-images.githubusercontent.com/1043076/47307545-254f1680-d5e4-11e8-9c7d-fffb3d9d75fb.jpg)
Sucury => Sucuri

To be consistent with other add-ons, I think it should only be called "Sucuri", not "Sucuri cache sync"

**Comment by ernee** [comment]
Should the same be applied for the tab when the add-on is turned on:

![screen shot 2018-10-23 at 8 51 06 am](https://user-images.githubusercontent.com/8108643/47373507-ddda9000-d6a0-11e8-8a8d-671a09d72ef8.png)

Just displaying it as "Sucuri" like "Cloudflare" ?

**Comment by Tabrisrp** [comment]
Yes I changed that too
