### ISSUE TITLE
3.2 Alpha: Mysterious Facebook file not optimized

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1275]
https://jmp.sh/XXfmDlK
The indicated file is not flagged by PageSpeed, but it is flagged by Yslow

Reporting here because it's not clear based on the original feature spec if we should be optimizing it or not.
It's a scope issue probably. Maybe could be considered for a minor version. But a decision should probably be made either way.

Slack: https://wp-media.slack.com/archives/CBJ2KQ0MU/p1539821810000100

**Comment by GeekPress** [comment]
This is the "real" Facebook Pixel. It's an URL for the 1x1 gif FB Pixel.

There is nothing we can do here to optimize this file. It's a fallback for non JS. It's added by using a noscript HTML tag.

Then this URL can't be stored locally as it's need to go on FB to be able to triggered the pixel on non JS.
