### ISSUE TITLE
3.2-alpha6: Missing CDN on 2 favicons type 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1276]
There are 2 more type of favicon to match with the CDN:

- manifest
- mask-icon

Here an exemple code from WP Rocket website:

```
<link rel="manifest" href="/wp-content/themes/wp-rocket/assets/favicons/manifest.json">
<link rel="mask-icon" href="/wp-content/themes/wp-rocket/assets/favicons/safari-pinned-tab.svg" color="#f56640">
```

**Comment by Screenfeed** [comment]
The manifest is not a fivicon, why would we handle it here?

**Comment by GeekPress** [comment]
GT Metrix detects the href and then complaints about not using the CDN on this too.

**Comment by Tabrisrp** [comment]
I agree with Greg, it's a different type of file, not related to favicons, not in scope of this specific feature.

It doesn't mean it should not be served from the CDN, but it should be a new feature request instead.

**Comment by GeekPress** [comment]
The manifest contains URLs to favicons. It's also a part of of favicon generator tools. Anyway, it's only take few minutes (or seconds) of work to add this compatibility.
