### ISSUE TITLE
Auto-exclude smartDonations JS from Combine JS option

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1281]
A dynamic inline JS which includes a post ID as to be auto-excluded to avoid the "cache dir size" issue.

The Inline JS needs to be inserted after the concatenated JS file.

`...'element':'donationContainer2014869551'});</script>`

element is the dynamic value.

Ref: https://secure.helpscout.net/conversation/688023390/83221?folderId=1050087

**Comment by Tabrisrp** [comment]
What's the complete inline script?
