### ISSUE TITLE
Auto-exclude inline JS from the Combine JS process

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1287]
An inline JS which includes a dynamic comment ID leads to the `cache dir size` issue:
`document.getElementById("comment").setAttribute( "id", "c05e4a0b1f3bd2ce3930a55f0343e041" );document.getElementById("313e069377").setAttribute( "id", "comment" );`

**Patterns to exclude**
```
document.getElementById("comment")
addComment
```

**Related ticket**
https://secure.helpscout.net/conversation/692782838/83777/

**Comment by Tabrisrp** [comment]
Is there something more specific that can be used as a pattern? Those two could be used by other themes/plugins

**Comment by vmanthos** [comment]
I'm afraid there isn't something more specific to the particular block of JavaScript than what I've included in my original message:
```
<script type="text/javascript">
   document.getElementById("comment").setAttribute("id", "3d1f95ba3a973c3eea6603f3eeed7ae6");
   document.getElementById("203c549a13").setAttribute("id", "comment");
</script>
```
