### ISSUE TITLE
404 error in console for lazyload.min.js.map

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1302]
With the newest version we see this - https://jmp.sh/iZm6BSE

Related chat with Remy - https://wp-media.slack.com/archives/C43T1AYMQ/p1541518198109100

> it’s new in the latest version of the lazyload script
> the map file is to display an unminified version of the script in the browser dev tools
> it doesn’t have an impact on the website itself
> I can add the map file in 3.2.1 to prevent that

**Comment by Tabrisrp** [comment]
Fixed in 3.2.1
