### ISSUE TITLE
Paypal Add-on

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#1304]
**Is your feature request related to a problem? Please describe.**

Please support Paypal expess checkout. It takes too much time to load their script.

<img width="807" alt="screen shot 2018-11-07 at 12 10 22" src="https://user-images.githubusercontent.com/2909982/48111907-6868e500-e286-11e8-9c6a-b033f763a1b7.png">

**Describe the solution you'd like**

Store Paypal Script as facebook and Google Analytics.

**Comment by arunbasillal** [comment]
@kevin25 in 3.7, we have introduced a feature to delay JS execution. Can you try delaying the PayPal script and see how that works out? 

If delaying works correctly that would be a much better UX improvement that hosting the file locally.
