### ISSUE TITLE
Replace Wistia iframe with a preview image 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1305]
Replace **Wistia** video `iframe` with a preview thumbnail like we currently do for **Youtube** videos.

**Related ticket**
https://secure.helpscout.net/conversation/702192540/85129?folderId=273761

**Additional context**

Wistia's documentation regarding thumbnail extracting:
https://wistia.com/support/developers/extracting-thumbnails#extracting-the-thumbnail

**Relevant Wistia documentation links**

- https://wistia.com/support/developers
- https://wistia.com/support/developers/data-api

**Comment by Tabrisrp** [comment]
> Extracting thumbnails like this isn’t instaneous. In most cases, our system will have to pull the original video file out of storage to operate on it. When this happens, we will return a 202 Accepted response instead of the thumbnail image when you hit that URL, and in the background our servers will be extracting the thumbnail for you. This usually takes anywhere from 15 seconds to a few minutes depending on the size of the video file you’re pulling the thumbnail from.

This might be an issue for us.

**Comment by GeekPress** [comment]
It seems that it's not going to be possible to do this enhancement. I'm closing it.
