### ISSUE TITLE
Preload Idea - A fallback when sitemap preload fails

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1306]
No matter how much we improve the preload process, fetching the sitemap is always going to be a bottle neck. There isn't much we can do if the cURL request takes longer other than asking users to contact their host, upgrade hosting and so on. 

An idea is to come up with a fallback plan. 

- When sitemap fetch fails, get the links from the DB.
- Do something similar to what the SEO plugins do to generate the sitemap in the first place. 
- We know all the custom post types and taxonomies. 
- Show an admin notice that we are switching to fallback. 

I think this would reduce a ton of issues we have related to sitemap based preload. The customer is happy because we are auto-magically switching strategies and his/her pages are preloaded one way or another.

**Comment by Tabrisrp** [comment]
Points to discuss:

- Do we still display errors to the customers if things went wrong and the fallback is used?
- Can the customers opt-out of the fallback? If yes, how?

**Comment by arunbasillal** [comment]
Documenting raw thoughts:

> Do we still display errors to the customers if things went wrong and the fallback is used?

- We never did this before and it only started with 3.2.4. So if we choose to not show the errors, it isn't a major pull back.
- We could choose to display the errors if `WP_DEBUG` and / or `WP_ROCKET_DEBUG` is enabled. 

> Can the customers opt-out of the fallback? If yes, how?

- Fallback is used only when things fail, so if no fallback means no preload. 
- Disable preload to opt out of fallback
- Unless we have a specific use case where a customer wants this, imho, lets keep things simple.
