### ISSUE TITLE
Cloudflare Google Analytics

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#1307]
Hi, I use this
![screenshot_17](https://user-images.githubusercontent.com/43606394/48132248-36aa4b00-e293-11e8-8dd8-b4e1fb9c2d8a.png)

and the google analytics add-on from cloudflare

But it's not working
![screenshot_18](https://user-images.githubusercontent.com/43606394/48132333-72451500-e293-11e8-92db-cf3eff5b4d60.png)

![screenshot_19](https://user-images.githubusercontent.com/43606394/48132391-a8829480-e293-11e8-9239-afa1f36cd9b2.png)

**Comment by arunbasillal** [comment]
The Google Tracking add-on does not work with tag manager. See the note here: https://docs.wp-rocket.me/article/1103-google-tracking-add-on

Please open a ticket for support - https://wp-rocket.me/support/
We use GitHub more to address confirmed bugs and coordinate development.
