### ISSUE TITLE
Issue Spanish Language

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#1314]
![screenshot_20](https://user-images.githubusercontent.com/43606394/48164170-063dcd80-e2e2-11e8-9afb-9ce28083c46f.png)

**Comment by Camilo517** [comment]
It's pretty ugly that a paid plugin has these basic errors ... Google translator ...
![screenshot_21](https://user-images.githubusercontent.com/43606394/48164410-b7dcfe80-e2e2-11e8-87e0-a75fe61278e0.png)
![screenshot_22](https://user-images.githubusercontent.com/43606394/48164496-f5418c00-e2e2-11e8-89e0-3a1034816b23.png)
![screenshot_23](https://user-images.githubusercontent.com/43606394/48164594-405b9f00-e2e3-11e8-97ed-e8198e038f07.png)
![screenshot_24](https://user-images.githubusercontent.com/43606394/48164734-a811ea00-e2e3-11e8-86dd-ec96d746d3e0.png)

**Comment by AliceOrru** [comment]
Hi Camilo, 
Thanks for taking the time to note these errors. 
I'm the translator of WP Rocket in Spanish; what you see is not an automatic Google Translation but the result of human work (and sometimes typos occur, unfortunately!) ;)
I edited the typos you mention except for the term _URL_: in Spanish, you can find this acronym translated in both forms (female and masculine), and both are correct. 
I decided to keep the masculine form, following what suggested in the [forum of the Instituto Cervántes](https://cvc.cervantes.es/foros/leer_asunto1.asp?vCodigo=53614), and in [Wikipedia](https://es.wikipedia.org/wiki/Localizador_de_recursos_uniforme).

Thanks again for your contribution!

**Comment by Camilo517** [comment]
Hola, te escribo mejor en español.
Si eres española jamás oirás decir los URL porque queda mal y suena muy mal...
Un saludo, buen finde :)
