### ISSUE TITLE
Please make it possible for GTM and other locally-copied scripts to be included in the minified bundle

### ISSUE THREAD

**Issue by x1024** [wp-media/wp-rocket#1316]
I am referring to the WP Rocket add-on that enables local caching for Google's ad scripts.

At the moment, this script is getting cached, but not minified or concatenated with the other scripts on the site. It constitutes the majority of the JS code running on my site and therefore it being unoptimized is a noticeable performance penalty.

Are there any plans to implement such a feature? I would imagine that the minifier simply runs before the code that creates local caches of scripts, and at least an initial solution could be simple to implement.

How would one go about implementing this?

Thanks.

**Comment by x1024** [comment]
Indeed removing `data-no-minify="1"` from `class-google-tag-manager.php` and moving the relevant `Cache_Busting_Subscriber` instances further up the list of subscribers does address the issue.

Since the code is obviously implemented on purpose this way, is there any downside to optimizing and bundling gtm.js? Am I missing something, and if not - will there be an option/a default setting to do what I want?

**Comment by Tabrisrp** [comment]
We are playing it safe with this, because users are most of the time very sensitive about the statistics.

Minifying and combining the script by default could have unexpected consequences, and create a wave of tickets about incorrect tracking.

**Comment by x1024** [comment]
That is understandable. However, given the low complexity of the solution
(It was less than 10 lines for me), would you consider adding a checkbox
option for that in the "Advanced options" section?

**Comment by GeekPress** [comment]
@x1024 Sorry for the late response ^^

To be direct, we won't change the current behavior for the reason @Tabrisrp gave you. Also, in terms of performance, it won't speed up anything to get the GA inline JS included to other or included the GTM JS file into the concatenated file (we just save 1 HTTP request).

As these scripts are critical for a website, we decide to be careful and select the safest option.
