### ISSUE TITLE
Homepage preload process needs fixes

### ISSUE THREAD

**Issue by foliovision** [wp-media/wp-rocket#1322]
Thank you for the new (WP Rocket 3.2) preload bot, it's great! However:

1) If it finds the same URL multiple times it doesn't filter it out.

2) The URLs with query strings are not handled properly. WP Menu editor changes `&` to `&#038;` and then parse_url() doesn't recognize that properly.

3) It doesn't understand relative URLs, like /about

We worked on fixing this, please check our fixes here: #1321

**Comment by kevin25** [comment]
Well i found it preloading my homepage many times.
