### ISSUE TITLE
When the Facebook Pixel is implemented using signal.co tracking might break 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1324]
When the Facebook Pixel is implemented using *signal.co* (https://www.facebook.com/business/help/1045288012177021) and the Facebook add-on is enabled we replace some strings in the sdk.js that will most likely break tracking for customers.

Here is the diff file demonstrating the changes we make in comparison to the Signal's file:
https://www.diffchecker.com/zcNADfLW

*Related Ticket*
https://secure.helpscout.net/conversation/704013562/85513?folderId=2135277

*Link to check this*
http://wealthweekly.com/contest

*Using the Facebook pixel with Signal*
https://www.facebook.com/business/help/1045288012177021

**Comment by GeekPress** [comment]
Closing this issue as Facebook Pixels add-on will be removed in WP Rocket 3.9
