### ISSUE TITLE
The Facebook Pixel add-on breaks the Facebook Like/Share plugin

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1326]
When enabled, the Facebook Pixel add-on breaks the [Facebook Like/Share Plugin](https://developers.facebook.com/docs/plugins#like-share-send).

**To Reproduce**

1. Go to http://wealthweekly.com/contest?nocache. There is a Facebook Like/Share box there (https://vgy.me/UmTONB.jpg), which is embedded using an `iframe`.
2. Go to http://wealthweekly.com/contest/
The Like/Share box is gone.

We replace only the `revision:` value in comparison to the sdk.js that we fetch from Facebook. Check the diff here:
https://www.diffchecker.com/FT5VIg3v

**Related Ticket**
https://secure.helpscout.net/conversation/704013562/85513?folderId=2135277

**Comment by crystinutzaa** [comment]
Fixed with v3.4.3 release

**Comment by alfonso100** [comment]
This issue was fixed and closed, but I've just encountered a similar case here with WPR 3.5.5.1: 
https://secure.helpscout.net/conversation/1178785091/168787/

If the Facebook Add-on is enabled, this likebox doesn't work: https://jmp.sh/dUFCT6O

Saved the JS files in the ticket for reference

**Comment by GeekPress** [comment]
@crystinutzaa Can you have a look to this?
@alfonso100 can you ask a FTP access? It will be easer for @crystinutzaa if we can try directly on the customer website.

Thanks =)

**Comment by crystinutzaa** [comment]
@GeekPress sure. @alfonso100 please contact me when we have access and I will take a closer look

**Comment by piotrbak** [comment]
Related ticket:
https://secure.helpscout.net/conversation/1233430729/182036?folderId=2415573

**Comment by GeekPress** [comment]
Closing this issue as Facebook Pixels add-on will be removed in WP Rocket 3.9
