### ISSUE TITLE
CDN image replacement and WPML using different domains

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1327]
Reported by customer, when using WPML and different domains per language. 
Image replacement only working on main domain and not others. 

From the customer: 

> wp-content/plugins/wp-rocket/inc/front/cdn.php:150

>$wp_content_dirname -> This one returned the wrong domain. It returned .nl (the main domain) while the page is on the .com domain.

>wp-content/plugins/wp-rocket/inc/front/cdn.php:161
>if ( empty( $path ) || ! preg_match( '#(' . $wp_content_dirname . '|wp-includes)#', $path ) )
>The loop stopped after this if statement.

https://secure.helpscout.net/conversation/703442709/85394?folderId=377611

**Comment by webtrainingwheels** [comment]
Customer has investigated further and says that this was not a problem in 2.11.4 - all features (cdn, minification) work as expected in that version.

**Comment by dries863** [comment]
It would make more sense to me to make the replacement script like this:

1. Get all domains from WPML
2. Replace "WPML domains" by the CDN domain for all `scr` attributes in `img` tags in $html.

That make the rocket_cdn_images() way simpler and less error prone. This will also remove most of the if statements in that method.

**Comment by Tabrisrp** [comment]
I'm not able to reproduce the issue on the current 3.2.3.1 version.

Testing with 2 different top level domains, all assets are correctly rewritten to the CDN on both.
