### ISSUE TITLE
OneSignal Add-ON

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#1329]
Is your feature request related to a problem? Please describe.

Please support OneSignal. It takes too much time to load their script.

Describe the solution you'd like

Onesignal Script as facebook and Google Analytics.

https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js

**Comment by Camilo517** [comment]
Is it possible to include it in 3.2.3 or 3.2.4? I'm sure it will improve the load time a lot @Tabrisrp 
Thanks 🥇 👍

**Comment by Camilo517** [comment]
Any news about this? @Tabrisrp  Thanks

**Comment by arunbasillal** [comment]
@Camilo517 in 3.7, we have introduced a feature to delay JS execution. Can you try delaying the OneSignal script and see how that works out?

If delaying works correctly that would be a much better UX improvement that hosting the file locally.

**Comment by JohnTorvik** [comment]
Adding the **"OneSignalPageSDKES6.js"** and **"OneSignalSDK.js"** in Delay JS Textarea worked successfully:
See these scripts being delayer correctly: https://recordit.co/m10p6IKVxk

**Comment by GeekPress** [comment]
Hi @Camilo517

Thanks for contributing to WP Rocket repository.

As @arunbasillal and @JohnTorvik suggested, you should use our new Delay JS to optimize OneSignal loading time.
