### ISSUE TITLE
I can't regenerate the Critical Path CSS after upgrading to 3.2.1.1

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#1330]
Does anyone have issue with Critical Path CSS after upgrading to 3.2?

Critical CSS for front_page not generated. Error: The API returned an invalid response code.
Critical CSS for home not generated. Error: The API returned an invalid response code.
Critical CSS for elementor_library not generated. Error: The API returned an invalid response code.
Critical CSS for page not generated. Error: The API returned an invalid response code.
Critical CSS for post not generated. Error: The API returned an invalid response code.
Critical CSS for product not generated. Error: The API returned an invalid response code.
Critical CSS for category not generated. Error: The API returned an invalid response code.
Critical CSS for pa_color not generated. Error: The API returned an invalid response code.

**Comment by arunbasillal** [comment]
@kevin25 Please open a support ticket for this issue - https://wp-rocket.me/support/

We use GitHub mainly for development and to report confirmed bugs and not for support. 

Cheers.
