### ISSUE TITLE
CPCSS generation on infinite Loop - Force exit when this happens

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1333]
There were couple of tickets where CPCSS generation never stopped. 

![screen shot 2018-11-08 at 1 09 57 pm](https://user-images.githubusercontent.com/5751474/48340129-236bf680-e66a-11e8-854f-d69c03f4f644.png)

For some weird reason, the `complete()` method was never called - https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/classes/class-rocket-background-critical-css-generation.php#L181-L201

**Tickets:**
- https://secure.helpscout.net/conversation/680055496/82258?folderId=273766#thread-1887162396
- https://secure.helpscout.net/conversation/693314047/83840?folderId=1724284

**Idea:** 
We could add a check to see if the count ever goes beyond the total count and when it does force the process to exit. It sounds hacky, but when weird things happen, a hack is not such a bad idea imo.

**Comment by webtrainingwheels** [comment]
Same here: https://secure.helpscout.net/conversation/716615436/87936?folderId=273761

https://prnt.sc/lmx7xu

**Comment by webtrainingwheels** [comment]
HS tag: `cpcss generation loop`

**Comment by arunbasillal** [comment]
This is becoming more and more common. Did something change that could possibly cause this?

**Comment by arunbasillal** [comment]
Another related ticket - https://secure.helpscout.net/conversation/803183217/100511/

**Comment by arunbasillal** [comment]
@Tabrisrp I was able to replicate this simply by regenerating CPCSS multitple times - https://jmp.sh/Th7UkzY

If I launched the Critical Path CSS generation thrice, it will be 3 times the number of post types. 

WP Rocket version `version 3.3.1-beta1`
You can test it here: http://mega.wp-rocket.me/avada/wp-admin/options-general.php?page=wprocket#dashboard

Wondering if this was the reason after all.
