### ISSUE TITLE
Exclude "Revolution Slider" inline JavaScript to avoid the cache directory size issue

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1335]
The **Revolution Slider** plugin adds inline JavaScript that causes the cache directory size to increase.

The part that is changing and causes the issue is:
- data.token

```
jQuery(document).ready(function() {
            var ajaxRevslider = function(obj) {
                    var content = "";
                    data = {};
                    data.action = 'revslider_ajax_call_front';
                    data.client_action = 'get_slider_html';
                    data.token = '7bf9cf305b';
                    data.type = obj.type;
                    data.id = obj.id;
                    data.aspectratio = obj.aspectratio;
                    jQuery.ajax({
                                type: "post",
                                url: "https://cotswoldgiftware.com/wp-admin/admin-ajax.php",
                                dataType: 'json',
                                data: data,
                                async: !1,
                                success: function(ret, textStatus, XMLHttpRequest) {
                                        if (ret.success == !0)
```
**Diff file:** https://www.diffchecker.com/1JloI7Zt

**Proposed Solution**
Exclude the following from the JavaScript combination process:

`data.token`

**Related Ticket**
https://secure.helpscout.net/conversation/702254330/85140?folderId=2135277

**Comment by hrcoliqueo** [comment]
it worrkss!!!!

> The **Revolution Slider** plugin adds inline JavaScript that causes the cache directory size to increase.
> 
> The part that is changing and causes the issue is:
> 
> * data.token
> 
> ```
> jQuery(document).ready(function() {
>             var ajaxRevslider = function(obj) {
>                     var content = "";
>                     data = {};
>                     data.action = 'revslider_ajax_call_front';
>                     data.client_action = 'get_slider_html';
>                     data.token = '7bf9cf305b';
>                     data.type = obj.type;
>                     data.id = obj.id;
>                     data.aspectratio = obj.aspectratio;
>                     jQuery.ajax({
>                                 type: "post",
>                                 url: "https://cotswoldgiftware.com/wp-admin/admin-ajax.php",
>                                 dataType: 'json',
>                                 data: data,
>                                 async: !1,
>                                 success: function(ret, textStatus, XMLHttpRequest) {
>                                         if (ret.success == !0)
> ```
> 
> **Diff file:** https://www.diffchecker.com/1JloI7Zt
> 
> **Proposed Solution**
> Exclude the following from the JavaScript combination process:
> 
> `data.token`
> 
> **Related Ticket**
> https://secure.helpscout.net/conversation/702254330/85140?folderId=2135277
