### ISSUE TITLE
Improvement: Don't display number of cached page from automatic preload

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1354]
Since the 3.2, we are using the background process for our old "Manual" and "Automatic" preloaders.

Then when one of them is triggered we display the total of pages cached. The problem is that our users can be confused by the number.

Indeed, for the old Automatic which preload pages related to a post/page after updating it will preload just a few pages. So it could be considering like a bug for our users. "Why just 10 pages has been preloaded?"

As we doing this kind of preload in background, we could display the numbers on these condition:
- nothing related to the old "Automatic" preload
- if sitemap preload is turned off, nothing related to the old "Manual" (Homepage now)

Related ticket:
https://secure.helpscout.net/conversation/704929819/85734/?folderId=273768

**Comment by Tabrisrp** [comment]
The notice is not displayed for the "automatic" preload.

It is displayed for the "manual", even when sitemap preload is not selected.

Do you want to remove it too and only display for sitemap preload?

**Comment by Tabrisrp** [comment]
This need to be discussed further before moving forward

**Comment by arunbasillal** [comment]
The customer in the ticket hadn't enabled sitemap preload and that was the source of the confusion as to why all the links in the sitemap are not preloaded. 

The reporting on the preload page happens only when preload is triggered manually as Remy mentioned. The purpose of the notice is to report how many pages were preloaded. Even if we count both links discovered from the homepage and sitemap, it will be greater than the links in the sitemap. And no one should be unhappy about that. 

I feel like we are trying to over-engineer a non-existent problem. My suggestion is to let this one pass and revisit this when we see obvious confusion.

**Comment by GeekPress** [comment]
What about that one?

> Indeed, for the old Automatic which preload pages related to a post/page after updating it will preload just a few pages. So it could be considering like a bug for our users. "Why just 10 pages has been preloaded?"

It's very confusing for a user. When someone edit a page we display a notice: 5 pages preloaded. 

Why just 5? We don't explain anything about that. Should we really display a notice for this automatic feature?

**Comment by arunbasillal** [comment]
Hey @GeekPress 

> When someone edit a page we display a notice: 5 pages preloaded.

When someone edit a page, it's the automatic preload and no notice is displayed. The notice is only displayed for manual preload. [reference](https://github.com/wp-media/wp-rocket/issues/1354#issuecomment-441081796)

The notice only applies to **manual preload**. And how it works is explained in the admin area

> When you enable preloading WP Rocket will generate the cache starting with the links on your homepage followed by the sitemaps you specify. 

![preload](https://user-images.githubusercontent.com/5751474/62467464-744fec00-b7b1-11e9-8aeb-b35c0af6b5d3.png)

Apart from the ticket mentioned in your original issue, how often do we see this confusion reported?

**Comment by GeekPress** [comment]
Awesome, I thought we had a notice when we update a post. I don't remember exactly why I reported that, it was a long time ago now...

**Comment by arunbasillal** [comment]
Glad to hear 👍 

Since we haven't heard about this confusion in almost a year, I am going to close this issue for now. Please feel free to re-open if anyone disagrees.
