### ISSUE TITLE
Add SEOPress support to automatically detected sitemaps

### ISSUE THREAD

**Issue by wp-seopress** [wp-media/wp-rocket#1357]
URL of the sitemaps: http://example.com/sitemaps.xml 
<img width="398" alt="sp" src="https://user-images.githubusercontent.com/30056254/48509810-67b9eb00-e852-11e8-9f11-99936efd5557.PNG">

**Comment by Tabrisrp** [comment]
Is there easily-accessible functions to detect if the sitemap option is active in SEOPress and to get the sitemap URL?

**Comment by wp-seopress** [comment]
Yes,
`seopress_get_toggle_xml_sitemap_option()=='1'`

The rewrite rule to get the sitemap index:
`add_rewrite_rule( '^sitemaps.xml$', 'index.php?seopress_sitemap=1', 'top' );`

**Comment by wp-seopress** [comment]
any news on this?

**Comment by Tabrisrp** [comment]
This was not yet scheduled for a release. If you want to do a PR to do the third-party compatibility, similar to other SEO plugin, you're welcome to and we'll integrate it in the next version.

**Comment by wp-seopress** [comment]
OK, the code is ready, how do I share it? Thx

**Comment by Tabrisrp** [comment]
You can for the repository and create a pull request with the new code to be reviewed 👍

**Comment by arunbasillal** [comment]
@wp-seopress We are prepping for another minor version. If the code is ready, please feel free to send in a PR. Thanks.

**Comment by wp-seopress** [comment]
@arunbasillal @Tabrisrp here it is: https://github.com/wp-seopress/wp-rocket

**Comment by arunbasillal** [comment]
@wp-seopress Thank you. Please open a pull request to the develop branch.

**Comment by wp-seopress** [comment]
done: https://github.com/wp-media/wp-rocket/pull/1884

**Comment by wp-seopress** [comment]
@Tabrisrp Just to be sure, should I do something more? or my job is finished?

**Comment by Tabrisrp** [comment]
You're done 👍
