### ISSUE TITLE
Enable CDN URL per WPML Domain

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1359]
When using WPML with a different domain per language, it may be desirable to use a different CDN URL per language. 

Feature request: https://secure.helpscout.net/conversation/706812897/86051?folderId=377611

**Comment by WordPresseur** [comment]
Another ticket: https://secure.helpscout.net/conversation/987503879/128025?folderId=1213662

**Comment by WordPresseur** [comment]
Another one : https://secure.helpscout.net/conversation/1000384013/130499/

**Comment by camilamadronero** [comment]
Another one: https://secure.helpscout.net/conversation/1016997058/133526.

**Comment by camilamadronero** [comment]
Another one: https://secure.helpscout.net/conversation/1018252125/133844/.

**Comment by adinaWP** [comment]
Another ticket: https://secure.helpscout.net/conversation/1178211786/168636?folderId=343175

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll get back to it when working on WPML compatibility in the future.
