### ISSUE TITLE
Request Some Features with database optimization

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#1360]
These features are really important to clean and optimize database.

1. Detect orphan options, plugins options, themes options and WP options
2. Detect orphan tasks, plugins tasks, themes tasks and WP tasks
3. Detect orphan tables, plugins tables, themes tables and WP tables

**Comment by Camilo517** [comment]
Hello, any news about this? @Tabrisrp

**Comment by GeekPress** [comment]
@kevin25 @Camilo517 Do you actually use another plugin to do the requested improvements?
If so, which one? :)

Thanks

**Comment by Camilo517** [comment]
@GeekPress 
https://codecanyon.net/item/wp-cleaner-pro/21459036?_ga=2.30720767.1946846970.1590088865-2012854876.1590088865
https://wordpress.org/plugins/advanced-database-cleaner/

**Comment by piotrbak** [comment]
This is currently not planned for development. If we decide to take care of database optimization, we'll revisit the issue.
