### ISSUE TITLE
Embed jQuery file into HTML

### ISSUE THREAD

**Issue by dev4press** [wp-media/wp-rocket#1364]
**Is your feature request related to a problem? Please describe.**
jQuery is required for practically all WordPress websites, and it is loaded with every page request. But, this file (and accompanying jQuery Migrate) is always a render blocking.

**Describe the solution you'd like**
Embed jQuery and jQuery Migrate into HTML head. Both files take 105KB, and when they are part of HTML they will have the benefit of GZip compression. And, they are not going to be render-blocking any more.

Add extra option along with the render-blocking JavaScript settings, to turn on HTML embedding for jQuery, instead of using Safe mode option. Also, maybe use a similar method to embed some more JS files that should go into the HTML head.

**Comment by GeekPress** [comment]
Hi @dev4press again 😇

Inline JS for big JS files like jQuery isn't a good performance practice. Here some details from Google: https://developers.google.com/speed/docs/insights/BlockingJS?hl=fr#InlineJS
