### ISSUE TITLE
License Validation - Detect when connection is blocked by firewall or security plugins

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1366]
A common issue with license validation is the connection to our validation system is blocked by a security plugin. 

Right now, we show the notice and point them to our doc - https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation

![file-qfu04rjlwy](https://user-images.githubusercontent.com/5751474/48710003-719f6d80-ec07-11e8-9af6-a59d1f4153a9.png)

Since the validation error says to contact support, they often contact us and all we can do is tell them that it's a connection issue. Which can be automated. 

- We can definitely confirm if it's a connection issue or not. If it's a connection issue, displaying that info to the user directly in the UI and asking them to whitelist our IP or contact their host would be better. 
- We could go one-step further and check to see if any of the security plugins that often cause issues are installed and point that out to the user as well with a solution.

**Comment by webtrainingwheels** [comment]
Old error notice is still showing even if issue is rectified. 
While testing I added this to wp-config: 
`define( 'WP_HTTP_BLOCK_EXTERNAL', true );`
But even after removing it, I still get this error notice showing: 

![error_notice_not_updated](https://user-images.githubusercontent.com/1043076/51564482-470aa480-1e44-11e9-9aa4-ebf8c4225e60.jpg)

**Comment by ernee** [comment]
Update the following license validation errors:

1) _There seems to be an issue validating your license. You can see the error message below. Resolve per documentation, or contact support._

**New**

There seems to be an issue validating your license. Please see the error message below.

2) _License validation failed. Unexpected response from the validation server._ 

**New**

License validation failed. Our server could not resolve the request from your website.

Try clicking _Save Changes_ below. If the error persists, follow [this guide](https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation#general).

3) _License validation failed. No body available in response._

**New**

License validation failed. Our server could not resolve the request from your website. 

Try clicking _Save Changes_ below. If the error persists, follow [this guide](https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation#general).

4) _License validation failed: Your license is not valid._

**New**

License validation failed: Your license is not valid. 

Make sure you have an active [WP Rocket license](https://wp-rocket.me).  

5) _License validation failed: You cannot add more websites. Upgrade your account._

**New** 

License validation failed: You have added as many sites as your current license allows. 

Upgrade your [account](https://wp-rocket.me/account/) or [transfer your license](https://docs.wp-rocket.me/article/28-transfering-your-license-to-another-site) to this domain. 

6) _License validation failed: This website is not allowed._

**New**

License validation failed: This website is not allowed. 

Please [contact support](https://wp-rocket.me/support/).


7) _License validation failed: This license key is not accepted._

**New**

License validation failed: This license key is not recognized.

- Login to your WP Rocket [account](https://wp-rocket.me/account)

- Download the zip file

- Reinstall

 If the issue persists, please [contact support](https://wp-rocket.me/support/).

8) _License validation failed. You are using a nulled version of the plugin._

**New**

License validation failed. You may be using a nulled version of the plugin. Please do the following: 

- Login to your WP Rocket [account](https://wp-rocket.me/account)

- Download the zip file

- Reinstall

If you do not have a WP Rocket account, please [purchase a license](https://wp-rocket.me).

9) _License validation failed. This user account does not exist in our database._

**New** 

License validation failed. This user account does not exist in our database. 

To resolve, please [contact support](https://wp-rocket.me/support/).

10) _License validation failed. This user account is blacklisted._

**New**

License validation failed. This user account is blacklisted. 

Please see [this guide](https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation#errors) for more info.

**Comment by ernee** [comment]
Additional comment that when there is a failure, the notice will be red (error).

**Comment by ernee** [comment]
Along with issues raised in #1492 the following need review:

1) There seems to be an issue validating your license. Please see the error message below. Resolve per documentation, or contact support.

**Correction:** 

There seems to be an issue validating your license. Please see the error message below.

2) Link formatting broken: https://jmp.sh/PFnc6Zj

**Correction:**

License validation failed. Our server could not resolve the request from your website. 

Try clicking Save Changes below. If the error persists, follow [this guide](https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation#general).

(replaces previous “No body available in response” and “Unexpected response from the validation server.”)

3) stray `<br>` in the notice: https://jmp.sh/qTJbjVN

**Correction:** 

License validation failed. This user account does not exist in our database. 

To resolve, please [contact support](https://wp-rocket.me/support/).

4) Correct message, broken formatting: https://jmp.sh/hrazvMa

**Correction:**

 License validation failed. This user account is blacklisted. 

Please see [this guide](https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation#errors) for more info.

**Comment by Tabrisrp** [comment]
Fixed by the same commit as #1492

**Comment by webtrainingwheels** [comment]
Formatting now looks good 👌

Small text fix still remaining (remove underlined text): 
![wp_rocket](https://user-images.githubusercontent.com/1043076/51856385-70b04980-22e4-11e9-84b4-0c1662aa70cd.jpg)

Current text: `There seems to be an issue validating your license. Please see the error message below. Resolve per documentation, or contact support.`

Should be changed to: `There seems to be an issue validating your license. Please see the error message below.`
