### ISSUE TITLE
WPML second language (Arabic) isn't cached or preloaded 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1367]
The WPML second language (Arabic) wasn't cached or preloaded.

In WPML:

- The **Different languages in directories** option was enabled.
- The **Use directory for default language** option wasn't enabled.

Adding the following query strings in the **Cache Query String(s)** field started the preloading for the Arabic language:
`_glang `
`gurl`

I added those because I saw a cached folder that had them in the folder name.

I couldn't determine where these come from.

**WPML settings screenshot:**
http://bit.ly/2Bh0Ou9

**WPML debug info:**
http://snippi.com/s/sjj2rb3

The _/wp-content/cache/wp-rocket/www.example.com/ar/_ directory, after the addition of the prementioned query strings, included files named like this:
_glang=ar&gurl=الجديد-في
**Screenshot:** https://vgy.me/8nbCEN.jpg

The first part is for setting the language and the last query string is the path of the URL. So this:
https://www.example.com/?_glang=ar&gurl=الجديد-في

becomes this:
https://www.example.com/ar/الجديد-في

**Related ticket:**
https://secure.helpscout.net/conversation/706762778/86038/?folderId=273766

**Comment by Tabrisrp** [comment]
I did some testing with Arabic and WPML. I was not able to replicate the issue.

`_glang` and `gurl` are not parameters used by WPML anywhere in the code. Was there another plugin that could have added them?

Did you check that the wp-rocket-config file was created for this language?

**Comment by GeekPress** [comment]
@vmanthos I know the issue has been created a long time ago, but is it still fresh to be able to reply to @Tabrisrp ? 👆

**Comment by vmanthos** [comment]
@Tabrisrp I apologize for missing this one.

It's been long since I worked on it and I don't remember the details.

@GeekPress Since we didn't have something similar, I think it's safe to close this issue.

**Comment by GeekPress** [comment]
@vmanthos Thanks for the feedback. Let's close it ;)

**Comment by alfonso100** [comment]
these 2 query strings, `glang` (without underscore) and `gurl` resurfaced today in a new case. 
The source was a leftover in the .htaccess, doing a redirect, from the gTranslate plugin: 

```
### BEGIN GTranslate config ###
RewriteRule ^(af|sq|am|ar|hy|az|eu|be|bn|bs|bg|ca|ceb|ny|zh-CN|zh-TW|co|hr|cs|da|nl|en|eo|et|tl|fi|fr|fy|gl|ka|de|el|gu|ht|ha|haw|iw|hi|hmn|hu|is|ig|id|ga|it|ja|jw|kn|kk|km|ko|ku|ky|lo|la|lv|lt|lb|mk|mg|ms|ml|mt|mi|mr|mn|my|ne|no|ps|fa|pl|pt|pa|ro|ru|sm|gd|sr|st|sn|sd|si|sk|sl|so|es|su|sw|sv|tg|ta|te|th|tr|uk|ur|uz|vi|cy|xh|yi|yo|zu)/(af|sq|am|ar|hy|az|eu|be|bn|bs|bg|ca|ceb|ny|zh-CN|zh-TW|co|hr|cs|da|nl|en|eo|et|tl|fi|fr|fy|gl|ka|de|el|gu|ht|ha|haw|iw|hi|hmn|hu|is|ig|id|ga|it|ja|jw|kn|kk|km|ko|ku|ky|lo|la|lv|lt|lb|mk|mg|ms|ml|mt|mi|mr|mn|my|ne|no|ps|fa|pl|pt|pa|ro|ru|sm|gd|sr|st|sn|sd|si|sk|sl|so|es|su|sw|sv|tg|ta|te|th|tr|uk|ur|uz|vi|cy|xh|yi|yo|zu)/(.*)$ /$1/$3 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(af|sq|am|ar|hy|az|eu|be|bn|bs|bg|ca|ceb|ny|zh-CN|zh-TW|co|hr|cs|da|nl|en|eo|et|tl|fi|fr|fy|gl|ka|de|el|gu|ht|ha|haw|iw|hi|hmn|hu|is|ig|id|ga|it|ja|jw|kn|kk|km|ko|ku|ky|lo|la|lv|lt|lb|mk|mg|ms|ml|mt|mi|mr|mn|my|ne|no|ps|fa|pl|pt|pa|ro|ru|sm|gd|sr|st|sn|sd|si|sk|sl|so|es|su|sw|sv|tg|ta|te|th|tr|uk|ur|uz|vi|cy|xh|yi|yo|zu)/(.*)$ /wp-content/plugins/google-language-translator/url_addon/gtranslate.php?glang=$1&gurl=$2 [L,QSA]
RewriteRule ^(af|sq|am|ar|hy|az|eu|be|bn|bs|bg|ca|ceb|ny|zh-CN|zh-TW|co|hr|cs|da|nl|en|eo|et|tl|fi|fr|fy|gl|ka|de|el|gu|ht|ha|haw|iw|hi|hmn|hu|is|ig|id|ga|it|ja|jw|kn|kk|km|ko|ku|ky|lo|la|lv|lt|lb|mk|mg|ms|ml|mt|mi|mr|mn|my|ne|no|ps|fa|pl|pt|pa|ro|ru|sm|gd|sr|st|sn|sd|si|sk|sl|so|es|su|sw|sv|tg|ta|te|th|tr|uk|ur|uz|vi|cy|xh|yi|yo|zu)$ /$1/ [R=301,L]
### END GTranslate config ###
```
