### ISSUE TITLE
Fatal error when simplexml module missing

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1368]
Some customers get this fatal error when trying to preload: 
`PHP Fatal error: Uncaught Error: Call to undefined function WP_Rocket\Preload\simplexml_load_string() in /var/www/html/wp-content/plugins/wp-rocket/inc/classes/preload/class-sitemap.php:114`

Apparently due to  php-simplexml module not being installed or available on the server. 

Could we check for this, and any other minimum requirements for preloading, and display an admin message instead, to prevent a fatal error?

HS tag: `simplexml_load_string`

**Comment by Tabrisrp** [comment]
Needs copywriting for the notice to be prepared
