### ISSUE TITLE
Rollback from 3.1.4 to 3.0.5.1 doesn't work

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1374]
It re-installs 3.2.2 :(

**Comment by GeekPress** [comment]
I got it too. Not reported as I thought it was an edge case from me. It doesn't seem to be isolated now.

**Comment by ernee** [comment]
Even with 3.2.3-alpha1 update, it still rolls back to this version when trying to roll back from 3.1.4 to 3.0.5.1. Screenshot:

![screen shot 2018-12-06 at 12 32 54 am](https://user-images.githubusercontent.com/8108643/49571576-8e69bf80-f8ee-11e8-9a1e-dd5b37bd6d5f.png)

**Comment by Screenfeed** [comment]
>roll back from **3.1.4** to 3.0.5.1

Read again :D 

What I did is fix this bug in **3.2.3**, so this release and the furure ones won't suffer from this issue.
If we want to patch this in 3.1.4 we must fix... 3.1.4 (and all releases between today and august 2015).
