### ISSUE TITLE
Exclude Hubspot JS from deferred JS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1378]
This has to be excluded: 
//js.hsforms.net/forms/shell.js

**Comment by webtrainingwheels** [comment]
This works :)

I've found there are a few different ways Hubspot can be integrated on a page, this exclusion may not cover all of them. I don't have clear customer feedback on the others yet. 

So for the sake of the changelog, can we reference this as: 
> Exclude embedded Hubspot form from deferred JS
or more specifically: 
> Exclude the following Hubspot file from deferred JS: js.hsforms.net/forms/shell.js

**Comment by Tabrisrp** [comment]
is there a common pattern for the different ways? We could exclude just the domain if it's covering more cases

**Comment by webtrainingwheels** [comment]
I can find a few other cases where it seems that excluding: `js.hsforms.net` should also work, although lacking final customer confirmation. But, probably excluding the domain is the way to go.
