### ISSUE TITLE
Enhancement: Update preload notice with AJAX

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1387]
When preloading is happening we have to refresh the page to see the updated number of pages cached. Would be ideal if this refreshed automatically with AJAX. 

Customer request: https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/46787/conversations/19469904643

**Comment by piotrbak** [comment]
The issue is not relevant with the 3.12 preload implementation
