### ISSUE TITLE
Deferred JS option ignores conditional enqueing

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#139]
Customer has enqueued a script only on one page. He adds that file to deferred JS, but now it's loaded on every page. 
https://secure.helpscout.net/conversation/233861853/19389/?folderId=377611

**Comment by AliceOrru** [comment]
Another customer has a similar problem with the JS files to be included in the footer during the minification process: he says the files are loaded on every page. 
https://secure.helpscout.net/conversation/343323796/37130/?folderId=628132
