### ISSUE TITLE
WP-rocket and woocommerce_items_in_cart issue

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#1394]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When I added product to cart, it was fine. Then I closed the tab then browser. After that, I open the browser and went back to my store, the item in cart was gone. I added other item to cart, then that item came back. I checked the cookies at the first time visit after closing it, there is no woocommerce_items_in_cart. However, when I added other item to cart, I saw it then with 1 item. It’s weird issue. Any advice?

 I disabled WP-rocket and the issue was gone. I tried many times and it’s them same. Something was wrong with wp-rocket.

**To Reproduce**
1. Go to single product page
2. Click on add to cart
3. close the tab and browser
4. open the browser and go back to the store. The item in cart disappears.
5. Go to single product page, add something again, then it comes back with new item.

**Expected behavior**

The existing item in cart should be appeared without issue when customer comes back.

**Comment by Camilo517** [comment]
I tried to reproduce your problem and it works for me correctly @kevin25

**Comment by kevin25** [comment]
Do you have mini cart enabled?

**Comment by Camilo517** [comment]
no

**Comment by Tabrisrp** [comment]
This is happening because we create a cache of the empty cart request, and serve it when the cookies are not set.

If this is an issue for you, you can disable this by using this code:
`add_filter( 'rocket_cache_wc_empty_cart', '__return_false' );

**Comment by kevin25** [comment]
Thank you. I added it to functions.php but it doesn't work out for me.

**Comment by Tabrisrp** [comment]
you should add it in a mu-plugin, or wrap it like below, else it's too late in the loading process:
```
add_action( 'wp_rocket_loaded', function() {
add_filter( 'rocket_cache_wc_empty_cart', '__return_false' );
} );
```
