### ISSUE TITLE
Suggestion - Update "Return to Plugins page" link on Rollback to "WP Rocket settings" page

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1395]
<img width="413" alt="01" src="https://user-images.githubusercontent.com/5751474/49216427-54b72700-f3cb-11e8-9f1d-6d3b5a50d9c9.PNG">

Since rollback is initiated from the Tools tab of WP Rocket, doesn't it make sense to go back to WP Rocket settings page instead of WordPress plugins page?

**Comment by Tabrisrp** [comment]
The rollback page output is generated by WP itself, we don't have control on it as there is no filter available.
