### ISSUE TITLE
Improve Embeds option description mentioning Gutenberg

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#1418]
By default WP Rocket comes with the option "Disable WordPress embeds" enabled.
This prevents Gutenberg Embeds block to work.

Gutenberg Embeds block not working ("Disable WordPress embeds" enabled by default):
![screenshot 2018-12-05 09 24 34](https://user-images.githubusercontent.com/14943244/49500882-0514a780-f872-11e8-9feb-f2a7a7395352.png)

Gutenberg Embeds block working ("Disable WordPress embeds" disabled): 
![screenshot 2018-12-05 09 25 28](https://user-images.githubusercontent.com/14943244/49500923-12ca2d00-f872-11e8-876e-ddf2ebd36713.png)

Can we maybe improve the description of the option, mentioning it has to stay disabled if the user wants to use Gutenberg Embeds blocks?

**Comment by blogjunkie** [comment]
Hi there, I’m the person who first reported this issue (I believe) https://twitter.com/clickwp/status/1070121388281815040?s=21

I’d like to suggest that the setting also be disabled by default. 

And for sites that have upgraded to WP5.0 it might also be useful to display a notice directing the user’s attention to how this affects embeds in Gutenberg.
