### ISSUE TITLE
Add "_ga" GET parameter to query strings served a standard cache

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1420]
Per customer request here: https://secure.helpscout.net/conversation/722636981/88975?folderId=1391600

recommendation to include `_ga` to our list of parameters to receive a standard cache automatically.

**Comment by dries863** [comment]
Since Google Analytics automatically adds this parameter when cross domain tracking is enabled, it would be great to have this GET parameter cached.
