### ISSUE TITLE
Multisite, subsites' excluded pages got cached

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1424]
When WP Rocket is active on the main site (main network site), _exclude pages from being cached_ feature is not working on subsites (excluded pages are being cached).

After deactivating WP-Rocket from the main site, everything is working fine on each subsite.

This is related to below ticket:
https://secure.helpscout.net/conversation/716301944/87882?folderId=2415573#thread-2009772070

Unfortunately, we don't have access to his environment.

**Comment by piotrbak** [comment]
Made some further tests. Blogs are fetching the content of the main site WP Rocket config file instead of their own.

Thanks to Alfonso we have our own Multisite environment where I was able to recreate the problem.

Related ticket:
https://secure.helpscout.net/conversation/845943447/106761?folderId=2415573

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/1285218548/195640/

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1357861344/220215/
