### ISSUE TITLE
SiteGround caching compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1425]
At this moment WP Rockets' compatibility with SiteGround caching is fully dependent on their plugin SG Optimizer.

After the last release of this plugin, SiteGround is giving their users more performance options. They're recommending their customers to [use only one caching plugin](https://www.siteground.com/blog/sg-optimizer-new-version/#comment-426976).

Is there any way we can bypass SG Optimizer with clearing Dynamic Cache and make more compatibilities without the need of using SG Optimizer?

**Comment by arunbasillal** [comment]
In the latest version of SG Optimizer, `$sg_cachepress_environment` is no longer present and this breaks our current compatibility 

https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/3rd-party/hosting/siteground.php#L7
