### ISSUE TITLE
Trying to delete directory that doesn't exist

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1426]
It seems to happen only when Remove Query String feature is enabled in a different plugin (perfmatters in this case). I believe below scenario is happening:

-Perfmatters is removing query string before WP Rocket
-WP Rocket Remove Query Strings option is active
-There's nothing to do for WP Rocket, so /busting/ directory is empty, WP Rocket is not creating 1/ directory
-WP Rocket's option Remove Query String is activated, so WP Rocket is trying to clear directory that doesn't exist

Error received:
RecursiveDirectoryIterator::__construct(/home/s1/html/wp-content/cache/busting/1): failed to open dir: No such file or directory
/wp-content/plugins/wp-rocket/inc/functions/files.php: 454

Maybe we should check if the directory exists before trying to delete it in this case.

Related ticket:
https://secure.helpscout.net/conversation/724258569/89229?folderId=2415573

**Comment by gerfoley** [comment]
I'm seeing a similar error here that I can't figure out yet.

I'm seeing the same error message show up in newrelic when I clear cache and am getting no feedback on admin that cache has cleared

E_WARNING: RecursiveDirectoryIterator::__construct(/var/www/vhosts/mywebsite.com/httpdocs/wp-content/cache/busting/1): failed to open dir: No such file or directory

**Comment by GeekPress** [comment]
Closing it as our « Remove Query String » option will be removed in 3.6
