### ISSUE TITLE
Transaction Manager Pro breaks our settings page

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1428]
Transaction Manager Pro v2.5, by Cloudswipe https://cloudswipe.net/, breaks our settings page due to loading its JavaScript all over the admin. 

In case we want to add to core, this helper removes the offending file from our settings page:
https://jmp.sh/VD7gieO

Plugin doesn't seem to be on the repo, so it's hard to say how many users it has.

**Comment by piotrbak** [comment]
Looks like this was the only feedback since that time. We'll reopen it if the problem is still there
