### ISSUE TITLE
Import settings failed with error: Settings import failed: incorrect filetype

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1430]
Tools tab > export settings, then import the same settings. Got this error.

![import error](https://user-images.githubusercontent.com/5751474/49935052-fa06ea80-fef5-11e8-9322-69b27a43bb17.png)

Recreated both on `3.2.3` and `3.1.4`. [Vasilis got the same](https://wp-media.slack.com/archives/C08N8J6VC/p1544699369019200?thread_ts=1544698554.018800&cid=C08N8J6VC) and [customer reported it as well](https://secure.helpscout.net/conversation/730832086/90166/).

**Comment by Tabrisrp** [comment]
This is caused by the latest WP security update
