### ISSUE TITLE
Be more explicit in our metabox title

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1431]
Shouldn’t we be more explicit in our metabox title and use `WP Rocket Options` instead of `Cache Options`? Or even create a button like Yoast is doing...

![capture d ecran 2018-12-13 a 09 50 12](https://user-images.githubusercontent.com/11939512/49947552-d17cf180-fef1-11e8-9845-e985f005fbe5.png)

**Comment by webtrainingwheels** [comment]
I agree, `WP Rocket Options` would be better. Not sure about adding the button, to be honest. Now that Yoast has started this trend, there's likely going to be button wars in that space and I don't think that's a good thing. Would rather not contribute to that problem. But that's just my personal opinion, obvi ;)

**Comment by Tabrisrp** [comment]
The button is for a different sidebar with Gutenberg, and Yoast has a lot of content to handle in that. We only have one small metabox with checkboxes, so it's not useful for us.

We can update the metabox label in a next update.

**Comment by Tabrisrp** [comment]
Needs to determine/confirm which title we want to use. Current proposition is `WP Rocket Options`
