### ISSUE TITLE
LazyLoad Conflict

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#144]
Based on this ticket: https://secure.helpscout.net/conversation/244799449/21404/?folderId=273766 - When the customer activates the tag from google tag manager plugin or install the code within the html, his images/videos don't show on Safari and mobile devices. He solved it disabling our LazyLoad. But he installed the LazyLoad plugin https://wordpress.org/plugins/lazy-load/ and it works.

**Comment by arunbasillal** [comment]
The ticket suggests that this was a conflict with our LazyLoad and it worked with a different LazyLoad script. 

We do not have enough data to replicate this issue. Our LazyLoad approach has changed few times since 2016 and we have fixed a lot of conflicts. 

Closing this for now.
