### ISSUE TITLE
Message Translation Dashboard Welcome notice

### ISSUE THREAD

**Issue by GeekZebre** [wp-media/wp-rocket#1441]
Two messages are not in French !

The message are : 
 - WP Rocket is now activated and already working for you.	
 - Your website should be loading faster now!

![wp-rocket-traduction-erronee](https://user-images.githubusercontent.com/30160793/50098717-c4773f80-021c-11e9-9daa-5e8130526982.jpg)

There are no msgid in 'po' files.

https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/languages/rocket-fr_FR.po#L2252

https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/languages/rocket-fr_FR.po#L2259

**Comment by WordPresseur** [comment]
@Tabrisrp There's also the ad block notification: https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/languages/rocket-fr_FR.po#L2240

**Comment by Tabrisrp** [comment]
Strings translations will be pulled from transifex before next update.
