### ISSUE TITLE
Facebook for Woocommerce: Deferred JS + Combine JS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1448]
When using Facebook for WooCommerce, you have this code on the page: 
http://snippi.com/s/4tehb2x

With only Combine JS enabled, there's no problem since we make some auto-exclusions. 

However, if you enable both Deferred JS and Combine JS, you'll get this error: 
![mission_control_-_astronaut_training](https://user-images.githubusercontent.com/1043076/50181007-0c9b6e00-02c0-11e9-86bb-04b7d95f47f6.jpg)

In this case we also have to exclude this inline script from being combined:
`<script type='text/javascript'>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
</script>
`

I noticed that when I excluded it with a string entry in the UI, that section of the inline script was loaded at the top of the page, while the second part was loaded in the footer. By default, without any optimization, the whole thing loads at the top. There's no JS error in the console, but not sure if this separation could cause any other issue.

**Comment by Tabrisrp** [comment]
The second part is loaded in the footer because it contains code depending on jQuery, so it's moved after the combined file. The separation should not be an issue as long as the loading order is respected.
