### ISSUE TITLE
Explicit the Sucuri Firewall Alert

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1449]
When the Sucuri Firewall alert is triggered, it can be confusing for customers: from which plugin this alert is coming from? Sucuri?

I suggest being more explicit: 
![capture d ecran 2018-12-19 a 14 09 20](https://user-images.githubusercontent.com/11939512/50222363-52c40080-0398-11e9-8d7c-f10fe5ebd1c8.png)

**Comment by webtrainingwheels** [comment]
Good idea. Let's be consistent with our other notices though. I think we normally just preface them with: **WP Rocket:**
![wp_rocket_notice](https://user-images.githubusercontent.com/1043076/51066737-e87e3480-15c0-11e9-8724-c82b7e61eb6f.jpg)

**Comment by Tabrisrp** [comment]
Needs to determine/confirm how to update the notice

**Comment by ernee** [comment]
**Update notice to:** 

Sucuri Add-on: The API key for the Sucuri firewall must be in format {32 characters}/{32 characters}.
