### ISSUE TITLE
Some strings related to Sucuri Add-on are not translated

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1450]
Label: `Firewall API key (for plugin), must be in format {32 characters}/{32 characters}:`
Alert: `The API key for the Sucuri firewall must be in format {32 characters}/{32 characters}.`

They're missing into https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/languages/rocket-fr_FR.po

![capture d ecran 2018-12-19 a 14 20 53](https://user-images.githubusercontent.com/11939512/50222715-60c65100-0399-11e9-8de6-9350083c8385.png)

2 others:

- https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/languages/rocket-fr_FR.po#L1356

- https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/languages/rocket-fr_FR.po#L1621

**Comment by Tabrisrp** [comment]
String translations will be pulled from transifex before next update.
