### ISSUE TITLE
Media Webp support

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#1458]
It would be good if wp-rocket supports this type of plugins, to be able to use Webp (Other cache plugins already support it)
Wp-rocket should detect when the browser is compatible and load the image in Webp format
Plugin: https://wordpress.org/plugins/media-webp/

A plugin that does this: https://wordpress.org/plugins/cache-enabler/

**Comment by pcfreak30** [comment]
I would look at https://wordpress.org/plugins/webp-express/ which is more powerful I think and supports restricted hosting like wp-rocket does
