### ISSUE TITLE
Database Optimization UX Improvement

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1459]
Since the database optimization uses background processing, it takes a while to complete and the numbers do not update until the page is refreshed. 

I have seen few tickets where customers think that the optimization did nothing and opened tickets for the same. 

**Some suggestions to solve this problem:** 

- Right now we show the message, `Database optimization process is running`. We could make it to, `**WP Rocket:** Database optimization process is running. (refresh to see progress)`

- Alongside the count of database entries, when the process is running, we could add an inline message: `22 spam comments in your database. Optimization is progress`. People might miss the notice, but will not miss this. 

<img width="412" alt="01" src="https://user-images.githubusercontent.com/5751474/79767998-c8066380-8347-11ea-9563-a062bb554ff2.png">

- Add timestamp to the complete message. 

Right now: 

![image](https://user-images.githubusercontent.com/5751474/79768361-4f53d700-8348-11ea-84d7-b9dae52fd59d.png)

Proposed: 

- Add **WP Rocket:** prefix
- Add timestamp
- Remove `List of optimized items below:` (isn't it obvious? Also comes in the way of the timestamp) 

![image](https://user-images.githubusercontent.com/5751474/79774266-3818e780-8350-11ea-9237-2507e50f08f4.png)

**Comment by GeekPress** [comment]
@arunbasillal @webtrainingwheels Could you work together on this to validate a new message?

**Comment by arunbasillal** [comment]
@webtrainingwheels I have updated my original comment with some changes. Would you please review it and let us know what you think?

**Comment by piotrbak** [comment]
Closing it in favor of:
https://github.com/wp-media/wp-rocket/issues/2285
