### ISSUE TITLE
Automatic cache clearance / Preload triggers

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1464]
When we are dealing with active e-commerce sites with many products cache might be cleared way too often.

Let's say we have Woo site with 5000 products and a new user being registered every 10 minutes (less in traffic peaks). We will clear the whole cache every 10 minutes, and don't trigger preload.

Preloading cache doesn't seem to make sense in this case, as we won't be able to preload all pages before next user registration and the server will be under heavy load all the time.

Also, if sitemaps are not placed in the correct order it may happen that we will preload news/pages and don't even start preloading products which are the most important ones.

We could add a section in UI to let users control the automatic clearance of cache.

**Comment by arunbasillal** [comment]
This came up again in #2139 and will be added in 3.5
