### ISSUE TITLE
Implement option to Hide Sucuri Firewall API key in settings 

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1467]
Like Cloudflare, we could implement a way for users to hide their Firewall API key for the Sucuri Add-on.

**Comment by Tabrisrp** [comment]
Will require update for the Sucuri doc to explain how to use the hide/constant system

**Comment by Tabrisrp** [comment]
Looking back at the code we already have everything in place for that.

customers can use this constants in `wp-config.php`:
- `define( 'WP_ROCKET_SUCURI_API_KEY_HIDDEN', true );` to hide the Sucuri API key field
- `define( 'WP_ROCKET_SUCURI_API_KEY', 'API Key value' );` to register the value of the Sucuri API Key
