### ISSUE TITLE
Exclude reCaptcha from being deferred

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1468]
It looks like reCaptcha initialised by CF7 plugin is not always working with Defer JS feature.
https://jmp.sh/IGokckC

Excluding the following pattern resolves the problem:
$excluded_files[] = 'google.com/recaptcha';

Related tickets:
https://secure.helpscout.net/conversation/746633170/91993?folderId=2415573
https://secure.helpscout.net/conversation/735262358/90763?folderId=273766

**Comment by arunbasillal** [comment]
Potentially related - https://secure.helpscout.net/conversation/748815931/92261/
Helper: https://www.dropbox.com/s/ax4je41fupgx0sa/wp-rocket-static-exclude-recaptcha-defer-js.zip?dl=1
