### ISSUE TITLE
Proposal: Detect if CRON is disabled

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1472]
WP Rocket needs CRON for multiple operations. Critical Path CSS generation, Preload, Database optimization etc. 

WP CRON being disabled is a common issue for why these fails. We could try and detect if WP Cron is disabled. 

- The easiest check would be to check the value of `DISABLE_WP_CRON` constant. 
- Incorporate few other tricks from - https://wordpress.org/plugins/wp-cron-status-checker/

## When to detect? 

It doesn't make sense to detect unless the user is trying to use a feature that needs WP Cron. Check for WP Cron when user enables Preload, Critical Path CSS generation, or database optimization

## Thoughts and notes

- The website might have a server CRON setup, so if we display a notice to the customer and should be dismissible. 
- During the check, see if the counter for the preload, or Critical Path CSS generation is already increased. In that case, even if WP CRON is disabled, there is server cron hopefully and the notice is no longer needed.

**Comment by webtrainingwheels** [comment]
+10000

**Comment by arunbasillal** [comment]
@Tabrisrp What design changes does this need? My original suggestion was for an admin notice like we have for incompatible plugins.

**Comment by Tabrisrp** [comment]
Good news is, it's automatically included in WP 5.2 Site Health Check tool, so we don't have to develop our own

**Comment by arunbasillal** [comment]
I still think showing an admin notice would be more effective. Customers are going to enable Preload / Critical Path CSS and say it's not working and write to us. We could piggyback on 5.2's features to do this hopefully. Lets wait till 5.2 is actually here.

**Comment by GeekPress** [comment]
I'm kindly re-open this issue. A notice to warn our users or grey out our options will be helpful

**Comment by arunbasillal** [comment]
Re-opening this issue as discussed in the QA channel. 

**With the 3.3.7 update, here is what we did:** 

- An admin notice is displayed if a scheduled event missed it's schedule time. 
- This will accommodate for WordPress installations that use server cron as well. 
- The notice displayed on WP Rocket dashboard can be dismissed and will not come back once dismissed. 
- This is basically what WordPress health check tool uses as well

**False positives**

At the time of writing, we have 9 false positives reported where customers saw this notice even when cron was working correctly. This could be because of an edge case. 

- Say an event is scheduled for 15:02
- Server cron is set to run every 5 minutes.
- It runs at 15:00
- Customer visits the dashboard at 15:03 and the notice will be displayed because the even scheduled for 15:02 is missed and will only be done at 15:05 when the server cron runs again. 

**Next Steps**

We will continue to monitor tickets about this and make a decision about whether to make changes in a future update.

**Related conversations:**

- https://wp-media.slack.com/archives/C08N8J6VC/p1567075962002300
