### ISSUE TITLE
3.2.4beta-1 : fatal error on incorrect sitemap url

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1473]
Testing for the notice on: `Sitemap(s) URL can’t be reached`
In WP Rocket settings, entered an incorrect sitemap URL which 404s. 
Got this fatal error on launching preload: 
`PHP Catchable fatal error:  Object of class LibXMLError could not be converted to string in /wp-rocket/inc/classes/preload/class-sitemap.php on line 135`

**Comment by Tabrisrp** [comment]
good catch, fixed in 3.2.4-beta2
