### ISSUE TITLE
Exclude SyntaxHighligher files from Deferred JS and Combine JS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1476]
https://wordpress.org/plugins/syntaxhighlighter/

When Deferred JS is active it breaks the display. 

These exclusions work to fix it: 
/syntaxhighlighter2/scripts/(.*).js
/syntaxhighlighter3/scripts/(.*).js

The plugin allows you to choose a version to use, hence 2 or 3 in the path.

Same issue with Combine JS. Exclude: 
/wp-content/plugins/syntaxhighlighter/syntaxhighlighter3/scripts/(.*).js
/wp-content/plugins/syntaxhighlighter/syntaxhighlighter2/scripts/(.*).js

**Comment by ciorici** [comment]
I don't think this solution works anymore.

Getting an error:

```
Uncaught ReferenceError: SyntaxHighlighter is not defined
    at disable-comments-wordpress/:757:2
```

**WP Rocket: Version 3.16.4**
