### ISSUE TITLE
Allow changing Varnish Purge method

### ISSUE THREAD

**Issue by Rahe** [wp-media/wp-rocket#1478]
**Is your feature request related to a problem? Please describe.**
Hello,

I'd like to change the Varnish Purge Method to something else.
Most of the time I have BAN method and not PURGE.

**Describe the solution you'd like**
Add a filter to the wp_remote_request to change any parameter.

**Describe alternatives you've considered**
Currently I'm adding a mu-plugin replaying exactly the same request but with the BAN word.

**Comment by arunbasillal** [comment]
@Rahe This will be part of upcoming WP Rocket 3.5. Once you have it, the following filter should help you change the method to `BAN`

```
/**
 * Modify Varnish purge request from PURGE to BAN
 * 
 * @param $args array Array of arguments for the request.
 */
function mysite_wp_rocket_modify_varnish_purge_method ( $args ) {
	
	$args[ 'method' ] = 'BAN';
	
	return $args; 
}
add_filter( 'rocket_varnish_purge_request_args', 'mysite_wp_rocket_modify_varnish_purge_method' );
```

**Comment by Rahe** [comment]
Hello,

Great ! thank you :)

Nicolas
