### ISSUE TITLE
License Validation - Rename "Save Settings" to "Validate License"

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1479]
Currently when license validation fails this is one of the user flow

- Sees the validation failed message
- Checks our documentation and does what they can. Lets say they whitelisted our IP
- Goes back to the WP Rocket settings page to see if it worked. 
- They should click `Save Changes`, but not everyone does this step
- In fact our documentation doesn't say to "Save Changes" - https://docs.wp-rocket.me/article/100-resolving-problems-with-license-validation

## Proposal 

- We could automate this by trying to validate the license each time the settings page loads. 
- Of course, this happens only when the license isn't validated yet. 

## Back Story

- In SuperPWA, sometimes [file generation fails](https://superpwa.com/wp-content/uploads/2018/05/manifest-and-service-worker-generation-failed-1.8.png) when WordPress cannot write to the root folder. 
- After adjusting server write permissions, users had to deactivate and reactivate plugin (or change a setting and save) to regenerate the files. 
- Even with documentation, because not everyone reads it fully, users complained that file generation failed.
- Added an attempt to generate the file each time the UI was loaded (and file could not be read) and this resolved the issue forever.

**Comment by webtrainingwheels** [comment]
Another use-case for this. Now that we're showing notices with validation messages - they will only update when Save has been clicked again.

e.g. While testing I added this to wp-config: 
`define( 'WP_HTTP_BLOCK_EXTERNAL', true );`
But even after removing it, I still get this error notice showing: 

![error_notice_not_updated](https://user-images.githubusercontent.com/1043076/51564482-470aa480-1e44-11e9-9aa4-ebf8c4225e60.jpg)

That's even after deactivating / reactivating WP Rocket. 

I have to click Save to clear it and I think that won't be intuitive for most people.

**Comment by webtrainingwheels** [comment]
There is no need to have a "Save Changes" button on this screen at all since the fields are not editable. 
It should either say "Re-try validation" or be removed.

**Comment by GeekPress** [comment]
Doing a check each time someone will load our Settings page, even if it's done only for unvalidated license, could have a signifiant impact on our website / server. We will increase the number of tests.

What Lucy suggested to rename the button could be a first iteration to fix the problem.

**Comment by arunbasillal** [comment]
It's a minor difference, user has to do one more click, so let's go with the suggestion from Jonathan and rename the button. 

@webtrainingwheels How about we just name the button: `Validate License`? It will be intuitive enough I think. Retry validation would look less nicer in my head.

**Comment by webtrainingwheels** [comment]
@arunbasillal `Validate License` sounds good to me!
