### ISSUE TITLE
UX - Indicator or spinning wheel for Safe Mode 

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1484]
When the "Apply Safe Mode" button is clicked, there is no feedback. 

https://jmp.sh/huO2EnK

Usually it takes only a moment, but just now on a website it took a while. 

This is trivial for sure. But a user is about to deactivate WP Rocket and the user is already frustrated. Adding a spinner might make sure that the frustration doesn't go up.

**Comment by piotrbak** [comment]
The UI has changed since then.
