### ISSUE TITLE
widget_update_callback and Elementor - Cache cleared on every page load

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1485]
We have been seeing some issues lately where cache was being cleared on every page load because of calling `rocket_clean_domain()` via the `widget_update_callback` filter. 

@webtrainingwheels [observed](https://secure.helpscout.net/conversation/746685551/92001?folderId=1724284#thread-2089002539) that all reported cases used `Elementor`. 

I just tested this on a staging site and found it to be true. 

Elementor uses the filter: 
https://github.com/pojome/elementor/blob/73a598fb0dc7c97322ce351d71fdf8db2597e319/includes/widgets/wordpress.php#L207

Elementor Issue: https://github.com/pojome/elementor/issues/5844

HS tag: [widget_update_callback](https://secure.helpscout.net/search/?query=tag:widget_update_callback)

Helper plugin to fix - https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-no-cache-purge-widget-update

**Comment by webtrainingwheels** [comment]
Just another observation - this can be a really bad combo when Autoptimize is active too. AO listens for cache clearing and it can result in server overload. Similar to: https://github.com/futtta/autoptimize/issues/195

**Comment by Tabrisrp** [comment]
Removing the action on `widget_update_callback` if Elementor is active seems to be the most straightforward solution. Do you see any other one?

**Comment by arunbasillal** [comment]
Can't think of anything better either and that seems to have the least impact overall. 👍
