### ISSUE TITLE
rocket_clean_user() does not clear the cache on a multisite

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1486]
On a multisite, the `rocket_clean_user()` function doesn't clear the cache of a user on a subsite.

The  `$user_key` here:
https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/functions/files.php#L863

is different than the one used to create the logged in user's cache folder here:
https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/front/process.php#L296

The first is created using the`secret_cache_key` from the subsite's _example.com.subsite.php_ file while the second one is created using the`secret_cache_key` from  _example.com.php_.

This results in trying to delete the contents of a non-existing path. Consequently the user's cache is not deleted.

**Related Ticket:**
https://secure.helpscout.net/conversation/753451337/92877?folderId=2135277

**Comment by Tabrisrp** [comment]
The issue happens if/because the the config file for the main site exists, so it is used in priority during the loading in `process.php`. The logic should be reversed, and use the more specific config file if it exists, fallback to the main site config file if needed.

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1313782969/203771

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
