### ISSUE TITLE
Empty Cart notice is cached when having multiple languages with WPML

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1487]
When a site has multiple languages the `get_refreshed_fragment` **empty cart notice** is saved in the transient and the language that it's displayed in, won't change when changing languages. 

I've tested this with WPML but most likely the same thing stands for other translation plugins.

![Screenshot](https://vgy.me/TYEguC.jpg)
Full-scale image: https://vgy.me/TYEguC.jpg

**To reproduce:**

1. Clear cache in all languages and visit one of them so the transient will be created.
2. Visit a page to see the empty cart notice.
3. Change language. The notice should be displayed in the language that was set during the first visit to the page.

Installing the [Deactivate WooCommerce Refresh Cart Fragments Cache plugin](https://github.com/wp-media/wp-rocket-helpers/raw/master/compatibility/wp-rocket-compat-wc-cart-fragments/wp-rocket-compat-wc-cart-fragments.zip)  resolves the issue.

**Proposed Solution:**
 Create and serve a different transient per language.

**Related Ticket:**
https://secure.helpscout.net/conversation/755968859/93247?folderId=2135277

**Comment by arunbasillal** [comment]
I had something related today as well. `WPML and Multicurrency`

When empty cart is cached, the currency does not update when switching languages. 

Related ticket - https://secure.helpscout.net/conversation/735719145/90811?folderId=1724284#thread-2114922972
