### ISSUE TITLE
On cURL error 60, provide UI option to set sslverify to false

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1490]
This is what a sample cURL error 60 looks like: 

`cURL error 60: SSL certificate problem: self signed certificate`

<img width="828" alt="01" src="https://user-images.githubusercontent.com/5751474/51673156-44f14300-2008-11e9-9030-ca2c30198fa4.png">

When this happens, if the customer contacts us, the solution we offer is to set the filter `https_local_ssl_verify` to false. 

As per this doc: https://codex.wordpress.org/HTTP_API#Other_Arguments

```
The 'sslverify' argument was added in Version 2.8 and will check to see if the SSL certificate is valid (not self-signed, actually for the site in the request) and will deny the response if it isn't. If you are requesting HTTPS and know that the site is self-signed or is invalid and are reasonably sure that it can be trusted, then set to false.\
```

- Since almost all of our requests are to sitemaps and self links, setting it to false shouldn't be an issue right? 
- This is what we suggest if they contact support anyways. 

Proposed solution: 

- Along with the notice show a button with which the user can set `sslverify` to false. 
- Restart the preload process (or whatever process that caused the notice).

**Comment by arunbasillal** [comment]
Another related idea: 

- When something fails with `sslverify` as `true`, try it with `sslverify` as false. 
- If the test is successful, then ask the user for action. 
- (Maybe link to a doc to let him know whats happening)
- If user takes action, set `sslverify` as false and move on.

**Comment by Tabrisrp** [comment]
Points to discuss:

- When do we perform the test?
- How do we offer the possibility for the  customers to adjust that value?
- How do we offer the possibility to switch back and forth if needed?
