### ISSUE TITLE
Purge the files cache with the "Purge OPcache" function

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1491]
Currently, we use the `opcache_reset()` to clear the OPCache in memory.

We could implement a binary files deletion for that particular feature.

**Related Ticket:**
https://secure.helpscout.net/conversation/761321134/94021?folderId=2135277

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1472389207/252767

**Comment by alfonso100** [comment]
**related ticket:** https://secure.helpscout.net/conversation/1652534370/299624

**Comment by piotrbak** [comment]
Related:
https://github.com/wp-media/wp-rocket/issues/2950
