### ISSUE TITLE
Minify_CSS_UriRewriter removed yet still in use

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#1494]
The latest release deleted the file `inc/vendors/classes/class-minify-css-urirewriter.php` and using https://github.com/matthiasmullie/path-converter instead.

However... there are two references still for the class.  https://github.com/wp-media/wp-rocket/blob/branch-3.2.4/inc/deprecated/deprecated.php#L2889 and https://github.com/wp-media/wp-rocket/blob/branch-3.2.4/inc/functions/files.php#L1234. This could mean a fatal if these code paths are ran.

**Comment by vmanthos** [comment]
**Related ticket:**
https://secure.helpscout.net/conversation/767014089/94807/

**Comment by sabrina-zeidan** [comment]
**Related ticket:**
https://secure.helpscout.net/conversation/767262231/94847

**Comment by vmanthos** [comment]
I've tested this on 3.2.5-beta1 and I got a **PHP fatal error**:
```
PHP Fatal error:  Uncaught Error: Class 'Minify_CSS_UriRewriter' not found in /home3/example/public_html/DEV/rocket/wp-content/mu-plugins/qatest.php:53
Stack trace:
#0 /home3/example/public_html/DEV/rocket/wp-settings.php(277): include_once()
#1 /home3/example/public_html/DEV/rocket/wp-config.php(93): require_once('/home3/example...')
#2 /home3/example/public_html/DEV/rocket/wp-load.php(37): require_once('/home3/example...')
#3 /home3/example/public_html/DEV/rocket/wp-admin/admin-ajax.php(22): require_once('/home3/example...')
#4 {main}
  thrown in /home3/example/public_html/DEV/rocket/wp-content/mu-plugins/qatest.php on line 53
```
