### ISSUE TITLE
Logic to get cache root in get_rocket_htaccess_mod_rewrite() seems incorrect. 

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1495]
The haystack and the needle seems to be revered here - https://github.com/wp-media/wp-rocket/blob/c92efa3a52ef285eb6230a04ac4c5e6d4e2f8e26/inc/functions/htaccess.php#L187

syntax for [strpos](http://php.net/manual/en/function.strpos.php): `strpos ( string $haystack , mixed $needle [, int $offset = 0 ] ) : int`

`WP_ROCKET_CACHE_PATH` ([when evaluated](https://github.com/wp-media/wp-rocket/blob/c92efa3a52ef285eb6230a04ac4c5e6d4e2f8e26/wp-rocket.php#L59-L62)) = `ABSPATH/wp-content/cache/wp-rocket/`

So in the current order, the `needle` is always bigger than the `haystack`, so it will ALWAYS be `false`. 

I tried it by swapping the values in our mega site. Here is the diff (original on the left, new on the right) - https://www.diffchecker.com/VhDkRQIX

Related ticket - https://secure.helpscout.net/conversation/763704797/94315/

**Comment by arunbasillal** [comment]
Update: customer switched the position of `WP_ROCKET_CACHE_PATH ` and `ABSPATH` and things were good. 

In many setup's `$_SERVER['DOCUMENT_ROOT']` and `ABSPATH` would be the same. But Google wisdom suggest that it need not be.

**Comment by ozmodiar** [comment]
This issue was actually quite breaking for us. I've created a pull-request with the fix and more information about our specific case in the description.
