### ISSUE TITLE
Compatibility with Plesk

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1511]
Opening an issue so that we can learn and explore how we can be auto-compatible with Plesk. 

What we know so far:

- `$_GET` is not empty even when there are no query strings.
- Since pages with query strings are not cached, WP Rocket does not serve the cache. 
- A minor config update in Plesk can fix this - available here: https://secure.helpscout.net/settings/saved-replies/26583/

HS tags: `plesk`, `plesk onyx`

**Comment by Camilo517** [comment]
Could you share here the improvement that needs to be done in plesk to test? Thanks @arunbasillal

**Comment by movergan** [comment]
Guys, could you please share clear steps to reproduce it on Plesk Server?
Please specify:
Plesk Version
OS
The website configuration (Apache/Nginx/php-version and mode)
WordPress version
Steps to verify that cache is not working (step by step guide with examples if possible)
A trial key for the plugin. 

I can try to take a look when I have a bit of free time.

**Comment by GeekPress** [comment]
@arunbasillal Do you know how to replicate the issue?

**Comment by Camilo517** [comment]
@GeekPress Hello, can you share the improvement that needs to be made in plesk to see the problem? so I can help

**Comment by GeekPress** [comment]
> @GeekPress Hello, can you share the improvement that needs to be made in plesk to see the problem? so I can help

I personally have no idea ;)

**Comment by webtrainingwheels** [comment]
This is what was reported to us by the customer: 
==
We have Plesk Onyx installed on the server and it seems that there is a problem with their suggested nginx configuration file for wordpress. On their official website they suggest to put such code to nginx directives:
```
if (!-e $request_filename) {
set $test P;
}
if ($uri !~ ^/(plesk-stat|webstat|webstat-ssl|ftpstat|anon_ftpstat|awstats-icon|internal-nginx-static-location)) {
set $test "${test}C";
}
if ($test = PC) {
rewrite ^/(.*)$ /index.php?$1;
}
```
This code works (permalinks are OK) but it seems that it breaks the WP Rocket caching mechanism that You described. So, we used different directives from another source:
https://gist.github.com/VirtuBox/a8781a7cf53a9a72447cac5acec11b1c

```
if (!-e $request_filename){
rewrite ^(.*)$ /index.php break;
}
```

**Comment by Camilo517** [comment]
This should be shown when using wp rocket + plesk, in my case it wasn't shown, in the google sitekit web if I see that it shows
![Screenshot_4](https://user-images.githubusercontent.com/43606394/82106077-2ba16800-971f-11ea-950c-bf0a22d38651.png)

**Comment by webtrainingwheels** [comment]
@Camilo517 Are you referring to GZIP compression? That is unrelated to this Issue. Please open a support ticket if you need help with that (although it's probably not related to WPR, and more related to your Plesk config and you need to enable compression there). This thread is not to help with that particular issue.

**Comment by arunbasillal** [comment]
> @arunbasillal Do you know how to replicate the issue?

@GeekPress These happened on customers who were on Plesk Onyx based on our ticket history. Only homepage was cached and the inner pages were not. 

@movergan Hello Alex, thanks for your offer to take a look. Here is what we know so far and the cause.  

- In all the cases that were reported, the global variable `$_GET` contained the `path` of the url. 
- For example, if the url was `domain.com/sample-page/` the `$_GET` array will look like: 
```
$_GET = Array
(
[sample-page/] =>
)
```
- WP Rocket by design [does not cache pages](https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/Buffer/class-tests.php#L118) with a query string. (example if the url is `domain.com/?query=1`
- When the array isn't empty, this is exactly what it looks like to WP Rocket. And thus cache isn't served. 

Do you know why the `path` is added to the `$_GET` variable on Plesk?

**Comment by Camilo517** [comment]
Have you tried in plesk obsidian?

**Comment by GeekPress** [comment]
@wp-media/qa Could you plan a test to be able to reproduce the issue? Do we have a test account on Plesk?

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/1258616326/188413?folderId=3864740

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1271451821/191700?folderId=2135277

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1306610438/201629

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1334513895/210829/

**Comment by Camilo517** [comment]
Can I help with this?
I can give you access to a website with Plesk if you need it

**Comment by NataliaDrause** [comment]
Looks like related: https://secure.helpscout.net/conversation/1392306436/230194?folderId=3864740

**Comment by camilamadronero-zz** [comment]
New issue https://secure.helpscout.net/conversation/1665530712/301926/ (NGINX, not Plesk)

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1780475154/324697?folderId=2135277

**Comment by joejoe04** [comment]
Possibly related: https://secure.helpscout.net/conversation/1949978825/356080

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/2015904468/370037/
