### ISSUE TITLE
Support for PixelYourSite for our Facebook Pixel Add-on

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1513]
From a customer: The Facebook Pixel add-on does not support the PixelYourSite plugin.

Related ticket:
https://secure.helpscout.net/conversation/768453798/0/?folderId=273761

**Comment by webtrainingwheels** [comment]
see HS tag: `pixel your site` for further requests

**Comment by adinaWP** [comment]
2 more requests arrived in the past month: 
https://secure.helpscout.net/conversation/1286339284/196003/
https://secure.helpscout.net/conversation/1313321547/203608/
_Note: it has It has 100k installs_

**Comment by GeekPress** [comment]
Closing this issue as Facebook Pixels add-on will be removed in WP Rocket 3.9
