### ISSUE TITLE
Combined CSS added multiple times when <title>is included more than once

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1514]
Normally, one pair of `<title></title>` tags should exist in the `head` block of a page:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title

If, for any reason, there are more, WP Rocket adds the combined CSS file multiple times because of how this is implemented here:
https://github.com/wp-media/wp-rocket/blob/c92efa3a52ef285eb6230a04ac4c5e6d4e2f8e26/inc/classes/optimization/CSS/class-combine.php#L115

Maybe it would be best to use a RegEx to find the `<title>` tag.
This can also have a check, about the `<title>`  tag not being there, that will print a warning in the Dashboard, making it easier to troubleshoot CSS combination related issues.

**Related Ticket:**
https://secure.helpscout.net/conversation/768028020/94982?folderId=2135277

**Comment by webtrainingwheels** [comment]
I also had a case of this a whiles back: https://secure.helpscout.net/conversation/663487180/80084/?folderId=273766

**Comment by vmanthos** [comment]
**Related Ticket:**

https://secure.helpscout.net/conversation/784365624/97673?folderId=2135277

**Comment by GeekPress** [comment]
Another case with this website => https://www.samanage.com/

**Comment by GeekPress** [comment]
A preg_replace only on the first occurence will fix the issue

**Comment by GeekPress** [comment]
Another website => https://ferryheijnen.nl/
