### ISSUE TITLE
Replace YouTube iframe by Thumbnail breaks Matomo analytics media tracking

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1515]
Message from the customer:

I have started doing my web analytics with Matomo. For media tracking, I add the code "enablejsapi=1" to every video URL. With the use of WP Rocket, I cannot track video anymore. 

I suggested him to try a3 LazyLoad plugin to know if he will also have the problem. He confirmed me that it works well with a3 LazyLoad. The issue seems to be on our side.

**Related ticket:**
https://secure.helpscout.net/conversation/768510251/95063/

**Comment by Tabrisrp** [comment]
Was it lazyload iframe only, or also with the youtube thumbnail option?

**Comment by GeekPress** [comment]
Oups, I never replied :D 

The customer confirmed the issue was related to « Replace YouTube iframe by Thumbnail ».

Could we avoid to apply this option if we detect the `enablejsapi` attribute?

**Comment by Tabrisrp** [comment]
We _could_, best thing would be to do some testing ourselves to see what is the best solution in this case

**Comment by Tabrisrp** [comment]
Reproduce the issue ❌
I tested this with a Youtube video on my local. Here is the HTML generated by the `Replace Youtube iframe by thumbnail preview` option:

```
<div class="rll-youtube-player" data-src="https://www.youtube.com/embed/YPj_4m2Do0k" data-id="YPj_4m2Do0k" data-query="enablejsapi=1"></div>
<noscript><iframe src="https://www.youtube.com/embed/YPj_4m2Do0k?enablejsapi=1" allowfullscreen="" width="560" height="315"></iframe></noscript>
```

And after clicking on the thumbnail, the HTML for the iframe:

`<iframe src="https://www.youtube.com/embed/YPj_4m2Do0k?autoplay=1&amp;enablejsapi=1" allowfullscreen="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" frameborder="0"></iframe>`

As we can see, the attribute `enablejsapi` was correctly preserved by the option.

**Comment by piotrbak** [comment]
We were not able to reproduce this one and there's a similat 2757 issue opened. We'll keep another one opened since it has steps to reproduce.
