### ISSUE TITLE
Elementor's External File CSS print method prevents changes from showing without manually clearing the cache

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1516]
The Elementor page builder has two methods to save changes to the styling of a post/page:

- External File (Default)
- Internal Embedding

![](https://vgy.me/80M7xt.jpg)

When the **External File** CSS print method is selected, every change of the styling in a post/page is saved to an external file, like this:
`/wp-content/uploads/elementor/css/post-1414.css?ver=1549378921`

Every change/update cycle will change the version of the file:
`/wp-content/uploads/elementor/css/post-1414.css?ver=1549379082`

Updating the post/page clears its cache, but the HTML references the same WP Rocket-created CSS file, which doesn't include the applied changes. Those will become visible when the cache is cleared manually.

A temp workaround is to enable the `Internal Embedding`.

**Related Ticket:**
https://secure.helpscout.net/conversation/769483145/95221?folderId=2135277

**Comment by Tabrisrp** [comment]
Is there a hook available in Elementor when they update the CSS, on which we could hook on our clear of the minified files?

**Comment by vmanthos** [comment]
They have this part to enqueue the created CSS files:
https://github.com/elementor/elementor/blob/97c873bfe9bfe8d2a7066ab88ffab66179df45ee/core/files/css/base.php#L169-L249

This could be useful to hook on:
https://github.com/elementor/elementor/blob/97c873bfe9bfe8d2a7066ab88ffab66179df45ee/core/files/css/base.php#L248

**Comment by nicomollet** [comment]
@Tabrisrp 
I came here to say with my WP Rocket 3.3.7, I still have the problem.

Reproduce:
1. Elementor 2.6.8 + Elementor Pro 2.6.5 + WP Rocket 3.3.7
2. Enable CSS combine+minify in WP Rocket
3. Select CSS print method "External file" in Elementor
3. My homepage has an Elementor slider.
4. Add a slide (with background image) to the slider
5. Purge cache of homepage 
6. Anonymous user can see the new slide content but not the slide background image
7. Empty all caches
8. Anonymous now can see the background image

Thank you

**Comment by phillycodehound** [comment]
So this isn't solvable other than doing internal embedding for the time being. Man that sucks!!!!

**Comment by kuczys** [comment]
The same problem with Elementor a Hummingbird.
