### ISSUE TITLE
Use the configured WP Filesystem object

### ISSUE THREAD

**Issue by KrisShannon** [wp-media/wp-rocket#1518]
**Is your feature request related to a problem? Please describe.**

We host our WordPress installs under a setup where the FTP Filesystem has to be used to update files.  

This means WP_Rocket can't update .htaccess etc

**Describe the solution you'd like**

Stop forcing the use of WP_Filesystem_Direct where possible.

It should be possible to use the configured `$wp_filesystem` global in most backend pages.

**Comment by KrisShannon** [comment]
Looking through the source it appears that the `rocket_direct_filesystem()` function was created in the commit f668cb5f23d0f08737c7fe5636a68bbc1e1ef5ba (First pass with new PHP CS rules)

I assume these rules are something from WordPress core or WP best practices.

If so,  then switching `@unlink()` to `rocket_direct_filesystem()->delete()` and `is_writable()` to `rocket_direct_filesystem()->is_writable()` sort of misses the point of the rule.

**Comment by Tabrisrp** [comment]
Yes not depending on `WP_Filesystem_Direct` only is something we want to do, that has not been prioritized yet because the setups not supporting it are few in our customers base.

It's good to have an issue filed here to keep track of it.

**Comment by hellofromtonya** [comment]
This issue will need R&D and extensive testing to determine if all of Rocket's functionality works as expected and is reliable and stable with any of the `WP_Filesystem_*` types.

**Comment by piotrbak** [comment]
@Tabrisrp @MathieuLamiot Do you feel this is still something that could add any value to the product?

**Comment by remyperona** [comment]
It's something valid for WP Rocket and Imagify, maybe as part of a library or launchpad

**Comment by CrochetFeve0251** [comment]
This is indeed something we could add to Launchpad and maybe to the [`filesystem` library](https://github.com/wp-launchpad/filesystem) to provide more value to it.

But adding that functionality also comes with its own set of questions to answer first:
- Should we create a new class, or should we extend from the existing one to keep backward compatibility and make it easier to introduce it inside the wpr codebase but would be tricker to handle?
- How do we let users change the filesystem? By using a filter?
- How the testing library will interact with this file system implementation?

For that reason I think we should try to scope the needs first by maybe trying to investigate how the file system is used each repo and find out the main constraints.

**Comment by MathieuLamiot** [comment]
This is indeed an interesting discussion to have, in the context of Launchpad. So I suggest @CrochetFeve0251 you "move" this issue to Launchpad, listing the information and steps you highlighted here, to keep track. 
In the meantime, if this is not an implementation we plan in the upcoming months, Product team can close this issue in WP Rocket repo.

**Comment by CrochetFeve0251** [comment]
@MathieuLamiot the related issue is created on Launchpad I will close this one.
