### ISSUE TITLE
rocket_clean_domain() doesn't clear the cache of subsites when domain mapping is used

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1519]
On a multisite using domain mapping (WPMU Dev plugin), the cache of the mapped subsites is not cleared.

The main site is _example.com_ and the subsite is _subsite.com_. The _example.com/subsite_ is mapped to _subsite.com_.

When triggering cache clearing for the subsite the following folder should be cleared:
`/wp-content/cache/wp-rocket/subsite.com`

Instead, WP Rocket tries to clear this:
`/wp-content/cache/wp-rocket/example.com/subsite`.

So, in this line:
https://github.com/wp-media/wp-rocket/blob/c92efa3a52ef285eb6230a04ac4c5e6d4e2f8e26/inc/functions/files.php#L736

the `$file['host'] == example.com` instead of  `$file['host'] == subsite.com` and `$file['path'] == subsite` instead of the actual file path.

**Related Ticket:**
https://secure.helpscout.net/conversation/772209960/95688/

**Comment by Tabrisrp** [comment]
As a reference, this is supposed to be handled here https://github.com/wp-media/wp-rocket/blob/master/inc/domain-mapping.php#L30

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
