### ISSUE TITLE
Manually applied LazyLoad doesn't work for logged-in users

### ISSUE THREAD

**Issue by blogtutor** [wp-media/wp-rocket#1520]
I followed [the directions here](https://docs.wp-rocket.me/article/130-manually-apply-lazyload-to-an-image) to manually apply LazyLoad to the HTML of an image tag (Option A), adding the code to footer.php:

`<img src="data:image/gif;base64,R0lGODdhAQABAPAAAP///wAAACwAAAAAAQABAEACAkQBADs=" data-lazy-src="http://example.com/image.jpg" alt="" width="600" height="400" />`

We have LazyLoad Images enabled in WP Rocket, and WP Rocket is configured _not_ to cache pages for logged-in users.

I found that when logged out, the lazy loading worked just fine.  But when logged in, the placeholder blank space would be shown, and the image itself would never load into place.

So I had to switch to "Option B" in the above-linked instructions, which was significantly more complicated to implement, of course.

I get why this is happening -- because WP Rocket isn't lazy loading anything else on the page, either (since it's not optimizing/caching for logged in users).   However, this makes "hardcoding" the lazy loading into the HTML tag a non-option. 

It would be nice if the hardcoded "Option A" could still be processed/lazy loaded when the feature is enabled in WP Rocket, even if the user is logged in.

**Comment by Tabrisrp** [comment]
Currently if you want lazyloaded for both logged-out and logged-in users, I would recommend to use our standalone plugin: https://wordpress.org/plugins/rocket-lazy-load/

As an additional benefit, it's also incorporating new improvements before they are added to WP Rocket.
