### ISSUE TITLE
Proposal: Purge Cloudflare cache automatically

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1521]
For customers that use the Cache Everything feature in Cloudflare (i.e. they are caching the HTML) we could automatically purge that cache along with ours according to our usual triggers. 

Currently customers have to manually purge that cache when updating content.

Not sure if it's possible to automatically detect the cache everything setting when our Cloudflare integration is connected, but if not, it could be an option in the add-on UI.

**Comment by ScottTravisHartley** [comment]
I want to add some input to this recommendation as well in theory users can cache via the workers API as well which would then not register at all in the API (this is how I do it) that being said I pass back custom headers to auto-purge the cache system in the event of a post/page being updated. But this is something to keep in mind. 

You could do what the CloudFlare plugin does and add an additional option for "automatic cache management" which I believe they have it set up to simply purge the entire cache if a post/page/theme/etc is updated.

**Comment by alriksson** [comment]
@webtrainingwheels @Tabrisrp  

This is not good if the user use workers KV. Which only flush the html and the page which is modified. Right now you would flush all my files in the edge. Such as static assets and html for other pages and pops.

This would affect the FCP, TTFB and rendering consider you remove all cace in the pops. Which takes time to warm up in cloudflares all 200 pops if you have a global audience on a mid size website.

Please add an option to disable auto-purge. This is handle by the worker and helper plugin itself once using workers KV.
