### ISSUE TITLE
Proposal: Automatically adjust the cURL timeout to resolve the cURL error 28

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1522]
Sometimes preload fails due to a `cURL error 28`, which isn't WP Rocket's fault.

We can avoid that by dynamically setting the `wp_remote_get` timeout value.

This can be set:
- on WP Rocket's installation and
- if a `cURL error 28` is detected during the preload process.

As @arunbasillal proposed, we can also check with `sslverify` set as false.

**Comment by Tabrisrp** [comment]
Points to discuss:

- When do we test the response time for the URL?
- Response time for Homepage and sitemaps can be different, how do we manage this?
- How do we offer the possiblity for the customers to change the timeout value?
- How do we offer the possibility to adjust the value?
