### ISSUE TITLE
Wildcards do not work in Always Purge URL(s)

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1523]
Here is a video recording of the issue: https://www.youtube.com/watch?v=h-uebLmqE38

To recreate: 

- Add `/category/(.*)` to Always Purge URL(s)
- Add any other non-wildcard-ed URL to the list (eg: `/sample-page/`)
- Clear the cache of a page or post
- Make sure preload is turned off
- The cache for `sample-page`is cleared but the `category` is not

Reproduced both on local and mega test site. 

Related ticket: https://secure.helpscout.net/conversation/772518070/95724?folderId=1724284
@vmanthos tested this with mixed results - https://wp-media.slack.com/archives/C08N8J6VC/p1549542729626300

**Comment by Tabrisrp** [comment]
What's the content of the config file?

**Comment by arunbasillal** [comment]
@Tabrisrp Here is the one of the mega site where it failed - http://snippi.com/raw/qr8rrkn

**Comment by vmanthos** [comment]
@Tabrisrp Here is the content of the config file:
http://snippi.com/raw/rqzrl50

**Comment by Tabrisrp** [comment]
`/category/(.*)` is not in the variable containing the excluded URLs

**Comment by arunbasillal** [comment]
@Tabrisrp I am confused. You are talking about `$rocket_cache_reject_uri` right? Should be page be in it for it to be purged? I am talking about `Always Purge URL(s)`

**Comment by Tabrisrp** [comment]
My bad my mind was set on the exclusion URLs, I don't know why

**Comment by Tabrisrp** [comment]
@arunbasillal @GeekPress 

Re-reading that, wildcards has been used for exclusions, but not for this field.

I don't know why `Use (.*) wildcards to address multiple URLs under a given path.` was added under this field, but it **never** has worked.

Introducing this would also require an important change in the purge process to be compatible with regular expressions. Do we want to go that way?

**Comment by GeekPress** [comment]
@Tabrisrp Which regex are actually working for exclusion?

**Comment by Tabrisrp** [comment]
`(.*)` is the only regEx pattern working for exclusions currently.

RegEx never worked for `Always purge URL(s)` field though. The code is expecting standard paths.

**Comment by GeekPress** [comment]
Ok, thanks for the confirmation. 

I will go for a fix as it's an expectation since we specified it's possible to do.

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
This was never working: RegEx never worked for Always purge URL(s) field though. The code is expecting standard paths.

**Scope a solution** ✅ 
I made some prototyping / discovery work and this code should work just fine:
```
function get_recursive_dir_files_by_regex( $dir, $regex ) {
	try {
		$iterator = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator( $dir )
		);
		return new RegexIterator( $iterator, $regex,  RecursiveRegexIterator::GET_MATCH);
	} catch ( Exception $e ) {
		return [];
	}
}
$files = get_recursive_dir_files_by_regex( WP_CONTENT_DIR . '/cache/wp-rocket/wp.local/' , '/category\/(.*)\/sub-category\/(.*)/i');

foreach ($files as $file) {
	print_r( $file );
}
```

**Effort** ✅ 
I would assume this will be an [S].

**Comment by crystinutzaa** [comment]
@Davidacu this one is ready for QA
