### ISSUE TITLE
Add Brotli rules to htaccess

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#1524]
Brotli is a new compression algorithm that performs better than gzip to compress static assets.

It is now well supported in all major browsers: https://caniuse.com/#search=brotli

This means we can add a rules block to add support for it in the htaccess, which will result in a performance improvement for websites using Apache server.

We will keep the current deflate rules as a fallback for servers without `mod_brotli` or for older browsers.

**Comment by arunbasillal** [comment]
Remy did some initial R&D and noticed that the performance boost from dynamic Brotli compression was not very efficient. Ideally we need to generate Brotli compressed files. 

More R&D is needed on this one.

**Comment by shaneonabike** [comment]
We really like the quality of WP Rocket and it's ability to produce good results. I think that the element missing is Brotli. Google PageInsights detects if you have it, and any website that I use that allows for Brotli I can see a significant performance improvement. This was researched over a year ago, but there are clearly advancements and I don't imagine implementing this would be that much more difficult than what is done to compress you just need to provide the bz file.

**Comment by alexincore** [comment]
Any progress on this? there's a pretty straightforward extension available https://github.com/kjdev/php-ext-brotli, which you can easily check with `extension_loaded` and/or by checking for function `brotli_compress`. Looks like only class-cache.php needs to be updated together with htaccess rules, plus maybe a few more places (you know best)

**Comment by camilamadronero-zz** [comment]
Related ticket https://secure.helpscout.net/conversation/1539258239/270630?folderId=2675957

**Comment by kevinjavitz** [comment]
Updates please? Shouldn't this just be a simple selector in the WP Rocket settings which compression to use?

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1584477724/283404?folderId=377611

**Comment by tnowak** [comment]
Any progress on this issue?

**Comment by slhuile** [comment]
Since 2019 the Brotli compression feature is requested for WP-Rocket. Many updates appeared but still no Brotli!!
Isn't it nonsense for a plugin that prides itself on being one of the best for improving PageSpeed ​​score?

Please provide a fix urgently because on many servers with PHP 8.1 it is no longer possible to integrate GZIP, only Brotli.

**Comment by ultrazeus** [comment]
When can we expect something movement on this topic?

**Comment by carstenjaksch** [comment]
This seems like a small change. Why isn't it supported in 2022?

**Comment by joaodath** [comment]
Hey! Can we have an update on this? Pre-compressing cache files with Brotli could lead to better performance for our websites. A free plugin from KeyCDN called [Cache Enabler](https://github.com/keycdn/cache-enabler) already offers the very same function. So why is a paid plugin like WP-Rocket still not offering it?

**Comment by inspiredtaste** [comment]
I agree with joaodath. I understand that Brotli wasn't fully supported by browsers a few years ago but now all CDN's and browsers fully support it. In fact, many CDN's are making Brotli compression to the end user enabled by default. However, for real bandwidth savings it would be optimal to have the origin server with WProcket pre-compressed natively with Brotli. That way bandwidth costs are significantly reduced end-to-end (origin-proxy) since the origin source is compressed using Brotli. This seems like a no brainer. Plus, this feature request was started back in 2019. It is 2023!

**Comment by shaneonabike** [comment]
i agree honestly. Also, we are paying for this service and adding this feature is not that much of a deal breaker. There are plenty of other extensions that generate the proper images we just need this final setup to make things roll perfectly.

**Comment by thinkjarvisdesignandmarketing** [comment]
Is there any update on this? Really does seem like something easy to implement.

It is now August 2023. Can we have some Brotli headers for HTACESS please.

I have raised an additional feature request to try and prompt an official response from WP-Rocket.

**Comment by inspiredtaste** [comment]
Still no native Brotli support in the major 3.15 plugin update? Is this on the roadmap for WProcket 3?

**Comment by fidoboy** [comment]
There is any hope to have the brotli support for WP Rocket?

**Comment by thinkjarvisdesignandmarketing** [comment]
Can we have an update please? Seems like an easy fix. Surely we just need brotli headers adding to ht.access?

**Comment by ultrazeus** [comment]
Crazy. Issue opened on Feb 8, 2019, more than 4 years ago.

**Comment by thinkjarvisdesignandmarketing** [comment]
@piotrbak Do we have an update on this post? Seems like a fairly easy fix to make as it is literally a change to .htaccess and nginx settings. There shouldnt be anything to change in Wp-Rocket itself? We are just telling the server how to compress the files?

**Comment by endymion0000** [comment]
There would also be pre-compressing cache files for css/js using brotli. Other cache plugins make use of the Brotli PHP extension so so I presume WP-Rocket could as well. There's really no reason for years of delay other than the obvious that they're just not working on it.

**Comment by thinkjarvisdesignandmarketing** [comment]
> There would also be pre-compressing cache files for css/js using brotli. Other cache plugins make use of the Brotli PHP extension so so I presume WP-Rocket could as well. There's really no reason for years of delay other than the obvious that they're just not working on it.

Shouldnt that be handled by the server like GZip?

**Comment by camilamadronero** [comment]
Ticket: https://secure.helpscout.net/conversation/2494107486/471685/

**Comment by inspiredtaste** [comment]
Thanks for the link but we don't have access to help scout. It is a paid service. Is this link internal to WProcket?

**Comment by j-peeters** [comment]
I also came here to read up on WP Rockets Brotli support when noticing that activating it on my server made my Wordpress login stop from working properly. Any news on the status of Brotli support? Thanks!

**Comment by Kpax7** [comment]
benorfaz closed this as [not planned] ??? Without any response or clarification? After all these years?

**Comment by johan-las** [comment]
related: https://secure.helpscout.net/conversation/3148207149/602584?viewId=8127840

**Comment by thinkjarvisdesignandmarketing** [comment]
All - One thing to consider here is Brotli is server side which means the files get served by Brotli if your server supports it.

We use Ubuntu, Plesk with both GZIP and BROTLI enabled. By default it uses a reverse proxy and serves data via NGINX which includes Brotli support.

Check your network panel in chrome dev tools. You should see Brotli as long as your server is configured for it.

**Comment by realrellek** [comment]
Hello,

I'd like to see support for brotli too. I do NOT mean by adding it to the htaccess file (although it would not hurt as Apache would pick either brotli or gz, depending on what the client accepts).

What I mean is, WP Rocket should pre-compress its files and store it on the server, so apache or nginx only have to grab the .br file if available and call it good.
Same thing as with the gz version of things.

**Comment by thinkjarvisdesignandmarketing** [comment]
> Hello,
> 
> I'd like to see support for brotli too. I do NOT mean by adding it to the htaccess file (although it would not hurt as Apache would pick either brotli or gz, depending on what the client accepts).
> 
> What I mean is, WP Rocket should pre-compress its files and store it on the server, so apache or nginx only have to grab the .br file if available and call it good. Same thing as with the gz version of things.

I dont think I've ever heard of things being done this way. The saving will be tiny. This is about saving bandwidth by compressing files and serving them not space on the server by using br instead of gz.

I dont actually think this is possible to be honest. (I dont work for wp-rocket but we use it on 200 websites)

**Comment by realrellek** [comment]
> I dont think I've ever heard of things being done this way

This is a pretty common use case on nginx with `brotli_static on;` ([ref](https://www.getpagespeed.com/server-setup/nginx/brotli-static)) - and also `gzip_static on;` ([ref](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html)).

For Apache, you would have to make some Rewrites to achieve the same.

It is entirely NOT about saving disk space but rather about saving CPU cycles when delivering the request. Because in this case, the server just grabs the .br or .gz file and delivers it. With the normal `gzip on; brotli on;` the server will compress the files for each request, which obviously is not free (compared to just grabbing the finished file and sending it).

Also, brotli is smaller in many cases, but first and foremost, it can be decompressed faster, which is a plus on mobile devices that tend to have weak hardware and potentially a bad internet connection.

**Comment by thinkjarvisdesignandmarketing** [comment]
> > I dont think I've ever heard of things being done this way
> 
> This is a pretty common use case on nginx with `brotli_static on;` ([ref](https://www.getpagespeed.com/server-setup/nginx/brotli-static)) - and also `gzip_static on;` ([ref](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html)).
> 
> For Apache, you would have to make some Rewrites to achieve the same.
> 
> It is entirely NOT about saving disk space but rather about saving CPU cycles when delivering the request. Because in this case, the server just grabs the .br or .gz file and delivers it. With the normal `gzip on; brotli on;` the server will compress the files for each request, which obviously is not free (compared to just grabbing the finished file and sending it).
> 
> Also, brotli is smaller in many cases, but first and foremost, it can be decompressed faster, which is a plus on mobile devices that tend to have weak hardware and potentially a bad internet connection.

Carry on sir....

**Comment by realrellek** [comment]
Carried on as suggested. 🫡

For anyone interested in the implementation details or the performance impact:

1. **The Tool:** I released `auto-brotli`, a cron-ready script that handles incremental pre-compression (Level 11) for existing caches. [[Auto-Brotli]](https://github.com/realrellek/auto-brotli)
2. The Integration: I submitted a PR to `rocket-nginx` to natively serve these pre-compressed files if they exist. [[See here](https://github.com/SatelliteWP/rocket-nginx/issues/230)]

Result: On my production setup, TTFB (Waiting for Server Response) dropped by ~25% compared to on-the-fly compression.
