### ISSUE TITLE
Files index-https-true.html 

### ISSUE THREAD

**Issue by Tainq** [wp-media/wp-rocket#1525]
If cache preloading is enabled, files are created in the form of an index-https.html

But if the user enters such a page, he will not receive this cache file. Instead, the user waits for a while until a file is created in the form index-https-true.html

Is this a mistake? If not, then what's the point of preloading in general, if in the end the first user will expect to create the correct cache file?

![image](https://user-images.githubusercontent.com/43818231/52533238-90f6f400-2d39-11e9-82a4-e0508026e02d.png)

**Comment by Tabrisrp** [comment]
You must have a plugin that is using our dynamic cookie system, like cookie notice for example. It's creating different versions of the cache based on a cookie value.

When the dynamic cookie system is used, only the default cache is preloaded.

**Comment by delacruzdesign** [comment]
So, how do we solve this? If this is done, the preload does not make much sense.
