### ISSUE TITLE
Handling fatal error due to missing mb_substr_count

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1526]
Ever since we switched to path-converter, we have been seeing few tickets related to missing `mb_substr_count`. 

When this is enabled, entire caching seems to silently fail. No fatal error is reported in the UI. The solution is to install the package `php7.0-mbstring` for which the customer needs to contact their host. 

## Ideas

- Add a check for this function and report it to the customer.
- Disable the features that use path-converter while preserving the rest. 
- The latest version of path-converter doesn't use `mb_substr_count` I think. Switch to that. 
- [Proposal / needs testing] Include a fallback function where if `mb_substr_count` is missing use `substr`. (probably helper plugin scope for customers who cannot install the package for some reason)

HS tag: [mb_substr_count](https://secure.helpscout.net/search/?query=tag:mb_substr_count)
Sample ticket - https://secure.helpscout.net/conversation/766511203/94703/

**Comment by GeekPress** [comment]
About this issue, @Tabrisrp told me on Slack that it will be fixed with 3.2.5 when I asked some infos. 

@Tabrisrp, can you confirm? If so, how it will be handle?

**Comment by arunbasillal** [comment]
@GeekPress Thanks. I am not sure if its related to - https://github.com/wp-media/wp-rocket/issues/1494

Have asked him - https://wp-media.slack.com/archives/CBJ2KQ0MU/p1549876354001000

**Comment by Tabrisrp** [comment]
In 3.2.5 we're updating the path converter library version, which includes a change where `mb_substr_count` is not used anymore.

**Comment by arunbasillal** [comment]
Closing the issue since `3.2.5` is here. 
I also tested this on a customer website and the issue is now resolved. Thanks Remy 👍
