### ISSUE TITLE
HTTPS scheme gets overwritten with HTTP with a PURGE request to Varnish

### ISSUE THREAD

**Issue by poralix** [wp-media/wp-rocket#1527]
Hello,

Referenced file: wp-rocket/inc/functions/varnish.php

This way it seems to work for us:

```
        $scheme = apply_filters( 'rocket_varnish_http_purge_scheme', $parse_url['scheme']);

        $parse_url['host'] = ( $varnish_ip ) ? $varnish_ip : str_replace('*','',$parse_url['host']);
        $purgeme           = $scheme . '://' . $parse_url['host'] . $parse_url['path'] . $regex;
```

It used to fail to purge Varnish cache due to 2 reasons:

1. Wrong scheme, the plugin calls http when is should be https. We have nginx in front of Varnish and both http and https are proxied to Varnish.

2. We have multi-host environment we need to specify valid domain with PURGE request. So we remove * from a domain name.

Regards,
Alex.

**Comment by piotrbak** [comment]
Provided solution fixed the problem:
https://secure.helpscout.net/conversation/1004756957/131201?folderId=2415573
