### ISSUE TITLE
Installing via Composer asks for requirement that doesn't exist

### ISSUE THREAD

**Issue by mike-source** [wp-media/wp-rocket#1529]
When installing via Composer (as per docs), it fails asking for a requirement version which doesn't appear to exist:

```
$ composer require wp-media/wp-rocket
Using version ^3.2 for wp-media/wp-rocket                
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)            
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wp-media/wp-rocket v3.2.4 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2.3.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2.3 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2.2 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2.1.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2.0.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.2 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - Installation request for wp-media/wp-rocket ^3.2 -> satisfiable by wp-media/wp-rocket[v3.2, v3.2.0.1, v3.2.1, v3.2.1.1, v3.2.2, v3.2.3, v3.2.3.1, v3.2.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**To Reproduce**
Just run `composer require wp-media/wp-rocket` in your project.

**Expected behavior**
It should have a resolvable set of requirements.

**Additional context**
It asks for version 1.3 of https://packagist.org/packages/a5hleyrich/wp-background-processing but the latest version that exists is 1.0.1

**Comment by mike-source** [comment]
I think this will fix: https://github.com/wp-media/wp-rocket/pull/1530

(apologies if I've not done the pull request 100% correctly! I tried...)

**Comment by bweiler-marketingflotte** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wp-media/wp-rocket 3.2.5 -> satisfiable by wp-media/wp-rocket[v3.2.5].
    - wp-media/wp-rocket v3.2.5 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.

**Comment by Tabrisrp** [comment]
For now the solution is to do what's suggested here: https://github.com/wp-media/wp-rocket/issues/741#issuecomment-392001608

I'll also add that to the docs to make it clearer.

**Comment by seagyn** [comment]
Why are we not helping that author get their package onto packagist and changing the dependency?
