### ISSUE TITLE
[WIP] Large number of URLs automatically excluded 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1535]
I'm opening this issue just to have a central place to gather cases and to keep tabs on it.

There have been a few cases where customers report that huge number of URLs have been automatically excluded. 

The issue is sometimes discovered because it causes the htaccess rules to grow beyond the server limit, and they get a 500 error. 

Have not yet been able to reproduce it to find out more, but there are several cases:
https://secure.helpscout.net/conversation/448774617/50718/?folderId=273766
https://secure.helpscout.net/conversation/765481551/94555/?folderId=377611
https://secure.helpscout.net/conversation/475530098/54114/?folderId=273766

unconfirmed but sounds similar: https://secure.helpscout.net/conversation/771970900/95637/?folderId=377611

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/912260653/117267?folderId=377611

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/977423357/126317?folderId=377611

**Comment by piotrbak** [comment]
Noo further feedback for 4 years. We'll reopen it if needed
