### ISSUE TITLE
Cache file not generated when the filename is longer than 255 characters

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1538]
While testing out #1537 I noticed that the cache file was not being generated for the dynamic cookies. 

Logged this:

[$rocket_cache_filepath](https://github.com/wp-media/wp-rocket/blob/79fe1d8ba52d37f318751cf40a3c4f13cc1d184c/inc/front/process.php#L350) = `/home/xxx/www.xxxx.net/xxxx/wp-content/cache/wp-rocket/www.xxxx.de/index-https---asp_data---asp_id---asp_phrase---cookie_notice_accepted---gdpr-allowed_cookies----gdpr-consent_types----wfwaf-authcookie---woocommerce_recently_viewed---wordpress_logged_in---wordpress_sec---wordpress_test_cookie---_ga---_gid---_gat-----privacy-policy--.html`

Checked for value of `rocket_put_content` [here](https://github.com/wp-media/wp-rocket/blob/79fe1d8ba52d37f318751cf40a3c4f13cc1d184c/inc/front/process.php#L439) and logged this on `false`: put_contents failed

If I limit the filename to 200 characters (to stay under 255), everything works. Looks like we need to add a limit for maximum file length for the cache file. 

In fact, I did some tests and on this server `$filename = substr( $filename, 0, 250 );` worked. While `251` didn't. I guess 250 + 5 for `.html`

**Comment by dfroberg** [comment]
Silly question perhaps, why not md5 the file(name) if it's too long, should ensure "uniqueness"?
