### ISSUE TITLE
Update WordPress compatibility

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#1550]
We display this information to customers : 

```
You have version 3.1.4 installed. Update to 3.2.5. View version 3.2.5 details.
Compatibility with WordPress 4.9.9: Unknown
Compatibility with WordPress 5.0.3: Unknown
```

We would need to update the compatibility to the latest version of WordPress.
We can use that : https://github.com/YahnisElsts/plugin-update-checker/blob/d98d6bc6caac4b46b61186447a947323a466a021/Puc/v4p5/Plugin/UpdateChecker.php#L94

**Comment by crystinutzaa** [comment]
I need some clarifications for this one. Basically this is needed:
https://www.screencast.com/t/nl1xha5U4gT

On WP Rocket  `get_latest_version_data()` API call I don't see any latest version tested, so at this point I think I need to get the latest WordPress version and add it in there for compatibility with all Wordpress versions. 
Did I got this right or not?

**Comment by arunbasillal** [comment]
@crystinutzaa Exactly as per your screenshot. We need to display that WP Rocket is compatible with the latest version of WordPress and its compatibility is 100%.
