### ISSUE TITLE
Removing ETags from WordPress dashboard

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1559]
When running WP Rocket on servers that use .htaccess file, we are removing the ETags header for the whole site (also for dashboard).

As WP Rocket optimizations are not taking place on the dashboard, we are not applying our Last-Modified validator to the resources. Basically, it means that we are preventing WordPress from serving the 304 status code in the dashboard:
https://github.com/WordPress/WordPress/blob/master/wp-admin/load-styles.php#L44

We need to perform further tests to see what are the performance benefits when ETags are working correctly in the WP Dashboard on various environments.

**Comment by Roy-Orbison** [comment]
The performance benefit is that the admin CSS is not re-fetched on every admin page load. Chrome seems to respond to content like this by caching it anyway and not re-fetching it again for a long time which means when the content *does* change, Chrome users will not get the content without a hard reload. I'm sure you have plenty of users who don't even know what a hard reload is.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.

**Comment by Roy-Orbison** [comment]
I believe this could be implemented quite easily.

You currently have this:
```apache
# FileETag None is not enough for every server.
<IfModule mod_headers.c>
Header unset ETag
</IfModule>

# Since we’re sending far-future expires, we don’t need ETags for static content.
# developer.yahoo.com/performance/rules.html#etags
FileETag None
```

Which could be changed to this:
```apache
# FileETag None is not enough for every server.
<IfModule mod_headers.c>
<IfModule mod_setenvif.c>
SetEnvIf Request_URI "^/wp-admin/" ETAGWPADMIN
</IfModule>
Header unset ETag env=!ETAGWPADMIN
</IfModule>

# Since we’re sending far-future expires, we don’t need ETags for static content.
# developer.yahoo.com/performance/rules.html#etags
<IfModule !mod_headers.c>
FileETag None
</IfModule>
```
This way, you only unset ETag if `mod_setenvif` is disabled, or it's not an admin request. It also prevents the `FileETag` directive from causing the same problem, unless `mod_headers` is disabled, so the conditional wouldn't work anyway.

WP-Rocket should not be touching admin requests at all. They're supposed to remain stable and predictable even if the front end is broken.
