### ISSUE TITLE
Filter Request - A filter to exclude external files from all optimizations

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1560]
Afaik, external CSS files are left alone but external JS is combined and deferred if the appropriate options are enabled. 

While these can be individually excluded, having a filter to exclude all of them can be helpful for users with a lot of websites. 

Hopefully the filter will: 

- Exclude external JS files from combination
- Exclude external JS files from JS defer
- Prevent any other optimization on external JS files.

**Comment by dillix** [comment]
+1 for this feature!

**Comment by dillix** [comment]
@arunbasillal I found filter "rocket_minify_excluded_external_js" can it be used for this situation?

**Comment by dillix** [comment]
Hi, is there any news for this feature? We have about 100 clients which uses wp rocket, and manually adding js exclusions  takes a lot of time. If you don't plan to implement this feature we will move them to another caching plugin :(

**Comment by arunbasillal** [comment]
@dillix This is probably safe to include and we will consider this. To keep expectations straight, I have included this in the proposal for WP Rocket 3.6. I will keep this thread updated if it happens :)

**Comment by dillix** [comment]
Hi, @arunbasillal I haven't seen this in 3.6 milestone https://github.com/wp-media/wp-rocket/milestone/69

**Comment by arunbasillal** [comment]
@dillix It is part of the internal proposal doc for 3.6. We haven't discussed it yet. Don't worry, I will update this thread about what happens after the discussion for sure. We are still working on 3.5 at the moment.

**Comment by dillix** [comment]
@arunbasillal Is there any news?

**Comment by arunbasillal** [comment]
@Tabrisrp Please advise. Currently do we have individual filters to exclude external files from file optimization? 

For example, to `Exclude external JS files from JS defer` we currently can specify the external file and get it excluded. But is there a filter to disable processing of all external JS files from defer without specifying the files individually?

**Comment by GeekPress** [comment]
@arunbasillal What are the benefits of adding an extra hook for this?

**Comment by arunbasillal** [comment]
@GeekPress This issue originated from a customer request with infinite license. They always had issues with external files being optimized. Since different websites have different external files, each time they had to write specific helpers to exclude them from all our optimizations. 

Having a **single filter to specify if WP Rocket should process external files or not** will help in these cases. Now that we are going to process external CSS files too, we could extend the same filter for CSS files as well.

**Comment by GeekPress** [comment]
If I get you right, the filter will exclude ALL external JS files from ALL optimization? I guess the need is very rare...

**Comment by arunbasillal** [comment]
> If I get you right, the filter will exclude ALL external JS files from ALL optimization?

Correct

**Comment by GeekPress** [comment]
@arunbasillal Thanks for confirming. Well I guess the need is very very rare... Let's close it for now and re-open if we have more requests.

**Comment by dillix** [comment]
@GeekPress My clients have errors if all external scripts combined.

**Comment by petuzueg** [comment]
+1 for this feature!

**Comment by Ilyano** [comment]
+1 for this feature!

**Comment by sandyfzu** [comment]
A user that is requesting this feature: https://secure.helpscout.net/conversation/1397049837/231665
