### ISSUE TITLE
Auto-deactivate "Disable Embeds" on Caldera Forms 1.8+

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1561]
From version 1.8 of Caldera Forms, the "disable embeds" option prevents form submissions, with this error: 
https://jmp.sh/sVuG7Mg

We could automatically deactivate that option to prevent tickets (unless Caldera have a fix from their end).
Possibly with a UI notice as we do for file optimization options when AO is active.

**Comment by arunbasillal** [comment]
We are not alone, so there might be a fix coming from Caldera - https://wordpress.org/support/topic/1-8-1-jquery-error/

**Comment by Shelob9** [comment]
Hey @webtrainingwheels it was nice to see you at WordCamp OC. So, talked about this with our support. The only plugin that is causing https://github.com/CalderaWP/Caldera-Forms/issues/3141 is WP Rocket. 

Our front-end is dependent on assets from WordPress core. We assume in Caldera Forms that they will be loaded the default way - on the `wp` global at DOM ready.

**Comment by Tabrisrp** [comment]
@Shelob9 We're planning on fixing this in the next minor version. Can you confirm that you don't have this issue with https://wordpress.org/plugins/disable-embeds/

If it's working with this plugin, it will also work with our changes in 3.3.3

**Comment by webtrainingwheels** [comment]
@Shelob9 @New0
Got another weird thing going on. 
![caldera_test_–_WordPress_Themes](https://user-images.githubusercontent.com/1043076/57493375-76b9ad00-7279-11e9-9eb4-de8e766ae22b.jpg)
This error seems to be caused by the "Disable Emoji" option. 
Commenting out this line resolves it :
https://github.com/wp-media/wp-rocket/blob/master/inc/common/emoji.php#L11

Any idea why that would interfere?!

**Comment by camilamadronero** [comment]
Related ticket and self reminder: https://secure.helpscout.net/conversation/851527960/107698/.
