### ISSUE TITLE
Disabled WordPress Embeds applied to pages excluded from cache

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1562]
The issue with Caldera forms turns out to be missing WordPress embeds file (#1561). Even if you exclude the page with the form from WP Rocket cache, the issue still happens. 

Turns out, `wp-includes/js/wp-embed.min.js` is removed even on pages excluded from cache. Confirmed by testing on the mega site. 

### Proposal

- If we could add the option to WP Rocket options meta box in the post editor, that could be ideal. 
- Also users would expect pages excluded from WP Rocket cache to not have any optimization applied.

**Comment by Tabrisrp** [comment]
The disable embeds is applied on both front-end and admin sides. This means we can't test for `DONOTROCKETOPTIMIZE`, nor can we only check with `is_admin()` because the REST API is not an admin context.

For this we will have to rely on the global option on WP Rocket settings.
