### ISSUE TITLE
Add a filter to keep empty lines in the htaccess file

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#157]
A customer requested that we don't remove empty lines when writing in the htaccess file. We could add a filter in htaccess.php to allow that

**Comment by Screenfeed** [comment]
+1 for this one.
@GeekPress: what is the reason to remove the empty lines?

**Comment by blogtutor** [comment]
I agree: It's annoying that WP Rocket strips out blank lines elsewhere in the .htaccess file.  I add blank lines in my .htaccess files (usually between groups of redirects or other directives) because it improves legibility and therefore reduces time and errors.

**Comment by webtrainingwheels** [comment]
Just documenting another complaint about this: https://secure.helpscout.net/conversation/348083233/37873/?folderId=273761
Agree with all above - we should only touch our own rules and not any other part of the file.
