### ISSUE TITLE
3.3-alpha6: Background Image lazyloading is not working in Avada

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1575]
In Avada lazyloading of background images is not working.

The HTML of the `div` is this:
```HTML
<div
class="fusion-fullwidth fullwidth-box fusion-parallax-none nonhundred-percent-fullwidth non-hundred-percent-height-scrolling"
style="background-color: #ffffff;background-image: url(http://mega.wp-rocket.me/avada/wp-content/uploads/2014/11/review_bkgd321-compressor.jpg");background-position: center center;background-repeat: no-repeat;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;-webkit-background-size:cover;-moz-background-size:cover;-o-background-size:cover;background-size:cover;">
```

Here is the RegEx not picking up the `background-image`:
https://regex101.com/r/x8HA5f/1

**Comment by Tabrisrp** [comment]
There is a stray `"` after the image URL, breaking the rest of the CSS in the style attribute. Removing it makes the background lazyload work correctly (tested with unit tests).

I don't think we should be expected to fix bad code or errors.

**Comment by webtrainingwheels** [comment]
Looks like this was a false alarm. There was an old version of the standalone plugin (pre-background support) active on the test site which took precedence over the alpha. Markup seems fine, maybe was a copy/paste issue. 
It's working as expected here: http://mega.wp-rocket.me/avada/background-image-check/
🙌
