### ISSUE TITLE
Query strings and search urls not preloaded via sitemap

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1577]
A customer wanted to cache searches and wanted to preload them. Since search urls look like `domain.com/?s=search`, they are ignored by the `is_already_cached` check and are hence not preloaded. 

https://github.com/wp-media/wp-rocket/blob/de4009f5931f92362d9b841bfbb2c6b995fdf576/inc/classes/preload/class-full-process.php#L83-L104

Test sitemap to re-create the issue - https://www.dropbox.com/s/pz8viw05v1ex2jh/sitemap_test.xml?dl=1

**Comment by sabrina-zeidan** [comment]
[Related ticket  ](https://secure.helpscout.net/conversation/793264000/99016)

**Comment by camilamadronero** [comment]
Related -> https://secure.helpscout.net/conversation/860002531/108960/.

**Comment by vmanthos** [comment]
**Related Ticket:**
https://secure.helpscout.net/conversation/897956215/114905?folderId=2135277
