### ISSUE TITLE
Regression Issue: Rollback from 3.2.X to 3.1.4 stops caching to work

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1578]
The content of the advanced-cache.php has been updated from 3.1.4 to 3.2.X

When we do a rollback from 3.2.X to 3.1.4, the content of the advanced-cache.php will be the one from 3.2.X

As we introduced a check for the Logger Class and the class doesn't exist in the 3.1.4, the process.php stops in the first condition.

To fix the issue, we must clear and update the content of advanced-cache.php after the rollback.

**Comment by webtrainingwheels** [comment]
It's an issue rolling back from 3.3 to 3.2.X as well. you have to deactivate/reactivate WPR after rolling back in order to cache the site again
