### ISSUE TITLE
Regression Issue: Mixed content from concatenated CSS file for relative assets

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1579]
Assets with a relative URL into a CSS file are causing a mixed content issue on SSL website when we turn on the combine CSS option.

Version 3.1.4:
https://cl.ly/16aca21c4c58

Version 3.2.6:
https://cl.ly/fe9f52c13c6f

The 3.2.X version adds http protocol which cause the issue.

Related ticket: 
https://secure.helpscout.net/conversation/802481613/100381?folderId=273768

**Comment by Tabrisrp** [comment]
Path in the actual file on the FTP:
![real-file](https://user-images.githubusercontent.com/3465180/54538860-741e9380-496b-11e9-928b-7addbf0cc3f4.jpg)

Path when viewing the URL in the browser:
![cloudflare](https://user-images.githubusercontent.com/3465180/54538858-7385fd00-496b-11e9-899c-db5ef73e5135.jpg)

Something is modifiying the file content in-between, most likely Cloudflare. It's not WP Rocket that is adding this.
