### ISSUE TITLE
Varnish add-on causes timeout when saving posts on Flywheel/5.0.0 (cloud)

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#1581]
Slack combo: https://wp-media.slack.com/archives/C08N8J6VC/p1552659803374000

On Flywheel server version 5.0.0 the Varnish add-on is causing long delays / 503 errors when saving posts. 
This happens independently of plugins, editor and theme, using Gutenberg, the Classic Editor and Visual Editors (tested Beaver Builder and Visual Composer. 

- Enabling **Disable Cache Clearing** helper fixes the issue when saving posts. 
- Manually clearing posts from WP Rocket menu works without issues.
- Commenting 
https://github.com/wp-media/wp-rocket/blob/ae9c35a23b6552fe0bfc501f2857314e3fb3413b/inc/3rd-party/hosting/flywheel.php#L28 resolves the issue

**To Reproduce**
1. log in to FlyWheel account, 
2. website: wp-rocket.flywheelsites.com is using FlyWheel/4.1.0
3. website: www.lifequestchiro.com is using FlyWheel/5.0.0
4. Save a post in each of the websites and check the timeout/delays on flywheel 5.0 vs the speed on FlyWheel/4.1.0

** Related tickets **
> https://secure.helpscout.net/conversation/801818620/100294
site: https://www.lifequestchiro.com/
server: Flywheel/5.0.0

> https://secure.helpscout.net/conversation/798299781/99741/
site: https://questforgroove.com/
server: Flywheel/5.0.0

> https://secure.helpscout.net/conversation/795859035/99341/ 
site: sitehttp://journey.flywheelstaging.com/
Server: Flywheel/5.0.0

**Comment by webtrainingwheels** [comment]
We have a 5.0.0 test site now: 
https://wp-media.slack.com/archives/C08N8J6VC/p1553819284046500?thread_ts=1552659803.374000&cid=C08N8J6VC

CC: @piotrbak / @arunbasillal
