### ISSUE TITLE
Enhancement: Auto-exclude all Product Attribute Taxonomies from Critical CSS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1583]
With WooCommerce we can create unlimited product attributes.

As these attributes don't have a public page, we can auto-exclude them to the Critical CSS process.

They are all started by pa_

Here an example:
https://secure.helpscout.net/file/5de4805abf96951b/42565/2246487466/181699937/

**Comment by arunbasillal** [comment]
The functions `wc_get_attribute_taxonomy_names` and `wc_get_attribute_taxonomies` are useful to get the product attributes - https://docs.woocommerce.com/wc-apidocs/source-function-wc_get_attribute_taxonomies.html
