### ISSUE TITLE
Variable width for radio button - "My Status" section

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#1590]
This is the message that one of our volunteer translators sent us:

> Hi there. I'm one of the volunteer translators for wp rocket and i noticed a glitch/bug that's not strictly related to the translation itself. I translated WP Rocket to Croatian. The translation works just fine but i noticed that the checkboxes under the Status section have a fixed width so the translated text doesn't fit.
> In the upper checkbox i used the abbreviation for Off in Croatian and it still doesn't fit not to mention that in the screenshot i added some padding to it so you can see the text. Otherwise, it overlaps the description.

This is a screenshot representing the issue:
![radiobox fixed width](https://user-images.githubusercontent.com/14943244/54906802-565dab00-4ee4-11e9-8f2a-9a6e426009df.png)

**Comment by crystinutzaa** [comment]
I think that On / OFF should be kept in all languages in order to accomodate that field. I noticed the same issue in Romanian, Turkish, Suomi, Portuguese.

**Comment by arunbasillal** [comment]
Waiting for feedback here - https://wp-media.slack.com/archives/CFSCRLVGB/p1576193721002700

**Comment by arunbasillal** [comment]
@AliceOrru Is there a way to get feedback from our translators about the suggestion to use `ON/OFF` or `YES/NO` for all languages? Maybe they know how it's handled in other plugins or themes?

**Comment by AliceOrru** [comment]
The tool we use to keep in touch with our translators is Transifex: I can try to send a message from there and explain the issue. 
YES/NO is, in my opinion, the best solution, since it's very short in most languages ([Yes](https://www.wolfestone.co.uk/free-tools/yes-in-different-languages/)/ [No](https://www.wolfestone.co.uk/free-tools/no-in-different-languages/)).

**Comment by arunbasillal** [comment]
Thanks @AliceOrru. Please let us know if you hear back from the community. If not, we will decide this internally based on your feedback :)

**Comment by GeekPress** [comment]
I guess we wait enough time ^^

Let's go with `Yes` and `No`.

**Comment by GeekPress** [comment]
Yes/No is quite weird, isn't it? What does it mean for an option?
- Yes, I want it
- Yes, I want to deactivate

When On/Off can't be confused

**Comment by remyperona** [comment]
@GeekPress What should we do for this?

**Comment by GeekPress** [comment]
@Tabrisrp We can go with On/Off for all languages

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In
- `view/settings/page.php`
- `view/settings/one-click-addon.php`
- `view/settings/rocket-addon.php`
- `view/settings/sliding-checkbox.php`

- Change `<?php echo esc_attr_x( 'On', 'Active state of checkbox', 'rocket' ); ?>` to `On`
- Change `<?php echo esc_attr_x( 'Off', 'Inactive state of checkbox', 'rocket' ); ?>` to `Off`

### Estimate the effort ✅
Effort `[XS]`
