### ISSUE TITLE
LazyLoad compatibility with printing

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1591]
On a page with LazyLoad enabled, if one attempts to print the page without scrolling down, the images do not show up in print. 

This has been discussed in the LazyLoad library that we use - https://github.com/verlok/lazyload/issues/257

And an answer from the author here - https://stackoverflow.com/a/52768850/8255629

Wondering if we can make this part of WP Rocket so that printing pages with LazyLoad won't be an issue.

**Comment by mcyger** [comment]
I'd love to see this enhancement added. Thank you!

**Comment by Tabrisrp** [comment]
This isn't an applicable solution for us. It requires adding a button on the page to send the print request with some custom JS, instead of using the default browser behaviour for that action.

@GeekPress @arunbasillal In my opinion this is a `wontfix`.

**Comment by arunbasillal** [comment]
@Tabrisrp @GeekPress 

Thinking about this a year later, I have to agree with Remy. Adding a new button doesn't make sense. 

Some thoughts:

- Printing a page shouldn't be a common scenario. We have not had very many issues about it. 
- Before someone prints a page, they are likely to read the entire page and scroll down. So the images will be loaded. This might be why we do not see tickets about it. 
- Print preview will show the issue to the user before they print. 

My recommendation is to close this as it is an edge case.

**Comment by GeekPress** [comment]
@Tabrisrp @arunbasillal Thanks for your feedbacks. Then let's close it for now
