### ISSUE TITLE
When lazyload is enabled, images are not available to pin in the Pinterest app 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1592]
Normally, when visiting a page using the Pinterest app, images are available to pin in the user's boards.

When lazyload is enabled on a site, the images that _are_ lazyloaded, are not available to pin because the app doesn't scroll and all it only detects transparent pixels.

To reproduce:

- Install the Pinterest app on your phone.
- Visit this page: [www.musicol.de/geige-lernen](url)
- Click the Pinterest button on the bottom row and select the page to be opened using the app (not your browser)

A workaround would be to automatically disable lazyloading when the **Pinterest** user-agent is detected.

**Related Ticket:**
https://secure.helpscout.net/conversation/810094359/101517/

**Comment by piotrbak** [comment]
We didn't have any request ralted to this issue for many years. Going to close it, feel free to reopen it if needed
