### ISSUE TITLE
Display admin notice when "Disable caching" in Geo IP Detection plugin is enabled

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1593]
The [plugin](https://wordpress.org/plugins/geoip-detect/) `GeoIP Detection` defines `DONOTCAHCEPAGE` constants on pages and disables caching and optimizations. This can be disabled via the settings UI of the plugin but the option is enabled by default. 

<img width="769" alt="geo ip" src="https://user-images.githubusercontent.com/5751474/55001486-f98ded80-4fd4-11e9-8414-5c39af3119c1.png">

Adding an admin notice to warn them about the incompatibility and the solution would help many users. 

Related ticket - https://secure.helpscout.net/conversation/809907708/101472/

**Comment by GeekPress** [comment]
@arunbasillal What do you suggest for the notice wording?
@webtrainingwheels Do you have some ideas for this one? :)

**Comment by camilamadronero** [comment]
Related ticket: https://secure.helpscout.net/conversation/1118172782/153463?folderId=2675957.

**Comment by arunbasillal** [comment]
@GeekPress Given what we know now, I am wondering if we can have a better approach. We haven't had many support tickets about this issue. 

Maybe, we could get in touch with the plugin author and suggest a compatibility. They could use our dynamic cookie feature to create different versions of cache.

**Comment by webtrainingwheels** [comment]
I agree notices have backfired on us in the past. 

What about outputting something something in our footer comment?
-- caching disabled by GeoIP ---

**Comment by arunbasillal** [comment]
@webtrainingwheels Since we do not have enough ticket volume regarding this issue, my thinking is to see if we can not include the code (and its maintenance) in WP Rocket. 

And since WP Rocket already has the tools to accomplish compatibility (using dynamic cookies), this is something that the plugin author might consider including at their end. 

The HTML comment is not very user friendly imo. Many users who install the GeoIP plugin will not notice it.

**Comment by GeekPress** [comment]
> They could use our dynamic cookie feature to create different versions of cache.

@arunbasillal  If I understand well, the caching file should be generated depending to a range of IPs. How could we make it compatible the dynamic cookie?

@webtrainingwheels I'm agree with Arun, people may be confused by the HTML comment and not notice it.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1281589119/194682/

**Comment by piotrbak** [comment]
We didn't have enough requests related to this one. We might want to include it within 2598, if ever implemented. Closing it in favor of the above.
