### ISSUE TITLE
Add compatibility for Slider 3

### ISSUE THREAD

**Issue by jroddington** [wp-media/wp-rocket#1594]
**Describe the bug**
There are currently some compatibility issues with Slider3 - https://smartslider3.com/ (see helpscout tickets)

We could create a compatibility file to fix these issues.

**Comment by piotrbak** [comment]
The only incompatibility we have is that SmartSlider doesn't appear unless user interaction when DelayJS is enabled. Exclusions needed:
```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js 
/jquery-migrate(.min)?.js
/smart-slider-3/(.*).js
/SmartSlider3/(.*).js
_N2
```

**Comment by piotrbak** [comment]
Closing it since it works as expected. To load it immediately when Delay JS is enabled, we need to add exclusions described here:
https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#smart-slider
