### ISSUE TITLE
Multiple insert by php

### ISSUE THREAD

**Issue by ibreezer** [wp-media/wp-rocket#1595]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

> \inc\classes\optimization\JS\class-combine.php

> These files try to insert the combined js & css before the body tag with str replace it makes the assumption that there is only one body tag, while many times multiple body tags can occur, for example when you have javascript to create a "popup" window etc. Which in direct consequence creates broken javascript.

**Expected behavior**

> Only add to the last body tag

**Additional context**

I solved it by adding a new function to the class
```
function str_lreplace($search, $replace, $subject)
{
$pos = strrpos($subject, $search);

if($pos !== false)
{
$subject = substr_replace($subject, $replace, $pos, strlen($search));
}

return $subject;
}
```
and replaced 
`$html = str_replace( '</body>', '<script src="' . esc_url( $minify_url ) . '" data-minify="1"></script>' . $move_after . '</body>', $html );`

With:
`$html = $this->str_lreplace( '</body>', '<script src="' . esc_url( $minify_url ) . '" data-minify="1"></script>' . $move_after . '</body>', $html );`

**Comment by ScottTravisHartley** [comment]
I get what this is trying to solve but a document should only ever contain a single body tag, more than one is not proper markup.

**Comment by ibreezer** [comment]
There are other scripts using the body tag made in JavaScript that uses the body tag like wprocket for example to append code and it is not bad practise to use JavaScript code to create a Window that contains the body tag in some avses either way this is a simple dig to make and would provide a more secure way and better under experience to attach the combined code, with next to none impact on performance.

**Comment by GeekPress** [comment]
@ibreezer Can you please share a website where we can view multiple `<body>` tags?

Thanks

**Comment by GeekPress** [comment]
Hi @ibreezer 🤚

We haven't back from you since I asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best
