### ISSUE TITLE
Proposal - Make $rocket_remove_query_strings part of config file and add a filter

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1597]
There are many use cases where users want the same cache file to be served for multiple values of query strings. And we do have a whitelist that is hard-coded into `process.php` (WP Rocket 3.2.6) - 

https://github.com/wp-media/wp-rocket/blob/de4009f5931f92362d9b841bfbb2c6b995fdf576/inc/front/process.php#L129-L151

If we could make this whitelist part of the config file and have a filter (to be used during the config file generation) to add custom values to this, a lot of customers would find it useful.

**Comment by webtrainingwheels** [comment]
There is also a need from customers to be able to change the default behaviour of our currently whitelisted parameters. 

Not every customer wants the same cache file to be served for every variation of a parameter. They may want the URL cached but a separate cache file per value (as if they had manually entered the parameter into the Advanced Rules setting). So we should provide a way to be able to remove entries from the default whitelist as well as add custom values. 

We have a few tickets were this behaviour causes issues for tracking, e.g. 
https://secure.helpscout.net/conversation/864381130/109554?folderId=377611
https://secure.helpscout.net/conversation/845778320/106726/

Essentially, we should allow customers to choose how they want query strings to behave on their site. So we can set our opinionated handling as defaults but everything should be made filterable for the user.

**Comment by camilamadronero** [comment]
Related https://secure.helpscout.net/conversation/883954106/113057/

**Comment by sabrina-zeidan** [comment]
Another [ticket](https://secure.helpscout.net/conversation/909092779/116820/)
