### ISSUE TITLE
Fix issue with Divi blog module + Optimize CSS Delivery

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1598]
When Optimize CSS Delivery is activated on a site using the Divi theme, its blog module does not display. 

To prevent this, we can auto-exclude the main style sheet from being loaded async.
i.e `wp-content/themes/Divi/style.css`

If Minify CSS or Combine CSS are also active, this file should be auto-excluded as well (to enable the async exclusion to work).

**Comment by piotrbak** [comment]
It looks like in a specific case the file can be named differently. We should exclude this file too:
`/wp-content/themes/Divi/style.dev.css`

Related ticket:
https://secure.helpscout.net/conversation/1260605302/189021?folderId=2415573

**Comment by piotrbak** [comment]
Feedback from the Divi support team:
> If the "Minify And Combine CSS Files" is enabled in theme options then the site will load style.css file. If that option is disabled then the site will ignore the style.css file and will show "style.dev.css" file

I believe we should exclude both files.

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1490300790/257822/

**Comment by piotrbak** [comment]
It looks like `Minify And Combine CSS Files` feature was removed from Divi options.
