### ISSUE TITLE
wpr-admin.js : Cannot read property 'value' of null

### ISSUE THREAD

**Issue by iwebroot** [wp-media/wp-rocket#1602]
**Describe the bug**
Error in **wpr-admin.js**

`Uncaught TypeError: Cannot read property 'value' of null`
`at new s (wpr-admin.js:formatted:416)`
`at HTMLDocument.<anonymous> (wpr-admin.js:formatted:450)`

**To Reproduce**
1. Login to backoffice
2. Go to WP Rocket settings
3. See error

**Screenshots**
<img width="1280" alt="Erreur wpr-admin js" src="https://user-images.githubusercontent.com/13943732/55401268-e4770880-5558-11e9-9ca7-e28b02339c32.png">

**Additional context**
All tab not work

Thank you.

**Comment by Tabrisrp** [comment]
Which version of WP Rocket are you using?

Did you test with a default theme and no other plugins, to make sure it's not a conflict?

**Comment by iwebroot** [comment]
> Which version of WP Rocket are you using?
> 
> Did you test with a default theme and no other plugins, to make sure it's not a conflict?

Thank you for your reply.
The version of WP Rocket is 3.3. I have tested with default theme and all others plugins disabled.

**Comment by dreamjobma** [comment]
Same here, Disabled all plugins, error is still present.

Cannot choose tabs.

**Comment by Tabrisrp** [comment]
This seems to happen only when the admin is in French, because of a mistake in the translation file. We'll fix this quickly.

**Comment by iwebroot** [comment]
> This seems to happen only when the admin is in French, because of a mistake in the translation file. We'll fix this quickly.

Thank you @Tabrisrp

**Comment by Tabrisrp** [comment]
Fixed in 3.3.0.1

**Comment by sabrina-zeidan** [comment]
Another [website](https://secure.helpscout.net/conversation/916003952/117785) with this issue. Version 3.3.6. Admin language is Português do Brasil. Switching to English resolves it.
