### ISSUE TITLE
Minify for logged user

### ISSUE THREAD

**Issue by Tainq** [wp-media/wp-rocket#1603]
Is it possible to make it so that the page would be minified for logged in users, but did not cache .

**Comment by ScottTravisHartley** [comment]
Would be useful for BuddyPress and bbPress based websites.

**Comment by fabianskibr** [comment]
Any news about this option??

**Comment by Tainq** [comment]
Is there any information about this option?

**Comment by Tainq** [comment]
Is this being considered?

**Comment by arunbasillal** [comment]
@Tainq We considered this a few months back. Based on what we know so far, the tiny gain in minifying is offset by the extra overhead of processing the page. 

Also this will complicate WP Rocket and raise too many confusions. 

Not saying that we won't revisit this, but at the moment, this isn't a priority.
