### ISSUE TITLE
cookie cache 

### ISSUE THREAD

**Issue by Tainq** [wp-media/wp-rocket#1604]
I use cookie-notice plugin. In version 3.2.6 I commented out the code. This made it possible to create files of the type index-https.html **without** index-https-true.html
This did not affect the work of the plugin. Cookie worked properly

But in version wp-rocket 3.3, it is impossible to login/exit correctly
Is there any way around this?

<details><summary>Code</summary>

    if ( ! empty( $rocket_cache_dynamic_cookies ) ) {
	          foreach ( $rocket_cache_dynamic_cookies as $key => $cookie_name ) {
		      if ( is_array( $cookie_name ) && isset( $_COOKIE[ $key ] ) ) {
			foreach ( $cookie_name as $cookie_key ) {
				if ( '' !== $_COOKIE[ $key ][ $cookie_key ] ) {
					$cache_key = $_COOKIE[ $key ][ $cookie_key ];
					$cache_key = preg_replace( '/[^a-z0-9_\-]/i', '-', $cache_key );
					$filename .= '-' . $cache_key;
				}
			}
			continue;
		}
		if ( isset( $_COOKIE[ $cookie_name ] ) && '' !== $_COOKIE[ $cookie_name ] ) {
			$cache_key = $_COOKIE[ $cookie_name ];
			$cache_key = preg_replace( '/[^a-z0-9_\-]/i', '-', $cache_key );
			$filename .= '-' . $cache_key;
		}
	}

</details>

**Comment by guytzhak** [comment]
any update?

**Comment by piotrbak** [comment]
@Tainq This is made for compatibility with GDPR. If you feel that our compatibility is not working correctly, please reopen the issue and share with me some more details.
