### ISSUE TITLE
Serving static content from cookieless domain - limitations and possibilites

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1618]
This is a documentation of what we know so far while trying to use a separate cookieless domain for static assets and using it with WP Rocket. Using a GitHub issue so that we can possibly improve a few aspects and so that we can share with our customers if needed. 

Our [current documentation](https://docs.wp-rocket.me/article/889-parallelize-downloads-across-hostnames-serve-static-content-from-a-cookieless-domain) links to [this external guide](https://www.reginaldchan.net/serving-static-content-from-cookieless-subdomain/). This guide suggests to define `WP_CONTENT_URL` as below:

```
define("WP_CONTENT_URL", "http://static.domain.com"); 
```

### Known issues and causes

- Minification and combination doesn't work
- The primary reason is that `rocket_url_to_path` returns false. 
- There are two reasons for this. First is a conflict between CDN [$url_host](https://github.com/wp-media/wp-rocket/blob/1ffb4f447d6f6ed8f413cec1b1c88f10beb0dcc4/inc/functions/formatting.php#L333) and [$root_url](https://github.com/wp-media/wp-rocket/blob/1ffb4f447d6f6ed8f413cec1b1c88f10beb0dcc4/inc/functions/formatting.php#L336) causing issue with this replacement. 
- The above issue happens if any CDN CNAME is filled in and even if the option "Enable Content Delivery Network" is unchecked. Refer issue #1588 
- Even without the CDN, if `WP_CONTENT_URL` doesn't have `/wp-content`, the resulting URL is broken. 

### Enough confusion, just tell me what works

- ~~Make sure CDN tab is not filled in at all. As of now (WP Rocket 3.3), `Enable Content Delivery Network` is ignored by `rocket_url_to_path`~~. #1588 (Fixed in WP Rocket 3.4)
- Instead of pointing `http://static.domain.com` to the `wp-content` folder, point it to the root folder and define `WP_CONTENT_URL` as below: 

```
define("WP_CONTENT_URL", "http://static.domain.com/wp-content"); 
```

Note sure if the following is relevant, but one of the users had these three definitions: 

```
define("WP_CONTENT_URL", "http://static.domain.com/wp-content"); 
define( 'COOKIE_DOMAIN', 'https://domain.com');
define( 'WP_PLUGIN_URL', 'https://static.domain.com/wp-content/plugins');
```

### Related tickets and conversations

- https://secure.helpscout.net/conversation/791066308/98721/
- https://secure.helpscout.net/conversation/814269969/102106?folderId=1213664
- https://wp-media.slack.com/archives/C43T1AYMQ/p1553275534110600
- https://wp-media.slack.com/archives/C43T1AYMQ/p1551866918030700
- https://secure.helpscout.net/conversation/887744224/113586?folderId=1724284 (LazyLoad JS was not replaced with CDN as well)

**Comment by Tabrisrp** [comment]
What should we do with this now that the CDN related bug is fixed?

**Comment by GeekPress** [comment]
@arunbasillal Does this issue is still accurate?

**Comment by arunbasillal** [comment]
@GeekPress This is complex to test and recreate, previous customers had made the recommended switch (`define("WP_CONTENT_URL", "http://static.domain.com/wp-content");`). 

I think we can close this for now since this is very rare and there is a solution in case this is needed. If this can be confirmed in the future, we can look into it.

**Comment by piotrbak** [comment]
Closing it since there's no interest in this topic. It can be easily fixed with CDN and we have a solution if needed.
