### ISSUE TITLE
Fatal error when Rank Math XML sitemap for preloading

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#1620]
**PHP Fatal error: Class 'RankMath\Modules\Sitemap\Router' not found in /wp-content/plugins/wp-rocket/inc/3rd-party/plugins/seo/rank-math-seo.php on line 86**

In the Rank Math SEO plugin code, they're retrieving the sitemap URL like this:

`return \RankMath\Sitemap\Router::get_base_url( 'sitemap_index.xml' );`

whereas we're doing it like this:

`$sitemaps[] = \RankMath\Modules\Sitemap\Router::get_base_url( 'sitemap_index.xml' );`

So I just took the **\Modules** bit out of that line on my test site, which seems to have fixed the problem.

**Comment by webtrainingwheels** [comment]
HS tag: `rank math seo`

**Comment by Tabrisrp** [comment]
@MyThemeShop did your code change between #1445 and now?

**Comment by MyThemeShop** [comment]
Hello @here 

We have created a pull request, which should fix the issue:
https://github.com/wp-media/wp-rocket/pull/1629

Thank you.
