### ISSUE TITLE
Cache not cleared/preloaded

### ISSUE THREAD

**Issue by grosssmutttr** [wp-media/wp-rocket#1625]
**Setup:**
WP Rocket Version 3.3.0.1
WP Version Version 5.1.1
WooCommerce Version 3.5.7

**Steps to reproduce:**
1. Activate preloading
2. Activate sitemap preloading
3. Set reset cache after 10 hours
4. We have a page that can be accessed via wildcard domain so:
test.example.com
test2.example.com
test3.example.com 
...
Every available page is available in a separate sitemap.xml
so test-sitemap.xml, test2-sitemap.xml, test3-sitemap.xml ...
6. Enter the sitemaps in the preload sitemaps area
7. Click on clear cache and preload cache
---> Cache is generated as expected for each of these domains and every page

**Problem:**
--> The cache is never regenerated automatically after the 10 hours.

I also checked whether wp-cron is not running but it is...
Plugin activation/deactivation also without success.

**Comment by arunbasillal** [comment]
Please write directly to support @grosssmutttr - https://wp-rocket.me/support/

We use GitHub for confirmed bugs and feature discussions.
