### ISSUE TITLE
Can't import settings. Filetype error.

### ISSUE THREAD

**Issue by codetipi** [wp-media/wp-rocket#1630]
**Describe the bug**
Can't import settings file. Trying to import gives the following error:

Settings import failed: incorrect filetype.

**To Reproduce**
1. Go to Tools and try to import a fresh WPRocket settings file

**Expected behavior**
Import settings successfully.

**Comment by Tabrisrp** [comment]
This could not be replicated on a test installation.

To get support for your specific case, please send a support ticket through the plugin page, or https://wp-rocket.me/support/

We do not provide support on GitHub directly, it's focused on confirmed bugs, new enhancements and new features.

**Comment by arunbasillal** [comment]
The site tested was potentially a multisite. And this is probably the same as #1765
