### ISSUE TITLE
Exclude Rev Slider JS from Remove Query Strings

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1631]
When Remove Query Strings is enabled we process a couple of files from Revolution Slider, but the originals are also loaded. This has a negative impact in GT Metrix (and creates extra requests). It's flagged under: _Serve Resources from a consistent URL_

Could we either prevent this from happening while still optimizing the files, or maybe just exclude these files from the process?
![Latest_Performance_Report](https://user-images.githubusercontent.com/1043076/55988107-d95a6180-5c57-11e9-8138-303ee77659c9.jpg)

**Comment by Tabrisrp** [comment]
Closing this as we're removing the related option.
