### ISSUE TITLE
Replace a5hleyrich/wp-background-processing with deliciousbrains/wp-background-processing

### ISSUE THREAD

**Issue by njbarrett** [wp-media/wp-rocket#1633]
It's currently not possible to install via composer as the a5hleyrich/wp-background-processing no longer exists.
It seems to have been renamed to deliciousbrains/wp-background-processing

Composer file needs updating

**Comment by Tabrisrp** [comment]
`deliciousbrains/wp-background-processing` is currently not available on packagist, so that won't work. They need to re-publish it under the new vendor name for us to be able to fix this.

**Comment by kl3sk** [comment]
Why not refer Github repository directly in the composer file until it is published on packagist ?

**Comment by ryanmcdonnell** [comment]
If you want to install wp-rocket from packagist, you can add
```
"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/tabrisrp/wp-background-processing"
		}
	],
```
to your `composer.json`. This will satisfy a5hleyrich/wp-background-processing v1.3 when composer looks for the wp-rocket dependencies.

**Comment by Tabrisrp** [comment]
Closing this as we moved our dependency to our own copy of the background process.
