### ISSUE TITLE
WP Rocket is causeing an issuse with the webview app.

### ISSUE THREAD

**Issue by wavwax** [wp-media/wp-rocket#1637]
Hello, im using WP Rocket on my website: https://wavwax.com, the issuse i'm having is, i have a  plugin that makes a web view of my website into an app for the IPhone and Android. Everything works great, but when i turned on WP Rocket, the app stop updating new post....what ever was on the mobile view of the site once i turned on WP Rocket, is still there....i troubleshot the app with WP Rocket by turning things on and off, still couldnt get the app to update....once i delete WP Rocket and reload the app, the app works fine, it updates great.....once i turn WP Rocket back on....the app stops updateing....please help and thank you....

Reagrds

WAVWAX.COM

**Comment by Tabrisrp** [comment]
For support, please open a support ticket from the plugin or from https://wp-rocket.me/support/

This will be the best channel to get help. Our Github is focused on fixing confirmed bugs and development of enhancements or new features.
