### ISSUE TITLE
Display admin warning when "WP Facebook Open Graph protocol" plugin is active

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1640]
Output buffer cleaned incorrectly. While caching is fine, other optimizations fail. Confirmed this on a customer website and staging. 

We should probably do the same for every plugin and theme on our list - https://hub.wp-media.me/wp-rocket/knowledge-base/issues/plugins-and-themes-with-known-conflicts/

Related #1593

**Comment by piotrbak** [comment]
The plugin is not maintained since 3 years already. We won't be fixing the compatibility.
https://wordpress.org/plugins/wp-facebook-open-graph-protocol/
