### ISSUE TITLE
Proposal: Detect staging path on advanced-cache.php on WP Engine Live websites

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1642]
I got a ticket on a live WP Engine website where no features from WP Rocket were able to work.

I checked the advanced-cache.php file and I noticed the config dir path contains the staging path like:

'config_dir_path' => '/nas/content/**staging**/xxxxxxx/wp-content/wp-rocket-config/',

instead of

'config_dir_path' => '/nas/content/**live**/xxxxxxx/wp-content/wp-rocket-config/',

One of the reason could be because the customer tried WP Rocket on their staging site and then did a "push" from the staging to the prod website.

To avoid that we could make an auto-detection between the config dir path and the website URL.

If we detect the URL of the website doesn't contains **.wpengine.com** (used for staging) and the config dir path contains **staging** to delete the advanced-cache.php and regenerate it.

**Comment by webtrainingwheels** [comment]
related: 
https://secure.helpscout.net/conversation/831441961/104865/
https://secure.helpscout.net/conversation/830224699/104700/

possibly related: https://secure.helpscout.net/conversation/829374911/104568/

**Comment by webtrainingwheels** [comment]
The advanced-cache.php is blank but now I get this admin notice:
![Legacy_Staging_‹_Mission_Control_—_WordPress](https://user-images.githubusercontent.com/1043076/56996696-3613b280-6b5a-11e9-8c87-ccafad33fd7c.jpg)
