### ISSUE TITLE
Clear all scheduled cron jobs when WP Rocket is uninstalled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1644]
When WP Rocket is uninstalled, these two cron jobs are cleared currently:

https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/uninstall.php#L26-L27

We should also add these:
```PHP
rocket_google_tracking_cache_update
rocket_purge
```

**Related Ticket**
https://secure.helpscout.net/conversation/827766635/104317/

**Comment by Tabrisrp** [comment]
We don't have an event called `rocket_purge`

But for the other one it's correct, and we should also add `rocket_facebook_tracking_cache_update`
