### ISSUE TITLE
Preload: 0 pages have been cached. Even if we have pages to preload.

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1645]
I recorded a video to explain and show the issue:
https://cl.ly/9ff68a9d92e6

Related ticket with access:
https://secure.helpscout.net/conversation/827671653/104293?folderId=273768

**Comment by Tabrisrp** [comment]
Copying here the description of this from Slack

> During preload, the system checks if the pages are already checked, and skip them if that’s the case, so if there is no page uncached, it will just return zero.
> 
> Also, not all settings changed will clear the cache, only the ones which needs to. That’s why when you switch the value of clear cache lifespan, you still got a zero for the preload, because it’s not a setting that will clear the cache.
> 
> When you switched HTML minification, it’s clearing the cache, and the preload is caching the pages that were just cleared.
> 
> So technically there is no bug. We can now argue that the UI doesn’t communicate what is happening correctly

**Comment by GeekPress** [comment]
Copying my response from Slack here

> Thanks for the explanation. As a user perspective and even for me before you explained the reason, it sounds like a bug. If we don't have new pages to preload, it will be better to update the actual behavior by changing the message to warn the user his pages are already preloaded / cached.

**Comment by arunbasillal** [comment]
Thinking of a way to present this better. 

What if we increment the count even if a page is already preloaded? This will give consistent results every time. 

- Increase the count
- check of the page is preloaded. If yes, return. 
- If not, preload the page and return

The job of the preloader is to make sure that cache is ready. It does this job even if the cache for certain (or all in this case) is already available.
