### ISSUE TITLE
Exclude jQuery served from wp.com's CDN, from minification/combination/deferring

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1646]
The jQuery library on some websites is loaded from the wp.com's CDN:
`c0.wp.com/c/5.1.1/wp-includes/js/jquery/jquery.js`

Currently, we are not excluding that kind of URLs from the JavaScript combination/deferring process, which results in `jQuery not defined` errors.

**Related Ticket**
https://secure.helpscout.net/conversation/828578755/104444/

**Comment by webtrainingwheels** [comment]
Related: https://github.com/wp-media/wp-rocket/issues/1196

**Comment by Tabrisrp** [comment]
Yes it's most likely because of Jetpack CDN function
