### ISSUE TITLE
Proposal: Apply Lazyload Background on <span> tag 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1649]
A customer reported the Lazyload wasn't applied on his website.

After checking on PageSpeed insight, we can have the list of all images which aren't lazyloaded:

- PageSpeed Report: https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Ftollwear.gr%2Fshop%2F%25CE%25B3%25CF%2585%25CE%25BD%25CE%25B1%25CE%25B9%25CE%25BA%25CE%25B1%2Faxesouar-gunaika%2Ftsantes-gunaika%2F%25CF%2580%25CE%25BF%25CF%2581%25CF%2584%25CE%25BF%25CF%2586%25CE%25BF%25CE%25BB%25CE%25B9-replay-018563-blood-red%2F
- Website URL: https://tollwear.gr/shop/%CE%B3%CF%85%CE%BD%CE%B1%CE%B9%CE%BA%CE%B1/axesouar-gunaika/tsantes-gunaika/%CF%80%CE%BF%CF%81%CF%84%CE%BF%CF%86%CE%BF%CE%BB%CE%B9-replay-018563-blood-red/

The reason is the theme a a plugin is using background images on <span> tag.

Do we have a specific reason to not apply it on <span> tag too?

**Comment by arunbasillal** [comment]
Another website where the background images were in a `span` instead of `div` - https://secure.helpscout.net/conversation/835933669/105471/

**Comment by GeekPress** [comment]
Another ticket:
https://secure.helpscout.net/conversation/849384916/107390/
