### ISSUE TITLE
Minify + mandatory cookies

### ISSUE THREAD

**Issue by timersys** [wp-media/wp-rocket#1650]
When using the mandatory cookies function from a third party such as [GeotargetingWP ](https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/plugins/geotargetingwp.php) the cache on the first-page load fails until the cookies are set. That's right, for page cache, but minified scripts and assets should still work as is not compromised by cookies.

**To Reproduce**
1. Enable any third party plugin with required cookies
2. Get a clean browser and do a first load of page
3. Cache is disabled and files are not minified

**Expected behavior**
Cache is still disabled but js and css are minified

**Comment by mariamishenina** [comment]
+1 for this issue, kindly waiting for the solution

**Comment by GeekPress** [comment]
Duplicate of #2713
