### ISSUE TITLE
Proposal: make htaccess permissions warning less ominous

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1651]
![WP_Rocket_‹_WordPress_Themes_—_WordPress](https://user-images.githubusercontent.com/1043076/56327719-8a696c00-6130-11e9-943e-0bcb24788fde.jpg)

This admin notice leads people to believe that WP Rocket will not function without htaccess permission. That can lead to some panic, and even refund requests:
https://secure.helpscout.net/conversation/827250883/104247?folderId=377611#thread-2314448219

Since the htaccess file is not _required_ for WP Rocket to function, maybe we can tone it down? 
- Change it to yellow instead of red
- Modify the wording to communicate that while the htaccess rules are helpful, they are not required

**Comment by vmanthos** [comment]
A related ticket:

https://secure.helpscout.net/conversation/829579207/104605/

**Comment by arunbasillal** [comment]
@webtrainingwheels Please see how this sound:

`WP Rocket could not write into .htaccess due to missing writing permissions. For optimum performance, adding the following lines into your .htaccess is recommended`

**Comment by arunbasillal** [comment]
Copy @webtrainingwheels suggested - https://wp-media.slack.com/archives/G8L4EE8N9/p1559754346003800?thread_ts=1559728359.002200&cid=G8L4EE8N9

```
WP Rocket could not modify .htaccess due to missing writing permissions.
Troubleshoot: how to make system files writeable
Don't worry, WP Rocket's page caching and settings will still function correctly.
For optimal performance, adding the following lines into your .htaccess is recommended (not required):
```

**Comment by WordPresseur** [comment]
FR translation:
```
WP Rocket n'a pas pu modifier le fichier .htaccess en raison d’un défaut de permissions en écriture.
Dépannage : comment rendre les fichiers système inscriptibles
Ne vous inquiétez pas, la mise en cache des pages et les réglages de WP Rocket fonctionneront toujours correctement.
Pour des performances optimales, il est recommandé d'ajouter les lignes suivantes dans votre fichier .htaccess (pas obligatoire) :
```
