### ISSUE TITLE
Beacon from Mobile Can't Be Closed

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#1653]
A customer (from Twitter) is reporting an issue on the usability of the beacon from mobile.
After they open the beacon to search for a doc, they can't close the pop-up which takes the whole screen.
The button to close the pop-up doesn't appear.
The only solution is to go back to the previous page of the browser, but this takes you out from the settings page.

I tested it from my Android phone, and experienced the same problem, see screenshot below:
https://jmp.sh/bkUUdVn

**Comment by ernee** [comment]
@Tabrisrp applied some adjustments, and per my testing on Andriod, there is now a "Close" button at the top:
![Screenshot_20190418-092752](https://user-images.githubusercontent.com/8108643/56377195-b03d5200-61be-11e9-8938-b72d0607a252.png)

@AliceOrru could you confirm if you and the user also see this? Thank you!

**Comment by AliceOrru** [comment]
@ernee thanks a lot! It works on my end, going to write to the customer, too :)
