### ISSUE TITLE
Critical CSS showing incorrect characters in place of symbol ">".

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#1654]
**URL**
Any. Example: http://mega.wp-rocket.me/.

**Steps to reproduce**
1. Edit theme's stylesheet with the code. Example: `li>ul{margin-bottom:0}`.
2. Generate Ctritical Path CSS.
3. See the rocket-critical-css style from source code.
4. Look for `ul{margin-bottom:0}`
5. See:
![2019-04-16_11-55](https://user-images.githubusercontent.com/23031592/56229036-a42a8680-603e-11e9-890b-8a77ac5a7c4d.png)
6. `>` was changed to `&gt;`. 

**Note**
Customer's Addendum: The previous version (version 3.2.6) didn't have this problem.

**Ticket**
https://secure.helpscout.net/conversation/825091390/103847/

Thanks a lot!

**Comment by arunbasillal** [comment]
Related conversation - https://wp-media.slack.com/archives/C08N8J6VC/p1555589790200800?thread_ts=1555582852.198100&cid=C08N8J6VC

Work of `wp_kses`
