### ISSUE TITLE
WP Engine: Whitescreen after copy to new location

### ISSUE THREAD

**Issue by cryptotinker** [wp-media/wp-rocket#1655]
**Version and environment**
- Version tested: 3.3.1.1
- Host: WP Engine

**Describe the bug**
After copying a site to a new location with WP-Rocket enabled, the new site whitescreens. Errors will not appear in the site's error logs because the failure is occurring at the source site from the copy rather than the destination site that's whitescreening. The errors specifically pertain to a request made to /wp-rocket/inc/classes/Buffer/class-cache.php - this is only occurring because the request is to the origin site and permission is being denied.

**To Reproduce**
1. Copy site to new environment (in my case I copied from a live WP Engine site to it's staging equivalent.
2. New site whitescreens immediately after the copy is complete. 

**Additional context**
The /wp-content/advanced-cache.php contains hard coded links to the original site that was copied from:

```
<?php
defined( 'ABSPATH' ) || die( 'Cheatin&#8217; uh?' );

define( 'WP_ROCKET_ADVANCED_CACHE', true );

if ( version_compare( phpversion(), '5.4' ) >= 0 ) {

	spl_autoload_register(
		function( $class ) {
			$rocket_path    = '/nas/content/live/{SOURCE_INSTALL_NAME}/wp-content/plugins/wp-rocket/';
			$rocket_classes = [
				'WP_Rocket\\Buffer\\Abstract_Buffer' => $rocket_path . 'inc/classes/Buffer/class-abstract-buffer.php',
				'WP_Rocket\\Buffer\\Cache'           => $rocket_path . 'inc/classes/Buffer/class-cache.php',
				'WP_Rocket\\Buffer\\Tests'           => $rocket_path . 'inc/classes/Buffer/class-tests.php',
				'WP_Rocket\\Buffer\\Config'          => $rocket_path . 'inc/classes/Buffer/class-config.php',
				'WP_Rocket\\Logger\\HTML_Formatter'  => $rocket_path . 'inc/classes/logger/class-html-formatter.php',
				'WP_Rocket\\Logger\\Logger'          => $rocket_path . 'inc/classes/logger/class-logger.php',
				'WP_Rocket\\Logger\\Stream_Handler'  => $rocket_path . 'inc/classes/logger/class-stream-handler.php',
				'WP_Rocket\\Traits\\Memoize'         => $rocket_path . 'inc/classes/traits/trait-memoize.php',
			];

			if ( isset( $rocket_classes[ $class ] ) ) {
				$file = $rocket_classes[ $class ];
			} elseif ( strpos( $class, 'Monolog\\' ) === 0 ) {
				$file = $rocket_path . 'vendor/monolog/monolog/src/' . str_replace( '\\', '/', $class ) . '.php';
			} elseif ( strpos( $class, 'Psr\\Log\\' ) === 0 ) {
				$file = $rocket_path . 'vendor/psr/log/' . str_replace( '\\', '/', $class ) . '.php';
			} else {
				return;
			}

			if ( file_exists( $file ) ) {
				require $file;
			}
		}
	);

	if ( ! class_exists( '\WP_Rocket\Buffer\Cache' ) ) {
		if ( ! defined( 'DONOTROCKETOPTIMIZE' ) ) {
			define( 'DONOTROCKETOPTIMIZE', true ); // WPCS: prefix ok.
		}
		return;
	}

	$rocket_config_class = new \WP_Rocket\Buffer\Config(
		[
			'config_dir_path' => '/nas/content/live/{SOURCE_INSTALL_NAME}/wp-content/wp-rocket-config/',
		]
	);

	( new \WP_Rocket\Buffer\Cache(
		new \WP_Rocket\Buffer\Tests(
			$rocket_config_class
		),
		$rocket_config_class,
		[
			'cache_dir_path' => '/nas/content/live/{SOURCE_INSTALL_NAME}/wp-content/cache/wp-rocket/',
		]
	) )->maybe_init_process();;
} else {
	define( 'WP_ROCKET_ADVANCED_CACHE_PROBLEM', true );
}

```

This in itself isn't directly the cause of the white screen though, though deleting `/wp-content/advanced-cache.php` will restore the site. 

The `\WP_Rocket\Buffer\Cache` class is further referencing a domain-specific file set in `/wp-content/wp-rocket-config/`. The old `/wp-content/advanced-cache.php` will only break the site if this folder doesn't contain the correct destination domain config file, ie. `/wp-content/wp-rocket-config/newsite.com.php`.

The file will be called "DOMAIN.com.php" and contains domain-specific values and keys. After a copy, you will see a file named after the original site but not the new destination equivalent. It looks like this:

```
$rocket_cookie_hash = 'a52a602dxxxxxxxxxxx6cbbdcde';
$rocket_logged_in_cookie = 'wordpress_logged_in_a52a602d2xxxxxxxxxx06cbbdcde';
$rocket_cache_mobile_files_tablet = 'desktop';
$rocket_cache_mobile = 1;
$rocket_cache_ssl = 1;
$rocket_cache_reject_uri = '/(.+/)?feed/?|/(index\.php/)?wp\-json(/.*|$)';
$rocket_cache_reject_cookies = 'wp-postpass_|wptouch_switch_toggle|comment_author_|comment_author_email_';
$rocket_cache_reject_ua = 'facebookexternalhit';
$rocket_cache_query_strings = array();
$rocket_secret_cache_key = '5cbdxxxxxxxxxx37992';
$rocket_do_caching_mobile_files = 0;
$rocket_cache_mandatory_cookies = '';
$rocket_cache_dynamic_cookies = array();
```

**QUICK FIX**
Delete `/wp-content/advanced-cache.php`. On the next admin login with WP-Rocket enabled, the advanced-cache.php file will be regenerated correctly, along with the domain-specific config file at wp-content/wp-rocket-config/ (ensure file permissions are set correctly or WP-Rocket won't be able to write it).

**POTENTIAL LONG TERM FIX**
Perhaps enabling an environment variable would stop the request from firing if the domain/file path doesn't match on the new environment.

**Comment by WordPresseur** [comment]
It looks like it’s not fixed: https://secure.helpscout.net/conversation/867035679/109925?folderId=1213662
