### ISSUE TITLE
Database optimization: List of optimized items reports incorrect totals for Post Cleanup

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#1657]
Before and After screenshots are the easiest way to make this clear:

Before, there are 2 Revisions and 1 Auto Draft to be purged:

<img width="325" alt="3 3 1 1-before" src="https://user-images.githubusercontent.com/44367/56504671-e80a0980-64de-11e9-85f4-c90c2ab809d7.png">

After, those items are gone from the Post Cleanup section, but the _List of optimized items_ reports that 0 were removed:

<img width="541" alt="3 3 1 1-after" src="https://user-images.githubusercontent.com/44367/56504694-fb1cd980-64de-11e9-90e0-3960aaaa12ff.png">

While I don't have a screenshot showing this issue for Trashed Posts, I do recall observing the same issue for those too.

What I did not see was that any items other than those in the Post Cleanup section were affected; however, very few of the other items have values to begin with in my installation, so I don't have the ability to test them fully to confirm that they're not affected, too.

NOTE: I've tested this in 3.26, 3.3 and 3.3.1.1 -- and **3.3** is where the misbehavior was apparently introduced.

**Comment by piotrbak** [comment]
Looks like there might be a problem when WP Rocket is not able to delete transients using the **All Transients** setting. 

Example: There are 24 transients in the database after the optimization process WP Rocket claims that 24 were deleted but they're still showing up on the UI and also in the database itself.

Screencast:
https://jmp.sh/lMcCOnP

Records that match the %_transient_% in the wp_options table:
https://jmp.sh/dsFtaVV
