### ISSUE TITLE
Show conflict notice when Hummingbird is active

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1658]
https://wordpress.org/plugins/hummingbird-performance/
https://premium.wpmudev.org/project/wp-hummingbird/

It has some non-optimization related features which could still be used. So the notice should probably be a yellow one with info about duplicate options, rather than a red one.

**Comment by arunbasillal** [comment]
@Tabrisrp 

The Gzip compression rules were in the .htaccess, but that notice did not show up. 
Everything else worked. You can see it here - http://mega.wp-rocket.me/wp-admin/admin.php?page=wphb-gzip

Also it looks like it's only written for the free version of Hummingbird. Is that correct?

**Comment by Tabrisrp** [comment]
I only tested with the free version, not the pro as we don't have a copy of it.

**Comment by arunbasillal** [comment]
@webtrainingwheels Seeking your advice on this. Shall we buy a license and include the pro version as well? Probably much easier doing it now than having to come back to it again in the future.

**Comment by webtrainingwheels** [comment]
@arunbasillal I agree it would be ideal to handle both versions from the start of possible
