### ISSUE TITLE
Critical Path CSS and backslashes in CSS not playing nicely

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1659]
Dear Caspar brought this to our attention. 

Input: `content: '\203B\00A0';`
Debug tool output: `content: '\203B\00A0';`
Output written to file after `wp_strip_all_tags` : `content:'3B</title>A0';`

Main mega site has the following style in `style.css` if you want to test it out. 

```
.main-navigation .main-menu > li.menu-item-has-children > a:after,
.main-navigation .main-menu > li.menu-item-has-children .menu-item-has-children > a:after {
  content: '\203B\00A0';
  display: none;
}
```

Ticket: https://secure.helpscout.net/conversation/834293654/105222?folderId=1724284
Slack: https://wp-media.slack.com/archives/C08N8J6VC/p1555582852198100

**Comment by arunbasillal** [comment]
The reason why the output is weird `3B</title>A0` is because of the `preg_replace` here: 

https://github.com/wp-media/wp-rocket/blob/7de6e7024760c4e4021d09e335c59005f30d3c33/inc/classes/subscriber/Optimization/class-critical-css-subscriber.php#L344

Remy confirmed this: https://regex101.com/r/yooBLR/1

**Hotfix that worked for me:** 

- Remove `wp_strip_all_tags` here: https://github.com/wp-media/wp-rocket/blob/81a8cbd50e026142322332b4e85de1599ab55219/inc/classes/optimization/CSS/class-critical-css-generation.php#L128
- So that line becomes `$cpcss_content = $job_data->data->critical_path;`
- Before this line: https://github.com/wp-media/wp-rocket/blob/7de6e7024760c4e4021d09e335c59005f30d3c33/inc/classes/subscriber/Optimization/class-critical-css-subscriber.php#L344
- Add `$critical_css_content = str_replace( "\\", "\\\\", $critical_css_content );`

**Comment by Tabrisrp** [comment]
It's probably not necessary to remove `wp_strip_all_tags()`, the important thing is to escape the backslash character.

**Comment by arunbasillal** [comment]
@Tabrisrp You are right. I tested this on our mega test site without removing `wp_strip_all_tags`. 

Updated the hotfix and the title.
