### ISSUE TITLE
Purge the cache of a specific URL and a specific user 

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#166]
Add a function to purge the cache of a specific URL for a determined user.

Asked by a customer here: https://secure.helpscout.net/conversation/251283143/22322/?folderId=628132

**Comment by Tabrisrp** [comment]
@arunbasillal @GeekPress Do we see much value from adding a function for that?

From a technical standpoint it's not too complicated, but I want to make sure we feel it brings enough value to dedicate dev time for it.

**Comment by arunbasillal** [comment]
This seems too niche of a feature request. And we do not seem to have very many requests from users based on the inactivity in this issue in the last 4 years. 

If its complicated, I guess it's safe to `wontfix`

**Comment by Tabrisrp** [comment]
Well it's not complicated, but if it's going to be very rarely used, we could allocate the same dev time to something more impactful.

**Comment by arunbasillal** [comment]
Sorry I misread, I have asked this to our support team [here](https://wp-media.slack.com/archives/C08N8J6VC/p1591635021052600).

**Comment by arunbasillal** [comment]
Camila pointed out that we have had some requests for this. 

- https://secure.helpscout.net/conversation/284811206/27824/
- https://secure.helpscout.net/conversation/551180035/63856/

We used to have this card - https://trello.com/c/hDZ2exxG/169-purge-cache-for-a-specific-url-and-a-specific-user
Not sure if we backed up the data before it was deleted. Any idea @GeekPress ?

**Comment by GeekPress** [comment]
> Not sure if we backed up the data before it was deleted. Any idea @GeekPress ?

The card on Trello had no vote.

> Camila pointed out that we have had some requests for this.

The requests were done in 2016 and 2018. It doesn't seem to have a lot of interest from our users about that.

**Comment by arunbasillal** [comment]
@GeekPress I agree. This is your call now. The whole requirement is very "niche". It's best not to complicate our code with features that doesn't have much use.

**Comment by GeekPress** [comment]
Ok, then let's close it for now ;)
