### ISSUE TITLE
Proposal: Detect Jetpack mobile theme

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1661]
If it's possible to detect when the Jetpack mobile theme is active, we could automatically activate our separate mobile cache option to prevent conflicts, or at least show an admin notice about it.

**Comment by arunbasillal** [comment]
Can be handled similar to this - https://jmp.sh/5V00E7I

Related code - https://github.com/wp-media/wp-rocket/blob/83dd655946f6f0a61f4b29b4dfcfa5ab3553bbb4/inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php#L286-L297
