### ISSUE TITLE
Auto-detect SSL migration and set $rocket_cache_ssl = 1;

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1662]
A lot of these migrations lead to a not cached/optimized website because config file keeps `$rocket_cache_ssl = 0;`.

WP Rocket should be able to detect SSL migration and rebuild its config file to set `$rocket_cache_ssl = 1;` automatically.

Or at least show an admin notice to deactivate/reactivate WP Rocket

**Comment by webtrainingwheels** [comment]
related: https://github.com/wp-media/wp-rocket/issues/1193
