### ISSUE TITLE
Issue with Elementor + CDN + LazyLoad

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1677]
- the image on the CDN was not the correct one, because the elementor resize was happening after the CDN rewrite
- the lazyload was referencing the incorrect image because it was applied before the CDN rewrite

- https://secure.helpscout.net/conversation/835660195/105414/
- https://secure.helpscout.net/conversation/826535990/104146/

**Comment by webtrainingwheels** [comment]
related: 
https://github.com/wp-media/wp-rocket/issues/1129
@Tabrisrp do these look like duplicates to you, so the fix should close both issues?

**Comment by Tabrisrp** [comment]
Yes indeed #1129 will be closed by #1740
