### ISSUE TITLE
Combine Google fonts files causing error 400

### ISSUE THREAD

**Issue by cdvv7788** [wp-media/wp-rocket#1681]
**Describe the bug**
When I check the option "Combine google fonts files", a parameter is added to the generated url: subset=,,,
This causes the request to fail with code 400

**To Reproduce**
1. Go to 'wp-admin/options-general.php?page=wprocket#file_optimization'
2. Check the option to combine Google fonts files
3. Save changes
4. Bits of your site where the google font is required will not work properly

**Expected behavior**
A single google fonts call is made, combining everything into a single request without issues

**Additional context**
The generated request is:
https://fonts.googleapis.com/css?family=Roboto:300,400,700%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CRoboto:700%7CRoboto:300,400,700%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CRoboto:700&subset=,,,,,,,
If you remove the subset bit, it doesn't raise the issue tho:
https://fonts.googleapis.com/css?family=Roboto:300,400,700%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CRoboto:700%7CRoboto:300,400,700%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CRoboto:700

**Comment by Tabrisrp** [comment]
Hi,

Can you provide the original HTML/list of Google Fonts loaded on the page where you had the issue?

This will give us a test case to replicate and fix the issue.

**Comment by cdvv7788** [comment]
After disabling the option, I only see this one:
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700%7CRoboto:300,400,700%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CPT+Serif:700%7CRoboto:400,700,500,300,100%7CRoboto:700%7CRoboto:700" media="all">

**Comment by arunbasillal** [comment]
Related tickets:

- https://secure.helpscout.net/conversation/788643761/98349/
- https://secure.helpscout.net/conversation/754879857/93093/
- https://secure.helpscout.net/conversation/848019263/107108/

**Comment by Tabrisrp** [comment]
Duplicate of #1713
