### ISSUE TITLE
LazyLoad updated file causing images to break

### ISSUE THREAD

**Issue by nicomollet** [wp-media/wp-rocket#1684]
Hello,

**Describe the bug**
On my frontend, LazyLoad JS file is 404 not found.
Which is causing all my images to stay hidden :(

**To Reproduce**
My website just auto updated to WP Rocket 3.3.2, which has a new version of LazyLoad (11.0.6).
Cache still has the reference to the old LazyLoad JS file `/wp-content/plugins/wp-rocket/assets/js/lazyload/11.0.3/lazyload.min.js`

**Expected behavior**
Should not have 404, maybe automatically empty the cache after updating WP Rocket and/or that important JS file. Or keep the old lazyload file to make the images work until the cache is refreshed.
Indeed, empty the cache fixed the error but you should prevent this from happening.
Thank you

**Screenshots**
![updatelazyload](https://user-images.githubusercontent.com/108828/57144450-6610bf00-6dc1-11e9-84b0-e6002ce7114f.PNG)

**Comment by Tabrisrp** [comment]
The upgrade process does include a call to the clean domain function: https://github.com/wp-media/wp-rocket/blob/master/inc/admin/upgrader.php#L412

Did you update the plugin from WP admin?

**Comment by nicomollet** [comment]
WP Rocket auto updated through background updates. No manual action.
Does this help?

**Comment by GeekPress** [comment]
We are keeping the previous version when we implement a new version of the script to avoid this kind of problem.

I'm closing this issue as it should not happen again.
