### ISSUE TITLE
Proposal : Remove SSL Cache option and auto-apply it.

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1685]
Here the story of the SSL Cache option:

At the beginning, WP Rocket didn't have an option to cache SSL pages. These pages were automatically excluded from the cache.

At this period SSL was just used on checkout pages for e-commerce website. We didn't auto-exclude these pages automatically yet like we can do.

We added an option for SSL Cache to avoid these issues. People who used SSL on few pages could decide to apply the cache or not.

A couple of time later, we decide to auto-exclude cart & checkout pages. 

Then Google recommended to apply SSL on all websites. Some times later, the SSL options make more sense to be auto-activated if we detected SSL on the general settings URL.

Now, people doesn't have anymore mixed pages. I mean some in non-ssl and other in ssl. You have SSL or not on all your pages.

So, now we could have no difference between SSL and non-SSL website. The option is useless and caching should be applied whatever we have SSL or not.

It will help us to avoid this kind of ticket when people as non-ssl in their general setting but using something else for applying SSL on their website:
https://secure.helpscout.net/conversation/843383300/106384/

**Comment by arunbasillal** [comment]
Makes sense. We could in fact turn the option into a filter so that even if someone (for whatever reason) wanted to not cache all pages with ssl, they could do it.

**Comment by Tabrisrp** [comment]
Related #1193
