### ISSUE TITLE
Multisite, preload queries are clogging up database

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1686]
We are using the following query to check if the preload batch is empty:
**SELECT COUNT(*) FROM wp_sitemeta WHERE META_KEY LIKE 'rocket_preload_batch_%'**

On bigger multisite environments, wp_sitemeta might grow pretty much (in this specific case it's 500k records). 

This table is shared between all blogs in the network. Each blog that uses the preload feature is looking for the same string in the wp_sitemeta table. It means that if preload is not finished on site A, the count will return a value greater than 0 on site B too. It can lead to resource leaks.

Related ticket:
https://secure.helpscout.net/conversation/842897231/106291?folderId=2415573
https://secure.helpscout.net/conversation/484493133/55183/

Slack convo:
https://wp-media.slack.com/archives/C43T1AYMQ/p1556901524002000

The solution used by WooCommerce here will not work, as wp_sitemeta is shared between all blogs:
https://github.com/woocommerce/woocommerce/pull/18060

**Comment by Tabrisrp** [comment]
The solution made in WC should work too, as we would have an identifier for each website, so instead of the default query:
`SELECT COUNT(*) FROM wp_sitemeta WHERE META_KEY LIKE 'rocket_preload_batch_%'`

We would have:
`SELECT COUNT(*) FROM wp_sitemeta WHERE META_KEY LIKE 'rocket_2_preload_batch_%'`

The blog ID is integrated into the identifier for the batch, which will make the SQL request more specific and prevent the issue.

**Comment by JohnTorvik** [comment]
Related:
https://secure.helpscout.net/conversation/1245953019/184760?folderId=3773397

**Comment by rasmustaarnby** [comment]
This is still an issue. I just had to delete just over 3 million rows with `rocket_preload_batch_%`, which were causing the sitemeta table to grow to an unreasonable ~1.7 GiB

The quick solution was to delete the rows using: 
```
DELETE FROM poa_sitemeta WHERE meta_id LIKE "rocket_partial_preload_batch%"
```
I'm guessing this could also relate to background processes being terminated untimely. Perhaps it would make sense to implement a fallback job to clean up old entries?

**Comment by NataliaDrause** [comment]
Likely related: https://secure.helpscout.net/conversation/1419240643/237605?folderId=3864740

**Comment by piotrbak** [comment]
The issue is not relevant anymore starting from 3.12 update of the WP Rocket, since we're not using WP Background Processing anymore.
