### ISSUE TITLE
Incompatibility between ShortPixel Global WebP rewrite and WPR Lazyload

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#1693]
Shortpixel uses the `init` hook with a priority of `1` to call its output buffer function to rewrite the default `img` tag to the `picture` tag.

Meanwhile, WP Rocket uses the `template_redirect` with a priority of `2`.

This means Shortpixel rewrite happens after WP Rocket rewrite, producing unexpected markup, and breaking lazyload.

Shortpixel also provides a solution based on WP hooks, and this one works well with our own buffering.

2 solutions here:
- ShortPixel changes the hook they use, to use `template_redirect` with a priority higher than `2`.
- We add a way to change the default hook and priority we use, to make sure we perform our optimizations after ShortPixel

**Comment by arunbasillal** [comment]
Note from version doc proposal - "Remy noted that this was a little risky in terms of how it could produce issues, and so far has only produced 2 tickets. So we decided to leave it out of 3.3.4"

**Comment by djped** [comment]
Just to add (I think this is the issue I've been hit with). Shortpixel AI CDN rewrite just does nothing when WP Rocket Lazyload is enabled.

Shortpixel AI (Adaptive Images) includes Lazy Loading itself. All you have to do is switch the WP Rocket option off and Shortpixel AI starts to work. Maybe a 3rd option is to notify and disable WP Rocket lazy load when Shortpixel AI is detected as enabled?

**Comment by nathanaelphilip** [comment]
i would like to suggest that Rocket WP allow the option to serve up WebP with the <picture> element when you‘re not using the Caching portion of Rocket WP. I’m more than happy to jump in and help out!

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1181425003/169514/

**Comment by JohnTorvik** [comment]
Related ticket: https://secure.helpscout.net/conversation/1386897351/228672?folderId=273766

**Comment by piotrbak** [comment]
Just tested this one, I wasn't able to reproduce it. Closing it, we'll reopen if the issue comes back.
