### ISSUE TITLE
WP Rocket deactivation fails on Flywheel

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1703]
Flywheel has a specific process to allow their customers to enable the `WP_CACHE` constant:
https://getflywheel.com/wordpress-support/how-to-enable-wp_cache/

It also disallows editing the `wp-config.php`:
https://getflywheel.com/wordpress-support/how-do-i-make-changes-to-my-wp-config-php-file/

When someone tries to temporarily deactivate WP Rocket, they get an error and the only option is to delete the plugin.

To avoid that we can:
- Check if the host is Flywheel.
- Skip the `wp-config.php` writeable check here: https://github.com/wp-media/wp-rocket/blob/240533b8483c5dd35db882ff2ce48aaf88cf8543/inc/main.php#L115-L118
- Display an admin warning to remind the customer to disable `WP_CACHE`, if this is a permanent deactivation.

**Comment by Tabrisrp** [comment]
They should still be able to force deactivation from the notice I believe?

**Comment by arunbasillal** [comment]
I am wondering if Flywheel provides an API for this. I will ask them about this when I consult with them about `Fastly caching`.

**Comment by piotrbak** [comment]
We received no feedback about that issue at all. Going to close it

**Comment by carasmo** [comment]
This still happens when you try to deactivate. Now we're using Perfmatters.io which got better results than WPRocket and FlyingPress.
