### ISSUE TITLE
Disable LazyLoad options if Avada & Autoptimize LazyLoad is activated

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1707]
Avada and Autoptimize as an option to apply LazyLoad on images.

It can't cause a conflict with our LazyLoad if both are activated.

Like we do with HTML/CSS/JS optimization and Autoptimize, we could disable our Lazyload option and display a text to ask the user to disable the option on Avada or Autoptimize

**Comment by arunbasillal** [comment]
**For Autoptimize:** 

It looks like we have to disable BOTH LazyLoad for images and iframes. I did a test on this page with YouTube embeds - http://mega.wp-rocket.me/nieuws/youtube-videos-arun/

When LazyLoad in AO was active, I got a console error and the YouTube embeds didn't show up. 

Proposed copy: 

`Lazyload is currently activated in Autoptimize. If you want to use WP Rocket’s LazyLoad, disable those options in Autoptimize.`

**For Avada**

LazyLoad for iframes worked okay even when LazyLoad for images was active. 

Tested here - http://mega.wp-rocket.me/avada/2019/05/16/youtube-videos-arun/
http://mega.wp-rocket.me/avada/wp-admin/post.php?post=11935&action=edit

We have to disable only LazyLoad for images in this case. 

Proposed copy:

`Lazyload for images is currently activated in Avada. If you want to use WP Rocket’s LazyLoad, disable those options in Avada.`
