### ISSUE TITLE
qTranslate-X integration option causing fatal error

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1712]
When qTranslate-X plugin is being used with **Function Name Compatibility**, switching languages in the backend causes a Fatal Error:
http://snippi.com/s/tr0ob7i

It happens because when this option is enabled, the **$fork** value is not set to **x**:
https://github.com/wp-media/wp-rocket/blob/master/inc/functions/i18n.php#L82

Which causes a call to undefined **qtrans_isEnabled** function here:
https://github.com/wp-media/wp-rocket/blob/master/inc/functions/i18n.php#L88

We could check for the existence of qTranslate or qTranslate-X using the is_plugin_active function instead.

Related ticket:
https://secure.helpscout.net/conversation/840166468/105964?folderId=2415573

**Comment by arunbasillal** [comment]
I think its safer to rely on the presence of `qtrans_isEnabled` or `qtranxf_isEnabled` to detect the plugin version.
