### ISSUE TITLE
Google Fonts display attribute compatibility with combine Google Fonts

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#1717]
Google updated their fonts with a new attribute `display` that can have the value of `swap` to display the default font until the Google fonts are loaded, instead of displaying no text.

WP Rocket combine Google Fonts option now needs to take this new attribute into account when combining the fonts found on the page.

**Comment by sandeepbek** [comment]
Is this added?

**Comment by Tabrisrp** [comment]
Closed by #1764
