### ISSUE TITLE
Use of undefined constant WP_ROCKET_FRONT_URL - assumed 'WP_ROCKET_FRONT_URL' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by fydy** [wp-media/wp-rocket#1735]
The wp-rocket version is 3.3.3.1, the server version is php7.2+apache2.4+mysql5.6, and the website front desk warns.
![image](https://user-images.githubusercontent.com/39726855/58062643-9a4ff200-7bad-11e9-832a-751075c8c6d8.png)

**Comment by arunbasillal** [comment]
In the latest version of WP Rocket we have made changes to how LazyLoad is implemented. Are you still seeing this issue @fydy ?

Thanks for your feedback.
