### ISSUE TITLE
Proposal: Auto-Excluding Dynamic Filenames (The7 theme)

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1736]
We have a documentation about how to exclude dynamic CSS files from The7 theme:
https://docs.wp-rocket.me/article/132-excluding-dynamic-filenames-the7-theme

To be avoid issues and be easer for our users, we could directly put the exclusions into the plugin.

**Comment by piotrbak** [comment]
@GeekPress Do you think we can close this issue?

Seems that there are no tickets about this at all:
https://secure.helpscout.net/search/?query=tag%3Athe7%20theme%20dynamic

**Comment by GeekPress** [comment]
@piotrbak Indeed, I think we can safely close it :D
