### ISSUE TITLE
Proposal: Auto-compatibility with YITH & WooCommerce Recently Viewed Products

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1738]
We have a documentation related to the compatibility with YITH & WooCommerce Recently Viewed Products widget:
https://docs.wp-rocket.me/article/852-making-wp-rocket-work-with-woocommerce-recently-viewed-products-widget

We could auto-include the exclusion by detecting if the widget is used or not. WP saves into the database the slug of used widget on the website.

We already have an helper plugin to adapt with the widget detection:
- https://github.com/wp-media/wp-rocket-helpers/blob/master/compatibility/wp-rocket-compat-yith-wc-recently-viewed/wp-rocket-compat-yith-wc-recently-viewed.php
- https://github.com/wp-media/wp-rocket-helpers/blob/master/compatibility/wp-rocket-compat-wc-recently-viewed-widget/wp-rocket-compat-wc-recently-viewed-widget.php

**Comment by webtrainingwheels** [comment]
FYI - it looks like we have to make the cookie mandatory here otherwise it will not be set on pages that have already been cached, and the Recently Viewed widget will not be displayed.  Our helper will be updated soon.

**Comment by vmanthos** [comment]
> it looks like we have to make the cookie mandatory here

I confirmed this is the case, at least for the WooCommerce widget.

>  Our helper will be updated soon.

I updated the respective helper plugin:
https://github.com/wp-media/wp-rocket-helpers/blob/eff956e0229cd9fd2e7df95a3daae720cb5733db/compatibility/wp-rocket-compat-wc-recently-viewed-widget/wp-rocket-compat-wc-recently-viewed-widget.php#L37
