### ISSUE TITLE
Footprint duplicated on WP Engine

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#1742]
On WP Engine sites, our caching footprint can appear **twice** in the HTML source:

```
<!-- This website is like a Rocket, isn't it? Performance optimized by WP Rocket. Learn more: https://wp-rocket.me -->
<!-- This website is like a Rocket, isn't it? Performance optimized by WP Rocket. Learn more: https://wp-rocket.me -->
```

_Ticket: https://secure.helpscout.net/conversation/852397839/107838_

**Comment by alfonso100** [comment]
I had a similar case here: https://mylittlethreads.com.au
WP Engine site, duplicated footer signature 

Ticket: https://secure.helpscout.net/conversation/847687364/107027/
The ticket issue was not related to the duplicated signature

**Comment by arunbasillal** [comment]
We have a compatibility with WP Engine where we add this footer 

https://github.com/wp-media/wp-rocket/blob/240533b8483c5dd35db882ff2ce48aaf88cf8543/inc/3rd-party/hosting/wpengine.php#L124-L136

We also have our standard footer

https://github.com/wp-media/wp-rocket/blob/1ffb4f447d6f6ed8f413cec1b1c88f10beb0dcc4/inc/classes/Buffer/class-cache.php#L374-L383

Could this be because both these are applied in these cases?

**Comment by Tabrisrp** [comment]
On WPEngine, the cache class should not be used at all since the advanced-cache.php file is now empty.

A duplicate footprint means the advanced-cache.php file was not correctly updated to be emptied. A deactivation/reactivation of the plugin will be enough to fix it.

**Comment by GeekPress** [comment]
As we don't seem to have anymore tickets about this problem, I'm closing it.

Feel free to reopen it if a new case is reported.

**Comment by DahmaniAdame** [comment]
Another case - https://secure.helpscout.net/conversation/1205291466/175747/

WP Rocket 3.6.1
Looks to be WP Engine too (Google Cloud servers)

**Comment by GeekPress** [comment]
@DahmaniAdame Could you ask to the user to deactivate / reactivate WP Rocket? It should fix the duplicate issue.

**Comment by DahmaniAdame** [comment]
@GeekPress they still didn't reply about the original issue they asked for. I sent a request to ask them to do it. I Will update accordingly.
