### ISSUE TITLE
WPML + Domain Per Language + Optimize CSS Delivery issue

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1756]
When working on WPML + Language Per Domain setup, there is technically one WordPress and many domains. Sites are sharing the same Critical CSS code and it can lead to some issues:

-Mixed content when CPCSS was generated on HTTP domain while other domains are HTTPS
-CORS problem when loading fonts from a different domain

**Expected behaviour**
We could add CORS rules to .htaccess and inform customer about the possible problem when we detect HTTP domain
**or**
Create a different set of Critical CSS for each domain

**Screenshots**
https://jumpshare.com/v/2iAvgR87axf0aOtzzKyA

**Comment by webtrainingwheels** [comment]
This issue still exists. The commit that closed it is unrelated. 

New case: 
https://secure.helpscout.net/conversation/1965737480/359306?folderId=377611

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2008215877/368260/

**Comment by piotrbak** [comment]
We didn't get enough feedback for it to be implemented. Feel free to reopen it if we'll receive more
