### ISSUE TITLE
Page exclusions are not working on NGINX, when our compatibility fix is applied

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1761]
We have a compatibility file for unusual NGINX configurations here:
https://github.com/wp-media/wp-rocket/blob/13b9b006c54b92e0d301204b006462921e9085e8/inc/3rd-party/hosting/nginx.php

That adds a `q` in the `$rocket_cache_query_strings` variable of the config file (wp-rocket-config folder).

I debugged `cache-tests.php` (https://pastebin.com/0URBxHsb) and I got this:
```
[2019-06-05 06:39:38] Query Params before processing:
Array
(
    [q] => /cart/
)

[2019-06-05 06:39:38] Query Params after processing:
Array
(
    [q] => /cart/
)

[2019-06-05 06:39:38] URI being processed: /cart/?q=%2Fcart%2F
[2019-06-05 06:39:38] URIs not to cache: /(.+/)?feed/?|/(?:.+/)?embed/|/checkout/(.*)|/cart/|/my-account/(.*)|/wc-api/v(.*)|/(index\.php/)?wp\-json(/.*|$)
```

The URI being processed has the `q=%2Fcart%2F` query string appended, which seems to elude the RegEx we are using to exclude URIs:
https://github.com/wp-media/wp-rocket/blob/35533b0069b2f1313e30c2b310856daf47fd9880/inc/classes/Buffer/class-tests.php#L567

Check here: https://regex101.com/r/T14S5G/1 and here: https://www.phpliveregex.com/p/smz

**Related ticket**
https://secure.helpscout.net/conversation/867363003/109979?folderId=2135277

**Comment by fabianskibr** [comment]
I looked into my cache folder and saw that the folders are being created the same way you described it. For example, the blog page was stored like this:

cache/wp-rocket/domain.com/blog
_q=%2f**blog**%2f

this is causing the cache not to be served directly by nginx with the configuration [rocket-nginx ](https://github.com/SatelliteWP/rocket-nginx) because it looks for the file but do not think ...

Any solution for this? Were you able to resolve with any changes?

**Comment by vmanthos** [comment]
@fabianskibr This has to do with a special NGINX configuration which is used on some servers including yours:

```
try_files $uri $uri/ /index.php?q=$uri&$args
```

This isn't compatible with the rocket-nginx configuration you've linked to.

You should contact your host and ask them if this is something they can change for you.

**Comment by fabianskibr** [comment]
Hi, thanks for answering!

Yes, I can change this.
What change would be needed?

**Comment by piotrbak** [comment]
Sounds to be too edgy for it to be implemented anywhere soon.
