### ISSUE TITLE
CNAME for JS files in CDN feature won’t replace the LazyLoad script

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1768]
If you choose to replace your domain by your CDN CNAME only for JS files, our Lazyload URL script won’t be replaced because of https://github.com/wp-media/wp-rocket/blob/240533b8483c5dd35db882ff2ce48aaf88cf8543/inc/classes/subscriber/Optimization/class-lazyload-subscriber.php#L141

**Comment by arunbasillal** [comment]
Fixed by https://github.com/wp-media/wp-rocket/commit/46e3a8fbb2cf7af311ede36c11c70f9635e26562 I believe
