### ISSUE TITLE
critical css and divi video background

### ISSUE THREAD

**Issue by wassy83** [wp-media/wp-rocket#1772]
**Before submitting an issue please check that you’ve completed the following steps:**
I'm on latest wp rocket 3.3.3.4 and latest divi theme 3.24 with latest google chrome

**Describe the bug**
When enabling critical css with the divi theme, I have a good speed boost, but randomly, if I have a background video applied to a module, this will make divi to calculate the wrong inline left margin of the video container(I think that this is calculated by divi js to center things on all devices)

from this:
`<div id="mep_0" class="mejs-container mejs-container-keyboard-inactive mejs-video" tabindex="0" role="application" aria-label="Video Player" style="width: 1903px; height: 594.688px; min-width: 0px; margin: 0px 0px 0px -951.5px;">`

to this:
`<div id="mep_0" class="mejs-container mejs-container-keyboard-inactive mejs-video" tabindex="0" role="application" aria-label="Video Player" style="width: 1903px; height: 594.688px; min-width: 0px; margin: 0px 0px 0px -10951.5px;">`

so the background will not be visible, cause the left margin will put out the video from the screen and not centered as I would expected. If I resize the browser window it will fix immediately.

You have to refresh several times the page to reproduce the issue.

I'm attaching some screen.

**To Reproduce**
1. add a background video to a module with divi theme
2. enable critical css in wp rocket
3. try to refresh the page several times
4. you will notice that background disappears

**Screenshots**
without critical css enabled
[https://imgur.com/a/MXxfaNT](https://imgur.com/a/MXxfaNT)

with critical css enabled
[https://imgur.com/a/d7ynb0k](https://imgur.com/a/d7ynb0k)

**Comment by wassy83** [comment]
if can helps I'm pretty sure that this is related to the jquery library http://fitvidsjs.com/

**Comment by piotrbak** [comment]
We didn't receive any feedback related to this markup and Critical CSS since that time. We'll reopen the issue if we'll have more feedback and data here.
