### ISSUE TITLE
CDN + srcset

### ISSUE THREAD

**Issue by lobin21** [wp-media/wp-rocket#1773]
It looks like current version and doesn't do regex on **srcset** attribute of the image tag:

<img width="975" alt="Screenshot 2019-06-07 at 14 22 15" src="https://user-images.githubusercontent.com/17177682/59107106-cef2d600-892f-11e9-8ce5-5e6e871afd89.png">
Original domain: www.confetti.co.uk
CDN: omg.imgix.net (this is set for Images only)

I was previously on 3.2.4 and it was working just fine. I'm not using LazyLoading

**Comment by kieran-wpmedia** [comment]
Related customer ticket: https://secure.helpscout.net/conversation/883147497/112946
The issue can be seen in the site logo and various other images

**Comment by Tabrisrp** [comment]
CDN on srcset is done on this filter https://github.com/wp-media/wp-rocket/blob/master/inc/front/cdn.php#L125

If the image is not using the default WP functions to be displayed and generate the responsive code, it's possible that it is skipped.

**Comment by Tabrisrp** [comment]
This should be fixed since version 3.4 and our rewrite of the CDN feature
