### ISSUE TITLE
SSL warning on LazyLoad placeholder image

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#1785]
LazyLoad placeholder output looks like this:

`<img class='avia_image ' src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20300%20300'%3E%3C/svg%3E" alt='' title='judd-dunagan-avatar' height="300"width="300" itemprop="thumbnailUrl" data-lazy-src="https://cdn.brightvessel.com/wp-content/uploads/2015/02/judd-dunagan-avatar-300x300.png" />
`

It uses `http` instead of `https`, so there is SSL warning message.

Reference ticket: https://secure.helpscout.net/conversation/875438588/111001/

**Comment by arunbasillal** [comment]
It seems that we have made a mistake in understanding this issue. 

What we failed to understand was that, these are not URI's but namespaces and need to be an exact match as mentioned in the spec - https://www.w3.org/TR/REC-xml-names/#NSNameComparison

There is a good explanation here - https://stackoverflow.com/a/39960091/8255629

And a reference here - https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course#Declaring_namespaces

Thanks @piotrbak in helping with research and finding all the information :)

**Comment by arunbasillal** [comment]
This was reverted in 3.3.5.2

**Comment by kieran-wpmedia** [comment]
I have a ticket related to this issue here: https://secure.helpscout.net/conversation/935651408/120176

**Comment by alfonso100** [comment]
Another customer asking about this: https://secure.helpscout.net/conversation/1164169812/165062/

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1469373461/251991/
