### ISSUE TITLE
Some CDATA Inline JS aren't detected and auto-exclude from Combine JS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1799]
I noticed sometimes some inline JS which are declared into a CDATA aren't auto-excluded.

This is a couple of time I noticed that since we have the alert. I though it was a edge case and found these 2 examples just today. I will report new one if I find.

Here two examples:

`<script type='text/javascript'>
/* <![CDATA[ */
var yith_wccl_general = {"ajaxurl":"\/?wc-ajax=%%endpoint%%","actionAddCart":"yith_wccl_add_to_cart","actionVariationGallery":"yith_wccl_variation_gallery","cart_redirect":"","cart_url":"https:\/\/www.samsonite.co.za\/basket\/","view_cart":"View Cart","tooltip":"1","tooltip_pos":"bottom","tooltip_ani":"fade","description":"1","add_cart":"Add to cart","grey_out":"","image_hover":"","wrapper_container_shop":"div.product.product-small","image_selector":"img.wp-post-image, img.attachment-woocommerce_thumbnail","enable_handle_variation_gallery":"1"};
var yith_wccl = {"attributes":"{\"attribute_pa_colour\":{\"descr\":\"\",\"type\":\"image\",\"terms\":{\"black\":{\"value\":\"http:\\\/\\\/www.samsonite.co.za\\\/wp-content\\\/uploads\\\/2018\\\/03\\\/sams_1041_cmbp.jpg\",\"tooltip\":\"black\"},\"granita-red\":{\"value\":\"http:\\\/\\\/www.samsonite.co.za\\\/wp-content\\\/uploads\\\/2018\\\/03\\\/sams_6546_poyu.jpg\",\"tooltip\":\"granita red\"},\"navy-blue\":{\"value\":\"http:\\\/\\\/www.samsonite.co.za\\\/wp-content\\\/uploads\\\/2018\\\/03\\\/sams_1598_popr.jpg\",\"tooltip\":\"navy blue\"},\"ocean-blue\":{\"value\":\"http:\\\/\\\/www.samsonite.co.za\\\/wp-content\\\/uploads\\\/2018\\\/03\\\/sams_1621_popr.jpg\",\"tooltip\":\"ocean blue\"},\"tangerine-red\":{\"value\":\"http:\\\/\\\/www.samsonite.co.za\\\/wp-content\\\/uploads\\\/2018\\\/03\\\/sams_6270_popr.jpg\",\"tooltip\":\"tangerine red\"},\"white\":{\"value\":\"http:\\\/\\\/www.samsonite.co.za\\\/wp-content\\\/uploads\\\/2018\\\/03\\\/sams_1908_pu60.jpg\",\"tooltip\":\"white\"}}}}"};
/* ]]> */
</script>`

From here:
https://www.samsonite.co.za/flux-spinner-expandable-55cm-2/?nocache=1

The inline JS is inserted into the concatenated file:
https://www.samsonite.co.za/flux-spinner-expandable-55cm-2/

And

`<script type='text/javascript'>
/* <![CDATA[ */

var nextgen_lightbox_settings = {"static_path":"","context":"all_images_direct"};
var galleries = {};
galleries.gallery_f9ec67b37ad0b4de9baa88f227b43318 = {"id":null,"ids":null,"source":"galleries","src":"","container_ids":[],"gallery_ids":[],"album_ids":[],"tag_ids":[],"display_type":"photocrati-nextgen_basic_thumbnails","display":"","exclusions":[],"order_by":"sortorder","order_direction":"ASC","entity_ids":["512"],"tagcloud":false,"returns":"included","slug":"widget-ngg-images-2","sortorder":[],"display_settings":{"use_lightbox_effect":true,"images_per_page":1,"number_of_columns":"4","thumbnail_width":"150","thumbnail_height":"125","show_all_in_lightbox":false,"ajax_pagination":"1","use_imagebrowser_effect":false,"template":"\/var\/www\/vhosts\/leonardo.hosting\/pinodigennaro\/wp-content\/plugins\/nextgen-gallery\/products\/photocrati_nextgen\/modules\/widget\/templates\/display_gallery.php","display_no_images_error":1,"disable_pagination":true,"show_slideshow_link":false,"slideshow_link_text":"[Show as slideshow]","override_thumbnail_settings":0,"thumbnail_quality":"100","thumbnail_crop":1,"thumbnail_watermark":0,"ngg_triggers_display":"never","display_type_view":"default","_errors":[],"display_view":"default","maximum_entity_count":1,"image_type":"thumb","show_thumbnail_link":false,"image_width":160,"image_height":100,"widget_setting_title":"Immagine Casuale","widget_setting_before_widget":"<widget id=\"ngg-images-2\" name=\"ngg-images-2\" class=\"widget ngg_images\"><div class=\"hslice\" id=\"ngg-webslice\">","widget_setting_before_title":"<title>","widget_setting_after_widget":"<\/div><\/widget>","widget_setting_after_title":"<\/title>","widget_setting_width":160,"widget_setting_height":100,"widget_setting_show_setting":"thumbnail","widget_setting_widget_id":"ngg-images-2"},"excluded_container_ids":[],"maximum_entity_count":500,"__defaults_set":true,"_errors":[],"ID":"f9ec67b37ad0b4de9baa88f227b43318"};
galleries.gallery_f9ec67b37ad0b4de9baa88f227b43318.wordpress_page_root = "http:\/\/pinodigennaro.it\/8x8-forme-nello-spazio\/";
var nextgen_lightbox_settings = {"static_path":"","context":"all_images_direct"};
galleries.gallery_f9ec67b37ad0b4de9baa88f227b43318.captions_enabled = false;
/* ]]> */
</script>`

From here:
http://pinodigennaro.it/8x8-forme-nello-spazio/?nocache=1

The inline JS is inserted into the concatenated file:
http://pinodigennaro.it/8x8-forme-nello-spazio/

On smashingcoding.com I was able to replicate the issue for the first example by just copy and paste the code. But for the second example, the CDATA has been excluded.

**Comment by Tabrisrp** [comment]
In fact currently there is no auto-exclusion of the inline scripts wrapped in `CDATA`.

The auto-exclusion we have is for scripts registered with `wp_localize_script`, but if the inline scripts are inserted with a different method, they won't be auto-excluded.

**Comment by GeekPress** [comment]
What do we do here:
https://github.com/wp-media/wp-rocket/blob/master/inc/classes/optimization/JS/class-combine.php#L218

**Comment by Tabrisrp** [comment]
We match all scripts with content inside the `script` tags, with or without CDATA. But we discovered yesterday that there is an issue with the regEx, and some scripts might have not matched correctly, like the 2 above.

Updating the regEx should solve the issue.

**Comment by GeekPress** [comment]
Great news 👊
