### ISSUE TITLE
serving .gz files with gzip causes corruption in FF

### ISSUE THREAD

**Issue by tridoan** [wp-media/wp-rocket#1801]
**Describe the bug**
On wp-rocket 3.3.5 (and other versions), im getting a corrupted file when serving download files with .gz extension on FF v68.0b9

The .gz file that is downloaded does not fully download, or is corrupted, not sure--it results in the file not being usable. On Chrome however, the files download and opens just fine.

**To Reproduce**
1. On FF, go to our downloads page and click on a link that serves files ending in .gz
2. Try to open downloaded file, see OS error regarding file not being correct
3. Try steps above in, Chrome, and successfully open downloaded file

**Expected behavior**
FF should be able to download .gz files without issues

**Additional context**
I've determined that the error block in htaccess causing this issue is this:

`<IfModule mod_deflate.c>
    # Active compression
    SetOutputFilter DEFLATE
    # Force deflate for mangled headers
    <IfModule mod_setenvif.c>
        <IfModule mod_headers.c>
        SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
        RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
        # Don’t compress images and other uncompressible content
        SetEnvIfNoCase Request_URI \
        \.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g|mp4|webm|webp|pdf)$ no-gzip dont-vary
        </IfModule>
    </IfModule>
    # Compress all output labeled with one of the following MIME-types
    <IfModule mod_filter.c>
    AddOutputFilterByType DEFLATE application/atom+xml \
                                      application/javascript \
                                      application/json \
                                      application/rss+xml \
                                      application/vnd.ms-fontobject \
                                      application/x-font-ttf \
                                      application/xhtml+xml \
                                      application/xml \
                                      font/opentype \
                                      image/svg+xml \
                                      image/x-icon \
                                      text/css \
                                      text/html \
                                      text/plain \
                                      text/x-component \
                                      text/xml
    </IfModule>
    <IfModule mod_headers.c>
    Header append Vary: Accept-Encoding
    </IfModule>
</IfModule>`

However, even adding "gz" to the list of excluded file types does not work:

`SetEnvIfNoCase Request_URI \

		\.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g|mp4|webm|webp|pdf|gz)$ no-gzip dont-vary`

Any ideas?

edits: sorry cant get code format to work

**Comment by piotrbak** [comment]
@tridoan We haven't heard about any similar case during that time. I'm closing this issue then, if you feel that there's still a problem, please reopen this and provide us with some further details.
