### ISSUE TITLE
Support for Pixel Caffeine for our Facebook Pixel Add-on

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1802]
The Facebook Pixel add-on does not support the [Pixel Caffeine plugin](https://wordpress.org/plugins/pixel-caffeine/) we recommend [in this blog post](https://wp-rocket.me/blog/facebook-pixel-add-wordpress/)

Related discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1561017395006400

**Comment by piotrbak** [comment]
Another ticket with my findings:
https://secure.helpscout.net/conversation/1135310443/157628/

**Comment by NataliaDrause** [comment]
Same markup as in Piotr's ticket: https://secure.helpscout.net/conversation/1331092442/209782?folderId=3864740

It causes this error:
`Check that you're sending valid and unique values for the fbp, ip_address, user_agent parameters for your AddToCart event and that the data is normalized correctly.`

**Comment by GeekPress** [comment]
Closing this issue as Facebook Pixels add-on will be removed in WP Rocket 3.9
