### ISSUE TITLE
Proposal: Minify our Lazyload Inline JS script

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1804]
We have requests from customer who wants us to minify our LazyLoad Inline JS script.

We had 4 tickets about just for this week, here an example
- https://secure.helpscout.net/conversation/883475838/112994?folderId=343175

**Comment by sabrina-zeidan** [comment]
Another [one ](https://secure.helpscout.net/conversation/888907687/113750/)
