### ISSUE TITLE
Proposal: Update our Uncode compatibility.

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1806]
We fixed some conflicts with Uncode:
- https://github.com/wp-media/wp-rocket/pull/1689
- https://github.com/wp-media/wp-rocket/pull/1509

And we still had one:
- https://github.com/wp-media/wp-rocket/issues/1194

We had the issues because Uncode added a timestamp query string into the ver= when their Production mode option was turned off.

Since Uncode 2.10,  the theme detects if WP Rocket is active and turn off this option if Remove Query String or CSS / JS minification are activated.

We can update our Uncode compatibility by reverting:
- https://github.com/wp-media/wp-rocket/pull/1689
- https://github.com/wp-media/wp-rocket/pull/1509

And by forcing the Uncode Production Mode option to be off if the version is prior to 2.10

**Comment by vmanthos** [comment]
I've tested this on MEGA and I confirm that **Uncode 2.1.0** disables the production mode when any of these is enabled:

- Remove query strings from static resources
- CSS minification
- JavaScript minification

I also reverted #1689 and #1509 as @GeekPress suggested and everything worked as expected.
