### ISSUE TITLE
Multisite with Domain Mapping: Cache is not created

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1810]
The cache is not created when using WP Rocket on a multisite with domain mapping ([WordPress MU Domain Mapping](https://wordpress.org/plugins/wordpress-mu-domain-mapping/)) .

I debugged the `/wp-rocket/inc/functions/files.php` using this:
https://pastebin.com/gH2TYzq6

**Debug log:** http://snippi.com/s/4mordhq

The WP Rocket configuration filename is created like this:
https://github.com/wp-media/wp-rocket/blob/3fd199ed5dc05c080a691e747f0d8ef850e4e7e7/inc/functions/files.php#L200

On a multisite using domain mapping, the site is treated as a regular subfolder installation. This results in the config filename to be:
`example.com.example.php`

This fails here:
https://github.com/wp-media/wp-rocket/blob/3fd199ed5dc05c080a691e747f0d8ef850e4e7e7/inc/classes/Buffer/class-tests.php#L194-L201

and the cache is not created.

**Related ticket:**
https://secure.helpscout.net/conversation/886063430/113339/

**Similar issue:** #1519 This was before WP Rocket 3.3 and the use of the `Buffer` class.

**Comment by guix69** [comment]
Hello, has this been fixed?
As well as everything related to multisite.
Thanks

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
