### ISSUE TITLE
Attached CSS not lazy loaded

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [wp-media/wp-rocket#1814]
I've talked to your team on last WCEU in Berlin and you have asked me to insert my feedback / "bug report" here on github.

We have a highly optimized theme which results in wp-rocket's critical CSS feature comes not in affect. This results in attached CSS files are not lazy loaded when they are combined through wp-rocket.

See function **insert_combined_css** in file [class-combine.php](https://github.com/wp-media/wp-rocket/blob/master/inc/classes/optimization/CSS/class-combine.php)

The combined file is loaded directly after title tag. This can be fixed e.g. via

- JS lazyload
-  media="none" onload="if(media!='all')media='all'"
- loading in footer
- filter to allow to change the html tag.

or a combination of these.

It would be great if you could optimize this behavior, as currently, a highly optimized theme has performance drops due to the current behavior.

**Comment by Tabrisrp** [comment]
Hi,

Could you provide example of codes used, resulting HTML, etc to be able to understand the issue more.

Currently I don't see how our Optimize CSS delivery option conflicts with your theme.

**Comment by straightvisions-matthias-bathke** [comment]
Hi,

please see https://lab-mb.straightvisions.com/ for example.

File https://lab-mb.straightvisions.com/wp-content/cache/min/1/bac0d9b14f93578df0b4da61b7f54717.css isn't lazyloaded or attached to footer, instead it's attached right after <title> which results in renderblocking behavior. Attached CSS should be lazyloaded, as render-critical css going to be printed inline.

![image](https://user-images.githubusercontent.com/4689792/62865568-225a1980-bd0f-11e9-83ca-9c825f55cd14.png)

![screenshot-lab-mb straightvisions com-2019 08 12-14-38-49](https://user-images.githubusercontent.com/4689792/62865488-f2ab1180-bd0e-11e9-86de-117299333e90.png)

**Comment by ScottTravisHartley** [comment]
You have the optimize CSS delivery option enabled but there is no CSS output in the HTML. Try regenerating the critical CSS. It seems that when the option is simply enabeld critical CSS is not generated until AFTER you select regenerate critical CSS. 

Once you do this the CSS will no longer be renderblocking and the critical css will be injected into the header.

**Comment by straightvisions-matthias-bathke** [comment]
unfortunately, critical CSS generation seems to fail here:

![image](https://user-images.githubusercontent.com/4689792/62927337-9c91a900-bdb6-11e9-95b0-c980da0ee3c3.png)
![image](https://user-images.githubusercontent.com/4689792/62927338-9ef40300-bdb6-11e9-9f0d-2461afde48ec.png)

**Comment by Tabrisrp** [comment]
I would recommend to take this to our support team, from the plugin "Help" Beacon or from our support page [https://wp-rocket.me/support/](https://wp-rocket.me/support/).

They will be able to do tests related to the CPCSS generation for your website and see where it's failing.
