### ISSUE TITLE
Auto exclude Jetpack related-posts.min.js from being combined

### ISSUE THREAD

**Issue by kierantaylorio** [wp-media/wp-rocket#1818]
When not excluded Jetpack's related posts are shown twice on a page

/wp-content/plugins/jetpack/_inc/build/related-posts/related-posts.min.js

Related ticket: https://secure.helpscout.net/conversation/894936572/114496

**Comment by webtrainingwheels** [comment]
I couldn't replicate this problem on my site that has Jetpack. Unless someone else can, we may want to monitor tickets to see if we get more instances, before auto-excluding.

**Comment by GeekPress** [comment]
I'm closing this issue as we didn't have new cases since a while. Feel free to re-open it if a new case will come up.
