### ISSUE TITLE
Notice remains and cache is not cleared when Asset CleanUp plugin is enable

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1820]
When [Asset CleanUp plugin](https://wordpress.org/plugins/wp-asset-clean-up/) is enable with WP Rocket, notice to clear cache remains and cache is not cleared at all.

Related discussion and test: https://wp-media.slack.com/archives/C08N8J6VC/p1562328905196400

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/877578432/#thread-2503174607

**Comment by kieran-wpmedia** [comment]
Asset CleanUp 1.3.3.2 update includes "Bug Fix: Sometimes, WP Rocket caching was not fully cleared because of an Asset CleanUp hook that interfered with it". Needs testing again.

https://wordpress.org/plugins/wp-asset-clean-up/#developers

**Comment by arunbasillal** [comment]
I tested this with `1.3.3.2` and the issue seems to have been fixed at their end - https://jmp.sh/CozKBLg

**Comment by kieran-wpmedia** [comment]
I tested 1.3.3.2 over the weekend as well and found the cache was cleared properly (verified via FTP) and the notice was no longer present on the page.

**Comment by mifrero** [comment]
It's fixed for my client too with the update

**Comment by arunbasillal** [comment]
Thanks @mifrero and everyone. So we can close this :)
