### ISSUE TITLE
Google Tracking add-on not matching Google Tag Manager script

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1827]
Our Google Tracking Add-on will not match GTM script when it's implemented like below:
https://jmp.sh/mf07a6t
https://wp-media.slack.com/files/UDJNM4LSG/FL641P3M3/image.png

That's because of this part of the code:
https://github.com/wp-media/wp-rocket/blob/c92efa3a52ef285eb6230a04ac4c5e6d4e2f8e26/inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php#L95-L97

Not sure if there are any arguments against processing both files in this kind of markup.

Related ticket:
https://secure.helpscout.net/conversation/888821686/113737?folderId=2415573

**Comment by arunbasillal** [comment]
Comments from the discussion. 

Remy: 
> the logic was that we didn’t need to replace both if we already replaced the GA one

Piotr
> Because the GTM one shouldn't be loaded when Analytics is already there?

**Thoughts**

Shall we replace it either way? This will avoid user confusion and in case it is used, then we are covered. 

Can't think of any downsides for doing it either way.

**Comment by Tabrisrp** [comment]
Are we sure avoid both at the same time is valid?

**Comment by arunbasillal** [comment]
I did some [internet research](https://www.simoahava.com/analytics/ga-snippet-and-ga-gtm-tag-on-the-same-page/) on this. There isn't anything wrong with having both of them. 

Tag manager is bigger than Google Analytics and it can co-exist on the same page. One doesn't depend on the other.

**Comment by ScottTravisHartley** [comment]
Just so give a bit more insight I personally run into this on many client sites where they will have both integrated. IE they have their google analytics code and they will have Google Tag Manager both on the same page. (Most of the time I just tell them to combine them into one but it does happen quite frequently).

**Comment by Tabrisrp** [comment]
Removing the conditional check should be enough to resolve this issue
