### ISSUE TITLE
Auto exclude cartsguru_cart_token from inline JS

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1832]
The pattern **cartsguru_cart_token** has to be auto-excluded from Inline JS to avoid the cache dir size issue.

Check diff:
https://www.diffchecker.com/M4Fyyqt6

**Comment by Tabrisrp** [comment]
Add `cartsguru_cart_token` to the default array https://github.com/wp-media/wp-rocket/blob/7e0d419a3c0128dcc9de9ca87af831da3585093c/inc/classes/optimization/JS/class-combine.php#L384
