### ISSUE TITLE
Add a filter to adjust the cURL timeout for Sucuri add-on

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1835]
We are already doing it for preload, it would be great to do the same for this `wp_remote_get` request:
https://github.com/wp-media/wp-rocket/blob/6b432e03e4bc076aa811b486b703ec9abc21b253/inc/classes/subscriber/third-party/plugins/security/class-sucuri-subscriber.php#L276

Right now we don't provide filters to change the timeout, it can lead to the broken layout problems.

Related ticket:
https://secure.helpscout.net/conversation/896105624/114664?folderId=2415573

**Comment by arunbasillal** [comment]
Had a discussion with Piotr. Notes

- These issues are rare and probably not noticed by customers. Adding a filter would help resolve them when they are noticed.
- Increasing the [timeout](https://github.com/wp-media/wp-rocket/blob/6b432e03e4bc076aa811b486b703ec9abc21b253/inc/classes/subscriber/third-party/plugins/security/class-sucuri-subscriber.php#L277) to 10 seconds could be an additional step. Similar to what we do for sitemaps in preload. 

In the future, if we end up adjusting timeouts automatically on failure (as we discussed for Preloads at one point), we could think of adding it here too.

**Comment by Tabrisrp** [comment]
The filter name should be `rocket_sucuri_api_request_args`, and applied on the second parameter (array) of the `wp_remote_get` function.

An example with our preload can be seen here: https://github.com/wp-media/wp-rocket/blob/b8a54656afd7acc86fec1b1ac4e85d7b72ba5317/inc/classes/preload/class-homepage.php#L67
