### ISSUE TITLE
Revolution Slider 6 is not working with LazyLoad

### ISSUE THREAD

**Issue by sabrina-zeidan** [wp-media/wp-rocket#1839]
Revolution slider supposed to be excluded from LazyLoad https://docs.wp-rocket.me/article/38-lazyload-plugin-compatibility but after the latest update (tested with version 6.0.1/6.0.2) it's not showing while LazyLoad is enabled. 
[Related ticket ](https://secure.helpscout.net/conversation/899906143/115318/)
To reproduce the issue: add regular slider and enable LazyLoad for images [link](https://secure.helpscout.net/conversation/899906143/115318/)

**Comment by arunbasillal** [comment]
This has been fixed in Revolution Slider `6.0.5`

Related ticket - https://secure.helpscout.net/conversation/904706221/116254/
