### ISSUE TITLE
Automatically exclude Beaver Builder Custom Post Type from CPCSS

### ISSUE THREAD

**Issue by kieran-wpmedia** [wp-media/wp-rocket#1840]
Description:

WP Rocket tries and fails to create CPCSS for the Beaver Builder layout Custom Post Type: **fl-builder-template**

Expected:

Custom Post Type should be ignored

Related:

https://secure.helpscout.net/conversation/902561657/115801

**Comment by Tabrisrp** [comment]
`fl-builder-template` should be added to the CPT exclusion array here: https://github.com/wp-media/wp-rocket/blob/7e0d419a3c0128dcc9de9ca87af831da3585093c/inc/classes/optimization/CSS/class-critical-css.php#L182
