### ISSUE TITLE
Issue with image CDN src in AMP

### ISSUE THREAD

**Issue by Zabi09** [wp-media/wp-rocket#1844]
I am one of the developers of AMPforWP plugin and currently, I am working on image CDN issue as one of our users is having issues that the CDN links are not coming on the GIF format and only CDN links are coming in images and here is the link - https://wordpress-298611-917212.cloudwaysapps.com/mobile-problems/android-problems/there-was-a-problem-parsing-the-package-17/amp

You can see that the CDN is coming only for images but not in GIF

Will you please tell us how you are making changes in the src in non-amp version? Are you using this function - wp_get_attachment_image_src to change the src in non-AMP version?

Please let us know,

**Comment by Tabrisrp** [comment]
We did a major change on version 3.4 for our CDN feature. Can you test and see if there is anything that is not working correctly with that version?

**Comment by GeekPress** [comment]
Hi @Zabi09  🤚

We haven't back from you since @Tabrisrp asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best
