### ISSUE TITLE
Link href attribute is not being replaced

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1845]
This kind of [correct HTML markup ](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content)will force the browser to download the same file two times:

```
<head>
  <link rel="preload" href="main.js" as="script">
</head>
<body>
  <script src="main.js"></script>
</body>
```

That's because the script `src` is replaced, while link `href` attribute is not.

It leads to the situation when the browser is preloading link element (/path-to-the-file/main.js) and then loading the second script (/wp-content/cache/busting/1/path-to-the-file/main.js).

Related ticket:
https://secure.helpscout.net/conversation/902825345/115828?folderId=2415573

Related convo:
https://wp-media.slack.com/archives/C43T1AYMQ/p1563294576011800

**Comment by arunbasillal** [comment]
From a conversation on this with Remy. Saving these notes so that it can be worked on later. 

> That requires planning & development time, since we need to think about support for cache busting, minification, etc. How do we handle cases with combine?
> We have to develop a whole new search & replace for those links specifically, taking into account which options are active, how to get the correct names

**Comment by piotrbak** [comment]
We didn't get enough feedback here.
