### ISSUE TITLE
Cache clearing when updating a page, when WC status set to complete

### ISSUE THREAD

**Issue by frederic-vdb** [wp-media/wp-rocket#1850]
- WP Rocket Version 3.3.5.2 
- WooCommerce Ver Version 3.6.5
- WP 5.2.2

When updating a post-type "page", not a article, all cache is clear.
- Edit the page
- Make even a very small correction in the text
- Save the page => all the cache is gone !

Set an order to _complete_ in Woocommerce.
- Edit the order
- Set the order to complete
- Save the order => all the cache is gone.
or in the backoffice panel of Woocommerce
- Click on the complete button for an order
- All the cache is gone.

**Comment by arunbasillal** [comment]
Hello @frederic-vdb 

When editing the page, it is expected to clear the cache of the specific page and that of the homepage and related caches. Details here - https://docs.wp-rocket.me/article/78-how-often-is-the-cache-updated#when-does-wp-rocket-clear-the-cache

I just tested this and the entire cache was not deleted. If that isn't true for you, maybe something isn't right and please reach out to support - https://wp-rocket.me/support/
