### ISSUE TITLE
Proposal: add a "preload complete" notice

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1853]
Currently you can see the progress of the preload by refreshing the page. 
But if preload finishes in between refreshes, the next page load will remove the notice entirely. 
I'm left thinking: "Did it finish? Did something go wrong? How many pages were cached in the end?"

It would be nice to have a "Preload complete: x pages cached" notice so the user knows when it's done.

**Comment by arunbasillal** [comment]
Hey Lucy,

I have noticed what you mentioned a few times, but is it consistent? This is what I see when I try to replicate - https://jmp.sh/X5gZqh6

**Comment by webtrainingwheels** [comment]
I can't tell from your demo if we're doing the same thing. If you refresh again after seeing 24 pages,  you won't see the notice anymore. 
Even if you are seeing the same notice about 24 pages repeatedly, what indicates it's complete, rather than stuck?

**Comment by webtrainingwheels** [comment]
This request is related - https://github.com/wp-media/wp-rocket/issues/1867

**Comment by arunbasillal** [comment]
Had a discussion with Lucy.

At the very least we could modify the notice to say `Preload Complete`. 
So that the final notice would say `Preload Complete: 24 pages have been cached`

Adding the timestamp mentioned in #1867 if we end up doing it will add more info.

**Comment by Tabrisrp** [comment]
We could change the color of the notice too, keep green for complete, but use blue for in progress.
