### ISSUE TITLE
Alternating method of cache clearing and preloading

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#1856]
_Request from a customer:_

--
We have been using WP Rocket for a few years now and we noticed there is a flaw in the cache updating process. What we noticed is, there is a major update with Woocommerce or some other plugins, we would have to clear the entire cache of All Pages, then preload the cache of all pages again.

Since we have around 15K products in our Woocommerce Store, the entire preloading process would take approx 10 hours. During this 10 hour period, shoppers' experience were badly affected, because there are many pages that are "not yet cached". 

Shoppers would hit some uncached pages from time to time. This is Extremely Bad for eCommerce store! So, I am wondering if you could offer an additional method for updating cache that much more "graceful". 

I suggest that the additional method to clear the cache of each page 1 by 1:

Right after the cache of each page is cleared, then immediately preload the cache of that specific page ... as opposed to the current method of clearing the cache of All Pages in one shot, leaving many pages in the site uncached for 10 hours.

With my suggested Graceful Method, shoppers will be highly unlikely to hit any uncached pages.

Would you consider adding this additional method for updating cache?

--

See also:

- https://secure.helpscout.net/conversation/896225413/114683/
- https://secure.helpscout.net/conversation/896875827/114765/

**Comment by webtrainingwheels** [comment]
Here's another example of the same request (different customer): 
https://secure.helpscout.net/conversation/871778503/110569/

**Comment by gevcen** [comment]
Totally agree @girlie on the request

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1367154979/223129?folderId=377611

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1441900781/244000?folderId=377611

**Comment by piotrbak** [comment]
I don't think we'll be able to implement this one. The customer could just take advantage of cache lifespan, it'll gradually replace the old cached files with the new ones.
