### ISSUE TITLE
Better way to handle cache of CSS & JS

### ISSUE THREAD

**Issue by Dibbyo456** [wp-media/wp-rocket#1859]
**Is your feature request related to a problem? Please describe.**

Yes. When CSS Minification in WP Rocket enabled, changing codes on style.css and without changing the version number causes the css changes not to show up even when the Page Cache is cleared. The only way to reflect updated content is to change style.css version number which is pretty much [described here](https://docs.wp-rocket.me/article/966-css-changes-dont-show-up).

**Describe the solution you'd like**

This happens because when a **same named minified css** already exists wp-rocket skips it judging by the codes of **Line 100-120** on `\inc\classes\optimization\CSS\class-minify.php`.

I think the better way would be compare contents of the minified file with the exists one. If they don't match save the new one with a different a name.

That way changes without on style.css or any other internal css files should reflect when the page cache is cleared.

**Additional context**
The same technique is used by very popular Publisher theme.

So, what do you think?

**Comment by arunbasillal** [comment]
Not updating the version number would be an issue even without minification right? The CSS file will be cached in the browser and users will not see the update.

**Comment by Dibbyo456** [comment]
when minification is enabled wp-rocket does not add any version number to the css file instead it uses a random name.

**Comment by arunbasillal** [comment]
The hash generated is for combined CSS file and will be reset when cache is cleared. 
Even if you clear the cache manually, the name isn't re-generated for you?

**Comment by arunbasillal** [comment]
@Dibbyo456 Any feedback on this please?

**Comment by Dibbyo456** [comment]
Nothing atm. I still believe, my approach will work but will increase cpu usages.

**Comment by arunbasillal** [comment]
Since this isn't an issue for everyone, I am going to close this for now. If you have additional information in the future, please feel free to reopen.
