### ISSUE TITLE
"Exclude files from CDN" should automatically remove the files from Minify JS & CSS

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#1861]
@vmanthos mentioned that when CDN is enabled and some CSS & JS files are excluded from CDN, then some issues may appear if Minify JS & CSS is activated. So these files must be added also in the Excluded JS / CSS Files from Optimization tab?

Possible solution:

The excluded files from CDN shouldn't be automatically added in Excluded JS / CSS Files from Optimization tab?

**Comment by Tabrisrp** [comment]
With the PR #1878 this should not be needed anymore
