### ISSUE TITLE
SUCURI - if x-sucuri header is present add notification to enable the Sucuri Addon

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#1862]
I think it is possible to identify if x-sucuri header is present. 
If is present then just add a notification for the user to enable Sucuri Addons and insert the API key from Sucuri. 

I think this will reduce the no. of CS emails related to Sucuri and sync caches.

**Comment by arunbasillal** [comment]
Based on feedback from Remy, here are some considerations. 

- The notification could ideally be a suggestion, not a warning.
- The suggestion could be dismissible. 
- Customer might be using a different plugin (eg: Sucuri plugin) or might have another reason not to use the add-on.
