### ISSUE TITLE
Plugin replaces data-src with data -src

### ISSUE THREAD

**Issue by mihdan** [wp-media/wp-rocket#1863]
There’s an extra space that gets added between `data` and `src` attribute in the `img` tag.

Before WP Rocket:

`<img data-src="path" />`

Aftre WP Rocket:

`<img data -src="path" />`

WP-Rocket 3.3.6
WordPress 5.2.2

**Comment by Tabrisrp** [comment]
To be able to investigate your report, please provide more context about the issue:
- With which of the plugin options does it happen
- Steps to reproduce the behavior

**Comment by mihdan** [comment]
**Plugin options:** 
- Cache - http://screenshot.kobzarev.com/2019-07-25-1564083418.png
- File Optimization - http://screenshot.kobzarev.com/2019-07-25-1564083490.png
- Media - http://screenshot.kobzarev.com/2019-07-25-1564083519.png
- Preload - http://screenshot.kobzarev.com/2019-07-25-1564083537.png
- Advanced Rules - http://screenshot.kobzarev.com/2019-07-25-1564083577.png
- Database - http://screenshot.kobzarev.com/2019-07-25-1564083619.png
- CDN - http://screenshot.kobzarev.com/2019-07-25-1564083981.png

**Comment by Tabrisrp** [comment]
Please open a support ticket about your issue, either from [here](https://wp-rocket.me/support/?utm_source=github&utm_medium=wp_rocket_profile) or from the integrated support in the plugin settings page.

One of our support team members will help you pinpoint the source of the issue, and if it's indeed a bug, will report back here with the details.

**Comment by mihdan** [comment]
ok

**Comment by mihdan** [comment]
I added the `src` attribute with a placeholder to the images and the problem disappeared.

`<img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 0 0'%3E%3C/svg%3E" class="owl-lazy wpstickies" style="font-size: 12px;" height="421" data-src="...plugins.jpg">`

> As soon as it's present in the source with correct markup WP Rocket is not manipulating the `data-src` attribute. You're probably not including `src` because of lazy load solution. Here at WP Rocket, we use the following placeholder for elements that should be lazyloaded: http://snippi.com/s/awuegl7
