### ISSUE TITLE
Add Shareaholic Plugin Exclusion for Combine JavaScript Files - External JS [Additional Domains]

### ISSUE THREAD

**Issue by jmeattle** [wp-media/wp-rocket#1881]
This is a follow up to https://github.com/wp-media/wp-rocket/issues/1197

Additional CDN domains:

```
$excluded_external[] = 'cdn.shareaholic.net';
$excluded_external[] = 'k4z6w9b5.stackpathcdn.com';
```

These two are in addition to those listed in https://github.com/wp-media/wp-rocket/issues/1197

Would appreciate it if this can be added to WP-Rocket. We've added it to Shareaholic here -
https://plugins.trac.wordpress.org/browser/shareaholic/trunk/utilities.php#L1322

**Comment by arunbasillal** [comment]
Hello @jmeattle 

I see it already as part of Shareaholic plugin as you pointed out sing the right filter. That should be good enough and no more addition is required in WP Rocket core. It's more efficient this way rather than us shipping it to all customer including those who do not use Shareaholic.

Please let me know if I am missing something.

**Comment by ScottTravisHartley** [comment]
Mixed issue ShareThis also includes the ability to add it's JS via its web platform as follows.

**Comment by jmeattle** [comment]
Hi @arunbasillal you already ship other Shareaholic exclusion rules, hence thought you'd want to include the latest ones.

https://github.com/wp-media/wp-rocket/commit/2bd2c9ff8e3ed2f44187f0d470c26a2ca46f15f1#diff-659add6e0f48dda9bcd68ceab379dceeR511

@ScottTravisHartley Very unrelated issue. This issue pertains to a change request specifically for Shareaholic (from its authors). Can you please open another issue ticket for yours. thanks!

**Comment by piotrbak** [comment]
We didn't have any complains related to this one since 2019. Feel free to reopen it if it's still an issue
