### ISSUE TITLE
WPML content outside a directory isn't purged

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1890]
When a site uses the "Different languages in directories" option in WPML, if any content exists  under the root, and therefore outside of a language directory, this content will not be detected for automatic cache purging by WP Rocket. 

A solution could be to exclude that content from the cache but I don't think that's expected by our customers. 
Slack convo: https://wp-media.slack.com/archives/C43T1AYMQ/p1564776956066500

Example tickets: 
https://secure.helpscout.net/conversation/909523541/116881/
https://secure.helpscout.net/conversation/918696268/118126/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1476575061/253955/

**Comment by camilamadronero-zz** [comment]
New case: https://secure.helpscout.net/conversation/1804685395/329416/

**Comment by kskonovalov** [comment]
+1 same issue: when we update the page in the second language, the cache is not flushed for this page, even if we used the code from https://gist.github.com/herewithme/055a44497e7ad51920a9 (sometimes it worked and sometimes it's not)

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/2072713376/382729/

**Comment by piotrbak** [comment]
Closing in favor of https://github.com/wp-media/wp-rocket/issues/5611 as it contains more details.
