### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by pintolog** [wp-media/wp-rocket#1891]
Hi,
I downloaded the file from here at github but i can't activate it because of an error:

**Plugin could not be activated because it triggered a fatal error.**

Fatal error: Uncaught Error: Class 'WP_Rocket\Admin\Options' not found in /var/www/vhosts/***********.com/httpdocs/wp-content/plugins/wp-rocket-master/inc/functions/options.php:19 Stack trace: #0 /var/www/vhosts/***********.com/httpdocs/wp-content/plugins/wp-rocket-master/inc/functions/options.php(528): get_rocket_option('secret_key') #1 /var/www/vhosts/***********.com/httpdocs/wp-content/plugins/wp-rocket-master/inc/main.php(182): rocket_valid_key() #2 /var/www/vhosts/***********.com/httpdocs/wp-includes/class-wp-hook.php(286): rocket_activation('') #3 /var/www/vhosts/***********.com/httpdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /var/www/vhosts/***********.com/httpdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #5 /var/www/vhosts/***********.com/httpdocs/wp-admin/plugins.php(177): do_action('activate_wp-roc...') #6 {main} thrown in /var/www/vhosts/***********.com/httpdocs/wp-content/plugins/wp-rocket-master/inc/functions/options.php on line 19

![image](https://user-images.githubusercontent.com/7497319/63296245-5d43ea80-c2d7-11e9-827d-d4786272a895.png)

**Comment by Tabrisrp** [comment]
To use the plugin directly from Github, you need to run `composer install` after downloading it to install the dependencies & generate the autoloader.
