### ISSUE TITLE
Additional requests to Rocket Loader in page source

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1903]
When **Rocket Loader** from Cloudflare is enabled alongside with our **Optimize CSS Delivery** feature, additional requests to Rocket Loader script are added to the source:
https://jmp.sh/XeZDR9D

They're appended to the files processed by `async_css` function:
https://github.com/wp-media/wp-rocket/blob/dfb5e1cf4fe9486b528d6ca9eaf33605acc7bceb/inc/classes/subscriber/Optimization/class-critical-css-subscriber.php#L368

Cloudflare adds calls to this file just before all <link> resources that have `onload="this.onload=null;this.rel='stylesheet'"` attribute.

Here's a related ticket:
https://secure.helpscout.net/conversation/933884906/119957/

From the network point of view this resource is being downloaded only once, so it doesn't seem to affect the performance:
https://jmp.sh/0jnsvMA

However, it might be confusing for our customers.

**Comment by Tabrisrp** [comment]
Seems more a bug from Cloudflare side when they determine where to inject the rocket loader script than anything from us.
