### ISSUE TITLE
Detect incorrect wildcard rule on Never Cache URLs

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1917]
Below our Never Cache URLs field we provide this instruction: 
`Use (.*) wildcards to address multiple URLs under a given path.`

Despite that, customers will often try to use this format for wildcards:
`/page/*`

This exclusion won't work but there's no UI feedback. 

Could we either: 
- Respect that wildcard format so it does work
or
- Detect it and either automatically correct it, or show a UI message

Sample tickets: 
https://secure.helpscout.net/conversation/923715360/118725/
https://secure.helpscout.net/conversation/929162814/119416/
https://secure.helpscout.net/conversation/901984588/115728/

**Comment by arunbasillal** [comment]
It would be awesome if we can automatically correct it. Showing an admin notice will still be ignored if the user doesn't read the notice of it they do not understand it.

**Comment by Tabrisrp** [comment]
We can't respect when they use only `*` because it's not a valid regular expression token.

Potentially we could try to detect it and automatically replace it with the valid format, which can be either `.*` or `(.*)`

**Comment by arunbasillal** [comment]
In our current inline documentation, we recommend to use `(.*)` - https://jmp.sh/ItllZ6K
So for consistency, let's please stick to `(.*)` instead of `.*`

Thanks!
