### ISSUE TITLE
Minify HTML do not take into account attribute values that span multiple lines.

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#1931]
Minify HTML will break at trimming each line when attributes span on multiple lines:

This line is causing the issue:
https://github.com/wp-media/wp-rocket/blob/7f9af51eec7336d4bd4d7a0193be8d9f06750d99/inc/vendors/classes/class-minify-html.php#L131

I fixed it replacing with a " ":
`$this->_html = preg_replace('/^\\s+|\\s+$/m', ' ', $this->_html);`

Checked other solutions, but it seems this is the only one (extra space) or by changing the trim line with this code which adds a line instead an extra space:
`//Remove blank useless space`
`        $search = array(`
`            '@( |\t|\f)+@',    // Shorten multiple whitespace sequences`
`            '@(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+@',    //Remove blank lines`
`            '@^(\s)+|( |\t|\0|\r\n)+$@' //Trim Lines`
 `       );`
 `       $replace = array(' ',"\\1",'');`
`        $this->_html = preg_replace($search, $replace, $this->_html);`

https://cl.ly/83cc119afb9e

https://secure.helpscout.net/conversation/939694690/120616?folderId=3083222
https://secure.helpscout.net/conversation/943488407/121105?folderId=3083222

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/958223097/123414?folderId=2683093
