### ISSUE TITLE
Lazy loading youtube iframe in chrome 76

### ISSUE THREAD

**Issue by bainternet** [wp-media/wp-rocket#1934]
**Describe the bug**
When using the lazy-load feature for youtube videos in chrome 76 the video doesn't start auto-playing and a second click is required to start the video.

**To Reproduce**
1. enable lazy-load for youtube
2. add a video to a page
3. load the page of the video using chrome 76+ in caching mode( ex: incognito would work) 
4. click on the play button and see that the iframe is loaded but not auto-playing.

**Additional context**
Seems like adding `allow="autoplay"` attribute to the iframe fixes the issue.

**Comment by Tabrisrp** [comment]
Is this new behaviour in Chrome 76?
