### ISSUE TITLE
3.4-alpha1: Capabilities - preload notice

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1935]
When a user initiates a preload from a non-WP Rocket settings page, we display this notice: 
![Dashboard_‹_WordPress_Themes_—_WordPress](https://user-images.githubusercontent.com/1043076/64220347-e7ff1a80-ce7d-11e9-9e74-07fc3c054650.jpg)

However if a user is given the capability to preload, but doesn't have access to the settings page, that link won't work for them.

Is it possible to detect the capabilities and change the notice accordingly?
Removing this part should be enough: 
>Go to the WP Rocket settings page to track progress.

**Comment by arunbasillal** [comment]
Tested for this in beta-3 and it's all good
