### ISSUE TITLE
Offer a way to expire CDN caches (e.g. CloudFront)

### ISSUE THREAD

**Issue by ctschach** [wp-media/wp-rocket#1938]
**Is your feature request related to a problem? Please describe.**
Serving assets via CDN is a nice way to speed up a website. However, you sometimes change and image after some of the managers reviewed a page. So you delete the old image and upload the the updated one with the same name.

Why do you choose the same name? Unfortunately you have used this image on 20 different pages on the site. So you don't want to change every single page again. So using the same image URL will some your issues.

But now it comes to CDN - based on your cache settings, the image might be on the CDN cache (we use CloudFront) for the next 30 days before it's fetched from your server again.

The only way to force CloudFront to load the images again from your server is to go into the Cloudfront backend and invalidate your cache. A time-consuming thing.

**Describe the solution you'd like**
This idea comes from a different caching solution we used before. They simply added the Querystring to each CDN url. This was used as a version number - similar to what WP does for it scripts and CSS files. 

There was an option on the CDN page which allowed you the expire CDN cache. This would increase the version number on the assets URLs, so that they are fetched again from the server by the CDN.

So the image URL looked like this:

     https://cdn.site.me/...../myimage.jpg?iv=2

Once you expire the cache the version number is incremented by one:

     https://cdn.site.me/...../myimage.jpg?iv=3

This will force the CDN to load a new copy from the original site.

The old version will expire in the CDN if its not accessed for a defined period of time.

**Describe alternatives you've considered**
The only alternative would be use the backend from AWS to invalidate the Cloudfront cache

**Additional context**

**Comment by GeekPress** [comment]
Hi @ctschach 🤚

Welcome and thanks for your contribution to WP Rocket repository.

> Why do you choose the same name? Unfortunately you have used this image on 20 different pages on the site. So you don't want to change every single page again. So using the same image URL will some your issues.

For this kind of problem (image replacement), there is an excellent plugin named [Enable Media Replace](https://wordpress.org/plugins/enable-media-replace/).

You can change an image and the plugin will change the URL everywhere it was linked 🚀
