### ISSUE TITLE
Allow to add more filetypes to CDN caching

### ISSUE THREAD

**Issue by ctschach** [wp-media/wp-rocket#1939]
**Is your feature request related to a problem? Please describe.**
Our site has some MP4 files which are used as page headers and are hosted locally (no YouTube, no Vimeo, just the local server).

At the moment WP-Rocket will not rewrite those URLs to use the CDN server. 

It would be great if I could add additional filetypes to the CDN cache settings. Maybe even via a regular expression.

**Describe the solution you'd like**
On the CNAME tab for CDN where you select the filetype, add an "expert" which will then show and text input box which allows to add a regular expression of file types for that CDN setting.

**Describe alternatives you've considered**
A fast way currently is to create some rewrite rules which will redirect the the CDN instead loading it from the local machine. However, this will created a redirect request and is not changing the code to contain the right URL by default.

**Additional context**

**Comment by ctschach** [comment]
Maybe an imported addition:  My theme is including a video using the html5 <video> tag: 

<video id="wp-custom-header-video" autoplay="" loop="" width="2000" height="800" src="https://my.domain.com/wp-content/uploads/2019/01/Website-Intro.mp4"></video>

So it would be great to find a way to rewrite the "src" in the video tag with the CDN host.

**Comment by Tabrisrp** [comment]
This will be automatically handled in 3.4 with the CDN rewrite.
