### ISSUE TITLE
HTML minification + var wc_product_block_data

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1940]
WooCommerce recently started inserting this inline script, beginning: 
`var wc_product_block_data`

In some cases it can be really large and seems to cause a problem - a blank screen - with HTML minification. 

Sample tickets:

- https://secure.helpscout.net/conversation/942490237/120952/
- https://secure.helpscout.net/conversation/940796878/120724?folderId=2952229

Related conversation: 
https://wp-media.slack.com/archives/C43T1AYMQ/p1567089731008200

**Comment by crystinutzaa** [comment]
This issue is coming from: WooCommerce Blocks plugin:
https://wordpress.org/plugins/woo-gutenberg-products-block/

There is excessive JS (1.5MB of JS) from it causing the issue with WP Rocket: https://wordpress.org/support/topic/causes-excessive-js/

**Comment by webtrainingwheels** [comment]
var wc_product_block_data is coming from WooCommerce itself - you can replicate that on sites without the blocks plugin. It's possible they merged the feature generating it from the blocks plugin into core woocommerce. 

https://woocommerce.wordpress.com/2019/08/12/woocommerce-3-7-has-landed/

>WooCommerce 3.7 ships with Product Blocks 2.3 for the WordPress Block Editor which contains numerous enhancements and performance improvements since the introduction of Product Blocks in 3.6.
>In addition to these new blocks, there were also performance improvements made in looking up products and loading block assets on frontend pages.

**Comment by webtrainingwheels** [comment]
We are seeing a similar issue on some sites with Avada which now has an option that inserts inline CSS into the page. In some cases it's adding a huge amount (1MB +, for example) and it causes the same white screen issues. 

- https://secure.helpscout.net/conversation/969198763/124996?folderId=377611
- https://secure.helpscout.net/conversation/951037774/122377/

**Comment by arunbasillal** [comment]
@crystinutzaa left this note:

> Fixed but needs to be revisited and some new directions on it because right now no inline JS will be minified if a backtrack_error appears

Let's see how common this issue is before we get proactive about this.

**Comment by jodhavishalsingh** [comment]
yes, it's issue and getting mail from few of my clients, it's unwanted and slowing down sites.

**Comment by vmanthos** [comment]
@arunbasillal 

`wc_product_block_data` will be excluded from JavaScript combination with #2036 . 

It is also responsible for the `/cache/min/` directory size issue caused by dynamic JavaScript.

**Comment by arunbasillal** [comment]
Thanks @vmanthos 

Cristina's previous comment was about `PREG_BACKTRACK_LIMIT_ERROR`. Which is  an edge case, but when that happens no inline JS or inline CSS will be minified. 

Even if it happens, it isn't a big deal. Minification of inline JS and CSS isn't going to make a world of difference to begin with.

**Comment by asksock** [comment]
I think it's from Woocommerce, have any idea to cut off this this inline script?
