### ISSUE TITLE
Randomize path and file to cached GA/Facebook JavaScript files

### ISSUE THREAD

**Issue by Greger-cmd** [wp-media/wp-rocket#1941]
**Is your feature request related to a problem? Please describe.**
Cached GA and Facebook JavaScript files are easily blocked by ad blockers because of "tracking" in the name o file path. Preview: https://imgur.com/9HJjEuU

**Describe the solution you'd like**
Those files should have random names and paths.

**Comment by arunbasillal** [comment]
If we end up doing this, I vote that we do not do it for all customers but instead have a filter that customers can use instead. 

Imo, for an end user, if they do not want to be tracked, they should be able to do so and I think by doing this for everyone we will take that option away from a lot of end users.

**Comment by Tabrisrp** [comment]
What we should do is be on par with the default behaviour. If the not-local script is not blocked, ours shouldn't be either. If it is, ours should be.

Can you give us some details about this?

**Comment by Greger-cmd** [comment]
What details do you need? "Everything" is visible on screen from first post: https://imgur.com/9HJjEuU There is filter for AdBlock/uBlock which is blocking path with "google-tracking" and "facebook-tracking" inside ;) What can I provide more?

**Comment by Tabrisrp** [comment]
Specifically, if the original scripts were not blocked, while the one saved locally are blocked?

Or were the original scripts blocked too, so in this case the behaviour is ok.

**Comment by arunbasillal** [comment]
I completely agree with this comment from Remy - https://github.com/wp-media/wp-rocket/issues/1941#issuecomment-557786779

As a performance plugin, it's not our job to change the default behaviour of tracking scripts. 

From what I understand based on the screenshot shared by the customer, blocking of these scripts happen with and without WP Rocket. 

Going to close this issue based on this feedback. 

@Greger-cmd Please note. If blocking is something that happens only when WP Rocket add-ons are used, please re-open the issue and let us know.
