### ISSUE TITLE
Add option to dequeue jQuery Migrate

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#1943]
**Is your feature request related to a problem? Please describe.**
jQuery migrate is a compatibility script loaded along side jQuery to provide backward compatibility to code written on old version of jQuery. The script is no longer needed a vast majority of the time, so dequeuing it can remove an HTTP request and reduce the amount of JS loaded on a page.

**Describe the solution you'd like**
We can add a a checkbox option on the file optimization tab, in the Javascript section, offering to dequeue jQuery Migrate when checked.

**Comment by MarcoMCM** [comment]
Great solution for me!
