### ISSUE TITLE
Cache race condition with shared filesystem for multiple servers

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#1945]
**Describe the bug**
On a setup with multiple servers reading the same shared filesystem for cached files, it can happen that one server is requesting the cache file while another is still writing it, causing the first one to return a blank/incomplete page.

This is happening because we start writing directly in the final cache file destination.

As a solution, instead we can first write to a temp file which can then be renamed to the final name once complete.

**Comment by arunbasillal** [comment]
Related conversation - https://wp-media.slack.com/archives/G8L4EE8N9/p1571922642154800

**Comment by rosamillan** [comment]
related: https://secure.helpscout.net/conversation/2966930961/566563?viewId=7406897
Full description and possible fix in [Slack thread](https://group-onecom.slack.com/archives/C08F4M3BBJL/p1751043297660569)
