### ISSUE TITLE
CRON failure notice reappears when clicking default WordPress dismissal button

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1947]
Documenting this here, as discussed in yesterday's meeting, hoping it will help with the discussion for #1472.

When a user clicks the default WordPress dismissal button instead of WP Rocket's "_Dismiss this notice._",  the CRON failure notice reappears.

This can be frustrating and misleading in cases of false positives.

**Comment by arunbasillal** [comment]
The notice doesn't have the dismissal x in the top corner - https://jmp.sh/YqaRNnp

But the notice did come back. I had dismissed the notice in the above example yesterday. And today it is back. As seen in the recording above, I have dismissed it again now.
