### ISSUE TITLE
Feature request: Event on lazyload elements

### ISSUE THREAD

**Issue by qmdev** [wp-media/wp-rocket#1964]
Hi

**Situation:**
We have some script that changes the color grading of some of our images after the page loads.
When we enable lazyload in wp-rocket this feature does not work anymore because the pictures are not available when the script runs on pageload. A common issue.

**Current fix:**
We disabled the lazyload on those specific images using `data-no-lazy="1"`

**Desired fix:**
Fire an javascript event on each element when it is loaded. Then we can hook on that event and run the color grading function after. This way lazyloading and our custom functionality works.

This should be changed in file: _wp-rocket\vendor\wp-media\rocket-lazyload-common\src\Assets.php_
On line 63 you could add two extra lines at the bottom of the callback_loaded function to fire the event:
```
$script .= 'window.lazyLoadOptions = {
	elements_selector: "' . esc_attr(implode(',', $args['elements'])) . '",
	data_src: "lazy-src",
	data_srcset: "lazy-srcset",
	data_sizes: "lazy-sizes",
	class_loading: "lazyloading",
	class_loaded: "lazyloaded",
	threshold: ' . esc_attr($args['threshold']) . ',
	callback_loaded: function(element) {
		if ( element.tagName === "IFRAME" && element.dataset.rocketLazyload == "fitvidscompatible" ) {
			if (element.classList.contains("lazyloaded") ) {
				if (typeof window.jQuery != "undefined") {
					if (jQuery.fn.fitVids) {
						jQuery(element).parent().fitVids();
					}
				}
			}
		}
		var lazyloaded = new Event("lazyloaded");
		element.dispatchEvent(lazyloaded);
	}';
```

This way developers can hook in the event like this for example:
```
// Test on event
var imgs = $('img.dosomething');
$.each(imgs, function(index, img) {
	$(img).on('lazyloaded', function(e) {
		$(this).doSomethingWithIt();
	});
});
```

Would be wonderfull if you could add that to the "callback_loaded" option of lazyLoadOptions.
Much appreciated.

Thanks

**Comment by qmdev** [comment]
A little more readable: What I added after the IF that checks if it's an Iframe in the "callback_loaded" option:
```
var lazyloaded = new Event("lazyloaded");
element.dispatchEvent(lazyloaded);
```
This had the desired effect for us.

**Comment by Tabrisrp** [comment]
The `callback_loaded` is in fact already what you're looking for. What is currently missing is a way to modify the callback passed to it. This can be done in a future version of the plugin.

**Comment by mderubertis** [comment]
@Tabrisrp is there an example of how we can use `callback_loaded`?

**Comment by GeekPress** [comment]
I'm closing this request as lazyload on images won't be a problem anymore after switching to native LazyLoad (coming in 3.11).
