### ISSUE TITLE
Detect and report when closing </html>, </body> and wp_footer() aren't available

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1985]
Since WP Rocket relies on the `wp_footer` action and the closing `</html>` to work correctly, it would be ideal if we can report it the customer. 

Remy said we could use `did_action` to see if the action `wp_footer` was done. For `</html>` we can check the buffer directly. 

If these are not present and if the features that use them are activated (lazyload uses wp_footer for example), show an admin warning requesting the customer to fix it. 

Related discussion: https://github.com/wp-media/wp-rocket/issues/1883#issuecomment-518240417

**Comment by arunbasillal** [comment]
Notice suggestion:

**WP Rocket:** Failed to detect closing `</html>` and `wp_footer()` in your theme which are required for proper functionality. Read the [documentation](https://docs.wp-rocket.me/article/99-pages-not-cached-or-minify-cssjs-not-working#theme) for further guidance.

Doc links to: https://docs.wp-rocket.me/article/99-pages-not-cached-or-minify-cssjs-not-working#theme

**Comment by Tabrisrp** [comment]
Please remind me why we need to check for the closing `</html>`? We use it to add our footprint, but it doesn't prevent caching if it's not there.

Also, I can see false positives arise if someone uses the REST API. The content won't have a `</html>`, but it's still valid caching. It will probably not have executed `wp_footer()` either.

Currently we don't have a way to detect what kind of request it is, to be able to make the difference between a REST API response and an HTML response.

**Comment by vmanthos** [comment]
We also use it to apply optimizations here:
https://github.com/wp-media/wp-rocket/blob/1ffb4f447d6f6ed8f413cec1b1c88f10beb0dcc4/inc/classes/Buffer/class-optimization.php#L75

**Comment by vmanthos** [comment]
You are right about that.

At least, we can add an error logging statement to have this in WP Rocket's debug log. It will make easier for our teammates to spot this kind of case.

**Comment by arunbasillal** [comment]
So let's check for `</body>` tag as well. All these are things to be fixed at the customers end and ideally it's better that they are informed directly where possible. 

Regarding false positives, @crystinutzaa please the conversations above: 

- Add a check for `</body>` as well. 
- Please test with REST API and see what happens. If false positives are encountered, then lets figure out a way to exclude REST.
- Add this to WP Rocket's debug log.
