### ISSUE TITLE
Setup several Cloudflare Accounts for WPML

### ISSUE THREAD

**Issue by chrislind** [wp-media/wp-rocket#2003]
**Is your feature request related to a problem? Please describe.**
We have several domains, one per language. When using Cloudflare through WP-Rocket it's impossible to setup more than one zone/domain. Which means we're going to have to do a hacky workaround with htaccess or something to get it up and running.

**Describe the solution you'd like**
When WPML is installed and is using seperate domains, since you can cache the different domains you should also be able to setup cloudflare for each.

**Describe alternatives you've considered**
Using .htaccess to redirect all css, js and image requests on non-main language domains to the main domain. Which should work in theory but is not at all ideal.

**Additional context**

**Comment by piotrbak** [comment]
We didn't get enough feedback here to implement this enhancement soon. Closing it for now, we might get back to it in the future.
