### ISSUE TITLE
ExpiresByType text/html  prevents Cloudflare from caching content

### ISSUE THREAD

**Issue by pascalroget** [wp-media/wp-rocket#2005]
I'm not sure if or why it is necessary to set send cache-control: max-age=0 for HTML via .htaccess.
This prevents Cloudflare from caching static pages if the user desires to.

**Comment by webtrainingwheels** [comment]
Yes it's necessary to send that in most cases to ensure browsers have the latest content. 
In the case of Cloudflare Cache Everything,  you can override it in your Cloudflare account using the **Edge Cache TTL** setting: 
https://support.cloudflare.com/hc/en-us/articles/200172256-How-do-I-cache-static-HTML-
