### ISSUE TITLE
Time shown in preload message not respecting user's time location

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2008]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When I hit on preload action, it generates a message with the status of the number of pages preloaded, but it shows a wrong timing.

**To Reproduce**
1. Go in the adress https://www.gevcen.be/staging4
2. Open the plugin WP Rocket
3. Hit on preload action.

**Expected behavior**
The time shown in the error should respect the users' time location.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/66134558-c918b300-e5f8-11e9-9912-7d05432f0317.png)

**Additional context**
N/A

**Comment by arunbasillal** [comment]
What is the timezone set in the General settings of WordPress?

**Comment by gevcen** [comment]
![Desktop Time](https://user-images.githubusercontent.com/51261962/66188818-8f8f8880-e688-11e9-9428-4395b34984db.JPG)
![WordPress Time](https://user-images.githubusercontent.com/51261962/66188819-8f8f8880-e688-11e9-8aa7-b7b5e4a3a39f.JPG)

**Comment by arunbasillal** [comment]
The timezone set in WordPress shows `8:20` while your local time is `9:20`. So the timezone isn't right? 

Also, I hope you are using the latest version of WP Rocket. We had this issue that was fixed in 3.4 #1923

**Comment by arunbasillal** [comment]
Hello @gevcen Looking for an update on this one. Do you still see this issue even after correcting the timezone in WordPress and using WP Rocket 3.4?

**Comment by arunbasillal** [comment]
Closing this issue for lack of feedback and since I couldn't replicate. Hopefully this is resolved in 3.4. 

Please feel free to re-open if that isn't the case.
