### ISSUE TITLE
Preserve youtube-nocookie.com during LazyLoad

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2013]
While WP Rocket can identify youtube-nocookie.com YouTube links thanks to #911, the replacement doesn't respect this and simply uses youtube.com links. 

An example test is added here - http://mega.wp-rocket.me/nieuws/youtube-videos-arun/ (third video)

Related ticket - https://secure.helpscout.net/conversation/971332030/125325?folderId=273761

**Comment by crystinutzaa** [comment]
This must be fixed in Lazy Load Common and is fixed:
https://github.com/wp-media/rocket-lazyload-common/pull/56
