### ISSUE TITLE
Update Cloudflare "Find Your API Key" doc link

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2017]
This is the link in question: 

<img width="406" alt="cloudflare doc" src="https://user-images.githubusercontent.com/5751474/66404303-2d02f900-e9b6-11e9-9b94-ffeabaa59eb2.png">

Currently links to: https://support.cloudflare.com/hc/en-us/articles/200167836-Where-do-I-find-my-Cloudflare-API-key-
Which isn't very easy to understand. 

**Please update it to**: https://docs.wp-rocket.me/article/18-using-wp-rocket-with-cloudflare#add-on

We have blessings from @webtrainingwheels - https://wp-media.slack.com/archives/CFSCRLVGB/p1570484018001000

**Comment by webtrainingwheels** [comment]
As discussed with @arunbasillal let's link specifically to this section since it's most relevant for the context: https://docs.wp-rocket.me/article/18-using-wp-rocket-with-cloudflare#add-on

And for French it's: 
https://fr.docs.wp-rocket.me/article/247-utiliser-wp-rocket-avec-cloudflare#add-on
