### ISSUE TITLE
CDN Exclusion Not Working In Latest Beta

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2018]
When testing the beta version both .04 and .03 the CDN exclusion no longer appears to be working. 

To test setup a test website, enable the CDN feature (either for images or all files it happens either way). 
Add an exclusion such as (.*).png
Clear cache
.png files are still being served from cdn. 

I tested a variety of ways to exclude files, copying the whole url, copying the url starting at wp-content, etc it doesn't appear to be working. 

Downgrade to the latest stable version and the issue disappears. (3.3.7 is where I downgraded and the issue resolved its self).

**Comment by arunbasillal** [comment]
@Tabrisrp I was able to replicate this. The only difference is that a full exclusion worked in my case.

3.3.7 is installed here: http://mega.wp-rocket.me/divi/
With CDN exclusion of `/divi/wp-content/(.*)`

3.4.0.4 is installed http://mega.wp-rocket.me/
with these two exclusions:
```
/wp-content/uploads/2019/09/IMG_4635-100x100.jpg.webp
/wp-content/(.*)
```

The first one works as you can see in the source of http://mega.wp-rocket.me/nieuws/webp-image-test-arun/
The second exclusion doesn't.

**Comment by Tabrisrp** [comment]
This is happening because of the use of `preg_quote` in `get_excluded_files`, which will add a backslash before the tokens `.*` and prevent the regex from working.

Replacing `preg_quote` by `str_replace( $delimiter, '\\' . $delimiter, $file );` fixes the issue.
