### ISSUE TITLE
Add support for WebP Express

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2034]
Plugin - https://wordpress.org/plugins/webp-express/

WebP Express has 40,000 active installs and has CDN friendly modes of WebP delivery. 
Note that destination folder by default is `In Separate Folder`.

**Comment by alfonso100** [comment]
I've been testing WebP Express, and it looks we are compatible when their HTML rewriting is enabled:
![Screenshot at dic 27 12-12-15](https://user-images.githubusercontent.com/229406/71522272-bc77c400-28a2-11ea-8dd4-3fc75f57c247.png)

there's no need to enable WebP version in WP Rocket settings.

**Comment by piotrbak** [comment]
We didn't have enough feedback to move forward with this one. Moreover, we're comaptible with part of the plugin
