### ISSUE TITLE
Kinsta CDN compatibility improvements

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2046]
Right now we auto detect Kinsta CDN 

https://github.com/wp-media/wp-rocket/blob/21f00d1c3df4d83af1cfda109da86d9b0834bf07/inc/3rd-party/hosting/kinsta.php#L116-L131

However: 

- Customers do not have any UI feedback for this.
- They still need to enable the `CDN` option in WP Rocket settings. 

We can improve this and fix it for our customers. 

Kinsta doc: https://kinsta.com/blog/wp-rocket/

```
If you’re a Kinsta client, this menu [CDN tab] won’t be needed as the Kinsta CDN is automatically deployed on your site behind the scenes. However, we’ve noticed on a few sites that you might need to enter in your Kinsta CDN URL when WP Rocket is enabled. We recommend running your WordPress site first through a website speed test tool to confirm all of your assets (JS, CSS, and images) are loading from the Kinsta CDN. If they aren’t, try entering in your Kinsta CDN URL manually (example: mk0dgs321g.kinstacdn.com).
```

**Comment by alfonso100** [comment]
A ticket from a customer using Kinsta and their CDN:
https://secure.helpscout.net/conversation/1088789520/147129?folderId=2683093

The customer has noticed that, if he does not enable the WP Rocket CDN feature and doesn't enter kinsta's CDN URL the number of requests will increase. 
I spoke with Vasilis about this, and it is because we need that URL in our CDN tab to combine CSS/JavaScript files. 

So this part: 
> If you’re a Kinsta client, this menu [CDN tab] won’t be needed as the Kinsta CDN is automatically deployed on your site behind the scenes

is confusing for customers, as enabling our CDN  tab will be needed for some of our optimization features

**Comment by GeekPress** [comment]
@arunbasillal If we automatically turn on the CDN option, set up the CNAME, we should be good, isn't it?

**Comment by arunbasillal** [comment]
@GeekPress Yes, I think so. 

Kinsta doc says
> However, we’ve noticed on a few sites that you might need to enter in your Kinsta CDN URL when WP Rocket is enabled

I am wondering if we can know for sure if we do this for everyone if there will be any issue. There shouldn't be right? Maybe the best plan is to get in touch with them and confirm. What do you think?

**Comment by arunbasillal** [comment]
@engahmeds3ed said

> In sites that are hosted on Kinsta, they are using by default kinsta CDN so some WP Rocket functionality that uses rocket_url_to_path function like JS/CSS combine.
> So if CDN is not active this will make a conflict and won't return the file paths.

**Comment by remyperona** [comment]
Kinsta doesn't use CDN like that anymore, so we can close this.
