### ISSUE TITLE
Disable caching by IPs.

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2051]
Add a way to exclude IPs from seeing cached content.

**Related ticket:**
https://secure.helpscout.net/conversation/982054116/127180?folderId=2135277#thread-2767584608

**Comment by arunbasillal** [comment]
Related conversation - https://wp-media.slack.com/archives/C08N8J6VC/p1571409803215800

**Comment by arunbasillal** [comment]
This was discussed with the support team (slack thread above) and the general feedback was that this is a very rare feature request and one that can be handled with a helper plugin. 

@vmanthos tried something similar to this - https://github.com/wp-media/wp-rocket-helpers/blob/45d343a7ac5312ce5a5513882004ee767bf9a13d/cache/wp-rocket-no-cache-for-admins/wp-rocket-no-cache-for-admins.php#L60-L66

And it worked. Closing this for now. Thanks everyone for their feedback :)

**Comment by luckyankit** [comment]
Can anyone please provide an updated code for this. I tried that  code and it doesn't work anymore
