### ISSUE TITLE
Implement compatibility with Memcached

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2053]
**Is your feature request related to a problem? Please describe.**
There is currently no possibility to benefit from Memcached with WP Rocket. It's well known that multiple caching plugins should be avoided on a site, so using WP Rocket to preload the page cache and using W3 Total Cache on the same site for setting up Memcached isn't a good idea as some backend systems could overlay.

**Describe the solution you'd like**
Implement configuration to benefit from Memcached.

**Describe alternatives you've considered**
SG Optimizer (SiteGround).
W3 Total Cache

**Additional context**
N/A

**Comment by NataliaDrause** [comment]
another request: https://secure.helpscout.net/conversation/1990656022/364278?folderId=3864740

**Comment by kevin25** [comment]
i wonder why they don't support it while it's so good for performance and database load.

**Comment by piotrbak** [comment]
This is not something we'll be implementing anywhere soon.

**Comment by kevin25** [comment]
What a pitty. Your competitor is head you
