### ISSUE TITLE
Develop auto-regeneration of Critical CSS

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2054]
**Is your feature request related to a problem? Please describe.**
Currently, the page cache is able to get regenerated after X amount of time defined by the user. However, there is no way to regenerate at the same time the critical CSS.

**Describe the solution you'd like**
Please consider including the regeneration of critical CSS along the regeneration of page cache.

**Describe alternatives you've considered**
If the above doesn't work, please provide a separate setting to regenerate the critical every X amount of time (separately from the preload regeneration action).

**Additional context**
N/A

**Comment by arunbasillal** [comment]
Hello @gevcen Thanks for the feedback. 

The main reason why cache is regenerated is to accommodate for WordPress nonces. The Critical Path CSS for a page shouldn't change every 8 hours and the only time it changes is when the theme is changed or when CSS is updated manually. 

When the theme is switched, we regenerate Critical Path CSS automatically - https://github.com/wp-media/wp-rocket/blob/2431e8fd4771922d3a6e237cc31096a17b06843a/inc/classes/subscriber/Optimization/class-critical-css-subscriber.php#L48

Also note that Critical Path CSS generation uses our servers and is quite resource intensive at our end. 

Is there any other reason to regenerate Critical Path CSS that I missed?
