### ISSUE TITLE
Exclude CDATA from JavaScript combination

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2064]
Quite often we have to exclude keywords inside `CDATA` to fix the increased cache directory size issue.

Automatically excluding `CDATA` would significantly reduce that kind of issue.

**Related conversation:**
https://wp-media.slack.com/archives/C43T1AYMQ/p1571757619120300

**Example ticket:**
https://secure.helpscout.net/conversation/986527249/127834?folderId=2135277

**Comment by alfonso100** [comment]
Another case where 2 `CDATA` scripts caused a dir size issue:
https://secure.helpscout.net/conversation/1284375275/195431?folderId=2683093

**Comment by vmanthos** [comment]
**Related tickets:**
https://secure.helpscout.net/conversation/1436341939/242384/
https://secure.helpscout.net/conversation/1443527132/244491/
https://secure.helpscout.net/conversation/1442426480/244197

**Comment by piotrbak** [comment]
We didn't have enough feedback to move forward with this one.
