### ISSUE TITLE
Cloudflare warning shown despite API & Email are correct

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2082]
**Before submitting an issue please check that you’ve completed the following steps:**
Enter the Cloudflare email adress, API key and zone ID

**Describe the bug**
WP Rocket shows warning that either of the values are wrong.

**To Reproduce**
Credentials can be given in private.

**Expected behavior**
No warning to be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/67807675-95189c80-fa95-11e9-8b19-8ec62a964bd8.png)

**Additional context**
N/A

**Comment by arunbasillal** [comment]
Hello @gevcen 

We are currently investigating some issues related to Cloudflare in 3.4.1.1, but this seems to be unrelated to all of them. 

I am assuming that you have already verified that the credentials are correct. If so, could you please open a support ticket with WordPress admin + FTP credentials + Cloudflare login. We will not modify anything outside of WP Rocket settings without prior consent and credentials are always deleted after they are needed. 

We recommend https://revealit.me/ to securely send your credentials. It generates a URL for any message you store. After the URL with your message has been opened once, it destroys itself. 

Looking forward to it.

**Comment by Tabrisrp** [comment]
I believe this should be fixed by #2081

**Comment by arunbasillal** [comment]
I hope this is fixed with WP Rocket 3.4.1.2
