### ISSUE TITLE
Incorrect purge of expired cache files when using multilingual plugins

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2084]
**Describe the bug**
When checking for expired cached files based the lifespan, The following line is using an incorrect second parameter for `array_unique`. This is causing the returned value to only preserve the first entry of the array, instead of all the unique elements.

https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/classes/Cache/class-expired-cache-purge.php#L83

The purge was working fine for the remaining element, but not happening for any other language defined in the multilingual plugin. This is corresponding to some reports we had related to nonce not being updated automatically.

**Solution**
The issue is fixed by removing the incorrect parameter on this line.

**Comment by arunbasillal** [comment]
Related ticket - https://secure.helpscout.net/conversation/979414839/126691/
