### ISSUE TITLE
404 issue on some websites hosted with GoDaddy managed hosting

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2087]
We have seen this recently with some customers hosted on GoDaddy managed hosting where the homepage shows 404. 

**Removing our rewrite rules ([helper](https://github.com/wp-media/wp-rocket-helpers/raw/master/htaccess/wp-rocket-htaccess-remove-rewrites/wp-rocket-htaccess-remove-rewrites.zip)) fixes the issue.** 

Vasilis noted that the error 404 is thrown only for the homepage `/`.

HS Tags: `error 404` and `godaddy managed hosting`

Related tickets: 
- https://secure.helpscout.net/conversation/990101225/128473?folderId=377611
- https://secure.helpscout.net/conversation/994009311/129263/

Related conversations: 
- https://wp-media.slack.com/archives/C43T1AYMQ/p1572283271141700
- https://wp-media.slack.com/archives/C08N8J6VC/p1572527108077600

**Comment by arunbasillal** [comment]
@vmanthos reported. 

> I've been getting very inconsistent results, where the error 404  isn't there even with our rewrite rules in place.
> I've noticed that WP Rocket doesn't create a cache file immediately when accessing a page. I have to refresh a page a lot of times for this to happen.
> Also, the error 404 comes up after flushing their cache, but again it's not easy to reproduce.
> At this point, I think it's impossible to figure this out from our end.
> I propose we wait for GoDaddy to get involved.

**Comment by viobru** [comment]
Another related ticket: https://secure.helpscout.net/conversation/999690855/130365/

**Comment by piotrbak** [comment]
Another ticket:
https://secure.helpscout.net/conversation/998070233/130041?folderId=2415573

**Comment by arunbasillal** [comment]
We discussed this in our last support call. 

- Lucy tried to initiate contact with GoDaddy but no luck so far and slow responses
- It's time to take things into our hands and do what we can. 
- The solution we know is to remove rewrite rules for GoDaddy customers. 
- GoDaddy's managed hosting has their own caching. So that is where every request lands first. Removing our rewrite rules shouldn't affect performance at all. 

So let's do it 👍
