### ISSUE TITLE
WP Rocket causes notifications to be sent out in duplicate for BNWP

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2098]
WP Rocket causes notifications to be sent out in duplicate for Better Notifications for WP plugin.

This issue is described here: https://wordpress.org/support/topic/double-notifications-for-posts-and-pages/

And mentionned here: https://betternotificationsforwp.com/known-compatibility-issues/

It needs further investigation.

Related tag: https://secure.helpscout.net/search/?query=%20tag%3Abetter%20notification%20for%20wordpress

**Comment by piotrbak** [comment]
Resolved here:
https://github.com/wp-media/wp-rocket/issues/2620
