### ISSUE TITLE
Regenerate Critical Path CSS hangs and prevents cache preload

### ISSUE THREAD

**Issue by TechDaddyK** [wp-media/wp-rocket#2100]
After choosing "Regenerate Critical Path CSS" from the WP Rocket drop-down in the admin bar, I keep seeing the notification below even after refreshing the page. 

> Critical CSS generation is currently running: 10 of 20 page types completed. (Refresh this page to view progress)
> Critical CSS for front_page generated. (November 7, 2019 @ 11:06 am)
> Critical CSS for ambassador generated. (November 7, 2019 @ 11:06 am)
> Critical CSS for ambassador-post generated. (November 7, 2019 @ 11:06 am)
> Critical CSS for articles generated. (November 7, 2019 @ 11:07 am)
> Critical CSS for astra-advanced-hook generated. (November 7, 2019 @ 11:07 am)
> Critical CSS for nutrition-note generated. (November 7, 2019 @ 11:08 am)
> Critical CSS for page generated. (November 7, 2019 @ 11:08 am)
> Critical CSS for post generated. (November 7, 2019 @ 11:08 am)
> Critical CSS for product generated. (November 7, 2019 @ 11:08 am)
> Critical CSS for tribe_events generated. (November 7, 2019 @ 11:09 am)

![WP_Rocket_‹_Blue_Seal_—_WordPress](https://user-images.githubusercontent.com/1278435/68414131-34542880-0155-11ea-9367-fc4f2d21f2f4.jpg)

It never progresses beyond "10 of 20". It also seemingly prevents the preload of cache. 

Maybe related (???) is the fact that users have to refresh our WooCommerce-generated product detail pages (like https://blueseal.com/product/easy-cover-100-4/) in order to see the image and most product data.

We're using WP Rocket v3.4.1.2 on WP v5.2.4 with WooCommerce v3.8.0.

**Comment by Tabrisrp** [comment]
Hi,

For support, please open a [ticket](https://wp-rocket.me/support/?utm_source=github&utm_medium=wp_rocket_profile) and we will be happy to help you out! This will be the best channel for you to resolve the issue with our support team.
