### ISSUE TITLE
CDN srcset rewrites

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2107]
When rewriting `srcset` elements and one of the sizes is repeated, we will print wrong output (CDN URL will be multiplied) due to this change:
https://github.com/wp-media/wp-rocket/blob/389f7462cd9cc8424ab0b3ab88acea4db6884cd9/inc/classes/CDN/CDN.php#L71

To be more specific, we will be looking for `branding-magazine-news.png` in the already changed path.

Not sure if we should handle this kind of situation, as this doesn't seem to be correct markup:
http://snippi.com/s/6w69x4l

Look for: `branding-magazine-news.png 1024w`

Related ticket:
https://secure.helpscout.net/conversation/999401292/130285?folderId=2415573

**Comment by Tabrisrp** [comment]
The `srcset` sources were using relative URLs?

It's probably easy to fix by using `array_unique` on the `$sources` array before looping on it, to prevent doing multiple replacements of the same source origin.
