### ISSUE TITLE
PHP Warning touch() .mobile-active on NGINX

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#211]
Customer on NGINX server having this error:

```
PHP Warning: touch(): Unable to create file /…/wp-content/cache/wp-rocket/example-do-main.com/?s=example+do+main/.mobile-active because No such file or directory in /…/wp-content/plugins/wp-rocket/inc/front/process.php on line 178
```

Is WP Rocket trying to create the .mobile-active file before the cache file even exists ? 

Ticket (ES): https://secure.helpscout.net/conversation/263598522/24193/?folderId=628132

**Comment by rohitmanglik** [comment]
Hi Team, this issue is still present. Can you please include it in your todo list.

**Comment by retroriff** [comment]
Hello, any update?

**Comment by RBrang** [comment]
+1

**Comment by mkasu** [comment]
+1

**Comment by Alphabc** [comment]
+1
wp-content/plugins/wp-rocket/inc/front/process.php on line 197
(file already exists)
debian 8.1
nginx version: nginx/1.13.5
PHP 7.0.24-1~dotdeb+8.1 (cli) ( NTS )

Thx!
