### ISSUE TITLE
Compatibility with Speed Booster Pack plugin

### ISSUE THREAD

**Issue by jroddington** [wp-media/wp-rocket#2110]
Speed Booster Pack can be found at https://wordpress.org/plugins/speed-booster-pack/. Currently WP Rocket displays an error message when both plugins are installed and asks for deactivation of SBP. 

WP Rocket could provide compatibility with this plugin so that it is possible to use both in tandem (such as is done with Autoptimize for example). 

Here are screenshots showing all the features of the SBP plugin:

![image (3)](https://user-images.githubusercontent.com/39446646/68999235-f1e4c700-088b-11ea-8349-2d56bdb91ee7.png)
![image (2)](https://user-images.githubusercontent.com/39446646/68999236-f4dfb780-088b-11ea-9b40-c47c9d0fa0d3.png)
![image (1)](https://user-images.githubusercontent.com/39446646/68999238-f7421180-088b-11ea-9d57-0a6e8ad9a010.png)
![image](https://user-images.githubusercontent.com/39446646/68999239-f9a46b80-088b-11ea-85c7-673231ff43fa.png)

This can be discussed with the plugin developers or they can submit PR's if preferred to go that route.

**Comment by Tabrisrp** [comment]
That's a _lot_ of features in common to check and ensure compatibilities with. My personal take would be to keep it as a duplicate plugin.

**Comment by jroddington** [comment]
@Tabrisrp Thanks! Is there any other way to stop the error message, or would your suggestion basically mean that both plugins shouldnt used at the same time? Also, is it possible for their developers to do the compatibility work instead of us?

**Comment by Tabrisrp** [comment]
They shouldn't be used at the same time. If the developers of the plugin want to do the compatibility work they can, but we shouldn't do it on our side.

**Comment by arunbasillal** [comment]
I am in agreement with Remy on this one. For an end user, there is really no major reason to use both plugins at the same time. 

Autoptimize is a real exception. It has 1 million+ active installs. 

I am going to close this one. If anyone feels strongly against it, please feel free to re-open.
