### ISSUE TITLE
PHP warning: Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2118]
We have a few tickets reporting this PHP warning: 
`array_flip(): Can only flip STRING and INTEGER values! in wp-rocket/inc/classes/optimization/class-abstract-optimization.php on line 54`

In a previous ticket on a WPML site Remy has said:
>it's because he is using languages with the query string attribute (?lang=)
>Switching to the subdirectory structure will fix this

However is there anything we can do on our side to prevent the warning anyway?

Sample tickets: 
https://secure.helpscout.net/conversation/783028991/97255/
https://secure.helpscout.net/conversation/918028444/118041/
https://secure.helpscout.net/conversation/1006719128/131560/#thread-2839362969 (using gtranslate not wpml)

**Comment by Tabrisrp** [comment]
We can update the code to do the same thing but in a different way, which will prevent the warning
