### ISSUE TITLE
Disable stripping of comments when FacetWP is installed

### ISSUE THREAD

**Issue by kierantaylorio** [wp-media/wp-rocket#2121]
Issue:

When activating HTML minification FacetWP no longer outputs the HTML for its filters. I have found through testing that this is specifically related to the HTML comments being removed. 

Reproduce:

Enable HTML minification in WP Rocket after adding FacetWP filters to any page. 

Solution:

1. Add a filter so that HTML comments can be left in place when minifying the HTML
2. Add a compatibility file for FacetWP disabling comment stripping when detecting the plugin is installed and WP Rocket's HTML minification is activated

Additional information:

This issue is not specific to WP Rocket as this can be reproduced with other HTML minification plugins that remove HTML comments. However, it is something we may be able to address internally with some minor changes for our mutual customers.

**Comment by Tabrisrp** [comment]
What does those comments look like? We have a way of excluding certain comments patterns from being removed by HTML minification

**Comment by kieran-wpmedia** [comment]
I didn't know that we could exclude specific comments, sorry. The comment that is being removed is:
`<!--fwp-loop-->`

This appears to be a required element for FacetWP to work
Post explaining the comment: https://halfelf.org/2017/facetwp-json-api-wp_query-searches/
Docs: https://facetwp.com/documentation/developers/how-facetwp-works/

**Comment by webtrainingwheels** [comment]
Is there anything we can advise FacetWP do on their side to prevent this? Use a different comment format or something?

**Comment by Tabrisrp** [comment]
The change has to be on our side, to make an exception for their pattern
