### ISSUE TITLE
Missing topbar

### ISSUE THREAD

**Issue by Martha073** [wp-media/wp-rocket#2122]
Hi!
After upgrading to version: 3.4.2.1, the bar at the top of the page disappeared so that I cannot clear the page cache. Where can I find it now?

**Comment by Tabrisrp** [comment]
Hi,

For support, please open a [ticket](https://wp-rocket.me/support/?utm_source=github&utm_medium=wp_rocket_profile) and we will be happy to help you out! This will be the best channel for you to resolve the issue with our support team.
