### ISSUE TITLE
rocket_clean_post() running when saving drafts

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2124]
The `rockec_clean_post()` function is run after saving drafts of posts:
https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/common/purge.php#L56

This means that everything that is hooked to `after_rocket_clean_post` will also run.

For example, if someone is using Cloudflare's "Cache Everything" the `rocket_auto_purge_cloudflare_by_url()` function will run, increasing the hits to Cloudflare's API.

**Proposed solution:**

Add a check to see if a post is **draft** after the following line:
https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/common/purge.php#L56

```
if( 'draft' ==  get_post_status( $post_id ) ){
		return;
}
```

**Related ticket:**
https://secure.helpscout.net/conversation/1011323712/132260?folderId=2135277

**Comment by Tabrisrp** [comment]
Did you check the status of a post going from draft to published? I think we don't exclude this status because it's not yet updated at the time the action is ran, which would prevent the purge from occuring correctly

**Comment by vmanthos** [comment]
I've checked the code I've proposed and it works except for when someone changes a post from `publish` to `draft`. In this case, the cache isn't cleared and the page will still be available.

I haven't had the time to look more into this, but we could probably use the post status transitions hooks to resolve this:
https://codex.wordpress.org/Post_Status_Transitions#.7Bstatus.7D_.7Bpost_type.7D_Hook

**Comment by Tabrisrp** [comment]
A long time ago, status transitions were used instead of `clean_post_cache`, and that was causing issues too I believe (it's a time I was not there yet)

**Comment by webtrainingwheels** [comment]
Related ticket: https://secure.helpscout.net/conversation/1014986966/132954?folderId=377611
customer is seeing the notice when Scheduling a post.

**Comment by crystinutzaa** [comment]
There could be a solution.
1. Add the condition in `rocket_clean_post()` function:
`if ( 'draft' === $post->post_status ) return;`
2. On `pre_post_update` hook if previous status is `publish` and the current status is `draft` to delete the cache for that specific post.
What do you think? Will this work?

**Comment by arunbasillal** [comment]
I edited [this part](https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/common/purge.php#L80-L85) to be like so: 

```
error_log( "\n Post Status = " . $post->post_status, 3, dirname(__FILE__) . "/my_error_log.log" ); 

// No purge for specific conditions.
if ( 'auto-draft' === $post->post_status || 'draft' === $post->post_status || empty( $post->post_type ) || 'nav_menu_item' === $post->post_type || 'attachment' === $post->post_type ) {
	return;
}

error_log( "\n running rocket_clean_post ", 3, dirname(__FILE__) . "/my_error_log.log" ); 
```

And logged this: (Comments added extra)

```
 Post Status = draft
 Post Status = inherit
 running rocket_clean_post 
 Post Status = draft
 Post Status = draft
 Post Status = inherit
 running rocket_clean_post 
 Post Status = draft
 Post Status = publish // post published
 running rocket_clean_post 
 Post Status = publish
 running rocket_clean_post 
 Post Status = draft // switched back to draft
 Post Status = draft
```

**Notes:** 

- It works to plan when we switch from `draft` to `publish`. No problems there. 
- There is a [post status named `inherit`](https://wordpress.org/support/article/post-status/#inherit). We should probably exclude that too. 
- Switching from `publish` to `draft` is a problem as discussed before. Using what Cristina suggested should cover that.
