### ISSUE TITLE
Add target path and source path in rocket_css_content filter

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2127]
Currently only the content of the CSS files are sent in the filter.

https://github.com/wp-media/wp-rocket/blob/1a7cde69e787ee54492d82cd650465c2d653ba7d/inc/classes/optimization/CSS/trait-path-rewriter.php#L53

Add also the target path ( possibly also source path) in the apply_filter:
`return apply_filters( 'rocket_css_content', $this->move( $this->get_converter( $source, $target ), $content ), $target );`

**Comment by arunbasillal** [comment]
Related ticket: https://secure.helpscout.net/conversation/1005586614/131342?folderId=3083222
