### ISSUE TITLE
3.4.2: Cloudflare purge notice displayed on content update

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2130]
When updating content we don't normally show a notice that the WP Rocket cache has been purged. But with the new Cloudflare integration re: Cache Everything, we are showing a notice, when using the Classic Editor (didn't see it when using Gutenberg), that the CF cache has been purged: 
https://recordit.co/2oWn9LA9j2

**Comment by arunbasillal** [comment]
I thought this was [going to happen](https://www.wrike.com/open.htm?id=416470208), but couldn't replicate it during QA.

@crystinutzaa We do not show an admin notice when we clear caches automatically. 

We only show them when the user initiates it. For example, if the user clicks on the "Clear Cloudflare Cache" button from the admin bar, then the notice is displayed.

**Comment by webtrainingwheels** [comment]
Related ticket: https://secure.helpscout.net/conversation/1014986966/132954?folderId=377611

**Comment by arunbasillal** [comment]
More tickets: https://secure.helpscout.net/conversation/1016270610/133235?folderId=273761

**Comment by webtrainingwheels** [comment]
Sort of related: https://github.com/wp-media/wp-rocket/issues/2124

**Comment by glueckpress** [comment]
> when using the Classic Editor (didn't see it when using Gutenberg)

Yup, with Gutenberg too. (WPR 3.4.2.2, WP 5.3)

**Comment by alfonso100** [comment]
Another ticket, this customer says Cache Everything is disabled on his CF account. 
https://secure.helpscout.net/conversation/1016233693/133210?folderId=2683093

**Comment by webtrainingwheels** [comment]
@alfonso100 were you able to verify that the customer does _not_ have Cache Everything enabled? False detection of that on our part feels like an additional issue that should be investigated.

**Comment by alfonso100** [comment]
@webtrainingwheels yes, the customer sent the screenshot. aded it here: https://wp-media.slack.com/archives/C43T1AYMQ/p1575473036012400

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1029980682/136309?folderId=3051575
