### ISSUE TITLE
Mixpanel error in backend on plugin site

### ISSUE THREAD

**Issue by Netzlichter** [wp-media/wp-rocket#2131]
Hello,

the Mixpanel script is throwing the following error on the plugin site:

Loading failed for <script> with source "https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".

Would be great to give us a possibility to remove third party script.

Thank you.

**Comment by Tabrisrp** [comment]
On which page did you have this error?

**Comment by GeekPress** [comment]
Hi @Netzlichter 🤚

We haven't back from you since @Tabrisrp asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best
