### ISSUE TITLE
RegEx in CDN Rewrite is breaking some inline JS

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2132]
I have noticed this in 2 sites using the Newspaper theme (2 tickets in a row). Looks like our CDN rewrite is rewriting an inline JS and this is causing a console error:

**Uncaught SyntaxError: missing ) after argument list**

This is one ticket: https://secure.helpscout.net/conversation/1016380218/133305?folderId=273761
site: https://viralrang.com/

the other ticket:
https://secure.helpscout.net/conversation/1015948039/133168?folderId=2683093
site: https://www.earthava.com 

A part of the inline script gets replaced by our CDN rewrite, and this:
```javascript
            if ( !!navigator.userAgent.match(/Trident.*rv\:11\./) ) {
                htmlTag.className += ' ie11';
            }
```
becomes this:
```javascript
          if ( !!navigator.userAgent.match(https://i2f3j2a9.stackpathcdn.com/Trident.*rv\:11\./) ) {
                htmlTag.className += ' ie11';
            }
```

The function is this:

```javascript
//td_js_generator - mini detector
        (function(){
            var htmlTag = document.getElementsByTagName("html")[0];

	        if ( navigator.userAgent.indexOf("MSIE 10.0") > -1 ) {
                htmlTag.className += ' ie10';
            }

            if ( !!navigator.userAgent.match(/Trident.*rv\:11\./) ) { 
                htmlTag.className += ' ie11';
            }

	        if ( navigator.userAgent.indexOf("Edge") > -1 ) {
                htmlTag.className += ' ieEdge';
            }

            if ( /(iPad|iPhone|iPod)/g.test(navigator.userAgent) ) {
                htmlTag.className += ' td-md-is-ios';
            }

            var user_agent = navigator.userAgent.toLowerCase();
            if ( user_agent.indexOf("android") > -1 ) {
                htmlTag.className += ' td-md-is-android';
            }

            if ( -1 !== navigator.userAgent.indexOf('Mac OS X')  ) {
                htmlTag.className += ' td-md-is-os-x';
            }

            if ( /chrom(e|ium)/.test(navigator.userAgent.toLowerCase()) ) {
               htmlTag.className += ' td-md-is-chrome';
            }

            if ( -1 !== navigator.userAgent.indexOf('Firefox') ) {
                htmlTag.className += ' td-md-is-firefox';
            }

            if ( -1 !== navigator.userAgent.indexOf('Safari') && -1 === navigator.userAgent.indexOf('Chrome') ) {
                htmlTag.className += ' td-md-is-safari';
            }

            if( -1 !== navigator.userAgent.indexOf('IEMobile') ){
                htmlTag.className += ' td-md-is-iemobile';
            }

        })();
```

**Comment by vmanthos** [comment]
Similar to this issue, but not related to Newspaper, the RegEx here:
https://github.com/wp-media/wp-rocket/blob/7723e789d158d2bf00ee5da49ef9158061e158eb/inc/classes/CDN/CDN.php#L39

picks up the following inline JavaScript:
```JAVASCRIPT
(/[^\w\.]/)
(/[\._]/)
```
part of this:
```JAVASCRIPT
try {
  return _normalizeSemverString(ua.split(token)[1].trim().split(/[^\w\.]/)[0]);
  } catch (o_O) {
  }
  return "0.0.0";
  }
   
  function _normalizeSemverString(version) {
  var ary = version.split(/[\._]/);
  return (parseInt(ary[0], 10) \|\0) + "." +
  (parseInt(ary[1], 10) \|\0) + "." +
  (parseInt(ary[2], 10) \|\0);
  }
```

These are later rewritten with the CDN URL, breaking the JavaScript:
```JAVASCRIPT
return _normalizeSemverString(ua.split(token)[1].trim().split(https://clonewatchpci.b-cdn.net/[^\w\.]/)[0]);
```
```JAVASCRIPT
var ary = version.split(https://clonewatchpci.b-cdn.net/[\._]/);
```

Here is how the RegEx works in this specific case:
https://regex101.com/r/WU0fCb/2

**Ticket:**
https://secure.helpscout.net/conversation/1013915036/132786?folderId=2135277

**Comment by alfonso100** [comment]
@vmanthos I'm getting the exact same result with my case:
https://regex101.com/r/2CctDf/1

I have confirmed here that disabling our CDN rewrite solves the issue:
https://secure.helpscout.net/conversation/1015948039/133168/

![Screenshot at nov 27 12-40-06](https://user-images.githubusercontent.com/229406/69737412-1dc93d80-1113-11ea-9b4a-a388644aa4d3.png)

**Comment by piotrbak** [comment]
Affected
https://secure.helpscout.net/conversation/1013401590/132677?folderId=2415573

**Comment by alfonso100** [comment]
another case. 
https://secure.helpscout.net/conversation/1022484927/134969/

**Comment by vmanthos** [comment]
Another ticket:
https://secure.helpscout.net/conversation/1023457142/135188/

The following JavaScript was falsely rewritten:
```JAVASCRIPT
n.src = "https://cdn.segment.com/analytics.js/v1/" + t + "/analytics.min.js"; var a = document.getElementsByTagName("script")[0];
```
Intead of having this:
`https://cdn.segment.com/analytics.js/v1/FfN54zAXBKN62cZnwtnV5lhcZHlGmNo6https/analytics.min.js`
the result was:
`https://cdn.segment.com/analytics.js/v1/FfN54zAXBKN62cZnwtnV5lhcZHlGmNo6https://cdn.mailfloss.com/analytics.min.js`

Changing the inline JavaScript to the following prevented the rewriting:
```JAVASCRIPT
n.src = "https://cdn.segment.com/analytics.js/v1/" + t + "/" + "analytics.min.js"; var a = document.getElementsByTagName("script")[0];`
```

**Comment by mifrero** [comment]
Another case:

**Comment by mifrero** [comment]
Another case: 
https://secure.helpscout.net/conversation/1088062154/146978/

Adding this script on his website footer:
```
<script type="text/javascript">
(function(e,a){
var t,r=e.getElementsByTagName("head")[0],c=e.location.protocol;
t=e.createElement("script");t.type="text/javascript";
t.charset="utf-8";t.async=!0;t.defer=!0;
t.src=c+"//front.optimonk.com/public/"+a+"/js/preload.js";r.appendChild(t);
})(document,"99397");
</script>
```
is change for:
`<script type="text/javascript">(function(e,a){var t,r=e.getElementsByTagName("head")[0],c=e.location.protocol;t=e.createElement("script");t.type="text/javascript";t.charset="utf-8";t.async=!0;t.defer=!0;t.src=c+"//front.optimonk.com/public/"+a+"https://cdn.cursosdesarrolloweb.es/js/preload.js";r.appendChild(t);})(document,"99397");</script>`
