### ISSUE TITLE
Improve "Separate cache files for mobile devices" help text

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2134]
Currently in 3.4.2.2 this is how the UI looks like: 

<img width="406" alt="01" src="https://user-images.githubusercontent.com/5751474/69707496-e57c2c00-111f-11ea-8f75-e55679be3fbe.png">

- The wording says: `Mobile cache works safest with both options enabled. When in doubt, keep both.`
- Most users would enable both. 
- If the theme is responsive, separate cache file is not needed in fact. 
- If separate cache files are not present, our rewrite rules in .htaccess will be in place. In other words, there is a performance gain by NOT enabling the separate cache file option. In most cases the gain will be too small. 
- Separate caches also creates extra load during preload which is often unnecessary. 

Documenting this here so that we can improve on this later.

**Comment by arunbasillal** [comment]
Things we are trying to communicate here: 

- This option is not required if your theme is responsive. 
- This option is required if you have a mobile specific theme. 
- Enable this if your website looks differently on desktop or mobile after enabling WP Rocket. 
- Enable if you have mobile specific content. 

Suggested text: 

`Enable this if you have mobile specific content or a dedicated mobile theme. Most modern themes are responsive and should work without a separate cache. More info`.

**Comment by arunbasillal** [comment]
Based on the discussion here - https://wp-media.slack.com/archives/CFSCRLVGB/p1576549573006300

Final copy: 

`Most modern themes are responsive and should work without a separate cache. Enable this only if you have a dedicated mobile theme or plugin. More info`

`More info` links to https://docs.wp-rocket.me/article/708-mobile-caching/?utm_source=wp_plugin&utm_medium=wp_rocket (This link https://jmp.sh/5qe7CW3)

**Comment by gevcen** [comment]
Dear,

In the latest release 3.4.4, the new improved text isn't translated tough. I'm using French version but the text is still in English. Would be good to translate it? Suggestion below :

"De nos jours, la plupart des thèmes sont responsives et devraient fonctionner parfaitement sans avoir un cache spécifique pour les appareils mobiles. Activez cette option seulement si vous avez un site mobile avec un thème et des plugins spécialement dédiés."

![image](https://user-images.githubusercontent.com/51261962/72218855-079b0380-3540-11ea-994a-08a630510790.png)

**Comment by arunbasillal** [comment]
Thanks for catching this @gevcen. We (in fact I) forgot to assign this during the release. I will get this done for you and everyone :)
