### ISSUE TITLE
Lazy Load Google Maps

### ISSUE THREAD

**Issue by bernardoliveira** [wp-media/wp-rocket#2135]
**Describe the solution you'd like**
Most of the Google Maps sections are located on the footer page, most of them are not even displayed, therefore, we are creating and downloading requests and resources unneeded. This functionality could improve the user experience from both clients and WP Rocket users to have this easy option.

On every scroll and browser resize interval the script would check whether there are any maps in the viewport to be displayed. If yes, it loads (if it wasn’t loaded before) Google Maps API script file and then initiates the corresponding map instances.

**Describe alternatives you've considered**
There are several scripts that can help to integrate this functionality into WP Rocket. I'll leave some here.

https://www.jqueryscript.net/loading/lazy-load-google-maps-lazymap.html
https://osvaldas.info/examples/lazy-loading-google-maps/jquery.lazy-load-google-maps.js

Thank you for all the love and support!

**Comment by arunbasillal** [comment]
@bernardoliveira Thanks for the kind words. 

If you enable lazyload for iframes ( https://jmp.sh/wA8zFlT ) isn't this handled? I setup a test here: http://mega.wp-rocket.me/nieuws/lazyload-for-google-maps/ and it looks like it's working.

Please see this: https://jmp.sh/oHBcruk

**Comment by arunbasillal** [comment]
@bernardoliveira Following up to see if you had a chance to test the same.

**Comment by bernardoliveira** [comment]
Sorry for the late reply! I tested in several other websites and now everything is working, perhaps was some incompatibility. Thank you for your work and support <3

**Comment by arunbasillal** [comment]
Thanks for confirming. Glad to hear it :)
