### ISSUE TITLE
Stop clearing the entire cache when a user is added / updated / deleted

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2139]
**Is your feature request related to a problem? Please describe.**

By default, we clear the entire cache when a user is created, updated and deleted. On some websites like e-commerce websites, it could be a problem.

Each time a new order is created by a new customer, it means the entire cache will be automatically cleared.

In fact it doesn't make sense to have this behavior. Until the customer isn't logged in, there is no info related to them on the default caching file version. So we don't have a valid reason to clear the entire cache for logged out visitors.

**Describe the solution you'd like**

Don't clear the entire cache when a user is added / updated / deleted.

**Describe alternatives you've considered**

Clear the user cache if the "User Cache" option is turned on when a user is updated / deleted.

**Comment by luk911** [comment]
yes - it's a problem with my e-commerce website. Long-time I don't understand why all cache in cache directory was clearing. And now I understand - that has happened because I adding customers to WordPress

**Comment by luk911** [comment]
In WP Fastest Cache cool options don't all cache delete but only for that page.
![screenshot-8](https://user-images.githubusercontent.com/1578035/69944057-7031a200-14f7-11ea-9b06-2530264c8a36.jpg)

**Comment by arunbasillal** [comment]
During the meeting on 10.Dec.2019, we decided on these things: 

- Disable entire cache deletion for everyone when `user cache` is disabled OR if `rocket_common_cache_logged_users` is `true`. (on user creation, user update and user deletion). 
- For users with `user cache` enabled, the main cache is never deleted. The user specific cache will be cleared on user update or user deletion.
