### ISSUE TITLE
Link to Tutorials tab in welcome message?

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2140]
On a fresh install of WP Rocket, we show a little notice at the top: https://github.com/wp-media/wp-rocket/blob/17bbc04a0f1e925ecd9e4f3e1c8f06a2e1037db3/inc/admin/ui/notices.php#L592

> WP Rocket is good to go! Test your load time, or visit your settings

Should we also point people to the Tutorials tab for help configuring?

H/t @glueckpress

**Comment by piotrbak** [comment]
Welcome message will be redesigned soon based on the new requirements.
