### ISSUE TITLE
Error 403 on admin-ajax requests and WooCommerce nonces

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2149]
This is a copy of what @vmanthos reported here: https://hub.wp-media.me/wp-rocket/knowledge-base/issues/error-403-on-admin-ajax-requests-and-woocommerce-nonces/

In some cases, on WooCommerce websites with plugins, e.g. WooCommerce Mailchimp Discount, that use AJAX requests (admin-ajax.php), those fail with an error 403.

This is related to nonces and the way, when WooCommerce is installed, they are produced.

The issue has to do with the fact that WooCommerce uses the following filter, which is defined in the wp_create_nonce() function:

`$uid = apply_filters( 'nonce_user_logged_out', $uid, $action );`

When a user is logged out, WooCommerce sets the user ID for the non-logged in user to be the session ID, if one is set.

When WP Rocket generates the cache files, nonces are generated without any UserID (uid).

So, they are different than the ones WooCommerce creates. That’s why, when check_ajax_referer() is used in a plugin or theme, it fails during nonce validation.

The issue is also described here:

- https://github.com/CalderaWP/Caldera-Forms/issues/894
- https://codeclimate.com/github/skyverge/wc-plugin-framework/woocommerce/utilities/class-sv-wp-background-job-handler.php/source (lines 153-156)

**Comment by vmanthos** [comment]
To set things straight, @crystinutzaa was the one who discovered the mechanics of the issue. 

I just documented this. 😊

**Comment by vmanthos** [comment]
Another case:
https://secure.helpscout.net/conversation/1024456545/135380?folderId=2135277

This time the "Load more" AJAX functionality of the Newspaper theme is affected.

**Comment by crystinutzaa** [comment]
Closed with v3.4.4
