### ISSUE TITLE
Improve "Optimize" button on Database tab

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2154]
![optimize_button](https://user-images.githubusercontent.com/1043076/70173656-262bf600-1688-11ea-8dca-4d5ddbf05ac5.jpg)

A few customers have reported that this button is not very clear if all you want to do is adjust the automatic scheduling feature. It also means you can't adjust that setting without running another optimization. 
HS tags: `ui question` `database optimization`

Clear feedback in these: 
https://secure.helpscout.net/conversation/1020840922/134536?folderId=377611
https://secure.helpscout.net/conversation/986353448/127811#thread-2794220426

Another case:
https://secure.helpscout.net/conversation/1013222886/132633/#thread-2859074447

Ideas:
- Rename button to "Save Settings and Optimize" or similar
- Have an Optimize button above the Automatic Cleanup section and a Save Settings below Automatic Cleanup
- .... ?

**Comment by Tabrisrp** [comment]
In an ideal world, the process of optimizing would not live in the settings page, and that confusion would be avoided.

Since we were previously using 2 buttons, and we changed it because it was confusing too, that's probably not the way to go.

**Comment by arunbasillal** [comment]
If I remember correctly, we moved away from two buttons to a single button when we figured out how to trigger the optimization even when no settings were changed. Correct me if I am wrong please. 

I think, being explicit with the button to say `Save Settings and Optimize` as Lucy suggested should be clear enough for everyone. 

Another slightly complicated solution would be to change the text `Optimize` to `Save Settings and Optimize` only when customers change a setting in the UI. We could detect this with some JS.

**Comment by GeekPress** [comment]
Let's moving forward to this issue by changing the button label to `Save Settings and Optimize`
