### ISSUE TITLE
FOUC happens every now and then

### ISSUE THREAD

**Issue by codetipi** [wp-media/wp-rocket#2157]
Hey guys,

I've noticed the plugin has recently starting causing FOUC. It definitely wasn't happening before, but I can't tell exactly when it started (I develop every day, so constantly refresh without cache and have used the plugin for a long time). My feeling is it's started happening since one of the latest updates.
 
**Describe the bug**
FOUC occurs.

**Expected behavior**
No FOUC.

**Screenshots**
This is the css settings:
<img width="872" alt="Screenshot 2019-12-05 at 15 28 31" src="https://user-images.githubusercontent.com/22545313/70249163-e80c0080-1773-11ea-8da7-819b1aee59db.png">

I would've imagined the "Optimize CSS delivery" option might possibly cause FOUC, but I've never enabled it.

**Comment by Tabrisrp** [comment]
It's very unlikely to have FOUC without Optimize CSS delivery active. Did you open a support ticket so our support team could check the concerned website directly?

**Comment by arunbasillal** [comment]
@codetipi Please open a [support ticket](https://wp-rocket.me/support/) as Remy suggested so that our team can investigate your issue directly.
