### ISSUE TITLE
Cache recreated on each page load when WebP Caching is enabled

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2158]
This is a very similar case to this one:
https://github.com/wp-media/wp-rocket/issues/2156

When WebP Caching is enabled but `$_SERVER` array doesn't include `image/webp` value in the `HTTP_ACCEPT`, the `get_cache_path` function returns path without `-webp`.
https://github.com/wp-media/wp-rocket/blob/7723e789d158d2bf00ee5da49ef9158061e158eb/inc/classes/Buffer/class-cache.php#L286

@crystinutzaa has already investigated this problem.

Related tickets:
https://secure.helpscout.net/conversation/1005343810/131288/

**Comment by Tabrisrp** [comment]
I believe this should be fixed with the change here: https://github.com/wp-media/wp-rocket/pull/2147/files#diff-094b220e4f6e0e5e459bd40cbe4fafe8

I found it when doing testing for the #2147 PR changes, and it will be included in 3.5.
