### ISSUE TITLE
Create a local version of gtm.js file (Google Analytics Add-on)

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2160]
**Is your feature request related to a problem? Please describe.**

It's more an enhancement than a problem.

Our GA add-on is actually working on these files:

https://www.google-analytics.com/analytics.js
https://www.googletagmanager.com/gtag/js

But it seems to have a new one:

https://www.googletagmanager.com/gtm.js

The Inline JS:

`<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K3Z293R');</script> <script>(function(h,o,t,j,a,r){
h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
h._hjSettings={hjid:1476666,hjsv:5};
a=o.getElementsByTagName('head')[0];
r=o.createElement('script');r.async=1;
r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
a.appendChild(r);
})(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');</script>`

**Describe the solution you'd like**
Get a local version of https://www.googletagmanager.com/gtm.js  when Google Analytics add-on is activated.

**Comment by remyperona** [comment]
Closing this issue as Google tracking add-on will be removed in WP Rocket 3.9.
