### ISSUE TITLE
Flying Pages in WP Rocket

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#2161]
**Is your feature request related to a problem? Please describe.**
There is a new plugin on the area, Flying Pages. Its focus is either on preloading links the user is viewing at the moment in the viewport, or preloading links when the user hover the mouse on it.
These are brilliant contributions for preloading a website.

**Describe the solution you'd like**
WP Rocket has gone further in optimizing of the preloading of pages, besides deffering critical bytes, lazy loading...
I can only imagine what you guys could do, if preloading on hover was a WP Rocket feature.

**Describe alternatives you've considered**
Your plugin can take the lead in this area, implementing not only the preload on hover as an independent feature, but also merging it with the real preloading and minification techniques, "preloading on hover only critical css and html", OR the other way around -> "Preload on hover only images, or non-critical code". It is a feature that can add value to any other WP Rocket feature in an intelligent way, if you want.

**Additional context**
Flying Pages works well enough to already be used in Elementor Page Builder homepage.
https://wordpress.org/plugins/flying-pages/

**Comment by arunbasillal** [comment]
For internal use: We have the same request in Wrike as well - https://www.wrike.com/open.htm?id=399436710

**Comment by gevcen** [comment]
agree with @marceloaof, it would be a great feature request

**Comment by GeekPress** [comment]
Hi @ghost @gevcen 🤚

Please vote for this feature directly on our official roadmap:
https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/30-preload-pages-before-the-user-click-on-it

Cheers 😇
