### ISSUE TITLE
Not updating to 3.4.2.x through composer

### ISSUE THREAD

**Issue by synio-wesley** [wp-media/wp-rocket#2163]
**Describe the bug**

Version 3.4.2.x cannot be installed using Composer. Latest version that installs using Composer is 3.4.1.2. Cause might be that tagged versions now contain a dot after the 'v' (v.3.4.1.2 instead of v3.4.1.2)?

**To Reproduce**
1. composer require wp-media/wp-rocket
2. it should install version 3.4.1.2 (instead of expected version 3.4.2.x)
3. trying to force "v.3.4.2.2" in composer.json doesn't work, because then composer complains about `Could not parse version constraint v.3.4.2.2: Invalid version string "v.3.4.2.2"`

**Expected behavior**
Version 3.4.2.x to be installed through composer

**Comment by simonlayfield** [comment]
The latest version I can install via composer is 2.11.4

@synio-wesley Curious as to how you're installing 3.4.1.2. If you specify this version number does it not fail?

**Comment by synio-wesley** [comment]
Hi @simonlayfield if you just 'require wp-media/wp-rocket' it should install the latest available version, unless you have version constraints inside your composer.json file already (try removing it first, or update the version constraint manually?)

I have specified '^3.4' for my version constraints in composer.json to get the latest 3.x version, but it won't see 3.4.2.2 as the newest version because there's a dot after the 'v.' in the tag name. I think this is the problem...

**Comment by simonlayfield** [comment]
Ah - ok, interesting.

My deployment fails when specifying '^3.4' as the version - same with '3.*'. The only way I can get my deployment to work is using '*', which installs 2.11.4

**Comment by simonlayfield** [comment]
If I were to install this plugin using a zip file in composer, would anyone happen to know what to use as the value for `"autoload": {}` in order to activate the plugin automatically? If so, this'll be my workaround for now.

**Comment by Tabrisrp** [comment]
I updated the tag name to fix the issue, the update should be working with the latest version available: `3.4.2.2`

**Comment by synio-wesley** [comment]
Thanks @Tabrisrp It's working! :-)
