### ISSUE TITLE
Cant require wp-media/wp-rocket   runtimeexception?

### ISSUE THREAD

**Issue by mjmc-jporter** [wp-media/wp-rocket#2166]
Anyhelp with this?

[RuntimeException]                                                                                                                             
  Could not scan for classes inside "application/custom-content/mu-plugins/wp-rocket/inc/classes" which does not appear to be a file nor a folder  

if i run composer update right after this its fine.

**Comment by Tabrisrp** [comment]
Never ran into this before, can you give more information about your setup?

Was the issue a one-time thing, or can you repeat it?

**Comment by GeekPress** [comment]
Hi @mjmc-jporter 🤚

We haven't back from you since @Tabrisrp asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best

**Comment by Trisky** [comment]
Hi there. Just went through the same issue.

It seems that it happens if you run `composer install` in a system that doesn't have `unzip`. For example, if you run it inside a php container. 

Solution is just `apt-get install unzip` before running `composer install` in your Dockerfile
