### ISSUE TITLE
After clearing Autoptimize cache, rocket_clean_domain is not being called

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2167]
I have noticed that after clearing Autoptimize cache, using their menu bar link, our cache is not cleared and then we produce a 404 their combined JS and CSS files.

In our compatibility file we are checking if **autoptimize_do_cachepurged_action** exists, and if it does, we hook our **rocket_clean_domain** function to : **autoptimize_action_cachepurged**. However, this is not happening. 

https://github.com/wp-media/wp-rocket/blob/35533b0069b2f1313e30c2b310856daf47fd9880/inc/3rd-party/plugins/autoptimize.php#L4

This is the **autoptimize_do_cachepurged_action** function we are verifying: 
https://github.com/futtta/autoptimize/blob/c92350652fcb3213c8b0a7b65434a1ac74ddbf54/classes/autoptimizeCache.php#L368

If I verify a different Autoptize function, rocket_clean_domain gets called as expected.

Ticket: 
https://secure.helpscout.net/conversation/1019920724/134329?folderId=2683093

**Comment by Tabrisrp** [comment]
It was definitely working before, we'll have to do some tests to see what changed. Possibly a timing issue.
