### ISSUE TITLE
Replace YouTube iframe with preview image is not working when using relative protocol 

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2177]
When **Replace YouTube iframe with preview image** is active, and a Youtube video is added using a relative URL, our lazyload rewrite strips the // and it causes a 404 error when the video is played.

So, this kind of iframe:
`<iframe src="//www.youtube.com/embed/vWxHWLqO8yc" allowfullscreen="1"></iframe>`

When the user tries to play the youtube video, outputs like this, causing a 404 error:
`<iframe src="www.youtube.com/embed/vWxHWLqO8yc?autoplay=1" frameborder="0" allowfullscreen="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"></iframe>`

Related ticket:
https://secure.helpscout.net/conversation/1029194499/136176?folderId=2683093

**Comment by arunbasillal** [comment]
Replicated here: http://mega.wp-rocket.me/nieuws/youtube-relative-test/
When you click `Play` in the cached version, you will get a 404.

**Comment by crystinutzaa** [comment]
Closed with v3.4.4
