### ISSUE TITLE
PHP 7.4 notice - Trying to access array offset on value of type null, in class-cache-dynamic-resource.php

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2185]
On Kinsta, this website is showing this notice after upgraded to PHP7.4

`Notice: Trying to access array offset on value of type null in /www/xxxx/public/wp-content/plugins/wp-rocket/inc/classes/optimization/class-cache-dynamic-resource.php on line 170`

This is the specific line:
 https://github.com/wp-media/wp-rocket/blob/7723e789d158d2bf00ee5da49ef9158061e158eb/inc/classes/optimization/class-cache-dynamic-resource.php#L170

Ticket:
https://secure.helpscout.net/conversation/1028206508/136026?folderId=2683093

**Comment by Tabrisrp** [comment]
`get_rocket_parse_url` can return either an array of `null` if the provided parameter is not a string.

Before PHP 7.4, there was no warning when trying to access an offset of a `null` value, but now there is.

The easy fix is to check for the type of `$file` before using it and trying to access the offsets.

**Comment by hellofromtonya** [comment]
**This PHP 7.4 notice will be thrown anywhere in our codebase where we are using a non-array variable as an array.** 

This ticket specifically identifies one instance. However, please note, we will need to audit and fix all instances in our codebase to ensure WP Rocket is PHP 7.4 compatible.

## What's the notice and Why is it happening?

PHP 7.4 is more strict with data types. It now throws the above notice whenever a non-array variable is being used like an array. Here's some documentation on it:

- [Array-style access of non-arrays](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access)
- PHP 7.4: Fix issues regarding accessing null/bool/etc as if they were an array. [WP Core Trac Ticket 47704](https://core.trac.wordpress.org/ticket/47704)

**Comment by manuelRod** [comment]
Related: https://github.com/wp-media/wp-rocket/issues/2466
