### ISSUE TITLE
Include information about 3rd party cache clearing in WP Rocket cache clear notice

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2186]
When WP Rocket clears it's own cache, depending on the host or Cloudflare configuration, there are other caches that we clear automatically. Customers might not be aware of this and might be clearing multiple caches manually when it's not required. 

We had a customer request a `Clear All Caches` button during WCUS (and others via tickets) when in reality we do this already. 

Here are some examples: 
- Hosting cache like [Kinsta](https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/hosting/kinsta.php) for example.
- [Cloudflare cache](https://github.com/wp-media/wp-rocket/blob/7723e789d158d2bf00ee5da49ef9158061e158eb/inc/functions/cloudflare.php#L670-L711) if `Cache Everything` is used in CF settings.
- Some theme caches like [StudioPress Accelerator cache](https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/themes/studiopress.php). 

Searching for `before_rocket_clean_domain` and `after_rocket_clean_domain` gives a more complete list 
- https://github.com/wp-media/wp-rocket/search?q=before_rocket_clean_domain
- https://github.com/wp-media/wp-rocket/search?q=after_rocket_clean_domain

**Comment by piotrbak** [comment]
It doesn't have enough feedback from customers.
