### ISSUE TITLE
Update compatibility with ThirstyAffiliates

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2187]
Per their request could we update our auto-exclusion: 

> Move: https://github.com/wp-media/wp-rocket/blob/v3.4.2.2/inc/classes/optimization/JS/class-combine.php#L534
>into the $move_after_scripts array:
>https://github.com/wp-media/wp-rocket/blob/v3.4.2.2/inc/classes/optimization/JS/class-combine.php#L669

https://secure.helpscout.net/conversation/1031598174/136555?folderId=343175

**Comment by piotrbak** [comment]
It was moved to the file.
