### ISSUE TITLE
rocket_database_optimization_time_event - schedule doesn't change based on UI setting

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2188]
Dear,

I saved the plugin setting to be "weekly" but the task still runs daily as proven by the cron job review. Please check this video : https://gevcen.tinytake.com/tt/Mzk0Nzc4NF8xMjExNjQyMg

Can you fix this please?
Thanks

![image](https://user-images.githubusercontent.com/51261962/70855688-38e7cb80-1ecf-11ea-95a2-993cf7b9018c.png)

![image](https://user-images.githubusercontent.com/51261962/70855692-4e5cf580-1ecf-11ea-8329-f71f9e7c92d6.png)

**Comment by arunbasillal** [comment]
Thanks for the report @gevcen 

I tested this out and was able to replicate similar results. It seems that `rocket_database_optimization_time_event` is always scheduled to the interval that it is created and doesn't change as when the setting is changed. 

For example, I started with a monthly interval and it stayed that way even when I changed the scheduled interval to `daily`.

**Comment by crystinutzaa** [comment]
@arunbasillal I was not able to recreate this issue. It seems that the scheduled action is changed based on the Frequency set. Any idea how I can recreate this?

**Comment by arunbasillal** [comment]
@crystinutzaa You were right. I tried it out. 
The schedule takes a bit to update. Probably OPCache? I recorded a video - https://www.youtube.com/watch?v=VJLnsWiwFLw

@gevcen Could you please clear OPCache and recheck the reported issue again?

**Comment by arunbasillal** [comment]
Closing this since it seems to be invalid. @gevcen If you can still replicate this at your end, please open a support ticket to investigate if this is related to your setup.
