### ISSUE TITLE
Add Ezoic Integration to conflicting plugins list, with custom message

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2200]
https://wordpress.org/plugins/ezoic-integration/

They are deliberately preventing caching since they say it affects their ability to make the modifications their service provides: 
https://secure.helpscout.net/conversation/1028150089/136015?folderId=377610

Since there's not a solution, we should warn customers about the conflict. 
Since we have additional information for this case, we should provided a customized version of the conflict notice. 

Suggestion: 

> This plugin blocks WP Rocket's caching and optimizations. Deactivate it and use [Ezoic's nameserver integration](https://support.ezoic.com/support/solutions/articles/48000453926-name-server-integration) instead. 

https://secure.helpscout.net/search/?query=tag%3Aezoic%20integration

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Create a 3rd party subscriber `EzoicSubscriber` class. In this class, we will have one method `show_conflict_notice()` hooked on `admin_notices`.

In `get_subscribed_events()`, check for the constant `EZOIC_INTEGRATION_VERSION`, to see if the Ezoic plugin is enabled. Bail-out if it isn't.

In the method, we will need to:
- check for the current user capabilities if they are allowed to see the notice
- call `rocket_notice_html()` with the appropriate message

The subscriber needs to be initialized in the 3rd party service provider, and added to the common subscribers array in the plugin class.

### Estimate the effort ✅
Effort `[S]`, with unit & integration tests to be added.
