### ISSUE TITLE
2 slow queries in wp-admin wp-rocket settings

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2204]
**Before submitting an issue please check that you’ve completed the following steps:**
WordPress : 5.3.2
WP Rocket : 3.4.3
All other plugins up to date

**Describe the bug**
2 slow queries identified by Query Monitor extension.

**To Reproduce**
1) Install Query Monitor
2) Refresh the WP Rocket admin screen
3) Open the Slow Queries tab

**Expected behavior**
Slow queries should be avoided.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/71284793-e3df0600-2363-11ea-9d49-c50b76f29f4f.png)

**Additional context**
N/A

**Comment by gevcen** [comment]
![image](https://user-images.githubusercontent.com/51261962/71284844-02dd9800-2364-11ea-92b0-57236ce3a1cb.png)

**Comment by Tabrisrp** [comment]
These SQL queries are necessary to display the counters in the database optimization tab.

We can have a look to see if they can be optimized further, but there is no guarantee.

**Comment by gevcen** [comment]
Ok yes please investigate on this matter, and let me know. Thanks

**Comment by jorgemartine00** [comment]
related: https://secure.helpscout.net/conversation/1398833354/232111

**Comment by piotrbak** [comment]
It doesn't have enough feedback from customers.
