### ISSUE TITLE
Uncaught Error: Failed opening required file

### ISSUE THREAD

**Issue by alexstandiford** [wp-media/wp-rocket#2206]
**Describe the bug**
I use a logging utility that catches uncaught errors on the sites I host. This plugin has an error that crops up every once in a while on one of my sites.

```
Failed opening required '/home/wp/public_html/wp-content/plugins/wp-rocket/inc/functions/htaccess.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear')
```

**To Reproduce**
(sorry, I don't have steps to reproduce, only that it was detected)

**Expected behavior**
I expect that this error would be captured appropriately, or be changed so it doesn't happen at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/8210827/71321484-efc3e880-2487-11ea-854b-3e00192a84d5.png)
![image](https://user-images.githubusercontent.com/8210827/71321486-f0f51580-2487-11ea-8f69-37f7a691adf6.png)

**Additional context**
The site is hosted on WPEngine

**Comment by Tabrisrp** [comment]
Hi,

Did you check on your installation that the concerned file is indeed present?

**Comment by alexstandiford** [comment]
> Hi,
> 
> Did you check on your installation that the concerned file is indeed present?

I just now checked, and the file is there, and according to the modified date it appears to have been there since the plugin was installed.

**Comment by Tabrisrp** [comment]
Since the file is present, this seems to be a very odd error, especially since it's among other `require` for different files at the same time, why would it be specifically this one that doesn't work from time to time?

Did you also check with WPEngine about this? In our code there is nothing we can change here, errors from `require` are not catchable.

**Comment by alexstandiford** [comment]
From WPEngine:

> So looking over the server I do see there have been some requests that have been denied going to wp-content/plugins/wp-rocket/inc/front/process.php. The requests have been denied as a we do not allow write requests to files for users that are not logged in. 
> 
> Although I do see now that thread appears to be referring to a different file. I do not see that request getting blocked. Also the error in question appears to be referencing a cPanel style configuration of the files structures.
>
> The request is trying to make a request to a file that doesnt exist on the server. 

This doesn't seem to be relevant to the issue, but I can't tell.

**Comment by Tabrisrp** [comment]
The first part seems irrelevant to the issue at hand, but the last line seems to indicate that for them the file doesn't exist on the server?

I'm sorry I can't help further on that, on our side there is nothing else we can do.

**Comment by alexstandiford** [comment]
@Tabrisrp No, it's no problem. I know this is a vague issue, and I am almost certain it's related to WP Engine's config. The file _does_ exist. I checked.

This isn't causing any obvious problems to the site, so this can probably just be closed. If nothing else, at least it's been reported and if it crops up again someone else may be able to provide more info if they are getting the error in a replicate-able manner.

**Comment by Tabrisrp** [comment]
I'm going to go ahead and close this 👍 

It can be reopen if we have more details later, or it starts causing real issues.
