### ISSUE TITLE
3.4.3: CDN + Optimize CSS Delivery - assets not rewritten

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2217]
In 3.4.3 the CDN feature is not rewriting asset paths in critical path CSS.

The original assets are included in CSS files with relative paths (no idea if that part is relevant). They end being served twice, once from the origin and once from the CDN. 

The issue is not present when rolling back to 3.3.7 
https://secure.helpscout.net/conversation/1039885862/137956?folderId=377611

**Comment by vmanthos** [comment]
Another one:
https://secure.helpscout.net/conversation/1041996908/138380?folderId=273761

**Comment by GeekPress** [comment]
Another related ticket:
https://secure.helpscout.net/conversation/1053674116/140569?folderId=273761

**Comment by WordPresseur** [comment]
Another: https://secure.helpscout.net/conversation/1056032073/0/?folderId=273761

**Comment by alfonso100** [comment]
Another case: https://secure.helpscout.net/conversation/1062383184/142272?folderId=2683093
