### ISSUE TITLE
Fatal error: Call to undefined function Cloudflare\curl_init() in /inc/vendors/CloudFlare/Api.php on line 206

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#222]
This error is triggered when curl_init & curl_exec functions don't exist.

**Comment by webtrainingwheels** [comment]
This still seems to be an issue: 
https://secure.helpscout.net/conversation/519872505/59655?folderId=377611
https://secure.helpscout.net/conversation/515508231/59040/?folderId=273764

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/733924851/90571?folderId=377611
