### ISSUE TITLE
Split Critical CSS between Desktop & Mobile Devices

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2220]
**Is your feature request related to a problem? Please describe.**
Nowadays, most WooCommerce stores use responsive themes which provide different layout between desktop & mobile devices. Therefore, it's not relevant to generate a unique critical css file for both types of devices.

**Describe the solution you'd like**
The Critical CSS Generator shall distinguish desktop & mobile devices.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by arunbasillal** [comment]
Hello @gevcen . Happy new year!

Mobile specific CPCSS is already in the works for WP Rocket 3.6. In fact, development has already started on this I believe. 

Since we are already tracking this internally, I am going to close this issue. Thanks again for the feature request :)
