### ISSUE TITLE
Bad .htaccess rules on Showit Platform

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2226]
An interesting issue was occurring on a website hosted on Showit (which uses WPEngine as it's hosting platform). 

Every time the plugin was activated or saved it would end up spitting out an internal server error. We ended up tracing the error to the following in the htaccess file. 

When the plugin is activated it adds this top part of the .htaccess file 
Use UTF-8 encoding for anything served text/plain or text/html
AddDefaultCharset

It should be this with the UTF-8 following that rule:
Use UTF-8 encoding for anything served text/plain or text/html
AddDefaultCharset UTF-8

To stop it from crashing the site all together on every save we ended up adding the companion plugin as mentioned in the documentation here: https://docs.wp-rocket.me/article/110-resolve-500-internal-server-error#reference-htaccess-rules

While this prevents the rewrites it also stops the site from being broken on every save or clear due to the plugin. 

Possible solutions: 
Make sure the rule is UTF-8 on every save OR check for the Showit.co platform and disable all rewrites via a compatibility file. 

showit.co

**Comment by Tabrisrp** [comment]
The charset value is taken from the site option here: https://github.com/wp-media/wp-rocket/blob/72e1f60c4ae6f7f67900a33f559a63dcb7c8d364/inc/functions/htaccess.php#L513

If it's empty in the resulting htaccess code, it means it's not set there, which is unusual.

For this specific part, you can use this filter for exclusion from the htaccess `rocket_htaccess_charset` you don't need to remove the rewrite rules.

**Comment by piotrbak** [comment]
We haven't had any further feedback about that for 3 years, going to close it.
