### ISSUE TITLE
Update dependency a5hleyrich/wp-background-processing

### ISSUE THREAD

**Issue by clifgriffin** [wp-media/wp-rocket#2228]
**Describe the bug**
In the repo details, it includes instructions for installing WP Rocket via composer, however attempting to follow them results in this:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wp-media/wp-rocket v3.4.3 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.2.2 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.1.2 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.1.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.0.5 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.0.4 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.0.3 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.0.2 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4.0.1 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - wp-media/wp-rocket v3.4 requires a5hleyrich/wp-background-processing 1.3 -> no matching package found.
    - Installation request for wp-media/wp-rocket ^3.4 -> satisfiable by wp-media/wp-rocket[v3.4, v3.4.0.1, v3.4.0.2, v3.4.0.3, v3.4.0.4, v3.4.0.5, v3.4.1, v3.4.1.1, v3.4.1.2, v3.4.2.2, v3.4.3].
```

It appears a5hleyrich/wp-background-processing now resolves to this repo:
https://github.com/deliciousbrains/wp-background-processing

Which does not have a version 1.3. The highest version is 1.0.1?

There doesn't seem to be a new package in packagist for the new repo location. Using `composer require a5hleyrich/wp-background-processing` still works.

**Comment by clifgriffin** [comment]
Note, a workaround is to add this to your site's composer.json file:
```
"replace": {
      "a5hleyrich/wp-background-processing": "*"
    }
```

**Comment by hellofromtonya** [comment]
@Tabrisrp Can you confirm that we should be using `"tabrisrp/wp-background-processing"` package  instead of `"a5hleyrich/wp-background-processing"` package?

https://github.com/wp-media/wp-rocket/blob/72e1f60c4ae6f7f67900a33f559a63dcb7c8d364/composer.json#L27-L35

If yes, then we need to fix it like this:

```
    "require": {
		"php": ">=5.6.0",
		"tabrisrp/wp-background-processing": "1.3",
```

**Comment by hellofromtonya** [comment]
@clifgriffin Thanks alerting us. I think we're using `"tabrisrp/wp-background-processing"`, which is a modification of the `"a5hleyrich/wp-background-processing"` package. Remy will verify for us. Then we'll get it fixed.

**Comment by clifgriffin** [comment]
Note: The workaround is here: https://github.com/wp-media/wp-rocket/issues/741#issuecomment-392001608

Looks like this is a duplicate of #741, which I didn't find since it is closed.

**Comment by Tabrisrp** [comment]
Yes indeed the current workaround is noted in issue 741.

We are using a fork of the library because the original is not updated anymore. We can't put the fork on packagist to be able to get it as a dependency with composer directly, as it's not allowed, so for now that's the only solution.

We probably will move away from this library at some point, which will solve the issue at the same time.
