### ISSUE TITLE
Auto-detect Cloudflare Rocket Loader - Disable "Defer Parsing JS"

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2230]
**Is your feature request related to a problem? Please describe.**
If WP Rocket is linked to Cloudflare API, it shall automatically detect the status of their setting Rocket Loader.

**Describe the solution you'd like**
If Rocket Loader is enabled, WP Rocket shall disable and freeze the setting "Defer Parsing of JS" to avoid duplicate conflicts.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ScottTravisHartley** [comment]
I personally haven't run into a situation where defer and the rocket loader are not compatible with one another. I will note though page speed insights (common means of clients and users to measure their page speed) bypasses the rocket loader all together. If this was checked and ignored there is a strong possibility users will complain their JS is not being deferred.

**Comment by Tabrisrp** [comment]
One of our optimization when enabling the optimal settings option on our Cloudflare add-on is to disable the Rocket Loader from CF.

From our experience, Rocket Loader is causing more issues than it solves. So we won't prevent the use of defer JS in our plugin when Rocket Loader is enabled.
