### ISSUE TITLE
Add a way to directly exclude files from the CDN in WP Rocket's code

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2232]
With the CDN changes in 3.4 we are picking up more URLs than before, e.g. inline JavaScript.

Sometimes, this can break functionality such as in the case of OneSignal:
**Ticket:** https://secure.helpscout.net/conversation/1043339429/138628/

Although in the case of OneSignal there could be a fix on their side, we need to have a way to exclude URLs from being rewritten by the CDN feature, the same way we have for JavaScript files, inline JavaScript etc.

**Related Slack Discussion:** https://wp-media.slack.com/archives/C08N8J6VC/p1578061227103400?thread_ts=1577700561.067900&cid=C08N8J6VC

**Comment by Tabrisrp** [comment]
Doesn't this filter serve this purpose? https://github.com/wp-media/wp-rocket/blob/72e1f60c4ae6f7f67900a33f559a63dcb7c8d364/inc/classes/CDN/CDN.php#L336

**Comment by vmanthos** [comment]
Yes, it does. 😊

So we just have to start adding URLs there.

Thank you, Remy!
