### ISSUE TITLE
Satisfy Leveraging Browser Cache for MailChimp

### ISSUE THREAD

**Issue by twigandolive** [wp-media/wp-rocket#2235]
**Is your feature request related to a problem? Please describe.**
I continue to have PageSpeed issues with the Mailchimp code placed in the footer and pop-up on my site.

**Describe the solution you'd like**
The add-ons for Pixel to satisfy leveraging browser cache worked brilliantly. Do you think you can do something like this for Mailchimp?

**Describe alternatives you've considered**
As there isn't a way to set browser cache locally for an injected script, I'm hoping you have a workaround as you did for Pixel :)

**Additional context**
N/A

**Comment by GeekPress** [comment]
Hi @twigandolive 🤚

In 3.7, we have introduced a feature to delay JS execution. Delaying external JavaScript files is better than localizing them. I recommend you to try this new awesome feature :)
