### ISSUE TITLE
Plugin Incompatibility with PDF Embedder (Free and Paid versions) 

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2242]
For the FREE version - https://wordpress.org/plugins/pdf-embedder/

When our **JS combine** and Remove query strings from static resources are enabled, the PDF viewer doesn’t work. It displays an error like this in the place where the PDF file should be embedded:

_Setting up fake worker failed: "Cannot load script at: https://www.example.com/wp-content/cache/busting/1/wp-content/plugins/PDFEmbedder-premium-secure/js/pdfjs/pdf.min-4.4.worker.js"._

Disabling **Remove query strings from static resources** and excluding the plugin JS files from the JS optimizations solves the issue:

`/wp-content/plugins/pdf-embedder/js/(.*).js`

This plugin also has a premium version:
**PDF Embedder Premium** - https://wp-pdf.com/premium/

In this case the same fix works, you just need to change the plugin folder:
`/wp-content/plugins/PDFEmbedder-premium-secure/js/(.*).js`

**Comment by webtrainingwheels** [comment]
Looks like there are 3 possible versions of this plugin: 
https://wp-pdf.com/kb/using-caching-or-minifying-plugins/

**Comment by webtrainingwheels** [comment]
While their support person was responsive to my messages, there was never any confirmation that this would be fixed on their side. Should we move forward with our own fix? @GeekPress @arunbasillal

**Comment by GeekPress** [comment]
@webtrainingwheels Yes, it will better to have our own fix even it's not the best solution than nothing.

@wp-media/wprocketplugin Do you have enough info to groom this issue?
FYI, the complete list of JS files to exclude is available here:
https://wp-pdf.com/kb/using-caching-or-minifying-plugins/

**Comment by webtrainingwheels** [comment]
If I recall, I think maybe @alfonso100 started to work on a PR for this?

**Comment by alfonso100** [comment]
hey @webtrainingwheels yes, I created this compatibility file for **PDFembedder** and **PDFEmbedder-premium** a while ago. I didn't know there were 3 versions at that time, but it can be easily added, and based on [their exclusions list](https://wp-pdf.com/kb/using-caching-or-minifying-plugins/), more targeted to those particular files

This was the code: http://snippi.com/s/pgsfher

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
Create a compatibility file in `inc/ThirdParty/Plugins` for this plugin, using the code Alfonso already wrote as a base.

We no longer need to exclude from `Remove Query Strings` since the option was removed, so it will be specifically to exclude from minify/combine JS.

### Estimate the effort ✅ 
Effort `[S]`

**Comment by crystinutzaa** [comment]
@webtrainingwheels & @alfonso100 any idea how I can grab the third plugin version class name. Till now I have:
1. Free - `core_pdf_embedder`
2. Premium - ???? ( I used it as `pdfemb_premium_pdf_embedder` but I am not sure if this is the correct one)
3. Premium Secure - `pdfemb_commerical_pdf_embedder`

Can we contact their support so that they can provide us the class names?

**Comment by webtrainingwheels** [comment]
@crystinutzaa I sent a message to their support asking for a license. I believe we should have a full copy of the plugin available for testing on our side. If they don't reply in time, I think we should just buy a copy. Let me know when you'll need it by.

**Comment by crystinutzaa** [comment]
@webtrainingwheels I made the PR and I only need to write tests for it. This change is easy to be applied so I can work on it while we are waiting for their reply. This should be ready for QA this week to be included in v3.6.2 release.
@GeekPress Could we leave this PR for another minor release until we get a reply from them? 

It seems that Premium and Secure versions are different and we should buy both of them for our testing.

**Comment by GeekPress** [comment]
To not depend to when we will get their reply, I bought the plugins.

@crystinutzaa I guess we have everything to be able to finish this PR for this week, isn't it?

**Comment by crystinutzaa** [comment]
@GeekPress thank you! The PR is ready and in QA 🙏
