### ISSUE TITLE
Rename GZIP caching file with .gz instead of _gzip

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2245]
On NGINX server, it seems that serving our caching file with the extension `.gz` instead of `_gzip` helps to deliver our caching files faster.

@arunbasillal @hellofromtonya @Tabrisrp Is it possible to do some benchmark to validate that?

Related issue:
https://github.com/wp-media/wp-rocket/issues/1213

Related conversations:
https://secure.helpscout.net/conversation/1047434108/139419/
https://secure.helpscout.net/conversation/1053040835/140458?folderId=273761

**Comment by dillix** [comment]
This change can break sites which use https://github.com/SatelliteWP/rocket-nginx

**Comment by nsgoyat** [comment]
Hey @GeekPress 
Any update on this? I noticed that WP Rocket doesn't generate `.gz` version of cache files. Instead, it creates `index-https.html` and `index-https.html_gzip` files. CSS/JS files processed by WP Rocket are in `.gz` format but the cache files aren't.

A lot of Wp Rocket users like me use NGINX so it would be a great addition to the plugin...

**Comment by GeekPress** [comment]
Hi @nsgoyat,

We have no update and no ETA to provide you. We currently have 591 open issues, and we need to prioritize what we want to fix. This issue is more an enhancement and not something really urgent compare to other current issues we have.

**Comment by nsgoyat** [comment]
I never asked for an ETA. I was just wondering if you dropped the plans to add this compatibility for NGINX users or it's still on your list.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
