### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function get_rocket_cloudflare_api_instance() in /inc/admin/compat/cf-upgrader-5.4.php on line 3

### ISSUE THREAD

**Issue by BoiteAWeb** [wp-media/wp-rocket#225]
Fresh install on WP 4.6.1 on PHP 5.6

`Fatal error: Uncaught Error: Call to undefined function get_rocket_cloudflare_api_instance() in /Users/julio/Sites/wpsolo/wp-content/plugins/wp-rocket/inc/admin/compat/cf-upgrader-5.4.php:3 Stack trace: #0 /Users/julio/Sites/wpsolo/wp-content/plugins/wp-rocket/inc/admin/upgrader.php(314): require() #1 /Users/julio/Sites/wpsolo/wp-includes/plugin.php(524): rocket_new_upgrade('2.9', '2.8.14') #2 /Users/julio/Sites/wpsolo/wp-content/plugins/wp-rocket/inc/admin/upgrader.php(20): do_action('wp_rocket_upgra...', '2.9', '2.8.14') #3 /Users/julio/Sites/wpsolo/wp-includes/plugin.php(524): rocket_upgrader('') #4 /Users/julio/Sites/wpsolo/wp-admin/admin.php(154): do_action('admin_init') #5 /Users/julio/Sites/wpsolo/wp-admin/plugins.php(10): require_once('/Users/julio/Si...') #6 {main} thrown in /Users/julio/Sites/wpsolo/wp-content/plugins/wp-rocket/inc/admin/compat/cf-upgrader-5.4.php on line 3`

After some debug, the admin_init hook is triggerred before the end of plugin_loaded
The function is not defined yet.

**Comment by Tabrisrp** [comment]
Fixed it during beta testing of 2.9
