### ISSUE TITLE
Issues with Theme Requirements Notice

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2261]
There are some cases where the `theme requirements notice` isn't functioning as expected: 

- https://secure.helpscout.net/conversation/1054862262/140780/ - notice showed up but the elements are there, so it's a false positive
- https://secure.helpscout.net/conversation/1050621434/139992/ - notice didn't show up, and missing wp_footer was the cause of the problem.
- https://secure.helpscout.net/conversation/1054852673/140779/ - notice didn't show up, and unclosed html was the cause of the problem.

**Comment by arunbasillal** [comment]
Related discussion: https://wp-media.slack.com/archives/G8L4EE8N9/p1579209704008500

**Comment by GeekPress** [comment]
@webtrainingwheels Do we know how to reproduce the issues?

**Comment by webtrainingwheels** [comment]
@GeekPress I don't think so. The underlying issue is "not cached" or similar and is often resolved by manually observing the missing tags. Level 2 hasn't typically been called on to investigate why the notice itself didn't show up.

**Comment by arunbasillal** [comment]
@webtrainingwheels Can we make sure that next time this happens level 2 or Cristina (since she worked on the feature) gets to review the case please. All these are very curious cases. Let's try to figure out why.

**Comment by piotrbak** [comment]
There are no problems with this issue since more than 3 years. Going to close it.
