### ISSUE TITLE
Partial Preload IIS/Windows directory separator bug

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2262]
IIS / Windows Directory Separator is `\` and the conversion from filepath to url and url to filepath is wrong so Partial Preload is not working:

The first issue is related to logged checkup in here:
https://github.com/wp-media/wp-rocket/blob/57940fa791b42ee3ad96f648e376b01542d5822e/inc/classes/Cache/class-expired-cache-purge.php#L131

$dir_path will always be different than $this->cache_path so that partial preload will not work due to logged always true.
Wordpress default directory separator is `/` and 
`$dir_path     = $item->getPathname();` will get the value with `\`

The second issue is in here:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/subscriber/preload/class-partial-preload-subscriber.php#L144

Replacing path to url will cause wrong slashes which makes breaks partial preload.

Also this function might be affected by the DIRECTORY_SEPARATOR:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/preload/class-partial-process.php#L77
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/preload/class-full-process.php#L83

**The function which converts the URL to path and vice-versa can be optimized so the performance will be increased.**

**Comment by hellofromtonya** [comment]
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1330713824/209655?folderId=2135277

**Comment by mifrero** [comment]
Related ticket: https://secure.helpscout.net/conversation/1810674246/330535/

**Comment by piotrbak** [comment]
There's not enough feedback or complains. Feel free to reopen
