### ISSUE TITLE
Malformed displaying of polylang flags in the WP adminbar

### ISSUE THREAD

**Issue by basticodes** [wp-media/wp-rocket#2263]
With polylang installed the items clear cache and preload cache have options to clear / preload for every page.

But due to the shown flags there are some styling issues. See:
http://downloads.proxenos.de/_bug/polylang-flags.PNG

**Comment by arunbasillal** [comment]
Hello @basticodes 
Thanks for reporting this. We already have report of it here https://github.com/wp-media/wp-rocket/issues/510

I will close this one and make sure this gets corrected asap. 

Best regards.
