### ISSUE TITLE
Improve varnish cache support to clear only what is necessary

### ISSUE THREAD

**Issue by cdvv7788** [wp-media/wp-rocket#2264]
Whenever I try to `clear cache`, a PURGE request with `/.*` is sent to varnish. This has some a little issue: PURGE in varnish does not handle regexes.
If we filter the request method in VCL, and change it to use BAN, it works, however we get a troublesome situation when we update a single element in the site:
- A PURGE request with `/.*` is sent to varnish, so if we implement the BAN action as previously described, the WHOLE cache will be BANNED. This is the main issue, clearing the whole cache when updating a single post.
- There are a lot more PURGE requests sent to specific paths. They have a header with the method, so those could be used to decide which method to use (BAN or PURGE) if the previous problem didn't exist.

I am not sure about how wp-rocket works in this case (if it should clear the whole cache every time I update a single entry), but it sounds like it is not the way varnish cache should be invalidated.

**Comment by trendymail** [comment]
Hi!

Same problem here.

When WP Rocket sends a PURGE request to Varnish with URL "/" or "/*", I have to ignore these requests because I do not want the whole Varnish cache invalidated (images, css, js, etc).

PURGE requests should be tied to pages/category/posts (if this is possible).

Have a nice day!

**Comment by GeekPress** [comment]
Hi @cdvv7788 🤚

Thanks for your contribution!

@Tabrisrp Do you have any ideas about this issue?

**Comment by Tabrisrp** [comment]
To give more context on how the Varnish sync works:

With our purge request we are following the recommended configuration from Varnish: https://www.varnish-software.com/wiki/content/tutorials/wordpress/wp_step_by_step.html#handling-purge-requests

- If the purge request contains the header X-purge-method: regex, it uses ban
- If not, it uses a normal purge

The purge requests are sent right before a purge event happend in WP Rocket:
- The whole cache was cleared
- The homepage was cleared
- A content was modified, so a partial clear happened

See: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/Addon/Varnish/Subscriber.php#L44

**Comment by trendymail** [comment]
Hi!

I could be wrong but, AFAIK, header "X-purge-method" is not handled by the default builtin VCL file of Varnish.

Instead, you have to handle this specific header manually. So you need to write a "custom" VCL rule.

Nevertheless, if WP Rocket could send regex compatible ban requests, it would be great!

Have a nice day!

**Comment by GeekPress** [comment]
> Nevertheless, if WP Rocket could send regex compatible ban requests, it would be great!

@Tabrisrp Is it something we can do?

**Comment by Tabrisrp** [comment]
It's already possible to filter the method use to send the requests to Varnish, using the `rocket_varnish_purge_request_args` filter: https://github.com/wp-media/wp-rocket/blob/c7a020448d6639ca3cb4cddf72195f9d9c18fbec/inc/Addon/Varnish/Varnish.php#L106

The default `PURGE` value can be replaced by `BAN` with that.

**Comment by piotrbak** [comment]
When updating the single entry the `/*` is not sent anymore.

Varnish method can be filtered to match whatever VCL settings are being used.
