### ISSUE TITLE
Prevent the use of CDN on images when ShortPixel AI is enable

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2270]
**Description**
ShortPixel Adaptative Images plugin: https://wordpress.org/plugins/shortpixel-adaptive-images/ has a feature to replace images and CSS domain with their CDN CNAME: https://cdn.shortpixel.ai/spai

This results in this type of URLs: https://cdn.shortpixel.ai/spai/w_786+q_lossy+ret_img+to_webp/https://domainname.com/wp-content/uploads/2017/11/6150e363-786d-3317-9865-e08c2aabc1d4.jpg

If our CDN feature is enable for images, https://domainname.com/ will be replaced by the other CNAME provided there (e.g: cdn.cname.com), and WP Rocket will render this type od URLs : 
https://cdn.shortpixel.ai/spai/w_786+q_lossy+ret_img+to_webp/https://cdn.cname.com/wp-content/uploads/2017/11/6150e363-786d-3317-9865-e08c2aabc1d4.jpg

Which will leads to 404 on images.

**To Reproduce**
This issue only occur when a CDN is in place in WP Rocket (like RocketCDN), so it requires to set a  CDN first. Then, these are the steps to reproduce the behavior:
1. Search, install & activate **[ShortPixel Adaptive Images](https://wordpress.org/plugins/shortpixel-adaptive-images/ )** plugin
2. Login/signup here https://shortpixel.com/login and [associate your domain to your account](https://help.shortpixel.com/article/94-how-to-associate-a-domain-to-my-account)
3. Go to ShortPixel AI Settings page > Advanced tab : /wp-admin/options-general.php?page=shortpixel_ai_settings_page&section=adv-settings
4. Check if API URL is : https://cdn.shortpixel.ai/spai
5. Save your settings
6. Clear WP Rocket’s cache & wait for their CDN to catch your images (it may take up to 5 minutes after you associated a domain, for the CDN to start serving the images instead of redirecting to origin.)

As the WP Rocket's CDN feature is enable for images, https://domainname.com/ will be replaced by the CNAME provided there (e.g: cdn.cname.com), and WP Rocket will render this type of URLs : 
https://cdn.shortpixel.ai/spai/w_786+q_lossy+ret_img+to_webp/https://cdn.cname.com/wp-content/uploads/2017/11/6150e363-786d-3317-9865-e08c2aabc1d4.jpg
_instead of :_
https://cdn.shortpixel.ai/spai/w_786+q_lossy+ret_img+to_webp/https://domainname.com/wp-content/uploads/2017/11/6150e363-786d-3317-9865-e08c2aabc1d4.jpg

Which will leads to 404 on images.

**Backlog Grooming**
- [x] Issue cannot be reproduced

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
I cannot reproduce it on my localhost or on mega.wp-rocket.me. I checked client ticket to grab some more info, but it seems that there is no more info in there either.
I checked the log file from ShortPixel AI plugin and I may assume they fixed it on their side based on this log: `* Add preconnect header.` so we should ask the clients to upgrade to v.1.8.
The URLs are modified and include the CDN provided in WP Rocket, however the image is well displayed and I get a redirect to the CDN url.
URLs will look like this (eg. from mega.wp-rocket.me):
`https://cdn.shortpixel.ai/spai/w_970+q_lossy+ret_img+to_webp/https://e5i6p7w7.rocketcdn.me/wp-content/uploads/2020/02/rotekirsche20-WBQtvJoh9Og-unsplash-1549x2000.jpg`
and will be redirected to:
`https://e5i6p7w7.rocketcdn.me/wp-content/uploads/2020/02/rotekirsche20-WBQtvJoh9Og-unsplash-1549x2000.jpg`
https://wordpress.org/plugins/shortpixel-adaptive-images/#developers


**Scope a solution** ✅ 
I think solution is on their side ( ShortPixel AI)

I have contact from Shortpixel and I can contact them to clarify what the preconnect header means. Should I contact them to clarify?

**Estimate the effort** ✅ 
No effort for this one.

**Comment by hellofromtonya** [comment]
@arunbasillal What do you think about what @crystinutzaa found?

**Comment by arunbasillal** [comment]
@WordPresseur Can you please reach out to the customer and confirm this?

**Comment by WordPresseur** [comment]
waiting for customer feedback here: https://secure.helpscout.net/conversation/1058120785/141412/

**Comment by WordPresseur** [comment]
At this point, we won’t get any feedback from the customer. I’m closing it and will reopen it if needed.

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1365142867/222623
