### ISSUE TITLE
Feature Request - Add button "preload" at page / article / product level

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2282]
**Is your feature request related to a problem? Please describe.**
Assume the case in which my entire site is preloaded. However, I'm updating only one page which therefore requires that (1) the cache of that page must be cleared and (2) the cache of that page must be then preloaded.

**Describe the solution you'd like**
For the first part, there is no problem because we already have a button "clear cache" for each page. However, for the second part, we don't have a button "preload cache" at page/article/product level.

**Describe alternatives you've considered**
Next to the button "clear cache", add the button "preload cache" so that we don't have to preload the entire cache for having this page cached again.

**Additional context**
![image](https://user-images.githubusercontent.com/51261962/73135436-3cc84b00-4042-11ea-8bfe-a91dbbf60eb1.png)

**Comment by GeekPress** [comment]
Hi @gevcen 🤚

Thanks for your contribution and suggestion.
For your information, if the preload feature is turned on, this button will be totally useless and you won't need to have one.

**Why?**
When you will update your post, WP Rocket will automatically preload the cache of your post 😇
