### ISSUE TITLE
Exclude JS From Defer via Admin Panel

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2290]
When working even on a moderately complicated website's often times there is a JS file that needs to be excluded from being combined. Often times a JS is also in need of being excluded from defer but the current method is a bit cumbersome. 

Currently, if I run into an issue with defer / combine I have to exclude the file from being combined in the admin panel. Then I need to exclude the file from being deferred via PHP. This is a bit annoying when attempting to diagnose what JS needs to be excluded. 

For instance, I am working on a site powered by WP Job Manager / Listify I need to exclude many files from combine AND defer to help determine what the problem child is. But being able to do half of the ignoring from the admin panel and the rest requiring me to add via PHP is becoming a bit tedious. 

There is already an area to exclude both inline JS as well as files but being able to exclude JS files from defer in a similar fashion would make this substantially easier.

I also don't think this option should be merged into the existing "Excluded JavaScript Files" option for a couple of reasons. Many times a file can still be minified but just isn't able to be deferred. On the flip side, many times a JS file can be deferred but it can't be merged (oftentimes this happens with 3rd party JS).

**Comment by jazir5** [comment]
+1

**Comment by webtrainingwheels** [comment]
Another request for this: https://secure.helpscout.net/conversation/1166771383/165715?folderId=377611

**Comment by NataliaDrause** [comment]
One more request: https://secure.helpscout.net/conversation/1229505479/181192

**Comment by Camilo517** [comment]
+1

**Comment by GeekPress** [comment]
Closing this one in favor of https://github.com/wp-media/wp-rocket/issues/3233
