### ISSUE TITLE
Cloudflare empty error

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2295]
When recreating a specific scenario WP Rocket will display the following output:
![image](https://user-images.githubusercontent.com/26767037/73772252-b9140a00-4777-11ea-98c2-189e8554da3d.png)

Steps to reproduce:

1. Fill the wrong Cloudflare details
2. Save options
3. Switch Cloudflare to the Development Mode or turn on the Optimal Settings
4. Save options

The error is caught here, but it's not displayed:
https://github.com/wp-media/wp-rocket/blob/4b8b155c0a3c5543f70867a4b26725e1dbd8457e/inc/functions/cloudflare.php#L293

Errors that are logged when reproducing and they're not displayed:
`2020-02-04 17:48:30] Error: Array
(
    [0] => Could not route to /zones/ZONE_ID/settings/development_mode, perhaps your object identifier is invalid?
    [1] => No route for that URI
)`

Related ticket:
https://secure.helpscout.net/conversation/1073800207/144348?folderId=2415573

**Comment by piotrbak** [comment]
An empty error also occurs when enabling Cloudflare add-on for the first time and providing correct data. Steps to reproduce:

1. Enable Cloudflare Add-on
2. Provide correct data and enable Optimal Settings
3. Save settings

Screencast:
https://jmp.sh/ax26MYQ

**Comment by Tabrisrp** [comment]
Can you test if that issue is still present on 3.5 alpha when it's available?

**Comment by piotrbak** [comment]
In 3.5 alpha the error message is still present but it's not empty. Scenario:
-Install WP Rocket
-Provide correct CF details
-Enable Optimal Settings
-Save settings

Error message:
Cloudflare email and/or API are not set
https://jmp.sh/QJpSkM7

**Comment by GeekPress** [comment]
Thanks @piotrbak for the feedback.

Could you please open a new issue with the behavior? We will close this one.

Why?
We are considering the original issue "fixed" as we don't have blank error anymore. Now we have multiple duplications of the message. It's new bug.
