### ISSUE TITLE
Custom error message for WordPress.com

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2299]
When a customer tries to activate WP Rocket on WordPress.com, they get 
>WP Rocket cannot configure itself due to missing writing permissions."

related to `advanced-cache.php`

Since we know they can't use WP Rocket on WordPress.com, it would be more ideal to show a custom error message here instead.

**Comment by webtrainingwheels** [comment]
We had 23 tickets for this in May:
https://secure.helpscout.net/search/?query=tag%3Awordpress.com%20between%3A2020-05-01%262020-05-31

**Comment by GeekPress** [comment]
> We had 23 tickets for this in May:

Even adding this notice won't reduce the number of tickets. The users will still ask a refund. The best solution will be to make WP Rocket compatible on WP.com (if possible ^^)

I asked from someone from Automattic to know how we could work on a compatibility. The suggestion was to submit a request to this form: https://wordpress.com/support/developers/

@webtrainingwheels Can you take the lead on this contact?

**Comment by webtrainingwheels** [comment]
@GeekPress Sent a message via the form you linked above

**Comment by webtrainingwheels** [comment]
@GeekPress I got a reply from them, they're going to provide us with a testing site

**Comment by GeekPress** [comment]
What a great news :)

**Comment by webtrainingwheels** [comment]
Account info: https://wp-media.slack.com/archives/G8L4EE8N9/p1592844721002200

**Comment by GeekPress** [comment]
I'm closing this one in favor of https://github.com/wp-media/wp-rocket/issues/2814
