### ISSUE TITLE
Exclude jQuery that is added with jQuery Manager for WordPress

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2301]
The [jQuery Manager for WordPress](https://wordpress.org/plugins/jquery-manager/) plugin allows the user to load the jQuery version of their choice.

If it's not the default WordPress one, `jQuery not defined` errors pop-up in the JavaScript console, because we do not automatically exclude it from JavaScript minification/combination and deferring.

**Steps to reproduce**
1. Install the [jQuery Manager for WordPress](https://wordpress.org/plugins/jquery-manager/) plugin.
2. Go to _Tools > jQuery Manager for WordPress_
3. Select any from the non-default jQuery versions:
![](https://i.vgy.me/u68wcj.jpg)
4. Add some inline `jQuery` code, e.g.:
```JavaScript
<script>
jQuery('.toHide').on('click', function() {
  jQuery(this).hide();
})
</script>
```
5. Enable WP Rocket's **Defer JavaScript feature**
**Related ticket:** https://secure.helpscout.net/conversation/1073480224/144294/
6. Check the JavaScript console. A `jQuery not defined` error should appear there:

**Related ticket: **
https://secure.helpscout.net/conversation/1073480224/144294/

**Comment by piotrbak** [comment]
After talk with @vmanthos we can close the issue. It was created before we introduced Defer JS for inline scripts.
