### ISSUE TITLE
Improve our compatibility with XtremeCache from o2switch

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2305]
It looks like our `Purge` command doesn’t clear properly the o2switch XtremeCache.

Tickets: https://secure.helpscout.net/search/?query=tag%3Ao2switch%20xtremcache

**Comment by arunbasillal** [comment]
Romain said that we are waiting on: `o2switch boss to provide us a dedicated test environment`

**Comment by WordPresseur** [comment]
I received the testing environment and I’ve tested it. WP Rocket’s purge also purge the XtremeCache. So I’m closing this.
