### ISSUE TITLE
Use Action Scheduler for background processing

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#2315]
Right now the primary issue with the delicious brains batch processing is it stores everything in wp_options and tries to use admin-ajax to keep the queue going. The preloader is also badly designed in my opinion such that all URLs are stored as a single batch vs individual.

The problem with that is no way to detect for the actual progress of the queue beside the simple options based counter.

the latest action scheduler (https://actionscheduler.org) stores to a dedicated table and has integrated delicious brains async class, but it does not rely on it 100%, and you can still process everything individually.

This overall would provide better scalability and performance in both shared hosting and more advanced setups/use cases.

I have had to write a plugin myself not too long ago that hooks into the WP HTTP API to abort the ajax callbacks from the preloader and force everything on the CLI/cron, and I would like to see that not be needed truthfully.

Thanks :)

**Comment by GeekPress** [comment]
@hellofromtonya @Tabrisrp What are your thoughts about that?

**Comment by Tabrisrp** [comment]
Overall I agree on that, we do have to do testing to make sure action scheduler can process each task fast enough for the preload. The default values are fairly conservative, and I fear they might be too low.

They provide filters to change those values, but it's something we have to be careful with at the same time since the filters would impact all plugins using action scheduler (like WooCommerce).

**Comment by hellofromtonya** [comment]
I agree. We need to a hard look at it, run it through some testing and benchmarking, and then analysis how its impacts.

**Comment by jazir5** [comment]
Bumping this, Woocommerce 4 includes the new Action Scheduler by default. This would likely result in massive performance improvements on Woocommerce based websites.

**Comment by SeparateReality** [comment]
+1 especially with woocommerce

**Comment by piotrbak** [comment]
Preload feature is using Action Scheduler since 3.12 version.
