### ISSUE TITLE
WooCommerce Gutenberg blocks: "wp not defined" error with JS combination/deferring

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2318]
When WooCommerce Gutenberg blocks are being used on a page, there is a `wp not defined` error when the following WP Rocket options are enabled:

* JavaScript combination
* JavaScript deferring

The solution is to exclude the following files from both processes:

```PHP
/wp-includes/js/dist/api-fetch.min.js
/wp-includes/js/dist/hooks.min.js
```

Depending on the blocks that are used more files and inline JavaScript have to be excluded.

For example, if the **All Reviews** block is used these two exceptions have to also be added:

```PHP
/wp-includes/js/dist/url.min.js
```
and this inline JavaScript:

```JavaScript
wcSettings
```

This can be reproduced in our MEGA site.

**Related ticket:** https://secure.helpscout.net/conversation/1079564082/145400?folderId=377611#thread-3068022924

**Comment by vmanthos** [comment]
The following file also has to be excluded from deferring:
`/wp-includes/js/dist/i18n.min.js`

**Comment by Tabrisrp** [comment]
Is this related to #1720 ? Did you do the test with/without the Disable Emoji option?

**Comment by vmanthos** [comment]
The issue is happening even when the **Disable Emoji** option is disabled:
https://youtu.be/Yume_f8_Z1U

All it takes is having the deferring option enabled.
