### ISSUE TITLE
Enable CDN for css and js ，will also change the content of the code block 

### ISSUE THREAD

**Issue by cmhello** [wp-media/wp-rocket#2322]
After enabled CDN for css and js ，will also change the content of the code block. 

wp-rocket version 3.4.4

![20200218125126_wpdaxue_com](https://user-images.githubusercontent.com/3368507/74705533-35661d00-524f-11ea-8816-d37adfdd1d56.jpg)

**Comment by vmanthos** [comment]
@cmhello Thank you for reaching us.

**Comment by cmhello** [comment]
@vmanthos Thanks for the reply, but you misunderstood what I meant. The code in the picture is not in the php file, but the content of code block that I posted in the article using the Gutenberg editor plugin.

**Comment by vmanthos** [comment]
@cmhello 

Thanks for the clarification. Still, you should reach out to our support.

Thank you!

**Comment by GeekPress** [comment]
@cmhello To be able to work on this issue, we need first to replicate it.

To help us, thanks to provide us the exact steps to reproduce the issue by using this template:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

Please note that the steps are an example.

We also need to have infos about your WordPress Environment.

Thanks

**Comment by CodAffection** [comment]
I'm having an almost the same situation here.

wp rocket optimizes code in `<code>` and in brackets (). which end in removing parts lines from `<code>` block or re-write with CDN basepath.

To Reproduce

```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
```
But I'm having following issues.
![wp rocket support github](https://user-images.githubusercontent.com/32505654/94510612-d466e480-0234-11eb-8868-f4363cf95bea.png)

To avoid this issue I've added the following exception to css combine & minify.
```
/bootstrap/4.5.2/css/bootstrap.min.css
/ajax/libs/font-awesome/5.14.0/css/all.min.css
```

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1349923858/216910?folderId=2135277

**Comment by alfonso100** [comment]
related case: https://secure.helpscout.net/conversation/1365650105/222773?folderId=4130695

**Comment by sandyfzu** [comment]
Another case: https://secure.helpscout.net/conversation/1365650105/222773?folderId=3963184

**Comment by piotrbak** [comment]
The issue will be resolved while using the `rocket_cdn_relative_paths` filter:
https://docs.wp-rocket.me/article/42-using-wp-rocket-with-a-cdn#troubleshoot
