### ISSUE TITLE
WP Content Copy Protection prevents our CPCSS to be generated

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2323]
This plugin https://wordpress.org/plugins/wp-content-copy-protector/ prevents our CPCSS to be generated.

We could grey out the **Optimize CSS Delivery** option and show a warning when this plugin is detected.

**Related ticket**: https://secure.helpscout.net/conversation/1085347394/146447?folderId=273766

**Comment by WordPresseur** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1085347394/146447?folderId=273766

**Comment by piotrbak** [comment]
Tested the plugin, RUCSS/CPCSS are working just fine 👌
