### ISSUE TITLE
Can't fully use regex patterns for "cache rejected URIs"

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/wp-rocket#233]
For the pages that should never be cached, in the textarea, while something like `/fete-du-slip/.*` works, the following doesn't: `/fete-du-slip/?`. In that case I want to exclude this URI, with or without the trailing slash, but the `?` is stripped off.
I suspect the following would also fail: `/sauter?-du-lit/`, to match with or without the `r` character, it would probably become `/sauter`.

The problem is located in `rocket_settings_callback()`:
```php
$inputs['cache_reject_uri'] = array_map( 'rocket_clean_exclude_file', $inputs['cache_reject_uri'] );
```
`rocket_clean_exclude_file()` uses `parse_url( $file, PHP_URL_PATH )`, that explains why any `?` character and the following ones would be removed.

I guess the problem is present in other textareas (exclude css, js...).

**Comment by glueckpress** [comment]
Iterating on the above, this gets accepted as a value in the exclusion field, but it does not show any effect on the front-end (files still being minified/concatenated):

```
/wp-content/*.css
```

Only this would actually exclude files:

```
/wp-content/(.*).css
```

Other RegEx patterns don’t seem to work at all, as explained by @Screenfeed. 

Changing descriptions for these options in 2.10 to reflect the actual behaviour, however, single asterisks like `*.css` should probably not pass field validation if they don’t do anything.

**Comment by pcfreak30** [comment]
I dont think the description should be changed, but the behavior actually fixed to the original description as its a potential powerful feature.

**Comment by glueckpress** [comment]
@pcfreak30 Agreed, but iteration. :)

**Comment by arunbasillal** [comment]
@GeekPress We do not have many requests for the same. The regex we already have works for all use cases that we know of. It's bee 4 years since the original issue was reported. 

Shall we close this issue?

**Comment by GeekPress** [comment]
> Shall we close this issue?

Yes, we can :)
