### ISSUE TITLE
Suggestion - Freeze "CDN Activation Settings" when Cloudflare Add-On is Enabled

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2332]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I know that a message is already displayed to indicate that the CDN Activation Settings are not necessary when Cloudflare Add-On is enabled but, by security, it would be better to freeze the former if the latter is enabled.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tabrisrp** [comment]
a CDN service and Cloudflare can be used at the same time, so they need to be available at all time too.

The current warning we have is to reduce confusion from people who might think the CDN option is necessary when using Cloudflare.
