### ISSUE TITLE
Preload count in admin notice is inaccurate

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/wp-rocket#2341]
The number of pages being preloaded does not match the number displayed in the admin notice.

**Comment by hellofromtonya** [comment]
Re-opening due to reports of Preload counter not updating until the Preload is done.

**Comment by hellofromtonya** [comment]
@Screenfeed What is the root cause of the Preload counter not updating until the Preload process is done? It gave the impression of being "stuck."

**Comment by Screenfeed** [comment]
@hellofromtonya Yes. The notice was displaying only the "homepage preload" count, leaving the "sitemap preload" count aside.
This is what is happening internally, chronologically:
- Request the home page, grab the links on it, push them into the queue as non mobile items.
- Request the home page with a mobile user agent, grab the links on it, push them into the queue as mobile items.
- Request all items from the queue, one after the other: the non mobile items are the first ones in the queue, so they are preloaded before the mobile items.
- Request the sitemap, grab its links.
- For each link, push it into the queue as non mobile item, then push it into the queue as mobile item.
- Request all items from the sitemap queue.

Now, what was happening before this fix:
- request the home page,
- request it again with mobile UA,
- **the counter starts**,
- request all non mobile links,
- **the counter increases for each non mobile request then pauses here until the end**,
- request all mobile links,
- request sitemap,
- request sitemap links,
- **display the total of preloaded links (including sitemap count this time)**.
