### ISSUE TITLE
Htaccess is deprecated on WP Engine with PHP 7.4

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2345]
https://wpengine.com/support/htaccess-deprecation/
While this shouldn't cause any issues, Remy suggested that we could update our compatibility to stop trying to write to the htaccess file.

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by nlebrozec-github** [comment]
Hi,

I've seen some communication from WP Engine that PHP 7.4 was available on their end but in one of their posts they also gave a heads-up regarding the deprecation of .htaccess files. I know that WP Rocket relies on it (as Wordfence BTW). Before trying this new PHP version (on Staging) I wanted to get your recommendation regarding possible issues.
Any advice is much appreciated.

Regards,
Nico

**Comment by Tabrisrp** [comment]
@nlebrozec-github There should be no issue transitioning to 7.4 and no htaccess, the optimization usually configured by WP Rocket in this file will be applied automatically by WP Engine on their server and NGINX reverse proxy setup.

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Not really a problem, I tested on our WP Engine test site, and using PHP 7.4 with a `.htaccess` file at the root is not causing any issue, the file is ignored.

**Identify the root cause** ✅ 
WP Engine has deprecated the use of the `.htaccess` file when using PHP 7.4. The file is ignored, so any directive inside are ignored too.

This is not an issue for us, as WP Engine is applying static file caching and compression at a server level directly.

**Scope a solution** ✅ 
To avoid writing in an unused file, we can update our WP Engine compatibility file to add a callback preventing our `.htaccess` functions insertions from running.

We can take this opportunity to update the compatibility file to OOP too.

**Estimate the effort** ✅ 
`effort: [S]`

Most of the effort will be on writing automated tests and refactoring the code to OOP.

**Comment by nlebrozec-github** [comment]
Bonjour Rémy et merci beaucoup ;)

My main concern was that I wanted to make sure that all the config that you were supposed to use in the .htaccess file is correctly replicated on WP Engine's to avoid mismatch. Regarding the static file caching for instance, we need to make sure that'll match WP Engine's one.

Anyway, thanks for making sure that the transition will be as smooth as possible. I'll test the PHP 7.4 soon on other environments.

Thanks for your great support!
Nico

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

- On WP Engine with PHP version lower than 7.4, no change is to be expected. They continue as they do now. 
- Do not try to write to `.htaccess` when hosting is WP Engine and PHP >= 7.4. Even if `.htaccess` exist. 
- Do not display the `cannot modify file` admin notice even if  `.htaccess` is write protected.  
- When customer updates to this version of WP Rocket and if their PHP >= 7.4, remove WP Rocket rules from `.htaccess` if they exist. If the file does not exist, do nothing. 
- When host is not WP Engine, `.htaccess` should be updated as before. 
- When host is not WP Engine and `.htaccess` cannot be written into show the `cannot modify file` admin notice. 

**What if**
- Customer is on WP Engine with PHP less than 7.4. Updates to this version of WP Rocket. 
- ^ Would it be need to check this on every update of WP Rocket? That seems like a lot and unnecessary for each update (until eternity). 
- ^ Maybe when such customers update WP Rocket settings that involve `.htaccess` we can clear the contents of the file and move on? 

- Customer update to 7.4 and then rolled back. 
- ^ Will WP Engine use `.htaccess` for them? Should we consider putting back the rules in this case? 
- ^ Maybe we can stick to updating WP Rocket settings in this case as well. If the PHP version is less than 7.4, the rules will come back based on the previous `What if` case's solution.

**Comment by Tabrisrp** [comment]
I'm pretty sure WPEngine was already applying browser caching & compression at the server level before 7.4, and the cache itself is also handled by them.

So in my opinion, we can limit ourselves to:
- Add filter to not write anything from WP Rocket in the `.htaccess` file on WPEngine
- flush htaccess on update to this version

**Comment by nlebrozec-github** [comment]
FYI I touched base with WPEngine support to shed some light on this and here is their answer:
_Yes, so by default we do have cache expiry header present on server side, we also do page caching, gzip compression is also enabled by default_
_This is default cache control header, might be useful for you as a reference:

# Serve static files directly; missing files need to hit the backend in case they're
# created dynamically (i.e. minify) or have a rewrite rule (e.g. Multisite or custom rewrite).
​
location ~* ^.+\.(?:jpe?g|gif|png|css|js|ico|zip|7z|tgz|gz|rar|bz2|do[ct][mx]?|xl[ast][bmx]?|exe|pdf|p[op][ast][mx]?|sld[xm]?|thmx?|txt|tar|midi?|wav|bmp|rtf|avi|mp\d|mpg|iso|mov|djvu|dmg|flac|r70|mdf|chm|sisx|sis|flv|thm|bin|swf|cert|otf|ttf|eot|svgx?|woff2?|jar|class|log|web[pma]|ogv)$  {
### MU Rules (Static) ###(none)###
        if_modified_since       before;
        add_header      Cache-Control  "public, max-age=31536000";
        add_header      Vary "Accept-Encoding";
        add_header      Access-Control-Allow-Origin *;
}_

Hope this is helpful to you.
Happy coding ;)
Nico

**Comment by arunbasillal** [comment]
Thanks for the feedback @Tabrisrp and @nlebrozec-github 
I have updated the acceptance criteria accordingly.

**Comment by arunbasillal** [comment]
@GeekPress I tested on a WP Engine website running PHP 7.3 and no WP Rocket. They apply browser caching rules and compression (Brotli) at their end. So we are good to go ahead with our plan 👍

**Comment by GeekPress** [comment]
@arunbasillal Thanks for the double check :)
