### ISSUE TITLE
CDN rewrite not applied to URLs when written within JSON-like blocks

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#2353]
A customer reported that our CDN rewriting feature disregarded certain URLs from his slider plugin; and Remy confirmed in [this Slack thread](https://wp-media.slack.com/archives/C43T1AYMQ/p1583155947056500) that it's because they're contained within JSON-like blocks, which we don't currently target for rewriting. 

Example of what such a block might look like:

`[{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/WmdAnimal.png","alt":""},{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/whartons.png","alt":""},{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/NAlogo2017-150x150.jpg","alt":""},{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/The-Estate-of-HOWARD-SULLIVAN-Logo_FINAL-e1568502778885.jpg","alt":""},{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/Walmart_logo-e1568502712339.png","alt":""},{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/Wilson_supply.png","alt":""},{"url":"https:\/\/www.howardsrunfestival.com\/wp-content\/uploads\/2019\/09\/RSW_logo-150x150.jpg","alt":""}]}`

**Steps to reproduce**

According to Remy, he's seen such blocks used in several different slider and gallery plugins -- so, in order to reproduce, you would just need to install any slider or gallery plugin which embeds URLs in a similar fashion within JSON-like blocks.

But if you want to reproduce the customer's issue more exactly, then he's using **Slider Revolution FilmStrip**.

Customer is also using 3.4.4: https://secure.helpscout.net/conversation/1096384028/148615

**Comment by GeekPress** [comment]
@girlie Thanks for reporting the issue.

Can you please follow our template issue:

**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by girlie** [comment]
Another ticket:
https://secure.helpscout.net/conversation/1099058848/149115

**Comment by Screenfeed** [comment]
@Tabrisrp I first thought about [detecting URLs wrapped in quotes](https://regex101.com/r/x4kEho/1), but then I had the feeling that it would probably catch things it shouldn’t (maybe I’m being paranoid).
So I wondered if we can [detect JSON strings instead](https://regex101.com/r/x4kEho/2) (based on [this solution](https://stackoverflow.com/questions/21994677/find-json-strings-in-a-string)) and then use `json_decode()`, but unfortunately [it will fail](https://regex101.com/r/x4kEho/3).
Maybe [hardening a bit](https://regex101.com/r/x4kEho/4) my first solution will help but I’m worry about replacing URLs that are not in JSON strings.

Any opinion about this?

**Comment by Tabrisrp** [comment]
I agree with you, it all seems risky, and it will also complicate things when we need to perform the actual replacement, to preserve the escaping.

I'm thinking, to handle this case, we could rewrite to the CDN URL earlier, using WP hooks. BUT, we had issues with that before, notably with page builders, because the CDN URL was applied on the "builder page" (because it's not considered an admin page).

So we need to think about this whole thing more, to be sure we can find a no-conflicts solution.

**Comment by GeekPress** [comment]
Thanks @Screenfeed @Tabrisrp for your feedbacks.

@girlie What was the slider used in that case?

As it seems to be risky to implement, we could contact the plugin author and ask them to use our function to serve the CDN URL in their code.

**Comment by Tabrisrp** [comment]
For now we know about 2 cases:
- Revolution Slider
- Elementor

**Comment by camilamadronero** [comment]
New ticket:
https://secure.helpscout.net/conversation/1115862324/152981?folderId=2675957
Apparently, the JSON formatting comes from the Porto theme or its plugin Porto Functionality.
https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme/9207399

**Comment by GeekPress** [comment]
@Tabrisrp Can you please remind me how the developers will have to do to make their URLs used by our CDN?

**Comment by GeekPress** [comment]
@webtrainingwheels Can I let you be in touch with Elementor & Revolution Slider about this issue?

**Comment by webtrainingwheels** [comment]
@GeekPress Yes, no problem :) Seems we'll need Remy's feedback first about the best approach on their side

**Comment by webtrainingwheels** [comment]
@GeekPress Yes, no problem :) Seems we'll need Remy's feedback first about the best approach on their side

**Comment by girlie** [comment]
Looks like we can add NextGen Gallery to the list:
https://secure.helpscout.net/conversation/1180039965/169135/

**Comment by JohnTorvik** [comment]
Related: https://secure.helpscout.net/conversation/1230142671/181314?folderId=3773397

**Comment by sandyfigueroa** [comment]
Related case (Elementor): https://secure.helpscout.net/conversation/1240536721/183660/

http://prntscr.com/trya64

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1293625199/197846?folderId=377611

In this case it's related to a customer using the WooCommerce product bundles plugin. However, the plugin author has clarified that they are using functions found in WooCommerce core related to product variations, which are not specific to their plugin.

Here is a sample of the HTML - http://snippi.com/s/544c7f2

**Comment by girlie** [comment]
Related (Elementor): https://secure.helpscout.net/conversation/1391212563/229918/

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
