### ISSUE TITLE
Update lazyload script

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#2358]
![Screenshot_1](https://user-images.githubusercontent.com/43606394/75758346-38bfd500-5d34-11ea-8558-b1a712910d78.png)
Currently wp rocket uses version 12.0, currently the latest version is 13.0
https://github.com/verlok/lazyload/releases

**Comment by alihs** [comment]
+1 
If not possible, maybe a hook is mentioned here that we could use to update the script

**Comment by Tabrisrp** [comment]
**Scope a solution**
- Add new version of the lazyload script to WP Rocket source repository and load it
- Add a clean domain in the upgrade routine to make sure new version is used after update

**Effort**
[XS]

**Comment by Camilo517** [comment]
Hi @Tabrisrp @GeekPress 
In version 17.1.0 performance is improved, it would be good to update
https://github.com/verlok/vanilla-lazyload/releases
