### ISSUE TITLE
Provide option to turn off X-CF-Powered-By HTTP header

### ISSUE THREAD

**Issue by EatonZ** [wp-media/wp-rocket#2363]
Please allow us to turn off this header. It looks like there's an option to change it, but not remove it.
Is this header necessary at all?

https://github.com/wp-media/wp-rocket/blob/8cc8fe16b953f578685600a05bfaab71edc94202/inc/common/cloudflare.php#L56-L65

**Comment by EatonZ** [comment]
@Tabrisrp Please link to the PR that provides a solution for this, thank you.

**Comment by Tabrisrp** [comment]
The header was removed in version 3.5 of the plugin, as you can see here in the method: https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/Addon/Cloudflare/Subscriber.php#L249
