### ISSUE TITLE
Wrong VAT Calculations in an Order

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2372]
I've received an order which is facing a wrong VAT calculation.

8,59 EUR / 1,21% (vat) = 7,09917 EUR

normally, this amount should be rounded to 7,10 EUR
so that, 8,59 EUR - 7,10 EUR = 1,49 EUR of VAT Tax Amount

however, this is not the amount of VAT Tax shown => I see 1,50 EUR which is wrong

![image](https://user-images.githubusercontent.com/51261962/75878920-b100c600-5e1a-11ea-941c-6ab176666b7e.png)

**Comment by gevcen** [comment]
I'm using latest version of WooCommerce / WordPress / PHP 7.3 / all other plugins up to date

**Comment by GeekPress** [comment]
Hi @gevcen 🤚

Are you sure that this issue is caused by WP Rocket? 

**Why I'm asking the question?**
The cart page isn't cached and WP Rocket isn't active. There are a lot of chance that your issue is caused by another plugin or a WooCommerce bug.

**Comment by gevcen** [comment]
Oops wrong github, sorry I mixed up...

**Comment by gevcen** [comment]
you can close it

**Comment by GeekPress** [comment]
No worries, thanks for your feedback ;)
