### ISSUE TITLE
PHP Warning filemtime()

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#238]
PHP Warning: filemtime(): stat failed .... in /wp-rocket/inc/front/process.php on line 281

For some reasons filemtime() is failing randomly for some customers (maybe the cache file was not successfully created).

We can either use error suppression (@) or do a file_exists() before

```
// Send headers with the last modified time of the cache file
header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s', filemtime( $rocket_cache_filepath ) ) . ' GMT' );
```
When this happens, it results in PHP warnings – uncritical, but annoying we you monitor your site and receive alerts repeatedly.

A simple way to fix the warning would probably look like this:

```
$rocket_cache_filepath_filemtime = filemtime( $rocket_cache_filepath );
if ( $rocket_cache_filepath_filemtime ) {
	
	// Send headers with the last modified time of the cache file
	header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s', $rocket_cache_filepath_filemtime ) . ' GMT' );
} else {

	// What? Send another header?
}
```

**Comment by Tabrisrp** [comment]
Duplicate https://github.com/wp-media/wp-rocket/issues/238

**Comment by glueckpress** [comment]
> For some reasons filemtime() is failing randomly for some customers…

According to recent feedback, those issues can be related to insufficient permissions. One customer fixed their permissions and the issue went away.
