### ISSUE TITLE
PHP Fatal error in WP ROCKET 3.5

### ISSUE THREAD

**Issue by alriksson** [wp-media/wp-rocket#2381]
Version 3.5

**Describe the bug**
`: PHP Fatal error: Cannot redeclare rocket_remove_partial_purge_hooks() (previously declared in /www/application_hidden/public/wp-content/plugins/wp-rocket/inc/3rd-party/hosting/kinsta.php:114) in /www/application_hidden/public/wp-content/plugins/wp-rocket/inc/3rd-party/hosting/presslabs.php on line 72`

Hosted with Kinsta. Had to rollback with a backup.

**To Reproduce**
1. Install WP Rocket 3.5 on Kinsta.
2. Fatal error and wp-admin blank white screen.

**Comment by Tabrisrp** [comment]
Hi,

Thank you for the report!

We just released 3.5.0.1 to fix this particular issue. Please update to it and everything should be working now.
