### ISSUE TITLE
Compatibility issues PRO 3.2.1

### ISSUE THREAD

**Issue by alriksson** [wp-media/wp-rocket#2385]
**Before submitting an issue please check that you’ve completed the following steps:**
WP Rocket v.3.5

**Describe the bug**
Combine CSS feature cause issues with PRO 3.2.1. Dropdown menu breaks together with the sticky feature. Drop down menu bug is only present on `is_front_page`. Works on all other pages. Any known related bugs?
Works as normal on a rollback to 3.4.4

https://theme.co/changelog/

**Comment by GeekPress** [comment]
Hi, 

To avoid multiple discussion on different websites, we are going to close this issue.

Thanks to continue the discussion on your ticket support.
