### ISSUE TITLE
WP Rocket can't recognize .htaccess when site_url =! home_url

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2386]
**Describe the bug**
When site_URL is different from home_URL, WP Rocket receives the wrong path to the WordPress root directory here:
https://github.com/wp-media/wp-rocket/blob/70cb44dab060baff2f88901e3c1a184e139f0c00/inc/admin/ui/notices.php#L439

In this specific case, `home_url` is set to `domain.com` while `site_url` is set to `domain.com/wordpress`

It leads to the situation when we're looking for .htaccess file here:
`/var/www/path/to/web/.htaccess`
instead of
`/var/www/path/to/web/wordpress/.htaccess`

**To Reproduce**
1. On the environment where `site_url` != `home_url`
2. Enable WP Rocket
3. Check if .htaccess got generated

**Expected behavior**
I'm not sure if this kind of setup is correct, but it happens from time to time. We should either, be able to write to .htaccess or inform the customer about the wrong configuration of his WordPress.

**Additional context**
If the testing environment is needed, I believe that this customer will be happy to help us:
https://secure.helpscout.net/conversation/1091855621/147673?folderId=2415573

Old slack thread regarding this issue:
https://wp-media.slack.com/archives/C43T1AYMQ/p1553890940034000

**Comment by Tabrisrp** [comment]
Normally with this kind of setup, which is totally fine ([See this article](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)), the `.htaccess` file is still in the root folder, along with the `index.php` file. So WP Rocket is searching for the correct path here.

**Comment by piotrbak** [comment]
In this specific case, WP Rocket was searching for `.htaccess` in:
`/var/www/path/to/web/.htaccess`
while the real, WordPress root path on the server was:
`/var/www/path/to/web/wordpress/.htaccess`

**Comment by Tabrisrp** [comment]
I can't reproduce the issue.

Website with installation in a sub-directory:
![wp-general](https://user-images.githubusercontent.com/3465180/76764249-e5ee1080-676a-11ea-9aef-a31ed05cd138.jpg)
![filestructure](https://user-images.githubusercontent.com/3465180/76764261-eab2c480-676a-11ea-9d75-b363686ecef7.jpg)

On WP Rocket activation, the rules are correctly added to the `.htaccess` file in the root folder

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
