### ISSUE TITLE
RocketCDN: Safari 13+ is always blocking iFrame cookies.

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2389]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️ 
- Used the search feature to ensure that the bug hasn’t been reported before ✔️ 

**Describe the bug**
This is not technically a WP Rocket bug, but a security limitation on Safari 13+. But this affects the iframe of RocketCDN. 

Plagiarizing Tonya's description of the issue:

"This particular issue impacts our iframes in Imagify, Rocket, and even our websites (if we have any). It needs R&D to understand what Apple's Safari 13+ browser will let us do in order to figure out how to properly resolve it."

During testing Romain could not enable RocketCDN. He was getting a 404. After some searching it was discovered that this was due to Safari 13+ blocking iFrame cookies. Firefox and Chrome seem to work fine.

**To Reproduce**
1. Visit WP Rocket CDN tab in Safari 13+ browser
2. Launch the RocketCDN iframe (by clicking "Get Started" - https://jmp.sh/ixFj4yV
3. Right now (WP Rocket 3.5.0.x) we show the following notice in the iframe: 

```
RocketCDN account creation is not currently supported for the Safari browser. To sign up for RocketCDN, please use Chrome, Firefox, Opera or Edge.
```

**Expected behavior**
iframe works as expected just like it does in Firefox and Chrome

**Additional context**
Relevant slack thread: https://wp-media.slack.com/archives/CBJ2KQ0MU/p1582043344012400

**Comment by crystinutzaa** [comment]
This was fixed and released on 18.03 so it can be closed now
