### ISSUE TITLE
403 (and some other codes) pages are cached

### ISSUE THREAD

**Issue by BoiteAWeb** [wp-media/wp-rocket#239]
When a 403 page is loaded using PHP, WPR will add this page into the cache.

I suggest to only add in cache codes 200 and 304.

Huge impact on 150,000 sites BUT nobody want 414,500,503,403 etc in cache.

**Comment by drexlma** [comment]
solution:
front/process.php:292

&& (http_response_code() != 200)

**Comment by drexlma** [comment]
`	if ( strlen( $buffer ) > 255
			&& (http_response_code() != 200)
		&& ( function_exists( 'is_404' ) && ! is_404() ) // Don't cache 404
		&& ( function_exists( 'is_search' ) && ! is_search() || $rocket_cache_search ) // Don't cache search results
		&& ( ! defined( 'DONOTCACHEPAGE' ) || ! DONOTCACHEPAGE || $rocket_override_donotcachepage ) // Don't cache template that use this constant
		&& function_exists( 'rocket_mkdir_p' )
	) {`

**Comment by arunbasillal** [comment]
Tested this with 403 and 500 response codes and its is a pass in `3.1-alpha2`. :+1:
