### ISSUE TITLE
Make our file optimizations compatible with Jetpack's CDN

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2394]
![Jetapck_site_accelerator](https://user-images.githubusercontent.com/1043076/76108505-96039280-5f8f-11ea-9f4c-a9edab0fa5db.jpg)

When customers active Jetpack's "site accelerator" features, their CSS/JS files are served from Jetpack's CDN. WP Rocket can no longer process them for minify/combine etc. So customers have to choose either the benefit of the CDN, or the benefit of our options. If technically feasible it would be great to be able to handle those files. 
See HS tags "jetpack cdn" and "jetpack site accelerator" for related tickets. 

**Steps to reproduce**

1. You need a site with Jetpack plugin active and connected to WordPress.com
2. Make sure that some File Optimizations are enabled in WP Rocket, like Combine CSS / JS 
3. Go to _Jetpack settings > Performance > Enable site accelerator > Speed up static file load times_
4. Clear the WP Rocket cache
5. Observe that files served from Jetpack's CDN won't be processed by WP Rocket:  

- Without optimizations: 21 CSS requests - https://jmp.sh/QyfBggF
- With WP Rocket Combine CSS: 4 CSS requests - https://jmp.sh/J6uZeOT
- With WP Rocket Combine CSS + Jetpack Site Accelerator: 12 CSS requests - https://jmp.sh/v03yOMN

**Comment by Tabrisrp** [comment]
Jetpack site accelerator speed up for static files rewrites the URLs of files from WP core, Jetpack and WooCommerce to the URL coming from `wp.com`.

It's not technically possible for us to optimize those and at the same time using Jetpack CDN.

@arunbasillal @GeekPress We need to decide what is the best approach there, because this option and our file optimization options for CSS/JS are not compatible.

**Comment by GeekPress** [comment]
@Tabrisrp It should work for JS minify / combine as external scripts are included in the process, isn't? 

If so, it means that if we include external CSS in the minify/combine process, this issue will be fixed.

**Comment by Tabrisrp** [comment]
Currently it would be for combine JS, we don't process any external CSS/JS files when doing minify.

And I believe we have reports of combine JS not working correctly with Jetpack CDN enabled at the same time, something along the line of `jQuery not defined` issue. See #2296

**Comment by arunbasillal** [comment]
I am trying to wrap my head around this problem. 

- Before activating site accelerator, all the said JS and CSS were combined correctly and the site didn't have any issue. (Let's say)
- Then why should serving these files from Jetpack's CDN cause new issues? (with reference to #2296) 🤔

**Comment by webtrainingwheels** [comment]
@arunbasillal please check the conclusion of the discussion in #2296 , that issue turned out to be a bit different and led to the creation of #2493 instead.

**Comment by webtrainingwheels** [comment]
@arunbasillal @GeekPress Since 3.7 this issue isn't really relevant anymore. 

Now, if Jetpack CDN for Static Files is activated, we will process everything and they will end being locally hosted (except any excluded file), so there is no point in using Jetpack CDN in that case.

**Comment by GeekPress** [comment]
> Now, if Jetpack CDN for Static Files is activated, we will process everything and they will end being locally hosted (except any excluded file), so there is no point in using Jetpack CDN in that case.

In terms of performance, this behavior is better for our users.

Why?

Based on this comment https://github.com/wp-media/wp-rocket/issues/2394#issuecomment-597075883, Jetpack CDN isn't applied on all files.

I suppose for websites with an international audience, Jetpack CDN isn't enough for them. They will want to have a CDN applied on all their files, and not just on WP Core, Jetpack and WooCommerce. They will need to use a global CDN solution.

For websites without an international audience, Jetpack CDN will add a useless extra DNS resolution to solve.

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
