### ISSUE TITLE
Auto detect local by flywheel

### ISSUE THREAD

**Issue by wpsumo** [wp-media/wp-rocket#2398]
Information:
Wp Rocket: version 3.5.0.2
Local environment: https://localwp.com/

**Describe the bug**
Something in WP Rocket makes the local environment using local by flywheel extremely slow. Mainly while saving to the DB. For example, saving a page or post.

I always disable WP Rocket on local, but it would be smooth with auto detect that disable the features causing issues. Or finding the issue and bug and fix it.

**Comment by GeekPress** [comment]
Hi @wpsumo 🤚

We would love to work on improvement. For that, we need more details to be able to reproduce the issue.

May I ask you what are the steps to reproduce the problem?

**Comment by wpsumo** [comment]
Just install wp rocket on a site created with local and enable cache features. That's basically it.

**Comment by GeekPress** [comment]
@wpsumo Thanks for your feedback.

Our dev and support team are using Local By Flywheel and we never notice this kind of problem. We also never get any reports about that.

I guess this is something related to your installation and not really WP Rocket on Local By Flywheel.
