### ISSUE TITLE
When information_schema.tables is queried on multisite, query the tables that contain the subsite's prefix

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#2401]
The WP Rocket backend slows down on multisite with huge databases when **information_schema.tables** is queried.

**Suggestion:** Query the tables that contain the subsite’s prefix instead.

![image](https://user-images.githubusercontent.com/26235782/76227282-5b178e00-621f-11ea-83d2-e2c19822d095.png)

Related ticket: https://secure.helpscout.net/conversation/1103754541/150067/
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1583762204151900

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
