### ISSUE TITLE
Pages are not cached if the WooCommerce German Market plugin is enabled

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#2403]
**Describe the bug**

The WooCommerce German Market is setting the DONOTCACHEPAGE constant in

_/woocommerce-german-market/inc/WGM_Template.php_

By using the `wc_nocache_headers()` function.

WooCommerce German Market plugin: [https://marketpress.de/shop/plugins/woocommerce-german-market/](https://marketpress.de/shop/plugins/woocommerce-german-market/)

**To Reproduce**
1. Install the WooCommerce German Market plugin
2. Visit any page on the site
3. You’ll see that the cached files are not created.

**Expected behavior**
Pages should be cached when having this plugin enabled.

**Screenshots**
The wc_nocache_headers() fucntion is present in the WGM_Template.php file:
￼
![image](https://user-images.githubusercontent.com/26235782/76301737-0e838f80-62bf-11ea-8310-136b7e944666.png)
Full-size image: https://share.getcloudapp.com/12u144nG

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1098150692/148911?folderId=3051575

In this previous ticket: https://secure.helpscout.net/conversation/993489681/129138/ the customer mentioned:

_The problem was in the German Market Plugin. The constant is actually only set for shopping cart, checkout and confirmation pages. But if the "Confirm Order" page is deactivated, a bug occurs in the function and the constant is set for all pages.
I think the next version of German Market will fix that, we talked to the support._

From the German Market plugin settings:
![image](https://user-images.githubusercontent.com/26235782/76301868-4c80b380-62bf-11ea-9647-8fd67bfc74bc.png)
￼
**BUT I confirmed that this fix suggested by the customer does NOT help.**

The issue persists even when enabling the second checkout page using the shortcode:
￼
![image](https://user-images.githubusercontent.com/26235782/76301906-5f938380-62bf-11ea-8f50-208f245d685a.png)

**Comment by viobru** [comment]
**Update:** the customer just confirmed that updating the German Market plugin to the newest version fixes the issue.
Ticket: https://secure.helpscout.net/conversation/1098150692/148911/

**Comment by GeekPress** [comment]
@viobru Thanks for the confirmation. We can close this issue :)
