### ISSUE TITLE
Preload doesn’t stop when asked to

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/wp-rocket#2404]
**Describe the bug**
The "Stop preload" button doesn’t stop the preload when sitemap preloading is enabled.

**To Reproduce**
1. Choose a site with a "large" number of pages
2. In the Preload section from WPR’s settings, enable preloading + sitemap-based cache preloading, and fill in the sitemap URL.
3. Once the settings saved, hit the "Preload cache" button from the admin bar or in the quick actions sidebar from WPR’s settings page.
4. The banner displaying the number of paged that have been preloaded will appear.
5. Hit the "Stop preload" button.
6. The same banner should still be displayed with the same button: preloading didn’t stop.

**Expected behavior**
Preloading should stop and the result banner should appear.

**Source of the bug**
The reason of this bug is quite simple: the "stop" action only cancels the homepage preloading, not the sitemap preloading. See `WP_Rocket\Engine\Preload\PreloadSubscriber->do_admin_post_stop_preload()`:
https://github.com/wp-media/wp-rocket/blob/e154e170c205534398247e935cc5eaef070eaeeb/inc/Engine/Preload/PreloadSubscriber.php#L360-L374

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Screenfeed** [comment]
I guess it is time to separate homepage preload, sitemap preload, and everything that is common to both (like admin notices).
It will probably end up with `PreloadSubscriber`, `HomepagePreloadSubscriber`, and `SitemapPreloadSubscriber`. We could also create an interface for homepage and sitemap subscribers, to harmonize things. The main class `PreloadSubscriber` would trigger hooks that homepage and sitemap subscribers would use.

Effort: `[M]`.

**Comment by GeekPress** [comment]
@Screenfeed Before to plan a complete rewrite, do we have a solution which will work with a slower effort?

**Comment by Screenfeed** [comment]
@GeekPress It is not a complete rewrite. Basically, it is splitting the class `PreloadSubscriber` into 2 classes with different concerns instead of piling up another bandage.
The other solution is to add another dependency to the class `PreloadSubscriber`, which will be refused during the review.

**Comment by webtrainingwheels** [comment]
Another case: https://secure.helpscout.net/conversation/1125854331/155259?folderId=377611

**Comment by jazir5** [comment]
Can confirm i am experiencing the same issue on my production sites. Preload is uncancelable via the stop preload button if sitemap preloading is enabled.

**Comment by evagabond** [comment]
I can confirm the same. Preload isn't stopping in a large site with lots of pages.

**Comment by viobru** [comment]
Another case: https://secure.helpscout.net/conversation/1155046039/162715?folderId=3051575

**Comment by hellofromtonya** [comment]
@GeekPress This issue will be fixed in the new Preload module in 3.7. We aren't able to fix it until we do the rewrite/refactor.

**Comment by vmanthos** [comment]
Another ticket: https://secure.helpscout.net/conversation/1162851074/164717?folderId=2135277

**Comment by kierantaylorio** [comment]
Another ticket: https://secure.helpscout.net/conversation/1169041464/166247/

**Comment by hellofromtonya** [comment]
This issue will be fixed in 3.7. It's blocked until we build the new Preload module.

**Comment by gevcen** [comment]
Still no update on this bug? if the new preload module will take time, you should at least fix this bug and make the button work. Thanks

**Comment by jazir555** [comment]
The preload update was scheduled for 3.7 and the project date was like July
of last year. I think they just gave up on preload.

**Comment by gevcen** [comment]
Or at least please provide us a workaround to stop it somehow in the meantime

**Comment by GeekPress** [comment]
@gevcen No update until you will see a milestone set up on this issue. As you may know, we are fully focused on Remove Unused CSS for few months. We can't work on our 410+ issue at the same time, we have to prioritize.

Thanks for your comprehension.

**Comment by jazir555** [comment]
@GeekPress 

Do you have a projected ETA for the remove unused css feature?

**Comment by GeekPress** [comment]
@jazir5 I can't provide any ETA as well.

**Comment by orrburgel** [comment]
Hey, I'm still having this issue with the latest version,
I implemented all required solutions and even whitelisted in cloudflare, turned on dev mode and what not,
This is stuck like this ever since yesterday:
![image](https://user-images.githubusercontent.com/41600149/130256135-c16f1e29-467d-4583-95b3-523b6236cf8a.png)
We just renewed wp rocket for another year, (170$*12) is a lot, and the thing is not working ever since than.

**Comment by orrburgel** [comment]
1) I've set PHP execution time to 450 on both the cpanel PHP Configuration and wp-config,
2) Gave more ram both on the php config and the wp-config
3) Made sure Cron is working, and that there are no loopback errors.
4) Completely replaced WP-Cron with real cron on the server.
5) Installed "WP Rocket | Custom cURL Timeout For Preload Request"
6) Made sure Cache is being purged in both cloudflare and wp-rocket everytime I test and that dev mode is enabled
7) Made sure there isn't any other errors (like all the cURL ones)
8) I did like a hundred other things to try and fix it ever since than, like pressing the combination of these buttons in every imaginable way:
![image](https://user-images.githubusercontent.com/41600149/130257005-1c692806-2cb3-4484-9889-3892eb0dcd1a.png)

**Comment by orrburgel** [comment]
Even tried to uninstall and reinstall it.

**Comment by orrburgel** [comment]
It just deleted all my settings and after re-configuring -> same error

**Comment by orrburgel** [comment]
it's not really an error, it's just stuck for days

**Comment by orrburgel** [comment]
Also it worked faster before I installed "WP Rocket | Custom cURL Timeout For Preload Requests"
I'm talking 1000x faster,
After I pressed PRELOAD CACHE almost 8 times, I managed to get it to stop and restart:
![image](https://user-images.githubusercontent.com/41600149/130258144-690009f4-1a53-48e4-904b-cb8500f11f63.png)
Problem is it's not stuck on 0.
Also critical CSS generation stopped working, When I press on it nothing happens.

Would you like me to start a new issue and provide a video of the problem or more details?

Also it seems like WP-Rocket is reading the WPML plugin although it's not configured and prompts me to clear cache on every language from the top menu but not from the dashboard.

**Comment by orrburgel** [comment]
Ok this is the first time I managed to literally get it bugged:
![image](https://user-images.githubusercontent.com/41600149/130258606-a1b41870-bc90-458e-b869-1dba05092338.png)
I have the latest wp-rocket version (wp-rocket_3.9.1.1.zip) and WordPress v5.8

**Comment by orrburgel** [comment]
I will keep updating this issue with all the problems I will have for you to solve it

**Comment by orrburgel** [comment]
Just managed to uninstall WPML, and also reinstalled WP-Rocket just to be sure, And now the problem got even worst, Nothing happens no matter what I click, I even tried to disable all the plugins:
![image](https://user-images.githubusercontent.com/41600149/130263479-a8cfdb37-99e2-4e43-9b1b-a13f42f7dd7f.png)

**Comment by iCaspar** [comment]
Hey there @orrburgel 
Thanks for letting us know about this.
Sounds like you might need some more immediate support to troubleshoot.
We can't provide direct support here, but our support team would be happy to look into this with you.
https://wp-rocket.me/support/

**Comment by orrburgel** [comment]
Just followed the following guide and completely removed all records for WP-Rocket, trying again
https://docs.wp-rocket.me/article/694-uninstalling-wp-rocket
![image](https://user-images.githubusercontent.com/41600149/130270200-a24ccee2-2c40-492d-9abc-aa2d1f3925c4.png)

**Comment by orrburgel** [comment]
> Hey there @orrburgel
> Thanks for letting us know about this.
> Sounds like you might need some more immediate support to troubleshoot.
> We can't provide direct support here, but our support team would be happy to look into this with you.
> https://wp-rocket.me/support/

Thanks will do

**Comment by gevcen** [comment]
@orrburgel workaround that worked for me: disactivate auto-preload
when you finished your testing configuration, re-enable it back

**Comment by orrburgel** [comment]
> @orrburgel workaround that worked for me: disactivate auto-preload
> when you finished your testing configuration, re-enable it back

Thanks I'll try, for now after reinstalling and waiting a bit, I managed to regenerate critical CSS, **but I'm still having the same issue with preload where it's stuck on 0**
![image](https://user-images.githubusercontent.com/41600149/130271952-5d4ded57-7c4e-48a5-b2b1-dfb27adac859.png)

**Comment by orrburgel** [comment]
Weird effect that it had is making the preload option go away while it's still stuck on 0 and I can't click Stop
![image](https://user-images.githubusercontent.com/41600149/130272486-f07c68fe-8be5-44a8-85b4-fd8dffeb1be2.png)

**Comment by juricazuanovic** [comment]
Another case: https://secure.helpscout.net/conversation/1652233228/299529/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1878847753/342181?folderId=3864735

**Comment by JerissCloudCenter** [comment]
Will this be fixed as part of the New Preload Module ?

It was supposed to be the case as mentioned in https://github.com/wp-media/wp-rocket/issues/2404#issuecomment-626641823

**Comment by piotrbak** [comment]
The issue is not relevant with the 3.12 preload implementation, as the preload now is an ongoing process.
