### ISSUE TITLE
Rocket CDN cannot be activated in chrome

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [wp-media/wp-rocket#2407]
When trying to activate the CDN on our site, the loginform is just refreshed and I cannot proceed.

**To Reproduce**
1. Go to WP-Admin -> WP Rocket -> CDN -> Get Started -> Loginform
2. Submit Form
3. In Chrome Browser, Login Form just refreshes. Additionally, the following warning is printed in browser console:
`A cookie associated with a cross-site resource at https://wp-rocket.me/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Expected behavior**
Payment Form is going to be loaded, works in Firefox

**Comment by GeekPress** [comment]
Hi @straightvisions-matthias-bathke 

Thanks for the report. 

There's a couple of things you can try:

1) If you've been trying to sign up in Chrome, try using Firefox. In some cases Chrome blocks the cookie and causes a problem.
2) If Firefox still doesn't work, please try temporarily deactivating any security plugins you may be using on your site

We are aware of the issue and we are going to work on it this week.

I'm going to close this issue as it's related to our website (the iframe) and not WP Rocket.
