### ISSUE TITLE
RocketCDN not detecting staging subdomain

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2414]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
staging.website.com is not detected as a staging website, allowing the customer to register for a RocketCDN account 

**To Reproduce**
1. Login into any staging website with this kind of URL https://staging.website.com
2. go to WP Rocket settings tab
3. Find our RocketCDN offer and signup
4. migrate your staging site to production
5. CDN information is not available

**Expected behavior**
Our RocketCDN offer should be hidden on staging subdomains.

**Additional context**
This ticket: 
https://secure.helpscout.net/conversation/1105772944/150488?folderId=2683093

Slack Convo: 
https://wp-media.slack.com/archives/CR8RSB1T8/p1584026531292400

This customer created the RocketCDN account while the site was in staging. and when migrating to production the CDN wasn’t valid.  Renaming the website URL in our rocketCDN admin solved the issue.

The CDN offer was available and the customer managed to purchase a subscription from his staging site: https://staging.domain.com/

We have a function called `rocket_is_live_site()` that checks if this website is a live PROD site. If no, it should block presenting RocketCDN to the customer. 

URLs like URL https://staging.domain.com/ will be allowed because we don’t have that in our “staging” sites configuration. Therefore, we aren’t recognizing here:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/functions/api.php#L117

**Comment by Tabrisrp** [comment]
@arunbasillal @GeekPress Excluding any sub-domain containing `staging` seems a bit risky to me, it's very easy to get into false positive cases.

We try to avoid bandaids fixes as much as possible, this feels like one.

**Comment by GeekPress** [comment]
@Tabrisrp I'm agree too. This is why we don't have this kind of detection on our license validation system.

Let's keep our detection like that for now, we handle most of cases already.
