### ISSUE TITLE
Preload blocks around ~150 pages since v3.5

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2415]
I've updated to latest version 3.5.0.3 but since then, my preload counter constantly indicates that the process has cached around ~150 pages altough in the past, it used to preload around 700 pages. Is there any known bug related to this?

![image](https://user-images.githubusercontent.com/51261962/76547848-2a895b80-648e-11ea-8642-ca18fffbb760.png)

**Comment by gevcen** [comment]
Issue still occuring with lastest version 3.5.0.4

**Comment by piotrbak** [comment]
It looks like in some cases, we're not fetching the sitemaps at all. This is happening constantly for this customer:
https://secure.helpscout.net/conversation/1107833503/151289/

I'm able to reproduce it on Mega, however, from time to time the sitemap is fetched correctly. I wasn't able to pinpoint the issue.

To reproduce:
- Go to the Mega site
- Make sure `Separate Cache for Mobile Devices` is enabled (it happens definitely more frequently then, but it also happened when it was disabled)
- Add the sitemap manually
- Save settings

If you're not able to reproduce it, please enable the `Yoast SEO XML sitemap` feature and save settings.
The results are very inconsistent with Mega. I'll keep testing on the customer site.

**Comment by gevcen** [comment]
I'm unable to check the link in the helpscout website altough I have an active license of WP Rocket. How can I consult this page?

I made some testing on my side too. So far the below combinations of settings didn't help to fix the problem since I'm still at around 160 pages instead of 600+ pages :

- yoast enabled + mobile cache disabled => NOK
- yoast enabled + mobile cache enabled => NOK
- yoast disabled but sitemap manually added + mobile cache enabled => NOK
- yoast disabled but sitemap manually added + mobile cache disable => NOK
- yoast enabled and sitemap manually added + mobile cache disable => NOK

**Comment by webtrainingwheels** [comment]
@gevcen 
>I'm unable to check the link in the helpscout website altough I have an active license of WP Rocket. How can I consult this page?
This is for our internal use only.

**Comment by piotrbak** [comment]
The issue is not relevant with the 3.12 preload implementation.
