### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WPaas\Plugin' not found 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2416]
`Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/wp-rocket/inc/functions/files.php on line 266
`
Fatal error: Uncaught Error: Class 'WPaas\Plugin' not found in //wp-content/plugins/wp-rocket/inc/3rd-party/hosting/godaddy.php:108 Stack trace: #0 /wp-content/plugins/wp-rocket/inc/3rd-party/hosting/godaddy.php(58): rocket_godaddy_request('BAN') 
#1 /wp-includes/class-wp-hook.php(290): rocket_clean_domain_godaddy('/home/C4011/web...') #2 /wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) 
#3 /wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#4 /wp-content/plugins/wp-rocket/inc/functions/files.php(840): do_action('before_rocket_c...', '/home/C4011/web...', '', 'https://progros...') 
#5 /wp-content/plugins/webtoffee-gdpr-cookie-consent/third-party/scripts/wp-rocket/wp-rocket.php(72): rocket_clean_domain() 
#6 /hom in/wp-content/plugins/wp-rocket/inc/3rd-party/hosting/godaddy.php on line 108

Cases: 
https://secure.helpscout.net/conversation/1107655511/151233?folderId=273764
https://secure.helpscout.net/conversation/1106857067/150928/

Neither ever hosted on Godaddy. 
@piotrbak is investigating

**Comment by GeekPress** [comment]
Got one too:
https://secure.helpscout.net/conversation/1106792213/150876?folderId=273768

**Comment by piotrbak** [comment]
Related:
https://secure.helpscout.net/conversation/1098565592/149029?folderId=2415573
https://secure.helpscout.net/conversation/1106857067/150928/

**Comment by hellofromtonya** [comment]
This issue appears to be related to [GDPR Cookie Consent Plugin](https://www.webtoffee.com/product/gdpr-cookie-consent/).
