### ISSUE TITLE
Anti-spam by CleanTalk - Output buffering stops caching/file optimization

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2423]
The **Spam protection, AntiSpam, FireWall by CleanTalk** plugin:
https://wordpress.org/plugins/cleantalk-spam-protect/

clears our buffer, removing the `</html>` tag for which we check here:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/Buffer/class-optimization.php#L85

That halts the caching/file optimization process.

**To Reproduce**

1. Install/activate the plugin (they offer a free trial).
2. Enable WP Rocket's file optimization features.
3. Visit a page and check the source code for the previous features.
4. There shouldn't be there.

**Expected behavior**

Caching/file optimizations should be applied.

**Additional context**

On this file, `/cleantalk-spam-protect/inc/cleantalk-public.php` I commented out the `ob_end_clean()` function and everything started working as expected.
![](https://i.vgy.me/zlXmWY.jpg)
Full-Scale image > https://i.vgy.me/zlXmWY.jpg

---

**Related ticket**

https://secure.helpscout.net/conversation/1100934721/149496?folderId=2135277

**HelpScout tag**

`anti-spam cleantalk`

**Comment by vmanthos** [comment]
**UPDATE**

The customer heard back from the plugin's team. 

Disabling the "Capture buffer" option in the plugin's advanced settings, allows WP Rocket to work as expected.
![](https://i.vgy.me/6pG5WR.jpg)

I think we can safely close this @arunbasillal .

**Comment by arunbasillal** [comment]
Thanks for the update @vmanthos. Closing this :)

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1671873794/303366/
