### ISSUE TITLE
UI update for "Combine Google Fonts files" feature

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2429]
During the discussion for #2241 we had the following feedback: 

- https://github.com/wp-media/wp-rocket/issues/2241#issuecomment-586631339
^ Lucy said: 
```
To be a bit pedantic, the option is called "Combine Google Fonts" so it makes logical sense that if there isn't anything to combine (i.e there isn't more than 1 font), nothing is going to be done. I would propose that we should rename the option "Optimize Google Fonts" then it will make sense to process a single font and it takes into account the fact that we're doing more than just combining.
```

- https://github.com/wp-media/wp-rocket/issues/2241#issuecomment-586666669
^ Vasilis said:
```
There is confusion about this among some of our customers who think that we combine Google Fonts. There is no way for us to either combine or optimize the actual fonts. We optimize Google fonts' requests.

On top of what @webtrainingwheels suggested, I'd propose we call it "Optimize Google Fonts' requests".
```

Based on this we had a discussion for new UI:

- https://wp-media.slack.com/archives/CFSCRLVGB/p1583496051012400
- Jonathan also suggested that we could think about removing this option and making it automatic - https://wp-media.slack.com/archives/CFSCRLVGB/p1584019694023000?thread_ts=1583505331.015200&cid=CFSCRLVGB

**Comment by crystinutzaa** [comment]
@arunbasillal What are the directions in here? What changes should be applied in "Combine Google Fonts Files" feature exactly?

**Comment by GeekPress** [comment]
@crystinutzaa We can go with « Optimize Google Fonts »

**Comment by Tabrisrp** [comment]
Is the scope of the issue only renaming the option label on WP Rocket settings page?

**Comment by GeekPress** [comment]
@Tabrisrp Good question ^^ I've just deleted the grooming part on this issue as it's just for renaming an option.

**Comment by webtrainingwheels** [comment]
The descriptive text also needs to be updated. 
And let's introduce a doc about this feature, so it will need a "more info" link too.

**Comment by arunbasillal** [comment]
[Proposal for rename of UI](https://wp-media.slack.com/archives/CFSCRLVGB/p1583496051012400)
-------------------------------
**Option Title: Optimize Google Fonts** (Current: Combine Google Fonts files)
**Option Description: Improves font performance and combines multiple font requests to reduce the number of HTTP requests** (Current: Combining Google Fonts will reduce the number of HTTP requests.)

**Comment by webtrainingwheels** [comment]
@arunbasillal text looks good!

**Comment by arunbasillal** [comment]
Once this is done, please ping Lucy to add screenshots to the updated doc - https://wp-media.slack.com/archives/G8L4EE8N9/p1585875873026800

**Comment by arunbasillal** [comment]
@webtrainingwheels This feature is ready and has been QA'd. You [had requested](https://wp-media.slack.com/archives/G8L4EE8N9/p1585875873026800) that you be notified once this is ready to update the doc.

PR - https://github.com/wp-media/wp-rocket/pull/2525
Doc - https://docs.wp-rocket.me/article/1312-optimize-google-fonts

**Comment by xguiboy** [comment]
it would be nice to add the option like in the plugin OMGF, where you can host the google fonts locally and deactivate the external request
