### ISSUE TITLE
Remove Query Strings Option Removal: 3rd party compatibility part (1/8)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2436]
Sub-card for the epic #2406

This is for 3rd party compatibility files.

#### inc/3rd-party/plugins/page-builder/beaver-builder.php
- [x] Deprecate `rocket_beaver_builder_clean_domain()`
- [x] Create new subscriber for Beaver Builder with method `purge_cache`
- [x] Write tests for `purge_cache`
#### inc/3rd-party/themes/avada.php
- [x] Deprecate `rocket_exclude_avada_dynamic_css()` function and remove related `add_filter`
####  inc/3rd-party/themes/uncode.php
- [x] Deprecate `rocket_exclude_busting_uncode()` function and remove related `add_filter`
#### inc/classes/subscriber/third-party/plugins/PageBuilder/class-elementor-subscriber.php
- [ ] Write tests for `clear_cache()`
- [ ] `clear_cache()` method: remove call to `rocket_clean_cache_busting()`
####  inc/classes/subscriber/third-party/plugins/Optimization/class-hummingbird-subscriber.php
- [ ] Remove `check_remove_query_strings()` method
#### inc/classes/subscriber/third-party/Themes/class-bridge-subscriber.php
- [ ] Write tests for `maybe_clear_cache()`
- [ ] `maybe_clear_cache()` method: remove checks for remove query strings and call to `rocket_clean_cache_busting()`

**Comment by hellofromtonya** [comment]
This issue is current blocked by PR #2510. Once merged, then this issue can progress.
