### ISSUE TITLE
UI improvements for LazyLoad compatibility notice with third party plugins

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2439]
During the discussion for #2260, Greg pointed out how our UI notice is "messy". (here: https://github.com/wp-media/wp-rocket/issues/2260#issuecomment-594604795 and here: https://github.com/wp-media/wp-rocket/issues/2260#issuecomment-594643602)

Basically there are multiple layers of notice as you can see below: 

![image](https://user-images.githubusercontent.com/5751474/76844856-f33af600-6863-11ea-9fc0-cc7dd50ef106.png)

We could improve on this and display one single notice no matter what happens. 

I think we could get rid of the notices in grey and just keep the "red" notice, that would work for all cases. Let's discuss. 

**To reproduce:**

- Enable LazyLoad in [Autoptimize](https://wordpress.org/plugins/autoptimize/) and [WP Smush](https://wordpress.org/plugins/wp-smushit/)
- Visit WP Rocket Settings > Media tab

**Comment by crystinutzaa** [comment]
I was not able to recreate 100% this situation. Only the red message is kept for Autoptimize and WP Smush. Avada theme also addsa new notice so please take into consideration also Avada LazyLoad:
![2020-03-23_1109](https://user-images.githubusercontent.com/45258937/77300638-0849d600-6cf7-11ea-807b-173b29fbc7fa.png)

**Comment by Tabrisrp** [comment]
This should not be asking for grooming when a final decision has not been made yet on the final UI for this.

**Comment by arunbasillal** [comment]
Since the notice in red is more readable, I think keeping that and removing the others would be better. 

**When only one of the LazyLoad's is conflicting (i.e. either LazyLoad images or LazyLoad for iframes):** 

- Lazyload for `<media type: images/ iframes> is currently activated in `<plugin/theme>`. If you want to use WP Rocket’s lazyload, disable this option in `<plugin/theme>`.

**When both LazyLoad's are conflicting:** 

- Lazyload is currently activated in `<Plugin/Theme 1 [and Plugin/Theme 2]>`. If you want to use WP Rocket’s lazyload, disable this option in `<Plugin/Theme 1 [and Plugin/Theme 2]>`.

The interesting thing is, this is how I see it already in `3.5.4` (almost close). Did something change? 🤔 

![image](https://user-images.githubusercontent.com/5751474/80212674-8df1d600-8655-11ea-97f8-641f12d2bb28.png)
^ This one needs to specify which LazyLoad if possible. 

![image](https://user-images.githubusercontent.com/5751474/80212551-5125df00-8655-11ea-9a70-28ab45a81b1b.png)

![image](https://user-images.githubusercontent.com/5751474/80212468-29367b80-8655-11ea-9e24-acb2f26ec591.png)

@GeekPress, @webtrainingwheels What do you think?

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
