### ISSUE TITLE
Auto-purge the "Posts page" when a post is added / updated / deleted

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#244]
When a user uses a page for the "Posts page" option, the page doesn't seem to be purged when a post is added / updated / deleted.

So, the user has to clear cache the view the updates on the Posts page defined.

**Comment by Tabrisrp** [comment]
Works on my testing environnement, can you reproduce the issue on your side?

**Comment by GeekPress** [comment]
I wasn't able to reproduce the issue on several websites. So, it was a specific case for the customer.
