### ISSUE TITLE
The background of the plugin loads various advertising js, which causes the background to be very stuck and garbage!

### ISSUE THREAD

**Issue by pecially520** [wp-media/wp-rocket#2442]
The background of the plugin loads various advertising js, which causes the background to be very stuck and garbage!

**Comment by GeekPress** [comment]
Hi @pecially520 🤚

Not sure here to understand your problem. Can you pleas elaborate?

By the way, can you edit your original post by respecting our template:
https://github.com/wp-media/wp-rocket/issues/new?template=bug_report.md

Thanks ;)

**Comment by GeekPress** [comment]
Hi @pecially520,

We would love to help you. For that, we will need more details as we explained in my previous comment.

As we don't have any news from you, I'm going to close this issue.

Feel free to comment or edit your first message with more details.
