### ISSUE TITLE
PHP warnings & license validation issue created by the use of WP_Filesystem

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2455]
**Describe the bug**
In somes cases where the `licence-data.php` file doesn't have the correct permissions, or the filesystem is using a different method that `Direct`, we have seen 2 kind of issues:
- PHP warnings showing in the error logs
- License validation not working, with the API key & email fields blank

**Root cause**
https://github.com/wp-media/wp-rocket/blob/8b2a567efcab3925dba6fff72c5a622ec2d16386/wp-rocket.php#L87

The use of the global `WP_Filesystem` here is causing the issue. Tonya described it in length:
> In 3.5, we are not specifying which method to use when we invoke WP_Filesystem().  That means another plugin or theme could be specifying it before our code runs.  There’s a filter 'filesystem_method' If it’s using a different method than Direct, then the Warning can be thrown. That’s not what we want.

> We’re currently not checking if WP_Filesystem() succeeded in setting up the env. How? We should be checking if it returns true. If no, it failed.

**Solution**
Get rid of WP_Filesystem() and the global. Instead just do:

```
if ( @is_readable( WP_ROCKET_PATH . 'licence-data.php' ) {
   //
} 
```

We agreed that it was the right choice here: more performant, less risk. We will add a ignore comment for our coding standards, and a comment explaining why.

**Effort**
[XS]

**Comment by alfonso100** [comment]
Related tickets:
https://secure.helpscout.net/conversation/1119941438/153829?folderId=2683093
https://secure.helpscout.net/conversation/1120026469/153844?folderId=2683093

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/search/?query=tag%3Alicense%20validation%20tag%3A3.5

https://secure.helpscout.net/search/?query=tag%3Assh%20sftp%20updater%20support
