### ISSUE TITLE
3rd party not prefixing field called "update" breaks "pre_post_update" and causes Rocket fatal error

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2462]
This is not a Rocket bug or defect. It is being caused by a 3rd party with a non-prefixed field called "update". This non-prefixed field is causing a side-effect in WordPress Core that recalls our callbacks and results in a fatal error.

## Describe the issue
The issue is in a 3rd party plugin, must-use file/plugin, or theme. A 3rd party has a non-prefixed field called "update". 

What does it do to Rocket?
It causes a fatal error _when_ the non-prefixed field is processed in WordPress Core during a post update.

**To Reproduce**
1. Create a field and name it "update".
2. Add a new post.
3. Update the post as a draft.
4. Bam, the error happens.

Or you can add a must-use file with this code to simulate it:

```php
add_action( 'pre_post_update', function( $post_id ) {
	sanitize_post_field( 'update', 'foo', $post_id );
} );
```

## Expected behavior
Fields are supposed to be prefixed. A field named "update" will break any callback that is registered to the WordPress Core action event called `"pre_post_update"`. I'll explain why below.

## The Why

Let me explain what's happening and why.

In WordPress Core, there is an important action event called [`'pre_post_update'`](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/post.php#L3895). [You can learn more about it in Codex here](https://developer.wordpress.org/reference/hooks/pre_post_update/). 

[Here's the code](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3912-L3920):

```php
/**
 * Fires immediately before an existing post is updated in the database.
 *
 * @since 2.5.0
 *
 * @param int   $post_ID Post ID.
 * @param array $data    Array of unslashed post data.
 */
do_action( 'pre_post_update', $post_ID, $data );
```

That hook provides 2 arguments to each registered callback. 

In Rocket, we have 2 callbacks that are registered to `'pre_post_update'` action event. Both expect to receive the 2 arguments that WordPress provides per how the action event is supposed to work:

- [`add_action( 'pre_post_update', 'rocket_clean_post_cache_on_status_change', 10, 2 );`](https://github.com/wp-media/wp-rocket/blob/master/inc/common/purge.php#L352)
- [`add_action( 'pre_post_update', 'rocket_clean_post_cache_on_slug_change', PHP_INT_MAX, 2 );`](https://github.com/wp-media/wp-rocket/blob/master/inc/common/purge.php#L642)

These registrations are done in the `inc/common/purge.php` file.

As this is a WordPress Core action event, it's heavily used by plugins and themes. We expect it to always fire at the right time, i.e. immediately before an existing post is updated in the database, and give us 2 arguments.

But... here comes the fun part ....

In WordPress Core's [`wp-includes/post.php` file](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L2456), there's a filter inside of the `sanitize_post_field()` function. Here it is:

```php
$value = apply_filters( "pre_post_{$field}", $value );
```

Look at the filter event name "pre_post_{$field}". What do you notice? 

👉 If the value for `$field` is equal to 'update', oh no, the filter event name is `"pre_post_update"`. No no no. That's bad. That's really bad. 

Again, a lot of plugins and themes rely on this event name to only apply to the WordPress Core action, including WooCommerce.

### What is happening?

Something in this customer's stack, i.e. some plugin or the theme, has a field name of "update" that is being passed through the function `sanitize_post_field()`. When it does, it fires all of the callbacks registered to "pre_post_update". But through this function, it only passes 1 argument. Just one. So Rocket throws a fatal error. Others may too if they are using both arguments.

## Reference HS

Here are links to HS tickets:
- [ticket](https://secure.helpscout.net/conversation/1088587705/147100/?)

## Backlog Grooming (for WP Media dev team use only)
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by hellofromtonya** [comment]
Let's explore code philosophical design questions:

👉 For this specific problem, should Rocket protect itself in the event that a 3rd Party incorrectly steps on WordPress Core event functionality? 

👉 Should we change Rocket to protect itself from _all_ fatal errors for when a function/callback/method is incorrectly invoked?

We might think "yes" and "why not." But there is a significant impact to Rocket. How? Why? Let's explore.....

## Exploring how far we should go to protect Rocket

In general, we trust WordPress Core functionality and events work as documented and expected. For example, when we register a callback to an event, we expect to receive the argument or arguments that are specified in the source code and Codex.

What if we take the stance to not trust and to guard Rocket in all cases? How can we do that?

It would mean:

- No callback can trust that it will receive the argument(s) it expects or the data type or value.
- As such, we'd need to do the following for ALL callbacks:
    - remove the parameters from the callback param list
    - use [`func_get_args()`](https://www.php.net/manual/en/function.func-get-args.php) to pull the passed argument(s) into the callback.
    - validate each arg to ensure it's the right data type and value we expect

Yes that's doable. But wow, think about what we did to Rocket. We made it:

- More complex
- Less readable and understandable
- Harder to maintain

While yes we can protect Rocket from _all fatal errors_ due to incorrect usage outside of Rocket, I wonder:

👉 Should we? 

I don't think so. The ramifications of not trusting Core are too steep.

## What should we do? 

Work with each customer to identify which 3rd party is causing the problem.  Empower our customers.

- Help them to identify which plugin, must-use file, or theme is causing it
- Potentially create a custom helper plugin 
- Work with the 3rd party to help them fix the problem

Instead of modifying Rocket to fix a problem that exists externally, empower our customers.

**Comment by webtrainingwheels** [comment]
So far we can identify 2 culprits that cause this issue: 

- Classified Listing Pro: https://www.radiustheme.com/downloads/classified-listing-pro-wordpress/
- SW WooCommerce : https://www.smartaddons.com/forum/519-sw-matrix/32662-sw-woocommerce

I will reach out to them

**Comment by hellofromtonya** [comment]
@webtrainingwheels Good work! Yes, I agree. Reach out to alert them to the problem.

**Comment by webtrainingwheels** [comment]
Contacted: 
SW WooCommerce: https://secure.helpscout.net/conversation/1183121538/169943?folderId=377610

Classified Listing Pro: https://secure.helpscout.net/conversation/1183102664/169939?folderId=377610
