### ISSUE TITLE
Gzip compression for static files

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2465]
## Why are we doing this feature?
WP Rocket enables gzip compression on activation. Right now we generate the gzip versions of the files on the fly. That is, the file is gzipped when a browser requests it. For huge websites with a lot of traffic, this is inefficient and the file can be gzipped once and served multiple times. 

The impact is minimal for a huge portion of our customer base with smaller websites. But we can do this to be more efficient and improve performance wherever possible. 

## User expectations and experience 
Nothing changes for the end user, the feature will be invisible and under the hood. Smaller websites shouldn't expect any noticeable performance gain either. 

For websites with a lot of traffic might notice lower CPU usage. 

## How will we do this feature? 
- We already gzip compress HTML files. We will do the same for CSS and JS. 
- On Apache, rewrite rules to be added to accommodate for this. (Examples: [here](https://httpd.apache.org/docs/2.4/mod/mod_deflate.html#precompressed) and [here](https://royal.pingdom.com/can-gzip-compression-really-improve-web-performance/))

**Technical overview**
- Update the write_file() method in WP_Rocket\Optimization\Abstract_Optimization to also save a gz file for the same content, with the extension .css.gz or .js.gz
- Add new method to functions/htaccess.php, to generate the htaccess code to serve compressed assets directly, based on the rewrite rules above
- Update functions cleaning the minify/cache busting files in functions/files.php, to also clean the .gz files

This represent a couple days of work, but relies on the first note point below to make sure we can add proper automated tests for it.  

**Notes**
- @everyone: This only applies to files that are minified/combined/cache busted by us. This means that:
- If none of the options above are used, CSS/JS files will **not** be statically compressed
- If only minify is checked, only CSS/JS files minified by us will be statically compressed. Files which already have .min in their filename will be **not** statically compressed
- If combine is checked, the generated CSS/JS files will be staticly compressed
- CSS/JS files without a version query strings will **not** be statically compressed
- Any CSS/JS file excluded from the options above will **not** be statically compressed  

## Risks
- Since we will be generating more static files, the cache_dir_size issue could be an issue. 
- This shouldn't stop us from implementing this though. gzipped file will be small anyways. Plus we need to fix the original issue some other way anyways. 

## Testing
- Load a website on a gzip compatible browser. Make sure there are no 404 or such errors
- Test scenarios where CSS and JS combination is enabled and disabled.

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4218021

**Comment by tonya** [comment]
Think you tagged the wrong Tonya :)

**Comment by GeekPress** [comment]
Hi 🤚

Sorry, I don't why you have been tagged 🤨

**Comment by nsgoyat** [comment]
Hey @Tabrisrp 
Any update on this? I noticed that WP Rocket doesn't generate `.gz` version of cache/html files. Instead, it creates `index-https.html` and `index-https.html_gzip` files. CSS/JS files processed by WP Rocket are in `.gz` format but the page cache files aren't.

A lot of Wp Rocket users like me use NGINX so it would be a great addition to the plugin...
