### ISSUE TITLE
Preconnect requests resources from Google Fonts 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2473]
**Describe the solution you'd like**
If the « Combine Google Fonts » options is activated, we can preconnect requests resources from Google Fonts (fonts.gstatic.com).

Adding the preconnect resource hint will instruct the browser to preconnect to Google Fonts while it is loading the CSS, saving load time.

The solution is to automatically add this line in the `<head>` section:
`<link href="https://fonts.gstatic.com" crossorigin rel="preconnect" />`

**Backlog Grooming**
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Screenfeed** [comment]
Scope a solution ✅
Add a new callback to the hook `wp_head`, conditioned on the option `minify_google_fonts`. This callback will print the `<link>` element.

Estimate the effort ✅
effort: `[S]`
