### ISSUE TITLE
Chrome phasing-out User Agent starting from Chrome 81

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2475]
**Describe the bug**
Google is planning to phase-out support of user agent starting from Chrome 81 and complete with version 85, replacing it with an API "Client Hints" instead. Target is mid-September 2020.

Other browsers intend to follow the same trend.

WP Rocket is using User Agent detection for mobile caching, cache exclusion based on user agent option, WebP compatibility, and preload.

We will need to follow the changes made in Chrome and other browsers, and adjust accordingly.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
I think it's too early for grooming on this one, looking at the status everything is still in motion and specs are still in draft, so we have to wait.

**Comment by hellofromtonya** [comment]
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by piotrbak** [comment]
@Tabrisrp this seems to be ongoing topic, right?
https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/

**Comment by remyperona** [comment]
Indeed, it's been more than 2 years already, so we can still wait and see.

**Comment by piotrbak** [comment]
It's still being discussed:
https://github.com/miketaylr/user-agent-reduction/issues

**Comment by piotrbak** [comment]
It was lastly updated 2 years ago
