### ISSUE TITLE
Jetpack Custom CSS compatibility

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#248]
Jetpack has an option to add custom CSS on the front-end. It generates an HTTP request like this website.com/?custom-css=1&csblog=1&cscache=6&csrev=489 which causes a lack of performance.

Like we did for Simple Custom CSS plugin, we could create a CSS file with the content of this request if we detect that this feature is used by the customer.

**Comment by Tabrisrp** [comment]
Duplicate of #955
