### ISSUE TITLE
Replace YouTube iFrame With Image Doesn't Work For Video Series

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2495]
**Describe the bug**
When you enable the replace youtube iframe with an image option by default the player is replaced with an image to improve load time. This works fine for standard video urls but not so much if you're embedding a playlist. 

**To Reproduce**
1. Enable the option Replace YouTube iframe with preview image
2. Embed a video playlist such as the following 

https://www.youtube.com/playlist?list=PLQrysnKct_bgKHNqOMf6x56cZkeFTFBEs

I pasted the URL into a paragraph block and let the oembed system do the rest. 
3. Visit the URL and see that the player still loads. 

**Expected behavior**
I expected the option to replace with the playlist player with an image which it does not (it only lazyloads the iframe with an about:blank source attribute (as if the media option was never checked). 

**Screenshots**
I set up a test URL here you can analyze -> https://www.sertmedia.com/video-series-lazyload-test/

**Additional context**
I stumbled across the error on a client site I was working on where I noticed the video player on the homepage was still being downloaded on the initial load (in a GTMetrix waterfall). Needless to say, I had the option enabled and tried to determine if the issue was due to a plugin or theme issue. I then noticed that playlists aren't replaced with an image. 

**Possible Solutions**
1. There should be documentation or a notice that it only works with a standard single video embed, but this is not a preferred fix. 
2. A preferred fix would be the player is replaced by the thumbnail of the first video in the playlist this way even above the fold videos are properly optimized.

**Comment by Tabrisrp** [comment]
The way the thumbnail replacement works is by doing a relatively simple correspondance between the Youtube URL and the thumbnail URL.

The issue with a playlist is that we can't do that, there isn't a thumbnail URL to directly associate with the playlist, and we have no way to know what is contained in the playlist from the URL only.

There is a way to display thumbnail for a playlist, by using the Youtube API, but:
- it requires an API key
- it will be much slower

@GeekPress @arunbasillal do we want to go down that way?

Else, the solution is to update our documentation and maybe option description to explain that it doesn't work with playlists.

**Comment by GeekPress** [comment]
Thanks @Tabrisrp for the details.

@arunbasillal @webtrainingwheels Can we write an internal and public documentations about that?

**Comment by Tabrisrp** [comment]
> Thanks @Tabrisrp for the details. Do we have a way to detect video series to not apply the feature on these videos and avoid to trigger the issue?

That's already the case, we detect them and apply the default iframe solution to playlist

**Comment by webtrainingwheels** [comment]
@GeekPress I will be writing a doc about iframe lazyload specifically and we will include it there. Have noted it here: https://app.asana.com/0/1170215314810181/1170238436418110/f

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
