### ISSUE TITLE
Add compatibility for the AMP for WP plugin

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2498]
The following plugin has 100.000 active installations:
https://wordpress.org/plugins/accelerated-mobile-pages/

We should consider adding compatibility with it, the way we have for the official AMP plugin.

Features not working:
* CDN rewriting
* Advanced settings > **Change End Point to ?amp** stops caching.
![image](https://user-images.githubusercontent.com/193660/78529357-16651f80-77ea-11ea-8b3b-67cda059fef4.png)

**Ticket:** https://secure.helpscout.net/conversation/1122238401/154357?folderId=2135277
**HelpScout tag:** `amp for wp`

**Backlog Grooming**
- [x] Scope a solution
- [x] Estimate the effort

**Comment by GeekPress** [comment]
Hi @vmanthos 🤚

Could you add more details about what should we check and do in terms of compatibility?

**Comment by camilamadronero** [comment]
JIC, related issue: https://github.com/wp-media/wp-rocket/issues/753.
New ticket:https://secure.helpscout.net/conversation/1147967492/160998?folderId=2675957.

**Comment by kierantaylorio** [comment]
Related ticket: https://secure.helpscout.net/conversation/1199626639/174221

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1250522964/185792/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1248418261/185307

**Comment by sandyfigueroa** [comment]
Related: https://secure.helpscout.net/conversation/1362599019/221830/

**Comment by alfonso100** [comment]
related: https://secure.helpscout.net/conversation/1444848127/244951?folderId=273766

**Comment by camilamadronero-zz** [comment]
related https://secure.helpscout.net/conversation/1456361827/248443?folderId=2675957

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1511321016/263601?folderId=4075535

**Comment by NataliaDrause** [comment]
Communication with the plugin's theme: https://secure.helpscout.net/conversation/1739992100/316138/

@piotrbak could you please take a look into this compatibility issue, if this can be added to one of the upcoming projects?

**Comment by remyperona** [comment]
@piotrbak Looking at the code on their side, they copied a lot of our code to handle the compatibility already, in this file: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php

They are also handling the query string compatibility based on the related option value, and the CDN rewritting for images.

I don't think there is anything more to do on our side in fact?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, it seems so. I'll confirm to see if we pass the AMP tests using their compatibility

**Comment by piotrbak** [comment]
@Tabrisrp @vmanthos I've checked with the latest version of the [plugin](https://wordpress.org/plugins/accelerated-mobile-pages/) and it seems that their compatibility is working just fine. The page is cached and AMP tests are passing when all features are enabled.
