### ISSUE TITLE
Error in query monitor on PHP 7.4.4: "Invalid characters passed for attempted conversion, these have been ignored"

### ISSUE THREAD

**Issue by jazir5** [wp-media/wp-rocket#2499]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
Using WP-rocket 3.5.1

**Describe the bug**
Receiving the quoted error in the php notices section in query monitor

**To Reproduce**
1. Install Query Monitor
2. Change from PHP 7.3 to 7.4
3. Open Query Monitor's php notices section

**Screenshots**

![wp-rocket php error](https://user-images.githubusercontent.com/31750063/78104333-ebbb3700-73a3-11ea-9315-f073aa8ae6e8.PNG)

**Additional context**

**Comment by GeekPress** [comment]
Hi @jazir5 🤚

Thanks for reporting the issue. We are already aware about it: https://github.com/wp-media/wp-rocket/issues/2430 and we will try to fix it as soon as possible.

I'm closing this issue as we already have one open for it :)
