### ISSUE TITLE
Deprecated: tag_row_actions after update to WooCommerce 4.0

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#2504]
![Screenshot_2](https://user-images.githubusercontent.com/43606394/78176388-b0c90a00-745c-11ea-9744-dd6c2a9868c0.png)
This occurs when Wp-rocket 3.5.2 is active
Deprecated: tag_row_actions has been deprecated since version 3.0.0. Use {$ taxonomy} _row_actions instead.

**Describe the bug**
A message displayed from a function listed as "deprecated"

**To Reproduce**
1. With WooCommerce installed, we go to products
2. We go to categories
3. Just below the category name you see the message

**Comment by GeekPress** [comment]
Hi @Camilo517 🤚

To be able to work on this issue, thanks to edit your original message by using our issue template:
https://github.com/wp-media/wp-rocket/issues/new?template=bug_report.md

Thanks

**Comment by Tabrisrp** [comment]
`tag_row_actions` is used in `inc/admin/admin.php`.

After testing, this is happening after WooCommerce 4.0 update. I was not having the warning with version 3.8.

We need to replace the usage of `tag_row_actions` by `{$taxonomy}_row_actions`, which means we now have to loop over all public taxonomies instead.

**Comment by GeekPress** [comment]
Thanks @Camilo517 for the update :)

**Comment by Camilo517** [comment]
The next time I report something I will try to follow what he told me :)

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
After testing, this is happening after WooCommerce 4.0 update.

**Identify the root cause** ✅ 
tag_row_actions is used in `inc/admin/admin.php`.

**Scope a solution** ✅ 
We need to replace the usage of tag_row_actions by {$taxonomy}_row_actions: 
- we now have to loop over all public taxonomies
- for each, hook on the action to add the purge link

**Effort** ✅ 
Effort `[S]`

**Comment by GeekPress** [comment]
**Customer to follow up when fixed:**
https://secure.helpscout.net/conversation/1133390725/157122/

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1154831860/162646/

**Comment by mifrero** [comment]
Related ticket: https://github.com/wp-media/wp-rocket/issues/2504

**Comment by mifrero** [comment]
Related: https://secure.helpscout.net/conversation/1152485392/162106/

**Comment by oguilleux** [comment]
This doesn't happen only for Woocommerce, I have the exact same error in the native category taxonomy (wp-admin/edit-tags.php?taxonomy=category).

I'm using WP Rocket 3.5.1 on WP 5.4.1 - Deactivated all plugins and used default theme Twenty Twenty.

**Comment by GeekPress** [comment]
@oguilleux This issue has been fixed with WP Rocket 3.5.5, please update to the last version (3.5.5.1).

Best
