### ISSUE TITLE
Improve l18n in faq.php

### ISSUE THREAD

**Issue by fxbenard** [wp-media/wp-rocket#251]
Before pushing a new pot in transifex sprintf should be used to remove URLS from the strings:

https://github.com/wp-media/wp-rocket/blob/master/inc/admin/faq.inc.php#L4 and all following lines

**Comment by Tabrisrp** [comment]
What's your preferred method to make the URL translatable too? the links will be different for each language

**Comment by fxbenard** [comment]
I missed the fact that URLs will change for each locales. Having them hard coded in the pot will break their translations anyway.
A wp_localize_script for each locale?
Might not be working, do you have an idea?

**Comment by Tabrisrp** [comment]
It's not possible to have URLs to be translated in the pot file?

**Comment by fxbenard** [comment]
Generating the pot will lock the URL and create a generic file to translate. How are URLs generated?

**Comment by Tabrisrp** [comment]
They are created in HelpScout, they will have a different subdomain and slug for each language

**Comment by GeekPress** [comment]
Could we fix this issue for a next major release as we plan to release the 2.9 beta friday?

**Comment by fxbenard** [comment]
As I don't have any idea how to fix that yes! Not sure the translations will work and I'm **definitely not in favor** of providing such strings to translate:

![2016-12-07_11-47-36](https://cloud.githubusercontent.com/assets/802114/20964743/0a714248-bc73-11e6-977d-96db3ad24f0f.png)

Up to you!

**Comment by glueckpress** [comment]
Those URLs should be translatable in order to provide full localized FAQ for fr_FR, it_IT, es_ES and de_DE. Since we’re managing translations ourselves, including URLs in strings should not be of any security-related concerns either.

@fxbenard Something like this should work, shouldn’t it?
```
<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/67-what-exactly-does-wp-rocket-do?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">What exactly does WP Rocket do?</a>',  ); ?></h2></li>
```
The URL also provides context. If we’d exclude the URL via `sprintf`, the localization of it would need extra context, like: 
```
<?php
sprintf( 
	'<li><h2><a href="%1$s" target="_blank">%2$s</a></h2></li>',
	__( 'http://docs.wp-rocket.me/article/67-what-exactly-does-wp-rocket-do?utm_source=plugin&utm_medium=faq&utm_campaign=doc' ),
	/* translators: link text for http://docs.wp-rocket.me/article/67-what-exactly-does-wp-rocket-do */
	__( 'What exactly does WP Rocket do?'  )
);
```
… though `/* translators: … */` comments only show up in GlotPress afaik.

**Comment by fxbenard** [comment]
It's not only a security concern. It's more a source of errors.
Comments show also in transifex (not sure if it's the _n content or the *translators). Adding context to all string is a good practice.
But Yes if strings needs to be translated, leave the string as that and ask all translators to change directly the URL in transifex.
**I'll push the pot in tx**

**Comment by GeekPress** [comment]
@Tabrisrp The UTM parameters could be excluded from the URLs to translate and added later.

**Comment by fxbenard** [comment]
Happy translations to all: https://www.transifex.com/wp-media/wp-rocket/dashboard/
