### ISSUE TITLE
500ms of pause between each preload request is not applied

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2514]
**Describe the bug**
There's a `usleep` function that was supposed to make a pause between each preload request. It's not happening at this moment:
http://snippi.com/s/ljuruem

This log comes from:
https://github.com/wp-media/wp-rocket/blob/9b175725a5c568f27808875c041fc67cba264ae7/inc/Engine/Preload/AbstractProcess.php#L201

**To Reproduce**
1. Enable preload in WP Rocket settings
2. Make sure to log each request with the current time from the mentioned line of code
3. Launch the preload
4. Check the time of requests

**Expected behavior**
Preload URL and make a 500ms pause before making another request.

**Comment by GeekPress** [comment]
@piotrbak Which kind of preload did you do? It seems that the `usleep` is used only for sitemap preload.

**Comment by piotrbak** [comment]
@GeekPress I've just checked on `mega`, it's the same for `sitemap preload`.

**Comment by GeekPress** [comment]
I'm wondering if we should stay like that :D 

Our preload process is actually slow. I'm afraid by adding a 500ms pause between requests, then it's going to be even slower.

@crystinutzaa @Tabrisrp @Screenfeed @hellofromtonya What do you think?

**Comment by Tabrisrp** [comment]
@piotrbak Did you test the value passed to the `usleep` function to confirm it's correctly set?

**Comment by jazir5** [comment]
@GeekPress 

As a user, i agree, the current preload process is quite slow, an additional 500 ms per request seems like it would make the entire process take an onerous and excessive amount of time to complete on large sites.

**Comment by hellofromtonya** [comment]
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by piotrbak** [comment]
The approach has changed in the 3.12 WP Rocket. We use Action Scheduler to handle the queue
