### ISSUE TITLE
Order of categories is different between Categories page & Product "categories" filter

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2517]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If you open the Categories page, you will find one particular order for the categories and sub-categories. However, if you go in the Products page and open the "categories" dropdown filter, then you will see another different order for the categories and sub-categories.

**To Reproduce**
See above.

**Expected behavior**
The order in the Product "categories" dropdown filter should be identical as the one defined by the user in the Categories page.

**Screenshots**
https://gevcen.tinytake.com/tt/NDE4NTM4NF8xMjk5MjQwNA

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
Wrong repository I think?
