### ISSUE TITLE
French mistake in sitemap description

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2519]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In the French description of the sitemap preload, you wrote :
"Préchargement de la sitemap" but it should be "Préchargement **du** sitemap"

Also, just below, you wrote :
"Indiquez la ou les sitemap(s) XML à utiliser pour le préchargement" but it should be "Indiquez **le** ou les sitemap(s) XML à utiliser pour le préchargement"

The word "sitemap" is better used as a masculin in French.

**To Reproduce**
N/A

**Expected behavior**
See above.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/78447425-0f1f0400-767a-11ea-87c0-30414f61c794.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by WordPresseur** [comment]
Fixed
