### ISSUE TITLE
Move vendors dir outside of inc & move min in vendors

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#252]
Reorganize directories a bit to have a better structure. Currently we have:

- min/ in root directory, but in reality it's a vendor since we use Minify
- vendors directory in inc/, but it's not our code, so should be outside

So I propose to have:

- vendors in root directory
- min in vendors

**Comment by GeekPress** [comment]
In fact, inc/ contains all PHP code. It's why vendors/ is in inc/ actually.

I'm agree for the min/ folder, it should be in vendors/. The reason to be in the root directory is we are limited by the URL length during a minification.

The URL can't have more than 255 characters. If we decide to move min/ into vendors/ it will add inc/vendors/ in the URL so 12 characters. So, in some case we will concatenate 1 less CSS or JS files in the same minified file.

**Comment by Tabrisrp** [comment]
I forgot about that point, won't fix then 👍
