### ISSUE TITLE
Add an option or filter to exclude by header

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2528]
The Gtranslate plugin is not really compatible with caching, but one of their team suggested that if we could make cache exclusions based on their header, this would work. 

We already have about 15 related tickets.
Helpscout tag: `gtranslate`

The Gtranslate support member edited our core files to resolve this for the customer, with this: 

```
// Don't process if request is from GTranslate
if(isset($_SERVER['HTTP_X_GT_LANG'])) {
$this->set_error(
'GTranslate requests are excluded.',
[
'language' => $_SERVER['HTTP_X_GT_LANG'],
]
);
return false;
} 
```

I don't think this is a common request but if we could start with a filter, we could provide some kind of solution for this issue. 

https://secure.helpscout.net/conversation/1124275965/154838?folderId=377611#thread-3205853452

The core issue is related to RTL/LTR languages. They should be cached separately but what's happening with Gtranslate is one version gets cached then used for the wrong language:
https://secure.helpscout.net/conversation/1120798112/154024/#thread-3183924216

Excluding by IP address would also work for them.

**Comment by GeekPress** [comment]
@hellofromtonya @Tabrisrp @cristianuibar What do you think about that?

**Comment by Tabrisrp** [comment]
Excluding by a specific header is not much different than other exclusions we already do, like with the user-agent.

Adding an option is likely overkill compared to the benefit it would bring for most of our users, but a filter, with the values saved in the config file, can work.

**Comment by mifrero** [comment]
I think this ticket could be related: https://secure.helpscout.net/conversation/1153553998/162350?folderId=2952229

**Comment by mifrero** [comment]
Related: https://secure.helpscout.net/conversation/1204526427/175534/

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1404489917/233653?folderId=2135277

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1457460107/248774?folderId=2135277

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1461210021/249870?folderId=2135277

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1505481799/262070/

**Comment by kmmathis** [comment]
Would definitely be useful to have a filter for bypassing the cache for requests with a specific header. We are building an app that uses Inertia.js to load dynamic content, if we could bypass all requests with the X-Inertia header that would be very convenient.

**Comment by piotrbak** [comment]
There's currently no way for us to be compatible with the Pro version of the GTranslate plugin. However, we're fully comaptible with the free one. In order to mvoe forward with this compatibility we'd need to have access to their API to clear their cache. Closing it for now, as it's not going to be implemented anywhere soon
