### ISSUE TITLE
Comments for ESI tags are removed

### ISSUE THREAD

**Issue by juliquiron** [wp-media/wp-rocket#253]
The comments of the ESI tags are being removed by wp rocket and breaking the interaction with varnish. For example:
```
<!--esi <esi:include src="http://XXXX/views/esi/snippet.php?name=oc_oezgarten"/> -->
<esi:remove> Heute geöffnet bis 19:00 Uhr, <a href="/XXXX">so finden Sie uns!</a> </esi:remove>
<!--esi <esi:include src="http://XXXX/views/esi/overview.php?name=oc_oezgarten_overview"/> --> <esi:remove>
```
Becomes to:
```
<esi:remove> Heute geöffnet bis 19:00 Uhr, <a href="/XXXX">so finden Sie uns!</a> </esi:remove>
```

and this breaks the expected behavior.

**Comment by juliquiron** [comment]
With this patch the issues is sovled
```
diff --git a/wp-content/plugins/wp-rocket/min/lib/Minify/HTML.php b/wp-content/plugins/wp-rocket/min/lib/Minify/HTML.php
index e6b4fcd..f54d455 100644
--- a/wp-content/plugins/wp-rocket/min/lib/Minify/HTML.php
+++ b/wp-content/plugins/wp-rocket/min/lib/Minify/HTML.php
@@ -164,7 +164,7 @@ class Minify_HTML {
     
     protected function _commentCB($m)
     {
-        return (0 === strpos($m[1], '[') || false !== strpos($m[1], '<!['))
+        return (0 === strpos($m[1], '[') || false !== strpos($m[1], '<![') || 0 === strpos($m[1], 'esi'))
             ? $m[0]
             : '';
     }
```

**Comment by GeekPress** [comment]
Hi @juliquiron 

Thanks for your report and contribution.

What do you think about testing ```strpos($m[1], 'esi:include'))``` instead of just ```strpos($m[1], 'esi'))```?

**Comment by juliquiron** [comment]
Nope, because the tag detected and which we need to keep is `<!--esi` and not `<esi:include`, right?

**Comment by GeekPress** [comment]
Yes you're right.

Is it possible to create a pull request with your fix?

I also suggest you to warn the library's author, there is a github repo too: 
https://github.com/mrclay/minify

**Comment by juliquiron** [comment]
@GeekPress I have no permissons for create a branch for a pull request, no problem if you authorize my user.

**Comment by GeekPress** [comment]
You can fork the repo and then submit your PR.

**Comment by GeekPress** [comment]
@juliquiron The fix will be added on the next major version (2.9).
