### ISSUE TITLE
PenNews AMP plugin compatibility

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#2536]
**Describe the bug**
[PenNews theme](https://themeforest.net/item/pennew-multiconcept-newsmagazine-amp-wordpress-theme/20822517) uses a PenNews AMP plugin which is not compatible with WP Rocket.

**To Reproduce**
1. Install PenNews theme and WP Rocket
2. Enable Minify CSS files or optimize CSS delivery options
3. AMP page errors show up

**Expected behavior**
Working Minify and optimize CSS delivery with integrated AMP function.

**Additional context**
Theme developer tried to make their integrated AMP function compatible with WP Rocket like we did with for Automattic AMP:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/3rd-party/plugins/mobile/amp.php

Based on compatibility we have with [Automattic AMP](https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/3rd-party/plugins/mobile/amp.php) theme developer tried to make PenNews AMP plugin compatible but did not succeed. 

Related to ticket [#155069](https://secure.helpscout.net/conversation/1125205937/155069/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
