### ISSUE TITLE
Add a "just-in-time" preloading - preload pages upon mouse hover

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2538]
**Is your feature request related to a problem? Please describe.**
Reduce the "visible" loading time to the end-user

**Describe the solution you'd like**
Implement a just-in-time preloading

**Describe alternatives you've considered**
A third-party plugin is doing the job well, but would be great to have such kind of feature built-in in WP Rocket, to avoid compatibility issues : https://wordpress.org/plugins/wp-instant-links/

**Additional context**
N/A

**Comment by Camilo517** [comment]
Something better was proposed, flying pages is more powerful #2161

**Comment by GeekPress** [comment]
Hi @gevcen @Camilo517 🤚

Please vote for this feature directly on our official roadmap:
https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/30-preload-pages-before-the-user-click-on-it

Cheers 😇

**Comment by Camilo517** [comment]
@GeekPress There are improvements that I proposed years ago and it was marked as "feature request" can you add in the roadmap? Thanks
