### ISSUE TITLE
Require a minimum time for Cache Lifespan

### ISSUE THREAD

**Issue by blogtutor** [wp-media/wp-rocket#255]
I just had a client site that was maxing out her CPU usage. Turns out that her designer changed the cache lifespan to 2 seconds. Since cache preloading was active (on the default 500ms rate), her server was stuck in a cycle of regenerating pages like crazy. Changing the cache lifespan back to 7 days immediately solved the issue.

It would be really great if WP Rocket had a protection in place to keep this from happening -- maybe if cache preloading is enabled, the lifespan should not be able to be set lower than, say 30 minutes?

Even better, WP rocket could figure out what the total time to preload the entire cache would be, and then require the cache lifespan to be at least that long. (But that's probably overly complicated... just making it a 30 or 60 minute lifespan minimum, when preloading is active, is probably sufficient.)

Thanks!

**Comment by Tabrisrp** [comment]
In 2.10 lifespan can't be under 10 minutes
