### ISSUE TITLE
Preload Enhancement //fonts.gstatic.com 3.5.3

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#2567]
In the new version of wp rocket 3.5.3 the automatic preload of //fonts.gstatic.com is done
![Screenshot_3](https://user-images.githubusercontent.com/43606394/80001027-32411480-84be-11ea-88df-23080baaef34.png)
But there is also //fonts.googleapis.com that should also be preloaded
And in many cases when updating from wp rocket 3.5.2 to 3.5.3 //fonts.gstatic.com we already had it added, a message should appear warning not to double preload
Thank you

**Comment by Mic2005** [comment]
Why is it done automatically now? Only for Goovle fonts. I add all external urls in the preload list. Why not scan all external urls and add them automatically in the list?

**Comment by Tabrisrp** [comment]
`fonts.googleapis.com` is the URL used to request the list of fonts + options from Google fonts.

`fonts.googleapis.com` should be prefetched using `dns-prefetch`. It's likely added automatically by WordPress if the google font is enqueued via `wp_enqueue_style()`. If not, you can add it to our DNS prefetch option.

We use `preconnect` for `fonts.gstatic.com` as it's the URL used for the actual font files. It enables to start the connection alongside the initial request to Google fonts, and that way improve loading time.

Further reading is available here: https://www.smashingmagazine.com/2019/06/optimizing-google-fonts-performance/

**Comment by GeekPress** [comment]
Hi @Camilo517 

As @Tabrisrp explained, the `fonts.googleapis.com`  should be already prefetched by WordPress if your theme is using `wp_enqueue_style()`

One thing we can maybe improve is to « force » this domain to be prefetched if for any reason your fonts aren't enqueued by using WordPress function.

If your are using another plugin to preload `fonts.gstatic.com` I suggest you to let WP Rocket takes care of that. It's one less thing to have to do on your side ;)

**Comment by Camilo517** [comment]
Hello @Tabrisrp @GeekPress 
I understand, but in many cases in versions before 3.5.3 many of us have added fonts.gstatic.com in the text field of prefetch dns. So when updating wp-rocket it would be duplicating because wp-rocket already has it by default
Wouldn't it be better if you couldn't add fonts.gstatic.com in the text field to prevent duplication?

@GeekPress I understand perfectly, I will check if wp_enqueue_style is used
I think the second thing you said is good

**Comment by GeekPress** [comment]
dns-prefetch and preconnect aren't the same. preconnect is doing more than dns-prefetch.

If you already added the dns-prefetch by using our option, then you can keep it, it won't have any bad impact on your loading time.
