### ISSUE TITLE
Google plugins request

### ISSUE THREAD

**Issue by xguiboy** [wp-media/wp-rocket#2568]
Google Fonts
it would be nice to add the option like in the plugin OMGF, where you can host the google fonts locally and deactivate the external request

Google Tag Mananger
Like in the google analytics, it would be nice to host the events from the GTM locally as well

**Comment by GeekPress** [comment]
Hi @xguiboy 

Can you please submit your feature request here?
https://portal.productboard.com/wp-media/1-wp-rocket-portal/tabs/4-suggestion-box/submit-idea

Thanks :)

**Comment by xguiboy** [comment]
sure, just did it. thanks

**Comment by worldsdream** [comment]
Local google fonts, thats a great option to have.
