### ISSUE TITLE
Include FIGURE element when applying LazyLoad to background images

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#2570]
Currently, we only apply LazyLoad to background images included on four elements: div, span, section, li

_See https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket#background-images_

But sometimes background images are applied to the FIGURE element; for example, Oxygen Builder does this.

So it would be a benefit for our customers if we were to include the FIGURE element and allow those background images to be lazyloaded as well.

Related ticket: https://secure.helpscout.net/conversation/1139746134/158786/

Related Slack discussion: https://wp-media.slack.com/archives/C43T1AYMQ/p1587406626009600

(Note to readers: the two links above are internal to WP Media, so only our staff can view them.)

**Customer to follow up when released**
- https://secure.helpscout.net/conversation/1131560651/156572?folderId=273768

**Comment by GeekPress** [comment]
@hellofromtonya I guess this issue should be moved to this repo?  https://github.com/wp-media/rocket-lazyload-common

**Comment by hellofromtonya** [comment]
@GeekPress What if instead we keep it here to help us better track its progress as part of our sprint? The fix for it can reference this issue number, which then automatically wires the 2 repos together in this issue and our sprint project board(s). What do you think?

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Reproduced the issue on localhost.

**Identify the root cause** ✅ 
The root cause is that figure is not included in lazyload and needs to be added in here:
https://github.com/wp-media/rocket-lazy-load/blob/2eb7afda9ccb5e168f0017f9d4cdca27b7e59d64/src/Dependencies/RocketLazyload/Image.php#L101
https://github.com/wp-media/rocket-lazy-load/blob/2eb7afda9ccb5e168f0017f9d4cdca27b7e59d64/src/Dependencies/RocketLazyload/Image.php#L56

**Scope a solution** ✅ 
Add `figure` on those 2 lines.

**Effort** ✅ 
Effort `[S]`

**Comment by Tabrisrp** [comment]
@arunbasillal There won't be a specific PR on WPR for this one, as the PR was made on the rocket-lazyload-common repository, and there is no changes needed on WPR itself.

What you can do to test is to use the `develop` branch, and do a `composer update` to get the latest version of the `rocket-lazyload-common` package (2.5.7).

Then use a `figure` element with a background image, to confirm it's lazyloaded as expected.

**Comment by arunbasillal** [comment]
I tested this as recommended here (https://github.com/wp-media/wp-rocket/issues/2570#issuecomment-621292370) with the following input (from customer website)

```<figure class='oxy-gallery-item-contents' style='background-image: url(https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png);'>
<img src="https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png" data-original-src="https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png" data-original-src-width="150" data-original-src-height="90" alt="Logo Sols">
<figcaption></figcaption>
</figure>
```

Output:

```
<figure data-bg="url(https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png)" class='oxy-gallery-item-contents rocket-lazyload' style=''>
<img src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E" data-original-src="https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png" data-original-src-width="150" data-original-src-height="90" alt="Logo Sols" data-lazy-src="https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png"><noscript><img src="https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png" data-original-src="https://customer-domain.com/wp-content/uploads/2020/04/logo-sols.png" data-original-src-width="150" data-original-src-height="90" alt="Logo Sols"></noscript>
<figcaption></figcaption>
</figure>
```

The image was lazyloaded correctly as I scrolled down.

**Comment by Tabrisrp** [comment]
This is marked for 3.6, but it will be pulled with the next release, is it ok @GeekPress ?

**Comment by GeekPress** [comment]
@Tabrisrp Which next release? 3.5.5?

**Comment by Tabrisrp** [comment]
Yes

**Comment by GeekPress** [comment]
Can we make a release on Rocket Lazy Load first? To stress test the change before to apply it on WP Rocket?

**Comment by hellofromtonya** [comment]
>Can we make a release on Rocket Lazy Load first? To stress test the change before to apply it on WP Rocket?

@Tabrisrp What's the status of 👆 ?

**Comment by Tabrisrp** [comment]
This PR contains the change and is ready for review: https://github.com/wp-media/rocket-lazy-load/pull/108

**Comment by hellofromtonya** [comment]
@Tabrisrp In talking with @GeekPress and @arunbasillal, we'd like to move this to 3.6 instead of 3.5.5. Why? We want to stagger release it to slowly validate that everything works as we expect. If something goes wrong, then it gives us a longer runway to make adjustments.
