### ISSUE TITLE
licence-data.php deleted during development

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2572]
**Describe the bug**
With the introduction of the deletion of `licence-data.php` after a successful validation in 3.4, now this file can be marked as deleted when we develop and the deletion incorrectly pushed to git.

**To Reproduce**
1. Validate license locally
2. See the file marked as deleted in the git changes

**Expected behavior**
The file should be preserved. Dev team can discuss together the best approach to handle that.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
By adding the licence-data.php file into a .gitignore, the issue fixed, isn't it?

**Comment by Tabrisrp** [comment]
We still want the file to be added to git, so we can't use `.gitignore` in this case

**Comment by GeekPress** [comment]
If we edit the file, the git issue will still remain, isn't it?

**Comment by GeekPress** [comment]
@hellofromtonya Can you plan to talk about the best approach on this issue with the dev team?

**Comment by hellofromtonya** [comment]
@GeekPress on it. Thanks for pinging me.

@Tabrisrp We can use [`pre-commit` git hook](https://www.atlassian.com/git/tutorials/git-hooks) to do tasks such as:

- run `phpcs`
- check if any files shouldn't be committed
- etc.

Specifically for this task, we can use the 2nd option. How?

1. Add a tag in the file such as `!nocommit`
2. Add [code like this](https://gist.github.com/arturadib/97a17752301ee796f9a0) to bail out of the commit and tell us that we have a problem

## How do we share it with the team and any contributors?

We can add a `.githooks` folder into the repo with the hook scripts. 

And then add instructions for each dev to configure locally:

- If using git 2.9+:
```
git config core.hooksPath .githooks
```

- If using git < 2.9, [we'll have to copy or symlink to the scripts](https://www.smashingmagazine.com/2019/12/git-hooks-team-development-workflow/#sharing-hooks).

**Comment by Tabrisrp** [comment]
2 questions:
- @GeekPress If we modify the file, is it still ok on the website side when it adds the license data for each user in it?
- @hellofromtonya Can you confirm this doesn't prevent the `licence-data.php` file from being part of the git repository? It would be there, but not modifiable

How about using the file locking system available in git-lfs? https://github.com/git-lfs/git-lfs/wiki/File-Locking

Github supports this extension

**Comment by hellofromtonya** [comment]
>Can you confirm this doesn't prevent the licence-data.php file from being part of the git repository? It would be there, but not modifiable.

It would yes. It prevents us from committing a `delete` of the file.

>How about using the file locking system available in git-lfs? https://github.com/git-lfs/git-lfs/wiki/File-Locking

I haven't used this one. But let's try it and see what happens. We want it to be as easy as possible for devs when working locally. The idea is to prevent deletion of the file in a commit after WPR has deleted it when running in a localhost.

**Comment by GeekPress** [comment]
@Tabrisrp @hellofromtonya Do you have all info to be able to groom this one?

**Comment by hellofromtonya** [comment]
@GeekPress This one is a DevOps issue. I'll move it to the DevOps backlog in Asana.

**Comment by hellofromtonya** [comment]
Closing this issue as it is now tracked in the [DevOps Backlog in WP Media's Asana](https://app.asana.com/0/1178016458578137/1180109945063873/f).

**Comment by iCaspar** [comment]
Temporary workaround until devops gets to the script:
`git update-index --assume-unchanged licence-data.php`
If the file in the repo changes you'll need to undo using:
`git update-index --no-assume-unchanged licence-data.php`

**Comment by nicomollet** [comment]
@Tabrisrp Is this issue still tracked somewhere?
The DevOps backlog is still a thing?

I experienced my self the issue on RocketCDN website.
1. Downloading WPR from the WPR website account for contact@rocketcdn.me
2. Install manually on the website
3. The file is deleted

So when pushing on production, the licence won't be added.
