### ISSUE TITLE
Create dedicated query string to bypass WP Rocket

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2576]
Support requires a way to bypass WP Rocket, for debugging and comparison purposes. 
[Since we are now going to again start mixing up which features are applied on uncached pages,](https://github.com/wp-media/wp-rocket/issues/2543#issuecomment-618380044) let's create a dedicated query string that we know will bypass ALL of WP Rocket's features. 

We are aware that some have to be applied on uncached pages for technical reasons:
https://docs.wp-rocket.me/article/1285-bypass-wp-rockets-caching-and-optimizations

But besides those, the new query string will turn off everything else including anything that has been chosen to be applied on an uncached page. 

Secondarily, if possible, a dedicated query string that bypasses _only_ RocketCDN would be valuable when doing debugging on that specific feature. (props @camilamadronero )

**Comment by GeekPress** [comment]
Before to be put this into « grooming », we need to decide about the query string names.

We used to use `nocache` in some of our saved reply, what about using this one?

> Secondarily, if possible, a dedicated query string that bypasses only RocketCDN would be valuable when doing debugging on that specific feature. (props @camilamadronero )

It won't be possible to do that.

Why?
We will need to have 2 caching files:
- one with all optimizations, included RocketCDN
- another one with all optimizations, but excluded RocketCDN

**Comment by webtrainingwheels** [comment]
Yes, let's keep `nocache` since it's what we already use and we also have it as [an example in our doc](https://docs.wp-rocket.me/article/1285-bypass-wp-rockets-caching-and-optimizations)

This choice has also been validated by @daniella-wp-rocket

**Comment by Tabrisrp** [comment]
**Scope a solution** ✅ 
This was discussed with the dev team, and to make sure we don't conflict with anyone else, we proposed to use `nowprocket` as the query string to use. We believe `nocache` _might_ be used somewhere, even if very unlikely.

As for implementation, we will add a new function `rocket_noptimize()` to the API, which will check if the query string is set, and return true if yes.

We will then use this function everywhere where it's needed to prevent all optimizations when the query string is used:
- Conversion of dynamic CSS/JS files to static files
- Disable Emoji
- Disable WordPress embeds
- Heartbeat settings
- Preload fonts

**Estimate the effort** ✅ 
I'm estimating this to be an `[S]` task, but it might become a bit more depending on the tests to write for some of the code that doesn't have it yet in the above optimizations.
