### ISSUE TITLE
Add a notice to disable ProPhoto cache option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2577]
**Is your feature request related to a problem? Please describe.**
ProPhoto has a page cache option which conflict with our caching system.

![ProPhoton options page](https://p195.p4.n0.cdn.getcloudapp.com/items/yAu2Y2oN/Capture%20d%E2%80%99e%CC%81cran%202020-04-14%20a%CC%80%2022.40.28.png?v=966bb880baa678ca83abc6190ab15b27)

**Describe the solution you'd like**
We could display a notice to warn our user about the conflict with ProPhoto page cache option and ask them to disable it.

Endurance Cache is doing that. When it detects WP Rocket, a notice is displayed to the user to ask them to set Endurance Cache to level 0 to avoid conflicts with WP Rocket.

**Additional context**
ProPhoto website: https://pro.photo/
We will need to ask a test license.

**Comment by GeekPress** [comment]
@arunbasillal @webtrainingwheels If you have some suggestions for the copywriting :)

**Comment by arunbasillal** [comment]
Thinking out loud: 

- What if we disable our page cache when page cache is enabled in ProPhoto?
- How about we contact the developers of ProPhoto and disable the option for their users when they detect WP Rocket? 

Either of this could be a more user friendly solution than a notice.

**Comment by webtrainingwheels** [comment]
>How about we contact the developers of ProPhoto and disable the option for their users when they detect WP Rocket?

I prefer that option to the other ;)

But failing that, as @Tabrisrp has suggested a few times, maybe we should start moving such notices to the Site Health tool. Many users won't find it immediately for themselves, but at least when they contact support we can tell them to check it, which could resolve an issue without us having to log in.

**Comment by arunbasillal** [comment]
Site health is now a widget in WordPress dashboard since WordPress 5.4 (I think), so this must be a good spot to point out things to customers. 

For this one, let's contact ProPhoto first and see if auto-compatibility is possible. That would be most ideal.

**Comment by webtrainingwheels** [comment]
@GeekPress in your screenshot there's also a LazyLoad option - does this create a conflict for us that we also need to handle?

**Comment by webtrainingwheels** [comment]
I contacted them through their website contact form.

**Comment by GeekPress** [comment]
Indeed, if the issue could be directly fixed by the theme directly it will be better.

But what did we expect from them? Display a notice? Auto-deactivate the option?

>  in your screenshot there's also a LazyLoad option - does this create a conflict for us that we also need to handle?
Good question. I didn't take the opportunity to check. Yes we should also do something for LazyLoad to avoid any conflicts.

**Comment by arunbasillal** [comment]
> what did we expect from them? Display a notice? Auto-deactivate the option? Ot something else

The most ideal would be to disable the option when WP Rocket is detected. There is no need for two caches and two caches to sync and all that drama. 

> Good question. I didn't take the opportunity to check. Yes we should also do something for LazyLoad to avoid any conflicts.

@GeekPress Do we have access to the theme to test?

**Comment by GeekPress** [comment]
@arunbasillal Nope, I don't have access anymore to the customer website. We can still ask for a test license to ProPhoto or at least buying one.

**Comment by webtrainingwheels** [comment]
fyi @GeekPress I asked them for a test license.

**Comment by GeekPress** [comment]
@webtrainingwheels Thanks for the update =)

**Comment by GeekPress** [comment]
@webtrainingwheels Do you have any news about the test license?

**Comment by webtrainingwheels** [comment]
@GeekPress not yet - I just sent a follow up

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
