### ISSUE TITLE
Delay 3rd Party Script

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2581]
# Delay Third Party JavaScript Execution

## What are we proposing to do?

With this feature WP Rocket will delay the execution of third party JavaScript files. This will essentially be a LazyLoad for third party scripts. 

## Why are we doing this?

Third party scripts are often performance bottlenecks. On many websites, third party scripts are used for non-critical features. With this feature, WP Rocket will delay the download and execution of third party scripts, thus letting the browser prioritize downloading and executing the local JS first.

As a side effect, delaying the execution of third party JavaScript will help improve PageSpeed score and speed test results.  

## Benchmark Tests

For these tests, Flying scripts plugin was used. The delayed script was manually excluded from the combined JS file. 

<p></p>

**Comparison with a Twitter Widget**

Page: <http://mega.wp-rocket.me/delay-js-execution/>

GTmetrix: <https://gtmetrix.com/compare/NEYtJjGK/BvfecQQE>

PageSpeed:

![](https://lh6.googleusercontent.com/Q28ZA3vFGACAQ5IDCGmhOLLShC0DCrI3NBjgqj4Tn_fuatXjpmOc47a2-VMdLEak2hfPc1Sy7boPyq8vEwxIyrKrnC-vKpYYvWK9ENvCvdHafAWS4PfFMl1ZsQreyV4tipT72Kv8)

Source: <https://jmp.sh/yvh7L9e>

![](https://lh6.googleusercontent.com/VVX-_dM-7Am8zU9_4tEFmiN90MXUHrCAcd5gHRSIze6BY-iFc12YE5ltx7BZM6leKS2-4xizuqtJ485Ahmks19TDdn1atxHrL7BYZWCguqHwXe9kcss3CEEzyCzVIcUN0OhyQiMW)

Source: <https://jmp.sh/Hi1E6go>  

**Comparison when using Facebook page plugin**

Page: <http://mega.wp-rocket.me/delay-js-execution-fb/>

GTmetrix: <https://gtmetrix.com/compare/aohl7DfR/wa5FnPC2>

PageSpeed:

![](https://lh4.googleusercontent.com/4v2r250Js2R3nJhwja4kBibzpq6GVeMiTIQYT6kXQK9XvE0CORoq8UAeYrW4EGI7qYTUFx272Z29uGhjnN93CxqXkFqCFn3g-QFGbQKAAwUIquRQwN_hVpBRESUz0lhacddtQ1e_)

Source: <https://jmp.sh/NN988dp>

![](https://lh3.googleusercontent.com/tJTID2St7F4lB1N_8bQz3-8JFee3uMHdi3bCMo_T8lsyO3FoyJiRjA8KG_gxTnKFaoX1GrhZQCQ1wxep2T11dsU3YZ8CCEWcP4ALWeCyEylV5sJ1YnVsVk10jreDBKoCOc4BD8vX)

Source: <https://jmp.sh/ShorGyb>  

**Things to note:** 

- There is a clear impact on page size and fully loaded time. 

- PageSpeed recommendations like JavaScript execution time, main-thread work are satisfied. 

## User expectations and experience. How will we do this feature?

Five approaches were considered for the implementation of this feature. 

1. An option in the File Optimization tab which delays all external third party JS by default. A text area will follow this to add exclusions. 

2. An option in File Optimization tab with a text area that only delays the files selected by the user. 

3. A Rocket add-on that lists all third party JS that we can detect and lets the user pick which ones to exclude. 

4. A Rocket add-on that lists the third party JS that we have handpicked and lets users choose the ones they want to exclude. 

5. An option in the File Optimization tab which when enabled delays only specific JS scripts handpicked by us. This list can be curated based on user feedback and our research. 

<p></p>

**Things to consider:** 

- Blindly excluding every third party JS is risky. If there is inline JS that needs functions defined in the external file, it will lead to errors. ([Test](https://youtu.be/gWPr6JUt5qw)) (happens with Flying Scripts and Swift Performance Lite)

- Putting the weight of choosing the files to exclude on the customer (implementation #2) is the safest and the easiest to , but goes against our “easy to use” philosophy. 

- The add-on approach makes the feature hidden from view and needs a lot of user interaction. Many users who don't understand the feature will simply enable all scripts. 

- The add-on based approach needs a lot of design and development time which can be saved for a future iteration of feature if needed.   

**The winning approach (for the first iteration):** 

- The UI option to be placed in the File Optimization tab. It will be a simple checkbox named: “Delay third party JavaScript execution”. 

- We will pre-select the JS files that can be safely delayed. Sometimes it will be a script and related inline JS. 

- On enabling the option, if the website contains any of the selected scripts, they will be delayed. 

- There will be no text area in the UI to exclude or include any scripts. 

- Instead we can include a filter with third party scripts can be either added or removed. 

- When a file is selected for delayed loading, the file and any inline JS will be excluded from the combined JS file (right now third party JS is combined into the combined JS file). 

- This approach might be more work for us (to hand pick the files), but will be the best experience for our users. Since we will do rigorous testing during the selection of the files, support load should also be limited to edge cases. 

<p></p>

**UI proposal**

- Option name: **Delay third-party JavaScript execution**

- Option description: **Improves initial loading time by delaying the loading of specific third-party JavaScript files.** 

- Option location: **WP Rocket > File Optimization tab > after “Load JavaScript deferred”**

![](https://lh6.googleusercontent.com/s0BQT8PlHiDJMQyiunciIUCVheS6rMWaunUpSnm1sXx9mT6TGzKHwzWy7ktJma8aJSRr16OmHIa5NGdHwEUtcYJ--fQHKpqDHdtpPEj1h_jAOfHc9Xi9f2KYRIvdw5VbaGWcwPHX)

## Third Party JavaScript Suggestions

Please refer this doc for suggestions: 

- <https://www.notion.so/wpmedia/95155dc2f51f47fd94f3c942096a02d7?v=970b622c689843f9b2aa5235bf394420>

## Technical Specs

The following is meant to be a starting point for the dev team found during research. 

<p></p>

**A good starting point is Flying Scripts WordPress plugin -** [**https://wordpress.org/plugins/flying-scripts/**](https://wordpress.org/plugins/flying-scripts/)

<p></p>

This plugin does the following conversion for scripts and replaces them during runtime. Similar to what we do for LazyLoad.  

```
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0"></script>
```

<p></p>

to

```
<script async defer crossorigin="anonymous" data-type="lazy" data-src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0"></script>
```

<p></p>

**And for inline JS:**

<p></p>

```
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "<https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";>
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
```

<p></p>

To  

```
<script data-type="lazy" data-src="data:text/javascript;base64,KGZ1bmN0aW9uKGQsIHMsIGlkKSB7DQogICAgdmFyIGpzLCBmanMgPSBkLmdldEVsZW1lbnRzQnlUYWdOYW1lKHMpWzBdOw0KICAgIGlmIChkLmdldEVsZW1lbnRCeUlkKGlkKSkgcmV0dXJuOw0KICAgIGpzID0gZC5jcmVhdGVFbGVtZW50KHMpOyBqcy5pZCA9IGlkOw0KICAgIGpzLnNyYyA9ICJodHRwczovL2Nvbm5lY3QuZmFjZWJvb2submV0L2VuX1VTL3Nkay5qcyN4ZmJtbD0xJnZlcnNpb249djIuNSI7DQogICAgZmpzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKGpzLCBmanMpOw0KICB9KGRvY3VtZW50LCAnc2NyaXB0JywgJ2ZhY2Vib29rLWpzc2RrJykpOw=="></script>
```

~~Note: Flying Scripts adds a delay (default 5 seconds) or waits for user interaction (mouse movement, scroll etc) with the website, whichever is first. No user is going to be idle after loading the website. The time delay is useless and let’s NOT do it. Load the delayed script at the first interaction.~~

^ We need to add a similar delay, let's do a delay of 3 seconds. So the scripts will be loaded after 3 seconds or first user interaction, *whichever is earlier*. 

^ Reason: During investigation Jonathan noticed that GTMetrx records fully loaded time as `Fully loaded time - is the point after the Onload event fires and there has been no network activity for 2 seconds.` ([source](https://gtmetrix.com/faq.html#faq-fully-loaded-vs-onload)). So any delay less than 2 seconds is not recorded in the report. 

( Another method of handling inline JS is described here: <https://stackoverflow.com/questions/8946715/lazy-loading-javascript-and-inline-javascript> )

<p></p>

Swift performance Lite has this feature and it handles it a bit differently. The third party JS is included and delayed from within in the combined JS file. 

- To test this, go to Swift Performance Lite > Settings tab

- Switch to advanced view - <https://jmp.sh/4X4denu>

- Under optimization > scripts. Enable “Merge Scripts” - <https://jmp.sh/1s5JpfK>

- Add a keyword from the script to LazyLoad - <https://jmp.sh/tXmasBj>

<p></p>

**An idea: We could store the list of third party files to exclude at our end (wp-rocket.me)**. And have the plugin ping our server for the list

- A basic list could be included in the plugin

- The plugin pings our server on a schedule (once a week? Once a day?).

- wp-rocket.me sends a json response. 

- The local list is updated on the website. 

- When the cache is cleared and rebuilt, new changes are applied. 

## Risks

Risk of this feature is of two kinds: 

- First is the risk when the feature is first released. This is very minimal as the feature will have to be manually enabled by a user. Also the third party scripts that we are delayed are hand picked and tested by us. We should be okay. 

- The second risk is when we keep adding third party scripts to our list. When a user updates WP Rocket and if the user has already enabled “Delay third party JavaScript execution”, the new scripts are automatically applied to the website. This could look risky. But since we are hand picking these scripts (goes through all our QA and live testing) and with staggered release, the risk should be managed reasonably. 

<p></p>

We could also show customers a notice and seek their manual approval before applying delay for more third party scripts to handle this. Something like:   

*> New 3rd Script to delay are available: Tidio Chat, Twitter Ads, XXXX, etc...*

*> To optimize these scripts, please confirm by clicking here.*

## Testing

**Acceptance Criteria**

- On a website with some of the third party scripts that we exclude

- In the File Optimization tab, enable only “Delay third-party JavaScript execution”. 

- The third party file must be loaded on first interaction with the website (scroll, mouse movement, etc). 

- Enable minification and combination of JS. The third party file should not be combined and should still be loaded with a delay. 

What if (Lucy):

- What's the expectation when the Deferred JS option is active?

- What's the expectation when the Facebook Add-on is active?

- What's the expectation when the Google tracking add-on is active? (if we're touching any analytics stuff?)

- Are there any 3rd party compatibilities affected by this? For example, will this be compatible with AMP and if not, will our AMP compat automatically remove it, or does this have to be considered and built into the feature?

## Documentation and Translations

- A new document will be needed. 

- Filter to add or remove 3rd party script

- Troubleshooting part needs details on how to exclude specific scripts.

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4200192

**Comment by Tabrisrp** [comment]
Question: option applied on cached pages only, or cached + uncached?

**Comment by arunbasillal** [comment]
> Question: option applied on cached pages only, or cached + uncached?

During our last call Jonathan said that we could add this on both cached and uncached pages.

**Comment by arunbasillal** [comment]
A small change was added and updated in the main card:

~~Note: Flying Scripts adds a delay (default 5 seconds) or waits for user interaction (mouse movement, scroll etc) with the website, whichever is first. No user is going to be idle after loading the website. The time delay is useless and let’s NOT do it. Load the delayed script at the first interaction.~~

^ We need to add a similar delay, let's do a delay of 3 seconds. So the scripts will be loaded after 3 seconds or first user interaction, *whichever is earlier*. 

^ Reason: During investigation Jonathan noticed that GTMetrx records fully loaded time as `Fully loaded time - is the point after the Onload event fires and there has been no network activity for 2 seconds.` ([source](https://gtmetrix.com/faq.html#faq-fully-loaded-vs-onload)). So any delay less than 2 seconds is not recorded in the report.

**Comment by GeekPress** [comment]
I removed this epic from 3.6, it's going to be a new plan for 3.7 with a better way to defer external and internal files to get the best performance.

**Comment by GeekPress** [comment]
I'm closing it as we should do this in another way and for all JS files.

**Comment by gijo-varghese** [comment]
@arunbasillal 

Regarding: https://www.youtube.com/watch?v=gWPr6JUt5qw

The "multiply.js" keyword is not inside the inline script. So you've to use something like "multiply" instead of "multiply.js" to make it work.

**Comment by arunbasillal** [comment]
@gijo-varghese Thanks for your input. Of course, that makes sense. 
That test was to point out that if "only" the file is delayed and not the inline JS, it will lead to errors. This was in reference to "Blindly excluding every third party JS".
