### ISSUE TITLE
Check for `background` property

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2588]
To lazyload background images, we are looking for the` background-image` property:
https://github.com/wp-media/rocket-lazyload-common/blob/1ea0cf2ae5d302a0214e05176c1dda321b1d6690/src/Image.php#L65

But in some cases, a shorthand version of the `background` property can be used like that by [Related Posts Thumbnails Plugin for WordPress](https://wordpress.org/plugins/related-posts-thumbnails/) to display thumbnails:
`<div class="relpost-block-single-image" alt="Fashion Illustrator Bella" style="background: transparent url(https://lemontrend.com/vz01pro1/wp-content/uploads/2019/12/fashion-illustrator-bella-featured-150x150.jpg) no-repeat scroll 0% 0%; width: 150px; height: 150px;"></div>`

Which is correct:
https://developer.mozilla.org/en-US/docs/Web/CSS/background

We should also checking for that.

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
https://github.com/wp-media/rocket-lazyload-common/blob/fde493535ca389882484327af32c99c839d2527f/src/Image.php#L63

**Scope a solution** ✅ 
Preg_match should accomodate both `background-image` and `background` .

**Effort** ✅ 
Effort `[S]`

**Comment by Tabrisrp** [comment]
Is it enough to change the RegEx to match both `background` and `background-image`?

Since we want to extract only the URL, we will need more processing in the case of `background` to preserve the other properties set in it.

Currently we're removing everything inside the `style` attribute when there is a match, which will not work with `background`.

**Comment by crystinutzaa** [comment]
Ah. Good catch @Tabrisrp . What if we modify that regex to grab everything after :
`background: or background-image:` till the end ';'. Then grab the url  and simply keep the format and use the data which is needed.

**Comment by Tabrisrp** [comment]
I agree, something like this: https://regex101.com/r/oDwynV/1

Then we can have another RegEx to extract the `url()` part. That also means for `background` that there might not be an `url()`, so it's an additional check to do.

And after, depending on the case, we will either need to:
- Remove the whole property if it's `background-image`
- Only remove the `url()` part if it's `background`

**Comment by GeekPress** [comment]
@arunbasillal I updated the priority to `high`.

Why?
This could have an important impact on Core Web Vitals for websites containing a huge image background. I'm seeing a ton of websites with this configuration.

**Comment by arunbasillal** [comment]
@engahmeds3ed + @iCaspar I have added this to the current sprint based on the Feedback from Jonathan above. No pressure of course, if time allows. If not, we can plan for a future sprint.

**Comment by Tabrisrp** [comment]
The estimated effort needs to be revised following what was found during QA of https://github.com/wp-media/wp-rocket/pull/3451

Support for multi-images background needs to be added, which increases the complexity of the changes required.

**Comment by iCaspar** [comment]
From @MadMaxInfinity -- @see #3509:

https://github.com/wp-media/wp-rocket/blob/df26acdfbe015d056fc442cfbf28734f9635aa9f/inc/Dependencies/RocketLazyload/Image.php#L65
If I make no mistake, this regexp is ending with `\))\s*;?` but this way no background-images having fallback values or `!important` directive are not matched. Moreover this doesn’t take into account multiple images background.
Samples [can be found here](https://css-tricks.com/almanac/properties/b/background-image/#setting-a-fallback-color).

Maybe something like `'#background-image\s*:\s*(?<attr>\s*url\s*\((?<url>[^)]+)\))[^;]*;?#is'` could do?
( Replaced ending `\s*;?` with `[^;]*;?` )

_Just something I found while searching why my SVG background was not loaded in CDN and check if it aws related to lazyloading..._

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1616037038/291051

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.
