### ISSUE TITLE
Add troubleshooting info to API key page 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#259]
When customers get the greyed out API key page on activation, let's add some helpful information. e.g.
"If you're seeing this message it means your server is blocking communication with ours. 
Please whitelist the following IP addresses"
etc etc

**Comment by Tabrisrp** [comment]
Old ticket about it: https://github.com/wp-media/wp-rocket/issues/44

We clearly need to improve this, showing what needs to be done is a great idea 👍
