### ISSUE TITLE
Add the license information to the Beacon

### ISSUE THREAD

**Issue by daniella-wp-rocket** [wp-media/wp-rocket#2595]
**Describe the solution you'd like**
For the Beacon to bring the license information to HelpScout and be added into the "License" custom field based on what the customer has.

![image](https://user-images.githubusercontent.com/64215408/80641406-6ff7ed00-8a2a-11ea-9e24-a234e03edd03.png)

**Comment by Tabrisrp** [comment]
**Scope a solution** ✅ 
- In Helpscout, enable "Show custom fields", and select the "License" field
- In WP Rocket, `Beacon` class, add prefilling for the License custom field using [schema from this doc](https://developer.helpscout.com/beacon-2/web/javascript-api/#pre-filling-custom-fields)
- Add a new method to get the data from our stored `customer_data` transient, and insert it into the `prefill` property, by matching it with the field ID in Helpscout. If no data is available, default to `nulled`.

**Effort** ✅ 
Effort `[S]`

**Comment by GeekPress** [comment]
> In Helpscout, enable "Show custom fields", and select the "License" field

@Tabrisrp Is it mandatory to show the field in the form?

The idea was to set the value in background for the customer, without giving the possibility to change the value.

**Comment by Tabrisrp** [comment]
From my testing, when you prefill the custom field, it's not shown to the user. But the "show custom fields" option still needs to be enabled on HS side for the data to be transmitted.
