### ISSUE TITLE
Mobile caching hard to understand

### ISSUE THREAD

**Issue by worldsdream** [wp-media/wp-rocket#2605]
The mobile caching is hard to understand for users, including me.
Is it possible to rewrite the text in the plugin?

In this blog post section https://wp-rocket.me/blog/wp-rocket-3-5/ is being told:

_You won’t see any explicit changes in the plugin interface, but the preloading from mobile will work when the three following settings are enabled:_
   
   _Enable caching for mobile devices, located on the Cache tab
    Separate cache files for mobile devices, also situated on the Cache tab
    Activate Preloading, located on the Preload tab_

Now that's great, right?

In the plugin it's showing: https://i.imgur.com/OxYuER0.png

_Seperate cache files for mobile devices
Most modern themes are responsive and should work without a seperate cache. Enable this only if you have a dedicated mobile theme or plugin._

Now is my question, if we like to enable mobile preloading, do we have to enable the checkbox _Seperate cache files for mobile devices_? I do have a modern theme and it's responsive. This is why I don't enable it. But then mobile preloading will not work, the awesome introduction in WP Rocket 3.5.

I guess, if I am reading it correct. We need to enable the _Seperate cache files for mobile devices_.
But the text in the plugin needs to be rewritten.

Please let me and other know what would be best. Maybe we don't need preloading?

**Comment by Tabrisrp** [comment]
If your theme is responsive, you don't need to enable the option. The preloaded cache will be used for all devices accessing your site, which is fine since your site is responsive and don't need to have different versions of the cache file.

**Comment by worldsdream** [comment]
Thank you. That cleared it for me. I hope that others don't ask this question, as this one was not easy to understand.
