### ISSUE TITLE
CPCSS for mobile: tools part (2/4)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2611]
Sub-task for epic #2378 

### views/settings/page-sections/tools.php
- [x] Add `do_action( 'rocket_settings_tools_content' );` to the view

### views/cpcss
- [x] Add a `activate-cpcss-mobile.php` view file, containing a description + button to enable the CPCSS for mobile

### inc/Engine/CriticalPath/AdminSubscriber.php
- [x] Add `display_cpcss_mobile_section()` method as a callback for `rocket_settings_tools_content` to display the "active CPCSS for mobile" view when needed (Optimize CSS delivery + specific cache for mobile options enabled)
- [x] Add `enable_cpcss_mobile()` method AJAX callback to enable the `async_css_mobile` option via the button in the view
- [x] Add tests

**Comment by Tabrisrp** [comment]
I'm blocking this issue until the discussion happening in #2378 about it comes to a conclusion.

**Comment by Tabrisrp** [comment]
Unblocking as per https://github.com/wp-media/wp-rocket/issues/2378#issuecomment-629495866

**Comment by hellofromtonya** [comment]
This one is now unblocked.
