### ISSUE TITLE
CPCSS for mobile: generation part (3/4)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2612]
Sub-task for epic #2378 

### inc/Engine/CriticalCSSSubscriber.php
- [x] Update `generate_critical_css_on_activation()` to also trigger a generation when "Optimize CSS delivery" is enabled, "specific cache for mobile" is enabled and "async_css_mobile" = `1`
- [x] Update tests

### inc/Engine/CriticalCSS.php
- [x] Update `set_items()` to also add mobile version of each item if the "specific cache for mobile" option is enabled and "async_css_mobile"  = `1`
- [x] Add tests

### inc/Engine/CriticalCSSGeneration.php
- [x] Update `task()`to use the new handshake with the API introduced in #2512. Re-queue the task when it's still in progress instead of using a `while` loop and `sleep`. Also make sure the `mobile` parameter is passed along the POST request when needed
- [x] Add tests

### CPCSS for specific posts
- [x] Generate the mobile version when needed along the normal version
- [x] Update tests

**Comment by hellofromtonya** [comment]
This user story / sub-task is currently blocked by:

- [ ] PR #2622
- [ ] PR #2639
