### ISSUE TITLE
i'm getting some errors while activating the plugin

### ISSUE THREAD

**Issue by ashish168527** [wp-media/wp-rocket#2614]
Hi there,
I downloaded the latest release from here https://github.com/wp-media/wp-rocket/releases
and uploaded to a Wordpress site when i'm trying to activate it's not activating it's throwing an error how can I fix it I just want to try it can you guys please help me out?

`Fatal error: Uncaught Error: Class 'WP_Rocket\Subscriber\Plugin\Capabilities_Subscriber' not found in /home/hn347rhc/example.com/wp-content/plugins/wp-rocket-3.5.4/inc/main.php:177 Stack trace: #0 /home/hn347rhc/example.com/wp-includes/class-wp-hook.php(287): rocket_activation('') #1 /home/hn347rhc/example.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /home/hn347rhc/example.com/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/hn347rhc/example.com/wp-admin/plugins.php(179): do_action('activate_wp-roc...') #4 {main} thrown in /home/example.com/wp-content/plugins/wp-rocket-3.5.4/inc/main.php on line 177`

how can I activate it and try it?

**Comment by ashish168527** [comment]
@Tabrisrp can you guys please help me to try this plugin I want to know what should I do after downloading the latest release from here https://github.com/wp-media/wp-rocket/releases and uploading to Wordpress plugin? in the readme it says that You can use the composer to install the plugin as a dependency: "composer require wp-media/wp-rocket" but I also tried working from other website sources but they don't require this composer step I just downloaded to WordPress plugin and uploaded and activated and that worked!?  

please tell me what should I do in order to try this plugin after downloading and uploading the latest release to WordPress plugin of the WordPress site?

**Comment by girlie** [comment]
@ashish168527 We don't provide support here on GitHub, it's only used for confirmed bugs, enhancements, and new features.

Support requests can be submitted from WP Rocket's settings page in the WordPress admin, or from our website: https://wp-rocket.me/support/
