### ISSUE TITLE
Once the page is loaded, remove the CPCSS style tag via JS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2635]
**Is your feature request related to a problem? Please describe.**
We don't remove our CPCSS once the page is loaded. It can cause layout issues if some JS scripts are added or updated CSS classes after applying the CPCSS.

**Describe the solution you'd like**
We could remove the CPCSS style tag once the page is fully loaded.

**Additional context**
We already tried to implement this:
https://github.com/wp-media/wp-rocket/pull/1172/files

We decided to not implement because it cause an issue for one customer during the beta test, even if it helped to fix issues for more people. We will like to implement it as it should fix more issues than it should create.

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
I can confirm that CPCSS is not removed from my localhost.

**Scope a solution** ✅ 
The solution wil
https://developer.mozilla.org/en-US/docs/Web/API/Document/readyStatel be to add an event listener and check when readyState = complete to remove the CPCSS code.
And for IE and Opera we should use:
attachEvent on window load. 

**Effort** ✅ 
Effort `[S]`
