### ISSUE TITLE
Style changes with Elementor are not available when combining CSS files

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2654]
Elementor, by default, creates a separate file for each post, containing the post's style customizations.

Those are saved in `/wp-content/uploads/Elementor/css/` like this:
`/wp-content/uploads/elementor/css/post-134.css`

where the number represents the post ID. Every time the user changes the styling and saves the post, the CSS file is deleted and recreated.

When CSS combination is enabled, the CSS changes someone makes on a page will not be reflected, until the `cache/min` folder is cleared using the admin bar menu item.

If only CSS minification is enabled, there isn't any issue.

**Steps to reproduce**

1. Enable CSS combination.
2. Install the [Elementor](https://wordpress.org/plugins/elementor/) plugin and create a new post.
3. Add some content, edit the styling and save the document.
4. Visit the page to check your changes.
5. Edit the post again to change the styling.
6. Clear the post's cache and check the styling. It won't have the applied changes.
7. Clear the cache from the admin bar menu. The changes will be visible.

**Expected behavior**

The changes should be immediately reflected when the post's cache is cleared.

**Related ticket**
https://secure.helpscout.net/conversation/1165116617/165327?folderId=2135277

**Comment by Tabrisrp** [comment]
Did Elementor change anything on their side?

We already have 3 hooks from them in our compatibility file: https://github.com/wp-media/wp-rocket/blob/c7a020448d6639ca3cb4cddf72195f9d9c18fbec/inc/classes/subscriber/third-party/plugins/PageBuilder/class-elementor-subscriber.php#L50

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
I cannot reproduce on my localhost. The folder /cache/min cleans just fine the css file.

What I noticed is that this operation seems slow. Took around 5-10 seconds on my local to clean everything. 

I checked also the code in Elementors and nothing seems to be changed and this hook is triggered just fine in WP Rocket:
`'elementor/core/files/clear_cache'`

@vmanthos , @Tabrisrp I cannot recreate this issue.

**Comment by vmanthos** [comment]
This was my bad, I apologize.

Everything is working fine.

In my testing environment, the theme's styling messed up the changes I was looking into.
At the same time, there was a "lag" in deleting combined files, which made it seem like they weren't deleted, when I was checking them.
