### ISSUE TITLE
Add cURL test and better UI feedback for Cloudflare feature

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#266]
Without cURL the Cloudflare settings are showing that the API key is invalid, even though it may be valid. After installing cURL it works. 

We should add a cURL check and more fine-tuned UI feedback for the Cloudflare feature.

**Comment by arunbasillal** [comment]
Not sure in which version we did this, but we currently check for cURL and provide a UI notice if cURL isn't installed.

https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/functions/cloudflare.php#L18

Thanks @crystinutzaa for pointing this out.
