### ISSUE TITLE
Include <a> tags when applying LazyLoad to background images 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2660]
Currently LazyLoad isn't applied on background images within `<a>` tags

https://secure.helpscout.net/conversation/1166046824/165537?folderId=377611
https://secure.helpscout.net/conversation/1000291510/130477/

**Comment by hellofromtonya** [comment]
https://github.com/wp-media/rocket-lazyload-common/pull/72
