### ISSUE TITLE
[WIP] PHP Warning in admin.php related to license validation

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2661]
[Under investigation]

We have a couple of tickets reporting this PHP warning and having license validation issues: 
`Warning: count(): Parameter must be an array or an object that implements Countable in //wp-content/plugins/wp-rocket/inc/functions/admin.php on line 23`
>There seems to be an issue validating your license. Please see the error message below. 

Previous cases:

- https://secure.helpscout.net/conversation/1162149079/164529/
- https://secure.helpscout.net/conversation/1163650645/164898/

I do not have specifics on how to reproduce yet since I discovered these cases retroactively.

Have requested access here to see if it's the same error: 
https://secure.helpscout.net/conversation/1166566106/165669?folderId=377611 (license fields are blank)
https://secure.helpscout.net/conversation/1166932605/165739?folderId=377611 (license fields are blank)

**Comment by JohnTorvik** [comment]
Related: https://secure.helpscout.net/conversation/1423906536/238966/

**Comment by vmanthos** [comment]
This is a duplicate of #3449, which has more info about this.

@GeekPress I'll add the info there.

**Comment by piotrbak** [comment]
@webtrainingwheels I think we can close this one too, right?

**Comment by webtrainingwheels** [comment]
@piotrbak yes, since it seems to be a duplicate
