### ISSUE TITLE
Improve compatibility with Pagely

### ISSUE THREAD

**Issue by JohnTorvik** [wp-media/wp-rocket#2664]
WP Rocket is compatible with Pagely, but we received a refund request where the customer pointed:

- Pagely's caching system did not play nicely with WP Rocket. I then installed the WP Rocket disable caching add-on as well and still was having issues with Pagely

- WP Rocket does several thousand cache purge requests, impacting the server performance.

Ticket link: https://secure.helpscout.net/conversation/1166399003/165639/

**Comment by GeekPress** [comment]
Another related ticket (and refund):
https://secure.helpscout.net/conversation/1114214010/152669/

**Comment by GeekPress** [comment]
@arunbasillal Could you do some investigation about that? 

I don't know if we have a Pagely test account. Let me know if not.

**Comment by ScottTravisHartley** [comment]
#1759 is relevant to this as well

**Comment by GeekPress** [comment]
@ScottTravisHartley Thanks a lot for the reminder :)

@wp-media/wprocketplugin Do you have any idea?

**Comment by hellofromtonya** [comment]
@Tabrisrp Can you look into this and provide feedback? Thank you.

**Comment by webtrainingwheels** [comment]
FYI we have a testing account with Pagely now, [more info here](https://wp-media.slack.com/archives/G8L4EE8N9/p1595963468028200).
They are also doing some tests from their side.

**Comment by klong-pagely** [comment]
Hello,

There is a hook for pagely_cache_purge_after to run a rocket_clean_domain. Then on rocket_clean_domain there is a hook for after_rocket_clean_domain to run a pagely cache purge.

The natural result of this is an infinite loop until the process is killed.

I created a simple pull request with a solution which sets a global variable that stops the purge after a single cycle.  See the pull request above for details.

Please take a look.

Thanks,
Keelan

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1303211209/200535/

**Comment by jorgemartine00** [comment]
Related ticket - https://secure.helpscout.net/conversation/1314607610/204012
