### ISSUE TITLE
Expired cache preload doesn't fetch the correct URLs

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2665]
**Describe the bug**
In 3.5.5 version we fixed the problem with expired cache preload for WPML. In this fix, we introduced another problem. When `$data['home_url']` doesn't contain `/`:
https://github.com/wp-media/wp-rocket/blob/c7a020448d6639ca3cb4cddf72195f9d9c18fbec/inc/Engine/Preload/PartialPreloadSubscriber.php#L151

We're not preloading the expired cache.

**To Reproduce**
1. Go to the WordPress site without WPML and other plugins manipulating home_url
2. Set Cache Lifespan to 10 minutes
3. Preload cache manually
4. Confirm that the expired cache is not preloaded

**Expected behavior**
We need to preload expired cache correctly

**Additional context**
The solution would be to make an additional check and append `/` if it's missing:
http://snippi.com/s/wpld6o2

We need to be sure that `$data['home_url']` doesn't contain `/` before appending it because we might introduce another bug.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by GeekPress** [comment]
@hellofromtonya I added the milestone for 3.6 on this issue.
