### ISSUE TITLE
Disable the Varnish purge on Cloudways when Varnish has been disabled on the server side

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#2668]
**Describe the bug**
When a customer has its site hosted on Cloudways WP Rocket it automatically activates cache synchronization with Varnish and the toggle button for Varnish add-on doesn't show on dashboard. but when the customer disables Varnish on the server-side there is no way to disable the Varnish purge from the WP Rocket side, this causes the site's error log to be filled in with messages due to the failed request. 

**To Reproduce**
1. In a Cloudways test environment, disable Varnish on the server-side.
2. Check in the WP Rocket dashboard that the toggle button on the Varnish add-on is not present.
![image](https://user-images.githubusercontent.com/11164737/82351168-9cbc7600-99d2-11ea-9358-6e286c142390.png)

**Expected behavior**
When Varnish is turned off on the server-side, Varnish synchronization is automatically turned off on WP Rocket side and can be clearly seen on the dashboard

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by GeekPress** [comment]
I don't think we can have an automatic detection when a user turn off Varnish on Cloudways side.

@Tabrisrp Do you know if we can have another check (https://github.com/wp-media/wp-rocket/blob/master/inc/ThirdParty/Hostings/Cloudways.php#L21) to be sure that we turn on the Varnish add-on only when Varnish is on?

**Comment by piotrbak** [comment]
I asked customer to dump `$_SERVER` array when Varnish is enabled and disabled, to see if there's something we can do about the automatic compatibility. This might be interesting, but needs further testing:
`["HTTP_X_APPLICATION"]`

Related ticket:
https://secure.helpscout.net/conversation/1168115583/166002?folderId=2415573

**Comment by webtrainingwheels** [comment]
another case here: https://secure.helpscout.net/conversation/1185223236/170517?folderId=273761

@GeekPress Could we get a fix for this into our next minor? We've introduced a new problem and there's no workaround for customers besides commenting out our code

**Comment by GeekPress** [comment]
@webtrainingwheels If we have a solution to really detect Varnish, it could be done in the next minor version. If not, we will have to decide what to do.

> @Tabrisrp Do you know if we can have another check (https://github.com/wp-media/wp-rocket/blob/master/inc/ThirdParty/Hostings/Cloudways.php#L21) to be sure that we turn on the Varnish add-on only when Varnish is on?

@wp-media/wprocketplugin Can you please check that 👆

**Comment by Tabrisrp** [comment]
- HTTP_X_VARNISH for server
- HTTP_X_APPLICATION for application

**At the server level:**

If HTTP_X_VARNISH returns HIT, Varnish is enabled and if it returns MISS, Varnish is disabled.

**At application level:**

If HTTP_X_APPLICATION returns the name of the application (for instance WORDPRESS), Varnish is enabled. If the variable returns VARNISHPASS, Varnish is disabled.

Breeze uses the following pseudocode for detecting Varnish's status (ENABLE/DISABLE) at both server and application level:

- X-Varnish → True → X-Application → varnishpass → return false
- X-Varnish → True → X-Application → other than varnishpass → Go to function
- X-Varnish → False → return false

**Comment by GeekPress** [comment]
@Tabrisrp It seems that we could have a solution.

Can we plan it for a next minor version?

**Comment by Tabrisrp** [comment]
Yes, with this we should be able to manage the automatic detection

**Comment by GeekPress** [comment]
Updating the priority to `high` per @webtrainingwheels feedback.

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
In `inc/ThirdParty/Hostings/Cloudways.php`, update the check in `get_subscribed_events()` to also check for `HTTP_X_VARNISH` & `HTTP_X_APPLICATION` values, following this logic:
- X-Varnish → True → X-Application → varnishpass → return false
- X-Varnish → True → X-Application → other than varnishpass → Go to function
- X-Varnish → False → return false

### Estimate the effort ✅ 
Effort `[XS]`
