### ISSUE TITLE
Cache doesn't work on Siteground's staging

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#267]
When creating a staging site on siteground, the cache doesn't work.

This is because the HTTP_HOST value is still the main domain URL (example.com), while the WP Rocket config file will use the staging URL (staging.example.com), so it doesn't match when we check for the config file in process.php

Ideally, if we have a way to detect that we're on a siteground staging site, we could filter the config file path to force its name to the main domain.

**Comment by pcfreak30** [comment]
You should just compare HTTP_HOST to SERVER_NAME as a crude sanity check here. Hit this today and hacking process.php on staging to work.

**Comment by arunbasillal** [comment]
Thinking out loud. 

When the config file doesn't exist, what if we attempt to create a new config file? 

Somewhere here: https://github.com/wp-media/wp-rocket/blob/7ff6b932752c910ef9b8ea73433bc58fad72535b/inc/classes/Buffer/class-tests.php#L192-L202

One potential problem is that if customers push staging back to production, there will be two config files. And there will always be two config files with different config information from there on.

**Comment by Tabrisrp** [comment]
That wouldn't work, because the issue is not the existence of the config file, but the mismatch between the expected hostname and the actual one. Having 2 config files would also be an issue, because one would be updated on staging, and the other one on production, so their content might not be matching correctly.

**Comment by Tabrisrp** [comment]
I did a new test for this, and the cache is now working properly on a staging site created on Siteground after updating the `advanced-cache.php` file. The original problem in this issue doesn't exist anymore, so we can mark it as `invalid` and close it.

@arunbasillal @GeekPress

**Comment by GeekPress** [comment]
@Tabrisrp Thanks for the update :)
