### ISSUE TITLE
Wp-Rocket is not compatible with LearnPress - facing too many problems

### ISSUE THREAD

**Issue by masuksarker** [wp-media/wp-rocket#2683]
I am facing too many problems when WP-Rocket is activated. I am using Learnpress to sell online courses through my website.

1) Users are unable to enroll FREE Courses from my website. But when they click on Enroll Button, then get a confirmation email, and also I can see that in the Order list. But all they can see is the Course Landing page / Buying page watch this video to see what happen https://cl.ly/99938a

2) After Clearing the Cache of Wp-Rocket users can see their free enrolled course in their dashboard but they unable to complete lessons!!! https://share.msbofficial.com/L1u7Zv7v
Lessons are not marked as complete!! - This problem happens for all types of courses not only free enrolled courses!

3) Even in the Students Certificate tab, when they click on their certificate, then they can see nothing!!! https://share.msbofficial.com/QwuK18Nx
as a result students are unable to download their certificate!

**Comment by camilamadronero** [comment]
Related to https://secure.helpscout.net/conversation/1175325115/167926?folderId=2675957

**Comment by piotrbak** [comment]
Not enough feeddback from customers, it'll not be implemented anywhere soon. Feel free to reopen this if needed.
