### ISSUE TITLE
Add filters for minified/combine JavaScript content before saving to file

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2695]
**Is your feature request related to a problem? Please describe.**
Some plugins have a need to modify the content of the JavaScript before it's saved to the minified/combined files, for examples to hide real paths (WP Hide plugin, etc).

We already provide a solution to do that for CSS content via the filters `rocket_css_asset_source_path`, `rocket_css_asset_target_path` and `rocket_css_content`, we can do the same for JS.

**Describe the solution you'd like**
Provide equivalent filters for JS before saving the minify/combine content.

**Additional context**
This was requested by the WP Hide & Security Enhancer dev team.

https://secure.helpscout.net/conversation/865404157/109714?folderId=637039

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1352871779/218397?folderId=3864740

**Comment by fabiomail** [comment]
@Tabrisrp @NataliaDrause any updates on this?

**Comment by jazir555** [comment]
Please add this, being able to utilize wp hide is pretty critical for security.

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/1667407005/302475/

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
