### ISSUE TITLE
Cache Busting adds a "?" adds the end for filename which contains a number

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#270]
When an enqueued CSS file contains a number, it causes a bug with the cache busting feature. A "?" is added at the end of the busted file => https://infinit.io/_/3nzRN8a

**Comment by Tabrisrp** [comment]
Fixed by https://github.com/wp-media/wp-rocket/commit/ad45870796bfdfde27e5130671506d309ab6ce11
