### ISSUE TITLE
Essential Grid not compatible and cannot be excluded by class

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2709]
Some or all of the Essential Grid configurations are not compatible with LazyLoad. Currently they do not provide any class on the image, so exclusions are not usually possible. 

LazyLoad typically has to be disabled for the whole page. 
We have this helper to do it programmatically: 
https://github.com/wp-media/wp-rocket-helpers/tree/master/compatibility/wp-rocket-compat-essential-grid

Example tickets:
https://secure.helpscout.net/search/?query=tag%3Aessential%20grid%20tag%3Alazyload

**Comment by GeekPress** [comment]
@arunbasillal What do you think about that? Which solution would you like to implement?

**Comment by webtrainingwheels** [comment]
Essential Grid fixed this on their side. I don't know why I didn't update this issue about that 😳

**Comment by GeekPress** [comment]
Thanks @webtrainingwheels for the update, it's good to know, even when it has been fixed :)

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1643839843/297534/
The width/height attributes can be targeted to exclude the problematic images.
