### ISSUE TITLE
wp_get_attachment_image_src CDN

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#271]
`wp_get_attachment_image_src` filter needs to be added for rocket_cdn_file

**Comment by Tabrisrp** [comment]
It can't be added like this because rocket_cdn_file expect a string url and not an array, which is the first argument of `wp_get_attachment_image_src`, but doing the replacement using this filter instead of rocket_buffer does make sense, so I'll look into an alternative.

**Comment by pcfreak30** [comment]
[wp-rocket-image-cdn-fix.zip](https://github.com/wp-media/wp-rocket/files/679477/wp-rocket-image-cdn-fix.zip)

I made a very simple plugin to fix this. You may use as needed to  fix the core.
