### ISSUE TITLE
FullScene/Premitheme Portfolio slider not compatible and cannot be excluded

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#2710]
**Issue**
The images in the slider are not shown when the LazyLoad is enabled.
The `img` tag doesn't have a class to exclude, and the attribute `data-no-lazy="1"` can't be added.
The LazyLoad needs to be deactivated globally.

**Steps to reproduce***

1. Create a portfolio with some images using the Premitheme theme.
**Example URL:** https://www.motorverso.com/portfolio-items/citroen-c5-aircross-flair-plus/.

2. Check portfolio images HTML markup:
![2020-06-13](https://user-images.githubusercontent.com/23031592/84578808-266f2180-ad8e-11ea-8d62-4dfd723c3c85.png)

3. The `img` tag doesn't have a class to use in the current LazyLoad exclusions.
4. The theme's UI doesn't have any options to add the attribute `data-no-lazy="1"` either.
5. You can't apply any exclusions so you can't use LazyLoad in the pages.

**Theme** 
https://themeforest.net/user/premitheme/portfolio.

**Related Ticket**
 https://secure.helpscout.net/conversation/975357626/125937?folderId=2675957.

**Comment by GeekPress** [comment]
@camilamadronero Will it possible to add the **Steps to reproduce**?

**Comment by camilamadronero** [comment]
@GeekPress Done! Please let me know if you need anything else :+1:

**Comment by GeekPress** [comment]
@camilamadronero It's all good, thanks 🙏

**Comment by Tabrisrp** [comment]
Do we have the theme available somewhere? The credentials for this customer case have been removed, so we can't test there.

**Comment by iCaspar** [comment]
Adding Waiting for feedback to see if we can make contact with the theme developer about adding a CSS class to the images. If so, we can call this an `[S]` (just add the new class to the LazyLoad excludes`.

If we don't get any response, we'll have to implement a way to check/exclude for child images within known slider `div`s, which we can probably do by leveraging the new DOMDocument module -- once the issues have been worked out with that.

**Comment by kierantaylorio** [comment]
@iCaspar Contact has been made with the theme developer and they'll be adding the skip-lazy class to their slider as of version 2.2

**Comment by Tabrisrp** [comment]
Per above feedback, fix is being done in the theme side directly.
