### ISSUE TITLE
Some images are not lazy loaded

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2711]
There are pretty many tickets related to the images that couldn't be lazyloaded because JavaScript is not changing the placeholder value in `src` attribute.

Many of them could be solved with a simple CSS tweak:
http://snippi.com/s/kzd147f

I don't think that this solution can cause any difficulties. However, it needs further testing and also it would be good to see how many tickets could be resolved with it.

It's related to this GitHub issue:
https://github.com/verlok/lazyload/issues/350

Related ticket:
https://secure.helpscout.net/conversation/924377566/118793/

Slack convo:
https://wp-media.slack.com/archives/C08N8J6VC/p1565625245026400

**Comment by piotrbak** [comment]
@GeekPress I haven't found this CSS to be useful for a while, I tried it for a couple of customers but it didn't help.

**Comment by GeekPress** [comment]
@piotrbak Thanks for the feedback. Let's close it for now ;)
