### ISSUE TITLE
3.6 alpha2 - Invalid admin notice when CPCSS for mobile fails and few PHP notices

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2716]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
By design, we agreed not to display a separate notice for CPCSS for mobile. However, when "Separate cache for mobile" is enabled after enabling "Optimize CSS delivery", and if CPCSS generation fails, a notice is displayed. 

I noticed this first on the mega site. But since it's not easy to replicate a failed CPCSS generation, I tried it on Local. There I had more luck replicating it. 

**PHP Notices:** 

```
PHP Notice:  Undefined index: Unavailable in C:\Users\Arun Basil Lal\Local Sites\a-test-site\app\public\wp-content\plugins\wp-rocket\inc\Engine\Admin\Beacon\Beacon.php on line 215
```
Details: http://snippi.com/raw/tq40z51

```
PHP Notice:  Undefined index: total in C:\Users\Arun Basil Lal\Local Sites\a-test-site\app\public\wp-content\plugins\wp-rocket\inc\Engine\CriticalPath\CriticalCSSSubscriber.php on line 353
```

**To Reproduce**
- Make sure `Separate cache for mobile` is disabled. 
- Enable `Optimize CSS delivery`. Let the generation complete.
- Now enable `Separate cache for mobile`
- Notice should be visible. 

Video: https://youtu.be/1ECnkDSEvUc

Note: 

- As you can see it isn't generated every time. But if you start with a fresh install you should see it at least once. 
- The PHP notices were also hit and miss. I will keep trying to find a reliable way to replicate this. 

**Expected behavior**
- No notice is to be displayed. If CPCSS For mobile generation fails, let it fail silently. WP Rocket will use the desktop CPCSS in this case. 
- No PHP notices to be generated. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5751474/83776413-c5688f00-a6a5-11ea-94f1-fdc8c12df4be.png)

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
@arunbasillal Can you re-test for the 2 notices and confirm that they are not displayed anymore for you, on the `develop` branch?

**Comment by arunbasillal** [comment]
I tested with the develop and tried to recreate this. The notices are gone 👍 

~~I couldn't recreate the admin notice when enabling `separate cache for mobile`~~
As I was writing this, I did another test and got this:
![image](https://user-images.githubusercontent.com/5751474/83872920-817e9400-a750-11ea-92d2-4ebd1cb698b8.png)

🤔 such is life.

**Comment by arunbasillal** [comment]
I found a way to reliably replicate this - https://youtu.be/xotU7nEMfmQ

**Steps:** 
- Fresh WP Rocket install (current develop branch used in the video).
- Make sure `Enable caching for mobile devices` is disabled. This is enabled by default. 
- Enable `Optimize CSS delivery`. 
- While the process is running, click on `Regenerate CPCSS` from the admin bar. 
- Wait for the generation to complete. 
- Enable, `Enable caching for mobile devices` and `Separate cache for mobile`.
- The admin notice should show up. 

I tried this three times and was able to replicate the notice.

**Comment by arunbasillal** [comment]
I recreated this on `mega/divi` by adding `define( 'WP_HTTP_BLOCK_EXTERNAL', true );` to `wp-config.php` right after license validation.

Then repeated the steps as above. 

![image](https://user-images.githubusercontent.com/5751474/83877677-97905280-a758-11ea-879b-8b10f071d86e.png)
