### ISSUE TITLE
False positive on missing write permissions notice for advanced-cache.php

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2721]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 (develop branch)
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
This notice is incorrectly displayed on Windows, using Local. There is writing permissions:
![image](https://user-images.githubusercontent.com/5751474/83875337-8a716480-a754-11ea-8a29-8f118f9f2dcf.png)

**To Reproduce**

- Add `define( 'WP_HTTP_BLOCK_EXTERNAL', true );` to `wp-config.php`
- Install a new copy of WP Rocket. License validation will fail
![image](https://user-images.githubusercontent.com/5751474/83875224-572ed580-a754-11ea-94ed-bd197dbad043.png)
- Remove `WP_HTTP_BLOCK_EXTERNAL` from `wp-config.php`
- Refresh WP Rocket settings page and click `Validate License`
- License validation will succeed, but this notice about missing write permissions will be displayed:
![image](https://user-images.githubusercontent.com/5751474/83875337-8a716480-a754-11ea-8a29-8f118f9f2dcf.png)
- If you check `wp-content` folder, `advanced-cache.php` is generated correctly.
- If you refresh WP Rocket settings page, the notice is no longer displayed. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@arunbasillal Does this issue is related to 3.6?

**Comment by Tabrisrp** [comment]
don’t think that’s something new. The processes order on the page load probably result in this:

- validation happens
- check for advanced-cache happens
- advanced-cache is written
- Which means the notice will display even though in the end the file was written correctly

Also this notice copy is wrong since a long time, it should not talk about writing permissions but about the content of the file not being ours. The one which is actually about writing permissions has the file content in a textarea to be copied

**Comment by arunbasillal** [comment]
- I tested this with 3.5.5.1 and couldn't replicate the issue. 
- I retested with the current develop and the issue still popped up. 

So it looks it's new. 

> Also this notice copy is wrong since a long time, it should not talk about writing permissions but about the content of the file not being ours. The one which is actually about writing permissions has the file content in a textarea to be copied

I will open a new issue for this one. Thanks 👍
