### ISSUE TITLE
WP Rocket options page missing icons

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#2723]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark:
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark:

**Describe the bug**
On some servers, and if WooCommerce has the geolocation option enabled, fonts/icomoon.eot?-4yq2oj will be redirected to fonts/icomoon.eot?v=XXX, which will ultimately fail.

**To Reproduce**
Steps to reproduce the behavior (only on faulty servers):
1. Go to WooCommerce and activate Geolocation.
2. Go to WP Rocket options page.
3. See error on WP Rocket options pages and browse console.

**Expected behavior**
No redirects. Icons showing properly.

**Screenshots**
![vgy.me](https://i.vgy.me/IJw2iX.jpg)
![vgy.me](https://i.vgy.me/6dbrjO.png)
![vgy.me](https://i.vgy.me/1AUCwy.png)

**Additional context**
It only happens on misconfigured servers AND WooCommerce has geolocation enabled. 
Removing the "-" from fonts/icomoon.eot?-4yq2oj fixes the issue.

Ticket - https://secure.helpscout.net/conversation/1183758870/170104/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by DahmaniAdame** [comment]
@vmanthos

**Comment by vmanthos** [comment]
Similar tickets where the query string was involved: 
- https://secure.helpscout.net/conversation/1178156488/168608/
- https://secure.helpscout.net/conversation/1183690521/170078/

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
- Remove the query string from the font URL in `src/scss/base/_icons.scss`
- Regenerate the production CSS file

### Estimate the effort ✅ 
Effort `[XS]`

**Comment by DahmaniAdame** [comment]
Another related case - https://secure.helpscout.net/conversation/1214421166/177717
