### ISSUE TITLE
Improve admin notice for invalid content in advanced-cache.php

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2730]
Currently we have two admin notices related to `advanced-cache.php`

- One is when `advanced-cache.php` cannot be written into.
- Another is when `advanced-cache.php` has the wrong content.

Here they are in the above mentioned order: 
![image](https://user-images.githubusercontent.com/5751474/83898836-185d4780-a775-11ea-8f85-864261b31de1.png)

**The first notice above can be re-used for both cases and we shall get rid of the second notice. Here is why:** 

- If the file is writable and if the contents are not WP Rocket's, then WP Rocket updates the content.
- If the file is not writable and the contents are correct, then we do not show any notice.
- If the file is not writable and if WP Rocket has to update the file (example when we enable caching for mobile), then we can show the notice with the updated content and leave it at that. 

The second notice doesn't serve any real purpose and can be removed. 

Note: Some customers / hosts prevent writing into `advanced-cache.php` as a security measure. We should show the notice only if the content is not what it is supposed to be (as we do now). 

**To Reproduce**
- Remove writing permissions to `advanced-cache.php` (set it to 444) and delete the contents of the file. 
- Enable or disable mobile caching. 
- The notice should show up. 

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the problem ✅ 
Yes, reproduced this during development of 3.6

### Identify the root cause ✅ 
Arun noted everything in the OP 👍 

### Scope a solution ✅ 
#### inc/Engine/Cache/AdvancedCache.php
- remove `notice_content_not_ours()` method

#### inc/Engine/Cache/AdminCacheSubscriber.php
- remove `notice_content_not_ours()` callback method

### Estimate the effort ✅ 
Effort `[XS]`
