### ISSUE TITLE
CloudFlare: Make HTTPS Protocol Rewrite option more consistent

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#275]
* WP Rocket 2.9.1
* CloudFlare + Flexible SSL

With Flexible SSL from CloudFlare and the _HTTPS Protocol Rewrite_ option enabled, WP Rocket is expected to implement relative protocol for assets. As per setting description:

> Rewrite all images, stylesheets and scripts from using either `http://` or `https://` to using just `//` to support Flexible SSL.

This does not seem to work 100%. For example, WP Rocket’s own LazyLoad script shows up as `http://`, triggering insecure content warnings.

Flexible SSL from CloudFlare may be controversial in general, but once WP Rocket claims to support it, we should make sure that support works 100%. Not sure how to approach it technically, but currently it seems “broken” from a user perspective.

**Comment by GeekPress** [comment]
@glueckpress Except the LazyLoad script, are there other files we forget to remove the HTTP protocol?

**Comment by glueckpress** [comment]
@GeekPress I’m not into our code enough to know if a function like `__rocket_fix_ssl_minify()` would need to be checked in this context. Just noticed it does something with `is_ssl()` which can be potentially problematic for CF Flexible SSL.

For sure, this stack seems relevant here:

```
WP_ROCKET_FRONT_JS_URL
┗ WP_ROCKET_FRONT_URL
  ┗ WP_ROCKET_INC_URL
    ┗ WP_ROCKET_URL
      ┗ plugin_dir_url()
        ┗ plugins_url()
          ┗ WP_PLUGIN_URL
            ┗ WP_CONTENT_URL
              ┗ get_option( 'siteurl' )
```

So anything front-end we do based on `WP_ROCKET_URL` will contain `http://` when the site URL is set with `http://` (like in the case above where only CF Flexible SSL is used).

At this point, we seem to be lucky, though, because only _LABjs_ in `rocket_insert_deferred_js()` seems to be affected. 😉

**Comment by glueckpress** [comment]
> So anything front-end we do…
Correction: Afaik, CF Flexible SSL would apply on the back-end as well, wouldn’t it?

**Comment by Tabrisrp** [comment]
Lazyload script URL won't be caught by the regular expression we currently use for the rewrite, as it is in an inline script. We would need to add a specific filter for that case.

@glueckpress The option is only applied on the front because it uses the `rocket_buffer` hook.

**Comment by GeekPress** [comment]
I'm closing this one as the LazyLoad script is now included from a JS file which solve the original problem.
