### ISSUE TITLE
YouTube statistics are not collected when replacing the video with thumbnail

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2757]
**Describe the bug**
When LazyLoading YouTube video, the statistics in YouTube dashboard are not collected.

**To Reproduce**
1. Add your YouTube video to the page
2. Enable `Replace YouTube iframe with preview image` feature
3. Go to YouTube dashboard to see the live statistics for this specific video
4. In the incognito mode (no AdBlock, etc.) watch the video and confirm that the statistics are not collected
5. Do the same test with `Replace YouTube iframe with preview image` feature disabled and confirm that statistics are correct.

**Expected behavior**
Make sure that statistics are being collected as expected when LazyLoad features are enabled.

**Additional context**
We did some tests with the team. Results in [this slack](https://wp-media.slack.com/archives/C08N8J6VC/p1591813507196700) thread.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
I guess this is a normal behavior.

Why?
We replace the iframe by a preview image. It means that the iframe isn't loaded = no stats to report. The stat will be reported after the iframe will be displayed.

Or the stats are also not reported after displaying the iframe?

**Comment by piotrbak** [comment]
@GeekPress Unfortunately, stats are also not collected when playing the video. We have confirmed this with @arunbasillal on his YouTube channel.

**Comment by arunbasillal** [comment]
@GeekPress You can see how we tested in this thread - https://wp-media.slack.com/archives/C08N8J6VC/p1591813507196700

If you check for the screenshot of the live analytics in the last entries in the thread. No view was logged.

**Comment by GeekPress** [comment]
@arunbasillal Do we know if we can fix the issue?

**Comment by Tabrisrp** [comment]
Is this the same issue as for #1515?

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/1239404750/183406?folderId=2683093

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1346266045/215010?folderId=3864740

**Comment by TheTeacherPoint** [comment]
> I guess this is a normal behavior.
> 
> Why?
> We replace the iframe by a preview image. It means that the iframe isn't loaded = no stats to report. The stat will be reported after the iframe will be displayed.
> 
> Or does the stats are also not reported after displaying the iframe?

No, it doesn't show the view count in YouTube - Traffic Sources - External - MyWebsite.

**Comment by TheTeacherPoint** [comment]
May I know when the issue will be resolved? I have to disable the "YouTube iFrame" option in LazyLoad which is slowing down my site as I want to see the Analytics (View Count) in YouTube.

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1395315145/231118/

**Comment by arunbasillal** [comment]
@TheTeacherPoint Thanks for the feedback. We don't know how to handle it differently at this point. Which also means we can't estimate this right now.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
