### ISSUE TITLE
Increase WP nonce lifespan

### ISSUE THREAD

**Issue by foliovision** [wp-media/wp-rocket#2760]
**Is your feature request related to a problem? Please describe.**
When the **Cache Lifespan** is set to 24 hours, the nonces in the HTML of the pages are sometimes invalid.

**Describe the solution you'd like**
WordPress nonce lifespan is set to 24 hours by default.

If WP Rocket **Cache Lifespan** is set to 24 hours I imagine it should be set to something like 30 hours to be safe. You could be adjusting that using the `nonce_life` filter hook. By default it's set to `DAY_IN_SECONDS` = 24 hours: https://developer.wordpress.org/reference/functions/wp_nonce_tick/#source

**Describe alternatives you've considered**
For now we set the **Cache Lifespan** to 10 hours. But in some cases we would like to have it at even 72 hours. So it would be good to set the nonce lifespan accordingly.

**Additional context**
If you run a Easy Digital Downloads store you might run into this issue. You have a cached page with the buy button and if that cache page is too old, the nonce won't validate and the product won't be added into cart.

**Comment by GeekPress** [comment]
Hi @foliovision 🤚

Thanks for your suggestion.

After discussing with the dev team, we decided to decline this feature request. The main reason is about security reason. Updating nonce life is something which can break some security features on other plugins. In security wise, it's going to be very risky!

If you are sure about what are doing, we recommend to use the `nonce_filter` yourself.

All the best!

**Comment by foliovision** [comment]
Hello GeekPress,

in that case the maximum setting of WP Rocket cache life span shouln't be more than 12 hours I think, as otherwise the plugin can create cache files with invalid nonces. There is currently only an explanation to use not more than 10 hours and no explanation given.

Thanks,
Martin
