### ISSUE TITLE
Content encoding issue with serve pre-compressed static files rules

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2767]
**Identify the root cause**
On some configuration, the current rules to serve pre-compressed static files are creating a content encoding issue, preventing the files from being loaded.

This creates a broken layout on the website.

**Scope a solution**
Using the following rules resolved the issues on 2 websites affected. Those rules were taking from the [HTML5 boilerplate](https://github.com/h5bp/server-configs-apache/blob/master/h5bp/web_performance/pre-compressed_content_gzip.conf):

```
<IfModule mod_headers.c>

    RewriteCond %{HTTP:Accept-Encoding} gzip
    RewriteCond %{REQUEST_FILENAME}\.gz -f
    RewriteRule \.(css|js)$ %{REQUEST_URI}.gz [L]

    # Prevent mod_deflate double gzip
    RewriteRule \.gz$ - [E=no-gzip:1]

    <FilesMatch "\.gz$">

        # Serve correct content types
        <IfModule mod_mime.c>
            # (1)
            RemoveType gz

            # Serve correct content types
            AddType text/css              css.gz
            AddType text/javascript       js.gz

            # Serve correct content charset
            AddCharset utf-8 .css.gz \
                             .js.gz
        </IfModule>

        # Force proxies to cache gzipped and non-gzipped files separately
        Header append Vary Accept-Encoding

    </FilesMatch>

    # Serve correct encoding type
    AddEncoding gzip .gz

</IfModule>
```

**Comment by hellofromtonya** [comment]
Tested on these customer sites:

https://secure.helpscout.net/conversation/1191509765/171968/
https://secure.helpscout.net/conversation/1191658228/172014?folderId=377611
