### ISSUE TITLE
Remove certain browser cache rules which may no longer be relevant

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#2775]
Context for how this came to light: A WP Engine customer asked if these rules were still important (as WPE handles browser caching instead of WPR, but doesn't include similar rules):

- text/x-component
- application/x-web-app-manifest+json 
- ext/cache-manifest still

Opened at Piotr's request here: https://wp-media.slack.com/archives/C43T1AYMQ/p1592245213219000

Related ticket here: https://secure.helpscout.net/conversation/1195061052/172907

**Comment by GeekPress** [comment]
@girlie The .htaccess is deprecated which mean WP Engine doesn't use it anymore. Even if our rules and the .htaccess is added, it's not used anymore.

3.6.1 will also deprecate .htaccess on WP Engine: https://github.com/wp-media/wp-rocket/issues/2345

I'm closing the issue as we don't have to do anything ^^
