### ISSUE TITLE
LiteSpeed broken layout incompatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2776]
**Describe the bug**
When using LiteSpeed (and seems that in connection with WooCommerce), double click on the WooCommerce page creates a broken layout cache.

I wasn't able to replicate this on pages other than WooCommerce ones.

**To Reproduce**
1. On WooCommerce site hosted on LiteSpeed
2. Clear all caches, including OPCache
3. Go to the taxonomy page
4. Double-click on the chosen product
5. See if the layout is broken

**Expected behavior**
WP Rocket caching the pages correctly.

**Screenshots**
Double click on the product page:
https://jmp.sh/ve9YdcY

Double click on taxonomy page:
https://jmp.sh/4n8e1nJ

**Additional context**
I was working on one ticket related to this issue, I was pretty sure that it's related to the HTTP/3 protocol and QUIC, but I have a second ticket with HTTP/2.

Nothing special in the WP Debug log. The cached HTML file just stops at some point.

In the first ticket, it was happening only for mobiles (still not for all), in the second one, I've reproduced it on the desktop.

I'm getting more information regarding the second environment, as it seems that it has a shared cache directory.

**Related tickets:**
1. We have access to the full cPanel and we can test there whatever needed:
https://secure.helpscout.net/conversation/1173326494/167375?folderId=2415573

2. New ticket (from screencast), still getting more information about the environment:
https://secure.helpscout.net/conversation/1165493465/165403?folderId=2415573

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by BenHarris** [comment]
We hit this today too. Have temporarily rolled back to 3.5.5.1

**Comment by piotrbak** [comment]
@BenHarris This issue is not related to this one:
https://github.com/wp-media/wp-rocket/issues/2767

Please check if the 3.6.0.3 version fixes your problem. If not, contact us via support and mention this GitHub issue.

**Comment by vmanthos** [comment]
There is a related ticket here: https://secure.helpscout.net/conversation/1213394116/177393
Check my notes: https://secure.helpscout.net/conversation/1213394116/177393/#thread-3526587635

This is WIP, but I'll be on leave, so I'm adding here my findings so far.

As Piotr found, the issue can occur when there are multiple clicks on the link of a product. I found this can happen with normal pages too. This site is hosted on a LiteSpeed server, as in previous cases.

When doing multiple clicked, some of the requests are canceled:
![](https://i.vgy.me/TWjbn5.jpg)
Full-Scale image > https://i.vgy.me/TWjbn5.jpg

The caching process stopped in these two checks:
* https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/classes/Buffer/class-tests.php#L318-L322
* https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/classes/Buffer/class-tests.php#L324-L328

One obviously passes through resulting into only a part of the page being cached, e.g. http://snippi.com/s/pvej1ql

**Comment by vmanthos** [comment]
Potentially related ticket: https://secure.helpscout.net/conversation/1274338964/192449/

**Comment by vmanthos** [comment]
Potentially related ticket:
https://secure.helpscout.net/conversation/1285231945/195643/

This is again a WooCommerce site on a Litespeed server.

**Comment by vmanthos** [comment]
**A similar ticket:**
https://secure.helpscout.net/conversation/1385330595/228167

**Slack Convo about a potential solution:**
https://wp-media.slack.com/archives/C43T1AYMQ/p1611140026043100

**Comment by arunbasillal** [comment]
@piotrbak Is this issue still WIP? If not, can you please update the title?

**Comment by vmanthos** [comment]
**Potentially related ticket:** https://secure.helpscout.net/conversation/1419934340/237835/

The site is hosted on a LiteSpeed server, and pages are randomly cached incomplete, e.g.: http://snippi.com/s/0rj03ck

**Comment by NataliaDrause** [comment]
Likely related: https://secure.helpscout.net/conversation/1420783987/238073?folderId=3864740

**Comment by vmanthos** [comment]
**Potentially related:** https://secure.helpscout.net/conversation/1434303232/241865/

**Comment by camilamadronero-zz** [comment]
Probably related https://secure.helpscout.net/conversation/1424294729/239107/

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1458397773/249020/

**Comment by AscensionAynat** [comment]
Hi, is there already a solution for this issue? I'm having this problem.

**Comment by sandyfzu** [comment]
Related ticket: https://secure.helpscout.net/conversation/1460570318/249648/

The client applied the changes that Vasilis proposed and says that fixes the issue.

**Comment by NataliaDrause** [comment]
Likely related: https://secure.helpscout.net/conversation/1465576506/251041/

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1472466353/252789/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1473348791/252971

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1482570374/255785?folderId=3864740
