### ISSUE TITLE
Automatically exclude /superpwa-sw.js & /superpwa-manifest.json from being cached

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2778]
When https://wordpress.org/plugins/super-progressive-web-apps/ is active along WP Rocket, WP Rocket is caching these 2 files and thus triggers a unsupported MIME type error:
- /superpwa-sw.js
- /superpwa-manifest.json

Excluding these 2 files by adding them to **Never Cache URL(s)** fixes the issue.

We could exclude them automatically.

Slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1592206372355700
Ticket: https://secure.helpscout.net/conversation/1194340674/172683/

**Comment by arunbasillal** [comment]
For now my recommendation is to contact the plugin developers (🖐️ ) and try and add the configuration at their end. This might change as service workers make their way into WordPress core. 

Also the filename is different for multisite. 

- /superpwa-sw-BLOGID.js
- /superpwa-manifest-BLOGID.json

Example: https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/79d65a2f079a55bcb410023512b5fab403aa1651/public/sw.php#L26

**Comment by GeekPress** [comment]
@arunbasillal Do you plan to fix it directly fro your plugin? If so, do we close the issue here?

**Comment by arunbasillal** [comment]
I have opened an issue for it on the plugin repository. It's best to be handled at the plugin end 👍
