### ISSUE TITLE
Check for get_post_type_object() = null when purging

### ISSUE THREAD

**Issue by vagskal** [wp-media/wp-rocket#278]
I use post_types that are not registered and the WP Rocket code throws this PHP notice:

> Notice: Trying to get property of non-object in /…/wp-content/plugins/wp-rocket/inc/common/purge.php on line 107

Would it be possible to change lines 105-107 in the indicated file from:

```php
 // Don't purge if post's post type is not public or not publicly queryable
    $post_type = get_post_type_object( $post->post_type );
    if ( $post_type->public !== true ) {
```

To:
```php
 // Don't purge if post's post type is not public or not publicly queryable
    $post_type = get_post_type_object( $post->post_type );
    if ( ! is_object( $post_type ) || $post_type->public !== true ) {
```

Thanks.

**Comment by GeekPress** [comment]
@vagskal Thanks for reporting this issue and providing the fix!

@Tabrisrp could we fix it directly for the next minor version (2.9.2)?

**Comment by Tabrisrp** [comment]
See commit https://github.com/wp-media/wp-rocket/commit/ffff6d20811ffcd96b3dda85a1e70d789004d903
