### ISSUE TITLE
Compatibility with WordPress GDPR by welaunch plugin

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#2788]
Plugin: [https://codecanyon.net/item/wordpress-gdpr/21880726](https://codecanyon.net/item/wordpress-gdpr/21880726)
(I don't know if it is available in our account)

**Quoting customer:**
With this file (adding it to /inc/3rd-party/3rd-party.php) I could successfully check the according to cookies set by the WordPress GDPR plugin to load dynamic content bound to the user's cookie consent.

There are no further settings to be done in the WordPress GDPR plugin.
My concern was to check programmatically a cookie value set by WP GDPR in order to load or not to load another plugin (Actionable Google Analytics by Tatvic).
While using WP Rocket the corresponding mu-plugin I created did not work, but without using WP Rocket it worked.
So my guess was that the WP GDPR cookies must be "told" to WP Rocket, so that they do not conflict with caching and get statically stored.

With the 3rd party code for WP GDPR I submitted to you, it is possible to check WP GDPR cookies for dynamically loading content, plugins and so on.
No further settings need to be done.

Code provided by the customer here: [https://secure.helpscout.net/conversation/1198620771/173846/](https://secure.helpscout.net/conversation/1198620771/173846/)

tag: `there is no tag for WordPress GDPR by welaunch plugin`

**Comment by GeekPress** [comment]
@juricazuanovic Are there some settings to do on the GDPR plugin? If you can provide us a **Step to reproduce,** it will be awesome.

**Comment by juricazuanovic** [comment]
@GeekPress I asked the customer for the steps to reproduce but did not get an answer.

**Comment by juricazuanovic** [comment]
@GeekPress The customer has replied that there are no further settings or steps to reproduce. 

Please check the full answer on the ticket. I did not think it is necessary to copy-paste it here.

**Comment by GeekPress** [comment]
@juricazuanovic Thanks for the update. It will be very helpful to have all infos directly in your first message. We will be sure that the dev team won't miss any important infos.

**Comment by piotrbak** [comment]
Not enough feedback from customers, it'll not be implemented anywhere soon. Feel free to reopen this if needed.
