### ISSUE TITLE
Improve DreamPress hosting compatibility

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2789]
As part of our Hosting compatibility initiative, we can have a new look at our compatibility with DreamPress.

### Current state
- Helper plugin: https://github.com/wp-media/wp-rocket-helpers/tree/master/compatibility/wp-rocket-compat-dreampress
- Documentation: https://docs.wp-rocket.me/article/1016-dreampress--varnish-compatibility

This works, but discoverability for those is low, as users might:
- Not know there is an issue when using WP Rocket on DreamPress without the helper
- Not find the helper plugin and/or documentation
- There is nothing in the core plugin to indicate that something might not be working well

### Ideal state
- Be able to integrate the helper plugin directly in core, if we can get a way to auto-detect DreamPress
- Update the code for our new architecture

#### Related tickets
- https://secure.helpscout.net/conversation/1196851806/173436?folderId=637040

**Comment by webtrainingwheels** [comment]
Per Remy's request about the best way to detect DreamPress, I have an email in to Mika about this: https://secure.helpscout.net/conversation/1200317169/174434?folderId=377610

**Comment by engahmeds3ed** [comment]
**Reproduce the issue** ✅ 
No need to reproduce.

**Identify the root cause** ✅ 
that the code is not inside our core so the customer has to use helper plugin.

**Scope a solution** ✅ 
We need to make this third party compatibility hosting class and use the following condition to check if this is hosted on dreampress or not
```
if ( "DreamPress" === $_SERVER[‘x-hosted-by’] )
```

**Effort** ✅ 
Effort `[S]` , for third party class, Unit & Integration tests

**I think we will need dreampress account when working on that to test.**

**Comment by webtrainingwheels** [comment]
Just an FYI, DreamPress is in the process of rolling out the new header. Hopefully it will be fully available in a couple of weeks, I will confirm with Mika. @engahmeds3ed If you are still in need of a test account, let me know, I can ask Mika about that.

**Comment by webtrainingwheels** [comment]
@piotrbak @Tabrisrp Got confirmation that the new header is rolled out to all sites. Just waiting to hear back about the test account now :)

**Comment by webtrainingwheels** [comment]
@Tabrisrp @piotrbak Test account details now available, youknowwhere.

Just some further details about the general DreamPress setup:

All DreamPress sites will either be on Nginx as a proxy or Varnish with Nginx to process https. Depends on if they’re on old DreamPress, Current, or the new experimental version. There’s no way to disable the proxy though, as it’s a part of the managed service.
The Nginx proxy uses the same curl-type commands as Varnish (so purges work the same way). 

The new header they have implemented is set by the proxy itself. If it’s running, it’s there.
So we should _not_ run into a Cloudways-esque scenario where we are spamming the server with purge requests without a proxy actually being enabled.

**Comment by piotrbak** [comment]
Our compatibility doesn't work. It seems that the `x-hosted-by` header is not present in the `$_SERVER` array. You can see the whole array here:
https://snippi.com/s/mfw76zr

On the other hand, it's present in the header list:
![image](https://user-images.githubusercontent.com/26767037/93611557-5d288980-f9c6-11ea-8dbd-d075c41b6c4e.png)


@Tabrisrp Could you contact them about that?
