### ISSUE TITLE
Remove query string fails when “?ver=” doesn’t start the query string

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#279]
* WP Rocket 2.9.1
* __Remove query string__ enabled

Apparently the _Remove query string_ option fails for URLs where the query string starts with another parameter then `?ver=`.

A URL like this:
```
https://example.com/wp-content/uploads/avada-styles/avada-6.css?timestamp=1483366399&ver=5.0.6
```
…becomes this:
```
https://example.com/wp-content/cache/busting/1/wp-content-uploads-avada-styles-avada-6.css?timestamp=1483366399&#038;ver=5.0.6
```
…which results in a 404.

The _Remove query string_ option should work for any possible combination of query parameters, or degrade gracefully if support for any combination is not possible/desirable.

**Comment by glueckpress** [comment]
I’m re-opening this with https://github.com/wp-media/wp-rocket/commit/a783f2487904015158b9ead65f3fb6ef6150c139#commitcomment-20465144

**Comment by Tabrisrp** [comment]
@glueckpress what do you think about that : the default source is returned if the preg_replace was not able to modify the filename. That way, unexpected query strings won't break the file, and we'll be able to improve our code depending on what we encounter.

https://github.com/wp-media/wp-rocket/compare/9a7e852c56e4...275c04423e35

**Comment by glueckpress** [comment]
@Tabrisrp Sounds good! We should probably add something UI-wise, though, to let people know the option cannot yet be expected to remove _all_ possible query strings yet? 

Something along these lines maybe:

![screenshot 2017-01-14 um 11 23 21](https://cloud.githubusercontent.com/assets/308422/21954257/089dd0e8-da4c-11e6-864f-d13587c8800c.png)

```php
array(
	'type'        => 'helper_description',
	'name'        => 'rocket_remove_query_strings_desc',
	'description' => __( 'This will remove the version query string from static resources and encode it in the resources filename instead. Example:  <code>style.css?ver=1.0</code> will become <code>style-1.0.css</code>.', 'rocket' )
),
array(
	'type'        => 'helper_description',
	'name'        => 'rocket_remove_query_strings_desc',
	'description' => __( '<strong>Note:</strong> Activating this option can improve the “Remove query strings from static resources” grade on GT Metrix, though currently this option only supports the default <code>?ver=</code> parameter.', 'rocket' ),
),
```

_(Code grabbed from https://github.com/wp-media/wp-rocket/blob/0ed47ce5b026ddaff6effd9effaa25a10e59d0da/inc/admin/ui/modules/advanced.php#L19-L30)_

**Comment by glueckpress** [comment]
Tested https://github.com/wp-media/wp-rocket/compare/9a7e852c56e4...275c04423e35, validated.

Query string gets removed from any of these:

```php
wp_enqueue_style( 'breakage', get_theme_file_uri( '/assets/css/breakage.css' ), array( 'twentyseventeen-style' ), '123456' );

wp_enqueue_style( 'breakage', get_theme_file_uri( '/assets/css/breakage.css?ver=123456' ), array( 'twentyseventeen-style' ) );
```

…but not these:

```php
wp_enqueue_style( 'breakage', get_theme_file_uri( '/assets/css/breakage.css?123456' ), array( 'twentyseventeen-style' ) );

wp_enqueue_style( 'breakage', get_theme_file_uri( '/assets/css/breakage.css?random-query=123456' ), array( 'twentyseventeen-style' ) );
```

**Comment by Tabrisrp** [comment]
Current expected behaviour, so all good, closing this.
