### ISSUE TITLE
Clarify preload font text to include CDN

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2793]
In the font preload text we state:
>Fonts must be hosted on your own domain. 

However this has understandably confused some customers in regards to CDNs. 

We could clarify by saying: 
>Fonts must be hosted on your own domain, or the domain you have specified on the CDN tab.

**Comment by GeekPress** [comment]
I guess this issue don't need a grooming session. It will be scheduled for 3.6.2.
