### ISSUE TITLE
Move rocket_get_dns_prefetch_domains into inc/functions/options.php

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#280]
The function rocket_get_dns_prefetch_domains() is declared in /inc/front/dns-prefetch.php.

The inc/front folder is reserved for functions called by a hook.

The function rocket_get_dns_prefetch_domains() isn't directly called by a hook so we have to move it into the inc/functions folder.

The file options.php seems to be the more appropriate.

**Comment by Tabrisrp** [comment]
https://github.com/wp-media/wp-rocket/commit/7833799ef168bd6d39b2e5d9d3266b66a6aa99a3
