### ISSUE TITLE
Fallback CPCSS - CSS files are not loaded asynchronously

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2800]
Tested with WP Rocket 3.6.0.3

When using Fallback CPCSS, the CSS files are not loaded asynchronously anymore. 

**Steps to reproduce**

1. Enter CSS into Fallback CPCSS field (also take appropriate steps to apply it, delete existing cpcss, stop automatic regeneration. 
2. Observe the the CPCSS is correctly inserted into the page, but the CSS files are loaded normally and render-blocking

Related ticket: https://secure.helpscout.net/conversation/1197138109/173482?folderId=377611

**Comment by crystinutzaa** [comment]
@webtrainingwheels & @GeekPress I caught this bug while working on this PR: https://github.com/wp-media/wp-rocket/pull/2786
And is fixed in this PR.
