### ISSUE TITLE
jQuery Updater compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2807]
**Describe the bug**
There are some sites that are using jQuery Updater (40k installations) plugin to load their jQuery file. In this case, when **Load JavaScript Deferred** with **Safe Mode for jQuery** is enabled, those files are not excluded.

**To Reproduce**
1. Install jQuery Updater plugin
2. Enable Load JavaScript Deferred with Safe Mode for jQuery feature
3. Confirm that the jQuery file is deferred

**Expected behavior**
Automatically exclude those files from being deferred, possibly also remove the jQuery migrate when our associated feature is enabled.

**Additional context**
Paths to the files:
/wp-content/plugins/jquery-updater/js/jquery-migrate-3.3.0.min.js
/wp-content/plugins/jquery-updater/js/jquery-3.5.1.min.js

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1252935297/186462?folderId=2135277

**Comment by Tabrisrp** [comment]
The new pattern used in 3.8 should cover the jQuery URL used in this plugin, so this issue is no longer valid.
