### ISSUE TITLE
Compatibility Issue with WPEngine

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#281]
Sometimes the config updater does the following

```
define('WP_DEBUG', false);

# That's It. Pencils down
if ( !defined('ABSPATH') )
define('ABSPATH', dirname(__FILE__) . '/');
require_once(ABSPATH . 'wp-settings.php');

$_wpe_preamble_path = null; if(false){}


define('WP_CACHE', true); // Added by WP Rocket
```

Causing the minify to never work

**Comment by glueckpress** [comment]
@pcfreak30 Can that behaviour be reproduced?

**Comment by pcfreak30** [comment]
its random unfortunately. I have not found any test case yet to narrow, just that on some sites, when initially installing it happens and I have learned to check.

**Comment by arunbasillal** [comment]
Have you ever seen this since @pcfreak30 ?

**Comment by pcfreak30** [comment]
I have not worked on WPEnginbe for a while now, so I can not say.

**Comment by arunbasillal** [comment]
Since we have a good number of WP Engine users and haven't spotted this issue lately, I suppose its best to close this now and revisit if we ever see this again. 

@Tabrisrp Inviting your judgement.

**Comment by GeekPress** [comment]
I'm closing this one as we don't seem to have any bugs reported by other customer since all this time.
