### ISSUE TITLE
Host external CSS and JS files locally when minification is active

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2810]
## What are we proposing to do? 

WP Rocket already combines externally hosted JS files into the combined JS file. And with the recent enhancement #[<u>2689</u>](https://github.com/wp-media/wp-rocket/issues/2689), externally hosted CSS files are also combined into the combined CSS file. 

<p></p>

However, if only minification of CSS or JS is enabled, the external CSS and JS files are not hosted locally. 

<p></p>

With this enhancement, WP Rocket will download and cache the external CSS and JS files on the same server and serve them. 

## Why are we doing this? 

Hosting external CSS and JS files locally can have the following advantages: 

- Reduce the number of DNS resolutions needed. 

- Control the browser cache headers of these files when needed. 

- If the externally hosted files are not minified, we can minify them for our customers. 

- Serve these files from a CDN if the customer uses a CDN service. 

## User expectations and experience. How will we do this feature?

The change will be transparent to new and existing customers and no user input is required. They can exclude any file from this using the “Exclude CSS files” and “Exclude JavaScript files” text areas in the File Optimization tab of WP Rocket. 

## Technical Specs

- Current exclusions need to work as they do now. If a user excludes an external CSS or JS file from combination using the text area in the UI or the filter, exclude these files from minification as well. 

- If the external file is not minified, then minify the contents of the file. 

- Remove references to the external file in the source code.

- Only process files with .css and .js extensions for now. 

## Risks

Since we are not modifying these files or its order, but only changing its location, this feature should be safe and we are not expecting any issues because of this. 

## Acceptance Criteria

- When minification is active, externally hosted CSS and JS files are hosted locally. 

- The reference to the external file is replaced with the local one. 

- When combination is active, these files are combined into the combined CSS or JS file.

- If the file is excluded using the UI or filter, the file is not minified or combined. 

- When CDN is enabled, the files are rewritten to the CDN CNAME

<p></p>

**Edge Cases**

- What if the external CSS changes from time to time (i.e. dynamic CSS)? 

- ^ The user can fix this by excluding this CSS file from minification. This should be really rare. 

## Documentation and Translations

- Update this documentation to include minification - [<u>https://docs.wp-rocket.me/article/39-excluding-external-js-from-concatenation</u>](https://docs.wp-rocket.me/article/39-excluding-external-js-from-concatenation)

Once #[<u>2689</u>](https://github.com/wp-media/wp-rocket/issues/2689) is done and if we create a doc for that, update that as well.

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4947075

**Comment by iCaspar** [comment]
Once #2689 is completed, this becomes a relatively straightforward extension of that.

For each file type (css/js) what is needed:

1. Modify the subscribers for minify CSS/JS to pass the `AssetsLocalCache` as a dependency to the `Minify` classes
2. In the `Minify` classes, remove the `is_external_file()` check from the `optimize()` method
3. In `replace_url()`, use `is_external_file()` to determine if we should process the passed URL as an internal one like currently, or use the `AssetsLocalCache` to save the local copy if external
4. Update our tests.

Effort: [S] + [S] -- One for each file type.
So, [M] in all.

**Comment by Tabrisrp** [comment]
Blocked waiting for #2785 to be merged

**Comment by Tabrisrp** [comment]
Unblocking now that #2785 is merged

**Comment by Tabrisrp** [comment]
Thinking about this more, shouldn't we have a default exclusion for google analytics and facebook pixel scripts, since we have one-click add-on taking care of that already?

**Comment by GeekPress** [comment]
@Tabrisrp It's a good question 👍 

For Facebook Pixel, it's an inline JS. We won't need to exclude it.

For Google Analytics, let's exclude it

**Comment by webtrainingwheels** [comment]
@Tabrisrp In the CSS exclusion section, currently (alpha-2) the "more info" link is going to: https://docs.wp-rocket.me/article/39-excluding-external-js-from-concatenation/

Could we change that to the following:
https://docs.wp-rocket.me/article/1131-resolving-issues-with-css-minify-combine
This doc will be updated with info about excluding external files.
