### ISSUE TITLE
Add apply_filter to CDN rewrite_srcset

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2812]
Our CDN rewrite looks for specific patterns of `srcset`
If developers are using a custom attribute name, we won't detect it for rewriting. We could make the $pattern filterable to address this. 

Related ticket: https://secure.helpscout.net/conversation/1200037694/174367?folderId=377611
>Can you guys please add an apply_filter() to the $pattern? That is the best solution as it makes WPRocket a lot more flexible for all situations. As your code currently is assuming data-srcset/data-lazy-srcset, but due to plugin + theme incompatibilities, themes have to have their own custom attributes for things like this.

**Comment by GeekPress** [comment]
I checked the website and all attributes are using the CDN. I suppose that the user found another way to apply our CDN, isn't it?

If so, a filter isn't required.

**Comment by codetipi** [comment]
@GeekPress Not quite - I ended up editing the plugin's CDN.php file to manually change the pattern for it to work. 

Please can you add a filter so that I don't have to edit core plugin files after each update :)

Thanks in advance!

**Comment by GeekPress** [comment]
@codetipi Thanks for the feedback ;)

We will add a filter there.

**Comment by engahmeds3ed** [comment]
Reproduce the issue :white_check_mark:
Tested locally with other lazyload attributes and found the need to use a filter here.

Scope a solution :white_check_mark:

https://github.com/wp-media/wp-rocket/blob/28e7b00cb74df0a18b79c65631d0ba438e019db8/inc/Engine/CDN/CDN.php#L63

Here we can apply filter `rocket_cdn_srcset_attributes` so it will return/change the following part of the regex `data-lazy-|data-` so if for example our theme is using the attribute `data-wow-src` we will use this filter to return `data-lazy-|data-|data-wow-`.
I think this is better than add the full regex to the filter not to break the full main functionality.

Estimate the effort :white_check_mark:
Effort [XS].
