### ISSUE TITLE
Auto-compatibillity with WordPress.com hosting

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2814]
**Describe the solution you'd like**
WordPress.com is using their own page caching system. Because of that, WP Rocket is banned from this hosting. When someone activate WP Rocket, a notice is displayed to let the user know the plugin has been automatically disable to avoid conflict with their caching system.

To avoid any conflicts, and be possible to activate WP Rocket on wp.com, we must disable our page caching if the current website is hosted on wp.com 

**Additional context**
If possible, we should not try to write anything into advanced-cache.php. Having an empty advanced-cache.php like we are doing on WP Engine isn't a solution. This file is used by their page caching system.

On wp.com, another performance plugin is automatically installed on new website: [Page Optimize](https://wordpress.org/plugins/page-optimize/). This plugin can concatenate CSS and JS + add `async` or `defer` on JS files.

We will have to grey out our options if we notice these options are activated (like we do with Autoptimize).

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
#### inc/functions/files.php
- Add a new filter `rocket_generate_advanced_cache_file` with a boolean value, in a conditional, to early bail-out if the value is `true`

#### inc/Plugin.php
- Add the `wordpresscom` subscriber to the list of common subscribers in `init_common_subscribers()`

#### inc/main.php
- Check for `WPCOMSH_VERSION` in `rocket_activation()`, to add the filter before trying to write in `advanced-cache.php` file
- Update `rocket_deactivation()`, to not try to write a blank `advanced-cache.php` file when `WPCOMSH_VERSION` is set

#### inc/ThirdParty/Hostings/WordPressCom.php
Add a new third party subscriber `WordPressCom`. In this subscriber, we will:
- Detect wp.com by using the constant `WPCOMSH_VERSION`
- Prevent writing the cache files with a callback on `do_rocket_generate_caching_files`
- Prevent mandatory cookies with a callback on `rocket_cache_mandatory_cookies`
- Prevent displaying the Varnish addon with a callback on `rocket_display_varnish_options_tab`
- Prevent displaying `advanced-cache.php` notice, by removing the `AdminSubscriber::notice_advanced_cache_permissions` callback on `admin_notices`
- Prevent trying to write in the `advanced-cache.php` file, by adding a callback on filter in `rocket_generate_advanced_cache_file` with a value of `true`

### Other considerations
- There is no way to clear the built-in cache manually. It's clearing itself after 300 seconds
- For the pre-installed `Page Optimize` plugin, I'm thinking to add it to the list of incompatible plugin, as it is doing less than WP Rocket, and it can be deactivated
- Currently WP Rocket is automatically detected and can't be activated without changing the folder name, so we'll have to confirm with them that we are allowed before pushing this in an update

### Estimate the effort ✅ 
I believe it's an `[M]` effort, there is quite a lot to do and to test (automatic + manual)

**Comment by GeekPress** [comment]
> For the pre-installed Page Optimize plugin, I'm thinking to add it to the list of incompatible plugin, as it is doing less than WP Rocket, and it can be deactivated

@Tabrisrp Let's go with your suggestion.

**Comment by iCaspar** [comment]
Merged/closed with PR 2851
