### ISSUE TITLE
Auto-compatibility with RunCloud hosting

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2817]
RunCloud (https://runcloud.io/) has its own plugin to clear their NGINX FastCGI cache:
https://blog.runcloud.io/runcloud-hub/

It means that customers probably won't use our NGINX Helper compatibility.

**Current state**
We can't clear their cache.

**Ideal state**
It would be great to have compatibility with their RunCloud Hub plugin to clear the cache whenever needed. Just as we do with NGINX Helper.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@webtrainingwheels It seems we don't have an account/ access on this hosting. Could you contact them and take the lead on that?

**Comment by GeekPress** [comment]
Runcloud fixed the issue on their side:
https://runcloud.io/changelog

I tested and the auto-compatibility is working well.

**Comment by slomeli79** [comment]
> Runcloud fixed the issue on their side:
> https://runcloud.io/changelog
> 
> I tested and the auto-compatibility is working well.

Does this mean that the "never cache URLs" setting in WP Rocket need to be duplicated within the Runcloud Hub settings for exclusion as well? I'm posing the same question to the Runcloud team. Thanks in advance.

**Comment by GeekPress** [comment]
@slomeli79 I don't know how the purging feature is working. You can easily do the test yourself to know if you have to duplicate the exclusions. But I think it should be the case ;)
