### ISSUE TITLE
Inline JavaScript is not minified when HTML minification is on

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2818]
Inline JavaScript is not minified when HTML minification is on.
I've tested this with the following versions:
* 3.6.1
* 3.5.5.1
* 3.4.4

This is because of the HTML options not including the method to `minify_inline_js` that handles minification of inline JavaScript:
https://github.com/wp-media/wp-rocket/blob/0455940481777146a4677dbf59ed928223351639/inc/classes/subscriber/Optimization/class-minify-html-subscriber.php#L69-L70

**To Reproduce**

1. Add some inline JavaScript: http://snippi.com/s/wjutn82
2. Make sure HTML minification is enabled.
3. Check the source code of the page. JavaScript will not be minified.

**Expected behavior**
Inline JavaScript should be minified.

**Additional context**

HTML minification will be removed in one of the next WP Rocket versions, but this is an easy fix if we decide to do it.

**Related ticket**

https://secure.helpscout.net/conversation/1204067401/175422?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@vmanthos This is a normal behavior. We had issues by automatically apply the minification of inline JS scripts during HTML minification.

As we are going to remove the HTML minification and everything is ready about it for 3.7, I'm closing this issue.
