### ISSUE TITLE
Add a filter to exclude taxonomies in Purge::get_post_terms_urls()

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2820]
Add a filter to exclude taxonomies based on third party needs in here:
https://github.com/wp-media/wp-rocket/blob/0455940481777146a4677dbf59ed928223351639/inc/Engine/Cache/Purge.php#L178-L185

Add a filter `rocket_exclude_post_taxonomy` 

Based the Review from this PR: https://github.com/wp-media/wp-rocket/pull/2750

**Comment by GeekPress** [comment]
@crystinutzaa What will be the usage of this filter? I tried to check the PR, but I didn't find a comment / thread about that suggestion.

**Comment by crystinutzaa** [comment]
@GeekPress the filter will allow to exclude more taxonomies and not only `product_shipping_class` . Right now only `product_shipping_class` taxonomy is excluded, however there could be users which would want to exclude more taxonomies from auto purge.

**Comment by GeekPress** [comment]
@crystinutzaa Thanks for the feedback :)

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
No need to reproduce.

**Identify the root cause** ✅ 
https://github.com/wp-media/wp-rocket/blob/0455940481777146a4677dbf59ed928223351639/inc/Engine/Cache/Purge.php#L178-L185
Only `product_shipping_class` is excluded from taxonomy purge.

**Scope a solution** ✅ 
The solution is to add a filter `rocket_exclude_post_taxonomy` which will return an array and will allow to exclude more taxonomies.

**Effort** ✅ 
Effort `[S]` , I think Unit & Integration tests will need almost all the effort
