### ISSUE TITLE
Slider images no longer showing after upgrade from 3.5.5.1 to 3.6

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#2821]
**Describe the bug**
Slider images using inline style background images stopped showing when using WP Rocket lazy load.

**To Reproduce**
1. Enable WP Rocket lazyload for images.
2. See error: images disappearing and data-ll-status="error" added

**Expected behavior**
Slider images to show when using WP Rocket lazyload.

**Screenshots**
No.

**Additional context**
Porto theme 5.3.2
Owl Carousel 2.3.4
The issue is fixed if excluding the images from the lazyload using our helper plugin.
Case - https://secure.helpscout.net/conversation/1202881379/175130/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
After checking, I found that this issue is related to this issue: https://github.com/wp-media/wp-rocket/issues/2822
As you can see on the following HTML(extracted from the affected site as an example)
```
<div class="porto-ultimate-content-box vc_custom_1584201052538 has-content-pos justify-content-center" style="background-image:url(&#039;https://www.bucuriajucariilor.ro/wp-content/uploads/2020/03/13239-1.jpg&#039;);background-size: cover;background-repeat: no-repeat;background-position: center center;background-color: rgba(0, 0, 0, 0);box-shadow: none;min-height:500px;">
    <div class="vc_btn3-container  mb-0 vc_btn3-left vc_custom_1589319544717">
        <a class="vc_btn3 vc_btn3-shape-default btn btn-modern btn-sm btn-dark" href="https://www.bucuriajucariilor.ro/categori/lumea-desenelor-animate/" title="">Lumea Desenelor animate</a> </div>
</div>
```
so the problem mainly on the quote special characters `&#039;`

**Comment by GeekPress** [comment]
@engahmeds3ed Thanks for the feedback! I'm closing this one as it's a « duplicate » of #2822

**Comment by engahmeds3ed** [comment]
sorry for changing the labels as I opened the labels box on the same time u were changing.
