### ISSUE TITLE
background-image lazyloading breaks when escaped quotes are included in the url

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2822]
When escaped quotes are included in a `background-image` like this:
```HTML
<div style="background-image: url(&quot;https://www.example.com/wp-content/uploads/2018/04/telephonie-ip-couleur.jpg&quot;);" class="image_article bkgd-img"></div>
```
the `$url['url']` added here also includes them:
https://github.com/wp-media/rocket-lazyload-common/blob/fde493535ca389882484327af32c99c839d2527f/src/Image.php#L75

This breaks the lazyload of such images.

I found that the following escaped quotes are incompatible:
* `&#39;`
* `&quot;`

**To Reproduce**

1. Add a `background-image` with this markup: 
```HTML
<div style="background-image: url(&quot;https://www.example.com/wp-content/uploads/2018/04/telephonie-ip-couleur.jpg&quot;);" class=""></div>
```
2. Visit the page where the image is included.
3. The image won't be visible.

**Expected behavior**

Images with escaped quotes should be properly lazyloaded.

**Related Ticket:**
* https://secure.helpscout.net/conversation/1204052553/175417?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
A little bit different escaped quote:
- &#039;

Related ticket:
https://secure.helpscout.net/conversation/1201738666/174808?folderId=2415573

**Comment by hellofromtonya** [comment]
This problem was introduced in 3.6 when we upgraded to the version 16.1 lazyload script.

**Comment by hellofromtonya** [comment]
The PR for this issues in the `rocket-lazyload-common` repo https://github.com/wp-media/rocket-lazyload-common/pull/77
