### ISSUE TITLE
3.6.1 CSS files don't load on Firefox when using Fallback CPCSS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2826]
Steps to reproduce:

- Enable Fallback Critical CSS on the site
- Load the site in Firefox
- The layout will be broken. CSS files are present in page source, but not loaded. 
- LoadCSS library is not present

WPR version: 3.6.1

**Comment by hellofromtonya** [comment]
This bug was introduced in 3.6.1.  Lucy applied the changes to validate the implementation.

**Comment by webtrainingwheels** [comment]
I forgot to add the ticket links 🤦 
https://secure.helpscout.net/conversation/1205743863/175849/
https://secure.helpscout.net/conversation/1192993610/172355/
https://secure.helpscout.net/conversation/1201122789/174627/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1206961745/176130?folderId=377611

**Comment by blogtutor** [comment]
Just wanted to chime in that we've been having quite a few clients report this issue to us as well... So I'm glad to see you're working on 3.6.2 as fast as possible!  Thanks!  :)
