### ISSUE TITLE
Load JavaScript deferred prevents https://reviews.io/ widget from being displayed

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#2833]
**Before submitting an issue please check that you’ve completed the following steps:**
- WP Rocket Version 3.6.1
- https://github.com/wp-media/wp-rocket/search?q=reviews.io&unscoped_q=reviews.io

**Describe the bug**
Load JavaScript deferred prevents https://reviews.io/ widget from being displayed.

**To Reproduce**
1. Integrate https://reviews.io/ on a site.
2. Enable Load JavaScript deferred.
3. Visit the website.
4. The widget is not displayed.

**Expected behavior**
Add widget.reviews.io to the exclusion list here: 
https://github.com/wp-media/wp-rocket/blob/0455940481777146a4677dbf59ed928223351639/inc/functions/options.php#L413

**Additional context**
Ticket https://secure.helpscout.net/conversation/1205855513/175882?folderId=2675957.
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1593447592324200.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@piotrbak @vmanthos As the exclusion has been tested with a mu-plugin and validated by the customer, can one of you directly do a pull request with the new exclusion?

**Comment by hellofromtonya** [comment]
@GeekPress Piotr created a PR, which is now merged into `develop`.

**Comment by james83848** [comment]
Share some more courses about JS at [https://www.toiletvibe.com/](https://www.toiletvibe.com/)
