### ISSUE TITLE
Preload CSS Firefox Not Supported

### ISSUE THREAD

**Issue by alihs** [wp-media/wp-rocket#2838]
So With the 3.6 update, when the critical CSS is removed the CSS is replaced with
<link href="/cache/min/1/48a14e3c62af2d5ca54db452a9766987.css" as="style" onload="this.onload=null;this.rel='stylesheet'" data-minify="1" rel="preload">

The above is not supported in Firefox, at this time. Has broken my site and many others using the most recent WPRocket.

**To Reproduce**
Just have the most recent version and open up the site on Firefox

**Expected behavior**
Should either have a polyfil or not be used.

**Comment by arunbasillal** [comment]
Hello @alihs, thanks for the report. 

Are you using Fallback CPCSS? If that is the case, then this is a duplicate of https://github.com/wp-media/wp-rocket/issues/2826 schedule to be fixed in 3.6.2

**Comment by alihs** [comment]
Yes, i am. So yes it seems to be a duplicate. Closing it in favor of https://github.com/wp-media/wp-rocket/issues/2826
