### ISSUE TITLE
Automatically deactivate other conflicting caching plugins

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2844]
**Is your feature request related to a problem? Please describe.**
Yes. It will avoid this kind of problem https://github.com/wp-media/wp-rocket/issues/1783

**Describe the solution you'd like**
Before to write into advanced-cache.php, we could check if another caching plugin is installed to avoid any conflicted problems and automatically deactivate it. 

We could do that for all plugins listed here:
https://github.com/wp-media/wp-rocket/blob/master/inc/admin/ui/notices.php#L110

As we know these plugins aren't compatible with WP Rocket, let's simplify our user experience by avoiding an extra step to deactivates the plugins.

We will display a notice that let the users know we deactivated these plugins to avoid conflicts. Then, it will be at their own risk to re-activate them.

**Comment by iCaspar** [comment]
Reopens issue #1783

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 

That could be a good application to our activation process update from #2860 

We can add a new class `DeactivateCachePlugins`, which would implement the `activate` method.

Steps to perform:
- Get list of plugins, and foreach
- if the plugin is active (check with `is_plugin_active()`)
- call the `deactivate_plugins()` ([source](https://developer.wordpress.org/reference/functions/deactivate_plugins/)) function
- add the plugin to a transient `rocket_deactivated_cache_plugins`

For the notice:
- in the Activation module, add a Subscriber
- the subscriber will add one callback method for `admin_notices`
- In the method, read the transient, and display a message warning that the following plugins have been deactivated to prevent incompatibilities

### Estimate the effort ✅ 
Effort `[S]`, 2 new classes to create with one public method each, tests to write too

**Comment by jazir555** [comment]
Please do not include flying pages in the list of plugins that are automatically deactivated. You guys claim there is an incompatibility with the plugin, yet I experience zero issues having it active.

**Comment by piotrbak** [comment]
This is handled by the backend currently
