### ISSUE TITLE
Auto-Purge Cloudflare

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#285]
add hooks on `after_rocket_purge` and related to run `rocket_purge_cloudflare`.

**Comment by glueckpress** [comment]
While we appreciate input, but please be specific. A hook named `after_rocket_purge` does not exist.

What would you want to be added where, and—most importantly—to solve what kind of problem? 
Thanks.

**Comment by pcfreak30** [comment]
Sorry after_rocket_clean_domain, after_rocket_clean_post, after_rocket_clean_term.

Basically if CF is on CDN/CF caching should get purged when content is updated/expired.

**Comment by arunbasillal** [comment]
Same as https://github.com/wp-media/wp-rocket/issues/1521

Closing this one in favour of that.
