### ISSUE TITLE
Prevent creation of advanced-cache.php in WP Engine

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2855]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
- On WP Engine, we do not need to write anything into `advanced-cache.php`, but still we create the file on WP Rocket activation, deactivation and settings update.
- With WP Rocket 3.6.1, we actually write contents into the file. (Issue with some more details here: https://github.com/wp-media/wp-rocket/issues/2896)

Video: https://youtu.be/6TqcUQS1M6k

**To Reproduce**
- Install WP Rocket 3.4.4 on WP Engine. Empty `advanced-cache.php` is created on activation and deactivation
- Install WP Rocket 3.6.1 on WP Engine. `advanced-cache.php` is not empty. 

**Expected behavior**
Since we do not intend to use the file on WP Engine as per: https://github.com/wp-media/wp-rocket/blob/7838b137afad05907f6281d114c72f8c34423de8/inc/ThirdParty/Hostings/WPEngine.php#L39

we should not create the file, nor modify it. 

**Additional context**
Feedback from Remy - https://wp-media.slack.com/archives/GUT7FLHF1/p1593444250001500

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
PR #2851 will have a new filter for short-circuiting writing into `advanced-cache.php` (which we need to do for WordPress.com. Maybe we can roll the fix for this into there.

**Comment by vmanthos** [comment]
**Related tickets:**
* https://secure.helpscout.net/conversation/1226743457/180582/
* https://secure.helpscout.net/conversation/1231549191/181601

**Comment by iCaspar** [comment]
Merged/closed with PR 2851
