### ISSUE TITLE
Add code.jquery.com to the list of external files to exclude from Safe mode for jQuery

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#2859]
**Before submitting an issue please check that you’ve completed the following steps:**
- Version 3.6.1 (3.6.2 in staggered)
- No other reports: https://github.com/wp-media/wp-rocket/search?q=code.jquery.com%2Fjquery&type=Commits

**Describe the bug**
Load JavaScript deferred defers the jQuery file from https://code.jquery.com/jquery-1.12.4.min.js.

**To Reproduce**

1. Integrate https://code.jquery.com/j on a site.
2. Enable Load JavaScript deferred and the Safe mode for jQuery.
3. Visit the website.
4. See the jQuery is not defined error in the Console.

**Expected behavior**
Add the code.jquery.com to the list of common external jQuery files, not sure if here:
https://github.com/wp-media/wp-rocket/commit/bd8aa17d7a35899a5ae3b10f9596211b4752de1d

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1217809098/178617?folderId=2675957.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related ticket: https://secure.helpscout.net/conversation/1234956530/182400
