### ISSUE TITLE
W3C error: Element source is missing required attribute srcset when LazyLoad is enable

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2862]
**Describe the bug**
When we LazyLoad the images, _srcset_ becomes **_data-lazy-srcset_**.
​
The solution would be to leave the _srcset_ attribute in place. But that would be only to satisfy the validator. Otherwise, this has no negative impact.

**To Reproduce**
1. Activate LazyLoad on a page/post with _srcset_ attributes
2. Test it in https://validator.w3.org/nu/

**Expected behavior**
There should be no error but you’ll get this one:
`error: Element source is missing required attribute srcset`

**Screenshots**
![Image 2020-07-09 at 8 59 12 AM](https://user-images.githubusercontent.com/11939512/87007447-996b8c80-c1c2-11ea-9b2f-4d5850f56299.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1218747414/178841/

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1293740508/197894/

**Comment by GeekPress** [comment]
As it's very trivial and has no impact on the website, we won't fix this problem.
