### ISSUE TITLE
New Attributes Beacon Messages

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#2863]
To display more targeted messages using Beacon messages, we need to create new attributes to trigger these messages.
We already have attribute = status with 3 values: new, active, expired.

We would like to create 3 new attributes:

attribute = rocketCDN
values: yes, no
N.B. no matter if the user is new, expired or active, no matter the license.

attribute = imagify
values: no, free, paying
N.B. this is for cross-sell purposes, no matter if the user is new, expired or active, no matter the license.

attribute= active_license
values: single, plus, infinite
N.B. with this attribute we would like to target only non expired users.

**Comment by Tabrisrp** [comment]
@jbma Is the best way to get the Imagify account type, to request the API on `https://app.imagify.io/api/users/me/`, using the API key (if it's available in the DB), and use the `account_type` attribute returned?

What are the possible values for this attribute?

**Comment by jbma** [comment]
@Tabrisrp Yes I think `https://app.imagify.io/api/users/me/` is the best.
Probably would be easier to check `plan_id`.
If `plan_id` = 1, it's a free user. If it's >1 it's a paying (monthly/yearly subscription).

For one time plan you can check `extra_quota` value. If it's > 499 that means the user has bought a one time plan.

**Comment by GeekPress** [comment]
@Tabrisrp Here how are getting the info for Imagify and RocketCDN on the website:
 - Imagify: https://github.com/wp-media/woocommerce-rocket/blob/master/inc/classes/class-customer.php#L37
- RocketCDN: https://github.com/wp-media/woocommerce-rocket/blob/master/inc/classes/class-customer.php#L70

**Comment by GeekPress** [comment]
After discussing with @Agathemed we don't need that anymore. I'm closing it.
