### ISSUE TITLE
Make our Google tracking add-on compatible with Exactmetrics plugin

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2864]
**Describe the bug**
When [Google Analytics Dashboard for WP by ExactMetrics ](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/) (+1M installs) is installed, the inline JS that will be used contains this line:
`(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker')`
which will be replaced by this line when our Google tracking add-on is enable:
`(window,document,'script','https://domainname.com/wp-content/cache/busting/google-tracking/ga-871c3xxxxxxxxxxxxxxxxxxxx31212c.js','__gaTracker');`
This leads to a tracking issue.

**To Reproduce**
1. Install [Google Analytics Dashboard for WP by ExactMetrics ](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/)
2. Follow the install wizard
3. Check the JS inline script that will begin with `<!-- This site uses the Google Analytics by ExactMetrics plugin v6.1.0 - Using Analytics tracking - https://www.exactmetrics.com/ -->`
3. active our Google tracking add-on

**Expected behavior**
This line shouldn’t be modified even when our add-on is ON.
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1217952700/178656?folderId=1213662

**Comment by GeekPress** [comment]
@WordPresseur Are we sure the problem was related to that change? With 1M+ active installs, I'm surprised to not have more reports about this potential bug.

**Comment by remyperona** [comment]
Closing this issue as Google tracking add-on will be removed in WP Rocket 3.9.
