### ISSUE TITLE
3.6.2 Encoding issues with DOM Module for Non-Latin Characters causing broken layouts

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2866]
`DOMDocument` encoding sets the `<meta>` tag but not the overall HTML encoding. When creating the DOM and saving it back to a string, the UTF-8 encoding is not respected. As such, it creates encoded entities and in some cases can break the layout.

**Comment by hellofromtonya** [comment]
Fixed in PR 6 of the DOM Module repo https://github.com/wp-media/module-dom/pull/6

**Comment by hellofromtonya** [comment]
This ticket might be this problem...maybe https://secure.helpscout.net/conversation/1219841185/179108

**Comment by ScottTravisHartley** [comment]
I just want to highlight I have run into this issue as well on many sites. The temporary fix I have stumbled across was to turn off the optimize css delivery option.

**Comment by hellofromtonya** [comment]
Hey @ScottTravisHartley, could you try the PR on one of your sites to see if it resolves the problem for you with Optimize CSS delivery option turned on?

**Comment by ScottTravisHartley** [comment]
Sure thing will do

**Comment by hellofromtonya** [comment]
Thanks @ScottTravisHartley 🎉  Really appreciate it.

**Comment by ScottTravisHartley** [comment]
Well, I am not getting any odd characters but with the optimize critical css feature the page layout is still very much broken. Granted this could be an issue with how I implemented the update. 

I went to plugins/wp-rocket/inc/Engine/DOM  -> replaced the contents of HTMLDocument.php with https://raw.githubusercontent.com/wp-media/module-dom/master/HTMLDocument.php

Page outputs like: 
![image](https://user-images.githubusercontent.com/45110039/87096156-cc843f00-c207-11ea-9212-81edb0ae410a.png)

**Comment by ScottTravisHartley** [comment]
The issue does go away when I roll back to 3.5.5.1 (which I just did on the site)

**Comment by hellofromtonya** [comment]
That's interesting. Hey @ScottTravisHartley, could I work with you on it to discovery the root cause? If yes, could you create a Support Ticket where we can talk in private and you can share credentials with me?

**Comment by ScottTravisHartley** [comment]
Sure thing

**Comment by hellofromtonya** [comment]
Thanks @ScottTravisHartley. Once the ticket comes in, I'll assign to myself and ping you.

**Comment by ScottTravisHartley** [comment]
Sent it in!

**Comment by ScottTravisHartley** [comment]
Not really sure why but the name it auto responded with was -> Bassel Enab

**Comment by hellofromtonya** [comment]
I saw that. Replying to you now.

**Comment by dawnbirth** [comment]
We're facing the same issue, on one site we rolled back to 3.5.5.1 and the issue was solved and on the other one we disabled the optimize css delivery and the issue is solved also.

**Comment by vmanthos** [comment]
Related tickets:
* https://secure.helpscout.net/conversation/1222072945/179670?folderId=2135277
* https://secure.helpscout.net/conversation/1222086342/179674/

**Comment by NataliaDrause** [comment]
Related ticket: https://secure.helpscout.net/conversation/1228518886/180982/

**Comment by NataliaDrause** [comment]
Another one: https://secure.helpscout.net/conversation/1230433629/181369

**Comment by hellofromtonya** [comment]
Closing as the DOM Module has moved out of Rocket.
