### ISSUE TITLE
3.6.2 LazyLoad and Optimize CSS Delivery break layouts when both are enabled

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2871]
When LazyLoad and Optimize CSS Delivery options are both enabled in 3.6.2, it breaks the layout when there's malformed HTML.

We validated this on @ScottTravisHartley's website. https://secure.helpscout.net/conversation/1220716013/179344

**To Reproduce**
1. Use @ScottTravisHartley's website
2. Turn on Optimize CSS Delivery and LazyLoad. Save.
3. View the site incognito
4. Notice the images are not rendering correctly and the layout is broken.

Next, turn off LazyLoad (images and iframe/videos). Save. Critical CSS generates. Refresh the main page and the site renders correctly. 

Turn off Optimize CSS Delivery and turn on LazyLoad. Save. Refresh. Site renders correctly.

**Expected behavior**
We expect the site to render correctly when one or both options are turned on.

**Additional context**

When both are off:

```html
<div class="mainVisualCover" style="background: url('https://xxxx/assets/uploads/2017/01/Top-Page-Video-Logos-hrtech2018.png') no-repeat left center; background-size: cover;"></div>
<img src="https://xxxx/assets/uploads/2017/01/main_visual_sp-1024.png" alt="Main Visual">
<video src="https://xxxx/assets/uploads/2017/01/movie.mp4" autoplay="" preload="auto" poster="https://xxxx/assets/uploads/2017/01/main_visual.png"></video>
```

LazyLoad is on and Optimize CSS Delivery is on:
```html
<div class="mainVisualCover" style="background: url('https://xxxx/assets/uploads/2017/01/Top-Page-Video-Logos-hrtech2018.png') no-repeat left center; background-size: cover;"></div>
<img src="https://xxxx/assets/uploads/2017/01/main_visual_sp-1024.png" alt="Main Visual" class="lazyloaded" data-ll-status="loaded">
<noscript><img src="https://xxxx/assets/uploads/2017/01/main_visual_sp-1024.png" alt="Main Visual"></noscript>
<video src="https://xxxx/assets/uploads/2017/01/movie.mp4" autoplay="" preload="auto" poster="https://xxxx/assets/uploads/2017/01/main_visual.png"></video>
```

LazyLoad is off and Optimize CSS Delivery is on:
```html
<div class="mainVisualCover" style="background: url('https://xxxx/assets/uploads/2017/01/Top-Page-Video-Logos-hrtech2018.png') no-repeat left center; background-size: cover;"></div>
<img src="https://xxxx/assets/uploads/2017/01/main_visual_sp-1024.png" alt="Main Visual">
<video src="https://xxxx/assets/uploads/2017/01/movie.mp4" autoplay="" preload="auto" poster="https://xxxx/assets/uploads/2017/01/main_visual.png"></video>
```

LazyLoad is on and Optimize CSS Delivery is off:
```html
<div class="mainVisualCover" style="background: url('https://xxxx/assets/uploads/2017/01/Top-Page-Video-Logos-hrtech2018.png') no-repeat left center; background-size: cover;"></div>
<img src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E" alt="Main Visual" data-lazy-src="https://xxxx/assets/uploads/2017/01/main_visual_sp-1024.png">
<noscript><img src="https://xxxx/assets/uploads/2017/01/main_visual_sp-1024.png" alt="Main Visual"></noscript>
<video src="https://xxxx/assets/uploads/2017/01/movie.mp4" autoplay="" preload="auto" poster="https://xxxx/assets/uploads/2017/01/main_visual.png"></video>
```

Notice the differences. These are clues.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by hellofromtonya** [comment]
@engahmeds3ed @Tabrisrp Can you take a look at the LazyLoad common library to see what could be the problem?

**Comment by hellofromtonya** [comment]
The root cause is [libxml library less than 2.8.0](http://xmlsoft.org/news.html) has a bug in it: `HTML parser error with <noscript> in the <head>`. This bug was fixed in version 2.8.0

>2.8.0: May 23 2012
>- Bug fixes: … HTML parser error with <noscript> in the <head>

@ScottTravisHartley web server is using a libxml 2.7.8.

Our LazyLoad common library is adding a `<noscript>` as the last element before the closing `</head>` tag:

```html
    <noscript><style id="rocket-lazyload-nojs-css">.rll-youtube-player, [data-lazy-src]{display:none !important;}</style></noscript>
</head>
```

What happens? 

Libxml can't handle the `<noscript>` in the `<head>`. In the DOM Module, when the first `<noscript>` is encountered in the `<head>`, the DOMDocument adds a `<body>` element and shifts that `<noscript>` and the rest of the stuff after in the `<head>` into the `<body>`. 

How can we handle this?

1. We'll move the LazyLoad `<noscript>` to the first element after the opening `<body>` tag. 
2. We'll need to figure out how to grab all of the `<noscript>` elements in the `<head>` _before_ loading the HTML string into the DOM and then reinsert them back into the `<head>` after processing. Why? To respect the order of the CSS rules.

**Comment by ScottTravisHartley** [comment]
For additional context, the client is hosted on a GrowBig plan on SiteGround so we have no way of updating it either!

**Comment by hellofromtonya** [comment]
@ScottTravisHartley Totally agree. Rarely do customers have the ability to update these types of libraries.

We have a solution that will take care of it. We'll work on that today and early next week.

**Comment by djflores** [comment]
Hey there! Do you guys have an estimated time on when this fix will be live? I know of quite a few sites that are currently experiencing this and the only solution we've found, is to turn off image lazy loading and optimize CSS delivery.

Thanks!

**Comment by hellofromtonya** [comment]
@djflores Just merged it into the new DOM Module with the fix to this particular issue. We're targeting 🤞 3.6.2.1 release on Monday. 🤞

**Comment by NicoleMediavine** [comment]
@hellofromtonya 
Are you guys halting the rollout of 3.6.2 due to this issue?

**Comment by hellofromtonya** [comment]
Hello @NicoleMediavine 👋, Yes we did this afternoon and rolled back the released version to 3.6.1. For those customers who had not yet updated, they will see the 3.6.1 version as the latest.

**Comment by hellofromtonya** [comment]
Update: The fix for this specific issue is now built. This weekend and Monday, we will be testing it. On track for 3.6.2 on Monday.

**Comment by djflores** [comment]
Hey @hellofromtonya will this be merged in on Tuesday now?

**Comment by hellofromtonya** [comment]
Closing this ticket as the DOM Module has been moved out of Rocket.
