### ISSUE TITLE
3.6.2 Lazy Load Images Breaks With Certain Alt Text Values

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2873]
I first noticed this on a client site because his output was showing ™“> where his image was. He added the alt text as it was suggested to add the focus keyphrase from his SEO plugin. 

I was able to replicate it on my own website by adding the following HTML on a blank page using a code block. 
`<img src="https://www.sertmedia.com/wp-content/uploads/2020/07/pexels-photo-1166991.jpeg" alt="TEAgel<sup>™</sup>">
`
 I set up a test page: https://www.sertmedia.com/test-broken-lazy-load/

This is the output:

`<img src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E" alt="TEAgel<sup data-lazy-src=" https:><noscript><img src="https://i0.wp.com/www.sertmedia.com/wp-content/uploads/2020/07/pexels-photo-1166991.jpeg" alt="TEAgel<sup></noscript>™</sup>&#8220;>`

With lazy load enabled (I have optimized CSS delivery disabled to eliminate the possibility it was related to #2871)

In both sites, I am running the latest version of WordPress Rocket 3.6.2 rolling back to 3.5.5.1 doesn't resolve the issue. I will also say this technically passes the W3C validator. 

I also forgot to mention that if the image is added via the media library (which by default includes a srcset attribute the image outputs correctly), I also added that to the test page to show it spits it out correctly.

**Comment by Tabrisrp** [comment]
Hey Scott,

We saw the issue yes, we have a fix in preparation here: https://github.com/wp-media/rocket-lazyload-common/pull/81

**Comment by ScottTravisHartley** [comment]
Yall are just too quick for me thanks!
