### ISSUE TITLE
Whitelabel Should Remove Beacon Support Button

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2876]
If you're using the constant for whitelabel 
`define ('WP_ROCKET_WHITE_LABEL_ACCOUNT', true);`

It doesn't make a lot of sense to me to load the contact support button when Whitelabel is active which is meant to remove the account information. I think if Whitelabel is active the button should stop loading, all together.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `WP_Rocket\Engine\Admin\Beacon\Beacon::insert_script()`:

- add an additional conditional check for `rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT' )`
- update the tests & fixtures to add this case

### Estimate the effort ✅
Effort `[XS]`
