### ISSUE TITLE
Auto-enable Google Fonts Optimization

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2877]
## What are we proposing to do? 

With this update, we will be removing the UI option to “Optimize Google Fonts”. 

![](https://lh3.googleusercontent.com/28A3HklQS5YBBiJtzqmah4S9BqxuT-wtVVLNjd5Uj29j1SRd-diQaEc3LJ007MaspTHJRhnri15GxZWCSg6oU_xRUL3npxfRXU054-K-3ctvZcbpPxThccU6G6GuBiBbW-nyNsuz)

We will remove the « Basic Settings » section too as « Minify HTML » will be removed too from the UI.

## Why are we doing this? 

Optimize Google Fonts is one of the options that is [<u>enabled by default</u>](https://github.com/wp-media/wp-rocket/blob/da65dc571fcab9c2c3bc7fad6964d684202abae0/tests/Fixtures/inc/admin/rocketFirstInstall.php#L35) in WP Rocket. Based on the data we have from Mixpanel, about 94% of our customers keep it enabled. 

![](https://lh4.googleusercontent.com/EXebaVl1SlSiHGiXNIrpkb1KlGdxRq67ODU-WqO4fy5NO35FLOKLCKW9evE8o4QX9AhfbOXCk4G5a3vZMsMabE3zoDe0XXsKIhH5fIAen8PdVKQ48rQo6E1EgjTxRROlmDgRU_Fd)

<p></p>

There are two probable causes why the rest of the users have disabled this feature (thanks to Jonathan)

<p></p>

- They do not use Google fonts on their website (like [<u>https://wp-rocket.me/</u>](https://wp-rocket.me/))

- They had an issue with this feature. 

<p></p>

On the support side, we do not have many issues generated by this option and often when these are reported, we fix them (example [<u>#2561</u>](https://github.com/wp-media/wp-rocket/issues/2561), [<u>#2328</u>](https://github.com/wp-media/wp-rocket/issues/2328))

<p></p>

So in summary, removing this option from the UI can make WP Rocket cleaner, more intuitive and users will have one less “decision” to worry about. 

<p></p>

This also ties up with our goal to remove the “Basic Options” section in the “File Optimization” tab.

## User expectations and experience. How will we do this feature?

Let’s look at the user experience from the perspective of an existing user and a new user separately. 

<p></p>

Existing users on update: 

- Users with Google font optimization enabled before update will continue to have their Google fonts optimized. 

- Users with Google font optimization disabled before update; WP Rocket will continue to not process Google fonts on update. 

- For both users, the UI option in the “File Optimization” tab will be removed. 

- Users with Google font optimization disabled previously will see a new helper tool in the “Tools” tab to enable Google font optimization. This is very like the helper tool we had for enabling “Optimize CSS Delivery for mobile”. 

<p></p>

New users: 

- There will be no UI for this feature. 

<p></p>

Both existing and new users: 

- Feature can be turned off using a filter and helper plugin.

- Whenever the option is disabled, the user will have the helper tool in the “Tools” tab. 

<p></p>

**Helper tool proposal in the Tools Tab:** 

<p></p>

**Title**: “Enable Google Font Optimization”

**Icon**: Use the same icon from the “File Optimization” tab - [<u>https://jmp.sh/kPjo9jU</u>](https://jmp.sh/kPjo9jU)

**Description**: Improves font performance and combines multiple font requests to reduce the number of HTTP requests. 

This is a one-time action and this button will be removed afterwards. More info

<p></p>

**More info in the description links to**: [<u>https://docs.wp-rocket.me/article/1312-optimize-google-fonts</u>](https://docs.wp-rocket.me/article/1312-optimize-google-fonts)

data-beacon-article="5e8687c22c7d3a7e9aea4c4a"

<p></p>

**Button color**: Blue

**Button text**: Optimize Google Fonts

(Button need not have any icon)

<p></p>

![](https://lh4.googleusercontent.com/fLLDS6ANmeknJWHJRWyWJEzHz9XlndsGmqxrUNIPckd5M4eqt_LoLX9Vjm_KDpV2RtFwOdepqVh2GAwmZQnfpa3vcKEjg_wSoZegT3-2yESevDGnWbJDzgi0m4Syur37UIEnZwe4)

## Technical Specs

- Please refer to the user experience description above for scope. 

- In practice, the feature will continue as an invisible option. 

- We do not need a new filter. We can filter the value of the option in the database. Similar to how [<u>we do for SSL cache</u>](https://github.com/wp-media/wp-rocket-helpers/blob/a6bba74191f5e8f374ff23791ce68073c438db3a/cache/wp-rocket-cache-ssl/wp-rocket-cache-ssl.php#L31). 

- Safe mode disables the option just as we do now. 

## Risks

Risk is expected to be minimal since we are not enabling it for existing users. Users who have issues with it will be able to disable the feature using a helper plugin. 

## Acceptance Criteria

- Existing user with Optimize Google Fonts enabled. No change on update. The option will be removed from the “File Optimization” tab. 

- Existing install with Optimize Google Fonts disabled. The option stays disabled on update. The option will be removed from the “File Optimization” tab. The “Tools” tab will list the option to enable this. 

- New install. Google fonts will be optimized. Nothing in the UI to disable this. Users can disable it using a filter and helper plugin. 

## Documentation and Translations

- Create a new helper plugin to disable Google Fonts optimization. 

- Update our existing doc, link to helper plugin: [<u>https://docs.wp-rocket.me/article/1312-optimize-google-fonts</u>](https://docs.wp-rocket.me/article/1312-optimize-google-fonts)

- Should we mention safe mode in this doc?

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4951941

**Comment by Tabrisrp** [comment]
### Remove the UI in `inc/Engine/Admin/Settings/Page.php`
- remove the `basic` entry from the `add_settings_sections()` call in `assets_section()`
- remove the `minify_google_fonts` entrye from the `add_settings_fields()` call in `assets_section()`
- remove the line `$google_fonts_beacon   = $this->beacon->get_suggest( 'google_fonts' );`

### Add Helper tool for one-time activation of Google Fonts Optimization
Create classes `Engine\Optimization\GoogleFonts\Admin\Admin` & `Engine\Optimization\GoogleFonts\Admin\Subscriber`

#### `GoogleFonts\Admin\Admin`
- Inject `Options_Data`, `Beacon`, `template path` dependencies
- Extends `Abstract_Render`
- add method `display_google_fonts_enabler` to output the view for the helper tool
- add method `enable_google_fonts` to serve as a callback to the AJAX request triggered from the button
- Write unit tests for the 2 methods

#### `GoogleFonts\Admin\Subscriber`
- Inject the `Admin` instance as a dependency
- Add a callback method for the `rocket_settings_tools_content` action hook, calling `Admin::display_google_fonts_enabler`
- Add a callback method for the `wp_ajax_rocket_enable_google_fonts` action hook,  calling `Admin::enable_google_fonts`
- Write integration tests for the 2 methods

#### JavaScript
in `src/js/global/ajax.js`, add a new fuction to handle the AJAX request to enable the option from the helper

#### View
Add a new view in `views/settings`, `enable-google-fonts.php` to handle the HTML output for the helper

**Comment by gevcen** [comment]
How about those users who use OMGF Free plugin to host locally the fonts? You did not take this situation into account. If you enable this feature "Optimize Google Fonts" by default inside WP Rocket, then I will face troubles on my site. Please provide a helper to disable this feature for those who don't want it, otherwise I'm gonna be really stuck!

**Comment by arunbasillal** [comment]
Hello @gevcen 

A helper plugin to disable Google Font Optimization is here: https://github.com/wp-media/wp-rocket-helpers/tree/master/static-files/wp-rocket-disable-google-font-optimization 

> I see that you wrote "Users with Google font optimization disabled before update; WP Rocket will continue to not process Google fonts on update." => assume that the plugin is disabled/uninstalled, what will happen? will the feature "optimize google fonts" be enabled again?

- If plugin is disabled, the settings are still in the database. When plugin is activated and if Google Font Optimization was disabled before, it will continue to be disabled. 
- On uninstall, WP Rocket will delete the settings. On new install, it will be treated as new install and the feature will be enabled. You can use the helper plugin to disable the feature. 

Best regards.

**Comment by thegulshankumar** [comment]
With Version 3.10.5.1, AMP validation fails for /web-stories/ page


Search Console says 'HTML Event attributes, aka 'on*', are not allowed in AMP. Instead use 'amp-bind'.'

Not related: We also need to disable Lazy Rocket Loader for /web-stories/ as custom JS is not allowed.

**Comment by piotrbak** [comment]
The problem is described here, we're in talkis with Web Stories developer:
https://github.com/wp-media/wp-rocket/issues/3879
