### ISSUE TITLE
Backport wp_get_environment_type() & use it where we use rocket_is_live_site()

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2878]
`wp_get_environment_type()` is a new function introduced in WordPress 5.5 giving the possibility to check the type of environment, and for anyone to set the type before WP is loaded. See: https://fr.wpseek.com/function/wp_get_environment_type/

The possible default values are `development`, `staging` and `production`

We can backport this function to the plugin using our `inc/compat.php` file, and use this function in addition to where we currently use `rocket_is_live_site()`. That way we will be forward compatible with hostings (notably) & others setting up the environment that way.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
- Copy the code of `wp_get_environment_type()` to `inc/compat.php`, wrapping it in a `function_exists()` check
- Use the function where we use `rocket_live_site()`, it's currently specifically in the RocketCDN code
- Update related tests

### Estimate the effort ✅
Effort `[XS]`

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
