### ISSUE TITLE
Divi +Image Lazy Load + Mobile Specific Image = Wrong Image Served

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2886]
I don't have a means to duplicate this site but I am going to break down the issue as best I can. The site in question was built using Divi and after activating lazy loading their images (on mobile) weren't showing correctly. I hadn't noticed the issue until the client pointed it out but it was due to lazy loading. 

I opened up the Divi builder and the client has an image in the footer using the standard image element in Divi. However, they have 2 separate images one for desktop 
![image](https://user-images.githubusercontent.com/45110039/87457250-ad056180-c5cd-11ea-98b5-724164500f32.png)

and one for mobile
![image](https://user-images.githubusercontent.com/45110039/87457275-b68ec980-c5cd-11ea-92c1-952a0fa0cdda.png)

Quite simply what happens is if lazy loading is on the desktop image gets served always. 

Code Without WP Rocket Running:
`<span class="et_pb_image_wrap"><img src="https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized.png" alt="" title="desktop_footer-resized" srcset="https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized.png 1920w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-1280x147.png 1280w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-980x112.png 980w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-480x55.png 480w" sizes="(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) and (max-width: 1280px) 1280px, (min-width: 1281px) 1920px, 100vw" data-et-multi-view="{&quot;schema&quot;:{&quot;attrs&quot;:{&quot;desktop&quot;:{&quot;src&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized.png&quot;,&quot;alt&quot;:&quot;&quot;,&quot;title&quot;:&quot;desktop_footer-resized&quot;,&quot;srcset&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized.png 1920w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-1280x147.png 1280w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-980x112.png 980w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-480x55.png 480w&quot;,&quot;sizes&quot;:&quot;(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) and (max-width: 1280px) 1280px, (min-width: 1281px) 1920px, 100vw&quot;},&quot;phone&quot;:{&quot;src&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer.png&quot;,&quot;srcset&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer.png 376w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer-300x123.png 300w&quot;,&quot;sizes&quot;:&quot;(max-width: 376px) 100vw, 376px&quot;}}},&quot;slug&quot;:&quot;et_pb_image&quot;}" /></span>`

Code With Lazyload Active:

`<span class="et_pb_image_wrap"><img src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E" alt="" title="desktop_footer-resized" data-lazy-srcset="https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized.png 1920w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-1280x147.png 1280w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-980x112.png 980w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-480x55.png 480w" data-lazy-sizes="(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) and (max-width: 1280px) 1280px, (min-width: 1281px) 1920px, 100vw" data-et-multi-view="{&quot;schema&quot;:{&quot;attrs&quot;:{&quot;desktop&quot;:{&quot;src&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized.png&quot;,&quot;alt&quot;:&quot;&quot;,&quot;title&quot;:&quot;desktop_footer-resized&quot;,&quot;srcset&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized.png 1920w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-1280x147.png 1280w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-980x112.png 980w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-480x55.png 480w&quot;,&quot;sizes&quot;:&quot;(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) and (max-width: 1280px) 1280px, (min-width: 1281px) 1920px, 100vw&quot;},&quot;phone&quot;:{&quot;src&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer.png&quot;,&quot;srcset&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer.png 376w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer-300x123.png 300w&quot;,&quot;sizes&quot;:&quot;(max-width: 376px) 100vw, 376px&quot;}}},&quot;slug&quot;:&quot;et_pb_image&quot;}" data-lazy-src="https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized.png" /><noscript><img src="https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized.png" alt="" title="desktop_footer-resized" srcset="https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized.png 1920w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-1280x147.png 1280w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-980x112.png 980w, https://www.example.com/wp-content/uploads/2020/07/desktop_footer-resized-480x55.png 480w" sizes="(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) and (max-width: 1280px) 1280px, (min-width: 1281px) 1920px, 100vw" data-et-multi-view="{&quot;schema&quot;:{&quot;attrs&quot;:{&quot;desktop&quot;:{&quot;src&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized.png&quot;,&quot;alt&quot;:&quot;&quot;,&quot;title&quot;:&quot;desktop_footer-resized&quot;,&quot;srcset&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized.png 1920w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-1280x147.png 1280w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-980x112.png 980w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/07\/desktop_footer-resized-480x55.png 480w&quot;,&quot;sizes&quot;:&quot;(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) and (max-width: 1280px) 1280px, (min-width: 1281px) 1920px, 100vw&quot;},&quot;phone&quot;:{&quot;src&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer.png&quot;,&quot;srcset&quot;:&quot;https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer.png 376w, https:\/\/www.example.com\/wp-content\/uploads\/2020\/06\/Mobile-Footer-300x123.png 300w&quot;,&quot;sizes&quot;:&quot;(max-width: 376px) 100vw, 376px&quot;}}},&quot;slug&quot;:&quot;et_pb_image&quot;}" /></noscript></span>`

**Comment by Tabrisrp** [comment]
HTML for the lazyload looks ok, this is exactly what is expected to happen during the transformation process.

However, the `data-et-multi-view` makes me think Divi has its own way of handling desktop vs mobile image, and that having lazyload on top of this is breaking it? It's also in this part that the reference to the mobile-specific footer image exists.

**Comment by piotrbak** [comment]
I wasn't able to reproduce this one with the newest Divi and WP Rocket. Feel free to reopen if it's still happening with detailed steps.
