### ISSUE TITLE
People should contribute to develop branch

### ISSUE THREAD

**Issue by szepeviktor** [wp-media/wp-rocket#2889]
Please change default branch here on GitHub.
https://github.com/wp-media/wp-rocket/branches

The default branch should be "develop".

**Comment by arunbasillal** [comment]
@Tabrisrp @hellofromtonya This seems like a suggestion for the dev team. Please take a look when possible.

**Comment by remyperona** [comment]
Done, thank you for the suggestion @szepeviktor

**Comment by szepeviktor** [comment]
You're welcome.
