### ISSUE TITLE
CDN for background image in HTML is breaking if URL is surrounded by &quot;

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#289]
Example code

`<div class="out" style="background-image: url(&quot;http://skylensdesign.com/wp-content/uploads/2016/11/dark_brick_wall.png&quot;); background-repeat: repeat;" data-tve-custom-colour="29514876">`

**Comment by JuergenB** [comment]
PS, reverting to V 2.8.23 solved this, however CDN URLS were being concatenated at that time was working. This broke with V 2.9.1. 

Also please keep in mind that customers using Wordpress sites are not manually adding quotes to background images, this is happening in the section of the code that adds the base CDN URL and then concatenates the individual resource/image url to the end of that.

TX, JB

**Comment by JuergenB** [comment]
PPS, for me this was more than a minor bug, as my site is broken under V 2.9.1 -  and I had to revert back to V 2.8.23 after lengthy investigation.
