### ISSUE TITLE
Commented HTML elements may generate unintended markup.

### ISSUE THREAD

**Issue by Davidacu** [wp-media/wp-rocket#2890]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️ 
- Used the search feature to ensure that the bug hasn’t been reported before ✔️ 

**Describe the bug**
When there are HTML tags inside a commented line, WP Rocket seems to process these tags and treat them as actual source code.

**Preconditions**
1. Use this [template ](http://snippi.com/s/x1c631b)to quickly reproduce the issue
2. Optimize CSS delivery is enabled in WP Rocket.

**To Reproduce**
1. Go to the admin dashboard of the WP site and create a new page choosing the template provided.
2. Navigate to the new page created in an incognito window.
3. Either check the cache generated by WP Rocket or just look at the page source in the browser
4. Scroll down to where the `</head>` element is commented, it should start as`<!-- missing closing </head> -->`

**Expected behavior**
The comment should be `<!-- missing closing </head> -->` as in original template.
![image](https://user-images.githubusercontent.com/4731836/87473316-771ca900-c5de-11ea-89a6-747a77d03199.png)

**Actual behavior**
The comment is `<!-- some commented tags </head><body> -->` 
notice that WP rocket adds an extra `<body>` tag inside the comments
**Screenshots**
![image](https://user-images.githubusercontent.com/4731836/87473428-aa5f3800-c5de-11ea-9a67-ef0a8cc3edec.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by hellofromtonya** [comment]
This also occurs with the CPCSS remove script insertion _when_ there's comment with `</body>` in it. 

## To Reproduce
Steps to reproduce the behavior:

1. Use the template David provided away and add a `<!-- </body> -->` comment to it within the body.
2. Go to the admin dashboard of the WP site and create a new page choosing the template provided.
3. Navigate to the new page created in an incognito window.
4. Either check the cache generated by WP Rocket or just look at the page source in the browser
5. Scroll down to where the comment is. Notice that it's inserting the script into that comment.

**Comment by hellofromtonya** [comment]
Essentially, if there are any main structural HTML tags commented out, unintended markup can happen if that tag is a regex target within Rocket. This is a systematic issue.

I'd estimate occurrence to be very low. 

Why? We haven't had any tickets about this issue. And it's uncommon to comment out structural tags.

While we do want to fix this, it is a low priority.
