### ISSUE TITLE
htaccess not regenerated when flush_rocket_htaccess is called from CLI

### ISSUE THREAD

**Issue by Sidlegionair** [wp-media/wp-rocket#2892]
Hi,

When using https://github.com/GeekPress/wp-rocket-cli, it fails to regenerate the htaccess because it fails to detect the correct path and then it will fail on the permissions check. Related issue from the cli tool: https://github.com/GeekPress/wp-rocket-cli/issues/27

**Comment by arunbasillal** [comment]
Since the issue is reported on the CLI's specific repo, I will close this as duplicate.

**Comment by Sidlegionair** [comment]
@arunbasillal The issue will probably require code-changes in the main plugin, that's why I opened the issue here as well.

**Comment by arunbasillal** [comment]
@Sidlegionair Thanks. That is fine. Since the same dev team works across both, they will initiate the change as needed. Totally understand the reasoning 👍
