### ISSUE TITLE
Automatically fetch customer's site/WP Rocket information for support

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2893]
When customers submit tickets from the plugin interface, Beacon provides all this info which greatly assists with support. 

We need a way to do the same when the customer submits a ticket from the support form on our website. We don't want them to have to check boxes or copy/paste info which is annoying and could be inaccurate. 

We have to automatically retrieve: 

- List of active plugins
- List of WP Rocket settings
- WP Rocket version
- WordPress version
- Site URL
- Theme
- Hosting company (per @DaniJacome) 

This is related to the support form for the new website.

**Comment by Tabrisrp** [comment]
What are the expectations there?

Is the website going to do a request to the user website when a ticket corresponding to it is requested? Or should the plugin send data to the website on a regular basis to store it in the website database?

**Comment by GeekPress** [comment]
@Tabrisrp We will do a request from wp-rocket.me to the customer's website to grab the infos.

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
- Create a REST API endpoint that can be requested by our website to get the above data: `wp_rocket/v1/support`
- Share the data to send to the support between our Beacon class & the new REST class to avoid duplicating code

#### New `Engine\Support\Data`
- Extract the data we collect in `Beacon::session_data()` to a method `get_support_data()` in this class
- Write tests (can use the existing `Beacon::session_data()` tests as a base)

#### New `Engine\Support\REST`
- Inject the `Data` class as a dependency
- Add a method `register_route()` to add the route to the WP REST API. The route should use a `GET` method, and should only be allowed to return data if the origin request is the `wp-rocket.me` website
- Add a method to serve as the callback for the endpoint, returning the data using `Data::get_support_data()`
- Write tests

#### New `Engine\Support\Subscriber`
- Inject the `REST` class as a dependency
- Register the callback on `rest_api_init` to add the route to the WP REST API

#### New `Engine\Support\ServiceProvider`
- Instantiate the classes

#### Update `Plugin`
- Add the ServiceProvider & the `support_subscriber` alias to the `init_common_subscribers()`

#### Update `Admin\Beacon\Beacon`
- Inject `Support\Data` as a dependency
- Update the `session_data()` method to use the method from `Data` to get the data

### Estimate the effort ✅ 
Effort `[M]`

**Comment by GeekPress** [comment]
@arunbasillal FYI, I removed the `module: Beacon` label. This is related to our new website and the Help Center page :)
