### ISSUE TITLE
PHP Warning - Invalid argument supplied for foreach() in class-expired-cache.purge.php#L120

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2909]
In the following line:
https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/classes/Cache/class-expired-cache-purge.php#L120

` get_cache_files_in_dir()` can return `false` in any of these cases:
https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/classes/Cache/class-expired-cache-purge.php#L281-L293

That can lead to a PHP warning about `Invalid argument supplied for foreach()` when the expired cache is cleared.

**To Reproduce**

1. Simulate one of the conditions [here](https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/classes/Cache/class-expired-cache-purge.php#L281-L293).
2. Set the cache lifespan to 10 minutes.
3. Enable WordPress's debugging.
4. Check the debug.log after 10-15 minutes.

**Expected behavior**

No warnings should appear in the `debug.log` when the expired cache is cleared.

**Additional context**

I discussed this with @engahmeds3ed, and he suggested the following solutions:
1. make the method `get_cache_files_in_dir` return an empty array, not `false` when there is an error.
2. check if the return data is array like the customer sent (solution in the related ticket).

**Related ticket:**
https://secure.helpscout.net/conversation/1227966516/180845?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by rasmustaarnby** [comment]
@vmanthos

Just noticed your comment about proposed solution after making the pull request. 

The reason I chose to keep the boolean return and use `is_iterable` on the `$files` variable is that it felt more in line with the current implementation, however it's not compatible with older php versions, so I guess we should stick to returning an empty array. 

I'll commit an updated version.
