### ISSUE TITLE
Cached requests to the REST API should be saved as json

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#291]
It's currently saved as HTML, and returning an incorrect content-type which is breaking some applications expecting an application/json type strictly.

**Comment by iruzevic** [comment]
Are there any updates on this ticket?

**Comment by hippocampestudio** [comment]
I have the same problem. Is there a solution ?

**Comment by GeekPress** [comment]
Duplicate of 2542

**Comment by GeekPress** [comment]
Duplicate of #2542
