### ISSUE TITLE
IE Conditional statements are removed when minify html is enabled

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#2914]
**Describe the bug**
With version 3.6.2 and 3.6.2.1 when your theme header (or any part of the page) has IE conditional statements and minify html is enabled so this conditional statements are removed.

**To Reproduce**
1. Open your theme `header.php` file and replace html opening tag with the following
```
<!--[if IE 8]><html class="no-js ie8" id="ie8" dir="rtl" lang="ar" xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 9]><html class="no-js ie9" id="ie9" dir="rtl" lang="ar" xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if !IE]><html class="no-js" dir="rtl" lang="ar" xmlns:fb="http://ogp.me/ns/fb#"><!--<![endif]-->
```
2. Enable `Minify HTML` from WP Rocket options
3. Open any page source you will find the page without opening html tags.

**Expected behavior**
Conditional statements must be kept without any change.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by webtrainingwheels** [comment]
Related tickets: 
- https://secure.helpscout.net/conversation/1232263721/181770?folderId=377611
- https://secure.helpscout.net/conversation/1232580527/181827?folderId=377611\

**Comment by engahmeds3ed** [comment]
**Root cause:**
it’s related to a change we made for the IE conditionals placeholders during 3.6.2, and the fact that they are now wrapped in HTML comments markers `(<!-- -->)`
This resulted in the HTML minification stripping them, and since they were no longer in the HTML, when the time came to add back the original content, nothing happened which resulted in missing part of the HTML

Scope a solution: 
https://github.com/wp-media/wp-rocket/blob/0b67592e25696699d73b5af08af33bc66cfce00d/inc/vendors/classes/class-minify-html.php#L179

add condition here to check on `{{WP_ROCKET_CONDITIONAL}}`

**Estimate the effort:**
[XS] as this option would be removed from 3.7 we won't refactor any part

**Comment by DahmaniAdame** [comment]
Another case - https://secure.helpscout.net/conversation/1232650135/181850/

Conditional <html> headers are stripped from the cached file.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1233974091/182173?folderId=377611

**Comment by DahmaniAdame** [comment]
https://secure.helpscout.net/conversation/1232021119/181714

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1236321127/182727

**Comment by camilamadronero** [comment]
Related https://secure.helpscout.net/conversation/1239504129/183428/
