### ISSUE TITLE
New Preload System - Cache Warmup (2 / 4)

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2938]
Sub-task from epic https://github.com/wp-media/wp-rocket/issues/2678

[M] - Create a new class which will be responsible for populating the Cache DB table. This will have a Button in Admin: Cache Warmup which will delete the full db cache table (or merge the current values with the new values identified). Clicking on the button the warmup functionality will either check the sitemaps or will create a crawler which will grab the URLs and add those in DB cache table.

**Comment by GeekPress** [comment]
Closing this issue in favor of the new one just created.
