### ISSUE TITLE
New Preload System -  SYNC Files (3 / 4) 

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2939]
Sub-task from epic https://github.com/wp-media/wp-rocket/issues/2678

[M] -this is needed in case someone deletes the full cache directory to invalidate full DB cache and start preloading
We can end up in the situation when the customer manually deleted all files in /wp-content/cache/wp-rocket and our DB table is out of sync.
In this situation I think we need to have a functionality which will check and sync the files with our DB table.
I think we shall use a scheduled event which will check on a regular basis (each 12 hour / hourly / once a day) if the cache files exist in the DB. If the files do not exist it will update the missing files (either set it to expired or delete totally the row from the DB)

**Comment by jazir555** [comment]
Can you please start developing the new preload system again? This project was started 7 months ago and the work on it seems to have died off.

**Comment by GeekPress** [comment]
Closing this issue in favor of the new one just created.
