### ISSUE TITLE
New Preload System - Continuous preloading (4 / 4) 

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2940]
Sub-task from epic https://github.com/wp-media/wp-rocket/issues/2678

[M] - The new functionality will not allow for Full Preload and Partial Preload. The new functionality will be a continuous preload based on the DB cache table.
Create a new class Preload.php which will take care of preloading a single URL based on the Cache Row table. This class will preload both desktop and mobile version of the URL if this option is enabled.
Create a new controller PreloadController.php which will take care on preloading a batch of URLs (function preload_heartbeat()) - The controller will grab from the Cache DB the next 10 -20 - X cache files which are expired and Preload those.
Create a new Subscriber for Preload which will implement the preload_heartbeat() and will enqueue the preload heartbeat JS script.
The Preload will work with a heartbeat exactly as CriticalPath.
Create a JS file which will run in Backoffice exactly as: \assets\js\wpr-cpcss-heartbeat.js with an AJAX call rocket_preload_heartbeat.

**Comment by GeekPress** [comment]
Closing this issue in favor of the new one just created.
