### ISSUE TITLE
Cache DB update - third party connections

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2941]
Sub-task from epic https://github.com/wp-media/wp-rocket/issues/2678

https://docs.google.com/document/d/1DteuvWytTewVGvy480XC7cGKuYwpp7jRfLat3k5W5NA/edit?usp=sharing
The Cache DB needs to be updated in certain situations specified in the previous document. This will trigger 3 different calls:
Invalidate full cache - meaning that all DB tables should set the expiry date in the past. I created in DB Module a new function which will set all db table rows expiry column to NOW() - 1 hour ( so the cache is expired)
https://github.com/wp-media/module-db/blob/8dace413f31b258f00db96f750d4b446c2b733a1/Cache/Model.php#L129-L131
Invalidate Partial Cache - send an array of Paths (paths will be unique in the DB table and not URLs) for which the expiry date needs to be set in the past
Delete a row in the Cache DB in case a post / page is totally deleted.

**Comment by GeekPress** [comment]
Closing this issue in favor of the new one just created.
