### ISSUE TITLE
Elementor - GTM tracking fails to be triggered for Youtube video when Lazyload for iframe is ON

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2949]
**Describe the bug**
As you can see [on this capture](https://share.getcloudapp.com/Wnub2kx4), Elementor is adding this attribute: `data-gtm-yt-inspected-30328775_104="true"` 
The attribute is not present in the noscript, which means it’s not present in the original HTML. It must be added dynamically via JS after page load.

GTM tracking fails to be triggered for Youtube video when Lazyload for iframe is ON and it works when Lazyload for iframe is OFF 

We’ll have to communicate with Elementor team to see how to handle that ([Discussion on Slack](https://wp-media.slack.com/archives/C43T1AYMQ/p1591108272142800))

**To Reproduce**
Don’t know how to reproduce it. Didn’t found the option in Elementor

**Expected behavior**

**Related ticket**
[https://secure.helpscout.net/conversation/1174681735/167733/#thread-3373309859](https://secure.helpscout.net/conversation/1174681735/167733/#thread-3373309859)

**Screenshots**
GTM tracking fails should be triggered
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
