### ISSUE TITLE
Eliminate filetime() warnings

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#295]
For whatever reason, and in rare cases, `filetime()` would return `false` in [process.php#L286](https://github.com/wp-media/wp-rocket/blob/v2.9.2/inc/front/process.php#L286)

```php
// Send headers with the last modified time of the cache file
header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s', filemtime( $rocket_cache_filepath ) ) . ' GMT' );
```

When this happens, it results in PHP warnings – uncritical, but annoying we you monitor your site and receive alerts repeatedly.

A simple way to fix the warning would probably look like this:

```php
$rocket_cache_filepath_filetime = filemtime( $rocket_cache_filepath );
if ( $rocket_cache_filepath_filetime ) {
	
	// Send headers with the last modified time of the cache file
	header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s', $rocket_cache_filepath_filetime ) . ' GMT' );
} else {

	// What? Send another header?
}
```

**Comment by Tabrisrp** [comment]
Duplicate https://github.com/wp-media/wp-rocket/issues/238

**Comment by glueckpress** [comment]
Sry, had searched for the wrong keyword. `filetime` instead `filemtime`.
