### ISSUE TITLE
OPCache compatibility & invalidation update with WordPress 5.5

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2950]
WordPress 5.5 is introducing a core function to handle OPcache invalidation: https://make.wordpress.org/core/2020/07/27/opcode-cache-invalidation-in-wordpress-5-5/

For WP Rocket, that will allow us to use this function instead of the custom `rocket_reset_opcache()` we currently have.

We also can deprecate `rocket_maybe_reset_opcache()`, as WP automatically attempts to invalidate PHP files when plugins are updated.

We can make the function available to users with WP < 5.5 by adding it to the `inc/compat.php` file.

**Comment by piotrbak** [comment]
I'd like to see if it resolves the following issue:
https://github.com/wp-media/wp-rocket/issues/4640

**Comment by piotrbak** [comment]
That would be the first step in order to get rid of `Clear OPcache` buttons:
https://github.com/wp-media/wp-rocket/issues/4439
https://github.com/wp-media/wp-rocket/issues/1491

**Comment by remyperona** [comment]
Since `opcache_invalidate()` requires a specific script path, we won't be able to use this in the end.

But we could still deprecate `rocket_maybe_reset_opcache()` and remove its callback on `upgrader_process_complete`, as WP is handling that automatically, and more precisely. What do you think @piotrbak ?

**Comment by piotrbak** [comment]
Yes, that sounds like a good idea, definitely. Can we be sure that WordPress itself is doing just enough?

From what I can see it's clearing specified file before upgrading core and this is the only thing related to `upgrader_process_complete` and `opcache_invalidate`:
https://developer.wordpress.org/reference/classes/core_upgrader/upgrade/

**Comment by remyperona** [comment]
@piotrbak The `wp_opcache_invalidate()` function is used in `copy_dir()`, which is the function used by WP when installing/updating a theme/plugin (notably). And the function is called for each file in the directory.

It is also what is stated in the make post:
> WordPress attempts to invalidate PHP files when Core, Plugins, or Themes are updated.

So I believe this is safe to do.
