### ISSUE TITLE
[WIP] 3.6+: Issues with generating CPCSS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2955]
There seems to be some increased issues with generating critical path CSS since version 3.6. 

Complaints are: 
- It takes a really long time and causes slowness in the site
- It doesn't complete
- Error: Job not found

Some issues seem temporary and can be resolved with waiting and regenerating the CPCSS - I guess that's an overload issue with our generator, which seems to be happening more often?

Related tickets (this list is not exhaustive): 
Job not found
https://secure.helpscout.net/conversation/1235507538/182554/
https://secure.helpscout.net/conversation/1204553730/175542/
https://secure.helpscout.net/conversation/1215039521/177867/

Slow/ Not completing:
https://secure.helpscout.net/conversation/1227239420/180668/
https://secure.helpscout.net/conversation/1230192593/181316/
https://secure.helpscout.net/conversation/1233768949/182104/
https://secure.helpscout.net/conversation/1201085882/174615/ (this one relates to page-specific cpcss)

**Comment by webtrainingwheels** [comment]
Update on: https://secure.helpscout.net/conversation/1233768949/182104 which @engahmeds3ed started to look into:

>I reverted back to version 3.5.5.1 and I can see it works there then backed to 3.6.2.1 and replicated the issue then I installed transients manager plugin and checked the transients saved by CPCSS and I can see the links for cpcss and their issues.
also when I installed 3.6.2.1 and the preload started to work I can see the slowness on the full site and on this time if I tried to regenerate cpcss again it would fail completely.
so I'm still investigating getting those links locally not to test on the customer site itself.

Could be lack of resources on the customer's server, since 3.6 is using more background processes. 

Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1595840257052200

**Comment by webtrainingwheels** [comment]
Update on: https://secure.helpscout.net/conversation/1227239420/180668?folderId=377611

The first time WP Rocket is installed and Optimize CSS Delivery is enabled, the CSS generation gets stuck after the first page.
There is no admin notice with an error, it’s just stuck and does not proceed.
The second page is accessible and our external test tool can reach it without issue.
According to Site Health, cron is fine, and separate mobile cache is not enabled.
After deactivating and reactivating the Optimize CSS Delivery option, the transient is finally updated and an admin message is displayed. 

The problem is “job not found”
a:2:{s:5:"total";i:2;s:5:"items";a:2:{s:8:"page.css";a:1:{s:6:"status";a:1:{s:9:"nonmobile";a:2:{s:7:"message";s:57:"Critical CSS for page not generated. Error: Job not found";s:7:"success";b:0;}}}s:14:"front_page.css";a:1:{s:6:"status";a:1:{s:9:"nonmobile";a:2:{s:7:"message";s:38:"Critical CSS for front_page generated.";s:7:"success";b:1;}}}}}

Now, when the regeneration is tried, it works fine for both pages.
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1596738227177800

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1252753366/186431?folderId=2135277

The process was stuck at "0".

Once I deactivated/reactivate the Optimize CSS Delivery option, I got the "Job not found" error.

After that, regenerating the CPCSS eventually worked.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1319245331/205415/

Had errors:
_The API returned an invalid response code._
_Job not found_

After disabling Preload and Separate Cache files for mobiles the CPCSS generation finally worked for some pages.
Increasing PHP memory helped the process to run even better.

**Comment by piotrbak** [comment]
@webtrainingwheels I think we can close the issue, CPCSS seems to be fully stable, is that correct? 🤔

**Comment by webtrainingwheels** [comment]
@piotrbak Indeed, I haven't seen this issue for a long time so I think it's safe to close this :)
