### ISSUE TITLE
Add text to YouTube preview image when using lazy load.

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#2956]
**Is your feature request related to a problem? Please describe.**
YouTube lazy load preview image has an empty alt tag. This makes it unreadable for blind users using a screen reader to browse the page. 

**Describe the solution you'd like**
Maybe grab the iframe title tag content and use it to populate the alt tag for the holder image?

**Describe alternatives you've considered**
N/A.

**Additional context**
I'm not sure if the actual image will be readable by screen readers as the lazy load would replace the holder image with the actual iframe before it reaches the viewport.

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1281337585/194597/

**Comment by alfonso100** [comment]
a related ticket here: https://secure.helpscout.net/conversation/1251310020/185973?folderId=2683093

**Comment by roeewe** [comment]
One more problem,
The YouTube lazy load preview image element will not get focus with keyboard ("tab key") navigation, and will not be clickable by people who have disability. It's really a big problem for people who need it.

**Comment by camilamadronero** [comment]
Another one https://secure.helpscout.net/conversation/1349453669/216575/

**Comment by NataliaDrause** [comment]
Another request: https://secure.helpscout.net/conversation/1913362632/347250?folderId=3864740

**Comment by Wolic** [comment]
The problem with the empty alt tag still exists. Will it still be fixed?

**Comment by NataliaDrause** [comment]
Related request: https://secure.helpscout.net/conversation/1976765678/361564

**Comment by piotrbak** [comment]
Closing this issue in favor of https://github.com/wp-media/wp-rocket/issues/5127 where we have more details.
