### ISSUE TITLE
PHP Notices when editing page with UX Builder

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2960]
**Describe the bug**
When editing a page or post with UX Builder (built-in Flatsome builder), we're receiving the following notices:
`[30-Jul-2020 15:05:11 UTC] PHP Notice:  Trying to get property of non-object in /home/wpquicki/mega/flatsome/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/Admin/Post.php on line 157`

`[30-Jul-2020 15:05:11 UTC] PHP Notice:  Trying to get property of non-object in /home/wpquicki/mega/flatsome/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/Admin/Post.php on line 165`

`[30-Jul-2020 15:05:11 UTC] PHP Notice:  Trying to get property of non-object in /home/wpquicki/mega/flatsome/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/Admin/Post.php on line 157`

`[30-Jul-2020 15:05:11 UTC] PHP Notice:  Trying to get property of non-object in /home/wpquicki/mega/flatsome/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/Admin/Post.php on line 165`

**To Reproduce**
1. Install Flatsome theme
2. Make sure that the newest WP Rocket version is installed
3. Edit the page and click on the `Edit With UX Builder` button
![image](https://user-images.githubusercontent.com/26767037/88940544-c7069b80-d27f-11ea-8d0a-b32039497832.png)
4. See PHP Notices in the logs

**Expected behavior**
No PHP Notices in the logs

**Additional context**
The UX Builder is using the following URL:
`post.php?post=313&action=edit&lang=en&app=uxbuilder&type=editor#/`

That's why it's not bailed out here:
https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/Engine/CriticalPath/Admin/Post.php#L103

We should make sure not to try to load our Critical CSS admin section when editing posts with UX Builder. The `$post` object is not available while editing the post with this builder.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1320280794/205749?folderId=3864740

**Comment by piotrbak** [comment]
It's not reproducible anymore.
