### ISSUE TITLE
container-interop is abandoned

### ISSUE THREAD

**Issue by ethanclevenger91** [wp-media/wp-rocket#2961]
**Is your feature request related to a problem? Please describe.**
Enhancement.

**Describe the solution you'd like**
Swap out abandoned container dependency. Those of us installing via Composer see a warning, while vanilla users are still impacted, just not notified.

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`

**Describe alternatives you've considered**
No action. Not sure I'd flag this as "urgent" without known vulnerabilities in the existing dependency.

**Comment by iCaspar** [comment]
Thanks for this Ethan. That warning is annoying, I agree!

Currently, the package that pulls in `container-interop` is our `league/container` which is sitting at `^2.4`. In version 3+ of that package, they've bumped the minimum PHP requirement to 7.0 - and we're still supporting PHP 5.6 in the plugin. :( So we can't go that route (yet!).

Still, it may be worth taking a look whether other container packages using the `psr/container` are available that still support 5.6, and can be swapped out without significant refactoring of other stuff. Suggestions welcome!

**Comment by ethanclevenger91** [comment]
Ah, that tracks.

Well here's a vote in favor of dropped PHP 5.6 support, but I'm also a move-fast-break-things sort so take that with a grain of salt. I assume any roadmap you might have for that is tied to official WP support?

Thanks for the update!

**Comment by Tabrisrp** [comment]
Hey,

in PR #3008, We switched the dependency from container-interop to psr/container.

This change is included in version 3.7, which is currently being released over time to everyone 👍
