### ISSUE TITLE
Exclude cms_block post type from CPCSS generation

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2970]
There is a post type `cms_block` (I think it's from the Woodmart theme) which generates an "error url unreachable" from our CPCSS generation - it's not a publicly available post type. We have at least 3 tickets related to this so we could automatically exclude it. 

https://secure.helpscout.net/conversation/1244958588/184550/
https://secure.helpscout.net/conversation/1240422850/183633/
https://secure.helpscout.net/conversation/1232777347/181911/

**Comment by gevcen** [comment]
I confirm it's from Woodmart theme

**Comment by gevcen** [comment]
To give some more infromation on this, Woodmart theme is able to turn those HTML Blocks into public mode if you edit the theme files, and therefore WP Rocket will become able to generate CPCSS for these HTML Block.

I think you can close this issue. For Woodmart users, follow the instructions of this thread :
https://xtemos.com/forums/topic/html-block-not-accessible-for-wp-rocket-to-generate-cpcss/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1407002602/234468?folderId=377611

**Comment by remyperona** [comment]
As validated with QA and product, since the recent version of the `woodmart core` plugin already is compatible (`publicly_queryable = false`), we are not going forward with this.

**Comment by sandyfzu** [comment]
Here is a case where the user has the latest version and this issue still happens:

https://secure.helpscout.net/conversation/1431351234/241044/
