### ISSUE TITLE
LazyLoad for iframes removes the %0A HTML character from the src.

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#2972]
**Before submitting an issue please check that you’ve completed the following steps:**
- On 3.6.3
- No similar issues found

**Describe the bug**
LazyLoad for iframes removes the `%0A` HTML character from the `src`.

**To Reproduce**
1. Insert an iframe with an `%0A` HTML character 
2. Enable LazyLoad for iframes
3. Visit the page with the iframe
4. See example error: 
https://i.imgur.com/4wdtdSa.png -  the %0A HTML character was removed from the src, so the C++ code breaks.

**Expected behavior**
LazyLoad for iframes doesn't remove the `%0A` HTML character from the `src`.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1596661759267000
Ticket: https://secure.helpscout.net/conversation/1245387937/184640?folderId=2675957

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
