### ISSUE TITLE
Woodmart Theme's HTML Block + WP Rocket CPCSS = Error

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2978]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Rocket is wrongly targeting the Woodmart theme's HTML Blocks are an element that can have CPCSS, altough they are not supposed to since those blocks are not publicly available => the CPCSS is supposed to be generated through the Page in which they are added.

**To Reproduce**
1. Install Woodmart theme
2. Create HTML Block
3. Add the HTML Block in a page
4. Generate CPCSS for the page

**Expected behavior**
WP Rocket shouldn't target HTML Blocks are elements that can have CPCSS separately. The CPCSS should be created within the Page in which they are added.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/89892195-9a834580-dbd6-11ea-8346-ae57c985beab.png)

**Additional context**
https://xtemos.com/forums/topic/woodmart-html-block-wp-rocket-critical-path-css-error/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
I think this is a duplicate of : https://github.com/wp-media/wp-rocket/issues/2970

**Comment by gevcen** [comment]
Yes indeed, it seems duplicate :)
