### ISSUE TITLE
Add support for wp_cache_get_multiple

### ISSUE THREAD

**Issue by addedlovely** [wp-media/wp-rocket#2982]
**Is your feature request related to a problem? Please describe.**
WordPress 5.5 has added a new function for retrieving multiple object cache values in a single request.

**Describe the solution you'd like**
Implement the new function, sounds like a performance gain.

**Additional context**
https://make.wordpress.org/core/2020/08/11/introduce-wp_cache_get_multiple

**Comment by Tabrisrp** [comment]
Hi 👋 ,

Thank you for opening this suggestion, we appreciate you took the time to do it.

WP Rocket doesn't handle object caching at the time, So this is not something that can make a difference in our plugin currently.

But if we ever get into the object caching part, it's something we will keep in mind!

**Comment by addedlovely** [comment]
Ah, sorry bad suggestion! I always assumed WP Rocket was doing something with object caching, as opcache has an option to purge. Thanks for checking it out anyways!

**Comment by Tabrisrp** [comment]
OPCache is even another layer of caching, different from object caching in this context.

All good, I'll be closing this issue now.
