### ISSUE TITLE
​​Cleaning the front page cache, doesn't clear cached homepage #lang folders

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2983]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Cleaning the front page cache using the "Clear this cache button" at the posts edit page, doesn't clear any home page cache additional folders when #lang=, or were a combination of #lang= + query parameters are used.

**To Reproduce**
1. Using WPML 
2. Generate custom cache folders for the home page like this
3. Visit the pages section in WP Admin and clear the cache using the Clear this cache link at the posts edit page: https://jmp.sh/VhwGSHs
4. check the cache folder. Before clearing the Front page cache:
```
example.com/
--/#lang=es/
----/index-https.html
----/index-https.html_gzip
--/#lang=es&v=ar/
----/index-https.html
----/index-https.html_gzip
--/#lang=pt-pt/
----/index-https.html
----/index-https.html_gzip
index-https.html
index-https.html_gzip
```

After clearing the Front page cache, using the [Clear this cache](https://jmp.sh/SDIcHRc) link from the edit posts page. The top level index-https.html files are removed, but we're not removing any child folders containing the #lang + any vars: 

```
example.com/
--/#lang=es/
----/index-https.html
----/index-https.html_gzip
--/#lang=es&v=ar/
----/index-https.html
----/index-https.html_gzip
--/#lang=pt-pt/
----/index-https.html
----/index-https.html_gzip
```

**Expected behavior**
We should remove any additional cached versions of the homepage.

**Screenshots**
After clearing the home page cache, there are some remaining folders: https://jmp.sh/w1X4wzK

**Additional Information**
ticket: https://secure.helpscout.net/conversation/1235234705/182501/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
The customer proposed a solution here: 
https://secure.helpscout.net/conversation/1235234705/182501?folderId=2683093#thread-3613352332

it modifies line 594 of our `[files.php](https://github.com/wp-media/wp-rocket/blob/master/inc/functions/files.php#L594)` 

This is the proposed change: 
```
	$files = array_merge(
	 glob( $root . '/{index,index-*}.{html,html_gzip}', GLOB_BRACE | GLOB_NOSORT ), 
	 glob( $root . '/#*/{index,index-*}.{html,html_gzip}', GLOB_BRACE | GLOB_NOSORT ) 
	 ); 
```
I have tested it on MEGA and it is clearing the extra index pages for additional languages as expected. 
But of course, it needs further testing and validation to see if is a valid approach.

**Comment by piotrbak** [comment]
@iCaspar Both of the issues (+ https://github.com/wp-media/wp-rocket/issues/3444) are blocked by https://github.com/wp-media/wp-rocket/issues/146

**Comment by Mai-Saad** [comment]
Note: for retesting, we need to check it with the AMP plugin as well (#AMP folder is not cleared for the home page)

**Comment by piotrbak** [comment]
Closing it in favor of:
https://github.com/wp-media/wp-rocket/issues/3444
