### ISSUE TITLE
PHP Notice: Missing permissions_callback triggered by doing_it_wrong in WP 5.5

### ISSUE THREAD

**Issue by Davidacu** [wp-media/wp-rocket#2985]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
After updating to WP 5.5, whenever you open a page for edit or try to create a new post/page a PHP notice is displayed

**Preconditions:**
1. WP Rocket is activated.
2. Site is running WP 5.5

**To Reproduce**
1. Go to the Admin dashboard and click "All pages"
2. Click on "Add New" button

**Expected behavior**
The post editor is displayed.

**Actual Behavior**
The post editor is displayed, but a notice flash for a second, the error is also written to the debug log:
http://snippi.com/s/ekrsai6

**Screenshots**
![image](https://user-images.githubusercontent.com/4731836/89951440-a546d600-dbe8-11ea-8b8f-8350e7b9f248.png)

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by iCaspar** [comment]
✔️ Reproduced locally.
✔️ Root cause is lack of a `permissions_callback` item in our route registrations array is now triggering a `doing_it_wrong` notice as of WP 5.5
✔️ Solution:
- [ ] Add the `permissions_callback` to the arrays in `RESTSubscriber.php`
- [ ] Update the integration tests that will fail without having the `permissions_callback` defined in the API tests' REST routes.
✔️ Estimated effort: [s]

**Comment by JohnTorvik** [comment]
Related: https://secure.helpscout.net/conversation/1252680783/186408/

**Comment by piotrbak** [comment]
Related:
https://secure.helpscout.net/conversation/1252157227/186256/
https://secure.helpscout.net/conversation/1252385189/186334/

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1252869153/186451?folderId=3051575

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1252912621/186459/

**Comment by JohnTorvik** [comment]
Related: https://secure.helpscout.net/conversation/1253200773/186532/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1253374564/186587?folderId=377611
https://secure.helpscout.net/conversation/1253396640/186592?folderId=377611

**Comment by piotrbak** [comment]
https://secure.helpscout.net/conversation/1253534119/186627/

**Comment by DahmaniAdame** [comment]
https://secure.helpscout.net/conversation/1254304492/186787/

**Comment by NataliaDrause** [comment]
https://secure.helpscout.net/conversation/1255756294/187141

**Comment by iCaspar** [comment]
Hey folks, we cherry picked and rolled this change into yesterday's 3.6.4 hotfix, so 🤞 we won't be seeing any more of these.
