### ISSUE TITLE
Check for Divi child theme fails unless it is named "Divi"

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#2992]
The check I'm referring to is here:
https://github.com/wp-media/wp-rocket/blob/master/inc/ThirdParty/Themes/Divi.php#L112

One way this check is used is to prevent the customer from enabling the "Replace YouTube iframe with preview image" setting when Divi is the current theme _or the current theme's parent_, to address this issue:
https://github.com/wp-media/wp-rocket/issues/1803

However, in a case where the customer was using a Divi child theme, they were still able to turn on that option, because their child theme wasn't named _Divi_:

```
/* 
 Theme Name:     Melbourne Entertainment Company
 Author:         MEC
 Author URI:     http://www.melbourneentertainmentco.com.au/
 Template:       Divi
```

Once I changed the value of `Theme Name` to _Divi_, the disabling of the option went into effect.

**To Reproduce**

1. Install the Divi theme.

2. Create a child theme and specify Divi as the parent.

3. Activate the Divi parent theme, then go to the MEDIA tab and enable _Lazyload for iframes_; the preview option will be greyed out:

<img width="762" alt="Screen Shot 2020-08-12 at 9 50 26 AM" src="https://user-images.githubusercontent.com/44367/90045244-5d7d8880-dc94-11ea-872f-ba1bba4a33af.png">

4. Activate the Divi child theme, then go back to the MEDIA tab; you'll see that the preview option is no longer greyed out:

<img width="684" alt="Screen Shot 2020-08-12 at 9 55 14 AM" src="https://user-images.githubusercontent.com/44367/90045446-ac2b2280-dc94-11ea-82dd-2cf31d3430fb.png">

5. Change the child theme's `Theme Name` to _Divi_ in its _style.css_; refresh the MEDIA tab and the preview option will be greyed out again.

**Expected behavior**
WP Rocket correctly detects when Divi is the parent theme, and the preview option is greyed out.

Reference: https://secure.helpscout.net/conversation/1236797266/182819/

**Comment by iCaspar** [comment]
This bug was found and is fixed as part of #2875, to be included in 3.7.
