### ISSUE TITLE
Remove Unused CSS and Javascript

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#2997]
Currently, almost 80-90% of the CSS and Javascript loaded are actually unused by the posts or pages. For example, a lot of backend-specific files are being minified and added to the single file that will be loaded everywhere. So, if we can develop a feature that strips out these unused files and code snippets that are not being used by a certain Post Type, that can reduce the file size of the .js and .css file loaded by Wp-Rocket. This would be an amazing feature if we are able to accomplish it somehow.

**Comment by arunbasillal** [comment]
Hello @MuhammedSwalihct 

Thanks for the suggestion. We have some related features already planned:

- https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/41-remove-unused-css-tree-shaking
- https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/14-remove-unused-css-and-js-on-individual-pages

You can browse through all the suggested features and suggest new ones there 👍
