### ISSUE TITLE
Combine JS problems with IE Conditionals

### ISSUE THREAD

**Issue by sandyfigueroa** [wp-media/wp-rocket#2999]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When a JavaScript inline code has an IE conditional, an error occurs when combining JavaScript.

Example:

``<script type="text/javascript">
const wpvViewHead = document.getElementsByTagName( "head" )[ 0 ];
const wpvViewExtraCss = document.createElement( "style" );
wpvViewExtraCss.textContent = `<!--[if` IE 7]><style>
.wpv-pagination { *zoom: 1; }
</style><![endif]-->
`
wpvViewHead.appendChild( wpvViewExtraCss );</script>``

After combination, the inline JavaScript still present in the html (not removed) and in the combined file there is a bad copy, the resulting code (In the combined file) is:

``<script type="text/javascript">
const wpvViewHead = document.getElementsByTagName( "head" )[ 0 ];
const wpvViewExtraCss = document.createElement( "style" );
wpvViewExtraCss.textContent = `
`
wpvViewHead.appendChild( wpvViewExtraCss );</script>``

I checked deleting IE conditional tags from the example code and this error is not present.

In addition, that inline JavaScript code stops working (Neither the one in the HTML nor the one in the combined file works.)

**To Reproduce**
1. Add the example inline JavaScript code to the HTML
2. Activate combine JS

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/90448923-f6a10a80-e0ab-11ea-8c19-0e803da806ca.png)
![image](https://user-images.githubusercontent.com/13713107/90448940-fef94580-e0ab-11ea-9a1c-562919d2d1a5.png)
![image](https://user-images.githubusercontent.com/13713107/90448905-f0129300-e0ab-11ea-80ae-799a40c02ff0.png)

**Additional context**
This does not happen in version 3.6.1, only happens in 3.6.2+ (including the last version 3.6.3).

Check the ticket here: https://secure.helpscout.net/conversation/1253460241/186608

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
Another case: 
https://secure.helpscout.net/conversation/1247944875/185194?folderId=2683093

**Comment by samlowry** [comment]
Hey, WP Rocket ! I can't update your plugin to the new from 9th of September! My bug number is #2999 and according to your last change log you're way into #31XX-#32XX! Doesn't look at all like you're going to fix that old bug. Pls do something finally!

**Comment by remyperona** [comment]
This issue has been solved with the following PR #3239

The inline script is excluded from combine JS to avoid the problem.
