### ISSUE TITLE
Namespace external package dependencies to avoid conflicts with other plugins/theme using the same package but different version.

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#3005]
As we experienced with the WooCommerce container conflict #3003 and [here](https://github.com/woocommerce/woocommerce/issues/27384), when other plugins/themes use the same external composer dependencies but with a different version, the risk is high for a fatal error conflict. We can mitigate this risk by encapsulating each production-level dependency with a namespace.

There are multiple ways to accomplish this including:

- Pulling dependencies into the Engine as we did with the Container
- Using namespacing tools such as [Daniel points out here](https://github.com/wp-media/wp-rocket/issues/3003#issuecomment-675685924) 

Let's be proactive to guard Rocket and our customers from this happening again.

**Comment by DanielRuf** [comment]
Some example from another plugin using php-scoper: https://github.com/mundschenk-at/wp-typography/blob/master/composer.json#L88

**Comment by iCaspar** [comment]
On a quick review of those tools mentioned/linked, I think our support of PHP 5.6 will rule out both php-scoper and imposter, as they both require at least 7.2. Mozart seems like it could work, as it requires 7.2 to run on composer, but can handle packages using < 7, BUT it is still an experimental package with it's own warning about "wearing a hard hat for use in production". Not good with a million sites relying on stability. :( 

I think our best solution (for now) is likely to re-namespace our other dependencies into Engine, as we did for league/container. This requires some additional maintenance overhead, as we'd have to track the packages ourselves, but as we move into the new roadmap and get significant parts of the plugin out of the plugin :) it should be less cumbersome over time, until we can either drop 5.6 or Mozart stabilizes.

**Comment by hellofromtonya** [comment]
@DanielRuf Your point is valid. It does add work for releases as we have to manually check and update each dependency. Definitely not optimal.

>Mozart seems like it could work, as it requires 7.2 to run on composer, but can handle packages using < 7, BUT it is still an experimental package with it's own warning about "wearing a hard hat for use in production". Not good with a million sites relying on stability.

We're using Mozart on our [standalone LazyLoad plugin](https://github.com/wp-media/rocket-lazy-load). We have support tickets with a similar League Container fatal error. At the moment, we're not sure yet of the root cause. 

However, @iCaspar your point is valid. "Experimental" is not stable or robust enough for our customers. 

This is why we pulled the League Container into Rocket's Engine as it's a critical component to Rocket.

**Comment by DanielRuf** [comment]
Not sure but to me it looks like the dependencies are twice in there.

In the default vendor folder with the autoloader:
https://plugins.trac.wordpress.org/browser/rocket-lazy-load/trunk/vendor

In src/Dependencies:
https://plugins.trac.wordpress.org/browser/rocket-lazy-load/trunk/src/Dependencies

**Comment by hellofromtonya** [comment]
@DanielRuf Great catch. You pointed us in the right direction from which [I created this issue](https://github.com/wp-media/rocket-lazy-load/issues/116).  Thank you!
