### ISSUE TITLE
Info regarding usage

### ISSUE THREAD

**Issue by DevelopedByAnurag** [wp-media/wp-rocket#3016]
Hey just wandering does this plugin work if I don't buy WP-rocket from website as it is opensource so will it work ?

**Comment by arunbasillal** [comment]
Hello @DevelopedByAnurag 

To answer your question, purchase from website is required for license validation. So installing it from GitHub will not work until you provide a key. 

The source code is available so that other developers and users can see it and collaborate on it. 

Best regards.
