### ISSUE TITLE
Update User Cache feature description to aware customers that it'll bypass WP Rocket features if disabled and an user is logged in

### ISSUE THREAD

**Issue by JohnTorvik** [wp-media/wp-rocket#3023]
**Is your feature request related to a problem? Please describe.**
Our current feature description is:
![image](https://user-images.githubusercontent.com/8461763/91204156-020eba00-e6da-11ea-9482-b512e58be3c7.png)

**Describe the solution you'd like**
Even we have this stated in our doc "the site will be cached as normal for any visitor that is not logged in", isn't clear enough for customers that if this feature is disabled, it'll bypass WP Rocket when logged-in.

**Describe alternatives you've considered**
Add a warning under the checkbox to clarify that WP Rocket will be bypassed if this option isn't activated.

**Additional context**
Related ticket:
https://secure.helpscout.net/conversation/1258218763/188143?folderId=3773397

**Comment by arunbasillal** [comment]
Asked for feedback from Lucy here: https://wp-media.slack.com/archives/CFSCRLVGB/p1599229085001700
