### ISSUE TITLE
Fatal error when activating plugin at the network level

### ISSUE THREAD

**Issue by Davidacu** [wp-media/wp-rocket#3037]
**Description**
When activating the plugin at the network level a fatal error is displayed.

**Preconditions**
the plugin is activated in the main subsite.

**To Reproduce**
1. Go to Network admin -> Plugins
2. Click on "Network activate" under WP Rocket plugin.

**Expected behavior**
The plugin is activated successfully

**Actual**
Fatal error is displayed:
`Fatal error: Cannot redeclare rocket_load_textdomain() (previously declared in C:\Users\David\Local Sites\wprocketmultisitesstaging\app\public\wp-content\plugins\wp-rocket\wp-rocket.php:100) in C:\Users\David\Local Sites\wprocketmultisitesstaging\app\public\wp-content\plugins\wp-rocket\wp-rocket.php on line 100`
full log -> http://snippi.com/s/7xp72ce

**Screenshots**
![image](https://user-images.githubusercontent.com/4731836/91599692-ebf43a00-e923-11ea-9375-2edc3e7d1603.png)

**Additional context**
I noticed it was only reproduced when the plugin was activated on the Main site.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1776646575/323858/

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
