### ISSUE TITLE
Add mandatory cookie for "Italy Cookie Choices (for EU Cookie Law)"

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3040]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version 
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using WP Rocket with Italy Cookie Choices (for EU Cookie Law), the Cookie plugin will prevent caching unless the visitor accepts the cookie policy (expected behavior). 
Once they click, WP Rocket will cache the page and serve it for all following visitors without the cookie consent banner showing. 

**To Reproduce**
1. Install and activate Italy Cookie Choices (for EU Cookie Law) - https://wordpress.org/plugins/italy-cookie-choices/
2. Visit a page and click on the consent button
3. All following visits will get the cached page

**Expected behavior**
We should not serve cache for new visitors unless they click on the cookie consent button. 
Adding the following mandatory cookie fixes the issue - displayCookieConsent

**Screenshots**
N/A

**Additional context**
* Non-technical users, or the users not knowing they should use a mandatory cookie, will have the assumption that the consent plugin is working properly. But once the page cached, the consent mechanism no longer operates as it should.
* Italy Cookie Choices (for EU Cookie Law) is outdated but has hundreds of downloads per month.
* Case - https://secure.helpscout.net/conversation/1267347378/190659/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@DahmaniAdame Thanks for the detailed report. 

I see from the ticket that the customer has opted for one of the [plugins that we are compatible with](https://docs.wp-rocket.me/article/687-which-cookie-law-plugins-are-compatible-with-wp-rocket
). 

My concern is that the plugin hasn't been updated in 2 years. Adding support for a plugin is a lot of effort in terms of maintenance and if we can reserve that for the top most installed active plugins, that would be ideal. 

@webtrainingwheels Can we try to contact the plugin author to see if they can add compatibility at their end please?

**Comment by arunbasillal** [comment]
Some additional feedback on discussion with Jonathan. 

- It's unlikely that the plugin developers listen to us and add the compatibility. 
- Even if they do, we shouldn't be recommending a plugin that isn't well maintained while there are plenty of other options. It's not in the best interest of our users for us to recommend it to them. 

Closing the issue.

**Comment by DahmaniAdame** [comment]
Thank you @arunbasillal !

Yes, the customer opted for a compatible plugin instead. I guess it's best to just point to compatible GDPR/Cookie plugins that are still maintained.
