### ISSUE TITLE
Queries when not necessary

### ISSUE THREAD

**Issue by Camilo517** [wp-media/wp-rocket#3042]
Hello, I am testing WP Rocket 3.7, in the administration page of my custom plugin I see that wp rocket makes a little strange queries
"imagify_settings" -> I don't have imagify installed
"_transient_rocket_cloudflare_is_api_keys_valid" -> I don't have cloudflare configured
"_transient_1_sucuri_purge_result" -> I don't have the branch cdn so it is not configured
"_transient_rocket_critical_css_generation_triggered" -> Critical css is not configured
etc

![Screenshot_3](https://user-images.githubusercontent.com/43606394/91644647-5ef1d380-ea3e-11ea-9ebc-3156f432fc38.png)

**Comment by piotrbak** [comment]
Related: https://github.com/wp-media/wp-rocket/issues/1599

**Comment by arunbasillal** [comment]
@Camilo517 I have linked this issue in #1599. We will continue the discussion there when we work on it. 

There is room to improve. This year we are definitely cussed on the performance of the product and this will come under our radar at some point. Thanks for the heads up.
