### ISSUE TITLE
Fatal error on plugin activation

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3043]
Fatal error: Uncaught Error: Class 'WP_Rocket\Plugin' not found in /home/customer/www/DOMAIN/public_html/wp-content/plugins/wp-rocket-3.7/inc/main.php:44 Stack trace: #0 /home/customer/www/DOMAIN/public_html/wp-includes/class-wp-hook.php(287): rocket_init('') #1 /home/customer/www/DOMAIN/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/customer/www/DOMAIN/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/customer/www/DOMAIN/public_html/wp-settings.php(409): do_action('plugins_loaded') #4 /home/customer/www/DOMAIN/public_html/wp-config.php(101): require_once('/home/customer/...') #5 /home/customer/www/DOMAIN/public_html/wp-load.php(37): require_once('/home/customer/...') #6 /home/customer/www/DOMAIN/public_html/wp-admin/admin.php(34): require_once('/home/customer/...') #7 /home/customer/www/DOMAIN/public_html/wp-admin/plugins.php(10): require_once( in /home/customer/www/DOMAIN/public_html/wp-content/plugins/wp-rocket-3.7/inc/main.php on line 44

une erreur critique est survenue sur votre site. Veuillez consulter la boite de réception de l’e-mail d’administration de votre site pour plus d’informations.

En apprendre plus sur le débogage de WordPress.

**Comment by hellofromtonya** [comment]
@gevcen There are a few possibilities:

1. Missing Composer files or `vendor` folder.
2. Something else happened while the update was in progress.
3. The update itself failed.

Is your site down?
    - If yes, you'll need access to your website's filesystem (S/FTP or SSH). [Here's a document to help you](https://docs.wp-rocket.me/article/14-updating-wp-rocket). You can get access to the production ready file through [your WP Rocket account](https://wp-rocket.me/account/).
    - Is no, then likely something else happened during the update itself but the update did complete.

How did you update the plugin?
- [ ] Received an update notice and updated through your site's admin UI
- [ ] Downloaded the plugin zip file from your WP Rocket account
- [ ] Downloaded or pulled files from this GitHub repo and then transferred them to your site via ssh or ftp

If through this repo, the files in the repo are not fully ready for transfer to a website. Why? They don't have Composer or dependencies packaged with them. We do this through the Ansible build process to bundle the WP Rocket zip file and make it available through your account or directly in your website's Plugin UI. I'd advise that you log into [your WP Rocket account](https://wp-rocket.me/account/) and download the zip file (it's production ready).

**Comment by gevcen** [comment]
On my wp rocket account, the version available is still 3.6.4 so I downloaded the one available in the github to test it. How can I get the 3.7 if it's not available through the wp rocket account?

See : https://sgevcen.tinytake.com/tt/NDU4MjM1M18xNDUyMzU1Nw

**Comment by hellofromtonya** [comment]
Aha, okay that makes sense. 

>How can I get the 3.7 if it's not available through the wp rocket account?
We are in a staggered release cycle, meaning we are dripping the release out slowly to our customers. You have 2 options to get it now:

1. Do the steps below to prepare a package from this repo.
2. Open a support ticket and one of our Rocketeers will update your account to give you early access.

### Get access now with the files from this repo
The `master` branch in this repo is not fully ready for transfer to a website. Why? They don't have Composer or dependencies packaged with them. We do this through the Ansible build process to bundle the WP Rocket zip file and make it available through your account or directly in your website's Plugin UI.

When downloading the zip files from this repo, you'd also need to do the following:

1. Unzip it.
2. Open a command line tool (like terminal).
3. Navigate to where the Rocket folder is.
4. Type: composer install --no-dev --no-scripts to load Composer. This creates a `vendor` file in the plugin's root.
5. To install, transfer all of the files/folders in the plugin to your website.
