### ISSUE TITLE
3.7 - Clearfy - PHP fatal error from using deprecated Minify_HTML class

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3047]
**Describe the bug**

This affects users that:
* Have [Clearfy](https://wordpress.org/plugins/clearfy/) installed.
* They are updating to WP Rocket `3.7`.

The error is this one:
```
PHP Fatal error:  Cannot declare class Minify_HTML, because the name is already in use in /home/domains/example.com/public_html/wp-content/plugins/wp-rocket/inc/deprecated/vendors/classes/class-minify-html.php on line 22
```

Clearfy is also declaring a `Minify_HTML` class in:
```
/wp-content/plugins/clearfy/components/html-minify/includes/classes/ext/php/class-minify-html.php
```

**To Reproduce**

1. Rollback to `3.6.4` if that's not the version already installed.
2. Install [Clearfy](https://wordpress.org/plugins/clearfy/).
3. Enable WordPress debugging.
4. Update WP Rocket to `3.7`.
5. Check the `debug.log` for the error.

**Expected behavior**

No fatal error should occur.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1268667344/191001?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by hellofromtonya** [comment]
This is a Composer dependency that we unique namespaced and pulled into WPR to guard WPR from fatal errors.

However, by deprecated it here `inc/deprecated/vendors/classes/class-minify-html.php`, it no longer protects WPR if a 3rd party is using it too.

Solution: Remove the deprecated class.

Risk: A 3rd party was using that specific class from WPR. If that's the case, a fatal error in that 3rd party will happen.
