### ISSUE TITLE
LazyLoad disabled on page, but still enabled on query string version

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#305]
LazyLoad is disabled on this url, via the cache options meta box: http://staging.houseplansdirect.co.uk/search-house-designs/

The page has a filter on it, when you select an option the url becomes something like: http://staging.houseplansdirect.co.uk/search-house-designs/?_sft_product_cat=dormer-bungalow-designs
and Lazyload is applied again, breaking it. 
Expectation would be that Lazyload it not applied to any version of this page.

**Comment by Tabrisrp** [comment]
I can't replicate the issue

**Comment by Screenfeed** [comment]
Couldn't reproduce neither.
