### ISSUE TITLE
LazyLoad : Add Lazyload for comments

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3055]
There's another plugin out there that does this but many support questions go unanswered there. I trust you to implement lazy loaded comments correctly and it fits in nicely with your other lazy loading.

Plugin: https://wordpress.org/plugins/lazy-load-for-comments/
Ref ticket: https://secure.helpscout.net/conversation/1268966252/191088?folderId=1213662

**Comment by arunbasillal** [comment]
@WordPresseur This is an entirely new feature that isn't related to any of the existing features. So please add this to product board directly. Thank you!
