### ISSUE TITLE
PHP notice when picture element doesn't contain any source tags

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#3056]
**Describe the bug**
When the `<picture>` element does not contain a `<source>` tags PHP notice appears into the logs:

`[01-Sep-2020 07:58:56 UTC] PHP Notice: Undefined variable: lazy_sources in /***/wp-content/plugins/wp-rocket/vendor/wp-media/rocket-lazyload-common/src/Image.php on line 273`

https://github.com/wp-media/rocket-lazyload-common/blob/09bdc9a550b8bd1197c155a98e17c45adcb190af/src/Image.php#L273

**To Reproduce**
1. Enable lazy load for images
2. Add `<picture>` element without `<source>` tags to the page or post and save it
3. Open the said page or post in incognito/private browser mode
4. Check the debug.log

**Expected behavior**
No new lines in the log file.

**Additional context**
Sugested solution:  [changing line 273 to](https://github.com/wp-media/rocket-lazyload-common/blob/master/src/Image.php#L273): `if ( !isset( $lazy_sources ) || 0 === $lazy_sources )`

Ticket: https://secure.helpscout.net/conversation/1269795281/0/?folderId=3572910

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
https://github.com/wp-media/rocket-lazyload-common/blob/master/src/Image.php#L273

the mentioned variable $lazy_sources is set if this regex passes

https://github.com/wp-media/rocket-lazyload-common/blob/master/src/Image.php#L259

so is there any case on his site that he has picture tag without source tag inside it?
I think he needs to adjust his content to let all picture tags has at least source tag inside it and also we need to get this variable declaration outside the condition to be on safe side

https://wp-media.slack.com/archives/C08N8J6VC/p1598980221140500

**Comment by arunbasillal** [comment]
As per: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

> The HTML <picture> element contains zero or more <source> elements and one <img> element to offer alternative versions of an image for different display/device scenarios. 

So it is totally "legit" to have zero `source` elements.

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
We are not initializing correctly the `$lazy_sources` variable before trying to use it, which can trigger the notice if there is no `source` element.

### Scope a solution ✅ 
We should initialize the `$lazy_sources` variable before the loop instead, with a default value of `0`.

### Estimate the effort ✅
Effort `[XS]`
