### ISSUE TITLE
DNS & Fonts "Pre-Populate" + "Restore Default" Button

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3058]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's a nice to have.

**Describe the solution you'd like**
Since 3.7, you've provided a new list of JS Delay Execution that is pre-populated with a button "restore default"

We should do same (i.e. pre-populate + restore button) for
- Preloading DNS
- Preloading Fonts

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by arunbasillal** [comment]
@gevcen Thanks for the suggestion. 

The JS delay inclusion list is not site specific and is just a common list for everyone. Preloading of DNS and Fonts are specific for each site and very much dependent on the website. 

We discussed about automating these, but the effort involved v/s the benefit is so low, so we are focused on features that make a bigger impact. 

Going to close this issue, but we can continue discussion if needed.
