### ISSUE TITLE
[WIP] Advanced-cache.php notice showing on WordPress.com

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3061]
Our contact at wp.com reported that 2 users reported to them an issue with seeing our advanced-cache.php notice: 

 > WP Rocket cannot configure itself due to missing writing permissions.
 > Affected file/folder: wp-content/advanced-cache.php

We don't have further info about at what point they saw it or what actions triggered it.

**Comment by Tabrisrp** [comment]
David tested it again on our test site and was not able to replicate the issue for now.

**Comment by webtrainingwheels** [comment]
This hasn't come up since, so I'm closing it.
