### ISSUE TITLE
Apply LazyLoad to Images Dynamically Added to the DOM

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#3063]
**Is your feature request related to a problem? Please describe.**
Images dynamically added to the DOM are not LazyLoaded

**Describe the solution you'd like**
LazyLoad can cover scenarios where new elements are dynamically added to the DOM

**Customer suggestion**
1.  triggering the update of the lazy loading Routine manually by adding this to my Body tag (basically getting the lazy load instance and saving it to a global variable): http://snippi.com/s/u621xtc
2. calling this after clicking on "load more": http://snippi.com/s/0p576x7

Working example at https://5ive-shop.com/produkte - clicking on the pagination buttons

More information in the ticket.

**Additional context**
[Ticket ](https://secure.helpscout.net/conversation/1266959672/190588?folderId=2675957#thread-3644284639)
[Slack thread](https://wp-media.slack.com/archives/C08N8J6VC/p1599074377206900?thread_ts=1598889901.027300&cid=C08N8J6VC)

**Comment by arunbasillal** [comment]
@camilamadronero We prepare the HTML for LazyLoad at the time of cache file generation. The new images are dynamically added and this is not compatible with our current LazyLoad library. So it won't be able to doing this feature with reasonable effort.
