### ISSUE TITLE
 Fatal error: Uncaught Error: Argument 1 passed to MatthiasMullie\Minify

### ISSUE THREAD

**Issue by MrGKanev** [wp-media/wp-rocket#3065]
**Describe the bug**
When updated to the last version of the WP rocker plugin(3.7.0.1) I get a fatal error. I tried deleting the cache (one by one and all at once in different scenarios but it didn't make a difference) and the only solution, for now, was to remove all the JS minify stuff so the website loads as it should. Here is the error: [LINK](https://pastebin.com/AS6L0Ebi)
**Screenshots**
It just bugs the whole design for not sure what reason. https://ibb.co/tpqzFqb

**Comment by vmanthos** [comment]
Hi @MrGKanev.

Can you please open a ticket so our support can investigate this for you?

**Comment by vmanthos** [comment]
The customer opened a ticket: https://secure.helpscout.net/conversation/1272998038/192111?folderId=273761
