### ISSUE TITLE
Be able to upgrade from the plugin

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3067]
## What are we proposing to do? 

With this enhancement, WP Rocket users with a Single or Plus license will be able to upgrade their license by clicking a link on the WP Rocket dashboard. They will be redirected to our checkout page. No payment will proceed from the customer website directly.

<p></p>

More info:

<https://docs.google.com/document/d/1g68IUjNW4dOiCe9QR0jWEkZpF6JMOK6hJhG40iL4_ds/edit#>

<p></p>

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4090026

**Comment by Tabrisrp** [comment]
Sub-tasks:
- #3143 
- #3149 
- #3150
- #3151 
- #3152
- #3153
