### ISSUE TITLE
Be able to renew from the plugin

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3068]
## What are we proposing to do? 

With this enhancement, WP Rocket users will be notified directly from the plugin that their license is expired or about to expire. We will display a link enabling them to renew directly by clicking on it. They will be redirected to our checkout page. No payment will proceed from the customer website directly.

<p></p>

More info:

<https://docs.google.com/document/d/1oqArI9u1U6frFsFCBwPKEq5WnqahPktpPcDBaCAhVu4/edit#heading=h.fe02x22oxiz3>

<p></p>

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/5366561

**Comment by Tabrisrp** [comment]
Sub-tasks
- #3143 
- #3149 
- #3150 
- #3154 
- #3155 
- #3157 
- #3158 
- #3165
