### ISSUE TITLE
Display promotions in the plugin

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3069]
## What are we proposing to do? 

With this enhancement, we will notify single and plus users directly in the plugin when there is a promotion going. They will be able to upgrade their license with the discounted price by clicking a link on the WP Rocket dashboard. They will be redirected to our checkout page. No payment will proceed from the customer website directly.

<p></p>

More info:  
<https://docs.google.com/document/d/1TtENtXMzyUoUbBCiYuHfcfuxKp5WThe1NJVY9L86aNI/edit#heading=h.dz9zk3oob6p1>

<p></p>

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4090004

**Comment by Tabrisrp** [comment]
Sub-tasks:
- #3143 
- #3149 
- #3150 
- #3151
- #3152
- #3153
- #3154 
- #3155 
- #3157
- #3158
