### ISSUE TITLE
Auto-exclude "http://www.industriejobs.de" external domain from the JS minification 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#307]
We must auto-exclude from the JS minification this example:
<script type="text/javascript" src="http://www.industriejobs.de/teaser/pharmafood.js"></script>

**Comment by glueckpress** [comment]
There are like half a dozen external JS URLs I can think of that we should auto-exclude, can I just add them here?

**Comment by GeekPress** [comment]
@glueckpress We exclude all the domain, it's not from the filename.
