### ISSUE TITLE
Preload Links: Javascript siteUrl variable is using WordPress Address and not Site Address

### ISSUE THREAD

**Issue by tombonez** [wp-media/wp-rocket#3071]
The siteUrl variable output in the Preload Links Javascript code is using the WordPress Address and not the Site Address, so whilst using WordPress in a sub-directory environment (e.g. [Bedrock](https://github.com/roots/bedrock)) this variable will output as `https://example.com/wp` instead of `https://example.com` stopping preloading links from working (if I understand the Javascript code correctly).

**Steps to reproduce**

1. Install WordPress in a sub-directory environment (e.g. [Bedrock](https://github.com/roots/bedrock)).
2. Enable link preloading under WP-Rocket->Preload.
3. Inspect the siteUrl variable output as inline Javascript in the cached code.

**Expected behavior**

The siteUrl variable to output the Site Address (using `home_url()` or similar) so that all links under the website can be preloaded on hover.

**Additional context**

The code in question is the following:
```js
var RocketPreloadLinksConfig = {"excludeUris":"\/(.+\/)?feed\/?.+\/?|\/(?:.+\/)?embed\/|\/(index\\.php\/)?wp\\-json(\/.*|$)|\/wp-admin\/|\/logout\/|\/wp-login.php","usesTrailingSlash":"1","imageExt":"jpg|jpeg|gif|png|tiff|bmp|webp|avif","fileExt":"jpg|jpeg|gif|png|tiff|bmp|webp|avif|php|pdf|html|htm","siteUrl":"https:\/\/example.com\/wp","onHoverDelay":"100","rateThrottle":"3"};
```

And I believe the code that needs modifying is [here](https://github.com/wp-media/wp-rocket/blob/8f7f67b621e5085ccf6424a08a15ce636e4fbf2f/inc/Engine/Preload/Links/Subscriber.php#L119):
```php
$config = [
	'excludeUris'       => $this->get_uris_to_exclude( $use_trailing_slash ),
	'usesTrailingSlash' => $use_trailing_slash,
	'imageExt'          => $images_ext,
	'fileExt'           => $images_ext . '|php|pdf|html|htm',
	'siteUrl'           => site_url(),
	'onHoverDelay'      => 100, // milliseconds. -1 disables the "on hover" feature.
	'rateThrottle'      => 3, // on hover: limits the number of links preloaded per second.
];
```

**Comment by arunbasillal** [comment]
@tombonez Thanks for the detailed report. In case you haven't noticed, as an interim solution you can take advantage of the `[rocket_preload_links_config](https://github.com/wp-media/wp-rocket/blob/8f7f67b621e5085ccf6424a08a15ce636e4fbf2f/inc/Engine/Preload/Links/Subscriber.php#L134)` filter. 

@hellofromtonya Can you please take a look when you have a chance?

**Comment by tombonez** [comment]
Thanks @arunbasillal that's definitely good to know 😃

**Comment by hellofromtonya** [comment]
@arunbasillal What do you think of this in the next minor release?

**Comment by arunbasillal** [comment]
@hellofromtonya For sure 👍

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1280540274/194381/
