### ISSUE TITLE
Inclusion of Google Recaptcha script in Delay JavaScript Execution breaks Contact Form 7 Recaptcha

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#3075]
The inclusion of the Google Recaptcha _api.js_ script in Delay JavaScript Execution breaks the Contact Form 7 Recaptcha, by introducing a console error.

**To Reproduce**

1. Install the Contact Form 7 plugin: https://wordpress.org/plugins/contact-form-7/
2. Complete the integration for Google Recaptcha: https://contactform7.com/recaptcha/
3. Create a basic contact form, then add its shortcode to a test page, e.g., Contact
4. Enable _Delay JavaScript execution_ on WPR's File Optimization tab
5. View the Contact page in an incognito browser window
6. Observe console error: _Uncaught ReferenceError: grecaptcha is not defined_
7. Remove _google.com/recaptcha/api.js_ from _Scripts to delay_ field on WPR's File Optimization tab
8. Refresh the Contact page in browser window, and see that the error is gone

**Expected behavior**
Don't break the Contact Form 7 recaptcha. :)

**Ticket**
https://secure.helpscout.net/conversation/1276111354/192926

**Comment by Tabrisrp** [comment]
@arunbasillal what's the status for this? I see it on the 3.7.1 milestone, but it doesn't have the grooming tag

**Comment by camilamadronero** [comment]
Another ticket: https://secure.helpscout.net/conversation/1280654294/194411/.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1279733248/194184?folderId=377611

**Comment by juricazuanovic** [comment]
https://secure.helpscout.net/conversation/1283648268/195221/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1281811873/194739?folderId=377611

**Comment by arunbasillal** [comment]
Some discussion and thinking later, let's remove `google.com/recaptcha/api.js` from the default list to delay.

Capturing the highlights of the discussion. 

- Jonathan tested this with reCAPTCHA V2 and delay works safely for that. 
- CF7 officially supports reCAPTCHA V3 from version 5.1 (which means [76% of users](https://wordpress.org/plugins/contact-form-7/advanced/) are officially on V3)
- There is an [unofficial plugin](https://wordpress.org/plugins/wpcf7-recaptcha/) with 100,000+ active installs that lets you use reCAPTCHA V2 with CF7
- However, there is no standard way to easily detect between V2 and V3 reliably. 
- Since the % of V3 is much higher, it's best to remove it from our default list.

**Comment by DahmaniAdame** [comment]
https://secure.helpscout.net/conversation/1282461682/194873/

**Comment by Tabrisrp** [comment]
### Scope a solution
- Remove `google.com/recaptcha/api.js` from the default inclusion list in `inc/Engine/Optimization/DelayJS/Admin/Settings.php`
- Update the related tests
- Add a new method to update the option value when updating from a previous version to this plugin version (3.7.2)
- Add tests for the new method

### Estimate the effort
Effort `[S]`

**Comment by camilamadronero** [comment]
Related: https://secure.helpscout.net/conversation/1289584294/196817/

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1290015500/196894/

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1290072621/196928/

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1290065644/196924?folderId=1213662

**Comment by kierantaylorio** [comment]
Related ticket: https://secure.helpscout.net/conversation/1293144296/197702/
