### ISSUE TITLE
Excluding images from Lazyload

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3076]
## What are we proposing to do? 

To add a text area in WP Rocket UI that excludes images and iframes from LazyLoad. This text area will be located in the “Media” tab under LazyLoad.

<p></p>

The text area will be shared for both images and iframes and will allow users to exclude images and iframes from LazyLoad by entering the class name, filename, or domain src. 

![](https://lh3.googleusercontent.com/4iKKePSMFVt72YOOMJVX-C6AfW8Ll9r4Xdf9rKKAM3PoJxK-ib7Xs_G0NLmDi6afj8Nb3EifDkyqMKNouYDCdF6ahTkzyUs-dvyyo7MaOWdHZgTf4rlZqQpi1LTlUs41Nup26vsc)

## Why are we doing this?

This is a well requested feature and a common need for our customers. Currently they have to rely on [<u>snippets we provide in our documentation</u>](https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images) or a helper plugin to disable images or iframe from LazyLoad. 

<p></p>

We hope to improve the experience of our customers and move one step further in the direction of making WP Rocket even more user friendly. 

## User expectations and experience. How will we do this feature?

- As described before we will be adding a text area to the WP Rocket UI

- This text area will be visible when either LazyLoad for images or iframes is enabled. If both these are disabled, then the text area can be hidden. 

- Any keyword that they enter in the text area will be used to exclude images and/or iframes from LazyLoad. 

## Technical Specs

Spec for text area UI:

- Title: **Excluded images or iframes**

- Description: **Specify keywords (e.g. image filename, CSS class, domain) from the image or iframe code to be excluded (one per line).**

- Placeholder: example-image.jpg

<p></p>

Other notes: 

- The UI should be able to accept a class-name, part of an image filename, or the domain name (src) all in one text area. One per line. 

- The same exclusions apply to both images and iframes. 

- Existing filters continue to exist and work (rocket_lazyload_excluded_attributes, rocket_lazyload_excluded_src, rocket_lazyload_iframe_excluded_patterns)

## Risks

We are not expecting any new issues to be caused by this enhancement. Since existing filters will work as they are now, no websites should be broken or unusable. Nothing changes for existing users. 

<p></p>

We might get a few questions on how to use the UI. This might be the first time many users learn about the possibility to exclude images from LazyLoad. This can be answered with documentation of course. 

## Acceptance Criteria

- The new UI is added as per the given specification. When none of the options for LazyLoad are enabled, the text area stays hidden. 

- Any class name, image filename, domain or iframe pattern added to the text area will prevent the image or iframe from LazyLoad. 

- Current filters continue to work as they do right now. 

## Documentation and Translations

The following documentations need to be updated:

- [<u>https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images</u>](https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images)

- [<u>https://docs.wp-rocket.me/article/1260-disable-lazyload-iframes</u>](https://docs.wp-rocket.me/article/1260-disable-lazyload-iframes)

- Since the doc linked from the UI is [<u>https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket</u>](https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket) it needs to be updated with explanations for using the text area for exclusion. 

- Helper plugin can be deprecated if needed - [<u>https://github.com/wp-media/wp-rocket-helpers/tree/master/lazyload/wp-rocket-lazyload-disable-src</u>](https://github.com/wp-media/wp-rocket-helpers/tree/master/lazyload/wp-rocket-lazyload-disable-src)

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4224254

**Comment by crystinutzaa** [comment]
## Backend

**Update class WP_Rocket\Engine\Admin\Settings\Page**

- https://github.com/wp-media/wp-rocket/blob/3b8b2d7debc83641045f9af82baa08b14e41daed/inc/Engine/Admin/Settings/Page.php#L1014-L1032
- Update method assets_section(), to register the new field exclude_lazyload
- The field is a child of the lazyload_section
- Field data is visible if `Enable for images` or `Enable for iframes and videos` are enabled, hidden otherwise.
- The UI should be able to accept a class-name, part of an image filename, or the domain name (src) all in one text area. One per line. 


## Frontend

- @Tabrisrp for frontend shall we modify the Lazyload common dependency or we an use  the filters: `rocket_lazyload_excluded_attributes` , `rocket_lazyload_excluded_src` and `rocket_lazyload_iframe_excluded_patterns` and add the values from the field: `exclude_lazyload` option to be excluded ?
Which solution is the best?


- Existing filters continue to exist and work (rocket_lazyload_excluded_attributes, rocket_lazyload_excluded_src, rocket_lazyload_iframe_excluded_patterns)

**Comment by Tabrisrp** [comment]
Since the exclusion field is specific to WP Rocket, and not (as of now) for the lazyload standalone plugin, we should modify WP Rocket files specifically, and not the common library.

**Comment by crystinutzaa** [comment]
@Tabrisrp so we shall use those filters, right?

**Comment by Tabrisrp** [comment]
We need to combine the filters values with the option value, yes
