### ISSUE TITLE
JS Console errors when Preload Links and Combine JS are both ON

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#3078]
We have 2 customers who have reported that when Preload Links and Combine JS features are both ON, they get console errors. These errors cause JS to fail and our scripts to stop working.

This happens when a customer script has a naming collision with our script. 

Why? Our gulp uglify mangle process removed our scripts' unique namespaces and replaced them with generic single character names. If another script has that same variable name, this happens.

**To Reproduce**

1. [Install this script](https://github.com/danielstjules/blankshield/blob/master/blankshield.min.js). You can enqueue in a theme or helper plugin. Make sure it enqueues _before_ the Preload Links script.
2. Turn on the Preload Links feature.
3. Turn on the Combine Js feature.
4. Open the web page in the browser (incognito)
5. Inspect anything on the page.
6. Open the Console tab.

Notice the error in the console. Turn off Combine JS feature. Refresh. Notice no error in the console.

**Expected behavior**
WPR scripts should retain their scope (either by namespace or IIFE) and not have naming conflicts with other scripts.

**Root Cause**
The problem is due to scope. When we optimize the minified script for production, we use a gulp task. That task runs Babel (to convert from modern JS to an older version that more browsers support), minify, and mangle (compresses names and space to free up more bytes). The mangle part saves us about 1000 bytes in the script size. Yes, we want that. But it's also renaming our unique namespace. Darn it. 

props to @engahmeds3ed 

**Solution**
We need the mangle task as it compresses the Preload Links script by ~1kb. We need it.

We will add an IIFE around the Preload Script and LazyLoad Scripts scripts. The IIFE provides a functional scope, which thereby encapsulates each script and prevents naming conflicts.

**Backlog Grooming (for WP Media dev team use only)**
- [X] Reproduce the problem
- [X] Identify the root cause
- [X] Scope a solution
- [X] Estimate the effort

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1278249931/193661?folderId=2135277
