### ISSUE TITLE
Updated WP_ROCKET_WP_VERSION_TESTED to 5.5.1 (or newer)

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#3081]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the issue**
- Right now it's set to `5.4.1` - https://github.com/wp-media/wp-rocket/blob/8f7f67b621e5085ccf6424a08a15ce636e4fbf2f/wp-rocket.php#L23
- We know it works with `5.5.1`

**Additional context**
A ticket related to this - https://secure.helpscout.net/conversation/1277592690/193388?folderId=273761

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
This is a trivial change. [XS]
We can get this into the 3.7.1 release
