### ISSUE TITLE
Compatibility with Simple Webp Images

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3087]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Simple Webp Images plugin prevents WP Rocket from caching pages if their **HTML Output Buffering is enabled**.
Minification and combination assets creations seem to go through and the resulting files are stored on their respective directories.

**To Reproduce**
1. Go to **Settings > Simple Webp Images**
2. Check **Enable HTML Output Buffering**
3. Click the save button
4. WP Rocket is no longer able to cache files

**Expected behavior**
WP Rocket caches pages.

**Screenshots**
![](https://i.vgy.me/U1knXm.png)
![](https://i.vgy.me/1a6Emm.png)

**Additional context**
Link to the plugin - [https://wordpress.org/plugins/simple-webp-images/](https://wordpress.org/plugins/simple-webp-images/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
https://secure.helpscout.net/conversation/1276981666/193082/

**Comment by arunbasillal** [comment]
@webtrainingwheels Since the plugin has just 60 active installs it doesn't make any sense to do it at our end. Can you please take the initiative to contact the developer directly and fix it at their end?

**Comment by piotrbak** [comment]
The plugin was not updated for 2 years and it's just 100 installs.
