### ISSUE TITLE
Delay JS - Google Ads script uses DOMContentLoaded

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3089]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

By default, WP Rocket delays Google Ads scripts,  with the `adsbygoogle` keyword which is in the prepopulated list of scripts to delay.

According to the discussion in [Slack](https://wp-media.slack.com/archives/C43T1AYMQ/p1599758505118600), @engahmeds3ed mentioned that the Google Ads script is using `DOMContentLoaded`.

The way our feature is implemented, the execution of such scripts should not be delayed.

**To Reproduce**

This isn't relevant here.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@vmanthos Thanks for the report. Isn't it a duplicate of #3085 though?

**Comment by vmanthos** [comment]
@arunbasillal 

GitHub's search played tricks on me. 😅

I'll add the link to the Slack discussion in #3085 and I'll close this one.
