### ISSUE TITLE
Delay JS causing a particular product page to not load (blank page)

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3090]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

FYI I'm a paying customer (info@gevcen.be), I tried to contact the support but they are not of any help...

**Describe the bug**
Whatever the JS line added in the feature, this functionality breaks a particular product page :
https://www.gevcen.be/cordonnerie/produits-dentretien/cirages/saphir-surfine/
(In the meantime, I am disabling the feature otherwise my customers can't visit this page as this is a live site)

**To Reproduce**
1. Enable the feature
2. Either keep the pre-populated or add a custom list (provided below)
3. Either keep them all or even just keep 1 line (even if it's a third-party domain, which obviously cannot explain why the page would go totally blank)

**Environment**
Hosting : SiteGround GoGeek
PHP : 7.4.8 (Standard)
WordPress : 5.5.1
WooCommerce : 4.4.1
Other Plugins : all up-to-date

**Expected behavior**
If I enable the feature and add some scripts in the list, the given page should load. Whatever the scripts added in the list below, none explain why the page would go blank and not load at all.

I tried to install Flying Scripts and added the same scripts in the list, that plugin didnt cause this white page. If I revert again to your feature, it's causing this white page.

I tried to reproduce the issue on live site, I was able to reproduce it many times. Then, I tried to reproduce the issue on staging, but it didnt happen on staging (strange...).

**Product Details**
Maybe some elements that can help you reproduce the issue. This product is a variable product with about 80+ variations, all loaded upon page load through a custom PHP code in functions.php as below (not sure if it's directly related but I just inform you about it) :
```
function custom_wc_ajax_variation_threshold( $qty, $product )
{
    return 500;
}
add_filter( 'woocommerce_ajax_variation_threshold', 'custom_wc_ajax_variation_threshold', 10, 2 );
```
**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/92959747-a7f94d00-f46c-11ea-901e-50f6a7bb2f95.png)
![image](https://user-images.githubusercontent.com/51261962/92959769-b182b500-f46c-11ea-908f-c2acc7d3b4d8.png)

**Additional context**
https://sgevcen.tinytake.com/tt/NDYyMTU2M18xNDY0NjA3OQ
(download the video to see it full screen)

```
/wp-content/caos-webfonts/fonts.css
/wp-content/cache/min/1/8b5e67c72104be03cdd656c771280c18.js
/wp-content/plugins/jquery-updater/js/jquery-3.5.1.min.js
/wp-content/plugins/contact-form-7/includes/js/scripts.js
/wp-content/plugins/js_composer/assets/css/js_composer.min.css
/wp-content/plugins/js_composer/assets/lib/bower/isotope/dist/isotope.pkgd.min.js
/wp-content/plugins/mega-addons-for-visual-composer-pro/css/ihover.css
/wp-content/themes/woodmart/js/functions.js
/wp-content/themes/woodmart/style.css
/wp-content/uploads/wga-cache/local-ga.js
translate.googleapis.com
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by gevcen** [comment]
In the meantime, I am disabling the feature otherwise my customers can't visit this page. This is a live site.

**Comment by gevcen** [comment]
I've done one more test with clear video capture, where you can perfectly see explanations with the problem. I was able to reproduce the issue many times on live site, so clearly the Delay JS feature has a problem :

https://sgevcen.tinytake.com/tt/NDYyMjg3Ml8xNDY1MzAzMw

**Comment by engahmeds3ed** [comment]
Thanks @gevcen and sorry about what you are facing here.

Now I can see the issue with your content and this is because your product page html size, you can see the page without wp rocket from here: https://www.gevcen.be/cordonnerie/produits-dentretien/cirages/saphir-surfine/?nocache

**Reproduced locally?**
Yes, Now I can see the issue locally and found the root cause.

**What's next?**
I'm checking with the team to get a solution and I will update you once finishing that which should be very soon.

**Comment by Tabrisrp** [comment]
This HTML is causing the `preg_replace_callback()` to reach the backtrack_limit, which results in a return value of `null` instead of the expected HTML.

We can check for the return value of the function, and return the unchanged HTML if the value is not as expected, to prevent the blank screen. The page won't have delay JS applied, but it will at least remain usable.

**Comment by LawaxP** [comment]
Hi @gevcen 
Did you solve your problem ? I have the same error in my logs.
I would like to determine if this can be the source of my errors 503.
Thanks

**Comment by gevcen** [comment]
@LawaxP 
Yes and No.

Yes because WP Rocket has implemented a workaround in their plugin, so that the Delay JS feature gets automatically bypassed when the HTML page is too large. In my case, the page was above 2 MB (because of a high amount of pictures in the gallery, even if pictures were very compressed already) and that is a very high size for a website page.

No because the workaround is providing me lower PageSpeed score, therefore lower SEO scores, and consequently lower user experience, even though technically the page now loads correctly indeed (so there is no white page anymore).

Hope this helps you
