### ISSUE TITLE
Static name for Javascript and CSS file Generated

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#3092]
As of now, WP-Rocket generates some random strings as the file name of the JS and CSS file. So, whenever the file is regenerated, the caching systems such as the NGINX fast-CGI cache generates a 404 error because the previous file cached by the system doesn't exist anymore. Also, a readable name for these files would be much better than some random-long string.

Another problem I faced in Siteground hosting where I hosted one of my sites is that, because the file name was too big, the hosting provider returned access denied error for some reason. I was able to fix that by reaching them out.

So overall, if the file names of these two JS and CSS files can be set to something static (maybe using the website's name or something) and whenever the file is regenerated, the existing file is replaced, it will be a small but effective improvement.

**Comment by arunbasillal** [comment]
Hello @MuhammedSwalihct 

Browser caching for JS and CSS files are set to 1 year. This means if we use the same filename, a returning user (assuming they haven't cleared their local browser cache), will see the same old file for 1 year. Any changes you make to the CSS or JS will not be reflected. 

> So, whenever the file is regenerated, the caching systems such as the NGINX fast-CGI cache generates a 404 error because the previous file cached by the system doesn't exist anymore

Are these caching systems caching the HTML too? Can they be configured not to do that? 

The file names are changed only if you manually clear the cache or update CSS/JS minifcation options. All of them are listed here under `/cache/min` section - https://docs.wp-rocket.me/article/1135-when-does-wp-rocket-delete-which-files

So this shouldn't be an issue in any normal use cases. Hope that helps.
