### ISSUE TITLE
Exclude inline scripts which have listeners for some events from Delay JS

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3093]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
If you used an inline script which uses the following JS events, they won't be triggered if the user interacted with the page after being loaded.

**To Reproduce**
1. On any theme page template add the following script
```
<script type="text/javascript" id="script_id">
window.addEventListener('load', function () {
    alert("Hi I need to be alerted");
}, false);
</script>
```
2. Open WP Rocket admin page and enable Delay JS execution option and add `script_id` to the list of inclusion scripts keywords .
3. Open the page frontend, the script is delayed successfully.
4. You will never see the alerted message.

**Expected behavior**
This type of scripts needs not to be delayed anymore.

**Additional context**
JS events are as follows:-
1. load
2. readystatechange
3. DOMContentLoaded

jQuery events are as follows:-
1. jQuery(window).load(
2. jQuery(document).ready(

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
I feel this is a really good idea and quite simple from our end (for inline scripts). Kudos Ahmed!

One UX issue that I can think of is that the user might specify an inline script to be delayed and when it's not delayed might wonder why. But I don't think we have to cover that case now (other than mentioning this in the documentation). We can cover that case when this becomes too common. 

I vote for implementing this as a `priority: low` enhancement when we have some breathing space. After 3.8 probably. 

What do you think @GeekPress and @Tabrisrp?

**Comment by GeekPress** [comment]
I will keep the `priority: medium` depending to the number of tickets we have related to this problem.

**Comment by Tabrisrp** [comment]
In my opinion, since we are working with an inclusion list for this option, we should not start having exclusions in parallel. This will be confusing for everyone.

A better approach is to refine the inclusion list to make sure it only matches with "safe" scripts that we tested and curated.

**Comment by vmanthos** [comment]
**Related ticket & details:** https://secure.helpscout.net/conversation/1339022046/212312/#thread-3862248172

The following inline script is "picked up" due to the `adsbygoogle.js` keyword: https://snippi.com/s/e549491

Delaying the related JavaScript file `/wp-content/plugins/media-ace/includes/gallery/js/gallery.js` is causing a new JavaScript error because of the use of `$(document).ready()`.

**Comment by GeekPress** [comment]
The new Delay JS in 3.9 is compatible with these events. I'm closing this issue.
