### ISSUE TITLE
Web Stories plugin compatibility: validation errors with JS file optimizations

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#3102]
**Describe the bug**

As reported [in this issue](https://github.com/google/web-stories-wp/issues/4490), when using the [Web Stories plugin](https://wp.stories.google/) (release candidate) and some of WP Rocket's JavaScript file optimization options, AMP [validation errors](https://jmp.sh/mIrkNRS) occur on the story URL (current permalink base _/stories/_). From testing, the _JS Minify_ and _Combine_ options look to be involved: 

<img width="554" alt="Screen Shot 2020-09-10 at 9 42 20 PM" src="https://user-images.githubusercontent.com/8108643/93253125-4a565080-f74b-11ea-815c-c4782038005e.png">

**To Reproduce**

1) Enable the _JS Minify_ and _Combine_ options on the **File Optimization tab**
2) See validation errors on the story URL (using either the AMP validator browser extension, AMP test tool, or AMP validator)

**Expected behavior**

No validation errors occur on the story URL when using WP Rocket + Web Stories

**Additional context**

- The story URL is an AMP document will need to adhere to the [AMP specification](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#ampd) in order to be valid
- As WP Rocket already works to have AMP compatibility, one method to consider is looking for the HTML tag to check if the page is AMP. This [pull request](https://github.com/futtta/autoptimize/pull/340) for the Autoptimize plugin may be a good reference. 
- Note the story URL permalink base may become [customizable in the future](https://github.com/google/web-stories-wp/issues/4459)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
A couple of related tickets:

- https://secure.helpscout.net/conversation/1241679983/183899/

- https://secure.helpscout.net/conversation/1241443020/183835

**Comment by webtrainingwheels** [comment]
@arunbasillal @GeekPress They have just announced the release of the first stable version. So it would be great to get ahead of this before it can start generating tickets

**Comment by ernee** [comment]
Quick follow up that the default permalink base is now _/web-stories/_ with the [stable release](https://wordpress.org/plugins/web-stories/). In the meantime, one method to prevent validation errors on these URLs is to exclude them on the [Advanced Rules tab.](https://jmp.sh/b2mELvw)

**Comment by camilamadronero** [comment]
Related ticket https://secure.helpscout.net/conversation/1300969682/199907/

**Comment by swissspidy** [comment]
#3245 should help a lot here
