### ISSUE TITLE
Some scripts are not being delayed in 3.7.1

### ISSUE THREAD

**Issue by Davidacu** [wp-media/wp-rocket#3109]
Some scripts from the safe to delay list are not being delayed in 3.7.1

**Preconditions:**
1. Have Delay JS feature enabled.
2. The page under test is not excluded from cache.
3. The page under test is not excluded from Delay JS 

**Steps to reproduce**r:
1. Go to https://rocketlabsqa.dev/getbutton-delay-js-script/
2. Observe the page bottom right corner

**Expected behavior**
Only after user interaction, the Whatsapp icon will load in the bottom right corner.

**Actual**
The icon is displayed right away, the request to static.getbutton.io is fired right away, the inline script is not encoded in the page source, the attribute `data-rocketlazyloadscript` is not added either.
https://screencast-o-matic.com/watch/cYQD08Jgx6

**Additional context**
The scripts loaded in these pages are not delayed either:
https://rocketlabsqa.dev/optinmonster-delay-js-script/
https://rocketlabsqa.dev/delay-js-script-linkedin-ads/
https://rocketlabsqa.dev/delaj-js-script-twitter-ads/
https://rocketlabsqa.dev/delay-js-script-fb-chat/
https://rocketlabsqa.dev/delay-js-script-leadpages/
https://rocketlabsqa.dev/delay-js-script-hotjar/
https://rocketlabsqa.dev/delay-js-script-smartsupp/
https://rocketlabsqa.dev/delay-js-script-tawk-api/
https://rocketlabsqa.dev/delay-js-fbevents-js/
https://rocketlabsqa.dev/delay-js-shopify-buy/

These are delayed as expected:
https://rocketlabsqa.dev/delay-js-script-feedback-company-widget/
https://rocketlabsqa.dev/delay-js-scripts-twitter-widgets/
https://rocketlabsqa.dev/delay-js-script-facebook-page-plugin/
https://rocketlabsqa.dev/delay-js-script-fb-plugins/
https://rocketlabsqa.dev/delay-js-script-google-translate/
https://rocketlabsqa.dev/delay-js-script-manychat-widgets/
https://rocketlabsqa.dev/delay-js-script-recaptcha/
https://rocketlabsqa.dev/delay-js-script-shareaholic/
https://rocketlabsqa.dev/delay-js-script-sharethis/
https://rocketlabsqa.dev/delay-js-script-add-to-any/
https://rocketlabsqa.dev/delay-js-script-fontawesome/
https://rocketlabsqa.dev/wpdiscuz-comments/
https://rocketlabsqa.dev/delay-js-script-pinterest/
https://rocketlabsqa.dev/delay-js-google-ads/
https://rocketlabsqa.dev/delay-js-widget-trustpilot/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the problem
Reproduced on test site

### Identify the root cause
The RegEx to find scripts was modified in #3097 to fix the reported issue, but the `s` flag was removed. It needs to be preserved to match new lines in inline JS content.

### Scope a solution

Add back the `s` flag to the affected RegEx

### Estimate the effort

Effort `[XS]`
