### ISSUE TITLE
 PHP Parse error:  syntax error, unexpected ':' since 2.9.4

### ISSUE THREAD

**Issue by TangRufus** [wp-media/wp-rocket#311]
WP Rocket 2.9.4 gives the following error. 
```
PHP Parse error:  syntax error, unexpected ':' in /var/www/htdoc/wp-content/plugins/wp-rocket/inc/3rd-party/plugins/sf-move-login.php on line 41
```

Should that `:` be `;` on https://github.com/wp-media/wp-rocket/blob/8d022b90184e7fc57c5d0469f6feb2e41bf83955/inc/3rd-party/plugins/sf-move-login.php#L41?

**Comment by Tabrisrp** [comment]
You're correct, it has been fixed with this commit https://github.com/wp-media/wp-rocket/commit/2a235935978f81549ffc254853e287485d1521c7
