### ISSUE TITLE
Stop removing the empty lines on .htaccess

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3113]
**Describe the solution you'd like**
Stop removing the empty lines on .htaccess since it doesn't cause any issue or make it slower to WP Rocket proper work. 

The .htaccess files sometimes have many "Sections" - which are always separated by lines starting with # - and having the line breaks removed just adds more mind-work to find what we're looking for. So I can't see any real improvement on having those empty lines removed, just like wp-config.php.

**Additional context**
From productboard:
https://wp-media.productboard.com/insights/shared-inbox/notes/9673577

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
In `inc/functions/htaccess.php`, `flush_rocket_htaccess()` function, remove the filter and conditional between lines 59 and 69.

### Estimate the effort ✅
effort `[XS]`

**Comment by Presskopp** [comment]
What about not deleting but replacing the regex like so:
https://regex101.com/r/Esp1BS/1

should result in the following, iinm

`$ftmp = preg_replace( "/\n{3,}/", "\n\n", $ftmp );`
