### ISSUE TITLE
Issue with Lazy load and ajax generated content

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#3117]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
There seems to be an issue with lazy load with ajax generated content like woocommerce "Load more" or ajax filtering plugins as Berocket ajax filters.

The issue is that content loads but the lazy load doesn't trigger so images are empty.

**To Reproduce**
Go to the following link:
https://rb.gy/qqpicm

Navigate on page 2 or hit load more.

**Expected behavior**
The images should load

**Comment by alfonso100** [comment]
Thank you for opening this issue. 
I'll be closing it in favor of https://github.com/wp-media/wp-rocket/issues/3215 which is already under investigation.
