### ISSUE TITLE
DelayJS default adsbygoogle keyword breaking Adsense functionality on Newspaper Theme

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3119]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The **Newspaper** theme creates its responsive google Ads spots using Javascript and `document.write`, like this: 
[https://jmp.sh/YH2vvdQ
](https://jmp.sh/YH2vvdQ)

When our **DelayJS** feature is enabled, we rewrite this code because it contains the **adsbygoogle** keyword and encode it as base64: https://jmp.sh/zKLJaU5 

So, the ad spots doesn’t exist in the HTML, triggering an error like this for each ad spot:
https://jumpshare.com/v/Mj2lb7BBWwSuucmb2TO7 

**To Reproduce**
1. On Newspaper theme, set some ad sizes
2. The theme will inject the ads like this: https://jmp.sh/YH2vvdQ
3. Enable DelayJS
4. The ads won't be created because the containers won't be generated: https://jmp.sh/zKLJaU5 

**Expected behavior**
We should exclude this inline Javascript from the DelayJS feature

**Additional context**
If I replace the DelayJS keyword to use **googlesyndication** instead of **adsbygoogle**  everything works as expected, the JS is delayed, and the ad containers are intact: https://jumpshare.com/v/APJLAmvb50QTsRbNyYQW

The specific console error is: 
`Object { message: "adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.", stack: "O@https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:69:574\nZl@https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:228:210\nTl@[.....]\nm.ba@https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:64:294\225\n", name: "TagError", pbr: true }
adsbygoogle.js:216:110`

Related Issue: 
https://github.com/wp-media/wp-rocket/issues/3085

HelpScout Ticket:
https://secure.helpscout.net/conversation/1282673567/194973/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
@arunbasillal What do you think of using `googlesyndication` instead of `adsbygoogle` for the keyword?

From the tests above and the code snippets available, the only script we need to delay is the external, not the inline one.

**Comment by Tabrisrp** [comment]
@arunbasillal I can't do the grooming without your input on the keyword to use. On this issue there is a proposition for `googlesyndication`. On issue #3085, There is a proposition for `adsbygoogle.js`.

What do we want to do?

**Comment by arunbasillal** [comment]
@Tabrisrp Sorry about the delay. I am leaning towards `adsbygoogle.js`. 

- The latest suggestion from Adsense only includes an external script and no inline script. So using `adsbygoogle.js` would work. 
- `adsbygoogle.js` is more readable as compared to `googlesyndication`. It implies Google Ads. 
- We have good confirmation here - https://github.com/wp-media/wp-rocket/issues/3085#issuecomment-693731345

**Comment by Tabrisrp** [comment]
### Scope a solution
- Replace `adsbygoogle` by `adsbygoogle.js` in the default list for delay JS.
- Add a method to update the value in the existing option if it's present, during the update process
- Update existing automated tests
- Add new automated tests for the new method

### Estimate the effort
Effort `[XS]`

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1312796984/203470?folderId=377611
customer confirmed this worked: 
>Replace adsbygoogle by adsbygoogle.js
