### ISSUE TITLE
Remove "Image Optimization" menu when WP_ROCKET_WHITE_LABEL_ACCOUNT is used

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3120]
**Describe the solution you'd like**
The customer wants to be able to disable Imagify ads in WP Rocket. We could add this to the WP_ROCKET_WHITE_LABEL_ACCOUNT constant.

**Additional context**
From productboard:
https://wp-media.productboard.com/insights/shared-inbox/notes/9688386

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
- In `inc/views/settings/page.php`, add a check for `rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT` )` on line 44
- Inc `Engine/Admin/Settings/Subscriber::add_imagify_page()`, add a check for `rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT` )`

### Estimate the effort ✅
Effort `[XS]`
