### ISSUE TITLE
PHP fatal error caused by missing autoloaded classes from the Cloudflare addon

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3123]
We are receiving numerous tickets from customers that are receiving a Fatal error message after updating WP Rocket to 3.7.1.

This is the error message: 
```
Uncaught Error: Call to a member function withArgument() on null
in /nas/content/live/gie/wp-content/plugins/wp-rocket/inc/Addon/ServiceProvider.php on line 79
```

Our devs are currently investigating this to find and fix this issue.

**Comment by alfonso100** [comment]
The bug has been identified and the fix is on its way: https://github.com/wp-media/wp-rocket/pull/3122

**Comment by Tabrisrp** [comment]
classes are added to the autoloader (whatever the namespace) only if they are part of the corresponding `require`.

So on a default `composer install`, composer is correctly reading from the `composer.json` located in the Cloudflare Addon directory, and adding the `WPMedia\\Cloudflare` namespace to the autoloader.

But when running the production command, it doesn’t read from it anymore, so we need to have the PSR-4 value in the main `composer.json` file to make sure it’s autoloaded
