### ISSUE TITLE
Add more GT Metrix IPs to is_speed_tool

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3126]
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/Buffer/class-tests.php#L843
Here we are checking GT Metrix server IPs so that we can ensure that a cached page is sent. 

GT Metrix has added more servers so we need to add more IPs here. 
Their full list can be found here: 
https://gtmetrix.com/locations.html

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
Add the missing IPs to the `$ips` array in the `Buffer/Tests` class

### Estimate the effort ✅
Effort `[XS]`
