### ISSUE TITLE
Delay JS - Google "api js" still delayed altough removed from the list

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3127]
1) I've removed the google "api js" of the default list (because it's generating error => known issue in your repository)
2) I cleared cache + dev mode in cloudflare
3) the api is still being delayed

video capture : https://sgevcen.tinytake.com/tt/NDY0NDg2N18xNDcxNzc0NA

**Comment by arunbasillal** [comment]
Hello @gevcen I just checked the website and it doesn't seem to be having the console error. 
Since it's specific to a website, if the issue persists, please open a support ticket so that our support team can investigate - https://wp-rocket.me/support

Best regards.
