### ISSUE TITLE
Delay JS - File "JSON" added to list of delay, not working

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3129]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On my website, I have an file "JSON" loaded from a third-party domain. I added the domain name of that site to the list of scripts to be delayed but it's not working. Is that expected?

**To Reproduce**
https://gtmetrix.com/reports/www.gevcen.be/BGHANuGM

**Expected behavior**
Should be delayed if added to the list, no? Or it doesn't apply to JSON?

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/93667218-60824a80-fa84-11ea-8967-2a9db89cf054.png)

**Additional context**
/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@gevcen It only applies to JS files and this is expected.
