### ISSUE TITLE
Rewrite font files URLs when WP Rocket saves external CSS

### ISSUE THREAD

**Issue by socialpreneur** [wp-media/wp-rocket#3131]
**Is your feature request related to a problem? Please describe.**
Since 3.7 WP Rocket keeps local cached copy of external CSS such as font awesome. However, links inside CSS files are still linked to original URLs such as font awesome CDN, and these still make the site slower.

**Describe the solution you'd like**
WP Rocket should also rewrite links and save .woff and other font files locally.

**Comment by GeekPress** [comment]
Hi @socialpreneur 

Thanks for sharing this suggestion.

I don't think this is something we will do.

Why?
It means we will have to download and saved locally all external fonts. It's a huge extra work and we have some doubts about the benefits since you can preload the fonts within WP Rocket.
