### ISSUE TITLE
PHP warning - RocketCDN API  strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3132]
**Before submitting an issue please check that you’ve completed the following steps:**

- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

We check if requests are done to the RocketCDN API URL, and we make sure the `token` is preserved:
https://github.com/wp-media/wp-rocket/blob/10a5ab2606759dd82d2a4c89732d6ef76ea4120d/inc/Engine/CDN/RocketCDN/APIClient.php#L249

The `$url` can be a `WP_Error` object. When it is, the following is being logged in `debug.log`.

```
PHP Warning:  strpos() expects parameter 1 to be string, object given in /home/velobrival/public_html/wp-content/plugins/wp-rocket/inc/Engine/CDN/RocketCDN/APIClient.php on line 249
[16-Sep-2020 08:44:34 UTC] PHP Recoverable fatal error:  Object of class WP_Error could not be converted to string in /home/velobrival/public_html/wp-includes/kses.php on line 1611
```

**To Reproduce**
1. Enable WordPress's debugging.
2. Pass a `WP_Error` object to the `preserve_authorization_token()` method, e.g. https://snippi.com/raw/xukhkz1
3. Check the debug.log for warnings.

**Expected behavior**

No PHP warnings should be there in the `debug.log` even when `WP_Error` objects are passed into this function.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1284756787/195526?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
The second parameter for `http_request_args` should always be a string. Reading the ticket, there was a mistake caused by some custom code from the user, causing the `WP_Error` to be passed instead of a string for the URL.

This looks like a very edge case. We _could_ guard on it, but this is an extremely unlikely case where the issue is coming from a _doing_it_wrong_ originally.

@arunbasillal FYI

**Comment by arunbasillal** [comment]
@vmanthos Based on Remy's feedback, my vote is not to do anything about it. While we can, should we be guarding against every possibility? And in the worst case, all it creates is a warning and not a fatal error. 

Shall we file it off as an unlikely edge case?

**Comment by vmanthos** [comment]
> Shall we file it off as an unlikely edge case?

This is fine with me! 👍
