### ISSUE TITLE
Eliminate render-blocking doesn't work at all

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3135]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
I enabled the setting "Optimize CSS" to create the CPCSS for both desktop & mobile but after checking the Google PageSpeed, it still requests to eliminate render-blocking CSS. I made sure to clear cache and have Cloudflare dev mode enabled, but it still occured as such.

**To Reproduce**
https://sgevcen.tinytake.com/tt/NDY1MjA3Nl8xNDc0MzA5OQ

**Expected behavior**
If CPCSS is activated, there should be no render-blocking CSS anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/93879634-565a8900-fcdc-11ea-9068-2ffcdb130c12.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@gevcen This is a very specific issue. Please use our support channel for the same - https://wp-rocket.me/support/

Please use GitHub to report issues that are not site specific and are more generic. Thanks for your contribution.
