### ISSUE TITLE
Custom development - Running code just before WP Rocket

### ISSUE THREAD

**Issue by daigo75** [wp-media/wp-rocket#3136]
This is not an issue, nor a feature request, more of a developer question. 

A client asked me to implement a customisation, whose purpose is to help WP Rocket serving custom content based on specific criteria. For this to work, I would need to implement some custom code that runs before WP Rocket, to prepare the appropriate "environment", so to speak. 

Do you have some guidelines explaining how that could implemented? The custom code doesn't necessarily need to access WP Rocket's features, the important thing is that it runs before the caching logic. 

If you don't have specific guidelines for this kind of development, would you be so kind to point me in the right direction? For example, if you could tell me how WP Rocket loads and where it intercepts the standard WordPress flow, that could help. Thanks.

**Comment by Tabrisrp** [comment]
Hi,

The most appropriate moment would be when the `rocket_buffer` hook is fired. This hook takes the page html as its parameter, and sends it back optimized.

In term of the loading, WP Rocket uses the `advanced-cache.php` file to load its cache files during the loading process, and either serve the cache if it exists, or create it if it doesn't.

**Comment by daigo75** [comment]
@Tabrisrp Hi Remi, thanks for your reply. In my case, I would have to intervene before WP Rocket does anything at all. Would the `advanced-cache.php` file be the one loaded within `wp-settings.php`? Normally, it's either empty, or a zero-length file, does WP Rocket replace it with its own?

**Comment by Tabrisrp** [comment]
Yes it's the file loaded in `wp-settings.php`, WP Rocket creates it to manage the cache system.
