### ISSUE TITLE
CDN - Prevent Relative URLs to be replaced by CNAME inside <p> blocks

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3138]
**Before submitting an issue please check that you’ve completed the following steps:**
- WP Rocket 3.7.1.1
- Similar issue for < code > blocks: https://github.com/wp-media/wp-rocket/issues/2322

**Describe the bug**
When there’s a mention to a file with a relative path inside a paragraph block, if CDN feature is enabled, the CNAME will take place.

![Capture d’écran 2020-09-23 à 15 40 40](https://user-images.githubusercontent.com/11939512/94022403-5a0e0e80-fdb5-11ea-916b-8e87c9abb6aa.png)

![Capture d’écran 2020-09-23 à 15 38 55](https://user-images.githubusercontent.com/11939512/94029583-3ea70180-fdbd-11ea-955a-e96e05010aff.png)

**To Reproduce**
1. create a paragraph inside a post and insert a relative path to a static file
2. Activate the CDN feature and enter a CNAME
3. Check your post

**Expected behavior**
The CNAME shouldn’t appear there. The CNAME doesn’t replace the domain name if it’s there.

Ticket: https://secure.helpscout.net/conversation/1284566998/195463?folderId=273766

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The issue will be resolved while using the `rocket_cdn_relative_paths` filter:
https://docs.wp-rocket.me/article/42-using-wp-rocket-with-a-cdn#troubleshoot
