### ISSUE TITLE
Delay JS - IE11: Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3140]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The ""rocket-delay-js-js-after" script we use contains a `forEach` method:
https://github.com/wp-media/wp-rocket/blob/7e8d54aaf5ad8ddffda404d7011931f1a43f3a53/assets/js/lazyload-scripts.js#L59

That's not supported on IE11 when using ES6, and results in the following error:
```JavaScript
Object doesn't support property or method 'forEach'
```
which breaks the feature.

I'm quoting @engahmeds3ed who was kind enough to clarify the "why" this doesn't work in IE11:

> forEach() is actually working on IE11, just be careful on how you call it.
> querySelectorAll() is a method which return a NodeList. And on Internet Explorer, foreach() only works on Array objects. (It works with NodeList with ES6, not supported by IE11).

**To Reproduce**

1. Enable **Delay JavaScript execution**.
2. Visit a site using IE11 on your PC or **browserstack.com** .
3. Open the JavaScript console.
4. See error.

**Expected behavior**

The feature should work on IE.

**Screenshots**

![image](https://user-images.githubusercontent.com/193660/94146415-96587200-fe7c-11ea-9a5f-621c7375e129.png)

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1287835559/196361?folderId=2135277

**Potential solution:** https://rimdev.io/foreach-for-ie-11/

**IE11 worldwide market share:** [2.1% the previous year]( https://gs.statcounter.com/browser-version-market-share/desktop/worldwide/#monthly-201908-202008)

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by arunbasillal** [comment]
Thanks Vasilis. If I understand correctly this will make the scripts useless on IE11, right? Not just the feature, but any delayed script will not work at all.

**Comment by vmanthos** [comment]
@arunbasillal @piotrbak informed me that for **Preload links** Jonathan asked to drop IE11 compatibility:
https://github.com/wp-media/wp-rocket/pull/2989#issuecomment-674140532

Something to consider when making your decision.

**Comment by GeekPress** [comment]
@vmanthos My comment was on the Preload Links feature. On this one, if the feature doesn't work, it won't break anything on the website. This is why we decided to not be compatible with IE11. Our code is less complex by dropping IE compatibility.

For Delay JS, the situation is different. If the script doesn't work, it breaks the website.

**Comment by vmanthos** [comment]
@GeekPress Good point, Jonathan!
Thank you!

**Comment by piotrbak** [comment]
@arunbasillal @GeekPress I was talking with @Davidacu about this yesterday. It was discovered by him during the QA before the 3.7 release:
https://wp-media.slack.com/archives/GUKB44GNN/p1598486724004900
https://wp-media.slack.com/archives/G012GDXJGQN/p1597420741058000

**Comment by arunbasillal** [comment]
@piotrbak Thanks, I was wondering the same as to how it was not discovered in QA. 
It seems that my comments in that thread distracted everyone from the actual issue and it slipped through the cracks. The issue is also noted in the release note - https://github.com/wp-media/wp-rocket/releases/tag/v3.7

Let's talk about this in our retro so that we can improve.

**Comment by engahmeds3ed** [comment]
**Reproduce the problem:** Yes

**Identify the root cause:** Yes

The problem mainly is on `document.querySelectorAll` that returns `NodeList` and on IE11 forEach is used only with type array.

https://github.com/wp-media/wp-rocket/blob/7ec9d996f004707a57c4c8476090d5bd943051f0/assets/js/lazyload-scripts.js#L57-L59

**Scope a solution**
We can simply convert your NodeList into an array with the slice.call() method so it can easily work with forEach.

```
const scripts = Array.prototype.slice.call( document.querySelectorAll( `script[${ this.attrName }]` ) );
```
**Estimate the effort**
[XS]

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/1301839373/200133/
