### ISSUE TITLE
UX improvement - "Restore Defaults" button for Delay JS is clicked accidentally in place of "Save Changes"

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#3145]
**Is your feature request related to a problem? Please describe.**
Our team mate @camilamadronero reported in Slack that she accidentally clicked the "Restore Defaults" button few times. Other team mates agreed. Our customers might also face this issue and they might loose all the scripts that they added manually. 

![image](https://user-images.githubusercontent.com/5751474/94235915-f78a4f00-ff29-11ea-9305-c0112fd4b7e9.png)

**Describe the solution you'd like**
We could make the button less prominent. I have two suggestions. 

One, make the button into an inline link. 
![image](https://user-images.githubusercontent.com/5751474/94237576-b5164180-ff2c-11ea-9942-743bf1335b7a.png)

Move the button to the right and make it smaller (5px padding instead of 8px. 5px is the padding for `View my account` button in the dashboard).
![image](https://user-images.githubusercontent.com/5751474/94237667-d4ad6a00-ff2c-11ea-94e2-61adb9187a98.png)

**Comment by camilamadronero** [comment]
Thanks, Arun! 

I'd vote for the inline link option, because:

- the smaller button option still feels too visible and therefore _clickable_
- restoring defaults doesn't seem to be a commonly needed option, so it's ok to "hide" it a little

Cons:

- customers could still accidentally click on it, confusing it with a doc link

**Comment by webtrainingwheels** [comment]
I agree with what @camilamadronero said!

**Comment by Mai-Saad** [comment]
What about?
1- Having confirmation message when the button clicked to mitigate clicking by mistake.
2- Making the btn dimmed till scripts to delay were changed than defaults to mitigate confusion when clicked and doing nothing

**Comment by GeekPress** [comment]
I'm closing this one as this problem will be fixed with the Delay JS new UI.
