### ISSUE TITLE
Import no longer works on WordPress 4.7.1

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#315]
```
PHP Warning:  gzinflate(): data error in /wp-content/plugins/wp-rocket/inc/admin/options.php on line 937
PHP Notice:  Undefined index: file in /wp-content/plugins/wp-rocket/inc/admin/options.php on line 939
PHP Warning:  file_put_contents(): Filename cannot be empty in /wp-content/plugins/wp-rocket/inc/admin/options.php on line 939
```

Apparently something changed and the import is blocked because the mime type we send `text/plain` doesn't correspond to the real one defined by PHP `application/octet-stream`

**Comment by glueckpress** [comment]
✅  Tested with WP 4.7.2:

- Settings files exported under 2.9.4 apparently were corrupted during export. Import of those deletes all settings.
- Under 2.9.5-beta2 export and import of (uncorrupted) settings files work like a charm.
