### ISSUE TITLE
JS countdown for promotion & renew notices

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#3158]
Sub-task for #3068 #3069 

- Write a countdown in JS for the promotion notice, and for the renew notice when license is soon expired
- Good tutorial here: https://www.sitepoint.com/build-javascript-countdown-timer-no-dependencies/

**Comment by GeekPress** [comment]
About the JS countdown, we can reuse the one used into our new website. It's actually ready, so we can ask the HTML/CSS/JS to the web agency.
