### ISSUE TITLE
Keep "Minify" working while files are excluded from combine

### ISSUE THREAD

**Issue by socialpreneur** [wp-media/wp-rocket#3162]
**Is your feature request related to a problem? Please describe.**
Since 3.7, WP Rocket introduced a new feature to locally cache external scripts if minification is activated. However with the current state of the plugin, if a user decides to exclude a certain file, it also gets excluded from minification. This means if external file is excluded, then WP Rocket fails to cache locally.

**Describe the solution you'd like**
Do not exclude from minification.

**Describe alternatives you've considered**
Do not use combine feature of WP Rocket.

**Comment by jazir555** [comment]
Agreed, needed.

**Comment by GeekPress** [comment]
Hi @socialpreneur

Thanks for your feedback.

Being able to separate exclusion from Combine and/or Minify will require another textarea. 

We won't go on this solution for two reasons:
- it's going to complexify the configuration
- One file not being minified won't hurt your loading time in a signifiant bad way.

**Comment by socialpreneur** [comment]
@GeekPress Just by reading your answer, I don't think are on on the same topic. ;) I originally never requested to add another textarea idea you mentioned, so I'm a bit confused right now.

I just hope WP Rocket will continue to cache external scripts locally at any condition if a user wants it, even the script is excluded from minify.

**Comment by GeekPress** [comment]
@socialpreneur Ok I got your point now.

We still have the same problem ;) 

By excluding a CSS/JS file from the Minify/Combine options, it's excluded from the whole process. It means an external file won't be hosted anymore.

And this is the behavior we want to have and to keep.

Why?
If someone has a problem by hosting an external file, the exclusion will allow fixing the problem.
