### ISSUE TITLE
Uncombine jQuery file when Defer JS is deactivated on a specific post

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3169]
**Before submitting an issue please check that you’ve completed the following steps:**
- WP Rocket 3.7.1.1
- Bug hasn’t been reported before

**Describe the bug**

- When you globally **activate** Safe Mode for jQuery, if you deactivate Defer JS option on a specific page, jQuery will be separate from the combined JS file. It’s an expected behavior.
- When you globally **deactivate** Safe Mode for jQuery, if you deactivate Defer JS option on a specific page, jQuery will still be included to the combined JS file. Like Safe Mode hasn't been enabled by deactivate Defer JS.

**Expected behavior**
As the Safe Mode for jQuery option is linked to the Load JavaScript deferred option (you can’t activate Safe Mode for jQuery option independently from Load JavaScript deferred option as you can see here: https://share.getcloudapp.com/ApuLwYwN).
When Defer JS option is deactivated on a specific page, we expect that the jQuery file will be in safe mode and excluded from being combined too.

**To Reproduce**
1.  Activate, Combine JS, Load JavaScript deferred option and uncheck the Safe Mode for jQuery option
2. Go on a page and deactivate the Defer JS option
3. Check in the source code, jQuery file will still be included in the Combined JS file.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1293418415/197801/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@WordPresseur Thanks for the details. 

I am confused a bit. Defer JS only deals with adding the `defer` to the JS files. It has nothing to do with if the file is combined or not, right? 

- If defer JS is globally disabled, then jQuery file will still be combined, right? 
- This is the same behavior if Defer JS is disabled on a post, right?

🤔

**Comment by arunbasillal** [comment]
We had a chat about this.

Romain said: 

> It works as expected when the JS files are not combined
> But when you combine JS + uncheck safe mode + disable Defer JS on a single page: jquery is not separated from the combine JS files and thus, is defered with the whole combined file
and put at the bottom of the document
> that’s the thing I guess
> the combined file is not defered indeed but it is loaded at the bottom of the document

I said: 

> All you have to do is to remove combined JS for the specific page and that should fix the issue

Closing the issue.

**Comment by DahmaniAdame** [comment]
Another possible alternative is excluding /wp-includes/js/jquery/jquery.js from combination.

**Comment by arunbasillal** [comment]
> It will be great if we had a function/filter to exclude specific JS files on a post.

@DahmaniAdame You mean exclude a specific JS file from being processed by WP Rocket? Pretty sure it can be done by using the specific filter. Simply return if it's not the post you wish to exclude on. 

Similar to what we do in this helper: https://github.com/wp-media/wp-rocket-helpers/blob/a6023ce1cbd444cc50887e6bc8eec98bcfef161f/cache/wp-rocket-no-cache-for-page/wp-rocket-no-cache-for-page.php#L26-L35
