### ISSUE TITLE
Plugin compat: Contact Form Generator Business

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#318]
- Plugin page: [Contact Form Generator Business](https://wordpress.org/plugins/contact-form-generator/)
- Compat steps: auto-exclude dynamic files from cache busting.

The plugin generates dynamic CSS/JS files based on form IDs in which form IDs get inserted into classnames, or are used as array index. So every form must have its own set of dynamically generated files. 

Styles and functionality break, because WP Rocket generates a static file from the form ID on one page, but applies it on all other pages with other forms just as well.

URL patterns look like this:

```
# CSS
/wp-admin/admin.php?page=cfg_forms&act=cfg_submit_data&holder=generate_js&id_form=24&ver=4.7.1

# JS
/wp-admin/admin.php?page=cfg_forms&act=cfg_submit_data&holder=generate_css&id_form=24&module_id=0&ver=4.7.1
```

**Comment by arunbasillal** [comment]
I tested this here with version `2.1.82` of the said plugin: http://mega.wp-rocket.me/nieuws/contact-form-generator-creative-form-builder-for-wordpress/

- The CSS file no longer exists
- The JS file created is excluded from our optimizations already. 

Closing this.
