### ISSUE TITLE
Export settings in chrome opens JSON file in new tab, and when saved manually then imported it fails, because of 'invalid filename'

### ISSUE THREAD

**Issue by djbritt** [wp-media/wp-rocket#3187]
When I click export settings in chrome (brave), it opens a new tab full of the JSON settings for the plugin.

So I copy that into a file called settings.json and tried to import it into another site. This fails, as it says invalid filename.

I then went through the plugin and found the regex for parsing the filename, and found out that this filename works.

wp-rocket-settings-2020-10-06-a1a1a1a1a1a1a.json

This is a bug, and should download the file, not open it in a new tab in chrome.

**Comment by arunbasillal** [comment]
Hello @djbritt 

I just tried this and I couldn't replicate this in Brave browser - https://youtu.be/0mFheSdp22Q
Can you see if this is the case with Google Chrome as well? It might be another plugin conflict or a server issue specifically to your setup.

**Comment by arunbasillal** [comment]
Going to close this since this doesn't seem to be an issue and might be a plugin or add-on conflict. Please reach out to support if issue persists.

**Comment by djbritt** [comment]
That's weird, it doesn't do that now. It downloads the file fine now.

Thank you.

**Comment by arunbasillal** [comment]
Happy to know that it is working 👍
