### ISSUE TITLE
Allow wildcard exclusions for CSS/JS minification/combination in the core

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3192]
**Before submitting an issue please check that you’ve completed the following steps:**

- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Currently, excluding external JavaScript files in the core doesn't support wildcards:
https://github.com/wp-media/wp-rocket/blob/443f2e1b902c592bd517cbaa641571bb2ddce1a5/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L184-L266

If we want to exclude this and any newer versions:
```HTML
c0.wp.com/p/jetpack/8.9.1/_inc/build/postmessage.min.js
```
we'll have to exclude all files coming from `c0.wp.com` regardless of whether this is necessary or not.

Apart from not optimizing those files, this can have side-effects since we don't know how all of the dependencies, e.g. inline JavaScript or other files, of the excluded files.

For example, the exclusion of the following file:
```HTML
https://s0.wp.com/wp-content/mu-plugins/notes/admin-bar-v2.js
```
leads to a JavaScript error in the console:
![](https://i.vgy.me/Im3hha.png)

when:
* JetPack is installed.
* User Cache is enabled.

This requires more exclusions to fix the new issue.

**To Reproduce**

1. Install JetPack
2. Try to exclude one of their files in WP Rocket's core using wildcards:
```HTML
c0.wp.com/p/jetpack/8.9.1/_inc/build/postmessage.min.js
```
3. Check the front-end.
4. The file won't be excluded

**Expected behavior**

We should be able to target specific files using wildcards for the dynamic parts.
The same way this is done for excluding files from deferring:
https://github.com/wp-media/wp-rocket/blob/443f2e1b902c592bd517cbaa641571bb2ddce1a5/inc/functions/options.php#L415-L431

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1294828159/198156?folderId=2135277

For popular plugins like JetPack, we should see how the front-end/back-end is affected by our current exclusions.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jazir555** [comment]
Would this also benefit Elementor?

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
