### ISSUE TITLE
Visiting any form of wp-login.php child URLs creates a cached page

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3200]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
A customer reported this to us. 
When you visit this kind of URL: `example.com/wp-login.php/hello-world/` where `hello-word` can be any random string, it doesn't necessarily cause a 404 error. In our tests, the page is delivered 3 of 4 times. 
We don't know if it's coming from WordPress, or if it's related to the specific server configuration. 

Should we prevent this by excluding any form of caching to URLs containing **wp-login.php**? 

**To Reproduce**
1. Go to _example.com/wp-login.php/hello-world/_
2. Switch to _example.com/wp-login.php/hello-world-2/_
3. Visit the cache folder
4. Find these cached pages inside a wp-login.php folder

**Expected behavior**
Visits to any URL that contains **wp-login.php** shouldn't be cached.

**Screenshots**
For WP Rocket, this will result in creating a new cached page for anything that comes after **wp-login.php** like this:  

![main_full](https://user-images.githubusercontent.com/229406/95616593-672b2e80-0a40-11eb-8890-9d2c0c71b8e2.png)
Full image here: https://jmp.sh/FZrnQvB

**Additional context**
Slack discussion:
https://wp-media.slack.com/archives/C43T1AYMQ/p1602254429178900

Ticket from @juricazuanovic :
https://secure.helpscout.net/conversation/1302960011/200442/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
@arunbasillal This is very edge case. This type of URL, although strange, is behaving the same way with or without WP Rocket (no 404, always showing the login page).

No one is really going to access the login page that way, and there is no critical data here.

Trying to craft custom exclusions doesn't make a lot of sense to me, and it could also start being problematic when taking into account plugins that are changing the login URL.

**Comment by arunbasillal** [comment]
@Tabrisrp If it's complicated, then let's not do this until we know this is a serious issue. Thanks for taking a look!

In the original ticket, they ask if it's a security risk. Since we only generate HTML files, there is no risk. Someone might try to fill up their disk, but that will need a lot of time since HTML files are quite small. 

@alfonso100 Please note ^
Going to close the issue as per the above feedback from Remy.
