### ISSUE TITLE
Location Of rocket critical css After Yoast Plugin Code

### ISSUE THREAD

**Issue by sarehnajibi** [wp-media/wp-rocket#3202]
Hi, Why the style section codes are after the title, I think it is much better if it is after the  Yoast plugin codes.
Does anyone have any idea how to do this?
![rocket](https://user-images.githubusercontent.com/72815453/95889348-28bea800-0d8f-11eb-8d42-da9f25fa5f9f.png)

**Comment by arunbasillal** [comment]
@sarehnajibi Hello 👋 
Is this causing any issue for your website? We have a related issue - https://github.com/wp-media/wp-rocket/issues/2636
Please add your thoughts there so that we can have one single conversation.
