### ISSUE TITLE
Create a file like ".webp-active" when WebP is activated

### ISSUE THREAD

**Issue by maximejobin** [wp-media/wp-rocket#3207]
I'm the author and maintainer of [Rocket-Nginx](https://github.com/SatelliteWP/rocket-nginx/), a configuration for Nginx to speedup WP Rocket even more.

If I understand correctly, the cache file created when the WebP setting is active is _only_ created if the browser supports WebP. I'm not sure I understand why don't you create both versions at the same time. 

If there is no reason to do so, I would like WP Rocket to create both versions (WebP and non-WebP) at the same time. That way, that is one less request per page that will generate the cached file. And this will solve my problem!

If there is a reason to do so, Rocket-Nginx needs a way to know if the WebP setting is activated or not. Otherwise, there is no way for the configuration to know what is the current status.

This is the same process as with the `.mobile-active` file that tells if the mobile cache is enabled.

Here is an example of the problem we face right now:

Let's assume the cache is empty. A visitor with a browser that does not support WebP visits the page.

The file `index.html` will be created.

Then, a visitor with a browser that supports WebP visits the same page. The behaviour will (should) be different depending on if the WebP setting is activated or not.

If WebP is activated, the request should not go through WP Rocket (and let WP do its job) as we need to generate the `index-webp.html` file or generate the `.non-webp` file. If WebP is not activated, the request should go through WP Rocket and serve the `index.html` file previously created.

Right now, when the `index-webp.html` file does not exist, Rocket-Nginx fallsback on `index.html`. This is right if WebP is not activated. If it is activated, this isn't right. It seems there is no way to know, from the filesystem, what is the current status.

Note that this is my understanding based on looking at the code and experimenting. Please correct me if I'm wrong.

The problem I see here is a roadblock I have that disables me from finishing version 3.0 of Rocket-Nginx! Please help me figure this out!

**Comment by arunbasillal** [comment]
@maximejobin Nice to meet you 👋 

I can confirm that your understanding of how the feature works is correct.

> If there is no reason to do so, I would like WP Rocket to create both versions (WebP and non-WebP) at the same time. That way, that is one less request per page that will generate the cached file. And this will solve my problem!

If we can do this, this seems the best solution. That way preloading will also generate all versions of the cache. 

I will tag @Tabrisrp to invite his comment. Please allow some extra time for his response, we are going through a busy week of development.

**Comment by maximejobin** [comment]
Thank you for the quick answer @arunbasillal !

Remy and I have worked on the `.mobile-active` in the past so waiting for his input makes a lot of sense!

I can't wait to solve this for the next release of Rocket-Nginx! Don't worry about the timeline, I'll do what it takes when we get to a fix. :-)

**Comment by maximejobin** [comment]
I'm following up on the issue to know what could be a solution so I can wrap up this issue. You do not have to fix everything now. Maybe we can discuss the future outcome. What do you think?

**Comment by Alnaggar94** [comment]
@arunbasillal @Tabrisrp @maximejobin - Any updates?

**Comment by maximejobin** [comment]
There isn't much I can do on my end, unfortunately. I'm waiting to see what can/will be done. I'm pretty sure we'll have news soon.

Happy new year!

**Comment by remyperona** [comment]
Allo Maxime 👋🏼 

> If I understand correctly, the cache file created when the WebP setting is active is only created if the browser supports WebP. I'm not sure I understand why don't you create both versions at the same time.

The way the plugin is built, we always generate only the corresponding cache file for the current visitor (if the cache file doesn't exist yet). That's why there is never multiple versions of the cache created at the same time.

Anyway, we can find a solution similar to the `.mobile-active` for this case.

**Comment by maximejobin** [comment]
Merci Rémy!

The `.webp-active` file would clearly help.

Generating both files' version too (webp and non-webp).

Your call!

**Comment by maximejobin** [comment]
@Tabrisrp What is the next step? 

Do you want to organize a small chat/video conference to exchange on it and find a solution that is simple and fast to implement?

I'm ready when you are!

**Comment by Alnaggar94** [comment]
@Tabrisrp Could you please try to find a solution with Maxime to solve this issue, we can't wait to see the new version of Rocket-Nginx. This is a real game-changer as serving cache from the PHP level is not effective with high demand traffic. I think the WP Rocket team should support this by default or at least help Maxime going along with it, He is doing a great job.

**Comment by remyperona** [comment]
@GeekPress Do you want to plan for this, and when?

**Comment by GeekPress** [comment]
@Alnaggar94 May I know how are you using WebP on your website? I'm asking the question as we are seriously thinking about removing the WebP Cache option.

Why?
WebP is supported by all browsers except for IE 11 which represents only 0.8% of browser usage...

And all image optimization plugins like Imagify, Shortpixel, etc.. provide a solution to use the WebP format on front-end.

Source:
- https://caniuse.com/?search=webp
- https://gs.statcounter.com/

**Comment by maximejobin** [comment]
@GeekPress 

> I'm asking the question as we are seriously thinking about removing the WebP Cache option.

I'm sorry to see I'm about to derail my own issue... but do you mean that you would only generate one html cache file that would display WebP images if they are available or their original format if WebP is not available?

**Comment by GeekPress** [comment]
> I'm sorry to see I'm about to derail my own issue... but do you mean that you would only generate one html cache file that would display WebP images if they are available or their original format if WebP is not available?

We won't do anything. All image optimization plugins have an option to let you decide how the WebP images should be displayed: htaccess rules, picture, etc...

**Comment by maximejobin** [comment]
It was decided that Rocket-Nginx will not support the WebP feature.
