### ISSUE TITLE
Avada Lazyload is detected as always active

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3209]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Avada has added WordPress Lazyload option: https://jmp.sh/3SpVHLf

In our [compatibility file](https://github.com/wp-media/wp-rocket/blob/6c811c18c1739349a51753b07816b7260b1e2c07/inc/3rd-party/themes/avada.php#L22), we are checking Avada’s lazyload setting to be **empty**, and in that case, our Lazyload is available.

But now, the value is never empty, it’d be one of:
- none
- Wordpress
- avada

**To Reproduce**
1. Go to MEGA Avada
2. Deactivate Lazyload in Avada's settings, set it to "None": https://jmp.sh/3SpVHLf
3. Visit WP Rocket settings page
4. WPR Lazyload option is disabled: https://jmp.sh/7tNbWYk

**Expected behavior**
We should detect Avada's Lazyload **none** setting is deactivated, and enable WPR Lazyload option.

**Screenshots**
Avada's new option: https://jmp.sh/3SpVHLf

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1311060316/202908?folderId=3051575

**Comment by DahmaniAdame** [comment]
Related ticket: https://secure.helpscout.net/conversation/1318322328/205171/

**Comment by camilamadronero** [comment]
Related https://secure.helpscout.net/conversation/1317405236/204874?folderId=2675957

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1319951841/205645?folderId=3051575

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1323117426/206691/

**Comment by mifrero** [comment]
This issue is back on Avada V7.2.1 and WP Rocket 3.8.6. 
Ticket: https://secure.helpscout.net/conversation/1450879907/246662/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1646176049/298036/
