### ISSUE TITLE
Adding domains to the blacklist

### ISSUE THREAD

**Issue by serg-pervushin** [wp-media/wp-rocket#3214]
It would be great if it was possible to block domains in the user's personal account. Now, for example, I install wp rocket on the client's site, but then, when we finish working with him and I don't have access to the admin panel of his wordpress site, I would like to disconnect his domain from my WP Rocket account, forbidding to receive updates.

It seems impossible now. A simple deletion of the domain from your personal account, as I understand it, does not give the desired result.

**Comment by arunbasillal** [comment]
Hello @serg-pervushin 

Thanks for the feedback. This is planned for the website redesign and should be available soon. You can refer the feedback here: https://github.com/wp-media/wp-rocket/issues/1206#issuecomment-632056982

Best regards.
