### ISSUE TITLE
Lazyload isn't working when using AJAX pagination

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3215]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When using AJAX pagination or "load more" functionality, the transparent pixels aren't replaced with the actual images.

**To Reproduce**

1. Install the WooCommerce Load More Products plugin (download link and instructions in [the HelpScout ticket](https://secure.helpscout.net/conversation/1301212663/199965?folderId=2135277#thread-3751208364))
2. Enable WP Rocket's lazyload.
3. Use the **Infinity Load**
4. Images won't load.

**Expected behavior**

Images should be lazyloaded when "load more" or infinite scroll is used.

**Additional context**

**Slack Conversation:** https://wp-media.slack.com/archives/G01BNRJ3PRQ/p1602167442002200

I've tried the solution provided by a customer and it worked: https://secure.helpscout.net/conversation/1266959672/190588?folderId=2675957#thread-3644284639

`Assets.php` with the changes: https://gist.github.com/vmanthos/af4115a83b62931c19e74710eee303d8

**Related tickets:**
https://secure.helpscout.net/conversation/1301212663/199965
https://secure.helpscout.net/conversation/1266959672/190588

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the problem
Reproduced on test site

### Identify the root cause
Currently a `return` is used in the loop, which makes it stop early if an element doesn't match, instead of ignoring this element and continuing.

### Scope a solution
Replace the `return` calls by `continue` instead, to make sure we go through all the matched elements

### Estimate the effort
Effort `[XS]`
