### ISSUE TITLE
Script and style manager

### ISSUE THREAD

**Issue by serg-pervushin** [wp-media/wp-rocket#3223]
It would be great to get a script and style manager in WP Rocket, which allows you to choose which scripts and styles (or entire plugins) should be loaded on the page and which should not. For example, contact form7 is only used on the contact page, so you can disable it everywhere except the contact page.

There are plugins of this kind, but it will be good to have it in one tool, in WP Rocket :)

**Comment by arunbasillal** [comment]
Hello @serg-pervushin 

Thanks for the request. 

There is a feature request for the same on the roadmap - https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/14-remove-unused-css-and-js-on-individual-pages

Please add your vote there. You can also suggest new ideas there directly. 

Thanks once again.
