### ISSUE TITLE
JavaScript error when visiting the dashboard in IE11

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3229]
**Describe the bug**
When visiting our dashboard in IE11, we're getting the `forEach` error related to the `wpr-admin.js` file. The case is very similar to this one:
https://github.com/wp-media/wp-rocket/issues/3140

**To Reproduce**
1. Use IE11
2. Visit WP Rocket dashboard
3. Open the JavaScript console
4. See an error

**Expected behavior**
No errors in the JavaScript console in IE11 while working in the WP Rocket dashboard.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@wp-media/productrocket Knowing that support for IE11 will be dropped in either WP 5.8 or 5.9, do we want to go forward here? Or consider this as a `wontfix` and close?

**Comment by GeekPress** [comment]
@Tabrisrp Indeed, we can consider this issue as `wontfix` as we know support for IE will be dropped soon in WordPress
