### ISSUE TITLE
Allow custom Cache implementations

### ISSUE THREAD

**Issue by tillkruss** [wp-media/wp-rocket#3231]
Currently the [`advanced-cache.php`](https://github.com/wp-media/wp-rocket/blob/master/views/cache/advanced-cache.php) doesn't allow for any customization. The only way for [Redis Object Cache](https://github.com/rhubarbgroup/redis-cache) to store cached pages in Redis is to manipulate the `advanced-cache.php` drop-in.

The easiest way to resolve this would be to make the loaded [`Cache`](https://github.com/wp-media/wp-rocket/blob/master/inc/classes/Buffer/class-cache.php) class configurable. I'm happy to submit a pull request.

Alternatively, WP Rocket could ship with an alternative `Cache` implementation that uses the `wp_cache_*()` functions.

Thoughts?

**Comment by arunbasillal** [comment]
Hello @tillkruss 

There is a filter to modify the contents of `advanced-cache.php` - `rocket_advanced_cache_file`

https://github.com/wp-media/wp-rocket/blob/7e8d54aaf5ad8ddffda404d7011931f1a43f3a53/inc/Engine/Cache/AdvancedCache.php#L126-L133

That can be used, right?

**Comment by tillkruss** [comment]
Ah, that's neat @arunbasillal. It still requires running a regular expression to replace the `Cache` class. Would you be open to a PR to make this a bit easier?

**Comment by arunbasillal** [comment]
Let me tag @Tabrisrp here so that there is feedback from the dev team on that.

**Comment by Tabrisrp** [comment]
Hey Till,

I'm thinking swapping the Cache implementation could be a good idea, especially in an OOP context, where concrete implementation should be swappable easily. We can collaborate on that.

**Comment by tillkruss** [comment]
@Tabrisrp: Fantastic, should I open a PR and we can discuss the approach there?

**Comment by Tabrisrp** [comment]
Yes, let's do that

**Comment by tillkruss** [comment]
@Tabrisrp: Thoughts on https://github.com/wp-media/wp-rocket/pull/3447?

It requires a bit more work on my end, but that seems to be the easiest implementation with the least amount of changes.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future while working on the filesystem.
