### ISSUE TITLE
Auto enable "Preload Links" and "Heartbeat Control" for new installs

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#3234]
Please enable these features by default for new WP Rocket installs. These two features are generally safe and have not created issues. 

**Why are we doing this?** 

To make WP Rocket easier to configure for our users. They will have two less decisions to make. 

**Notes**

- We are not removing the UI. We simply want these features to be enabled by default. i.e. add these in [here](https://github.com/wp-media/wp-rocket/blob/e49355167e75f1d3cf51ee65c429b75f3e28682e/tests/Fixtures/inc/admin/rocketFirstInstall.php). 
- The default values for `Heartbeat activity` stays the same as `Reduce Activity`. Simply enable the `Control Heartbeat` option by setting `control_heartbeat` to `1`

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
In `inc/admin/upgrader.php`, `rocket_first_install()`, change the value for `control_heartbeat` from `0` to `1`.

In `inc/Engine/Preload/Links/AdminSubscriber.php`, `add_option()`, change the value from `0` to `1`.

### Estimate the effort ✅ 
Effort `[XS]`
