### ISSUE TITLE
Will there be optimization for elementor?

### ISSUE THREAD

**Issue by EvgenDoman** [wp-media/wp-rocket#3241]
I would like to see optimization for the elementor Builder

**Comment by arunbasillal** [comment]
Hello @EvgenDoman 

WP Rocket is already compatible with Elementor and there are plenty of customers using them together. There are [few reported issues](https://github.com/wp-media/wp-rocket/issues?q=is%3Aissue+is%3Aopen+elementor) that needs some love, but other than that, we are good. 

If you have specific issues related to Elementor, please open a [bug report](https://github.com/wp-media/wp-rocket/issues/new?template=bug_report.md).

Best regards.
