### ISSUE TITLE
After updating, WordPress Automatic updates link is not available on last version

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3243]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
if you have the last version of any plugin (WPR on his case), the link for Enable auto-updates on plugins page will disappear but if there is an update for the plugin, this link will appear.
So we need always to be able to enable/disable it regardless there is an update or not.

**To Reproduce**
1. Install WP Rocket the last version.
2. Open Plugins admin page to see list of available plugins.
3. Check `Automatic Updates` column for WP Rocket row.

**Expected behavior**
We need to be able to see the enable/disable link with last installed version.

**Screenshots**
With last version 3.7.4
![image](https://user-images.githubusercontent.com/15707971/97171962-fb162d80-1796-11eb-977c-98e8f9021d21.png)

With the version before 3.7.3
![image](https://user-images.githubusercontent.com/15707971/97172118-357fca80-1797-11eb-8362-97d76f11285b.png)

**Additional context**
We have two options here:-
1. We can force this auto update to be always disabled by using this filter auto_update_plugin as documented [here](https://wordpress.org/support/article/configuring-automatic-background-updates/#plugin-theme-updates-via-filter).

and this may be [here at this class](https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Plugin/class-updater-subscriber.php#L117)

```
public function force_disable_autoupdate( $update, $item ) {
	if ( 'wp-rocket/wp-rocket.php' === $item->plugin ){
		return false;
	}
	return $update;
}
```
and the output will be like:
![image](https://user-images.githubusercontent.com/15707971/97172881-5bf23580-1798-11eb-938b-70b4e5ee72f8.png)

2. Make this feature enabled/disabled by the user:
we need to adjust two things here:-
**a.** change [this code](https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Plugin/class-updater-subscriber.php#L247-L249) to be:

```
// If a newer version is available, add the update.
if ( version_compare( $this->plugin_version, $remote_data->new_version, '<' ) ) {
	$transient_value->response[ $remote_data->plugin ] = $remote_data;
}else{
	$transient_value->no_update[ $remote_data->plugin ] = $remote_data;
}
```

**b.** adjust [this method code](https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Plugin/class-updater-subscriber.php#L312) to handle the API response when there is no update and return the object again not error (I sent @Tabrisrp to ask him about the following API response if it's expected or not and he told me that it's valid one)
```
{"success":false,"data":{"reason":"NO_UPDATE","consumer_key":"f760c170","consumer_email":"ahmed@wp-media.me"}}
```
with response code 202 but the code handles not 200 response to be error.

@wp-media/productrocket I think you need to take decision on which approach is needed.
@Tabrisrp to be validated from technical side, if u have any moment.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
**Root Cause:**

[This line of code](https://github.com/engahmeds3ed/wordpress-develop/blob/c0570b13980922a4b94841c693af5332ec46cf43/src/wp-admin/includes/class-wp-plugins-list-table.php#L1109) is the one used to show/hide this auto-updates link on wordpress core.
and this key `update-supported` is [set here](https://github.com/engahmeds3ed/wordpress-develop/blob/c0570b13980922a4b94841c693af5332ec46cf43/src/wp-admin/includes/class-wp-plugins-list-table.php#L205-L211) on the same file so u can see that this code checks if there is any response from checking the updates API from the server so if it found plugin update, it will automatically set this attribute `update-supported` to be true and this is the first condition and this is which makes our issue as we are setting the response key [here on WP Rocket](https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Plugin/class-updater-subscriber.php#L247-L249).

**Comment by hellofromtonya** [comment]
First reported in this Support ticket https://secure.helpscout.net/conversation/1317850798/205037.

**Comment by hellofromtonya** [comment]
In WordPress 5.5, free and premium themes and plugins have an `Enable auto-updates` link that allows users/customers to opt into automatic updates. 

@GeekPress @arunbasillal Do we want this feature for WP Rocket customers? In other words, do we want to allow our customers to opt-into automatic updates whenever we release a minor or major version of Rocket?

- If yes, we need to make an adjustment in the code, as Ahmed notes above. It's a very small adjustment `[XS]` that can ship in the next minor release.
- If no, we'll make Rocket default to `false` which turns off this option. `[XS]` can ship in the next minor release.

From a Product point of view, should we allow automatic updates?

**Comment by GeekPress** [comment]
@hellofromtonya I suppose the auto-update is working for minor and major versions. And we can't control to do the auto-update only for minor versions.

If so, as we know major versions can cause issues, (and this is why we have our staggered process) I think we have to disable the auto-update for WP Rocket. 

Below the `Auto-updates disabled`, could we add a link to documentation? To explain to our users why we don't allow auto-updates on WP Rocket.

About the text, what about this?
`Auto-updates aren't available.
More info.
`

**Comment by Tabrisrp** [comment]
I discussed with JB Audras about this, and it is possible to only allow auto-updates for minor versions, if we write our own code to manage that, hooked on the `auto_update_plugin` filter.

Unfortunately it's not built-in like for core, but is it something we want to explore?

**Comment by engahmeds3ed** [comment]
@Tabrisrp Yes I think we can do that using this filter as we have the full item on our hand so instead of checking on the plugin slug only we can add check `new_version` attribute and detect if this is major version or minor one.

https://github.com/engahmeds3ed/wordpress-develop/blob/0c4958bdbcc29beed02a37e5a6d06defd7927643/src/wp-admin/includes/class-wp-automatic-updater.php#L207

**Comment by arunbasillal** [comment]
Let's say we enabled auto updates only for minor versions
- We need to educate the customer that it's only for minor versions and not for major versions
- If not won't they wonder why some updates are not automatically installed? 
- Can we reliably educate our customers the differences between major and minor? I would think a lot of our customers would install an update without thinking twice about it. 

Since any update of WP Rocket has the potential to cause major issues, I think it's best if the update is manual and not automatic. 

> About the text, what about this?
> `Auto-updates aren't available. More info.`

I like this ^

**Comment by Tabrisrp** [comment]
The text displayed is not filtered, so we can't modify the default value.

**Comment by arunbasillal** [comment]
> The text displayed is not filtered, so we can't modify the default value.

If that is the case, let's silently disable the feature for now. Don't think we have much of a choice here. In the future if there is a filter or if we have a need (eg: many users ask why auto updates are not available), then we can work on this. 

What do you say @GeekPress ?
