### ISSUE TITLE
JS Files without a scheme are automatically excluded from combination when the CDN is enabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3253]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When:
1. JavaScript files are loaded without a scheme, e.g.:
`//www.example.com/wp-content/themes/ashe/mobile.js`
_AND_
2. the CDN option is active

the JavaScript files are automatically excluded from JavaScript combination.

After CDN rewriting the URL becomes:
`//cdn.example.com/wp-content/themes/ashe/mobile.js`

When there isn't a scheme the `strpos()` returns `false`:
https://github.com/wp-media/wp-rocket/blob/e49355167e75f1d3cf51ee65c429b75f3e28682e/inc/Engine/CDN/Subscriber.php#L231-L241

The asset's `$url` remains unchanged:
`//cdn.example.com/wp-content/themes/ashe/mobile.js`

and eventually, this fails here:
https://github.com/wp-media/wp-rocket/blob/e49355167e75f1d3cf51ee65c429b75f3e28682e/inc/Engine/Optimization/Minify/JS/Combine.php#L205

**To Reproduce**

1. Enqueue a JavaScript file without using a scheme.
2. Enable JavaScript combination.
3. Enable CDN.
4. The file will not be combined with the rest of the JavaScript files.

**Expected behavior**

Schemeless JavaScript files should be combined when the CDN feature is enabled.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1314693548/204046

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
