### ISSUE TITLE
Requesting AMPforWP Compatibility

### ISSUE THREAD

**Issue by itzmostafiz** [wp-media/wp-rocket#3256]
Hi,
The wp-rocket plugin works for Automattic's AMP plugin very well. But it disables AMPforWP to redirect into the mobile version with AMP. Please make the plugin compatible with AMPforWP https://wordpress.org/plugins/accelerated-mobile-pages/

**Comment by ScottTravisHartley** [comment]
Have you tried enabling the mobile cache by chance to create a separate cache for mobile devices?

**Comment by itzmostafiz** [comment]
Thanks, It's a good solution.

**Comment by GeekPress** [comment]
I'm closing this issue as the problem seems to be solved ;)
