### ISSUE TITLE
Changes to Promo notice

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#3257]
**Notice bubble:** 
Change the color of the bubble when a promotion is active. Now it’s a red bubble with an exclamation point.To make it less alarming I’d like to change the color to green.

**Countdown timer:**
According to the design, It should be made of white squares but right now they all have different width.

![Capture d’écran 2020-11-02 à 12 02 15](https://user-images.githubusercontent.com/48359715/97861924-d2e17e00-1d04-11eb-966a-01a77dc91e99.png)
![Capture d’écran 2020-11-02 à 12 02 49](https://user-images.githubusercontent.com/48359715/97861928-d412ab00-1d04-11eb-83ad-5b950b33ebc9.png)

**Comment by Tabrisrp** [comment]
### Scope a solution
Update CSS for the notice bubble: create a custom class `rocket-promo-bubble` to replace the use of `awaiting-mod`. Use the same rules as `awaiting-mod` but change the background color.

Update CSS for the countdown: update container width, and set the children to use `flex: 1`

### Estimate the effort
Effort `[XS]`
