### ISSUE TITLE
When <title> tag is commented out, combined CSS is added inside the comment.

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3265]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When there is a <title> tag within a comment added before the actual <title> tag like this:
`<!-- <title>My Title</title> --> <title>My Title</title>`

the combined CSS file is added inside the comment like this:
`<!--	<title>My Title</title><link rel="stylesheet" href="https://example.com/wp-content/cache/min/1/d8feea3d697248c9003c73d0e50840fd.css" media="all" data-minify="1" /> --> <title>My Title</title>`

**Expected behavior**
WP Rocket should disregard the comment and add the minified file after the actual <title> tag.

Relater ticket: https://secure.helpscout.net/conversation/1325834148/207806/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@NataliaDrause Thanks for the report. Any idea why `title` tag is commented out like this? Was it a manual action that the user / their developer did? 

This seems to be an edge case to me and may not be worth a fix from our side. Please advise.

**Comment by NataliaDrause** [comment]
Thank you for checking this @arunbasillal ! Indeed this seems like an edge case. I will wait for the reply from the customer and maybe can check this further if the FTP is provided.

**Comment by NataliaDrause** [comment]
It looks like the markup was added by the customer's theme in header.php in this way:
![image](https://user-images.githubusercontent.com/60236665/98112072-d65e3c00-1ea1-11eb-9608-90233189624c.png)
Full-screen image: https://jmp.sh/As4w540

This is a very strange markup and probably shouldn't happen. I suggested the customer to contact the theme regarding this.
Theme Clever Course with 4300+ sales.

I think this wouldn't happen when we had Minify HTML, but now comments are not being removed and this kind of issue may happen.

Maybe we can leave this GH issue as a low priority just to see if anything similar comes up. But if you also think it is a very unusual scenario, maybe closing this is OK.

**Comment by arunbasillal** [comment]
@NataliaDrause Thanks for the feedback. 

That looks like something they did at their end. It's very unusual that the original theme would have something like that. 

**Can you please check with the customer to see if this is part of the original theme?** 

> I think this wouldn't happen when we had Minify HTML, but now comments are not being removed and this kind of issue may happen.

This makes sense. Let's leave the issue open for a while to see what happens 👍

**Comment by NataliaDrause** [comment]
One more related: https://secure.helpscout.net/conversation/1385502095/228198/
The comment is again added to the head.php of the theme. Not sure if it is part of the original theme.

**Comment by iCaspar** [comment]
We intentionally target the `<title>` tag for a number of rocket optimizations/replacements, because it is the one thing in the head that _must_ be present in a valid html page, and the WP themes require that there be one to get approval for listing on the `.org` theme repo. Basically, if the title is missing, it's going to cause all kinds of trouble. I'm not sure I'd call this a bug.

**Comment by NataliaDrause** [comment]
Thanks, @iCaspar !
The title is there, it is there **twice** in fact. One is commented out and another one the actual one. Like this:
```
<!--<title>My commented out title</title>-->
<title>My actual title</title>
```
So the CPCSS is being added inside the comment (i.e. the first closing title tag that is inside the comment)

**Comment by arunbasillal** [comment]
@NataliaDrause Can you please find out if the second case was something custom or part of a factory theme? Just so that we know whether to expect more tickets. 

I am siding with Caspar on this one. It's too much of an edge case to fix on our end. Plus we will be phasing out CPCSS soon.

**Comment by NataliaDrause** [comment]
I cannot download the original theme online. It looks like it is a free theme, but the download links are removed from all the resources. So I don't know if the comment was there originally or not.
Regardless, it is very strange to have the commented out <title> and I don't see why this comment would be a part of a theme.
So it is probably safe to close this issue and we'll suggest customers to remove the commented <title>

**Comment by arunbasillal** [comment]
Yes indeed. Thanks for the confirmation 👍
