### ISSUE TITLE
Remove Cache Lifespan “Minutes” Frequency

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3267]
## What are we proposing to do? 

With this minor enhancement, we will remove the “minutes” option as a frequency from the Cache Lifespan choices

![](https://lh6.googleusercontent.com/jrDIwh2BwIpg0SPS7F7Va7W127EOSczom1Eff-rofsR8g1dqB1MF-ZTngN28IbLJIttuWpp7sFzTgU6ihrZasrq0oLa4ueg3iyZpbpSOaJI5eaw-CS19VJVazuxkLPb7_IfVpu3h)

## Why are we doing this? 

Clearing the cache every few minutes can mean that WP Rocket is constantly generating cache files. This can be bad for performance and can cause high CPU issues. 

<p></p>

**Note**: If customers have these use cases, where they need a really short cache, the better approach would be to [<u>disable page cache generation</u>](https://docs.wp-rocket.me/article/61-disable-page-caching) and rely on a server cache like Varnish.   

WP Rocket will soon be interacting with our upcoming SASS API’s on a page by page basis. Websites using the API every few minutes could overload our API and cost us.   

Furthermore, as per MixPanel data, this option is only used by about 1.34% of our customers. 

![](https://lh4.googleusercontent.com/d1JRaJ1hZj-wXJqyNiKIEgBayNRGn-y0KueQyXOJoYcnVeZn8e8Nqk1EunraOixcKDo-seIYca_bpuGZSdsypg39uGc05og9SSQWnB1fFh6ZrV1DpnxNiYoBPHPyInyeGlYcJZnL)

[<u>https://mixpanel.com/s/1lAQmM</u>](https://mixpanel.com/s/1lAQmM)

<p></p>

If we break down that 1.34% further down, a sizable number of users use values greater than 60 minutes. These use cases can be covered by our “hours” and “days” frequency. 

![](https://lh4.googleusercontent.com/fx6Kt1ysCbvH3zGl_k7xCWNGQNMYAngu0crKSLXtMUDFny8F4pS3_RaAbYZ2fIbCywCAP1ZEBY_75UreUpKDhQ9asujU4vApLhN8ZyBgRHQNf-Lvmg7_nKXuWJGgteEV8cMyXbEm)

[<u>https://mixpanel.com/s/2QNh1J</u>](https://mixpanel.com/s/2QNh1J)

## User expectations and experience. How will we do this feature?

This update will be transparent for over 98.5% of the users. They will not be affected in any way.   

For the remaining users, we will port them to the closest frequency as per the following proposal:   

- Any user set to less than 60 minutes can be set to 1 hour

- Users using values greater than 60 minutes can be ported to the closest hour. Example: Values from 60-119 can be ported to 1 hour, values from 120-179 can be ported to 2 hours, and so on. 

## Technical Specs

Please refer to the user experience. 

## Risks

The primary risk is that the user might not know about this change and they might miss all the announcements we make. This will impact about 1% of our users (users with values less than 60 minutes). We can educate them as much as we can. However, if they insist on having their cache cleared every 10 minutes, we can assist them with [<u>setting up a cron job</u>](https://docs.wp-rocket.me/article/494-how-to-clear-cache-via-cron-job) that clears their cache every 10 minutes. 

## Acceptance Criteria

- The UI element for “minutes” is removed. 

- When a user updates from old version to new with “hours”, or “days” as the option, nothing changes for them. 

- If the user updates with minutes set as the cache lifespan option, they are set to “hours” based on the criteria in the user experience. i.e. <60 minutes is set to 1 hour and >60 minutes is approximated to the lowest hour.

- Cache lifespan can be set to 0 for infinite cache lifespan means that the cache is no longer deleted. 

## Documentation and Translations

- None of our documentation mentions “minutes” as far as I could find. Don’t think we need to update anything. 

- This issue is no longer relevant and can be closed - [<u>https://github.com/wp-media/wp-rocket/issues/2202</u>](https://github.com/wp-media/wp-rocket/issues/2202)

- We might need to inform our users about this change via an email, release post, beacon message, and changelog.

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/6058400

**Comment by Tabrisrp** [comment]
### Code changes
- Move `inc/classes/Cache/class-expired-cache-purge.php` and `inc/classes/subscriber/Cache/class-expired-cache-purge-subscriber.php` to the new architecture. Group them in `inc/Engine/Cache/PurgeExpired/`, rename the files & classes
- Add class alias for the moved classes above, in the `deprecated/3.8.php` file

#### `WP_Rocket\Engine\Cache\PurgeExpired\PurgeExpiredCache`
- Add a method `update_lifespan_value()` to update the lifespan value if it was using the minutes value before
- Add tests

#### `WP_Rocket\Engine\Cache\PurgeExpired\Subscriber`
- Remove `clean_expired_cache_scheduled_event()` method and the associated event
- Add a callback on `wp_rocket_upgrader`, calling `PurgeExpiredCache::update_lifespan_value()`
- Add tests

#### `WP_Rocket\Engine\Admin\Settings\Page`
- Update the `purge_cron_interval` index, to remove the `MINUTE_IN_SECONDS` choice

#### `WP_Rocket\Engine\Admin\Settings\Settings`
- Update `sanitize_callback()`, to remove the `MINUTE_IN_SECONDS` choice in`$allowed_cron_units`
- Remove the conditional checking for a value < 10 minutes

**Comment by Jonras78** [comment]
My sites changes content every 10 minutes, so newest WP-Rocket versions is useless because there is no option to set cache lifespan of these 10 minutes....
