### ISSUE TITLE
WP Rocket can't clear min folder when clearing cache in Windows OS

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3270]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes, there is an issue already created before but for preloading**

**Describe the bug**
On Windows Operating system, When you try to clear the cache the `min` directory not cleaned.

**To Reproduce**
1. Install WPR in windows environment.
2. Clear the cache from WPR admin.
3. Check the min directory inside `wp-content/cache`
4. You will find directory with blog ID and the css/js files aren't removed.

**Expected behavior**
The directory with blog ID should be completely removed and files inside it.

**Additional context**
We solved this issue temporary on one of our customer's site as follows:-

https://github.com/wp-media/wp-rocket/blob/f24cdc04fbe98e405733b72b5a0f88150163ed5b/inc/functions/files.php#L332

replaced with
```
$min_path       = str_replace('/', DIRECTORY_SEPARATOR, $min_cache_path . get_current_blog_id() . '/');
```

AND

https://github.com/wp-media/wp-rocket/blob/f24cdc04fbe98e405733b72b5a0f88150163ed5b/inc/functions/files.php#L339

replaced with

```
$min_path_regex = str_replace( '\\', '\\\\', $min_path );
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by crystinutzaa** [comment]
@wp-media/php in here I think we have a bigger issue and this seems just a patch.
This is a bigger fish to catch and solve, because is connected to this:
https://github.com/wp-media/wp-rocket/issues/2584
The exact issue is related to directory separators under IIS.

This got blocked on 14 May 2020 because we need to figure out how to handle both files and directories for both Linux and IIS.

My opinion is that also this one needs to get blocked and discuss a proper solution on how to handle files and directories properly under Linux and IIS.

**Comment by jazir555** [comment]
> @wp-media/php in here I think we have a bigger issue and this seems just a patch.
> This is a bigger fish to catch and solve, because is connected to this:
> #2584
> The exact issue is related to directory separators under IIS.
> 
> This got blocked on 14 May 2020 because we need to figure out how to handle both files and directories for both Linux and IIS.
> 
> My opinion is that also this one needs to get blocked and discuss a proper solution on how to handle files and directories properly under Linux and IIS.

If there are issues clearing the min folder on both windows and linux, that means the behavior of the cache is faulty on all common operating systems wp-rocket runs on. Shouldn't this be considered a critical bug? Cache clear is an extremely basic functionality of WP-Rocket, if cache clear doesn't work properly, the whole plugin may as well not be functioning.

**Comment by sandyfzu** [comment]
A case that presents this issue: https://secure.helpscout.net/conversation/1518072975/265223/

It was fixed by adding the modification that @engahmeds3ed  suggests.

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1731975365/315065?folderId=2135277

**Comment by artkom** [comment]
> 

It looks like the modification suggested by @engahmeds3ed not working anymore. The min folder still uncleader.

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/2049033139/377332

**Comment by matthias-jauernig** [comment]
We ran in this issue last week, using WP-Rocket 3.11.5 on Wordpress 6.0.3. Today, I was able to track it down to `wp-rocket/inc/functions/files.php` and could solve it (assumed to work for Linux and Windows) with the following adaption in `function rocket_clean_minify` (starting at [line 331](https://github.com/wp-media/wp-rocket/blob/f24cdc04fbe98e405733b72b5a0f88150163ed5b/inc/functions/files.php#L331)):

````
        $min_cache_path = str_replace("\\", "/", rocket_get_constant( 'WP_ROCKET_MINIFY_CACHE_PATH' ));
	$min_path       = $min_cache_path . get_current_blog_id();
	$iterator       = _rocket_get_cache_path_iterator( $min_path );

	if ( false === $iterator ) {
		return;
	}

	$filesystem     = rocket_direct_filesystem();
	$min_path_regex = str_replace( '/', '\/', $min_path ) . "[\/\\\\]";
````

**Comment by johndillonuk** [comment]
This still happens for me in windows why is such an obvious and critical bug still not fixed? This effectively stops the plugin working for anyone who cant access FTP

**Comment by jazir555** [comment]
You download a file manager plugin if you don't have ftp access

**Comment by jazir555** [comment]
You can download*

**Comment by johndillonuk** [comment]
Thanks no I have FTP, my point is I shouldnt have to do this for a plugin I pay for when a bug was logged 3 years ago.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on Windows OS issues.
