### ISSUE TITLE
Critical CSS generation encountered one or more errors,  AMP site.

### ISSUE THREAD

**Issue by itzmostafiz** [wp-media/wp-rocket#3273]
After adding AMP, the Critical CSS generation encountered one or more errors arrived. please check the screenshot. http://prntscr.com/vefeim

**Comment by arunbasillal** [comment]
Hello @itzmostafiz 

Please open a support ticket for issues related to one specific website - https://wp-rocket.me/support
Our support team will be happy to take a look 👍
