### ISSUE TITLE
User Cache - Native WordPress logout results in a sanity check

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3274]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When using:

1. User Cache _AND_
2. Native WordPress functionality to logout users,

the user logout works fine the first time. 

However, the next time the user logs in, they get a new session hash, which results in a different nonce.:
https://github.com/WordPress/WordPress/blob/42b6ece05920be90fc3bb155827f95e85fd6bb46/wp-includes/pluggable.php#L2208

When they try to logout, they are getting the sanity check: `Do you really want to log out?`
https://github.com/WordPress/WordPress/blob/42b6ece05920be90fc3bb155827f95e85fd6bb46/wp-includes/functions.php#L3281

This finally allows the user to logout, but it's not the way the logout process normally works, i.e. without a message being displayed.

**To Reproduce**
1. Enable **User Cache.**
2. Browse the site to create the cache.
3. Sign out: this should work fine.
4. Sign in again.
5. Sign out: the sanity check should appear.

**Expected behavior**

The sanity check shouldn't be triggered.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1330015594/209414?folderId=2135277

A workaround, far from ideal, is to clear the user's cache when the user logouts.

The following snippet can do that:
```PHP
add_action( 'wp_logout', function( $user_id) {
	if ( function_exists( 'rocket_clean_user' ) ) {
		rocket_clean_user( $user_id );
	}
});
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1826988775/333761

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
