### ISSUE TITLE
Add LazyLoad support for video poster attribute

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3285]
**Is your feature request related to a problem? Please describe.**
Currently, if the following markup is used, the poster image is not lazy-loaded:

```
<video controls poster="lazy-wannabe.jpg">
  <source src="movie.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>
```

**Describe the solution you'd like**
Lazy-load the poster image.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1332287072/210078?folderId=3864740

**Comment by arunbasillal** [comment]
Since we already have a similar feature request here - https://github.com/wp-media/wp-rocket/issues/2952, I am going to close this as duplicate. I have added the suggestion into the old one. Thank you!
