### ISSUE TITLE
CPCSS script is loaded on the post edit screen for non-administrator causing a JS error

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3292]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When you open the admin panel for a user which isn't an administrator our scripts are loaded and this makes a problem.

So for example this script

https://github.com/wp-media/wp-rocket/blob/cc3edc25191b69fa7d90ce6744c010d83415f4f8/assets/js/wpr-cpcss.js

when loaded for non-admins at edit post webpage it will give JS blocking error on `line 10` as this ID `rocket-delete-post-cpss` is not on the page (because our WP Rocket meta box is not here for this role)

**To Reproduce**
1. Open admin panel with a user has editor role.
2. Open any page/post for edit
3. Check the console so you can see an error

**Expected behavior**
All WP Rocket scripts should be loaded only for admins

**Screenshots**
![image](https://user-images.githubusercontent.com/15707971/98743409-aab6e680-23b8-11eb-8592-fb7d958ea21b.png)

**Additional context**
1. for now I told the customer to add the following code into his theme functions.php and this will do the trick till solving this bug (https://gist.github.com/engahmeds3ed/db6a4ea1556e262a3172dec92c4449ee)

2. We need to add the following check before adding any script to the admin page
```
if ( current_user_can( 'rocket_manage_options' ) ) { }
```

Like in the following function:
https://github.com/wp-media/wp-rocket/blob/1232eb75bf1e16a2290254af407259cdc93dee6d/inc/Engine/CriticalPath/Admin/Post.php#L99

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on test site

### Identify the root cause ✅ 
We don't check for the current user capabilities when enqueue this script on the edit screen.

### Scope a solution ✅ 
As described in the OP, we need to add a check for `current_user_can( 'rocket_manage_options' )` in `CriticalPath/Admin/Post::enqueue_admin_edit_script()`.

We also need to update the fixtures and tests for this to add this test case for the method.

### Estimate the effort ✅
Effort `[XS]`

**Comment by remyperona** [comment]
Related #3395

**Comment by alfonso100** [comment]
Another case here: https://secure.helpscout.net/conversation/1591367126/285274?folderId=2683093
In this case, the error appears on **WP Bakery/ Visual Composer**: https://jmp.sh/kii4Bpq

**Comment by JiveDig** [comment]
We're hitting this error as well. One user is Administrator and the other is Editor. Both hit the same error when trying to save some posts and cpts.
