### ISSUE TITLE
Divi child theme issue with divi video module + overlay image when wp-rocket "Replace youtube iframe" option is enabled

### ISSUE THREAD

**Issue by mitsios** [wp-media/wp-rocket#3293]
Divi video is not working when we are using a child theme as parent theme the "Divi" and we have the wp-rocket -> media -> "Replace Youtube iframe with preview image" enabled and the divi video module settings has enabled the overlay image

**Steps to reproduce the issue:**
1. Create a child theme as parent the Divi theme

i.e.
```
/*
 Theme Name: Test child theme
 Description: This is a test child theme for Divi
 Template: Divi
 Text Domain: test-divi-theme
*/
```
2. Switch to this new child theme
3. Go to admin dashboard -> wp-rocket -> Media, enable the "Enable for iframes and videos" and also the checbox below "Replace Youtube iframe with preview image"
4. Create a new page, add a video module, add an overlay image for this video module
5. Preview this new page

**Expected behavior**
The video to work correctly 

**Actual behavior**
The video is not working, when we click the play button it just takes us to the top of the page and we get a js error in the console log.
Below is the js error:
```
 Uncaught TypeError: Cannot read property 'play' of undefined
    at window.et_pb_play_overlayed_video (57142510dd94504b2fb78c81aaedafca.js:216)
    at HTMLDivElement.<anonymous> (57142510dd94504b2fb78c81aaedafca.js:216)
    at HTMLDivElement.dispatch (jquery.js?ver=1.12.4-wp:3)
    at HTMLDivElement.r.handle (jquery.js?ver=1.12.4-wp:3)
```

**Additional comments**
I noticed that you fixed this issue on this PR #2875 but actually for us is not fixed because the actual template name(folder name) is "Divi" and not 'divi' as is the actual fix in your code.

File of the fix, Divi.php:121
`return ( 'Divi' === $theme->get( 'Name' ) || 'divi' === $theme->get_template() );`
This can be fixed with two ways, either by changing the 'divi' to 'Divi' or converting the $theme->get_template() to lower case
but i am not sure there is a reason to convert the template_name to lower case since the actual folder name of the template is "Divi" so i believe the best would be to just change the 

`'divi' === $theme->get_template()`

to 

`'Divi' === $theme->get_template() `

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The issue was fixed when moving to the new architecture:
https://github.com/wp-media/wp-rocket/blob/57ef824d3e2ea60c1c05c1a09881592e27877bc0/inc/ThirdParty/Themes/ThirdpartyTheme.php#L30

Feel free to reopen if you're still experiencing this.
