### ISSUE TITLE
SeedProd Coming Soon plugin - clear our cache when the coming soon page or the maintenance page are enabled

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3299]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [x]
- Used the search feature to ensure that the bug hasn’t been reported before [x]

**Describe the bug**
When our cache is generated, enabling the coming soon page requires us to manually clear the cache.
They seem to have a DONOCACHE directive, but it only applies if there is no cache generated the first place from my testing.
<img src="https://i.vgy.me/6Pfgg7.png" width="300px">
[https://i.vgy.me/6Pfgg7.png](https://i.vgy.me/6Pfgg7.png)
Any cached page won't show the coming soon or the maintenance page.

**To Reproduce**
1. Enable SeedProd Coming Soon plugin.
2. Generate our cache.
3. Turn on coming soon page or maintenance page.
4. Already cached pages won't show the coming soon page or maintenance page.

**Expected behavior**
Our cache needs to be cleared whenever the coming soon page or the maintenance page are enabled. 

**Screenshots**
N/A

**Additional context**
It's best if the plugin developer detects WP Rocket, and triggers rocket_clean_domain() whenever the coming soon page or the maintenance pages are activated. 
https://docs.wp-rocket.me/article/92-rocketcleandomain

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Slack discussion - https://wp-media.slack.com/archives/G01BGNQU7AP/p1605249301000300

**Comment by arunbasillal** [comment]
@webtrainingwheels I think this is a good candidate where the update can be made at their end. Would you please initiate contact and see if they are interested in a collab? Thanks!

**Comment by webtrainingwheels** [comment]
@arunbasillal I'm not handling 3rd party stuff anymore, @Tabrisrp is

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
