### ISSUE TITLE
Add Missing Width And Height Attributes On Images

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3301]
## What are we proposing to do? 

With this enhancement, WP Rocket will add any missing “width” and “height” values to images used on a website. 

## Why are we doing this? 

When a browser is parsing a page it loads the HTML first and waits for the images to be downloaded. If width and height values are available, browsers can use that information to reserve the space needed for the images on the page. 

<p></p>

When space for an image is not reserved, the browser will move content around to accommodate the image once the image is downloaded. This layout shift leads to a poor reading experience for the user. Having this feature will help improve the user experience for our users. 

<p></p>

In the new version of PageSpeed, this layout shift is counted towards the [<u>Cumulative Layout Shift</u>](https://web.dev/cls/) metric. This feature will also help with improving the CLS score. 

## Benchmark Tests

Test page: [<u>http://mega.wp-rocket.me/cls-test</u>](http://mega.wp-rocket.me/cls-test)

<p></p>

Test method: Twelve images were added first without the “width” and “height” attribute. CLS was recorded using PageSpeed thrice. Then the “width” and the “height” attribute were added and rested with PageSpeed. Three tests were recorded in each case and the average was calculated. 

<p></p>

**Results**

- Without “width” and “height” attributes. Average CLS on desktop = 1.875

- With “width” and “height” attributes. Average CLS on desktop = 1.015

![](https://lh6.googleusercontent.com/R336vfJkuwbE5WcqnnCF4jep45ZaSIjkcWjEGhMPbHjoUpZXmXc7YBa3GOyUzgjEsAHLkEB5LM1yEulHWewM8RYtTJb7c5kLrXj71Pr7lMAxAEP729eE9t_b2gKI6ep503AL-_cq)

Before ^

<p></p>

![](https://lh6.googleusercontent.com/5hcKD1s_pv6oxqSSeStE19k2CttfGNL0hfMLdpeOs5K6xSVr3y5M53x4Lyswd60fmfKWUDTq4_VAUrBYGjje2onEypGnowgjB70-nq3oRBzs0D-EdnAAAnpu0mhMFPpCVbqG0TC2)

After ^

## User expectations and experience. How will we do this feature?

We will add a UI for this feature. UI Location: Media tab. After “LazyLoad”. The option will be disabled by default for existing users and new users alike. 

<p></p>

Heading: **Image dimensions**

<p></p>

Description: **Add missing width and height attributes to images. Helps prevent layout shifts and improve the reading experience for your visitors. More info**

<p></p>

Option name: **Add missing image dimensions**

<p></p>

![](https://lh3.googleusercontent.com/IsnpWR6vWxvQgW4FSeX8h6pVZi83De1118xYm6aK8TQLz3eVVgRtA45IZZmLWxOfIkHsui2rygo2xr6NMSe7rSsZdYdzqZSAzqTdigfT7Dbtv7w5dgDhKEcRnXwdPkkKmCs1dcm7)

<p></p>

**Recommendations for a future iteration**

- We can enable this option by default for new users if we notice that the option is generally safe to use. 

- Option can be added to the WP Rocket metabox on every post if users need it to disable on a per post basis. 

## Technical Specs

<p></p>

This feature is already part of WP Rocket since version 1.1 as a “secret option”. Details can be found here: [<u>https://github.com/wp-media/wp-rocket/blob/master/inc/front/images.php</u>](https://github.com/wp-media/wp-rocket/blob/master/inc/front/images.php)

<p></p>

This was changed in WP Rocket 2.2.2 with the following note in the changelog: 

<p></p>

*Fix: Width and Height attributes will no longer be added automatically to prevent conflicts. Simply add this filter: add_filter( 'rocket_specify_image_dimensions', '__return_true' );.*

## Risks

Since there are countless themes and plugins that insert images, we are most likely going to be incompatible with some of them and cause layout issues. Since it’s a visual change, this would be easy to identify. 

<p></p>

This is the main reason why we have the UI for the option so that it can be easily disabled.

## Acceptance Criteria

- UI is as per specification

- When the option is enabled, any images with missing “width” and “height” attributes have the appropriate width and height added. 

- The filter 'rocket_specify_image_dimensions' still works and enables the feature even if the UI is disabled. (To use the filter add add_filter( 'rocket_specify_image_dimensions', '__return_true' ); to functions.php)

<p></p>

## Documentation and Translations

- A new documentation is to be created to explain the feature for our users.

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/6143376

**Comment by crystinutzaa** [comment]
## Backend

**Update class WP_Rocket\Engine\Admin\Settings\Page**

- https://github.com/wp-media/wp-rocket/blob/3b8b2d7debc83641045f9af82baa08b14e41daed/inc/Engine/Admin/Settings/Page.php#L940-L941
- Update method media_section(), to register the new field `image_dimensions`
- Field disabled by default for all users
- Add Beacon data

**UI text:**
Heading: **Image dimensions**

Description: **Add missing width and height attributes to images. Helps prevent layout shifts and improve the reading experience for your visitors. `More info` <---  link with Beacon**

Option name: **Add missing image dimensions**



## Frontend

- Move `https://github.com/wp-media/wp-rocket/blob/master/inc/front/images.php` into new structure `/inc/Engine/Media/Images/ImagesSubscriber.php` 
- Modify the ServiceProvider.php to provide the ImagesSubscriber
- Deprecate `rocket_specify_image_dimensions()`
- Revisit the compatibility with  LayerSlider - https://github.com/wp-media/wp-rocket/blob/3b8b2d7debc83641045f9af82baa08b14e41daed/inc/3rd-party/plugins/slider/layerslider.php#L10-L13
- When the option is enabled, any images with missing “width” and “height” attributes have the appropriate width and height added. 
- The filter 'rocket_specify_image_dimensions' still works and enables the feature even if the UI is disabled. (To use the filter add add_filter( 'rocket_specify_image_dimensions', '__return_true' ); to functions.php)
- Write Unit & Integration tests

**Comment by webtrainingwheels** [comment]
@wp-media/productrocket 
This will be an awesome feature, thank you!
Since we know that some types of images will conflict, and that this is an important feature for CLS, is it planned to have a way to exclude this from being applied on specific images? I think we can predict this will be a request from customers.

**Comment by crystinutzaa** [comment]
@webtrainingwheels what images will conflict? Can you please provide us an example? It would be really helpfull if you can share with the dev team before starting coding it. 😃

**Comment by webtrainingwheels** [comment]
@crystinutzaa I can't give you specifics, it's based off: 
- Risk assessment above: _Since there are countless themes and plugins that insert images, we are most likely going to be incompatible with some of them and cause layout issues._
- The fact that this feature was previously disabled due to conflicts (I think this was before my time so I don't know what the specific conflicts were. maybe @GeekPress remembers?)

**Comment by GeekPress** [comment]
@webtrainingwheels We had issues with CSS rules when the theme used redimension for responsive. It was 7 years ago, I don't remember what was the rule :D

**Comment by arunbasillal** [comment]
@webtrainingwheels 

> Since we know that some types of images will conflict, and that this is an important feature for CLS, is it planned to have a way to exclude this from being applied on specific images? 

I thought about this and the solution would be to manually add the "width" and "height" parameters to the images so that WP Rocket does not add them. So basically if what WP Rocket added was incorrect, please add the right parameters manually. Won't that cover these cases?

**Comment by webtrainingwheels** [comment]
@arunbasillal 

> please add the right parameters manually

Wouldn't this require the customer to have access to the markup? 
They may not have that if the image has been added by a theme/plugin and not through the WordPress editor.

**Comment by arunbasillal** [comment]
> Wouldn't this require the customer to have access to the markup?

Yes indeed.

- Unless there is a UI for exclusions, they will still have to edit and install a helper plugin with the exclusions. So still some code editing is required. 
- Wouldn't it be better if they put that effort to fix the root cause?

**Comment by webtrainingwheels** [comment]
> Wouldn't it be better if they put that effort to fix the root cause
Yes it would. So why are we doing this feature at all if we believe they should fix the root cause of missing image dimensions manually?

> So still some code editing is required.
Even if they (or support) have to edit a helper, that is code they have access to and can edit safely.
But they cannot edit the code of another plugin safely, obviously.

If the Product view is that this is an all or nothing feature, fair enough.

It would be great to QA this on a variety of images/markup though, generated with plugins etc to we can see how this will work in the wild.

**Comment by arunbasillal** [comment]
@webtrainingwheels 

>Even if they (or support) have to edit a helper, that is code they have access to and can edit safely.
>But they cannot edit the code of another plugin safely, obviously.

True. 

> If the Product view is that this is an all or nothing feature, fair enough.

Since the impact of this feature is minimal, lets start small and see how it turns out and then iterate? 
Maybe even adding this to the `metabox` in the post editor might be enough for exclusion so that users can disable it on a post by post basis.

**Comment by hunter249** [comment]
Why external images are excluded automatically in this feature ?
Please Make it available for external images as well

**Comment by GeekPress** [comment]
@hunter249 External images aren't excluded from this feature. If it doesn't work, it means you don't have the right server configuration:
https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L248

Please contact on our support if you need help: https://wp-rocket.me/support/
