### ISSUE TITLE
Allow custom post types to be excluded from purge

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#3304]
Hello. Is there any way to add a helper in purge.php so we can disable custom post types from auto purge?

https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/common/purge.php#L211

**Comment by arunbasillal** [comment]
This might not be the most elegant solution, but I have an idea

- Check the post type using the `rocket_post_purge_urls` filter here: https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/common/purge.php#L253
- If the post type is the one you wish to exclude, then replace `$purge_urls` with an empty array. 

Won't that work? 🤔 Please give it a try.

**Comment by seldimi** [comment]
Good idea, but I have a suspicion that will block purge from rocket_clean_files, but rocket_clean_domain will still fire.

**Comment by arunbasillal** [comment]
You mean, the `rocket_clean_home` following it? Yes, that will still be fired with this approach. `rocket_clean_domain` is not used anywhere.

**Comment by seldimi** [comment]
I think that when someone puts an order on WooCommerce, rocket_clean_domain is called and the whole cache folder is emptied..

**Comment by arunbasillal** [comment]
@seldimi Iirc, this was the case before WP Rocket 3.5. With #2139 this was changed. 

Side note, we have a helper plugin to disable out automatic cache clearing. You can refer to it's code to see what works for you - https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-no-cache-auto-purge

**Comment by GeekPress** [comment]
I'm closing this ticket as @arunbasillal provided a way to do the trick by using another filter:
https://github.com/wp-media/wp-rocket/issues/3304#issuecomment-731986549

@seldimi Even if we had a filter, the `rocket_clean_home` function will be triggered.
