### ISSUE TITLE
Extend the font family for textarea to improve its appearance on Windows

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#3305]
From a customer:

Can you extend the monospaced textarea font-family like this:

```
.wpr-textarea textarea {
font-family: Monaco, Menlo, Consolas, "Courier New", monospace;
}
```

Because Windows 10 won't recognize Monaco und it looks kinda ugly.

Related ticket: https://secure.helpscout.net/conversation/1324529327/207305/

**Comment by arunbasillal** [comment]
@girlie I am on Windows 10 and the `textarea` looks normal to me. This might be something specific to the customer alone, if not, I think we would have seen more of these before? 🤔 

Here is what I see: 

![image](https://user-images.githubusercontent.com/5751474/99937885-b62ce900-2d8c-11eb-9f82-37276b2eda37.png)

Can you ask the customer to send a screenshot please?

**Comment by GeekPress** [comment]
I'm closing this one as everything seems good for the rest of them which are on Windows. We also never got other complaints about that problem. 

Feel free to re-open it if another case will be reported.
