### ISSUE TITLE
Database optimization queries are run even options are disabled on admin page.

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3310]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When you open the WP Rocket admin page the queries related to database is called even if database options are not checked and this affects the admin load time.

**To Reproduce**
1. Go to WP Rocket admin
2. Go to database page
3. Disable `Optimize Tables` option.
4. Save and open the page again.
5. Check Query Monitor queries and you will find the following query screenshot.
![image](https://user-images.githubusercontent.com/15707971/99406983-3ff53600-28f7-11eb-93b9-8ed8098cc494.png)

**Expected behavior**
Only query the selected options not all.

**Screenshots**
Previously added.

**Additional context**
Here we are looping on all options
https://github.com/wp-media/wp-rocket/blob/7ee30284a5b266712366186b43bea6b0fdd27649/inc/Engine/Admin/Settings/Page.php#L1341-L1343

and options are set here:
https://github.com/wp-media/wp-rocket/blob/58b612d1a808917f2abc6e393f061026bdfb3ad7/inc/classes/admin/Database/class-optimization.php#L40-L49

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
These queries are there to display the number of items for each database cleanup type, to let the user know if there is anything to clean or not.

They are not queries to do the optimization itself.

Though ideally, we would use an AJAX request to populate the items count instead of doing it during page load, to improve the speed.

**Comment by arunbasillal** [comment]
@engahmeds3ed @Tabrisrp Shall we close one of these issues since it's more or less a `duplicate`? Not sure which one, I am thinking let's close this one since we already had a previous one.
