### ISSUE TITLE
PHP Warning copy() failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mzimma** [wp-media/wp-rocket#3314]
**Describe the bug**
Following PHP Warning has been reoccurred on our production sites.

PHP Warning ( Generic )
`copy( /cache/wp-rocket/{website_url}/*.html_gzip_temp): failed to open stream: No such file or directory in wp-admin/includes/class-wp-filesystem-direct.php on line 309`

PHP Warning ( Specific )
`copy(/var/www/wordpress/achilles/wp-content/cache/wp-rocket/www.scarboroughtoyota.ca/vehicles/2021/-/-/-/-/49884372/null/index-https.html_gzip_temp): failed to open stream: No such file or directory in /var/www/wordpress/achilles/wp-admin/includes/class-wp-filesystem-direct.php on line 309`

^ This file does not exist on our server filesystem. 
`# ls /var/www/wordpress/achilles/wp-content/cache/wp-rocket/www.scarboroughtoyota.ca/vehicles/2021/-/-/-/-/49884372/null/index-https.html_gzip_temp
ls: cannot access /var/www/wordpress/achilles/wp-content/cache/wp-rocket/www.scarboroughtoyota.ca/vehicles/2021/-/-/-/-/49884372/null/index-https.html_gzip_temp: No such file or directory`

The copy php warning only seem to appear once for a specific filepath and then disappears.  We have seen a lot of them on our production sites. It does appear to happen frequently without any sort of action ( plugin re-activation or cache purge ).

Is this related to a zipping error of WP-Rocket or rather a temp file not being written into the filesystem? I would appreciate any input on this. 

Unfortunately, can not reproduce the error on purpose.

**Comment by arunbasillal** [comment]
Copy of #2441
