### ISSUE TITLE
3.7 - High CPU usage when CSS combination is used

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3323]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

In `3.7` when CSS combination is used and there is a lot of CSS content, the CPU usage can substantially increase.
This is because contrary to what we did in `3.6.4`, where optimization was applied separately to every CSS file, in `3.7` it's applied to the combined content.

On a customer's site, where the combined CSS content was ~2.2MB, the following part takes 20-25s to complete on WP StageCoach, where no traffic exists:
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/Dependencies/Minify/CSS.php#L311

This can cause timeouts and bring down a busy site.

**To Reproduce**

1. Use the latest WP Rocket.
2. Enable CSS combination.
3. Enqueue a few large CSS files
4. Measure the time it takes for this part to complete:
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/Dependencies/Minify/CSS.php#L311

**Expected behavior**

The CPU usage should be affected as little as possible by our file optimization features.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1327441678/208364?folderId=2135277
**Slack conversation:** https://wp-media.slack.com/archives/C43T1AYMQ/p1605710940034300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1341165856/213133?folderId=2135277

This site is hosted on Kinsta.

You can see in the following New Relic screenshot how long the `Minify::replace` takes.

![](https://i.vgy.me/RDePmQ.png)

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1284807311/195539/

**Comment by webtrainingwheels** [comment]
FYI, I believe there are quite a few un-diagnosed cases of this issue. 
As [noted here, we did observe an increase](https://wp-media.slack.com/archives/C43T1AYMQ/p1600375991214200) of `high cpu usage` and related errors since 3.7.  But most probably weren't investigated to the extent that our dear Vasilis did here, being attributed instead to other usual CPU factors.

**Comment by Tabrisrp** [comment]
### Scope a solution
in `CSS\Combine::get_content()`, modify the methods as:
```
private function get_content( $combined_file ) {
		$minifier = new MinifyCSS();

		foreach ( $this->styles as $key => $style ) {
			if ( 'internal' === $style['type'] ) {
				$filepath     = $this->get_file_path( $style['url'] );
				$file_content = $this->get_file_content( $filepath );
				$file_content = $this->rewrite_paths( $filepath, $combined_file, $file_content );
			} elseif ( 'external' === $style['type'] ) {
				$file_content = $this->local_cache->get_content( $style['url'] );
				$file_content = $this->rewrite_paths( $style['url'], $combined_file, $file_content );
			}

			if ( empty( $file_content ) ) {
				unset( $this->styles[ $key ] );

				continue;
			}

			$minifier->add( $file_content );
		}

		$content = $minifier->minify();

		if ( empty( $content ) ) {
			Logger::debug( 'No CSS content.', [ 'css combine process' ] );
		}

		return $content;
	}
```

Also remove the `Combine::minify()` method.

### Estimate the effort
Effort `[XS]`, no changes needed for the automated tests
