### ISSUE TITLE
Cache is emptied when changing currency using WooCommerce Multilingual currency switcher

### ISSUE THREAD

**Issue by jorgemartine00** [wp-media/wp-rocket#3326]
**Describe the bug**

**To Reproduce**
1. Install WooCommerce Multilingual currency switcher
2. Change currency when on live site
3. Navigate to cache folder from WP Rocket via FTP
4. See cache completely purged

**Expected behavior**
This was created as the expected behaviour for compatibility but needs to be investigated if feature can change from purging full cache to partial purge.

**Additional context**
Currently "clean_post_cache" function is tied to "wcml_switch_currency" hook thus it's clearing cache completely when any user changes currency at the moment they visit the site. Causing server load to be increased and cache not to be available most of the time the site is visited. This was done for compatibility with the currency switcher but needs to be revisited.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by jorgemartine00** [comment]
This is a related case. Automatic clear cache is disabled though https://secure.helpscout.net/conversation/1312375948/203334/

**Comment by vmanthos** [comment]
@jorgemartine00 
> Currently "clean_post_cache" function is tied to "wcml_switch_currency"

I think you mean `rocket_clean_domain()`:
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/3rd-party/plugins/ecommerce/woocommerce-multilingual.php#L7

**Comment by arunbasillal** [comment]
@Tabrisrp This seems to be by design. Do you remember why this was the case? Maybe we had no other (reasonable) way to do it otherwise?

**Comment by Tabrisrp** [comment]
We have no way to do otherwise, WPML relies on WC session to store the currency, which is not accessible to us once the page is cached.

From conversation with Piotr, they don't seem eager to use cookies instead, so we're stuck with that.

**Comment by piotrbak** [comment]
@Tabrisrp I've just received an email from WPML, they're going to give us a filter, so we can enable the cookie way. Will create a GitHub issue shortly.

**Comment by Tabrisrp** [comment]
@arunbasillal Considering issue #3418, and the fact that the current behaviour is not what we want, I would suggest to remove the code we currently have as a first step, and work on the other issue when the new way is available on WPML side. What do you think?

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
- Remove the compatibility file `inc/3rd-party/plugins/ecommerce/woocommerce-multilingual.php`
- Remove the require for the above file in `inc/3rd-party/3rd-party.php`

### Estimate the effort ✅
effort `[XS]`

**Comment by arunbasillal** [comment]
@Tabrisrp I think we should do this and #3418 in one update. Otherwise, we might see issues where end users switch currency and still see wrong currency. An empty cache is a lesser issue as compared to wrong output.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1532530351/268942/
