### ISSUE TITLE
WP Rocket's cache is not cleared when Elementor CSS is set to External file, and WP Rocket's Combine CSS Files is disabled

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3327]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
When WP Rocket **Combine CSS** is disabled, and Elementor CSS print method is set to **External File**, our cache won't be cleared after an edition is made in Elementor,  leading to a 404

**To Reproduce**
1. Go to Elementor and set CSS Print Method to **External File** https://jmp.sh/KCTeLFq
2. Deactivate **Combine CSS Files** in WP Rocket: https://jmp.sh/w3BMUug
3. Update a post in Elementor so the CSS gets updated too.
4. The cache won't be cleared and WP Rocket cache files will refer to the old version of the Elementor CSS file.

**Expected behavior**
We should clear WP Rocket's cache also when **Combine CSS** is disabled.

**Additional context**
It is kinda related to this old issue: https://github.com/wp-media/wp-rocket/issues/1516

We are only clearing WP Rocket cache when Combine CSS is enabled, per our compatibility file: 
https://github.com/wp-media/wp-rocket/blob/master/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L84-L86

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by davideprevosto** [comment]
@alfonso100 I have the same issue here. Have you found any workaround to quickly fix the issue?

**Comment by NataliaDrause** [comment]
Potentially related: https://secure.helpscout.net/conversation/1365333478/222688

**Comment by d19dotca** [comment]
I am experiencing this issue as well with Elementor + WP Rocket with Combine CSS disabled (also minify disabled too and no Optimize CSS Delivery), whenever I edit anything that modifies the CSS. I always have to purge the cache every-time I make such a change, which is quite annoying during development of the site. 

I run on an HTTP/2 enabled server, and would prefer not to enable the Combine CSS as it tends to compete with the HTTP/2 advantages.

This experience [goes against the documentation](https://docs.wp-rocket.me/article/1135-when-does-wp-rocket-delete-which-files) (thus a bug): "When Elementor's CSS Print Method is set to External File, and the Elementor CSS of a post is updated."

Interestingly though, I temporarily enabled the Minify & Combine CSS, assuming that'd be a workaround so I don't have to manually clear the cache every time I make an edit to the CSS, but this does not seem to work as I'd expect either in my brief testing. Still continuing to test this workaround though.

**Comment by NataliaDrause** [comment]
maybe related: https://secure.helpscout.net/conversation/1481480844/255393?folderId=3864740

**Comment by d19dotca** [comment]
This has been an issue for quite some time, any ETA on when this might be fixed? Surprised this issue still exists when it impacts one of the most popularly used website builders on the market. This would surely affect many people.

**Comment by camilamadronero-zz** [comment]
New case https://secure.helpscout.net/conversation/1734816420/315578/

**Comment by marka33** [comment]
This problem is still NOT RESOLVED.
I'm using Elementor v3.6.7, Elementor Pro v3.7.2 and WP Rocket 3.11.4.2

I run on an HTTP/2 enabled server (kinsta), and would prefer not to enable the Combine CSS as it tends to compete with the HTTP/2 advantages.

**Comment by ojosejefferson** [comment]
I found a temporary solution. Elementor > Tools  + Recreate files and data + Sync library, here it works
