### ISSUE TITLE
JS error on preload links script

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3328]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
TypeError: e.target.closest is not a function
This issue occurred with one of our customers with the following specifications:-

Device model iPhone
Operating system iOS 14.1
Browser version Chrome Mobile iOS 86.0
SDK version javascript:2.5.9

**To Reproduce**
I can't reproduce the issue but when talked with @hellofromtonya she told me

> Definitely. There can be a conflict or raise with another script. Could be lots of different things.
> But in this case, the code should guard itself to fail gracefully.
> The event fired calling the listener, but the passed event isn’t in a state for the listener to do anything with it. So bail out.

**Expected behavior**
No such error should happen

**Screenshots**

**Additional context**
We need to check if `event.target` has `closest` inside it OR bailout
https://github.com/wp-media/wp-rocket/blob/85bbdd895c80665f5cd5b9f87846c14a807b3218/assets/js/preload-links.js#L60

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1385905204/228385

**Comment by seangolob** [comment]
This error is popping up for my team and I would love an update on this. Are there any negative side effects besides the error itself? Also, I can't seem to access the Help Scout conversation linked above. 

Side note: This plugin has been a lifesaver for my team! Thank you all for your hard work!

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
