### ISSUE TITLE
Issue with Easy Responsive Tabs plugin

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#333]
Upon activation of WP Rocket, files from the [Easy Responsive Tabs](https://wordpress.org/plugins/easy-responsive-tabs/) plugin are busted automatically, even if "Remove query strings from static resources" option is not activated.

Affected files:

```
../easy-responsive-tabs/assets/css/ert_css.css
../easy-responsive-tabs/assets/js/ert_js.js
```

No WP Rocket (correct behaviour):

![screen shot 2017-02-02 at 2 24 05 pm](https://cloud.githubusercontent.com/assets/7384779/22551097/9cb54958-e953-11e6-8a1f-e13b39dcc00f.png)

WP Rocket active - bug:

![screen shot 2017-02-02 at 2 24 21 pm](https://cloud.githubusercontent.com/assets/7384779/22551106/a7b8b15a-e953-11e6-8251-654f6a5c4ee3.png)

**Comment by arunbasillal** [comment]
I just tested this with ERT `3.1` here: http://mega.wp-rocket.me/nieuws/easy-responsive-tabs-test/

The files have changed to: 
- `/plugins/easy-responsive-tabs/assets/css/ert_css.php`
- `/plugins/easy-responsive-tabs/assets/js/ert_js.php`

And the issue no longer exists.
