### ISSUE TITLE
CRITICAL error when using `TM Extra Product Options` plugin

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3332]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Special Thanks to @vmanthos 

One of our customers are using the plugin `TM Extra Product Options by themeComplete` along with EWWW plugin and gets the following error

> 2020-11-16T14:54:47+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Subscriber\Third_Party\Plugins\Images\Webp\EWWW_Subscriber::maybe_remove_images_cnames(), 1 passed in /home/XXX/public_html/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /home/XXX/public_html/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/Images/Webp/class-ewww-subscriber.php:126
> Stack trace:
> `#0` /home/XXX/public_html/wp-includes/class-wp-hook.php(287): WP_Rocket\Subscriber\Third_Party\Plugins\Images\Webp\EWWW_Subscriber->maybe_remove_images_cnames(Array)
> `#1` /home/XXX/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
> `#2` /home/XXX/public_html/wp-content/plugins/wp-rocket/inc/functions/api.php(69): apply_filters('rocket_cdn_cnam...', Array)
> `#3` /home/XXX/public_html/wp-content/plugins/woocommerce-tm-extra-product-options/include/class-tm-extra-product-options.php(1451): get_rocket_cdn_cnames(Array)
> `#4` /home/XXX/public_html/wp-includes/cl in /home/XXX/public_html/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/Images/Webp/class-ewww-subscriber.php in Zeile 126

**To Reproduce**
1. Install TM Extra Product Options plugin
2. Install WP Rocket
3. Install EWWW plugin
4. Check error log,you will see the error

**Expected behavior**
No error.

**Screenshots**
The code from `TM Extra Product Options` plugin that triggers the issue
![image](https://user-images.githubusercontent.com/15707971/99805243-e08c6580-2b44-11eb-8e05-f41dd4e30e48.png)

**Additional context**
When the function [get_rocket_cdn_cnames](https://github.com/wp-media/wp-rocket/blob/f83e9ea6944883824645259eaae19b23afb476ed/inc/functions/api.php#L40) is called, it will apply the filter [rocket_cdn_cnames](https://github.com/wp-media/wp-rocket/blob/f83e9ea6944883824645259eaae19b23afb476ed/inc/functions/api.php#L69) with only one argument `$hosts` but we need it to be like the following one with two argument

https://github.com/wp-media/wp-rocket/blob/28e7b00cb74df0a18b79c65631d0ba438e019db8/inc/Engine/CDN/CDN.php#L197

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced above

### Identify the root cause ✅ 
Root caused identified above by Ahmed

### Scope a solution ✅ 
In https://github.com/wp-media/wp-rocket/blob/f83e9ea6944883824645259eaae19b23afb476ed/inc/functions/api.php#L40

We should also be passing the `$zone` value to the `apply_filters` call, in addition to what is already there.

### Estimate the effort ✅
Effort `[XS]`

**Comment by engahmeds3ed** [comment]
## For history and @wp-media/qa :

**How to reproduce the issue?**

1. Open product to edit / create new product at woocommerce
2. Go to the part of Extra Product Options as in the following screenshot
![image](https://user-images.githubusercontent.com/15707971/107404922-6a7a1800-6b0f-11eb-958d-10f3e71258dc.png)

3. Add new element and choose radio type
4. Adjust the settings by going to General Options and choose Use Image Replacements and make it Yes and enable swatch mode as in the following screenshot
![image](https://user-images.githubusercontent.com/15707971/107404984-7ebe1500-6b0f-11eb-9527-d94a221c552b.png)

5. Upload swatches image as in the following screenshot
![image](https://user-images.githubusercontent.com/15707971/107405078-9dbca700-6b0f-11eb-9afa-fe81a9091a10.png)

6. Try opening the product page and you will see the following screen
![image](https://user-images.githubusercontent.com/15707971/107405179-b75dee80-6b0f-11eb-87e9-515a61476f15.png)

then check the log, you will see the critical error mentioned above.
