### ISSUE TITLE
Update Never Cache Cookies textarea description to explain partial matches are allowed 

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3334]
**Is your feature request related to a problem? Please describe.**
Our **Never Cache Cookies** exclusion box accepts a partial match,  so adding `wp_woocommerce_session_` will also exclude any cookie including that string on its name, like in the case of tokenized cookies, ie: `wp_woocommerce_session_[TOKEN]`

This is not clearly documented and it might lead users to understand the cookie match has to be literal.  

**Describe the solution you'd like**
- Update the field description to let users know that a partial match is allowed: "Partial matches are allowed"
- Create a DOC about **Never Cache Cookies**, explaining its usage, documenting the possibility of using partial matches. and linked from UI like in other exclusion boxes with the "More Info" links: https://jmp.sh/ZcUiRfo

**Additional context**
On [this doc](https://docs.wp-rocket.me/article/875-using-wp-rocket-with-yith-woocommerce-wishlist) we already recommend the usage of a partial match to exclude `yith_wcwl_session_` type cookies. 

On this issue: https://github.com/wp-media/wp-rocket/issues/1358 we are requesting the usage of **wildcards**, and it could lead users to think that any cookie exclusion has to be literal.

Example ticket: 
https://secure.helpscout.net/conversation/1341907384/213435/

**Suggested update to the help text** (https://github.com/wp-media/wp-rocket/issues/3334#issuecomment-731976401): Specify full or partial IDs of cookies that, when set in the visitor's browser, should prevent a page from getting cached (one per line). More info

**Comment by arunbasillal** [comment]
Current help text: *Specify the IDs of cookies that, when set in the visitor's browser, should prevent a page from getting cached (one per line)*

Suggested update: *Specify full or partial IDs of cookies that, when set in the visitor's browser, should prevent a page from getting cached (one per line)*

@webtrainingwheels What do you think? Also, do you think creating a doc is feasible for this?

**Comment by webtrainingwheels** [comment]
@arunbasillal Looks good! And yes, we can do a doc!

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
Update the helper text for the never cache cookie field in `Engine/Admin/Settings/Page::advanced_cache_section()`

### Estimate the effort ✅
Effort `[XS]`

**Comment by webtrainingwheels** [comment]
@Tabrisrp This will be the doc url: https://docs.wp-rocket.me/article/1382-never-cache-cookies (it will be published by release time) 
And article ID: 5fe5462df24ccf588e3fe804
