### ISSUE TITLE
Cache clearing - With Divi the whole cache is cleared when activating/deactivating plugins

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3349]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When Divi is the active theme, activating/deactivating any plugin, fires the `rocket_clean_domain()` function and clears WP Rocket's cache.

That's done by their `et_core_clear_wp_cache()` function, which is located in `/core/components/init.php`.

They are doing the same for other caching plugins.

**To Reproduce**

1. Activate Divi.
2. Preload the cache.
3. Activate any plugin.
4. Look in the `/wp-content/cache/wp-rocket/` folder. The cache will have been cleared.

**Expected behavior**

By default, we don't clear the cache when activating/deactivating plugins. Instead, we display a notice asking the user to clear the cache manually.

I'd expect the same behavior regardless of the usage of Divi.

**Additional context**

I'm documenting this here, so we'll take it into consideration when the new preload module is built.

Since preloading doesn't take place after `rocket_clean_domain()` runs, preloading will take place only if it's manually triggered.
If it's not, caching will take place when visitors will visit URLs, with the impact this may have on first visits.

It may worth exploring the possibility to reach out to Divi or come up with a way of handling this on our side.

**Related ticket:** https://secure.helpscout.net/conversation/1338166057/212013?folderId=273766#thread-3879175361

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
Divi might have this as a "standard practice" for all cache plugins. I think the best way would be to reach out to them in this case and inform them that we indeed display a notice. 

@Tabrisrp When you have the time, can you please take the lead on this one to contact them?

**Comment by Tabrisrp** [comment]
@arunbasillal If they deemed necessary to do that on their side, why would we need  to reach to them?

**Comment by arunbasillal** [comment]
@Tabrisrp Since we show our users a notice when a plugin is activated or deactivated, this isn't necessary with WP Rocket, right? Hopefully they can remove it for WP Rocket?

**Comment by Tabrisrp** [comment]
This was already discussed here: https://github.com/wp-media/wp-rocket/issues/2630

**Comment by arunbasillal** [comment]
@Tabrisrp That was related to clearing cache when updating a post, right? 

But either way, this is not really our domain and something for Divi to change. Also, activating and deactivating plugins are rare instances and shouldn't be a huge concern. 

Vasilis noted:

> Since preloading doesn't take place after rocket_clean_domain() runs, preloading will take place only if it's manually triggered.

Do you think it's a good idea to preload the cache when `rocket_clean_domain` is used?
