### ISSUE TITLE
Prevent CDN URL replacement on images posted via XMLRPC.php

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#337]
When using WP Rocket's CDN feature, if you post using XMLRPC (e.g., using the WordPress app or Windows Live Writer) and include an image in the post, its URL will end up being modified by the CDN filter _within the post editor itself_ (rather than just on the front end).

![img_0809_crop](https://cloud.githubusercontent.com/assets/44367/22609353/7e771542-ea26-11e6-9b69-6c1ffdf6b79d.png)

We should keep our filter (located in _/inc/front/cdn.php_) from executing during XMLRPC requests, e.g.: 

```
if ( !defined( 'XMLRPC_REQUEST' ) || !XMLRPC_REQUEST ) {
	add_filter( 'wp_get_attachment_url'		, 'rocket_cdn_file', PHP_INT_MAX );
}
```

**Comment by GeekPress** [comment]
We can directly check in the rocket_init if the XMLRPC constant is defined. There is no reason to have WP Rocket working on this case.

@Tabrisrp do you confirm?

**Comment by Tabrisrp** [comment]
I agree
