### ISSUE TITLE
Borlabs Cookie and Optimize CSS delivery issue on Firefox

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3374]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When **Borlabs Cookie** plugin and **Optimize CSS delivery** in WP Rocket are activated, the page loads from the end, i.e. the end of the page is displayed in Firefox browser.
This seems to be happening only on German sites where the file `/wp-content/cache/borlabs-cookie/borlabs-cookie_1_de.css` is used.

**To Reproduce**
1. activate Borlabs Cookie plugin;
2. activate Optimize CSS delivery option in WP Rocket;
3. Open the page in Firefox browser and you will see the issue.

**Expected behavior**
Page to load normally from the top.

**Additional context**

Current solution:

1. Add `/wp-content/cache/borlabs-cookie/borlabs-cookie_1_de.css`  file to the _Excluded CSS files_ text area in the File Optimization tab.
2. Install the helper plugin to exclude Borlabs cookie stylesheet from optimization: /wp-content/cache/borlabs-cookie/borlabs-cookie_1_de.css. Helper plugin can be downloaded here: https://jmp.sh/Lyy80R1
Ref.: [Exclude files from Optimize CSS Delivery](https://docs.wp-rocket.me/article/977-exclude-files-from-optimize-css-delivery)
3. Clear cache in WP Rocket settings.
4. Enable _Optimize CSS delivery_ option.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related tickets:
https://secure.helpscout.net/conversation/1343976022/214174/
https://secure.helpscout.net/conversation/1299977431/199564
https://secure.helpscout.net/conversation/1300804809/199848

**Comment by iCaspar** [comment]
Another related ticket:
https://secure.helpscout.net/conversation/1360152568/221022

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1504142883/261637/

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
