### ISSUE TITLE
Download WP Rocket directly through a WP Rocket repository

### ISSUE THREAD

**Issue by MaximeCulea** [wp-media/wp-rocket#3381]
**Is your feature request related to a problem? Please describe.**
I am managing my WordPress install with composer for WordPress core and plugins and also WP Rocket. For now, I am forced to check regularly if there are updates, download manually the plugin and upload it into my composer private repository. At this point, I can finally update into my project with composer the package.

**Describe the solution you'd like**
Ideally, you would need to implement a repository to allow composer projects to be directly fed from your repository rather than each people private repository. It's time saver!
See an example from wpmudev here: https://premium.wpmudev.org/blog/composer-repository/

**Comment by arunbasillal** [comment]
Tagging @Tabrisrp here for comment. Thanks.

**Comment by ethanclevenger91** [comment]
WP Rocket is already on Packagist, with the correct installer type at that, and I have no issues requiring it in my composer-driven WP setups like any other package:

```
{
    "name": "sterner-stuff/bedrock",
    ...
    "require": {
        ...
        "wp-media/wp-rocket": ">=3.5"
        ...
    }
}
```

**Comment by MaximeCulea** [comment]
Then @arunbasillal @Tabrisrp downloading from https://packagist.org/packages/wp-media/wp-rocket or from the plugin account is strictly the same?

**Comment by remyperona** [comment]
@MaximeCulea Almost, the only difference is that from packagist, your licence data is not present at the root of the plugin directory (And composer autoloading is not yet created, but that's normal).

You should not have any issue using the plugin via packagist and composer directly.

**Comment by MaximeCulea** [comment]
The idea was to automagically do that like ACF, WPMUDEV, etc.

**Comment by ethanclevenger91** [comment]
I don't know if any way to configure your license as you install ACF via
Composer, but with WP Rocket, I set my license information via env
variables and then have an mu-plugin that loads those into constants. I do
this for a variety of licensed plugins where possible to avoid managing my
licenses in the database or having them in Git.

**Comment by MaximeCulea** [comment]
Yes it is possible like so:
- for ACF plugin: https://roots.io/guides/acf-pro-as-a-composer-dependency-with-encrypted-license-key/
- for WPMUDEV plugins: https://premium.wpmudev.org/docs/getting-started/download-wpmu-dev-plugins-themes/

Maybe I am asking too much here, but nowadays it is quite a standard in the PHP community especially when it comes to premium, located on a private packagist. Freemium are moreover located on the public packagist.

Anyway @ethanclevenger91 the way you do it could be a lead. So you add .env variables which are loaded afterwards as PHP globals then used by the plugin?

Just for the record, in any cases I am not fan of saving the credentials in the base code, that's why the way wpmudev do it, is very elegant for me, with an auth key 👌
