### ISSUE TITLE
Default or template settings

### ISSUE THREAD

**Issue by MaximeCulea** [wp-media/wp-rocket#3382]
**Is your feature request related to a problem? Please describe.**
I am faced to deal a huge amount of websites on several multisites and/or as we start a lot of new projects on the behalf of the clients, we lose to much time to configure the settings of the plugin, which in our cases are 90% the same.

**Describe the solution you'd like**
So Ideally, it would be awesome to have like a starter of settings to make the installation of WP Rocket smooth!
See an how I deal that for another plugin: https://gist.github.com/MaximeCulea/7d160fcf97e707fd1dc4e066a7cb46c5

**Comment by arunbasillal** [comment]
@MaximeCulea There are two ways currently to make this happen. 

- You can configure WP Rocket once and then download the settings via `Tools` tab. Then import the settings in a new installation. ([Doc](https://docs.wp-rocket.me/article/1137-tools-tab-export-import-settings-and-version-rollback#export-import-settings))
- Filter the option similar to what you have done for Autoptimize. Details below. 

To filter:

- Use the filter, `pre_get_rocket_option_ . $key` - https://github.com/wp-media/wp-rocket/blob/da65dc571fcab9c2c3bc7fad6964d684202abae0/inc/classes/admin/class-options-data.php#L58
- `$key` is the name for the option. One easy way to find it is to inspect the option in the UI. Please refer the screenshot below. 
- You can see an example in the helper plugin here: https://github.com/wp-media/wp-rocket-helpers/blob/78142b653c120020103c85d382dc2a346dbcba17/static-files/wp-rocket-static-desktop-opt-css-mobile/wp-rocket-static-desktop-opt-css-mobile.php#L56

![image](https://user-images.githubusercontent.com/5751474/100970841-c0ed3800-355b-11eb-87e9-ba5173ae83dd.png)

Hope that helps.

**Comment by MaximeCulea** [comment]
Thank you for your quick answer :)

The idea was to write down on a single doc all that options and moreover expose each field with a filter. It's pretty handy to hook only the wanted option instead of all the bunch of options.

**Comment by arunbasillal** [comment]
> It's pretty handy to hook only the wanted option instead of all the bunch of options.

This is exactly possible with the filter. Examples below. 

- `pre_get_rocket_option_async_css_mobile` will only filter the Optimize CSS delivery option. 
- `pre_get_rocket_option_minify_css` will filter the option, Minify CSS 

and so on. 

I hope I got your question correctly.

**Comment by MaximeCulea** [comment]
Yeah of course 👍 

My point was more a documentation talking about all theses, return values and effects, so on. 
I can deal without it, I was just thinking it was worth it ;)
