### ISSUE TITLE
Automatic backup of the settings before the update

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3386]
**Is your feature request related to a problem? Please describe.**
If an update causes any changes to the customers' settings, it would be great to have a backup of the old settings made automatically before the update.

**Describe the solution you'd like**
We could export the settings in JSON to `/wp-rocket-config/` directory before updating to the newer version.

**Additional context**
I thought about this due to the last, 3.7.6 update problem.

**Comment by WordPresseur** [comment]
Or even before deactivation: https://secure.helpscout.net/conversation/2393677704/449082?folderId=1213662

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
