### ISSUE TITLE
rocket_is_internal_file() returns false all the time

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#3387]
In connection with a regression found following #3232 I've reverted the change there to return `false` when `$file_host` is empty -- which as it turns out is all the time, thus treating every file as external (the previous fix - returning the same line `true`, therefore misidentified too much as being internal).

The bugged value of `$file_host` is because entries like `example.com` or `example.com/some-path...` always are returned in the `path` part of the parsed url from `wp_parse_url()` -- there needs to be a `//` to properly trigger the file component as the `host`.

I've played around with some alternative regex to match (below) but we will still need some more thorough testing to confirm it is working properly.

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
