### ISSUE TITLE
Use PHP port of the YUI Compressor's CSSmin

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#339]
Default minify CSS compressor is unmaintained, and the CSSmin port gives better performance

enabling it by uncommenting this line in min/config.php

`$min_serveOptions['minifiers']['text/css'] = array('Minify_CSSmin', 'minify');`

**Comment by GeekPress** [comment]
What do you mean by "port gives a better performance"?

**Comment by Tabrisrp** [comment]
PHP code is more optimized so the CSS minification process works better and is faster

**Comment by GeekPress** [comment]
Oh looks great :)
