### ISSUE TITLE
Optimize CSS Delivery - Allow wildcard exclusions of CSS files

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3396]
**Is your feature request related to a problem? Please describe.**

One of the ways to fix a FOUC is excluding files from being loaded asynchronously.

Currently, it's possible to exclude files with static names:
https://github.com/wp-media/wp-rocket/blob/b0fe07b2335a5aa39a0f9a51e811ff3f41c99ea4/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L658

However, many themes and page builders create CSS files with dynamic names, e.g.:
`wp-content/et-cache/global/et-divi-customizer-global-16075198797636.min.css`

**Describe the solution you'd like**

Allow the exclusion of dynamic filenames from async loading.

**Comment by vmanthos** [comment]
Another usage case where this will be useful:

With RUCSS and Optimize CSS delivery (OCD), when there is a FOUC, we need to exclude the `used.min.css` file from being loaded asynchronously.

This is not currently possible if we need to do it site-wide, and the only solution currently is to disable OCD.

**Related ticket:** https://secure.helpscout.net/conversation/1523385410/266603

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1530505740/268431

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
