### ISSUE TITLE
Automatic update announced on update-core.php screen but disabled on plugins screen

### ISSUE THREAD

**Issue by audrasjb** [wp-media/wp-rocket#3397]
Hi friends,

I think there is a bug in your auto-updates implementation.
Indeed, even if auto-updates are disabled on the Plugins screen, an update is announced in my update-core.php screen.

See screenshots below.

Auto-updates disabled on plugins screen:
<img width="1147" alt="Capture d’écran 2020-12-09 à 19 57 27" src="https://user-images.githubusercontent.com/1590998/101674581-f6f95300-3a58-11eb-8d5c-84725b72731b.png">

Auto-updates scheduled on update-core screen:
<img width="1127" alt="Capture d’écran 2020-12-09 à 19 57 06" src="https://user-images.githubusercontent.com/1590998/101674648-0e384080-3a59-11eb-8e16-0ed51a670fd8.png">

**Comment by Tabrisrp** [comment]
hey @audrasjb thank you for the report.

We use the `auto_update_plugin` filter and this method hooked on it to disable the auto-updates, is there a different filter to use for the update-core screen?

https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/classes/subscriber/Plugin/class-updater-subscriber.php#L270

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
