### ISSUE TITLE
Set variable once delayed scripts are loaded

### ISSUE THREAD

**Issue by androidacy** [wp-media/wp-rocket#3400]
**Is your feature request related to a problem? Please describe.**
I have several scripts that rely on the scripts wp-rocket defers execution for when they execute (or do not). Currently I have to use window.Onload and a timer, but that timer can be imprecise and cause the script to misfire because the user has not "interacted" or such

**Describe the solution you'd like**
Once the scripts are executed, set a global variable so that scripts that depend on the delayed scripts can check to see if they've been loaded yet.

**Describe alternatives you've considered**
The aforementioned timer.

**Additional context**
My scripts display notices or do redirects based on if certain JS has loaded

**Comment by arunbasillal** [comment]
@Tabrisrp What do you think about this request? Is this something that we can do or is there already a way to detect this?

**Comment by GeekPress** [comment]
Hi @androidacy 🤚

Welcome and thanks for contributing to WP Rocket repository.

I understand your need and how it could help you. On another side, the need seems to be very rare, and we try to avoid to complexify our features with cases like that.

To help to achieve what you would like to do, we contributed to the WordPress core to add new hooks:
https://core.trac.wordpress.org/ticket/51325

Thanks to them you will be able to update the content of an inline script like ours.
