### ISSUE TITLE
Wp rocket keeps overwriting and deleting my custom .htaccess file rules

### ISSUE THREAD

**Issue by jazir5** [wp-media/wp-rocket#3406]
**Describe the bug**
My htaccess contents keep getting wiped.

**To Reproduce**
Activate wp-rocket. It completely erases and overrides the existing htaccess file.

**Expected behavior**
Checks for the expected wp-rocket rules in the .htaccess file regardless of what line they are on in the .htaccess file, and only add the needed rules to the htaccess file if theyre not there, leaving the custom rules I put in alone. I've had to replace them 5 times. Every single time I restore from a duplicator backup, wp rocket just straight wipes my configuration.

**Additional context**
I simply cannot use the default wp-rocket htaccess rules. I have tons of custom htaccess rules that I need to keep. There should be a tick box in the settings to leave the htaccess file alone and stop editing it.

**Wanted Solution**

Enable a simple tick box in wp-rocket settings which disables editing of the htaccess file. It should come with a warning that you need to implement the wprocket htaccess rules yourself if you enable this option.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
Hello @jazir5 

Normally WP Rocket should only edit the .htaccess between the markets `# BEGIN WP Rocket v3.x` and `# END WP Rocket`. 

You can disable editing .htaccess completely using the `rocket_disable_htaccess` boolean filter. We have a helper plugin to do the same - https://github.com/wp-media/wp-rocket-helpers/tree/master/htaccess/wp-rocket-no-htaccess

Once you use the filter and set it to `true`, WP Rocket will no longer try to edit .htaccess 

I hope that helps.
