### ISSUE TITLE
Import settings by cli command

### ISSUE THREAD

**Issue by angelorock** [wp-media/wp-rocket#3412]
How to import setting with a cli command? I need enable a feature in my docker image, help.

**Comment by Tabrisrp** [comment]
Hi @angelorock,

This is not yet possible with a CLI command, but we do have an issue for this on our CLI repository: https://github.com/wp-media/wp-rocket-cli/issues/18

You can add a comment on this one if you'd like.

I'm going to close this issue as this repo is for the plugin specifically.

**Comment by angelorock** [comment]
Ok, thanks @Tabrisrp 
My solution:
`
wp option update wp_rocket_settings < /usr/src/wp-rocket/settings.json --format=json
`
