### ISSUE TITLE
Get rid of "Remove jQuery Migrate" option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3413]
## What are we proposing to do? 

With this update, WP Rocket will no longer have the option to remove jQuery migrate. The associated option in WP Rocket’s “File Optimization” settings titled “Remove jQuery Migrate” will also be removed. 

![](https://lh4.googleusercontent.com/i2B7ysYE2c-4gD4be2_l3az7f3N2Rx_n8RTYPbUMv87DZMLWYB1eS4fQ6HRffKu90sgQ80i_3TFT7IyqyemmAwI16RBPGQ458dJbOY1uH98F9rw_7MqQLb5XsJykFPjWC-9qsY7t)

## Why are we doing this? 

[<u>jQuery migrate</u>](https://plugins.jquery.com/migrate/) is a compatibility plugin for jQuery to migrate old versions of jQuery code into new. As of WordPress 5.6, this file is bundled with the core. 

<p></p>

However, with WordPress 5.7, WordPress will [<u>no longer be shipping with jQuery migrate</u>](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/). This means that the WP Rocket option will no longer be relevant. This is planned for [<u>March 2021</u>](https://wordpress.org/about/roadmap/). 

<p></p>

With WordPress 5.6 release, WordPress updated the jQuery library and the associated jQuery migrate plugin. Since many plugins and themes are not updated to be compatible with the new version of jQuery library, they need the jQuery migrate plugin to work correctly. So removing the jQuery migrate is breaking websites for some of our customers when they update to WordPress 5.6. 

<p></p>

We can ask these customers to not remove the jQuery migrate file by unchecking the option. But a better solution would be to remove the feature as such, since the feature will become obsolete in the coming months. Since jQuery related errors are hard to discover for many users, this will avoid frustration and lead to better user experience. 

<p></p>

jQuery migrate file is very small (~4.2KB) and has very low impact on performance. 

## User expectations and experience. How will we do this feature?

The experience will be the same for existing users and new installs. 

<p></p>

- The UI option “Remove jQuery Migrate” will be removed from the “File Optimization” tab. 

- jQuery migrate will no longer be removed. 

## Risks

We are not expecting any risks with this change. Even if jQuery migrate is not needed by the website, adding the file back is not going to break anything or impact performance in a meaningful way. 

## Acceptance Criteria

- The UI for “Remove jQuery Migrate” is removed from File Optimization settings

- jQuery migrate file is loaded on WordPress versions that ship with jQuery migrate. 

## Documentation and Translations

- Doc update needed for: [<u>https://docs.wp-rocket.me/article/1304-remove-jquery-migrate</u>](https://docs.wp-rocket.me/article/1304-remove-jquery-migrate)

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/6439259

**Comment by iCaspar** [comment]
I think there was some discussion about doing this conditionally that is not included in the card here:
For customers not yet on WP 5.6, this will remove something that has been of some (perhaps small) benefit, without causing the problem. It seems like a conditional removal, contingent on WP version is in order here.

Contingency or not, this is a UI change that will need full QA. It should be prioritized for 3.8.1, as 3.8 is already halfway out.

**Comment by GeekPress** [comment]
@iCaspar We are going to directly remove the option whatever the WordPress version. Here the thread about that decision on Slack: 
https://wp-media.slack.com/archives/G087NJ788/p1607618134012000

**Comment by crystinutzaa** [comment]
**Code changes** ✅ 
1. Deprecate class `Dequeue_JQuery_Migrate_Subscriber`
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/classes/subscriber/Optimization/class-dequeue-jquery-migrate-subscriber.php#L14

2. Remove Jquery Migrate from Plugin.php
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/Plugin.php#L202

3. Remove JQuery Migrate Subscriber from ServiceProvider
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/Engine/Optimization/ServiceProvider.php#L35
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/Engine/Optimization/ServiceProvider.php#L76-L77

4. Remove Tests ( Unit & Integration )
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/tests/Integration/inc/classes/subscriber/Optimization/Dequeue_JQuery_Migrate_Subscriber/dequeueJqueryMigrate.php#L12
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/tests/Integration/inc/classes/subscriber/Optimization/Dequeue_JQuery_Migrate_Subscriber/getSubscribedEvents.php#L12

5. Remove jQuery Migrate Beacon info
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/Engine/Admin/Beacon/Beacon.php#L354-L363

6. Remove JQuery Migrate option from WP Rocket Admin
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/Engine/Admin/Settings/Page.php#L560
https://github.com/wp-media/wp-rocket/blob/968e48def617c89190720018235fd50f4707be21/inc/Engine/Admin/Settings/Page.php#L693-L702

**Estimate the effort** ✅ 

`Effort: [XS]`

**Comment by hellofromtonya** [comment]
@crystinutzaa What about removing the option from the database?

**Comment by engahmeds3ed** [comment]
Trying to get slack final decision about that point here:

@hellofromtonya : What happens if the admin doesn’t save the settings and a 3rd party plugin/theme reads the options?
@hellofromtonya : And if they open a ticket, don’t we grab the options as part of the report?
@Tabrisrp : We can always remove it during the upgrade routine to be safe 

So final decision is to remove this option completely from the database when upgrade.

**Comment by hellofromtonya** [comment]
Yes, during the update, let's have a script that pulls the option, removes it (if it exists), and then updates the option. In doing so, we are cleaning up this feature from the UI and database.
