### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined - compatibility with Enable jQuery Migrate Helper

### ISSUE THREAD

**Issue by EmmanuelHmar** [wp-media/wp-rocket#3414]
- WP Rocket Version 3.7.6.1

**Describe the bug**
jQuery is being deferred even with Safe Mode turned on after Enable jQuery Migrate Helper update (version 1.2.0 and up)

**To Reproduce**
1. Enable jQuery Migrate Helper - version 1.2.0 or 1.3.0

**Problem**
jQuery is served from `wp-content/plugins/enable-jquery-migrate-helper/js/jquery-1.12.4-wp.js?ver=1.12.4-wp`
vs `wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` after version 1.2.0

**Screenshots**
https://i.imgur.com/jHrtISB.png
https://i.imgur.com/eVbt5V2.png

**Comment by arunbasillal** [comment]
Hello @EmmanuelHmar 

The latest version of WP Rocket (3.8.0.1) ships with a UI to exclude files from Defer JS - https://github.com/wp-media/wp-rocket/issues/3233

3.8 is in [staggered release](https://docs.wp-rocket.me/article/1293-wp-rocket-release-process) right now, so if it's available, please update to it and exclude the file. 

Until then, exclusion can be done using a helper plugin as described here: https://docs.wp-rocket.me/article/976-exclude-files-from-defer-js#previous

I hope that helps.

**Comment by arunbasillal** [comment]
@wp-media/support The `jQuery Migrate Helper` plugin is supposed to be a short term fix. It doesn't make sense to have explicit compatibility with it I think. 

However, if we have more reports and issues like this customer, maybe we should do something out of the box. What do you think?

**Comment by Tabrisrp** [comment]
This jQuery file will be matched by the new jQuery pattern in 3.8, and the plugin is there to be a short term fix, so as you said it doesn't make sense to do a fix specifically for it.
