### ISSUE TITLE
CDN breaking Javascripts userAgent detection

### ISSUE THREAD

**Issue by arlg** [wp-media/wp-rocket#3416]
**Before submitting an issue please check that you’ve completed the following steps:**
- Wp-Rocket version 3.7.6.1 
- The bug has not been reported before.

**Describe the bug**
I have activated The Rocket CDN and my site javascript breaks after it. 
my javascript console logs : `Uncaught SyntaxError: missing ) in parenthetical`

**To Reproduce**

1. I have some userAgent detection code in my javascript (inlined in the page) like : 
`if ( /Mobi|Android/i.test(navigator.userAgent)) {}` 

2. When I turn on the CDN, this line becomes : 
`if ( (https://h3v4h5y4.rocketcdn.me/Mobi|Android/i.test(navigator.userAgent)) {}`

**Expected behavior**
CDN activation should not break javascript .test by prepending cdn URL.

**Screenshots**
No screenshots

**Additional context**
The bug occors in all browsers.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
It was fixed in https://github.com/wp-media/wp-rocket/pull/4535
