### ISSUE TITLE
Remove multiple CDN CNAME choices

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3417]
**Is your feature request related to a problem? Please describe.**
Within the CDN options of WP Rocket, currently users can add multiple CDN CNAMES. With this update, we will remove these options from WP Rocket. 

Specifically, we will be removing the button to “ADD CNAME” and the dropdown titled “reserved for” in the UI.

**Describe the solution you'd like**
Further details related to this improvement are available [here](https://www.notion.so/wpmedia/5d9809fbfff74a30a0a6e2ab72498fa4?v=791d9573e7c34c8f87fa031d27da0b70&p=bba7447e6d134628bc27b7ca59d2f6f4&pm=s).

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/6461264

**Comment by Mai-Saad** [comment]
@GeekPress Just a side note: inside the single field for CDN name, we can enter currently multiple CDNs separated by comma (As per what mentioned above, I think we may need to block this option)

**Comment by GeekPress** [comment]
> @GeekPress Just a side note: inside the single field for CDN name, we can enter currently multiple CDNs separated by comma (As per what mentioned above, I think we may need to block this option)

@Mai-Saad About which documentation are you referring to? I can't see anywhere that we can add multiples CNAME in the same fields by using a comma.

**Comment by Mai-Saad** [comment]
@GeekPress I just saw it while exploring the feature and it worked (not referring to any docs)

https://user-images.githubusercontent.com/76941962/109012524-c5d50a00-76ba-11eb-9bcb-d1e72600f600.mp4

**Comment by GeekPress** [comment]
@Mai-Saad Thanks for the video. It seems that nobody in the team was aware of this possibility. In the meantime, there is no documentation to let our users know it's possible to do this. 

Can we safely assume that this specificity isn't used by our users?

**Comment by Mai-Saad** [comment]
@GeekPress I guess we can assume so, but there is no 100% guarantee. So recommend, we guard ourselves anyway while doing this enhancement if doable.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen the issue when it'll be scheduled for the release.
