### ISSUE TITLE
WooCommerce Multilingual currency switcher compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3418]
**Is your feature request related to a problem? Please describe.**
WooCommerce Multilingual currency switcher is not compatible with caching. Since the new, 4.11 version they are giving a possibility to store the currency in cookies.

**Describe the solution you'd like**
We should use a `dynamic cookie`, disable `rewrite rules` and be compatible with this currency switcher. This is the code that will enable the usage of cookies:
https://snippi.com/s/108po0y

They also have a way to use geolocation, we should then make sure that `mandatory cookie` is used. I've just asked their team to provide us a way to determine whether the `geolocation` or `site's language` is used.

**Additional context**
- We're doing a similar thing for Aelia
- https://github.com/wp-media/wp-rocket/issues/3326 will be closed
- I was testing the 4.11 beta, the cookie way doesn't seem to work correctly there 👎

**Comment by strategio** [comment]
Hi @Tabrisrp and @piotrbak, please check my suggestion in https://github.com/wp-media/wp-rocket/pull/3483.

**Comment by piotrbak** [comment]
@strategio I've sent an email to Olivia and Sergey on 18.12 with the information that changing the currency is not changing the cookie at all. On 13.01 Olivia told me that you're still working on this. I haven't received any further information on whether it's already fixed or not. Without this working as expected, we won't be able to test everything correctly.

Do you know if it's fixed?

**Comment by strategio** [comment]
@piotrbak, the change suggested in #3483 will work only with another fix in WCML (not released yet), but it causes no problem if it runs with an old version of WCML.

So if you want to test it on your side, I can share a dev version of WCML. The corresponding merge request can be find [here](https://git.onthegosystems.com/glue-plugins/wpml/woocommerce-multilingual/-/merge_requests/1461) and you can download the plugin from this branch [here](https://git.onthegosystems.com/glue-plugins/wpml/woocommerce-multilingual/-/jobs/1001661/artifacts/download) (beware, the download link might expire in 7 days).

Let me know your findings via Olivia's email, thanks :)

**Comment by piotrbak** [comment]
@strategio I've been testing your cookie caching mechanism using the 4.11 beta and this filter:
https://snippi.com/s/108po0y
It didn't work at all. Do you know if it is fixed? Unfortunately, I'm not able to access provided links.

Thanks!

**Comment by strategio** [comment]
Hi @piotrbak, I am confused because you shared a [small snippet](https://snippi.com/s/108po0y) in your previous comment , and this is just a part of the whole configuration. Please check the code in https://github.com/wp-media/wp-rocket/pull/3483.

So, in order to test this properly you need:
- The [WCML in-dev plugin](https://git.onthegosystems.com/glue-plugins/wpml/woocommerce-multilingual/-/jobs/1001661/artifacts/download) (you can check what we included in [this merge request](https://git.onthegosystems.com/glue-plugins/wpml/woocommerce-multilingual/-/merge_requests/1461)) 
- The WP Rocket plugin including the new WCML compatibility code ([pull request 3483](https://github.com/wp-media/wp-rocket/pull/3483))

If your tests are still failing, let me know your actual steps (or please share a screencast) and I'll re-test on my side.

**Comment by piotrbak** [comment]
@strategio Hi! This snippet should force WPML to use cookies instead of the sessions to store current currency data, right?

So when I was testing this using the mentioned 4.11 beta version, it wasn't working:
1. I visited the not cached page, the currency cookie was set correctly to EUR
2. I changed the currency using switcher in the menu to USD and refreshed the page
3. The currency cookie was still pointing to the EUR

When it comes to the links, they're bringing me to the `Not Found` page:
![image](https://user-images.githubusercontent.com/26767037/106319157-e69b7280-6268-11eb-9573-9d761f11e254.png)

I guess I need some kind of access. In the downloads section on your site I'm not able to see WPML beta:
![image](https://user-images.githubusercontent.com/26767037/106319328-2d896800-6269-11eb-9100-3861acd568fd.png)

Please let me know!

**Comment by strategio** [comment]
Hi @piotrbak!

>@strategio Hi! This snippet should force WPML to use cookies instead of the sessions to store current currency data, right?

This snippet is not sufficient. Please use [all the code changes needed on WP Rocket side](https://github.com/wp-media/wp-rocket/pull/3483/files#diff-1d043ceb3db90cf761c7342144111ffb1bf1514d68b07bc3861534aabedfb6cbR10) (pull request => https://github.com/wp-media/wp-rocket/pull/3483).

Concerning the WCML dev version (greater than WCML 4.11), I've uploaded a version below:
[woocommerce-multilingual.wcml-3503.13434 (2).zip](https://github.com/wp-media/wp-rocket/files/5905230/woocommerce-multilingual.wcml-3503.13434.2.zip)

**Comment by piotrbak** [comment]
Hello @strategio 

The things are working on the version you shared with me. I have some questions/concerns though:

1. I'm not sure when exactly this hook is triggered, but if it's used on the frontend, I don't think it's necessary:
https://github.com/wp-media/wp-rocket/blob/436996870bd073db3119115c1c690c04ea492e97/inc/3rd-party/plugins/ecommerce/woocommerce-multilingual.php#L7

2. When changing some settings we should also clear the WP Rocket's cache. I'm thinking about adding or removing the currencies, also geolocation.

@Tabrisrp What's your opinion?

**Comment by strategio** [comment]
Thanks for the feedback @piotrbak, and glad it works :)

>1. I'm not sure when exactly this hook is triggered, but if it's used on the frontend, I don't think it's necessary:

When a visitor decides to switch the currency, we are also refreshing so parts of the display via AJAX (code is located in `\WCML_Multi_Currency::switch_currency`) and this is where the `wcml_switch_currency` action is fired.

But to be honest, I don't know why we are calling `rocket_clean_domain`.

**Comment by piotrbak** [comment]
@strategio The fix is okay on our end, but there's something wrong happening on your side. I've already contacted Olivia and Mohamed about this via email. Commenting here se you're also aligned. We can discuss everything here:
https://github.com/wp-media/wp-rocket/issues/3998
