### ISSUE TITLE
Compatibility with Minification & Sucuri's .htaccess hardening

### ISSUE THREAD

**Issue by blogtutor** [wp-media/wp-rocket#342]
The Sucuri Security plugin offers hardening features for several folders, adding .htaccess files that restrict access to PHP files.  This interferes with WP Rocket's minification functionality, since it restricts access to the /wp-content/plugins/wp-rocket/min/index.php file... even though the .htaccess in the /min/ folder tries to allow the access.

Here is the .htaccess file that Sucuri adds in the /wp-content/ folder:
```
<FilesMatch "\.(?i:php)$">
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
</FilesMatch>
```

Here is the current .htaccess file that WP Rocket includes in the /wp-content/plugins/wp-rocket/min/ folder:
```
<Files index.php>
Allow from all
</Files>

<IfModule mod_rewrite.c>
RewriteEngine on

# You may need RewriteBase on some servers
#RewriteBase /min

# rewrite URLs like "/min/f=..." to "/min/?f=..."
RewriteRule ^([bfg]=.*)  index.php?$1 [L,NE]
</IfModule>
<IfModule mod_env.c>
# In case AddOutputFilterByType has been added
SetEnv no-gzip
</IfModule>
```
To make these two compatible, I propose changing the included WP Rocket .htaccess file to this (replacing the first three lines with this new FilesMatch directive):
```
<FilesMatch "index.php">
  <IfModule !mod_authz_core.c>
    Allow from all
  </IfModule>
  <IfModule mod_authz_core.c>
  Require all granted
  </IfModule>
</FilesMatch>

<IfModule mod_rewrite.c>
RewriteEngine on

# You may need RewriteBase on some servers
#RewriteBase /min

# rewrite URLs like "/min/f=..." to "/min/?f=..."
RewriteRule ^([bfg]=.*)  index.php?$1 [L,NE]
</IfModule>
<IfModule mod_env.c>
# In case AddOutputFilterByType has been added
SetEnv no-gzip
</IfModule>
```
Obviously one could manually edit Sucuri's .htaccess file, but it would be very easy to accidentally undo the changes by someone who isn't familiar with the setup (for example, if they remove the hardening and then re-enable it, this change would be lost)... which would then break minification again.

So, it would be great if the /wp-content/plugins/wp-rocket/min/.htaccess file could be adjusted for future versions of WP Rocket.

**Comment by Tabrisrp** [comment]
Seems a good suggestion, did you test the change and confirm it works?

**Comment by blogtutor** [comment]
Yes - I have the updated .htaccess in place on my site (blogtutor.com) and it's working fine.  :)

**Comment by blogtutor** [comment]
Sidenote: It looks like this problem started with version 1.7.12 of the Sucuri plugin. They had previously been using only the "Deny from all" directive to block php files...and with that version they added the logic to include the "Require all denied" directive.

**Comment by Tabrisrp** [comment]
Reopening this as it caused issues on some setups, probably Apache < 2.4. Code provided is not universally compatible so we have to find a workaround.

**Comment by blogtutor** [comment]
Bummer. 

According to the notes in the Sucuri plugin, the current hardening method they're using in.htaccess should work in both Apache 2.2 and 2.4:
https://plugins.trac.wordpress.org/browser/sucuri-scanner/trunk/sucuri.php#L9194

**Comment by Tabrisrp** [comment]
We'll look into it further and test on both 2.2 and 2.4 to understand what happened with the previous code

**Comment by blogtutor** [comment]
I wonder: If someone had enabled the Sucuri hardening while they were running earlier than 1.7.12 of their plugin, they could have had the "old" .htaccess hardening already in place. And I'm betting Sucuri didn't automatically update an existing .htaccess file when they changed how they do the hardening (in 1.7.12 and later).

So perhaps the incompatibility was with Sucuri's old .htaccess file? I think the hardening before 1.7.12 was simply this:
```
<Files *.php>
deny from all
</Files>
```

**Comment by Tabrisrp** [comment]
No longer a concern with our change to a different minification library
