### ISSUE TITLE
Google Analytics Tracking Issues with Delay Javascript execution

### ISSUE THREAD

**Issue by alihs** [wp-media/wp-rocket#3420]
**Describe the bug**
Google Analytics doesn't properly record the user data when javascript execution is delayed. Which means irregularities with tracking user data/traffic.

**To Reproduce**
1. Have Javascript Execution delayed making sure analytics is part of the list
2. Scroll around the website with Analytics real-time data open as a window.
3. Out of 3 actions (page load + movement, refresh, navigate to other page) only the navigation to the other page is recorded.

**Expected behavior**
Should record fine.

**Video**
https://streamable.com/6uhaoq

**Comment by alihs** [comment]
Anyone facing the same issue?

**Comment by socialpreneur** [comment]
Could you explain "Scroll around the website with Analytics real-time data open as a window." in more detail?

For example, delay JS won't get triggered at all if you are testing mobile view on Chrome. You actually have to click any space on the website to trigger the load. Two finger scroll doesn't trigger. That' something I know of, but did you check it by viewing network waterfall during your scroll test?

**Comment by alijiwani** [comment]
If you see the video attached you can see analytics not being triggered properly. So i opened up the website and scrolled around i.e. scroll up and down using the mac trackpad (window was active), _ga wasn't sending info to analytics and not showing real-time users.

**Comment by alihs** [comment]
If you see the video attached you can see analytics not being triggered properly. So i opened up the website and scrolled around i.e. scroll up and down using the mac trackpad (window was active), _ga wasn't sending info to analytics and not showing real-time users.

**Comment by alijiwani** [comment]
no one?

**Comment by socialpreneur** [comment]
@alihs Did you try this with the latest version? The one in the video is outdated. While I'm just a user, normally on desktop, scroll should trigger the script loads.

**Comment by alijiwani-srti** [comment]
No i didnot, will try and let you guys know

**Comment by GeekPress** [comment]
I'm closing this one as it should be fixed by #3142 or #3454
