### ISSUE TITLE
Purge OPCache option disappear from the top menu

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3428]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
The issue is reported for a site hosted with WP Engine so far.
When OPCache is enabled there is no _Purge OPCache_ option on the top WP Rocket menu. The host confirmed that OPCache is enabled.

WP Engine support provided these details:

> save_comments were disabled in PHP 7.3 for performance improvements. Due to this, any plugins that would require this being enabled, they need to update their coding to work around this change going forward with PHP 7.3 or higher on our platform.

**Expected behavior**
Purge OPCache option has to be available on the top WP Rocket menu when OPCache is enabled.

Related ticket: https://secure.helpscout.net/conversation/1366757469/223021
Slack convo: https://wp-media.slack.com/archives/C43T1AYMQ/p1608475042006700

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@NataliaDrause The `Purge OPCache` button is not mandatory as mentioned in our documentation - https://docs.wp-rocket.me/article/673-what-is-opcache

I see that @engahmeds3ed is on the case. I hope he can fill in on the details. Please advise if this is something we can improve, or simply a limitation.

**Comment by engahmeds3ed** [comment]
@arunbasillal 

I contacted WP Engine support team and they confirmed that `opcache_reset` function is one of disabled functions on their platform, 

and I asked them if there is any workaround or configurations they provide to make it active and they got a reply from one of their senior consultants that there is no way to enable it.

So I think we can't do anything here.

**Comment by arunbasillal** [comment]
Thanks Ahmed for the proactive effort! 🤘

@NataliaDrause Please note ^
OPCache rarely needs to be purged and it definitely do not have to be purged on a regular basis. Unless the customer faces issues (typically settings not saved when they save a WordPress or WP Rocket setting), we can advise them to not worry about it.

**Comment by NataliaDrause** [comment]
thank you all!
