### ISSUE TITLE
Issue with Polylang URL modifications options

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#343]
[https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/settings/](https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/settings/)

In URL modification options, when you select the option "The front page url contains the language code instead of the page name or page id". For example, the home URL will look like: http://www.example.com/en/ instead of http://www.example.com/home/. 

WP Rocket will clear the cache of http://www.example.com/en/ but not for http://www.example.com anymore.

**Comment by Tabrisrp** [comment]
Is EN the default language? what content is at the root?

**Comment by WordPresseur** [comment]
In this case, EN is the default language and the content at the root is the same.

**Comment by Tabrisrp** [comment]
Closed in favour of #531
