### ISSUE TITLE
In WP Rocket 3.8.0.1 the Perfmatters Lazyload script gets deferred when Defer JS is enabled, breaking its functionality

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3431]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before -  **Yes**

**Describe the bug**
In WP Rocket 3.8.0.1, the **Perfmatters Lazyload** script gets deferred when Defer JS is enabled, breaking their lazyload functionality. 

**To Reproduce**
1. Update to WP Rocket 3.8.0.1
2. Enable Permatters Lazyload, disable WP Rocket Lazyload.
3. Visit the website and see the console error: "**Lazyload is not defined**". the images won't load
4. Add exclusion: `/wp-content/plugins/perfmatters/js/lazyload.min.js`
5. Lazyload should be working as expected

**Expected behavior**
We should automatically exclude Perfmatters lazyload script from being deferred

**Screenshots**
https://jmp.sh/oGOEKUp

**Additional context**
Related ticket: 
https://secure.helpscout.net/conversation/1372699297/224831/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@alfonso100 It's a bit unclear from the ticket. But is this something new with 3.8? Or did the issue happen with <3.8 versions too? 

I believe L2 directly adds such exclusions with a PR, right?

**Comment by GeekPress** [comment]
I had a look at the Permatters website and they don't defer their lazyload file:
[screenshot](https://share.getcloudapp.com/bLugmO2J)

All other JS files are deferred, so I suppose it's voluntary to have excluded their lazyload file.

I'm going to contact them to have more info and to know if they can do the compatibility on their side.

**Comment by GeekPress** [comment]
FYI, I have just contacted Brian Jackson about this problem.

**Comment by brianleejackson** [comment]
Hey guys!
Thanks for roping me in. We did some testing today and can see that it appears to have changed with WP Rocket 3.8+. We now have a fix in place on dev, and it will get pushed out in the next update of Perfmatters.

Thanks

**Comment by GeekPress** [comment]
Thanks @brianleejackson for the confirmation and the fix on your side. I'm going to let our team know about the coming update.
