### ISSUE TITLE
Apply missing image dimensions for images with a relative path

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3438]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Images added with a relative path don't have image dimensions applied.

**To Reproduce**
1. Activate _Add Missing Image Dimensions_ option in the Media tab
2. Add image with a markup like this: `<img src="/wp-content/uploads/2020/12/photo-123.jpg">`
3. The dimensions are not applied:
![image](https://user-images.githubusercontent.com/60236665/103013923-3d14e300-453e-11eb-92a9-2353dd5e9b77.png)
Full-screen image: https://jmp.sh/RNI1CNa

**Expected behavior**
Image dimensions have to be applied for images with a relative path.

**Additional context**
Debug log: https://jmp.sh/XfT839x
Specify Image Dimensions failed because the internal image is not found.

Slack discussion: https://wp-media.slack.com/archives/C43T1AYMQ/p1608732263037200

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jorgemartine00** [comment]
**Related:** https://secure.helpscout.net/conversation/1372364607/224681/

**Comment by jazir555** [comment]
Considering there are multiple issues open that are relative path based, you may want to consider revising the way wp-rocket deals with relative paths in general to solve all the issues at once.
