### ISSUE TITLE
Guard stats API against too many failures that results in flooding server with requests

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3440]
**Is your feature request related to a problem? Please describe.**
We noticed that the pricing API when returns status code other than `200`, it will try to get the pricing details with each time the administrator opens any admin page.

**Technically:**
It's bailing out here:
https://github.com/wp-media/wp-rocket/blob/55e722d07a857fea52eed9f186ed93231d23d24e/inc/Engine/License/API/PricingClient.php#L48

that is called here
https://github.com/wp-media/wp-rocket/blob/55e722d07a857fea52eed9f186ed93231d23d24e/inc/Engine/License/API/PricingClient.php#L24

so it will bailout also here:
https://github.com/wp-media/wp-rocket/blob/55e722d07a857fea52eed9f186ed93231d23d24e/inc/Engine/License/API/PricingClient.php#L27

without setting the transient `wp_rocket_pricing`.
and this mainly called here:
https://github.com/wp-media/wp-rocket/blob/5dd3fa10d54a6619aeefa1589e270e715ce6925c/inc/Engine/License/ServiceProvider.php#L47

that is called only on admin as in here:
https://github.com/wp-media/wp-rocket/blob/aef2714666ac9fc20eac8a1759feffe3a30885da/inc/Plugin.php#L163

**Describe the solution you'd like**
As @hellofromtonya mentioned we need to find a way to guard hitting the API after failure and I would suggest that each time we find a failure we can increase a transient with time interval so we need to wait this time till sending the request again for example:

hit the API first time `=>` status != 200 `=>` set transient time with timenow + 5 minutes
hit the API again after this 5 minutes `=>` status != 200 `=>` increase transient value with 10 minutes
over and over, and only remove this transient when success.
This will help not to hit the API once it's live from all of our sites.

**Additional Context**
I think also user data has the same behavior that needs to be adjusted also:

https://github.com/wp-media/wp-rocket/blob/55e722d07a857fea52eed9f186ed93231d23d24e/inc/Engine/License/API/UserClient.php#L75-L77

**Comment by iCaspar** [comment]
Per @engahmeds3ed 's OP, failure to set the `wp_rocket_pricing` transient (by getting a valid response from the pricing API), causes a new attempt with each admin page load.
The proposed solution, means setting a `wp_rocket_pricing_timeout` transient on failure, which is checked in `PricingClient::get_raw_pricing_data()` before the API call.
Pseudo-code:
```
if (pricing_timeout) {
    return false;
} else {
    wp_safe_remote_get(API_Endpoint);

    if (200 response) {
        clear_pricing_timeout;
        return response;
    } else {
       set_or_double(pricing_timeout);
       //first set @ 5 min, double up to 24hr max.
    }
}
```
`set_or_double` probably is best as a new private method.

Update integration tests with fixture/testcase for checking the presence/content of `rocket_pricing_timeout` transient.

Effort:
[S]
