### ISSUE TITLE
Incorrect directory detection on Azure servers prevents cache files from being created

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3443]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version YES
- Used the search feature to ensure that the bug hasn’t been reported before YES

**Describe the bug**
A customer on an Azure server, reported the following: 
> If a parent folder does not exist in the cache directory, and the PHP function is_dir() reports that it does exist, then cache files for child folders will not be created

**To Reproduce**
1. On Azure server, PHP 7.4
2. Force` is_dir()` to return a parent folder as existent, when in reality the folder doesn't exist.
3. Cache files are not created
3. Apply the proposed changes in **advanced-cache.php** and **files.php**
4. See cache files created as expected

**Expected behavior**
The folder should be detected correctly in windows servers to avoid this kind of issue. @engahmeds3ed confirmed that 
> In Windows there is a difference between 'file' and 'folder' types, so need to use `file_exists()` and `is_dir()` at the same time.

**Additional context**
I have confirmed the cache files are being created as expected after they have applied their proposed fix. 
This is the full report from the customer: 

> I discovered that one line of code was actually reporting that directories were there when in fact they were not. To make matters worse, it worked properly sometimes as well. When that one php function reported incorrectly, the entire cache building process could fail.
> 
> Here is a scenario to help explain..
> 
> If we are trying to write the file /cache/wp-rocket/mysite/news/blurb1 the code may fail and will then check to see if /cache/wp-rocket/mysite/news/ exists. If it doesn't exist, the code will attempt to create that folder. If the code fails to create /cache/wp-rocket/mysite/news/ then it will check to see if /cache/wp-rocket/mysite/ exists. That process continues...
> 
> Now, if the code reports that /cache/wp-rocket/mysite/news/ exists when in fact that it doesn't, then things start falling apart.
> So... There are two changes to WP Rocket code that I made.

> 1 - The wp-content/advanced-cache.php file is autogenerated by WP Rocket. I changed from: 
```
$rocket_path = 'D:\home\site\wwwroot\wp-content\plugins\wp-rocket/';
$rocket_config_path = 'D:\home\site\wwwroot/wp-content/wp-rocket-config/';
$rocket_cache_path = 'D:\home\site\wwwroot/wp-content/cache/wp-rocket/';
```
> to
```
$rocket_path = '/home/site/wwwroot/wp-content/plugins/wp-rocket/';
$rocket_config_path = '/home/site/wwwroot/wp-content/wp-rocket-config/';
$rocket_cache_path = '/home/site/wwwroot/wp-content/cache/wp-rocket/';
```

> 2 - In the /wp-content/plugins/wp-rocket/inc/functions/files.php I changed line ~1114 from:

```
} elseif ( rocket_direct_filesystem()->is_dir( dirname( $target ) ) ) {
````
> to
```
} elseif ( rocket_direct_filesystem()->exists( dirname( $target ) ) && rocket_direct_filesystem()->is_dir( dirname( $target ) ) ) {
```

Related ticket: https://secure.helpscout.net/conversation/1365459686/222734?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
