### ISSUE TITLE
Query string version of the homepage is not cleared with rocket_clean_home

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3444]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When `rocket_clean_home` is triggered, the cache of the query string is not removed.

**To Reproduce**
1. Add a query string to cache in the settings
2. Cache the homepage with query string `domain.com/?test=123`
3. Make sure that it's cached on the SFTP
4. Update any post to trigger the `rocket_clean_home`
5. Confirm on SFTP that the homepage is cleared but the `#test=123` is not

**Expected behavior**
We should clear also the query strings versions, including the cache and ignored query strings. Probably just looking for directories starting with `#` in the root cache directory and passing them to `rrmdir` will be fine.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Seems to be the same ones:
https://github.com/wp-media/wp-rocket/issues/2983

**Comment by CrochetFeve0251** [comment]
### Reproduce the issue 
I  was able to reproduce the issue.

### Root of the problem
We are not checking for folders starting with the # character when clearing the cache inside `rocket_clean_home`.

### Scope a solution
We need to add a check for `#` starting folders in `rocket_clean_home` and delete them if they exist.
For that we can add this code to the `rocket_clean_home` method:
```php
$param_dirs = glob( $root . '/#*'  );

	if ( $param_dirs ) {
		foreach ( $param_dirs as $dir ) {
			rocket_rrmdir( $dir );
		}
	}
``` 

### Estimate effort
`XS`
