### ISSUE TITLE
Cache on Cloudflare is not cleared if "cache everything" is set using Workers

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3448]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When cache everything is set using Workers instead of page rules, WP Rocket cache clearing won't trigger cache clear on Cloudfare as well. 

**To Reproduce**
1. Enable our Cloudflare add-on.
2. Enable Cache Everything using a Worker.
3. Clear our cache.
4. Check if cache is cleared on the page's header.

**Expected behavior**
Cache getting cleared even if the cache everything is deployed using Workers. 

**Screenshots**
Page is still delivered from Cloudflare's cache with aging `age` header.
![](https://i.vgy.me/W8FY8s.png)

**Additional context**
The following line checks the presence of Cache Everything on Cloudflare. 
https://github.com/wp-media/wp-rocket/blob/443f2e1b902c592bd517cbaa641571bb2ddce1a5/inc/Addon/Cloudflare/Subscriber.php#L154
We can maybe wrap it inside a conditional statement to check for a constant that can be added to the wp-config.php file. 

Something like: 

On the wp-config.php file:
`define('WP_ROCKET_CF_CACHE_EVERYTING_WORKER', true);`

Remplace the line - https://github.com/wp-media/wp-rocket/blob/443f2e1b902c592bd517cbaa641571bb2ddce1a5/inc/Addon/Cloudflare/Subscriber.php#L154 - with:

```
if (defined('WP_ROCKET_CF_CACHE_EVERYTING_WORKER')) {
  $cf_cache_everything = true;  
} else {  
  $cf_cache_everything = $this->cloudflare->has_page_rule( 'cache_everything' );  
}
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1377963805/226368/

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
