### ISSUE TITLE
rocket_need_api_key() - PHP Fatal error during license validation

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3449]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

A PHP fatal error is thrown when the `$errors` is not an array/countable type, e.g. it's a `false` here:
https://github.com/wp-media/wp-rocket/blob/3f4de3116cbd9c97f1ac5bff0002f31587353d1d/inc/functions/admin.php#L23

Here is the log:
```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, bool given in /home/example.com/wp-content/plugins/wp-rocket/inc/functions/admin.php:23
Stack trace:
#0 /home/example.com/wp-includes/class-wp-hook.php(287): rocket_need_api_key('')
#1 /home/example.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/example.com/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/example.com/wp-admin/admin-header.php(292): do_action('admin_notices')
#4 /home/example.com/wp-admin/admin.php(239): require_once('/home/gunacom/p...')
#5 /home/example.com/wp-admin/options-general.php(10): require_once('/home/gunacom/p...')
#6 {main}
  thrown in /home/example.com/wp-content/plugins/wp-rocket/inc/functions/admin.php on line 23
```

**To Reproduce**
1. Enable WordPress's debugging.
2. Go to `/inc/functions/admin.php` and hardcode `$errors` to `false` in line 11.
3. .Visit WP Rocket's dashboard.
4. Check the `debug.log`.

**Expected behavior**

No fatal error should take place even when the `get_transient()` returns a boolean.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1367704657/223307/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the problem**
Recreate it on my local computer

**Identify the root cause**
@vmanthos identified the exact error which cause this.

**Scope a solution**
The solution is to revisit the code and in case `$errors  = get_transient( 'rocket_check_key_errors' );` returns false to init $errors as [];
Probably the code will look something like this:
```
        if ( ! is_array( $errors ) ) {
		$errors = [];
	}
	foreach ( $errors as $error ) {
		$message .= '<p>' . $error . '</p>';
	}
```

**Estimate the effort**
[S] - Will need both Unit and Integration tests

**Comment by vmanthos** [comment]
From #2661, which is a duplicate.

**Related tickets:**
https://secure.helpscout.net/conversation/1162149079/164529/
https://secure.helpscout.net/conversation/1163650645/164898/
https://secure.helpscout.net/conversation/1423906536/238966/

And a new one: https://secure.helpscout.net/conversation/1457208727/248660/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1460702868/249713/
