### ISSUE TITLE
Feature Request: new hooks.

### ISSUE THREAD

**Issue by NizarBlond** [wp-media/wp-rocket#345]
Hi,

I need a 2 hooks, to be invoked before and after the static HTML files are compiled and written to the /wp-content/cache folder.

Is it possible to have them?

Reason being, syncing between caching folders of the same site on various servers (load balancer and multi-servers). Also, for statistical reports we do at our company on the frequencies of caching.

Cheers

**Comment by arunbasillal** [comment]
@Tabrisrp Are there any current filters / hooks that could be used to identify when files are written? WordPress is loaded when we write, so maybe there is another one that could be used to identify this rather than having a dedicated one?

**Comment by Tabrisrp** [comment]
There isn't any existing ones. We _could_ add filters before/after writing the cache HTML file if we want to.

**Comment by GeekPress** [comment]
Let's close it for now as the request has been initiated 3 years ago and nobody else requested it.
