### ISSUE TITLE
Missing Image Dimensions are not being applied on Multisite

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3453]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before -yes

**Describe the bug**
Missing Image Dimensions are not being applied for images on Multisite.

**To Reproduce**

1. Created a post with the image markup:
```
<figure>
<img src="http://my.site.com/multisite/green/wp-content/uploads/sites/4/2020/12/photo-1.jpg" alt="my alt">
<img src="http://my.site.com/multisite/wp-content/uploads/2020/12/photo-2.jpg" alt="another alt">
</figure>
```
2. Enabled **Add Missing Image Dimensions** option. Check the site - the dimensions are not applied.
3. Added filter for including external images to functions.php:
`add_filter( 'rocket_specify_image_dimensions_for_distant', '__return_true' );`
4. Check the site - the dimensions are not applied.

**Expected behavior**
Image dimensions have to be applied.

**Additional context**
WP Rocket debug log:
_Specify Image Dimensions failed because internal image is not found._
Screenshot: https://jmp.sh/KZZb1xD

Related ticket: https://secure.helpscout.net/conversation/1375704680/225688/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
**Can Reproduce:**
On Multi-site, there are 4 possibilities to check:
Subdomain type multisite --
1. Main domain site (`mysite.com`)
2. Subdomain site (`site1.mysite.com`)
Subdirectory type multisite --
3. Main domain site (`mysite.com/blog/...`)
4. Subdomain site (`mysite.com/site1/...`)

Given WP Rocket Network Activated, and the `rocket_specifiy_image_dimensions_for_distant` filter `true` -- I found the following behaviors.

For the Subdomain types:
1. On `http://rocketmultisubdomain.local/2021/01/11/image-dimensions-test-page/` we have
```
<figure>
<img src="http://site1.rocketmultisubdomain.local/wp-content/uploads/sites/2/2021/01/hippo_birdie_card.jpg" alt="hippo birdie">
<img width="350" height="266" src="http://rocketmultisubdomain.local/wp-content/uploads/2021/01/backyardview2.jpg" alt="back yard view">
</figure>
```
(Dimensions added for main domain image, but not subdomain image.)

2. On `http://site1.rocketmultisubdomain.local/image-dimensions-test-page/` we have:
```
<figure>
<img width="512" height="512" src="http://site1.rocketmultisubdomain.local/wp-content/uploads/sites/2/2021/01/hippo_birdie_card.jpg" alt="hippo birdie">
<img width="350" height="266" src="http://rocketmultisubdomain.local/wp-content/uploads/2021/01/backyardview2.jpg" alt="back yard view">
</figure>
```
(Dimensions added for both images.)

For the Subdirectory types for both:
3. On `http://rocketmultisubdir.local/blog/2021/01/11/image-dimensions-test-page/` and
4. On `http://rocketmultisubdir.local/site1/2021/01/11/image-dimensions-test-page/` we have:
```
<figure>
<img src="http://rocketmultisubdir.local/site1/wp-content/uploads/sites/2/2021/01/hippo_birdie_card.jpg" alt="hippo birdie">
<img width="350" height="266" src="http://rocketmultisubdir.local/wp-content/uploads/2021/01/backyardview2.jpg" alt="back yard view">
</figure>
```
(Dimensions added only for main site image.)

**Comment by piotrbak** [comment]
Not sure if that changes anything, but we should also cover the relative paths here.

**Comment by piotrbak** [comment]
I've just tested this once again. After this patch https://github.com/wp-media/wp-rocket/pull/3493 only the 1st scenario fails

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
