### ISSUE TITLE
Delay JS is not working if scrolling the page with the mouse wheel

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#3454]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
Delay JS is not working when scrolling the page using **only** the mouse wheel.

**To Reproduce**
1. Enable Delay JS execution.
2. Scroll the page using the mouse wheel, making sure the mouse does not move.
3. You’ll see Delay JS does not work.

**Expected behavior**
Delay JS should work when scrolling the page with the mouse using its wheel, even if the mouse is not moved at all.

**Screencast**
https://jmp.sh/y2VW7f5

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1376120950/225831?folderId=3051575
Slack Thread: https://wp-media.slack.com/archives/C08N8J6VC/p1609175796001900

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by socialpreneur** [comment]
Two finger scroll also doesn't trigger the load, so the best is to follow Flying Scripts idea to auto load after x seconds, where x can be defined by user.

**Comment by seriusokhatsky** [comment]
+1

**Comment by engahmeds3ed** [comment]
@wp-media/productrocket 

I think the decision here is related to the following comment:
https://github.com/wp-media/wp-rocket/issues/3142#issuecomment-754893929

also for this issue specifically, we can add scroll event to our list here:
https://github.com/wp-media/wp-rocket/blob/098403382744fe6e7adfd4a8c795c2cc93e3fa4d/assets/js/lazyload-scripts.js#L97-L100

waiting for your feedback to continue grooming.

**Comment by arunbasillal** [comment]
@engahmeds3ed If we add the scroll event to our list of events, this specific issue will be taken care of, right? If so, let's proceed with it. 

Not sure how it is related to #3142. Can't these be handled separately?

**Comment by GeekPress** [comment]
@engahmeds3ed What are your feedbacks about the last Arun response 👆

**Comment by jazir555** [comment]
Seriously? This is how I primarily browse, I *never* use the arrow keys. To me this is a severe bug, not medium priority.

**Comment by engahmeds3ed** [comment]
@GeekPress sorry for missing this question!
yes for this issue if we added the scroll event to list of events it will solve the issue.

I think it's related to adding timeout beside those events so if we missed any event, the timeout will work on this case.

**Comment by engahmeds3ed** [comment]
@jazir5 Don't worry, it's an edge case when u scroll using the scroll wheel without changing the mouse position so don't worry, we will handle this also.

**Comment by Garnet-Fox** [comment]
What about [3142](https://github.com/wp-media/wp-rocket/issues/3142)?
Apple will never fix this problem, as this is not a bug, it is a feature.
Can even put a trigger on the immediate execution of deferred scripts. Who wants to start it with setTimeOut, or trigger on the wheel, or if you need immediate loading from a third-party non-deferred script, launch the trigger, load delayed scripts?

**Comment by GeekPress** [comment]
@wp-media/dev This issue seems to be ready for grooming.

@Mai-Saad @piotrbak Can I let you set the severity label?

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
Yes I saw the issue on client's site and reproduced it locally.

**Identify the root cause**
when scrolling using mouse wheel but the mouse itself isn't moved from its place on the screen so mouse events are not triggered so delayed scripts are not triggered with wheel.

**Scope a solution**
https://github.com/wp-media/wp-rocket/blob/098403382744fe6e7adfd4a8c795c2cc93e3fa4d/assets/js/lazyload-scripts.js#L97-L100
we need to add JS event `wheel` instead of scroll as after doing some search about that I found that if the page doesn't have scroll bars the `scroll` event won't be triggered, so using `wheel` will be safer.

**Estimate the effort**

[XS]
