### ISSUE TITLE
NextGEN Gallery UI breaks with WP Rocket

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3456]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When WP Rocket is used alongside [NextGen Gallery](https://wordpress.org/plugins/nextgen-gallery/) their UI breaks.
It should be like this:
![](https://i.vgy.me/BSHFQg.png)

Instead, it's like this:
![](https://i.vgy.me/3PzrSl.png)

The error is related to our compatibility code. Since `3.3.1` we are disabling NGG's resource manager:
https://github.com/wp-media/wp-rocket/blob/3f4de3116cbd9c97f1ac5bff0002f31587353d1d/inc/classes/subscriber/third-party/plugins/class-ngg-subscriber.php#L29

Here is the part of our changelog related to this change:
> Third Party Compatibility: Disable NGG resource manager to prevent conflict with JS minification/combine

Unhooking the `deactivate_resource_manager` method from `run_ngg_resource_manager` resolves the issue.

**To Reproduce**

1. Install [NextGen Gallery](https://wordpress.org/plugins/nextgen-gallery/)
2. Create a new post, and add a NextGen Gallery:
![](https://i.vgy.me/HoqaZv.gif)
3. Click the **UPLOAD IMAGES** tab.
4. See the error,

**Expected behavior**

NextGen Gallery should work with WP Rocket.

**Additional context**

We should check whether the specific compatibility isn't necessary anymore.

**Related ticket:** https://secure.helpscout.net/conversation/1373096881/224963?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by gracevillarino** [comment]
Hello. Do we have any update on this? Or a workaround without having to deactivate WP rocket?
We have other sites that are using both WP rocket and Nextgen that is affected by this issue.
Thank you.

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
We are deactivating the resources manager all the time, instead of only on the front end.

### Scope a solution ✅ 
Add a `is_admin()` check to the `deactivate_resource_manager()` method, to only return false if we are on the front end.

Also, move the class to the new architecture.

### Estimate the effort ✅
Effort `[XS]`
