### ISSUE TITLE
Page microcache (allows for dynamic pages to use microcaching + ajax for stale-less experience)

### ISSUE THREAD

**Issue by partounian** [wp-media/wp-rocket#3462]
**Is your feature request related to a problem? Please describe.**

I'm frustrated that my client uses WHM & Apache. He is using WP Rocket, which is the best plugin for caching and general performance, but sadly because he uses live data for sporting events, WP Rocket isn't as helpful as it can be.

**Describe the solution you'd like**

An option to set a page cache for x amount of time (default 30s) for a set of pages.

**Describe alternatives you've considered**

Installing Nginx.

**Additional context**

**Comment by arunbasillal** [comment]
Hello @partounian 

Thanks for the request. But to be short, I don't believe this is the direction we want WP Rocket to head towards. In fact, we removed the option to set cache lifespan in minutes (https://github.com/wp-media/wp-rocket/issues/3267) and the minimum now is 1 hour. 

For similar use cases, why not stick to populating the "live" data with AJAX?
