### ISSUE TITLE
Disabling lazyload for the first screen

### ISSUE THREAD

**Issue by serg-pervushin** [wp-media/wp-rocket#3466]
Hello.

I'm not sure if such a request has already been made, but the LCP is greatly increased when enable lazyload for images. Don't need to delay loading images on the first screen, and if it's just one image, can add it to the exceptions, but it can be a news portal with a lot of images and we can't add all of them to the exception. Need to somehow automatically exclude all images from lazyload for the first screen.

**Comment by GeekPress** [comment]
Hi @serg-pervushin 

There is no easy way to detect all above the fold images with PHP. The actual solution will be to let you exclude X images. But the problem with that it's not totally accurate. Most of the time, you don't need to exclude the same number of images on mobile than desktop. 

This is why we introduced the exclusion field for lazyload. I suggest you to exclude yours above the fold images with that.

On our side, we are thinking about some ideas to try to automatically exclude some images like the logo.
