### ISSUE TITLE
Delayed Scripts are not Loading in AMP

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#3467]
The delayed Javascript files are not being called on AMP when using the Transitional template mode. Several other incompatible scripts are also being reported as errors in the official AMP plugin. Is it an overall AMP compatibility issue? If so, are you working on it? Any updates?

**Comment by arunbasillal** [comment]
Hello @MuhammedSwalihct 

We do have an issue for the same #3450 which we hope to resolve sooner rather than later. Please refer that issue and add comments if any. Thanks.
