### ISSUE TITLE
Exclude application/ld+json inline scripts from DeferJS

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3470]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
We need to exclude `application/ld+json` from being deferred as this inline JS has json contents and on some edge cases it contains the keyword `jQuery` so it's enclosed between our
```
window.addEventListener('DOMContentLoaded', function(){
HERE
});
```
and this isn't valid.

**To Reproduce**
1. Create page template which has the following script
```
<script type="application/ld+json">
{"text": "Technology &amp; Services. xhtml. SEO campaign. Javascript &ndash; Jquery &amp; Mootols Library&rsquo;s."}
</script>
```
2. Enable DeferJS
3. Check the optimized page source.

**Expected behavior**
This json shouldn't be enclosed between `DOMContentLoaded` event.

**Additional context**
@GeekPress Commented on that issue with the following message:
> it seems to be an edge case. But to be sure it won’t happen again, we should exclude application/ld+json inline scripts. It’s safe as it won’t contains any executed code.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
As Ahmed said, we are not excluding this type of inline JS right now, so in some edge cases it can happen if there is matching keywords.

### Scope a solution ✅ 
Add a check for `application/ld+json` in `DeferJS::defer_js()`, to skip those scripts from the process.

### Estimate the effort ✅
Effort `[XS]`

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1405765532/234099?folderId=377611
I cannot find jquery used in the script on the page, but the description of the issue is the same as above.

**Comment by matzeeable** [comment]
When not using linked data, should `<script type="application/json">` also be excluded?
