### ISSUE TITLE
Enable brotlin and other htaccess tweaks

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [wp-media/wp-rocket#3475]
`<ifModule mod_headers.c>
	Header set Connection keep-alive
</ifModule>
<IfModule mod_headers.c>
	Header set X-XSS-Protection "1; mode=block"
	Header always append X-Frame-Options SAMEORIGIN
	Header set X-Content-Type-Options nosniff
	Header always set Referrer-Policy "no-referrer, strict-origin-when-cross-origin"
</IfModule>
<IfModule mod_brotli.c>
	#BrotliCompressionQuality 6
	AddOutputFilterByType BROTLI_COMPRESS application/atom+xml \
		                          application/javascript \
		                          application/json \
		                          application/rss+xml \
		                          application/vnd.ms-fontobject \
		                          application/x-font-ttf \
		                          application/xhtml+xml \
		                          application/xml \
		                          font/opentype \
		                          image/svg+xml \
		                          image/x-icon \
		                          text/css \
		                          text/html \
		                          text/plain \
		                          text/x-component \
		                          text/xml
</IfModule>
`

**Comment by arunbasillal** [comment]
@Tabrisrp Could you please take a look to see if any of this is something we can or should add to our .htaccess config? 🙏

**Comment by remyperona** [comment]
The first part are security headers, which are out of our scope.
The second part is for brotli, for which we already have an issue for #1524
