### ISSUE TITLE
Optimize static images

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [wp-media/wp-rocket#3476]
Static images can be slightly reduced if you use an image optimization tool such as FileOptimizer (https://sourceforge.net/projects/nikkhokkho/files/FileOptimizer/)

**Comment by arunbasillal** [comment]
Hello @javiergutierrezchamorro I suppose you are suggesting to add this to WP Rocket? 

We already have a plugin named Imagify (https://imagify.io/) that is recommended for use and is part of the Image Optimization tab of WP Rocket. So it's unlikely that we will add another tool. 

Thanks for the suggestion regardless. Best regards.

**Comment by javiergutierrezchamorro** [comment]
@arunbasillal I meaning statically optimizing the images that come with the plugin.

![image](https://user-images.githubusercontent.com/4672971/104309270-2c6ae380-54d2-11eb-88f4-a80d2ad08aa3.png)

**Comment by arunbasillal** [comment]
Thanks for the clarification @javiergutierrezchamorro 
These images only appear on WP Rocket backend, right? We will be reworking the UI and will change these up. Thanks for the heads up.
