### ISSUE TITLE
Multisite - Cache Query String(s) & other features not working on subsites

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3477]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

**Cache Query String(s)**, as well as any other option we save in the configuration file in `/wp-content/wp-rocket-config/` will not work on multisite.

Changes made on a subsite will be written in the subsite-specific configuration file, e.g. `example.com.subsite.php`.

However, the configuration file that we are using is that of the main site:
https://github.com/wp-media/wp-rocket/blob/df26acdfbe015d056fc442cfbf28734f9635aa9f/inc/classes/Buffer/class-tests.php#L192

which doesn't have the changes applied to the subsite.

**To Reproduce**
1. Go to MEGA/Multisite.
2. On a subsite add a query string in the **Cache Query String(s)** text area in the **Advanced Rules** tab.
3. Visit a URL after appending the query string from step 2.
4. Check the source code of the page. It won't be cached/optimized.

**Expected behavior**

The features should work when they are set up on subsites.

**Additional context**

A workaround is to use the main site's advanced rules tab to add the query strings that need to be cached.
However, this can be problematic if the specific behavior is only needed on subsites.

**Related ticket:** https://secure.helpscout.net/conversation/1393512095/230531?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@vmanthos @arunbasillal This is related to https://github.com/wp-media/wp-rocket/issues/1424

Since your issue is using the template, I guess we can close the above one.

**Comment by arunbasillal** [comment]
Notes from #1424 

> When WP Rocket is active on the main site (main network site), exclude pages from being cached feature is not working on subsites (excluded pages are being cached).

> After deactivating WP-Rocket from the main site, everything is working fine on each subsite.

> This is related to below ticket:
https://secure.helpscout.net/conversation/716301944/87882?folderId=2415573#thread-2009772070

> Made some further tests. Blogs are fetching the content of the main site WP Rocket config file instead of their own.

> Thanks to Alfonso we have our own Multisite environment where I was able to recreate the problem.

> Related ticket:
https://secure.helpscout.net/conversation/845943447/106761?folderId=2415573

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1404974285/233809/

**Comment by jorgemartine00** [comment]
Related ticket previously added in duplicate issue https://secure.helpscout.net/conversation/1285218548/

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1815232543/331474

**Comment by piotrbak** [comment]
The issue seems to be still there. Affecting and blocking https://github.com/wp-media/wp-rocket/issues/5207.
