### ISSUE TITLE
GeneratePress Premium + WooCommerce + Optimize CSS Delivery issue

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3494]
**Describe the bug**
With the above combination, the shop and product category pages do not display correctly on mobile devices using Chrome. 
Products are displayed in 4 columns instead of the number defined by the customer (usually 1 or 2). 

**To Reproduce**
Can be reproduced on Mega. Steps to reproduce the behavior:

- Activate GeneratePress theme 
- Activate GP Premium plugin
- Activate WooCommerce plugin
- Make sure WooCommerce module in GP Premium is activated
- In WPR, activate Optimize CSS Delivery and mobile cache
- Visit: http://mega.wp-rocket.me/product-category/clothing and http://mega.wp-rocket.me/shop in Chrome, mobile view
- Note that there are 4 columns instead of a single column: https://jmp.sh/qYgvc82

**Expected behavior**
Products should be displayed in one column: https://jmp.sh/GtxU8i1

**Additional info**
We can resolve the issue by excluding both these files from Optimize CSS Delivery
 /wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css
/wp-content/plugins/gp-premium/woocommerce/functions/css/woocommerce-mobile.min.css

Related tickets
- https://secure.helpscout.net/conversation/1312822453/203478/
- https://secure.helpscout.net/conversation/1321375373/206127/
- https://secure.helpscout.net/conversation/1331009370/209769/
- https://secure.helpscout.net/conversation/1391282903/229930/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
