### ISSUE TITLE
Add _gl to ignored querystrings (Google Stories)

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#3503]
One user recommended adding _gl to the ignored querystrings.

I have been checking, and it seems that Google WebStories is being used by more and more clients.

**Comment by sandyfzu** [comment]
Case: https://secure.helpscout.net/conversation/1392983874/230411/

**Comment by DahmaniAdame** [comment]
Might require some testing as the _gl parameter is used to record the customer's journey (by adding the source).

https://developers.google.com/gtagjs/devguide/linker

**Comment by arunbasillal** [comment]
>Might require some testing as the _gl parameter is used to record the customer's journey (by adding the source).

@DahmaniAdame Can you please explain what testing is needed here? Even if they add source, will ignoring this query string (and caching pages) make any difference do you think?

**Comment by DahmaniAdame** [comment]
@arunbasillal you are right. It should be safe since their JS file should be able to collect data. 
Maybe we can extend that to other trackers with query strings? https://maxchadwick.xyz/tracking-query-params-registry/

**Comment by arunbasillal** [comment]
> Maybe we can extend that to other trackers with query strings? https://maxchadwick.xyz/tracking-query-params-registry/

@DahmaniAdame That is a pretty good collection. @GeekPress For your consideration please.

**Comment by GeekPress** [comment]
@arunbasillal @DahmaniAdame Yes, we can include all missing query parameters from the list shared by Adame.

@Tabrisrp Can we ask to a level 2 to directly make the PR with the new patterns?

**Comment by vmanthos** [comment]
@GeekPress I've asked the tech team to tackle this.
We'll handle this very soon.
