### ISSUE TITLE
Not permisive enough

### ISSUE THREAD

**Issue by MadMaxInfinity** [wp-media/wp-rocket#3509]
https://github.com/wp-media/wp-rocket/blob/df26acdfbe015d056fc442cfbf28734f9635aa9f/inc/Dependencies/RocketLazyload/Image.php#L65
If I make no mistake, this regexp is ending with `\))\s*;?` but this way no background-images having fallback values or `!important` directive are not matched. Moreover this doesn’t take into account multiple images background.
Samples [can be found here](https://css-tricks.com/almanac/properties/b/background-image/#setting-a-fallback-color).

Maybe something like `'#background-image\s*:\s*(?<attr>\s*url\s*\((?<url>[^)]+)\))[^;]*;?#is'` could do?
( Replaced ending `\s*;?` with `[^;]*;?` )

_Just something I found while searching why my SVG background was not loaded in CDN and check if it aws related to lazyloading..._

**Comment by iCaspar** [comment]
Thanks @MadMaxInfinity. Copying this to related issue, #2588, where this regex is being discussed.
