### ISSUE TITLE
Update LazyLoad script to the latest version

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#3510]
Request made by the customer for updating LazyLoad script from version 16.1 to the latest version 17.3. There are some improvements made and the script is also 500 bytes lighter now.

**Comment by engahmeds3ed** [comment]
**Scope a solution**
1. Download the latest 17.3 version from here: https://github.com/verlok/vanilla-lazyload/releases/tag/17.3.0
2. Put the minified and not minified JS files into directory: `assets/js/lazyload/17.3`
3. Change version number here to `17.3`
https://github.com/wp-media/wp-rocket/blob/484263349028b50fc1c87891e1912d49102c2e36/inc/Engine/Media/Lazyload/Subscriber.php#L18

4. Adjust tests to change `16.1` to `17.3`

**Estimate the effort**
[XS]

**Comment by Presskopp** [comment]
just to mention 17.3.1 is the current version

https://github.com/verlok/vanilla-lazyload/releases/tag/17.3.1

**Comment by iCaspar** [comment]
Adding Priority high here, as this is linked to the acceptance criteria now for #3604

**Comment by Presskopp** [comment]
meanwhile we're on v17.5
