### ISSUE TITLE
Critical CSS for web-story not generated. Error: No valid stylesheets available

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3513]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Critical CSS for web-story not generated. Error: No valid stylesheets available

**To Reproduce**
1. Login to QAlabs "https://rocketlabsqa.dev/wp-admin/options-general.php?page=wprocket#dashboard"
2. Open WP Rocket Settings -> File optimization
3.  enable "Optimize CSS delivery" and press "Save changes"
4. Refresh till CSS generation is done 
5. Critical CSS for web-story not generated. Error: No valid stylesheets available

**Expected behavior**
Exclude web-story from critical CSS generation

**Screenshots**
![CriticalCSSGeneration](https://user-images.githubusercontent.com/76941962/105320802-48a40a00-5bcf-11eb-99ba-c7b63696abb9.png)

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by arunbasillal** [comment]
@Mai-Saad Thanks for the report. I changed the `type` from bug to enhancement. Why? We never designed CPCSS to exclude `web-stories` and it doesn't cause issues on customer websites (if I am not mistaken). Hopefully we will discuss these and more in the meeting we have today 👍

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
This CPT is not excluded from our generation currently

### Scope a solution ✅ 
Add `web-story` to our exclusion array `rocket_cpcss_excluded_post_types`

### Estimate the effort ✅
Effort `[XS]`
