### ISSUE TITLE
WP Rocket optimizations and cache is not working on WPML using different domain per language

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3516]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Adding new domains on the WPML multi-domain setup doesn't regenerate our wp-rocket-config files, leading to our optimizations/cache not getting processed. 
The issue is fixed by deactivating/activating WP Rocket.

**To Reproduce**
1. Enable WPML using different domain per language
2. Activate WP Rocket
3. Add new domains
4. Our optimization and cache are not working

**Expected behavior**
Add new config files for new domains when added to WPML without requiring to deactivate/activateWP Rocket.

**Screenshots**
![Missing config file](https://i.vgy.me/kbwAgg.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.

**Comment by sarsevanidze** [comment]
Hello,

I’m encountering an issue with WP Rocket’s caching when using WPML with the “Different Domain per Language” setting.


Languages:

English → example.com

German → example.de

Preload Cache: Enabled

Issue:
WP Rocket is successfully generating cache for the main domain (example.com) but not for the secondary domain (example.de). When browsing the .de site, no cache files are created, and the pages remain uncached.

What I’ve tried:

Cleared and preloaded the cache from the admin panel

Manually visited .de pages to trigger caching

Deactivated and reactivated WP Rocket

Verified WPML domain mapping and DNS setup

Checked file and folder permissions

Despite this, WP Rocket only creates cached files for the .com domain.

Could you please advise how to enable caching and preloading for all language domains in this WPML configuration?
If any additional debugging or logs are needed, I can provide them.

Thank you for your help!

**Comment by DahmaniAdame** [comment]
@sarsevanidze if deactivating/activating didn't solve it, then it's not related to this specific issue. 
It might be related to this one - https://github.com/wp-media/wp-rocket/issues/7500
Would you mind opening a ticket for further investigation?
