### ISSUE TITLE
Enfold theme prevents CPCSS from being injects

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3518]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Enfold is enabled, CPCSS is not injected on pages. 
Verified, CPCSS is properly created and stored. 

**To Reproduce**
1. Enable Enfold.
2. Enabled/generate CPCSS.
3. Check if CPCSS is properly added.

**Expected behavior**
CPCSS should be added with no issues.

**Screenshots**
![Debugger shows that the page is cached properly](https://i.vgy.me/xROt8A.png)
![CPCSS generated](https://i.vgy.me/7tp8Zo.png)

**Additional context**
Slack discussion - https://wp-media.slack.com/archives/C43T1AYMQ/p1610703532010700

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
Not marking this for `grooming` since RUCSS is more priority right now. Thanks for reporting :)

**Comment by webtrainingwheels** [comment]
the original related ticket: https://secure.helpscout.net/conversation/1393574469/230562/
customer is following up about this here: https://secure.helpscout.net/conversation/1636699755/295958/

**Comment by piotrbak** [comment]
Seems to be working properly now.
