### ISSUE TITLE
Display a warning when the user adds "/" into the Never Cache URL(s) box

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3526]
**Is your feature request related to a problem? Please describe.**
From time to time we get tickets where the customers claim cache is not working, performance is not improving, Lazyload doesn't work, etc,  and the cause is just a / or some form of global exclusion added in the **Never Cache URL(s) box**. 
 
**Describe the solution you'd like**
When we detect a global exclusion is being used, display a notification message to the user on the WP Rocket settings page. 

For Example:
![Captura de pantalla 2021-01-27 a la(s) 11 27 54](https://user-images.githubusercontent.com/229406/106012112-daad8600-6099-11eb-8406-8f99ebf8c3f9.png)

_full image  https://jmp.sh/i0WWnCB_

**Describe alternatives you've considered**
- Make the warning dismissable. 
- Instead of a notification, add a warning below the exclusion box, in red letters as we do in other cases for compatibility notices

**Additional context**
Example tickets: 
https://secure.helpscout.net/conversation/1365587907/222760?folderId=2683093
https://secure.helpscout.net/conversation/1305427220/201250#thread-3773680307
https://secure.helpscout.net/conversation/1365587907/222760?folderId=2683093#thread-4063587537

**Comment by GeekPress** [comment]
I see a potential problem with the actual notice. We are not displaying which value is causing the problem. If users have multiple values, how can they know which one we are talking about?

Instead, here another suggestion:
After saving the option, if we detect the pattern `/(.*)` we won't save this value. A notice will be displayed to let users we didn't save this value and why we did that.

It will avoid generating a problem on the website, and users won't have to do anything to fix it.

@wp-media/qa What do you think?

**Comment by piotrbak** [comment]
@GeekPress Makes sense, definitely. I'm wondering what would be the reason for customers to add that kind of exclusions. If we find that out we could add some further instructions or links to docs too.

**Comment by GeekPress** [comment]
@piotrbak Indeed, it doesn't make to want to cache only the homepage ^^
 
> If we find that out we could add some further instructions or links to docs too.

@alfonso100  @webtrainingwheels Do you know if we already have this kind of documentation?

**Comment by alfonso100** [comment]
I've just updated our doc: https://docs.wp-rocket.me/article/54-exclude-pages-from-the-cache

**Comment by GeekPress** [comment]
> Instead, here another suggestion:
After saving the option, if we detect the pattern /(.*) we won't save this value. A notice will be displayed to let users we didn't save this value and why we did that.

@webtrainingwheels Do you have any suggestions about the text for this notice?

**Comment by webtrainingwheels** [comment]
@GeekPress The text that @alfonso100 put in his original proposal looks good to me (it's in the screenshot). i have just tweaked it slightly:
>Heads up! You have added `/(.*)` in  Advanced Rules > Never Cache URL(s). This disables caching and optimizations for every page of your website

Side note - to avoid any unexpected issue I think we should let the customer save their value, but just show the notice. Maybe they are using it as a debugging shortcut to stop caching or something that we haven't thought about. 

If you really want to not save it, the text could be modified to: 
> You have added /(.*) in Advanced Rules > Never Cache URL(s) and it has not been saved! This disables caching and optimizations for every page on your site. 

And the notification should be red in this case.

**Comment by GeekPress** [comment]
Thanks Lucy for your suggestions.

If we decide to not remove the value, does the notice can be removed by the user?

**Comment by webtrainingwheels** [comment]
> does the notice can be removed by the user?

I think it we do the notification-style message at the top of the screen, per Alfonso's screenshot, I believe we should make it dismiss-able.

He also presented this idea:
>Instead of a notification, add a warning below the exclusion box, in red letters as we do in other cases for compatibility notices
If we used this method, the warning could remain

**Comment by camilamadronero-zz** [comment]
Another case https://secure.helpscout.net/conversation/1551081144/273813?folderId=2675957

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/1649738269/298917?folderId=3864740

**Comment by GeekPress** [comment]
Final version:

- If we detect the value `/(.*)`, remove it during the save process
- Then add a red notice with this content: `You have added /(.*) in Advanced Rules > Never Cache URL(s) and it has not been saved! This disables caching and optimizations for every page on your site.` This message can be removed.

**Comment by camilamadronero-zz** [comment]
Team, if possible, I would like to suggest another wording for the notice, please:
`Sorry! Adding /(.*) in Advanced Rules > Never Cache URL(s) was not saved because it disables caching and optimizations for every page on your site.`

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Create a new method in `Engine\Admin\Settings\Settings`, `check_global_exclusion()` to verify if the pattern `/(.*)` is used in the never cache URL(s) field.

If it is found, remove it, and display the notice using `add_settings_error()`.

Call this method inside `sanitize_callback()`.

### Estimate the effort ✅
Effort `[XS]`
