### ISSUE TITLE
Scripts and Stylesheets in custom folders are combined, but not excluded from the optimization

### ISSUE THREAD

**Issue by JohnTorvik** [wp-media/wp-rocket#3527]
**Before submitting an issue please check that you’ve completed the following steps:**
**- Made sure you’re on the latest version:** Yes. It's the 3.8.3
**- Used the search feature to ensure that the bug hasn’t been reported before:** Not found.

**Describe the bug**
When you load scripts or stylesheets from custom folders like _www.domain.com/tools/file.css/js_, the files are combined and minified, but these files aren't excluded when the path is added into the "Exclude CSS/JS files" fields. The same occurs with our Exclude CSS files from Async loading helper.

**To Reproduce**
1. Add scripts/stylesheets in custom folders in the root directory.
2. Enqueue these files.
3. Activate Combine CSS/JS 
4. Add these files to be excluded and see that it's not excluded then.

**Expected behavior**
Files should be excluded.

**Screenshots**
![image](https://user-images.githubusercontent.com/8461763/106043555-5a991780-60bd-11eb-93d5-622e4b02b306.png)
_files being excluded_

![image](https://user-images.githubusercontent.com/8461763/106043595-6b498d80-60bd-11eb-8435-e2d3c62a8129.png)
_files not excluded from our Optimization_

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by JohnTorvik** [comment]
Related: https://secure.helpscout.net/conversation/1399261518/232278/

**Comment by webtrainingwheels** [comment]
Possibly related: https://secure.helpscout.net/conversation/1406500805/234282?folderId=377611

**Comment by jazir555** [comment]
This may be tied into my elementor swiper issue thread that I made earlier?

**Comment by engahmeds3ed** [comment]
I can't reproduce the issue, I tried locally with simple page and then got the customer site's HTML trying to reproduce this issue but also didn't succeed to reproduce it and the files are excluded from combining without any problem ( I tried CSS combine )

Maybe it's solved with one of our changes in previous minor releases!

@JohnTorvik @webtrainingwheels @jazir5 waiting for your input if you still facing this issue.
Thanks

**Comment by piotrbak** [comment]
Can't reproduce this one. Feel free to reopen with the reliable steps to reproduce.
