### ISSUE TITLE
As a user, I want to have an option to automatically restore WPR to default settings 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3529]
**Is your feature request related to a problem? Please describe.**
I made changes in WPR settings then my site had an issue, expected to find option in tools to automatically restore back to default settings which was working properly, then change my settings 1 by 1 from there to catch the problem.

**Describe the solution you'd like**
Having a button in tools i.e restore to default (with tool tip or something) so once clicked I can restore back to default settings.

**Additional context**
Having confirmation msg as well will be great to avoid issues if this btn was clicked by mistake.

**Comment by webtrainingwheels** [comment]
Indeed this would be nice to have since we get inquiries about it: 
https://secure.helpscout.net/search/?query=tag%3Adefault%20settings%20
https://secure.helpscout.net/search/?query=tag%3Areset%20settings%20

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
