### ISSUE TITLE
Delay js execution: Better make restore default btn dimmed till changes occur in existing text

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3530]
**Is your feature request related to a problem? Please describe.**
Clicking restore default btn in file optimization page while delay js scripts not changing will do nothing.

**Describe the solution you'd like**
Restore default btn in delay js section be dimmed till scripts are changed

**Describe alternatives you've considered**
May be text displayed that scripts are already on default when restore default is clicked in case nothing change in default scripts

**Comment by arunbasillal** [comment]
We have a related issue - https://github.com/wp-media/wp-rocket/issues/3145
Maybe it's best to close this and add the info there so that it can be looked into together?

**Comment by Mai-Saad** [comment]
Added comment there and will close this one.

Thanks Arun!

**Comment by arunbasillal** [comment]
@Mai-Saad Thanks. I have adjusted the labels to `duplicate` fyi 🙏
