### ISSUE TITLE
When using Lazy Loading and Themler builder, class is missing in DIV wrapper for IMG element

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#3533]
**Describe the bug**
When the page is being built with [Themler builder](https://themler.io/), and when WP Rocket Lazy load is active some of the classes are not being added to the DIV wrapper of the IMG element. The result is that the correct CSS is not being applied and images are not displayed correctly.

Example of affected code, for comparison:

Lazy Load turned Off:
`<div class=" additional-class-2095861955 bd-own-margins bd-imagescaling  bd-imagescaling-2017747499  bd-imagescaling-img" style="background-image: url("https://example.com/wp-content/uploads/2020/08/pencil.jpg");"><img src="https://example.com/wp-content/uploads/pencil.jpg"></div>`

Lazy Load turned On:
`<div class="lazyloading bd-imagescaling-img" style="background-image: url("https://example.com/wp-content/uploads/2020/08/pencil.jpg");"><img width="1500" height="1000" src="https://example.com/wp-content/uploads/2020/08/pencil.jpg" data-ll-status="loaded" class="lazyloaded"></div>`

**To Reproduce**
1. Open the page in Themler builder, and add the image, publish the page.
2. Enable Lazy Load in WP Rocket
3. Open the page with the image and check the source-code
4. Compare it with a non-cached version

**Expected behavior**
Lazy Load should not remove, and/or block the loading of correct classes for the element.

**Screenshots**
Lazy Load turned Off: https://i.imgur.com/am9bRam.jpg
Lazy Load turned On: https://i.imgur.com/BlK5ylW.jpg

**Additional context**
Support ticket: https://secure.helpscout.net/conversation/1391146315/229896?folderId=3572910

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@juricazuanovic Were you able to check if those classes are present in the HTML source itself, not in the web developer tools? It's possible that they're added via JS, when we're adding our Lazy Load classes the process is interrupted.

**Comment by juricazuanovic** [comment]
@piotrbak  I didn't check in HTML source. I tried testing on my localhost, but the builder needs a license so I'll ask the customer for access and check it.

**Comment by juricazuanovic** [comment]
@piotrbak I didn't check the HTML source code, and the Themler requires a license so I wasn't able to test it on localhost. I'll ask the customer for access again and check it.

**Comment by juricazuanovic** [comment]
@piotrbak I didn't receive a reply from the customer so I'm unable to test it again and check the HTML source.

**Comment by piotrbak** [comment]
We haven't received any tickets nor feedback related to this issue. Most likely this is an enhancement that can be done with their JavaScript.
