### ISSUE TITLE
Feature Request: Separate combined css/js files for every page to prevent unnecessary code loading

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#3545]
**Is your feature request related to a problem? Please describe.**

My site is a woocommerce site that is built with elementor. On pagespeed insights if I scan my site, it shows that there are 157/164 kb of unused css on the page. 

If i edit the file and view the contents of which it says is causing the delay( the concentated css file has a load time of 1100 ms on mobile). If I edit the file via ssh and look through it's contents, it's loading completely unnecessary css rules on pages they are not being utilized on. 

The css file contains the woocommerce checkout form css for instance, even though it's the homepage which does not contain the checkout form.

If it's doing this for css, i'm sure it's doing this for js as well.

**Describe the solution you'd like**

Separate combined/minified files specific to each to each page that are autogenerated(exactly as they are now), that load conditionally only on the pages they were generated for. 

This would prevent loading extraneous unused code on every page and significantly reduce the page weight by reducing unnecessary css and js rules. There is no way to specify which files should be loaded on what page within wp-rockets settings, so it seems like you guys just took the approach of smushing everything into one file and loading it on every page, which creates tons and tons of unnecessarily loaded code.

I realize you guys have autogenerated files for each page already, the css/js and css/js.gz in the cache>min>1 folder, but they still contain the unnecessary extra data/rules on every page they are loaded on.

**Describe alternatives you've considered**
There are none.

**Additional context**

1. Install a few plugins so that they are loading their css/js. Gravity forms and woocommerce, elementor and elementor pro would be good ones to install to test this.

2. The concentated/minified files are autogenerated.

3. Examine the contents of the autogenerated file on a page to see if it contains code from one of the plugins that is not being utilized on the page.

This has the potential to significantly reduce page weight if implemented.

**Comment by remyperona** [comment]
There is a misunderstanding on how the plugin works for combining CSS/JS files here.

WP Rocket doesn't use one combined file for all pages. Instead, it works as followed:
- Gather all CSS/JS files present on the current page
- Check if a corresponding combined file exists (meaning the same CSS/JS files). If it exists, re-use it
- If it doesn't, create a new combined file corresponding to that set of CSS/JS

This doesn't get rid of unused code on the page, as some 3rd party are loading everything everywhere, but it also doesn't add more than what is originally on the page.

As for removing the unused, this is something that is coming up for the CSS part, we are currently working on that feature.

**Comment by GeekPress** [comment]
I'm closing this feature request as we are working on Remove Unused CSS. For JS, please use a tool like Perfmatters to include your files when needed.
