### ISSUE TITLE
WPR menu in admin top bar better open external links in new tabs

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3546]
**Is your feature request related to a problem? Please describe.**
While opening WP dashboard, I want to see Doc for WP rocket in new tab while keeping WP tab opened.

**Describe the solution you'd like**
Clicking any of these links {Documentation, FAQ, Support} in WPR top menu, will open the link in new tab.

**Additional context**

https://user-images.githubusercontent.com/76941962/106482859-96195480-64b6-11eb-9ab1-945232ea3114.mp4

**Comment by Presskopp** [comment]
Let me drop in briefly that in general the user should have full control over the link behaviour out of a UX perspective.

Read more:
https://www.w3.org/TR/WCAG20-TECHS/G200.html
https://www.nngroup.com/articles/new-browser-windows-and-tabs/
https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187
https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
