### ISSUE TITLE
Add epik to ignored querystrings (Pinterest)

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#3549]
It seems that the querysting "epik" is being added to the url when a link to an external site is clicked on Pinterest.

The querysting "epik" is not currently being ignored by WP Rocket, so, when this happens the site is not cached.

`?epik=XXXXXXXX`

Here is a case of a user asking to add this: https://secure.helpscout.net/conversation/1411765377/235691?folderId=3963184

**Comment by juricazuanovic** [comment]
@sandyfigueroa Today I created PR for new ignored query strings, "epik" is among them: https://github.com/wp-media/wp-rocket/pull/3547

**Comment by sandyfzu** [comment]
Thank you @juricazuanovic! I found nothing by searching epik in the search bar.

Closing this.

**Comment by blogtutor** [comment]
Thank you both!  :)
