### ISSUE TITLE
[Kinsta] Emptying the cache doesn't not empty the CDN

### ISSUE THREAD

**Issue by nicomollet** [wp-media/wp-rocket#3557]
Hello WP Rocket team,
I have trouble with the Kinsta CDN not emptied after I clear the WP Rocket cache. I have to connect to my Kinsta panel for an additionnal step.

**Is your feature request related to a problem? Please describe.**
On Kinsta, with both WP Rocket options "CDN" and "Minify+Combine CSS+JS" enabled, emptying the WP Rocket cache doesn't empty the CDN cache, for example for the Theme CSS.
I have to go to my Kinsta admin panel, CDN tab, and click "Empty CDN".

**Describe the solution you'd like**
Emptying the WP Rocket cache should empty the CDN.

**Describe alternatives you've considered**
No alternative as far as I know.

Thank you
Nico

**Comment by remyperona** [comment]
Hi 👋🏼 ,

WP Rocket doesn't empty the cache of any CDN, it's not part of our features-scope currently.

When using combine, and manually clearing the cache (from the settings page or the admin bar), a new minify key is generated, which should be also changing the resulting combined filenames for both CSS and JS, so CDN cache should not be an issue and the content always up to date.
