### ISSUE TITLE
Malcare - Picking Up WP Rocket as bug

### ISSUE THREAD

**Issue by cyberjosh** [wp-media/wp-rocket#3566]
Hello,

We use Malcare to help manage our fleet of WP sites. I was updating plugins today and when I update to 3.8.4, the site gets scanned and comes back as malware. Have you seen this before?

**Comment by GeekPress** [comment]
Hi @cyberjosh 

Can you please provide us more details? e;g which files has been reported as malware?

Thanks

**Comment by piotrbak** [comment]
Hello @cyberjosh.
We haven't heard back from you. I'll close the issue, please don't hesitate to reopen it and come back to us with more details.
