### ISSUE TITLE
Database Optimization - Detect InnoDB and display a message

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3567]
WP Rocket intentionally does not optimize InnoDB database tables. 
In the UI, it will say "0 tables to optimize" and no optimization takes place. This sometimes leads to customers opening tickets because they think something is not working correctly. 

We could add some text in the UI when InnoDB is detected to let the customer know what's happening. Something along these lines:

<img width="907" alt="Screen Shot 2021-02-05 at 3 44 52 PM" src="https://user-images.githubusercontent.com/1043076/107100422-257d7b00-67c9-11eb-801b-08a8e390e083.png">

Example tickets: 
- https://secure.helpscout.net/conversation/1248100589/185241/
- https://secure.helpscout.net/conversation/1392994139/230416/ (probably)
- https://secure.helpscout.net/conversation/1414044434/236304/

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/1944437692/354841?folderId=3864740

**Comment by rosamillan** [comment]
related https://secure.helpscout.net/conversation/3078416520/587186?viewId=7406897
