### ISSUE TITLE
Get required WordPress version automatically from the API

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3570]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
Now our plugin states that we support WordPress up to `5.5.1` but I'm pretty sure that we support latest one `5.6.1`

https://github.com/wp-media/wp-rocket/blob/5c698673a22509f5a4194ba8909a696a45f5bb68/wp-rocket.php#L25

**To Reproduce**
1. Install WP Rocket 3.8.3 or any version before latest one (3.8.4)
2. View details of upgrade
3. You will see a message that WP Rocket is tested up to `5.5.1` and not tested with latest WP version `5.6.1`

**Expected behavior**
We should show that we support latest WP release.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1406799537/234401/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
Yes

**Identify the root cause**

https://github.com/wp-media/wp-rocket/blob/5c698673a22509f5a4194ba8909a696a45f5bb68/wp-rocket.php#L25

here we are saying that last tested version is `5.5.1`

**Scope a solution**

Update it to be `5.6.1`

**Estimate the effort**
[XS]

@wp-media/qa this is from development perspective but I think you will need to take a round of testing to make sure that we are fully support WP `5.6.1`

**Comment by GeekPress** [comment]
@engahmeds3ed Can we set the value dynamically to not have to update the plugin each time there is a new WordPress version?

We have wp-rocket.me/plugin_information.php which has the info for the last tested WordPress version here:
https://github.com/wp-media/wp-rocket.me/blob/master/plugin_information.php#L21

**Comment by engahmeds3ed** [comment]
@GeekPress I'm sure that this was done like that to let QA team decide if our current version is matching (tested) with latest WP version so if we changed this value automatically, it may not be valid info!

If this is needed, yes we can get the value dynamically.

what do u think?

**Comment by GeekPress** [comment]
The tested value needs to be set on our back-end in any way (Settings > WP Rocket Update Handler). It's not automatic by detecting the new available WordPress version.

**Comment by engahmeds3ed** [comment]
@GeekPress 

Got your point, let me re-groom it today based on that change.

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
Yes I can see the issue locally and u can see it by changing the following version to any WPR older versions
https://github.com/wp-media/wp-rocket/blob/c05805521714c9a7e986bb13b44921a6f0e72754/wp-rocket.php#L6

then go to Dashboard -> Updates page

![image](https://user-images.githubusercontent.com/15707971/107983137-f8ea1000-6fcd-11eb-86fa-687589234068.png)

**Identify the root cause**
We depend on constant to change tested value so here we want to make it dynamic and get its value from WPR site API.

https://github.com/wp-media/wp-rocket/blob/c05805521714c9a7e986bb13b44921a6f0e72754/wp-rocket.php#L25

**Scope a solution**
1. Get the following lines into private method on the same class and call it `get_plugin_information` and call it on its current place
https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Plugin/class-information-subscriber.php#L120-L140

also use transient to save this response.

2. Add new filter `rocket_wp_tested_version` on the following constant
https://github.com/wp-media/wp-rocket/blob/562fbd819f282d41d5b060aa3e77c16465b6d2f7/inc/classes/subscriber/Plugin/class-updater-subscriber.php#L355

3. Use this created filter `rocket_wp_tested_version` here 
https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Plugin/class-information-subscriber.php#L72-L75

to call the method `get_plugin_information`

**Estimate the effort**
[S]
