### ISSUE TITLE
Delete WPR plugin failed message displayed when try to delete WPR plugin while having multiple php tags in wp-config.php

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3577]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Deletion failed displayed when try to delete WPR and deleting link keep loading

**To Reproduce**
Precondition: WPR installed and activated
1. In wp-config.php add `echo'hello <?php'; `after the main PHP tag and save
2. deactivate the plugin
3. delete the plugin

**Expected behavior**
Plugin deleted successfully

**Screenshots**
![can't delete Plugin](https://user-images.githubusercontent.com/76941962/107385996-19145d80-6afc-11eb-98d9-a84fcfd91c24.png)

**Additional context**
- Refresh the page will remove the failure message and the plugin will be removed
- The same occurs even if the added PHP tag has active code 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
That sounds like an edge case. We haven't received any feedback about that. We'll reopen if it appears
