### ISSUE TITLE
Remove delete expired transients from the database optimization

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#3578]
**Is your feature request related to a problem? Please describe.**
Since WP 4.9, WordPress handles cleaning of expired transients automatically.

A cron task called `delete_expired_transients` runs every day, calling the function `delete_expired_transients()`.

The function from WP core deletes expired transient on both single and multisite automatically.

**Describe the solution you'd like**
Considering the above, and the fact that we now require a minimum WP version of 5.2, we can remove our own delete expired transients option from our database optimization feature. It's duplicated functionality, and the one in core is likely better than ours at this point.

**Comment by ghost** [comment]
@Tabrisrp,

Thanks for opening this ticket. Leveraging off your recommendation, I would like to suggest the following:

**(1)** Delete the "Expired Transients" option of your plugin. (as you recommended)

**(2)** Update the code used  for "All Transients." Currently, it is not working properly. Recommend this field, when activated and run, delete all transients in the database (expired and active) using this SQL command: 

DELETE FROM `'wp_options'` WHERE `'option_name'` LIKE ('%\_transient\_%')

Reference: [Stackoverflow (Delete Transients)](https://stackoverflow.com/questions/10422574/can-i-remove-transients-in-the-wp-options-table-of-my-wordpress-install)

We use the above code frequently (once a week) and have never had any issues. However, as always, we highly recommend a backup before deleting all transients.

**(3)** Based on (1) and (2) above, this is what the "Transients Cleanup" section of your plugin should look like:  [Proposed changes](https://prnt.sc/yzdeb9).

Obviously, thorough testing required prior to implementation.

Hope this helps.

Cheers!

**Comment by remyperona** [comment]
Hi @Jetxpert,

What kind of issues did you encounter with the "All transients" option?

We are using an SQL command to select all of them, and then use the `delete_transient()` or `delete_site_transient()` functions for the deletion. It ensures it takes into account if there is an external object cache in place.

**Comment by ghost** [comment]
Hi @Tabrisrp,

When we click on "All Transients," nothing happens. None are deleted. 

We've tried this many times to no avail. The optimization engine does not appear to be working well for us (and perhaps others). Yes, transients regenerate but the "expired" ones should be deleted at least and the results should display "0" expired transients. Well, they are not deleted either.

Above recommendations should work well. As a guide, you may want to look at the database cleaning engine (i.e., dashboard) used by WP Sweep (plugin). We have to use both WP Sweep and the SQL command provided above to clear our transients. WP Rocket is not working  (not for us, at least).

If above does not help much, we can send screenshots. But trust me, it ain't working :)

The recommendations provided above should take care of everything. Thoughts?

Cheers!

**Comment by remyperona** [comment]
I had a look at WP Sweep, and we are basically doing exactly the same thing when clearing the transients:
- https://plugins.trac.wordpress.org/browser/wp-sweep/trunk/wp-sweep.php#L620
- https://github.com/wp-media/wp-rocket/blob/35c1cd12508e9f954fbb8e87fe4501d2eeb1e73c/inc/classes/admin/Database/class-optimization-process.php#L131

I'm suspecting there might be an issue more with the counter more than with the deletion process itself, and that's something we can investigating when working on this issue.

I don't think we will go the route of the direct SQL query for deletion, as I said earlier, using the delete transients functions ensure the object cache is correctly cleared (when there is one), which would not happen otherwise.

**Comment by ghost** [comment]
@Tabrisrp,

Thanks for the update.

We'll continue to monitor and test WP Rocket's "Transient's Cleanup" section but, as stated before, when we have transients listed and click "Save Changes and Optimize," the transients still show up. Practically, the counter should  instead display "0" for both "Expired transients" and "All transients."

And in case you're wondering, we're quite sure our WP Admin Dashboard is not being cached. We always clear it to make sure it's not part of this reported issue. So, as you stated, the counter might be the issue.

Hopefully, you have been able to replicate the same issue and have considered our [proposed changes (updated)](https://prnt.sc/101ad6f) to fix it.

Cheers!

**Comment by mostafa-hisham** [comment]
## Grooming Notes:

### Reproduce the Issue
nothing to reproduce

### Root Cause
remove our own delete expired transients option from our database optimization feature

### Scope for Solution
- Remove the "deletes expired transient" option from the settings page
https://github.com/wp-media/wp-rocket/blob/7c47b1e304692e6bb9c879fd32a8b2d8525c1455/inc/Engine/Admin/Settings/Page.php#L1509-L1518

- remove the switch case for `database_expired_transients` in
https://github.com/wp-media/wp-rocket/blob/7c47b1e304692e6bb9c879fd32a8b2d8525c1455/inc/classes/admin/Database/class-optimization-process.php#L117-L130

- remove the switch case and option for `database_expired_transients` in
https://github.com/wp-media/wp-rocket/blob/7c47b1e304692e6bb9c879fd32a8b2d8525c1455/inc/classes/admin/Database/class-optimization.php#L112-L115

https://github.com/wp-media/wp-rocket/blob/7c47b1e304692e6bb9c879fd32a8b2d8525c1455/inc/classes/admin/Database/class-optimization.php#L46

- remove `database_expired_transients` from arrays in those files
```
wp-rocket/inc/admin/options.php
wp-rocket/inc/admin/upgrader.php
wp-rocket/inc/deprecated/deprecated.php
wp-rocket/inc/Engine/Preload/PreloadSubscriber.php
wp-rocket/tests/Fixtures/inc/admin/rocketFirstInstall.php
wp-rocket/tests/Fixtures/inc/Engine/Support/Data/getSupportData.php
```

### Estimated Effort
[S]
