### ISSUE TITLE
Deactivation Stuck With WordPress Multisite & No Write Permissions To wp-config.php

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#3594]
An interesting edge case for a site that was on flywheel web hosting and was using WordPress multisite. On flywheel, by default you're not given write permissions to wp-config.php therefore to pass this WordPress Rocket requires you to force deactivate the plugin. 

The issue: If WordPress Rocket is activated in network mode (instead of individually per site) this causes a scenario where you're unable to disable the plugin. 

Steps to reproduce. 

1. Make sure wp-config.php is not writeable (so WordPress rocket is prompted to use force deactivation).
2. Activate wprocket in network mode. 
3. Attempt to disable wprocket (no network notice appears) to get the notice to appear go to example.com/wp-admin/ (instead of network mode) there will be a notice for force deactivation. 
4. Click the notice and return to the network panel WPRocket will still be activated.

The only way to break the deactivation loop is to go ahead and delete/deactivate the plugin outside of WordPress or provide write access which isn't always possible for various hosting platforms. 

Now, there is a bit of a workaround. WPRocket's issue stems from the assumption the plugin was activated correctly (according to the docs)...

So by default wp rocket generates a deactivation URL such as the following
https://example.com/wp-admin/plugins.php?action=deactivate&rocket_nonce=293706399a&plugin=wp-rocket%2Fwp-rocket.php&plugin_status=all&paged=1&s&_wpnonce=c90a95a848

You can trick the plugin by copying the deactivation URL and simply doing the following
https://example.com/wp-admin/network/plugins.php?action=deactivate&rocket_nonce=293706399a&plugin=wp-rocket%2Fwp-rocket.php&plugin_status=all&paged=1&s&_wpnonce=c90a95a848

By adding /network/ to the URL the plugin will deactivate its self correctly. 

Proposed fixe...
Since WPRocket doesn't support network activation there should be a mechanism either to prevent network activation or on activation provide a notice in the network panel warning users. If it does get activated in network mode by accident and is attempting to be disabled then the force deactivation url should be updated to prevent soft locking the deactivation process.

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
