### ISSUE TITLE
Get rid of Google Tracking and Facebook Pixels add-ons

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3597]
## What are we proposing to do?

With this update we are hoping to remove the « Google Tracking » and « Facebook Pixels » add-ons from WP Rocket UI (Add-ons tab).

## Why are we doing this? 

We originally released these features to fix the old « Leverage browser caching » PageSpeed Insight recommendation on Google Analytics and Facebook Pixels JS files. Both have a small cache policy.

By hosting these files locally we fix the browser caching issues.

Since 3.7, we introduced a feature to delay JS execution. The principle behind that is to load non-critical JS files after a user interaction (a kind of Lazy-Load).

Today, this is the way to go to optimize third-party JS files. 

Here what Google itself recommends: If they aren't critical or are below the fold (that is, if users have to scroll to view them), lazy-loading is a good way to improve page speed and paint metrics. This way, users will get the main page content faster and have a better experience. One effective approach is to lazy-load third-party content after the main page content loads. Ads are a good candidate for this approach. (source: https://web.dev/efficiently-load-third-party-javascript/)

Delaying third-party JS files would be a much better UX improvement than hosting the file locally.

We already pre-populates our Delay JS option with a list of third-party scripts including Google Tracking and Facebook Pixels.

Based on that, our add-ons to host locally Google Tracking and Facebook Pixels files are now useless.

## Benchmark Tests

Here the conclusion of our benchmark.

* Hosting locally Google Tracking and Facebook Pixels decrease the general Google PageSpeed score even if they aren't delayed.
* Delaying Google Tracking and Facebook Pixels JS files is confirmed to be the way to go to get better performance.

## User expectations and experience. How will we do this feature?
From 3.9, all users will not have Google Tracking and Facebook Pixels add-ons in WP Rocket UI and the optimizations won’t be applied anymore.

Both existing and new users will have the same experience.

## Risks

Since we are removing a feature, this should be low risk. The major concern is educating customers.

## Acceptance Criteria

* Update WP Rocket to 3.9.
* The UI for « Google Tracking » and « Facebook Pixel » add-ons are removed.
* On front-end, the tracking for Google and Facebook should not be modified

## Documentation and Translations

* https://docs.wp-rocket.me/article/1103-google-tracking-add-on
* https://docs.wp-rocket.me/article/1117-facebook-pixel-add-on
* https://docs.wp-rocket.me/article/1361-google-analytics-not-detected (Google Tracking Add-on is listed)
* https://docs.wp-rocket.me/article/115-can-i-use-wp-rocket-with-sg-optimizer (Google Tracking Add-on is listed)
* https://docs.wp-rocket.me/article/59-getting-started (Google Tracking and Facebook Pixels add-ons are listed)
* https://docs.wp-rocket.me/article/1419-minimize-main-thread-work (Google Tracking and Facebook Pixels add-ons are listed)
* https://docs.wp-rocket.me/article/1413-reduce-the-impact-of-third-party-code (Google Tracking and Facebook Pixels add-ons are listed)
* https://docs.wp-rocket.me/article/893-handling-external-resources (Google Tracking and Facebook Pixels add-ons are listed)

## Github issues
All opened issues related to Google Tracking and Facebook Pixels add-ons will be closed:

* https://github.com/wp-media/wp-rocket/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+Google+tracking+add-on%22+-label%3A%22epics+%F0%9F%94%A5%22+
* https://github.com/wp-media/wp-rocket/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+Facebook+Pixel+add-on%22+-label%3A%22epics+%F0%9F%94%A5%22+

**Comment by engahmeds3ed** [comment]
**Scope a solution**

1. Classes to be removed and added to deprecated file
    - \WP_Rocket\Addon\Busting\BustingFactory
    - \WP_Rocket\Addon\Busting\FileBustingTrait
    - \WP_Rocket\Addon\FacebookTracking\Subscriber
    - \WP_Rocket\Addon\GoogleTracking\GoogleAnalytics
    - \WP_Rocket\Addon\GoogleTracking\GoogleTagManager
    - \WP_Rocket\Addon\GoogleTracking\Subscriber

2. Remove their calls inside the service provider
https://github.com/wp-media/wp-rocket/blob/4fb2d41185562364ff57747738b6f8c4c3c75294/inc/Addon/ServiceProvider.php#L39-L52

and also here:
https://github.com/wp-media/wp-rocket/blob/4fb2d41185562364ff57747738b6f8c4c3c75294/inc/Addon/ServiceProvider.php#L25-L27

3. Remove addons from settings page
https://github.com/wp-media/wp-rocket/blob/a5eeb3012af05bfbfd6d735321f5c4b962b6ad61/inc/Engine/Admin/Settings/Page.php#L1765-L1809

and the following two lines

https://github.com/wp-media/wp-rocket/blob/a5eeb3012af05bfbfd6d735321f5c4b962b6ad61/inc/Engine/Admin/Settings/Page.php#L295-L296

4. Remove beacon docs
https://github.com/wp-media/wp-rocket/blob/b0711a77bfc759d69faf769758796e4149fff7ce/inc/Engine/Admin/Beacon/Beacon.php#L610-L625

5. Remove calling those two subscribers
https://github.com/wp-media/wp-rocket/blob/c353a69ebbc941c80a7418b17954cb1bb6c629a7/inc/Plugin.php#L242-L243

6. On upgrade we need to do the followings:-
    - Call `wp_clear_scheduled_hook` for [this schedule](https://github.com/wp-media/wp-rocket/blob/6fb90b422dc260e1b0fb9214680631f124a1de49/inc/Addon/FacebookTracking/Subscriber.php#L109) also for [this schedule](https://github.com/wp-media/wp-rocket/blob/6fb90b422dc260e1b0fb9214680631f124a1de49/inc/Addon/GoogleTracking/Subscriber.php#L96).
    - Check if one of those options was enabled `google_analytics_cache, facebook_pixel_cache` to fill the list of delay JS with corresponding keyword in case it was removed from the list, not to affect the page speed.

7. Remove those items from options to be sent here
https://github.com/wp-media/wp-rocket/blob/4519cd525d875f990c102e8c4e062c5b5adf9683/inc/Engine/Support/Data.php#L44-L45

8. Remove those tests (tests/Unit/inc/Addon)
9. Adjust old tests to make them working again after removing those addons options.

**Estimate the effort**
[S]
