### ISSUE TITLE
CDN breaks Envira gallery lightbox

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#360]
Envira gallery uses html code inserted in JS for its lightbox, and the src value is {href}, replaced by the actual image src when the lightbox is triggered.

This placeholder is considered as a relative path by the CDN function, so the CDN URL is applied to the placeholder, breaking the image URL in the lightbox.

Example:

- image URL: http://cdn.example.com/image.jpg
- placeholder: http://cdn.example.com/{href}
- src value in lightbox becomes: http://cdn.example.com/http://cdn.example.com/image.jpg

**Comment by AliceOrru** [comment]
@Tabrisrp and @GeekPress we're having the same kind of issue with NextGen gallery. 
Ticket: https://secure.helpscout.net/conversation/351557420/38380/?folderId=628132
