### ISSUE TITLE
Add support to wpstage.net (BlogVault) to allowed list of staging and development environments

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#3600]
**Is your feature request related to a problem? Please describe.**
blogvault.com is WP backup plugin that is using the following for staging/dev environments:

- staging.wpstage.net

Using WP Rocket in this domain will count as a license.

**Describe the solution you'd like**
Allow .wpstage.net as part of WP Rocket list of staging and development environments.

**Comment by GeekPress** [comment]
This domain has been added to WP Rocket website already:
https://github.com/wp-media/wp-rocket.me/pull/2290

**Comment by remyperona** [comment]
### Scope a solution ✅ 
- Add `.wpstage.net` to the list of staging domains in `functions/api.php` `rocket_is_live_site()`
- Update fixtures

### Estimate the effort ✅
Effort `[XS]`
