### ISSUE TITLE
Dynamic Inclusion and Exclusion Lists For WP Rocket

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3602]
**What are we proposing to do?**

WP Rocket includes many default inclusion and exclusion lists for some of our features. For example, we maintain a list of keywords for inline scripts to be excluded from JavaScript combination. Instead of hard-coding the list within WP Rocket, we are proposing to save them on our server and pull them dynamically from the plugin. 

In other words, these keywords will be saved on our server and WP Rocket plugin will read them periodically. A copy of the list will be stored locally on the WordPress installation. 

As part of the plugin package, a copy of the JSON / XML file will be included and this will act as fallback in case the dynamic update fails. 

[full doc](https://docs.google.com/document/d/1LCzqwCduwlu2xlddZ4o_A6kZhVf83jDUCYq4pM900L4/edit?usp=sharing)

**Comment by Joshfindit** [comment]
As an admin who regularly uses `git` for WordPress file tracking, it's important that plugins do not update files outside of our business processes.

The solution of changing permissions on `wp-content/wp-rocket-config/dynamic-lists.json` is not ideal as it means it cannot be updated in WP-Admin.
Instead, I'd like to ask for a setting that can be applied inside WP-Admin. One that *disables* automatic Inclusion and Exclusion List updates while keeping the UPDATE LISTS button.

**Comment by piotrbak** [comment]
Hello @Joshfindit and thanks for your comment.

I've created a small helper that will disable automatic updates of that file while preserving the Update Lists button functionality:
https://github.com/wp-media/wp-rocket-helpers/tree/master/various/wp-rocket-disable-auto-list-updates

I'm closing this issue since the feature is implemented already. Feel free to reach us if you have any further concerns.

**Comment by Joshfindit** [comment]
Checking in on this: The helper worked great up until recently. We now see `wp-content/wp-rocket-config/dynamic-lists-delayjs.json` has been updated automatically. Is that expected?

Edit: Found the addition in a recent commit. https://github.com/wp-media/wp-rocket/pull/5636/files#diff-45a15ccd8ec256743205db1b9b9b6018167e5243d11372ec3de3c4625b02c68cR59
