### ISSUE TITLE
Switch to Native LazyLoad for Images

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3604]
## What are we proposing to do? 

With this update, WP Rocket will switch from using the JavaScript based LazyLoad for images and start supporting native browser LazyLoad by default. 

WP Rocket will still use it’s JavaScript based LazyLoad for background images and iframes since these are not supported by native LazyLoad yet on all browsers.

([full doc](https://docs.google.com/document/d/1z4pkyZdYbOfKQzcEwGrvxuV4ngGaooQyQcxNtOw4yIk/edit?usp=sharing))

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll revisit it when planned to be released
