### ISSUE TITLE
Wrong CDN rewrite on inline SVG (clip-path=url) presents in the Critical Path CSS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3608]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the CDN option is enabled, we are replacing the internal URL on background rules, etc... with the CNAME URL.

Sometimes, background rules can contain an inline SVG like that:

`
background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg width='1436' height='12' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M5.5 9.9a4.4 4.4 0 110-8.8 4.4 4.4 0 010 8.8z' fill='%2352C0FF'/%3E%3Cpath d='M80.5 1l4.9 8.3h-9.8L80.5 1z' fill='%23F56F46'/%3E%3Crect x='155.5' y='.5' width='7.1' height='7.1' rx='.9' transform='rotate(45 155.5 .5)' fill='%23FFD147'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M230.5 9.9a4.4 4.4 0 110-8.8 4.4 4.4 0 010 8.8z' fill='%23fff'/%3E%3Cpath d='M305.5 1l4.9 8.3h-9.8l4.9-8.4z' fill='%23D0D3D8'/%3E%3Crect x='380.5' y='.5' width='7.1' height='7.1' rx='.9' transform='rotate(45 380.5 .5)' fill='%23D0D3D8'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M455.5 9.9a4.4 4.4 0 110-8.8 4.4 4.4 0 010 8.8z' fill='%23FFD0D8'/%3E%3Cpath d='M530.5 1l4.9 8.3h-9.8l4.9-8.4z' fill='%2399D1DE'/%3E%3Crect x='605.5' y='.5' width='7.1' height='7.1' rx='.9' transform='rotate(45 605.5 .5)' fill='%23005BC6'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M680.5 9.9a4.4 4.4 0 110-8.8 4.4 4.4 0 010 8.8z' fill='%23F56F46'/%3E%3Cg clip-path='url(%23clip0)'%3E%3Cpath d='M755.5 1l4.9 8.3h-9.8l4.9-8.4z' fill='%2352C0FF'/%3E%3C/g%3E%3Crect x='830.5' y='.5' width='7.1' height='7.1' rx='.9' transform='rotate(45 830.5 .5)' fill='%23D0D3D8'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M905.5 9.9a4.4 4.4 0 110-8.8 4.4 4.4 0 010 8.8z' fill='%23FFD147'/%3E%3Cpath d='M980.5 1l4.9 8.3h-9.8l4.9-8.4z' fill='%23fff'/%3E%3Crect x='1055.5' y='.5' width='7.1' height='7.1' rx='.9' transform='rotate(45 1055.5 .5)' fill='%2399D1DE'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M1130.5 9.9a4.4 4.4 0 010-8.8c2.4 0 4.3 2 4.3 4.4a4.3 4.3 0 01-4.3 4.4z' fill='%23D0D3D8'/%3E%3Cpath d='M1205.5 1l4.9 8.3h-9.8l4.9-8.4z' fill='%23FFD0D8'/%3E%3Crect x='1280.5' y='.5' width='7.1' height='7.1' rx='.9' transform='rotate(45 1280.5 .5)' fill='%23F56F46'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M1355.5 10.9a4.4 4.4 0 010-8.8c2.4 0 4.3 2 4.3 4.4a4.3 4.3 0 01-4.3 4.4z' fill='%2352C0FF'/%3E%3Cpath d='M1430.5 2l4.9 8.3h-9.8l4.9-8.4z' fill='%23FFD147'/%3E%3Cdefs%3E%3CclipPath id='clip0'%3E%3Cpath fill='%23fff' transform='translate(750)' d='M0 0h11v11H0z'/%3E%3C/clipPath%3E%3C/defs%3E%3C/svg%3E");
`

This code contains `clip-path='url(%23clip0)` which will be replaced by `clip-path='url(https://v3b4d4f5.rocketcdn.me/wp-content/themes/V4/assets/css/%23clip0)` in the CPCSS.

**To Reproduce**
1. Your CSS should contain a rule with a background CSS declaration including an SVG inline with `clip-path='url(%23clip0)`. This declaration should be declared in your header to be catched by the CPCSS.
2. Turn on the CPCSS and CDN options
3. Check the CPCSS generated and see error

**Expected behavior**
No CDN rewrite on `clip-path='url(%23clip0)`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
