### ISSUE TITLE
Optimization of non-existent external files

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3612]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When an external script or style doesn't exist, but the server responds with 200 status code + error page, WP Rocket will download the script/style and also combine it.

**To Reproduce**
1. Add a non-existent external JS or CSS file to the page ([for example ](https://rocketlabsqa.dev/wp-content/themes/fictional-university/js/scripts-bundled.js)). It's important that the server responds with a 200 status and error page
2. Enable Minification
3. Go to the page and check the source
4. "Resource" is downloaded and hosted on the local domain. The content is HTML.

**Expected behavior**
We shouldn't optimize that kind of scripts

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/108770801-ae7b0d00-7552-11eb-967f-fa746fc0631a.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
@piotrbak do you mean that we need to check if the content isn't HTML ( or at least  )?

As I think here: 

https://github.com/wp-media/wp-rocket/blob/f9e34ecfb4349258dc6a0ee3b91a001b6ae82f37/inc/Engine/Optimization/AssetsLocalCache.php#L59

we are getting the response body so it will only return content if the response body has content inside it.

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
