### ISSUE TITLE
Busting directory is not cleared during the cache clearing

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3617]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We're not removing the `/wp-content/cache/busting/1/wp-content/` content when clearing the cache from the top menu neither during deactivation.

**To Reproduce**
1. Visit the page when the dynamic CSS file is added (dynamic_css.php, etc.)
2. Confirm that the associated file is created in the busting directory
3. Clear the cache, deactivate WP Rocket
4. Confirm that the cache is not cleared

**Expected behavior**
We should be able to clear this cache at the correct moment, including the `.gz` files which are not listed in the `$extensions` array here:
https://github.com/wp-media/wp-rocket/blob/8c02750b89412eb7e395551c150ab06e4a4b8e2b/inc/functions/files.php#L401

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/109046566-cb3b5000-76cc-11eb-8db4-3f8d8c56cff4.png)

**Additional context**
We should think when the busting directory should be cleared exactly.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Referring to https://docs.wp-rocket.me/article/1135-when-does-wp-rocket-delete-which-files, I think it needs to be handled too with Clear Cache lifespan as currently, it is not.

**Comment by Mai-Saad** [comment]
Note: This issue will prevent updating used CSS  when the dynamic js file is updated
=> As per discussion with @piotrbak it affects minify js as well {the dynamic file is not updated in cache}

**Comment by webtrainingwheels** [comment]
likely related: https://secure.helpscout.net/conversation/1571793941/279766?folderId=377611

**Comment by remyperona** [comment]
### Scope a solution ✅ 
in `common/purge.php`, `do_admin_post_rocket_purge_cache()`, add a call to `rocket_clean_cache_busting()` after `rocket_clean_minify()` on line 439

### Estimate the effort ✅
effort `[XS]`
