### ISSUE TITLE
@charset rule should be added before the @import in the minified/combined file

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3621]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The `@charset` rule should be very first in the minified/combined CSS file. When we have `@import` rules, we're moving them to the beginning:
https://developer.mozilla.org/en-US/docs/Web/CSS/@charset

**To Reproduce**
1. Add the `@charset` rule to the top of the CSS file where there's already an `@import` present
2. Enable CSS Minification
3. Check the source of the minified file 
4. Confirm that the `@charset` is moved under the `@import` (after 3.8.6 after the content of the `@import` file)

**Expected behavior**
We should make sure that the `@charset` is at the very top.

**Additional context**
I'm thinking about the case when we combine or import files that already have the `@charset` defined. We'll add it somewhere in the middle of the file.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
As this is `XS` issue, I created PR directly for it with the code changes.

@wp-media/productrocket 
In my changes if we had multiple charset rules, I grabbed all of them and added them to the top of the file, if you want another approach please let me know ( I can for example put the first charset only or force all of them to be `utf-8` or ...etc. )

**Comment by GeekPress** [comment]
@piotrbak  @engahmeds3ed What could be the other value for charset than UTF8 for CSS files?

**Comment by engahmeds3ed** [comment]
https://www.w3.org/International/questions/qa-css-charset.en#nonutf8
https://www.iana.org/assignments/character-sets/character-sets.xhtml

you can find here list of charsets (standard ones), I don't know if those are commonly used or not.

Also please note this section (on the same article above)
> Important: Since the HTTP header has a higher precedence than the in-document `@charset` declaration, you should always take into account whether the character encoding is already declared in the HTTP header. If it is, `@charset` must be set to declare the same encoding, and will only have an effect when the style sheet is read in a context where there are no HTTP headers (eg. from a local drive).

and I think we are setting charset in htaccess for css files (this is for apache based only), I think this is the whole picture about charset in CSS.

**Comment by GeekPress** [comment]
@engahmeds3ed Ok thanks for the details.

What about relying on the website charset by using `bloginfo( 'charset' );`

Are there reasons to have a different charset on CSS files and the website?

**Comment by GeekPress** [comment]
From the WordPress doc:

> ‘charset‘ – Displays the “Encoding for pages and feeds” set in Settings > Reading. This data is retrieved from the “blog_charset” record in the wp_options table. Note: this parameter always echoes “UTF-8”, which is the default encoding of WordPress.

I'm wondering when the charset in CSS files could be different than UTF-8.

**Comment by ScottTravisHartley** [comment]
If you're using a UTF-8 encoding on the website and it's properly declared in the document which WordPress does for you, there wouldn't really be a need to declare a separate charset value in the CSS. 

"You should always use UTF-8 as the character encoding of your style sheets and your HTML pages, and declare that encoding in your HTML. If you do that, there is no need to declare the encoding of your style sheet.

Other approaches are only needed if your style sheet contains non-ASCII characters and, for some reason, you can't rely on the encoding of the HTML and the associated style sheet to be the same. In this case you should use @charset or HTTP headers to declare the encoding. (If your HTML and CSS files use the same encoding, the latest versions of major browsers will apply the encoding of the HTML file to the CSS stylesheet.)"

Src: https://www.w3.org/International/questions/qa-css-charset.en

**Comment by engahmeds3ed** [comment]
After communicating internally, we will take the following approach when finding more than one charset:-

> Grab the first charset we find and use only this one.

and the current approach on the PR #3628 is to put all found charsets at the top of the CSS file and the browser only understand the first one.

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
