### ISSUE TITLE
Sanitization on the CDN field

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3622]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We allow adding any string to the CDN CNAME.

**To Reproduce**
1. Go to the CDN section of WP Rocket
2. Add `I'm not a domain` string to the CDN field
3. Check the source of the cached page
4. `dns-prefetch` and `preconnect` are pointing to this string, all assets are rewritten too

**Expected behavior**
We should allow only URLs there. 3 different types of URLs will cover all scenarios:
- `example.com` To rewrite everything dependently on the website scheme
- `https://example.com` To rewrite everything to HTTPS
- `http://example.com` To rewrite everything to HTTP

`//example.com` is just the same as `example.com`, but adding the `preconnect` doesn't work for this case now. Thanks @Mai-Saad 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
Related to this - a customer entered the CDN URL like this: 
`HTTPS://cdn.com`
and it was rewritten to: `https://HTTPS://cdn.com`
If we can catch that and correct it automatically, it would be 👍

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
