### ISSUE TITLE
Display a warning when Minify/Combine files take too much space

### ISSUE THREAD

**Issue by nicomollet** [wp-media/wp-rocket#3627]
Hello

**Is your feature request related to a problem? Please describe.**
Minify/Combine create files in cache/min/1 and if some themes or plugins have many dynamic inline JS which doesn't work well with combine option. The risk is to create combined files on each visit.

At the moment, one of my website has 12 Gb of combined files (20k files) and it is filling my disk storage.
![image](https://user-images.githubusercontent.com/108828/109482363-2e870280-7a7e-11eb-84e4-75df8351db50.png)

**Describe the solution you'd like**
I would like WP Rocket to display a warning when too much space is used in cache/min/1.
And/or maybe remove the older files.

**Describe alternatives you've considered**
Indeed my job is to find which plugin has a dynamic inline JS so that I can exclude it.
https://docs.wp-rocket.me/article/1351-javascript-minify-combine

**Additional context**
I found out about the disk storage being almost 100% used as my hosting provider has a graph of the storage usage.

Thank you

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.

**Comment by nicomollet** [comment]
> We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.

Kinda surprised I was the only one with that issue :)
Worse thing is some host make you pay for every GB used above the GB allowed in the plan.
Sometimes I paid tens of $$$ because of it.
