### ISSUE TITLE
Remove Unused CSS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3635]
## What are we proposing to do? 
To build a new feature within WP Rocket that will remove all the unused CSS from each page of the website. 

We will do this by building a CSS tree-shaker from the ground up, and host it on our server. WP Rocket will then interact with this service via its API. This is similar to what we do for our CPCSS generator. 

We will do this for each page of the website and embed the CSS right into the HTML of the page. 

([full doc](https://docs.google.com/document/d/15hFzxmi5lBMJ7qw0EaO-td7p0IhkDSuNXO8fPoMwlxw/edit?usp=sharing))

**Comment by webtrainingwheels** [comment]
@Tabrisrp The doc link for this is going to be: https://docs.wp-rocket.me/article/1529-remove-unused-css
ID: 6076083ff8c0ef2d98df1f97
