### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3641]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
PHP error when deactivating amp while having cached page and the smart slider is enabled

**To Reproduce**
Precondition:
1- WPR installed and activated
2- Home page cached

1. install and activate AMP + smart slider
2. Change WPR settings 
3. Hard refresh home page multiple times
4. Deactivate AMP
5. Check the log file
`[04-Mar-2021 16:21:18 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/CDN/CDN.php on line 199
[04-Mar-2021 16:21:18 UTC] PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0`

**Expected behavior**
No error in a log file

**Screenshots**

https://user-images.githubusercontent.com/76941962/109996745-31048900-7d18-11eb-8bc8-65e895b09d1e.mp4

https://user-images.githubusercontent.com/76941962/109997012-70cb7080-7d18-11eb-87a2-d25ab10aa0e9.mp4

**Notes**
- attached cast may include other extra steps
- UI of the website is fine

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closing it since this is related to the plugin/theme/environment combination
