### ISSUE TITLE
Changes not reflected after save (memcached)

### ISSUE THREAD

**Issue by mircobabini** [wp-media/wp-rocket#3642]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When memcached is on, saving some settings does not reflect the value after page reload. For instance, I added some advanced cache configurations but after hit save and page reload, the changes are not shown. After memcached cleanup, hit F5 and changes are reflected.

**To Reproduce**
1. Activate memcached
2. Save wp rocket settings to store in memcached
3. Change the advanced cache settings
4. Save... and see that the new values are not reflected, but they are stored.

**Expected behavior**
As soon as I hit save, memcached should be flushed for wp rocket settings.

**Screenshots**
<img width="930" alt="Screenshot 2021-03-05 at 10 53 54" src="https://user-images.githubusercontent.com/636911/110099454-9e103100-7da1-11eb-8f94-cd1a04f8b625.png">

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
