### ISSUE TITLE
Enhancement - Self-host, Inline & Combine Google Fonts

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3647]
**Is your feature request related to a problem? Please describe.**
I think WP Rocket should reconsider its position regarding the optimization of Google Fonts.

https://wp-rocket.me/blog/self-hosting-google-fonts/

I refer to your Suggestion Box which has gathered no less than 50 votes for this improvement.

https://portal.productboard.com/wp-media/1-wp-rocket-portal/c/10-save-google-fonts-on-the-server

**Describe the solution you'd like**
WP Rocket should be able to self-host, inline & combine Google Fonts.

**Describe alternatives you've considered**
OMGF and FlyingPress

**Additional context**
You can find below recent blogs showing the benefits of hosting locally Google Fonts.

https://wpspeedmatters.com/self-host-google-fonts/

https://daan.dev/how-to/remove-google-fonts-wordpress/

https://dev.to/zwacky/time-to-say-goodbye-to-google-fonts-16dd

https://www.wpmediamastery.com/host-google-fonts-locally/#My_Site_Is_Twice_As_Fast_Since_I_Self_Host_Google_Fonts

**Comment by GeekPress** [comment]
We explained here why we don't plan to do that:
https://wp-rocket.me/blog/self-hosting-google-fonts/

**Comment by gevcen** [comment]
If you read my description, you'll notice that I already saw this article and I even mentioned it myself in the beginning.

And I've mentioned other blogs that take your arguments and counter-argue them.

**Comment by GeekPress** [comment]
You will find 10 posts saying the same conclusion as us, and 10 others with another conclusion. It doesn't seem to have a global conclusion and we prefer to follow the one we found.
