### ISSUE TITLE
Added url in Never Cache URL is automatically removed when save settings if it didn't start with / (without any note)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3649]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the user enters a URL in the Never Cache URL field that is not starting with /, The URL is automatically removed with no notice to the user to know what is the problem

**To Reproduce**
1. Open WPR settings -> Advanced rule
2. write test.com in never cache URL and save
3. URL is removed without any note

**Expected behavior**
URL remain there with a validation message displayed i.e URL must start with / (if it's really a must)

**Screenshots**

https://user-images.githubusercontent.com/76941962/110342872-91efd200-8034-11eb-952d-c5a5875f30c5.mp4

**Additional context**
- Same Applies to always purge URLs

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Same behavior of auto delete to url occurs when:
-  added wrong URL (i.e unsupported font or external URL) in preload font view, So recommend handle validations across the plugin.
- adding URL to prefetch DNS request but URL starts with single / (works fine if URL starts with no / or double /)

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
