### ISSUE TITLE
WP-Rocket website down resulting in extremely slow settings page

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#3653]
I am not sure if it is just in my location, the WP-Rocket website seems to be down for few hours as of now. But the real problem here is two resources requested from the WP-Rocket URL causing the WP-Rocket settings page to be extremely slow.

- https://wp-rocket.me/wp-content/uploads/1/imagify.jpg
- https://wp-rocket.me/cdn/iframe?website=https://www.example.com&callback=https://www.example.com/wp-json/wp-rocket/v1/rocketcdn/

Because the website is down, the above resources are not accessible causing the settings page to take more than almost a minute to load. **FYI, this is not the first time I am experiencing this issue.** I am not reporting this the first time I saw the slowness.

Apart from that, this also prevents generating Critical Path CSS. I do not have anything to propose as a fix for this. But, if problems with WP-Rocket servers affect all the websites it is installed on, I think it should be taken care of.

**Comment by GeekPress** [comment]
Hi @MuhammedSwalihct 

We had some problems yesterday related to the OVH crash. Everything has been fixed :)
