### ISSUE TITLE
Help link beside Always purge URL redirects to How often is the cache cleared? instead of Always Purge URL doc

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3654]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clicking help btn beside Always Purge Url, gets redirected to How often is the cache cleared

**To Reproduce**
1. Go to WPR settings -> advanced rules
2. Open in new tab need help besides Always purge URLs section 
3. How often is the cache cleared page

**Expected behavior**
Redirect to https://docs.wp-rocket.me/article/1391-always-purge-url-s

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
That's because we didn't have this doc -  https://docs.wp-rocket.me/article/1391-always-purge-url-s - until recently. 
I am actually preparing one issue which will update many of these docs links inside the plugin, so we can deal with them in one update :)

**Comment by Mai-Saad** [comment]
Thank you @webtrainingwheels. I Will close this one then to avoid duplication.
