### ISSUE TITLE
Update some documentation links in the plugin

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3657]
We need to update a few of the articles that are featured in the Beacon (https://jumpshare.com/v/zioongh75XrnIVZFD2Vj) , and also a few of the "Need Help" buttons. 

All the requested changes are here: https://docs.google.com/spreadsheets/d/1EM10uUWFrZBS-MWq-j7Ut4iua5wAkHzWy_CTahm_ZHQ/edit?usp=sharing
Note there are 2 tabs on the sheet - 1 for beacon articles, 1 for "need help" buttons
I hope the sheet is clear 😅 
Feel free to ping me if clarification is needed!!

**Comment by webtrainingwheels** [comment]
This update also addresses: https://github.com/wp-media/wp-rocket/issues/3654

**Comment by GeekPress** [comment]
@Tabrisrp @vmanthos Do you think it can be done by a Technical Support Engineer?

**Comment by remyperona** [comment]
Yes, everything is located in this method: https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd73/inc/Engine/Admin/Beacon/Beacon.php#L206

**Comment by webtrainingwheels** [comment]
How does this get moved forward and assigned to someone? I would like this to get into 3.8.8

**Comment by remyperona** [comment]
@webtrainingwheels I added it on our sprint board and in the release milestone. It should be handled either by someone from the support tech group, or one of the engineering team before the end of next week.

**Comment by webtrainingwheels** [comment]
@Tabrisrp Awesome, thank you!!
