### ISSUE TITLE
Don't preload fonts when CPCSS is injected on the current page & remove font-face rules from CPCSS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3667]
**Describe the solution you'd like**
When CPCSS is present on the current page, a combo will lead to a better LCP:
- Stop preloading fonts configured into our « Preload Fonts » option.
- Remove font-face rules from CPCSS

In our benchmarks, it can improve the LCP from 10 to 20%.

The CPCSS API is ready to be able to remove font-face rules from the CPCSS:
https://github.com/wp-media/criticalpath-css-generator/blob/master/app/controllers/register.js#L22  

We will need to send a new parameter in the CPCSS API config: https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd73/inc/Engine/CriticalPath/ProcessorService.php#L84

`'nofontface' => true,`

If this change causes a problem on a website, this could be solved by using this filter and set the `nofontface` parameter to `false`:
https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/CriticalPath/APIClient.php#L38

**Comment by crystinutzaa** [comment]
### Scope a solution ✅ 
**1. Add a Filter `rocket_disable_preload_fonts`  in Fonts.php** 
https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd73/inc/Engine/Preload/Fonts.php#L86
The filter will return TRUE / FALSE , by default will be FALSE and will bailout in case is true.
In this way the fonts will not be preloaded.

**2. wp-rocket/inc/Engine/CriticalPath/CriticalCSSSubscriber.php**
Hook into: `rocket_disable_preload_fonts` and check if the current page has CPCSS enabled and available:
Similar to:
```
public function disable_preload_fonts() {
		if ( ! $this->should_async_css() ) {
			return false;
		}

		// This filter is documented in inc/classes/Buffer/class-tests.php.
		$rocket_cache_search = apply_filters( 'rocket_cache_search', false );

		// Don't apply on search page.
		if ( is_search() && ! $rocket_cache_search ) {
			return false;
		}

		// Don't apply on 404 page.
		if ( is_404() ) {
			return false;
		}

		if (
			empty( $this->critical_css->get_current_page_critical_css() )
			&&
			empty( $this->options->get( 'critical_css', '' ) )
		) {
			return false;
		}
		return true;
}
```

**3. wp-rocket/inc/Engine/CriticalPath/ProcessorService.php**
Add a new filter `rocket_cpcss_nofontface` with default = TRUE and send it as a new param to CPCSS API:
`'nofontface' => true,`

https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd73/inc/Engine/CriticalPath/ProcessorService.php#L83-L86


### Estimate the effort ✅
Effort `[S]`

**Comment by GeekPress** [comment]
I'm re-opening this issue to revert it. We had some complaints and issues we aren't able to understand why we have the problem.

We would need to do these changes:
- Don't stop the preload fonts when CPCSS is on
- Set the `nofontface` argument to false (instead of true)
