### ISSUE TITLE
Add an entry in WP Rocket's debug log, when template_redirect doesn't fire

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3669]
**Is your feature request related to a problem? Please describe.**

WP Rocket is hooking to the WordPress `template_redirect` hook to apply its optimizations.

If for whatever reason, that doesn't fire, the optimizations aren't applied.

**Describe the solution you'd like**

It would be easier for the support to recognize the issue if we had an entry about this in WP Rocket's debug log.

**Describe alternatives you've considered**

We can add a log entry in WP Rocket's debug log checking `if ( ! did_action( 'template_redirect' )` here:
https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd7[…]inc/classes/subscriber/Optimization/class-buffer-subscriber.php

**Additional context**

**Slack convo:** https://wp-media.slack.com/archives/C43T1AYMQ/p1615557511037100

**Comment by piotrbak** [comment]
We didn't receive enough customer/support team feedback to implement this in the nearest future. Feel free to reopen.
