### ISSUE TITLE
Add a UI box to Exclude CSS files from Optimize CSS Delivery

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3672]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but it could be really useful to have a UI box that allows excluding files from Optimize CSS Delivery, for example when we need to resolve a FOUC issue, we recommend the procedure described in this doc: 
https://docs.wp-rocket.me/article/977-exclude-files-from-optimize-css-delivery

This is a complex procedure for customers and it is time-consuming for support agents, it requires WP-Admin + FTP access, you have to edit the plugin on each test, regenerate the CPCSS and test again.

**Describe the solution you'd like**
A UI box to exclude CSS files from Optimize CSS Delivery. 

**Additional context**
It'd be similar to the Defer JS Exclusion box (it is a lifesaver!)

The CPCSS feature might be deprecated in the future in favor of a more advanced one, but in the meantime, until that happens we will still need to do this manually. This is especially important when dealing with Pagespeed CLS cases related to FOUC 
thanks!

**Comment by gevcen** [comment]
This would indeed be a great help !

**Comment by SM-Fahim** [comment]
I came here just to know a similar topic, how to solve the FOUC issue when the optimized CPCSS option is enabled, even if it's manual. Looks like I found the tool, but any detailed documentation?

**Comment by gevcen** [comment]
Really looking forward to this, it would make the job so much easier!

**Comment by NataliaDrause** [comment]
Same request in this ticket: https://secure.helpscout.net/conversation/1547214807/272667?folderId=3864740

**Comment by piotrbak** [comment]
The recommended solution is currently RUCSS. Feel free to revisit if needed.
