### ISSUE TITLE
rocket_partial_preload_batch clogging the database

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3680]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

There are a few tickets where the database is clogged by `rocket_partial_preload_batch` entries coming from our partial preload feature.

In the case I investigated, this was happening because of high-frequency cache clearing, triggered by a plugin that updated WooCommerce products. Each time `clean_post_cache` fired, and after that `rocket_clean_post()`.

The purged URLs were pushed to the preload queue and ended up having more than 500,000 entries in the options table.
This resulted in `error 404` for URLs that were in the batches, but in the meantime have been removed from the website.

Noteworthy is that the batches were processed even when the **Activate preloading** feature was disabled. This is because we are not checking if preload is enabled here:
https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd73/inc/Engine/Preload/PartialPreloadSubscriber.php#L185

Bailing out there if preload isn't active can safeguard the process:
```
		if ( ! $this->options->get( 'manual_preload' ) ) {
			return;
```
**To Reproduce**
1. Run a script to emulate high-frequency cache clearing.
2. Search in the database for `rocket_partial_preload` using:
```mySQL
SELECT * FROM `wp_options` WHERE `option_name` LIKE "rocket_partial_preload%"
```

**Expected behavior**

We should safeguard the database from such edge cases when preload is used.

For example:
1. We could delete the batches when **Activate preloading** is disabled.
2. We can limit the number of batches in the database.
3. Stop processing the batches, when **Activate preloading** is disabled. This, in case "1" isn't an option.

**Additional context**

will prevent this issue from happening, when preload isn't 
**Related ticket:** https://secure.helpscout.net/conversation/1451291228/246821/ 
**Slack conversation:** https://wp-media.slack.com/archives/C43T1AYMQ/p1615565210046300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1539213429/270611

**Comment by NataliaDrause** [comment]
Related ticket: https://secure.helpscout.net/conversation/1561866652/276589/

This is also causing multiple PHP Warnings related to preload process:
`PHP Warning: Invalid argument supplied for foreach() in /www/wp-content/plugins/wp-rocket/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php on line 314`

PHP Warnings don't stop logging even when Preload is disabled.

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1575885646/281080?folderId=3572910

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1736195549/315811

**Comment by camilamadronero-zz** [comment]
New case https://secure.helpscout.net/conversation/1792952411/327251/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1876516229/341827/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1934976164/351286?folderId=377611

**Comment by camilamadronero-zz** [comment]
related https://secure.helpscout.net/conversation/1946719617/355394/

**Comment by CyberCr33p** [comment]
Any progress in this?
