### ISSUE TITLE
Whitespace added when Combine JS extracts inline scripts containing CDATA

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3681]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version YES
- Used the search feature to ensure that the bug hasn’t been reported before YES

**Describe the bug**
When an inline script contains CDATA with the following structure:
```
<script type="text/javascript" id="script-id">
/* <![CDATA[ */
var var_name = {"cur":{"title":"content"},"version":"1.1","currency":"EUR"};
/* ]]> */
</script>
```
and Combine JS is enabled, the inline script is combined but a line of whitespace is left in the HTML, where the inline code was present when we remove the script.

If the CDATA lines are removed, then the <script> is extracted without leaving whitespace behind.

**To Reproduce**
1. Add the following <script> code to the HTML: https://snippi.com/s/b2ju7gt
2. Enable Combine JS
3. Check the source code
4. See the white lines replacing the inline scripts in the HTML

**Expected behavior**
No white line should be added when replacing a script tag 

**Screenshots**
Example of the behavior https://jmp.sh/uxBw8EZ

**Additional context**
related ticket: https://secure.helpscout.net/conversation/1443591678/244523?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
I can reproduce this, not only for inline scripts, but also for script with a `src` attribute, and the same for CSS files when using combine CSS.

We currently strip the corresponding HTML code from the page HTML, but we don't remove the line it was on, so any line break/new line is preserved, which explains the spacing.

That said, it has no impact on functionality, and likely no impact on performance.

@wp-media/productrocket Is it something that we want to change? I don't know if there is any value working on this.

**Comment by GeekPress** [comment]
@Tabrisrp Does the fix to resolve this issue will be easy to implement and without risks to trigger another issue?

**Comment by remyperona** [comment]
I believe so, the idea would to be remove the matched content + any whitespace after it, instead of just the matched content.

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
