### ISSUE TITLE
We are getting cache issues in our website.

### ISSUE THREAD

**Issue by ShujaShah** [wp-media/wp-rocket#3686]
Hi there, we are having wp-rocket and wp-rocket force page cache plugin set up for page speeds in our website www.k21academy.com, and after setting these plugins up, we are encountering a problem for some trainees, when they log in and click on a course they automatically get logged off.... this behaviour is fixed in most of the cases when they clear the caches. 

Please let me know whether there is a particular setting or i am missing something..

Thanks and regards

Shuja Shah

**Comment by GeekPress** [comment]
Hi @ShujaShah,

Please open a ticket to get help from our support engineers: https://wp-rocket.me/support/
