### ISSUE TITLE
GoDaddy VIP - Varnish cache isn't cleared in sync with WP Rocket's

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3690]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On GoDaddy VIP, the Varnish's cache isn't cleared, when WP Rocket's cache is cleared.

This is because the following check is returning `false`:
https://github.com/wp-media/wp-rocket/blob/2be5659b88d0b6e279a239adbbb8e9ea6208698a/inc/3rd-party/hosting/godaddy.php#L104

The `vip()` method is defined in the `Helpers` trait in:
`/gd-system-plugin/includes/trait-helpers.php`

**To Reproduce**

1. Go to a GoDaddy VIP site.
2. Check the `age` header for the homepage.
3. Clear WP Rocket's cache.
4. Visit the homepage and check the `age` header again. It will have increased, instead of being `0`, or a value lower than step 2.

**Expected behavior**

Cache clearing should be done in sync.

**Additional context**

On the customer's site, I tried the following:
```PHP
if( ! ( defined( 'GD_VIP' ) ? (string) GD_VIP : false ) ){
	return;
}
```

This is what the `vip()` method is doing in the first place.

This cleared Varnish's cache when WP Rocket's cache was cleared.

**Related tickets**
* https://secure.helpscout.net/conversation/1453393326/247480/
* https://secure.helpscout.net/conversation/1433880108/241700/

**Slack Conversation**
https://wp-media.slack.com/archives/C43T1AYMQ/p1614957546110100

A copy of GoDaddy's mu-plugin can be found [here](https://wp-media.slack.com/archives/C43T1AYMQ/p1614958304111600?thread_ts=1614957546.110100&cid=C43T1AYMQ).

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1461226799/249873/

**Comment by engahmeds3ed** [comment]
We found the class still there but we requested access from customer and waiting for it

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
I can see the issue on the code level also @vmanthos and @alfonso100 confirmed that everything is working when we remove mentioned check.

**Identify the root cause**
On this line
https://github.com/wp-media/wp-rocket/blob/cf8b0b647456783d62d9f180b8e71643fe75d763/inc/3rd-party/hosting/godaddy.php#L104

we use wrong namespace `WPass` instead of `WPaas`

**Scope a solution**
1. Adjust namespace to use `WPaas`.
2. Refactor the full file to be under our new structure.

**Estimate the effort**
[S]

**Comment by engahmeds3ed** [comment]
We tried this fix on one of our customer's site and it's working properly.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1532820060/269048?folderId=377611
The fix suggested above worked to purge the GD cache in sync.

**Comment by vmanthos** [comment]
https://secure.helpscout.net/conversation/1550383886/273586/
