### ISSUE TITLE
WPML Multi-Domain Setup Sitemap Preloading does not take host into account

### ISSUE THREAD

**Issue by jorgemartine00** [wp-media/wp-rocket#3696]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using WP-Rocket with WPML some sites use the same sitemap, and the sitemap has the same path to pages only a different host name, pages won't be created as WP Rocket assumes the URL has been cached already.

**To Reproduce**
1. Set up a WordPress site with WP Rocket and WPML
2. Setup WPML to use different domains per language
3. Make sure pages are the same in all sitemaps across all domains
4. Trigger cache clearing and preloading

**Expected behavior**
All config files and cache for each of the domains should be created.

**Additional context**

https://github.com/wp-media/wp-rocket/blob/e154e170c205534398247e935cc5eaef070eaeeb/inc/Engine/Preload/Sitemap.php#L259-L263
fills $urls array with this url if it's not found and we use $path as a key
and this path is coming from here
https://github.com/wp-media/wp-rocket/blob/e154e170c205534398247e935cc5eaef070eaeeb/inc/Engine/Preload/Sitemap.php#L243
and this method is defined here
https://github.com/wp-media/wp-rocket/blob/e154e170c205534398247e935cc5eaef070eaeeb/inc/Engine/Preload/AbstractPreload.php#L131
and it returns the url path + query strings and doesn't take into account the domain itself (host)

**Proposed solution**
Replace the code [here](https://github.com/wp-media/wp-rocket/blob/e154e170c205534398247e935cc5eaef070eaeeb/inc/Engine/Preload/AbstractPreload.php#L131)

$path  = (array) wp_parse_url( $url );	
$query = isset( $path['query'] ) ? $path['query'] : '';	
$path  = isset( $path['path'] ) ? $path['path'] : '';	
$path  = strtolower( trailingslashit( $path ) );

and add:

$path  = (array) wp_parse_url( $url );
$query = isset( $path['query'] ) ? $path['query'] : '';
**$path_host = $path['host'];**
$path  = isset( $path['path'] ) ? $path['path'] : '';
**$path = $path_host . $path;**
$path  = strtolower( trailingslashit( $path ) );

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jorgemartine00** [comment]
Related case: https://secure.helpscout.net/conversation/1455258259/248107/

**Comment by optimiertes** [comment]
Do you have plans on fixing this? It basically makes cache preloading for people using WPML with multiple domains useless.

**Comment by piotrbak** [comment]
It's fixed starting from 3.12 WP Rocket version.
