### ISSUE TITLE
Commented-out @import rules are imported during CSS minification/combination

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3697]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When a child theme's CSS file includes a commented out `@import` rule, that's properly processed during CSS minification/combination:
```CSS
/* @import url("../foundation.css");  */
```

This isn't happening when that is added to the parent theme.

**To Reproduce**
1. Add a commented-out `@import` rule in the `style.css` of a child theme.
2. Enable CSS minification/combination.
3. Search for rules added by the commented-out `@import` rule.
4. Those should be there.

**Expected behavior**

Commended-out `@import` rules should be ignored.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1457846016/248876/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
