### ISSUE TITLE
Tailwind spacing CSS containing calc() function breaks during minification

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3698]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] - Made sure you’re on the latest version
- [x] - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Tailwind spacing CSS that contains calc() functions breaks when Minify CSS is enabled.
Ref. to the spacing CSS in Tailwind: https://tailwindcss.com/docs/space

**To Reproduce**

1. Add the Tailwind spacing CSS to the `style.css`. Example:
```
.myblock {
	margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse)));
        margin-bottom: calc(0.25rem * var(--tw-space-y-reverse));
}
```
2. Enable _Minify CSS_ option
3. Check the minified `style.css`. The markup will be the following:
```
.myblock{
margin-top:calc(0.25rem *)calc(1 - var(--tw-space-y-reverse)));
margin-bottom:calc(0.25rem * var(--tw-space-y-reverse))}
```
There is a closing bracket added after the `*`.

**Expected behavior**
No additional closing bracket should be added. The CSS should not break.

**Screenshots**

Original markup:
![image](https://user-images.githubusercontent.com/60236665/111973577-ef892180-8afe-11eb-840e-5550820066e1.png)
Screenshot URL: https://jmp.sh/j39vFK3

After Minify CSS applied:
![image](https://user-images.githubusercontent.com/60236665/111973779-252e0a80-8aff-11eb-90ab-079246d11258.png)
Screenshot URL: https://jmp.sh/7rGdxm8

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related ticket: https://secure.helpscout.net/conversation/1458875350/249190/

**Comment by GeekPress** [comment]
@Tabrisrp I suppose we depend on the minify library about this kind of bug?

**Comment by remyperona** [comment]
Yes we are

**Comment by Mai-Saad** [comment]
@Tabrisrp I can see the main issue affecting social media links icons fixed here https://new.rocketlabsqa.ovh/3698-2/ but for some reason when minify CSS is enabled, the logo of the page is removed => will we fix this here or open a new ticket?

**Comment by remyperona** [comment]
I can't tell without seeing the issue, to know if it's related to the change or something else

**Comment by Mai-Saad** [comment]
@Tabrisrp I can see it too on the trunk so I think it's not related to the current change
**Update:** Thanks to @piotrbak, the problem is that the logo relative URL in the template is written to the test domain and it's not there

**Comment by remyperona** [comment]
Ok then all good
