### ISSUE TITLE
AddDefaultCharset directive added to .htaccess missing $charset value causing internal server error. Function missing logic to check returned value.

### ISSUE THREAD

**Issue by chriseagle** [wp-media/wp-rocket#3704]
**Describe the bug**
AddDefaultCharset from function "get_rocket_htaccess_charset()" returns without a $charset value via get_bloginfo(). This function contains no logic to check the emptiness of the return from get_bloginfo(). Would recommend checking $charset before creating and appending rules. 

On Cloudways (host) this caused an internal server error and took down 4 sites on a multisite setup. 

**To Reproduce**
Not been able to reproduce, manually fixed issue by adding 'UTF-8' after directive via ssh.

**Expected behavior**
To not crash the site.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by chriseagle** [comment]
Version 3.8.2

**Comment by NataliaDrause** [comment]
This might be related ticket: https://secure.helpscout.net/conversation/1460752626/249734/

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `get_rocket_htaccess_charset()`, check if the value of `$charset` is empty before trying to use it. If empty, bail-out with an empty string.

### Estimate the effort ✅
Effort `[XS]`

**Comment by brandonkramer** [comment]
I experienced this problem multiple times with WP Rocket 3.9.1.1 and had to reset the .htaccess somehow also on  Cloudways (host). The error caused an internal server error and made the website non-functional.

![image](https://user-images.githubusercontent.com/17217494/139517619-37574c8d-6fd8-4703-a2d1-2e34a133bed5.png)

Anything I can do or change to prevent this problem from happening again?
