### ISSUE TITLE
WPR not displayed in admin bar although it is already activated after changing WP version

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3705]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x]  Made sure you’re on the latest version 
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WPR is not displayed in the admin bar after upgrading WP to compatible version

**To Reproduce**
Precondition:
WPR needs min WP version x i.e 5.3
1. WP version < x is installed i.e 5.2
2. install and activate WPR => message displayed that WPR needs to be downgraded or WP needs to be upgraded
3. upgrade WP to version x+ i.e 5.3+
4. go back to plugins view
5. WPR is active while not appearing in admin bar

**Expected behavior**
WPR is displayed in admin bar as long as it is active

**Screenshots**
![Screenshot from 2021-03-23 10-18-41](https://user-images.githubusercontent.com/76941962/112158101-8550a980-8bf0-11eb-90cd-f0eb1e8f5270.png)

**Additional context**
- Deactivating WPR plugin after step 3 then activating it will fix the problem and will appear normally in admin bar
- If WPR was installed & activated while WP >5.3 then downgraded WP to < 5.3 then upgrade WP to > 5.3 , WPR will be displayed normally in admin bar
- tested on the latest 3.9 alpha-1 version

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
