### ISSUE TITLE
Autoptimize - rocket-delay-js-js-after script and delayed scripts are being combined by Autoptimize 

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#3707]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔
- Used the search feature to ensure that the bug hasn’t been reported before ✔

**Describe the bug**
When Delay JavaScript Execution and JavaScript combination feature from Autoptimize are active, the Delay JavaScript Execution Script (rocket-delay-js-js-after) and all the delayed scripts (data-rocketlazyloadscript ones) are combined and disappear from the HTML, this prevents the delayed scripts for being executed.

**To Reproduce**
1. Activate Delay JavaScript Execution on WP Rocket
2. Add a script to be delayed to the "Scripts to delay" box if needed (Example GA, GTM)
3. Activate JavaScript combination on Autoptimize (Aggregate JS-files option) and "Also aggregate inline JS" if needed.

**Expected behavior**
These scripts shouldn't be combined by Autoptimize or WP Rocket should disable Delay JavaScript execution when Aggregate JS-files option is active on Autoptimize.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/112227825-40337400-8bfe-11eb-905e-67976bb367c7.png)

**Additional context**
Because the delayed scripts are "Empty" (there is nothing between the <script> tags and src is not present), they are just removed from the HTML and in the combined file they do not exist, since they are in the data-rocketlazyloadscript attribute.

Excluding **_data-rocketlazyloadscript_** and **_rocket-browser-checker-js-after_** from Autoptimize solves the problem, but by the moment this should be done manually from Autoptimize UI: 
![image](https://user-images.githubusercontent.com/13713107/112327862-c940be80-8c83-11eb-9f77-9220639a2453.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by sandyfzu** [comment]
A related case: https://secure.helpscout.net/conversation/1452663967/247296/

**Comment by Mai-Saad** [comment]
This ticket is not valid with the new delay JS, we don't have `rocket-delay-js-js-after`, and delayed scripts are preserved in HTML using 3.10.3

**Comment by piotrbak** [comment]
@Mai-Saad Are we able to delay their combined file at all?

**Comment by piotrbak** [comment]
We can close it then. Other conflict between DelayJS and JS Aggregation will be solved here: https://github.com/wp-media/wp-rocket/pull/4501
