### ISSUE TITLE
Delay JavaScript execution - Some keywords prevent Delay JS script from executing (can affect itself)

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#3708]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔
- Used the search feature to ensure that the bug hasn’t been reported before ✔

**Describe the bug**
When Delay JavaScript execution is enabled and a keyword is added that match with a string in the "rocket-delay-js-js-after" script https://snippi.com/s/4bmx88f, the script is converted to base64, so it won't be executed.

Example, if you add "document" to the Scripts to delay box, this issue appears.

**To Reproduce**
1. Activate Delay JavaScript execution
2. Add a keyword that can have a match with the code of "rocket-delay-js-js-after", something like "document"
3. Go to the page and check the source code

**Expected behavior**
Delay JavaScript execution should not affect itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/112236440-74169580-8c0e-11eb-989f-e2198f012415.png)
Adding the keyword "document"
![image](https://user-images.githubusercontent.com/13713107/112235996-bbe8ed00-8c0d-11eb-8390-bd3f0a59226a.png)
![image](https://user-images.githubusercontent.com/13713107/112236287-27cb5580-8c0e-11eb-9548-502c95a3597e.png)
![image](https://user-images.githubusercontent.com/13713107/112236328-3e71ac80-8c0e-11eb-83e4-d1321eb992a5.png)

**Possible solution**
We can check if the element has the id "rocket-delay-js-js-after" before processing it.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
With our new Delay JS option scheduled for 3.9, this problem will be automatically fixed. So I'm closing this issue.
