### ISSUE TITLE
UI suggestion: Notification and list of the pages on which an option has been turned off

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3710]
A classic ticket is "This option doesn’t work on this page even if it’s active in my settings"... When we check, the "issue" is that the option has been simply turned off by the user, on WP Rocket's options page level. 

I propose to show a warning below the option only when this option has been turned off on WP Rocket's options page level. 

A link could open a pop-up to quickly show the list of the pages concerned but this exclusion:
![Capture d’écran 2021-03-24 à 11 07 07](https://user-images.githubusercontent.com/11939512/112293998-06607d00-8c93-11eb-9666-83b2d3dd62fa.png)

**Comment by vmanthos** [comment]
Following today's next sprint meeting, and piggybacking on @WordPresseur's awesome idea, it would be great if **the list of pages offers the ability to directly revert the change from there**.

That is, enable the option, e.g. Combine CSS files, without the need to visit every page separately and use the meta-box there.

**Comment by sandyfzu** [comment]
A case related: https://secure.helpscout.net/conversation/1491823301/258342

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
