### ISSUE TITLE
WP Rocket not compatible with WOOCS - WooCommerce Currency Switcher?

### ISSUE THREAD

**Issue by SM-Fahim** [wp-media/wp-rocket#3715]
**Describe the bug**
The [site](https://shop.derval.ie/) using two currencies, EUR(Default) and GBP. When WP Rocket is enabled, the default changes to GBP. The weirdest thing is that when I disable options from the File Optimization tab one by one, the problem is solved. But when I clear the cache, the problem is again there. Currently, I've disabled all the options on the File Optimization tab, still, the default currency is changed to GBP. Trying /?nowprocket shows EUR as default. 

** Conflicting Plugin **
[WOOCS - WooCommerce Currency Switcher
](https://wordpress.org/plugins/woocommerce-currency-switcher/)

**To Reproduce**
1. Go to [the site](https://shop.derval.ie/)
2. Notice the currency on the top left corner

**Expected behavior**
EUR as default currency when WP Rocket is enabled

**Screenshots**
* [Logged into WP](https://drive.google.com/file/d/1Yxz9_GIdvVqDQt767VbfvRPc98dqPneV/view?usp=sharing)
* [Incognito](https://drive.google.com/file/d/1XqR3N-uGOnraO7vKJkNUNI8-DO8mL-S8/view?usp=sharing)
* [File Optimizatiom tab settings](https://drive.google.com/file/d/1bd5alSQIx2Z98DPToUAyAYHcIAhefDji/view?usp=sharing)

**Additional context**
* When I visit the website from incognito, only then the problem appears. When I'm logged into WP, it's working as expected.
* Even if I change the currency from GBP to EUR, visiting a different page changes it back to GBP.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@SM-Fahim Thanks for reporting the bug.

Can you please open a ticket from here: https://wp-rocket.me/support/?

One of your Rocketeers will try to help to fix your problem. We will like to confirm it's not a configuration problem first. Then, if it's a confirmed bug we can't fix with a WP Rocket configuration, we will re-open this issue.
