### ISSUE TITLE
"Replace YouTube iframe with preview image" is adding empty space

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3716]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When:

1. **Replace YouTube iframe with preview image** is active.
2. The `iframe` is wrapped in `<p></p>`, like this:
```HTML
<p><iframe src="https://www.youtube.com/embed/H1VIxUTzb1I" width="908" height="509" allowfullscreen="allowfullscreen"></iframe></p>
```
adding the YouTube thumbnail takes the processed `<div>`s out of the `<p></p>`, and becomes:
```HTML
<p></p>
<div class="rll-youtube-player" data-src="//www.youtube.com/embed/H1VIxUTzb1I" data-id="H1VIxUTzb1I" data-query="">
   <div data-id="H1VIxUTzb1I" data-query="" data-src="//www.youtube.com/embed/H1VIxUTzb1I">
      <img loading="lazy" alt="" width="480" height="360" src="https://i.ytimg.com/vi/H1VIxUTzb1I/hqdefault.jpg" class="lazyloaded" data-ll-status="loaded">
      <noscript><img src="https://i.ytimg.com/vi/ID/hqdefault.jpg" alt="" width="480" height="360"></noscript>
      <div class="play"></div>
   </div>
</div>
```
The empty `<p>`  gets the following styling:
```CSS
p:empty:before {
    content: "​";
}
```
from `/wp-includes/css/dist/block-library/style.min.css`

and that adds empty space.

**To Reproduce**

1. Activate **Replace YouTube iframe with preview image**.
2. Add a YouTube `<iframe>` using WordPress's classic editor. Make sure an empty line precedes the iframe.
3. Visit the front-end and check the source code. You'll see the following:
![](https://i.vgy.me/tkdw8F.jpg)

**Expected behavior**

Keep the document's structure and created the `<div>`s where they are originally located.

**Additional context**

This is related to WordPress automatically adding `<p>`s as line breaks.
Using the following, resolves the issue: `remove_filter( 'the_content', 'wpautop' );`

**Related ticket:** https://secure.helpscout.net/conversation/1456447455/248469/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
I discussed this with @DahmaniAdame and he brought to my attention that `<p><div></div></p>` isn't valid markup ([reference](https://stackoverflow.com/a/10763952)).

The following source code:
```HTML
<p>
    <div>This is something!</div>
</p>
```
will be converted by the browser to:
```HTML
<p></p>
    <div>This is something!</div>
<p></p>
```

We need to make sure we remove `<p></p>` when processing YouTube `iframe`s and the Replace YouTube iframe with preview image is active.

**Comment by GeekPress** [comment]
I'm not sure we can have an easy workaround. I let the @wp-media/php confirm that or not.

**Comment by remyperona** [comment]
We can't remove parent elements, because we have no way to access it in fact. When we do the search with the RegEx, we match with the specific `iframe` element alone.

The solution could be to use an HTML element that can be part of a block element like the paragraph. For example, replace the `div` by a `span`.

**Comment by GeekPress** [comment]
Ok, thanks for the feedback. As this enhancement won't have any impact on the performance, and it's going to be a pain to implement, let's invalid this request.

@vmanthos Can I let you contact the customer to let him know we won't fix that and why?

**Comment by GeekPress** [comment]
> The solution could be to use an HTML element that can be part of a block element like the paragraph. For example, replace the div by a span.

If I'm correct, the span is an inline element that can't contain a block element like div, isn't it?

**Comment by GeekPress** [comment]
Or does the solution is to replace all `<div> `to `<span>` like:

```
<p>
<span class="rll-youtube-player" data-src="//www.youtube.com/embed/H1VIxUTzb1I" data-id="H1VIxUTzb1I" data-query="">
   <span data-id="H1VIxUTzb1I" data-query="" data-src="//www.youtube.com/embed/H1VIxUTzb1I">
      <img loading="lazy" alt="" width="480" height="360" src="https://i.ytimg.com/vi/H1VIxUTzb1I/hqdefault.jpg" class="lazyloaded" data-ll-status="loaded">
      <noscript><img src="https://i.ytimg.com/vi/ID/hqdefault.jpg" alt="" width="480" height="360"></noscript>
      <span class="play"></span>
   </span>
</span>
</p>
```

**Comment by remyperona** [comment]
Yes, the proposed solution would be to replace in our code all `div` to `span` (and use CSS to make them display as block or inline-block)

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1487255691/256982?folderId=1213662

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
