### ISSUE TITLE
CDN srcset rewrite - Additional Variation Images Gallery for WooCommerce breaks

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3718]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The variable products gallery that's added by the [Additional Variation Images Gallery for WooCommerce](https://.wordpress.org/plugins/woo-variation-gallery/) plugin breaks when CDN rewriting is active.

They are using the following inline script: [https://snippi.com/s/0vxl9t9](https://snippi.com/s/0vxl9t9)

This includes `srcset="{{data.srcset}}`.

Our [RegEx](https://regex101.com/r/0jVKfX/1) picks that up, and rewrites it to this `srcset="https://adfa3ad.rocketcdn.me/{{data.srcset}}` breaking the functionality.

**To Reproduce**

1. Add the following script on a page: [https://snippi.com/s/0vxl9t9](https://snippi.com/s/0vxl9t9)
2. Enable CDN rewriting.
3. The `srcset="{{data.srcset}}` will be rewritten.

**Expected behavior**

We should have a way to exclude such scripts from CDN rewriting.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1450824927/246580?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1536021331/269823/
Excluding `{{data.srcset}}` from the CDN worked.

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1630463365/294577/

**Comment by camilamadronero-zz** [comment]
New ticket https://secure.helpscout.net/conversation/1835826416/335419/

**Comment by camilamadronero-zz** [comment]
related https://secure.helpscout.net/conversation/2000992076/366738/

**Comment by piotrbak** [comment]
It should be fixed here:
https://github.com/wp-media/wp-rocket/pull/4535
