### ISSUE TITLE
CDN CNAME prevent minification of external js scripts although CDN feature isnot activated

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3719]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Minification to external js is not working if CNAME is set while CDN is disabled

**To Reproduce**
Precondition:
Having page with external js i.e `<script src="https://mega.wp-rocket.me/qa/wp-content/rocket-test-data/scripts/print-helloworld.js"></script>
`
1. In WPR set CNAME to test while keep CDN unchecked
2. Enable js minification
3. open the page that contains external js and check source
4. external js is not minified

**Expected behavior**
external js is minified

**Screenshots**
![Screenshot from 2021-03-26 09-37-25](https://user-images.githubusercontent.com/76941962/112598231-f2458880-8e16-11eb-9ac8-818c8fa58390.png)

**Additional context**
- Used WPR settings 
[wp-rocket-settings-2021-03-26-605d921a4f780.zip](https://github.com/wp-media/wp-rocket/files/6210152/wp-rocket-settings-2021-03-26-605d921a4f780.zip)
- Removing CNAME or enable CDN will fix the problem and the external js file will be minified
- Tested on https://new.rocketlabsqa.ovh/ and local using trunk

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Wasn't able to reproduce this on the fresh settings, only when using the ones coming from this issue. In our debug log it stops here:
![image](https://user-images.githubusercontent.com/26767037/112623511-5a4e9b80-8e24-11eb-92f3-df85293255a4.png)

**Comment by piotrbak** [comment]
No further feedback here, and we couldn't reproduce it.
