### ISSUE TITLE
Excluded js files from load js deferred is affecting combine js although load js deferred is disabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3721]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Combine js only combine 1st URL in source incase it was excluded from load js deferred while load js deferred is unchecked

**To Reproduce**
Precondition:
1- Exclude from load js deferred` /wp-content/rocket-test-data/scripts/print-helloworld.js` then uncheck load js deferred
2- Page with script including excluded URL in header and in body i.e page template http://snippi.com/s/15fg03d

1. In WPR -> file optimization, enable load js deferred and add in excluded files `/wp-content/rocket-test-data/scripts/print-helloworld.js`
2. Uncheck load js deferred
3. enable minify js and combine js then save
4. open the page containing mentioned snippi and check source
5. js files mentioned in head aren't combined while for those in body, only the 1st URL gets combined

**Expected behavior**
All js files be combined and excluded js files shouldn't affect other features since it`s related feature is disabled

**Screenshots**
![Screenshot from 2021-03-26 11-41-58](https://user-images.githubusercontent.com/76941962/112613020-502e9c00-8e28-11eb-882e-e77f72eb764f.png)

**Additional context**
- same occurs if user insert header and footer plugin then add 
`<script src="/wp-content/rocket-test-data/scripts/print-helloworld.js"></script>
<script src="https://mega.wp-rocket.me/qa/wp-content/rocket-test-data/scripts/print-helloworld.js"></script>` in header/body and footer + precondition point 1 => will result in not combining all js 
![Screenshot from 2021-03-26 11-39-45](https://user-images.githubusercontent.com/76941962/112612909-28d7cf00-8e28-11eb-94c2-984ca35d65b7.png)
- tested local and on https://new.rocketlabsqa.ovh/
- Removing the excluded URL from load js deferred will fix the problem
- Used WPR settings 
[wp-rocket-settings-2021-03-25-605cb70aba287.zip](https://github.com/wp-media/wp-rocket/files/6210791/wp-rocket-settings-2021-03-25-605cb70aba287.zip)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
No feedback here, let's close it and reopen if needed.
