### ISSUE TITLE
W3C HTML Validation Error for Google Kit and Delay JavaScript execution

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#3723]
**Before submitting an issue please check that you’ve completed the following steps:**

- [ ] Made sure you’re on the latest version
- [ ] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
https://validator.w3.org/ HTML validation throws 2 errors for Google Analytics and Google AdSense codes inserted using Google Kit when using the Delay JavaScript execution feature.

**To Reproduce**
1. Insert Google Analytics and Google AdSense codes
2. Enable the Delay JavaScript execution feature
3. Run validation at https://validator.w3.org/ 
4. See errors: `Element script must not have attribute async unless attribute src is also specified or unless attribute type is specified with value module.`

**Expected behavior**
The https://validator.w3.org/ HTML validation goes through

**Screenshots**
![image](https://user-images.githubusercontent.com/23031592/112648399-7f88dd00-8e17-11eb-9ce2-dde3d3d3ab10.png)

**Additional context**
Example: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmarketprosecure.ca%2F
Ticket: https://secure.helpscout.net/conversation/1465009071/250925?folderId=2675957
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1616696552145100

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@Tabrisrp Does this problem will be fixed with the new Delay JS?

**Comment by remyperona** [comment]
Yes and no. This specific error will not be there anymore because we preserve the `src` attribute, but there is a new one that will be there instead:

> A script element with a src attribute must not have a type attribute whose value is anything other than the empty string, a JavaScript MIME type, or module.

`<script type="rocketlazyloadscript" data-type="text/javascript" src="test.js" async></script>`

However we have no way to work around that, we need to define a fake type to prevent the file from being executed.

**Comment by GeekPress** [comment]
But in the meantime, this is the only way we have to block the execution of a JS script.

Ok, let's put this into `wontfix`.

@camilamadronero Can I let you contact the customer to let him know why we aren't going to fix that? For his information, these errors don't have any impact on SEO or performance.

**Comment by camilamadronero-zz** [comment]
Customer was updated. Thank you.

**Comment by jekayode** [comment]
Another ticket: https://secure.helpscout.net/conversation/2750293387/520717/
