### ISSUE TITLE
Revise Integration tests relying on live API calls to external resources

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#3725]
Our current integration tests have several instances of relying on actual API calls to external resources. This is bad because our tests fail when those services are not available, and when the variable content from the API changes. It also creates additional unnecessary calls to our APIs.
 
These should be refactored to use the WP_HTTP `pre_http_request` filter to preempt live API calls and inject mock responses that reflect:

1. Expected API responses (Happy paths - 😄 ),
2. Non-200 responses which do not result in WP_Errrors, and
3. Responses resulting in WP_Error returns.

Most of these tests are within the `Engine\License` package, pertaining to User/Pricing API, and promobanners/renewals data. (There may be others.)

**Comment by remyperona** [comment]
In the Cloudflare addon too I think
