### ISSUE TITLE
Add missing image dimensions not working for SVG images

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#3727]
**Before submitting an issue please check that you’ve completed the following steps:**
- Running on the latest version

**Describe the bug**
The "Add missing image dimensions" feature doesn't seem to be working with SVG images. I am talking about SVG images added using the `<img>` tag. I read that the feature will not work on pure SVG. But is that the case for the .svg files as well? If so, isn't there any workaround for this?

**To Reproduce**
1. Visit any page with SVG images (.svg format) with "Add missing image dimensions" feature enabled.
2. Check the HTML output.

**Expected behavior**
Would be great if we add the support for the SVGs as well as more and more websites are adopting the SVG format over traditional image formats.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by gevcen** [comment]
WP Rocket doesn't support SVG format in that feature.
Therefore, it's not a bug but a feature request.

![image](https://user-images.githubusercontent.com/51261962/112760890-e1ed0380-8ff8-11eb-8efc-517d27c38c35.png)

However, I think it's a necessity to support for SVG because competitors do...
If FlyingPress can do it, WP Rocket can certainly do it too :)
https://flying-press.com/changelog/

![image](https://user-images.githubusercontent.com/51261962/112760826-9d616800-8ff8-11eb-8e36-c7a19af1f7d1.png)

**Comment by DahmaniAdame** [comment]
@Tabrisrp @GeekPress 

**Updated to use width and height first, and fallback to viewBox if any or both of the two are missing.**

We can extract dimension from the SVG document width and height, with [viewBox attribute](https://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute) as a fallback if one or both of the above are missing.

We can use a customized replacement for getimagesize() on /inc/Engine/Media/ImageDimensions/ImageDimensions.php ([#L363](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L363) and 
[#L386](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L386).

```
function wpr_getimagesize($image_url)  {

  // Get the extension to know if the file is SVG or not
  $file = new SplFileInfo($image_url);
  $ext  = $file->getExtension();
  
  // Fitler SVG files and extract the dimensions using the width and height attributes with the viewBox attribute as fallback
  // Reference for the viewBox attribute https://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute
  if( $ext === 'svg' ){
    $svgfile = simplexml_load_file(rawurlencode($image_url));
    $width = explode(' ', (string)$svgfile->attributes()->width);
    $height = explode(' ', (string)$svgfile->attributes()->height);
    
    // Use width and height attributes if present
    
    if(!empty($width[0]) && !empty($height[0])) {
        $size[] = $width[0]; // adding width
        $size[] = $height[0]; // adding height
        $size[] = 0; // adding image type - 0 for SVG since there is no IMAGETYPE_SVG constant
        $size[] = 'width="'.$width[0].'" height="'.$height[0].'"'; // adding the dimension on the array
        return $size;
    }
    
    // Fallback to viewBox if one or both width and height attributes are missing from the SVG document
    
    $viewBox = explode(' ', (string)$svgfile->attributes()->viewBox);
    if (!empty ($viewBox)) {
        // width and height are respectively the last two entries in the viewBox tag
        $size = array_splice($viewBox, -2);
        
        // Making the $size array fit the getimagesize() format
        $size[] = 0; // adding image type - 0 for SVG since there is no IMAGETYPE_SVG constant
        $size[] = 'width="'.$size[0].'" height="'.$size[1].'"'; // adding the dimension on the array
        
        return $size;
    }
  }

  $size = getimagesize($image_url);

  return $size;
  
}
```
Tested and it properly added the width and height for an SVG image. 

https://oxygen.adame.io/test-svg-image

![image](https://user-images.githubusercontent.com/1289174/112764327-e1a43680-8fff-11eb-8099-6352c0f46094.png)

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Media\ImageDimensions\ImageDimensions`, we need to update the method `get_image_sizes()`:
- Replace calls to `getimagesize()` by `$this->getimagesize()`

Create a new private method `getimagesize()`, which will use the code Adame wrote as the base. I believe there is some optimizations to do.

Add new test cases for svg files, with width/height attributes, and with viewBox

### Estimate the effort ✅
effort `[S]`
