### ISSUE TITLE
WP eMember : CDN disabled for logged-in users

### ISSUE THREAD

**Issue by aurelienpierre** [wp-media/wp-rocket#3729]
**Describe the bug**
* Users logged-off get served images, CSS and JS from CDN (AWS Cloudfront) as they should. 
* Users logged-in get served from CDN too if WP eMember is disabled
* Users logged-in **do not** get served from CDN if WP eMember is enabled.

**What should happen**

Everyone should get served from CDN, this has nothing to do with actual page/content caching.

**Context**

There is no cookie exclusion set in WP Rocket advanced caching options. This happens on regular pages (not behind the membership wall) as well as member-only pages. It used to work a couple of versions back (I didn't notice when it stopped exactly), so it would seem like a recent cookie exclusion or something.

I read PHP, Javascript, etc. in case you need help.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Hi @aurelienpierre,

Is it possible that this is prevented by WP eMember directly, in their code, by hooking on one of our filters?

I'm saying this because we don't have any compatibility code on our side for this plugin, and the fact that it seems to be working correctly when it is disabled.

**Comment by aurelienpierre** [comment]
What kind of hook should I grep ?

**Comment by aurelienpierre** [comment]
I have searched for `dequeue`, `deregister` and `rocket`, no success.

**Comment by piotrbak** [comment]
Hello @aurelienpierre 

WP Rocket is not doing anything special with WP eMember. I'd suggest contacting our amazing Support Team for further investigation, please share with them this ticket.

I'll close the ticket, but if our Support confirms that there's something we can do on our end, we'll reopen it and plan the fix.

**Comment by aurelienpierre** [comment]
Hi, I ended up disabling WP eMember because it's not the only issue I had with it, so I guess it will never be solved.
