### ISSUE TITLE
.htaccess BasicAuth and Minification

### ISSUE THREAD

**Issue by di5abled** [wp-media/wp-rocket#373]
Hello,

the site we are currently working on is a test environment which is secured with basic auth via `.htaccess`

Because of this when your `inc/functions/minify.php` is making a curl request to minify a file we currently get a 401 error.

I saw you already added the following lines in the `.htaccess` file in the `min/` folder.
```
<FilesMatch "index.php">
  ... allow
</FilesMatch>
```

Our problem is that the filename is `public/index.php` with our server setup and we aren't able to change this at the moment.

We currently serve the base folder which contains, among other things, a `public/` folder and an `.htaccess` file which rewrites all requests to the `public/` folder:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^(.*)$ public/$1 [QSA,L]
</IfModule>
```

And because of this the file path in your `.htaccess` doesn't match our `public/index.php` and we get our 401 exception.

I hacked a little bit in you sourcecode and found two possible solutions:

1. Allow the curl request to use basic auth, maybe via an advanced option setting?
```
curl_setopt( $ch, CURLOPT_USERPWD, "spinnwerk:staging");
curl_setopt( $ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC );
```

2. Adding `public/index.php` to the allowed files in `min/.htaccess`
<FilesMatch "(.*)?index.php">
   ... allow
</FilesMatch>

Would either of this be a possibility?
Or do you have any other advice for us how we could fix this problem?

**Comment by Tabrisrp** [comment]
Hi,

In 3.0, we're going to use wp_remote_get() instead of curl directly for minification. We'll add a filter to add custom arguments passed to wp_remote_get() to allow basic auth and minification to work together.
