### ISSUE TITLE
Uncaught TypeError caused by popover.js script from Wistia

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3730]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] - Made sure you’re on the latest version
- [x] - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
popover.js script from Wistia is throwing the following error in the WP Rocket dashboard in the Admin area:
`Uncaught TypeError: Cannot read property 'popoverBorderWidth' of undefined`

![image](https://user-images.githubusercontent.com/60236665/112799322-7c3b5e80-906e-11eb-9586-e380db818367.png)
Screenshot: https://jmp.sh/513an8v

**To Reproduce**
1. Go to the WP Rocket Settings page in the Admin area
2. Check the JS console for the errors

**Expected behavior**
No errors in the console.

**Additional context**
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1617000708093800

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
The error appears only when the browser window is resized (e.g. the JS console opens). The error is not present if the window stays the same size. Discovered thanks to @piotrbak

**Comment by piotrbak** [comment]
Doesn't seem to be happening anymore.
