### ISSUE TITLE
Don't show wp_cache warning in Site Health for those hosts where we set it to false

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3734]
There are some hosts where we [deliberately set wp_cache to false, like DreamPress](https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/ThirdParty/Hostings/Dreampress.php#L24). 

But in Site Health we are still showing this warning: 
`"WP_CACHE is set to false. The WP_CACHE constant needs to be set to true for WP Rocket cache to work properly".`

So it's confusing for customers. 

**Describe the solution you'd like**
Either:
- We don't show a warning at all for the hosts where we deliberately set it to false. 
- Or, if that's not possible, we change the wording of the warning and include a documentation link

Related tickets: 
- https://secure.helpscout.net/conversation/1434526043/241929/
- https://secure.helpscout.net/conversation/1467711445/251528?folderId=4130683
- https://secure.helpscout.net/conversation/1405183225/233867/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1470452378/252254?folderId=377611
https://secure.helpscout.net/conversation/1439456429/243223/

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Cache\WPCache::add_wp_cache_status_test()`, add a conditional check for the `rocket_set_wp_cache_constant` value. If it returns true, continue, if it returns false, bail-out and return the unchanged `$tests` value.

```
if ( ! (bool) apply_filters( 'rocket_set_wp_cache_constant', true ) ) {
    return $tests;
}
```

Update the related unit/integration tests too.

### Estimate the effort ✅
Effort `[S]`
