### ISSUE TITLE
Specific CPCSS Generation Notice in Sidebar Might be Confusing

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#3737]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The specific CPCSS generation notice that appears in the WP Rocket sidebar when the Optimize CSS delivery is disabled might be confusing. Customers might not see the relation to the Specific CPCSS generation but they could think it's a general warning.

**To Reproduce**
1. Disable Optimize CSS delivery
2. Go to a post/page editor page
3. Scroll down to WP Rocket's sidebar
4. See the notice: https://i.imgur.com/uP6BHts.png -  It might not be linked enough to the specific Optimize CSS delivery sidebar section.

**Expected behavior**
The notice is clearly attached to the Optimize CSS delivery sidebar section.
We could use a box or separators: 
- https://i.imgur.com/uDIRvsV.png
- https://i.imgur.com/ebr3cd0.png

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1469397596/251999/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
