### ISSUE TITLE
Delay JS execution time (LazyLoad Script) - V2

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#3738]
#### What are we proposing to do? 

To build a new way to delay the execution of JavaScript and getting a significant boost on website performance. WP Rocket will delay all JavaScript instead of an inclusion list with the current feature.

#### Why are we doing this? 

With the new Core Web Vitals metrics, the goal for performance tools is to provide the best user experience to deliver as fast as possible content above the fold. To do this, we need to load the images when needed (Lazyload), to avoid render-blocking files (defer JavaScript and defer non-critical CSS), preload critical assets, etc...

Most websites are loading a ton of JavaScript used for non-critical features. With this feature, WP Rocket will preload and delay all JavaScript by respecting the loading order.

As a side effect, it will improve PageSpeed score and loading time.

[Full feature doc](https://docs.google.com/document/d/1s1xbAkFz_o5gK5CtZAGCki-VefBdikIb16dhypv6xsE/edit?usp=sharing)

**Comment by gevcen** [comment]
When reading the phrase "we need to load the images when needed (Lazyload)", does that relate to the issue reported in the ticket https://github.com/wp-media/wp-rocket/issues/3695? Thanks

**Comment by piotrbak** [comment]
@Tabrisrp This LL script should be also excluded:
https://github.com/wp-media/rocket-lazyload-common/blob/bca56461c1126f4e2b7cc567ac457df69700dc38/src/Assets.php#L237

**Comment by piotrbak** [comment]
@Tabrisrp @GeekPress I'm also thinking, should we delay our Critical CSS script? 🤔

**Comment by GeekPress** [comment]
@piotrbak It shouldn't cause any problem.

**Comment by cgold1979** [comment]
The new delay javascript is causing an issue with website monetization as it delays the execution of external header bidding partners lowering viewability and the time it takes to show ads on the site. This will impact many publishers' revenues without them even knowing.

**Comment by Snadex** [comment]
The new update and most probably this feature prevented hubspot forms to load. They were working just fine before.

**Comment by gamersdunia16** [comment]
want to exclude google ads from Delay JavaScript.  I tried by adding two keywords `adsbygoogle.js` and `pagead2.googlesyndication.com` to the exclusion list but it did not work.  any suggestion!!

**Comment by GeekPress** [comment]
@gamersdunia16 Please open a ticket support from here: https://wp-rocket.me/support/

We won't provide you help on Github, it's not the right place.
