### ISSUE TITLE
Regenerate CPCSS progress not displayed in WPR settings when click on WPR settings link in regeneration message (regeneration in plugins view)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3745]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Regenerate CPCSS inside plugins tab of dashboard then clicking on WPR settings link in generation message => will navigate to WPR settings but CPCSS progress is not displayed

**To Reproduce**
1. Open WPR settings -> change anything in cache tab i.e check separate cache for mobile devices and save
2. go to plugins tab in dashboard
3. click on wpr in admin bar -> regenerate CPCSS
4. Click on the link go to WPR settings

**Expected behavior**
CPCSS progress is displayed

**Screenshots**

https://user-images.githubusercontent.com/76941962/113171913-3afea680-9248-11eb-8f72-3f8fe8db69c3.mp4

**Additional context**
Doing same scenario, without change anything in WPR settings, will work fine.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Even if we are on the WPR settings page, clicking regenerate CPCSS in the following scenario won't display the progress notice (tested on 3.10.3):

1- Enable mobile cache
2- Enable OCD => notice of generation is displayed
3- Enable separate cache for mobile
4- Regenerate CPCSS => notice is not displayed although mobile files are created (probably desktop files not updated)

https://user-images.githubusercontent.com/76941962/143264347-16f4fde8-d1b1-432e-aa70-c09925117b89.mp4

**Comment by piotrbak** [comment]
Can't reproduce that one.
