### ISSUE TITLE
Polylang/WooCommerce - Inactive languages cause all pages to be excluded from caching

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3747]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On a WooCommerce site using Polylang with inactive languages, our automatic WooCommerce pages exclusion is causing the `/(.*)` to be added in WP Rocket's configuration file, and this prevents page caching/optimizations from working.

This is because translated "cart", "checkout", "account" URLs for inactive language are set as `draft`.

For such URLs, the following appends `/(.*)` in the `$urls` array.
https://github.com/wp-media/wp-rocket/blob/bb7b907b254366de7da75197d76e9b8bba5ca638/inc/functions/i18n.php#L492

**To Reproduce**

1. Use Polylang on a WooCoomerce site.
2. Add 3 languages and make sure the WooCommerce pages are translated.
3. Disable one of them, and clear WP Rocket's cache.
4. Pages won't be cached.

**Expected behavior**

Caching/optimizations should work regardless of whether languages are inactive.

**Additional context**

We need to check the posts's status before adding that to the array:
```PHP
if ( ! empty( $translations ) ) {
    foreach ( $translations as $post_id ) {
        if( 'publish' !== get_post_status( $post_id ) ){
            continue;
        }
    $urls[] = wp_parse_url( get_permalink( $post_id ), PHP_URL_PATH ) . $regex;
    }
}
```

**Related ticket:** https://secure.helpscout.net/conversation/1458081896/248930?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
We're blocked on this issue because we can't reproduce it on our tests with the steps provided in the issue description.

**Comment by vmanthos** [comment]
@Tabrisrp @Mai-Saad I have reached out to the customer asking for access to their site, so I can see what's missing from the "steps to reproduce" process.

I'll update this thread as soon as I have something.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1551325854/273854

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.

**Comment by webtrainingwheels** [comment]
related: https://secure.helpscout.net/conversation/3120887812/595655?viewId=377611
Dutch checkout page is in draft and this exclusion is added to the config file: `/??(.*)|`

`$rocket_cache_reject_uri = '/(?:.+/)?feed(?:/(?:.+/?)?)?$|/(?:.+/)?embed/|/en/checkout/??(.*)|/??(.*)|/en/basket-winkelmandje/?|/winkelmandje/?|/en/my-account/??(.*)|/my-account/??(.*)|/(index.php/)?(.*)wp-json(/.*|$)';`
