### ISSUE TITLE
[REQUEST] Properly opt out of tracking

### ISSUE THREAD

**Issue by androidacy-user** [wp-media/wp-rocket#3751]
**Is your feature request related to a problem? Please describe.**
There's a big ol' switch on the front page that says Rocket Analytics, and it's off. So the plugin isn't tracking me, right? Seems wrong, actually!

**Describe the solution you'd like**
Let's take a look in network requests. What's this? Several requests to `https://distillery.wistia.com/x` especially on user actions. They're getting blocked by uBlock, of course, but damn that's a lot of them. There's also requests to `https://pipedream.wistia.com/mput?topic=metrics`. Even a tracking gif: `https://fast.wistia.com/assets/images/blank.gif`

Thing is, didn't I _opt out_ of analytics? Doesn't seem so!

When the switch is off, please ensure absolutely no tracking is done, nor metrics collected.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by GeekPress** [comment]
Hi @androidacy 

Wistia is the tool we are using to display the video you will find in the Tutorials tab. There is no relation with Rocket Analytics.
