### ISSUE TITLE
Cache clearing not working for CPTs with base using non-English characters

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3757]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

For CPTs, e.g. WooCoommerce products, where the base has been set to non-English characters, post cache clearing isn't working.

For example, the following:
`https://www.example.com/προιόν/nihil-commodi-illo-ad`

is saved in:
`/wp-content/cache/wp-rocket/www.example.com/%cf%80%cf%81%ce%bf%ce%b9%cf%8c%ce%bd/nihil-commodi-illo-ad`

When we are getting the `$permalink`:
https://github.com/wp-media/wp-rocket/blob/bb7b907b254366de7da75197d76e9b8bba5ca638/inc/common/purge.php#L48

that looks like this:
`https://www.example.com/προιόν/nihil-commodi-illo-ad`

When that ends up in `rocket_clean_files()`,  `get_rocket_parse_url( $url )` doesn't encode it:
https://github.com/wp-media/wp-rocket/blob/bb7b907b254366de7da75197d76e9b8bba5ca638/inc/functions/formatting.php#L363

This results in the cache not getting cleared because the path isn't matched on the disk.

I think the issue here is `get_rocket_sample_permalink()`
https://github.com/wp-media/wp-rocket/blob/bb7b907b254366de7da75197d76e9b8bba5ca638/inc/functions/posts.php#L17-L73

**To Reproduce**

1. On a WooCommerse site, change the base for the product PT, to use non-English characters:
![](https://i.vgy.me/iO0jcz.jpg)
2. Make sure a product is cached.
3. Clear its cache.
4. Check its folder in `/wp-content/cache`.

**Expected behavior**

The cache should be cleared regardless of the language the custom base is set to.

**Additional context**

In my local test site, adding the following:
```PHP
$permalink = rawurlencode( $permalink );
```
after this line:
https://github.com/wp-media/wp-rocket/blob/bb7b907b254366de7da75197d76e9b8bba5ca638/inc/common/purge.php#L48

allowed me to clear the cache.

**Related ticket:** https://secure.helpscout.net/conversation/1468848539/251818?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by SenseAndImage** [comment]
I am having a problem that is very much related to that:

https://mydomain.tld/artist/Stefano-della-Bella/Verschiedene-Tierköpfe-Têtes-de-différents-animaux-Drei-Kamelköpfe/
Is not being cleared since it is saved as /artist/Stefano-della-Bella/Verschiedene-Tierk%c3%b6pfe-T%c3%aates-de-diff%c3%a9rents-animaux-Drei-Kamelk%c3%b6pfe on disk.

Currently I have to fall back to deleting everything inside /artist/ effectively clearing 1000s of pages just because some of them are not picked up correctly.

**Comment by piotrbak** [comment]
It's fixed in 3.13.4.
