### ISSUE TITLE
Conditionally disable plugins + selected CSS/JS files if don't need them

### ISSUE THREAD

**Issue by serg-pervushin** [wp-media/wp-rocket#3758]
It will be great if we can disable plugins or parts of them that are not needed on certain pages (js/css). Now you have to use an additional plugin for these purposes, such as this one https://gonzalesplugin.com/

**Comment by GeekPress** [comment]
Hi @serg-pervushin,

Please vote for this feature here: https://feedback.wp-rocket.me/27
