### ISSUE TITLE
Lazyload content

### ISSUE THREAD

**Issue by serg-pervushin** [wp-media/wp-rocket#3759]
I don't know how they did it, but I checked it on one of the sites and it's just a great feature! Rather, it does not always work stably and requires careful use, but it helps a lot.

Here's what they have written briefly about this feature: «If you have any dynamic part on your page you don’t need to exclude it from caching. You can let Swift Performance to cache the whole page, and use AJAX to load specific widgets, Gutenberg blocks, or shortcodes.»

p.s. + they have a free unlimited image optimizer and a webp generator. This of course interested me a lot.

**Comment by GeekPress** [comment]
Hi @serg-pervushin 

We are working on Lazyload Content feature too. It won't be as SF is doing. It will be totally innovative. 

For image optimizer inside WP Rocket, we won't do it. We have our own service for this: Imagify.
