### ISSUE TITLE
Auto refresh is needed when change adds-on settings

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3761]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When activating/deactivating cloudflare and/or Sucuri, the note displayed/hidden in CDN tab won't be displayed till refresh the page

**To Reproduce**
Precondition:
WPR adds-on are disabled

1. Go to WPR settings -> adds-on
2. Enable cloudflare
3. Open CDN tab
4. The message " Cloudflare Add-on is currently enabled. Configuration of the CDN settings is not required for Cloudflare to work on your site." won't be displayed under CDN section till refreshing the page

**Expected behavior**
Message displayed in CDN without any need to refresh the page

**Screenshots**

https://user-images.githubusercontent.com/76941962/113569526-f477c600-9612-11eb-8f2c-cae36730a820.mp4

**Additional context**
- If we disable cloudflare after the message was displayed and open CDN , the message will still be there although cloudflare is disabled (until we refresh the page)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
