### ISSUE TITLE
Understanding "exlude external JS"

### ISSUE THREAD

**Issue by nicomollet** [wp-media/wp-rocket#377]
Hello,

Before WP Rocket 2.9.6, my website worked fine, with Gravity Forms plugin, Jquery library on Cloudflare, and WP Rocket "JS minification & concatenation" enabled.

I know WP Rocket 2.9.6 excludes cdnjs.cloudflare.com from JS minification.
My Jquery in enqueued in footer, from Cloudflare. But Gravity Forms sometimes needs Jquery to be loaded in header.

** Enqueue Jquery from Cloudflare , in footer** 
```php
wp_enqueue_script('jquery', '//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js', array(), null, true);
```

**Result with WP Rocket 2.9.5, no JS error since Jquery is loaded first**
```html
<html lang="fr-FR">
<head>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
<script src="http://www.domain.com/wp-content/cache/min/1/f044706d5b88c759d17c66c558477c23.js" data-minify="1"></script><!-- Gravity forms scripts-->
```

**Result with WP Rocket 2.9.6, Jquery not defined on the first minified JS**
```html
<html lang="fr-FR">
<head>
<script src="http://www.domain.com/wp-content/cache/min/1/f044706d5b88c759d17c66c558477c23.js" data-minify="1"></script><!-- Gravity forms scripts-->
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
```

In the end, I don't understand the "Exclude Cloudflare from JS minification". Is there something I can do to avoid my "Jquery not defined" errors?
I temporarly disabled Jquery from Cloudflare to remove errors.
Thanks

**Comment by Tabrisrp** [comment]
Don't replace the jQuery version included in WP core by an external one, it's too problematic

**Comment by nicomollet** [comment]
Alright, I am now using Jquery from WP core, it's better.
But what I want is, move all JS to the footer doesn't work as expected. Now combined JS (containing jquery) is loaded in the header, and is blocking rendering unfortunately. 

I managed to do it with WP Rocket 2.9.5. I will try to achieve this later.
Thanks

**Comment by nicomollet** [comment]
I gave up trying to combine with WP Rocket and put Jquery from WP core in the footer.

My web server is now HTTP/2, so I decided to disable "combine", and all JS are in the footer.
