### ISSUE TITLE
Caching issue with Avada theme -> Container Element -> Container Publishing Date

### ISSUE THREAD

**Issue by Matthiator** [wp-media/wp-rocket#3771]
We use the [Avada](https://avada.theme-fusion.com/) theme with container element and the option [Container Publishing Date]( https://theme-fusion.com/documentation/avada/elements/container-element/ ).
This allows us to publish time-based content on the website.
However, if the page is cached with wp-rocket, the time-controlled publication of the container no longer works. The only workaround is to completely deactivate caching for the website. But that is not a solution for us. 

<img width="893" alt="Bildschirmfoto 2021-04-08 um 18 12 10" src="https://user-images.githubusercontent.com/33330325/114060835-12a12880-9896-11eb-89e0-e875449a9563.png">

![doc_57_container_elements_publishing_status_date](https://user-images.githubusercontent.com/33330325/114060804-0cab4780-9896-11eb-9328-c2fb0367789d.jpg)

**Comment by GeekPress** [comment]
Hi @TW20-MH 

Please contact our support team about your issue. We will be more than happy to help to fix your problem.

You can submit your ticket from here: https://wp-rocket.me/support/
