### ISSUE TITLE
Get rid of Disable WordPress Embeds option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3773]
## What are we proposing to do? 

With this update, WP Rocket will no longer disable WordPress embeds. The UI will be removed.

## Why are we doing this? 

We are doing this as part of cleaning up the WP Rocket user interface to make WP Rocket even more user-friendly. Disabling WordPress embeds has a very low impact since it removes one HTTP request of 1.2 KB in size. 

## User expectations and experience. How will we do this feature?

- We will remove the entire feature for both existing and new users. 
- The UI associated with the feature will be removed. 

![Image of UI](https://p27.f0.n0.cdn.getcloudapp.com/items/jkuLQprW/2c0eb77f-e9e3-4b35-a75f-98fdc723f72b.png)

## Risks
Since we are removing a feature and not adding anything the risk is close to none. We might get questions from users, but that can be answered via a support doc or saved reply. 

## Acceptance Criteria

On update to the new version or on install, the UI to disable WordPress embeds in the “Media” tab no longer exists. 
On a website with “Disable WordPress embeds” enabled, when updated, the file “/wp-includes/js/wp-embed.min.js” will appear on the page. 

## Documentation and Translations
No explicit documentation is required at the moment. If we get too many questions about the missing feature, we can work on a saved reply. 

- https://docs.wp-rocket.me/article/1133-wp-rocket-compatible-with-gutenberg-wordpress-5-0 (to delete)

**Comment by engahmeds3ed** [comment]
## Scope a solution

- Remove the option to be sent to support:
https://github.com/wp-media/wp-rocket/blob/0554a857ce6efcaec23fd8c2ab0039eb71d24ca7/inc/Engine/Support/Data.php#L25

- Remove calling the subscriber at service provider
https://github.com/wp-media/wp-rocket/blob/753a36cdb774f2863b95d3d0fde661174d4dca16/inc/Engine/Media/ServiceProvider.php#L28
https://github.com/wp-media/wp-rocket/blob/753a36cdb774f2863b95d3d0fde661174d4dca16/inc/Engine/Media/ServiceProvider.php#L54-L56

- Deprecate the subscriber and remove the full directory
https://github.com/wp-media/wp-rocket/blob/94dd829a8c154ce260d3a7d37efae3dcc36ec59f/inc/Engine/Media/Embeds/EmbedsSubscriber.php#L14

- Remove the subscriber from list of subscribers to be loaded
https://github.com/wp-media/wp-rocket/blob/532d40c725d12928450dfddab89361ac52f8c276/inc/Plugin.php#L202

- Remove option from first install options
https://github.com/wp-media/wp-rocket/blob/6c3d0792315fe7ac3bbe948924f9c872eaa7d721/inc/admin/upgrader.php#L175

- Remove sanitization
https://github.com/wp-media/wp-rocket/blob/e17a92502ee7a9fdbeb9bd579fde4f351705a4d2/inc/Engine/Admin/Settings/Settings.php#L225

- Remove option from safemode
https://github.com/wp-media/wp-rocket/blob/6002b1ec6f08d1bad5fb766d3f4baff4cdbcd5fa/inc/Engine/Admin/Deactivation/DeactivationIntent.php#L141

- Adjust media tab description to remove embeds
https://github.com/wp-media/wp-rocket/blob/63ea93f922e4cb9cefeb8315a995851296f89104/inc/Engine/Admin/Settings/Page.php#L883

- Remove embeds section
https://github.com/wp-media/wp-rocket/blob/63ea93f922e4cb9cefeb8315a995851296f89104/inc/Engine/Admin/Settings/Page.php#L957-L962

- Remove the option itself
https://github.com/wp-media/wp-rocket/blob/63ea93f922e4cb9cefeb8315a995851296f89104/inc/Engine/Admin/Settings/Page.php#L1057-L1064

- Remove tests
https://github.com/wp-media/wp-rocket/tree/94dd829a8c154ce260d3a7d37efae3dcc36ec59f/tests/Integration/inc/Engine/Media/EmbedsSubscriber
https://github.com/wp-media/wp-rocket/tree/94dd829a8c154ce260d3a7d37efae3dcc36ec59f/tests/Unit/inc/Engine/Media/EmbedsSubscriber
https://github.com/wp-media/wp-rocket/tree/94dd829a8c154ce260d3a7d37efae3dcc36ec59f/tests/Fixtures/inc/Engine/Media/EmbedsSubscriber

And make other tests to pass

## Estimate the effort
[S]
