### ISSUE TITLE
wp_cache warning in Site Health

### ISSUE THREAD

**Issue by mcpat-it** [wp-media/wp-rocket#3775]
**Describe the bug**
wp_cache is set to true in config, but I see a error in Site health (see below)

**To Reproduce**
Go to site health, there is the warning (at least for me since updating to wp 5.7)
After downgrading to a lower version (5.6.x) the error warning disappears!

```
"WP_CACHE is set to false. The WP_CACHE constant needs to be set to true for WP Rocket cache to work properly".
```

**Expected behavior**
No error

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
It might be related to #3734, is your website on an hosting with its own caching system?

**Comment by mcpat-it** [comment]
No. I have an "own" server (netcup vServer), and there is this error. Before updating to wp 5.7 I didn't see this error

**Comment by piotrbak** [comment]
We haven't received any further feedback here. The problem is most likely related to malformed wp-config file.
