### ISSUE TITLE
The cache is not preloaded after the CPCSS is regenerated

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3788]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
After the Critical CSS is regenerated, and it successfully finishes, the preload is not triggered.

**To Reproduce**
1. Enable Preload
2. Click on **Regenerate Critical Path CSS**
2. Wait until it the generation finishes
3. Check the cache folder
4. The cache won't be regenerated

**Expected behavior**
The preload should be triggered after the CPCSS has been updated. 
 
**Additional context**
Ticket: https://secure.helpscout.net/conversation/1446326041/245294?folderId=2683093
Slack convo: https://wp-media.slack.com/archives/C43T1AYMQ/p1618342744193000

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is resolved with the new preload
