### ISSUE TITLE
CPCSS is generated/regenerated for mobile although caching for mobile devices is disabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3789]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x]  Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enable OCD or regenerate CPCSS while enable caching for mobile devices is a disabled but separate cache for mobile devices enabled

**To Reproduce**
1. Go to cache tab and enable separate cache for mobile devices and disable enable caching for mobile devices and save
2. enable OCD and save
3. check the /cache/critical-css/1 folder
4. CSS files are generated for mobile

**Expected behavior**
Only CSS files for desktop generated

**Screenshots**

https://user-images.githubusercontent.com/76941962/114730852-85e8e580-9d41-11eb-9810-fbb996fafefd.mp4

**Additional context**
- Recommend disabling separate cache for mobile devices once enable cache for mobile devices is disabled (probably this will fix it)
- Same will occur while regenerating CPCSS

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Not happening anymore. Most likely fixed here:
https://github.com/wp-media/wp-rocket/pull/5766
