### ISSUE TITLE
License Validation - PHP fatal error when the customer's email contains a single quote

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3796]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When a customer's account email contains a `'`, the `licence-data.php` file will contain such a line of code:
```PHP
define( 'WP_ROCKET_EMAIL', 'john.o'doe@example.com' );
```
This will cause a PHP fatal error when WP Rocket is activated:
```
Parse error: syntax error, unexpected 'doe' (T_STRING), expecting ')' in /home/public_html/wp-content/plugins/wp-rocket/licence-data.php on line 17
```
**To Reproduce**

1. Hardcode `john.o'doe@example.com` in the `licence-data.php` file.
2. Activate WP Rocket.
3. Check the `debug.log`.

**Expected behavior**

We should prevent the PHP fatal error if the customer's email contains a `'`.

**Additional context**

We should make sure `'` are properly escaped when we write the email in the respective file.

**Related ticket:** https://secure.helpscout.net/conversation/1485356718/256546?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
Stupid question, but is it allowed / possible to create an email with `'` inside?

**Comment by vmanthos** [comment]
I was wondering the same thing. I know for a fact that Gmail doesn't allow anything other than numbers, letters, and dots. 

However, in the end, it doesn't really matter.

The customer can use it when registering, even by mistake, and this is something we should also be looking at to prevent this kind of issue.

**Comment by remyperona** [comment]
> The format for email addresses is defined in RFC 5322; The local part (i.e. recipient) may use any of these ASCII characters:
> - Uppercase and lowercase English letters (a–z, A–Z)
> - Digits 0 to 9
> - Characters ! # $ % & ' * + - / = ? ^ _ ` { | } ~
> - Character . (dot, period, full stop) provided that it is not the first or last character, and provided also that it does not appear two or more times consecutively (e.g. John..Doe@example.com).

So yes it's valid, even though it's the kind of thing that will break when used in input, since the single quote delimiter is used so often in the code.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
