### ISSUE TITLE
AMP - the homepage's cache isn't cleared when publishing posts

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3798]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the official AMP plugin is used, publishing a new post won't clear the cache of the AMP homepage, the way we do for the non-AMP homepage:
https://example.com/?amp=1

This is because `rocket_clean_home()` doesn't have the necessary logic built-in:
https://github.com/wp-media/wp-rocket/blob/027571522d126aad22e836fdfde1bdf8f6c6adac/inc/functions/files.php#L576-L659

**To Reproduce**
1. Install/activate the [AMP plugin](https://wordpress.org/plugins/amp/)
2. Visit the homepage using a mobile emulator, and make sure that's cache.
3. Publish a new post.
4. The content in the `/#amp=1` folder will not have been cleared.

**Expected behavior**

To be consistent with our cache clearing, the AMP homepage should be cleared.

**Additional context**

We could use the `after_rocket_clean_home` hook in our AMP compatibility file to clear the homepage's cache.

**Related ticket:** https://secure.helpscout.net/conversation/1474551288/253298?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@vmanthos It's a duplicate:
https://github.com/wp-media/wp-rocket/issues/3444

**Comment by vmanthos** [comment]
Apologies @piotrbak. I searched for AMP specifically and missed that one.

I'll close this since a solution to #3444 will also apply here.
