### ISSUE TITLE
When utm_source, utm_medium and utm_campaign are set the page is cached, even when other query variables are set

### ISSUE THREAD

**Issue by hermanboomsma** [wp-media/wp-rocket#380]
By default WP Rocket does not cache pages with GET variables in the URL. This is expected behaviour because GET variables can be used to serve different content.

In https://github.com/wp-media/wp-rocket/blob/master/inc/front/process.php#L83 there's a check to see if no GET variables are set. If GET variables are set, it checks if the variables are included in the list of variables that are allowed to be cached. Some allowed variables are utm_source, utm_medium and utm_campaign, allowing campaign traffic to be cached.

I believe there should also be a check whether the allowed GET variables are the only ones set. For example, we have a vacancy view with an 'apply' query variable, which can be set to true. If 'apply=true' is appended to the URL, the application form is shown instead of some other content.

What happened is traffic came in like this, from an 'apply now' campaign:
?utm_source=linkedin&utm_medium=online&utm_campaign=vacancy&apply=true

When the cache was cleared just before someone visited the vacancies page from the LinkedIn campaign, the page was cached in the 'apply=true' state. When someone visited the (cached) page without 'apply=true' in the URL the 'apply=true' version would be shown, because WP Rocket had ignored the rest of the GET variables.

For me, the expected behaviour would be that the page is not cached, because additional GET variables are set.

**Comment by heintore** [comment]
+1 to this.

**Comment by glueckpress** [comment]
> the expected behaviour would be that the page is not cached, because additional GET variables are set.

Agreed, we’re going to fix it.

**Comment by Eksakte-Asser** [comment]
Yes please. It's totally fine that pages with the 3 utm attributes are cached, but it shouldn't be if there are additional non-utm parameters present too. This is a rather big problem for our setup too. So I'm really happy it has gotten some attention 👍 

Apart from that, thanks for a great plugin!
