### ISSUE TITLE
Add possibility to use Common Cache for Logged-in Users and No Cache for Admins

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3802]
**Is your feature request related to a problem? Please describe.**
There are two helper plugins available:
- [WP Rocket | Common Cache For Logged-in Users](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-common-cache-loggedin)
- [WP Rocket | No Cache for Admins](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-no-cache-for-admins)
But it is not possible to use these two functionalities at the same time.

Details: https://wp-media.slack.com/archives/C43T1AYMQ/p1602143842158800

**Describe the solution you'd like**
Ability to use Common Cache for Logged-in Users and No Cache for Admins at the same time

Related tickets:
https://secure.helpscout.net/conversation/1310676047/202823/
https://secure.helpscout.net/conversation/1486172546/256741/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1503023311/261370/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1826988775/333761/

**Comment by blizam** [comment]
Definitely looking for this solution as well. We have a large member site where all member content is the same (student courses) and thousands of active logged in members desperately needing faster loading cached pages. We have a large active admin population as well whom are creating new products and courses and need to see their changes in real time

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
