### ISSUE TITLE
make notification messages auto-dismissable

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3803]
**Is your feature request related to a problem? Please describe.**
When _clear cache_ or _clear OPcache_ options are clicked, or new plugin settings are saved, there is a notification message at the top of the WP dashboard. These messages can only be dismissed manually by clicking the corresponding "x" inside the message.
![image](https://user-images.githubusercontent.com/60236665/115211268-b04ef000-a0ff-11eb-9e9b-a40534854a7e.png)

Screenshots provided by the customer:
https://prnt.sc/11l9a7h
https://prnt.sc/11l9enb

**Describe the solution you'd like**
Make these messages auto-dismissable after 3-5 seconds.

**Additional context**
Ticket with this feature request: https://secure.helpscout.net/conversation/1487131885/256947

**Comment by GeekPress** [comment]
Not sure to understand why it will be helpful as the notice is deleted after refreshing the page.
