### ISSUE TITLE
Move WebP Compatibility option to One-Click Rocket Add-on

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3804]
## What are we proposing to do? 

To move the « WebP Compatibility » option from the « Media » tab to the « Add-ons » tab.

## Why are we doing this? 

In 3.9, we decided to remove two of our add-ons: Google Tracking and Facebook Pixels. All the rest can be considered as compatibility add-ons.

The « WebP Compatibility » option is a good candidate for being moved to the « Add-ons » section as per its name.

By moving this option to add-on, we want to reduce a misusing of it. Indeed, this option is used by 70.4% of our users when WebP format represents only 1.3% of all images format (source: https://w3techs.com/technologies/overview/image_format). 
Even if the usage of WebP format should be higher on our user base, the difference is too important to be the reality.

## User expectations and experience. How will we do this feature?

This update will be transparent for the users. The only difference is the new location of the « WebP Compatibility » option.

### User Experience

- For current users, we will keep the current status of the option on or off.
- For new users, the option will be still turned off by default.
- The « WebP Compatibility » option will be moved to the One-Click Rocket Add-ons section

### UI proposal

- Add-on name: WebP Compatibility
- Add-on logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.logo.wine%2Flogo%2FWebP&psig=AOvVaw2LHiv8BEEjTzWB17PiquFc&ust=1617119205686000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCU-9Ls1e8CFQAAAAAdAAAAABAD
- Add-on subtitle: Improve browser compatibility for WebP images
- Add-on description: Enable this add-on if you would like WP Rocket to serve WebP images to compatible browsers. Please note that WP Rocket cannot create WebP images for you. To create WebP images we recommend Imagify.
- Add-on location: One-click Rocket Add-ons - below Varnish add-on.

## Risks

No risk except to educate users where to find the new location for the option.

## Acceptance Criteria

- WebP option is displayed in the add-on sections as a one-click add-on
- The option is correctly enabled or disabled when switching the sliding checkbox
- The value of the option is correctly preserved when updating to 3.10
- The option is correctly disabled and greyed-out, the description updated, based on the same criteria as when the option was in the media tab

## Documentation and Translations
https://docs.wp-rocket.me/article/1282-webp (to update)

**Comment by ScottTravisHartley** [comment]
I want to note, a lot of client sites I run into personally, who have this option enabled think it creates webp versions of the image  (this might help clear things up by moving it to the addons section)

**Comment by GeekPress** [comment]
@ScottTravisHartley This is one of the main reasons we want to move it!

**Comment by engahmeds3ed** [comment]
# Grooming

## Scope a solution

- At page.php add new settings field below varnish here
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L1852

with the following code
```
if ( apply_filters( 'rocket_display_webp_options_tab', true ) ) {
  $webp_beacon = $this->beacon->get_suggest( 'webp' );

  if ( rocket_valid_key() && ! \Imagify_Partner::has_imagify_api_key() ) {
    $imagify_link = '<a href="#imagify">';
  } else {
    $imagify_link = '<a href="https://wordpress.org/plugins/imagify/" target="_blank" rel="noopener noreferrer">';
  }

  $this->settings->add_settings_fields(
    [
      'cache_webp' => apply_filters('rocket_cache_webp_setting_field', [
        'type'              => 'one_click_addon',
        'label'             => __( 'WebP Compatibility', 'rocket' ),
        'logo'              => [
          'url'    => WP_ROCKET_ASSETS_IMG_URL . 'logo-varnish.svg',
          'width'  => 152,
          'height' => 135,
        ],
        'title'             => __( 'Improve browser compatibility for WebP images.', 'rocket' ),
        // translators: %1$s = opening <a> tag, %2$s = closing </a> tag.
        'description'       => sprintf(
        // translators: %1$s and %3$s = opening <a> tag, %2$s = closing </a> tag.
          __( 'Enable this option if you would like WP Rocket to serve WebP images to compatible browsers. Please note that WP Rocket cannot create WebP images for you. To create WebP images we recommend %1$sImagify%2$s. %3$sMore info%2$s', 'rocket' ),
          $imagify_link,
          '</a>',
          '<a href="' . esc_url( $webp_beacon['url'] ) . '" data-beacon-article="' . esc_attr( $webp_beacon['id'] ) . '" target="_blank" rel="noopener noreferrer">'
        ),
        'section'           => 'one_click',
        'page'              => 'addons',
        'settings_page'     => 'webp',
        'default'           => 0,
        'sanitize_callback' => 'sanitize_checkbox',
      ]),
    ]
  );
}
```

also keep in mind to add documentation for `rocket_cache_webp_setting_field` filter.

- After this line 
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L292
add the following line
```
'cache_webp' => 1,
```

- Remove this section
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L974-L989

- Remove those lines
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L974-L989

- remove the field completely
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L1082-L1092

- remove this beacon
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L881

- Remove webp word from here
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L894

- remove not used lines here
https://github.com/wp-media/wp-rocket/blob/fe509b6b002ace0ef0974b9247b28b6fefbda7eb/inc/Engine/Admin/Settings/Page.php#L884-L888

## Estimate the effort
[S]

I don't think this needs any testing code.
