### ISSUE TITLE
Promotions in the plugin - Update for new customers

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#3807]
Following issue [#3218 ](https://github.com/wp-media/wp-rocket/pull/3218), we need to add a condition for displaying the banner during promo campaigns. 

In addition to the conditions already applied, this one should be added: 
_Display banner only if the customer bought WP Rocket more than 14 days ago_

**Comment by remyperona** [comment]
@GeekPress This will need to be planned before the next promo

**Comment by GeekPress** [comment]
@Tabrisrp Can we add this to the next sprint?

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `inc/Engine/License/Upgrade.php::can_use_promo`
- using `$user->get_creation_date()`
- Add a new conditional check, and bailout if current time + 14 days is inferior to the creation date

Also update tests using this method to add a new fixture for this condition

### Estimate the effort ✅
Effort for dev + QA `[S]`
