### ISSUE TITLE
SECURITY: sslverify / ssl_verify. Developers: Stop Using sslverify = false - WordPress has you covered.

### ISSUE THREAD

**Issue by mnemotiv** [wp-media/wp-rocket#382]
https://www.skyverge.com/blog/developers-stop-using-sslverify-false/

> While a couple of years ago sslverify = true may have caused more issues than it solved due to validation issues, this is no longer the case. When WordPress 3.7 was released, WordPress began to bundle CA certificates into core to validate them itself, bypassing the need for the external validation requests for known certificates and ensuring that the host configuration did not interfere with verification.

1. You don't support old WP versions anyway (as stated in your readme; errors on your "supported" old WP versions) - so no need to disable SSL verifications, unless you've forgotten to remove those disablements after you've worked on your local dev machines.
2. You've disabled SSL verifications everywhere in plugin = your plugin is unsafe.

**Comment by Tabrisrp** [comment]
Thank you for reporting this, it will be fixed in the next major version of the plugin
