### ISSUE TITLE
UI of combine js needs to match design when import settings having delay js and combine js on 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3831]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Y
- Used the search feature to ensure that the bug hasn’t been reported before => Y

**Describe the bug**
UI of combine js needs to match design when import settings having delay js and combine js on 

**To Reproduce**
Precondition:
- exported settings exist from version < 3.9 with delay js and combine js on 
- WPR 3.9 installed and activated

1. Go to the tools tab and import settings 
2. open file optimization tab
3. check the UI for combine js

**Expected behavior**
Combine js is dimmed and unchecked

**Screenshots**
![115689680-9c53fa00-a35c-11eb-953c-4e66a94a7df2](https://user-images.githubusercontent.com/76941962/115739219-06d15e00-a38e-11eb-933e-226635d6c652.png)

**Additional context**
Expected is 
![115689618-89412a00-a35c-11eb-92f8-2b62191be749](https://user-images.githubusercontent.com/76941962/115739356-26688680-a38e-11eb-85ce-e0a3f4030df9.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
