### ISSUE TITLE
Clear Used CSS link not visible at the admin bar menu in the frontend, in 3.9

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3835]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When **Remove unused CSS** is active, the **Clear Used CSS** link appears at the WP Rocket admin bar dropdown menu in the backend as expected. But the same option is not visible when opening the WP Rocket dropdown menu at the frontend

**To Reproduce**
1. Enable Remove Unused CSS
2. Check the dropdown menu in the backed
3. Compare with the same menu in the fronted
4. the Clear Used CSS link is not available in the frontend menu

**Expected behavior**
The option should be present in both scenarios?

**Screenshots**
Backend
![Captura de pantalla 2021-04-23 a la(s) 10 45 44](https://user-images.githubusercontent.com/229406/115881806-81e45400-a422-11eb-89d8-a4fdadec44ad.png)

Frontend
![Captura de pantalla 2021-04-23 a la(s) 10 46 10](https://user-images.githubusercontent.com/229406/115881833-8872cb80-a422-11eb-836c-40efbe31856e.png)

**Additional context**
This is happening with version **3.9-alpha4**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by camilamadronero-zz** [comment]
It's also happening for the Regenerate Critical CSS option (in my site too)

**Comment by remyperona** [comment]
Those items are only available when on the admin side indeed. It's on purpose to avoid too many items.

**Comment by alfonso100** [comment]
thank you Remy, we can close this one 🙏
