### ISSUE TITLE
Improve Remove Unused CSS onboarding

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#3836]
**Is your feature request related to a problem? Please describe.**
Our current solution generates partial used CSS on the first time the option is enabled, because of the ramp-up time to get the resources cached on the SaaS side during the cache generation process.

We currently provide no indicator around that, and this might generate unnecessary questions from our users.

**Describe the solution you'd like**
Our new solution to improve on that is to pre-cache the resources earlier, using a similar process than with CPCSS. We will fetch resources on the homepage, CPTs and taxonomies on option activation, and display a progress bar on the settings page to keep the user informed of the process.

Once the process is completed, we will start applying the used CSS on the cached page. This used CSS should be (close to) complete, providing good results on PSI.

**Describe alternatives you've considered**
We considered having the warmup run all the time, but this would be putting to much unnecessary pressure on our servers.

**Additional context**
Detailed doc: https://docs.google.com/document/d/1SMZqpO5UcrjOoB_BNo2bafIpVlgwq8aDyAKOjuEZsos/edit?usp=sharing

**Comment by crystinutzaa** [comment]
@wp-media/php 

I made a plan / the flow on how I see it working, however I think that there are still a lot of missing things which needs brainstorming.

In **WP Rocket** side, we have 2 options for that loading bar.
We can display the progress accurate by displaying it in 2 steps:
1. **Step 1** - _Collect the resources from pages - homepage, CPT & taxonomies_
2. **Step 2** - _Warmup resources._ 
Basically, we will display first the progress of collecting the resources from their page. Below the loading bar we display a text:
`Collecting resources in progress...`
When this step finish and is at 100% , we reset the same loading bar and we make the progress for warmup resources. The text below will be changed to:
`Warming resources in progress...`

**How we will do this?** 
For collecting the resources we need a Background Process which will fetch each page. Will merge and store the found resources in a transient(???).
For warming up the resources, we need another Background Process. This Background process will grab the found resources and send to warmup.
We need an REST API endpoint which will share to our React component the status of each step. It can be the percentage or the X out of Y values and compute the percent in React.
Refreshing / Navigating from WP Rocket options page while this process runs, will always display the accurate progress of this step.


**Questions:**
1. What will happen if the user change their theme? This step need to take place again, right?
2. When disabling & enabling back the RUCSS option, should this step be reloaded? 
3. What will happen if the transient / location where we are storing the progress of this is cleaned?
4. How we determine if we can do the TreeShaking if the transient / location where we store the flag is cleaned?
5. What will happen in case we never get a 100% for each step? For collecting the resources I am pretty confident that this step will pass.
However, during warmup, we may end up in the situation when not all pages are warmed up.
In case, the progress is not increasing for more than X minutes, I think it would be safe to display a list with files which could not be processed by our SAAS
and provide a button for the client to manually allow the TreeShaking + a link to a doc why this happened + contact us (???)


**In SAAS side,** we need an API endpoint in Central Saas and reuse it in Warmup / or create another microservice to provide the status of the resources.
We will send a list with CSS / JS resources and SAAS will give us back if the resource and a flag: is_cached = true / false .

**Comment by crystinutzaa** [comment]
### 1. Background Process for collecting resources from pages
Create a Background Process in `Optimization/RUCSS/Warmup` -> PageScanner.php and PageScannerFetcher.php
This Background process will scan all pages  `homepage, CPT & taxonomies` and will create 2 new options in the database.
The first option (`wpr_scanned_pages`) will update the list with all pages which needs to be scanned:
`[page_name, is_scanned]` -> page_name is the type of page (eg, homepage, page, post, and so on) and is_scanned detects if the page was accessed by this background process or not.
The second option (`wpr_found_resources`) will update the list with the found resources from all the scanned pages. The found resources must contain unique URLs. 
In wwpr_found_resources will have 2 data inside: resource_url, is_warmedup. Is Warmup will be inserted with default `false` value.

### 2. Background process for warming up resources from `wpr_found_resources` option
Create a Background process in `Optimization/RUCSS/Warmup` -> OptionWarmup.php and OptionWarmupFetcher.php
When the Background process for collecting the resources is complete, we will start the option warmup.
This means that this Background process will grab all resources from `wpr_found_resources` option which have the `is_warmedup =false` . It will send it to SaaS warmup, add it to local DB table.  

### 3. Background Process for pinging SaaS warmup
Create another Background process in  `Optimization/RUCSS/Warmup` -> PingWarmupSaaS.php
When OptionWarmup.php Background process is complete, then we will start this background process.
This process, will grab all resources from `wpr_found_resources` and ping SaaS Warmup to check the status of the resources.
SaaS Warmup will send the following values:  [url, is_warmedup]. 
In case is_warmedup = false, then the background process will continue running. 
The background process will update the `wpr_found_resources` options with the new status coming from SaaS. 
When all resources have id_warmedup = true, then this Background process is stopped.
Also when this Background process starts, we will add another option with the time when it started. (wpr_found_resources_started_time). 

### Admin Work needed:
When the theme is changed, the onboarding process needs to start again.
This means that:
- Stop any of these 3 background processes in case that are running
- Clean these 2 options - `wpr_found_resources` & wpr_scanned_pages
- Start Background Process for collecting resources from pages


### 4. Rest API Endpoint for checking `wpr_found_resources`  in SaaS
Create a Rest API Subscriber which will register 1 route under wp-rocket main route: `rucss/warmup/status`.
The method will be a GET.
This route will grab all options:
`wpr_scanned_pages` and `wpr_found_resources` and `wpr_found_resources_started_time`.
It will compute the percentages for how many pages were scanned, how many resources were warmed up completely and will compute the duration time of warmup process completion based on `wpr_found_resources_started_time` in seconds.


### 5. REACT component
Create a React component which will contain:
- a loading bar 
- 2 texts below with statuses
- an informal text + a button
React component will ping the RestAPI Endpoint : `rucss/warmup/status` and will grab the data from there and update the component.

**Comment by iCaspar** [comment]
After further team discussion, here's where we are:

### First Step: Collect key resources.
Get the pages we are going to use to collect resources. For that, currently in the CPCSS, we collect the URLs for each, which we then pass to the background process. We can extract from CPCSS into a trait and re-use.

### Second Step: New background process.
Then with the pages collected, background process calls collects the resources on pages identified in step 1 and with those resources assign a `process_ID` to that batch, and initiates a call to SaaS warmup.

The `wpr_rucss_resources` table on the plugin side, will need to be migrated with 2 new columns: `process_ID` and `status`.

(On SaaS Side, the following will need to be implemented: 
* the warmup route will need to receive a `process_ID` field along with the resource to be warmed up and will need to save the process_ID along with the warmed-up resource.
* the datalayer will need to have a new DB column for `process_ID`.
* the new warmup route -- see https://github.com/wp-media/warmup/issues/29 and https://github.com/wp-media/central-saas/issues/44 -- will need to be modified to receive process_ID instead of URLs and return an array of URLs with status: bool for present/not-present.)

### Third Step: Progress Bar (React component)
React progress bar polls new SaaS `resourceStatusQuery` route by the `process_ID`, calculates on each tick, the percentage completed (returned true), and unlocks treeshaking when `waiting` status items is (??? - To be determined).
