### ISSUE TITLE
Remove /inc/front/process.php if not longer needed

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3839]
**Is your feature request related to a problem? Please describe.**
/inc/front/process.php is called or included anywhere in newer versions of WP Rocket. 

**Describe the solution you'd like**
Removing /inc/front/process.php if no longer needed for backward compatibility. 

**Describe alternatives you've considered**
N/A

**Additional context**
Slack discussion - https://wp-media.slack.com/archives/C43T1AYMQ/p1619080309035200

**Comment by remyperona** [comment]
Suggestion is to keep the file to avoid breaking sites that don't have their `advanced-cache.php` file updated (most likely because of permissions). But the file will be empty instead.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Empty the `inc/front/process.php` file

### Estimate the effort ✅
Effort `[XS]`
