### ISSUE TITLE
rocket_lazyload_placeholder filter missing arguments

### ISSUE THREAD

**Issue by daomapsieucap** [wp-media/wp-rocket#3841]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (**yes, I'm at v.3.8.8**)
- Used the search feature to ensure that the bug hasn’t been reported before (**yes**)

**Describe the bug**
When using rocket_lazyload_placeholder filter to update the placeholder, I've got the PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function filter_rocket_lazyload_placeholder()...

**To Reproduce**
1. I want to replace "http" with "https" for content consistently. When I add custom filter function filter_rocket_lazyload_placeholder
to replace it something like

```
/**
 * WP Rocket lazyload placeholder
 */

add_filter( 'rocket_lazyload_placeholder', 'filter_rocket_lazyload_placeholder', 10, 3 );
function filter_rocket_lazyload_placeholder( $placeholder, $width, $height ) {
	$width  = 0 === $width ? 0 : absint( $width );
	$height = 0 === $height ? 0 : absint( $height );

	$placeholder = str_replace( ' ', '%20', "data:image/svg+xml,%3Csvg xmlns='https://www.w3.org/2000/svg' viewBox='0 0 $width $height'%3E%3C/svg%3E" );

	return $placeholder;
}
```

2. I've got this error message:
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function filter_rocket_lazyload_placeholder(), 1 passed in wp-includes/class-wp-hook.php on line 287 and exactly 3 expected in /home/directory/functions.php

It make my page response 500 when the page content has iframe.

**Expected behavior**
I found that on wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Iframe.php, the filter rocket_lazyload_placeholder has only one argument, could you please add the other missing 2 arguments to this filter please?

**Comment by remyperona** [comment]
Hi,

Thank you for the report. In fact, the filters should not be named the same for images and for iframes, as they don't use the same number of arguments.

It's something that we can fix in a future release.

Meanwhile, I would not recommend to do the change you're trying to do in the `xmlns` value, I invite you to read the following issue for the details: https://github.com/wp-media/wp-rocket/issues/1785

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
