### ISSUE TITLE
LazyLoad Content

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3843]
## What are we proposing to do? 

To build a new feature within WP Rocket to load some sections of a website when needed. This will be a LazyLoad for content.

## Why are we doing this? 

To please the new Core Web Vitals, we need to provide the above-the-fold content as fast as possible. To achieve this, we need to load images when needed and to delay the load of non-critical assets like CSS and JavaScript once the page has been rendered.

Not all sections of a website are relevant for the initial page render. For example, the footer is not relevant during initial page load and can be delayed.

We found an innovative way to load website sections on demand. WP Rocket will be the first optimization tool in the world to offer this new innovation.

([full doc](https://docs.google.com/document/d/18QDFgouB0rWJT8krA1hx8Qjs3cXV7rVsLkxj82GTsq0/edit?usp=sharing))

**Comment by Salimoh** [comment]
This can be done using CSS, but if wp-rocket provides a way for automating this that would be great.

**Comment by GeekPress** [comment]
@Salimoh Our approach is more efficient than using `content-visibility` ;)

**Comment by Salimoh** [comment]
Hope to see how you guys implement it in the upcoming updates. Good luck!

**Comment by deep27ak** [comment]
It would be good to have this done based on device type. Google somehow prefers mobile rendering over desktop and on mobile we will have more set of HTML elements which could be lazy rendered such as sidebars.

Although it would be interesting to see if this is not done using content-visibility and if the plugin can get the list of non-critical assets automatically.

**Comment by Woorooo** [comment]
Can't wait to get this feature, I hope it's still coming :)

**Comment by FawadNL** [comment]
Flying press now offers this. Hope you guys can also introduce this soon. 
https://youtu.be/XUP-WVQeEs4

**Comment by DivvyPT** [comment]
This is exactly what I'm looking for! Looking forward to seeing this feature in a near update! :)

**Comment by mehedihasanziku** [comment]
2 years still no progress 🙃, seems concept dropped
