### ISSUE TITLE
French version of the Remove Unused CSS unavailable

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3850]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
As a beta tester, I see that the French version of the feature Remove Unused CSS is not available.

**To Reproduce**
Install WordPress and WP Rocket in French.

**Expected behavior**
Translation should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/116215703-35618700-a748-11eb-888c-fa06f4249bbe.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
This is normal, we are still on alpha phase ;)
