### ISSUE TITLE
3.9 alpha4: Delay JS is breaking "Slider - Soliloquy"

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3856]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the Delay JS is enabled on the page with [Soliloquy Slider](https://wordpress.org/plugins/soliloquy-lite/), the Slider is not loaded, without any errors in the console. The only way to load it is to exclude both jQuery files and the following patterns:
`soliloquy_slider`
`/wp-content/plugins/soliloquy-lite/assets/js/min/soliloquy-min.js`

**To Reproduce**
1. Enable Soliloquy Slider
2. Create a new Slider
3. Add it to your site using shortcode
4. Enable Delay JS without any exclusions and visit the page with slider

**Expected behavior**
Delay JS working correctly with slider or automatic compatibility with exclusions present

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
Test page: https://rucss.rocketlabsqa.ovh/solislider/

**Comment by GeekPress** [comment]
### Note

The slider itself is loaded on `jQuery(window).load(function () { `in the inline JS

**Comment by remyperona** [comment]
@GeekPress @piotrbak Can this be closed with the latest version of the delay JS script?

**Comment by GeekPress** [comment]
> @GeekPress @piotrbak Can this be closed with the latest version of the delay JS script?

Yes :)
