### ISSUE TITLE
Improve partial cache clearing implementation at WP Engine

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3857]
**Is your feature request related to a problem? Please describe.**
On WP Engine, our page cache is completely disabled. WP Engine cleares their cache every 10 minutes. 

When WP Rocket's full cache clear is triggered, we clear their server-side cache as expected
This implementation works well. 

However, the _partial_ cleaning of elements doesn't work as expected:

When you edit a post, the post itself is cleared, but no further cache clearing is triggered. The cache for the **home page**, **category**, etc are not cleared after saving: http://recordit.co/ALE2LIG8ru

The **Always Purge URLs** functionality has no effect at all:  http://recordit.co/IOV9GmxTjr

**Describe the solution you'd like**
We could explore if our compatibility file can handle partial cache clearing at WP Engine, as we do in other environments when page caching is enabled 
More info here: https://wpengine.com/support/cache/#Purge_Cache_with_PHP 

**Additional context**
It is important to say that with WP Rocket disabled, the same behavior is happening: updating a post doesn’t clear the category or home page. However, I think we could improve this from our end, improving our integration and providing more value to our customers.

**Comment by GeekPress** [comment]
This enhancement should be done on WP Engine side directly. If they decided to make their clean cache like this, there are maybe some reasons.

@Tabrisrp What do you think?

**Comment by piotrbak** [comment]
It should be handled on WP Engine's end. We also have this issue with them that might be handled if they improve their tools:
https://github.com/wp-media/wp-rocket/issues/5186
