### ISSUE TITLE
Develop: Uncaught SyntaxError: Invalid left-hand side in assignment when delay js v2 is enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3859]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Yes (develop- 3.9alpha5)
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
While using an attached template on this page https://new.rocketlabsqa.ovh/test3849test then enable delayjs, Error Uncaught SyntaxError will be displayed in the console

**To Reproduce**
Precondition:
Delay js is enabled with the default exclusion list there

1. Go to https://new.rocketlabsqa.ovh/test3849test 
2. Inspect and see the console error

**Expected behavior**
No error in the console

**Screenshots**
![Screenshot from 2021-04-28 13-31-34](https://user-images.githubusercontent.com/76941962/116396845-20f3bc00-a826-11eb-933c-ef29c8405eaa.png)

Used settings: 
http://snippi.com/s/25ybz52

Template: 
http://snippi.com/s/zimg9te

**Additional context**
- Disable delay js will remove the error
- If the default exclusion list not there (while new install) and used the same template, will result in other errors and removing slider from the page => Recommend default exclusion exist for new installs as same as updates
- Theme : Divi

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
I can reproduce it on Divi theme

**Comment by piotrbak** [comment]
After further investigation, the problem goes away when emoji is excluded from the Delay JS in my case.

**Comment by remyperona** [comment]
This should be fixed with PR #3891
