### ISSUE TITLE
suggestion: replace Date.now with performance.now

### ISSUE THREAD

**Issue by brunocrosier** [wp-media/wp-rocket#386]
in the files wp-rocket/inc/front/js/lazyload.1.0.5.js and wp-rocket/inc/front/js/lazyload.1.0.5.min.js

i would suggest to replace Date.now with performance.now

**Comment by glueckpress** [comment]
@brunocrosier Would you mind expanding on why you’d prefer `performance.now`?

**Comment by brunocrosier** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

when RocketLoader is installed, it lowers the website's LightHouse score due to this issue

LightHouse: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

**Comment by Tabrisrp** [comment]
We'll change the lazyload script we use in a future version of WP Rocket, so it's unlikely we'll do any change in the current version.
