### ISSUE TITLE
Develop: Some images are auto removed from page after enable RUCSS with certain template

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3860]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes (3.9 alpha5)
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
While using the mentioned template then enable RUCSS, Some images aren't displayed on the page ( something happens related to lazyload although LL is not enabled in WP rocket)

**To Reproduce**
Precondition:
- RUCSS only is enabled

1. Go to https://new.rocketlabsqa.ovh/russsite1
2. Compare with https://new.rocketlabsqa.ovh/russsite1/?nowprocket
3. Check this image in elements of console `https://test.romainvincent.com/wp-content/uploads/2021/04/fooodiesfeed.com_sweet-and-salty-brunch.jpg` src became `data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201024%201023'%3E%3C/svg%3E`

**Expected behavior**
Images still displayed when RUCSS is on

**Screenshots**
![WithoutRUCSS](https://user-images.githubusercontent.com/76941962/116408625-52bf4f80-a833-11eb-83ab-d0d8f2724493.png)
![WithRUCSS](https://user-images.githubusercontent.com/76941962/116408633-55ba4000-a833-11eb-9f14-19bc70223813.png)

**Additional context**
- Theme: storefront
- Images normally displayed once RUCSS is disabled

Template:
http://snippi.com/s/cxr7tkl

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
~~Lazyload is enabled from the standalone plugin for lazyload, not from WP Rocket itself. We need to add an exclusion for it in the delay JS exclusions list.~~

**Comment by remyperona** [comment]
The issue is happening on the copy of the original page, but not on the original page itself.

**Comment by GeekPress** [comment]
@Tabrisrp @Mai-Saad Does this is related to RUCSS or Delay JS?
