### ISSUE TITLE
Which action fires on Clear cache in WP Admin?

### ISSUE THREAD

**Issue by mariadanieldeepak** [wp-media/wp-rocket#387]
I'm looking to clear WordPress DB options everytime, the Admin clears the Cache in the WordPress Admin Dashboard. Could you let me know which one of the following actions, should I use to achieve my desired result?

`after_rocket_clean_domain`
`after_rocket_clean_cache_dir`

**Comment by glueckpress** [comment]
@mariadanieldeepak Please don’t post support questions here, this is a working repo, thanks.
We’ll be happy to answer questions (including technical ones) here: https://wp-rocket.me/support/

**Comment by mariadanieldeepak** [comment]
Oops, I'm sorry. Thanks for pointing the Support link.
