### ISSUE TITLE
Used CSS in the file is not refreshed after changing the CDN option

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3874]
**Before submitting an issue please check that you’ve completed the following steps:**
- **3.9-alpha5**
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After changing the CDN option, the changes are not reflected automatically in the Used CSS File

**To Reproduce**
1. Enable CPCSS
2. Enable RUCSS
3. Visit the homepage
4. Enable the CDN
5. Visit the homepage and open the Used CSS file, confirm that it's using the domain paths

**Expected behavior**
It should be updated automatically

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
I'm closing, it won't be a problem anymore with 3.10.
