### ISSUE TITLE
Uncode theme and Delay JS compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3881]
**Before submitting an issue please check that you’ve completed the following steps:**
- 3.9alpha5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JS is enabled with the Uncode theme, the content might not be loaded until we move the mouse

**To Reproduce**
1. Go to http://mega.wp-rocket.me/uncode/homepages/blog-masonry/
2. Move the mouse
3. See an error

**Expected behavior**
I think we could exclude all files and patterns related to Uncode + jQuery files in our compatibility files. If not, some of the customers might experience errors in the PSI

This should be discussed though

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
After discussing in Slack, we won't do anything here. It will be the choice of the users to exclude the JS files if they don't like the rendering before user interaction.
