### ISSUE TITLE
Possible change of the CSS order if the file is not processed

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3887]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the file is not processed, it's possible that the CSS order will be changed. Especially, when the CSS Combination is enabled as it'll move the combined file before the Used one.

**To Reproduce**
1. Page when there's unprocessed CSS
2. Check the source when the CSS Minification is enabled
3. Check the source when the CSS Combination is enabled
4. Confirm that the order has changed.

**Expected behavior**
We should be able to preserve the order of the styles when there's an unprocessed file in the source.

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
It goes the other way around as well. Unprocessed files will be added after the Used CSS, which won't preserve the original order and override style. 

@piotrbak Will this one be fixed on the new Remove Unused CSS? 

If not, can we have a filter to prevent the Remove Unused CSS from being added to the page if not all resources are processed? To be used in cases where the CSS is overridden. 

Related - https://secure.helpscout.net/conversation/1801372696/328842

**Comment by piotrbak** [comment]
@DahmaniAdame There won't be unprocessed CSS in the new approach, so this is going to be fixed.
