### ISSUE TITLE
Multisite: Settings are not removed from the wp_options table for subsites when uninstalling WP Rocket

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3889]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Yes on both trunk and 3.9 alpha5
- Used the search feature to ensure that the bug hasn’t been reported before 

**Describe the bug**
When activating WPR on multisite (after a fresh installation), settings are different from site to another

**To Reproduce**
1. Go to https://newmulti.rocketlabsqa.ovh/ network admin -> plugins
2. Install WPR (trunk or 3.9 alpha5)
3. On each site activate WPR and open settings
4. Check WPR settings across all sites => settings are different

**Expected behavior**
After fresh activation of WPR , settings are the same across all sites

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
In case we are not supporting network activation then still after fresh installation, when activating each site individually, initial settings shall be the same which is not the case now.
Current behavior results in:  after a fresh installation of WPR on multisite, RUCSS will be enabled by default on non-main site while delay js will be disabled by default there.

**Comment by remyperona** [comment]
I was not able to reproduce the issue on a multisite with a fresh installation of the plugin.

What I noticed though, is that when we uninstall the plugin, we only delete the options for the current sub-site, and we don't loop over all sub-sites to remove the options on each of them.

In that case, when the plugin is re-installed, since the option is already there in the database, it will be re-used directly, which could explain the difference seen in the original ticket.

**Comment by piotrbak** [comment]
As an addition here, upon the deactivation, we should remove the following rows from `wp_options`:
`wp_rocket_settings`
`wp_rocket_prewarmup_stats`
`wp_rocket_resources_scanner`
`wp_rocket_resources_scanner_fetched`

**EDIT:** Also we should clear transients from subsites.

Not sure if there's something else

**Comment by Mai-Saad** [comment]
Note for retest: WPR transients shall be deleted as well

**Comment by vmanthos** [comment]
> Not sure if there's something else

@piotrbak The same is happening for transients as well, i.e. they are deleted from the main site but not from sub-sites. This should be taken into consideration when fixing the specific issue.

**Comment by piotrbak** [comment]
@vmanthos Thank you, updated my comment

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
