### ISSUE TITLE
Real regexes can not be used in exclude uri

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#389]
using something like `/\w+/mypage` is cleaned to `\w+/mypage` due to `rocket_clean_exclude_file` so no regex past wildcards can really get used.

**Comment by GeekPress** [comment]
Hi @pcfreak30 

And how this "issue" could be fixed?

**Comment by pcfreak30** [comment]
dont use rocket_clean_exclude_file? Your trying to allow a regex but then stripping it as its not a valid url.

**Comment by glueckpress** [comment]
Duplicates #233.
