### ISSUE TITLE
3.9 Alpha 5 and 6: Accessing website from IE11 while delay js is enabled isnot redirecting to the uncached version of the page

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3892]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Alpha 6
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
Accessing the website from IE11 while new delayjs is on, not redirecting to the uncached version as mentioned in the doc but using the cached version (Using the theme as Sydney, the user will stuck in white page with loader and nothing happen when user make any action)

**To Reproduce**
1. From the dashboard make sure that delayjs is on
2. Visit the home page from IE11
3. No redirection to the uncached version of page

**Expected behavior**
Redirect to the uncached version of the page as IE11 is not compatible with this feature as mentioned here https://www.notion.so/wpmedia/Delay-JS-Docs-49e40c0b46ae424eb9e2aeb04833ce4c

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@wp-media/php I would need someone with an environment where they can run IE11 to test & debug this. The inline script to do the redirection is included in the page, but there might be something wrong with it.

**Comment by gevcen** [comment]
Isn't it time to drop the support for Internet Explorer? Considering that Edge Chromium released the [integrated "IE Mode"](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode) to allow running old websites or programs for enterprises and/or individuals, I believe that no one still has a valid reason to keep using this dinosaure browser of the web. Don't you think?

Source : https://gs.statcounter.com/browser-market-share#monthly-202101-202104-bar
![image](https://user-images.githubusercontent.com/51261962/117492151-7d1ab680-af71-11eb-9d40-7cf9c236e629.png)

**Comment by piotrbak** [comment]
Wasn't able to reproduce this on the latest version 3.9-alpha8

**Comment by GeekPress** [comment]
@gevcen This is what we are doing. Delay JS isn't supported on IE11. We are just redirecting to the uncached version if a visitor is using IE11 to avoid navigating to an unusable website.

**Comment by Mai-Saad** [comment]
Fixed at my side too on 3.9 alpha9

**Comment by GeekPress** [comment]
@Mai-Saad Thanks for the confirmation, I'm closing it.
