### ISSUE TITLE
3.9 alpha5: Absolute URL of file isnot excluded from RUCSS when added to safelist

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3893]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9 alpha5
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
When we use the absolute URL of the file in the safelist of RUCSS, we still remove the unused CSS in that file and not preserving it in the Used CSS

**To Reproduce**
Precondition:
Having a page using an external CSS file containing some used/unused CSS

1. In the file optimization tab, enable RUCSS
2. Add the absolute URL of the used CSS file  and save
3. Access the page containing the excluded CSS file
4. Check Source, all unused CSS from the excluded file isn't added to the internal used CSS

**Expected behavior**
- All the CSS in the excluded file is preserved in the internal used CSS even if not used
- Maybe we will just ignore the domain part and handle it as same as we handle the relative path of file

**Additional context**
- Used template: https://github.com/wp-media/rocket-test-data/blob/master/templates/rucss_externalCss_template.php
- Used external CSS: https://github.com/wp-media/rocket-test-data/blob/master/styles/rucss_styles1.css and https://github.com/wp-media/rocket-test-data/blob/master/styles/rucss_styles2.css
- Relative URL of the file is working fine i.e '/wp-content/rocket-test-data/styles/rucss_styles2.css'

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
I'm having trouble reproducing this.

I added `https://tests.local/wp-content/themes/storefront/style.css?ver=3.5.1` in the safelist, which is the main style file of the theme.

Then cleared the cache and used CSS.

The new generation correctly contains the used CSS, including the CSS from the file in the safelist.

**Comment by Mai-Saad** [comment]
@Tabrisrp Still can reproduce it on alpha7 zip

https://user-images.githubusercontent.com/76941962/117644059-62228f00-b189-11eb-892e-18a4d3f44849.mp4

It's live here: https://new.rocketlabsqa.ovh/rucssexternalcss/

Note: I tried to add this `div.first {
  opacity: 0.1;
  background-image: url("/wp-content/rocket-test-data/images/paper.jpeg");
  }` in the active theme and add the theme file URL to safelist then clear cache and UCSS and access the page still can't find `.first` in the used CSS

**Comment by piotrbak** [comment]
The absolute URL exclusion worked for me in `alpha9`

**Comment by Mai-Saad** [comment]
- Still existing for a template that has relative URL in DOM then we add the absolute URL to safelist (slack discussion: https://wp-media.slack.com/archives/G01AMD70N7P/p1621324106010900?thread_ts=1621281267.098800&cid=G01AMD70N7P)
-  While it`s working fine for the theme ( added unused class in theme file print.css then added absolute URL of this file to safelist)

**Comment by remyperona** [comment]
Issue happens if you input the full URL in the exclusion, but on the front end links are using relative URLs.

**Comment by piotrbak** [comment]
We won't fix this. We didn't receive any complaint about this + that kind of setup and exclusion seem to be an edge case.
