### ISSUE TITLE
AMP plugin - Optimizations aren't applied when using the Standard Template mode

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3894]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

With the official [AMP plugin](https://wordpress.org/plugins/amp/), when the **Standard Template mode** is selected, none of WP Rocket's optimizations are being applied.
This is because the site uses a single theme and there is a single version of your content - the AMP one.

**To Reproduce**
1. Install the [AMP plugin](https://wordpress.org/plugins/amp/).
2. Make sure the **Standard Template mode** is selected:
![](https://i.vgy.me/e34J8t.jpg)
3. Enable WP Rocket's CSS/JavaScript minification.
4. Check the source code of a page. It won't include minified CSS/JavaScript files.

**Expected behavior**

When the specific option is used, display a notice suggesting changing to the **Transitional Template mode**, which allows optimizations to work:
![](https://i.vgy.me/TjdK9P.jpg)

**Additional context**

**Related ticket:** **https://secure.helpscout.net/conversation/1502538987/261269**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
That's the expect behaviour, isn't it? We disable a lot of things when AMP is taking control of the site output, to avoid conflicts and validation errors.

**Comment by vmanthos** [comment]
It _is_ an expected behavior.

I opened this issue to explore the possibility of adding a notice when the specific AMP option is active.

Doing that will allow customers to "resolve" the lack of file optimizations quicker, without
reaching out to support.

**Comment by remyperona** [comment]
With 3 different possible modes of AMP, we possibly need to discuss what needs to happen for each one now, because this became more complicated than what was happening initially.

@GeekPress Maybe something to investigate and take a decision on at some point.

**Comment by DahmaniAdame** [comment]
"Standard Mode" is meant for fully AMPified websites (AMP is served on both desktop and mobile). 

There is no CSS to process (added inline), or possibility to do the lazyload (natively supported), or to do any optimization for JS (minified, only few files load async).

Whatever is served through AMP is already optimized, so, improvement venues might be very limited. 

From what I could find, here are a couple of things that might qualify for potential improvement: 

- Adding resource hints to preload critical assets to improve the FCP (applies to the AMP library and images) - could be something we can cover!
- Server-Side Rendering to help JS kick in and start populating the page before it's sent to the browser. That if we are to explore SSR at some point in the future (could be useful for website relying on JS to render some parts of the page ~~and React-based themes as well~~).

Maybe, for now, we can simply show a notification saying that our optimization won't happen if the Standard Mode is in use? and explaining why.

The other two modes could have us keep desktop optimizations happening and stopping the optimization only for mobile. Which we already do.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
