### ISSUE TITLE
CSS/JS minification not working when the custom wp-content folder name matches the TLD

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3897]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When `WP_CONTENT_FOLDERNAME` has been customized to match exactly the site's TLD, CSS/JavaScript modification isn't working for internal files.

For example, this is happening when on https://www.example.com, `wp-content` is set to `example`. So:
```PHP
define('WP_CONTENT_FOLDERNAME', 'example');
define('WP_CONTENT_DIR', ABSPATH . WP_CONTENT_FOLDERNAME);
define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_CONTENT_URL', WP_SITEURL . WP_CONTENT_FOLDERNAME);
```

This is happening because of the `str_replace()` we are using here:
https://github.com/wp-media/wp-rocket/blob/b1d347a1e107c51329cad93514462e386f47a3f4/inc/functions/formatting.php#L474

which results in the `$root_url` being `https://.com/` following the previous example.

So, `$file` becomes `/example.com/wp-includes/css/dist/block-library/style.min.css` here:
https://github.com/wp-media/wp-rocket/blob/b1d347a1e107c51329cad93514462e386f47a3f4/inc/functions/formatting.php#L498

This isn't a valid path,  `rocket_url_to_path()` returns `false`, and the modification process stops here:
https://github.com/wp-media/wp-rocket/blob/b1d347a1e107c51329cad93514462e386f47a3f4/inc/Engine/Optimization/Minify/CSS/Minify.php#L154

**To Reproduce**

1. Use the code provided earlier to change the name/path of the `wp-content` folder to match exactly the TLD.
2. Rename the `wp-content` folder to the TLD.
3. Enable CSS/JavaScript minification.
4. Check the source code for internal minified CSS/JavaScript files.

**Expected behavior**

CSS/JavaScript modification should be working even when the `wp-content` folder's name matches the TLD.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1503394540/261488

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
