### ISSUE TITLE
Log all response errors from wp_remote requests

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#39]
Originally reported by: **Jonathan Buttigieg (Bitbucket: [wp-media](https://bitbucket.org/wp-media), GitHub: [wp-media](https://github.com/wp-media))**

---

---
- Bitbucket: https://bitbucket.org/wp-media/wp-rocket/issue/40

**Comment by Tabrisrp** [comment]
Will be part of #1053
