### ISSUE TITLE
RUCSS generation problem on multisite

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3901]
**Before submitting an issue please check that you’ve completed the following steps:**
- 3.9alpha7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When running the RUCSS process at the same time on 2 separate websites within one network, the process is not initialized on the second one.

**To Reproduce**
1. Remove from the database all tables + data from `wp_options` related to the RUCSS for all subsites
2. Open 2 sites' dashboard
3. Enable RUCSS at the same time on both of them

**Expected behavior**
We should be able to work in parallel

**Screenshots**
https://jmp.sh/LJzw77J

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Would it be related to https://github.com/wp-media/wp-rocket/issues/1686

**Comment by iCaspar** [comment]
I'm not able to reproduce this locally.
@piotrbak, can you please confirm whether this is still an issue on your test site(s).
I'm guessing that #1686 / https://github.com/wp-media/background-processing/pull/3 has solved this?

**Comment by piotrbak** [comment]
Closed with 3.11, WP Background Processing is not used anymore for RUCSS
