### ISSUE TITLE
3.9 Alpha 7: Progress bar loader for RUCSS is not styled on Firefox

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3902]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
The progress bar displayed after RUCSS is enabled is not green color as on other browsers

**To Reproduce**
1. Open the dashboard on Firefox
2. In WPR settings => enable RUCSS
3. See the progress bar color is grey

**Expected behavior**
The progress bar is green

**Screenshots**
![Screenshot from 2021-05-11 10-23-37](https://user-images.githubusercontent.com/76941962/117786592-f81bef80-b245-11eb-883e-784f393881d3.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
https://developer.mozilla.org/fr/docs/Web/CSS/::-moz-progress-bar
