### ISSUE TITLE
Documentation about rocket_clean_minify()

### ISSUE THREAD

**Issue by CyberCr33p** [wp-media/wp-rocket#3903]
Add documentation about rocket_clean_minify() here:

https://docs.wp-rocket.me/category/89-functions

**Comment by piotrbak** [comment]
@camilamadronero Would you take a look at this one?

**Comment by piotrbak** [comment]
It'll be added to the docs.

**Comment by camilamadronero** [comment]
Hey! There's already a [section for this function in this related doc](https://docs.wp-rocket.me/article/1801-how-to-programmatically-clear-the-cache-and-optimizations#delete-minified-files).
