### ISSUE TITLE
PHP 7.4 compatibility warning

### ISSUE THREAD

**Issue by mircobabini** [wp-media/wp-rocket#3904]
**Describe the bug**
The composer dependency `matthiasmullie/minify` is NOT at its latest version.

PHP Compatibility Checker on PHP7.4 is reporting `528 | WARNING | Passing the $glue and $pieces parameters in reverse order to implode has been deprecated since PHP 7.4; $glue should be the first parameter and $pieces the second`

This is already fixed in the latest version of `matthiasmullie/minify`.
Should update the dependencies.

**To Reproduce**
`$ ./vendor/bin/phpcs --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.4 wp-content/plugins/wp-rocket/`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Hi @mircobabini,

Which version of our plugin did you test this with? Here is the current trunk version for this file and this line: https://github.com/wp-media/wp-rocket/blob/4f86c478c74e962eb6361b59a0f0b575adab27a9/inc/Dependencies/Minify/CSS.php#L528

It looks correct with the parameters in the expected order. Therefore I'm closing this issue.

Feel free to comment if my findings are incorrect.
