### ISSUE TITLE
Add « Beta » mention for Remove Unused CSS option.

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3905]
**Describe the solution you'd like**
Like we are doing for minification options, we would like to display a confirmation message before to be able to activate Remove Unused CSS.

Even if our feature is working properly, we still need to improve our compatibilities with themes/plugins. We know during our QA phase we weren't able to think and find all edge cases. We also need to start releasing this feature to get feedback to improve it.

By adding a « Beta » mention, we want to let our users know that the feature could sometimes not properly work and why.

- Title: We’re still working on it!
- Text: This is a beta feature. We’re providing you early access but some changes might be added later on. If you notice any errors on your website, simply deactivate the feature.
- CTA: Activate Remove Unused CSS

The option name will be renamed to « Remove Unused CSS (Beta) »

**Comment by jazir555** [comment]
Will it be compatible with elementor on release?
