### ISSUE TITLE
rocket_clean_post ignores no purge no-cache-auto-purge

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#3910]
Hello.

Expected result: When rocket_clean_post runs, it should clean the post/product page and stop.

We have experienced an issue that was not causing any issues before. We are using no cache auto purge helper to disable cache clearing on a WooCommerce website. We have noticed that rocket_clean_post() was ignoring the no cache auto purge, and even the rocket_post_purge_urls filter.

We did a test. We've added a log at function rocket_get_purge_urls and rocket_clean_post to list the $purge_urls on an error_log and triggered rocket_clean_post(XXXXX) where XXXXX is the post_id.

We saw that it only listed product permalink and author. Though, seeking on cache folder, we've realized that wp rocket cleared not only the product page cache, but also its category page, parent category page, relative products etc. It ignored the helper for no-cache-auto-purge.

We have also made another test, added on functions.php the filter rocket_post_purge_urls to return an empty array. We, then ran rocket_clean_post(XXXXX) but still, it cleared all the default $urls and not the empty array we've set.

Any advise is welcome

**Comment by piotrbak** [comment]
Hello @seldimi thanks for creating the issue. We use Github to report bugs in our code and feature requests. Please be in touch with our Support Team and they'll help you to track down what's clearing the cache and how to stop it.

If you prefer to investigate the things on your own, please find this function useful:
https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/functions/files.php#L969

All cache files cleaned by WP Rocket are going there.
