### ISSUE TITLE
Replace sidebar content

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3913]
**Describe the solution you'd like**
We would like to update the content of our sidebar.

> Learn how to use best practices to correctly measure your site's performance.

This text will be replaced by

**Learn about optimal WP Rocket settings for mobile.**

CTA: 
- EN: https://docs.wp-rocket.me/article/1402-how-to-improve-your-mobile-pagespeed-score
- FR: https://fr.docs.wp-rocket.me/article/1432-comment-ameliorer-score-mobile-pagespeed

> Why Google PageSpeed grade should not matter

This text will be replaced by

**Test and Improve Google Core Web Vitals for WordPress.**

CTA: https://wp-rocket.me/google-core-web-vitals-wordpress/

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `views/settings/partials/sidebar.php`

Replace the texts and links by the new value we want to display. For the first CTA displayed in different languages, we need to add a check for the current user locale to determine which version to show.

### Estimate the effort ✅
Effort `[XS]`
