### ISSUE TITLE
Don't clear Used CSS files if the lifespan is set to 0

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3915]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Currently, if the page wasn't visited/PHP wasn't triggered for 30 days, we'll remove the Used CSS file to clean unused things.

**Expected behavior**
 I'd suggest not to remove them if the lifespan is set to 0.

**Additional context**
It's probably not a very often situation, but it's possible that someone will keep the same cached file for 30 days.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
I'm closing this issue as we won't need to fix it with the changes we did in 3.10.
