### ISSUE TITLE
3.9 alpha 9: safelist isnot reflected on cached used CSS until we clear the used CSS when OCD is re-enabled after editing safelist

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3919]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
Safelist added while having cached used CSS (and OCD off) is not reflected on the used CSS file when enable OCD until we clear the used CSS

**To Reproduce**
1- RUCSS  and OCD are on
2- Access a page containing unused CSS => used CSS file version is created
3- Disable OCD and Add item to safelist i.e .class and save
4- Hard refresh the page and check used CSS => unused CSS of the mentioned class is there inline
5- Enable OCD and hard refresh the page and check used CSS => unused CSS of the mentioned class is not there in the used CSS file

**Expected behavior**
 Safelist is reflected on the used CSS file

**Screenshots**

https://user-images.githubusercontent.com/76941962/118641210-2798a200-b7da-11eb-8b41-c47cca0c843f.mp4

**Additional context**
- clear used CSS then revisit the page, will fix the problem

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
We only update the static file if OCD is enabled at the time we save the used CSS in the table.

This means that if the static file already exists => then OCD is disabled => then used CSS is regenerated => then OCD is re-enabled = OCD file out-of-date.

**Comment by piotrbak** [comment]
@Mai-Saad Closing it, since we can't enable OCD and RUCSS at the same time now.
