### ISSUE TITLE
Jetpack Stat's Icon Shows When Using Remove Unused CSS

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#3923]
Basically just that as the title suggests, I use jetpack stats and it uses the silly invisible icon at the footer, activated the feature the icon started showing the fix was to add the following rule to the CSS safelist:

#wpstats

CSS rule removed
`img#wpstats{display:none}`

Jetpack stats is automatically activated when Jetpack is installed on a WordPress site so the test procedures for replication should be pretty standard.

**Comment by piotrbak** [comment]
It's not present in the DOM, added by this file:
https://stats.wp.com/e-202120.js
`_loadGif('g.gif',_serialize(o),'wpstats');`

The final element is:
```
<img src="https://pixel.wp.com/g.gif?v=ext&amp;j=1%3A9.6.1&amp;blog=188106414&amp;post=0&amp;tz=0&amp;&amp;ref=&amp;fcp=229&amp;rand=0.9226740278204668" alt=":)" width="6" height="5" id="wpstats">
```

**Comment by GeekPress** [comment]
@Tabrisrp We can directly add `#wpstats` in Tree Shaker safe list, what do you think?

The ID isn't common, and the original JS filename seems to be dynamic, so we can't totally rely on it.

**Comment by remyperona** [comment]
yes that's the best solution

**Comment by GeekPress** [comment]
@Tabrisrp I have created an issue on Tree Shaker repo, if this can be handle in priority as it's easy to fix 🙏

**Comment by remyperona** [comment]
Hey @ScottTravisHartley, we deployed & tested a fix for this on our production server, can you clean the used CSS on the website affected and re-test on your side?

**Comment by ScottTravisHartley** [comment]
This appears to be fixed on my end now

**Comment by remyperona** [comment]
Awesome thank you, closing the issue then
