### ISSUE TITLE
Remove Unused CSS "More Info" Link Is Broken

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#3924]
The Remove Unused CSS feature when its processing pages has a notice that reads as follows. 

![image](https://user-images.githubusercontent.com/45110039/118850548-828fcf00-b896-11eb-8542-1d6efab78076.png)

We are processing the CSS on your site. This may take several minutes to complete. More info. The More Info link doesn't go anywhere its just pointed as an # so you just get a screen such as the following. 

![image](https://user-images.githubusercontent.com/45110039/118850470-6c820e80-b896-11eb-8365-7544321b1577.png)

**Comment by remyperona** [comment]
@GeekPress @webtrainingwheels  Do we want to link this to anything, or remove it?

**Comment by webtrainingwheels** [comment]
@Tabrisrp Let's link it to the main doc for now: https://docs.wp-rocket.me/article/1529-remove-unused-css
If we get more insight into common issues, etc we may update it to a more specific link

**Comment by GeekPress** [comment]
We already have "more info" next to the option name which redirects to the same doc. Except if we plan to add a section related to the pre-warmup in this doc, we can keep it, if we have no plan, we can remove it.

**Comment by remyperona** [comment]
@webtrainingwheels what do you think?
