### ISSUE TITLE
Delay JS: Let users choose what scripts to delay like in 3.8

### ISSUE THREAD

**Issue by socialpreneur** [wp-media/wp-rocket#3930]
**Is your feature request related to a problem? Please describe.**
3.9 release will cause a lot of troubles unless users exclude all the scripts with errors.

**Describe the solution you'd like**
Just follow previous versions, 3.8.x series, where we were able to manually delay scripts.

**Describe alternatives you've considered**
Flying Scripts, Perfmatters, FlyingPress.

**Comment by NicoCaldo** [comment]
I completely agree with this. Delaying indiscriminately every JSs will bring 100% error on every website and finding out which JS don't need to be delayed will be a titanic work if you have more than, let's say 5.

Don't fix something that ain't broken.

**Comment by GeekPress** [comment]
Hi,

Our new Delay JS is more compatible than the previous script and works most of the time. Like every new feature, it will require some time to make it even more compatible. We know what is required to provide the best performance on a website, this new approach is the way to go.

We won't revert back to the previous solution. 

If you want to have the same behavior as before (just on 3rd party); you can add this in the exclusion list:

(?:wp-content|wp-includes)(.*) - to exclude all internal JS files
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js - to exclude jQuery
js-(before|after) - to exclude inline scripts
