### ISSUE TITLE
Impreza Theme - JS delay issue after upgrading to 3.9

### ISSUE THREAD

**Issue by TheZoker** [wp-media/wp-rocket#3932]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before (maybe related to #3931) ✅ 

**Describe the bug**
Every time I enable js delay within wp-rocket 3.9, I get the following error in the console (see screenshot 1). I get this on every website, where I use wp-rocket and the [Impreza theme ](https://themeforest.net/item/impreza-retina-responsive-wordpress-theme/6434280). The issue did not occur before 3.9 
On some websites, this issue does not cause any visual problems, but on other pages it does. 
I also tried to exclude the file from JS delay, that seems to cause the error (screenshot 2), but that does not change anything. 

**To Reproduce**
1. Enable `Delay Javascript execution` option
2. Use Impreza theme
3. Watch frontend console

**Expected behavior**
The option should not break theme functions, especially if the file is excluded from defer loading. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1368405/118952044-e4fed300-b95b-11eb-9a00-6d6c444d174b.png)

![image](https://user-images.githubusercontent.com/1368405/118952290-1b3c5280-b95c-11eb-9252-c9871cc24f40.png)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@TheZoker Hi!

Can you please open a ticket support and share us your WordPress access?

https://wp-rocket.me/support/

Thanks

**Comment by GeekPress** [comment]
@wp-media/php I have started a branch with the auto-compatibility with Impreza theme https://github.com/wp-media/wp-rocket/tree/fix-3932

**Comment by TheZoker** [comment]
Very nice, will test this out in the coming days! Thanks
