### ISSUE TITLE
js-(extra|after) Only Works If Script Tag has "type='text/javascript'"

### ISSUE THREAD

**Issue by thekendog** [wp-media/wp-rocket#3935]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yup, on 3.9.
- Used the search feature to ensure that the bug hasn’t been reported before - There are some recent JS delay issues but not exactly this.

**Describe the bug**
The Impreza theme outputs certain javascript options in an inline script.  The script tag does have type='text/javascript' added to it.  This script is not being excluded using the js-(extra|after) exclusion filter.

**To Reproduce**

**Expected behavior**
The inline script should not have type="rocketlazyloadscript" added.

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@thekendog Hi!

The problem isn't the missing type, but the missing id. You will need to find another pattern to exclude the inline script. It could be something inside the inline script.

**Comment by thekendog** [comment]
Ah, okay.  Figured it out.  Thanks!
