### ISSUE TITLE
MS Edge "smart screen" complains about iframes LazyLoad

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#394]
When the iframes option for LazyLoad is active, it triggers an "unsafe" warning. 
e.g https://secure.helpscout.net/conversation/345322788/37480/?folderId=273764
https://secure.helpscout.net/conversation/346658382/37670/?folderId=377611 (this ticket contains screenshots)
Related to the new placeholder we use.

**Comment by Tabrisrp** [comment]
Should be fixed with the new placeholder in v2.10.8
