### ISSUE TITLE
Excluding Avada menu script to allow the menu to load without delay (Delay JavaScript Exclusions - DJE)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3941]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using the customer header module on Avada, the menu starts the menu with opacity 0 (invisible), and then Avada uses JS to trigger its change to 1 (visible).

When DJE is enabled, the menu will remain invisible until there is user interaction. 

**To Reproduce**
1. Avada website. Use a customer header (happens only when custom headers are enabled).
2. Enable our DJE.
3. Check a page with a custom menu header.
4. See the menu remaining invisible.

**Expected behavior**
It's best to have the menu show on the first paint rather than have displayed after user interaction. 

**Screenshots**
N/A

**Additional context**
Excluding the following keyword from DJE fixes the issue. 

**fusionNavIsCollapsed**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@DahmaniAdame Can I please let you check with @vmanthos to try the last version of our Delay JS script?

**Comment by DahmaniAdame** [comment]
@GeekPress checking with @vmanthos. I will let you know the results.

**Comment by DahmaniAdame** [comment]
@GeekPress it worked to some extent. From my testing, CWV were the exact same. 
But still, from the real user perspective, having to wait for 2s to see the menu (in this particular case) is not a good user experience. 
The new timeout will surely help fix other use cases. Visual elements above the fold and things that need to be prioritized might still need to be excluded fully from DJE.

**Comment by GeekPress** [comment]
@DahmaniAdame Did you find the right JS file to exclude from being delayed?

**Comment by DahmaniAdame** [comment]
@GeekPress yes! It's: 
`fusionNavIsCollapsed`

Waiting for the customer's feedback to confirm. 

A quick comparison between the exclusion and the timeout only.

![image](https://user-images.githubusercontent.com/1289174/119559168-3b27a800-bd9a-11eb-8d41-e24396f6dd29.png)

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1519304192/265606/
