### ISSUE TITLE
Add "Restore Default" button below the exception list of Delay JS v2

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3942]
**Is your feature request related to a problem? Please describe.**
When I updated WP Rocket to 3.9, the Delay JS has added automatically some elements in the exception list. However, if user modifies the list, the default values cannot be retrieved anymore.

**Describe the solution you'd like**
Add a button "Restore Default Values" just like we had before in the Delay JS v1

**Describe alternatives you've considered**
Add the default values list in the documentation ?

**Additional context**

![image](https://user-images.githubusercontent.com/51261962/119258597-ae7abf80-bbca-11eb-8879-99ffbad3b841.png)

**Comment by GeekPress** [comment]
Hi @gevcen 

This default list is only for user updating from 3.7/3.8 to 3.9. As our previous default inclusion list was only for 3rd party, we decided to automatically exclude all internal JS files for users on 3.7/3.8 and with Delay JS on.

When you will install WP Rocket 3.9 on  a new website, these exclusions won't be inserted.

We can retrieve this list here: https://docs.wp-rocket.me/article/1349-delay-javascript-execution#troubleshooting
