### ISSUE TITLE
Add incompatibility notice when WP Meteor is activated and our Delay JS too

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3945]
**Is your feature request related to a problem? Please describe.**
WP Meteor is a plugin that delays all JS scripts.

This plugin will be in conflict with our Delay JS when it's activated. 

**Describe the solution you'd like**
Add WP Meteor to our list of conflicted plugins when our Delay JS option is activated.

**Comment by aguidrevitch** [comment]
Any examples of incompatibility issues? Or, how can I make WP Meteor compatible?

**Comment by GeekPress** [comment]
WP Meteor is compatible WP Rocket, but not when our Delay JS is turned on. The notice is displayed only if our Delay JS option is turned. 

It doesn't make any sense to have two scripts that will delay all JS and by using different solutions by the way.

**Comment by aguidrevitch** [comment]
> WP Meteor is compatible WP Rocket, but not when our Delay JS is turned on. The notice is displayed only if our Delay JS option is turned.
> 
> It doesn't make any sense to have two scripts that will delay all JS and by using different solutions by the way.

Absolutely no sense to have both. But giving 'Disable other plugin'  is, umm, let's say, a one way suggeston. I would have to add a notice about the other option - to disable WP Rocket's 'Delay Javascript Execution' and use WP Meteor instead.

**Comment by GeekPress** [comment]
> But giving 'Disable other plugin' is, umm, let's say, a one way suggeston.

It's a way to avoid our users to have problem.

Why are doing that?
Because we already had tickets about users using both at the same. Our role is to « protect » our users from conflicts.

>  I would have to add a notice about the other option - to disable WP Rocket's 'Delay Javascript Execution' and use WP Meteor instead.

If you are adding a notice too, that's going to be very confused for the users... 

I don't really understand what is the problem on your side. We are doing this with all conflicted plugins and it has never been a problem.

**Comment by aguidrevitch** [comment]
> I don't really understand what is the problem on your side. We are doing this with all conflicted plugins and it has never been a problem.

Because I'm the author of WP Meteor

**Comment by GeekPress** [comment]
> Because I'm the author of WP Meteor

And what is the problem?

**Comment by aguidrevitch** [comment]
> Because we already had tickets about users using both at the same. Our role is to « protect » our users from conflicts.
My role is to protect my users as well. My users come to me asking about the message and I have to explain each of them that only 'Delay Javascript Execution' is conflicting option, not the whole plugin.

**Comment by GeekPress** [comment]
@aguidrevitch I forgot we can do something else. Here an example of what we are doing when we detect Lazyload option activated on Autoptimize: https://share.getcloudapp.com/jkuPPqQq

We will do the same for Delay JS and WP Meteor. It means that we won't have a global notice like now to suggest disabling WP Meteor.

I will let you know once it will be released so you could remove the notice on your side too.

Does it sound good to you?

**Comment by aguidrevitch** [comment]
> @aguidrevitch I forgot we can do something else. Here an example of what we are doing when we detect Lazyload option activated on Autoptimize: https://share.getcloudapp.com/jkuPPqQq
> 
> We will do the same for Delay JS and WP Meteor. It means that we won't have a global notice like now to suggest disabling WP Meteor.
> 
> I will let you know once it will be released so you could remove the notice on your side too.
> 
> Does it sound good to you?

It sounds amazing, thanks! I will put the same warning in WP Meteor with suggestion to disable WP Meteor if user wants to use WP Rocket's 'Delay Javascript Execution'
