### ISSUE TITLE
Relative CDN URL rewriting breaks BuddyPress 'Change Avatar'

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#395]
WP Rocket's CDN rewrite breaks the BuddyPress Change Avatar screen. 
After the user uploads an image they should be able to crop it. Apparently on this screen BP uses a relative URL for the image.

tickets: 
https://secure.helpscout.net/conversation/332606202/35515/?folderId=377611
https://secure.helpscout.net/conversation/350273108/38196/?folderId=273761
https://secure.helpscout.net/conversation/347769213/37823/?folderId=273764

**Comment by EnactA2** [comment]
@webtrainingwheels 
@Tabrisrp 

Is there any progress on this issue? My site is suffering from it right now.

PHP 7.1.6
WP 4.8
BuddyPress 2.8.2 (also tested using 2.9 beta)
WP Rocket 2.10.6

**Comment by EnactA2** [comment]
Also, I have CC'd the BuddyPress developer. Maybe he will/can assist with this issue, to get it fixed more quickly.

**Comment by EnactA2** [comment]
Bueller? Bueller? Bueller? ... [https://www.youtube.com/watch?v=KS6f1MKpLGM](url)
