### ISSUE TITLE
mysqldump Error 1412 on wp_wpr_rucss_used_css

### ISSUE THREAD

**Issue by jcatello** [wp-media/wp-rocket#3951]
We noticed since introducing removing unused css the following error happens during automated backups.

` mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table wp_wpr_rucss_used_css at row: 0`

I cannot reproduce it when dumping the table by itself

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @jcatello thanks for creating the issue. We haven't heard about any similar problem during that time.

The error you mentioned claims that the table was altered or deleted during the transaction, this should not be caused by us. Could you tell me if you're still experiencing this issue?

**Comment by piotrbak** [comment]
We haven't heard about this issue for almost one year already and we can't reproduce it. If you're still experiencing the issue, feel free to reopen it.
