### ISSUE TITLE
Gravity Form disappears if jQuery is deferred

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3958]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
When Defer JS is applied to jQuery, Gravity Forms get "invisible" with no console errors.
This is happening since GR 2.5, and we're getting some tickets about it.

the form code is present in the HTML, but is not displayed because it contains an inline `display: none`
https://jmp.sh/zxdhubX
And, when jQuery is deferred, this code doesn't trigger: https://jmp.sh/dJltr9A
<img width="524" alt="Screen Shot 2021-05-27 at 11 57 02 AM" src="https://user-images.githubusercontent.com/229406/119849146-c3b16000-bee2-11eb-8b6e-d7b4d09f10ce.png">

The solution is to exclude jQuery from deferring, adding `/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js` to our exclusion box.

I wasn't able to find this style to be coming from a setting in Gravity Forms. 

**To Reproduce**
1. On a page with a Gravity Form displayed
2. Defer jQuery
3. See the Form disappearing
4. See no console error
5. Exclude jQuery form deferring
6. See the form working as normal again

**Expected behavior**
We should investigate if an automatic exclusion for jQuery from deferring JS is needed using a Gravity form, to prevent the forms from breaking, or if we could provide a more performant solution.

**Screenshots**
A video demo of the issue here: http://recordit.co/MPfvS4McXi

**Additional context**
Tickets: 
https://secure.helpscout.net/conversation/1518570662/265368?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@alfonso100 When Deferred JS is on, this inline should be wrapped into a DOMContentLoaded event. Was it the case?

**Comment by alfonso100** [comment]
@GeekPress In this case, `#gform_wrapper_28` is the ID of a form that's not being displayed.

And this is the current code, they use 2 different scripts, and we are wrapping both:

```
<script type='text/javascript'>window.addEventListener('DOMContentLoaded', function() { jQuery(document).bind('gform_post_render', function(event, formId, currentPage){if(formId == 28) {gf_global["number_formats"][28] = {"3":{"price":false,"value":false},"2":{"price":false,"value":false},"1":{"price":false,"value":false},"4":{"price":false,"value":false},"5":{"price":false,"value":false},"8":{"price":false,"value":false},"21":{"price":false,"value":false},"18":{"price":false,"value":false},"17":{"price":false,"value":false},"9":{"price":false,"value":false},"22":{"price":false,"value":false}};if(window['jQuery']){if(!window['gf_form_conditional_logic'])window['gf_form_conditional_logic'] = new Array();window['gf_form_conditional_logic'][28] = { logic: { 9: {"field":{"actionType":"show","logicType":"all","rules":[{"fieldId":"8","operator":"is","value":"Anders"}]},"nextButton":null,"section":null} }, dependents: { 9: [9] }, animation: 0, defaults: {"3":{"3.2":"","3.3":"","3.4":"","3.6":"","3.8":""}}, fields: {"3":[],"2":[],"1":[],"4":[],"5":[],"8":[9],"21":[],"18":[],"17":[],"9":[],"22":[]} }; if(!window['gf_number_format'])window['gf_number_format'] = 'decimal_dot';jQuery(document).ready(function(){gf_apply_rules(28, [9], true);jQuery('#gform_wrapper_28').show();jQuery(document).trigger('gform_post_conditional_logic', [28, null, true]);} );} if(typeof Placeholders != 'undefined'){
                        Placeholders.enable();
                    }} } );jQuery(document).bind('gform_post_conditional_logic', function(event, formId, fields, isInit){} );});</script>

<script type='text/javascript'> document.addEventListener( 'DOMContentLoaded', function(){jQuery(document).trigger('gform_post_render', [28, 1]) } ); </script>
```

**Comment by alfonso100** [comment]
This seems to be fixed on their side: https://docs.gravityforms.com/gravityforms-change-log/

> 2.5.3.1
> Fixed an issue which causes forms that rely on Javascript to not render in certain contexts.

asking a customer to see if they can test this update

**Comment by alfonso100** [comment]
A Customer confirmed that updating GR to the latest version, 2.5.3.1, fixes the issue: https://secure.helpscout.net/conversation/1524764536/266978?folderId=2683093

**Comment by GeekPress** [comment]
@alfonso100 Do we have new reports about the conflict? If not, we can close this issue.

**Comment by alfonso100** [comment]
@GeekPress no new reports. The last one was 6 days ago. closing this one 🙏
