### ISSUE TITLE
Caching key filter is missing

### ISSUE THREAD

**Issue by Ciantic** [wp-media/wp-rocket#396]
I'm trying to customize the cache key. With WP Super Cache it's this easy:

```
add_cacheaction( 'wp_cache_key', function ($key) { 
  return $key . $_SERVER["HTTP_CF_IPCOUNTRY"] 
});
```
Note: I want to add CloudFlare provided country code in the caching key.

I have identified the line of code I would like to customize in WP Rocket:

[Line 207 at inc/front/process.php](https://github.com/wp-media/wp-rocket/blob/master/inc/front/process.php#L207)
```
$rocket_cache_filepath = $request_uri_path . '/' . $filename . '.html';
```

But WP Rocket does not seem to provide a filter to modify the filepath so I could add extra identifier to there.

Thanks.

**Comment by glueckpress** [comment]
The bulk of [process.php](https://github.com/wp-media/wp-rocket/blob/master/inc/front/process.php) gets executed before WordPress filters are available, so adding a filter is not an option here.

Theoretically, a possible way around this could be to add a query string to the URL based on [`$_SERVER['HTTP_CF_IPCOUNTRY']`](https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-Cloudflare-IP-Geolocation-do-) and then have WP Rocket create extra caches for that query string via a setting in Advanced Options. 

Not sure if that would fit your use case, of course, but generally speaking, process.php can’t have filters, except inside of `do_rocket_callback()`.

**Comment by Ciantic** [comment]
That's why you should have equivalent of filters but not the WP filters, I suppose that's why WP Super Cache has function `add_cacheaction` which is not part of WP but part of WP Super Cache, in which WP Super Cache plugins can attach to.

Either way, I can already add it to URL as query string if I want, it's just really ugly there.

**Comment by glueckpress** [comment]
@Ciantic Alright, thanks for clarifying. Forwarded this, we’ll look into the idea.

**Comment by Tabrisrp** [comment]
This will be able to be revisited now that we required WP 4.7 and can use filters and actions in `process.php`

**Comment by cjhaas** [comment]
We have a need for this too. An `apply_filters` check could even be guarded by a magic constant that isn't normally defined if performance is a concern for the 99.999% of people that don't need this. I think this would be all done in [`/inc/classes/Buffer/class-cache.php`](https://github.com/wp-media/wp-rocket/blob/df26acdfbe015d056fc442cfbf28734f9635aa9f/inc/classes/Buffer/class-cache.php#L84)

It could either just be a filter on the file name itself:
```php
if (defined('WP_ROCKET_CUSTOM_CACHE_FILEPATH') && WP_ROCKET_CUSTOM_CACHE_FILEPATH) {
    $cache_filepath  = apply_filters('rocket_custom_cache_filepath', $cache_filepath );
}
```

Or appending to the file name:
```php
if (defined('WP_ROCKET_CUSTOM_CACHE_KEY') && WP_ROCKET_CUSTOM_CACHE_KEY) {
    $cache_filepath  .= apply_filters('rocket_custom_cache_key', '', $cache_filepath );
}
```

Obviously, performing complex logic in that filter could results in a major slowdown of the site, so implementers would have to be careful what they do, but I think that should be obvious to anyone using this, too.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future. We might reopen this in the future.
