### ISSUE TITLE
Notify the user that settings will be deleted after WP Rocket deletion 

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3964]
**Is your feature request related to a problem? Please describe.**
When users delete WP Rocket, we don't say at any stage that the settings will be deleted as well. 
Once the settings are deleted, they can't be recovered unless a backup of the settings is exported before the plugin uninstall. 
https://github.com/wp-media/wp-rocket/blob/75a25635ad7e1953fcd7fbfb288a2a7c5efeeeb9/inc/Engine/WPRocketUninstall.php#L168-L188

**Describe the solution you'd like**

- Either clearly state that the settings will be deleted, with a button to download the settings, and a recommendation to keep them safe in order to be able to restore the settings. 
- Or store the settings on the `/wp-content/uploads/` folder for example as a backup. Optionally have a way to import settings from `/wp-content/uploads/` if available. Few kb shouldn't be an issue if kept there.

**Describe alternatives you've considered**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1524209402/266848/

**Comment by remyperona** [comment]
Do we really need that? That's the default behaviour of the vast majority of the plugins, and also the recommended way: https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/

> When your plugin is uninstalled, you’ll want to clear out any plugin options and/or settings specific to to the plugin, and/or other database entities such as tables.

**Comment by DahmaniAdame** [comment]
@Tabrisrp I totally get why we are doing it. And it's the right thing to do. Uninstalling a plugin should indeed clean whatever it added. 

Tweaking performance could be time-consuming or even paid-for in some cases. Notifying the user to at least make a backup on uninstall would make sure the settings are not lost unexpectedly. 

I added it because of the last ticket about it. And to keep track if there is a need for it. I've only seen a couple of similar cases so far.

**Comment by piotrbak** [comment]
Closing it since upon the deactivation we're asking to export the settings.
