### ISSUE TITLE
RUCSS - 404 error for used CSS file when it is in a directory with an url-encoded name

### ISSUE THREAD

**Issue by gayanchandrab** [wp-media/wp-rocket#3968]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :white_check_mark: 3.9
- Used the search feature to ensure that the bug hasn’t been reported before :white_check_mark:

**Describe the bug**
When Remove Unused CSS with Optimize CSS Delivery is used together, file not found (404) error occurs if used CSS file is stored in a directory with an url-encoded name. 

For example if the url slug is in Hebrew, used css file will be stored in a url-encoded directory. And url for used css file will also contain url-encoded characters in the markup generated by WPRocket. When this page is visited, browser will not load used css file because of the 404 error. If the url-encoded directory is renamed to Hebrew characters manually, used css file is loaded correctly.

**To Reproduce**

**Expected behavior**
Used css file is loaded when critical css is also used for url-encoded permalinks.

**Screenshots**
![2021-05-29 13_50_18-Window](https://user-images.githubusercontent.com/38464697/120063487-f98e4a00-c084-11eb-8866-89788d58cee9.png)

![2021-05-29 13_42_02-Window](https://user-images.githubusercontent.com/38464697/120063285-078f9b00-c084-11eb-996f-cf9919bcbc3b.png)
![2021-05-29 13_42_35-Window](https://user-images.githubusercontent.com/38464697/120063292-0b232200-c084-11eb-8be1-ba4531defe3b.png)

![2021-05-29 13_12_59-Window](https://user-images.githubusercontent.com/38464697/120063144-64d71c80-c083-11eb-8e9e-cdce0ae4519a.png)

**Additional context**
I reproduced this issue on one of my sites. Screenshots are from it. This issue is there on a client site.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1557784125/275497?folderId=377611

**Comment by alfonso100** [comment]
https://secure.helpscout.net/conversation/1556756730/275243?folderId=2683093

**Comment by Mai-Saad** [comment]
Note for retesting:
- OCD is enabled
- create a page with AR slug
- enable RUCSS 
- Access this page  => in console used CSS file is canceled + accessing used CSS file in source gives 404

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1564890590/277649

**Comment by abdobasha2004** [comment]
I would like to suggest using post_id not post_url as identifier for CSS file

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1568979859/278862/

**Comment by vmanthos** [comment]
**Related:** https://secure.helpscout.net/conversation/1599809693/287145?folderId=2135277

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1613539137/290448?folderId=3864740

**Comment by DahmaniAdame** [comment]
A reported working fix by a customer is to use `urldecode()` on the `$path` variable - https://github.com/wp-media/wp-rocket/blob/v3.9.4/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L630

```$path = wp_parse_url( $used_css->url, PHP_URL_PATH );```

```
$path = urldecode(wp_parse_url( $used_css->url, PHP_URL_PATH ));
$path = wp_parse_url($used_css->url, PHP_URL_PATH);
if($path){
  $path = urldecode($path);
}
```

It needs to be tested for all encoded languages (Arabic, Chinese, Greek... etc).

Related ticket - https://secure.helpscout.net/conversation/1618087226/291505/

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1628080866/293994?folderId=2135277

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1637952005/296273/

**Comment by remyperona** [comment]
Closing this as starting from 3.10, we no longer save the used CSS as a file.
