### ISSUE TITLE
WPML Language Switcher dropdown doesn't expand anymore if Delay JS v2 enabled

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3969]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If you add a Language Switcher dropdown from WPML to your frontend and you enable Delay JS v2, then the dropdown doesn't expand when navigating in Incognito mode.

**To Reproduce**
1.  Install WP Rocket 3.9 and enable Delay JS v2
2. Install WPML and configure at least 2 languages
3. Add a Language Switcher to your header
4. Naviguate in Incognito mode
5. Hover the language switcher

**Expected behavior**
The language switcher doesn't expand. It should.

**Screenshots**
https://sgevcen.tinytake.com/tt/NTQ0NzExNV8xNzAzMDU5MA

![image](https://user-images.githubusercontent.com/51261962/120064287-b4a9e980-c06b-11eb-9fba-5e4b82ec6a28.png)

![image](https://user-images.githubusercontent.com/51261962/120064248-862c0e80-c06b-11eb-8d70-966b2c813bb3.png)

**Additional context**
I tried excluding WPML plugins from being delayed but it doesn't resolve it unfortunately.
/wp-content/plugins/wpml(.*)/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
The problem is related to Woodmart theme and not WPML directly.

These files need to be excluded from Delay JS to fix the problem:

```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/woodmart/js/scripts/global/helpers.js
/woodmart/js/scripts/menu/menuOffsets.js
```

We will investigate why we have to exclude 2 files of the theme and if we try to find a fix.

**Comment by gevcen** [comment]
Second issue with Woodmart identified, probably linked to this.

**Describe the bug**
If you enable Delay JS v2 with Woodmart theme and you add a mobile sidebar, WP Rocket generates some issues.

**To Reproduce**
Steps to reproduce the behavior:

- Install Woodmart theme
- Add a mobile sidebar (on both mobile & desktop for testing purpose)
- Enable WP Rocket Delay JS v2
- Try expanding the sidebar

**Expected behavior**
It should expand without issues. However, (1) it adds a # in the url which is unexpected (2) the mobile sidebar works only after you clicked for the second time on mobile (3) the mobile sidebar never works anymore when added to a desktop header

**Screenshots**
https://sgevcen.tinytake.com/tt/NTQ3MzkzMF8xNzEwNjI0MQ

**Additional context**
Credentials can be provided to the support if needed for testing purposes.

**Comment by gevcen** [comment]
Since its release 6.5.2, the Woodmart theme handles the JS files exclusions for WP Rocket automatically when enabling its feature. Therefore, this ticket can be closed.

![image](https://user-images.githubusercontent.com/51261962/174720959-6694a2ed-3d0f-4e97-bb2e-a92047ffb8fb.png)
