### ISSUE TITLE
Delay JS -  Woocommerce Product Reviews Pro plugin

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3970]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅checked with the Delay JavaScript script provided me on Monday, May 31.
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the Delay JavaScript execution is active the functionality of the [Woocommerce product reviews pro](http://www.woocommerce.com/products/woocommerce-product-reviews-pro/) plugin breaks.

The following exclusions resolved the issue on a customer's website:
```
/wp-includes/js/jquery/jquery-migrate.min.js
/woocommerce-product-reviews-pro/assets/js/frontend/wc-product-reviews-pro-frontend.min.js
/woocommerce/assets/js/jquery-tiptip/jquery.tipTip.min.js
wc_product_reviews_pro
```

**To Reproduce**
1. Install the [Woocommerce product reviews pro](http://www.woocommerce.com/products/woocommerce-product-reviews-pro/) plugin (paid).
2. Enable **Delay JavaScript execution** with no exclusions.
3. The review form will not work, i.e. clicking on the links won't change the displayed text area  (working -> https://youtu.be/aL9QPfPX4kw)

**Expected behavior**

The review form should work.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1518947601/265448/#thread-4428905359
For QA:  We can contact the customer to provide us access to the staging site.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
