### ISSUE TITLE
Lazyload: Uncaught TypeError: Assignment to constant variable when a constant "i" is declared

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#3976]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When a constant "i" is declared before this line (in the browser):

https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Dependencies/RocketLazyload/Assets.php#L104

The error Uncaught TypeError: Assignment to constant variable appears in the browsers console

**To Reproduce**
1. Add this test code to the website's <head>:
`			<script>
				 const i = true;
			</script>`
2. Activate Lazyload
3. Clear the cache
4. Try  and Check the browsers console

**Expected behavior**
This error doesn't appear when the page loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/120240673-c4216200-c226-11eb-9389-30387c7e4f52.png)

**Additional context**
This is caused because the next line is not declaring the variable "i" locally:

` for (i = 0; i < mutation.addedNodes.length; i++) {`

This means that if the variable is already declared / defined in a scope above, that declared variable will be used, but if the variable is not declared in a scope above, then it will be immediately declared in that line.

A possible solution could be adding a "var" keyword before the "i" variable, like this:

` for (var i = 0; i < mutation.addedNodes.length; i++) {`

This will declare a new "i" variable in the local scope, so, the global "i" won't be affected.

I can do the PR if needed.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced on local test site

### Identify the root cause ✅ 

> This is caused because the next line is not declaring the variable "i" locally:
> 
> ` for (i = 0; i < mutation.addedNodes.length; i++) {`
> 
> This means that if the variable is already declared / defined in a scope above, that declared variable will be used, but if the variable is not declared in a scope above, then it will be immediately declared in that line.

### Scope a solution ✅ 
Solution provided I the issue by @sandyfigueroa will fix the console error
> ` for (var i = 0; i < mutation.addedNodes.length; i++) {`


### Estimate the effort ✅ 

Effort [XS]

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1546947382/272543?folderId=3864740

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1580469255/282440?folderId=377611

**Comment by Mai-Saad** [comment]
Could reproduce it when added a mentioned script in the body while both LL and Delay JS are enabled

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1659055837/300846/
The fixed worked in this case.
