### ISSUE TITLE
Lazyload delay execution after WP Rocket 3.9

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#3977]
Hello.
After upgrading to WP Rocket 3.9 and turning on "Delay JavaScript execution" lazyload seems to delay in mobile, if there is no user interaction. 

How to reproduce:
Enable Delay JavaScript execution on a WooCommerce website, lazy load won't execute visible elements. Ajax cart and product single image (gallery) won't be visible unless you scroll a bit in your device. 

https://streamable.com/ka4dpl

**Comment by GeekPress** [comment]
Please disable the Lazyload of your theme or the other plugin you are using. And please use WP Rocket Lazyload instead.

**Comment by seldimi** [comment]
I am using wp rocket's lazy load, and I saw this happening on all websites I've upgraded to WP Rocket 3.9

**Comment by GeekPress** [comment]
Did you keep the default exclusion list?

```
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)
```

**Comment by seldimi** [comment]
Yes. But still.
Maybe woocommerce plugins should be also excluded?

**Comment by GeekPress** [comment]
WooCommerce plugins are already excluded if you are using the default exclusion list.

Please wait 3.9.0.1 which should fix your problem and contact us on support [at] wp-rocket.me to continue the discussion.

**Comment by seldimi** [comment]
Unfortunately version 3.9.0.1 didn't solve the issue
