### ISSUE TITLE
Astra theme's mobile menu problem with Delay JS

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3978]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using **Astra theme** + **Delay JS** and making sure that Separate Cache for Mobile Devices **is not** enabled the hamburger menu will be broken until the user interaction. When we're sharing the cache between desktop and mobile, Astra uses JS to determine the size of the screen.

**To Reproduce**
1. Use Astra theme
2. Disable Separate Cache for Mobile Devices
3. Enable Delay JS
4. Visit the page on the mobile

**Expected behavior**
There are two possible approaches:
1. Exclude the `/wp-content/themes/astra/assets/js/minified/frontend.min.js` from Delay JS automatically
2. Ask customers to enable **Separate Cache for Mobile Devices**. If they want to stay without the Separate Cache for Mobiles, do nothing because the timeout trigger will automatically load the menu after a specified period of time

**Additional context**
The affected file is here:
https://snippi.com/s/xn099ur

You can see many events like `document.addEventListener("astMobileHeaderTypeChange"` or `document.addEventListener("astLayoutWidthChanged"` that are being used to handle that.
 
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@piotrbak After checking with Gael, we don't have a workaround to implement on our Delay JS script. 

Can I let you check with @vmanthos to add a section about this into this doc? 
https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions

I'm also adding the `wontfix` label as we will have a workaround if a user doesn't like the behavior to have the burger menu broken until a user interaction.
