### ISSUE TITLE
CDN URL replacement issue with WordPress Playlist Shortcode

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#398]
Best way to describe is with examples. :)

HTML before CDN replacement:

```
<# if ( data.image ) { #>
<img src="{{ data.thumb.src }}" alt="" />
<# } #>
```

HTML after CDN replacement:

```
<# if ( data.image ) { #>
<img src="https://cdn.example.com/{{ data.thumb.src }}" alt="" />
<# } #>
```

The problem is that the value returned by `{{ data.thumb.src }}` is already a full URL, so it ends up being a value something like this:

```
https://cdn.example.com/https://example.com/image.jpg
```

which, of course, breaks the reference, causing the image to not display.

Edited to add: this HTML output apparently comes from WordPress's `playlist` shortcode; see function `wp_underscore_playlist_templates`: 
https://developer.wordpress.org/reference/functions/wp_underscore_playlist_templates/

**Comment by DonnieBoy** [comment]
wprocket 3.0.5: the same happen with youtube playlist image and with the the youtube videos, doesn't show the image and when you click on play button says on screen" the video is unavailable".
