### ISSUE TITLE
Allow to programmatically regenerate CPCSS

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3982]
**Is your feature request related to a problem? Please describe.**
Some customers would like to have a way of programmatically regenerate CPCSS. 

We do provide a snippet: https://snippi.com/s/4shymeq 
When used, it succeeds in clearing the current CPCSS, but the regeneration process doesn’t run unless an admin page is visited.

So, the process is correctly _enqueued_ but is not being _triggered_ unless there is WP-Admin activity

**Describe the solution you'd like**
Create a function that can be used by customers to trigger the CPCSS regeneration process. 

**Additional context**
Example tickets:
https://secure.helpscout.net/conversation/1513545056/264123?folderId=2683093
https://secure.helpscout.net/conversation/1259877117/188835
https://secure.helpscout.net/conversation/1271324482/191678
https://secure.helpscout.net/conversation/1491880654/258357

Slack convos:
https://wp-media.slack.com/archives/C43T1AYMQ/p1621528919034100
https://wp-media.slack.com/archives/C08N8J6VC/p1597994101062900

**Comment by warudin** [comment]
The main reason for this request is that we update our custom themes and plugins on clients sites through the [Git Updater plugin](https://github.com/afragen/git-updater) so everything gets rolled out automatically upon a commit. An update for a theme or plugin can cause visual changes to the site, so regenerating the critical CSS is absolutely necessary for us. But if we have to visit the back-end for every site that we update, that'd be a lot of extra work, so hopefully that can be automated somehow.

**Comment by wojsmol** [comment]
Hi
I have similar need but for deferent reason.  On same setups CPCSS is not regenerated after cache flushed because of expiration.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1757712607/319410?folderId=3864740

**Comment by jacksonwp** [comment]
+1 to everything @warudin said. We're seeing this alot with Beaver Builder when the included assets, eg: Font Awesome get a version bump. Critical CSS is then referencing asset folders that don't exist any longer.

**Comment by alfonso100** [comment]
Related: https://secure.helpscout.net/conversation/1810450642/330459?folderId=2683093

**Comment by slomeli79** [comment]
> ...An update for a theme or plugin can cause visual changes to the site, so regenerating the critical CSS is absolutely necessary for us. But if we have to visit the back-end for every site that we update, that'd be a lot of extra work, so hopefully that can be automated somehow.

💯Same is true when updating plugins/themes/WP-Core on multiple sites through a site management platform like BlogVault, ManageWP, MainWP, WP Umbrella, etc. It's inefficient and simply unreasonable to expect agencies to log into each and every site after updates to manually regenerate CPCSS.

There has to be a better way, whether it's a filter or special script call that must be initiated by cron.

(In a perfect world, WP Rocket could accept a webhook that triggers cache-flush + CPCSS regeneration + sitemap preload, maybe a combination of these based on parameters. Then, when these platforms perform updates and a before/after visual comparison, any detected visual changes could trigger that webhook.)

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
