### ISSUE TITLE
TradingViews embed JavaScript not working when hosted (JavaScript exclusion)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3984]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
TradingView is a trading tool platform with embeddable code for tickers and charts. 

```
<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-single-quote.js" async>
```

The script creates an iframe and pulls data from their app. 

```
<iframe scrolling="no" allowtransparency="true" frameborder="0" src="http://www.tradingview.com/embed-widget/single-quote/?XXX" style="box-sizing: border-box; height: 126px; width: 350px;">
```

If the script is hosted, it will reference the website's domain on the iframe instead of TradingView's. The widget will show a 404 page instead. 

**To Reproduce**
1. Add any embeddable ticket or chart from - https://www.tradingview.com/widget/advanced-chart/
2. Enable JavaScript minification
3. See error

**Expected behavior**
The right URL should be referenced on the iframe. 

**Screenshots**
N/A

**Additional context**
Excluding `s3.tradingview.com` fixes the issue.
Ticket - https://secure.helpscout.net/conversation/1527689891/267700/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
I can add the PR when this is greenlighted.

**Comment by GeekPress** [comment]
@DahmaniAdame Feel free to make a PR :)
