### ISSUE TITLE
Exclude WP Forms inline script from the DelayJS

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3987]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When updating from pre-3.9 we're excluding specific scripts from Delay JS. This one is not excluded causing JS error in the console:
`wpforms_settings`

**To Reproduce**
1. Enable Delay JS on 3.8.8
2. Update to 3.9
3. Use WP Forms on the page
4. Visit the page and see the error

**Expected behavior**
We shouldn't cause errors in the console

**Additional context**
This error happens only when we have our defaut exclusions in the UI. Just like https://github.com/wp-media/wp-rocket/issues/3932

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The whole script:
```
<script type="text/javascript">
    /* <![CDATA[ */
    var wpforms_settings = {
        val_required: "This field is required.",
        val_url: "Please enter a valid URL.",
        val_email: "Please enter a valid email address.",
        val_email_suggestion: "Did you mean {suggestion}?",
        val_email_suggestion_title: "Click to accept this suggestion.",
        val_email_restricted: "This email address is not allowed.",
        val_number: "Please enter a valid number.",
        val_number_positive: "Please enter a valid positive number.",
        val_confirm: "Field values do not match.",
        val_fileextension: "File type is not allowed.",
        val_filesize: "File exceeds max size allowed. File was not uploaded.",
        val_time12h: "Please enter time in 12-hour AM\/PM format (eg 8:45 AM).",
        val_time24h: "Please enter time in 24-hour format (eg 22:45).",
        val_requiredpayment: "Payment is required.",
        val_creditcard: "Please enter a valid credit card number.",
        val_post_max_size: "The total size of the selected files {totalSize} Mb exceeds the allowed limit {maxSize} Mb.",
        val_checklimit: "You have exceeded the number of allowed selections: {#}.",
        val_limit_characters: "{count} of {limit} max characters.",
        val_limit_words: "{count} of {limit} max words.",
        val_recaptcha_fail_msg: "Google reCAPTCHA verification failed, please try again later.",
        val_empty_blanks: "Please fill out all blanks.",
        post_max_size: "104857600",
        uuid_cookie: "",
        locale: "en",
        wpforms_plugin_url: "https:\/\/domain.com\/wp-content\/plugins\/wpforms-lite\/",
        gdpr: "",
        ajaxurl: "https:\/\/domain.com\/wp-admin\/admin-ajax.php",
        mailcheck_enabled: "1",
        mailcheck_domains: [],
        mailcheck_toplevel_domains: ["dev"],
        is_ssl: "1",
    };
    /* ]]> */
</script>
```

**Comment by webtrainingwheels** [comment]
In this case: https://secure.helpscout.net/conversation/1520155387/265828?folderId=377611 I had to make these wpforms exclusions to remove various errors: 
`/wp-content/plugins/wpforms-form-locker/assets/js/wpforms-form-locker.min.js`
`wpforms_settings`
`/wp-content/plugins/wpforms/assets/js/jquery.validate.min.js`
`wpforms.js`
`jquery.min.js`

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
I can't reproduce it locally but I can see it at one of our testing sites.

**Identify the root cause**
WPForms doesn't use the default WordPress enqueue functions to enqueue the settings script and instead they echo it here

https://plugins.trac.wordpress.org/browser/wpforms-lite/tags/1.6.7/includes/class-frontend.php#L1579

So with the default exclusion list for our Delay JS feature, it will not be able to exclude this pattern.

**Scope a solution**
We need to exclude the pattern `wpforms_settings` in case we use the default exclusion list.

**Estimate the effort**
[S]

I will check with @webtrainingwheels exporting this site form to be able to see the issue locally and try this exclusion.
