### ISSUE TITLE
Please add pre-load image capability to this plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#3989]
Please add a feature to this plugin, so I can put a custom image for store images to display to users before they are fully loaded.
This feature will be great and will not make the user tired of waiting.
Similar example for this feature : https://prnt.sc/13ud543
Please add this feature if possible

thanks

**Comment by GeekPress** [comment]
It's possible to set your own placeholder by using this filter:

```
/**
 * Filter the image lazyLoad placeholder on src attribute
 *
 * @since 1.1
 *
 * @param string $placeholder Placeholder that will be printed.
 * @param int    $width Placeholder width.
 * @param int    $height Placeholder height.
 */
return apply_filters( 'rocket_lazyload_placeholder', $placeholder, $width, $height );
```

Please contact our support if you need assistance to implement your own placeholder.
