### ISSUE TITLE
3.9 RUCSS - PHP Fatal error  - too few arguments passed in rocket_css_content

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3991]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The issue was reported by Simon Duduica, the CTO of ShortPixel. 🙏

In `WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS` we pass only `$used_css` to the `rocket_css_content` filter here:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L586

contrary to how this is defined here:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/CSSTrait.php#L68

This is causing a PHP Fatal error when the ShortPixelAI plugin is using our filter:
```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function ShortPixelAI::parse_cached_css(), 1 passed in /home/nginx/domains/example.com/public/wp-includes/class-wp-hook.php on line 292 and exactly 3 expected in /home/nginx/domains/example.com/public/wp-content/plugins/shortpixel-adaptive-images/includes/controllers/short-pixel-ai.class.php:1024
Stack trace:
#0 /home/nginx/domains/example.com/public/wp-includes/class-wp-hook.php(292): ShortPixelAI->parse_cached_css()
#1 /home/nginx/domains/example.com/public/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#2 /home/nginx/domains/example.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(586): apply_filters()
#3 /home/nginx/domains/example.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(360): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->save_used_css_in_filesystem()
#4 /home/nginx/domains/example.com/public/wp-content/plugins/wp-rocket/in in /home/nginx/domains/example.com/public/wp-content/plugins/shortpixel-adaptive-images/includes/controllers/short-pixel-ai.class.php on line 1024
```

**To Reproduce**

1. Install [ShortPixelAI](https://wordpress.org/plugins/shortpixel-adaptive-images/).
2. Enable the **Replace in CSS files** option in _ShortPixel AI Settings > Areas_
3. Add a `<span>` element on a page, and set a `background-image` for that by storing the CSS in an external file.
4. Enable the RUCSS feature _AND_ CPCSS.
5. Check the `debug.log` for the error.

**Expected behavior**

Not causing PHP fatal errors when 3rd-parties use our filters.

**Additional context**

We need to additionally pass `$source, $target` to the filter.

**Ticket:** https://secure.helpscout.net/conversation/1532365411/268869?folderId=2135277

Similar to #2127.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
We use `rocket_css_content` here to be able to rewrite URLs inside the used CSS to the CDN URL when CDN is enabled.

Adding the `$source` and `$target` don't make much sense in this case. `$source` doesn't exist at all for the used CSS, `$target` does but without the source it's not really useful.

I'm thinking we should create a new filter instead, like `rocket_used_css_content`, and apply our CDN rewrite to this filter in addition to the `rocket_css_content`.

This would avoid the fatal error, and allow custom filtering of the used CSS specifically if needed.

@wp-media/php What do you think?

**Comment by crystinutzaa** [comment]
@wp-media/php Yes, I agree with @Tabrisrp that a custom filter will avoid the Fatal error and also will give the possibility of custom filtering of the used CSS.

**Comment by engahmeds3ed** [comment]
I was talking yesterday with @Tabrisrp  about that one and here is a conclusion:-

- We added this filter here to be able to rewrite local URLs to use CDN for the returned used CSS.
- We apply this filter at fetcher when we send the resources' contents to warmup so we already rewrite CDN URLs for linked resources.
- For internal CSS on the page, we apply rewrite on the page at filter rocket_buffer with priority 20 so it's after sending the page HTML to treeshaker endpoint.
- So we need a new filter added here and then add a callback for it at CDN subscriber to rewrite URLs (maybe we have a page with internal CSS and needs to be rewritten)

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
Yes, I can see the issue on the code level.

**Identify the root cause**
We used one filter on two different places with different signatures.


**Scope a solution**
1. Replace the filter [here](https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L586) with this new filter `rocket_used_css_content`
2. Add callback on this new filter here
https://github.com/wp-media/wp-rocket/blob/46bb9d57358892ca7e3f3879e6a1d82e01c66c69/inc/Engine/CDN/Subscriber.php#L51
To rewrite CSS properties.
3. We may need to add an integration test for this CDN part.

**Estimate the effort**
[XS]

**Comment by Mai-Saad** [comment]
@vmanthos @Tabrisrp can't reproduce this issue on https://new.rocketlabsqa.ovh/3991template/ using 3.9.0.2 and 3.9.0.1 

https://user-images.githubusercontent.com/76941962/122582618-a3477200-d058-11eb-9c02-5cbd4ed75532.mp4

Please let me know what am I missing here or if we have a live URL with the problem.

Used template: http://snippi.com/s/ymo5lcn

Used ShortPixel AI : Version 2.3.0

**Comment by Mai-Saad** [comment]
Note for retest: Thanks to @engahmeds3ed this issue on shortpixel < 2.2.4 
[shortpixel-adaptive-images.2.2.3.zip](https://github.com/wp-media/wp-rocket/files/6692781/shortpixel-adaptive-images.2.2.3.zip)
and  minify CSS is enabled in WPR
