### ISSUE TITLE
A question about the ability to delete unused css

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#3992]
Doesn't using this feature create a problem for the website? For example, clutter in the appearance of the website or ...
Did anyone have a problem with this feature?

thanks

**Comment by javiergutierrezchamorro** [comment]
Not using 3.9 but you can try yourself and if not working properly disable RUCSS. Guess that WP-Media aim is to make it fully compatible and truly remove only what is not needed.

**Comment by 79ho3ein** [comment]
thanks

**Comment by GeekPress** [comment]
@79ho3ein Please contact our support team for this kind of question: https://wp-rocket.me/support/
