### ISSUE TITLE
Message displayed for preload when activating RUCSS needs to be more descriptive

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3994]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.1
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
Message displayed when activating RUCSS that `Preload complete: 11 pages have been cached. (June 3, 2021 @ 7:28 pm)` although, preloading is paused and this is not what inside cache

**To Reproduce**
1. Activate preload
2. Activate RUCSS
3. Notice the message at the top of the screen => check cache folder

**Expected behavior**
Another message displayed i.e " Preload will run after remove unused CSS has finished processing"

**Screenshots**

https://user-images.githubusercontent.com/76941962/120701479-2d1d0a00-c4b3-11eb-94de-bf2e9fa69e12.mp4

**Additional context**
- slack discussion here https://wp-media.slack.com/archives/G087NJ788/p1622748011107800?thread_ts=1622738164.105900&cid=G087NJ788

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closed with 3.11, warmup is not being used anymore
