### ISSUE TITLE
Actions in admin bar better not to auto change the current tab

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3995]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.1
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
Auto redirection to the WPR dashboard occurs with admin bar actions i.e clear cache, preload, ...etc

**To Reproduce**
1. Go to the file optimization tab
2. Clear cache from admin bar
3. Auto navigate to the dashboard tab

**Expected behavior**
Keep the user on the current tab

**Screenshots**

https://user-images.githubusercontent.com/76941962/120702774-c3056480-c4b4-11eb-8522-913ae0827487.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@Mai-Saad I'm not able to reproduce this problem on our website and https://smashingcoding.com/ Clearing the cache from the dashboard won't redirect to our options page.

**Comment by webtrainingwheels** [comment]
Just an FYI I did notice this on my site with Clear Cache, Purge OP cache and Clear Used CSS: 
https://recordit.co/Q792yRCJe2
( I start on the File Optimization tab but end up on the Dashboard tab after the action)

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
