### ISSUE TITLE
Optimize static images in the plugin

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [wp-media/wp-rocket#3997]
**Is your feature request related to a problem? Please describe.**
Some files onto the plugin can be optimized to reduce its size. As a followup on https://github.com/wp-media/wp-rocket/issues/3476 I am providing here more details. Just running FileOptimizer over the entire wp-rocket folder detected 60 optimizable files and saved 10 KB.

**Describe the solution you'd like**
Make wp-rocket better optimized, reduce distribution size and make it load faster.

**Describe alternatives you've considered**
Any file or image optimization tool will be OK

**Additional context**
Find the result:

![image](https://user-images.githubusercontent.com/4672971/120792171-65652c80-c535-11eb-8bc6-e1a40b561a78.png)

**Comment by arunbasillal** [comment]
Hello @javiergutierrezchamorro Is that a difference of 10kb after optimization? Sorry to say this, but pretty sure that is trivial and non-consequential for something that happens on WordPress admin side. 

Issues like #1599 can make a bigger difference for user experience.

**Comment by javiergutierrezchamorro** [comment]
Indeed. 10 KB savings for admin area, but also for ZIP plugin distribution. Of course there are other performance areas, but improving this one is almost trivial @arunbasillal
