### ISSUE TITLE
Monarch plugin broken with WP Rocket

### ISSUE THREAD

**Issue by LeleDev** [wp-media/wp-rocket#400]
Good morning, I've found that the [Monarch Plugin](https://www.elegantthemes.com/plugins/monarch/) by Elegant Themes (one the most used ones for social shares) is broken with WP Rocket.

In particular, it stops working after about 24 hours from the last cache purge.

How to reproduce the issue:
- Install Monarch plugin
- Install WP Rocket
- Enable WP Rocket, and set it to purge cache after a week
- Wait 24-48 hours
- Try to click on the triple dot button in the social sidebar (the one to share on other socials): it won't do anything, instead of opening the social network choice menu.

Thank you in advance!

**Comment by glueckpress** [comment]
@LeleDev Sounds like an issue with [nonces](https://joshpress.net/wordpress-nonces-and-wordpress-caching/). Usually this kind of issues can be solved by setting cache lifespan to a lower value, preferably 8-10 hours.

If you need further assistance, feel free to [open a support request](https://wp-rocket.me/support/).

**Comment by LeleDev** [comment]
Yes, I think that you are right because if I set 8-10 hours lifespan the issue doesn't occur.

But obviously I don't want to be forced to use a so low value due to a problem with a single plugin (Monarch).

So, assuming that it seems that we already found the nature of the problem, must I open a support request anyway or we can just continue here directly?

**Comment by glueckpress** [comment]
@LeleDev The problem with nonces and static page caching is not limited to our plugin. It is a problem in principle, and there is no other solution to it than to keep cache lifespan below nonce lifespan.

In the article linked above Josh recommends to actually do exactly that, set lifespan to something below 12 hours:

> The other thing you really should do is keep your cache times short. Definitely less than 12 hours, but probably even shorter.

As this is a general problem of technologies, not our plugin, and the one possible solution has been recommended, I’m closing this issue.

**Comment by LeleDev** [comment]
Thank you for your quick answers, glueckpress.

Just onther question: if it is a problem with the technologies, why it didn't happen when I used W3 total cache? I had all kind of caching enabled then, but I never experienced it within the same website until I switched to WP Rocket.
