### ISSUE TITLE
Adding a dot on WP Rocket folder name prevents it from deactivation

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4000]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using a dot on WP Rocket folder name, eg. wp.rocket or wp-rocket.bak, WP Rocket will get activated but won't be able to be deactivated. 

**To Reproduce**
1. Changing WP Rocket folder name to include a dot
2. Activate WP Rocket
3. Deactivate WP Rocket

**Expected behavior**
WP Rocket should deactivate normally even if the folder name includes a dot.

**Screenshots**
N/A

**Additional context**
The issue is fixed by using a folder name without ta dot. 
I tested by included a dot on other plugins. They were able to get activated/deactivated with no issues.
Ticket - https://secure.helpscout.net/conversation/1530020387/268314/
Issue confirmed on a testing WordPress install. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
If people want to change our folder name, it's at their own risk. If it's for testing, it's their responsibility to update the folder to the original name.

We won't fix that as it's not related to us.
