### ISSUE TITLE
Delay JavaScript not working for websites via browser history

### ISSUE THREAD

**Issue by tommy83** [wp-media/wp-rocket#4002]
fresh installed/latest WordPress
fresh installed/WP Rocket 3.9.0.1
fresh installed/latest Elementor.
Issue is also confirmed by elementor pro support.

How to reproduce:
1. Open website. Add the website to your favorites/bookmarks.
2. Close the website.
3.  Reopen the website via browser history and scroll or move the mouse. JS is not executed.
Result: Delay JavaScript for user interaction is not work if you open the website via browser history.
See attached video:
https://streamable.com/exa0fk

Its not an rare situation: user use very open "latest websites" / browser dashboard to reopen an website. And then the carousel (and many other widgets) are broken.

JS delay is only working in this way:
1. Open website via url field prompt and press enter.
2. Move the mouse. JS is executed (also shown in the video)

**Comment by GeekPress** [comment]
This bug will be fixed with the new version of the Delay JS script. It will be released on 3.9.0.2.
