### ISSUE TITLE
Delay JavaScript not working in firefox (click on logo)

### ISSUE THREAD

**Issue by tommy83** [wp-media/wp-rocket#4004]
fresh installed/latest WordPress
fresh installed/WP Rocket 3.9.0.1
fresh installed/latest Elementor.
Issue is also confirmed by elementor pro support.
fresh installed/latest firefox
fresh installed/latest chrome.

1. Open firefox.
2. Enter URL of website.

Visitor need to enter url and press enter or press RELOAD Button of browser.
But Delay JavaScript (for user interaction) will not work in firefox if user click on logo. So if visitor move the mouse the js script will be not executed. In chrome browser its working fine. Click on logo in firefox will not working.

See also video:
https://streamable.com/3f0o4y
Reloading the website via click on logo is not showing the website correct because user interaction does not start JS.
Forefox: JS is started only by reloading page via URL field and via pressing reload browser button. 
Chrome: No issues.

**Comment by GeekPress** [comment]
This bug will be fixed with the new version of the Delay JS script. It will be released on 3.9.0.2.
