### ISSUE TITLE
WPBakery animations not triggering with Delay JS v2

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#4005]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If you use WPBakery and you add some animations (fade in, zoom in ...), then the animations don't trigger with Delay JS.

**To Reproduce**
1. Create a page
2. Add an animation to an element
3. Enable Delay JS v2 (3.9.0.1)
4. Visit the page in incognito mode

**Expected behavior**
Animations should trigger.

**Screenshots**
Incognito Mode
![1](https://user-images.githubusercontent.com/51261962/120906797-c5a2be00-c65c-11eb-8211-4fc7d37605e0.JPG)

Admin View
![image](https://user-images.githubusercontent.com/51261962/120906817-e10dc900-c65c-11eb-9915-6d948ac53702.png)

**Additional context**
https://wordpress-573315-1965016.cloudwaysapps.com/
Credentials can be provided to the support if needed for testing purposes.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@gevcen If you do an interaction (scroll, click), the content should be displayed, isn't it?

**Comment by gevcen** [comment]
Indeed I've tested again and, with user interaction, the animations get triggered.
This issue can be closed since it's working as expected, it's caused by the fact that there is currently no timeout for the Delay JS to get triggered. It does only on user interaction, which I think is not a good idea in my opinion.

https://github.com/wp-media/wp-rocket/issues/3938
