### ISSUE TITLE
Exclude JS delay for Jetpack Stats by default 

### ISSUE THREAD

**Issue by sarangsss29** [wp-media/wp-rocket#4010]
Before submitting an issue please check that you’ve completed the following steps:

Made sure you’re on the latest version ✅
Used the search feature to ensure that the bug hasn’t been reported before ✅

Describe the bug
When using Jetpack Stats (or Wordpress Stats) using the Jetpack Plugin,
https://wordpress.org/plugins/jetpack/
The latest WP-Rocket v3.9.0.1 defers or delays the WP Stats script along with an additional script resulting in wrong reports of like number of pageviews, hits, etc.

Screenshots of the code being defferd and lazy loaded
https://prnt.sc/14i6w9e

Enable Delay Javascript execution option
Use Jetpack Plugin
Enable Stats
Watch pagesource

Expected behavior
Exclude the following code entirely from delay JS
https://prnt.sc/14i6w9e

Tried excluding by adding the following list
https://stats.wp.com/e-202122.js
stats
e-202122.js
stats.wp.com

But the script is still deferred and lazyloaded.

**Comment by GeekPress** [comment]
If you want to fully exclude Jetpack Stat, you have to also exclude `_stq` for the inline JS.
