### ISSUE TITLE
Autoptimize compatibility: make CPCSS compatible when using their "aggregate inline CSS" option

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4013]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Autoptimize `Aggregate CSS-files` > `Also aggregate inline CSS` is enabled, it will combine the CPCSS inline code.

WP Rocket won't make Autoptimize combined CSS file async. 

```
<link media="all" href="https://example.com/wp-content/cache/autoptimize/css/autoptimize_22e19a8b161c43025e4b28146a3a7e67.css" rel="stylesheet" />
<link media="print" href="https://oxygen.adame.io/wp-content/cache/autoptimize/css/autoptimize_f637c8737ec7525695a5301f7a69ccd9.css" rel="stylesheet" />
<link media="screen" href="https://example.com/wp-content/cache/autoptimize/css/autoptimize_1a1a4a4a3c1facc9c784acf7ad599d82.css" rel="stylesheet" /><title>Title</title>
<style id="rocket-critical-css"></style>
```

Probably because their buffer comes after WP Rocket's. 

**To Reproduce**
1. Enable CPCSS on WP Rocket
2. Enable `Aggregate CSS-files` > `Also aggregate inline CSS` on Autoptimize
3. Clear the cache
4. See error (missing CPCSS inline style and non-asynced CSS files)

**Expected behavior**
WP Rocket inline CPCSS should still be there even if the option is enabled. And all other CSS files should be loaded async.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/121151178-0dcc0700-c83c-11eb-8e7e-52802d6e094b.png)
![image](https://user-images.githubusercontent.com/1289174/121306600-f736b600-c8f6-11eb-8ee2-7be5878d697b.png)

**Additional context**
Excluding `rocket-critical-css` from `Autoptimize` > `CSS Options` > `Exclude CSS from Autoptimize` fixes the issue.

Autoptimize has the following filter to add CSS exclusions programmatically `autoptimize_css_exclude`.

It has also the following filter `autoptimize_html_after_minify` just before returning their processed buffer. It can be used to make their combined CSS file async.

Reference: 

https://github.com/futtta/autoptimize/blob/b9e3ff920ad9169559af1b2fb72fc1ab60033d58/classes/autoptimizeMain.php#L536

Ticket - https://secure.helpscout.net/conversation/1532468157/268917

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We'll go exactly the same way as we do in https://github.com/wp-media/wp-rocket/issues/4327

**Comment by iCaspar** [comment]
Grooming notes:

Per https://github.com/wp-media/wp-rocket/issues/4013#issuecomment-964385166 the solution will be the same as the grooming in #4327

There will need to be a second function in the autoptimize.php to check for aggregate_inline_css, and that will need to be called in another helper item with appropriate text re: inline aggregation vs cpcss. 

However, because the helper notice will need to be updated depending on which Optimize option is selected, this will also need to implement some JS to toggle the helpers depending with any change in the selection. Assigning a slight increase in effort for this case.

**Estimated Effort**:
[S]

**Comment by iCaspar** [comment]
**User Story:**
```
Given I am a WP Admin
When I have Autoptomize JS Aggregation AND Rocket Delay JS active at the same time,
Then I will see a dismissable (yellow) warning notice box that says:
   "We have detected that Autoptimize's Aggregate Inline CSS feature is enabled. 
    WP Rocket's Load CSS Asynchronously will not be applied to the file it creates.
    We suggest disabling it to take full advantage of WP Rocket's Load CSS Asynchronously Execution."
That persists between admin page loads until
    I dismiss it OR I disable either setting.
So that I am aware of the need to edit Autoptimize settings to work with WP Rocket.

```
