### ISSUE TITLE
Add Delay JS exclusion related to Divi

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4014]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Divi is adding its JS variables without the usage of `wp_enqueue_script`. We might want to exclude the following pattern:
`et_animation_data`

The issue is similar to those:
https://github.com/wp-media/wp-rocket/issues/3932
https://github.com/wp-media/wp-rocket/issues/3987

**To Reproduce**
1. Use Divi builder
2. Add some animations
3. Visit the page and hceck the source
4. `et_animation_data` containing script is delayed, if your animations are using data from it, you'll see an error, because we automatically excluded `/wp-content/ /wp-includes/`

**Expected behavior**
Variable deifnitions should not be delayed

**Additional context**
The whole script:
```
var et_animation_data = [
    { class: "et_pb_section_0", style: "fade", repeat: "once", duration: "50ms", delay: "0ms", intensity: "50%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_code_0", style: "fade", repeat: "once", duration: "500ms", delay: "100ms", intensity: "50%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_text_0", style: "fade", repeat: "once", duration: "1000ms", delay: "250ms", intensity: "50%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_text_1", style: "fade", repeat: "once", duration: "1000ms", delay: "350ms", intensity: "50%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_row_3", style: "zoom", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "50%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_image_0", style: "slideLeft", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "1%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_image_1", style: "slideRight", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "1%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_image_2", style: "slideLeft", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "1%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_image_3", style: "slideLeft", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "1%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_cta_0", style: "zoom", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "2%", starting_opacity: "0%", speed_curve: "ease-in-out" },
    { class: "et_pb_post_slider_0", style: "zoom", repeat: "once", duration: "1000ms", delay: "0ms", intensity: "2%", starting_opacity: "0%", speed_curve: "ease-in-out" },
];
var et_link_options_data = [{ class: "et_pb_cta_0", url: "https://domain.com/", target: "_self" }];
```

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by iCaspar** [comment]
## Grooming Notes

### Reproduced ✅ 
Confirmed on mega/divi that animated items do not animate with DelayJS active

### Root Cause
Script variables used in animations are added outside of `wp_enqueue_script`.
Specifically, `et_animation_data` variable.

### Solution Scope
Add `et_animation_data` to auto-excludes.
(Update test fixtures)

### Estimated Effort
[XS]
