### ISSUE TITLE
Automatically exclude AdThrive scripts from delay JS

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#4018]
**Describe the bug**
Our new delay JS is causing issues for users of AdThrive, preventing ads loading and CLS management before any user interaction.

Exclude the 2 inline scripts inserted in the HTML would avoid the issue, and improve the experience of our common users.

To do so, we can add `adthrive` to our exclusion patterns.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
After discussion, the way to go will be :
- detect if Adthrive plugin is activated
- If so, add the pattern `adthrive` in the exclusion (we don't insert into our default exclusion list)

**Comment by engahmeds3ed** [comment]
## Scope a solution

1. Create a new compatibility file/class here: 
https://github.com/wp-media/wp-rocket/tree/177960bddb73b75dd14407687351ee54a5bf511d/inc/ThirdParty/Plugins

2. Use the following constant to check if the plugin is installed or not: 
https://plugins.trac.wordpress.org/browser/adthrive-ads/tags/1.0.48/adthrive-ads.php#L33

3. Load this new class on service provider here: 
https://github.com/wp-media/wp-rocket/blob/753a36cdb774f2863b95d3d0fde661174d4dca16/inc/ThirdParty/ServiceProvider.php#L124-L126

4. Use the filter `rocket_delay_js_exclusions` to add `adthrive` to the list.

5. Add unit/integration test for this small method.

## Estimate the effort
[S]
