### ISSUE TITLE
Issues with CDN on WP Engine

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#402]
Per Remy's request, this is for "all the issues related to CDN and WP Engine".

Starting off, I know of three:

1) WP Rocket auto-activates its CDN features when it detects that the CDN on WP Engine is active; but there's no way to **turn off** the auto-activation (which might be needed, for example, in cases where the CDN URL replacement is causing problems, such as with images).

2) The auto-activation applies to ALL files; so it's not possible to change the application to target only certain files (e.g., "CSS & JavaScript" only), _even if_ you manually enter the CDN URL as a CNAME.

3) The Rejected files option doesn't seem to work, either.

**Comment by bhubbard** [comment]
I have seen the auto-activation of the CDN cause many issues for sites my company hosts.
