### ISSUE TITLE
Uninstallation - clear metadata from the postmeta table

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4020]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

During WP Rocket's uninstallation, the metadata that is saved in the `wp_postmeta` table isn't removed, the same way we do for other database entries/tables and folders:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/WPRocketUninstall.php#L126-L131

**To Reproduce**

1. Disable some of WP Rocket's features in a post using the metabox.
2. Unistall WP Rocket.
3. Search the `wp_postmeta` table for entries containing `_rocket_exclude_`.

**Expected behavior**

We should also clear the `metadata` table during uninstallation.

**Additional context**

This came after @DahmaniAdame asked a question in Slack:
https://wp-media.slack.com/archives/C08N8J6VC/p1623145035349500

We can either delete the data running a query like:
```Mysql
DELETE FROM `wp_postmeta` WHERE meta_key LIKE '%_rocket_exclude_%
```

or using `delete_metadata()`:

```PHP
$rocket_metadata = array( '_rocket_exclude_minify_css',
                          '_rocket_exclude_minify_js',
                          '_rocket_exclude_cdn',
                          '_rocket_exclude_lazyload',
                          '_rocket_exclude_lazyload_iframes',
                          '_rocket_exclude_async_css',
                          '_rocket_exclude_defer_all_js',
                          '_rocket_exclude_delay_js',
                          '_rocket_exclude_remove_unused_css',
			);
foreach( $rocket_metadata as $metadata){
	delete_metadata( 'post', '', $metadata, '', true);//delete metadata
}
```
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced on local test site

### Identify the root cause ✅ 
on uninstall we need to delete meta data of these
```
$fields = [
			'lazyload',
			'lazyload_iframes',
			'minify_css',
			'minify_js',
			'cdn',
			'async_css',
			'defer_all_js',
			'delay_js',
			'remove_unused_css',
		];
```
### Scope a solution ✅ 
like @vmanthos  said in his comment
> We can either delete the data running a query like:
> 
> ```sql
> DELETE FROM `wp_postmeta` WHERE meta_key LIKE '%_rocket_exclude_%
> ```
> 
> or using `delete_metadata()`:
> 
> ```
> $rocket_metadata = array( '_rocket_exclude_minify_css',
>                           '_rocket_exclude_minify_js',
>                           '_rocket_exclude_cdn',
>                           '_rocket_exclude_lazyload',
>                           '_rocket_exclude_lazyload_iframes',
>                           '_rocket_exclude_async_css',
>                           '_rocket_exclude_defer_all_js',
>                           '_rocket_exclude_delay_js',
>                           '_rocket_exclude_remove_unused_css',
> 			);
> foreach( $rocket_metadata as $metadata){
> 	delete_metadata( 'post', '', $metadata, '', true);//delete metadata
> }
> ```

### Estimate the effort ✅ 

Effort [XS]

**Comment by alfonso100** [comment]
related question: https://secure.helpscout.net/conversation/1672075001/303389
