### ISSUE TITLE
Remove Unused CSS Doesn't Automatically Inject Font-Display: Swap

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#4025]
A bug I have noticed with the introduction of this feature on a wide variety of sites is the generated CSS (inline or file) doesn't appear to automatically append or replace font-display swap for @font-face rules. If I disable the remove unused CSS feature and just have the first three css optimizations enabled, then without issue font-display swap is appended. 

So, the issue is related to the remove unused CSS feature and the treeshaker. If I had to guess, I would assume the treeshaker tests the URL with a querystring to bypass wprocket, so the optimization isn't applied. So, it might have to be added to the treeshaker itself. 

Just something I noticed its common on elementor / genesis block sites since they use elementor icons, and font awesome respectively.

**Comment by piotrbak** [comment]
@ScottTravisHartley This seems to be a duplicate:
https://github.com/wp-media/wp-rocket/issues/3993

**Comment by ScottTravisHartley** [comment]
Yep i was searching for the wrong keyphrase lcosing
