### ISSUE TITLE
Lazy loading script should be first

### ISSUE THREAD

**Issue by LeleDev** [wp-media/wp-rocket#403]
Good morning,
I've noticed that the lazy loading script is usually the very last to be loaded in the pages.

This is quite a big problem, because it make this functionality pretty useless: the user must wait all the other scripts to load first before being able to download and see any image.

Could you kindly add an option to make the lazyload  javascript file the first one to be downloaded and run? Or, at least, point out a workaround to achieve this behaviour through functions.php file modifications?

Thank you in advance!

**Comment by Tabrisrp** [comment]
Hi,

there is no workaround possible currently. Adding an option to load it earlier could be something we add in a future release though.

**Comment by LeleDev** [comment]
Thank you, it would be really really great!

**Comment by Tabrisrp** [comment]
Lazyload script loading changed a lot since then, so closing this.
