### ISSUE TITLE
Better change browser cache setup time in cloud flare msg to day/year/hr

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4030]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.1
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the issue**
When saving settings for Cloudflare, the unit of Cloudflare browser cache is in seconds => better make this in a unit like a day or an hour so it will be easier for the user (instead of 14400 seconds => 4 hours, instead of 31536000 seconds => 365 days or 1 year)

**To Reproduce**
1. Go to add-ons
2. Enable Cloudflare and set it up then save
3. Message displayed at the top by reflected settings

**Expected behavior**
Time for browser cache is in the suitable unit to be clear for the user without a need to use a time converter (if we still need to display it)

**Screenshots**
![Screenshot from 2023-05-17 17-16-06](https://github.com/wp-media/wp-rocket/assets/76941962/b6d612f1-3ce2-4cfc-ba75-17a9596c732c)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
