### ISSUE TITLE
Disabling Heartbeat causes Missing Dependencies error in Query Monitor

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4032]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When Heartbeat settings are set to "disable", query monitor reports the following error:
`Missing Dependencies	wp-auth-check	example.com	wp-includes/js/wp-auth-check.min.js	heartbeat (missing), wp-i18n`

If settings are set to "reduce activity", the error disappears.

**To Reproduce**
1. Instal and activate [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin.
2. Set Heartbeat settings in WP Rocket to "disable" position.
3. Check the Query Monitor for the error. Screenshot: 

![image](https://user-images.githubusercontent.com/60236665/121529788-68fd2580-ca05-11eb-8d73-f689108128c0.png)

**Expected behavior**
No errors

**Additional context**
Query monitor developers comment:

> The script should be overridden rather than deregistered.
> WP Engine used to do this too, there's an old thread here: https://wordpress.org/support/topic/suppress-presistent-errors-ex-broken-dependencies-wp-auth-check-on-wp-engine/

Related ticket: https://secure.helpscout.net/conversation/1536822724/269979?folderId=3864740

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alpercelilhankucuk** [comment]
hi, for some unknown reason i am getting this error. can you help me? also my website's admin panel is very slow. wp-auth-check.min.js error here. I'm not using wp-rocket. Thank you very much in advance for your interest.

![Ekran Resmi 2021-06-11 14 58 30](https://user-images.githubusercontent.com/75019590/121683725-729a9200-cac6-11eb-8f01-d474b6e01c2e.png)

![Ekran Resmi 2021-06-11 15 05 54](https://user-images.githubusercontent.com/75019590/121683843-9958c880-cac6-11eb-9c72-d004c5f0f317.png)

**Comment by moazam1** [comment]
Same issue. Please help.

**Comment by Mai-Saad** [comment]
Note: for retesting we can use the following settings (heartbeat enabled but activities are disabled)
![Screenshot from 2021-07-05 11-50-51](https://user-images.githubusercontent.com/76941962/124453651-e1969e00-dd87-11eb-8295-0aae12cae883.png)

**Comment by moazam1** [comment]
My settings are same like yours but still no luck.

**Comment by girlie** [comment]
Related ticket: https://secure.helpscout.net/conversation/1562079958/276667/

**Comment by Uhtredtb** [comment]
Yes, it still got this issue, confirmed. 

please someone fix this.

Thanks

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1578831054/281990?folderId=3326173

**Comment by EmSixTeen** [comment]
+1, this is still a thing, 🙂

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
We deregister the script when the settings is on disabled, but it's used as a dependency for other files, so it's going to cause this error.

### Scope a solution ✅ 
The solution is in 2 parts:
- Create an empty `heartbeat.js` file in our `assets/js` folder.
- When we deregister the core heartbeat script, enqueue the empty one with the same handle to replace it (`Engine/Heartbeat/HeartbeatSubscriber:maybe_disable()`)

### Estimate the effort ✅
Effort `[XS]`

**Comment by worldwildweb** [comment]
related https://secure.helpscout.net/conversation/1916333415/347773/ but in wpr 3.11.3
The issue occurs only when Behavior in backend is set to Reduce Activity
