### ISSUE TITLE
Automatically remove files with inappropriate extensions from exclusion fields

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4033]
**Is your feature request related to a problem? Please describe.**
It regularly happens that users put JS files in _Excluded CSS Files_ field or the opposite:
![image](https://user-images.githubusercontent.com/11939512/121553228-64d70500-ca11-11eb-9037-48e488db34fb.png)

**Describe the solution you'd like**
WP Rocket should automatically remove files with inappropriate extensions from exclusion fields, and perhaps warn the customer that they can’t do that.

**Comment by GeekPress** [comment]
@WordPresseur What is the problem with this? It should not generate issues, and the user should be able to know that what they are trying to exclude isn't working.

**Comment by WordPresseur** [comment]
It’s a recurrent UI issue and users who are doing this are actually not able to know that what they are trying to exclude isn't working and moreover are expecting that it will work at some point. As it doesn’t work, they’re opening a support ticket. 

All things being equal, I would compare this situation to the diameters of the diesel and gasoline pipes, they are different because you can't put diesel in a gasoline engine, it won’t work. the UI of cars and pumps prevents users to do this.

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1609005383/289230/

**Comment by worldwildweb** [comment]
also had the case where a user added is full domain URL in the Excluded JavaScript Files from Delay JavaScript execution
related https://secure.helpscout.net/conversation/1714941948/312265?folderId=5547167

![image](https://user-images.githubusercontent.com/1954918/145180441-c93180ef-411d-46d4-86d0-a369938568d2.png)

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
