### ISSUE TITLE
CSS minification breaks clamp()

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#4034]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Minify CSS is removing spaces before and after the + sign for the clamp() CSS function.

Correct code:
`font-size: clamp(2.3131rem, 0.6854rem + 4.823vw, 4.5438rem);`

Code after Minify CSS:
`font-size:clamp(2.3131rem,0.6854rem+4.823vw,4.5438rem);`

**To Reproduce**
1. Use clamp() in CSS
2. Enable Minify CSS
3. Check the minified CSS code

**Expected behavior**
Spaces around the + sign should be preserved, not removed.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1536866138/269993/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Will be fixed by PR #3907

**Comment by Mai-Saad** [comment]
Can see the problem on the trunk and see the fix on the related branch.
Note: if the expression was on 2 lines like this 
`font-size: clamp(2.3131rem, 0.6854rem+`
`4.823vw, 4.5438rem); `
After minification it becomes `h1{font-family:fantasy;font-size:clamp(2.3131rem, 0.6854rem) 4.823vw,4.5438rem)}` . Do we need to handle this @Tabrisrp ? (not sure if it's a valid case)

**Comment by remyperona** [comment]
No we don't need to handle this formatting
