### ISSUE TITLE
Feature request: add the possibility to remove DOM elements based on CSS Selectors

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#4038]
**Is your feature request related to a problem? Please describe.**
This is a feature request from a client.

Sometimes there are elements that the user don't want to be loaded on mobile devices, so, for "Separate cache files for mobile devices" add the possibility to remove DOM elements based on CSS Selectors, for example a specific div element with a specific id or class.

This could even be global (not only for mobile devices), to remove elements from the DOM that are being loaded for example by the theme and that the user wants to remove.

**Describe the solution you'd like**
Add a box under the "Separate cache files for mobile devices" option where the users can add some css selectors of elements that they want to remove from cached mobile pages.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1538354357/270420/

Example: 
![image](https://user-images.githubusercontent.com/13713107/121725529-01031980-caaf-11eb-9de9-9195e26ce482.png)

**Comment by GeekPress** [comment]
This is a « theme directory ». It's totally out of the scope of WP Rocket. Users can already customize their theme by using the `wp_is_mobile` native WordPress function to display or not something on mobile.

@sandyfigueroa Our public roadmap is https://feedback.wp-rocket.me/ ^^
