### ISSUE TITLE
Cache doesn't clear when ACF Options page is updated

### ISSUE THREAD

**Issue by dmpinder** [wp-media/wp-rocket#404]
ACF Pro allows us to create an Options page, but when this page is updated the Rocket cache isn't cleared. It can be done with a simple function (my workaround is below) but would be good to see this in the plugin.

```
add_action('acf/save_post', 'clear_cache_on_options_save');
function clear_cache_on_options_save($post_id) {
    if ($post_id == 'options') {
        rocket_clean_domain();
    }
}

**Comment by Tabrisrp** [comment]
Hi,

thanks for notifying this. We could integrate an automatic compatibility for it in a future release.

Is the $post_id value always **options** for an ACF options page, or is it dependant on something else?

**Comment by dmpinder** [comment]
It defaults to `options`, but can be overwritten by the theme author when they add the necessary code in the functions.php file, although I'm unsure how you'd test for what the $post_id is set to.

The docs for adding the code is here: https://www.advancedcustomfields.com/resources/acf_add_options_page/

**Comment by przestrzal** [comment]
Hi,

i found that WP Rocket already is clearing whole site cache after ACF options page is updated. Unfortunately it's not compatible with "WP Rocket | Disable Cache Clearing".

I've installed this addon and WP Rocket is clearing cache after every update. Please check it.
