### ISSUE TITLE
Enfold theme layout breaks when Delay JS is enabled

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4041]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes 3.9.0.1
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When Delay JS is enabled and the Exclusion box contains standard exclusions only, the animation for elements in the Enfold theme is not working.

Excluding the inline script `var avia_is_mobile` from the Delay JS resolves the issue. 

**To Reproduce**
Steps to reproduce the behavior (tested on the customer site only):
1. Enable the Delay JS feature with standard exclusions that are included after the plugin update.
2. Check the page with animated elements.
3. Elements will not load even after interaction on the page. No console errors are shown.

**Expected behavior**
Elements have to load after interaction on the page when scripts are loaded.

**Additional context**
More details in the ticket: https://secure.helpscout.net/conversation/1535312119/269622/#thread-4480980667

If standard exclusions are removed but the inline script  `var avia_is_mobile` is excluded, some animated elements above the fold may not load until an interaction on the page. To resolve this, additionally, the following scripts have to be excluded:
```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/wp-content/uploads/dynamic_avia/avia-footer-scripts-(.*).js
```

The documentation is updated accordingly: https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#enfold

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1580606237/282471/

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :heavy_multiplication_x: 
I don't have Enfold theme

### Identify the root cause ✅ 
create a new theme ThirdParty compatibility class

### Scope a solution ✅ 
for new ThirdParty compatibility class
We need to create a new theme ThirdParty compatibility class for  Enfold
in "get_subscribed_events" check if the Enfold theme is active and add
`$events['rocket_delay_js_exclusions'] = 'exclude_js_from_delay_js';`

```
public function show_notempty_product_gallery_with_delayJS( array $exclusions = [] ) {
	$exclusions[] = '/jquery-migrate(.min)?.js';
	$exclusions[] = '/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js';
	$exclusions[] = 'var avia_is_mobile';
	$exclusions[] = '/wp-content/uploads/dynamic_avia/avia-footer-scripts-(.*).js';
	return $exclusions;
}
```
Create Unit and integration tests for the new class


### Estimate the effort ✅
Effort `[S]`

**Comment by piotrbak** [comment]
Added to the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
