### ISSUE TITLE
[WIP] - RUCSS WordPress database error Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4042]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

A customer reported they found the following errors in their logs:
```
10-JUN-2021 15:22:13 UTCWordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM `wp_options` WHERE `option_name` = 'rocket_rucss_warmup_resource_fetcher_batch_122f58056071cd0d10b6e' made by do_action('wp_ajax_rocket_rucss_warmup_resource_fetcher'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket_WP_Background_Process->maybe_handle, WP_Rocket_WP_Background_Process->handle, WP_Rocket_WP_Background_Process->delete, delete_site_option, delete_network_option, delete_option
```
full log: https://snippi.com/s/x7rmqhn

After discussing this with @crystinutzaa these seem to be related to the Background Process.

I'm creating this issue to monitor this, see if we get more reports, and take action.

**To Reproduce**

I don't know of a way to reproduce this.

**Expected behavior**

No errors about deadlocks should occur.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1540274756/270878
**Slack discussion:** https://wp-media.slack.com/archives/C43T1AYMQ/p1623396799271100
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1591215475/285216/

**Comment by ecotechie** [comment]
Having the same issue with sites using CodeGuard as a backup. This is what they've reported:

"It's getting MySQL error 1412. This error means that columns or indexes on a particular table (in this case, the table is wp_snl_wpr_rucss_used_css) are being changed while CodeGuard is trying to back it up. Typically, a table's definitions are set when it is created and then rarely change after that. However, it appears that something is altering the table definitions for this particular table more frequently than normal."

**Comment by GeekPress** [comment]
@vmanthos Does this issue still exist?

**Comment by piotrbak** [comment]
@GeekPress This one can be closed as it's related to the old db structure.
