### ISSUE TITLE
Add Delay JS exclusion for Ajax Search Pro plugin

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4043]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**Expected behavior**
Automatically add this pattern `asp_url` to our default exclusion list. It's safe to exclude as it contains only used to declare variables.

**Additional context**

The complete inline script:

```<script type='text/javascript' id='wd-asp-ajaxsearchpro-js-before'> var ASP = {"ajaxurl":"https:\/\/tvsscsstaging.wpengine.com\/wp-admin\/admin-ajax.php","backend_ajaxurl":"https:\/\/tvsscsstaging.wpengine.com\/wp-admin\/admin-ajax.php","js_scope":"jQuery","asp_url":"https:\/\/tvsscsstaging.wpengine.com\/wp-content\/plugins\/ajax-search-pro\/","upload_url":"https:\/\/tvsscsstaging.wpengine.com\/wp-content\/uploads\/asp_upload\/","css_basic_url":"https:\/\/tvsscsstaging.wpengine.com\/wp-content\/uploads\/asp_upload\/style.basic-ho-is-po-no-da-au-se-is.css","detect_ajax":"0","media_query":"RHLN7V","version":"5013","scrollbar":"1","css_loaded":"1","js_retain_popstate":"0","highlight":{"enabled":false,"data":[]},"fix_duplicates":"1","debug":"","analytics":{"method":0,"tracking_id":"","string":"?ajax_search={asp_term}","event":{"focus":{"active":1,"action":"focus","category":"ASP {search_id} | {search_name}","label":"Input focus","value":"1"},"search_start":{"active":0,"action":"search_start","category":"ASP {search_id} | {search_name}","label":"Phrase: {phrase}","value":"1"},"search_end":{"active":1,"action":"search_end","category":"ASP {search_id} | {search_name}","label":"{phrase} | {results_count}","value":"1"},"magnifier":{"active":1,"action":"magnifier","category":"ASP {search_id} | {search_name}","label":"Magnifier clicked","value":"1"},"return":{"active":1,"action":"return","category":"ASP {search_id} | {search_name}","label":"Return button pressed","value":"1"},"try_this":{"active":1,"action":"try_this","category":"ASP {search_id} | {search_name}","label":"Try this click | {phrase}","value":"1"},"facet_change":{"active":0,"action":"facet_change","category":"ASP {search_id} | {search_name}","label":"{option_label} | {option_value}","value":"1"},"result_click":{"active":1,"action":"result_click","category":"ASP {search_id} | {search_name}","label":"{result_title} | {result_url}","value":"1"}}}}; </script>```

The script contains `js-before` which is excluded by default, but we still need to exclude it when we want to delay everything.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
This pattern safe is to delay `asp_url` but even without delay also no problem, but when all JS in delay+defer, it does wrong.

I looked on the source and found that it's wrapped with "DOMContentLoaded" when defer is on. and i used inline js exclude filter to exclude that, and plugin works perfectly fine. this pattern needs to be auto exclude from defer too.
