### ISSUE TITLE
Delay JS - Add explanatory text about default exclusions

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4044]
**Is your feature request related to a problem? Please describe.**

Per @wp-media/productrocket we need to display text to explain the reason we are adding the default exclusions when updating WP Rocket 3.7/3.8 and the delay JS feature is active.

@webtrainingwheels suggested the following for when the text area is populated:
`Internal scripts are excluded by default to prevent issues. Remove them to take full advantage of this option. More info[doc link]`

![](https://pouch.jumpshare.com/preview/b9gMjUM9pD1TzTPZ3OpRFFjCyBFjt-yg25M8s7ufwymKPlylW0JRYJ-gIH74p7G_bEz9PFUP7lB2pHVTUqSvdDJprjKJn4snkOQIlHyX-Do)
When the exclusion area is empty, the following should be displayed:
`To quickly resolve issues, restore the default exclusions, found here [doc link]`

Doc link [en]: https://docs.wp-rocket.me/article/1349-delay-javascript-execution#update
Doc link[fr]: to be added.

**Comment by GeekPress** [comment]
@vmanthos @webtrainingwheels  Thanks for your suggestions.

> To quickly resolve issues, restore the default exclusions, found here [doc link]

To be easier / faster for the user, can we directly display the list below the text and suggest just copy and paste it?

**Comment by vmanthos** [comment]
>To be easier / faster for the user, can we directly display the list below the text and suggest just copy and paste it?

Of course!

So, when the text area is empty, the text would be:
```
To quickly resolve issues, paste the default exclusions:
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)
```

**Comment by Agathemed** [comment]
Could we display the following text in green with an exclamation point to highlight the potential of the action?

> Internal scripts are excluded by default to prevent issues. Remove them to take full advantage of this option. More info[doc link]

**Comment by ScottTravisHartley** [comment]
Just want to add, the inclusion of the easy-to-get copy and paste for the default exclusions would help a lot. Since the default install, doesn't include them by default I have to go to the documentation and copy the 3 lines separately (since it's not one block in the docs), this would be very helpful for diagnosis delay JS issues on fresh installs.

**Comment by GeekPress** [comment]
> Just want to add, the inclusion of the easy-to-get copy and paste for the default exclusions would help a lot. Since the default install, doesn't include them by default I have to go to the documentation and copy the 3 lines separately (since it's not one block in the docs), this would be very helpful for diagnosis delay JS issues on fresh installs.

The exclusion list is going to be added by default on all installations (#4047).

**Comment by GeekPress** [comment]
@vmanthos @webtrainingwheels What do you think about adding a sentence + link to the exclusion documentation list?

https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions

**Comment by remyperona** [comment]
What happens if the textarea is populated, but not with the default exclusions? The currently suggested sentence would not make sense.

**Comment by GeekPress** [comment]
@Tabrisrp We should also display the sentence with the default exclusion list.

> To quickly resolve issues, restore the default exclusions, found here [doc link]

@vmanthos @webtrainingwheels Can we revisit this a little bit? Something like:

_If you are facing any issues since you removed our default exclusion list, you can restore it by copy and paste the code below:_

**Comment by vmanthos** [comment]
There are 3 scenarios:
1. Default exclusions are in place.
2. No exclusions exist in the text area.
3. Custom exclusions have been added.

The displayed text needs to serve two different purposes:
1. Educate our customers that they need to remove default exclusions to benefit from the feature.
2. Guide our customers to resolve common issues by restoring the default exclusion list for scenarios 2 and 3.

It's hard to find one sentence that will cover all 3 cases.

We can use the hash of the default exclusions to display two different messages:
For 1:
```
Internal scripts are excluded by default to prevent issues. Remove them to take full advantage of this option.
If this causes trouble, restore the default exclusions, found [here](https://docs.wp-rocket.me/article/1349-delay-javascript-execution#troubleshoot).
```
The default list is not there yet, but it will be added soon.
Update: the list is in our [doc](https://docs.wp-rocket.me/article/1349-delay-javascript-execution#troubleshoot).

For 2 and 3:
```
To quickly resolve issues remove any existing exclusions, and paste the default exclusions:
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)

Also, please check our [doc](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions) for a list of compatibility exclusions.
```

@GeekPress @Tabrisrp What do you think about this?

**Comment by remyperona** [comment]
@GeekPress How is this going to change based on today's discussion?

**Comment by GeekPress** [comment]
> @GeekPress How is this going to change based on today's discussion?

@Tabrisrp We can go with the last suggestion from Vasilis.

> @GeekPress @Tabrisrp What do you think about this?

Sounds good.

About 👇

`To quickly resolve issues remove any existing exclusions, and paste the default exclusions:`

Can we add more context? Like: `if after activating this option you have any problems...`

**Comment by vmanthos** [comment]
> Can we add more context? Like: if after activating this option you have any problems...

I think the line we have is self-explanatory, i.e. the exclusions are to be added to "quickly resolve issues" when the option is active. 

Also, we are not writing something like that for other features. It's a given that those text areas in the file optimization tab are to be used like that, if after activating an option that causes problems.

**Comment by engahmeds3ed** [comment]
@wp-media/productrocket 
To summarize this discussion, please confirm the following:-

Add the following message below delay JS exclusion Textarea section only when enabled with green color like what we do with minify JS exclusion list.

```
To quickly resolve issues remove any existing exclusions, and paste the default exclusions:
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)

Also, please check our [doc](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions) for a list of compatibility exclusions.
```

![image](https://user-images.githubusercontent.com/15707971/123588547-35cddb00-d7e8-11eb-931e-b89e36a2c68e.png)
(Thanks @vmanthos)

**Comment by engahmeds3ed** [comment]
This one is blocked because from 3.9.0.5 we don't add the default exclusion list by default. So we need to think again about this one.

https://github.com/wp-media/wp-rocket/issues/4111

**Comment by GeekPress** [comment]
@engahmeds3ed We can keep the same behavior but we will just change it a little bit the sentence:

```
If you have problems after activating this option, copy and paste the default exclusions to quickly resolve issues:
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)

Also, please check our [doc](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions) for a list of compatibility exclusions.
```

**Comment by engahmeds3ed** [comment]
## Scope a solution

1. Add `helper` key with the value of this description
```
If you have problems after activating this option, copy and paste the default exclusions to quickly resolve issues:
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)

Also, please check our [doc](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions) for a list of compatibility exclusions.
```

2. try getting the value of `wp-content` and `wp-includes` dynamically to help sites with customer directory names to show valid code.

## Estimate the effort
[XS]
