### ISSUE TITLE
disable saving data in varn_wpr_rucss_resources table

### ISSUE THREAD

**Issue by arashnz** [wp-media/wp-rocket#4045]
Hello,

There is a table in my database "varn_wpr_rucss_resources" that saves js, css ,type , media, content and last_access data, its like a log file, how can i prevent saving data in this table ? is it possible ?

**Comment by ScottTravisHartley** [comment]
1. probably not because the feature needs the data. 
2. why would you want to?

**Comment by arashnz** [comment]
Actually saving the data is not important, the problem is the data in this table won't delete, the table size was 2GB and I had to remove them manually. for the css table they remove automatically but for this table data won't delete. what is problem ?

**Comment by iCaspar** [comment]
This table is essential to the operation of the Remove Unused CSS feature. Please contact our support team for help about this. https://wp-rocket.me/support/
