### ISSUE TITLE
Add default exclusion list for new installation too

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4047]
**Is your feature request related to a problem? Please describe.**
The current behavior with the new Delay JS is to add a default exclusion list only for users updating from 3.7/3.8.

After discussing with the marketing & support team, we decided to have the default exclusion list for all users, even for new installations.

After a couple of weeks of the Delay JS usage, we know that excluding everything is too early.

**Describe the solution you'd like**
Add the default exclusion list for new and current users.

**Comment by engahmeds3ed** [comment]
## Proposed solution

https://github.com/wp-media/wp-rocket/blob/48f5466c8e9699f23318968a943b1302abadcab6/inc/Engine/Optimization/DelayJS/Admin/Settings.php#L75

- <strike>Here we need to change the new version to be `3.9.0.3` and the old version is before `3.9`.</strike> We will leave the check as-is for old users upgrading from a version before 3.9.
- Adjust the old test and add a new fixture.
- For new users add the default exclusion list here: https://github.com/wp-media/wp-rocket/blob/48f5466c8e9699f23318968a943b1302abadcab6/inc/Engine/Optimization/DelayJS/Admin/Settings.php#L59

## Effort
[XS]

**Comment by engahmeds3ed** [comment]
Thanks for @mostafa-hisham for reminding me of some other cases as follows:-

## Case 1
New user has version 3.9 so the exclusion list is empty and then upgraded to 3.9.0.3 so the exclusion list should be empty or also fill it with the default list?

## Case 2
The user is upgrading from 3.8.8 to 3.9 so the exclusion list is the default list, then he played on this list and then will upgrade to 3.9.0.3 so the exclusion list should be as is without any change, right?

I'm checking those questions with @GeekPress and will update the grooming comment.

**Comment by engahmeds3ed** [comment]
I got a reply from @GeekPress, We should not change the field in both cases.
so we will just do that with new users and users upgrading from a version before 3.9
