### ISSUE TITLE
Clear Varnish Cache on WP Engine Staging (Errors)

### ISSUE THREAD

**Issue by bhubbard** [wp-media/wp-rocket#405]
Notice we get errors for trying to clear varnish cache on WP Engine staging. Not sure if these were generated by users trying to use the clear cache button or if it was triggered. Ideally I would think WP Rocket could detect if its on a WP Engine Staging and prevent the function to clear the cache from running and causing php errors.

![screenshot may 09 09 32 35](https://cloud.githubusercontent.com/assets/3837/25861789/9cbd00f2-349a-11e7-897e-5dc237e1d606.png)

**Comment by Tabrisrp** [comment]
How are you clearing Varnish on the staging server? Using the Clear cache button of WP Rocket?

**Comment by bhubbard** [comment]
My guess is it was users hitting the Purge OPCache button on the WP Rocket tools page. WP Engine doesn't do any varnish caching on the staging urls so that's why the error occurs. Simply checking the url and disabling the OPCache button, or have it do nothing on the stage site should prevent the error from showing.

**Comment by Tabrisrp** [comment]
Not sure what's the relation between OPCache and Varnish here.

I also tried to purge OPCache and the purge cache from WP Rocket, and nothing is showing up in our WP Engine test install.

**Comment by bhubbard** [comment]
Not sure either, make sure you are testing on the staging site in wpengine. The site url must be install.staging.wpengine.com

**Comment by Tabrisrp** [comment]
I did, tested on both live and staging. Currently can't reproduce the issue.
