### ISSUE TITLE
[WIP] LazyLoad for Images causes endless scroll on Mac in Chrome browser

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4050]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.8.8
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
This issue is created to monitor the following problem:

When only _LazyLoad for Images_ option is enabled (i.e. all other options in File Optimization and Media tab are disabled) pages randomly have endless scroll up or down with blank space being added to the bottom or top of the website page.
This happens only on Mac Desktop in Chrome. It was possible to reproduce in Browser Stack.

**To Reproduce**
1. Enable only the LazyLoad for Images option in the Media tab
2. Open website on Mac Desktop in Chrome browser.
3. Scroll all the way to the bottom of the page and keep scrolling down 
4. A blank space starts growing at the bottom creating an endless scroll.
5. Then scroll all the way up and keep scrolling up.

**Expected behavior**
No blank space and endless scroll should happen.

**Screenshots**
Screen recording and details in Slack: https://wp-media.slack.com/archives/C08N8J6VC/p1623740434493600?thread_ts=1623671871.462000&cid=C08N8J6VC

**Additional context**
Similar reports found online not related to WP Rocket:
https://superuser.com/questions/1459503/google-chrome-infinite-scroll
https://www.reddit.com/r/LogitechG/comments/epknon/mac_mx_master_2_chrome_infinite_scrolling/

Customer mentioned:
> I have found the problem is ONLY happening in High Sierra.
But I was able to reproduce in Big Sur (Browser Stack) as well.

Having only the LazyLoad for Iframes and videos enabled does not cause this issue.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related ticket: https://secure.helpscout.net/conversation/1540351799/270924/

**Comment by NataliaDrause** [comment]
Customer shared an update in this ticket: https://secure.helpscout.net/conversation/1540351799/270924?folderId=3864740

CSS property `overscroll-behaviour` in Astra theme was causing this behavior. 
Setting `overscroll-behaviour` to `none` resolved the issue.

It is still unclear why the issue was triggered by our LazyLoad for Images option.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
