### ISSUE TITLE
SaaS maintenance mode support

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#4052]
**Is your feature request related to a problem? Please describe.**
Sometimes we will need to stop our SaaS for maintenance so we need a way to tell the user that we are on maintenance and stop sending requests to SaaS.

**Describe the solution you'd like**
We need to stop the RUCSS feature completely (using the filter, for example) when RUCSS is on maintenance mode and show admin notice until maintenance finishes.

**Describe alternatives you've considered**
No

**Additional context**
This will help not contacting our servers while maintenance so as not to lose any data from the client.

**Comment by piotrbak** [comment]
@engahmeds3ed What do you think about this in the 3.11 approach? We have an easier way to replace the servers with new instances, right?

**Comment by GeekPress** [comment]
Is it still required?

**Comment by piotrbak** [comment]
@GeekPress Do we expect any kind of maintenance? I think we can close the issue here as we could use Beacon/Status Page to inform customers about the problems.

**Comment by GeekPress** [comment]
Indeed, we can use Beacon to let the user know in advance, and during the maintenance, if needed. Let's close this one.
