### ISSUE TITLE
P3 Profiler plugin - causes PHP fatal errors

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4057]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When running the "scan" process of P3 Profiler several PHP fatal errors are thrown, e.g.:
```
PHP Fatal error: strict_types declaration must be the very first statement in the script in /home/public_html/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php on line 1
```

On a side note, I noticed the same happening for WooCommerce, again for `League`:
```
strict_types declaration must be the very first statement in the script in /home//public_html/wp-content/plugins/woocommerce/lib/packages/League/Container/Container.php on line 1
```

**To Reproduce**
1. Install [P3 Profiler](https://wordpress.org/plugins/p3-profiler/) 
2. Run a "scan"
3. Check the `debug.log`

**Expected behavior**

We should display an incompatibility notice when the plugin is installed the way we do for other plugins.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1543726216/271773/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1740377181/316222?folderId=3864740

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1764441703/320762/

**Comment by worldwildweb** [comment]
related: https://secure.helpscout.net/conversation/1855919898/338576/

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
