### ISSUE TITLE
Update the more info link from the Fallback Critical CSS in the UI

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4059]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
The _more info_ link from the _Fallback Critical CSS_ section in the UI goes to a doc that does not mention it at all.

**To Reproduce**
N/A

**Expected behavior**
The link could go the _Use Fallback Critical CSS_ section from [this other doc](https://docs.wp-rocket.me/article/1321-critical-css-issues-fouc), where we mention it and the steps to follow to create it.

**Screenshots**
![Image 2021-06-16 at 3 04 09 PM](https://user-images.githubusercontent.com/26235782/122225139-17e1ab80-ceb5-11eb-93a8-57c234526dfa.jpg)

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1542184436/271370/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@camilamadronero What do you think?

**Comment by camilamadronero-zz** [comment]
Thanks for the ping! I agree 100% with Violeta here.
I've added H2 to the document, so we can point to the specific section.
With this, the link to use is: https://docs.wp-rocket.me/article/1321-critical-css-issues-fouc#use-fallback-critical-css.

**Comment by remyperona** [comment]
We will need the same link to the french doc, and also the article IDs for both english and french

**Comment by camilamadronero-zz** [comment]
**English**
https://docs.wp-rocket.me/article/1321-critical-css-issues-fouc#use-fallback-critical-css
5ec5c4072c7d3a5ea54b7de7

**French**
https://fr.docs.wp-rocket.me/article/1327-problemes-critical-css-fouc#critical-path-css-de-secours
5edf8a5504286306f804e1dc

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine/Admin/Beacon:get_suggest()`, add a new entry to the array:
```
'fallback_css'             => [
				'en' => [
					'id'  => '5ec5c4072c7d3a5ea54b7de7',
					'url' => 'https://docs.wp-rocket.me/article/1321-critical-css-issues-fouc#use-fallback-critical-css,
				],
				'fr' => [
					'id'  => '5edf8a5504286306f804e1dc',
					'url' => 'https://fr.docs.wp-rocket.me/article/1327-problemes-critical-css-fouc#critical-path-css-de-secours',
				],
			],
```

in `Engine/Admin/Settings/Page:assets_section()`, use the fallback_css value for the CSS fallback field, instead of the async CSS one.

### Estimate the effort ✅
Effort `[XS]`
