### ISSUE TITLE
Compatibility with Extra Theme

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#406]
Extra Theme is powered by the Divi Builder, so it has the same JS minification issue as this one: 
https://github.com/wp-media/wp-rocket/issues/243

We can have automatic compatibility by auto-excluding the same file, in this case: 
/wp-content/themes/Extra/includes/builder/scripts/salvattore.min.js

**Comment by arunbasillal** [comment]
I tested this against most recent issues and couldn't replicate. Looks like the issue doesn't exist anymore. 

Divi Gallery on Extra theme reported an issue - http://mega.wp-rocket.me/divi/2019/06/04/267/
The original issue also doesn't seem to exit and I think its safe to close the issue. 

@webtrainingwheels Can you see if I missed something please?

**Comment by webtrainingwheels** [comment]
I think the current issue is due to Optimize CSS Delivery. 
The original issue hasn't been reported in tickets for a long time so I think we can close this.
