### ISSUE TITLE
3.9.X versions are a total mess

### ISSUE THREAD

**Issue by zohebnsr** [wp-media/wp-rocket#4063]
The best version I had was 3.8.8. Once installed 3.9 and even the latest 3.9.0.2 this is a total disaster for the site. 

The extremely bugged option: JS Delay.

Earlier it was the option that which script I want to delay and there was a button "Restore Default". Clicking on just this button added some scripts/Keys that needed to be delayed and it worked really great without any bug. 

The new one that delays all the script (I know I can put those that I don't want to delay that I have already tried), makes the website worst.

Issues I faced with new versions (3.9 to 3.9.0.2).

- Visitors are not tracked in Google Analytics (I know can add exception with gtag.js)
- Google and third-party ads are randomly disabled even after adding the exception.
- Jetpack traffic stats are randomly disabled (tracks just around 20% visitors I think).
- One of my site was completely disabled and was showing nothing but header without any content (probably caused by Ajax Search in header that Wp-Rocker disabled I guess).

It has caused my loss of revenue and waste of so much time. For those haven't upgraded so far, I would recommend stick to Version 3.8.8 or be ready to involve in the big mess.

**Comment by GeekPress** [comment]
Hi @zohebnsr,

Please open a ticket support: https://wp-rocket.me/support/

Our GH repository isn't the right place to help you.

Thanks
