### ISSUE TITLE
Add a Rate-Limited SaaS API Licence Check

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#4065]
## Feature Description
As we implement license checking on the Central-SaaS endpoint, we will need WPRocket to request an auth token for use with the SaaS API.

## Desired Solution
Implement a SaaSClient similar to the current [PricingClient](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/License/API/PricingClient.php) using transients to track both the token data and to rate-limit requests to the token endpoint in cases where the endpoint may be down.

## Context
@see issue https://github.com/wp-media/central-saas/issues/9

**Comment by remyperona** [comment]
On the same note, we will want to implement that on the user endpoint too, so that we are all covered

**Comment by iCaspar** [comment]
At this point, we will have at least 2 AP-related things using "rate-limits": `PricingClient` and now `SaaSClient`, or possibly `TokenClient` and `SaasClient`. As we lean toward API interactions, we will likely have more in the future. So we should abstract the API rate-limiting to a trait (starting with trait rather than an abstract base-class here because the rate-limiting methods in `PricingClient` are currently private, but could work with an abstract base and protected methods) and have classes using the trait implement a `APIRateLimiter` interface.
