### ISSUE TITLE
Promo counter isnot changed when change timezone using browserstack

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4066]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Yes
- Used the search feature to ensure that the bug hasn’t been reported before =>Yes

**Describe the bug**
When opening the dashboard from BrowserStack in the UK, the promo counter was the same as the one in the normal browser in Egypt

**To Reproduce**
- Have an active promo

1. Open Dashboard on 2 different time zone
2. Counter is the same

**Expected behavior**
Different counter displayed

**Screenshots**

https://user-images.githubusercontent.com/76941962/122425221-9f035200-cf8f-11eb-86f2-4fbab9b971a1.mp4

**Additional context**
- As per team discussion, the same timezone in the WP dashboard may impact here
- If we changed the time of the laptop, the counter is changed (as per discussion with @engahmeds3ed, we have a question here: do we really want the counter change as per laptop time or shall it be based on server time? )

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Looking back at it, this is the expected behaviour. The promotion end time is a fixed value, based on a date and time that is set on the API side.

Wherever you are, the absolute time between now and this fixed time value is the same, timezones differences don't apply.

I'll close this as a `wontfix`.
