### ISSUE TITLE
Automatically exclude inline script containing //<![CDATA[

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4073]
**Is your feature request related to a problem? Please describe.**
With our default list of exclusion, we can miss inline scripts to be excluded. An internal file can be delayed and add an inline script without using `wp_add_inline_script`.

We can avoid this problem for inline scripts wrapped into `//<![CDATA[ {script} //]]> `. We know these inline scripts can be safely excluded.

**Describe the solution you'd like**
Detect and exclude all inline scripts wrapped into `//<![CDATA[ {script} //]]> `

**Additional context**
This enhancement could automatically fix problem like #4071

**Comment by remyperona** [comment]
There is one issue with this proposal: it's totally possible and valid to have executed code inside `CDATA`, it does not necessarily contain only variables.

Automatically excluding those would mean we might be missing delay on some inline JS that are executing code.

**Comment by GeekPress** [comment]
As it's not 100% safe to exclude inline scripts wrapped into `CDATA`, we won't fix it.
