### ISSUE TITLE
Add Cube Portfolio inline script to the Delay JS exclusions

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4075]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
[Cube Portfolio](https://codecanyon.net/item/cube-portfolio-responsive-wordpress-grid-plugin/8534570) images are not displayed when Delay JS is activated.
Standard exclusions added on the update don't resolve the issue.

Excluding inline script `initCubePortfolio` resolves the issue.

**To Reproduce**
Steps to reproduce the behavior (tested on the customer site):
1. Have a portfolio created with _Cube Portfolio_ plugin displayed on a page.
2. Activate Delay JS option with or without standard exclusions (added on the update).
3. Open the page in a browser.
4. Images will not be displayed. No console errors.

**Expected behavior**
Images added with the _Cube Portfolio_ plugin should be displayed.

**Screenshots**
Screenshot of the inline script: 
![image](https://user-images.githubusercontent.com/60236665/122667650-95aafd00-d1bc-11eb-9285-d0c5b8fc83f9.png)

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1548498274/272968/
More info in the note.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `initCubePortfolio` to the `DelayJS\HTML::$excluded` array

Update tests fixtures to validate the change

### Estimate the effort ✅
Effort `[XS]`
