### ISSUE TITLE
Auto-exclusion for WooCommerce Product Gallery when Delay JS is on

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4077]
**Is your feature request related to a problem? Please describe.**
If we delay all JS files, the product image on a single product page won't be displayed until user interaction.

Here an example:
https://share.getcloudapp.com/9ZuddXp2

As you can see, it's not really a good user experience and even more on mobile.

**Describe the solution you'd like**
The product image on a single product page should be displayed without any user interaction when Delay JS is on.

We need to handle two cases:

1. when the product page doesn't have a gallery
2. when the product page has a gallery

--

1. In this case, we don't need to exclude any JS files from being delayed. We can still delay the WooCommerce JS files in this case if we had a small inline CSS in the header:

`<style>.woocommerce-product-gallery{ opacity: 1 !important; }</style>
`

2. In this case, when we are on a product page, we need to exclude these files from being delayed:

```
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
/woocommerce/assets/js/zoom/jquery.zoom.min.js
/woocommerce/assets/js/photoswipe/
/woocommerce/assets/js/flexslider/jquery.flexslider.min.js
/woocommerce/assets/js/frontend/single-product.min.js
```

**Comment by bwafels** [comment]
I have installed the latest update of wp rocket and I can confirm this is not a nice behaviour. On mobile screens the product image take up a large part of the screen. This means customers may get the impression the website is broken.

**Comment by engahmeds3ed** [comment]
I did some tests and reached the following code that solves the issue
```
add_action( 'wp_enqueue_scripts', function() {
	if ( ! is_product() ) {
		return;
	}

	$product = wc_get_product( get_the_ID() );
	$gallery_images = $product->get_gallery_image_ids();
	if ( ! empty( $gallery_images ) ) {
		return;
	}

	$custom_css = ".woocommerce-product-gallery{ opacity: 1 !important; }";
	wp_add_inline_style( 'woocommerce-layout', $custom_css );
} );

add_filter( 'rocket_delay_js_exclusions', function( $exclusions ) {
	if ( ! is_product() ) {
		return $exclusions;
	}

	$product = wc_get_product( get_the_ID() );
	$gallery_images = $product->get_gallery_image_ids();
	if ( empty( $gallery_images ) ) {
		return $exclusions;
	}

	$exclusions[] = '/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js';
	$exclusions[] = '/woocommerce/assets/js/zoom/jquery.zoom(.min)?.js';
	$exclusions[] = '/woocommerce/assets/js/photoswipe/';
	$exclusions[] = '/woocommerce/assets/js/flexslider/jquery.flexslider(.min)?.js';
	$exclusions[] = '/woocommerce/assets/js/frontend/single-product(.min)?.js';

	return $exclusions;
} );
```
I will do the same at our compatibility file.

**Comment by stefanmm** [comment]
This change results in high CLS score on mobile (~0.172). Is there a way to manually include again that excluded scripts?
`/woocommerce/assets/js/zoom/jquery.zoom.min.js
/woocommerce/assets/js/photoswipe/
/woocommerce/assets/js/flexslider/jquery.flexslider.min.js
/woocommerce/assets/js/frontend/single-product.min.js`

Web Vitals score on mobile dropped from 65 to 50 after 3.9.1 version.

Edit: after some more testing I found out that only "flexslider" script generates CLS (while building gallery layout). When I disable this script, or if I remove images from product's gallery, CLS is ok. In a slow-motion loading it can be seen how flexslider moves images around the screen and generates a lot of CLS.
Possible solution: initially do not load that script and hide gallery images thumbnails (except featured) to avoid long page of images. On user interaction load script and then display images. In "noscript" add style to show gallery images as a fallback.

**Comment by mehedihasanziku** [comment]
Indeed Good Feature, But can you guys please guard this with wordpress filter, so people may not confuse that delay js not working and excluded for valid reason.

with filter, advance people can work with it, please reconsider and guard this with filter so who not want exclude them and stay with it. or a possible approach will be option in wprocket safemode with woocommerce exclusion.

Thanks
