### ISSUE TITLE
Emulate Elementor Pro animation to improve user experience

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4080]
**Is your feature request related to a problem? Please describe.**
Elementor Pro allows users to add animation to elements. By using our Delay JS and when we delay everything, the animation in the header isn't triggered until user interaction.

It leads to an experience like that:
https://share.getcloudapp.com/o0ueez1J

It's not really a good user experience ^^

**Describe the solution you'd like**
We have developed a script that simulates the animation like Elementor is doing to have the content displayed without waiting for user interaction.

Only the animations above the fold are triggered by our script.

The inline script is available in the Delay JS repository into the `elementor` branch and in a separate file. 

**Please note that the delay JS script contains an update too!**

**Additional context**
The inline script related to Elementor animation should be added just before the `</body>` closure and added only if Elementor Pro is activated on the website.

**Comment by engahmeds3ed** [comment]
**Scope a solution**

1. Make a compatibility file for elementor pro by checking on the constant `ELEMENTOR_PRO_VERSION` like this one: 

https://github.com/wp-media/wp-rocket/blob/18ae1e009eaf9e93fad8fe23957cc50475e5381a/inc/ThirdParty/Plugins/PageBuilder/Elementor.php

2. Add callback with the `rocket_buffer` filter to add the script before closing the body tag if the Delay JS option is enabled.

3. Add unit/integration tests.

**Estimate the effort**
[S]
