### ISSUE TITLE
Don't activate Delay JS for new users by default + delay everything once it will be activated

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4085]
**Is your feature request related to a problem? Please describe.**
Not a problem but a user experience update.

We finally decided to not activate by default the new Delay JS for new installations. And we also decided to delay all files by default once the option will be activated.

It means that we will add our default exclusion list only for users updating from 3.7 or 3.8.

**Describe the solution you'd like**
When WP Rocket is installed on a new website:
- Delay JS will be disabled
- Once Delay JS will be enabled, all JS files will be delayed by default.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
- Revert PR #4061
- Set default value of the delay JS option to zero in `DelayJS\Admin\Settings`
- Update tests fixtures to reflect the change

### Estimate the effort ✅
Effort `[S]` with the QA

### QA scenarios
- New installation should have delay JS disabled and the exclusions list empty
- Upgrade from a version < 3.9 should:
    - have delay JS disabled and the exclusions list empty if the option was not enabled before
    - have delay JS disabled and the exclusions list with our default exclusions if the option was enabled before

**Comment by Mai-Saad** [comment]
@GeekPress @Tabrisrp Would you please confirm the different cases here:
1- Update
1.1 User update from < 3.9 while DJS is off => option will remain off  But once activated, the list will be filled by default exclusion or not?
1.2 User update from < 3.9 while DJS is on => option will remain on with the default exclusion list
1.3 User update from > 3.9 while DJS is off => option will remain off and the list is empty or preserved? .. once activated the list will be preserved or default?
1.4  User update from > 3.9 while DJS is on => option will remain on and exclusion list won't change
2- New installs
2.1 New install >= 3.9.0.4 => delay js is off , But once activated, the default exclusion will be there?
3- Rollback
3.1 Rollback to < 3.9 while delayjs off => the option is still off and once enabled default inclusion is there
3.2 Rollback to < 3.9 while delayjs on => the option is still on with the default inclusion

**Comment by GeekPress** [comment]
> 1.1 User update from < 3.9 while DJS is off => option will remain off But once activated, the list will be filled by default exclusion or not?

No exclusion list in this case.

> 1.3 User update from > 3.9 while DJS is off => option will remain off and the list is empty or preserved? .. once activated the list will be preserved or default?

Same as 1.1

> 2.1 New install >= 3.9.0.4 => delay js is off , But once activated, the default exclusion will be there?

No exclusion list too.
