### ISSUE TITLE
CPCSS for groups of pages (per post type)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4088]
**Is your feature request related to a problem? Please describe.**
Some websites organize their content layout based on templates applied to pages rather than a separate post type. 

Let's say we have 10 pages with a normal layout and 10 pages with a different layout. 

This will require generating one CPCSS for one layout (that would be the default CPCSS for the post type) and 10 more page-specific CPCSS for all the remaining pages with the different layout. 

It will give a convenient way to update CPCSS on multiple pages without having to do it individually. 

It will also have fewer hits on the CPCSS servers in order to create page-specific CPCSS.

**Describe the solution you'd like**
Having a way to set groups of CPCSS for each post type to use in case the same layout is applied on different pages.

**Describe alternatives you've considered**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1532468157/268917/

**Comment by DahmaniAdame** [comment]
Similar request - https://secure.helpscout.net/conversation/1317420645/204877

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
