### ISSUE TITLE
Automated Features Causing Dynamic Cache and Other Issues

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4091]
**Issue:**

We have learned that WP Rocket's htaccess code for Browser Caching (an automated plugin feature) causes [SG Optimizer's Dynamic Cache](https://prnt.sc/16ghn93) to fail every time. That is, we get the X-Proxy-Cache = MISS in our website header. Our website speed is affected as well (slows it down).

**Solution:**

To fix the above, we added the following filter to our functions.php file (via [Code Snippets](https://wordpress.org/plugins/code-snippets/)):

```
// Remove Browser Caching (Duplicated in SG Optimizer)
add_filter('rocket_htaccess_mod_expires', '__return_false');
```
Afterwards, we had to deactivate, then activate WP Rocket for the filter to work.

**Note:** The above issue is not all inclusive. Other WP Rocket automated features are causing issues that can only be fixed by applying custom filters provided by WP Rocket.

**Action Required:**

(1) Please update your knowledgebase (KB) to reflect the above and help the community.

(2) Please convert your plugin's [Automated Features to Default Settings](https://docs.wp-rocket.me/article/59-getting-started) to allow your users better control of their website's performance. Over time, WP Rocket's DevOPs team has been taking away the plugin users' ability to control your plugin's features. Not good!

Please expedite the above. Many websites (speed) are affected by this issue -- which is contrary to what you're trying to achieve with your plugin.

Thank you!

**Comment by webtrainingwheels** [comment]
(1) This information is already in our KB: 
https://docs.wp-rocket.me/article/115-can-i-use-wp-rocket-with-sg-optimizer
https://jmp.sh/sEGN0BF
https://docs.wp-rocket.me/article/1362-x-cache-miss-when-wp-rocket-is-activated

> Other WP Rocket automated features are causing issues that can only be fixed by applying custom filters provided by WP Rocket.

Please specify which other issues are caused by which features.

**Comment by ghost** [comment]
@webtrainingwheels,

Thanks for the information.

Here's the list of Automated features (previously available) that should be added to your plugin in the form of a toggle:

(1) Enable/Disable **Browser Caching** (the No. 1 item that's causing many to report X-Proxy-Cache = MISS) when using SG Optmizer which has over 1M customers. Check their support forum. SG is already claiming your plugin is injecting too much garbage into the htaccess file.

(2) Enable / Disable **GZIP Compression**

(3) Enable / Disable **HTTPS**

(4) Enable / Disable **Emojis**

(5) Enable / Disable **Remove Query Strings from Static Resources**

Give your paying customers a chance to select what they need or don't. WP Rocket appears to be back-pedalling and trying to fix these issues via separate fixer plugins. In our opinion, the wrong approach. Currently, your Automated Features are adding code to htaccess files that may not be needed and cannot be controlled manually (i.e., bloatware).

Thank you!
