### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by sparkbold** [wp-media/wp-rocket#4092]
I found the bug below. I am using:

- Wp Rocket Version 3.9.0.3 
- my userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"

```
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at <anonymous>:1:88
    at window.onload (<anonymous>:1:178)
    at RocketLazyLoadScripts._triggerWindowLoad ((index):3)
    at async RocketLazyLoadScripts._loadEverythingNow ((index):3)
```

**Comment by mehedihasanziku** [comment]
It's happen for me too, but it can be solved if you add full pattern in "Delay JS Execution", so mismatch/half pattern in that field throws console error.

means for example

```
<script id="blog-reader-nav"></script>
<script src="blog-reader-nav.js"></script>
```

now if you add "blog-reader-" it will show that error on console. but `"blog-reader-nav"` it doesn't.

**Comment by sparkbold** [comment]
Interesting, here are the patterns on our site and they are the default - [link to docs](https://docs.wp-rocket.me/article/1349-delay-javascript-execution?utm_source=wp_plugin&utm_medium=wp_rocket)
```
(?:/wp-content|/wp-includes/)(.*)
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
js-(before|after)
```

**Comment by GeekPress** [comment]
@sparkbold Please open ticket support from here: https://wp-rocket.me/support/

And provide your website URL and WordPress access to be able to help you.

Github isn't the right to help you solving unknown issue like that.
