### ISSUE TITLE
Compatibility of Delay JS (while default exclusion) with Divi tool box plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4095]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Yes 
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
When the user interacts with the Divi page (having Divi tool box plugin on it) after page load => the page will keep loading forever

**To Reproduce**
Precondition:
- Having a page with animation on Divi + Divi toolbox is on
- delay js is on with our default exclusion

1. Open the page
2. Move the mouse after the page is loaded in browser
3. Page keeps loading

**Expected behavior**
Animation is displayed with no user interaction as same as when Divi toolbox is off (here https://github.com/wp-media/wp-rocket/issues/4014)

**Screenshots**

https://user-images.githubusercontent.com/76941962/123292646-8a850380-d513-11eb-8906-fb7bef60b3f8.mp4

**Additional context**
- If no default exclusion, everything is delayed as expected (if we excluded `preloader` here => we will be in the infinite loading)
- While having default exclusion, if we moved the mouse while the page is loading, it will work fine. 
- We need to check similar plugins

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Fixed in the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
