### ISSUE TITLE
GTM compatibility with Delay JS (with/without default exclusion)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4096]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.4
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
When delay js is on, this script http://snippi.com/s/xqevkjy is delayed causing some images height to be set to 0

**To Reproduce**
Precondition:
- delayjs is on with default exclusion

1. Go to https://new.rocketlabsqa.ovh/3961template2/
2. Move the mouse after or while page load
3. Images height set to 0

**Expected behavior**
Image height displayed correctly

**Screenshots**

https://user-images.githubusercontent.com/76941962/123295478-0a13d200-d516-11eb-8b6f-94aa94806dc9.mp4

**Additional context**
- In case of no default exclusion, the same will occur if we move the mouse while the page loads
- Both cases fixed if we excluded `gtm`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
Decreasing the priority to low as we don't seem to have any tickets related to that problem yet.

**Comment by piotrbak** [comment]
We include GTM in the backend, together with lack of feedback/ticket it's enough to close the issue.
