### ISSUE TITLE
RUCSS Unstable | Added Limitation Between "Combine JS Files" and "Delay JS Execution" Slows Down Website

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4097]
**Before Submitting Issue, Ensure The following Steps Have Been Completed:**

- Make sure you’re on the latest version: **Yes, using V3.9.0.4**
- Use the search feature to ensure that the bug hasn’t been reported before: **Yes, checked. No similar issues found.**

**Describe The Bug:**

V3.9.X.X adds a "Remove Unused CSS" feature. It also limits the ability to execute "Combine JS Files" and "Delay JS Execution" at the same time.

After running GTMetrix and Lighthouse several times, **Unused CSS messages still appeared (at random) in the test results** for both Desktop and Mobile devices **and our website speed increased** (resulting from a higher number of HTTP calls).

**To Reproduce:**

(1) Deactivate "Optimize CSS Delivery."

(2) Activate "Remove Unused CSS."

(3) Activate either "Combine Javascript Files" or "Delay Javascript Execution" and enter same data from V3.8.8 (defaults) or the new ones provided in V3.9.0.4.

(4) Clear all cache (from theme, plugins, server, CDN)

(5) Run GTMetrix and Lighthouse in both Desktop and Mobile modes. Run each test at least three (3) times -- preferably five (5) times. Results (errors) vary. Not consistent.

**Expected Behavior:**

(1) Unused CSS messages no longer appear in GTMetrix or Lighthouse (for both Desktop and Mobile devices). 

(2) Same or fewer HTTP Calls > Improved website loading speed.

**Useful (Test) Information:**

Theme and Version: Avada V7.2.1
PHP Version: 7.4.20
jQuery Version: 3.60
Test Browser: Chrome (Incognito Mode)

**Action Requested:**

(1) Reinstate (allow) the simultaneous use of "Combine JS Files" and "Delay JS Execution."

(2) Investigate and update RUCSS code to eliminate instabilities noted in test results.

**Comment by GeekPress** [comment]
If your website is slower without combine JS, it means your website isn't on HTTP/2. In 2021, you must have your website running on HTTP/2, and even more when you are trying to optimize your performance. It's the first thing you must apply on your website or ask your hosting to have.

If you want more info about why combining isn't a good thing, please refer to this post: https://wpjohnny.com/why-you-shouldnt-combine-css-js-performance-reasons/
