### ISSUE TITLE
2.10 alpha-3 - saving critical css escapes some characters

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#410]
e.g. 
font-family:'droid_serifregular'
=> font-family:\'droid_serifregular\'

and therefore the font breaks

**Comment by Tabrisrp** [comment]
is it missing something here? it's the same for both lines

**Comment by webtrainingwheels** [comment]
Crap I think Github sanitized it or something. Here's how it ended up:
![critical_css](https://cloud.githubusercontent.com/assets/1043076/26071482/14a90d1a-395d-11e7-83b4-8a34b7c2da55.jpg)
