### ISSUE TITLE
Defer JS + SiteOrigin page builder: Prevents showing Revolution Slider in full width on first load

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4100]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When SiteOrigin page builder is in use with Defer JS, it prevents Revolution from showing on full width. 

![image](https://user-images.githubusercontent.com/1289174/123507999-ba8fec00-d664-11eb-9062-7a227fe482a1.png)

Clicking around restores the width. 

**To Reproduce**
1. Use SiteOrigin Page Builder
2. Enable Defer JS
3. Set a RevSlider slider to full width on a page.

**Expected behavior**
The slider should keep its full width. 

**Screenshots**
Added one on the description. 

**Additional context**
Update: The issue seems to happen only if the jQuery library is excluded.

Excluding the following script from Defer JS fixes the issue: 

```/wp-content/plugins/siteorigin-panels/js/styling.min.js```

Ticket - ​https://secure.helpscout.net/conversation/1545392967/272167/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
I can add the exclusion if greenlighted!

**Comment by Mai-Saad** [comment]
Can't reproduce it with revslider 6.4.11 and 6.5.3 with WPR 3.9.0.4 nor 3.8.8 and page builder Version 2.12.5  on both FF and chrome for https://new.rocketlabsqa.ovh/revslider/ , https://new.rocketlabsqa.ovh/revslider_client_template/, https://new.rocketlabsqa.ovh/4100template2/

**Comment by DahmaniAdame** [comment]
@Mai-Saad customer reshared the creds with some feedback from the SiteOrigin support. 

Current versions: 
- WPR 3.9.0.4
- SiteOrigin 2.12.5
- SiteOrigin Widgets Bundle 1.21.0
- RevSlider 6.4.11

The issue is still happening after removing  `/wp-content/plugins/siteorigin-panels/js/styling.min.js` from exclusions.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
