### ISSUE TITLE
Minify JS breaks CleverPush script

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4104]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.4
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When _Minify JavaScript_ option is enabled, the script throws console error:
![image](https://user-images.githubusercontent.com/60236665/123544714-34a39c00-d75d-11eb-838d-6b09aed0733e.png)

**Expected behavior**
No errors should be in the console

**Additional context**
The script comes from the CleverPush solution: https://cleverpush.com/

Excluding `static.cleverpush.com` resolves the error. Possibly making an automatic exclusion is necessary.

Ticket: https://secure.helpscout.net/conversation/1553687181/274476/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `static.cleverpush.com` as a pattern to the defaults exclusion array in AbstractJSOptimization::get_excluded_external_file_path()

### Estimate the effort ✅
Effort `[XS]`
