### ISSUE TITLE
Remove Google Adsense code from Delaying Javascript option

### ISSUE THREAD

**Issue by kuodain** [wp-media/wp-rocket#4107]
Hi,
My WPR version was just updated to 3.9.0.4  and i was noticed a serious Adsense earning dropout after update WPR. I have placed an AdSense code just above the fold and this was not loading during the page load, I have to skip the google Adsense js code from delaying.

Please I need to exclude google Adsense code from delaying the javascript list, earlier we can add /remove js code manually. But now I can't do that. 

I have added adsbygoogle.js in the Excluded JavaScript Files section, but it doesn't work

**Comment by GeekPress** [comment]
You need to add adsbygoogle without .js.
