### ISSUE TITLE
How to add a particular Js on Delay javascript execution

### ISSUE THREAD

**Issue by kuodain** [wp-media/wp-rocket#4108]
Hi

I have to add the below js to add in Delay javascript execution

//s7.addthis.com/js/300/addthis_widget.js
cse.google.com
google_cse_v2.js

**Comment by javiergutierrezchamorro** [comment]
You can simply add it to the exclusions.

![image](https://user-images.githubusercontent.com/4672971/123631268-d5a25d80-d816-11eb-8b83-9e50fa0cc63a.png)

**Comment by GeekPress** [comment]
@kuodain Github isn't the right place to get support. Please open a ticket from here: https://wp-rocket.me/support/
