### ISSUE TITLE
Template not displayed properly when created while Preload + RUCSS are enabled until we clear cache

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4118]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
When creating a page template while Preload and RUCSS, the page won't be displayed correctly incognito till clear cache

**To Reproduce**
precondition:
- default settings + enable RUCSS => {preload and RUCSS are both enabled}
1. Create a new page i.e using this template http://snippi.com/s/h1565x7
2. Open the page incognito
3. UI of template not displayed as ?nowprocket until we clear cache

**Expected behavior**
Page UI displayed properly even if there are some unprocessed CSS files with no need to clear cache

**Screenshots**

https://user-images.githubusercontent.com/76941962/123989806-87818b80-d9c9-11eb-8842-d17a2c7aea39.mp4

**Additional context**
- working fine locally using the same WPR settings
- Problem exists on https://new.rocketlabsqa.ovh/ which is using Astra theme with the 1st demo sample {the problem was reproduced on https://rocketlabsqa.ovh/ while using the same theme and demo site}
- If preload only enabled or RUCSS only enabled with the same rest settings, the page displayed properly with no need to clear cache

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closed with 3.11
