### ISSUE TITLE
WooCommerce Show Single Variations (Iconic) clears cache on product variation save

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4120]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The **WooCommerce Show Single Variations** plugin has an action to switch themes when a variation is saving, which forces WP Rocket to clear its cache: 
`switch_theme` > `maybe_regenerate_cpcss` > `wp_ajax_rocket_cpcss_heartbeat ` > `cpcss_heartbeat` > `generation_complete()`

The following code on the `/wp-content/plugins/iconic-woo-show-single-variations/iconic-woo-show-single-variations.php` triggers the `switch_theme` action.

```
public function on_variation_save( $variation_id, $i = false ) {
	$action = filter_input( INPUT_POST, 'action' );

	if ( $action === 'woocommerce_save_variations' && $i === false ) {
		return;
	}

	$this->save_product_variation( $variation_id, $i );
	Iconic_WSSV_Product_Variation::set_taxonomies( $variation_id );
	$this->add_attributes_to_variation( $variation_id, $i );
	$this->delete_term_counts_transient();

	// We need to send all the hook parameters to avoid issues with
	// other plugins/themes listening to this action
	$current_theme = wp_get_theme();
	do_action( 'switch_theme', $current_theme->get( 'Name' ), $current_theme, $current_theme );
}
```

`switch_theme` will fire the `maybe_regenerate_cpcss`:
https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L91

When `wp_ajax_rocket_cpcss_heartbeat` fires, the `cpcss_heartbeat()` method will run:
https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/CriticalPath/Admin/Admin.php#L42-L76

When there aren't any pending PTs or taxonomies, `generation_complete()` will run:
https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/CriticalPath/Admin/Admin.php#L68

and this will trigger `rocket_clean_domain()`:
https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/CriticalPath/Admin/Admin.php#L189

Props to @vmanthos 

**To Reproduce**
1. Install the **WooCommerce Show Single Variations** plugin
2. Add a variation to the product or edit/save a variation
3. See the cache fully cleared at `/wp-content/cache/wp-rocket/1/domain.ext`

**Expected behavior**
The cache shouldn't be fully cleared when the variation is saved.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1536021331/269823
Plugin - https://drive.google.com/file/d/1QCUzLkqs8YawIrAGixt-kZ6HE2x4hew0/view?usp=sharing

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
