### ISSUE TITLE
Charset declaration is missing or occurs too late in the HTML (in some cases)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4121]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On some occasions, Lighthouse & PageSpeed will show the following "Best Practice" notification: 

`Charset declaration is missing or occurs too late in the HTML`

**To Reproduce**
1. Enable Delay JavaScript Execution
2. Check a cached page source code
3. Run a test on Lighthouse with "Best Practices" enabled
4. See the error

From my testing, this will happen occasionally on some sites.

**Expected behavior**
Inject the IE fallback script after the meta tag defining the `charset` to prevent the recommendation from showing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/123789290-ee714880-d8d4-11eb-8f99-64b9904811b8.png)

**Additional context**
The notification is prompted because we add our IE fallback script (6300 bytes) right after the opening heading tag, which pushes the `<meta charset>` below the first 1024 bytes threshold. 

https://github.com/wp-media/wp-rocket/blob/4f86c478c74e962eb6361b59a0f0b575adab27a9/inc/Engine/Optimization/DelayJS/Subscriber.php#L98-L112

We could possibly run a check before defining the `$pattern`. If there is a meta tag defining the `charset`, it can be targeted with a pattern. 

`/<head[^>]*>/i` would be kept as a fallback in case there is no meta tag defining the `charset`.

Ticket - https://secure.helpscout.net/conversation/1551660251/273982/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vlaskiz** [comment]
Just found out about this in W3 validator tool, glad the ticket is open, but is anything being done regarding this?

**Comment by girlie** [comment]
Related ticket: https://secure.helpscout.net/conversation/1587743174/284214/

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `DelayJS\Subscriber::add_delay_js_script()`, modify the method to first check for a meta charset tag as the target pattern. If not found, fallback to the current head tag pattern.

Update corresponding tests fixtures to validate the change.

### Estimate the effort ✅
Effort `[S]`
