### ISSUE TITLE
Pre-warmup fetch resources are stopped in some cases

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#4122]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
I was checking an issue with @vmanthos and the issue was that the fetch process doesn't start at all till 1 hour elapsed and RUCSS is enabled.
After debugging on the customer's site, I found that the background process that we use on fetching resources from scanned pages failed saving the batches into the options table, exactly here on this line:

https://github.com/wp-media/wp-rocket/blob/3250a7ecdefeb1021bc780f2015566180195c9e7/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php#L101

so all what I did is to base64_encode the resource content here: https://github.com/wp-media/wp-rocket/blob/a0882549879826b9fe5e18ef620dc705d497efba/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcher.php#L179

and then use base64_decode here
https://github.com/wp-media/wp-rocket/blob/b7b4424f9e85cb389b489c481c93a336dfcccb4[…]inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php

like this
```
$resource['content'] = base64_decode( $resource['content'] );
```

this is exactly what I did here on this PR (I was researching some time ago)
https://github.com/wp-media/wp-rocket/pull/3985/files

so maybe encode/decode make size lower (theoretically it should reduce 30% of its size)

**To Reproduce**

I can't find a pattern to reproduce the issue at any host.

**Expected behavior**
The fetch process should perform properly.

**Additional context**
- I found a similar issue with our test site reported by @Mai-Saad but the difference is that only one page was stopped fetching not all pages then solved it also with encode/decode.
- I think we will not need this encode/decode mechanism if we solved this issue: https://github.com/wp-media/wp-rocket/issues/4072 so the resource's content will not be added to the batch at all.
https://wp-media.slack.com/archives/G01AMD70N7P/p1625049019275000

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
The ticket that's related to this issue is: https://secure.helpscout.net/conversation/1547161846/272643/

**Comment by vmanthos** [comment]
Likely related ticket: https://secure.helpscout.net/mailbox/5de4805abf96951b/2135277/

There are two pages that are not fetched:
![](https://i.vgy.me/xeNAk5.jpg)

`update_site_option()` returned `false` here:
https://github.com/wp-media/wp-rocket/blob/3250a7ecdefeb1021bc780f2015566180195c9e7/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php#L101

I used `base64_encode()`, and `base64_decode()`, but this didn't resolve the issue, and RUCSS is not created.

On the pages that were to be fetched, CSS/JavaScript weighs over 10MB!

In the `debug.log` I got errors like this: 
```
Error Got a packet bigger than 'max_allowed_packet' bytes de la base de datos de WordPress para la consulta INSERT INTO `qby_wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('rocket_rucss_warmup_resource_fetcher_batch_2e91e6f627adc21079dc3', 
```
https://pastebin.com/9JtBJk0r

MySQL's `max_allowed_packet` was exceeded, and this prevented the saving of the data in the DB.

Maybe we should be checking for that:
https://stackoverflow.com/questions/5688403/how-to-check-and-set-max-allowed-packet-mysql-variable

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1555327775/274885/

In this case, `base64_encode/base64_decode()` did the trick, and allowed all pages to be fetched. Previously only 6/9 were.

**Comment by engahmeds3ed** [comment]
@wp-media/php I think with this issue: https://github.com/wp-media/wp-rocket/issues/4072

We don't send the content to the options table (background process batch data) as we call the content only inside the background process task.

Also, what do you think about the new approach of encoding/decoding content when saving/updating and retrieving from the DB ( plz check this PR: https://github.com/wp-media/wp-rocket/pull/3985 )

**Comment by remyperona** [comment]
Indeed with this change added in 3.9.1 this issue should not happen anymore

**Comment by Mai-Saad** [comment]
On the current branch, still sometimes stuck fetching the last file after fresh install on https://mega.wp-rocket.me/divi so recommend anyone else test it on divi and try:
1- Enable RUCSS after fresh install
2- Enable RUCSS + OCD after fresh install
