### ISSUE TITLE
PHP warning: Invalid argument supplied for foreach() in wp-background-process.php

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4129]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
WP_DEBUG logs multiple errors of the following content:
`PHP Warning: Invalid argument supplied for foreach() in /www/wp-content/plugins/wp-rocket/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php on line 314`

The current issue appeared due to the rocket_partial_preload batches that contain serialized data.

The value of `$batch->data` logged after this line: https://github.com/wp-media/wp-rocket/blob/2d094e01278e3e911d50cdded013f22f53ea4e70/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php#L312 is the following:

![image](https://user-images.githubusercontent.com/60236665/124450241-e742b280-dd8c-11eb-961b-5accf3381314.png)
Link to the note with full value: https://secure.helpscout.net/conversation/1561866652/276589?folderId=3864740#thread-4543785933

**To Reproduce**
The issue was reproduced on a customer's site. The steps are unclear.

**Expected behavior**
No warnings in WP_DEBUG.
We should check if the `$data` is of the correct type before doing the `foreach` loop in the background process.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1561866652/276589
More details in the note: https://secure.helpscout.net/conversation/1561866652/276589?folderId=3864740#thread-4542818897
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1625397863006800

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Same warning, but related to the RUCSS.
Ticket: https://secure.helpscout.net/conversation/1558402299/275665/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1569090688/278901/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1573031603/280180?folderId=377611

**Comment by piotrbak** [comment]
The issue is not relevant with the 3.12 preload implementation.
