### ISSUE TITLE
Improve Delay JS safe exclusions to avoid breaking sites

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#4130]
**Is your feature request related to a problem? Please describe.**
I would like to provide some feedback about the default exclusion which is not added anymore by default since 3.9.0.5. Many websites are not working anymore since the default exclusion isnt added by default, while re-adding it makes them work again. Please think about the below idea.

**Describe the solution you'd like**
What about adding a sub-setting called "Exclude potentially unsafe files" above the custom exclusion box? If enabled, this automatic exclusion would apply automatically the below exclusion :

(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)

**Mockup**
![image](https://user-images.githubusercontent.com/51261962/124520248-23f1c680-ddec-11eb-9549-58fd7edb19c8.png)

**Comment by GeekPress** [comment]
> Many websites are not working anymore since the default exclusion isnt added by default,

It should be the reverse as the default exclusion list is failing a lot of time to exclude some inline JS.

Can you please provide an example where no exclusion is creating an issue?

Thanks
