### ISSUE TITLE
Cache Clearing - rocket_clean_home_feeds() runs even when feed caching is disabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4133]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ (3.9.0.5)
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When `rocket_clean_post()` runs, `rocket_clean_home_feeds()` will run as well, even when we are not caching the site's feeds, which is the default:
https://github.com/wp-media/wp-rocket/blob/93b71be41a646311462faa9497d60c4308115471/inc/common/purge.php#L245

On a Cloudways site, these results in sending 2 `PURGE` requests to their Varnish. Each of these took 2 seconds. 

**To Reproduce**
1. Install WP Rocket - feeds caching is disabled by default.
2. Add log statements in `rocket_clean_home_feeds()`.
3. Clear a post's cache to trigger `rocket_clean_post()`.
4. Check the log.

**Expected behavior**

`rocket_clean_home_feeds()` should run only if someone has activated feed caching.

**Additional context**
**Ticket:** https://secure.helpscout.net/conversation/1539262653/270635/
**Slack convo:** https://wp-media.slack.com/archives/C43T1AYMQ/p1625218864433800

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Since we don't have an option (anymore) for the feed cache, we don't have an easy way to detect if we should or not call the clean function.

I'm wondering though if at that point we should remove the default call of this function in our code, and instead update our helper plugin to hook on `after_rocket_clean_post` and call the function only when the helper is enabled.

@piotrbak what do you think?

**Comment by piotrbak** [comment]
Yes, that sounds like the best approach. Thanks @Tabrisrp !

**Comment by vmanthos** [comment]
This approach will result in feeds not being cleared, when we make the change, and will create tickets.

How about using `has_filter()` for `wp_rocket_cache_feed` which is used in the helper plugin?
https://github.com/wp-media/wp-rocket-helpers/blob/fe97245d17d5341f206de1638db87bdc0554a141/cache/wp-rocket-cache-feed/wp-rocket-cache-feed/wp-rocket-cache-feed.php#L30

```PHP
if( false !=== has_filter( 'rocket_cache_reject_uri', 'wp_rocket_cache_feed') ){
   rocket_clean_home_feeds();
}
```
Here I am making an assumption that whoever has enabled feeds caching has done it using our helper plugin.
If there are customers who've done it differently, they will be affected by the approach I'm suggesting.

I'm guessing they will be less than those that will be affected if we add `rocket_clean_home_feeds()` in the helper, given that in support and in [our docs](https://docs.wp-rocket.me/article/1662-enable-cache-for-rss-feed) we suggest using the helper.

**Comment by remyperona** [comment]
We can do that too, it's true that it will has less side-effect

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1805560493/329554/

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `rocket_clean_post()`, wrap the call to `rocket_clean_home_feeds()` to check if the helper plugin callback is used.

```
if ( false !=== has_filter( 'rocket_cache_reject_uri', 'wp_rocket_cache_feed') ) {
   rocket_clean_home_feeds();
}
```

### Estimate the effort ✅
Effort `[XS]`
