### ISSUE TITLE
WP Rocket External Links (Backend) Do Not Open in New Browser Tab

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4134]
**Describe the Bug**

Currently, WP Rocket's external links open in the same page we're logged in (WordPress Dashboard), which prevents us from "multitasking" and slows us down.

**To Reproduce**

1. Go to WordPress dashboard
2. Mouseover (hover) on top of  "WP Rocket" (top menu item)
3. Click on "Documentation", "FAQ", or "Support" (external links)
4. External links open in same WordPress Dashboard

**Expected Behavior**

All external links should open in a new browser tab. Please revisit plugin's entire list of external links and ensure they open in a new browser tab (i.e., add the parameter "target=_blank" to these links)

**Screenshots**

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/ZY36s95B/wp-rocket-menu-open-links-new-tab.jpg' border='0' alt='wp-rocket-menu-open-links-new-tab'/></a>

**Comment by Mai-Saad** [comment]
Duplicated with https://github.com/wp-media/wp-rocket/issues/3546
