### ISSUE TITLE
Delay JS causes console error when simpli.fi scripts are delayed

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4138]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When _[simpli.fi](https://simpli.fi/)_ scripts are delayed, there is the following console error:
![image](https://user-images.githubusercontent.com/60236665/124717525-e2593c80-df0d-11eb-8d84-7ad73735202b.png)
Full-screen image: https://jmp.sh/mlvhiYb

**To Reproduce**
Reproduced on a customer's site where the following scripts were present:
```
https://tag.simpli.fi/sifitag/209ec500-XXXX-XXXX-XXXX-XXXXXXXXX
https://tag.simpli.fi/sifitag/af459450-XXXX-XXXX-XXXX-XXXXXXXXX
https://i.simpli.fi/p?cid=XXXXX&cb=sifi_att_XXXXX._hp
```
1. Enable Delay JS option with or without standard exclusions
2. Check the console for the error.

**Expected behavior**
No console errors.

**Additional context**
The issue is resolved by excluding `simpli.fi` or `tag.simpli.fi` from the Delay JS

Ticket: https://secure.helpscout.net/conversation/1558025163/275536/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
I think the work we did in this issue #4263 should fix this

**Comment by mostafa-hisham** [comment]
### Identify the root cause ✅ 
The script should not be delayed to avoid this problem


### Scope a solution ✅ 
Add 
```
simpli.fi
```

as patterns in the 
WP_Rocket\Engine\Optimization\DelayJS\HTML::$excluded array 
and update the fixtures to validate

### Estimate the effort ✅

Effort `[XS]`
