### ISSUE TITLE
Add support of CDN rewrites for Avada’s parallax feature

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#414]
Avada’s parallax feature stores image URLs in a `data-bg-image` attribute of a `<div>`. That attribute is not supported by WP Rocket’s CDN rewrites, and since it is on a `<div>`, the `rocket_cdn_images_html` filter cannot be used to sneak in a custom attribute to be considered by `rocket_cdn_images()`.

We could create a custom function to fix this. Patch to follow.

**Comment by CristianDeluxe** [comment]
This would be perfect, right now I have to copy the parallax urls and tell the plugin not to serve them from the CDN to prevent them from being downloaded twice.

**Comment by webtrainingwheels** [comment]
Have another case of this here: https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/46787/conversations/20274099143
