### ISSUE TITLE
Emulate Monarch social icons replacement to improve user experience

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4140]
**Is your feature request related to a problem? Please describe.**
When using Monarch and Delay JS, the social icons aren't moved in their right position until a user interaction which can lead to an issue like this:
https://d33v4339jhl8k0.cloudfront.net/inline/18928/40f340a6cd26427b285d266de9732eebce7a95cf/8ee087c86de8054b2e8c57e015a9a8dbab9ab977/image.png

**Describe the solution you'd like**
Emulate the following code to not wait for user interaction to move the social icons.

```
<script id="dt-place-monarch-icons">
jQuery(function ($) {
  $(document).ready(function () {
      var icons = $('.et_social_inline.et_social_mobile_on.et_social_inline_top');
      if (icons.length) {
          icons.detach();
          icons.insertAfter($('.dt-monarch-icons'));
      }
  });
});
</script>
```

**Additional context**
We need to add the inline script only when the Monarch plugin is activated.

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
