### ISSUE TITLE
Remove Unused CSS ignores clamp()

### ISSUE THREAD

**Issue by gitgudcameron** [wp-media/wp-rocket#4145]
First of all, congrats on releasing such a kick-ass feature to remove unused CSS. You guys are absolute wizards.

Just wanted to let you know I came across an issue with the used CSS when using clamp(). The used CSS would ignore my clamp CSS and when I reverted to media queries, it worked fine.

I use clamp() for my font sizes and was having 

**To Reproduce**
1. Add some style to a h1 ` font-size: clamp(2.3rem, 4vw, 4rem);`
2. Select 'Remove Unused CSS'

**Expected behavior**
That CSS add should be added to the used CSS.

**Additional context**
I did have other h1 styles in place and the clamp style, in this case, was overwriting it but not when 'remove unused css' was active.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@gitgudcameron Was the CSS value completely removed in the used CSS generated? Could  you provide sample of the HTML and CSS where you had the issue?

**Comment by mostafa-hisham** [comment]
I tested it locally and couldn't reproduce it

**Comment by iCaspar** [comment]
To confirm, h1 with clamp property is retained on my test site as well.
@gitgudcameron Please see @Tabrisrp note above if you can give us any other context to reproduce, or let us know if this is still happening for you, that would be great.

**Comment by piotrbak** [comment]
Closed with 3.11. Confirmed the fix with the new SaaS
