### ISSUE TITLE
Remove Unused CSS has problems with dynamic css and css selectors

### ISSUE THREAD

**Issue by wpsumo** [wp-media/wp-rocket#4147]
Wanted to mention that I saw the RUCSS is having problems with selectors that is appended with javascript.

I tested on an Oxygen builder site and RUCSS removed all AOS css so menu drop down in oxygen pro menu is no longer having any fade in effect. 

Also tested an item which is appending classes on click, this no longer works as the css selectors is removed in the used.css

Modal 

**To Reproduce**
1. Add some styling to a class
2. Don't add it to any element
3. Append and add the class on click
4. Select 'Remove Unused CSS'

**Expected behavior**
The CSS should not be removed from used CSS. RUCSS needs better support for dynamic selectors.

**Additional context**
I was testing with Oxygen builder so use it for testing if needed. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
> Also tested an item which is appending classes on click, this no longer works as the css selectors is removed in the used.css

@wpsumo Please share the JS code you are using to append classes on click.

Thanks

**Comment by wpsumo** [comment]
@GeekPress I will share code example once I'm in front of my computer. But didn't see any jQuery based toggle class to work. One compatibility out of the box is Oxygen builder's pro menu which toggle class on hover for desktop and slide out off canvas on mobile. You can test that part here: https://oxygenbuilder.com/try/

**Comment by wpsumo** [comment]
@GeekPress Example here, which work with the same expressions.

`$(document).ready(function(){
  $("button").click(function(){
    $("p").toggleClass("main");
  });
});`
https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_html_toggleclass

**Comment by NataliaDrause** [comment]
This seems to be related: https://secure.helpscout.net/conversation/1573525768/280321/

The site is missing styling even for <body> and other top level elements.

Safelisting all the Oxygen stylesheets still didn't resolve the issue.

Notes and screenshots are in the note of the ticket.

**Comment by wpsumo** [comment]
Safelisting all Oxygen stylesheets would defeat the point of the remove unused css. So that would not be an ideal solution to the problem.

**Comment by jazir555** [comment]
You mean defeat the point right wpsumo?

**Comment by wpsumo** [comment]
@jazir5 Yes sorry for the typo, corrected. Thanks.

**Comment by NataliaDrause** [comment]
Possibly related: https://secure.helpscout.net/conversation/1791886419/327085/#thread-5279558329

**Comment by piotrbak** [comment]
We should have a better handling of those cases with 3.11. Leaving the issue opened and waiting for feedback.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1848224170/337518/ `3.11.0.4`

An issue with a highly dynamic class on https://wordpress.org/plugins/wp-recipe-maker/

![image](https://user-images.githubusercontent.com/1289174/163670259-a9a4dbfe-b922-415b-a611-43a9e31751bc.png)
https://drive.google.com/file/d/1_mh1OS7lKsEQq8l0_Jj1uI17pO7YaZIC/view?usp=drivesdk

By the time the CSS is generated and added to the database, the class would change. On the next cache clearing, the class would have been already changed.

Can be fixed by excluding `.wprm-advanced-list-` using `rocket_rucss_inline_content_exclusions`.

**Comment by piotrbak** [comment]
@DahmaniAdame isn't it related to this filter?
https://github.com/wp-media/wp-rocket/blob/63f649200fa3b5b81ec83812d3448eeeea28e464/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L345

**Comment by DahmaniAdame** [comment]
@piotrbak yes! I just used that filter last week. Forgot to update this one.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1856472620/338688/
Style is added after the element and selectors change on each cache generation. 
Fixed by excluding `#image_` using `rocket_rucss_inline_content_exclusions`.

**Comment by piotrbak** [comment]
I'm closing this issue. Each case should be treated separately.
