### ISSUE TITLE
Delay JS - WPML redirect according to browser language issue

### ISSUE THREAD

**Issue by bwafels** [wp-media/wp-rocket#4149]
- Made sure you’re on the latest version: YES (3.9.0.5)

**Describe the bug**
When using delay JS & having WPML automatically redirect to browser language (if it exists & isn't the default site language): 

The website loads all elements that don't require user interaction first. Once the user moves his/her mouse the page will load fully in the main language (dutch for my site). After it is fully loaded the website will detect it is actually a french speaking client. This creates a visual illusion of the site unloading elements again (e.g.: slider) because it goes to a different URL of the same page. After the user moves around again it will present the correct language and fully loaded page. This is a 4 step page load for them.

**To Reproduce**
1. Enable delay JS v2
2. Activate WPML automatically detect browser language (found in settings tab "languages")
3. Browse to the main URL using a browser language set to the non default language of the site (my main language is dutch and the translated is french)

**Expected behavior**
WPML should be able to redirect to the correct translated website version before full load.

**Additional context**
I found out this issue exists because I live in a country with multiple official languages and was playing around in a computer store with apple & windows computers setup in a different language than mine. I can imagine this is a jarring experience for those people. I always like to try my site in computer stores as it is difficult to understand how the site will perform in the real world. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

Edit: a fast reload may even be triggerd by the WPML setting if it is the same language. This is less visible because it is the exact same content

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
The WPML script handling the redirection is delayed.

### Scope a solution ✅ 
Add `/dist/js/browser-redirect/app.js` to the exclusion patterns for delay JS. This is the path to the script in WPML.

Add the corresponding fixture test to validate.

### Estimate the effort ✅
Effort `[XS]`
