### ISSUE TITLE
Exclude JS defer for Jetpack Stats not working

### ISSUE THREAD

**Issue by sarangsss29** [wp-media/wp-rocket#4151]
Before submitting an issue please check that you’ve completed the following steps:

Made sure you’re on the latest version ✅
Used the search feature to ensure that the bug hasn’t been reported before ✅

Describe the bug
When using Jetpack Stats
https://wordpress.org/plugins/jetpack/
The latest WP-Rocket v3.9.0.5 defers the WP Stats script resulting in wrong reports of like number of pageviews, hits, etc.

Screenshots of the code being deferred
http://prnt.sc/1aoyhxs

Enable Load JavaScript deferred option

Add the exclusion list:
https://stats.wp.com
stats.wp.com
stats
_stq

Use Jetpack Plugin
Enable Stats
Watch page source

Expected behavior
Exclude the JS from defer

**Comment by javiergutierrezchamorro** [comment]
This is the native JS defer and not the WP-Rocket rocketlazyloadscript implementation.

**Comment by GeekPress** [comment]
Jetpack Stats is automatically excluded from Delay JS since 3.9.0.5. As @javiergutierrezchamorro said, the defer attribute is added by Jetpack itself.
