### ISSUE TITLE
Delay JS Execution - Add a warning notice before activation

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4153]
We currently display a warning notification for Minify JS option but we don’t for Delay JS execution. We should add the same notification and maybe add a button to the [Delay JavaScript Execution compatibility exclusions](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions)

![Capture d’écran 2021-07-13 à 14 22 16](https://user-images.githubusercontent.com/11939512/125451589-a039c1f6-1ff8-449b-88d0-3490a562554b.png)

**Comment by GeekPress** [comment]
It's a bit overkill after we will release this, isn't it? https://github.com/wp-media/wp-rocket/issues/4044

**Comment by piotrbak** [comment]
After all, with default exclusions and 3.13 backend I don't think we should consider this. Feel free to reopen it if necessary
