### ISSUE TITLE
Delay JS - Elementor Post Widget & Elementor Menu Broken With jQuery Exclude

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4156]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

Elementor Submenu & Elementor Post Grid/Masonary Doesn't work After UI.

For Submenu: In dom i see `<span class="sub-arrow">` not present and more class like `has-submenu`. (Arrow Icon not visible and submenu doesn't work), it's an same case for mobile too.

For Elementor Post Widget : in dom i see `<div class="elementor-post__thumbnail elementor-fit-height">` 
**`"elementor-fit-height"`** class missing. it's resizes the image to fit container, without this image doesn't looks good

**To Reproduce**
1. Enable Delay JS
2. Exclude `"jquery.min.js"`
3. Do Interaction.

**Expected behavior**
1. It should work without any issue. this issue happens if `"jquery.min.js"` excluded, now for every site we can't make sure that all js should be delayed. so it should work even after jquery core excluded. 

**Screenshots**
N/A

**Additional context**
This is not related to rucss, while testing this i turned it off. I believe it will be big issues for all elementor sites.
I know that we can exclude all elementor js, but that's not the solution.

**`For More Details :`** I tried to use wp-meteor in this case, it doesn't have such issue, it fires all properly after jquery excluded & UI.

But I want to see it's fixed with wprocket.

Thanks.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@mehedihasanziku Please share your full list of Delay JS exclusion.

If you are excluding only jQuery, why are you doing that?

**Comment by mehedihasanziku** [comment]
> @mehedihasanziku Please share your full list of Delay JS exclusion.
> 
> If you are excluding only jQuery, why are you doing that?

I am excluding only jquery, i am doing that, because i need to trigger manually elementor menu, as i want to delay all js of elementor, so if i do some custom jquery then i can make work elementor menu on first click, but now we can't make it work on first click with all in delay.

this is an needed feature for all sites no matter (elementor or something). as we need to toggle our menu on first click.

**Comment by mehedihasanziku** [comment]
This is somehow related to my other cases without elementor

Like:

**`With WP-Meteor:`** If i exclude some JS including jQuery It fires all JS perfectly. [ no console errors ]
**`With WProcket:`** If i exclude some JS including jQuery It doesn't fires all JS perfectly. [ no console errors ]

**`Explaination With WP-Meteor:`** We don't need to exclude more JS like WProcket to make all other JS work fine.
**`Explaination With WProcket:`** It can work perfectly, but i need to exclude more JS to make it work and that doesn't i want to exclude from delay but i am forced to do that as it's not fired in right way.

**Comment by piotrbak** [comment]
@mehedihasanziku I'm closing this since we're applying a fix to save the events in memory in delay JS. It's going to fix the problem you mentioned here without the need of excluding jQuery:
```
I am excluding only jquery, i am doing that, because i need to trigger manually elementor menu, as i want to delay all js of elementor, so if i do some custom jquery then i can make work elementor menu on first click, but now we can't make it work on first click with all in delay.
```

The updated DelayJS script should be present in 3.10.4 version of WP Rocket. If you feel something different, please reopen the issue.

**Comment by mehedihasanziku** [comment]
This issue should be open as delayJS reverted to **3.9.4.1** and `clickEvents` was not the actual case of this thread
