### ISSUE TITLE
Custom PHP enqueued styles not purged

### ISSUE THREAD

**Issue by luukskeur** [wp-media/wp-rocket#4157]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
It's a weird bug in a complex situation. It definitely started when upgrading to 3.9+. I can't reproduce the issue on 3.8.8:

I'm using a custom theme where we include custom styles generated by PHP including some ACF fields to change various CSS stuff. Like so:
```
wp_enqueue_style('mycustomcss', get_template_directory_uri().'/lib/custom-styles.css.php', false, null);
```
Where I have something like this:
```
<?php
  require_once("../../../../wp-load.php");
  header("Content-type: text/css");
  ?>
  * {
    color: pink;
  } 
  // ... and 1000+ lines with various CSS styles based on PHP variables
```
After editing the CSS color manually inside the file we manually clear the WP Rocket cache. In v3.8.8 also above CSS will be purged and refreshed. After v3.9 it stopped working. I noticed it only happens for custom PHP enqueued styles because inline styles like below still work as expected:
```
add_action('wp_head', function() {
	echo "<style>*{color: cyan}</style>";
}, 100);
```
I've worked out multiple situations, logged in and in incognito. All WP-rocket settings are disabled, so only the plugin (basics) is activated. 

Also not unimportant to mention, our WP setup:
- WP **network** site @ 5.7.2 (latest version)
- WP Rocket upgraded from 3.8.8 to 3.9.0.5

**To Reproduce**
1. Create a setup as above where CSS is enqueued from a PHP file.
2. Upgrade WP rocket to 3.9.0.*
3. Change some CSS inside that file and save it
4. Clear WP rocket cache manually from admin (not from `wp-content/cache` files! -> which will work)
5. The cache is not cleared for incognito users. Even after hard-cache refresh etc.

**Expected behavior**
All assets are purged and the above file(content) is cleared.

**Additional context**
Looking forward to any reply and am willing to help out resolve/reproduce the issue. 
And ofcourse, thanks for the great plugin, it serves me well for a long time (and will do)!

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
It could be related to this:
https://github.com/wp-media/wp-rocket/issues/3617

Combined with the update of the cache busting technique:
https://github.com/wp-media/wp-rocket/issues/3618

**Comment by GeekPress** [comment]
@luukskeur Thanks for the report. Can you please turn off CSS & JS minification to confirm the issue is fixed by turned off these options?

**Comment by luukskeur** [comment]
Hi @piotrbak and @GeekPress thanks for your reply!

@GeekPress as I mentioned I have all WP-rocket settings disabled. The plugin is active and that's it. So the issue isn't fixed with deactivating all options sadly.

It's what @piotrbak is saying in #3617 . I can confirm that issue (also for js) and it is probably the same.
So I think this one can be closed and we'll follow up there. Maybe i'll reopen it if it still persists after the update in #3617.
