### ISSUE TITLE
Disadvantages of the new "remove unused css" feature

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4159]
hello
I examined this feature. **The result is that this feature has many disadvantages.**
Most importantly, it increased the size of the home screen to 400 KB. While it was supposed to reduce...
The next thing is that I measured the value of unused css before and after the test. After deleting unused css by the plugin, no improvement was achieved in the results.
Another thing is that by activating this feature, many parts of the site were corrupted. Of course, the problems were solved by deactivating.
Have other users' tests been the same as mine? Please share your comments

thank you

**Comment by GeekPress** [comment]
Hi @79ho3ein , please open a ticket support from here: https://wp-rocket.me/support/
