### ISSUE TITLE
google webfont optimizer

### ISSUE THREAD

**Issue by osvaldo0123** [wp-media/wp-rocket#4160]
** Is your feature request related to a problem? Please describe. **
Requests made for google sources often slow down the page for Largest Contentful Paint

** Describe the solution you would like **
I propose to be able to optimize the fonts by converting all the google font requests into one through JS and with the delay it would be a success in the plugin

** Describe the alternatives you have considered **
I have used this Plugin to do this and it works perfectly but not google-webfont-optimizer but it no longer works because it is no longer compatible with PHP 7.4

https://github.com/SGudbrandsson/google-webfont-optimizer
![image](https://user-images.githubusercontent.com/87344969/125723819-e6fba252-6ff4-46f5-bcca-47995ab12146.png)

**Comment by remyperona** [comment]
In our next version, wer are going to update our Google Fonts optimization with the following: #2772 

This will handle, in addition to the current combination + preconnect:
- preloading the Google Fonts stylesheet
- asynchronously loading the GF stylesheet

This should be the ideal configuration to load Google Fonts on a website.

We likely won't do a different implementation using JS via webfont.

**Comment by osvaldo0123** [comment]
observing the new updates and seeing how they applied the optimization I can say that I improved but it could have been better if they had observed this way of applying

What do I notice? because this method would reduce requests and the font would not load as much paint with larger content on the page
