### ISSUE TITLE
RocketCDN UI: Notification about RocketCDN still active even if CDN option has been unticked

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4163]
Many RocketCDN customers think that unticking "Activate Content Delivery Network" option will cancel RocketCDN. 
If RocketCDN and if CDN option has been unticked, we may should display a warning notification to indicate that a RocketCDN subscription is still running for this domain:
![Capture d’écran 2021-07-15 à 16 28 19](https://user-images.githubusercontent.com/11939512/125806724-a1acc84e-2878-4061-af03-da1942add4fa.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
