### ISSUE TITLE
Delay JS: Exclude EWWW inline script for webp

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4165]
EWWW image optimizer has an option for JS WebP Rewriting: https://jumpshare.com/v/9aPlSgSZ0qDLqA2ZPKrK
There is an inline script for this which must be excluded from Delay JS so that images will load correctly. When not excluded it can take multiple interactions, scrolling up and down the page for example, to display correctly. 

The script: https://snippi.com/s/d8h3vh3

In my case I used this exclusion: `ewwwWebPInit`

Ticket: https://secure.helpscout.net/conversation/1565708096/277916?folderId=377611

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Validated on the user website.

### Identify the root cause ✅ 
This inline script can't be delayed

### Scope a solution ✅ 
Add `ewwwWebPInit` to the exclusion patterns, and add a fixture test to validate

### Estimate the effort ✅
Effort `[XS]`

**Comment by nosilver4u** [comment]
Hi folks, just wanted to add some additional clarification to the recent changes in 6.2.0. The script load_webp.js has been split into two pieces:
load-webp.js (renamed as noted in #4174) with source at
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/includes/load-webp.js
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/includes/load-webp.min.js

check-webp.js located at
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/includes/check-webp.js
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/includes/check-webp.min.js

The JS files themselves are not typically referenced (though it IS possible with SCRIPT_DEBUG or EWWW_IMAGE_OPTIMIZER_WEBP_EXTERNAL_SCRIPT). Usually the scripts are inlined for speed of processing, with check-webp.min.js inlined into the <head> section and load-webp.min.js inlined at the top of the footer before (most) other scripts.

There is one additional nuance here, which is a single line of JS to add a webp-supported class to the `<body>`. This JS is directly after the opening body tag and depends on the code from check-webp.min.js having run already. I did not see that WP Rocket does anything to the "body" script, so there shouldn't need to be anything special there.
Regardless, an exclusion for inline scripts that matches on **ewww_webp_supported** would catch all three scripts in one fell swoop.
