### ISSUE TITLE
Exclude Perfmatter's Lazy Load from Delay JS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4169]
**Describe the bug**
When Perfmatters lazy load for images is activated in addition to Delay JavaScript Execution, images will only start showing after user interaction with the page.

This applies also to all lazy-loaded images above the fold.

**To Reproduce**

- Enable Lazy-load for images in Perfmatters
- Enable Delay JS in WP Rocket
- Check a page with images above the fold.
- No image will be disabled on page load

**Expected behavior**
Images should be disabled on page load.

**Additional context**
Excluding the following scripts from Delay JavaScript Execution fixes the issue:

```
/perfmatters/js/lazyload.min.js
lazyLoadInstance
```

Original inline script:

```
<script>document.addEventListener("DOMContentLoaded",function(){var lazyLoadInstance=new LazyLoad({elements_selector:"[loading=lazy],.perfmatters-lazy",thresholds:"200% 0px",callback_loaded:function(element){if(element.tagName==="IFRAME"){if(element.classList.contains("loaded")){if(typeof window.jQuery!="undefined"){if(jQuery.fn.fitVids){jQuery(element).parent().fitVids()}}}}}});});function perfmattersLazyLoadYouTube(e){var iframe=document.createElement("iframe");var params="ID?autoplay=1";params+=0===e.dataset.query.length?"":"&"+e.dataset.query;iframe.setAttribute("src",params.replace("ID",e.dataset.src));iframe.setAttribute("frameborder","0");iframe.setAttribute("allowfullscreen","1");iframe.setAttribute("allow","accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture");e.replaceChild(iframe,e.firstChild)}</script>
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add the following patterns to the `DelayJS\HTML::$excluded` array:
```
/perfmatters/js/lazyload.min.js
lazyLoadInstance
```

Update tests fixtures to validate the change

### Estimate the effort ✅
Effort `[XS]`
