### ISSUE TITLE
Auto-exclusion for WooCommerce Extra Product Options when Delay JS is on

### ISSUE THREAD

**Issue by pdfrequest3** [wp-media/wp-rocket#4170]
**Is your feature request related to a problem? Please describe.**
This problem is related to #4077 Auto-exclusion for WooCommerce Product Gallery when Delay JS is on. But apart from Product Gallery Images, WooCommerce Extra Product Options is also loading way too lazy and only executes seconds after user interaction.

Here an example:
https://share.getcloudapp.com/nOuPyZ84

As you can see, it's not really a good user experience and even more on mobile.

**Describe the solution you'd like**
WooCommerce's Extra Product Options on a single product page should be displayed directly without any user interaction when Delay JS is on.

@GeekPress, Let me know what you think.

**Comment by GeekPress** [comment]
@pdfrequest3 Hi 🤚

On my desktop, the extra product options aren't above the fold.

We did the enhancement for the product gallery as we are sure at 100% the product image above the bold whatever the screen resolution.

It doesn't seem to be the case for the extra product options.

If you don't want to delay them, add these line into the Delay JS exclusion field:

```
TMEPOJS
/woocommerce-tm-extra-product-options/assets/js/epo.min.js
```
