### ISSUE TITLE
Compatibility with Super Socializer when default exclusion are used

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4172]
**Before submitting an issue please check that you’ve completed the following steps:**
- [ ] Made sure you’re on the latest version
- [ ] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We need to exclude some inline scripts from Super Socializer to be delayed when the default exclusion list is used to avoid an issue.

**To Reproduce**

1. Install Super Socializer plugin
2. Activate Delay JS + include our default exclusion list
3. See error

**Expected behavior**
Automatically exclude this pattern: `theChamp`

**Screenshots**

**Additional context**
URL where the inline scripts can be found:
https://grillbillbbq.com/xl-kamado-bbq-23-inch-grill-bill-pro-ii-sr

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
