### ISSUE TITLE
Using Remove Unused CSS seems to increase I/O usage when generating and preloading

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4173]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The increase seems to be even more when CPCSS is used. 

This can be problematic on shared hosting services with low I/O cap.

Increasing the preload interval (fewer items to process at once = less I/O activity).

![image](https://user-images.githubusercontent.com/1289174/126068652-64c28760-be7b-419c-85ff-306c04071a97.png)
![image](https://user-images.githubusercontent.com/1289174/126068659-d589a1e0-6983-4ac1-99c7-8bc96d2f5c48.png)
![image](https://user-images.githubusercontent.com/1289174/126068663-8155d144-bcc5-434f-ab30-aa3a173ef86e.png)

**To Reproduce**
1. Monitor the disk using the command line `dstat -d` (SSH/terminal)
2. Enable RUCSS (alone and then with CPSS) + preload
3. Monitor the # of reads/writes
4. See the difference in disk activity

Do the same test by changing the preload interval from 0.5s to 3s to 5s.

**Expected behavior**
Manage RUCSS when used with CPCSS and preload to distribute disk activity over time if needed. 

**Screenshots**
Included above.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1566133338/278088/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
This should no longer be an issue starting in 3.10 where RUCSS and CPCSS will no longer be active simultaneously.
See Issue #4285
See PR #4287

Leaving it open for now to re-check after 3.10.

**Comment by piotrbak** [comment]
This is eliminated thanks to the async approach in 3.11
