### ISSUE TITLE
Generate specific cpcss has stopped working entire

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4178]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
I cannot generate specific cpcss. I enter a post via edit, then try to generate a specific CPCSS. It just stopped working suddenly.

**To Reproduce**
Not sure, it just stopped working randomly.

**Expected behavior**
Generation of specific cpcss

**Screenshots**

**Additional context**
Is this an issue server side? I didn't change anything and it just stopped working suddenly.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jazir555** [comment]
Weird, it just started working. Must have been a server side issue.

**Comment by iCaspar** [comment]
Indeed, this was a server issue.

**Comment by jazir555** [comment]
@iCaspar 

I'm having this issue again. Is there something server side again that's causing it?

**Comment by jazir555** [comment]
@Tabrisrp 

Do you know why the server issues keep popping up?
