### ISSUE TITLE
When OCD is enabled but CPCSS is not generated, Used CSS is added as a separate file and not as inline

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4180]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before -yes

**Describe the bug**
This GH created to monitor this behavior in case it can cause any potential issues.
This is an observation that hasn't produced any issues so far. 

When _Remove Unused CSS_ + _Optimize CSS Delivery_ options are both enabled, but Critical CSS is not generated (and not added to the page), the used-css is added as a separate file instead of an inline CSS.

**To Reproduce**
1. Enable Optimize CSS Delivery option
2. Enable Remove Unused CSS option
3. Make sure that CPCSS is added on the page and used-css is added as a CSS file.
4. Manually delete CPCSS files from the `/wp-content/cache/critical-css/1/` directory
5. Clear cache
6. Check the page - the Used CSS will be added as a separate file instead of inline.

**Expected behavior**
Used CSS should be added as inline CSS when Critical CPCSS is not added to the page.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/G087NJ788/p1626769030010700?thread_ts=1626762075.009400&cid=G087NJ788

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Note: 
- The same case while working local, CPCSS not generated while used CSS is in a file
- Until CPCSS is generated, used CSS will be in the file as well (not sure if we will change this)

**Comment by remyperona** [comment]
@GeekPress Since we're going to remove the possibility to have CPCSS and RUCSS enabled at the same time in 3.10, is it worth working on that issue?

**Comment by GeekPress** [comment]
Indeed, we can close this issue.
