### ISSUE TITLE
New Adsense Code & Preloading Error in the browser console

### ISSUE THREAD

**Issue by nsgoyat** [wp-media/wp-rocket#4184]
On July 19, 2021, Google has launched the New Adsense Ad Code ([Official Source](https://support.google.com/adsense/answer/10627874)) which includes `crossorigin="anonymous"` in the `<script>` tag.

![image](https://user-images.githubusercontent.com/36985369/126447968-63464119-493c-4f6d-a8df-485324d1c4cf.png)

I implemented the new codes from Adsense. I have delayed scripts turned on in WP Rocket. With the new code, it's resulting in the Preload error shown in the browser console on every page.

`A preload for 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxx' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.`

You can browse through any of the pages on [my site](https://www.apssb.in) to reproduce the behaviour.

Due to this preloading issue, the` adsbygoogle.js `is loading twice.

![image](https://user-images.githubusercontent.com/36985369/126448350-a64632e8-cc79-446d-8f6b-cf420030b47b.png)

**To reproduce the issue at your end:**

1. Use the new Adsense Ad Code from Google.
2. Turn on "Delay Javascript Execution" from WP Rocket.
3. Visit the site frontend and see the browser console.

**Comment by nsgoyat** [comment]
It seems we need a preload tag like this one:

`<link rel="preload" href="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" as="script" crossorigin="anonymous">`

**Comment by NataliaDrause** [comment]
Author's ticket: https://secure.helpscout.net/conversation/1578174914/281789?folderId=3864740

**Comment by nsgoyat** [comment]
The error isn't there if we exclude `adsbygoogle` from "Delay Javascript Execution". The error occurs only when we are delaying the Google Ads.

**Comment by nsgoyat** [comment]
> Author's ticket: https://secure.helpscout.net/conversation/1578174914/281789?folderId=3864740

Hey Natalia,
Any update on this?

**Comment by markllego** [comment]
Any update on this?

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
The script should not be delayed to avoid this problem


### Scope a solution ✅ 
Add adsbygoogle in the `WP_Rocket\Engine\Optimization\DelayJS\HTML::$excluded` array and add a the script to the fixtures to validate

### Estimate the effort ✅

Effort `[XS]`

**Comment by piotrbak** [comment]
Closing it in favour of:
https://github.com/wp-media/wp-rocket/issues/4938
