### ISSUE TITLE
Commented out stylesheet link loaded into the <noscript> footer

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4186]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
When a commented out stylesheet is added into the source code like `!-- <link rel="preload" href="https://example.com/wp-content/dummy.css"> --> `, WP Rocket will transform this link into `<!-- <link rel="preload" href="https://example.com/wp-content/dummy.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'"> -->` and add it into the footer <noscript> tags like this <link rel="stylesheet" href="https://example.com/wp-content/dummy.css"> when Optimize CSS Delivery option is active because we will add all CSS files that we find on a page:
https://github.com/wp-media/wp-rocket/blob/0085d86acc0ffe61b2375ab459b57f89b20fa1b8/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L646
 to the <noscript></noscript> element:
https://github.com/wp-media/wp-rocket/blob/0085d86acc0ffe61b2375ab459b57f89b20fa1b8/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L651-L677

**Expected behavior**
We shouldn't process such files. Since that file is added in the <noscript></noscript> element, that would be an issue only if JavaScript is disabled tho but this can lead to errors 404 for crawlers.

According to @vmanthos, we can process the buffer while removing comments and that will prevent such issues. We do the same thing in JavaScript/CSS minification:
https://github.com/wp-media/wp-rocket/blob/0085d86acc0ffe61b2375ab459b57f89b20fa1b8/inc/Engine/Optimization/AbstractOptimization.php#L202-L216

**Related ticket:** https://secure.helpscout.net/conversation/1572657529/280071?folderId=1213662

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Can reproduce it here https://new.rocketlabsqa.ovh/4186-template/ when OCD is enabled. (UI changed and console error was there if disable js is checked on the browser)

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
We are not ignoring comments when parsing the HTML during the critical CSS process.

### Scope a solution ✅ 
Use the `hide_comments()` method in the `CriticalCSSSubscriber::async_css()` method to do the parsing on an HTML with comments removed.

### Estimate the effort ✅
Effort `[XS]`
