### ISSUE TITLE
Google font URL with the display parameter right after the domain is not processed by the enhanced Google Fonts Optimization 

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4188]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes, 3.9.1
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
A Google font URL with a display parameter right after the domain is not processed by the Google Fonts Optimization enhanced feature of 3.9.1. https://github.com/wp-media/wp-rocket/issues/2772.

**To Reproduce**
1. Add a Google Font using the `?display=swap` parameter right after the URL. **Example:** `https://fonts.googleapis.com/css2?display=swap&family=Alatsi&family=Alata&family=Ubuntu`.
In the specific test case, the used plugin to add Google Fonts is https://wordpress.org/plugins/easy-google-fonts/.
2. Enable Remove Unused CSS and have Optimize CSS delivery disabled.
3. See Google Font files not processed: https://i.imgur.com/BUsM74I.png.
4. PageSpeed report listing the font in the Eliminate render-blocking resources audit: https://i.imgur.com/x5CrEbC.png.

**Expected behavior**
Google Fonts which uses `?display=swap` or other display parameter just after the domain (instead of at the end of the URL) is processed and loaded asynchronously by the Google Fonts Optimization feature.

**Additional context**
Slack conversation: https://wp-media.slack.com/archives/C08N8J6VC/p1626891020091600

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@camilamadronero Does this issue is related to 3.9.1?

**Comment by camilamadronero-zz** [comment]
@GeekPress Yes, 3.9.1

**Comment by GeekPress** [comment]
> @GeekPress Yes, 3.9.1

@camilamadronero Thanks for the confirmation.

@wp-media/php A ping for your information :)

**Comment by Mai-Saad** [comment]
Can reproduce it here https://new.rocketlabsqa.ovh/gfv1v2/ (after updating test template)

Note:
- Even with RUCSS disabled and OCD enabled => those URLs with display attribute right after the domain aren't processed

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
in `CombineV2::parse()`, we use the following pattern `^(family=[A-Za-z0-9;:,=%&\+\@\.]+)$`. The `^` means that we expect the string to start with family, which is not always the case.

### Scope a solution ✅ 
Updating the pattern to remove the `^` token will allow matching the family value wherever it is in the URL's query.

Need to add tests fixtures to validate the change.

### Estimate the effort ✅
Effort `[XS]`
