### ISSUE TITLE
Compatibility with TranslatePress

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4190]
When using TranslatePress and WP Rocket we don't purge the cache for additional languages when updating content.

The permalink structure in this case is like this: 
Default language: example.com
Additional language: example.com/de/

The customer in this case noted it specifically related to WooCommerce products, but the issue is the same for non-Woo content as well since I guess WP Rocket won't be aware of any other language.

We could create compatibility as we do for Polylang etc.
As with other multilingual plugins, various URL configurations are allowed and should be detected: https://jmp.sh/QAwHjUf

Ticket: https://secure.helpscout.net/conversation/1573104333/280196?folderId=377611

**Comment by webtrainingwheels** [comment]
I guess this would be fixed at the same time: https://github.com/wp-media/wp-rocket/issues/3760

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1838299316/335912

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1995267507/365271/

**Comment by webtrainingwheels** [comment]
More requests: 
https://secure.helpscout.net/conversation/2022483496/371558/
https://secure.helpscout.net/conversation/2015160692/369843/
https://secure.helpscout.net/conversation/2014759996/369762/
https://secure.helpscout.net/conversation/1988449432/363806/
https://secure.helpscout.net/conversation/1980369262/362112/
https://secure.helpscout.net/conversation/1916426051/347781/
https://secure.helpscout.net/conversation/2070611512/382234?folderId=377611

**Comment by razvan-translatepress** [comment]
Hi,
I am Razvan, developer at TranslatePress. Here are some code snippets that might help. The second one requires TranslatePress version 2.5.7 which will be released in about a week.
https://gist.github.com/razvan-translatepress/a05bb4dc8cd13ab152162194950993d1

**Comment by piotrbak** [comment]
Thank you @razvan-translatepress! Do you maybe have a function that would allow us getting the flag images of active languages, like here?
https://github.com/wp-media/wp-rocket/blob/14eba34b3e146f5ba8e4e0160ab57044b4c8a388/inc/functions/i18n.php#L18

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. When doing regular update of specific post, we'll clear the cache of all versions of translated content. 
2. When updating the post using TranslatePress UI, we'll clear the cache of updated language versions **(only for TranslatePress 2.5.7 or higher)**
3. In the admin bar we'll introduce section, just like for the other multilanguage plugins. `Clear Cache` will become a parent, not clickable string. In the submenu we'll list all available languages with their flags (max-width 16px, max height 11px) and `All Languages` link. Clearing specific languages will purge cache related to specific language only while clearing `All Languages` will purge everything.
![image](https://github.com/wp-media/wp-rocket/assets/26767037/11427bbc-c69a-4e25-95a8-f7b7a893e1c7)

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
**Cleaning all version of updated post.**
Add a new event `post_updated` with first callback [here](https://gist.github.com/razvan-translatepress/a05bb4dc8cd13ab152162194950993d1#file-wp-rocket-translatepress-php-L5-L38)

**Clearing cache via TranslatePress UI for 2.5.7+**
Add a a conditional check in `get_subscribed_events` - `version_compare( TRP_PLUGIN_VERSION, '2.5.7', '>=' )`
Add a new event `trp_save_editor_translations_regular_strings` with second callback [here](https://gist.github.com/razvan-translatepress/a05bb4dc8cd13ab152162194950993d1#file-wp-rocket-translatepress-php-L48-L62)

For the Admin bar
- Update this function here https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/functions/i18n.php#L158
```
if ( function_exists( 'trp_get_languages' ) && ! empty( trp_get_languages( 'nodefault' ) ) ) {
    return 'translatepress';
}
```
- Add a new function in https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/functions/i18n.php to get all the active languages with `trp_get_languages()` with flags in the path `TRP_PLUGIN_URL . 'assets/images/flags/`
- Call new function in the switch statement here https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/common/admin-bar.php#L89
- Add a new condition to clear cache for all languages just like how we do here:
https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/common/admin-bar.php#L118-L128

Estimate the effort ✅
[S]

**Comment by razvan-translatepress** [comment]
> Thank you @razvan-translatepress! Do you maybe have a function that would allow us getting the flag images of active languages, like here?
> 
> https://github.com/wp-media/wp-rocket/blob/14eba34b3e146f5ba8e4e0160ab57044b4c8a388/inc/functions/i18n.php#L18

I have added to existing [gist](https://gist.github.com/razvan-translatepress/a05bb4dc8cd13ab152162194950993d1) a 4th item with a code example on how to get flags and language names for active languages.
