### ISSUE TITLE
RUCSS Table Not Regenerating After Adding New CSS Safelist Item (After Initial RUCSS Run)

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4196]
**Pre-Submittal Check:**

- Made sure you’re on the latest version: 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before: Yes

**Describe the Bug:**

When we add a new item to the RUCSS CSS safelist field (after initial RUCSS execution), it appears the affected RUCSS table is not being regenerated. That is, there is no visual indicator (e.g., green progress bar) confirming that the new RUCSS CSS safelist item has been processed.

**Steps to Reproduce:**

(1) Click on (activate) "Remove Unused CSS (Beta)" 
(2) Add two or three items to the CSS safelist field.
(3) Click on "SAVE CHANGES" (a green progress bar will appear, wait for process to complete)
(4) After initial, successful RUCSS execution, add another item to the CSS safelist field.
(5) Click on "SAVE CHANGES" (nothing happens, there is no green progress bar indicating new item has been processed, all we see is "Settings saved" at the top of our dashboard)

**Expected Behavior:**

Every time we add a new RUCSS CSS safelist item (after initial RUCSS execution), there should be a visual indicator confirming the new RUCSS safelist item has been processed. 

For example, a green progress bar and/or messages like "Processing new safelist item" followed by "New safelist item successfully processed" should be displayed.

**Screenshots:**

<a href="https://ibb.co/h7P39zZ"><img src="https://i.ibb.co/tm7VKrx/rucss-table-not-regenerating.png" alt="rucss-table-not-regenerating" border="0"></a>

**Comment by GeekPress** [comment]
This is normal behavior. We don't need to re-parse your files and to re-do the pre-warmup process.
