### ISSUE TITLE
Re-Opening GitHub Issue #4196 (RUCCS CSS Safelist Re-Parsing)

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4197]
**Reference:** https://github.com/wp-media/wp-rocket/issues/4196

Reference issue was closed by WP Rocket without giving originator an opportunity to comment.

**Comment:**

If CSS safelist item re-parsing is not required, then please update your KB to explain better what happens when a new CSS safelist item is added after initial RUCSS run or execution.

**Additionally (Questions):** 

(1) Does the added safelist item get processed immediately - or - does it happen during next RUCSS cron?
(2) Do we need to clear all cache after adding a new CSS safelist item?

Thank you!

PS: Recommend not being so "trigger-happy" closing GitHub issues without giving originators (many times paying customers) a chance to understand better WP Rocket's DevOps analogy.

**Comment by GeekPress** [comment]
@Jetxpert  You aren't using Github for the good reason. This is NOT where you are getting support.

Please ask all these questions by opening a ticket from here: https://wp-rocket.me./support/
