### ISSUE TITLE
Strange bug with RUCSS only on category main pages

### ISSUE THREAD

**Issue by pgirzalsky** [wp-media/wp-rocket#4200]
When activating the "remove unused CSS" feature, I get a strange bug on my website.
All urls work fine and are displayed correctly, except for the main pages of the WooCommerce shop categories. 

The subcategories are displayed correctly as you can see here:
https://www-staging.lendis.io/bueroausstattung/bueroeinrichtung/telefonboxen/

But the main categories are somehow broken:
https://www-staging.lendis.io/bueroausstattung/bueroeinrichtung/

The elements are exactly the same, even the footer and call to action section are broken. It seems like that url causes a bug.

**Comment by GeekPress** [comment]
@pgirzalsky Hi, please open ticket support from here: https://wp-rocket.me/support/

One of our support engineer will have a look to your problem.
