### ISSUE TITLE
Regenerate CPCSS for specific CPT or Taxonomies without having to regenerate CPCSS for everything

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4201]
**Is your feature request related to a problem? Please describe.**

When there are a lot of items to generate CPCSS for, some items might fail randomly on the generation process and show the following error: 

> **An error prevents the generator from retrieving its contents.**

Potential causes could be rate-limiting on firewalls or server overloads when multiple uncached pages are checked on a short interval.

The main issue is that when re-generating the CPCSS, different items will fail. Getting CPCSS generated for all items successfully might never happen.

**Describe the solution you'd like**

It will be hard to accommodate CPCSS for each scenario. 

One of the following can cover most cases where CPCSS fails to be generated randomly on or more items: 

- Re-generating CPCSS for failed items on the background. 
- Have a link to trigger CPCSS generation for each failed item on the CPCSS progress window (to be manually clicked to attempt regenerating CPCSS). 

**Describe alternatives you've considered**
N/A

**Additional context**
Related ticket - https://secure.helpscout.net/conversation/1579117317/282095
Slack discussion - https://wp-media.slack.com/archives/C08N8J6VC/p1627380366027800

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
