### ISSUE TITLE
Option to Enable/Disable WP-Rocket Caching for Managed hosting like DreamPress

### ISSUE THREAD

**Issue by sarangsss29** [wp-media/wp-rocket#4203]
WP-Rocket automatically disables caching feature when it runs on DreamPress. It comes under the Hosting Compatibility feature (https://docs.wp-rocket.me/article/670-hosting-compatibility). 
I can understand this is because DreamPress has Server Side Caching (Varnish caching). So it makes sense that WP-Rocket has its caching turned off. It works great if not using Cloudflare Cache Everything Page Rule or APO.

However, while using Cloudflare Cache Everything Page Rule or APO, DreamPress' varnish caching breaks and is always MISS. Meaning server caching is not working.

**Describe the solution you'd like**
This is where the WP-Rocket Caching could benefit.
I propose giving the option to enable/disable WP-Rocket Caching in situations like this. I would like to test if in this specific scenario whether WP-Rocket Caching would benefit or not. I think it will.

Something like you have for the Flywheel hosting:
https://docs.wp-rocket.me/article/670-hosting-compatibility#flywheel

**Describe alternatives you've considered**
Make a plugin/addon that would remove or override the Hosting Compatibility feature. For advanced users.

**Additional context**
CF Cache Everything Page Rule or APO is very popular. Many users are implementing this. I think this could benefit many.

**Comment by sarangsss29** [comment]
Any update on this?

**Comment by iCaspar** [comment]
@GeekPress @Tabrisrp -- just a bump here for when you get back.

**Comment by GeekPress** [comment]
@sarangsss29 Adding an option to disable/enable our caching feature isn't something we plan to have. It's a decision we took since the first version and we won't change it.

By the way, your problem should be fixed by your hosting. You are looking for another solution to cache your website, when this could be fixed by your hosting ;)
