### ISSUE TITLE
htaccess - Add expiration rules for the avif image format

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4206]
**Is your feature request related to a problem? Please describe.**

Currently, we don't add expiration rules for the `image/avif` MIME type:
https://github.com/wp-media/wp-rocket/blob/f3d047fe745660805b96bcb9e0e927527a664a9d/inc/functions/htaccess.php#L455-L463

**Describe the solution you'd like**

Add rules for `image/avif`:
```
ExpiresByType image/avif                     "access plus 4 months"
```

**Additional context**

I saw the recommendation for this MIME type in a PageSpeed Insights test:

![](https://i.vgy.me/uh8BG2.jpg)

**Related ticket:** https://secure.helpscout.net/conversation/1585693109/283664?folderId=2135277

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `ExpiresByType image/avif                     "access plus 4 months"` to `get_rocket_htaccess_mod_expires()`

### Estimate the effort ✅
Effort `[XS]`
