### ISSUE TITLE
Include new rewrite rules in htaccess for query string caching

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4208]
**Is your feature request related to a problem? Please describe.**
When WP Rocket uses query string caching, the .htaccess rewrite rules do not change. This means that every request for a cached query string still has to trigger PHP (advanced-cache.php) to find the file. 

**Describe the solution you'd like**
Include new rewrite rules that will work with query string caching in htaccess

Ticket: https://secure.helpscout.net/conversation/1570320580/279292?folderId=1213662

**Comment by GeekPress** [comment]
@WordPresseur It's not a big deal to load the cached page from advanced-cached.php and the impact on the loading time should be ridiculous.

@Tabrisrp What do you think?

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1609005383/289230/

**Comment by remyperona** [comment]
I agree, and matching against query string in the htaccess would be adding a lot of complexity for a very small performance gain

**Comment by GeekPress** [comment]
Thanks, @Tabrisrp for your feedback. I'm closing the issue as we won't fix it.
