### ISSUE TITLE
Last-modified not always sent if htaccess rules don't exist

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#421]
JB helped me with a ticket and in the process discovered some things about the last-modified handling: 
1. In process.php we only send the last-modified the first time the cache file is created.
2. Htaccess rules are needed after that so the server can directly access the cache file and send the last-modified. 

So, if you activate the mobile sub-option and our rules are removed, you won't get the last modified (unless your visit to the page is the one that generates the cache file).

Is there a way we can send the last-modified via process.php even if the cache file already exists?

**Comment by arunbasillal** [comment]
It looks like this issue was already fixed here: https://github.com/wp-media/wp-rocket/commit/17cff2ba92c0dacb6706fa6fdbf4477ae60412fd

@Tabrisrp Will leave it up to you to close the issue when you see fit.

**Comment by Tabrisrp** [comment]
Indeed, I forgot about it
