### ISSUE TITLE
Incorrect relative URLs in Used CSS

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4210]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
The Used CSS seems to not rewrite all relative URLs.

Here the default CSS before to be processed by RUCCS:

`.wpex-site-overlay.wpex-active{cursor:url(assets/cursors/close.ico),default;cursor:-webkit-image-set(url(assets/cursors/close.ico) 1x,url(assets/cursors/close2x.ico) 2x);opacity:1;visibility:visible}`

For example, look in the file https://wp-staging-wtz21g6jwc.pairsite.com/wp-content/cache/used-css/1/blog/keys-to-a-successful-marketing-strategy/used.min.css?ver=1626284727

Note the two relative URLs in yellow:
![Screenshot](https://p195.p4.n0.cdn.getcloudapp.com/items/bLuq1bGz/29980368-5602-4a12-ae28-b61a22707540.png)

We can notice that 2 of 3 relative URLs haven't been updated.

The browser will try to load these incorrect files:
![Screenshot](https://p195.p4.n0.cdn.getcloudapp.com/items/8Lu52NyK/ae043f14-f834-4423-aa2f-2145b4433924.png)

**Expected behavior**
All relative URLs must be correctly rewritten.

**Additional context**
https://secure.helpscout.net/conversation/1571732618/279745?folderId=273768

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :heavy_multiplication_x: 
i can see the problem

### Identify the root cause ✅ 
the regex in CSS Minify that finds "url " in css bails out after it finds the first "url()"

### Scope a solution ✅ 
we need to add 'g' at line 154
`/ixg',`

https://github.com/wp-media/wp-rocket/blob/10461309b8a77102d5069beb31cca7130ad3f997/inc/Dependencies/Minify/CSS.php#L116-L155


### Estimate the effort ✅
need to be tested
Effort `[S]`

**Comment by remyperona** [comment]
This doesn't seem to come from the minification, when testing the CSS sample and minifying it, all the paths are rewritten correctly. 

I think this needs further investigation to determine the root cause of the issue.

**Comment by DahmaniAdame** [comment]
~~Related - https://secure.helpscout.net/conversation/1783623979/325298/~~

Not related to this one. Created a separate issue for it.

@mostafa-hisham your fix should work for this specific case 😅

**Comment by piotrbak** [comment]
Working correctly in the new approach.
