### ISSUE TITLE
RUCSS progress bar isnot displayed when switch theme (odd order)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4213]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before => yes 

**Describe the bug**
Progress bar of RUCSS is not displayed if switched the theme while having values in safelist

**To Reproduce**
- RUCSS is enabled   => RUCSS is completed and the progress bar was displayed

1. Switch theme
2. Open WPR settings=> File Optimization
3. RUCSS is still completed while it's processing in the background

**Expected behavior**
The progress bar is displayed whenever we switch theme
**Screenshots**

https://user-images.githubusercontent.com/76941962/127634062-f4e254c4-4aab-4304-a425-5418a893cbd4.mp4

**Additional context**
- When re-enable the RUCSS option => progress bar will be displayed normally
- Switching the theme again after step 3 will result in displaying the progress bar normally, but if we repeated the switch again it won't work (so 1st switch does not display bar, 2nd switch display bar, 3rd switch does not display bar, 4th switch display bar ....etc)
- the current behavior with/without safelist

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is fixed in 3.11 as we are not using the warmup process anymore.
