### ISSUE TITLE
Afterpay external script breaks if minified

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4214]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the following script is minified (and hosted) - `https://js.afterpay.com/afterpay-1.x.js` - it produces the following error: 

![image](https://user-images.githubusercontent.com/1289174/127736049-7a7caacc-d288-44cc-a07c-9a34bd531760.png)

**To Reproduce**
1. Add https://js.afterpay.com/afterpay-1.x.js using a plugin like Afterpay Gateway for WooCommerce exclusion
2. Enable JS minification
3. See error

**Expected behavior**
Afterpay should work properly when used.

**Screenshots**
Attached above.

**Additional context**
Excluding `js.afterpay.com` from minification fixes the issue.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
Please add this one also 

Plugin: https://wordpress.org/plugins/enable-accessibility/
same for `cdn.enable.co.il/licenses/enable-*/init.js'

Error: nginx error returned if minified

solved also by adding `cdn.enable.co.il` on exclude list.

**Comment by Mai-Saad** [comment]
Could reproduce the issue on 3.9.1.1 if added `<script type='text/javascript' src=' https://js.afterpay.com/afterpay-1.x.js'></script>` to test template i.e here https://new.rocketlabsqa.ovh/minify-js-template-001/

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `js.afterpay.com` as a pattern to the defaults exclusion array in AbstractJSOptimization::get_excluded_external_file_path()

### Estimate the effort ✅
Effort `[XS]`
