### ISSUE TITLE
Add preloaded fonts before CPCSS and RUCSS to avoid FOUTs

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4215]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In some cases, the font declaration comes a bit late in the style. As a result, CSS generated by CPCSS or RUCSS will start painting the page causing a FOUT. 

The FOUT can't be avoided by using our preload fonts feature as the inline CPCSS and RUCSS will come before the preload fonts are processed by the browser. 

**To Reproduce**
1. Declare fonts at the middle of CSS file
2. Use CPCSS or RUCSS
3. See the FOUC

Make sure to use a network throttling to 3G to see the FOUT. 

**Expected behavior**
There shouldn't be any FOUT when using RUCSS or CPCSS.

A potential fix is to move font-face declarations on RUCSS and CPCSS to the beginning of the inline style. 

Another alternative is to add the `<link rel=preload>` fonts before RUCSS and CPCSS styles.

**Screenshots**
N/A

**Additional context**
Slack discussion - https://app.slack.com/client/T02RYMVKQ/C08N8J6VC/thread/C02RYMVLU-1627725766.110500
We are already doing something similar for Google Fonts when RUCSS is generated - https://github.com/wp-media/wp-rocket/issues/2772

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Removing the `Remove Unused CSS` label as this is handled in 3.11

**Comment by piotrbak** [comment]
We can use `</title>` like we do for Preload Fonts in the RUCSS

**Comment by CrochetFeve0251** [comment]
## Scope a solution
To solve this we need to change the logic from the [Preload subscriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Fonts.php).

For that we will have to change the event we subscribe from `wp_head` to `rocket_buffer` and change the [`preload_fonts` method](https://github.com/wp-media/wp-rocket/blob/60b76bc8bc9a366bf5b9644894df8203bba103fd/inc/Engine/Preload/Fonts.php#L81) to that logic:
```php
public function preload_fonts($html) {
		if ( ! $this->is_allowed() ) {
			return $html;
		}

		$fonts = $this->options->get( 'preload_fonts', [] );
		/**
		 * Filters the list of fonts to preload
		 *
		 * @since 3.6
		 *
		 * @param array $fonts Array of fonts paths.
		 */
		$fonts = (array) apply_filters( 'rocket_preload_fonts', $fonts );
		$fonts = array_map( [ $this, 'sanitize_font' ], $fonts );
		$fonts = array_filter( $fonts );

		if ( empty( $fonts ) ) {
			return $html;
		}

		$base_url = get_rocket_parse_url( home_url() );
		$base_url = "{$base_url['scheme']}://{$base_url['host']}";

		$preloads = '</title>';

		foreach ( array_unique( $fonts ) as $font ) {
			$preloads .= sprintf(
				"\n<link rel=\"preload\" as=\"font\" href=\"%s\" crossorigin>",
				esc_url( $this->cdn->rewrite_url( $base_url . $font ) )
			);
		}

		return str_replace('</title>', $preloads, $html);
	}
```

## Estimate the effort
Effort `S`
