### ISSUE TITLE
WP Rocket Delay JS breaks Elementor sticky header when there is a top bar above it.

### ISSUE THREAD

**Issue by oliveandlake** [wp-media/wp-rocket#4216]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Sticky headers work fine without a top bar present. But don't work when there is a top bar present. 

**To Reproduce**
Create a sticky header with a top bar above it. 

**Expected behavior**
Header should be sticky always. 

**Screenshots**
Here's a video. 

https://www.loom.com/share/5e3cc1322e0740c183932ca4e0286e1b

**Additional context**
Happens on all sites I have with a top bar above the sticky header. Where there is no top bar, it works as expected. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by aviranbiz** [comment]
+1

**Comment by testAccount7558998** [comment]
I'm experiencing the exact same issue. I have a small pre-header section that is not sticky & the sticky header below. 
The sticky header never works as expected when delay js is activated. The only solution I found is to add jquery & Elementor Pro js files to the exclusion list of Delay JS, but it now loads many unuseful JS files because of Elementor... The delay Js feature is not useful anymore with this solution.

**Comment by oliveandlake** [comment]
I'm glad it's not just me! It happens on all websites I have with a top bar. I did reach out to WP Rocket's support. But their suggestion was to exclude the Elementor files which defeats the point of using Delay JS.

**Comment by mehedihasanziku** [comment]
**More observation:**

If top bar added, sticky works sometimes, but it doesn't works as expected.

**Normal action:** like after scroll it's adding some inline styles **(position:fixed)** on sticky section, after reached to top it removes that style attribute value. 
**Buggy action**: When sticky works that time it doesn't remove that style attribute value when reach to top. this cause non-sticky layout broken.

Looks like some issue with scroll events.

**Note:** Delay JS Tested with Zero Exclusion

**Reference:** This issue not visible with **WP-Meteor**

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1730493439/314856/
Issue seems to only happen when there is no exclusions.
Issue is fixed after using [Elementor's exclusions](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#elementor-pro).

**Comment by mehedihasanziku** [comment]
Dom Visualization: ![ezgif-1-cd1d1cdfb3](https://user-images.githubusercontent.com/48652123/160350029-ceff39aa-0b35-4412-9926-ae9526d5fcf1.gif)

This is what exactly happening in dom with elementor sticky and topbar. This working perfectly with competitor feature Permatters, here still this bug has no update.

Excluding is not a solution. it should work like works in competitor feature.

**Comment by piotrbak** [comment]
It should be fixed in 3.13.1:
https://github.com/wp-media/wp-rocket/issues/5811

**Comment by davronakil** [comment]
Facing this issue with the latest version of everything. Added all the necessary exclusions to WP Rocket. Let me know if I missed anything: 


<img width="841" alt="image" src="https://github.com/wp-media/wp-rocket/assets/3535504/01141375-bb93-4b20-9608-46cc7372053c">

**Comment by ahmedelakkad** [comment]
Same here!

**Comment by piotrbak** [comment]
@ahmedelakkad Please reach our Support Team to see what's going on.
