### ISSUE TITLE
Combine Google fonts - Allow to filter the display attribute

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4219]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

We used to allow the filtering of the `display` attribute when combining Google fonts using the `rocket_combined_google_fonts_display` filter in the `get_font_display_value()` method:
https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/GoogleFonts/AbstractGFOptimization.php#L90-L106

Now we are hardcoding `display=swap` for:
* [Combine Google fonts v1](https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/GoogleFonts/Combine.php#L142)
* [Combine Google fonts v2](https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/GoogleFonts/CombineV2.php#L133)

**To Reproduce**

No need to. It's evident in the code.

**Expected behavior**

We should offer the ability to filter the `display` attribute.

**Additional context**

**Slack conversation:** https://wp-media.slack.com/archives/C43T1AYMQ/p1627696817002900

Props to @webtrainingwheels @girlie.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :heavy_multiplication_x:  
No need to

### Identify the root cause ✅ 
We should offer the ability to filter the `display` attribute.

### Scope a solution ✅ 
edit `get_combined_url` in Both 
* [Combine Google fonts v1](https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/GoogleFonts/Combine.php#L142)
* [Combine Google fonts v2](https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/GoogleFonts/CombineV2.php#L133)
call `get_font_display_value` function first to apply the "rocket_combined_google_fonts_display" filter first

```
private function get_combined_url(): string {
$fonts_display = $this->get_font_display_value();
		return esc_url( ".......&display={$fonts_display}" );
}
```

update unit and integration tests

### Estimate the effort ✅
Effort `[S]`

**Comment by mifrero** [comment]
Related ticket: https://secure.helpscout.net/conversation/1696588582/307830?folderId=2952229

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1586175047/283845/

**Comment by webtrainingwheels** [comment]
- https://secure.helpscout.net/conversation/1596432385/286450/
- https://secure.helpscout.net/conversation/1584764071/283486/

**Comment by luckyankit** [comment]
You know it would be way better to give users a choice if they want to swap or not. You guys seriously are against providing options to fine-tune settings!

**Comment by piotrbak** [comment]
Hello @akkiverma Since 3.10.5 version you can use this filter to change the value of the `font-display`:
https://docs.wp-rocket.me/article/1312-optimize-google-fonts#changing-display-attribute

**Comment by luckyankit** [comment]
How about giving an option on main plugin only like Litespeed does. These hacks are temporary solutions and such practice should be strongly discouraged as you might change the decision again. Then no one has time to follow up updates and remove the code in the future if that becomes obsolete. Let's do better and stick to the main plugin on providing the options!

**Comment by GeekPress** [comment]
@akkiverma For this kind of advanced configuration, we prefer to use a filter, and not an option. We are strongly following the WordPress philosophy: « Decision, not option »

Here, we are making the decision to set the default value for our users. Most of them know nothing about web performance and rely on us to configure it properly without worrying about anything on their side. 

For advanced users like you, a filter is available.

**Comment by luckyankit** [comment]
Yes, hide those features behind an advanced toggle. That is way better decision.

**Comment by GeekPress** [comment]
> Yes, hide those features behind an advanced toggle. That is way better decision.

I'm not talking about and advanced toggle, but a WordPress hook (filter) ^^
