### ISSUE TITLE
The progress bar sometimes gets stuck until the page refresh

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4222]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling the RUCSS, the progress bar sometimes gets stuck at 100%. After the refresh it's being replaced by the confirmation that RUCSS is enabled.

The numbers of resources are not matching usually, for example:
1. The progress bar stopped at 86/85 resources, but nothing in the warm up
2. After refreshing the page, 2 requests to `_locale` were made, and the resources went to 91/91 and the process was finished

**To Reproduce**
1. Enable RUCSS and wait
2. If the error is not present, disable the RUCSS
3. Repeat the steps 1 and 2 until you experience the problem (it's happening pretty often on our RocketLabs)

**Expected behavior**
We should guard against this

**Screenshots**
86/85 with no `notwarmedup`
![image](https://user-images.githubusercontent.com/26767037/128011592-e5a64e8c-8054-43f7-9ccc-1bf14be51e8d.png)

The video:
https://jmp.sh/U38WJxE

**Additional context**
On the other scenario I can see that we reach 41/41 resources in the request call that's before the last one:
![image](https://user-images.githubusercontent.com/26767037/128017024-2d44045e-3cc2-4fd5-9a19-0e86275bd34e.png)

And then we make another call that shows us 42/41 there's a `notwarmedup` resource, but new requests are not being made:
![image](https://user-images.githubusercontent.com/26767037/128017145-1630e4c7-f472-4f01-9d6c-3bc8024970a0.png)

After refresh the problem is reseolved too

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1704129790/309327/

**Comment by piotrbak** [comment]
Fixed in 3.11, warmup is not used anymore.
