### ISSUE TITLE
3.9.1.1 - Delay JS exclusions for WooCommerce cause issues on Avada

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4224]
**Describe the bug**
On a site using Avada, updating from 3.9.0.5  → 3.9.1.1 breaks the layout of the WooCommerce product pages due to the changes here: https://github.com/wp-media/wp-rocket/issues/4077

When using 3.9.0.5 the customer had no exclusions for Delay JS and there were no issues (images displayed correctly on interaction) and no console errors. 

After updating to 3.9.1.1 the images are displayed vertically at full size instead of thumbnails: 
http://recordit.co/954umFKZ10
Correct display should be: https://jmp.sh/4moYhbK

This can be corrected by excluding the following files: 
/wp-content/themes/Avada/assets/min/js/general/avada-woo-product-images.js
/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.flexslider.js

BUT then this leads to jquery errors on other pages where previously there were none.

**Expected behavior**
Updating the plugin should not break the layout or require further exclusions. 

**Additional context**

- Customer in this case is on a multisite. 
- Theme is Avada
- Issue can be seen on customer's staging site, found in my note here: 
https://secure.helpscout.net/conversation/1586750255/283985?folderId=377611#thread-4632327399

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
I have revisited the issue on this customer's site, and the following scripts had to be excluded for the woocommerce product gallery to work:
```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/jquery-migrate(.min)?.js
/themes/Avada/assets/min/js/general/avada-woo-product-images.js
/themes/Avada/includes/lib/assets/min/js/library/jquery.flexslider.js
```

The above caused jQuery error for the Slider Revolution script, so additionally, the following were added to resolve the error:
```
/revslider/public/assets/js/
setREVStartSize
rev_slider_
revslider_
window.RS_MODULES

```
Ref.: https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#revolution-slider

There is additional JS optimization on the site with _Autoptimize_ and _Async JavaScript_ plugin. It it yet unclear if it has impact on the issue or not. Will update if tested.

**Comment by NataliaDrause** [comment]
I confirmed that additional optimization with _Autoptimize_ and _Async JavaScript_ plugins on the site did not have any impact on the issue.
The issue is present even when these plugins are deactivated.

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1646209049/298042/
Didn't notice any other errors after doing the exclusions.

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on https://rocketlabsqa.ovh/product/logo-collection/

### Identify the root cause ✅ 
The following files need to be excluded from delay JS execution to have the correct display:
```
/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.flexslider.js
/wp-content/themes/Avada/assets/min/js/general/avada-woo-product-images.js
```

### Scope a solution ✅ 
In our Avada compatibility file, we can add a new method `delay_js_exclusions()` to add those 2 files to the exclusions array. The method needs to be hooked on the `rocket_delay_js_exclusions` filter.

Add unit/integration tests for the new method.

### Estimate the effort ✅
Effort `[XS]`
