### ISSUE TITLE
Microsoft IIS - Azure - cache folders aren't recreated after deletion of the root cache folder

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4225]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On a Microsoft server (IIS) on Azure, the cache path isn't recreated once the root cache folder, e.g. `/cache/wp-rocket/www.example.com` is deleted. This fails here:
https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/classes/Buffer/class-cache.php#L275

Because of this, the following will not be created:
```
D:\home\site\wwwroot\wp-content\cache\wp-rocket\www.example.com\digitale-transformation
```
This **prevents page caching from working** since we cannot write to the disk. **Optimizations work fine**.

With @Tabrisrp's guidance, I found that using `wp_mkdir_p()` also isn't working when trying to create a folder in that kind of path (more in the [Slack convo](https://wp-media.slack.com/archives/C43T1AYMQ/p1627995172003100?thread_ts=1627562896.017600&cid=C43T1AYMQ)). 

This is related to the way [mkdir()](https://www.php.net/manual/en/function.mkdir.php) works. When using it to create a folder, whose parent folders don't exist, the 3rd argument `$recursive` of the function has to be `true`. In this case, the 2nd argument, ` $permissions` also has to be passed. It seems that on Azure (IIS) the latter doesn't exist in the expected format.

**To Reproduce**

1. Create a site on an IIS Azure server.
2. Delete the root cache folder, e.g. `/cache/wp-rocket/www.example.com`
3. Visit a page on the front end.
4. Check the `/wp-content/cache/wp-rocket` folder .The root cache folder won't be there.

**Expected behavior**

Folders should be created automatically the way this works on Linux servers.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1583373050/283180?folderId=2135277
**Slack conversation:** https://wp-media.slack.com/archives/C43T1AYMQ/p1627562896017600

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
