### ISSUE TITLE
JavaScript minification - Exclude enable.co.il JS to prevent JS error

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4227]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Saving locally the following external JavaScript file:
`cdn.enable.co.il/licenses/enable-###############-####-#####/init.js`
 causes a console error:
![https://i.vgy.me/KrOQhC.jpg](https://i.vgy.me/KrOQhC.jpg)
The following should be excluded from JavaScript minification:
`cdn.enable.co.il/licenses/enable-`

**To Reproduce**

Not relevant.

**Expected behavior**

No JavaScript error should take place when including the `enable.co.il` script.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1588412372/284343

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `cdn.enable.co.il/licenses/enable-` as a pattern to the defaults exclusion array in AbstractJSOptimization::get_excluded_external_file_path()

### Estimate the effort ✅
Effort `[XS]`
