### ISSUE TITLE
RUCSS - RGBA/RGB CSS Function Broken

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4228]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
> Case 1: 
```
.selector-a{
      -webkit-box-shadow: 0 1px 6px 0 rgb(0 0 0 / 18%);
      box-shadow: 0 1px 6px 0 rgb(0 0 0 / 18%);
}
```
> Case 2:
```
.selector-b{
	-webkit-box-shadow: 0 1px 6px 0 rgba(0, 0, 0, 0.18);
	box-shadow: 0 1px 6px 0 rgba(0, 0, 0, 0.18);
}
```

In Case 1: It's removed only shadow part [with safelist selector]
In Case 2: It's preserved the shadow [with safelist selector]

in both cases output should be `box-shadow: 0 1px 6px 0 rgb(0 0 0 / 18%); `

now case 1 should be fixed.

**To Reproduce**
1. Enable RUCSS

**Expected behavior**
In both cases output should be `box-shadow: 0 1px 6px 0 rgb(0 0 0 / 18%); `

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
another in Elementor Gradient CSS, this is an serious issue with rucss

1. `background-image: linear-gradient(to bottom, rgb(215,238,241) 0%, rgb(228, 251, 255) 60%, rgb(184, 222, 226) 100%);`

2. `background-image: linear-gradient(to bottom, rgb(215,238,241) 0%, rgb(228 251 255) 60%, rgb(184 222 226) 100%);`



![image](https://user-images.githubusercontent.com/48652123/128537445-9a9c46bd-88b8-49b4-bd2d-f7137ea345ac.png)

**Comment by Mai-Saad** [comment]
We need to handle this format:
`rgb[a](R G B[ / A])` https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

Notes: 
- For case 1 in the main issue, I think it shall be rgba not rgb as rgb is 3 level not 4

**Comment by vmanthos** [comment]
I came across another issue with `rgb()`, where if transparency is included the rule is not processed, and the parser removes the property.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb()) `rgb()` supports transparency.
This is for [CSS4](https://www.w3.org/TR/css-color-4/).

For example:
```CSS
.my-class{background-color:rgb(28,63,80,.85);}
```

The transparency is working only if `rgba()` is used:
```CSS
.my-class{background-color:rgba(28,63,80,.85);}
```

**Ticket:** https://secure.helpscout.net/conversation/1578363776/281843?folderId=2135277

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1605837928/288521/

This rule wasn't included:
```
.cta-home {
    background: linear-gradient(0deg, rgb(248 248 248) 59%, rgba(253,244,237,0) 60%);
}
```

I added the following rule instead:
```
.cta-home {
    background: linear-gradient(0deg, rgb(248, 248, 248) 59%, rgba(253,244,237,0) 60%);
}
```

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
produce it locally
### Identify the root cause ✅ 
The CSS parser does not support rgb() with transparency.
also if use spaces to separate rgb or rgba values 
### Scope a solution ✅ 
In css-parser, before parsing the CSS tokens we need to 
- replace the spaces with commas.
- replace rgb with rgba if it has transparent (4 values).

in CSSProcessor we can use these 2 functions
```
    private function fixRgbWithOpacity(){
        $pattern = '/rgba?\(\s*(-?\d+|-?\d*\.\d+(?=%))(%?)\s*(,| )\s*(-?\d+|-?\d*\.\d+(?=%))(\2)\s*(,| )\s*(-?\d+|-?\d*\.\d+(?=%))(\2)\s*(,| )\s*(-?\d+|-?\d*.\d+)\s*\)/';
        $replacmet = 'rgba($1,$4,$7,$10)';
        $this->content = preg_replace($pattern, $replacmet, $this->content);
    }

    private function fixRgbWithSpaces(){

        $pattern = '/rgb\(\s*(-?\d+|-?\d*\.\d+(?=%))(%?)\s*(,| )\s*(-?\d+|-?\d*\.\d+(?=%))(\2)\s*(,| )\s*(-?\d+|-?\d*.\d+)\s*\)/';
        $replacmet = 'rgb($1,$4,$7)';
        $this->content = preg_replace($pattern, $replacmet, $this->content);
    }
```
and use them in createValidatedCssDocument function to fix the rgb
https://github.com/wp-media/css-parser/blob/ba3c21ab918bb95bae631f53698f744129a66213/app/Services/CSSProcessor.php#L437

NOTE: I think this issue should be in [css-parser repo](https://github.com/wp-media/css-parser) 
### Estimate the effort ✅
Effort `[S]`

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1620412386/292073/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1671873794/303366/

**Comment by remyperona** [comment]
An update has been released to the RUCSS service to better handle those rgb() and rgba() notations cases. It should fix most of the issues related to it.

**Comment by mehedihasanziku** [comment]
I tested this issue right now by regenerating rucss. now it's triggering another issue related to it

Current CSS: `background-color: rgba(17, 17, 17, 1);` and it's removed after rucss available.
This issue was not here i think, looks like this thread fixes causing that issue.

**Comment by mehedihasanziku** [comment]
> Current CSS: `background-color: rgba(17, 17, 17, 1);` and it's removed after rucss available. This issue was not here i think, looks like this thread fixes causing that issue.


In RUCSS Available :  `background-color: rgba(17,17,17,0.2);`
But previous scenario not available.

**Comment by piotrbak** [comment]
@mehedihasanziku We already have an open issue for this:
https://github.com/wp-media/wp-rocket/issues/4463

It seems that `1` or at least integer at this position might break our regex

**Comment by mehedihasanziku** [comment]
> @mehedihasanziku We already have an open issue for this: #4463

I saw some opened thread, but there mentioned specific `linear-gradient()` , so i thought let's report here.
Thanks.

**Comment by NataliaDrause** [comment]
I have a related issue after the update:

This rule is not processed:
`background-color: rgba(0,0,0,1);`

I replaced it with this one which resolved the problem:
`background-color: rgba(0,0,0);`

Ticket: https://secure.helpscout.net/conversation/1683499202/305164/

@piotrbak could you please take a look if this has to be reported somewhere else, since we have some maybe related issues (e.g. linear-gradient) opened already.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1692715745/307001/

The following was removed: 

```
box-shadow: 1px 1px 3px 0px rgb(2 2 2 / 0%);
background-color: rgba( 27, 154, 170, 1.00 );
```
