### ISSUE TITLE
JS minification exclusion isn't working when an external URL contains the site's TLD

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4231]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On a site, e.g. `www.example.com`, when an external JavaScript file's URL contains the site's TLD, e.g. in a query string, like so:
```HTML
<script type="text/javascript" src="https://tarteaucitron.io/load.js?locale=fr&iswordpress=true&domain=www.example.com&uuid=a334ff7567f29a1047ddb578baf4dc230689285d"></script>
```
WP Rocket is treating the file as internal, because of how we are checking it here:
https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/AbstractOptimization.php#L133

Because of this, if the customer wants to exclude the file, using `tarteaucitron.io/load.js` or `tarteaucitron.io` will not work. Instead, `/load.js` will.

**To Reproduce**

1. Use the script I added earlier, making sure the `domain` query string matches the TLD of the test site.
2. Add `https://tarteaucitron.io/load.js` to the JavaScript minification exclusion text area.
3. Check the source code of a page. The exclusion will not work, i.e. the file will be served from the local cache.

**Expected behavior**

Exclusions for such URLs should work the same with all external URLs.

**Additional context**

This is definitely an edge case, but I'm documenting it in case we want to deal with this.

**Ticket:** https://secure.helpscout.net/conversation/1584764409/283487/
**Slack conversation:** https://wp-media.slack.com/archives/C08N8J6VC/p1628096218053100

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
Related: https://secure.helpscout.net/conversation/1835816307/335417?folderId=273766

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1834843919/335254/

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/1835380625/335338?folderId=2135277

**Comment by CrochetFeve0251** [comment]
### Scope a solution
Problem come from the fact we check the url with its params on [this line](https://github.com/wp-media/wp-rocket/blob/7bc0dd8dcc0ef5e2af156d978c8a437ec8bb1bd1/inc/Engine/Optimization/AbstractOptimization.php#L133).

A solution would be to apply `strtok($url, '?')` on the url before the check to remove params and preventing a match with them.

### Estimate effort
Effort `XS`
