### ISSUE TITLE
Notice when the "AMP Takeover" is enabled (AMP for WP plugin)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4233]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the `AMP Takeover (Beta)" feature is enabled, it will force AMP for all page, and consequently, none of our optimizations will be applied. 

![image](https://user-images.githubusercontent.com/1289174/128594093-12603d95-2656-47a9-aab9-09959423646f.png)

The cache is properly cached and served from the cache.

**To Reproduce**
1. Install and activate AMP for WP
2. Enable `AMP Takeover`
3. Check the source code to see that none of our optimizations are applied

**Expected behavior**
Show a notice that optimization won't be applied if that particular feature is enabled.

**Screenshots**
Added on the description.

**Additional context**
The `AMP Takeoever` is the equivalent of the `Standard Mode` on the official AMP plugin - https://github.com/wp-media/wp-rocket/issues/3894
Can be part of the AMP for WP plugin compatibility effort - https://github.com/wp-media/wp-rocket/issues/2498

Ticket - https://secure.helpscout.net/conversation/1579117317/282095/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
