### ISSUE TITLE
When HTML minified is enabled, feeds won't validate

### ISSUE THREAD

**Issue by ronilaukkarinen** [wp-media/wp-rocket#424]
Hello, noticed today that my PHP feed reader won't display any posts when WP Rocket HTML minify is enabled on the site:

````
DOMDocument::load(): Extra content at the end of the document in https://test.dev/feed/, line: 1
````

Ticking off HTML minify restores feed functionality. There is no option to disable feed compression in 2.10-beta6. This should be improved.

**Comment by Tabrisrp** [comment]
Support question should be sent through our support form, not here.

Option was removed because you can easily disable the caching for feed by excluding the feed pattern URL /feed/(.*)

**Comment by ronilaukkarinen** [comment]
This wasn't exactly a support question... just thought it as a bug or unexpected behaviour as I couldn't find a mention in [the official changelog](https://wp-rocket.me/changelog/). You shouldn't remove a feature that bluntly without informing users about it. Not fun to notice these things when bugs happen because of unvalid feed. Thanks anyway.
