### ISSUE TITLE
Delay JS Execution prevents search engines from reading Mediavine's video schema

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4241]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Mediavine is adding a video schema like the following for their publishers who are running videos:
```Javascript
<script class="mediavine-video__ld-json" type="application/ld+json">{"@context":"https://schema.org","@id":"https://video.mediavine.com/videos/vhjhd087s4vdvjlorkae","@type":"VideoObject","contentUrl":"https://mediavine-res.cloudinary.com/video/upload/t_original/v1621439458/vhjhd087s4vdvjlorkae.mp4","description":"test","duration":"PT7S","keywords":"test","name":"Homemade Pesto Recipe","thumbnailUrl":["https://mediavine-res.cloudinary.com/image/upload/s--nRIdcqHi--/ar_16:9,c_fill,f_auto,fl_lossy,q_auto/v1626459236/oscshyf0thxmfqzv2wie.jpg","https://mediavine-res.cloudinary.com/image/upload/s--dtfsLUS5--/ar_4:3,c_fill,f_auto,fl_lossy,q_auto/v1626459236/oscshyf0thxmfqzv2wie.jpg","https://mediavine-res.cloudinary.com/image/upload/s--hxlskzXf--/ar_1:1,c_fill,f_auto,fl_lossy,q_auto/v1626459236/oscshyf0thxmfqzv2wie.jpg"],"uploadDate":"2021-05-19T00:00:00.000Z","hasPart":[{"@type":"Clip","name":"zero second","startOffset":0,"url":"https://support-sandbox.com/trellis-blocks-test/?mvs=0#mv-first-video"},{"@type":"Clip","name":"one second","startOffset":1,"url":"https://support-sandbox.com/trellis-blocks-test/?mvs=1#mv-first-video"},{"@type":"Clip","name":"two boi","startOffset":2,"url":"https://support-sandbox.com/trellis-blocks-test/?mvs=2#mv-first-video"},{"@type":"Clip","name":"three boi","startOffset":3,"url":"https://support-sandbox.com/trellis-blocks-test/?mvs=3#mv-first-video"}]}</script>
```

That's done by a script:
```HTML
<script type="text/javascript" async="async" data-noptimize="1" data-cfasync="false" src="//scripts.mediavine.com/tags/xxxxxxxxx.js"></script>
```
where the `xxxxxxxxx.js` part is site-specific.

When Delay JavaScript Execution is active, the schema is added for human visitors, but that's not accessible by search engines. That prevents its indexing.

Excluding the following:
`scripts.mediavine.com/tags/`

allows the schema to be added, and be accessible by search engines.

**To Reproduce**

Check the HelpScout note:
https://secure.helpscout.net/conversation/1587269410/284122/#thread-4654087353

**Expected behavior**

The schema should work even when the Delay JavaScript Execution feature is active.

**Additional context**

This was a conversation initiated from within Mediavine.

I asked if there is a way to detect video insertion, so we can selectively exclude the script from Delay JavaScript Execution, but it seems "there are a lot of different ways that a video can be embedded in a post". This in conjunction with issues related to Mediavine ads, probably makes it safer to permanently exclude the script.

**Ticket:** https://secure.helpscout.net/conversation/1587269410/284122/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Reproducible on test site using 

> Check the HelpScout note

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
The script should not be delayed to avoid this problem


### Scope a solution ✅ 
Add scripts.mediavine.com/tags/ as a pattern in the WP_Rocket\Engine\Optimization\DelayJS\HTML::$excluded array and add a the script to the fixtures to validate

### Estimate the effort ✅

Effort `[XS]`
