### ISSUE TITLE
Delay JS Execution - LearnDash LMS quizzes break

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4242]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

LearnDash LMS quizzes are not working when Delay JavaScript Execution is active.

The following JavaScript error appears in the console:

![](https://i.vgy.me/eLUJge.jpg)

The issue is fixed by excluding the following files from Delay JavaScript Execution:
```HTML
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/jquery-migrate(.min)?.js
/sfwd-lms/includes/lib/wp-pro-quiz/js/wpProQuiz_front.min.js
```

**To Reproduce**

I've added the HTML of a page including such a quiz in a HelpScout note:
https://secure.helpscout.net/conversation/1582460138/282932/#thread-4654706661

That can be used for a template.

**Expected behavior**

LD LMS Quizzes should work when the Delay JavaScript Execution is active.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1582460138/282932/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Note:
- Couldn't reproduce it on the test site.

**Comment by piotrbak** [comment]
The problem appears when the jQuery is excluded independently only.
