### ISSUE TITLE
RUCSS - PHP Notice:  Trying to get property 'id' of non-object in /RUCSS/Database/Queries/ResourcesQuery.php on line 144

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4243]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The following PHP notice appeared in the `debug.log`:
```
PHP Notice:  Trying to get property 'id' of non-object in /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/ResourcesQuery.php on line 144
```

This is taking place here:
https://github.com/wp-media/wp-rocket/blob/d1fc8854869892b4ec5c061f88af98e49c6e450d/inc/Engine/Optimization/RUCSS/Database/Queries/ResourcesQuery.php#L144

On the specific site, none of the discovered pages are scanned, so no resources are fetched, i.e. `wpr_rucss_resources` is empty while `$used_css->unprocessedcss` isn't.
https://github.com/wp-media/wp-rocket/blob/d1fc8854869892b4ec5c061f88af98e49c6e450d/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L226

**To Reproduce**

Blocking the scanning process should be the way to go, maybe by short-circuiting it here:
https://github.com/wp-media/wp-rocket/blob/d1fc8854869892b4ec5c061f88af98e49c6e450d/inc/Engine/Optimization/RUCSS/Warmup/ScannerProcess.php#L85-L93

**Expected behavior**

No notices should appear, even when none of the pages are scanned.

**Additional context**

We could bail out if `$db_row` isn't an object :
```PHP
if( ! is_object(  $db_row ) ){
return;
}
```
**Ticket:** https://secure.helpscout.net/conversation/1600151165/287220?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Identify the root cause ✅ 
We are not checking if the `$db_row` variable is an object before trying to use its properties.

### Scope a solution ✅ 
As noted in the OP, we should check if `$db_row` is an object, and bail-out if it isn't

### Estimate the effort ✅
Effort `[XS]`

**Comment by Mai-Saad** [comment]
Steps to reproduce:
1. Page of unprocessed RUCSS template
2. Enable RUCSS
3. Access the page template
4. Edit the entry in the used CSS file and set retries to 3 and edit the unprocessed URL to a non-existing resource URL
5. Delete the entry from the cache folder wp-rocket
6. Access the page template and check debug.log
Thanks to @engahmeds3ed
