### ISSUE TITLE
Optimize CSS Delivery New UI

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4245]
## What are we proposing to do? 

To build a new UI to merge Removed Unused CSS and Generate Critical Patch CSS under the same parent option: Optimize CSS Delivery.

[Full Doc](https://docs.google.com/document/d/1uZGKZIn9kfDWt5DrS-ar50j0ga5_zJY7xt-lFx_V1BU/edit?usp=sharing)

**Comment by mostafa-hisham** [comment]
@GeekPress @wp-media/php 
The second point in `Technical Specs` section is not very clear
what is the code that needs to be deprecated?
>RUCSS & CPCSS can’t be activated at the same time anymore. It means we could deprecate the code which is saving the Used CSS into a CSS.

**Comment by mostafa-hisham** [comment]
### Reproduce the issue 
New UI Enhancement Nothing to  Reproduce 

### Identify the root cause ✅ 
new UI to merge Removed Unused CSS and Generate Critical Patch CSS under the same parent option: Optimize CSS Delivery.
### Scope a solution ✅ 
1. Create a new field type (radio) and js to hide and show content based on what is selected
2. update `inc/Engine/Admin/Settings/Page.php` to use the new field in the new "optimize_css_delivery"
3. create a function to set the default value "optimize_css_delivery" value based on the old option that was used (RUSS or CPCSS)
4. remove the code that handles the case when RUCSS & CPCSS are enabled at the same time

@wp-media/php Can you check if there is anything else missing?

### Estimate the effort ✅
Effort `[L]`

**Comment by iCaspar** [comment]
On code that considers cpcss and rucss activated simultaneously:
See https://github.com/wp-media/wp-rocket/blob/9e9b3645d051ddd52b0eeb88ab0bbacf5e0ed515/inc/Engine/Optimization/RUCSS/Frontend/Subscriber.php#L69 
and 
https://github.com/wp-media/wp-rocket/blob/9e9b3645d051ddd52b0eeb88ab0bbacf5e0ed515/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L154

Based on `cpcss_enabled()` we make saving-in-filesystem decision at https://github.com/wp-media/wp-rocket/blob/9e9b3645d051ddd52b0eeb88ab0bbacf5e0ed515/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L600 and we modify used-css output at https://github.com/wp-media/wp-rocket/blob/9e9b3645d051ddd52b0eeb88ab0bbacf5e0ed515/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L652

In these cases, we can eliminate the branching as we can know that CPCSS is always disabled at that point.
 
We also need to think about:
Update/set the appropriate options when updating/installing, per
```
Existing users who use Optimize CSS delivery will have Load Asynchronously selected.
Existing users who use Remove Unused CSS will have Remove unused CSS selected.
Existing users who use both options will have Remove unused CSS selected. It means we will automatically deactivate the CPCSS on their website.
First time users and new installs will default to Remove unused CSS.
```
This should happen in `inc/admin/upgrader.php`:
* First install options array (L:175)
* New version compare with version this will take effect in the `rocket_new_upgrade()` method.

Introducing a radio button implies that the option will be an enum-like value. Currently we have 2 options each with its own bool value for active/not-active for each of the 2 features involved. We have 2 options here:
1. Refactor the current options into a single new option the new radio option that will be set to `'async'|'optimize'`. This will require changing/refactoring the `Admin/Settings` classes in RUCSS and `CriticalPath` packages and all the tests that are dependent on those settings. In each case the refactors will be small ones, but there will be a lot of places to check.
2. **Let the new radio value be a proxy** that sets/unsets the other 2 settings appropriately in the background, making the current boolian options into hidden settings. This seems like the **easier/faster/preferred** way, as we will not have to touch the underlying Admin code and tests in above packages.

Finally, in addition to the above and @mostafa-hisham solution, another [XS] subtask will be to correctly style the new elements and regenerate the admin.css.

**Comment by Mai-Saad** [comment]
@GeekPress Please find my questions below:
1-  If we import old settings where OCD + RUCSS are enabled => then OCD will be auto disabled and only RUCSS will be enabled? If we roll back to the older version after that, OCD will still be disabled?
2- Currently, RUCSS is beta and we display confirmation message when enabled => how will this reflected on new UI? notice that for new users we now need RUCSS selected by default
