### ISSUE TITLE
Remove Query String - Support Jetpack Photon

### ISSUE THREAD

**Issue by bhubbard** [wp-media/wp-rocket#425]
It would be great if the remove query string would support photon. I notice that all photon urls get the query ?ssl=1 on any site using HTTPS. Doing a simple check and remove this one query will help sites perform better on the site speed test tools such as gtmetrix, etc.

**Comment by Tabrisrp** [comment]
Remove query strings only applies to resources loaded from your own website. Since photon is an external CDN, we don't do any modification on resources loaded from it.

**Comment by bhubbard** [comment]
Is there no way this can be revisited? Should be a pretty easy thing to enable, and can be a setting if needed:

```
function jetpack_kill_ssl_arg() {
	remove_query_arg( 'ssl' );
}
apply_filters( 'jetpack_photon_url', 'jetpack_kill_ssl_arg', 99 );
```

The code that adds it is here:
https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/functions.photon.php#L186
