### ISSUE TITLE
Ability to generate Specific CPCSS for taxonomy archives

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4250]
**Is your feature request related to a problem? Please describe.**
When archive pages need specific CPCSS per taxonomy, currently there is no way to generate it.

**Describe the solution you'd like**
Add the ability to generate Specific CPCSS for taxonomy archives.

**Describe alternatives you've considered**
 It might be added inside the category management page? _Generate Specific CPCSS for archive page_--- _Revert to Default CPCSS_ : https://jmp.sh/MbEFKyD 

**Additional context**
This is not critical, but we do get some requests about this. 
Example ticket: https://secure.helpscout.net/conversation/1603490634/287940?folderId=2683093

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
