### ISSUE TITLE
RUCSS - PHP Fatal error: Uncaught ValueError: Path cannot be empty in /wp-admin/includes/class-wp-filesystem-direct.php

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4257]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version✅ `3.9.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The following error popped up in the `error_log`:
```
PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /home/public_html/wp-admin/includes/class-wp-filesystem-direct.php:39
Stack trace:
#0 /home/public_html/wp-admin/includes/class-wp-filesystem-direct.php(39): file_get_contents('')
#1 /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/UrlTrait.php(125): WP_Filesystem_Direct->get_contents(NULL)
#2 /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php(123): WP_Rocket\Engine\Optimization\RUCSS\Warmup\ResourceFetcherProcess->get_file_content(NULL)
#3 /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php(183): WP_Rocket\Engine\Optimization\RUCSS\Warmup\ResourceFetcherProcess->get_resource_contents(Array)
#4 /home/public_html/wp-content/plugins/wp-rocket/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php(315): WP_Rocket\Engine\Optimization\RUCSS\Warmup\ResourceFetcherProcess->task(Array)
#5 /home/public_html/wp-content/plugins/wp-rocket/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php(471): WP_Rocket_WP_Background_Process->handle()
#6 /home/public_html/wp-includes/class-wp-hook.php(303): WP_Rocket_WP_Background_Process->handle_cron_healthcheck()
#7 /home/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#8 /home/public_html/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#9 /home/public_html/wp-cron.php(138): do_action_ref_array('rocket_rucss_wa...', Array)
#10 {main}
  thrown in /home/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 39
```

This is taking place here:
https://github.com/wp-media/wp-rocket/blob/9e9b3645d051ddd52b0eeb88ab0bbacf5e0ed515/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php#L123

The customer was using `mod_pagespeed` and that created 193,000 warmup-related batches in the options table.
It's the error described in #4207.

**To Reproduce**

I don't have a way to reproduce this.

**Expected behavior**

PHP fatal errors should be prevented.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1585279114/283557/
**Slack Conversation:** https://wp-media.slack.com/archives/C029G1B5HD2/p1629106397010900

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :heavy_multiplication_x: 
Couldn't Reproduce it

### Identify the root cause ✅ 
file_get_contents will generate fatal error with an empty string
### Scope a solution ✅ 
we can add if condition here
to return false if sting is empty
https://github.com/wp-media/wp-rocket/blob/f0c43a7a9bf0f4a8e7b4fd9a1548e6acd93b09f5/inc/Engine/Optimization/UrlTrait.php#L124
```
if ( empty( $file ) ) {
	return false;
}
```

### Estimate the effort ✅
Effort `[XS]`
