### ISSUE TITLE
Compatibility with new Divi update (4.10)

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4263]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In 4.10 version of Divi, they introduced a couple of enhancements and new features:
https://www.elegantthemes.com/blog/theme-releases/divi-performance

For now, the only feature that seems to be causing problems is `Enqueue jQuery Compatibility Script` (enabled by default). They're adding the following inline script to the top of the source:
http://snippi.com/s/cke9uvo

It causes problems with DelayJS and DeferJS. We need to exclude it to avoid errors in JS console (I haven't observed any problems with the functionalities of the site, but it's possible).

**To Reproduce**
1. Install newest Divi
2. Create a page in their page builder
3. Enable DelayJS and DeferJS in WPR settings

**Expected behavior**
We shouldn't cause any JS console errors

**Screenshots**
Errors when Delay and Defer are enabled:
![image](https://user-images.githubusercontent.com/26767037/130083906-805dddcc-78e9-4e92-a1e0-e4d04c508fb1.png)

Errors when only Delay is enabled:
![image](https://user-images.githubusercontent.com/26767037/130084135-e6276eb4-a44f-4c9f-88cc-fad4ff5f5a0a.png)

Errors when only Defer is enabled:
![image](https://user-images.githubusercontent.com/26767037/130084289-b752b1b3-e46f-460e-adb4-ee04efa0dea5.png)

**Additional context**
We can exclude them from Delay and Defer using the following pattern `jQuery,customHeadScripts` but we should make sure it doesn't cause any issues. In Mai's case on local it also excluded jQuery files.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@iCaspar In the newest version, they're turning off their feature when DeferJS is enabled:
```
if ( defined( 'WP_ROCKET_SLUG' ) ) {
	// Disable JQuery Body when WP Rocket Defer JS option is enabled
	// because the two features aren't compatible.
	if ( 1 === et_()->array_get( get_option( WP_ROCKET_SLUG ), 'defer_all_js' ) ) {
		et_builder_disable_jquery_body();
	}
}
```

It might be hard to reproduce it then. I think we still should exclude this script, just in case something happen in the future. You can manipulate this line to see an error.

Delay JS still need an exclusion.

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced locally only when Delay JS is on

### Identify the root cause ✅ 
As @piotrbak  explained in the issue
 Divi turning off the "JQuery Body" feature when DeferJS is on 
 we need to turn it off also if the delay js is on
### Scope a solution ✅ 
In Divi ThirdParty Class
we need to send false to "et_builder_enable_jquery_body" that turn off the feature in Divi if delay js is on
https://github.com/wp-media/wp-rocket/blob/3fc4780946513acfa595da40312f3394d977238a/inc/ThirdParty/Themes/Divi.php#L40-L55
```
$events['et_builder_enable_jquery_body'] = 'disable_divi_jquery_body';
return $events;
```
```
	public function disable_divi_jquery_body() {
                if ( ! $this->delayjs_html->is_allowed() ) {
		        add_filter( 'et_builder_enable_jquery_body', '__return_false' );
                    }
	}
```
send the dealy_js_html object to Divi third party so we can check if the option is on
in 
https://github.com/wp-media/wp-rocket/blob/3fc4780946513acfa595da40312f3394d977238a/inc/ThirdParty/ServiceProvider.php#L77-L81
```		
$this->getContainer()
          ->share( 'divi', 'WP_Rocket\ThirdParty\Themes\Divi' )
          ->addArgument( $this->getContainer()->get( 'options_api' ) )
          ->addArgument( $options )
          ->addArgument( $this->getContainer()->get( 'delay_js_html' ) )
          ->addTag( 'common_subscriber' );
```
### Estimate the effort ✅
Effort [S]
