### ISSUE TITLE
RUCSS - Pseudo-Class Broken 

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4265]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

Pseudo-Class broken after first selector

**Before RUCSS:**
Case 1:
```
:not(.div-stayzone-apple) .div-apple-T1, :not(.div-stayzone-mango) .div-not-mango-T2 {
	color: black;
	text-align: center;
	font-size: 20px;
	background: pink;
	border: 2px solid black;
}
```
Case 2:

```
:not(#tve) [data-css="tve-u-1764d178f06"] p, :not(#tve) [data-css="tve-u-1764d178f06"] li, .tcb-plain-text {
	color: var(--tve-color,rgb(255,255,255));
	--tve-applied-color: var$(--tve-color,var$(--tcb-tpl-color-14));
	--tcb-applied-color: var$(--tcb-tpl-color-14);
}
```

**After RUCSS:**
Case 1:
```
:not(.div-stayzone-apple) .div-apple-T1, .div-stayzone-mango, .div-not-mango-T2 {
	color: #000;
	text-align: center;
	font-size: 20px;
	background: pink;
	border: 2px solid #000;
}
```
Case 2:

```
:not(#tve) [data-css="tve-u-1764d178f06"] p, [data-css="tve-u-1764d178f06"] li, [data-css="tve-u-1764d178f06"] .tcb-plain-text{
	color: var(--tve-color,rgb(255,255,255));
	--tve-applied-color: var$(--tve-color,var$(--tcb-tpl-color-14));
	--tcb-applied-color: var$(--tcb-tpl-color-14);
}
```

**To Reproduce**

Code: 
```
<style>
:not(.div-stayzone-apple) .div-apple-T1,
:not(.div-stayzone-mango) .div-not-mango-T2{
    color:black;
    text-align: center;
    font-size: 20px;
    background: pink; 
    border: 2px solid black;
}
</style>
<div id="reproduce-template-x4">
<div class="div-apple-T1">ABC</div>
<div class="div-not-mango-T2">DEF</div>
</div>
```
Steps: Enable RUCSS, and safelist            **.div-stayzone(.*)**

**Expected behavior**
Output should be:

```
:not(.div-stayzone-apple) .div-apple-T1, :not(.div-stayzone-mango) .div-not-mango-T2 {
	color: black;
	text-align: center;
	font-size: 20px;
	background: pink;
	border: 2px solid black;
}
```

**Screenshots**
N/A

**Additional context**
It'a an problem with every pseudo class if selector start with pseudo, this case(2) i found in thrive builder, then i tried to reproduce it in my way case (1)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is fixed in 3.11, confirmed with the provided template.
