### ISSUE TITLE
HTTP/2 Server Push support

### ISSUE THREAD

**Issue by androidacy-user** [wp-media/wp-rocket#4269]
**Is your feature request related to a problem? Please describe.**
Although WP Rocket, correctly, tells us that we should not enable combine assets for HTTP/2 because of server push, Rocket does not take advantage of said feature. At all.

**Describe the solution you'd like**
According to https://www.cloudflare.com/website-optimization/http2/serverpush/, for /style/used.min.css, you'd need the following header for it to be pushed:
```
Link: </style/used.min.css>; rel=preload;
```
WordPress includes the send_headers() action WP Rocket could hook into, and add the appropriate headers to enable Server Push. As the header hurts nothing being on HTTP/1.x connections, just add it no matter what. For instance, Cloudflare always makes HTTP/1.x requests to the origin, so that detection is moot anyway.

Optimally, Rocket would add this header for all optimized assets, or at the very least Critical CSS and undeferred JavaScript.

**Describe alternatives you've considered**
The current situation, with no HTTP/2 Push involved/

**Additional context**
n/a

**Comment by javiergutierrezchamorro** [comment]
+1

**Comment by androidacy-user** [comment]
@javiergutierrezchamorro instead of replying "+1", hit the thumbs up emoji

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
