### ISSUE TITLE
Customize where the Lazy Loaded Scripts, Critical CSS, Combined CSS, and Used CSS tags appear in the <head> element.

### ISSUE THREAD

**Issue by richiekastl** [wp-media/wp-rocket#4270]
**Is your feature request related to a problem? Please describe.**
SEO is very important to my client and having full control over what's in the <head> element is ideal.

**Describe the solution you'd like**
The Lazy Loaded Scripts, Critical CSS, Combined CSS, and Used CSS tags were all getting placed into the <head> element by replacing the closing </title> and closing </head> tags. 

What I did was that I replaced </title> and </head> with variables you'd normally see in templating languages. 

Here are my edits: 

In wp-rocket\inc\Engine\CriticalPath\CriticalCSSSubscriber.php on line 563:
```
$buffer = preg_replace(
	'#{</title>}#iU',
	'{</title>}<style id="rocket-critical-css">' . wp_strip_all_tags( $critical_css_content ) . '</style>',
	$buffer,
	1
);
```

with this: 

```
$buffer = preg_replace(
	'#{{WPRocketCriticalCSS}}#iU',
	'<style id="rocket-critical-css">' . wp_strip_all_tags($critical_css_content) . '</style>',
	$buffer,
	1
);
```

In wp-rocket\inc\Engine\Optimization\RUCSS\Controller\UsedCSS.php on line 494 I replaced it with the following: 

```
$replace = preg_replace(
	'#{{WPRocketUsedCSS}}#iU',
	$this->get_used_css_markup($used_css),
	$html,
	1
);
```

In wp-rocket\inc\Engine\Optimization\DelayJS\Subscriber.php on lines 103-111:

```
$pattern = '{{WPRocketLazyLoadScripts}}';

$lazyload_script = $this->filesystem->get_contents(rocket_get_constant('WP_ROCKET_PATH') . 'assets/js/lazyload-scripts.min.js');

if (false !== $lazyload_script) {
	$html = preg_replace($pattern, "<script>{$lazyload_script}</script>", $html, 1);
}

return preg_replace($pattern, '<script>' . $this->html->get_ie_fallback() . '</script>', $html, 1);
```

In wp-rocket\inc\Engine\Optimization\Minify\CSS\Combine.php on line 279:

```
return preg_replace('{{WPRocketStyleSheet}}', '$0<link rel="stylesheet" href="' . esc_url($minify_url) . '" media="all" data-minify="1" />', $html, 1);
```

Then in my theme file's head.php, I'm referencing those variables to place the tags. 

**Describe alternatives you've considered**
This all could also be handled through the wp_head action

**Additional context**
I don't need exactly my implementation of this feature to be included into WP Rocket, as long as I have full control over where they go in the <head> element I would be happy and so would my client.

**Comment by remyperona** [comment]
We won't make this an option, but we could add a filter to allow users to change the value of the tag to be match in the search & replace.

**Comment by richiekastl** [comment]
That would be fantastic! Which release do you think your team would be able to fit it in?

**Comment by remyperona** [comment]
@richiekastl I can't say yet, and as you can see we have a lot to work on, but we will get around it at some point.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add filters to change the patterns used when inserting the delay JS script, used CSS, critical CSS and combine CSS in the `head` of the page.

#### inc\Engine\Optimization\DelayJS\Subscriber::add_delay_js_script()
filter the `$pattern` with the filter name `rocket_delay_js_matching_pattern`

#### inc\Engine\Optimization\RUCSS\Controller\UsedCSS::add_used_css_to_html()
filter the `</title>` pattern with the filter name `rocket_rucss_matching_pattern`

#### inc\Engine\CriticalPath\CriticalCSSSubscriber::insert_critical_css_buffer()
filter the `</title>` pattern with the filter name `rocket_critical_css_matching_pattern`

#### inc\Engine\Optimization\Minify\CSS\Combine::insert_combined_css()
filter the `</title>` pattern with the filter name `rocket_combine_css_matching_pattern`

### Estimate the effort ✅
Effort `[XS]`

**Comment by richiekastl** [comment]
@Tabrisrp Thank you!

**Comment by viobru** [comment]
We should also consider the Google Fonts too.

The automated Google Fonts optimization is causing the `<meta>` tags to be displayed below the `@font-face` lines, and this causes SEO issues on sites having hundreds/thousands of `@font-face` lines in their HTML.

Related ticket: https://secure.helpscout.net/conversation/1709506962/310866/
Slack conversation: https://wp-media.slack.com/archives/C08N8J6VC/p1638292559055400

**Comment by webtrainingwheels** [comment]
Related: https://secure.helpscout.net/conversation/1707641216/310371/
Missing `head` tag meant that our Delay script was added in the middle of the page, after this tag: `<header class=header_section>`

**Comment by GeekPress** [comment]
@richiekastl Hi!

Can you please elaborate what are the problems with SEO?

**Comment by GeekPress** [comment]
I'm closing the issue until to get more info about what is the issue with SEO.

@richiekastl Feel free to elaborate on why it is an SEO problem, so we can re-open it.
