### ISSUE TITLE
IIS servers - avoid PHP warnings when colons are used in URLs

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4278]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
when visiting a URL with a colon, we try to create the cache file and this causes a warning on IIS servers because the colon is not a valid character for filenames:

[19-Aug-2021 15:09:28 UTC] PHP Warning: copy(E:\web\folder\htdocs\wp/wp-content/cache/wp-rocket/site.com/wp/path:-name/index-https.html_temp): failed to open stream: No such file or directory in E:\web\folder\htdocs\wp\wp-admin\includes\class-wp-filesystem-direct..php on line 309

**To Reproduce**
1. on a IIS server
2. Visit a URL and force adding a colon at the URL
3. Check the logs
4. Find the PHP warning

**Expected behavior**
We should encode the filenames to avoid such issues on IIS servers

**Additional context**
Slack convo: https://wp-media.slack.com/archives/C43T1AYMQ/p1629734121035600
Ticket: https://secure.helpscout.net/conversation/1605037817/288330?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
