### ISSUE TITLE
PHP Warning: readfile() has been disabled for security reasons in /home/mysite/public_html/mysite.com/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php on line 180 #491

### ISSUE THREAD

**Issue by arianfar62** [wp-media/wp-rocket#4282]
hello every one

I had this error in error log file in root folder of site:

PHP Warning: readfile() has been disabled for security reasons in /home/mysite/public_html/mysite.com/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php on line 180

i changed

readfile( $cache_filepath );
to
echo file_get_contents ( $cache_filepath );

in class-cache.php on line 180

By this change, My problem was solved!
But the question:
Do this change , Creates any problem In wp-rocket plugin performance?

What do these changes mean?
echo file_get_contents ( $cache_filepath );

Thanks in advance for your help!

**Comment by remyperona** [comment]
Hi @arianfar62,

`readfile()` being disabled on an hosting is quite unusual these days, and I don't think we encountered that often before.

While your change is fine, it will be overwritten when you next update the plugin, so it's not something that is going to work long-term.

My suggestion would be to change your hosting provider, `readfile()` is safely used in our plugin, so there isn't really a reason to disable this function.

**Comment by arianfar62** [comment]
Thank you very much for your invaluable guidance
I have just called hosting and I am waiting for an answer.
Yes you are right and my changes will be removed with the plugin update and I will see the problem again.

I wish you and everyone good health
