### ISSUE TITLE
Minify JS: Comments are not being removed correcty in some cases (3.9.2)

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#4291]
**Before submitting an issue, please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ (3.9.2)
- Used the search feature to ensure that the bug hasn’t been reported before  ✅

**Describe the bug**
In 3.9.2 Minify JS is not removing the comments correctly. The issue happens when two slashed plus an "i" are in the file, so, something like this will be left in the file:

`//if()...`

So, when the rest of the code is minified and concatenated to that commented line, an additional piece of code is commented.

The issue is here: https://github.com/wp-media/wp-rocket/blob/7736b7dbbadba2f166d56a118c876d2873ab5ae0/inc/Dependencies/Minify/JS.php#L222

This is not happening in 3.9.1.1.

**To Reproduce**
1. Install WP Rocket 3.9.2
2. Install a plugin like Advanced Ads (It has a `//if()...`)
3. Activate Minify JS

**Expected behavior**
The comments should be removed without issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/131156969-6cb9ae20-35bf-4231-99e0-164e0c3b3f4a.png)
![image](https://user-images.githubusercontent.com/13713107/131157109-69f3b640-b625-409b-9817-83ab6992781f.png)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1613512341/290440?folderId=377611

**Comment by alfonso100** [comment]
https://secure.helpscout.net/conversation/1613749071/290507?folderId=4130695

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1612593445/290180?folderId=377611

**Comment by camilamadronero-zz** [comment]
https://secure.helpscout.net/conversation/1615398073/290889/
