### ISSUE TITLE
Add Customization to the Integrated Heartbeat Feature

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4297]
**Is your feature request related to a problem? Please describe.**
The integrated Heartbeat feature in WP Rocket doesn't offer the option to set the specific the Heartbeat frequency, and if the project requires it, customers need to install the Heartbeat Control plugin too. Increasing the number of installed plugins.

**Describe the solution you'd like**
Add the Modify Heartbeat option to customize the frequency of the Heartbeat API, inside WP Rocket.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1615373695/290887/

Thanks!

**Comment by DahmaniAdame** [comment]
If added to the UI, it might be wrongly used by customers not really needing to modify the Heartbeat increased periodicity (we set it to 120s).

Maybe just adding a filter to control the periodicity will do the trick for users really needing it? 

https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Heartbeat/HeartbeatSubscriber.php#L76-L85

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1742544395/316560?folderId=3864740

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1931222382/350631/

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
