### ISSUE TITLE
Used CSS is not cleared after editing a taxonomy

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4299]
**Before submitting an issue please check that you’ve completed the following steps:**
YES - Made sure you’re on the latest version
YES - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are not clearing the used css after editing a category, or product category.
If the category has, for example, description-related CSS, it won't be included since the element is new.
The customers will have to clear the used css to update it. The only way they have is to clear the whole Used CSS, This is problematic for big sites.

**To Reproduce**
1. Edit a Category description
2. Check the corresponding Used CSS Row, it won't be cleared

**Expected behavior**
Clear the specific Used Css of a taxonomy after it has been is updated
 
**Additional context**
Ticket: https://secure.helpscout.net/conversation/1602558912/287775/
The ticket contains a custom snippet that does the job of removing the used css for a specific taxonomy by hooking a wpdb request into `edit_term` (not very elegant, I know :) )

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
For retest:
1- Enable RUCSS, cache category page => entry added in used CSS table
2- Change CSS of any page element from appearance-> add custom CSS   (i.e https://blog.hubspot.com/website/style-individual-categories-wordpress) and save => expected here that page entry removed from UCSS table
3- Access the category page again => expected here to see updated style and new entry added to used CSS table

**Comment by remyperona** [comment]
We can add a new method to hook on `edit_term` in the RUCSS Admin Subscriber, which will be very similar to `delete_used_css_on_update_or_delete()`, but instead of using `get_permalink()`, we use `get_term_link()` to retrieve the URL of the related taxonomy, and clear its used CSS from the database.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Optimization\RUCSS\Admin\Subscriber`, add a new method `delete_term_used_css()` that will behave like described above. Hook it on `edit_term` in `get_subscribed_events()`

### Estimate the effort ✅
Effort `[S]`
