### ISSUE TITLE
Better message when the API key / license does not validate

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#43]
Reviving this old issue because I think it can save us some tickets! :) Whaddya think @glueckpress @Tabrisrp ?

When API key doesn't validate right away, we should add some copy on this screen:

![api_key](https://cloud.githubusercontent.com/assets/1043076/26007350/0194ca94-36f5-11e7-9614-6200e929b9c9.jpg)

To the effect of: 
1. Try clicking Save (works in a lot of cases)
2. If that doesn't work - link to our doc. 

The most glaring problem here is that we have text that tells people to enter their API key which is 100% wrong, lol.

**Comment by glueckpress** [comment]
This is how the UI feedback currently looks:

<img width="862" alt="screen shot 2017-05-16 at 19 38 58" src="https://cloud.githubusercontent.com/assets/308422/26119969/7ff59d00-3a6f-11e7-9308-3c9a3e8569c1.png">

Apart from that it deserves some CSS love regarding positioning and maybe colour, I’d propose to reduce additional copy to a doc link. Steps to troubleshoot should be listed there and not clutter the UI.

**Comment by webtrainingwheels** [comment]
@glueckpress This issue is in relation to the WP Rocket API key/license validation, not Cloudflare :)

**Comment by glueckpress** [comment]
@webtrainingwheels OMG, I am so stupid… _palms the face_

**Comment by glueckpress** [comment]
Forgot to reference this issue in these commits:

- https://github.com/wp-media/wp-rocket/commit/3e1bf5a4b4f796a1b10804f0e7a7afa27ea1bb40
- https://github.com/wp-media/wp-rocket/commit/e8d2f9112169e36f8da3f6157964003448a6e81b
- https://github.com/wp-media/wp-rocket/commit/317e2fb3b8c40e86a505e9292a406ad7f0714449
- https://github.com/wp-media/wp-rocket/commit/1c2c8a9d4ad79e7fc3d19fd051a0c4b2c580b9f3
- https://github.com/wp-media/wp-rocket/commit/d5b6f76bdc569e9ded7f253f4758fde7332439fc

This is how it would look: 

<img width="872" alt="screen shot 2017-05-22 at 19 26 59" src="https://cloud.githubusercontent.com/assets/308422/26320978/3bf2ccbc-3f25-11e7-976d-e99622a4fdbf.png">

What do you think, @webtrainingwheels?

**Comment by webtrainingwheels** [comment]
Looks great!!!
