### ISSUE TITLE
Update Delay JS script to the latest version

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4303]
For the 3.9.3 release, we need to update the Delay JS script to the latest version available. This version fixes a bug to avoid the user clicks on a button and nothing happens.

Branch to be merged: `replay-events`

**Comment by inewton24** [comment]
Nice, but now we have bug in real IOS 14 Safari (not emulator). replay-events not work, but if we will exclude main script in plugin, we will have double click event.

**Comment by inewton24** [comment]
> Nice, but now we have bug in real IOS 14 Safari (not emulator). replay-events not work, but if we will exclude main script in plugin, we will have double click event.

i think it is because of this article - https://stackoverflow.com/questions/43335183/window-click-event-does-not-fire-on-ios-safari-javascript-only click event not work in IOS, but touchstart must be good
