### ISSUE TITLE
RUCSS - wp_wpr_rucss_resources database table was 463MB on a site

### ISSUE THREAD

**Issue by lukecav** [wp-media/wp-rocket#4304]
**Describe the bug**
The remove unused CSS feature was enabled on the site which caused the `wp_wpr_rucss_resources` database table to grow to be 463MB in size. On another site, the `wp_wpr_rucss_resources` database table was over 200MB in size.

WP Rocket's current version is being used is 3.9.2 on WordPress version 5.8.

**Comment by lukecav** [comment]
Looks related to
https://github.com/wp-media/wp-rocket/issues/4161

**Comment by iCaspar** [comment]
Duplicate of #4161
