### ISSUE TITLE
Allow helper validation to run on pattern fields when importing settings

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#4305]
**Describe the bug**
Helper pattern-cleaning functions are used to correct common type-Os made in pattern fields when saving options. These helpers are not applied when importing settings.

**To Reproduce**
1. Temporarily disable/comment out the `pre_update_option` [filter](https://github.com/wp-media/wp-rocket/blob/410f1fa767a12d97bdccaa90553348d2faeda704/inc/admin/options.php#L221)
2. Add a type-o pattern into any of the pattern fields (DelayJS Exclusions, for example) `example.com/assets/js/*` and save options.
3. Export the options
4. Re-enable filter and re-save to view the corrected option value.
5. Import the saved options.
6. Observe that the type-o option is re-applied.
 
**Expected behavior**
Imported options with type-Os should be corrected, same as when saving.

**Backlog Grooming (for WP Media dev team use only)**
- [X] Reproduce the problem
- [X] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

Root cause: `rocket_pre_main_option()` checks for `$is_form_submit` before running pattern helpers, which is not true when importing.

**Comment by Mai-Saad** [comment]
Note for the retest: we need to check the update case too

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
