### ISSUE TITLE
Updating documentation for Divi

### ISSUE THREAD

**Issue by WPcare** [wp-media/wp-rocket#4315]
Hi there,

Is there any chance someone would update the [Divi theme documentation](https://docs.wp-rocket.me/article/657-divi-theme ) to reflect the more recent changes to the theme?

**Comment by camilamadronero-zz** [comment]
Hey there,

We've updated the [Divi theme doc](https://docs.wp-rocket.me/article/657-divi-theme#perf-update) a few hours ago. Please feel free to open a support ticket if you have any  additional questions! 
Thanks for your patience :)
