### ISSUE TITLE
RUCSS is stuck at fetching if we update theme while RUCSS is inprogress

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4317]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.3
- Used the search feature to ensure that the bug hasn’t been reported before =>yes

**Describe the bug**
RUCSS is stuck at fetching if we update the theme while RUCSS is in progress

**To Reproduce**
Precondition:
- RUCSS is enabled
- Having a theme that needs an update
1. Switch to the theme which needs an update
2. Update the theme
3. RUCSS stuck at fetching

**Expected behavior**
RUCSS is not stuck

**Additional context**
Re-enable the option will work fine

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Fixed in 3.11 as we're not using the warmup anymore.
