### ISSUE TITLE
Delay JS default exclusions cause error with Google Recaptcha and CF7

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4321]
- tested on 3.9.2

**Describe the bug**
When using Contact Form 7's recaptcha module and the default exclusions for Delay JS, an error prevents the form working: 
<img width="934" alt="Screen Shot 2021-09-02 at 9 56 15 AM" src="https://user-images.githubusercontent.com/1043076/131885685-a0977297-ebc6-40db-bfa3-f043ef86b44b.png">

This is the file that needs to be excluded in that case: `https://www.google.com/recaptcha/api.js?render=6LeIFD8cAAAAALUchSdKA7gvcg9Q2sdPyrsBlOWp&ver=3.0`

I'm not sure if we're able to do anything about this, but there are numerous tickets with this issue.

When all files are delayed this error doesn't occur.
Could be an issue with other form plugins that also use the same Google recaptcha file.

**To Reproduce**
There is already a test page on Mega for this.

The general steps are:
1. Enable Contact Form 7 and the recaptcha module
2. Add a form to a page
3. Enable the default exclusions in Delay JS
4. See the error given above

**Expected behavior**
Ideally our default exclusions don't create errors that wouldn't otherwise be there.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1627197387/293797?folderId=1213662

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1639397647/296648?folderId=2135277

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
