### ISSUE TITLE
Allow setting the cache-control header

### ISSUE THREAD

**Issue by lucalbert** [wp-media/wp-rocket#4323]
The Cache-Control header is a simple way to optimize the performance of a site.

I think it could be interesting that WP Rocket allows to manage this setting, and to be able to transmit this header for the pages, whether they are cached or not yet.
This therefore implies, a priori, to store somewhere (a "meta" file linked to the cache file, just like the gzipped version?)

At the configuration level, there could be a panel for the global configuration (home page, posts page, each type of public content, ...).
We could then have a metabox on each content to define more precisely the parameters.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
