### ISSUE TITLE
RUCSS, apply_filters on "safelist" selectors

### ISSUE THREAD

**Issue by hogash** [wp-media/wp-rocket#4328]
**Describe the solution you'd like**
Apply a filter on the "safelist" list of selectors that's passed on to RUCSS mod. 

**Additional context**
Should work pretty much the same as it does on the other options "exclusions" lists. 

Thanks!

**Comment by Mai-Saad** [comment]
Duplicated with https://github.com/wp-media/wp-rocket/issues/4343
