### ISSUE TITLE
Update compatibility with JetPack

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#433]
Sitemap is no longer detected because jetpack_sitemap_uri() is not available when we check for it

EU cookie law cookie is always added, even when the widget is not active

**Comment by Tabrisrp** [comment]
@jeherve tell me if you can have a look at these

**Comment by jeherve** [comment]
I'm AFK right now, but @dereksmart might be able to take a look.

**Comment by GeekPress** [comment]
@Tabrisrp Does this issue is still accurate?

**Comment by Tabrisrp** [comment]
Our whole jetpack compatibility file is currently commented because of the issues above. Jetpack changed a lot since 2017 too though, so we might need to rewrite everything.

Right now, consider that we currently don't have any built-in compatibility with Jetpack
