### ISSUE TITLE
Allow custom host(s) for cache generation

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4330]
**Is your feature request related to a problem? Please describe.**
Hi,
i'm working on a project which have a reverse-proxy environment with a custom host for the "public front url" and another host url for the administration.
I realised WP Rocket never generated static cache for my public front url.

For a better understanding of the situation:
- WP is installed & configured on a url which look like: `https://wpinstance.specificcloud.com`
- Public front url is something like: `https://www.mypublicsite.com`

WP Rocket never generated / served static cache for `https://www.mypublicsite.com`

**Describe the solution you'd like**
I added `www.mypublicsite.com` to the native WP core filter [`allowed_redirect_hosts`](https://developer.wordpress.org/reference/hooks/allowed_redirect_hosts/) so WP know he should allow connections from `www.mypublicsite.com`.
Maybe you could also check for hosts url in that filter to generate static cache folders.

**Describe alternatives you've considered**
I fixed the issue this way _(but it should be easier / have more infos on it)_:
```php
<?php
// Tell WP Rocket to generate static cache folders for my custom domains and serve it
add_filter( 'rocket_config_files_path', 'config_custom_hosts_domains' );
function config_custom_hosts_domains( $config_files_path ) {

    $config_files_path[] = WP_ROCKET_CONFIG_PATH . 'mypublicsite.com.php';
    $config_files_path[] = WP_ROCKET_CONFIG_PATH . 'www.mypublicsite.com.php';

    return $config_files_path;
}

```

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
