### ISSUE TITLE
Generate specific critical path css is not working again for the 7th time

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4334]
**Describe the bug**
Generate specific critical css is not working again. This is the 7th time this has happened. Why does critical css generation continue to fail randomly, and then start working again? This is incredibly frustrating.

**To Reproduce**
1. Try to generate specific critical path css.
2.  The spinning icon will appear for a few seconds, then disappear
3. Specific critical path css generation fails

**Expected behavior**
Specific critical css generation works correctly

**Additional context**
Please fix this once and for all. This is beyond frustrating. Are you doing server maintenance? Please give an explanation for why this occurs.

**Comment by GeekPress** [comment]
Please open a ticket support. 

@jazir5 If you don't stop using GH for asking for support, we will have to ban you from our repository.
