### ISSUE TITLE
Add a "Service Status and Connectivity" tab or widget to WP Rocket settings page

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4338]
**Is your feature request related to a problem? Please describe.**
We get tickets where, for diverse reasons, the customer server can't communicate with our services.

It'd be really useful to incorporate a place in the UI, where the user can see if their server can connect with our services: CPCSS, RUCSS, License Validation, RocketCDN,  etc

**Describe the solution you'd like**
It could be inside a dedicated tab, or as a widget in our dashboard. 
Containing:
- **Services Status:** a link to an _external_ **Service Status Page**. This is the original issue Romain opened: https://github.com/wp-media/wp-rocket.me/issues/2426
- **Connectivity:** is the server where WP Rocket is installed, capable of connecting and access our services? similar to: https://wphangar.com/ping.php 

**Additional context**
This, paired with @WordPresseur feature request: https://github.com/wp-media/wp-rocket.me/issues/2426
can be useful when we have issues/downtime with our services. 

- A common case use for a Services Status page is, when there is an issue with the CPCSS service, for example, our users start testing things on their end before opening a ticket, we answer the ticket, and at the end some of they come back asking for our status page. If they know beforehand that the service was down, we save their time. 

- Another case use for the Connectivity page, would be to help troubleshoot tickets related to License Validation, CPCSS generation, RUCSS generation, and RocketCDN. If we detect our IPs are blocked, we can provide links to relevant docs.

**Comment by WordPresseur** [comment]
https://wp-media.slack.com/archives/C6H7EC92P/p1634772202001700

**Comment by piotrbak** [comment]
We're considering it but it won't be part of the upcoming majors. We'll reopen the issue
