### ISSUE TITLE
Add a filter for programmatically adding entries for Safelist

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4343]
Currently, there is no filter to programmatically safelist selectors for the _Remove Unused CSS_ option.

Such filter could be useful for compatibility development in 3rd-party plugins/themes.

Related request: https://secure.helpscout.net/conversation/1609150673/289293

Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1631172880106900

**Comment by iCaspar** [comment]
The following should work for themes and plugins wanting to modify the safelist for RUCSS compatibility:
```
function cg_test_stuff( $safelist ) {
    $safelist[] = '.theme-specific-class';
    return $safelist;
}
add_filter( 'pre_get_rocket_option_remove_unused_css_safelist', 'cg_test_stuff' );
```

By way of documentation:
`$safelist` is an array with a single filename, class, id, tag, or attribute per item.
Any item can include the wildcard sequence `(.*)` indicating to safelist all matching items.
Note that currently we only handle safelisting attributes, without regard to any values.
```
[
    '/path/to/safelisted.css',   // safelist everything in this file
    '.classname',   // a class indicated by leading dott
    '#idname',   // an id indicated by leading hash
    'h1',   // any valid html tag
    '[title]',   // an attribute indicated by enclosed square brackets
    '#id-(.*)',   // matches #id-1213ab3, #id-anythingyouwant, etc
    '.class(.*)me',   // matches .class123me, .classClassyme, etc
    '#id.classname',   // invalid, two things in the same entry -- will be ignored
    '[title="image-title"]',   // invalid, only attributes are considered -- will be ignored
]
```

**Comment by iCaspar** [comment]
Note on the above... it will work. It will also actually update the wpr safelist setting next time the WPR settings page is loaded (as it filters on the `pre_get_rocket_option`).
That may or may not be a desired side-effect.
@GeekPress @Tabrisrp: We could add a filter `rocket_pre_send_unused_css_safelist` to filter only when shaking at this point: https://github.com/wp-media/wp-rocket/blob/8ed2cc120938a8f652794e3d6e53422ce7d8782e/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L182 that would apply only when actually sending for usedCss generation.
Would be an [XS] item.
Thoughts?

Meanwhile the save to wpr options can be avoided by checking for being on the rocket admin page and returning early:
```
function cg_test_stuff( $safelist ) {
	global $pagenow;
	if ( 'options-general.php' === $pagenow && 'wprocket' === $_GET['page'] ) {
		return $safelist;
	}
	$safelist[] = '.theme-specific-class';
	return $safelist;
}
```

**Comment by remyperona** [comment]
For our other options, we always use a separate, additional filter for custom/3rd parties. Possibly it's a good approach to continue this?

Also, it avoids tying it to the option itself, if for any reason in the future we change option name or anything like that.

**Comment by pedddro** [comment]
Is there a similar filter of "pre_get_rocket_option_remove_unused_css_safelist" but for Optimize CSS? some themes need it to avoid a high CLS while using Optimize CSS such as Elementor. [Excluding files](https://docs.wp-rocket.me/article/977-exclude-files-from-optimize-css-delivery) does not currently help much.

**Comment by alfonso100** [comment]
related question from a 3rd party developer: https://secure.helpscout.net/conversation/1662864389/301553/
