### ISSUE TITLE
Automatically exclude superpwa-manifest.json from the CDN to prevent an error 405

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4344]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On sites running the [Super Progressive Web Apps](https://wordpress.org/plugins/super-progressive-web-apps/) plugin, there is an **error 405** for the `superpwa-manifest.json` file when having the CDN enabled in our tab. 

**To Reproduce**
1. Install the Super Progressive Web Apps plugin
2. Enable the CDN on WP Rocket
3. Open the developer console, and you'll see the error 405 for the `superpwa-manifest.json` file

**Expected behavior**
There should be no 405 error.

**Screenshots**
https://share.getcloudapp.com/Wnu0mYKd

**Additional context**
@vmanthos has found the error is appearing because the file gets rewritten to the CDN: 
https://i.vgy.me/5UNhyA.jpg

Adding the following in the CDN exclusion area fixed it, so we could automatically exclude it in WP Rocket's core:
`/superpwa-manifest.json`

Related ticket: https://secure.helpscout.net/conversation/1626912542/293685/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
