### ISSUE TITLE
Replace the usage of navigator.userAgent

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#4347]
**Is your feature request related to a problem? Please describe.**

Replace de usage of `navigator.userAgent` for `navigator.userAgentData
` on WP Rocket code.

**Describe the solution you'd like**
According to the [chromium's blog](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html) they are changing how information obtained through `navigator.userAgent` is shared, as a result of this change, notices are being made in Chrome like this one:  https://i.imgur.com/qjJoSis.png

**Describe alternatives you've considered**
Replace de usage of `navigator.userAgent` for `navigator.userAgentData`

**Comment by piotrbak** [comment]
Closing it in favour of:
https://github.com/wp-media/wp-rocket/issues/2475
