### ISSUE TITLE
RUCSS - RUCSS not applied all over the site

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4350]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
RUCSS Is not applied all over the site.
When i test i see that rucss not applied in random pages.
If i press clear used css, i see rucss on not applied page. but then i see rucss not applied on some else pages. so this is randomly happened.

**To Reproduce**
I don't have an way to reproduce this, but it happens.

**Expected behavior**
It should applied all over the site.

**Screenshots**
N/A

**Additional context**
The problem much happens If preload on.
The problem tested multiple times and tested even without server cache. only rucss has this problem rest of things working fine.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
Hey there @mehedihasanziku 👋 
Thanks for bringing this to our attention.
Would you please [contact our support team](https://wp-rocket.me/support/). They can help you troubleshoot this, and if it turns out to be a code issue, that will help us figure out how to reproduce and solve it.
Thanks again!

**Comment by iCaspar** [comment]
We can re-open if we get any feedback about the issue.
