### ISSUE TITLE
DelayJS 3.9.4 events is triggered twice

### ISSUE THREAD

**Issue by Garnet-Fox** [wp-media/wp-rocket#4354]
I do not understand whether this is a normal behavior or not.
After update 3.9.3 -> 3.9.4 DelayJS
On mobile, if there were no events of loading delayed scripts, but immediately tap on the button, for example, opening a modal window, the event is triggered twice, that is, it opens, closes, and reopens modal windows (tested on Magnific Popup). On desktops, the behavior is similar, but in my opinion it happens even if the delayed scripts are loaded. The Tooltipster plugin has similar behavior. Flatsome theme, but I don't think that's the case.
If you exclude all scripts from delay, everything is fine. if you include at least one script in delay, double events occur again.

**Comment by piotrbak** [comment]
Hello @Garnet-Fox, thank you for your feedback.

Could you share your website url? You can reach me at piotr[at]wp-media.me

**Comment by Garnet-Fox** [comment]
Reply by mail
In my opinion, if the js event is set not through delayed scripts, then the following happens, it fires by itself, and then fires again, after all the delayed scripts have been loaded.

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1632306550/294971/

**Comment by bwafels** [comment]
I have the impression a similar thing is happening on my site. autodirect for WMPL language switching is excluded but often it still loads the site twice because of it detecting another language.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1639387637/296642/

In this case, the menu opens and closes immediately on first use. 

Works properly after that. 

Confirmation that the click event is triggered twice:

![image](https://user-images.githubusercontent.com/1289174/134641638-583ad4b1-dce9-4ee4-9d0e-b3d8d483f62e.png)

I used `monitorEvents(window, "click");` on the browser's console to monitor clicks.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1635202394/295645?folderId=377611

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1643884057/297545/

**Comment by camilamadronero-zz** [comment]
New ticket: https://secure.helpscout.net/conversation/1632486955/295016?folderId=2675957

**Comment by s60v5** [comment]
This bug still seems to be a problem. Just replicated this on a fresh Wordpress installation with WP Rocket 3.12.3.2. 

Steps to reproduce:
1. Create a new javascript file in your child theme, for example under "js/script.js".
2. Add a new event listener:
```
const test_button = document.getElementById("test-button")
if (test_button) {
	test_button.addEventListener("click", function() {
		console.log("Test button clicked")
	});
}
```
3. Exclude the script.js file in WP Rocket Settings under "Delay JavaScript execution" and enable the delay JS.
4. On frontend, everything is working ok as long as you move the cursor before clicking on the test-button and allow the script to be loaded. However, if you move your cursor exactly where the button is before the page is loaded to click on it directly without moving the cursor to avoid the script from being loaded, you will notice that the event listener is triggered twice. This is a big issue especially for mobile when the hamburger menu event listener gets triggered twice sometimes and so the menu closes right after it opens. 
5. Screen recording: https://drive.google.com/file/d/1--Dlz9a5CWqF4E_Ag_yui0YZHTEcQJwK/view?usp=sharing
6. Website for testing: https://wordpress-234187-3065954.cloudwaysapps.com/index.php/sample-page/

Is the WP Rocket team aware of this issue?
Thanks.

**Comment by s60v5** [comment]
Hello @piotrbak is the WP Rocket team aware of this issue? It's very problematic for us as we use WP Rocket for many sites.

**Comment by piotrbak** [comment]
Hello @s60v5 and thanks for your comment. We're investigating this issue with our developers, I can confirm that I'm able to reproduce it. Please note that we have a separate, private repository to handle the isseus strictly related to the JavaScript part of the Delay JS.
