### ISSUE TITLE
Is it possible to delay a script that's inside something like Tag Manager?

### ISSUE THREAD

**Issue by dazetoyo** [wp-media/wp-rocket#4356]
Looking to delay a bunch of our scripts but I don't want Tag manager itself to be delayed, is there a way to stop these scripts from activating with out moving them from TM onto our site?

**Comment by piotrbak** [comment]
Hello @dazetoyo thanks for being in touch with us. However, we don't provide support via GitHub. Please do a request to our support team to be helped on that matter: https://wp-rocket.me/support/
