### ISSUE TITLE
automate generating wp-rocket CSS and JS files after deployment

### ISSUE THREAD

**Issue by mostafa-hisham** [wp-media/wp-rocket#4357]
**Description**
If we are doing modifications in styling or js we generate the minified version of the files locally first with gulp then pushed
which leads to creating conflict between branches and it is not easy to resolve because we dealing with minified versions of files

**Expected behavior**
Generate CSS and JS files after deployment to avoid creating conflicts

**Comment by jeawhanlee** [comment]
After a discussion with @mostafa-hisham, We can add a new job here https://github.com/wp-media/wp-rocket/blob/develop/.github/workflows/deploy_plugin.yml that will run during deployment using 
- `gulp build` for javascript
- `gulp sass_all` for css

**Comment by piotrbak** [comment]
Reopening issue since the solution provided didn't match the requirements. Minified JS/CSS files were not present in the package.

**Comment by piotrbak** [comment]
@MathieuLamiot @Tabrisrp Is this still valid?

**Comment by MathieuLamiot** [comment]
This is a duplicated of https://github.com/wp-media/wp-rocket/issues/6649
