### ISSUE TITLE
Delay JS + Defer JS - Add compatibility with WPForms reCAPTCHA v2

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4358]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using WPForms reCAPTCHA v2, with Delay JS and Defer JS enabled, the Recaptcha checkbox is not loaded. There are no console errors, and the element doesn't appear after user interaction. 
There is pnly an info message in the console: `reCAPTCHA couldn't find user-provided function: wpformsRecaptchaLoad`

To solve it, from **Defer JS** you have to exclude:
```
/wp-includes/js/jquery/jquery.min.js
/wp-content/plugins/wpforms/assets/js/wpforms.js
```
And from **Delay JS**, exclude: 
```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/jquery-migrate(.min)?.js
wpformsRecaptchaLoad
wpformsRecaptchaCallback
/wp-content/plugins/wpforms/assets/js/wpforms.js
```

**To Reproduce**
1. Go to WPForms settings and enable recaptcha v2 https://jmp.sh/4Bc3GKC
2. Create a form using recaptcha: https://jmp.sh/XW8pKvF
3. Enable Defer JS and Delay JS in WP Rocket.
4. the recaptcha checkbox won't be present on the form with no console error, there's only an info msg in the console: `reCAPTCHA couldn't find user-provided function: wpformsRecaptchaLoad` - https://jmp.sh/5uRHkUF
6. Apply the exclusions above to see the recapcha checkbox.

**Expected behavior**
We should automatically exclude WPForms recaptcha V2 checkbox from related scripts for compatibility. 

**Screenshots**
<img width="1811" alt="main_full-2" src="https://user-images.githubusercontent.com/229406/133674850-d9d67564-7991-4c3e-b7d3-866af7b03421.png">

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1609277947/289351?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
On the test site, it happened randomly after n trials of refreshing the page. It happened once while Delay JS only was enabled. https://new.rocketlabsqa.ovh/wpform-recaptcha/

**Comment by camilamadronero-zz** [comment]
new case https://secure.helpscout.net/conversation/1698228425/308178/

**Comment by piotrbak** [comment]
For upcoming cases, can you check if adding the `wpformsRecaptchaCallback` alone exclusion to DelayJS solves the issue?

**Comment by piotrbak** [comment]
As per talks with @camilamadronero, we were not able to replicate any issue where we need more exclusions than:
`wpformsRecaptchaCallback` being excluded from Delay JS. 

Lets add this exclusion to DelayJS and see if we'll be receiving any further tickets about this. If so, we'll reopen the issue and work on that. If we, indeed need to exclude that many files, please make sure to create a staging site, so we can look for any alternative solution.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Based on the last comment, add `wpformsRecaptchaCallback`, to the `DelayJS\HTML::$excluded` array

### Estimate the effort ✅
Effort `[XS]`
