### ISSUE TITLE
Never Cache URLs limit causes 500 error (related to mod_rewrite)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4362]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.9.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When adding hundreds of items on the Never Cache URLs exclusion box, the server returns a permanent 500 unless the number is reduced from the `.htaccess` file. 

**To Reproduce**
1. Use an Apache server
2. Go to Never Cache URLs
3. Add hundreds of items from [the demo list](https://gist.github.com/DahmaniAdame/ef94a342e021e430098e7c567e19fa65)
4. Hit the save button
5. See error (on my test website, the 500 is visible when adding 130 items)

**Expected behavior**
It seems like it's an Apache `mod_rewrite` limit, though I couldn't find any information about it. The issue might not be fixable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/133886110-8c7b98d7-b614-4300-86bc-b83d840501b2.png)

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1632874772/295130/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/2011649144/369044/

**Comment by vmanthos** [comment]
Likely related: https://secure.helpscout.net/conversation/2017744677/370455/

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
