### ISSUE TITLE
Need filter for excluding Delay Execution JS for specific post type

### ISSUE THREAD

**Issue by royrakesh** [wp-media/wp-rocket#4363]
We are running a Woocommerce store and we want to enable Delay Execution JS for all pages excluding the product page.

This would be helpful for other also.

**Comment by remyperona** [comment]
This can be achieved by using the following code snippet:

```
add_action( 'wp_rocket_loaded, function() {
    if ( ! is_product() ) {
        return;
    }

    add_filter( 'pre_get_rocket_option_delay_js', '__return_false' );
} );
```

It will disable delay JS on product pages only, while keeping it enabled for all other pages.
