### ISSUE TITLE
Automatically exclude a file from JS minification when the site is running WP Forms Elite + hCaptcha

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4364]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
When our **JS minification** is enabled and the site is running [WP Forms Elite](https://wpforms.com/) + [hCaptcha](https://wordpress.org/plugins/hcaptcha-for-forms-and-more/), it is necessary to exclude the following file from JS minification for the form to work properly:
`hcaptcha.com/1/api.js`

**To Reproduce**
1. Install WP Forms Elite + hCaptcha
2. Enable WPR JS minification
3. Add a form to a page 
4. Integrate hCaptcha in the form using API
4. See error (form not loading properly)

**Expected behavior**
The form shouldn't break when JS minification is enabled. 

**Screenshots**
N/A

**Additional context**
Using WP Forms Elite plugin, you can integrate hCaptcha in their forms using API.

This issue was reported by a customer. He noticed that for some reason, WPR's JS minification was either removing or minifying the script in such a way that the form would not work. And that excluding that file fixed this.

Ticket: https://secure.helpscout.net/conversation/1632109995/294938/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
On the test site, when Minify JS is enabled, hCaptcha is added twice.
![2021-09-21](https://user-images.githubusercontent.com/76941962/134121199-74adfc86-e8a6-44ac-8488-3f18dda3816e.png)
Mentioned exclusion or deactivate hCaptcha will fix the problem.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `hcaptcha.com/1/api.js` to `AbstractJSOptimization::get_excluded_external_file_path()`

### Estimate the effort ✅
Effort `[XS]`

**Comment by Hakira-Shymuy** [comment]
Guys im having a problem on multiple websites with wpforms and Hcaptcha
With all the WPR settings enabled I'm getting a (This field is required) when sending the form

With all the settings active :
Minify/combine
Defer
Delay

It works yes for logged in users, if we test it on incognito this a real issue, any form wont work at all

Only way I can get it to work is if I disable the Defer and Delay, wich causes some problems on load page speed that may have some videos or so!

Cant find the right thing to exclude here
Tried:
hcaptcha.com/1/api.js
hcaptacha-checkbox.js
hcaptacha-challenge.js

https://hcaptcha.com/(.*)
https://newassets.hcaptcha.com/captcha/v1/f848ab9/hcaptcha.js
https://newassets.hcaptcha.com/(.*)
Im running out of options and mailbox running out of space with tickets :(

**Comment by piotrbak** [comment]
Hello @Hakira-Shymuy please reach our support in order to find the correct exclusions/solution.

**Comment by d19dotca** [comment]
@Hakira-Shymuy - according to https://github.com/wp-media/wp-rocket/pull/4566/files the change is to exclude 'hcaptcha.com/1/api.js' but if that's not working for you then this fix may not fix it in your particular case, meaning you may have a slightly different issue or require a different solution.
