### ISSUE TITLE
Uncode theme compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4366]
**Is your feature request related to a problem? Please describe.**
In upcoming weeks Uncode is going to release an update. We'll need to add some new exclusions to be still fully compatible.

**Describe the solution you'd like**
We need to exclude the following files [here](https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/3rd-party/themes/uncode.php#L17):
`/library/js/init.min.js`
`/library/js/ai-uncode.min.js`

And one more file [here](https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/3rd-party/themes/uncode.php#L56):
`/library/js/init.min.js`

**Comment by NataliaDrause** [comment]
@piotrbak 
there are new errors that popped up with Uncode and our Combine JS.

When no exclusions are added and only **Minify JS** and **Combine JS** are enabled, we get these errors:
![image](https://user-images.githubusercontent.com/60236665/153162745-9a7d2038-9279-40ef-87e4-e05063845e93.png)
_full-screen image: https://i.imgur.com/n5vsMyt.png_

We automatically exclude some Uncode files [here](https://github.com/wp-media/wp-rocket/blob/3d691234a87b8ad4664c8735c7e8e3241ca6f5f0/inc/3rd-party/themes/uncode.php#L18-L23). It seems, some of these files require jQuery and hooks.min.js.

Adding the following exclusions for Combine JS resolves the errors:
```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/dist/hooks.min.js
```

Interestingly, Defer JS doesn't require jQuery exclusions. No errors when **Minify+Combine with exclusions above + Defer JS with no exclusions** are enabled. jQuery is being deferred.

When Delay JS is enabled, it additionally requires jQuery exclusions:
```
/jquery/jquery.min.js
/jquery/jquery-migrate.min.js
```

Ticket: https://secure.helpscout.net/conversation/1781372866/324847/

**Comment by Mai-Saad** [comment]
Couldn't reproduce it on the test site using 3.10.7 with the default setup (account not registered)
Note: Maybe the problem with certain setup or other plugin is used with default auto exclusion to jQuery (further investigation is needed)

**Comment by piotrbak** [comment]
@NataliaDrause Do you happen to have a staging environment where we could see the problem?

**Comment by NataliaDrause** [comment]
Yes, there is a staging site in the ticket: https://secure.helpscout.net/conversation/1781372866/324847/
Customer provided credentials and they are still working for me.
