### ISSUE TITLE
Spaces improperly removed from regex during minification when used with certain operators

### ISSUE THREAD

**Issue by WebFX-dev** [wp-media/wp-rocket#4368]
**Describe the bug**

Spaces are improperly removed from JS regexes when the regex is used as an operand of certain operators. Operators that have confirmed issues are the nullish coalescing operator and the ternary operator.

**To Reproduce**

_Nullish Coalescing Operator_
1. Create a JS file with the following code (make sure the file will be minified) `/ / ?? false;`
2. Review the minified file and you should see that the space in the regex was removed, leaving the contents of the file as `//??!1`

_Ternary Operator_
1. Create a JS file with the following code (make sure the file will be minified) `true ? / / : false`
2. Review the minified file and you should see that the space in the regex was removed, leaving the contents of the file as `!0?//:!1`

**Expected behavior**

The spaces within the regex should be preserved.

**Additional context**

The issue occurs in /inc/Dependencies/Minify/JS.php in the `extractRegex` function. To fix this issue the `$before` pattern needs to include the `?` character:
Old: `$before = '(^|[=:,;\+\-\*\/\}\(\{\[&\|!]|'.implode('|', $keywords).')\s*';`
New: `$before = '(^|[=:,;\+\-\*\/\}\(\{\[&\|!?]|'.implode('|', $keywords).')\s*';`

 The `$after` pattern needs to include the `?` and `:` characters:

Old: `$after = '(?=\s*([\.,;\)\}&\|+]|\/\/|$|\.('.implode('|', $propertiesAndMethods).')))';`
New: `$after = '(?=\s*([\.,;\)\}&\|+?:]|\/\/|$|\.('.implode('|', $propertiesAndMethods).')))';`

These changes just fix this issue and have not been tested that they don't break other regex replacements.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.

**Comment by WebFX-dev** [comment]
Your WebFX Support Request has been Received!

wp-media/wp-rocket,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: https://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=404071

    Using the following login:
    E-mail: ***@***.***
    Password: a56d3137


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team

**Comment by WebFX-dev** [comment]
Your WebFX Support Request has been Received!

wp-media/wp-rocket,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: https://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=404072

    Using the following login:
    E-mail: ***@***.***
    Password: 2fba0c81


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team
