### ISSUE TITLE
PHP Fatal error: preg_match() expects parameter 2 to be string, null given in /DelayJS/HTML.php:221

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4374]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅(`3.9.4`)
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

A customer reported the following PHP fatal error:
```
2021/09/19 15:36:42 [error] 20009#0: *6485618 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: preg_match() expects parameter 2 to be string, null given in /home/atifitco/domains/exampe.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php:221

Stack trace:
#0 /home/atifitco/domains/exampe.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php(221): preg_match('/<head\\b/i', NULL)
#1 /home/atifitco/domains/exampe.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/Subscriber.php(114): WP_Rocket\Engine\Optimization\DelayJS\HTML->move_meta_charset_to_head(NULL)
#2 /home/atifitco/domains/exampe.com/public_html/wp-includes/class-wp-hook.php(303): WP_Rocket\Engine\Optimization\DelayJS\Subscriber->add_delay_js_script('<!doctype html>...')
#3 /home/atifitco/domains/exampe.com/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters('<!doctype html>...', Array)
#4 /home/atifitco/domains/exampe.com/public_html/wp-content/plugins/wp-rocket/inc/cl" while reading response header from upstream, client: 89.149.192.106, server: exampe.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/usr/local/php73/sockets/exampecom.sock:", host: "exampe.com"
```

This is related to the charset changes we made in #4312.

It seems this is coming from here:
https://github.com/wp-media/wp-rocket/blob/62ee027c2d2cfd8cc750b10d38a09e6455e76680/inc/Engine/Optimization/DelayJS/Subscriber.php#L114

To prevent this we can check if `$html` is `NULL` before passing it to `move_meta_charset_to_head()`:
```PHP
if( is_null( $html ) ){
    return;
}
```

**To Reproduce**

Set `$html` to `NULL` here:
https://github.com/wp-media/wp-rocket/blob/62ee027c2d2cfd8cc750b10d38a09e6455e76680/inc/Engine/Optimization/DelayJS/Subscriber.php#L113

**Expected behavior**

No errors should occur when Delay JavaScript Execution is active and `<meta charset>` exists.

**Additional context**

The customer reported that this was fixed by reinstalling the plugin, but they didn't activate Delay JavaScript Execution, and also didn't provide access for me to further investigate what exactly happened.

**Ticket:** https://secure.helpscout.net/conversation/1635289940/295670/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1645059434/297796/

**Comment by jcatello** [comment]
This is still occuring in 3.10

Causing Google to not index any new URL's

![image](https://user-images.githubusercontent.com/3605615/135635344-ada4e2af-b219-4d32-afba-1a8871265574.png)

**Comment by jcatello** [comment]
Seeing this again in 3.10.9

`PHP Fatal error: Uncaught TypeError: preg_match() expects parameter 2 to be string, null given in /home/nginx/domains/domain.com/public/w
p-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php:221
Stack trace:
#0 /home/nginx/domains/domain.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php(221): preg_match()
#1 /home/nginx/domains/domain.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/Subscriber.php(114): WP_Rocket\Engine\Optimization\DelayJS\HTML
->move_meta_charset_to_head()
#2 /home/nginx/domains/domain.com/public/wp-includes/class-wp-hook.php(303): WP_Rocket\Engine\Optimization\DelayJS\Subscriber->add_delay_js_script()
#3 /home/nginx/domains/domain.com/public/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#4 /home/nginx/domains/domain.com/public/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-optimization.php(104): apply_filters()`

**Comment by piotrbak** [comment]
Hello @jcatello have you already contacted our support team for further investigation?
