### ISSUE TITLE
Automatic compatibility for themes needing a "separate cache for mobile devices"

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4376]
**Is your feature request related to a problem? Please describe.**
Some themes use a different layout, menu system, widgets, ad spots, for mobile. 

We can add automatic compatibility just like we do with known plugins https://github.com/wp-media/wp-rocket/blob/develop/inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php

This will help reduce issues related to caching, RUCSS and CPCSS.

**Describe the solution you'd like**
Add a compatibility mechanism similar to the one related to mobile plugins that we can feed over time when themes need the `separate cache for mobile devices` to avoid issues.

**Describe alternatives you've considered**
N/A

**Additional context**
[Tickets](https://secure.helpscout.net/search/?query=tag%3Awpr%20separate%20mobile%20cache) tagged as `wpr separate mobile cache`
Potential themes spotted needed that so far: 
- [Woodmart theme](https://woodmart.xtemos.com/) uses a separate menu for mobile/desktop
- [Newspaper theme](https://tagdiv.com/) has an optional mobile theme
- [Avada theme](https://avada.theme-fusion.com/) uses different backgrounds, classes for mobile (hardcoded)
- [Total Themes](https://total.wpexplorer.com/) uses different classes for mobile vs. desktop. 
- [Xstore theme](https://xstore.8theme.com/) uses different layout and JS variables for mobile

**Comment by JerissCloudCenter** [comment]
Dear @DahmaniAdame 

Does this mean that enabling "Separate cache for mobile devices" is recommended for the themes spotted in this feature?

Thanks
Simon

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1732728449/315224/
The Woodmart theme was used.

**Comment by DahmaniAdame** [comment]
@jeriss-cloud-center yes :)

**Comment by JerissCloudCenter** [comment]
@DahmaniAdame Thanks for the confirmation

I just have one concern. I've seen in your documentation that enabling "Separate cache for mobile devices" may lead to some issues with Varnish on Cloudways environment. Is this still the case today with WP Rocket?

If yes, how are we supposed to "make sure that the Varnish configuration is set up to distinguish mobile requests from desktop requests"? How exactly?

![image](https://user-images.githubusercontent.com/87424739/147557115-193eb4b3-ddf3-4249-a820-b8d2c8f7c6ae.png)

**Comment by DahmaniAdame** [comment]
@jeriss-cloud-center we can't set how other cache tiers differentiate between mobile and desktop cache. 

For Varnish specifically, and if Cloudways allows modifying the config files, you can add the following to the `default.vcl` file - https://gist.github.com/marcofbb/99b7c1fdc14d2a262844a9d20d466ff0

It will basically create a different cache for each device type. So, each request will go initially to the origin, where WP Rocket has the desktop/mobile versions ready, and will store/serve the proper cache for it.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1736989193/315918/

**Comment by JerissCloudCenter** [comment]
@DahmaniAdame Is it mandatory to add this code in the `default.vcl` ? Modifying the `default.vcl` isn't available at every host (at least, not for mine). Therefore, I'm getting blocked. On one hand, I'd get a feature enabled automatically to ensure theme compatibility. On the other hand, I have host incompatibility with this feature enabled automatically, for which I can't apply the workaround because no direct access (and host support asks too high fee).

**Comment by DahmaniAdame** [comment]
@jeriss-cloud-center `default.vcl` is Varnish's configuration file. The directives should go there, I'm afraid.

Plugins can't change files outside of the premise of the WordPress environment. This is not something that can be controlled or automated from our end. 

You will need to check with the hosting provider to allow you to access the file. Or they can do it themselves for you if accessing the file is not permissible for whatever reason.

**Comment by webtrainingwheels** [comment]
I had 2 cases with Woodmart recently: 
- https://secure.helpscout.net/conversation/1747368659/317417/
- https://secure.helpscout.net/conversation/1736060054/315780/

**Comment by alfonso100** [comment]
Another case with woodmart: 
https://secure.helpscout.net/conversation/1889988975/343926

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1949610538/356018/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1965364903/359210/
Theme: Houzez
When RUCSS is used, mobile menu is not styled properly. Activating the separate cache for mobile devices fixes the issue.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2008590217/368335/
Woodmart

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/2014523790/369690?folderId=2135277
Woodmart theme.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2079159272/384785/
Woordmart

**Comment by piotrbak** [comment]
I'd say this is not relevant anymore after 3.16 and Separate Cache for Mobiles being enabled by default.
