### ISSUE TITLE
WebP notice shall be updated instantly when switching on/off with no need to refresh the page

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4380]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
When switch webP addon on / off , the notice doesn't change till the user refresh the page

**To Reproduce**
1. Go to Addons  => notice the current notice for WebP
2. Enable WebP
3. Refresh the page

**Expected behavior**
WebP notices changes instantly when switching webP on/off

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
