### ISSUE TITLE
Remove Unused CSS response is returning 409 or 500 errors

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4385]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.9.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In one case, RUCSS tree-shaker alternated between the following responses: 

```
Array
(
    [code] => 409
    [message] => The given data was invalid.
    [contents] => Array
        (
            [success] => 
            [exception] => Array
                (
                    [html] => Array
                        (
                            [0] => The html field is required.
                        )

                )

        )

)
```
```
Array
(
    [code] => 500
    [message] => Treeshaker failed!
    [contents] => Array
        (
            [success] => 
            [exception] => HTML could not be parsed.
        )

)
```
We couldn't narrow down the exact reasons why SaaS rejected processing in that particular case. 

From WP Rocket's side, the process goes through and is marked as successful. But nothing is stored on the `wp_wpr_rucss_used_css`.

**To Reproduce**
N/A

**Expected behavior**
If the page can't be processed on SaaS, the RUCSS process shouldn't go through and notify that SaaS wasn't able to process the request. 

We also should be able to narrow down the exact reason why SaaS wouldn't process specific URLs to better inform customers, and let them know if the issue can be fixed on their end (fixing faulty HTML for example).

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1617429785/291393?folderId=3864735
Slack - https://app.slack.com/client/T02RYMVKQ/C029G1B5HD2/thread/C029G1B5HD2-1632309930.144500

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Fixed in 3.11 as the SaaS is different.
