### ISSUE TITLE
Console error when click any more info link

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4389]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.4.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**To Reproduce**
1. Go to the file optimization tab
2. Click on more info link of any feature
3. Console error is there

**Expected behavior**
No console error when clicking more info

**Screenshots**
![Screenshot from 2021-09-28 06-01-24](https://user-images.githubusercontent.com/76941962/135037463-379dc811-8de5-4a6a-a67a-e017b7c4e992.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
I can't replicate the issue

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
I can reproduce the issue on test site

### Identify the root cause 🔴 
This is likely coming from Helpscout/Beacon side. But I don't have access anymore to Beacon configuration or Helpscout support, so we should have someone contact them to ask why this is happening.

**Comment by Mai-Saad** [comment]
The same error is displayed when clicking help beacon while being in any WPR tab
![Screenshot from 2021-12-01 08-21-20](https://user-images.githubusercontent.com/76941962/144184410-ad4ed03e-b97b-45fd-95d2-2002102f534b.png)

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
