### ISSUE TITLE
Disable CPCSS in post edit if it was excluded using helper plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4390]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10- alpha
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When excluding certain post types from CPCSS using helper plugin, it is expected that when we open post ->edit , the CPCSS option will be dimmed 

**To Reproduce**
1. Use the helper plugin here https://github.com/wp-media/wp-rocket-helpers/blob/master/static-files/wp-rocket-exclude-cpt-taxonomy-opt-css/wp-rocket-exclude-cpt-taxonomy-opt-css.zip to exclude post type i.e `product`
2. Enable CPCSS or load CSS async
3. Save settings
4. After CPCSS is generated, open the edit page for any product

**Expected behavior**
CPCSS or Load CSS Async id disabled

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
