### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WP_Rocket\Dependencies\Minify\JS when update WPR while RUCSS is in progress

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4391]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before 

**Describe the bug**
Fatal error added to the log file when upgrading plugin while having background process in progress

**To Reproduce**
1. Using version 3.9.4, Enable RUCSS
2. On the plugins page, update WPR to 3.9.4.1 or latest (While RUCSS is still in progress)
3. Check the debug.log

**Expected behavior**
No Error in debug.log file

**Screenshots**
[debug.log](https://github.com/wp-media/wp-rocket/files/7243468/debug.log)

**Additional context**
- Error is not affecting using of the dashboard nor the test site
- We need to check while CPCSS / preload is in progress too
- If we switched between branches in the same scenario without reactivate plugin, we will see different log error

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Other possible error when reproducing the issue:
[debug](https://github.com/wp-media/wp-rocket/files/7244024/debug.txt)
