### ISSUE TITLE
WooCommerce grouped products cache isn't cleared automatically

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4396]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.4`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

With WooCommerce, the cache of [grouped products](https://docs.woocommerce.com/document/group-bundle-products-woocommerce/#section-11) isn't cleared automatically, e.g. when placing an order.
This is because the `clean_post_cache` doesn't fire for these products, and can lead to issues such as stock numbers being inaccurate there.

**To Reproduce**

1. Create a grouped product.
2. Add one or more of the linked products in the cart.
3. Complete the order and checkout.
4. Check the folder of the cached product in `/cache/wp-rocket`. Its cache won't be cleared.

**Expected behavior**

Grouped products cache should be cleared when the linked products cache is cleared.

**Additional context**

The data that defines the children's products IDs for a grouped product is located in the `postmeta` table.
Also, a child product can belong in several grouped products. At the moment, WooCommerce doesn't offer a way to find the grouped product(s) a linked product belongs to. We'd need to run complicated queries to do so.

For the customer who reported the issue, I provided the following snippet which clears the cache of all grouped products after the order is placed:

```PHP
function clean_grouped_product_cache_after_order() {

	// Bail out if WP Rocket isn't installed.
	if( ! function_exists( 'rocket_clean_post') ) {
		return;
	}
	
	// Bail out if WooCommerce isn't installed.
	if( ! function_exists( 'wc_get_products') ) {
		return;
	}
	
	$grouped_product_ids = array();
	$grouped_product_ids = wc_get_products( array( 'type' => 'grouped', 'return' => 'ids', 'limit' => -1 ) ); // Find all grouped products IDs.
	
	if( ! empty( $grouped_product_ids ) ){
		// Clear the cache of all grouped products.
		foreach( $grouped_product_ids as $grouped_product_id ){
			// Clear the cache of each grouped product.
			rocket_clean_post( $grouped_product_id );
		} 
	}
}
add_action( 'woocommerce_payment_complete', 'clean_grouped_product_cache_after_order' );
```
Although it doesn't clear just the grouped products that it should, it gets the job done. We can additionally put some caching into it to avoid repeatedly querying the database.

Until this makes it to the core, I'll update the following helper plugin, so support and customers have an alternative:
https://github.com/wp-media/wp-rocket-helpers/tree/master/compatibility/wp-rocket-compat-wc-order-clean-cache

**Related ticket:** https://secure.helpscout.net/conversation/1622847633/292600/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1943500224/354659/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1966571981/359434?folderId=3864735

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
