### ISSUE TITLE
Delay JS - PREG_BACKTRACK_LIMIT_ERROR when moving meta to the head

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4397]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.10` but it should be the same with `>3.9.4`.
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On a customer's website, an `error 500` occurs for the homepage, when Delay JavaScript Execution is active.

This is because a `PREG_BACKTRACK_LIMIT_ERROR` error pop-ups here:
https://github.com/wp-media/wp-rocket/blob/0bdb9fced6dd474ce7f5e4b648a65b70d2500a0b/inc/Engine/Optimization/DelayJS/HTML.php#L220

This isn't happening on other pages.

The `backtrack.limit` is set to `1000000`.

![](https://i.vgy.me/dM1qHN.jpg)

**To Reproduce**

The raw HTML of the page is in the ticket's note. Using that in a template will likely trigger the error.

**Expected behavior**

We should fail gracefully when backtrack errors occur.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1645011344/297785/#thread-4801024582

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
another case: https://secure.helpscout.net/conversation/1651040982/299248?folderId=2683093

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1653821153/299936?folderId=2135277

**Comment by alfonso100** [comment]
another case here: https://secure.helpscout.net/conversation/1652627689/299643/
