### ISSUE TITLE
Mobile, Delay JS enabled, run click after scripts loaded

### ISSUE THREAD

**Issue by hogash** [wp-media/wp-rocket#4398]
**Is your feature request related to a problem? Please describe.**
This request is related to the Delay Javascript execution.

When browsing on mobile, on page load without any events (scrolling, tapping, clicking etc., basically scripts not loaded), when clicking on a hamburger menu button, the first click is loading the scripts. Only on 2nd click, the actual click event is fired.

**Describe the solution you'd like**
Something like "storing" the click event and firing it when the scripts finished loading.

**Comment by piotrbak** [comment]
Hello @hogash, we're already doing it in 3.10.2 version, but having some small issues. I'm closing this, since it is already implemented (might be reverted for a while though).
