### ISSUE TITLE
Google Fonts enhancement: Print Google Fonts CSS

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4399]
**Is your feature request related to a problem? Please describe.**
As part of the Google Fonts optimization, we enqueue the Google Fonts `<link>` right after the `<title>` tag.

It still counts as a request and will depend on how Google Fonts CDN will respond. 

Printing the CSS directly on the HTML gave the following results on the same page: 

![image](https://user-images.githubusercontent.com/1289174/135570540-0823bd3d-79ab-44e8-944b-5d8cb8e77733.png)

- Avoiding that additional request from happening and getting parsed by the browser (potential saving 170ms).
- The fonts are received much faster (potential saving 100ms) which can help enhance FOITs and LCP (if the element is text-based and depending on Google Fonts)

Preloading specific fonts didn't give a noticeable improvement. But it can still enhance specific cases by manually preloading fonts (will require https://github.com/wp-media/wp-rocket/issues/3276 to be enabled).

Implementations can be done after WP Rocket combines Google Fonts by using `file_get_contents()` to get `https://fonts.googleapis.com/css?` content and add it as an inline `<style>`.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
