### ISSUE TITLE
Update Avada compatibility with lazy load when WPML is used

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4400]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.9.4.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

We previously added compatibility to detect when Avada is using its Lazy Load for images feature to disable the one WP Rocket:

https://github.com/wp-media/wp-rocket/blob/da65dc571fcab9c2c3bc7fad6964d684202abae0/inc/3rd-party/themes/avada.php#L38

Reference - https://github.com/wp-media/wp-rocket/issues/3209

When Avada is used with WPML, and the language is changed, it will open a new array for fusion_options with the language as a suffix. Like `fusion_options_it` if the Italian language is picked.

Trying to check `lazy_load` stored on `fusion_options` will keep returning the value saved when the main language was selected. Regardless of the Lazy Load setting saved on Avada when switching to another language. 

**To Reproduce**
1. Latest Avada version
2. Set the `Avada > Options > Performance > Image Lazy Loading` to `avada` for the main language
2. Use WPML and change the language
![image](https://user-images.githubusercontent.com/1289174/135616402-4cc320a3-b3ba-44da-b67f-4cb5f6ab7471.png)
2. Change the language and choose `None` or `WordPress` on `Avada > Options > Performance > Image Lazy Loading`
3. Check WP Rocket lazy load for images
4. See that the option is grayed out

**Expected behavior**
We should test `lazy_load` where it's stored regardless of the language used by WPML + Avada.

**Screenshots**
N/A

**Additional context**
Changing `$avada_options = get_option( 'fusion_options' );` on https://github.com/wp-media/wp-rocket/blob/da65dc571fcab9c2c3bc7fad6964d684202abae0/inc/3rd-party/themes/avada.php#L38

To `$avada_options = get_option( 'fusion_options_it' );` fixes the issue (tested). 

A potential fix can be finding out what fusion_options array is currently in use when multilingual is activated (WPML or Polylang).

It seems to happen here on Avada: 

https://github.com/webwolfhosting/Avada/blob/master/includes/lib/inc/class-fusion-settings.php#L646-L683

```
	/**
	 * Sets the $lang property for this object.
	 * Languages are prefixed with a '_'
	 *
	 * If we're not currently performing a migration
	 * it also checks if the options for the current language are set.
	 * If they are not, then we will copy the options from the main language.
	 */
	public static function multilingual_options() {

		// Set the self::$lang.
		if ( ! class_exists( 'Fusion_Multilingual' ) ) {
			include_once 'class-fusion-multilingual.php';
		}
		$active_language = Fusion_Multilingual::get_active_language();

		if ( ! in_array( $active_language, [ '', 'en', 'all' ], true ) ) {
			self::$lang = '_' . $active_language;
		}
		// Make sure the options are copied if needed.
		if ( ! in_array( self::$lang, [ '', 'en', 'all' ], true ) && ! self::$lang_applied ) {

			// Get the options without using a language (defaults).
			$original_options = get_option( self::$original_option_name, [] );
			// Get options with a language.
			$options = get_option( self::$original_option_name . self::$lang, [] );
			// If we're not currently performing a migration and the options are not set
			// then we must copy the default options to the new language.
			if ( ! self::$is_updating && ! empty( $original_options ) && empty( $options ) ) {
				update_option( self::$original_option_name . self::$lang, get_option( self::$original_option_name ) );
			}
			// Modify the option_name to include the language.
			self::$option_name = self::$original_option_name . self::$lang;
		}

		// Set $lang_applied to true. Makes sure we don't do the above more than once.
		self::$lang_applied = true;
	}
```

Ticket - https://secure.helpscout.net/conversation/1646176049/298036/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1776653215/323862/

**Comment by girlie** [comment]
Related: https://secure.helpscout.net/conversation/1923648428/349105/

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.

**Comment by jekayode** [comment]
Another case: https://secure.helpscout.net/conversation/2742433161/519281?folderId=273766
