### ISSUE TITLE
Delay JavaScript Execution automatic exclusion for Anywhere Elementor Pro

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4402]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.9.4.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using Anywhere Elementor Pro with Delay JavaScript Execution, the AE grid elements are not clickable. 

Excluding the following fixes the issue: 

```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/jquery-migrate(.min)?.js
/anywhere-elementor-pro/build/index.js
```

**To Reproduce**
1. Use Elementor + Anywhere Elementor Pro
2. Build a grid of posts
3. See error

**Expected behavior**
The grid should be clickable without the customer having to add any exclusion.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1632650528/295072/
Exlcusion already adding to our Delay JavaScript Execution compatible help article - https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#anywhereelementorpro

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Fixed by backend in 3.13
