### ISSUE TITLE
Delay JS - PREG_BACKTRACK_LIMIT_ERROR when replacing attributes in scripts 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4406]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.10`
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**

A `PREG_BACKTRACK_LIMIT_ERROR` occurrs when trying to `parse()` the HTML:
https://github.com/wp-media/wp-rocket/blob/2d23ddb8cec8d3c2ea301c5f022ca8ffb87321ae/inc/Engine/Optimization/DelayJS/HTML.php#L159

**To Reproduce**

The raw HTML of the page is in the ticket's note. Using that in a template will likely trigger the error.

**Expected behavior**

We should fail gracefully when backtrack errors occur.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1649639891/298877?folderId=2135277

**Somehow related issue:** #4397 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Does it cause an error or a blank page when it happens for this case? Normally if there is failure, we should be catching it with the conditional that follows, and return the original HTML.

**Comment by vmanthos** [comment]
The conditional works fine, and no error is thrown nor a blank page is displayed/cached.

I mistakenly pasted the **Expected behavior** part from #4937. 😅 

The issue here is that Delay JavaScript Execution isn't applied. On the specific site the same goes for lazyload because of a `PREG_BACKTRACK_LIMIT_ERROR` here:
https://github.com/wp-media/wp-rocket/blob/61b63a5282105f66595b4bce8dbe7889398f0325/inc/Dependencies/RocketLazyload/Image.php#L23

Although I understand this isn't `our fault`, this is more about:
1. recording such cases to see how often they occur and 
2. discuss if it's possible to improve our processes. For example, when clearing the buffer from `<script></script>` using the `DOMDocument` class could be an alternative.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1710370950/311050/

In this case, they were also getting a `PHP Fatal error` here:
https://github.com/wp-media/wp-rocket/blob/100398b8216148f20bd90f83e731454f7b93eb60/inc/Dependencies/RocketLazyload/Image.php#L27

```
FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: preg_replace(): Argument #3 ($subject) must be of type array|string, null given in /www/example/public/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:27
Stack trace:
#0 /www/example/public/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(27): preg_replace('#<noscript>(?:....', '', NULL)
#1 /www/example/public/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(375): WP_Rocket\Dependencies\RocketLazyload\Image->lazyloadImages('<!DOCTYPE html>...', '', false)
#2 /www/example/public/wp-includes/class-wp-hook.php(303): WP_Rocket\Engine\Media\Lazyload\Subscriber->lazyload('<!DOCTYPE html>...')
#3 /www/example/public/wp-includes/plugin.php(189): WP_Hook->apply_filters('<!DOCTYPE html>...', Array)
#4 /www/example/public/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-optimization.php(104): apply_filters('rocket_buf" while reading response header from upstream, client: 91.160.5.101, server: biancolievito.it, request: "GET /scuola-di-pasticceria/pasta-frolla/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-biancolievitoit.sock:", host: "example.com", referrer: "https://example.com/scuola-di-crema-pasticcera/"
```

@Tabrisrp I think we should safeguard this as well. Do you want me to create a separate issue about this?

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1731822527/315029/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1803779422/329262/

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1866806214/340465/

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.

**Comment by suzoutlet** [comment]
Related: https://secure.helpscout.net/conversation/2630681041/498342/

**Comment by suzoutlet** [comment]
Related case: https://secure.helpscout.net/conversation/2922728288/557185
