### ISSUE TITLE
Filter to remove classes, urls, etc of Optimize CSS

### ISSUE THREAD

**Issue by pedddro** [wp-media/wp-rocket#4407]
Is there a similar filter of "pre_get_rocket_option_remove_unused_css_safelist" but for Optimize CSS? some themes need it to avoid a high CLS while using Optimize CSS such as Elementor. Excluding files does not currently help much. For some reason, the filter from RUCSS  `pre_get_rocket_option_remove_unused_css_safelist` does work for some classes on Optimize CSS.

**Comment by piotrbak** [comment]
Hello @pedddro Unfortunately, we have only filter that excludes whole files from the feature:
https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Engine/CriticalPath/CriticalCSS.php#L572

**Comment by pedddro** [comment]
Hey @piotrbak, somehow I managed to confirm that `pre_get_rocket_option_remove_unused_css_safelist ` works for Critical CSS.
Using Critical CSS: https://webvitals.dev/cls/g7Thk9T79AWFXyLu7IR4
![image](https://user-images.githubusercontent.com/18357571/200054037-86598d42-c562-417d-a4ad-3129509e8865.png)

Using Critical CSS and filter 

```
function cg_test_stuff( $safelist ) {
    $safelist[] = '#content';
    return $safelist;
}
add_filter( 'pre_get_rocket_option_remove_unused_css_safelist', 'cg_test_stuff' );
```

https://webvitals.dev/cls/S9L8oH61gXVzNV4RiJCy
![image](https://user-images.githubusercontent.com/18357571/200054101-7933f2e9-efd4-4ac4-8a9b-786a51ba9d0c.png)

**Comment by pedddro** [comment]
#5905

**Comment by pedddro** [comment]
#5905
