### ISSUE TITLE
Add a close button to conflicts warning notifications

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4411]
**Is your feature request related to a problem? Please describe.**
When WP Rocket has a conflict with a similar plugin, like LiteSpeed Cache, it shows a sticky notification that can't be removed.

`''WP Rocket: The following plugins are not compatible with this plugin and may cause unexpected results: LiteSpeed Cache''.`

Some customers might understand the risk and would prefer to dismiss the notification.

**Describe the solution you'd like**
Add a button to close the conflict notification.

**Describe alternatives you've considered**
Using the [WP Rocket | Remove Plugin Conflict Warning](WP Rocket | Remove Plugin Conflict Warning), but this helper plugin will dismiss all conflict notifications and not the specific plugin where the customer understands the risks of using it with WP Rocket.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1651406416/299366/

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/2075149866/383490/

**Comment by worldwildweb** [comment]
Not related to LiteSpeed Cache, but would it be possible to implement a button to close this notification as well:

> WP Rocket: The following plugins are not compatible with this plugin and may cause unexpected results: WP-Optimize - Clean, Compress, Cache

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
