### ISSUE TITLE
Delay JS - WooCommerce product images aren't displayed without user interaction in some cases

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4417]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.10`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

In #4077 to avoid excluding files when:
1. there is a **product image**
2. there is _not_ a **product gallery**

 @GeekPress suggested adding the following inline CSS:
```HTML
<style>.woocommerce-product-gallery{ opacity: 1 !important; }</style>
```
 
This is done here:
https://github.com/wp-media/wp-rocket/blob/61b63a5282105f66595b4bce8dbe7889398f0325/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L541

When WooCommerce's styles have been dequeued by a theme, our CSS is not added, and the product isn't displayed until a user interacts with the page. 

The solution to this is manually adding the respective JavaScript exclusions.

**To Reproduce**

1. Install the [Storefront](https://wordpress.org/themes/storefront/) theme, which dequeues WooCommerce's styles.
2. Enable Delay JavaScript Execution without adding any exclusions.
3. Create a product without adding a gallery.
3. Visit the product's URL. The product's image won't be visible until there is user interaction.
4. Repeat the test using the [Ashe](https://wordpress.org/themes/ashe/). The image will be displayed without interaction.

**Expected behavior**

We should follow the initial idea about adding the script without relying on the `woocommerce-layout` handler.

**Additional context**

**Slack convo:** https://wp-media.slack.com/archives/C43T1AYMQ/p1633466763022700

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
If I understand correctly, instead of using the CSS workaround, we would need to always exclude the additional scripts from delay JS, even when there is no gallery. Is that correct?

**Comment by vmanthos** [comment]
I think we can still use the CSS workaround if we don't add `woocommerce-layout` as a dependency.

**Comment by remyperona** [comment]
We have 2 possible approaches there, not sure if there is one really better than the other.

**First solution**
Change the hook to `wp_head`, and echo the custom CSS instead of using `wp_add_inline_style()`.

**Second solution**
Enqueue a fake style like `wp_enqueue_style( 'rocket-woocommerce-layout-fix' )`, and change the handler for `wp_add_inline_style( 'rocket-woocommerce-layout-fix' )`

Both solutions remove the dependency on `woocommerce-layout`.

For either of those, I think the effort is an `[S]`, to adapt the code and the related tests.
