### ISSUE TITLE
Delay JavaScript Execution compatibility with TravelTour (and all GoodLayers themes)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4419]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript Execution is used with the TravelTheme, the carousel slider is not showing even after user interraction.

**To Reproduce**
1. Use the [TravelTour](https://themeforest.net/item/travel-tour-travel-tour-management-system-wordpress-theme/19423474) theme
2. Add a slider carousel
3. Activate the Delay JavaScript Execution

**Expected behavior**
The slider should work properly when Delay JavaScript Execution is activated.

**Screenshots**
N/A

**Additional context**
Excluding the following fixes the issue: 

```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js 
/jquery-migrate(.min)?.js 
/goodlayers-core/plugins/script.js 
/goodlayers-core/include/js/page-builder.js
```

Props to @camilamadronero 

The same exclusions should be applicable to all Good layers themes where the `goodlayers-core` is used as a framework ([70 themes](https://themeforest.net/user/goodlayers/portfolio)).

Ticket - https://secure.helpscout.net/conversation/1651016587/299237/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Were you able to see any errors in the JS console?

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
