### ISSUE TITLE
Minor layout issue on auto-disabled "Combine JS" green notification

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#4422]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
There is a minor layout issue on the green notification displayed below Combine JS (when Delay JS is enabled).

**To Reproduce**
1. Go to Optimize CSS/JS
2. Enable Delay JS
3. Check Combine JS green notification

**Expected behavior**
The green notification should be aligned, just like the other green notifications below/up on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/87424739/137193222-33181539-a7e2-4696-84b0-36390931ff4d.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
