### ISSUE TITLE
Delay JavaScript Execution compatibility with GravityForms when using Recaptcha

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4425]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When GravityForms is using Recaptcha, enabling Delay JavaScript Execution creates the following console error and the form stops working:

![image](https://user-images.githubusercontent.com/1289174/137280037-dc4e8272-f267-4c76-8d47-203624c495ea.png)

Update: the setup used invisible ReCaptcha V3 +  Gravity Forms reCAPTCHA add-on.

**To Reproduce**
1. Add GravityForms with Recaptcha
2. Enable Delay JavaScript Execution
3. Go to the form page

**Expected behavior**
GravityForms should work properly out of the box when Delay JavaScript Execution is enabled.

**Screenshots**
N/A

**Additional context**
Excluding the following from Delay JavaScript Execution fixes the issue: 

`recaptcha`

Added exclusion to - https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#gravityforms

Ticket - https://secure.helpscout.net/conversation/1654444194/300057/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame I think that `recaptcha` exclusion is too general to be included in auto exclusion list. Do we happen to have a different string that would be more unique?

**Comment by GeekPress** [comment]
We can exclude this pattern to be safe: `gforms_recaptcha_`

**Comment by jeriss-cloud-center** [comment]
I use GravityForms with reCaptcha setting, and I haven't excluded anything.
But it works all fine.

Are you sure this is necessary?
Test site : https://wordpress-573315-2187485.cloudwaysapps.com/commandes/

Please ensure this before deploying this
Thanks
