### ISSUE TITLE
Wp-rocket interference with jet woobuilder plugin (please check)

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4427]
hello
The jet woobuilder plugin has a feature to display Recently Viewed products. But when the wp-rocket plugin is enabled, the recently observed feature has a problem.
This problem is such that if the user sees 1 product, 3 products will be added to the list. Or not added at all.
But when we disable the wp-rocket plugin, the problem is solved.
I have already reported this to you(#3990), you asked me to ask the creators of jet woobuilder where the problem is, so that you can fix it in the wp-rocket plugin.
I asked them about the problem, and they replied : We use woocommerce_recently_viewed cookie to get recently viewed products.

Please fix this problem if possible. it's too important, thank you

**Comment by piotrbak** [comment]
Hello! It seems that you can resolve your problem by following this guide:
https://docs.wp-rocket.me/article/1313-create-different-cache-files-with-dynamic-and-mandatory-cookies

I'm not closing this issue to see if we're getting more requests from customers.

**Comment by 79ho3ein** [comment]
hello @piotrbak, Thank you for your answer.
I experience this problem on all my websites. Many co-workers also have the same problem. Unfortunately there is this interference. Is it possible to solve this problem in wp-rocket?
As I said above, I talked to the developer of jet woobuilder. They said the problem is with the wp-rocket.
I hope this problem can be solved.

thank you

**Comment by piotrbak** [comment]
The solution for your problem is described step by step in the article. After following those steps, you'll end up with a helper plugin ready to be installed on all sites that are experiencing the issue. If you have problems with implementation, you can reach our support via https://wp-rocket.me/contact/

As you can see we have pretty many issues reported, that's why we need to prioritize them carefully. Thank for you understanding.

**Comment by 79ho3ein** [comment]
thank you

**Comment by 79ho3ein** [comment]
hi again @piotrbak 
I solved this problem. I deleted the cookie (woocommerce_recently_viewed) and the problem was solved : https://prnt.sc/JhGTbRPbnGlI

So I think it would be good if you remove this cookie from the cache by default, so that other users do not have this problem by installing the wp-rocket plugin. 

thank you
