### ISSUE TITLE
Native Lazy load fallback to LazyLoad.js

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [wp-media/wp-rocket#4429]
**Is your feature request related to a problem? Please describe.**
Since native lazy load is not yet supported by all browsers, you should choose between the added overhead of LazyLoad.js compatible with most browsers, or the lightweight native implementation not available on all.

Would be nice that WP Rocket manages if the browser supports native lazy loading images and if not, use the LazyLoad.js but if supported. go native.

**Describe the solution you'd like**
Enable Lazy Load for images instead of a checkbox could be a tristate: Yes (same as checked); No (same as unckecked); Auto (Use native if available and if not go to Lazyload.js)

**Comment by remyperona** [comment]
You have the possibility to do so using the `rocket_use_native_lazyload` filter `add_filter( 'rocket_use_native_lazyload', '__return_true' );`.

This will put the lazyload into native mode, where it will delegate the lazyloading to the browser if it's supported, or do a JS-based lazyload if the browser doesn't support native yet.

It's a feature that is included in the lazyload script that we use: https://github.com/verlok/vanilla-lazyload#mixed-native-and-js-based-lazy-loading
