### ISSUE TITLE
is_file(): open_basedir restriction in effect. when using is_file()

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4430]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When `open_basedir` is on, the error log will add warnings about failing to find the path.

```
"is_file(): open_basedir restriction in effect. File(/* <![CDATA[ */
var ajax_object_immowerft = {"ajax_url":"https:\/\/<domain>\/wp-admin\/admin-ajax.php"};
var ajax_object_auto_expose = {"ajax_url":"https:\/\/<domain>\/wp-admin\/admin-ajax.php"};
var ajax_object_immowerft_maps_pin = {"ajax_url":"https:\/\/<domain>\/wp-admin\/admin-ajax.php"};
var ajax_object_immowerft_kontakt = {"ajax_url":"https:\/\/<domain>\/wp-admin\/admin-ajax.php"};
/* ]]> */;) is not within the allowed path(s): (/web:/private:/tmp:/var/www/<domain>/web:/srv/www/<domain>/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:
/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom://log/wp-debug.log:/log/wp-debug.log:/usr/bin/du:/usr/bin/cut)"
at `./wp-content/plugins/wp-rocket/inc/Dependencies/Minify/Minify.php:457`.

Callstack:
is_file,
WP_Rocket\Dependencies\Minify\Minify->canImportFile,
WP_Rocket\Dependencies\Minify\Minify->load,
WP_Rocket\Dependencies\Minify\Minify->add,
WP_Rocket\Engine\Optimization\Minify\JS\Combine->add_to_minify,
WP_Rocket\Engine\Optimization\Minify\JS\Combine->get_content,
WP_Rocket\Engine\Optimization\Minify\JS\Combine->optimize,
WP_Rocket\Engine\Optimization\Minify\JS\Subscriber->process,
WP_Hook->apply_filters,
apply_filters(`rocket_buffer`),
WP_Rocket\Buffer\Optimization->maybe_process_buffer,
ob_end_flush,
wp_ob_end_flush_all,
WP_Hook->apply_filters,
WP_Hook->do_action,
do_action(`shutdown`),
shutdown_action_hook
```

This is resulting from sending a files contents `$path` to `is_file()`. 

https://github.com/wp-media/wp-rocket/blob/7aeacf9102bdcde51a020984c6592d13c267720d/inc/Dependencies/Minify/Minify.php#L457

A sanity check could be used to prevent sending a non-path to the `is_file()`.

**To Reproduce**
1. Use a system where `open_basedir` is on
2. Minify CSS or JS.
3. See error

**Expected behavior**
No warnings should result from using is_file().

**Screenshots**
N/A

**Additional context**
We are already using `@` before the `is_file()` to suppress errors/warnings, but still, it will show the warning. 

Ticket - https://secure.helpscout.net/conversation/1657738864/300592/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
I think this is related to wrong paths being used somewhere in WP config or wrongly configured hosting. 

@Tabrisrp do you think we can prevent this from happening?

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
