### ISSUE TITLE
Delay JavaScript Execution automatic compatibility with WooCommerce Stripe Gateway

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4434]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [WooCommerce Stripe Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) is used with Delay JavaScript Execution, the Stripe Buy Now button is not showing even after user interaction and the following console errors show up.

![image](https://user-images.githubusercontent.com/1289174/137582955-b5664844-1032-4f55-af49-ef1d874859d4.png)

Excluding the following fixes the issue: 

```
js.stripe.com
```

**To Reproduce**
1. Use WooCommerce Stripe Gateway
2. Enable Delay JavaScript Execution
3. Go to a product page

**Expected behavior**
Stripe Buy Now button should show properly without any console errors.

**Screenshots**
Added above.

**Additional context**
This might apply to all WooCommerce Stripe plugins that add the Stripe Buy Now button.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Couldn't reproduce it on the test site using 3.10.2, @DahmaniAdame Appreciate adding a video or link if possible.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
