### ISSUE TITLE
Delay JS/Remove Unused CSS  - Onboard Scanner/Compatibility Scanner

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4435]
**Is your feature request related to a problem? Please describe.**
Introuduce a scanner based if user select **Auto / Manual** compatibility.
**Auto:** Which will check installed plugin/themes and will look for compatibility in WP Rocket server, fetch exclusion list and store in exclude field (It will run only once after on, include an option that user can re-run with spinner/suitable icon).

Now adding every plugin/themes compatibility making plugin sizes larger. it will reduce also some work like releasing every new version with exclude compatibility and user have to wait for this long

**Manual:** It will there for thoose user whom want to stay with there own exclusion or zero exclusion. (this one should not be resetted if any user switch to auto)

**Describe the solution you'd like**
Onboard Scanner/Compatibility Scanner

**Describe alternatives you've considered**
As fallback keep an way in rocket website that user will select plugin/themes and generate an exclude list json/list, and simply will import/add in delay js exclude field.

**Additional context**
It may helpful also with Remove Unsed CSS Feature

**Comment by mehedihasanziku** [comment]
somehow related to #3602 , but with more specific objective.
maybe also help here #5038

**Comment by piotrbak** [comment]
Introduced in 3.13
