### ISSUE TITLE
Get rid of "Clear OPcache" action button

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#4439]
**Is your feature request related to a problem? Please describe.**
This improvement intends to simply the usage of WP Rocket by getting rid of an unnecessary action button from the Quick Actions : Clear OPcache

![image](https://user-images.githubusercontent.com/87424739/138421687-01273ee9-49c9-45c7-924c-1b7d8f975396.png)

**Describe the solution you'd like**
An average user (which is the target audience of your plugin) doesn't even know what is OPcache. I think there is no added-value to have different buttons for :
- clear OPcache
- clear all cache files

**Describe alternatives you've considered**
I've been using WP Rocket for years now and I've never found its interest. I think the "OPcache" clearing may just simply be merged into "all cache files" clearing.

**Additional context**
It's always a loss of time to hit both buttons even if I believe that the "clear all cache files" should be sufficient to also clear the OPcache). An average user like me would still hit both buttons to ensure that everything is cleared.

Also, if you look at competitors like FlyingPress, this doesn't exist neither as there is no need for it.

![image](https://user-images.githubusercontent.com/87424739/138324736-130e823f-4687-45b9-b56a-405d54a31f6f.png)

**Comment by GeekPress** [comment]
Hi @jeriss-cloud-center 

Thanks for your suggestion.

Indeed you are right, it seems logical to merge both. If we clear OPcache, we also need to clear the caching files. Let's do these actions together to have one action required only.

**Comment by remyperona** [comment]
@piotrbak Do we even want to keep the OPCache clear functionality?

It made sense when WordPress was not handling that for updates of core/themes/plugins, but now that it's in core, I'm not sure there is any value remaining here.

**Comment by piotrbak** [comment]
@Tabrisrp What about the situation when customer is making changes to the PHP code without updating any part of the WP? Does it make sense to clear the OPCache then?

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `inc/common/purge.php`, function `do_admin_post_rocket_purge_cache()`, add a call to `rocket_reset_opcache()` after the call to `rocket_clean_domain()`.

In `inc/common/admin-bar.php`, remove the section adding the link to purge OPCache (l174-197)

In `inc/views/settings/page-sections/dashboard.php`, remove the section adding the link to purge OPCache (l173-197)

### Estimate the effort ✅
Effort `[XS]`

**Comment by piotrbak** [comment]
@Tabrisrp I've scanned our HelpScout to see how and if our customers are using this option. 

Let's remove the feature and deprecate the function, just to make sure that we won't cause any fatal errors.

**Comment by 79ho3ein** [comment]
+1

**Comment by chrismask** [comment]
What is this shit? You are not fucking Apple to remove uNusED things by target audience. Your target audience is not only dumbasses but also programmers and people that need and want all the extra things. Personally, if I purge OPcache, my Google Maps API has to request again some details every time a page is accessed (if not already cached) and on average I have to pay 50$ daily if opcache is automatically purged like this. Get this back immediately and stop removing things and sImPLiFyINg the plugin, which is completely the wrong direction. I thought about leaving rocket because nothing new has come in last months, only exclusions and removal of things. There are plenty of things to be added to optimize sites performance ex. perfmatters which can block certain scripts on certain pages. But yes your tArGeT aUdiENcE are people who dont know how to turn off their pc, what am I asking...

**Comment by doodelybeep** [comment]
> What is this shit? You are not fucking Apple to remove uNusED things by target audience. Your target audience is not only dumbasses but also programmers and people that need and want all the extra things. Personally, if I purge OPcache, my Google Maps API has to request again some details every time a page is accessed (if not already cached) and on average I have to pay 50$ daily if opcache is automatically purged like this. Get this back immediately and stop removing things and sImPLiFyINg the plugin, which is completely the wrong direction. I thought about leaving rocket because nothing new has come in last months, only exclusions and removal of things. There are plenty of things to be added to optimize sites performance ex. perfmatters which can block certain scripts on certain pages. But yes your tArGeT aUdiENcE are people who dont know how to turn off their pc, what am I asking...

THANK YOU, about time someone said something...

**Comment by DarkAllMan** [comment]
Please bring this back! See above!

**Comment by creative-minded** [comment]
Because there are people who do not understand the function of opcache
It is not necessary to remove the function completely from the plugin..
So prefer to keep it in wp-rocket !

**Comment by GeekPress** [comment]
If you need to purge OPcache, we are recommended you to use [WP OPcache](https://wordpress.org/plugins/flush-opcache/) plugin which will also provide you a lot of useful data about OPcache that WP Rocket could not offer you.

**Comment by GeekPress** [comment]
> if I purge OPcache, my Google Maps API has to request again some details every time a page is accessed (if not already cached) and on average I have to pay 50$ daily if opcache is automatically purged like this. 

I think you didn't understand correctly what we are doing now: WP Rocket **doesn't purge OPCache anymore**. So if I understand well, thanks to that, we are saving you $50 daily ;)
