### ISSUE TITLE
If RUCSS is cleared, there is no "Renegerate RUCSS" action button available

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#4440]
**Is your feature request related to a problem? Please describe.**
Assume that you enable RUCSS, the process starts to create the Used CSS.

Once it's completed, you may need to redo the process (in case you've changed the CSS on your site). In this case, you have a "Clear RUCSS" button but there is no "Regenerate RUCSS" just like we have in CPCSS.

**Describe the solution you'd like**
Transform the button "Clear RUCSS" into a "Renegerate RUCSS" (similar behavior as CPCSS)

**Describe alternatives you've considered**
Currently, the only alternative is to (1) disable RUCSS, then (2) re-enable RUCSS
This is not a good process.

**Additional context**
![image](https://user-images.githubusercontent.com/87424739/137878552-4f9dda96-a833-4b42-a9ae-f2e61cd91e52.png)

**Comment by engahmeds3ed** [comment]
Thanks, @jeriss-cloud-center for your contribution.

I want to make sure that we are on the same background so I will explain in depth the RUCSS feature life cycle.

## RUCSS life cycle

When a user visits a page with an expired cache, WP Rocket will check if any resource changed its content then send it to our warmup process, then will create used CSS for this page.

## So what happens when the admin clicks on `Clear RUCSS`?

WP Rocket will clear cached files and also remove cached used CSS so the next visit to the page, we will do the checks mentioned above.

So for this reason, I think we don't need a button to regenerate used CSS

**Comment by JerissCloudCenter** [comment]
Dear @engahmeds3ed 

Thanks for the answer. I'd like to clarify few points just to be sure.

1) I understand that new Used CSS will be generated if a user visits a page whose cache has expired. But assume that me (as Admin) I'm changing the CSS of the header for instance or anything on the site layout. In this case, the cache is not expired, so the new Used CSS will not be regenerated. It means I must regenerate myself (as Admin) the Used CSS. For this, the issue remains that there is not Regenerate Used CSS. The only alternative is to disable the feature "Optimize CSS", save, re-enable it and save again. That's why I belive "Clear Used" CSS should become "Regenerate Used CSS"

2) Also, imagine a website with all the features on (Preload, CPCSS and RUCSS...). Check the Dashboard and see how many action buttons are being added : just too many. It becomes confusing for regular users who don't know anymore (when wanting to clear all caches and restart all caches/css), which button to even start with... Should I clear OPcache first? Should I clear all cache files first? Should I clear Used CSS first? Should I regenerate CPCSS first? It really is confusing I'm afraid.

I'm just giving an opinion. I don't know if other users feel the same, but I think the plugin's overall functionning can be simplified. That's why I also raised this ticket #4455 as well.

Thanks

**Comment by engahmeds3ed** [comment]
Really we appreciate your contribution here and are glad to read your welcomed suggestions.

> I understand that new Used CSS will be generated if a user visits a page whose cache has expired. But assume that me (as Admin) I'm changing the CSS of the header for instance or anything on the site layout. In this case, the cache is not expired, so the new Used CSS will not be regenerated. It means I must regenerate myself (as Admin) the Used CSS. For this, the issue remains that there is not Regenerate Used CSS. The only alternative is to disable the feature "Optimize CSS", save, re-enable it and save again. That's why I belive "Clear Used" CSS should become "Regenerate Used CSS"

What will happen if you just cleared the cache by clicking on the Clear Cache button?
I think this will force removing the cache and load the new used CSS once the cache file is created.

>Also, imagine a website with all the features on (Preload, CPCSS and RUCSS...). Check the Dashboard and see how many action buttons are being added : just too many. It becomes confusing for regular users who don't know anymore (when wanting to clear all caches and restart all caches/css), which button to even start with... Should I clear OPcache first? Should I clear all cache files first? Should I clear Used CSS first? Should I regenerate CPCSS first? It really is confusing I'm afraid.

@wp-media/productrocket , this is a product team's decision.

**Comment by GeekPress** [comment]
Hi @jeriss-cloud-center 

A `Regenerate Used CSS` button isn't required as the `Clear UsedCSS` button is the only action required. The UsedCSS is automatically generated once the caching file will be re-generated.

You can Clear UsedCSS and Preload the cache.
