### ISSUE TITLE
Lazyload isnot working correctly when background image URL contains special char

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4443]
- Made sure you’re on the latest version => 3.10.1 and native LL
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Lazyload not handling background image with URL containing special Char correctly

**To Reproduce**
Precondition:
- Having page using a background image with special Char i.e 
```
<div style="background-image: url('https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/(plaska)+ziemia_xD flat earth (lol).PNG');">
  You can specify background images<br>
  for any visible HTML element.<br>
  In this example, the background image<br>
  background image behaves.
  </div>
```
1. Enable LL images
2. Open the page and check the source
3. Image Url changed to `'https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/(plaska`

**Expected behavior**
Handle images with special char correctly as standard images

**Screenshots**
After LL

![LLversion](https://user-images.githubusercontent.com/76941962/138081837-cde74484-940a-482e-89bc-56c9fd1b48eb.jpg)

**Additional context**
- This URL is already handled for standard images
- Test page: https://new.rocketlabsqa.ovh/images_background/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
There is another case.

when alt has `<br>`  
`alt="A quick <br>  dog"`
it breaks like your case. please consider this case also.

Thanks.

**Comment by piotrbak** [comment]
@mehedihasanziku This is a separate issue, please find my explanation here:
https://github.com/wp-media/wp-rocket/issues/3502#issuecomment-769038333

And here you can see a correct workaround:
https://github.com/wp-media/wp-rocket/issues/3502#issuecomment-769020133

**Comment by mehedihasanziku** [comment]
> @mehedihasanziku This is a separate issue, please find my explanation here: [#3502 (comment)](https://github.com/wp-media/wp-rocket/issues/3502#issuecomment-769038333)
> 
> And here you can see a correct workaround: [#3502 (comment)](https://github.com/wp-media/wp-rocket/issues/3502#issuecomment-769020133)

Thanks, I haven't checked that case and it was little old case for me. 

Instead of messing with client alt tag i provided an solution that replace **`<br>`** tag using replacer (specific case) `rocket_buffer`

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
