### ISSUE TITLE
Lazy Load for images and/or delay JS stop background video to play on Safari 

### ISSUE THREAD

**Issue by nejko1** [wp-media/wp-rocket#4446]
**Describe the bug**
Tested and WP rocket plugin is the culprit. I have Crocal WP theme by Euthemians and cover video that plays as a background under header, at the top of the content. MP4 video plays normally on other browsers but not on Iphone or Mac (Safari) if WP Rocket's Lazy Load and/or Delay JS are activated. If they are deactivated video starts working. Video also works if the theme's own lazy load feature is utilized for images instead of the WP Rocket's (but this doesn't help if also Delay JS is activated at the same time).

**To Reproduce**
Add video as:
```
<div class="eut-background-wrapper">
<div class="eut-bg-video eut-html5-bg-video" data-video-device="yes">
<video data-autoplay="" loop="loop" muted="muted" autoplay="autoplay" preload="auto" style="max-width: 1000%; height: 725px;"><source src="https://example.com/example.mp4" type="video/mp4">
</video></div></div>
```

Enable Lazy Load for images and/or delay JS.

**Expected behavior**
Video will not play on Safari. The area will be blank or image will be frozen. Other browsers will play it normally.

**Additional context**
Quite interestingly, if I specifically exclude videos form Lazy Load media they sometimes don't work also on other browsers ... The theme was recently updated for the Safari 15 video issues and again, this is not the issue, as it works fine also on Safari if WP Rocket is deactivated. No CDN active.

Possibly related to: #114 (The originally proposed solution doesn't work for me).

**Comment by camilamadronero-zz** [comment]
Hey!

I'm taking care of this request via support ticket ([internal link](https://secure.helpscout.net/conversation/1670221481/303079)). We'll troubleshoot the issue and continue the communication over there.

Thank you!
