### ISSUE TITLE
CDN srcset rewrite not rewriting images when a faulty markup is used

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4448]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using the CDN feature with a retina image with a missing variant, the image is not processed. 

```
<img src="https://example.ext/wp-content/uploads/image-src.png" srcset="https://example.ext/wp-content/uploads/image-src.png 1x, 2x">
```
Notice the missing image URL for the 2x.

Will be processed as: 

```
<img src="https://cdn.example.ext/wp-content/uploads/image-src.png" srcset="https://example.ext/wp-content/uploads/image-src.png 1x, 2x">
```

**To Reproduce**
1. Add an image with the above markup.
2. Enable CDN rewrites
3. See error

**Expected behavior**
No errors should result from using the CDN feature. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/138444252-43a8d139-ba56-438e-9157-fd5e7305f19b.png)

**Additional context**
Related ticket - https://secure.helpscout.net/conversation/1670888276/303191/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Reproducible on test site srcset is not rewritten to CDN (no visual UI problem)

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
