### ISSUE TITLE
Add in the text whether we can refresh the screen (or not)

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#4450]
While the process of RUCSS is ongoing, users don't know if they can safely refresh the page, or navigate from the WP Rocket settings.

We should add short text explaining this.

![image](https://user-images.githubusercontent.com/2566224/138479699-29136084-7701-477b-bfdd-532fc5159c54.png)

**Comment by juricazuanovic** [comment]
Related ticket: https://secure.helpscout.net/conversation/1671444202/303271?folderId=3572910

**Comment by piotrbak** [comment]
Fixed in 3.11, there's no progress bar anymore
