### ISSUE TITLE
Excluded JavaScript Files for JetMenu

### ISSUE THREAD

**Issue by AlexandrSydoruk** [wp-media/wp-rocket#4453]
Hello.
We use on site wp rocket
We made the menu using the JetMenu plugin in the Jupiter X theme. 
But when Delay JavaScript Execution is enabled in the wp-rocket plugin, 
there is a problem with menu. Submenus do not open on hover.
How i can add the Excluded JavaScript Files for JetMenu?
Correct this issue if possible. 
This is too important, thank you!

**Comment by piotrbak** [comment]
Hello @AlexandrSydoruk please contact our Support Team using the following URL:
https://wp-rocket.me/support/

They will be able to investigate your problem.
