### ISSUE TITLE
Clearing cache should also clear used CSS in some cases

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4454]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some themes might use variable inline CSS.

Example from the Woodmart theme: 

```
<style>#wd-6173ac87bcf16 .info-box-title {color: rgba(255, 255, 255,1) !important;}</style>	
```

After each cache refresh, the string `#wd-6173ac87bcf16` will change, which will make any style picked up by RUCSS not be applied because that specific selector won't be used anymore. 

**To Reproduce**
1. Use the Woodmart theme
2. Edit the header and add a custom header with the "Infobox" element, and customize the look (color, fonts)
3. Check the inline style tied to the infobox element
4. Refresh the cache after a while to see that the selector has been changed

**Expected behavior**
RUCSS should always reference the right selectors, even in these cases.

**Screenshots**
N/A

**Additional context**
We could have a compatibility file to truncate the used CSS table before proceeding to clear the cache on specific themes/plugins.

For instance, the only theme I came across using that is the Woodmart theme.

Ticket - https://secure.helpscout.net/conversation/1667301045/302437/

Affected themes/plugins: 
- Woodmart
- Rehub
- Flatsome
- Kadence
- WPML

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
Related #4166

**Comment by DahmaniAdame** [comment]
Another theme spotted: Rehub

It ties some styles with a variable ID: 

```
#wpsm_banner_4725770081635487445 .wpsm-banner-image {
  background-color: #cecece;
  background-image: url(https://domain.ext/wp-content/uploads/2020/11/image.jpg);
  height: 20px
}
```

Ticket - https://secure.helpscout.net/conversation/1677217367/304076/

**Comment by DahmaniAdame** [comment]
Another theme spotted: Flatsome

They use variable IDs: 

```
<div class="banner has-hover has-parallax" id="banner-1979161772"></div>
```

```
<div id="page-header-1135992358" class="page-header-wrapper"></div>
```

Ticket - https://secure.helpscout.net/conversation/1692261669/306845/

**Comment by DahmaniAdame** [comment]
Another scenario to cover is when using mandatory cookies (WPML for example). 
The cache is renewed whenever the mandatory is not set. This will implicate the necessity of clearing the used CSS whenever a new visitor triggers a new cookie creation.

**Comment by vmanthos** [comment]
Another case where this is necessary and can/should be tackled easily is when a user is using WordPress's customizer to add or change CSS rules. If the used CSS for a page has been created and there aren't any unprocessed resources, the additions/changes won't be included in the used CSS until that's cleared.

We can use the `customize_save` hook to clear the used CSS along with HTML files which we are already doing.

**Related ticket:** https://secure.helpscout.net/conversation/1691713445/306772?folderId=2135277

**UPDATE**
To tackle cases with dynamic inline CSS selectors, we can create a hash of inline CSS and store that in the database for each page. When `rocket_buffer` fires and the `treeshake()` [method](https://github.com/wp-media/wp-rocket/blob/a5d2dbc7348dd99fc6e50027d7a955eb0a338cf0/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L130) runs, we can check if the hash has changed, and if it has, we should send the HTML to the SaaS. Otherwise, use the existing used CSS.

**Comment by DahmaniAdame** [comment]
Another one: Kadence theme

Uses dynamic classes for containers: 
```
<div class="wp-container-62034603b5d0a wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link has-background" href="#" style="border-radius:4px;background-color:#b5ab9f">learn more</a></div>
</div>
```
Ticket - https://secure.helpscout.net/conversation/1770437176/322376

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1788658765/326421
Theme: Jevelin
The theme is extensively using dynamic selectors: 

```
<div class="sh-heading" id="heading-a7B4xo2bnl"></div>	
<style type="text/css">#heading-a7B4xo2bnl .sh-element-margin {}@media (max-width: 1024px) {#heading-a7B4xo2bnl .sh-heading-content {font-size: 15px!important;}}#heading-a7B4xo2bnl .sh-heading-content {font-size: 20px;font-weight: 700!important;letter-spacing: 6px;color: #cb6827;}#heading-a7B4xo2bnl .sh-heading-content,#heading-a7B4xo2bnl .sh-heading-additional-text {}</style>
```

**Comment by GeekPress** [comment]
@piotrbak The best solution should be to add conditions in the safelist back-end instead of adding compatibilities into the plugin, what do you think?

**Comment by piotrbak** [comment]
@GeekPress Not sure if that's possible, it's about preserving whole inline styles in the source. 🤔

**Comment by piotrbak** [comment]
Closing, since it's resolved and we'll have a backend for safelisting.
