### ISSUE TITLE
Simplify the usage of CPCSS and RUCSS

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#4455]
**Is your feature request related to a problem? Please describe.**
The development of the new CSS features (CPCSS / RUCSS) have considerably increased the difficulty to use WP Rocket, and I believe it can be simplified further.

**Describe the solution you'd like**
Along with the simplification suggested in #4439 and with the issue raised in #4454, I suggest the following.

Let's start from the premise that when the entire cache is cleared, the CPCSS / RUCSS also needs to be cleared and regenerated to avoid any issue on the website. Why? Because if the cache needs to be cleared, it's necessarily because things have changed on the website, and therefore new CSS generation should be done too.

Consequently, the CPCSS / RUCSS action buttons could be removed from the dashboard and their generation could be triggered automatically along with cache preloading. As a result, the "cache preloading" should be enabled by default and its option removed from the settings. I believe most users enable this feature since it's a must-have for speed.

**Describe alternatives you've considered**
N/A

**Additional context**
This simplification will help a lot in making WP Rocket much easier to use with less troubles. Users will always be sure to have a new CPCSS / RUCSS everytime they empty the entire cache and preload new cache. Emptying the cache shoud clear the CPCSS/RUCSS, and preloading cache should generate new CPCSS / RUCSS.

Finally, if you look at a competitor like FlyingPress, there is only "purge" and "preload" buttons. That's indeed much more simple to use.

![image](https://user-images.githubusercontent.com/87424739/138567823-451e211f-99ad-4f6f-8c56-a15d86a3cf2f.png)

**Comment by GeekPress** [comment]
> Because if the cache needs to be cleared, it's necessarily because things have changed on the website, and therefore new CSS generation should be done too.

Don't forget when you update a page, its cache is automatically cleared and the same for CPCSS / RUCSS.

You don't need to clear the entire cache when you updated a page. This button is only to purge the entire cache, and should not be used when you just updated a page.

**Comment by JerissCloudCenter** [comment]
Indeed, your answer is true only if we talk about specific page/post update. However, I was actually refering to cases when "things have changed on the website" in terms of general CSS (not in terms of content updated per page/post).

Imagine for example that I change the general website CSS through my theme to modify the layout of some header elements. In this case, there is no page / post update, so then this doesn't work. Here comes my suggestion to simply the regeneration of CPCSS / RUCSS because here users must clear the entire cache (as well as the CPCSS / RUCSS) then regenerate the CPCSS / RUCSS and regenerate the cache.

That's why the simplification would make things easier, and ensure that CPCSS / RUCSS is always regenerated whenever the entire cache is emptied / regenerated. I hope this clears what I meant in this suggestion.

**Comment by piotrbak** [comment]
Hello @jeriss-cloud-center 

**>because here users must clear the entire cache (as well as the CPCSS / RUCSS) then regenerate the CPCSS / RUCSS and regenerate the cache.**

This is not 100% correct. After making the changes in CSS, you'll need to:
1. _Clear Used CSS_ from the top menu button (it's also clearing the cache)
2. Preload Cache (it's also generating new Used CSS)

However, I still think that there's a place for simplification of the process.

**Comment by JerissCloudCenter** [comment]
Dear @piotrbak 

Thank you for your clarification.

I think your answer actually even points in my direction. You confirmed that "clearing the Used CSS also clears the cache" but that isn't straightforward (at least for me it wasn't, so I suppose for other users it could too).

I really think (for sure) that there must be some more simple ways for all these features to work together. As in the example I gave above, if you look at FlyingPress, you just have 2 buttons : Purge Cache / Purge&Preload Cache. That really is very simple to use and I think this kind of approach would be better for most WP Rocket users too.

Here is a summary of my comprehensive view on how WP Rocket could be simplified (if you would consider that)

**1. On cache clearing**
a. Get rid of "Clear OPcache" #4439 *
b. Hitting on "Clear all cache files" should (1) clear cache files (2) clear OPcache (3) clear CPCSS/RUCSS

**2. On cache preloading**
a. Enable "Cache Preloading" by default and remove it from the settings [just like FlyingPress] **
b. Hitting on "Cache Preloading" should (1) preload cache (2) generate CPCSS/RUCSS if any enabled #4440
c. Remove "Generate CPCSS" action button from dashboard
d. Remove "Clear Used CSS" action button from dashboard

Note * I believe OPcache doesn't ring a bell to most users, so why making it a separate button? No need for this.
Note ** I hardly imagine a WP Rocket user not enabling preloading which is among the greatest speed boosting feature.

If this isn't the solution you'd consider, feel free to close this ticket. Thanks for hearing my voice.

Regards

**Comment by GeekPress** [comment]
Thanks for the details @jeriss-cloud-center 

We will discuss about your suggestions internally and will let you know about our decision :)

**Comment by luckyankit** [comment]
Clearing RUCSS everytime you clear cache is a bad idea as clearing cache triggers many times even when there is no change on the front end. It would be an unnecessary headache for the webmaster as many a time site would be loading pages with render-blocking CSS then. Over simplification can lead to terrible things too and wp-rocket has a great history with that!

**Comment by GeekPress** [comment]
We have decided to keep our actual behavior: clear the entire cache won't clear the Used CSS.

Why?
The need to clear the entire cache can be for so many reasons, and not related to a global CSS change. By the way, when a theme is updated, we already automatically clear the cache and regenerate Used CSS. We do the same when the user will switch to another theme.

If you did a change on your global CSS, you can simply click on « Clear Used CSS » which will clear the entire cache and regenerate the Used CSS for all pages.
