### ISSUE TITLE
WP-Rocket breaks for URLs that have .php file-extensions

### ISSUE THREAD

**Issue by megakraken** [wp-media/wp-rocket#4456]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using a plugin that adds .php file-extensions to page URLS (for SEO reasons) WP-Rocket will not cache the pages. No directories with index-https.html files are created under `/wp-content/cache/wp-rocket`.

This used to work fine with older versions of WP-Rocket (2.10.7).

**To Reproduce**
1. Install the [.PHP on Pages](https://de.wordpress.org/plugins/php-to-pages/) plugin
2. Clear the WP-Rocket caches
3. Open any page with a .php extension
4. Observe that it is not being cached

**Expected behavior**
The pages should be cached as in earlier versions of WP-Rocket.

**Additional context**
The [source code](https://www.codepile.net/pile/a1xaQoq7) of the [.PHP on Pages](https://de.wordpress.org/plugins/php-to-pages/) plugin is really just a couple of lines and you can look at it here. Any pointers on how to change the plugin to make it work with WP-Rocket are of course also appreciated.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Looking back at the source code in version 2.10.7, at that time we were already excluding php extension from cache: https://github.com/wp-media/wp-rocket/blob/v2.10.7/inc/front/process.php

**Comment by megakraken** [comment]
Hello,

that is strange since we are operating a Website with said version of
WP-Rocket and said .PHP on Pages plugin and the .php pages are cached just
fine.

Kind regards

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
