### ISSUE TITLE
WP Rocket REST API

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#446]
Create custom endpoints for WP Rocket to be able to interact with the plugin without depending on WP admin.

Could be used as starter to purge and preload the cache.

**Comment by arunbasillal** [comment]
@GeekPress Shall we move this to product board and put it up for voting?

**Comment by GeekPress** [comment]
@arunbasillal I'm not sure to understand the need. @Tabrisrp Could we have more details?
