### ISSUE TITLE
Add Image Dimensions not processing image if it's lazy loaded by a 3rd party

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4461]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Example, when Perfmatters applies the lazy loading, images will look like this:
​
```
<img src="data:image/svg+xml,%3Csvg%20xmlns=&#039;http://www.w3.org/2000/svg&#039;%20viewBox=&#039;0%200%20800%20800&#039;%3E%3C/svg%3E" data-src="https://domain.ext/wp-content/uploads/2021/07/image.png">
```

​​The <src> attribute has a `data:image` that can't be processed by Image Dimensions feature. We will not add any width/height for it and consequently PSI will show the following notification: **Image elements do not have explicit width and height** even if Add Image Dimensions is enabled

**To Reproduce**
1. Add an image with the above markup (with `data:image` as a `src`)
2. Enable Add Image Dimensions
3. See height/width not applied

**Expected behavior**
WP Rocket should pick the right image to process. We could look for `data-src` instead of `src` when we notice `data:image` is used for example. 

**Screenshots**
N/A

**Additional context**
Related ticket - https://secure.helpscout.net/conversation/1676137674/303945?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by swabhav** [comment]
my site logo loading under the script tag but getting an issue - Image elements do not have explicit width and height

screenshot - https://prnt.sc/CIO1j8Md2z4s
site url - https://sarkarify.com/

**Comment by camilamadronero-zz** [comment]
@swabhav Hey! Your site's logo was added using a `picture` tag ([as seen in the source code](https://jmp.sh/Rju1Bta)), and these images are excluded from the **Add missing image dimensions** feature. 

You can extend the feature to be applied on `picture` tags, [by following this guide](https://docs.wp-rocket.me/article/1570-extend-missing-image-dimensions). And, if you have any further questions, please feel free to open a support ticket.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
