### ISSUE TITLE
linear-gradient() function is removed in used CSS

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4463]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version -3.10.1
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Some linear-gradient() functions for background CSS property are not processed and removed in used CSS.

The following example is **not** being added to the used CSS:
`background: linear-gradient(45deg, rgba(241, 85, 105, 1) 0%, rgba(248, 160, 50, 1) 100%);`

The following example is successfully processed and added to the Used CSS:
`background: linear-gradient(#e66465, #9198e5);`

**To Reproduce**
1. Create a `<div>` element on a page with the following markup:
`<div class="my-style"></div>`
2. Add custom style in Customize -> Additional CSS:
```
.my-style {
	width: 100%;
	height: 300px;
	background: linear-gradient(45deg, rgba(241, 85, 105, 1) 0%, rgba(248, 160, 50, 1) 100%);
	border-style: solid;
	border-width: 5px;
}
```
3. Enable Remove Unused CSS option and wait for the process to complete. Additionally you can add `.my-style` to the Safelist to make sure it is added.
4. Check the page in the Incognito browser window. All the properties for the class will be added, except for the `background: linear-gradient()`.

Screenshot:
![image](https://user-images.githubusercontent.com/60236665/139141358-d22a5c7d-1845-4adc-a6eb-00a7d61f75a8.png)

**Expected behavior**
`linear-gradient()` function has to be preserved in the Used CSS

**Additional context**
Reference for `linear-gradient()` CSS function: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient()
Related ticket: https://secure.helpscout.net/conversation/1677795045/304217/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
It seems that this is another `rgba` case...

This one works and it's preserved:
```
background-image: linear-gradient(to bottom, rgba(215,238,241,0.18) 0%, rgba(228,251,255,0.18) 60%, rgba(184,222,226,0.18) 100%);
```

But the one mentioned in the issue not:
```
background: linear-gradient(45deg, rgba(241, 85, 105, 1) 0%, rgba(248, 160, 50, 1) 100%);
```

**Comment by mehedihasanziku** [comment]
This issue looks horrible, it's affecting also on generated rucss before the issue opened.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1680470261/304729/

In this case, the CSS was this:
```CSS
background-image: linear-gradient(to top , rgba(29, 54, 88, 0.8) 0%, rgba(29, 54, 88, 0.6) 80%, rgba(29, 54, 88, 0) 100%);
```
Replacing `rgba(29, 54, 88, 0)` with `rgb(29, 54, 88)` allowed the used CSS generator to preserve the `linear-gradient()`.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1678706687/304385/

In this case, it was the `radial-gradient`.

The presence of the `rgba()` seems to force the SaaS to dismiss the `background-image` property.

This is dismissed:

```
background-image:radial-gradient(at top right, rgba(255,255,255,0) 0%, #ffffff 69%);
```

The following two worked: 

- Without `rgba()`:
```
background-image:radial-gradient(at top right, transparent 0%, #ffffff 69%);
```
- With `rgba()` as the second argument: 
```
background-image:radial-gradient(at top right, #fff 0%, rgba(255,255,255,1) 69%);
```

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1682404160/304978?folderId=2135277

The original CSS was this:
```CSS
background-image: linear-gradient(180deg, #ffffff 0%, rgba(255,255,255,0) 100%);
```

and it was removed from the used CSS.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1682265464/304962?folderId=2135277

The following:
```CSS
background: linear-gradient(
180deg, rgb(0, 0, 0) 0%, rgba(0,0,0,0.006337569207370497) 30px, rgba(0,0,0,0) 100%) !important;
```
was removed.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1674776880/303744/

Not specific to `linear-gradient` or `radial-gradient`. 

Any color using `rgba()` opacity set to `0` or `1` is dismissed. 

Example: 
```
background-color: rgba(245, 166, 35, 1);
```

Anything other than `0` or `1` seems to be preserved: 

```
border-color: rgba(129, 129, 129, 0.2);
```

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1685115686/305490/

This is removed:
```CSS
border-image: linear-gradient(to bottom,dodgerblue,rgba(0,0,0,0)) 1 100%;
```

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1681515348/304860?folderId=3864735

This property is remove: 
```
background-image: radial-gradient(ellipse at center,rgba(247,250,252,1),rgba(247,250,252,1));
```

**Comment by mehedihasanziku** [comment]
This issue is on 🔥🔥

Removed by rucss `background-color: rgba(84, 89, 95, 0);`
changed to this `background-color: rgba(84, 89, 95, 0.0);` and preserved as `background-color: rgba(84,89,95,0);`

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/1684637888/305409/

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/1687888498/306055?folderId=2135277

**Comment by iCaspar** [comment]
Closed by https://github.com/wp-media/css-parser/pull/51

**Comment by remyperona** [comment]
This case should be fixed with our update on the SaaS side.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1690714535/306573?folderId=2135277

The background image isn't displayed:
```CSS
div.et_pb_section.et_pb_section_2 {
    background-image: linear-gradient(
180deg,#ffffff 20%,rgba(255,255,255,0) 80%),url(https://example.com/wp-content/uploads/2019/08/welkom-ophangen-1.jpg)!important;
}
```
