### ISSUE TITLE
linear-gradient() CSS function containing "turn" breaks during processing

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4464]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.1
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
background: linear-gradient() CSS function containing "turn" breaks during processing due to the added space between numerical value and `turn`.

Original declaration:
`background: linear-gradient(0.25turn, #3f87a6, #ebf8e1, #f69d3c);`

becomes this:
`background:linear-gradient(.25 turn,#3f87a6,#ebf8e1,#f69d3c);`

It causes _invalid property value_ warning in the browser and thus broken styling (gradient is not being applied).

Screenshot:
![image](https://user-images.githubusercontent.com/60236665/139144950-b8f4b300-cd1d-4430-b997-05388718587f.png)

**To Reproduce**
1. Create a `<div>` element on a page with the following markup:
`<div class="my-style"></div>`
2. Add custom style in Customize -> Additional CSS:
```
.my-style {
	width: 100%;
	height: 300px;
	background: linear-gradient(0.25turn, #3f87a6, #ebf8e1, #f69d3c);
	border-style: solid;
	border-width: 5px;
}

```
3. Enable Remove Unused CSS option and wait for the process to complete. Additionally you can add `.my-style` to the Safelist to make sure it is added.
4. Check the page in the Incognito browser window. The gradient is not applied and there is the _invalid property value_ error in the Inspect tool.

**Expected behavior**
There should be no space between the numeric value and `turn` in the `linear-gradient()` function.

**Additional context**
Reference for `linear-gradient()` CSS function: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient()
Props to @piotrbak for spotting this.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
This is a bug coming from the CSS parser library
