### ISSUE TITLE
PHP Notice:  Undefined index: host when exclude Defer JS domain name while Minify JS is enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4466]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
PHP Notice is added in debug.log when excluding domain name or file name from Defer JS while Minify JS is enabled 

**To Reproduce**
1.Add the following script in footer `<script type='text/javascript' src='widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js?ver=5'></script>`
2. Enable Minify JS and Defer JS
3. Exclude from Defer JS `widget.trustpilot.com`
4. Clear cache
5. Open the page containing this script
6. Check debug.log
`PHP Notice:  Undefined index: host in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/AssetsLocalCache.php on line 112`

**Expected behavior**
No notice is added to debug.log

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
I was able to reproduce the issue with just minify JS enabled
