### ISSUE TITLE
Preload user cache

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4467]
**Is your feature request related to a problem? Please describe.**
Some edge cases might require preloading the user cache either for the website in full or partially, for a single user or for all the user base. 

**Describe the solution you'd like**
Build hooks to facilitate enabling preloading user cache, at least programmatically, if needed.

**Describe alternatives you've considered**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1678680619/304376?folderId=3864735

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
