### ISSUE TITLE
Autoptimize aggregated JS file can't be delayed

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4472]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Autoptimize is using their `JS, CSS & HTML` > `JavaScript Options` > `Aggregate JS-files`, WP Rocket `Delay JS` is not applied to the resulting combined file.

The combined file will be added as:

```
<script defer src="https://domain.ext/wp-content/cache/autoptimize/js/autoptimize_609b9fb609c9a893772168880e9ef32e.js">
```

Checking the buffer received before applying the Delay JS: 

[/inc/Engine/Optimization/DelayJS/Subscriber.php#L84-L86](https://github.com/wp-media/wp-rocket/blob/v3.10.2/inc/Engine/Optimization/DelayJS/Subscriber.php#L84-L86)

The combined files are not there on the HTML to process. 

https://gist.github.com/DahmaniAdame/51aa691bad4070275eb565d8dc1e3445

**To Reproduce**
1. Go to enable `Autoptimize` > `JS, CSS & HTML` > `JavaScript Options` > `Aggregate JS-files`
2. Enable WP Rocket `Delay JS` with no exclusions
3. See error

**Expected behavior**
We should either delay the resulting combined file or hint to the customer that this particular file won't be delayed.

**Screenshots**
N/A

**Additional context**

Temporary fix: disabling `Autoptimize` > `JS, CSS & HTML` > `JavaScript Options` > `Aggregate JS-files` will allow delaying all scripts.

Ticket - https://secure.helpscout.net/conversation/1681325316/304823/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Let's go with the educative notice approach:
When we detect that DelayJS and Autoptimize JS Aggregation is enabled, we'll display dismissable, educative notice like we do for our Combine JS. We'll encourage customers to disable Autoptimize option to have the best results.

@webtrainingwheels @vmanthos What do you think would be the best wording here? 🙏

**Comment by vmanthos** [comment]
It could be something like this:

> We have detected that Autoptimize's JavaScript Aggregation feature is enabled. The Delay JavaScript Execution will not be applied to the file it creates. We suggest disabling it to take full advantage of Delay JavaScript Execution.

**Comment by iCaspar** [comment]
See grooming for #4327 
1. Add a function to detect the Autoptimize setting.
2. Add a helper in Settings/Page.php with the appropriate message.

**Estimated Effort**:
[XS]

**Comment by iCaspar** [comment]
**User story:**
```
Given I am a WP Admin
When I have Autoptomize JS Aggregation AND Rocket Delay JS active at the same time,
Then I will see a dismissable (yellow) warning notice box that says:
   "We have detected that Autoptimize's JS Aggregation feature is enabled.
    The Delay JavaScript Execution will not be applied to the file it creates. 
    We suggest disabling it to take full advantage of Delay JavaScript Execution."
That persists between admin page loads until
    I dismiss it OR I disable either setting.
So that I am aware of the need to edit Autoptimize settings to work with WP Rocket.
```

**Comment by piotrbak** [comment]
This issue will also resolve the https://github.com/wp-media/wp-rocket/issues/3707

**Comment by iCaspar** [comment]
Ready for @wp-media/qa . See [User Story](https://github.com/wp-media/wp-rocket/issues/4472#issuecomment-967139866).
