### ISSUE TITLE
Delay JS - after 3.10.2 update elements can become non-responsive when browser scroll is used

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4478]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.2
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
After update to 3.10.2 when _Delay JavaScript Execution_ option is enabled - links become non-clickable when a browser scroll bar is used.

**To Reproduce**
The issue was reproduced on customer's sites (3 sites) with the following steps:
1. Go to a page that has links in the footer;
2. Once page is loaded enough for interaction, navigate mouse to a **browser side scroll bar** and scroll to the footer
3. Try to click on any links in the footer - they are not clickable. If you scroll up - navigation menu is not clickable as well.

Customer's staging site with exact steps to reproduce and video is available in the ticket here: https://secure.helpscout.net/conversation/1683613179/305192/#thread-4927366678

The issue is NOT reproducible if you scroll:
- with the mouse wheel;
- with the "end" key.
It doesn't matter if you wait longer and let all the scripts to load.
It also doesn't matter if you move the mouse across the window to the scroll bar or not.

The issue is resolved when almost all scripts are excluded with `(?:/wp-content/|/wp-includes/)(.*)` or individually. I was not able to narrow down the list of script. Removing even one non-important script from exclusions would cause the issue.

The issue is NOT present in 3.10.1 version of WP Rocket.

All the affected sites are using Avada theme.
I was not able to reproduce the issue on a non-Avada testing site, but it is not yet clear if the issue is Avada specific.

**Expected behavior**
Links must be clickable when page is loaded.

**Screenshots**
Screen recordings are available in the notes: 
https://secure.helpscout.net/conversation/1683613179/305192/#thread-4927366678
https://secure.helpscout.net/conversation/1683613179/305192/#thread-4931107429

Documenting it now to monitor for similar issue reports. But this requires further investigation, as the root cause is not clear to me.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Garnet-Fox** [comment]
Not only Avada, at least Flatsome too. The console is empty, there is no mistake, where the legs grow from is not clear. Not only links do not work, but also the buttons of the button on which the event is hung, and it is not necessary that this is a click on the link. Helps F5. Rolling back the lazyload-script version to 3.9.4.1 helps completely. At the same time, not all computers react this way and not every time, on some the error appears, on some not. Yandex and Chrome browsers periodically cause a bug, the rest were not tested, a rollback was applied. In addition, a decrease in performance was noticed when controlling missed clicks, on a site where there are a lot of click events, buttons and links, if they work at the first load, react with a noticeable delay.
mouse wheel is causing the problem too.

**Comment by piotrbak** [comment]
Hello @Garnet-Fox thanks for your comment.

The problem with delayed onclick events _is kind of_ expected. Before, in some cases, onclick events were not working correctly on mobile devices. Hamburger menu could be a good example:
1. First tap on the hamburger menu
2. Scripts are loaded, nothing happens the menu doesn't open
3. Second tap on the hamburger menu, menu opens

We fixed this problem by saving the specific events from the 1st step and launching them late, when other core events are loaded.

**Comment by Garnet-Fox** [comment]
@piotrbak , are your talking about performance? Hamburger menu events are in delayed scripts? If yes, maybe it’s better not to delay them. It's just that the speed of loading does not always prevail over the performance of the site as a whole. By catching missed clicks, I managed to additionally postpone only one script, and the delay from the response is not comparable to the page load speed in terms of damage to usability.

**Comment by NataliaDrause** [comment]
Possibly related: https://secure.helpscout.net/conversation/1692702484/306996/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1889629277/343846
Scrolling was not required. Just navigating on the website will at some point lock clicks. Even anchor links stop working.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1907547127/346403?folderId=3864735

**Comment by piotrbak** [comment]
We haven't heard about this bug for a while, it's not happening on Avada anymore with the last version of the script. Let's wait a bit more to see if we can collect any further feedback.
