### ISSUE TITLE
Turn off Defer CSS Loaded in the <BODY> (Footer) on Asset Cleanup when Remove Unused CSS is used

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4480]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When one of the following Asset Cleanup Pro options are enabled:

- **Defer CSS Loaded in the <BODY> (Footer) > Yes, for any stylesheet LINK tags moved from HEAD to BODY**
- **Defer CSS Loaded in the <BODY> (Footer) > Yes, for all the stylesheet LINK tags that are moved or already loaded in the BODY**

Asset Cleanup will turn any processed CSS file to load after the DOM is loaded using JavaScript. 

Example:
```
<link rel='stylesheet' id='wpacu-moved-from-head-to-body-js_composer_front-css' href='/wp-content/cache/asset-cleanup/css/item/js_composer_front-v47a0deba42e9e80b2e90920eefcd149746f7d914.css' type='text/css' media='all' />
```
Will be turned to: 
```
<script type='text/javascript'>document.addEventListener('DOMContentLoaded',function(){var wpacuLinkTag1001=document.createElement('link');wpacuLinkTag1001.rel='stylesheet';wpacuLinkTag1001.href='/wp-content/cache/asset-cleanup/css/item/js_composer_front-v47a0deba42e9e80b2e90920eefcd149746f7d914.css';wpacuLinkTag1001.type='text/css';wpacuLinkTag1001.media='all';wpacuLinkTag1001.property='stylesheet';var wpacuUa=window.navigator.userAgent;if((wpacuUa.indexOf('MSIE ')>0||wpacuUa.indexOf('Trident/')>0||wpacuUa.indexOf('Edge/')>0)||typeof document.documentMode!=='undefined'){document.body.appendChild(wpacuLinkTag1001)}else{document.body.prepend(wpacuLinkTag1001)}})</script>
```

This will:
- Keep the Reduce Unused CSS recommendation on PSI 
- Might cause misstyled elements as any CSS file injected that way will override anything added on the inline `wpr-usedcss` we add on the top of the document

**To Reproduce**
1. Enable Asset Cleanup with one of the mentioned options
2. Enable the Remove Unused CSS feature
3. See that PSI is still recommending reducing the Used CSS mentioning the CSS file injected after the DOM loads

**Expected behavior**
The issue is not really caused by WP Rocket, but it nullifies what our Remove Unused CSS feature is about (minimizing the CSS and fixing the PSI recommendation).

Ideally, we could force the 3rd option on Asset Cleanup when Remove Unused CSS is used:
- **Defer CSS Loaded in the <BODY> (Footer) > No, leave the stylesheet LINK tags from the BODY as they are without any alteration**

That supposes Asset Cleanup has a hook to override this feature's settings programmatically without altering the default settings.

An alternative could be getting rid of the following inline script when Remove Unused CSS is used when we generate the cache: 

Another alternative could be adding a notification for the customer to turn off manually the problematic option on Asset Cleanup when Remove Unused CSS is enabled.

```
<script type='text/javascript'>document.addEventListener('DOMContentLoaded',function(){var wpacuLinkTag1001=document.createElement('link');wpacuLinkTag1001.rel='stylesheet';wpacuLinkTag1001.href='/wp-content/cache/asset-cleanup/css/item/js_composer_front-v47a0deba42e9e80b2e90920eefcd149746f7d914.css';wpacuLinkTag1001.type='text/css';wpacuLinkTag1001.media='all';wpacuLinkTag1001.property='stylesheet';var wpacuUa=window.navigator.userAgent;if((wpacuUa.indexOf('MSIE ')>0||wpacuUa.indexOf('Trident/')>0||wpacuUa.indexOf('Edge/')>0)||typeof document.documentMode!=='undefined'){document.body.appendChild(wpacuLinkTag1001)}else{document.body.prepend(wpacuLinkTag1001)}})</script>
```

It should be safe to remove it as RUCSS fetches the resource inside the script.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/140291843-4d73e5d4-f79b-464a-b43a-b8ac7f8dab95.png)

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1675891655/303875/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1674475699/303683?folderId=3864740

**Comment by gabelivan** [comment]
@DahmaniAdame @NataliaDrause  I was notified about this issue by one of the Asset CleanUp Pro users. Currently, you can disable "Defer CSS Loaded in the (Footer)" whenever "Remove Unused CSS" is turned on by hooking into get_option() for the settings via add_filter - https://developer.wordpress.org/reference/functions/get_option/ - however, you have to carefully alter the JSON value there. While it's possible, it's not ideal.

Perhaps having a hook for each option would be a better idea in this case OR automatically check if WP Rocket is enabled and if it has the removed unused CSS turned ON, then the alteration of the CSS files moved to BODY will not take place.

Let me know if you have any other ideas, hopefully, better ones :)

**Comment by GeekPress** [comment]
@piotrbak Maybe it's time to add Asset Cleanup into the default incompatible plugins. With RUCSS, there is no need to manage and select which CSS has to be loaded on the page. With Delay JS, there is no need to manage and select which JS has to be loaded on the page.

What do you think?

**Comment by GeekPress** [comment]
@gabelivan I would love to have your feedback too. Are you seeing any benefits to use Asset Cleanup and WP Rocket at the same time?

**Comment by GeekPress** [comment]
@DahmaniAdame Is it still an issue with the new RUCSS? As JS files are executed now, maybe it has been fixed.

**Comment by DahmaniAdame** [comment]
@GeekPress, we didn't have any new cases about it. 

The feature is part of the Pro version, so I couldn't test.

The problem has two parts: 

- Us detecting the CSS file. Which should be solved by executing JS on SaaS. That's likely working. 
- Asset Cleanup still injecting the script to the page because it's managed using JS and we don't remove JS when we inject our RUCSS. 
 
So, the recommendation about reducing unused CSS will still stand on PSI. 

I just checked Asset Cleanup changelog. No fix was added there. 

For now, it's only possible by manipulating JSON using `get_option()` to turn off the conflicting features on Asset Cleanup, but it's best if there are filters targeting specific features on Asset Cleanup instead. 

@gabelivan would that be something that you could consider adding to Asset Cleanup?

**Comment by piotrbak** [comment]
@gabelivan Would it be possible to get a copy of PRO version of Asset CleanUp to test the solution?

**Comment by gabelivan** [comment]
@GeekPress @piotrbak  I just received a few emails from people using Asset CleanUp Pro that are bothered by the notification about incompatibility. They can't dismiss it. Can you change it in future versions so that it will be dismissable? There are plenty of people using both plugins. I wasn't expecting that as a dismissable notice shown once would have been more professional.

If you can't change the notification's behavior, let me know. I must instruct both Lite and Pro users about the incompatibilities between the plugins and stop promoting WP Rocket, as I've been doing this for years, including as an affiliate.

If you are willing to remove the notification, I could provide you a copy of the Pro version (I thought you had it already since you made tests on it) and implement specific filters on some of the front-end optimization features.

PS: I'll check the email associated with this GitHub account more often to ensure I won't miss your replies and get back to you as soon as possible. I rarely use GitHub.

**Comment by piotrbak** [comment]
Hello @gabelivan thanks for your comment.

We'll revert this change asap, you can use piotr[at]wp-media.me for compatibility conversations.

What we did here is a part of preparations for 3.15 and 3.16 version of WP Rocket, if you'll be able to provide us necessary filters, I'm sure we'll be fully compatible.

**Comment by gabelivan** [comment]
@piotrbak I could provide you with the necessary filters, especially the ones related to the "Settings" area. If you have to disable a specific option from "Settings" whenever WP Rocket has an option enabled, that could be done.

From what I understood, that was a problem since you didn't want to use the filtering from get_option(), which is not ideal as you sometimes have to go through an array and unset specific values or even decode a JSON string, strip specific value from there and re-code it, not ideal at all.

PS: I could provide you a copy of the Pro license (to the email you mentioned). Can you also send me a copy of WP Rocket if I need to check anything in the source code?

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
