### ISSUE TITLE
Delay JavaScript Execution 3.10.2 bug with the Beaver Theme on iOS (no link is clickable)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4485]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When the latest version of the Delay JavaScript Execution script is used with the Beaver Theme on iOS, none of page's links are clickable on Safari and Chrome.

Falling back to the previous version of the Delay JavaScript Execution script fixed the issue.

The following error is present, but it was there as well when using the previous version of the script without interfering with links behavior:

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'event.persisted')
```

Android works fine.

**To Reproduce**
1. Use Beaver Theme + WP Rocket `3.10.2`
2. Enable Delay JavaScript Execution
3. Load the page and try to click on a link (menu, or any link)

**Expected behavior**
Links should be clickable on iOS devices.

**Screenshots**
https://drive.google.com/file/d/1xkRqVdRXTNO8kxiSOdp30Xz7SdYOgP19/view?usp=drivesdk

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1684368842/305336/

**Temporary fix**

Replacing the following file: 
`/wp-content/plugins/wp-rocket/assets/js/lazyload-scripts.min.js`
​with this one: 

​`​https://raw.githubusercontent.com/wp-media/wp-rocket/v3.10.1/assets/js/lazyload-scripts.min.js`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
Another possible related case here: 
https://secure.helpscout.net/conversation/1687266869/305940/

no links are clickable on **3.10.2:**
This is only affecting the homepage, not the internal pages.
It is affecting mobile and desktop

When reverting to 3.10.1, or 3.9.4 the console error is also present, _but it is not preventing the functionality of the links._

The following console error is present **after user interaction**:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replaceChild')     
at :formatted:149     at new Promise (<anonymous>)     at RocketLazyLoadScripts._transformScript (:formatted:138)     at async RocketLazyLoadScripts._loadScriptsFromList (:formatted:155)     at async RocketLazyLoadScripts._loadEverythingNow (:formatted:124)  
```
Related to https://jmp.sh/l0EI63N

In this case, excluding the following files solve the issue when 3.10.2 is running:
_staposthriftylifehacks.ck.page_
(here are the file contents: https://snippi.com/s/s4g39u8)

But, on previous versions of WP Rocket, these files are not preventing the links from working, nor need to be excluded.

**Comment by alfonso100** [comment]
probably related: 
https://secure.helpscout.net/conversation/1688011423/306096?folderId=2683093

**Comment by piotrbak** [comment]
This was fixed in the Delay JS repo while ago
