### ISSUE TITLE
Deperecation Warning:  implode(): Passing glue string after array is deprecated

### ISSUE THREAD

**Issue by SALLYPEMDAS** [wp-media/wp-rocket#4488]
Hi! Thanks for the plugin.

I am seeing this deprecation waring on PHP 7.4:

  #0 implode(): Passing glue string after array is deprecated. Swap the parameters:: called at [/home/redacted/public_html/web/app/plugins/wp-rocket/vendor/matthiasmullie/minify/src/CSS.php:518]

It looks like the dependency project is already updated:

https://github.com/matthiasmullie/minify/pull/300

Can we please bring the update into wprocket so we don't see these warnings?

Thank you!

**Comment by piotrbak** [comment]
Hello @SALLYPEMDAS we updated minification library in 3.9.1 version of WP Rocket while ago:
https://github.com/wp-media/wp-rocket/pull/3907

I can confirm that the code is updated on my environment. Could you tell me which WP Rocket version you're using?

**Comment by SALLYPEMDAS** [comment]
Oh I was on an old version. I didn't realize that plugin updates don't roll automatically for this plugin.

Thank you!
