### ISSUE TITLE
Can't generate CPCSS due to bad gateway on WP Rocket domain

### ISSUE THREAD

**Issue by smerriman** [wp-media/wp-rocket#4490]
https://cpcss.wp-rocket.me/ is giving a bad gateway error, causing all attempts to generate critical CSS to fail.

**Comment by piotrbak** [comment]
@smerriman I'm closign this, since the issue was resolved. Please note, that our GitHub repository is supposed to collect bugs related to our product. In the future, please be in touch with our awesome Support Team, they'll be happy to help you :)

**Comment by smerriman** [comment]
Your product directly uses this URL (I only discovered it after debugging through your code to see why it was generating errors), so I would consider it a pretty serious bug with the product :) But I'm glad you managed to resolve it.

**Comment by smerriman** [comment]
Addendum - perhaps consider this a feature request then - if your server is down and you attempt to generate critical CSS with the plugin, can you have a more appropriate error message?

All it currently says is 'The API returned an invalid response code', which according to https://docs.wp-rocket.me/article/1267-troubleshooting-critical-css-generation-issues says that we need to whitelist WP Rocket on *our* server.

It took me some debugging to realise that this was incorrect and your own server was broken.
