### ISSUE TITLE
Delay JS - Exclude Jetpack's lazyload scripts

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4492]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Images are not displayed till user interaction

**To Reproduce**
1. Enable Jetpack plugin
2. Enable delay js
3. Visit the page with images
4. images not displayed till user interaction

**Expected behavior**
Images displayed with no user interaction

**Additional context**
- Referring to https://github.com/wp-media/wp-rocket/pull/4479 we can add `jetpack-lazy-images-load` and change URL to `/wp-content/plugins/jetpack(.*)/vendor/automattic/jetpack-lazy-images/(.*)` or add `/jetpack/vendor/automattic/jetpack-lazy-images/(.*)`
- Another solution is to replace all exclusions with `jetpack-lazy-images(.*)` if safe

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Optimization\DelayJS\HTML::$excluded`, replace exclusions related to Jetpack lazyload by `jetpack-lazy-images`. This should cover everything we need for the exclusions when using JetPack and/or JetPack boost.

### Estimate the effort ✅
Effort `[XS]`
