### ISSUE TITLE
Disable Never cache (URLs) on hosting services where WP Rocket doesn't handle page cache

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4494]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When WP Rocket is not handling page cache, exclusions used on Never cache (URLs) won't have any effect. 

Kinsta for example mentions that exclusions will need to pass through the support service: https://kinsta.com/blog/wp-rocket/#advanced-rules

WP Engine requests as well reaching out to their support in order to add custom cache exclusions: https://wpengine.com/support/cache/#Custom_Cache_Exclusions

WP Rocket should: 
- Disable the `Never cache (URLs)` box when using hosts that require adding exclusions on their end.
- Add a message to tell the customer to do the exclusions on the hosting service's end.

**Describe alternatives you've considered**
N/A

**Additional context**
Related ticket - https://secure.helpscout.net/conversation/1692163302/306829/

**Comment by webtrainingwheels** [comment]
Excluding the URL from the cache will still disable optimizations on that page, which could be desirable in some cases couldn't it?
Maybe we can just update the helper text to say that if they are using a managed host or another cache layer, exclusions need to be done there as well.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
