### ISSUE TITLE
Space is added before turn (used in Woocommerce style sheet) in used CSS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4495]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Space is added before` turn `inside used CSS of `/wp-content/plugins/woocommerce-/packages/woocommerce-blocks/build/wc-blocks-style.css`

**To Reproduce**
- Woocommerce is enabled
- RUCSS is enabled 
1. Open home page and search for turn in used CSS
2. `spin{0%{transform:rotate(0deg)}to{transform:rotate(1 turn)}}` instead of `spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}`

**Expected behavior**
If this will cause a problem as in https://github.com/wp-media/wp-rocket/issues/4464 then we will need not to add any space before `turn` here as well

**Screenshots**
nowprocket
![Screenshot from 2021-11-10 13-01-06](https://user-images.githubusercontent.com/76941962/141101494-f10b6df7-92bc-4fd8-9969-c84aa2f4db1d.png)

Used CSS
![Screenshot from 2021-11-10 12-59-45](https://user-images.githubusercontent.com/76941962/141101567-c2f70bd5-d327-42a0-bdfc-252d2bcb137c.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Fixed with 3.11
