### ISSUE TITLE
PDF Embedder Plugin compatibility

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4500]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
**For PDF embedder (4.6.4)** Using Combine JS gives an error
![Screenshot from 2021-11-10 09-43-01](https://user-images.githubusercontent.com/76941962/141333248-ca063fe0-4891-450a-84f3-b9ed24f9d36e.png)
The error is fixed by the following exclusion from Combine JS
```
/pdf-embedder(.*)
jquery.min.js
jquery-migrate.min.js
```
**For PDF embedder (4.6.2)** when using Combine JS is enabled, links are displayed instead of the PDF.
![Screenshot from 2021-11-10 10-21-44](https://user-images.githubusercontent.com/76941962/141333843-36f08f87-0003-4c58-8ddc-c093ae83cdb1.png)
Excluding jquery and jquery-migrate will make PDF displayed
```
jquery.min.js
jquery-migrate.min.js
```
**For PDF embedder (4.6.2)** When using Defer JS, the file is stuck in loading or displayed as a link.
![Screenshot from 2021-11-10 10-20-29](https://user-images.githubusercontent.com/76941962/141334111-ca2b7c24-064a-4baf-a226-49c50ce67e52.png)
The following exclusion fixes the problem

```
/pdf-embedder/js/(.*).js
jquery.min.js
jquery-migrate.min.js
```
**To Reproduce**
1. Enable PDF Embedder (mentioned version(s)) and create a page with PDF(s) embedded
2. Enable Combine js
3. open the page incognito
4. repeat step 2,3 using Defer JS

**Expected behavior**
PDF displayed correctly (using auto exclusions)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
