### ISSUE TITLE
Bug in Wp-rocket settings. please check

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4503]
**Describe the bug**
hello
My site supports http2. But when I disable the **combine css files** and **combine javascript files** options, the following errors appear on the website. also Website performance is also disrupted in some cases. (Products carousel does not move)
![Screenshot (214)](https://user-images.githubusercontent.com/77163248/141678558-6f4b92d0-08b8-4fd7-9777-52aaa40f837f.png)

Please review this, it is very important. Thank you

**Comment by mehedihasanziku** [comment]
It's not bug, you need to learn how this things works 

1. https://docs.wp-rocket.me/article/106-my-site-is-broken
2. https://docs.wp-rocket.me/article/915-find-the-right-js-files-to-exclude-from-minification

**Comment by 79ho3ein** [comment]
hi @mehedihasanziku, Thank you for your answer. But the two things I mentioned above, their inactivity should not be a problem under any circumstances. Because almost all websites use http2. Therefore, their inactivity should not be a problem.
Am I wrong?

**Comment by mehedihasanziku** [comment]
> hi @mehedihasanziku, Thank you for your answer. But the two things I mentioned above, their inactivity should not be a problem under any circumstances. Because almost all websites use http2. Therefore, their inactivity should not be a problem. Am I wrong?

I couldn't understand about inactivity,but doesn't matter http/2 available or not, actually nothing do with it.

**Comment by piotrbak** [comment]
Hello @79ho3ein in our GitHub repository we report bugs related to the code and feature requests. Problem you're having is related to incompatiblity between one of our features and your site. @mehedihasanziku shared with you the correct documentation articles. If docs won't answer your questions, please be in touch with our amazing Support Team:
https://wp-rocket.me/support/
