### ISSUE TITLE
User Cache isnot working with Query monitor plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4504]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Cache for logged in users is not working while the Query Monitor plugin is enabled

**To Reproduce**
1. Enable [Query Monitor ](https://wordpress.org/plugins/query-monitor/)plugin 3.7.1
2. Enable Cache for logged in users
3. Open home page for logged in user
4. No-cache signature in source and nothing added to the cached folder

**Expected behavior**
Cache for logged in users is working independently on active plugins

**Additional context**
Cache for logged in users working normally if we disable Query Monitor Plugin

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
@Mai-Saad This is because the plugin sets the `DONOTCACHEPAGE` to `true`. You can read more about this in our internal doc:
https://www.notion.so/wpmedia/Known-Conflicts-8d0a97af9b9c49dd991b28b24550e3de#6e9bbb422c5c4bdda5ade098b25e96f8
