### ISSUE TITLE
Automatically exclude a file from WPR’s JS optimization features when Uncode’s Adaptive images is enabled

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4506]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
When Uncode’s _Adaptive Images_ option is enabled along with WPR’s _Load JS deferred_, background images appear blurred.

**To Reproduce**
1. Enable WPR’s _Load JS deferred_
2. Enable _Uncode > Theme options > Performance > Adaptive Images_
3. Visit a page with a background image (like [this one](http://mega.wp-rocket.me/uncode/inspired-by-clouds/) from Mega/Uncode)

The issue is fixed when excluding the following file from Load JS deferred:
`/themes/uncode/library/js/ai-uncode.js`

Screencast for reference: https://share.getcloudapp.com/DOu6k7eq

**Expected behavior**
Images should not be blurred when both features are enabled.

**Screenshots**
Blurred background image: https://share.getcloudapp.com/p9uNLmDR
Image properly displayed: https://share.getcloudapp.com/geupOXnj

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1694600613/307367/
Slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1637060245029300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1698641324/308273

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `/library/js/ai-uncode.js` to the function `rocket_exclude_defer_js_uncode()`, in addition to the current exclusions we already have. We might also want to add the minified version `/library/js/min/ai-uncode.min.js`, `/library/js/ai-uncode.min.js`.

### Estimate the effort ✅
Effort `[XS]`
