### ISSUE TITLE
Updating permalinks won't clear cache if WPML is enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4511]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Changing permalink structure won't clear wp-rocket cache while WPML is enabled

**To Reproduce**
- WPML is enabled and set up with some languages

1. cache some pages at the test site
2. from settings-> permalinks, change permalink structure and save
3. check cache

**Expected behavior**
The wp-rocket cache is cleared as per https://docs.wp-rocket.me/article/78-how-often-is-the-cache-updated

**Screenshots**

https://user-images.githubusercontent.com/76941962/142238019-ad4714a7-29a5-44c2-93ef-58e84484fd02.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
