### ISSUE TITLE
WP Rocket cache is not cleared after updating widget 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4512]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
wp-rocket cache is not clear after updating the existing widget (although it is cleared with add/delete widget)

**To Reproduce**

Precondition:
- Having cached pages

1. From appearance-> widget, edit existing widget and update
2. Check wp-rocket cache

**Expected behavior**
wp-rocket cache is cleared as per https://docs.wp-rocket.me/article/78-how-often-is-the-cache-updated

**Additional context**
- Add/delete widget is clearing wp-rocket cache

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
