### ISSUE TITLE
Compatibility between LazyLoad and Thrive Architect

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4517]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a page is edited using Thrive Architect page editor, lazyloading for images stops working. 

The issue is likely from a buffer conflict and is likely to affect any plugin/theme manipulating the buffer.

**To Reproduce**
1. Edit a page using Thrive Architect
2. Apply lazy load
3. See error

**Expected behavior**
Lazy loading should work properly when Thrive Architect is used to editing a page.

**Screenshots**
N/A

**Additional context**
Applying lazy load to the buffer fixes the issue.

```
function apply_lazyload_on_rocket_buffer() {

	if ( function_exists( 'rocket_lazyload_images' ) ) {
		add_filter( 'rocket_buffer', 'rocket_lazyload_images', PHP_INT_MAX );
	}
}
add_action( 'wp_rocket_loaded', 'apply_lazyload_on_rocket_buffer' );
```

PS.: We used to have a helper plugin for that but it was removed.

Ticket - https://secure.helpscout.net/conversation/1684205265/305280?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
The `rocket_lazyload_images()` function has been deprecated in `3.3`, therefore shouldn't be used:
https://github.com/wp-media/wp-rocket/blob/a5d2dbc7348dd99fc6e50027d7a955eb0a338cf0/inc/deprecated/3.3.php#L162-L189

Something along the line of this should work:
```PHP
add_action( 'wp_rocket_loaded', function (){
	$container = apply_filters( 'rocket_container', [] );
	if ( ! $container ) {
		return;
	}
	$event_manager = $container->get( 'event_manager' );
	$lazyload_subscriber = $container->get( 'lazyload_image' );
	$event_manager->add_callback( 'rocket_buffer', [$lazyload_subscriber, 'lazyload' ], PHP_INT_MAX );
}, 100 );
```

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
