### ISSUE TITLE
Loader is displayed when user interacts with page of Rife free theme while Delay JS is enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4522]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the user interacts with the page while using the Rife theme and Delay JS is enabled, the loader is displayed

**To Reproduce**

Precondition:
Rife free theme is active

1. Enable Delay JS
2. open the home page
3. move the mouse

**Expected behavior**
No loader displayed with page interaction

**Screenshots**
https://jmp.sh/uEZQe50

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
