### ISSUE TITLE
Enable autoptimize will automatically uncheck our LL video and preview image

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4527]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling Autoptimize while our LL video + preview image is enabled => LL video + preview image will be automatically unchecked

**To Reproduce**
1. Enable LL video and preview image at WPR
2. Enable Autoptimize
3. Check LL options at WPR

**Expected behavior**
Settings do not automatically change without notice 

**Additional context**
- If we can enable LL video + preview image while Autoptimize is enabled then no need to automatically uncheck them
- When we enable LL video + preview image while Autoptimize is enabled, our LL video script is removed from HTML and combined by Autoptimize but our changes for iframe are still applied in the source

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
In fact Autoptimize doesn't do any lazyload for iframes, so we shouldn't be disabling our lazyload for iframes and the sub-option.

### Scope a solution ✅ 
In `inc/3rd-party/plugins/autoptimize.php`, remove the calls to:

```
update_rocket_option( 'lazyload_iframes', 0 );
update_rocket_option( 'lazyload_youtube', 0 );
```

in `rocket_maybe_deactivate_lazyload()` and `rocket_activate_autoptimize()`

### Estimate the effort ✅
Effort `[XS]`
