### ISSUE TITLE
No notice is displayed when invalid regex is removed from Always Purge URL(s) and Never Cache URL(s)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4530]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version =>3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Notice shall be displayed when removing invalid exclusions and it shall include a link to documentation (as per point 4 here https://github.com/wp-media/wp-rocket/issues/4136#issuecomment-974312642)

**To Reproduce**
1. Go to the Advanced rules tab
2. Add the following to exclude from Always Purge URL(s) and Never Cache URL(s)
```
h(.*)apply(.*)(
h(.*)apply(.*))
gtag(
(test
test1
test2\(
```
3. save settings

**Expected behavior**
Notice is displayed by removed fields as same as with Never Cache User Agent, with a link to doc

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
