### ISSUE TITLE
Directory not empty

### ISSUE THREAD

**Issue by SALLYPEMDAS** [wp-media/wp-rocket#4532]
Hi! Thanks for the plugin!!!

We are on Version 3.10.3 

Seeing this on our staging and production site:

Message: Error: rmdir(/home/redacted/public_html/web/app/cache/min/1/releases/v5.3.1/..): Directory not empty
#0 rmdir(/home/redacted/public_html/web/app/cache/min/1/releases/v5.3.1/..): Directory not empty:: called at [/home/redacted/public_html/web/wp/wp-admin/includes/class-wp-filesystem-direct.php:373]
#1 ::{closure} called at [:0]
#2 ::rmdir called at [/home/redacted/public_html/web/wp/wp-admin/includes/class-wp-filesystem-direct.php:373]
#3 WP_Filesystem_Direct::delete called at [/home/redacted/public_html/web/app/plugins/wp-rocket/inc/functions/files.php:377]
#4 ::rocket_clean_minify called at [/home/redacted/public_html/web/app/plugins/wp-rocket/inc/common/purge.php:439]
#5 ::do_admin_post_rocket_purge_cache called at [/home/redacted/public_html/web/wp/wp-includes/class-wp-hook.php:303]
#6 WP_Hook::apply_filters called at [/home/redacted/public_html/web/wp/wp-includes/class-wp-hook.php:327]
#7 WP_Hook::do_action called at [/home/redacted/public_html/web/wp/wp-includes/plugin.php:470]
#8 ::do_action called at [/home/redacted/public_html/web/wp/wp-admin/admin-post.php:70]

Is this error to be expected?

Please advise!

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
Hi @SALLYPEMDAS 
Thanks for contacting us, and apologies for the inconvenience this issue is causing you.
Would you be so kind as to contact our support team with this. They will be much better able to help with troubleshooting, and if they find a code-related issue, we can reopen here.
Thanks!
https://wp-rocket.me/contact/
