### ISSUE TITLE
Minify JS files - JS errors when SCRIPT_DEBUG is set to true

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4538]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.10.3`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When:
1. WordPress's `SCRIPT_DEBUG` is set to `true`.
2. **Minify JavaScript files** is active.

errors like the following pop up in the JavaScript console:
```
Uncaught SyntaxError: Unexpected identifier         wp-polyfill.js?ver=1637832986
```

This is happening both for WordPress files, e.g. `wp-polyfill.js` as well as some plugins files, .e.g.:
```
/elementor-pro/assets/js/webpack-pro.runtime.js
/elementor/assets/js/webpack.runtime.js
/elementor/assets/js/frontend-modules.js
/elementor-pro/assets/js/frontend.js
/elementor/assets/js/frontend.js
/elementor-pro/assets/js/elements-handlers.js
```

The errors are resolved when excluding the files from JavaScript minification.

**To Reproduce**

1. Add `define( 'SCRIPT_DEBUG', true );` in the `wp-config.php` file.
2. Make sure `wp-polyfill.js` is enqueued: `wp_enqueue_script( 'wp-polyfill');`
3. Activate **Minify JavaScript files**.
4. See the error in the JavaScript console.

**Expected behavior**

No errors should be there in the JavaScript console when **Minify JavaScript files** is active and `SCRIPT_DEBUG` is set to `true`.

It seems this is caused by the minification library although I haven't been able to tell what exactly breaks. 
When I minified the original `wp-polyfill.js` file with an online tool and added the minified JavaScript to `/wp-content/cache/min/1/wp-includes/js/dist/vendor/wp-polyfill.js`, there wasn't any error in the console.

In case this is indeed due to that and we can't fix it, we could display a notice that `SCRIPT_DEBUG` is `true` and how that can cause JavaScript errors when **Minify JavaScript files** is active as well. Also, encourage the customers to set that to `false` when they don't need that anymore.

**Screenshots**
![](https://i.vgy.me/L9SqMx.jpg)

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1704124230/309326/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1707656006/310386/
The broken file was `wp-polyfill.js`.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1711933296/311464?folderId=273766

broken files: 
https://jmp.sh/DhGrxO5

wp-polyfill.js

from elementor and elementor pro:
webpack.runtime.js
frontend-modules.js
frontend.js
frontend.js
elements-handlers.js

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1774220074/323148?folderId=2135277

This was again an issue coming from Elementor's files.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
