### ISSUE TITLE
Console Notice: reCAPTCHA couldn't find user-provided function: renderInvisibleReCaptcha when Defer JS is enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4539]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
`Notice: reCAPTCHA couldn't find user-provided function: renderInvisibleReCaptcha` displayed in the console when Defer JS is enabled with https://wordpress.org/plugins/invisible-recaptcha/ plugin enabled

**To Reproduce**
1. Install and activate invisible-ReCaptcha plugin (add keys)
2. Enable Defer JS
3. Open the home page and check the console

**Expected behavior**
No notice displayed 

**Screenshots**
![Screenshot from 2021-11-25 12-34-13](https://user-images.githubusercontent.com/76941962/143426245-6fdf6a1e-e377-484c-ac66-96de59cde749.png)

**Additional context**
- Thanks to @engahmeds3ed notice will be removed by adding auto inline exclusion `renderInvisibleReCaptcha`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@piotrbak This plugin doesn't seem to be maintained anymore, do we still want to go forward with the exclusion for it?

**Comment by piotrbak** [comment]
Since it's just one exclusion, we cna move forward with this. It has more than 100k active installs.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `renderInvisibleReCaptcha` to `DeferJS::$inline_exclusions` array

### Estimate the effort ✅
Effort `[XS]`
