### ISSUE TITLE
Valid regex is removed from files (CSS, JS) exclusions

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4540]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Adding `test\(` to  Excluded CSS Files or Excluded JavaScript Files, will be considered as invalid regex and removed from field

**To Reproduce**
1. Go to File optimization
2. Add `test\(` to  Excluded CSS Files or Excluded JavaScript Files
3. Save and check settings

**Expected behavior**
Expression preserved in fields

**Additional context**
- Currently, msg displayed at notice as 
```
Excluded CSS Files: test(.
Excluded JavaScript Files: test(.
```
- We need to check similar fields

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
