### ISSUE TITLE
Tutorials Tab - Reorganize and Add Videos

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#4541]
**Reorganize the videos in 4 categories (see screenshot attached):**

1. Getting Started
2. Passing the Core Web vitals
3. Troubleshooting
4. Add-ons

**Add 3 new videos for the Core Web Vitals category:**

- How to improve LCP with WP Rocket
`<script src="https://fast.wistia.com/embed/medias/fj7gs031q6.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_fj7gs031q6 videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/fj7gs031q6/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>`

- How to improve FID with WP Rocket
`<script src="https://fast.wistia.com/embed/medias/krqb7ckugp.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_krqb7ckugp videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/krqb7ckugp/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>`

- How to improve CLS with WP Rocket
`<script src="https://fast.wistia.com/embed/medias/5wrdzcmj90.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_5wrdzcmj90 videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/5wrdzcmj90/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>`

![Tutorial tab](https://user-images.githubusercontent.com/48359715/143460163-84c88ee7-c984-4e03-9f38-23aa4a15d75c.png)

**Comment by remyperona** [comment]
### Scope a solution ✅ 
On the `views/settings/page-sections/tutorials.php` view, update the `$rocket_tutorials` array to change the categories name, re-order the videos in the appropriate categories, and to add the 3 new videos.

The new categories titles will require an update to the translation files.

### Estimate the effort ✅
Effort `[XS]`
