### ISSUE TITLE
Update Styles for RocketCDN 

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#4542]
Following the RocketCDN design, the frame for RocketCDN inside the WP Rocket plugin has been re-designed too.
You'll find attached the new design (with/without promo).

The steps coming after clicking the button remain the same.

![RocketCDN no promo](https://user-images.githubusercontent.com/48359715/143465342-c958695b-d388-4bcb-99da-d6ab73e82025.png)
![RocketCDN promo](https://user-images.githubusercontent.com/48359715/143465348-3c3bf653-0383-4976-b7a0-675d43e282a2.png)

**Comment by remyperona** [comment]
Is there any changes to the CTA styling when it's on the "minified" state? Can you provide the assets files for the 3 new icons, and the source to get the new colors?

There will be some HTML changes to be done on the view in `Engine\CDN\RocketCDN\views\cta-big.php`, via the wp-media/module-rocketcdn.

We will need to update the translation files too.

And CSS updates in `src/scss/layout/_Rocketcdn.scss` for the styling.

Effort `[S]`

**Comment by Agathemed** [comment]
We can keep the design as it is for the minified version.

Here are the 3 icons:
![High Performance](https://user-images.githubusercontent.com/48359715/144004151-e1263873-96ae-4a73-98c2-f0e535497a70.png)
![Easy](https://user-images.githubusercontent.com/48359715/144004179-192aff30-8947-48e3-8f26-d99fae1bf93f.png)
![Automatic configuration](https://user-images.githubusercontent.com/48359715/144004199-42ffd40e-9d5c-4853-90c9-a810eabb2457.png)

The svg versions are available here: https://drive.google.com/open?id=1MnwNorqORdcSi4b-MzY_8FicWUY1lWe1&authuser=agathe%40wp-media.me&usp=drive_fs

Design for the 2 banners is available here: https://www.figma.com/file/PG0TAlkrovVbKtz82QqY6a/RocketCDN?node-id=779%3A13006
