### ISSUE TITLE
Loading = "lazy" isnot added to excluded images/video 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4543]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When excluding image/video from LL, loading ="lazy" is not added to the excluded image/video

**To Reproduce**
1. Enable LL image
2. Exclude any image
3. visit the page containing this image and check the source

**Expected behavior**
Excluded Image has loading="lazy"

**Additional context**
- Same applied to exclude iframe

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@Mai-Saad We're also removing it from iframes, it should be fixed together or before this one: https://github.com/wp-media/wp-rocket/issues/3251

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
