### ISSUE TITLE
Setting up mandatory cookie with Cloudflare worker, results in wrong cache being served oppose to serving uncached version

### ISSUE THREAD

**Issue by sammyaxe** [wp-media/wp-rocket#4544]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
User seems to be served wrong cache even though mandatory and dynamic cookie with different value is present. Expected behaviour would be to serve non-cached page if mandatory cookie specific cache does not exist yet.

**To Reproduce**
1. Deploy Cloudflare worker (Code example is in Additional Context section)
2. Make sure that there is cloudflare proxy for the domain
3. Make sure that IP Geolocation setting is enabled in Cloudflare, this makes `request.cf.country` value available
3. Add route for the worker `yourdomain.com/*`
4. Visit website and inspect the site via devtools to confirm you can see cookie set up
5. In your webpage add `<?php echo $_SERVER["HTTP_CF_IPCOUNTRY"];?>` to display country code from which you are visiting.
6. Visit website from different countries using VPN and see if your `$_SERVER["HTTP_CF_IPCOUNTRY"]` value corresponds with mandatory cookie value. In my cases I can sometimes land on different country even though my cookie is set to GB, I can see `$_SERVER["HTTP_CF_IPCOUNTRY"];` value to be something else than GB for e.g. US.

**Expected behavior**
Expectation is to display non-cached page if user comes with mandatory/dynamic cookie set that has no cookie value specific cache generated. Any consecutive visits from same country should be served correct cache based on mandatory cache cookie value which is set in Cloudflare worker.

**Additional context**
I'm trying to create cache for each different country. 

In Cloudflare I'm intercepting every request and inserting user country into `country` cookie with values like US, CA, GB etc
since I want user to be served cache for their country even if they have never visited site before, but someone else did from same country. 

There are two scenarios that I expect, user hits a page from country X, and cache for country X does not exist yet, user is shown non-cached page, next user that comes from same country should be served cached version of the same page, as they get mandatory/dynamic cookie at worker level.

What happens now, it seems that on first load different country cache is served for the user if country specific cache doesn't exist, oppose to non-cached version.

```addEventListener('fetch', event => {
    try {
        event.respondWith(handleRequest(event.request, event))
    } catch (e) {
        console.log(e.toString());
    }
});

async function handleRequest(request, event) {
  
    let url = new URL(request.url);
    let country = null;
    if(request.cf && request.cf.country) country = request.cf.country

    // Check for cookie.
    let cookies = request.headers.get('Cookie') || ""
    if (cookies.includes("country")) {
        // User has been here before. Just pass request through.
        try {
            return fetch(url, request);
        } catch (e) {
            console.log(e.toString());
            return new Response.error(500, "An Error has occurred :(");
        }
    }

    // Forward request to origin, get response.
    let response = await fetch(url, request)

    // Copy Response object so that we can edit headers.
    response = new Response(response.body, response)

    // Set cookie so that we don't add the headers
    // next time.

    var now = new Date();
    var time = now.getTime();
    var expireTime = time + 1000*36000*90;
    now.setTime(expireTime);

    response.headers.set("Set-Cookie", "country="+country+";expires="+now.toUTCString()+";path=/")

    // Return on to client.
    return response

}
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @digiiitalmb thanks for creating this GitHub issue. Have you already contacted our support team?

Our mandatory cookie feature is not complicated system, so I suspect there's something happening in the middle. Please make sure not to have any other caching mechanism working, browser caching for HTML documents should be set always to 0 and rewrite rules should not be present in the htaccess/nginx config.

You can log what cookies we're seeing in the browser here:
https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/classes/Buffer/class-tests.php#L235

We're using GitHub for development purposes, if you need help with troubleshooting, please contact our support team. If we'll be able to confirm the bug on our end, we'll be working on the fix.

**Comment by piotrbak** [comment]
We haven't received any feedback here. I'm going to close it, feel free to reopen if the issue still persists and there's some additional data
