### ISSUE TITLE
exclude NEW google iOS related query strings

### ISSUE THREAD

**Issue by Volant-Digital** [wp-media/wp-rocket#4547]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
**yup**
- Used the search feature to ensure that the bug hasn’t been reported before
**nada**

**Describe the bug**
new QS bypass wp-rocket's cache

https://support.google.com/google-ads/answer/10417364?hl=en
google respond's to Apple’s App Tracking Transparency (ATT) ended up with adding **2 new uniqe query strings** to their tracking:

GBRAID – App measurement (deep linked campaigns). Search & Shopping campaigns.
WBRAID – Web measurement. YouTube, Display, and Discovery campaigns.

( taken from:
https://www.calltrackingmetrics.com/blog/marketing-o/attribution-o/what-apples-ios-14-5-release-update-means-for-call-tracking )

**To Reproduce**
1. use wp-rocket
2. watch iOS traffic bypass wp-rocket

**Screenshots**
![image](https://user-images.githubusercontent.com/78862161/143946392-7552187e-d6e0-4fba-9c33-78b8ef13cbe1.png)

**Additional context**
these two should be added to the default wp-rocket QS exclusion list

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `inc/functions/options.php`, `rocket_get_ignored_parameters()`, add the following to the array:
- `gbraid`
- `wbraid`

Also make sure to regenerate the config file in `rocket_new_upgrade()`, for the corresponding version this issue is fixed in.

### Estimate the effort ✅
Effrt `[XS]`
