### ISSUE TITLE
Compatibility with WooCommerce Bookings (Minification, Delay JS and DJE)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4550]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WooCommerce Bookings has a couple of issues when using WP Rocket JavaScript features. 
The issues seem to be only on product pages where a calendar is used.

**JS Minification**

When minification is enabled, the following error shows up:

![image](https://user-images.githubusercontent.com/1289174/144215068-8c8e383c-7df3-4f8b-bd01-49ec4207646d.png)

Uncaught SyntaxError: Unexpected token ')'

Excluding the following from minification fixes the issue:

```
/wp-content/plugins/woocommerce-bookings/dist/frontend.js
```

**Defer JS**

![image](https://user-images.githubusercontent.com/1289174/144215098-52917dc7-a3ff-4fe0-a19a-6d3278182783.png)

Dependency issues show up.

Uncaught ReferenceError: moment is not defined
Uncaught ReferenceError: wp is not defined

Excluding the following from JS defer fixes the issues:

```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/wp-includes/js/dist/vendor/moment.min.js
/wp-content/plugins/woocommerce-bookings/dist/frontend.js
```

**Delay JavaScript Execution**

![image](https://user-images.githubusercontent.com/1289174/144215127-dec59543-d41e-419f-a6f0-dd8175108182.png)

Dependency issues and errors show up.

Exlucding the following from Delay JavaScript Execution fixes the issue:

```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/wp-content/plugins/woocommerce-bookings/dist/frontend.js
/wp-includes/js/dist/date.min.js
/wp-includes/js/dist/vendor/moment.min.js
/wp-includes/js/jquery/ui/datepicker.min.js
/wp-includes/js/underscore.min.js
/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js
```

**To Reproduce**
1. Activate WooCommerce Bookings
2. Add a booking product with a calendar field
3. Enable the features

**Expected behavior**
WooCommerce Bookings should work with no issues when using with JS features.

**Screenshots**
Attached to each case. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1694288221/307317/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Delay JS part is handled on the backend

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
