### ISSUE TITLE
Automatic exclusion for Load JavaScript deferred and Carousel Upsells and Related Product for WooCommerce

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4553]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
When Load JavaScript deferred is enabled the carousel spacing is reduced, making products appear constrained.

**To Reproduce**
1. Install https://wordpress.org/plugins/carousel-upsells-and-related-product-for-woocommerce/.
2. Add linked products in the Product edit page: https://jmp.sh/wBNI1M4 and post changes.
3. Enable Load JavaScript deferred.
4. Check a product page with the carousel.
5. The products will be constrained, and the `Uncaught ReferenceError: Glide is not defined` error will appear in the console: https://jmp.sh/Po3ZK4d.
6. The error is fixed by excluding `/plugins/carousel-upsells-and-related-product-for-woocommerce/assets/js/glide.min.js` from Load JavaScript deferred.

**Note:** the more products are added to the carousel, the more constrained they will be.

**Expected behavior**
To automatically exclude `/plugins/carousel-upsells-and-related-product-for-woocommerce/assets/js/glide.min.js` when Carousel Upsells and Related Product for WooCommerce is activated.

**Screenshots**
- Constrained carousel: https://jmp.sh/g4mHgWz - 5 products.
- Original carousel: https://jmp.sh/wS0EDgt - 4 products.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1638376098032900

Thanks!!

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Optimization\DeferJS\DeferJS::get_excluded()`, add `/carousel-upsells-and-related-product-for-woocommerce/assets/js/glide.min.js ` to the exclusions array

### Estimate the effort ✅
Effort `[XS]`
