### ISSUE TITLE
Filter Missing to modify data-bg elements.

### ISSUE THREAD

**Issue by alihs** [wp-media/wp-rocket#4564]
Just like there is a filter available for `rocket_lazyload_html` where we can modify images loaded while cache is being generated.
Can we do the same while background-images are being generated? The function is `lazyloadBackgroundImages`.

Looking forward for help/support on how to do that?

**Comment by piotrbak** [comment]
@alihs This doesn't look like issue or feature request. For that kind of questions, please contact our Support Team.
