### ISSUE TITLE
Deactivation popup button "Send & Deactivate" looks grayed-out when active.

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4565]
WP Rocket feedback popup that appears on an attempt to deactivate the plugin has a misleading color of the button.

When one of the options is selected the "Send & Deactivate" button is visible but has a gray color. It looks grayed-out which generally means non-active. 
The button is still active though.

Screenshot:

![image](https://user-images.githubusercontent.com/60236665/144913368-a80e362d-f19d-4712-88fe-1be73163486e.png)

Changing the color to the one similar to the "Skip & Deactivate" button would provide better UI and UX.

Ticket: https://secure.helpscout.net/conversation/1716000704/312480?folderId=3864740

**Comment by Mai-Saad** [comment]
Can reproduce on the trunk.
@NataliaDrause Do we need style as Skip & Deactivate or as here?
![Screenshot from 2021-12-09 10-09-01](https://user-images.githubusercontent.com/76941962/145359665-2578f58e-b90a-4e73-b8bc-56f41d986dfd.png)

While exploring (even on older versions)found that:
1- Initially without selecting anything, the btn has no text at all. Is this what we want?
![Screenshot from 2021-12-09 10-10-17](https://user-images.githubusercontent.com/76941962/145359208-2d438ec0-4aae-41e8-a035-ebaa0e038c0e.png)

2- Selecting 2nd choice then clicking back will remove the Send & activate btn selection
https://jmp.sh/ExqlKGE

**Comment by NataliaDrause** [comment]
@Mai-Saad 

> Do we need style as Skip & Deactivate or as here?
Your variant (blue background) looks much better.

> 1- Initially without selecting anything, the btn has no text at all. Is this what we want?
It looks "broken". I would suggest having the inactive button visible but grayed out (they way it appears when active right now)

> 2- Selecting 2nd choice then clicking back will remove the Send & activate btn selection
I think this is correct, so you can pick a new option: screen recording https://recordit.co/3klQGjVdde
As long as the colors are correct, it'll look good.

These are just my opinions. Others may have different suggestions.

**Comment by piotrbak** [comment]
Not relevant anymore
