### ISSUE TITLE
Payment popup for RocketCDN UI problems with small screens

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4569]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some text or button is not fully displayed on payment popup for mobile screens

**To Reproduce**
1. Go to CDN
2. Click get started
3. Enter credentials and proceed to the next page
4. Some text is not displayed

**Expected behavior**
Pop up is responsive

**Screenshots**

**Additional context**
![Screenshot from 2021-12-07 09-26-52](https://user-images.githubusercontent.com/76941962/144987360-dfbd6848-7072-4d75-ad9d-684ae440fcc6.png)
![Screenshot from 2021-12-07 09-20-27](https://user-images.githubusercontent.com/76941962/144987378-3a183188-cdab-496c-badc-70d8349d0727.png)
![Screenshot from 2021-12-06 09-38-51](https://user-images.githubusercontent.com/76941962/144987429-eba5a31d-1969-4c3e-8806-82adf8e7441c.png)
![Screenshot from 2021-12-06 10-57-39](https://user-images.githubusercontent.com/76941962/144987458-a8e5abae-68eb-4c4e-b430-2bcc023e71a9.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
