### ISSUE TITLE
Config file is not generated when activating the plugin using WP CLI

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4570]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When activating WP Rocket using WP CLI, the configuration file is not generated.

Once the user accesses the admin, the configuration file is then generated. 

This can cause WP Rocket not working when activated using: 
`wp plugin activate wp-rocket`

Not until the user manually access the Admin section of WordPress. 

That can possibly be solved by adding `rocket_generate_config_file();` right after `rocket_init_config_dir();` while running the activation process.
https://github.com/wp-media/wp-rocket/blob/30cf906b5833fac4d691e826c46ad6461a5295a0/inc/Engine/Activation/Activation.php#L76 

**To Reproduce**
1. Activate WP Rocket using WP CLI `wp plugin activate wp-rocket`
2. See that the config file is not created on `wp-rocket-config folder`.

**Expected behavior**
The configuration file should be created when WP Rocket is activated using WP CLI.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1713364694/311853?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
related: https://secure.helpscout.net/conversation/1851896540/338025/

**Comment by hlorofos** [comment]
I used the following workaround to generate website config files without a need to manually visit admin panel:

`wp eval 'rocket_generate_config_file();'`

obviously you should run this as a very last command after you installed and activated the plugin.

**Comment by joejoe04** [comment]
This user has submitted a PR related to this, so I'm posting it here in case it could be useful:
https://secure.helpscout.net/conversation/2127640271/395601/
https://github.com/wp-media/wp-rocket-cli/pull/58
https://wp-media.slack.com/archives/C08N8J6VC/p1674140086985379

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on WP CLI
