### ISSUE TITLE
Minified files containing @font-face are processed with Minify CSS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4573]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.4 
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Minify CSS is minifying `.min` file which contains font rule

**To Reproduce**
Precondition:
- Having a page that uses local stylesheet containing font rules
```
@font-face {
    font-family: my-first-font;
    font-display: auto;
    src: url(https://developer.mozilla.org/static/media/ZillaSlab-Bold.subset.0beac26b.woff2) format("woff2");
  }

```
1. Enable Minify CSS
2. Open the page and check the source
3. The minified file changed from `<link rel="stylesheet" id='minified-styles-with-fontface-rule' href="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/styles/minifycss_style_2.min.css" />` 
to `<link data-minify="1" rel="stylesheet" id='minified-styles-with-fontface-rule' href="https://new.rocketlabsqa.ovh/wp-content/cache/min/1/wp-content/rocket-test-data/styles/minifycss_style_2.min.css?ver=1639035533" />`

**Expected behavior**
.min file is not processed as mentioned [here](https://docs.wp-rocket.me/article/1350-css-minify-combine)

**Additional context**
- This is already the behavior on WPR version 3.8
- In case this is not causing problems and will keep it as is then we will need to clarify this in the docs

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
@Mai-Saad Not sure if you already pinged @camilamadronero somewhere about this for the docs. But, can you confirm what the resulting content of the processed file was?  Any changes? Did we maybe  update the font-display to `swap` but didn't minify the content?

**Comment by camilamadronero-zz** [comment]
Thanks, @webtrainingwheels! Yes, I'm in the loop already thanks to @Mai-Saad!

I've also tested this on [my site](http://camilamo.esy.es/minify-files-check/), and we minified everything in the CSS it seems:

- http://camilamo.esy.es/wp-content/styles/minifycss_style_2.min.css

- http://camilamo.esy.es/wp-content/cache/min/1/wp-content/styles/minifycss_style_2.min.css?ver=1638983102

**Comment by Mai-Saad** [comment]
@webtrainingwheels 

> can you confirm what the resulting content of the processed file was? Any changes? Did we maybe update the font-display to swap but didn't minify the content?

For the `.min.css` file containing font rules:
1- If the file content was already minified => we only force` font-display=swap`
2- If the file content wasn't minified => we minify the file content and force `swap`

Note: if the `.min.css` file does not contain font rules, we won't do any changes to the file independent of the content state (actually minified or not)

**Comment by piotrbak** [comment]
It needs to be covered by our docs.

**Comment by webtrainingwheels** [comment]
@piotrbak Is the above how it's intended to work? I thought we weren't supposed to minify .min files at all?

**Comment by piotrbak** [comment]
@webtrainingwheels Yes, it's happening here:
https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Engine/Optimization/Minify/CSS/Minify.php#L274
