### ISSUE TITLE
Bump minimum support versions to WordPress 5.5 and PHP 7.1

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4574]
**Describe the solution you'd like**
We would like to bump the minimum required WordPress version to 5.5 and PHP version to 7.1.

We have today 97.15% of our users using WordPress 5.5 or + and 98.6% of our users using PHP 7.1 or +.

**What do we need to change?**
In `wp-rocket.php`, update `WP_ROCKET_WP_VERSION` to `5.5` and `WP_ROCKET_PHP_VERSION` to `7.1`

**Comment by iCaspar** [comment]
Also need to update test matrix in github workflows.
