### ISSUE TITLE
Add a notice when a compatibility mandatory/dynamic cookie is excluded

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4577]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Rocket is not notifying the customer if they are trying to use the `Never cache cookie(s)` feature against a dynamic/mandatory cookie automatically excluded as part of compatibility. 

This leads to feature requiring dynamic/mandatory cookie not working properly. 

**To Reproduce**
1. Use any plugin which has a dynamic/mandatory cookie compatibility
2. Exclude the same cookie from `Never cache cookie(s)`
3. Nothing will notify the user about the cookie compatibilities won't be working

**Expected behavior**
We should notify the user that using the `Never cache cookie(s)` will nullify the automatic cookie compatiblity if there is any.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1707114389/310214/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
