### ISSUE TITLE
Sanitize or Notify customers when trying to exclude /wp-content/cache/min/1/ from minification

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4579]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Users might sometimes try to exclude an already processed resource by adding the full path including the `/wp-content/cache/min/1/` from `CSS and JavaScript minification`.

The resource is not excluded. 

**To Reproduce**
1. Enable minification
2. Try to exclude a path using `/wp-content/cache/min/1/`
3. The target file is not excluded

**Expected behavior**
We could sanitize the exclusion box to remove `/wp-content/cache/min/1/` (needs to consider multisite scenario as well).

Alternatively, we can add a nofication won't work if adding `/wp-content/cache/min/1/`. 

**Screenshots**
N/A

**Additional context**
This doesn't apply to `Defer JS` and `Delay JavaScript Execution` exclusions as they come after the minification is processed on the Buffer order. Exclusions including `/wp-content/cache/min/1/` would work there.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
