### ISSUE TITLE
CDN src rewrite for images not working if the URL includes comma

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#4584]
Here is the example HTML provided by the customer which caused the failure in their case:

`<img src="https://www.xxx.com/wp-content/uploads/2021/12/2021121014410054.jpg?image_process=resize,w_850/quality,Q_95/sharpen,100" />`

And in my testing, it seems to be the comma that's actually triggering the problem:

FAIL: `<img src="http://example.com/wp-content/uploads/2021/12/2021121014410054?image_process=resize,w_850" />`

PASS: `<img src="http://example.com/wp-content/uploads/2021/12/2021121014410054?image_process=w_850/quality" />`

FAIL: `<img src="http://example.com/wp-content/uploads/2021/12/2021121014410054?resize,w_850" />`

PASS: `<img src="http://example.com/wp-content/uploads/2021/12/2021121014410054?w_850/quality" />`

Vasilis also did a regex test to demonstrate that our rewrite code fails to make a match: https://regex101.com/r/nh2uhz/1

TICKET: https://secure.helpscout.net/conversation/1723879528/313790/

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
