### ISSUE TITLE
Getwid compatibility with Delay JavaScript Execution (when jQuery is excluded)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4585]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using [Getwid](https://wordpress.org/plugins/getwid/) with Delay JavaScript Execution, and when jQuery is excluded, using the tab block produces the following error: 

![image](https://user-images.githubusercontent.com/1289174/145981201-d1b53fdf-886f-4d3b-93df-109dfe1fdb47.png)

```
jquery.min.js?ver=3.6.0:2    
    Uncaught TypeError: t(...).tabs is not a function
    at HTMLDivElement.<anonymous> (frontend.blocks.js?ver=1639248352:10)
    at Function.each (jquery.min.js?ver=3.6.0:2)
    at s.fn.init.each (jquery.min.js?ver=3.6.0:2)
    at n (frontend.blocks.js?ver=1639248352:10)
    at HTMLDocument.<anonymous> (frontend.blocks.js?ver=1639248352:10)
    at e (jquery.min.js?ver=3.6.0:2)
    at t (jquery.min.js?ver=3.6.0:2)
```

And the tabs are no longer operational. 

**To Reproduce**
1. Use Getwid
2. Add a tab block
3. Enable Delay JavaScript Execution + Exclude jQuery

**Expected behavior**
Getwid should work properly when Delay JavaScript Execution is used and jQuery is excluded. 

**Screenshots**
Added to the description. 

**Additional context**
Excluding the following fixes the issue: 

```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/wp-includes/js/jquery/jquery-migrate.min.js
/wp-includes/js/jquery/ui/tabs.min.js
/wp-includes/js/jquery/ui/core.min.js
```

Added temporarily to - https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#getwid

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
That kind of issues would be fixed with our recommended default exclusions. Feel free to reopen if needed
