### ISSUE TITLE
Preload Links inflating Thirsty Affiliates or Pretty Links referral click count

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4586]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
The Preload Links feature is inflating the Thirsty Affiliates or Pretty Links referral click count, when the links are setup as internal, because the visitors are preloading the referral links when they mouse over the specific links.

**To Reproduce**
1. Install Thirsty Affiliates on a website
2. Check stats for click count
3. Enable Preload Links
4. Check how stats for click count increased, as visitors hovered on links
5. Disable Preload Links
6. Check stats once more, click count should be decreased

This might be difficult to reproduce from scratch, but Nadia provided us with the click stats for the [WPBeginner](https://www.wpbeginner.com/) site where we can see how inflated the count was during the period Preload Links was enabled. See all at  https://wp-media.slack.com/archives/C08N8J6VC/p1639408185296700?thread_ts=1638814946.173200&cid=C08N8J6VC..

**Expected behavior**

Preload Links shouldn't inflate referral statistics. 

The following fix was suggested:

> It might be a good idea to auto-exclude `/refer/` and `/go/` paths from ThirstyAffiliates and Pretty Link plugins to ensure other users don't run into this issue.

**Additional context**
**Ticket:** https://secure.helpscout.net/conversation/1716780906/312607/
**Slack discussion:** https://wp-media.slack.com/archives/C08N8J6VC/p1638814946173200

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Preload\Links\Subscriber::get_uris_to_exclude()`, we can add to the `$uris` variable the 2 patterns `/refer/` and `/go/`.


### Estimate the effort ✅
Effort `[XS]`

**Comment by piotrbak** [comment]
@Tabrisrp There's a possibility to choose between link prefixes (or even add a custom one) in the ThirstyAffiliates plugin. The default one is `/recommends/`.

Prettylinks on the other hand allows to create totally custom links, there are no any suggestions nor recommendations.

Let's add `/recommends/` to the default exclusion list and later we'll see if we should do the compatibilities for each plugins (there are many of them)...

**Comment by GeekPress** [comment]
@piotrbak Does the prefix be saved into an option for `ThirstyAffiliates `? If so, we must grab the value of the option to automatically exclude the right path.

**Comment by piotrbak** [comment]
@Tabrisrp Compatibility for `ThirstyAffiliates` will be needed, they offer a function to grab the prefix. The scenario to cover is to:
1. If the TA plugin is enabled, we'll grab the prefix and exclude only it
2. If it's not enabled (customers are using different affiliate plugin) we'll use default list of exclusions, we'll do 1. step for other plugins in the future, if needed.

The default exclusions are:
```
/refer/
/go/
/recommend/
/recommends/
```

We'll need to use the same filter for both scenarios, to make sure that the custom exclusions will always work.

**Comment by 79ho3ein** [comment]
+1
