### ISSUE TITLE
Deleting post permanently isn't deleting cache for related category

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4587]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When permanently deleting the post, the related taxonomy cache is not cleared

**To Reproduce**
1. Create a category
2. Link post to the category in 1 using post-> edit page
3. Cache the category page
4. Trash the linked post => linked category cache is cleared
5. Cache the category
6. From Trash, delete the post permanently => linked category cache is not cleared

**Expected behavior**
Cache of linked category is cleared

**Additional context**
Thanks to @engahmeds3ed in highlight the expected here

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
