### ISSUE TITLE
Delay JavaScript Execution compatibility with XL WooCommerce Sales Triggers

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4588]
**Before submitting an issue please check that you’ve completed the following steps:**

- [X] Made sure you’re on the latest version: **3.10.5**
- [X] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [XL WooCommerce Sales Triggers](https://xlplugins.com/woocommerce-sales-triggers/) is used with Delay JavaScript Execution, the notification box doesn’t work without triggering any errors in the console : https://jmp.sh/QfDKD3S

Excluding the following fixes the issue:
`/wp-content/plugins/xl-woocommerce-sales-triggers/assets/js/wcst_combined.min.js`

**To Reproduce**
1. Use XL WooCommerce Sales Triggers
2. add a notification in a product
3. activate Delay JS Execution

**Expected behavior**
XL WooCommerce Sales Triggers should work out of the box when Delay JavaScript Execution is enabled.

**Screenshots**
[Screenshot](https://jmp.sh/QfDKD3S)

**Additional context**
HS ticket: https://secure.helpscout.net/conversation/1721065729/313322?folderId=1213662

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `/xl-woocommerce-sales-triggers/assets/js/wcst_combined.min.js` to the exclusion array `DelayJS::$excluded`

### Estimate the effort ✅
Effort `[XS]`

**Comment by alfonso100** [comment]
The file `/xl-woocommerce-sales-triggers/assets/js/wcst_combined.min.js` requires **jQuery**: https://i.imgur.com/1YMj5iR.png

So, excluding only that file will trigger jQuery console errors. 

In the specific site, there are no console errors because jQuery is excluded from DelayJS:
https://i.imgur.com/v3xDWnG.png

**Comment by iCaspar** [comment]
We'll need to find a different solution, given the need to exclude jQuery when this is present.

**Comment by piotrbak** [comment]
We're not able to reproduce the initial issue, it could be related to the specific themes/plugins combination. Let's wait for the future feedback in order to check the root cause.

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
