### ISSUE TITLE
Cloudflare cache not in the lead

### ISSUE THREAD

**Issue by worldsdream** [wp-media/wp-rocket#4589]
I always used wprocket without cloudflare and worked good. Now that I integrated cloudflare free plan, I see issues.

Enabled wprocket addon and added the api for a connection with cloudflare.

- Hosting (origin) uses http protocol 1.x
- Cloudflare uses http protocol 3.x
- No static caching enabled
- No APO or any other paid features enabled

Testing:
- Clear the wprocket cache.
- Clear browser cache
- Some files are served from origin and some are from cloudflare

What should happen:
- Clear wprocket cache
- Clear browser cache
- All files are served from cloudflare

The goal was to move to cloudflare so all files are served from cloudflare and not from the host itself…

**Comment by piotrbak** [comment]
Hello @worldsdream this sounds like an issue with Cloudflare not caching some resources. I'd suggest waiting a couple of minutes/hours to see if they're cached then.

If not, please be in touch with our support, they will investigate headers of your resources. Anyways, it doesn't sound like a bug with our product, if it's and it's confirmed, please reopen the issue.

**Comment by worldsdream** [comment]
@piotrbak Yes, I had to wait a little more for Cloudflare to propagate properly. However, even though it showed that the propagation finished, I double-checked it after 24 hours, and everything worked as described.

I have enabled minify JS/CSS/HTML in WPRocket and Cloudflare.
