### ISSUE TITLE
RocketCDN UI: In WP Rocket 3.10.5 RocketCDN price is not displayed

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#4590]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In a CDN tab, the price for RocketCDN is missing, This started happening in WP Rocket 3.10.5. I checked previous 3.10.x versions and they don't have this issue. All sites where I noticed this, can communicate with https://rocketcdn.me/api/pricing/

**To Reproduce**
1. Install WP Rocket 3.10.5
2. Click on the CDN tab in WP Rocket settings
3. See error

**Expected behavior**
The price for monthly RocketCDN subscription should be displayed

**Screenshots**
![VshHUDk](https://user-images.githubusercontent.com/2566224/146390973-4425bed1-a6c5-4614-ba47-ff2ccb61b297.jpeg)

**Additional context**
We don't have any support tickets reporting this, yet. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is what is logged in `$data` when visiting the dashboard.

```
[2021-12-16 15:01:02] $data: Array
(
    [is_discount_active] => 
    [discounted_price_monthly] => 6.99
    [discounted_price_yearly] => 95.88
    [discount_campaign_name] => 
    [end_date] => 2020-12-02
    [monthly_price] => 7.99
    [annual_price] => 79.99
)

[2021-12-16 15:01:02] $data: Array
(
    [container_class] => 
    [promotion_campaign] => 
    [promotion_end_date] => 
    [nopromo_variant] => --no-promo
    [regular_price] => 
    [current_price] => 7,99
)
```
