### ISSUE TITLE
Exclude additional hubspot domain from Load JavaScript Deferred

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4593]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
We have an [automatic exclusion for Hubspot ](https://github.com/wp-media/wp-rocket/blob/7efe5e0c685884f99cf54e6fc6b178a1a98fc256/inc/Engine/Optimization/DeferJS/DeferJS.php#L203)to resolve an error with Load JS Deferred: 

The same script, `shell.js` can also be loaded from this other domain which should also be excluded: 
`js-eu1.hsforms.net`

**To Reproduce**
1. Add this script to the site: 
```
<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/shell.js"></script>
<script>
  hbspt.forms.create({
	region: "eu1",
	portalId: "25164403",
	formId: "dfed4d9e-e999-4272-a287-8fabd2e0fdd7"
});
</script>
```
2. Activate Load JS Deferred
3. You will see this error: `hbspt is not defined`

**Expected behavior**
There should be no error.

**Additional context**
Original issue: https://github.com/wp-media/wp-rocket/issues/1378
New Ticket: https://secure.helpscout.net/conversation/1725349434/314036?folderId=377611

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `DeferJS` class, add `js-eu1.hsforms.net` to the `$exclude_defer_js` array.

### Estimate the effort ✅
Effort `[XS]`
