### ISSUE TITLE
Price format shall be consistent while FR local

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4596]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.5.10.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The regular price is displayed with `,` while discount price with `.`

**To Reproduce**
- Have an active campaign
1. Set user profile to Francais
2. Open the CDN tab
3. Regular price is using `,` instead of `.`

**Expected behavior**
Regular price using `.`

**Screenshots**
![Screenshot from 2021-12-17 08-26-43](https://user-images.githubusercontent.com/76941962/146499716-bf37f767-632e-419c-91c0-d403622f33f6.png)

**Additional context**
- Same with Deutsch (we need to check all supported language)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
In fact in french, the separator for decimals is a comma instead of a dot, so in this case it's the regular price that is using the correct formatting, and the discounted one that isn't.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Remove the method `normalize_number()` and its usage in the `Engine\CDN\RocketCDN\NoticesSubscriber`, as we already have `number_format_i18n()` to handle number formatting in the different locales.

### Estimate the effort ✅
Effort `[XS]`
