### ISSUE TITLE
Add an expire banner on the plugins page (like update banner)

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#46]

**Comment by Tabrisrp** [comment]
We have the text `Renew your licence of WP Rocket to receive access to automatic upgrades and support.` currently, @GeekPress was this the original intent of this issue?

If yes, we can close it.

**Comment by GeekPress** [comment]
I don't remember exactly what was the original request. As we have the renew text, we can consider this issue "fixed".
