### ISSUE TITLE
Delay javascript compatibility Prismatic plugin

### ISSUE THREAD

**Issue by worldsdream** [wp-media/wp-rocket#4600]
When you enable the feature Delay JavaScript Execution in the WP Rocket plugin, there are a couple of issues with [Prismatic](https://wordpress.org/support/plugin/prismatic/) plugin.

The issues that I see are:

1. Prism copy button doesn’t show up
2. Syntax highlighting colors don’t show up
3. Line numbers don’t show up

At WP Rocket they have a Delay JavaScript Execution compatibility exclusions page.

I searched for “Prismatic”, but unfortunately, I can’t find anything yet.

Do we need to add a line to the WP Rocket exclusion list to have 100% compatibility with Prismatic when enabling delay javascript execution compatibility?

Is there something that WProcket needs to add in the [Compatibility list](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions)?

Before screenshot: https://i.imgur.com/vYMEhtH.png
Enable feature screenshot: https://i.imgur.com/LTYZpqj.png
After screenshot: https://i.imgur.com/714hywX.png

With the “After screenshot”, you can see that the copy button, line numbers, and colors are missing.

PS: I did create a post at Prismatic WP plugin, but the developer likes to fix it if he can. Perhaps WP Rocket can show some love?

https://wordpress.org/support/topic/wprocket-delay-javascript-compatiblity/

**Comment by piotrbak** [comment]
Hello @worldsdream thank you for creating the issue. Have you already contacted our support team, so they would be able to investigate the case and find the correct exclusions? If not, please do so or post more detailed steps to reproduce it for us, for example:
1. Use Gutenberg editor
2. Create a new page and add specific element
3. Visit the page in incognito mode
4. See an error

Thank you!

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
