### ISSUE TITLE
Prevent unexisting fonts from getting preloaded

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4601]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When unexisting fonts are preloading using the Preload Fonts feature, it results in a 404 error on the browser's console. 

**To Reproduce**
N/A

**Expected behavior**
We should check first if the font exists before adding it to the page. 

This should be possible by checking if the font is reachable here: 

https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Engine/Preload/Fonts.php#L121-L139

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1719989017/313154

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
