### ISSUE TITLE
DJE and defer JS compatibility with  the WP Content Copy Protection & No Right Click

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4605]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript Execution is used with [WP Content Copy Protection & No Right Click](https://wordpress.org/plugins/wp-content-copy-protector/), a console error shows up: 

```
Uncaught ReferenceError: on is not defined
    at <anonymous>:5:33
    at (index):4
    at new Promise (<anonymous>)
    at RocketLazyLoadScripts._transformScript ((index):4)
    at async RocketLazyLoadScripts._loadScriptsFromList ((index):4)
    at async RocketLazyLoadScripts._loadEverythingNow ((index):4)
```

The following script seems to be faulty: 

```
<script id="wpcp_css_disable_selection" type="text/javascript">
var e = document.getElementsByTagName('body')[0];
if(e)
{
	e.setAttribute('unselectable',on);
}
</script>
```
Excluding `wpcp_css_disable_selection` fixes the issue.

The issue is triggered by a faulty JavaScript code on `WP Content Copy Protection & No Right Click`.

```
<script id="wpcp_css_disable_selection" type="text/javascript">
var e = document.getElementsByTagName('body')[0];
if(e)
{
	e.setAttribute('unselectable', on);
}
</script>
```
The attribute `value` is missing single quotes mark makes the parser look for an undefined function/variable. 

The weird part is that there are no console errors when Delay JavaScript Execution is not used 🤯

Fixing the error makes the exclusion not required: 

```
<script id="wpcp_css_disable_selection" type="text/javascript">
var e = document.getElementsByTagName('body')[0];
if(e)
{
	e.setAttribute('unselectable', 'on');
}
</script>
```

The same issue happens when Combine JavaScript is enabled. 

This time, excluding the following fixes the issue: 

```
e.setAttribute('unselectable',on);
```

**To Reproduce**
1. Install `WP Content Copy Protection & No Right Click`
2. Use Delay JavaScript Execution with no exclusions
3. See error

**Expected behavior**
There shouldn't be any console error when using Delay JavaScript Execution.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1732517182/315197/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Optimization\DelayJS\HTML::$excluded`, add `wpcp_css_disable_selection` as an exclusion pattern

### Estimate the effort ✅
Effort `[XS]`
