### ISSUE TITLE
jQuery regex doesn't exclude unminified jQuery - eg jquery.js 

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4607]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The Regex to exclude jQuery `/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js` doesn't take into consideration unminified jQuery - eg. `jquery.js`

This will give the user the impression that jQuery was excluded by using the proposed pattern. 

Using the following exclusions fixed the issue: 

Excludes jQuery migrate: 

`/jquery((.min|.slim|.slim.min)|.*?([0-9]+)(.min|.slim|.slim.min))?.js`

Includes jQuery migrate:

`/jquery(-migrate)?((.min|.slim|.slim.min)|.*?([0-9]+)(.min|.slim|.slim.min))?.js`

Found here - https://github.com/wp-media/wp-rocket/issues/4371

**To Reproduce**
1. Add `jquery.js`
2. Use the exclusion pattern `/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js`
3. . See that `jquery.js` won't be excluded

**Expected behavior**
All forms for the jQuery core library should be excluded using the pattern. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1732517182/315197/
This patterns fix the issue though it's not directly related - https://github.com/wp-media/wp-rocket/issues/4371

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
I'll close it in favor of [4371](https://github.com/wp-media/wp-rocket/issues/4371). We'll improve the regex there.
