### ISSUE TITLE
Remove Unused CSS to inform the user if there is a CSS error that might prevent a file from getting processed

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4610]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a CSS error exists in a CSS file, it might not be processed properly on SaaS. 

A couple of examples: 

- An additional `}`  or `{` or `;` between two rulesets on a CSS file will prevent anything below it from getting processed.
- An additional `,` or `(` or `)` between two rulesets will be added to the resulting CSS and won't be parsed by the browser.

**To Reproduce**
1. Add a faulty CSS like on the example
2. Process using RUCSS
3. No error will be communicated to the user about why the CSS wasn't properly processed

**Expected behavior**
The user should be information of potential issues that might result from having a faulty CSS.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/147340882-102a9f5e-3180-4f31-903f-bd4b0539050e.png)

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1727751196/314385

Jigsaw CSS validator has a JSON API that can be used. 

https://jigsaw.w3.org/css-validator/validator?uri=LINK_TO_THE_FILE_OR_PAGE&warning=0&profile=css2&output=json

And will return a JSON output with the error and the faulty file: 

```
{
  "cssvalidation" : {
     "uri"       : "https://www.mozilla.org/en-US/firefox/new/",
     "checkedby" : "http://www.w3.org/2005/07/css-validator",
     "csslevel"  : "css2",
     "date"      : "2021-12-24T09:51:49Z",
     "timestamp" : "1640339509987",
     "validity"  : false,
     "result"    : {
		"errorcount"   : 309,
		"warningcount" : 32
                   }
       ,
     "errors"    : [
  
      { 
	"source" : "https://www.mozilla.org/media/css/protocol-firefox.75c3df326a9e.css",
	"context" : "",
        "type"    : "java.lang.Exception",
	"message" : "Unknown error java.lang.Exception: class org.w3c.css.properties.css2.Css2Style cannot be cast to class org.w3c.css.properties.css2.font.Css2Style (org.w3c.css.properties.css2.Css2Style and org.w3c.css.properties.css2.font.Css2Style are in unnamed module of loader org.w3c.jigsaw.servlet.AutoReloadServletLoader @30ce3b37)"
      }
     ,
    ]
    }
}
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
This is an issue with some sites.

Used CSS added but missed some selector like the issue stated.
So, normally i go through https://jigsaw.w3.org/css-validator/ and add url with querystring `?nowprocket`
It will scan all inline/external and show the exact line of that file & w3c validator will mark it as **"Parse Error"**
![image](https://user-images.githubusercontent.com/48652123/147386738-60ef2767-c477-42ce-a022-0fc2f06f4f16.png)

But if wprocket inform us, that's also good feature.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
