### ISSUE TITLE
Delay JavaScript Execution compatibility with Gravity conditions

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4611]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript Execution is used with Gravity conditions, the form is not working and the following browser console message shows up: 

```
Uncaught ReferenceError: gf_apply_rules is not defined
    at HTMLDocument.<anonymous> ((index):1110)
    at e (jquery.min.js?ver=3.6.0:2)
    at t (jquery.min.js?ver=3.6.0:2)
```

Excluding the following fixes the issue: 

```
/gravityforms/js/conditional_logic.min.js
```

**To Reproduce**
1. Use Gravity forms conditions
2. Enable Delay JavaScript Execution
3. See error

**Expected behavior**
Gravity forms conditions should work without breaking the form when Delay JavaScript Execution is used.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/147378908-78362614-a9bf-4699-beaa-248954d1156e.png)

**Additional context**
The issue is there only if jQuery is excluded from Delay JavaScript Execution.
Ticket - https://secure.helpscout.net/conversation/1736063475/315781
Added to - https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#gravityforms

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Optimization\DelayJS\HTML::$excluded`, add `/gravityforms/js/conditional_logic.min.js` as an exclusion pattern

### Estimate the effort ✅
Effort `[XS]`
