### ISSUE TITLE
Delay JavaScript Execution compatibility with WP Search with Algolia

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4612]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript Execution is used with the [WP Search with Algolia](https://wordpress.org/plugins/wp-search-with-algolia/), the search featyre is not functional and the following console error shows up.

```
Uncaught ReferenceError: algoliasearch is not defined
    at HTMLDocument.<anonymous> ((index):890)
    at e (jquery.min.js?ver=3.6.0:2)
    at t (jquery.min.js?ver=3.6.0:2)
```

Excluding the following from Delay JavaScript Execution fixes the issue: 

```
/wp-search-with-algolia/js/algoliasearch/dist/algoliasearch-lite.umd.js
/wp-search-with-algolia/js/autocomplete-noconflict.js
/wp-search-with-algolia/js/autocomplete.js/dist/autocomplete.min.js
var algolia
```

**To Reproduce**
1. Enable WP Search with Algolia and link it to a working Algolia account
2. Enable Delay JavaScript Execution with no exclusions
3. See error

**Expected behavior**
WP Search with Algolia should work with no issues when using Delay JavaScript Execution. At least after user interaction.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/147379365-fedfc37d-a34c-49af-a8cf-f45c0cbbbbf5.png)

**Additional context**
jQuery needs to be excluded as well as one of the scripts is initialized using jQuery: 

```
jQuery( function () {
		/* Initialize Algolia client */
		var client = algoliasearch( algolia.application_id, algolia.search_api_key );
```

Ticket - https://secure.helpscout.net/conversation/1736063475/315781/
Added to - https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#wp-search-with-algolia

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\Optimization\DelayJS\HTML::$excluded`, add the following exclusion patterns:
```
/wp-search-with-algolia/js/algoliasearch/dist/algoliasearch-lite.umd.js
/wp-search-with-algolia/js/autocomplete-noconflict.js
/wp-search-with-algolia/js/autocomplete.js/dist/autocomplete.min.js
var algolia
```

### Estimate the effort ✅
Effort `[XS]`

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
