### ISSUE TITLE
The wp-rocket plugin is incompatible with jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4613]
hello
The jet woobuilder plugin has a query to display recently visited products. But when wp-rocket is enabled, this query completely crashes.
Please make wp-rocket compatible with this plugin. Both plugins are very popular, so this incompatibility is very bad. Please investigate this issue. thanks

**Comment by piotrbak** [comment]
Hello @79ho3ein can you tell me what does `this query completely crashes` mean?

If the results are cached, we can do nothing about this, authors should make sure that their plugin is compatible with page cache (use cookies to store and ajax to display data, for example).

**Comment by 79ho3ein** [comment]
hello @piotrbak, thank you for your attention.

The problem is that if, for example, we see the iphone 13 among the products, it will add other products to the list in addition to the iphone 13. Or sometimes it does not even show the product we have visited. But by disabling the wp-rocket plugin, the recently viewed product query works properly.

**I even disabled all the Rocket plugin options, but still the problem was not fixed.**

I first raised this issue with the authors of the Jet woobuilder plugin, who said: We use woocommerce_recently_viewed cookies to get recently viewed products. They also said that there is no problem on our part. Because we follow WooCommerce cods.

thank you

**Comment by piotrbak** [comment]
@79ho3ein This sounds like a problem with cache itself. If plugin is not using ajax to refresh some output, then we'll cache the response and it'll stay like it was during the first request.

If `woocommerce_recently_viewed` cookie is used, you can use this helper plugin to be sure things are displayed correctly:
https://github.com/wp-media/wp-rocket-helpers/tree/master/compatibility/wp-rocket-compat-wc-recently-viewed-widget

If you have any further questions, please reach our support Team.

**Comment by 79ho3ein** [comment]
thank you dear @piotrbak .
