### ISSUE TITLE
Partial purge does not clear CPT archive when non-default cache files are used

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4617]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
This arose in regards to WooCommerce, but I guess affects CPTs in general. Some customers complained that updating a product's stock didn't reflect on their main Shop page. Since this is the archive page for the products, it's expected that it should be purged when a product is updated. 

It works using default cache settings. But if using WebP, (or I guess any option that creates non-default cache files), the Shop page won't be cleared. 

In `$purge_urls` we are only looking for standard cache file names: 

```
    [0] => https://www.wpthemes.dev.cc/product/test-beaver-product/
    [1] => https://www.wpthemes.dev.cc/store/index-https.html
    [2] => https://www.wpthemes.dev.cc/store/index-https.html_gzip
    [3] => https://www.wpthemes.dev.cc/store/index-httpspage
    [4] => https://www.wpthemes.dev.cc/product/variable-product/
    [5] => https://www.wpthemes.dev.cc/product/wordpress-pennant/
    [6] => https://www.wpthemes.dev.cc/author/lucyb/

```
**To Reproduce**
1. Enable WebP cache and WooCommerce
2. Update a Product
3. Log the contents of `$purge_urls`
4. Note that the main Shop page is not purged. 

**Expected behavior**
All versions of the cache for the archive page of a CPT should be purged when updating content.

**Additional context**
This is related to https://github.com/wp-media/wp-rocket/issues/2068 and could be tackled at the same time. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
🤦‍♀️ Sorry,  I'm closing as a duplicate, in fact. It's the same as: https://github.com/wp-media/wp-rocket/issues/4508

**Comment by alfonso100** [comment]
new case here: https://secure.helpscout.net/conversation/2739932900/518810/
