### ISSUE TITLE
Automatically exclude Bridge theme files from static file generation

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4622]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - **Yes, 3.10.5.1**
- Used the search feature to ensure that the bug hasn’t been reported before - **Yes**

**Describe the bug**
Static File Creation breaks [Bridge theme's](http://bridge.qodeinteractive.com/) styles and scripts.

**To Reproduce**
1. Install Bridge theme (not sure if any specific Bridge feature triggered the error).
2. Enable WP Rocket with no UI features enabled. 
3. See broken layout and errors in the console:
![image](https://user-images.githubusercontent.com/23031592/147706154-fb88f4e0-272d-47ad-9bd8-591737df1234.png)

**Expected behavior**
Automatically exclude these Bridge theme files from the static file generation optimization.

**Additional context**
The issue is fixed if these files are excluded using the [WP Rocket | Exclude from Static File Creation](https://github.com/wp-media/wp-rocket-helpers/raw/master/static-files/wp-rocket-static-exclude-dynamic-files/wp-rocket-static-exclude-dynamic-files.zip) helper plugin.

```
wp-content/themes/bridge/js/default_dynamic_callback.php
wp-content/themes/bridge/css/style_dynamic_callback.php
```

Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1640797019014100
Tickets: https://secure.helpscout.net/conversation/1737671894/315972/ and https://secure.helpscout.net/conversation/1742613768/316567/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@piotrbak I'm adding the potential grooming under, but I'm wondering if this should be investigated more at first. Bridge is using this for a while I believe, and we didn't have any issue with those files before. So did something change on their side? Is it something else?

Also not sure it's a `good first issue`, as we would be creating a new method, and it needs tests added alongside it too.

### Scope a solution ✅ 
In `ThirdParty\Themes\Bridge`

Add a new method `exclude_static_file_generation( $excluded_files )`. In it, exclude the 2 paths from bridge, using the same logic as in https://github.com/wp-media/wp-rocket/blob/d777fbda8b3e584605f755cf68f42ae8f2796b53/inc/ThirdParty/Themes/Avada.php#L132

Add a new key/value pair in `get_subscribed_events()` array:
- `rocket_exclude_static_dynamic_resources` => `exclude_static_file_generation`

Add tests for the new method

### Estimate the effort ✅
Effort `[S]`

**Comment by piotrbak** [comment]
@Tabrisrp You're right about the `good first issue`. When it comes to the Bridge theme itself, I've been investigating it for a while, it looks like they're loading the `.php` dynamic file only when there are problems with permissions:
![image](https://user-images.githubusercontent.com/26767037/148541634-9a023fa4-e608-4c51-9fb7-4f8062594b69.png)

That's why we haven't had any problems with that so far. I also wasn't able to trigger this error at all. Changing priority since it's rather very rare problem.

**Comment by piotrbak** [comment]
We have only 1 ticket since beginning about this issue. I'm going to close it for now.

**Comment by WordPresseur** [comment]
Another case: https://secure.helpscout.net/conversation/2825845505/536419
