### ISSUE TITLE
Count of total preloaded pages

### ISSUE THREAD

**Issue by alihs** [wp-media/wp-rocket#4623]
We are working with preload and also use Cloudflare.
We have noted if pages are not preloaded they are wrongly cached within Cloudflare.
Would like to know if we have a list of pages that are preloaded within the dashboard or if i could find a hook/action that i could plug-into and create a custom function for this?

**Comment by piotrbak** [comment]
Hello @alihs thank you for creating the issue. We'll be rewriting the preload completely, unfortunately, it's still not scheduled.

When it comes to the status of the preload we don't have any official script, but one of our customers has written a script. You can reach me here piotr[at]wp-media.me and I'll send it to you. Of course, we don't maintain it nor guarantee that it'll work, but you would be able at least to see the concept.
