### ISSUE TITLE
Update Texts for the Expiring Soon and Expired Banners

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#4627]
We need to update the text displayed in the Expiring Soon and Expired banners in the plugin. 

You'll find the new texts and translation [here.](https://docs.google.com/document/d/1gSwxpp0VikIDJkO4uRWERXZX-lepXmCJlGdTtKIuLKo/edit?usp=sharing)

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `Engine\License\Renewal.php`

method `display_renewal_expired_banner()`:
- we don't need to get the discount percent/price anymore, so we can directly pass only the `renewal_url` to the view

in `Engine\License\views\renewal-expired-banner.php`:
- Update the paragraphs with the text changes
- Remove the references to the discount percent/price

in `Engine\License\views\renewal-soon-banner.php`:
- Use the `discount_percent` value to conditionally display the text with/without discount. If `discount_percent` === 0, it means there is no discount to display.

Update the related tests

### Estimate the effort ✅
Effort `[S]`
