### ISSUE TITLE
WP Rocket 3.10.6 - Conditional Comments removed when Async CSS is enabled

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4639]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
**IE Conditional Comments** are removed when using the latest version of **WP Rocket 3.10.6** and **Async CSS.**
It is related to #4186 and PR #4583 

**To Reproduce**
1. Add the following conditional comments to the theme header: https://snippi.com/s/cgfb2hk
2. Check you're on **3.10.6** 
3. Enable **Async CSS**
4. See the comments removed
5. Rollback to 3.10.5.1
6. See the comments preserved

**Expected behavior**
Conditional comments should be preserved. 

**Screenshots**
![YyTXjwM](https://user-images.githubusercontent.com/229406/148835930-d6c72504-6702-4599-ab1c-921a1743c319.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
Related: https://secure.helpscout.net/conversation/1750239202/317944?folderId=377611

**Comment by worldwildweb** [comment]
related https://secure.helpscout.net/conversation/1760535314/320015?folderId=5547167

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1762515052

**Comment by alfonso100** [comment]
related: https://secure.helpscout.net/conversation/1775567482/323492/
