### ISSUE TITLE
Disable OPCache purging on SiteGround

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4640]
**Is your feature request related to a problem? Please describe.**

We have at least a couple of reports from SiteGround customers that they are getting the `OPcache purge failed.` message when they are trying to purge the OPCache.

Their support told one of [the customers](https://secure.helpscout.net/conversation/1729608368/314685/#thread-5074820863) (internal link) they are using file-based OPcache, and the folder isn't accessible to plugins.

**Describe the solution you'd like**

On SiteGround, do not display:
1. The "Clear OPCache" admin menu item.
![](https://i.vgy.me/gyyDaq.jpg)
2. The dashboard "Quick Actions".
![](https://i.vgy.me/5YRDrg.jpg)

**Additional context**

**Tickets:**
https://secure.helpscout.net/conversation/1752825270/318477/
https://secure.helpscout.net/conversation/1729608368/314685/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1644124796/297607/

**Comment by piotrbak** [comment]
Tagging it as blocked as I'd like to see if WordPress built-in OPCache invalidation will work there.

**Comment by remyperona** [comment]
@piotrbak From the PHP doc for `opcache_invalidate()`, `This function only invalidates in-memory cache and not file cache.` It's the same for `opcache_reset()`.

I was not able to find a way to purge the file-based OPCache from a PHP function or script.

What we could do is check for the `opcache.file_cache_only` configuration value, and if it's set to `true`, we don't try to purge OPCache, and also don't display any UI element related to it.

**Comment by piotrbak** [comment]
@Tabrisrp This seems to be a good approach.

@vmanthos Do we have access to any SiteGround website to confirm in the PHPINFO that the `opcache.file_cache_only` value there is set to `true`?

**Comment by vmanthos** [comment]
> Do we have access to any SiteGround website to confirm in the PHPINFO that the opcache.file_cache_only value there is set to true?

No, we don't, but I'll keep my eye on this.

> I was not able to find a way to purge the file-based OPCache from a PHP function or script.

@Tabrisrp The [WP OPcache](https://wordpress.org/plugins/flush-opcache/) plugin claims they "support both memory and file caching". Maybe you want to take a look there.

**Comment by piotrbak** [comment]
@vmanthos Thank you, could you also check if the above plugin is compatible with their stack?

**Comment by vmanthos** [comment]
> could you also check if the above plugin is compatible with their stack?

According to SiteGround's support, the plugin isn't compatible because the path they save OPCache is out of the reach of plugins.

**Comment by remyperona** [comment]
I'm not seeing anything in this plugin that could be clearing the file cache, it uses `wp_opcache_invalidate()` too.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `inc/admin/upgrader.php`, `rocket_reset_opcache()`, add a check for `opcache.file_cache_only`. If it's true/1, bail-out, as we won't be able to reset OPCache with `opcache_reset()`.

We also need to add  this check in `rocket_admin_bar()` (`inc/common/admin-bar.php`), and in `inc/views/settings/page-sections/dashboard.php`, to prevent the display of the purge OPCache links in this case.

### Estimate the effort ✅
Effort `[XS]`

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1763060057/320494?folderId=3864740

**Comment by NataliaDrause** [comment]
PHP info from the previous ticket: 
![image](https://user-images.githubusercontent.com/60236665/150787048-8625be0b-8685-4da7-94a0-60b7d30af6cd.png)
Full-screen image: https://i.imgur.com/qNn7aI7.png

**Comment by remyperona** [comment]
Closing this as we are removing the OPCache purge feature.
