### ISSUE TITLE
Clear EWWW/ExactCDN cache when WP Rocket cache is cleared

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4643]
**Is your feature request related to a problem? Please describe.**
When updating posts, the ExactCDN cache needs to be manually purged. Maybe we could automate this?

**Describe the solution you'd like**
Clear ExactCDN cache to keep caches in sync after updating posts or pages in WP Rocket.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1752760856/318463?folderId=2683093

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
