### ISSUE TITLE
Delay JS auto-exclusion for WooCommerce Product Gallery break Elementor scripts

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4648]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.6
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
We add auto-exclusions for WooCommerce Product Gallery as per #4077 on pages with the gallery, but this breaks Elementor's elements.

On customer's site, the issue affects the desktop menu button - it is not responsive only on the Product pages that contain the gallery.
Menu works as expected on all other pages where we don't have auto-exclusions.

The following console error pops up when Delay JavaScript Execution is enabled with no exclusions:
![image](https://user-images.githubusercontent.com/60236665/149152483-dd850c86-4ef7-4e3d-888f-bfeeaeada1af.png)
full-screen image: https://i.imgur.com/skWnL7Q.jpeg

jQuery scripts on the Product page:
![image](https://user-images.githubusercontent.com/60236665/149153005-9be6a96a-2104-43dc-95ae-c9c61f5efd06.png)
full-screen image: https://i.imgur.com/Qqzy1Pn.png

vs. jQuery scripts on the homepage or other pages with no product gallery:
![image](https://user-images.githubusercontent.com/60236665/149153494-49b535d7-16f9-4953-b5d7-b2087fd37e84.png)
full-screen image: https://i.imgur.com/b7kQ63d.png

Adding the following scripts to the Exclusions for Delay JS resolved the issue for this case:
```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/elementor-pro/assets/lib/sticky/jquery.sticky.min.js
/wp-content/plugins/elementor-pro/assets/js/elements-handlers.min.js

```
but this list might be specific to the site and more exclusions would be needed.

Also adding these exclusions globally cause performance drop on other pages that don't need the exclusions.

In general, all the issues are resolved with our exclusions from the list here: https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#elementor-pro

**To Reproduce**
Reproduced on customer's site that uses Elementor 3.5.3 and Elementor Pro 3.5.2 and WooCommerce Product Gallery on Product pages.
1. Enable Delay JS option with no exclusions
2. Check homepage or other pages that are not product. Everything works with no issues and menu button is responsive.
3. Check Product page that has WooCommerce Product Gallery - there will be console errors shared above and menu button is not clickable.

**Expected behavior**
Elementor elements should be working as expected and with no console errors when auto-exclusions for WooCommerce Product Gallery are applied.

**Additional context**
Similar issue was #4224 on Avada

Ticket: https://secure.helpscout.net/conversation/1744124804/316790/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
If we turn off this by default wc exclusion (using filter by rocket ) , and exclude only jQuery above errors also noticable in console after UI.

Like this thread #4156 , so it's not completely related to wc exclusion, it's something which missing JS load order

**Comment by piotrbak** [comment]
Adding the following files to the exclusion on the product page with gallery resolves the issue:

- `/elementor-pro/assets/lib/sticky/jquery.sticky.min.js`
- `/elementor-pro/assets/js/elements-handlers.min.js`

We'll probably add those exclusions to the not empty product gallery exclusions:
https://github.com/wp-media/wp-rocket/blob/38e0fa379460fdc5bf6cbe6b49580c422d913274/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L553

**Comment by piotrbak** [comment]
@NataliaDrause whenever you have a chance, could you confirm on the customer's website that the [above](https://github.com/wp-media/wp-rocket/issues/4648#issuecomment-1013391073) exclusions solve the issue?

**Comment by jazir555** [comment]
Is there a way for the elementor team to modify their scripts loading method to allow these files to be delayed by wp rocket without breaking functionality?

**Comment by jazir555** [comment]
@piotrbak

**Comment by aharonyltd** [comment]
Hi
How do I turn off Delay JS auto-exclusions?
Anyone know?

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1963257907/358787/

Due to the automatic Gallery exclusions, the navigation menu breaks on Product pages only.

I had to exclude the following scripts:
```
/jquery/jquery.min.js
/jquery-migrate(.min)?.js
/elementor-pro/assets/lib/sticky/jquery.sticky.min.js
/elementor-pro/assets/js/elements-handlers.min.js
```
But these are applied globally and deteriorate homepage and other non-product pages' performance.

**Comment by worldwildweb** [comment]
related: https://secure.helpscout.net/conversation/1978541946/361811/
This broke the Elementor scripts and further other scripts that are dependent on it: jet-reviews, jet-gallery, AcyMailing

**Comment by FreddyEE** [comment]
I had to use this code, because my site had some issues with Elementor after the delay of JS:

`ElementorProFrontendConfig`
`elementorFrontendConfig`
`/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js`
`/jquery-migrate(.min)?.js`
`/elementor/`
`/elementor-pro/`

is there any way to exclude the least quantity of URLs ?

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
