### ISSUE TITLE
Extract all the "Can do X" checks to a "FeatureEnabledChecker"

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#4651]
In our current architecture, many features (and sub-functions within features) have a private "can_do" check. 

This is an anti-pattern: it requires the feature class to know details about the overall plugin state.
The code smell for this is that each feature/sub-function needs extensive additional test complexity to check all the conditions when it should or should not run. Any time the conditions for allowing a functionality change, the tests need to be updated and can break in unexpected ways.

All these checks should be extracted to another class (or set of classes) with the singular concern to check whether a feature should be allowed. The new class(es) should be injected into any given feature subscriber to enable a single check (runs or does not run), and the specifics of when features run tested separately in the checker class's public methods. Any given change in the specific requirements of a given feature to run based on system conditions can be tested in a single place with a single point of failure.

**Comment by piotrbak** [comment]
@Tabrisrp @CrochetFeve0251 What do you think about this one? Is it still something we should consider?

**Comment by piotrbak** [comment]
@MathieuLamiot WDYT?

**Comment by MathieuLamiot** [comment]
I think it is not the case anymore.
