### ISSUE TITLE
Delay JS: RocketElementorAnimation is declared twice

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#4653]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
In the next website: https://basaltblock.de/leistungen/webdesign/, two body tags can be found, one of them seems to be related to a modal.

WP Rocket adds the "fix_elementor_animation_script" before first < /body> (That seems to be related to the modal), so, when the modal is fired, the fix_elementor_animation_script is added again.

A possible fix to this could be checking all the < /body> tags on the page and inject the script to the last one (That should be the one that closes the main body / entire page).

**To Reproduce**
1. Go to https://basaltblock.de/leistungen/webdesign/
2. Click on "Zur Beratung" button
3. Check the developers console

**Expected behavior**
RocketElementorAnimation should be declared only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/149366370-99fc9aaa-78c8-40b5-b9c1-9e922d8c13ef.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@sandyfigueroa Valid HTML document can contain only one `head` tag and one `body` tag:
https://html.spec.whatwg.org/multipage/sections.html#the-body-element

The website doesn't pass the HTML validation. Unless there's any new specification that allows to use two `body` tags inside the document, we can not fix this issue. Basically, we expect a valid HTML document while processing it. Please let me know what do you think.

**Comment by sandyfzu** [comment]
You are absolutely right here @piotrbak .

In any case, @vmanthos was helping me to check this case, so, I would like to hear what his thoughts are.

**Comment by vmanthos** [comment]
We can safeguard our code even if that's not valid code.

@sandyfigueroa Our job is to report such findings. In the end, it's the product team that decides if putting the resources to cover such edge cases worths the trouble.

**Comment by piotrbak** [comment]
@sandyfigueroa @vmanthos Is this modal being added by any plugin or theme, or it's coming from the custom code written by a customer?

**Comment by piotrbak** [comment]
@sandyfigueroa @vmanthos It doesn't look like we have any further feedbacks about it. Since like an edge case, going to close it then, feel free to reopen if the issue reappears.

Thank you both 🙏
