### ISSUE TITLE
Compatibility with StatsCounter

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4654]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 🆗 
- Used the search feature to ensure that the bug hasn’t been reported before 🆗 

**Describe the bug**
Stats are not beign collected when Minify and Delay JS are enabled.

**To Reproduce**
1. Enable StatsCounter plugin and login to their dashboard
2. Enable Minify and Delay JS
3. Visit the page in incognito
4. Stats are not being collected

**Expected behavior**
Stats should be collected all the time

**Additional context**
We need to exclude from JS Minification:
1. `statcounter.com/counter/counter.js` so it's not rewritten to the domain name
and from the Delay JS:
1. `statcounter.com/counter/counter.js`
2. `var sc_project`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@piotrbak Can you provide a full code snippet for QA?

**Comment by piotrbak** [comment]
@Tabrisrp I have the plugin set up on my test website. I'll provide it with instructions to Mai to save the time.
