### ISSUE TITLE
Delay JS auto-exclusion for WooCommerce Product Gallery don't include jQuery-migrate script and break the gallery

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4660]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.6
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Delay JS auto-exclusions for WooCommerce Product Gallery don't include jQuery-migrate script for WordPress version 5.7+. This breaks the gallery and causes the following console error:
![image](https://user-images.githubusercontent.com/60236665/149806763-34c01f5a-8120-4a2e-a431-daf7483d190e.png)

Excluding `/jquery-migrate(.min)?.js` from Delay JS resolves the error and correctly displays the gallery.

This is happening because we check the WordPress version here: https://github.com/wp-media/wp-rocket/blob/74a8c93d41a8b72b3a197aaadd53c048aa99ef93/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L591-L595
But jQuery-migrate script is still being used in the latest versions of WordPress.

**To Reproduce**
1. Use the latest version of WordPress (tested on 5.8.3)
2. Use Twenty Twenty-One theme;
3. Install and activate the latest version of WooCommerce (tested on 6.1.0);
4. Create a Product and add a product image and a product gallery;
4. Enable **Delay JavaScript Execution** option with no exclusions;
5. Visit the product page in the incognito browser window: the gallery will be broken and console will have the error.

**Expected behavior**
No console errors and working product gallery.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by worldwildweb** [comment]
A customer has reported a woocommerce issue that is related to this issue where Images are not displayed:
When jQuery migrate is disabled, products with multiple images do not display images properly: https://github.com/woocommerce/woocommerce/issues/31636

**Comment by remyperona** [comment]
@piotrbak This looks like from the above that it will be fixed directly in WooCommerce with their next minor version, I think we don't need to do anything in the end, what's your opinion?

**Comment by piotrbak** [comment]
Yes, let's keep the issue open until their release.

**Comment by CrochetFeve0251** [comment]
@Tabrisrp looks like the [PR](https://github.com/woocommerce/woocommerce/issues/31636) linked with the issue  is merged and already in the last version from woocommerce: https://github.com/woocommerce/woocommerce/pull/31623 as last version is 6.3.1 and this was in the middlestone from 6.3.0.
Is this issue still blocked?

**Comment by engahmeds3ed** [comment]
@piotrbak what should we do here? do we need to still support older versions of WooCommerce or rely on the latest version?

**Comment by piotrbak** [comment]
@engahmeds3ed It would be great to have a condition to be compatible with older versions too.

**Comment by engahmeds3ed** [comment]
instead of checking the WP version [here](https://github.com/wp-media/wp-rocket/blob/74a8c93d41a8b72b3a197aaadd53c048aa99ef93/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L591-L595) to detect if jQuery Migrate is enqueue or not, we can use the function [wp_script_is](https://developer.wordpress.org/reference/functions/wp_script_is/)
to check if its enqueue or not.
Then adjust the corresponding tests.

**Effort:** S

**Comment by piotrbak** [comment]
Closing it, since it's related to the old versions of Woo
