### ISSUE TITLE
LazyLoad - Exclude from WP Rocket LazyLoad tick box in Image Elementor widget

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4662]
**Is your feature request related to a problem? Please describe.**
In Elementor, using a CSS class does not work because Elementor is not adding it to the image tag but to a parent div tag.
Putting every single filename in the LazyLoad exclude settings can be an issue for WP Rocket users.
[In this ticket](https://secure.helpscout.net/conversation/1759506315/319759?folderId=273766), I found out a way to easily add a class from the Elementor Image widget.

**Describe the solution you'd like**
Couldn’t we add a compatibility with Elementor to add a WP Rocket tick box in their image widget to exclude it from being LazyLoaded by adding a `data-no-lazy` attribute or a CSS class automatically excluded?
![Capture d’écran 2022-01-18 à 15 31 28](https://user-images.githubusercontent.com/11939512/149957434-45c14025-1b9e-4452-bccf-0d92907ebc2f.png)

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1759506315/319759?folderId=273766

**Comment by BoyetDgte** [comment]
Would love to have this feature also

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
