### ISSUE TITLE
Ability to preload images

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4663]
**Describe the solution you'd like**

hello

Image preloading has a tremendous impact on website speed. By placing the following tag in the website header, I preloaded the home page banner images and the site speed was greatly increased.

<link rel="preload" as="image" href="">

Adding the ability to preload images to the wp-rocket can be great. With this feature we can preload all the images on the website and that would be great.

thank you

**Comment by piotrbak** [comment]
Hello @79ho3ein we're planning to implement this feature totally automatically somewhere this year.

**Comment by 79ho3ein** [comment]
thank you @piotrbak. Good luck

**Comment by 79ho3ein** [comment]
hi @piotrbak , Is it roughly clear when this feature will be released? Another question is, what images are preloaded in this feature? For example, are the images on the main page or the images of the products in the product archive or even the images of the products on the product page included in this preload?

thank you

**Comment by piotrbak** [comment]
@79ho3ein It's not implemented yet. It'll preload necessary images automatically.

**Comment by 79ho3ein** [comment]
Thank you for your answer @piotrbak
