### ISSUE TITLE
Renewal banner better be auto dismissed once counter is 0

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4665]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
Although the counter for renewal is 0, the banner is still displayed until we refresh the page

**To Reproduce**
Precondition:
- Have user whose license will expire in mins (banner is displayed)
1. Go to Dashboard and see the counter is all 0 => we can click renew now and will display the discount price (probably correct price will be displayed after deploying new updates of API)

**Expected behavior**
Renewal banner is auto dismissed and expired banner displayed

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
