### ISSUE TITLE
Refreshing user info better auto reflect on existing banner

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4666]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Given renewal banner is displayed, then the license is renewed.
when the user refreshes his info, the renewal banner is still displayed till we refresh the page

**To Reproduce**
- Having an account with renewal banner displayed (License will expire within next 30d)
1. Update user license (expiry date > 30)
2. click refresh info on the dashboard page
3. Renewal banner still displayed until we refresh the page

**Expected behavior**
Renewal banner is auto removed after refresh user info as now License not expiring soon

**Additional context**
- Same is applicable for expired banner

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
