### ISSUE TITLE
RUCSS: Stylesheets with relative file path ../ are not processed

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4672]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.6
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When a stylesheet has a relative file path as in example `../mycss.css` it will not be processed by the Remove Unused CSS.

**To Reproduce**

1. Add a stylesheet on the server, for example, I put in the root `mycss.css`
2. Enqueue the stylesheet on the site as:
`<link rel='stylesheet' href='../mycss.css' media='all' />`
3. Enable the Remove Unused CSS option.
4. Once the process is completed, this stylesheet will be left out while Used CSS for other stylesheets is added on the page.

**Expected behavior**
All CSS files should be processed.

**Screenshots**
In the note: https://secure.helpscout.net/conversation/1755365709/318975/#thread-5182125523

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1755365709/318975/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Fixed with 3.11
