### ISSUE TITLE
Elementor hook leads to entire cache being cleared for every new page loaded

### ISSUE THREAD

**Issue by pcworld** [wp-media/wp-rocket#4673]
## Bug Description

When using the [Elementor plugin](https://github.com/elementor/elementor) with option `minify_concatenate_css` enabled and Elementor's "CSS Print Method" set to "External File" (appears to be default), the entire cache is cleared _every time_ a new page is accessed for which Elementor has not yet saved a corresponding `_elementor_css` postmeta, which appears to be done by Elementor only when a page is accessed the first time.
This can occur even during cache prefilling such that the cache is emptied multiple times during cache generation, thus after cache prefilling, the cache may not be populated fully.
This makes WP Rocket almost unusable on some installations with Elementor, since the cache keeps being emptied regularly.
When Elementor's CSS cache is cleared (`wp-admin/admin.php?page=elementor-tools#tab-general`), the problem starts anew since this deletes all `_elementor_css` postmeta.

I have observed this bug on WordPress 5.8.3 with Elementor 3.5.3 and WP Rocket 3.10.6.

## Underlying Issue

The issue stems from WP Rocket hooking `added_post_meta` https://github.com/wp-media/wp-rocket/blob/2412238498378634c509251c634f77d8c2f5ea7a/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L68
and then clearing WP Rocket's entire cache if any `_elementor_css` postmeta is updated: https://github.com/wp-media/wp-rocket/blob/2412238498378634c509251c634f77d8c2f5ea7a/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L100-L110 https://github.com/wp-media/wp-rocket/blob/2412238498378634c509251c634f77d8c2f5ea7a/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L120-L127 which calls `rocket_clean_domain` which clears the entire cache.

The `added_post_meta` event is triggered by Elementor when WordPress issues the `wp_enqueue_scripts` action which indirectly calls [the following code](https://github.com/elementor/elementor/blob/bd8b98c3aa39570e20e75021e7fafaf926bafbc4/core/files/css/base.php#L216-L218) in Elementor:
```php
		// First time after clear cache and etc.
		if ( '' === $meta['status'] || $this->is_update_required() ) {
			$this->update();
```
The update() function then [updates the postmeta](https://github.com/elementor/elementor/blob/bd8b98c3aa39570e20e75021e7fafaf926bafbc4/core/files/css/base.php#L155), triggering WP Rocket's `added_post_meta` hook described above. 

An example stack trace of such a call to `rocket_clean_domain` is:
```
#0  rocket_clean_domain() called at [/var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/PageBuilder/Elementor.php:125]
#1  WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache() called at [/var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/PageBuilder/Elementor.php:109]
#2  WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->maybe_clear_cache(123456, 8, _elementor_css) called at [/var/www/wp-includes/class-wp-hook.php:305]
#3  WP_Hook->apply_filters(, Array ([0] => 123456,[1] => 8,[2] => _elementor_css,[3] => Array ([time] => 1642703075,[fonts] => Array ([0] => Roboto,[1] => Roboto Slab),[icons] => Array (),[dynamic_elements_ids] => Array (),[status] => file,[0] => ))) called at [/var/www/wp-includes/class-wp-hook.php:327]
#4  WP_Hook->do_action(Array ([0] => 123456,[1] => 8,[2] => _elementor_css,[3] => Array ([time] => 1642703075,[fonts] => Array ([0] => Roboto,[1] => Roboto Slab),[icons] => Array (),[dynamic_elements_ids] => Array (),[status] => file,[0] => ))) called at [/var/www/wp-includes/plugin.php:470]
#5  do_action(added_post_meta, 123456, 8, _elementor_css, Array ([time] => 1642703075,[fonts] => Array ([0] => Roboto,[1] => Roboto Slab),[icons] => Array (),[dynamic_elements_ids] => Array (),[status] => file,[0] => )) called at [/var/www/wp-includes/meta.php:133]
#6  add_metadata(post, 8, _elementor_css, a:6:{s:4:"time";i:1642703075;s:5:"fonts";a:2:{i:0;s:6:"Roboto";i:1;s:11:"Roboto Slab";}s:5:"icons";a:0:{}s:20:"dynamic_elements_ids";a:0:{}s:6:"status";s:4:"file";i:0;s:0:"";}) called at [/var/www/wp-includes/meta.php:222]
#7  update_metadata(post, 8, _elementor_css, Array ([time] => 1642703075,[fonts] => Array ([0] => Roboto,[1] => Roboto Slab),[icons] => Array (),[dynamic_elements_ids] => Array (),[status] => file,[0] => ), ) called at [/var/www/wp-includes/post.php:2335]
#8  update_post_meta(8, _elementor_css, Array ([time] => 1642703075,[fonts] => Array ([0] => Roboto,[1] => Roboto Slab),[icons] => Array (),[dynamic_elements_ids] => Array (),[status] => file,[0] => )) called at [/var/www/wp-content/plugins/elementor/core/files/css/post.php:129]
#9  Elementor\Core\Files\CSS\Post->update_meta(Array ([time] => 1642703075,[fonts] => Array ([0] => Roboto,[1] => Roboto Slab),[icons] => Array (),[dynamic_elements_ids] => Array (),[status] => file,[0] => )) called at [/var/www/wp-content/plugins/elementor/core/files/css/base.php:155]
#10 Elementor\Core\Files\CSS\Base->update() called at [/var/www/wp-content/plugins/elementor/core/files/css/base.php:218]
#11 Elementor\Core\Files\CSS\Base->enqueue() called at [/var/www/wp-content/plugins/elementor/core/files/css/post.php:201]
#12 Elementor\Core\Files\CSS\Post->enqueue() called at [/var/www/wp-content/plugins/elementor/core/kits/manager.php:206]
#13 Elementor\Core\Kits\Manager->frontend_before_enqueue_styles() called at [/var/www/wp-includes/class-wp-hook.php:303]
#14 WP_Hook->apply_filters(, Array ([0] => )) called at [/var/www/wp-includes/class-wp-hook.php:327]
#15 WP_Hook->do_action(Array ([0] => )) called at [/var/www/wp-includes/plugin.php:470]
#16 do_action(elementor/frontend/after_enqueue_styles) called at [/var/www/wp-content/plugins/elementor/includes/frontend.php:630]
#17 Elementor\Frontend->enqueue_styles() called at [/var/www/wp-includes/class-wp-hook.php:303]
#18 WP_Hook->apply_filters(, Array ([0] => )) called at [/var/www/wp-includes/class-wp-hook.php:327]
#19 WP_Hook->do_action(Array ([0] => )) called at [/var/www/wp-includes/plugin.php:470]
#20 do_action(wp_enqueue_scripts) called at [/var/www/wp-includes/script-loader.php:2083]
#21 wp_enqueue_scripts() called at [/var/www/wp-includes/class-wp-hook.php:303]
#22 WP_Hook->apply_filters(, Array ([0] => )) called at [/var/www/wp-includes/class-wp-hook.php:327]
#23 WP_Hook->do_action(Array ([0] => )) called at [/var/www/wp-includes/plugin.php:470]
#24 do_action(wp_head) called at [/var/www/wp-includes/general-template.php:3015]
#25 wp_head() called at [/var/www/wp-content/themes/woodmart/header.php:12]
#26 require_once(/var/www/wp-content/themes/woodmart/header.php) called at [/var/www/wp-includes/template.php:770]
#27 load_template(/var/www/wp-content/themes/woodmart/header.php, 1, Array ()) called at [/var/www/wp-includes/template.php:716]
#28 locate_template(Array ([0] => header.php), 1, 1, Array ()) called at [/var/www/wp-includes/general-template.php:48]
#29 get_header() called at [/var/www/wp-content/themes/woodmart/page.php:11]
#30 include(/var/www/wp-content/themes/woodmart/page.php) called at [/var/www/wp-includes/template-loader.php:106]
#31 require_once(/var/www/wp-includes/template-loader.php) called at [/var/www/wp-blog-header.php:19]
#32 require(/var/www/wp-blog-header.php) called at [/var/www/index.php:17]
```

## Reproduction Steps
1. Create a WordPress instance with Elementor pages and Elementor set up as in the beginning of the bug description.
2. Clear Elementor's CSS cache by going to `wp-admin/admin.php?page=elementor-tools#tab-general` and clicking "Regenerate Files & Data" (probably optional and only needed if the pages have been accessed in the frontend before)
3. Access Elementor pages in the frontend while the cache is in use (i.e., do not be logged in). After each page load, observe in `wp-content/cache/wp-rocket` that the entire domain's cache is cleared after every newly accessed page.

## Expected Behavior
The entire domain cache should not be cleared when Elementor updates an `_elementor_css` postmeta.

## Workaround
Use the following plugin based on [wp-rocket-no-cache-auto-purge](https://github.com/wp-media/wp-rocket-helpers/tree/4b4b97f397741930d9edb2e2adf8cf38f513672c/cache/wp-rocket-no-cache-auto-purge) ([GPL 2.0 license](https://github.com/wp-media/wp-rocket-helpers/blob/4b4b97f397741930d9edb2e2adf8cf38f513672c/LICENSE)):
```php
<?php
/**
 * Plugin Name: WP Rocket | Disable Elementor CSS Cache Clearing
 * Description: Disables WP Rocket’s automatic cache clearing of Elementor pages when css postmeta is updated.
 * Plugin URI:  based on https://github.com/wp-media/wp-rocket-helpers/blob/4b4b97f397741930d9edb2e2adf8cf38f513672c/cache/wp-rocket-no-cache-auto-purge/wp-rocket-no-cache-auto-purge.php
 * Author:      WP Rocket Support Team
 * Author URI:  http://wp-rocket.me/
 * License:     GNU General Public License v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Copyright SAS WP MEDIA 2021
 */

namespace WP_Rocket\Helpers\cache\no_cache_auto_purge;

// Standard plugin security, keep this line in place.
defined( 'ABSPATH' ) or die();

function wp_rocket_disable_elementor_cache_clearing() {
	add_action( 'wp_loaded', function() {
		$container = apply_filters( 'rocket_container', '');
		$container->get('event_manager')->remove_callback( 'added_post_meta', [ $container->get('elementor_subscriber'), 'maybe_clear_cache'], 10, 3 );
	} );
}

add_action( 'wp_rocket_loaded',  __NAMESPACE__  . '\wp_rocket_disable_elementor_cache_clearing' );
```

## Backlog Grooming (for WP Media dev team use only)
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@piotrbak This should be solved with the changes in 3.10.9
