### ISSUE TITLE
Disable Google fonts in wp-rocket

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4678]
Removing Google fonts is a required feature that is present in most optimization plugins, but unfortunately does not exist in wp-Rocket.
Google fonts create additional requests that negatively affect the performance of the site. Please add the Google Fonts Disable feature.
thanks

**Comment by 79ho3ein** [comment]
+1 
This is really needed.

**Comment by 15kstudios** [comment]
+1

**Comment by VollWombat** [comment]
+1
Removing Google fonts is also needed for staying GDPR-compliant.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the next months. We'll reopen it when scheduling the feature to be released.
