### ISSUE TITLE
Lazy load image in wordpress & wp-rocket

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4679]
As you know, WordPress is lazy load by default. WordPress has also said that it will fully develop this feature in WordPress 5.9. Therefore, all WordPress websites have lazy load by default. The question is, with these conditions, does wp-rocket remove the lazy load feature?

**Comment by JerissCloudCenter** [comment]
WP Rocker provides additionnal settings to customize the lazyload (exclusions...), which is not the case (yet) with WordPress' lazyload. Therefore, I believe it would be a bad idea to remove this feature for now.

**Comment by piotrbak** [comment]
Hello @Michaelgimii thnak you for creating the issue. We're prepared to switch to native lazy load when it's needed, you can even do it with the filter any time:
https://github.com/wp-media/wp-rocket/blob/f48cb29346ab9a4f42c39d01f14e024b9a31086a/inc/Engine/Media/Lazyload/Subscriber.php#L161

For now, we made performance tests and JS library gives better results.
