### ISSUE TITLE
RocketCDN is not compatible with "Preload Fonts" functionality

### ISSUE THREAD

**Issue by Snadex** [wp-media/wp-rocket#4680]
Hello,
we are using self-hosted fonts and want to preload them. We are also using RocketCDN and turns out the "Preload Fonts" functionality is not compatible.

**To Reproduce**
Add Local Path in the "Fonts to preload" section.
Have RocketCDN enabled

**Expected behavior**
We would expect WP Rocket to preload the local fonts which are moved to the CDN - Currently it is not.

**Additional context**
WP Rocket is considering the CDN fonts "external" and is not preloading them

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @Snadex I tried to reproduce this issue and I was able to preload fonts hosted on CDN without any problems. Could you give us some more context there?

**Comment by Snadex** [comment]
@piotrbak 
I believe this was fixed in later versions of the plugin and currently works fine, you can close it :)
