### ISSUE TITLE
WP Rocket is not working with 3rd party plugin leadmarkt (Lead Generator)

### ISSUE THREAD

**Issue by Cr-Virtualassistant** [wp-media/wp-rocket#4681]
HI there,

I wanna use this plugin
https://profiles.wordpress.org/leadmarkt/
but it does not work with  WP Rocket – File optimization - Delay JavaScript execution

If I activate the box it displays like this (see Pic 1)
![Pic 1](https://user-images.githubusercontent.com/98343157/150832828-ffde8ef5-1059-49aa-89fb-e639f8a9c0c7.png)
 here.
If I deactive the box it displays properly like this (see Pic 2)
![Pic 2](https://user-images.githubusercontent.com/98343157/150833138-c62b967e-4054-4d2e-9ed3-ddac9fa55ad8.png)

So I tried several js exclusions but nothing works.

THe problem is on that website
https://hagemeier-immobilien.de/immobilienwert-ermitteln/

**Comment by Cr-Virtualassistant** [comment]
Sorry, I forgot to mention that the problem is happening on mobile and tablet.

**Comment by piotrbak** [comment]
Hello @Cr-Virtualassistant can you please reach our Support Team? After their investigation we'll be able to see what can be done to resolve the problem. Thank you.

**Comment by Cr-Virtualassistant** [comment]
How can I contact them?

**Comment by piotrbak** [comment]
You'll be able to reach us here, by following the dropdown:
https://wp-rocket.me/support/

**Comment by Cr-Virtualassistant** [comment]
ah ok, that is not working, cause I don't have a login....I got an agency installation

**Comment by alfonso100** [comment]
I have directly contacted the plugin developers about this. We will publish an update as soon as we can work on the issue.

**Comment by novelnet** [comment]
Hi there!
Thanks for contacting me, I'm the Dev at https://leadmarkt.ch.
The lead generator is embedded as an iFrame, for the responsibility we depend on a JS library, unfortunately.
It seems the initialization function initLeadGenIframe() at the iFrame onLoad event gets called before the whole script is loaded.
When initializing initLeadGenIframe() over the dev console manually, it works as test.
That issue sometimes happens with plugins using iframe lazyload or privacy blockers. Is there any procedure how wp-rocket handles iframes?
Best regards
Tobias

**Comment by novelnet** [comment]
We made a few updates for better compatibility and responsiveness support. As there is no new response, i guess the issue can be closed.

**Comment by piotrbak** [comment]
Closing it, thanks @novelnet
