### ISSUE TITLE
Fatal Error Wp Rocket

### ISSUE THREAD

**Issue by mediacerebri** [wp-media/wp-rocket#4686]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

Fatal Error in php, my website is down, error 503

**To Reproduce**
1. Go to 'upload plugin'
2. Click on 'activate'
3. Scroll down to 'settings'

**Expected behavior**

**Screenshots**

![IMG-20220126-WA0001](https://user-images.githubusercontent.com/75227805/151063875-acdf0267-e675-4955-95ac-4057438d134f.jpg)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mediacerebri** [comment]
I'm using openlitespeed server

**Comment by piotrbak** [comment]
Hello @mediacerebri thank you for creating this issue. Could you reach our Support Team, so we'll be able to verify and investigate the problem?
https://wp-rocket.me/support/

**Comment by piotrbak** [comment]
@mediacerebri Are you still experiencing this problem? If so, were you able to reach our support?
