### ISSUE TITLE
Fusion slider for Avada theme not displayed while Delay JS is enabled even after user interaction

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4688]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Slider is not displayed even with user interaction while Delay JS is enabled

**To Reproduce**
1. Enable Delay JS
2. Open the home page containing fusion slider https://mega.wp-rocket.me/avada/
3. Slider not displayed even with user interaction

**Expected behavior**
Slider is displayed without delay or displayed after user interaction

**Screenshots**
![Screenshot from 2022-01-26 18-24-08](https://user-images.githubusercontent.com/76941962/151204336-22cbdde3-4bd3-43a0-a8fe-8aedd3a85f92.png)

**Additional context**
- same exists on 3.9.4
- exclusions mentioned [here](https://avada.theme-fusion.com/) will fix the problem 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Will be fixed with backend in 3.13

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
