### ISSUE TITLE
Media upload is extremely slow when rocket enabled

### ISSUE THREAD

**Issue by tamimibrahim17** [wp-media/wp-rocket#469]
Hi, 

During new post creation, If I upload new image as post attachment, it take almost 45 - 50 seconds for a 400kb sizes image. But If I disable rocket plugin and upload same image it only take ~5 seconds to upload. 

My rocket dealing with image upload process. As far I know images files are static, there is no cache involve with that. 

Can anybody please give me some insights about it. Thanks

**Comment by Tabrisrp** [comment]
Our GitHub page is not used for support, but for report of code issues or suggestions.

Please open a support request on our website: https://wp-rocket.me/support/
