### ISSUE TITLE
Terms pages are not preloaded after updating posts

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4690]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.10.6`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When a post is updated, we clear the respective terms/date archive pages here:
https://github.com/wp-media/wp-rocket/blob/7b62ef5111c97c30888f7e6daa2ba2f920dabc7e/inc/Engine/Cache/PurgeActionsSubscriber.php#L48-L50

Partial preloading of such pages is supposed to be happening here:
https://github.com/wp-media/wp-rocket/blob/7b62ef5111c97c30888f7e6daa2ba2f920dabc7e/inc/Engine/Preload/PartialPreloadSubscriber.php#L70

hooked to `after_rocket_clean_term`.

The specific hook is defined in `rocket_clean_term()`:
https://github.com/wp-media/wp-rocket/blob/7b62ef5111c97c30888f7e6daa2ba2f920dabc7e/inc/functions/files.php#L866

which doesn't run when a post is updated, but only when the cache is purged using the admin bar menu item:
https://github.com/wp-media/wp-rocket/blob/7b62ef5111c97c30888f7e6daa2ba2f920dabc7e/inc/common/purge.php#L494

Therefore `after_rocket_clean_term` doesn't fire after updating a post, and partial preloading of terms/archive pages doesn't take place.

**To Reproduce**

1. Check the cache of the `category` a post belongs to.
2. Update a post.
2. Check the cache of the same `category`. It will have been cleared, but not preloaded.

**Expected behavior**

Terms/archive pages should be preloaded after a post type has been updated.

**Additional context**

Props @webtrainingwheels for discovering this.

**Slack convo:** https://wp-media.slack.com/archives/C08N8J6VC/p1643232812114300
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
Related: https://secure.helpscout.net/conversation/1754057435/318712?folderId=377611

**Comment by piotrbak** [comment]
This will be solved with the new preload.
