### ISSUE TITLE
Remove unused CSS break Elementor Pro popups

### ISSUE THREAD

**Issue by godlesowned** [wp-media/wp-rocket#4700]
Popups not working when Remove Unused CSS with Elementor Pro Popups.

1. Install Elementor Pro and create Popup
2. Create page with button and add action to button to load popup
3. Remove unused CSS

/*edit*/
Added this to exclusion and work.

.dialog-widget
#elementor-popup-modal-[YourPopupPostID]
.dialog-type-lightbox
.body.admin-bar
.dialog-lightbox-widget
.dialog-widget-content
.elementor-popup-modal
.dialog-header
.elementor-[YourPopupPostID]
.dialog-lightbox-message
/wp-content/uploads/elementor/css/post-[YourPopupPostID].css
.fadeIn

**Comment by CodebyJM** [comment]
You are a life saver. Thank you!

**Comment by piotrbak** [comment]
Fixed with 3.11, we have autocompatibility for that.

**Comment by veltix** [comment]
WP rocket 3.11.0.5 and still same issue with elementor pro popup when enabling remove unused css.

**Comment by piotrbak** [comment]
@Veltix Please contact our Support Team, we'll confirm the issue and fix it immediately.

**Comment by felixstuermer** [comment]
Same here

**Comment by piotrbak** [comment]
@medienstuermer Please contact our Support Team, we'll check the issue and fix it immediately.

**Comment by DjTribunus** [comment]
> Fixed with 3.11, we have autocompatibility for that.

No, the problem was not corrected. The bug is still present in version 3.11.2, is there any way to fix it? The solution proposed by the godlesowned user, not function always and it also seems to slow down the opening of the other pages on the site a lot.

I think it is appropriate to reopen this discussion.

**Comment by piotrbak** [comment]
@DjTribunus You might want to contact our Support Team, we'll check the issue and fix it immediately.

Please understand, we're doing extensive tests to make sure things are working correctly. Without seeing your websites, we can't check why our compatibility is not 100% accurate.

**Comment by claudio-uey** [comment]
@piotrbak I am also seeing this issue.

**Comment by piotrbak** [comment]
@claudio-uey Please contact our Support Team, we'll investigate this and apply the fix immediately.

**Comment by jivaneo** [comment]
Same here :(

**Comment by jivaneo** [comment]
Hey guys,

Elementor support sent me a solution.
Adding this to CSS safelist:

```
/elementor/assets/lib/animations/animations.min.css
@eicons
```
Worked for me.

Cheers!

**Comment by wnorth247** [comment]
Yes still an issue still exists and this above solution fixes it! Well done.

**Comment by rehmnanqureshi** [comment]
i am also facing the same issue can anyone please suggest the exclusions for elementor dynamic popup toggle trigger event please!!!!

**Comment by rehmnanqureshi** [comment]
i added all these in remove unused css exclusions list saved the changes and than purged cache and also unused css but not working :(

.dialog-widget
#elementor-popup-modal-8015
.dialog-type-lightbox
.body.admin-bar
.dialog-lightbox-widget
.dialog-widget-content
.elementor-popup-modal
.dialog-header
.elementor-8015
.dialog-lightbox-message
/wp-content/uploads/elementor/css/post-8015.css
.fadeIn
/elementor/assets/lib/animations/animations.min.css
@eicons

**Comment by piotrbak** [comment]
@rehmnanqureshi Please reach our Support team in order to find correct exclusions and/or investigate the issue.

**Comment by Lenglemetz** [comment]
> i added all these in remove unused css exclusions list saved the changes and than purged cache and also unused css but not working :(
> 
> .dialog-widget #elementor-popup-modal-8015 .dialog-type-lightbox .body.admin-bar .dialog-lightbox-widget .dialog-widget-content .elementor-popup-modal .dialog-header .elementor-8015 .dialog-lightbox-message /wp-content/uploads/elementor/css/post-8015.css .fadeIn /elementor/assets/lib/animations/animations.min.css @eicons

I have exactly the same problem

**Comment by mvincik** [comment]
I added these to the CSS Safelist and it corrected the issue. You can leave out the the last line if you are not using THE7 theme. 
```
/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css
/wp-content/plugins/elementor/assets/css/frontend.min.css
/wp-content/plugins/elementor/assets/lib/swiper/v8/css/swiper.min.css
/wp-content/themes/dt-the7/css/compatibility/elementor/elementor-global.min.css
```

This worked for me even though it's not the most optimized solution such as listing the individual classes and id's that are missing but this is a quick fix when you just need things to work.
