### ISSUE TITLE
Console Errors for logged-in user when Combine js is enabled while Elementor plugin is active

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4701]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Console error displayed for the logged-in user when combine js and user cache are enabled while Elementor is active

**To Reproduce**
- Elementor is enabled 
- User cache and Combine JS are enabled at WPR
1. open home page while logged-in
2. Console errors are there

**Expected behavior**
No console error

**Screenshots**
![Screenshot from 2022-02-01 17-52-37](https://user-images.githubusercontent.com/76941962/152003333-715e2046-aebe-45b6-a561-7929d4ce0a28.png)

**Additional context**
- Deactivate Elementor or disable Combine JS or disable User Cache will fix the problem
- Tested on 3.10.7 and 3.8 => same results

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by 79ho3ein** [comment]
I have this problem too. Please solve this problem.

**Comment by Michaelgimii** [comment]
+1
Please fix this in the new version.

**Comment by piotrbak** [comment]
Excluding the following script from Combine JS solved the issue for me:
`/wp-includes/js/dist/hooks.min.js`

**Comment by remyperona** [comment]
Is it only when user cache is enabled?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, this is happening because `/wp-includes/js/dist/i18n.min.js` is automatically excluded from JS Combination and it's calling `/wp-includes/js/dist/hooks.min.js` which is inside the combined file.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In the Elementor compatibility file, add a new method to exclude `/wp-includes/js/dist/hooks.min.js` from JS combine if:
- Combine JS is enabled
- User cache is enabled and the user is logged-in

Add tests for the method

### Estimate the effort ✅
Effort `[XS]`

Does that seem good from a product view @piotrbak ?

**Comment by nicomollet** [comment]
Can confirm the issue.
Waiting for a fix and subscribing.

**Comment by 79ho3ein** [comment]
hi , Is it clear when this update will be released?

**Comment by piotrbak** [comment]
The release is planned for the next week if everything goes correctly.

**Comment by 79ho3ein** [comment]
thank you @piotrbak , Good luck.

**Comment by Michaelgimii** [comment]
hi
Has 3.10.9 been released?
