### ISSUE TITLE
Emoji optimization and WordPress 5.9 compatibility 

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4703]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.7`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After upgrading to 5.9 and trying to use the `wp` function, a console error shows up. 

The issue seems to be related to our Emoji optimization and 5.9.

All tests were done with all optimizations disabled in the UI and using the Astra theme.

5.8.3 - WP Rocket only
![image](https://user-images.githubusercontent.com/1289174/152155650-6186d185-1ce2-4c39-b080-98174ff086fc.png)
https://drive.google.com/file/d/1D92xuxGwzW00IG74vH4Q4zFls5SlKBGG/view?usp=drivesdk

5.9 - WP Rocket only
![image](https://user-images.githubusercontent.com/1289174/152155660-530fb038-d475-4df6-b568-ad08200ef618.png)
https://drive.google.com/file/d/1sau_LQ8W6MBqgMyRaOtqLQyx8an2XowC/view?usp=drivesdk

5.9 - WP Rocket + Disable Emoji optimization
![image](https://user-images.githubusercontent.com/1289174/152155678-f22ae70d-f2f2-456f-a357-1ad321d496d9.png)
https://drive.google.com/file/d/1-nWfrFXIWvABFZK9ds6iyKpk9zxpRJYg/view?usp=drivesdk

Something has changed in how WP handles Emojis that triggers the error.

**To Reproduce**
1. 5.9 + Astra theme + WP Rocket
2. Call the `wp` using the browser console
3. See error

**Expected behavior**
There shouldn't be any errors when calling the `wp` function when WP Rocket is enabled. 

**Screenshots**
Attached to the description section.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1769653213/322224/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame if you see any way to reproduce it using the live elements/blocks, etc. instead of calling `wp` manually, it would be great.

**Comment by DahmaniAdame** [comment]
It only happens when the `wp` is called. So, I guess we need a scenario where something calls it.

I will try to find a way and update the ticket if I do.

**Comment by camilamadronero** [comment]
I have a `wp is not defined` case here: https://secure.helpscout.net/conversation/1775791636/323565/ - WordPress 5.9.

**Comment by DahmaniAdame** [comment]
@piotrbak Did some digging. 

The difference between loading `5.8.3` and `5.9` is that `5.9` is no longer loading the `/wp-includes/js/wp-embed.min.js` by default.

That's why testing `wp` on `5.8.3` worked while it returned a dependency error when used with `5.9`. 

Disabling the Emoji Optimization just added the dependency for `wp` to return without any errors. 

This is a `wontfix` since there is no way to trigger the error. 

Realistically, any plugin or theme using `wp` will make sure to add the proper dependencies for it to run.

**Comment by Alex43515** [comment]
Related ticket: https://secure.helpscout.net/conversation/1784824105/325587/

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1827521697/333828/

The `wp` is called by the menu. 

```
onOpened: function() {
    wp && wp.customize || this.$target.find("a").eq(0).focus(), this.opts.clickOutside && t(document).on("click." + this.namespace + " tap." + this.namespace, t.proxy(this.close, this)), this.detect.isMobileScreen() && t("html").addClass("no-scroll"), t(document).on("keyup." + this.namespace, t.proxy(this.handleKeyboard, this)), t(document).on("keydown." + this.namespace, t.proxy(this.handleKeyDown, this)), this.$close.on("click." + this.namespace, t.proxy(this.close, this)), this.$target.addClass("open"), this.callback("opened")
},
```

From [/colibri-page-builder-pro/extend-builder/assets/static/js/theme.js](https://gist.github.com/DahmaniAdame/74f6dc3e7d832fe2c3334890190522af#file-theme-js-L8372-L8374)

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
