### ISSUE TITLE
Ability to clear the database from empty and useless tables

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4704]
**Is your feature request related to a problem? Please describe.**

The problem is that some plugins add tables to the database after installation. But when we delete the plugin, their tables still remain in the database. Rarely does this increase the size of the database.

**Describe the solution you'd like**

Please add a new feature to the database configuration so that we can use it to completely clear the database of extra files and tables.
Currently, some plugins do this. Like the Advanced Database Cleaner plugin. But if you localize this feature, we will no longer need to use third-party plugins.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
