### ISSUE TITLE
Defer and minify JS compatibility with Typekit

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4706]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using the Typekit fonts with Defer JS, fonts are not rendered properly on Safari mobile. But they work fine on Desktop on Safari, and on both Desktop and Mobile of Android devices. 

Sample of the script added by Typekit - https://use.typekit.com/sgs4pbn.js (the file name is a random string)

A separate cache for mobile devices was enabled to exclude that possibility. 

Only excluding `use.typekit.com` fixes the issue. 

The same should be excluded from JS Minify to avoid the exclusion to stop working when the script is hosted. 

**To Reproduce**
1. Use Typekit to add a font
2. Enable Defer JS
3. See error (font-family not applied to target selector)

**Expected behavior**
Typekit fonts should work out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1770086284/322313/
Related to - https://github.com/wp-media/wp-rocket/issues/1912 - the only difference is that JupiterX has its own Typekit integration through the API using a hosted file.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@piotrbak we have occasionally automatic exclusions that require exclusions from both deferring and minify. 
Maybe we should have a different list for these for maintainability before the list grows too much?

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `use.typekit.com` to:
- `DeferJS::$exclude_defer_js` array
- `AbstractJSOptimization::get_excluded_external_file_path()` method

### Estimate the effort ✅
Effort `[XS]`

**Comment by Mai-Saad** [comment]
@DahmaniAdame @piotrbak if Delay JS is enabled, then wrong fonts will be displayed till user interaction. Do you think we shall exclude it from Delay JS as well?

**Comment by piotrbak** [comment]
@Mai-Saad Since it's not causing negative impact on the PSI score, we can easily exclude it from the DelayJS too.

**Comment by piotrbak** [comment]
@Mai-Saad editing my comment there, thanks to your finding. Exclusion makes PSI scores worse, let's not exclude it for now.
