### ISSUE TITLE
Issue with HTML compression and JS Templates 

### ISSUE THREAD

**Issue by philsbury** [wp-media/wp-rocket#471]
Hi,

I've noticed that compressing HTML is removing spaces from JavaScript templates rendering them unable to be processed. As an example, using [TwigJS](https://github.com/twigjs/twig.js):
{% include "tmpl-wp-age-gate-form-" ~ t %}

Has become:
{%include"tmpl-wp-age-gate-form-"~t%}

The spaces are important in Twig (and quite possibly others). Is there a way to either wrap these in some form of ignore tag or could the compress ignore anything in a script tag with certain type?

Thanks
Phil

**Comment by Tabrisrp** [comment]
Hi,

the template code is showing as is in the HTML code of the page? Do you have a full example that I could look at?

**Comment by GeekPress** [comment]
Hi @philsbury 🤚

We haven't back from you since @Tabrisrp asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best
