### ISSUE TITLE
Preload links isnot working properly for logged in users while user cache is disabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4711]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Preload Links is sending requests on hover for logged in users + add prefetch in the header also cache for logged in users is disabled

**To Reproduce**
- Cache for logged in users is disabled
- Preload links is enabled
1. Open the home page while logged in and hover on links
2. In the network tab, requests are sent. In header, prefetch is added for hovered links

**Expected behavior**
No requests are sent and nothing added to the header

**Screenshots**
https://jmp.sh/jy20bFO

**Additional context**
- Nothing is added to the cache folder 
- Same happened when using 3.8

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment]
@piotrbak This is probably a feature that should be completely disabled for logged-in users, as the prefetch doesn't have the cookies information.

**Comment by piotrbak** [comment]
@Tabrisrp Yes, totally agree

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add a check for `is_user_logged_in()` in `Preload\Links\Subscriber::add_preload_script()`, bailing-out if the user is logged-in.

### Estimate the effort ✅
Effort `[XS]`
