### ISSUE TITLE
Offer an option to determine whether to load the Combined CSS file early or late

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#4712]
Customer had excluded some files (used for above the fold content) from Combine CSS, leaving only "less important" files to be included in the combined CSS file, and thus, wanted that file to load _after_ all the excluded files.

To achieve this, they modified the code in `/wp-rocket/inc/Engine/Optimization/Minify/CSS/Combine.php:279`:

FROM: `return preg_replace( '/<\/title>/i',`
TO: `return preg_replace( '/<\/body>/i',`

They said this actually made their site load faster than using either of the recommended _Optimize CSS Delivery_ options (according to GTmetrix, at least). 

So they've asked if we could add an option that allows the end user to decide if they want the combined CSS file to load early or late.

After a brief discussion in Slack, @piotrbak asked me to file this request, so that he could conduct some benchmark tests to assess the significance / viability of offering such an option.

Related Ticket: https://secure.helpscout.net/conversation/1770616039/322453/

**Comment by piotrbak** [comment]
Closing it, since Combine CSS will be removed soon.
