### ISSUE TITLE
RocketCDN - Improve "RocketCDN is not available" message in CTA

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4714]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ☑️
- Used the search feature to ensure that the bug hasn’t been reported before ☑️

**Describe the bug**
Like this one [https://github.com/wp-media/rocketcdn-plugin/issues/12](https://github.com/wp-media/rocketcdn-plugin/issues/12), this message is not enough when it’s the communication between the site and RocketCDN server which is blocked.

We could add [a link to this doc](https://docs.wp-rocket.me/article/1608-error-notices-during-the-rocketcdn-subscription-process) or this kind of message too:
"**146.59.251.59** and **https://rocketcdn.me/api/** are probably also blocked by your server, a firewall, or a security plugin. Please allow these on all security levels."

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
We can improve the notifications a bit by:
- Returning the error message when we get a `WP_Error` from the WP Request API
- Returning a more specific message when we get a `40x` status code from the HTTP request
- Add a link to the doc in the notification

Would that work? @piotrbak

**Comment by piotrbak** [comment]
@Tabrisrp Yes, it'll work perfectly. Can we expect that any 40x status code is caused by the firewall, etc.?

**Comment by remyperona** [comment]
We can't expect it to be always the case no. So for this I wouldn't recommend using such a specific message, but something more along the lines of "Received an unexpected response code" or something like that.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `RocketCDN\APIClient::get_remote_pricing_data()`, update the method:
- If `$response` is a `WP_Error`, return it directly
- If the status code is not `200`, return a new specific error message
- Add links to the documentation to all error messages

In `RocketCDN\APIClient::purge_cache_request()`, add the method:
- If `$response` is a `WP_Error`, return the error message from the object
- Add links to the documentation to all error messages

Update tests for those methods

### Estimate the effort ✅
Effort `[S]`

**Comment by piotrbak** [comment]
@Tabrisrp Moving the issue to the 3.11.1. We don't have time to put it into the 3.10.9

**Comment by vmanthos** [comment]
@piotrbak @Tabrisrp

I checked the following cases:
* `WP_Error`
* Response code other than `200`
* No response data.
*
Notices are displayed as expected. Please find my comments below.

When the response code isn't `200` we are displaying this notification:
![](https://i.vgy.me/QknjE6.jpg)

I think the message is a bit cryptic without a more specific context for a user that doesn't know we are supposed to display a price there.

If we want to add context we can use something like:

> We couldn't fetch the current price because the RocketCDN API returned an unexpected error code.

Also, should we add the specific error code, e.g. `403`? That can give support a hint about what could be the reason and eventually enrich the [doc](https://docs.wp-rocket.me/article/1608-error-notices-during-the-rocketcdn-subscription-process/)

Lastly, the link of the doc while correct didn't open in the beacon in my case:
![](https://i.vgy.me/B36TWI.jpg)
Other docs did.

**Comment by piotrbak** [comment]
@vmanthos Thank you! Indeed, the wording could be more accurate here, @Tabrisrp could you change it to the one proposed by Vasilis?
```
We couldn't fetch the current price because RocketCDN API returned an unexpected error code.
```

@Tabrisrp Do you know why the Beacon doesn't work? The article is published and URL/code seem to be good:
`60ddc72d9e87cb3d01249270`
`https://docs.wp-rocket.me/article/1608-error-notices-during-the-rocketcdn-subscription-process`

@vmanthos In terms of troubleshooting, I believe that no matter what error code we are getting, the troubleshooting steps are the same 🤔 What do you think?

**Comment by remyperona** [comment]
I updated the message returned. For Beacon, the RocketCDN section was unchecked in the Beacon configuration, which would explain why it was not working. Should be good now.
