### ISSUE TITLE
Critical CSS generation process is overloading server

### ISSUE THREAD

**Issue by warudin** [wp-media/wp-rocket#4716]
I observed some problems with a new site we released recently. When we updated the theme (using GitHub Updater), the server got overloaded. At first I thought the problem was caused by GitHub Updater, but after investigating some more, it was clear to me that WP Rocket is causing the problem.

Our themes contain a hook to clean up and regenerate WP Rocket caches (Minified files, Page preloading, Critical CSS, Unused CSS) after a plugin/theme has been updated. This is because those kind of updates can cause visual changes to the front-end. When I disabled this hook, the server did not show the same behaviour anymore. This got me on the right path into investigating what exactly is causing the server overload.

When I manually activate the Critical CSS generating process in WP Rocket, the server is being flooded with requests. This can be seen in the following screen capture, at around 00:50 you will see that New Relic shows a big peak in network traffic and memory usage. Screen capture: https://drive.google.com/open?id=1HfGkAyXU-Iv1y1uzkh1QhwyfU0JKDTbp&authuser=dominique%40noesteijver.nl&usp=drive_fs

We have upgraded the server to deal with this. The server is running only two sites, which are not that heavy (in my opinion). The server was running on 2GB memory and 2 CPU's, these specifications got doubled after upgrading (4GB memory, 4 CPU's). However, upgrading specifications of a server is treating symptoms, rather than addressing the root problem.

My main questions: What's the interval that's being used by WP Rocket to visit the website when it regenerates Critical CSS? Can the interval be stretched some more?

**Comment by piotrbak** [comment]
Hello @warudin thank you for creating this issue. 
```
When I manually activate the Critical CSS generating process in WP Rocket, the server is being flooded with requests.
```
I'm not able to reproduce this issue on my own environment. Could you check access log to see what's happening there? Our requests will be present there.

**Comment by warudin** [comment]
Hi @piotrbak,

Here's an access log from the minutes after I activate the Critical CSS generation process: https://drive.google.com/open?id=1HseOReaUvj75W3do4NQTJ93h_5uQ3xS8&authuser=dominique%40noesteijver.nl&usp=drive_fs

**Comment by piotrbak** [comment]
@warudin thank you... Nothing special on our side there, we made 14 requests to the website in 2 minutes, it shouldn't overload any server.

**Comment by warudin** [comment]
Hi Piotrek,

I can agree with you that it shouldn’t overload a server, but it unfortunately it does.
Is there anything special about the requests that could make them more burdening for the server?
The page has not been cached at that moment, so that’s part of the problem but probably necessary.

--

Met vriendelijke groet,

Dominique Pijnenburg

***@***.***
+31 (0) 13 - 782 0130

Bezoek- & postadres:
Ringbaan-Oost 116F
5013 CD, Tilburg

Werkdagen: MA | WO | DO | VR

**Comment by piotrbak** [comment]
@warudin We haven't had any related feedback for more than year now. If it's still the problem, please reach our Support
