### ISSUE TITLE
Update Kinsta Compatibility

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4717]
Kinsta no longer use KeyCDN and they have updated their MU Plugin to remove the `\Kinsta\CDN_Enabler` class. 
That is causing the following notice to always show for users due to the logic in this file https://github.com/wp-media/wp-rocket/blob/develop/inc/3rd-party/hosting/kinsta.php :

> **Your installation seems to be missing core Kinsta files managing Cache clearing and CDN, which will prevent your Kinsta installation and WP Rocket from working correctly. Please get in touch with Kinsta support through your MyKinsta account to resolve this issue.**

This could also causes WP Rocket to no longer clear the Kinsta cache.

**Additional context**
HS Ticket from Kinsta support: https://secure.helpscout.net/conversation/1781767741/324931/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by viobru** [comment]
Related ticket (Kinsta cache not synced with WP Rocket): https://secure.helpscout.net/conversation/1779812094/324509/

**Comment by alexstine** [comment]
@WordPresseur I opened this PR: https://github.com/wp-media/wp-rocket/pull/4719

No idea if it works or not, cannot figure out how to build the plugin locally in to a production version that I can test on a Kinsta site. Can you provide build instructions?

Thanks.

**Comment by piotrbak** [comment]
@Tabrisrp could you take a look at the PR?

@alexstine you'd need to:
- clone repository using `git`
- install dependencies using `composer install --no-dev --no-scripts -o`
- define constants in the `wp-config`. `WP_ROCKET_EMAIL` which is the email for your WP Rocket account and `WP_ROCKET_KEY` which is your API Key. Both of them can be found in the downloaded zip file of WP Rocket in the `license.php` file.

```
define( 'WP_ROCKET_KEY', '' );
define( 'WP_ROCKET_EMAIL', '' );
```

- navigate to your branch using `git checkout`

Let me know if you don't have any WP Rocket account.

**Comment by alexstine** [comment]
@piotrbak I have successfully generated the patched plugin and uploaded it to a Kinsta dev site.

URL: https://kmpnocdn2.kinsta.cloud
User: test
Pass: r(KKprr1V30(jrd(3@m8D*vO

Don't worry, it is a dev site so I'll remove it when we're finished here.

Can you add a license key and give it a test? If I need to add license info in wp-config.php, you can reach out at alexstine@kinsta.com. I do not have license info for testing.

Thanks.

**Comment by alexstine** [comment]
@piotrbak Thanks for the email. I successfully activated the plugin on the test site above and all seems to be working fine. I tried a cache clear from both plugins and see no errors in logs. Would you like to confirm everything is working as it should?

Thanks.
