### ISSUE TITLE
Error activating Load java script deferred

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4718]
**Describe the bug**
If we disable the two options minify css & minify js, then enable the Load java script deferred option, the browser console error will be displayed.
In fact, Rocket's suggestion is not to enable these two options.

elementor is installed.

**Comment by piotrbak** [comment]
Hello @79ho3ein please reach our Support Team https://wp-rocket.me/support/. They will help you and we'll fix the issue in the core if that's needed.
