### ISSUE TITLE
[WIP] Lazyload - images aren't displayed on older mobile iOS devices with the default placeholder

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4722]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.10.7`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On a customer's website, **some** of the lazyloaded images weren't displayed on mobile iOS (tested on browserstack.com with an iPhone 11 /iOS 13), despite the fact that the placeholder was replaced by the URL of images.

Navigating away from the page, and then back again displayed images: https://youtu.be/kNzg9M8ijiU

Images were properly displayed on later iOS versions and on Android devices/Chrome's mobile simulator.

The "symptomatic" solution came by repacing the default placeholder with one that has dimensions of 1x1px with the following code:
```PHP
function custom_wpr_lazyload_placeholder() {
    return "data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201%201'%3E%3C/svg%3E";
} 
add_filter( 'rocket_lazyload_placeholder', 'custom_wpr_lazyload_placeholder' );
```

**To Reproduce**

It's not clear why the specific images markup prevented them from being displayed.

For testing purposes, the complete page can be found here: https://drive.google.com/file/d/1p8UM0K2cguzD49g5vl9Gc2-8mXDkC17m/view?usp=sharing

**Expected behavior**

Images should be displayed regardless of the iOS version/markup.

**Additional context**

This thread is to record/investigate such cases.

**Ticket:** https://secure.helpscout.net/conversation/1776962683/323988/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Possibly related: https://secure.helpscout.net/conversation/1780026066/324571/

**Comment by mifrero** [comment]
Related: https://secure.helpscout.net/conversation/1942309913/354402/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2051579814/377981/
Replacing the place holder with `data:image/gif;base64,R0lGODdhAQABAPAAAP///wAAACwAAAAAAQABAEACAkQBADs=` fixed the issue. 
One thing to watch for is the presence of `height` and `width` set to `auto` in this particular case. It might have had some kind of conflict with the SVG placeholder.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
