### ISSUE TITLE
I can confirm that WP-Rocket is working fine with Cloudflare APO.

### ISSUE THREAD

**Issue by AnkushChharri** [wp-media/wp-rocket#4725]
"Hi, Can You tell me, You use Cloudflare Plugin or WP Rocket Adon"
I can confirm that WP-Rocket is working fine with Cloudflare APO.

Header:

status: 200
x-cache: HIT
set-cookie: __cfduid=d47b0b49c7bf0f606541c64303647b1531602349346; expires=Mon, 09-Nov-20 17:02:26 GMT; path=/; domain=.teacherph.com; HttpOnly; SameSite=Lax; Secure
cf-cache-status: HIT
expires: Sat, 10 Oct 2020 14:53:22 GMT
vary: Accept-Encoding
x-via: speedwp/cache
last-modified: Sat, 10 Oct 2020 14:53:22 GMT
link: <https://www.teacherph.com/wp-json/>; rel="https://api.w.org/"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=22&lkg-time=1602349346"}],"group":"cf-nel","max_age":604800}
date: Sat, 10 Oct 2020 17:02:26 GMT
cf-ray: 5e01e8b6eeb40abc-NRT
cf-edge-cache: cache,platform=wordpress
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"report_to":"cf-nel","max_age":604800}
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
content-encoding: br
age: 6532
strict-transport-security: max-age=31536000; includeSubDomains; preload
cf-request-id: 05b50fc65100000abc9ca4f200000001
server: cloudflare
cache-control: max-age=0
x-frame-options: SAMEORIGIN
content-type: text/html; charset=UTF-8
:status: 200

_Originally posted by @markllego in https://github.com/wp-media/wp-rocket/issues/3180#issuecomment-706580529_

**Comment by piotrbak** [comment]
Hello @AnkushChharri thank you for being in touch.

Cloudflare cache might not be synchronised with WP Rocket's one. We did our best to make sure it won't cause broken layout on your site though.
