### ISSUE TITLE
Deprecation notice when using PHP 8.1

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4728]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ☑️
- Used the search feature to ensure that the bug hasn’t been reported before ☑️

**Describe the bug**
A customer informed this deprecation notice is displayed when running PHP 8.1:

`Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/vhosts/f****g.com/httpdocs/wp-content/plugins/wp-rocket/inc/admin/upgrader.php on line 41`

**To Reproduce**
N/A

**Expected behavior**
There should  be no deprecation notice displayed when running PHP 8.1

**Screenshots**
N/A

**Additional context**
The customer took this from the debug file from wp-content.

Related ticket: [https://secure.helpscout.net/conversation/1783564514/325265](https://secure.helpscout.net/conversation/1783564514/325265)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Replace the current sanitization code by `sanitize_key()` in `upgrader.php`, `rocket_upgrader()` line 41. 

### Estimate the effort ✅
Effort `[XS]`
