### ISSUE TITLE
Wp-rocket interference with the new version of elementor pro

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4731]
**Describe the bug**

After the new version of elementor, if we do not activate the wp-rocket plugin, there is no error. But after activating wp-rocket, an error will be displayed in the browser console. https://prnt.sc/26vj761
These two errors are fixed when we enable the java script deferred option.

There is definitely a problem. I only use hello elementor theme, elementor and elementor pro plugin. They are the most compatible plugins with wp-rocket.

**Comment by piotrbak** [comment]
Duplicated:
https://github.com/wp-media/wp-rocket/issues/4701
