### ISSUE TITLE
Wrong URL when using minification and relative URLs on subfolders

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4735]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WordPress is installed on a subfolder, relative paths are outputted wrong when using minification and relative paths.

Root folder: https://example.com/2020
Relative path: url(../fonts/elementskit.woff?y24e1e)
Stored path after minification: url(https://example.com/2020/2020/fonts/elementskit.woff?y24e1e)

**To Reproduce**
1. Go to use a subfolder installation
2. Add relative paths on CSS
3. Enable minification

**Expected behavior**
The paths on relative URLs should be properly written on subfolders when using relative URLs.

**Screenshots**
N/A

**Additional context**
Related - https://secure.helpscout.net/conversation/1783623979/325298/
It seems to be related to https://github.com/wp-media/wp-rocket/issues/757

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
