### ISSUE TITLE
Exclude js.hscta.net from JS defer (possibly minification as well)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4738]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.7`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When `js.hscta.net` is deferred, the following dependency errors show on the browser console. 

```
page:348 Uncaught ReferenceError: hbspt is not defined
```
![image](https://user-images.githubusercontent.com/1289174/154233787-daf99eea-4f85-4f79-af78-96d7730fb87b.png)

The script is the following: 

```
​<script charset="utf-8" src="https://js.hscta.net/cta/current.js">
<script type="text/javascript"> hbspt.cta.load(###, '###-###-###-###-###', {}); </script>
```

Excluding `/cta/current.js` from JS defer fixes the issue. But it might be too generic and other tracking platforms might use it. 

It will be safer to exclude `js.hscta.net` from both defer and minify JS.

**To Reproduce**
1. Add HubSpot CTA tracking script.
2. Enable defer JS
3. See error

**Expected behavior**
HubSpot CTA tracker should work when defer JS is enabled out of the box.

**Screenshots**
Added to the description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1783629654/325301

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by worldwildweb** [comment]
[related helpscout issue ](https://secure.helpscout.net/conversation/1810576085/330503/)

`current.js` and `hbspt.cta.load` should be excluded as well from the **Delay JavaScript execution feature**

`<script type="rocketlazyloadscript" data-rocket-type="text/javascript"> hbspt.cta.load(2579063, '###-###-###-###-###', {"useNewLoader":"true","region":"na1"}); </script>`


`<script type="rocketlazyloadscript" charset="utf-8" src="https://js.hscta.net/cta/current.js" defer>`

**Comment by piotrbak** [comment]
Added the following exclusions:
1. Defer JS: `js.hscta.net/cta/current.js`
2. Delay JS: `hbspt.cta.load`, `js.hscta.net/cta/current.js`
