### ISSUE TITLE
Always Purge URL isnot clearing Kinsta Cache when editing post

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4742]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When editing post1 while Always Purge URL contains /post2/, Post2 cache is not cleared by Kinsta 

**To Reproduce**
- Site hosted by Kinsta
- Always Purge URL contains /post2/
- Our preload is disabled

1. Cache post 2
2. edit post 1 or page 1
3. check post 2 in console => Kinsta-Cache: Hit 

**Expected behavior**
Kinsta cache is cleared 

**Screenshots**
https://user-images.githubusercontent.com/76941962/154452078-eb83fbe9-771c-4ae5-85ff-4b6e787ec98d.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Could be related to https://github.com/wp-media/wp-rocket/issues/4441

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
