### ISSUE TITLE
Can't exclude js file containing space in it's path from Delay JS nor Defer JS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4746]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Active theme containing space in its name or file name contains %20

**To Reproduce**
1. Enable Defer JS and Delay JS
2. Add file path in exclusion i.e /wp-content/themes/your%20theme/js_file.js
3. Save => %20 is removed from exclusion
4. check the home page => the file not excluded from Delay JS nor Defer JS

**Expected behavior**
js file is excluded

**Additional context**
- The same scenario is handled for Minify JS

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
It seems to be a very edge case, no reports till now. I'll close it and we'll reopen if we have any good reason to fix it.
