### ISSUE TITLE
Clearly warn customers that upgrading a license does NOT change its expiration date

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4747]
**Is your feature request related to a problem? Please describe.**

Currently, the way we inform the customers that upgrading a license won’t change its expiration date it is not clear enough.
We receive lots of tickets from customers that skipped that information or that are confused about this.

We only mention this in the following line on the Account page:

N.B.: Upgrading your license doesn’t change its expiration date.
Screenshot: https://i.imgur.com/GgxKS7S.png

And the message is gone after switching to the payment page:
Screenshot: https://i.imgur.com/WENASC3.png

**Describe the solution you'd like**

The message should be displayed in red and/or in a clearly noticeable warning box, and it should also include a link to [this doc](https://docs.wp-rocket.me/article/1262-i-upgraded-why-is-my-license-still-expired).

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
