### ISSUE TITLE
Delay JavaScript Execution compatibility with Dynamic Pricing & Discounts Lite

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4748]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript Execution is used with Dynamic Pricing & Discounts Lite, the following error show up on the browser console: 

```
Uncaught TypeError: $(...).owlCarousel is not a function
    at HTMLDocument.<anonymous> (rtwwdpdl-woo-dynamic-pricing-discounts-lite-public.js?ver=1.4.0:1:191)
    at e (jquery.min.js?ver=3.5.1:2:30005)
    at t (jquery.min.js?ver=3.5.1:2:30307)
```

The issue happens on both Delay JavaScript Execution and Defer JS. 

Excluding the following from Delay JavaScript Execution and Defer JS fixes the issue: 

```
/woo-dynamic-pricing-discounts-lite/assets/OwlCarousel/dist/owl.carousel.min.js
```
Requires excluding `jQuery` as well. 

**To Reproduce**
1. Use Dynamic Pricing & Discounts Lite
2. Enable Delay JavaScript Execution or Defer JS
3. See error

**Expected behavior**
Thre shouldn't be any browser console errors when Dynamic Pricing & Discounts Lite is used.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1788258912/326329/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Do you happen to have access to the site?

Why `owlCarousel` is not defined, is this because our auto exclusions?

**Comment by DahmaniAdame** [comment]
> @DahmaniAdame Do you happen to have access to the site?

Yes! It's still on the ticket. 

> Why owlCarousel is not defined 

It's because it comes after this one - [/wp-content/plugins/woo-dynamic-pricing-discounts-lite/public/js/rtwwdpdl-woo-dynamic-pricing-discounts-lite-public.js](https://gist.github.com/DahmaniAdame/bf88119e0802a2cb5a4a4d454b956d9c)

```
(function($){'use strict';$(document).ready(function(){$('body').on('change','input[name="payment_method"]',function(){$('body').trigger('update_checkout')});$('.rtwwdpdl-carousel-slider').owlCarousel({loop:!1,margin:15,nav:!1,navText:!1,responsiveClass:!0,responsive:{0:{items:1,nav:!0},600:{items:2,nav:!1},1000:{items:4,nav:!0,loop:!1}}})})})(jQuery)
```

For some reason, if both are delayed, `rtwwdpdl-woo-dynamic-pricing-discounts-lite-public.js` can't satisfy the dependency.

If none of them is delayed, there is no error as well.  

It's weird though because `owlCarousel` is declared after it's called because `rtwwdpdl-woo-dynamic-pricing-discounts-lite-public.js` proceeds `owl.carousel.min.js` in order. 

Maybe there is something else involved? 

> is this because our auto exclusions?

We don't have any auto exclusion related to that.

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
