### ISSUE TITLE
Disable WP Rocket CDN when any DNS CDN feature is enabled on WP Engine

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4750]
**Is your feature request related to a problem? Please describe.**
WP Engine's features [Global Edge Security](https://wpengine.com/support/ges/) or [advanced network](https://wpengine.com/support/advanced-network/) use a CDN at the DNS level.

If we have a way to check if any of the two services is activated, we could gray WP Rocket CDN feature and mention that the CDN is already being taken care of at the DNS level by WP Engine. 

This will create less confusion from users thinking that the Advanced Network requires activating the CDN feature on WP Rocket's side.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Added to the description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1791019748/326901/

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
