### ISSUE TITLE
WP Rocket CDN compatibility with Elementor's Improved Asset Loading feature

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4751]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.8`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Elementor's Improved Asset Loading is activated, assets subject to this feature won't load loading WP Rocket CDN. 

The reason for that is the assets are not found anywhere on the page until Elementors calls them using `/elementor-pro/assets/js/webpack-pro.runtime.min.js`

```
__webpack_require__.u = e=>714 === e ? "code-highlight.b6f0d66f4bf269cb0144.bundle.min.js" : 721 === e ? "video-playlist.0bb7afc906f060c147e9.bundle.min.js" : 256 === e ? "paypal-button.ac6722c1c8d5b5abd252.bundle.min.js" : 241 === e ? "progress-tracker.08fa72f4b90b839356ab.bundle.min.js" : 26 === e ? "animated-headline.fc85cfa4b6ff36a0d396.bundle.min.js" : 534 === e ? "media-carousel.1d2fb1c210214d92dace.bundle.min.js" : 369 === e ? "carousel.171966b0e9c3cf80fbc1.bundle.min.js" : 804 === e ? "countdown.3242868e4822d881943a.bundle.min.js" : 888 === e ? "hotspot.6761fa209b8076872172.bundle.min.js" : 680 === e ? "form.9c819fdcd2d2c5217b4a.bundle.min.js" : 121 === e ? "gallery.87cf817e57c8522b3dec.bundle.min.js" : 288 === e ? "lottie.2953a8902fb25dd5bebb.bundle.min.js" : 42 === e ? "nav-menu.4432c50d0d1f64da9d7c.bundle.min.js" : 50 === e ? "popup.6a2540c839ce119e42a7.bundle.min.js" : 985 === e ? "load-more.382e5f9900b20456ebc1.bundle.min.js" : 287 === e ? "posts.ec5203e2235ef585d19c.bundle.min.js" : 824 === e ? "portfolio.71d47a165e31757e99e4.bundle.min.js" : 58 === e ? "share-buttons.b7783b74aa530c677f8b.bundle.min.js" : 114 === e ? "slides.79313cea2968367844b8.bundle.min.js" : 443 === e ? "social.7ec4eb39eed98fc131c7.bundle.min.js" : 838 === e ? "table-of-contents.2c549e4ffc0c8124385d.bundle.min.js" : 685 === e ? "archive-posts.380546a8164927d2ae2c.bundle.min.js" : 858 === e ? "search-form.bb4995a71b0601723450.bundle.min.js" : 102 === e ? "woocommerce-menu-cart.afc0d0048e5096712e69.bundle.min.js" : 1 === e ? "woocommerce-purchase-summary.536fdf58998b053b371e.bundle.min.js" : 124 === e ? "woocommerce-checkout-page.97de28f3b51c9b3d79c2.bundle.min.js" : 859 === e ? "woocommerce-cart.9dd6efcdaf65d3f52417.bundle.min.js" : 979 === e ? "woocommerce-my-account.6eb9e2a105713bde71ee.bundle.min.js" : 497 === e ? "woocommerce-notices.78fdbf68535bcc1fe500.bundle.min.js" : void 0,
```

**To Reproduce**
1. Enable Elementor's Improved Asset Loading
2. Use WP Rocket's CDN feature
3. See that some assets won't load from the CDN

**Expected behavior**
Ideally, assets subject to the Elementor's Improved Asset Loading should be loaded from the CDN. But the compatibility will likely need to be done on Elementor's level as we can't control the mechanism used to load the assets.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1791161770/326919/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by girlie** [comment]
Related: https://secure.helpscout.net/conversation/2079027439/384753/

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Comment by deltafactory** [comment]
I have a similar need, not specifically with WP Rocket. I am hooking to `elementor/frontend/assets_url` which would seem to be related but it isn't changing the source for the webpack-pro.runtime.min.js.

Consider this another request to support this feature!

**Comment by deltafactory** [comment]
On a hunch I checked for instances of /frontend/assets_url/ and found that `elementor_pro/frontend/assets_url` exists and appears to do exactly what we're requesting. The OP may need to contact WP Rocket but the implementation is extremely easy.
