### ISSUE TITLE
Provide compatibility with Composer Installers v2

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4753]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
We are currently not compatible with Composer installers v2.

We require Composer installers ~1 [here](https://github.com/wp-media/wp-rocket/blob/db453edf38fecad142cea0fa898a6ed8dfadda66/composer.json#L42), when Composer 2 is used in the root, the following error occurs:

```
Problem 1
- Root composer.json requires wp-media/wp-rocket ^v3.10.8 -> satisfiable by wp-media/wp-rocket[v3.10.8].
- wp-media/wp-rocket v3.10.8 requires composer/installers ~1.0 -> found composer/installers[v1.0.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.0).
```

**Expected behavior**
WP Rocket compatible with Composer installers v2+

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1792292794/327143?folderId=3864740
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1645467256639999

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by dakkafex** [comment]
Any progress on this? its impossible to install or update the plugin right now.
