### ISSUE TITLE
Uncode theme + WooCommerce plugin compatibility

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4754]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
jQuery console error exists when WooCommerce is enabled with Uncode Theme and our Delay JS is enabled

**To Reproduce**
- Active theme Uncode
- WooCommerce is enabled
- Delay JS is enabled

1. Open the home page
2. jQuery Console error

**Expected behavior**
No console error

**Screenshots**
![Screenshot from 2022-02-22 09-59-20](https://user-images.githubusercontent.com/76941962/155090203-a45c2889-4846-430b-bfd3-fc92ad006dd1.png)

**Additional context**
- Excluding `/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js` will fix the problem (not sure if we need to exclude `/jquery-migrate(.min)?.js` too)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Will be fixed with the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
