### ISSUE TITLE
Delay JavaScript Execution compatibility with Product Slider Pro for WooCommerce

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4755]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Product Slider Pro for WooCommerce is used with Delay JavaScript Execution, the added slider stops working and the following error shows on the console: 

```
Uncaught TypeError: jQuery(...).slick is not a function
    at HTMLDivElement.<anonymous> (scripts.min.js?ver=2.7.4:1:1385)
    at Function.each (jquery.min.js?ver=3.5.1:2:2976)
    at s.fn.init.each (jquery.min.js?ver=3.5.1:2:1454)
    at HTMLDocument.<anonymous> (scripts.min.js?ver=2.7.4:1:469)
    at e (jquery.min.js?ver=3.5.1:2:30005)
    at t (jquery.min.js?ver=3.5.1:2:30307)
```

The issue is only there if `jQuery` is excluded. 

The issue is fixed by excluding: 

```
/woo-product-slider-pro/public/assets/js/slick.min.js
```

**To Reproduce**
1. Use Product Slider Pro for WooCommerce
2. Add a slider on the page
3. Use Delay JavaScript Execution and exclude `jQuery`

**Expected behavior**
The slider should work out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1788258912/326329/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closing it as we discussed on the meeting while ago. The issue only exists if there's a manual action done and can be solved with default exclusions.
