### ISSUE TITLE
WCML update/rollback/replace won't affect existing cookies in wp-config file

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4756]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Cookies in wp-config won't be affected when updating/rollback/replacing WCML version

**To Reproduce**
- WPR is installed and activated 3.10.8
- WCML is installed and activated v < 4.12.6 i.e 4.11

1. Update WCML
2. Cookies not added in wp-config (dynamic and mandatory cookies)

**Expected behavior**
Cookies are affected by WCML updates (dynamic/mandatory cookies are added based on currency state)

**Additional context**
- Reactivate plugin or change currency settings will adjust cookies
- If WCML is updated and cookies (mandatory and dynamic) were set then we replace the latest WCML with version < 4.12.6 or rollback to older version => existing cookies won't be changed unless we reactivate the plugin or change currency settings

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closing it since we didn't have any feedback about this issue + the WCML version is now 5.1.3
