### ISSUE TITLE
Exclude the script for AMP redirection from Delay JS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4757]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The script which redirects mobile pages to the amp is delayed

**To Reproduce**
- Cache for mobile devices is enabled
- Delay JS is enabled
- Amp redirect is enabled

1. Open the home page in mobile view 
2. redirect to ?amp does not occur till user interaction

**Expected behavior**
Amp redirect occurs without user interaction

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@Mai-Saad Which JS file or inline script must be excluded from Delay JS to have the redirection without user interaction?

**Comment by Mai-Saad** [comment]
@GeekPress this is the inline script (using AMP v2.2.1)

```
<script type="rocketlazyloadscript">
 !function(){var e={};e.g=function(){if("object"==typeof globalThis)return globalThis;try{return this\|\|new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),function(n){let{ampUrl:t,isCustomizePreview:r,isAmpDevMode:o,noampQueryVarName:s,noampQueryVarValue:i,disabledStorageKey:a,mobileUserAgents:c,regexRegex:u}=n;if("undefined"==typeof sessionStorage)return;const d=new RegExp(u);if(!c.some((e=>{const n=e.match(d);return!(!n\|\|!new RegExp(n[1],n[2]).test(navigator.userAgent))\|\|navigator.userAgent.includes(e)})))return;e.g.addEventListener("DOMContentLoaded",(()=>{const e=document.getElementById("amp-mobile-version-switcher");if(!e)return;e.hidden=!1;const n=e.querySelector("a[href]");n&&n.addEventListener("click",(()=>{sessionStorage.removeItem(a)}))}));const g=o&&["paired-browsing-non-amp","paired-browsing-amp"].includes(window.name);if(sessionStorage.getItem(a)\|\|r\|\|g)return;const m=new URL(location.href),h=new URL(t);h.hash=m.hash,m.searchParams.has(s)&&i===m.searchParams.get(s)?sessionStorage.setItem(a,"1"):h.href!==m.href&&(window.stop(),location.replace(h.href))}({"ampUrl":"https:\/\/new.rocketlabsqa.ovh\/?amp","noampQueryVarName":"noamp","noampQueryVarValue":"mobile","disabledStorageKey":"amp_mobile_redirect_disabled","mobileUserAgents":["Mobile","Android","Silk\/","Kindle","BlackBerry","Opera Mini","Opera Mobi"],"regexRegex":"^\\/((?:.\|\n)+)\\/([i]*)$","isCustomizePreview":false,"isAmpDevMode":false})}();
   </script>
```
excluding `amp-mobile-version-switcher` works fine for both standard and transitional mode

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `amp-mobile-version-switcher` to the `DelayJS\HTML::$excluded` array

### Estimate the effort ✅
Effort `[XS]`
