### ISSUE TITLE
Automatically exclude the script which remove cpcss style tag after page loads from Delay JS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4758]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When CSS load async is enabled with delay js, the `id='rocket-critical-css'` is not removed from inspect till user interaction

**To Reproduce** 

Precondition:
- Enable Load CSS Async

1. Open the home page 
2.  In inspect view : `id='rocket-critical-css'` is not removed till user interaction

**Expected behavior**
`id='rocket-critical-css'` is removed after page load without the need for user interaction

**Additional context**
- excluding `wprRemoveCPCSS` from Delay JS works fine (not sure if this is the best keyword to use)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@piotrbak Can this be planned for the next minor version? It's a very easy enhancement to do.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `wprRemoveCPCSS` to the `DelayJS\HTML::$excluded` array

### Estimate the effort ✅
Effort `[XS]`

**Comment by swabhav** [comment]
my site logo loading under the script tag but getting an issue - Image elements do not have explicit width and height

screenshot - https://prnt.sc/CIO1j8Md2z4s
site url - https://sarkarify.com/

**Comment by sarkariprep-in** [comment]
hello sir 
my site logo loading under the script tag but getting an issue - Image elements do not have explicit width and height. please check.
screenshot - https://prnt.sc/CIO1j8Md2z4s
site url - https://sarkariprep.in/

**Comment by cemca22** [comment]
my site logo loading under the script tag but getting an issue
https://cemca.org.in

**Comment by cemca22** [comment]
https://cemca.org.in

**Comment by sarkariprep-in** [comment]
hello sir
my site logo loading under the script tag but getting an issue - Image elements do not have explicit width and height. please check.
Site URL - [sarkariprep.in](https://sarkariprep.in/)
Site URL - [sarkariprep.com](https://sarkariprep.com/)

Please Help Me Sir
