### ISSUE TITLE
Lazy load dynamic element using AJAX

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4761]
**Is your feature request related to a problem? Please describe.**
Some themes have conditional elements as a feature where an element will show conditionally depending on the device, location, and other factors. 

When used with page cache, those types of elements will only show the first iteration at the moment of the cache creation. 

**Describe the solution you'd like**
Build a mechanism to extract dynamic elements, add placeholders, and use AJAX to re-populate them after the page loads. 

Blocks and shortcodes are easy to accurately isolate and execute separately. 

Functions might require loading the full page, extracting the specific selector for the dynamic element, and using AJAX to re-populate them after the page loads. 

**Describe alternatives you've considered**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1793749029/327392

**Comment by rikgoedhart** [comment]
Yes this would be GREAT for Avada (Wordpress theme) users! It's also great for improving the Google Pagespeed results when using different containers for mobile and desktop. There is a significant difference between not rendering an Element and simply hiding it on the page.

More info on this feature:
https://theme-fusion.com/documentation/avada/how-to/how-to-use-conditional-element-rendering-in-avada/

**Comment by itsinalis** [comment]
+1

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.

**Comment by rikgoedhart** [comment]
We are now two years on, and it remains crucial for the correct functioning of the Avada theme. You can use conditional logic for loading containers and columns. This means it's not just about displaying or hiding them with display: none; it genuinely ensures that blocks are loaded or not based on specific conditions.

Therefore, it would be very beneficial and important to schedule this implementation. Avada users could achieve significant speed improvements by applying conditional logic. It reduces the loading of many elements, such as those not needed for mobile but required for desktop, and vice versa.

I kindly request a reconsideration of the decision and ask that this functionality be implemented.

**Comment by piotrbak** [comment]
Closing as currently not planned doesn't mean we'll not work on it. It means that we'll not work on it in upcoming quarter and we might get back to it while working on related topic.
