### ISSUE TITLE
Woocommerce Image gallery [shortcode] broken on Safari when caching for mobile devices and LazyLoad are enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4762]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
when using [woocommerce Product Category shortcode](https://woocommerce.com/document/woocommerce-shortcodes/), images in the gallery are broken on the category page when WPR LazyLoad and Enable caching for mobile devices are both enabled on safari

**To Reproduce**
1. add shortcode [product_categories number="0" parent="0"] to any page 
4. Enable WPR LazyLoad and Enable caching for mobile devices
3. Go to the gallery page
4. See images broken on iPhone Safari or MacOs Safari (Responsive design mode)
![Screenshot 2022-02-23 at 11 39 05](https://user-images.githubusercontent.com/1954918/155303596-ef4b26e7-ac06-496b-b2a6-93963a017aa8.png)

**Expected behavior**
Images should not be broken on Safari when WPR LazyLoad and Enable caching for mobile devices are both enabled 

**Screenshots**
WPR LazyLoad and Enable caching for mobile devices are both enabled -> images are broken
![Screenshot 2022-02-23 at 11 39 05](https://user-images.githubusercontent.com/1954918/155303596-ef4b26e7-ac06-496b-b2a6-93963a017aa8.png)

WPR LazyLoad is enabled and Enable caching for mobile devices is **disabled** ->  images are not broken
![Screenshot 2022-02-23 at 11 39 33](https://user-images.githubusercontent.com/1954918/155303633-87670925-d11c-4994-8e31-6472e25ea893.png)

**Additional context**
GeneratePress Version 3.1.3
Woocommerce Version 6.2.0
WP Rocket Version 3.10.8
IOS 15.3.1 -> Safari Version 15
macOS Monterey 12.2.1 -> Safari Version 15.3 (17612.4.9.1.8)
[helpscout issue](https://secure.helpscout.net/conversation/1791667148)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
