### ISSUE TITLE
LazyLoad for iframe - Auto exclude Mediavines ads iframes from being LazyLoaded 

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4763]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Mediavines uses iframes like the following for showing their ads:
`<iframe frameborder="0" src="https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html" id="google_ads_iframe_/xxxxxxxx,xxxxxxxxxxx/domain/sticky_sidebar_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="1" height="1" data-is-safeframe="true" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" role="region" aria-label="Advertisement" tabindex="0" data-google-container-id="3" style="border: 0px; vertical-align: bottom; height: 250px; width: 300px;" data-load-complete="true" data-hooks="true"></iframe>`

Applying our LazyLoad in these iframes breaks them.

Excluding **google_ads_iframe_** from being LazyLoad fixes the issue.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1792313885/327148?folderId=1213662

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `RocketLazyload\Iframe::getExcludedPatterns()`, add `google_ads_iframe_` to the returned array. 

### Estimate the effort ✅
Effort `[XS]`
