### ISSUE TITLE
Google font optimization with 3rd party that rewrites the Google Fonts to the internal styles

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4766]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When having a template with no google fonts while Divi theme is enabled, we remove this from source `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />` 

**To Reproduce**
Precondition:
Active theme Divi

1. Go to https://new.rocketlabsqa.ovh/delay-js-order/
2. Compare source to nowprocket page

**Expected behavior**
Keeping `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />` in source

**Screenshots**
With WPR:
![Screenshot from 2022-02-28 10-22-49](https://user-images.githubusercontent.com/76941962/155949183-74f189e1-b4c2-4166-b5a4-ea63b709caa0.png)

Without WPR
![Screenshot from 2022-02-28 10-23-10](https://user-images.githubusercontent.com/76941962/155949219-429d37b8-0d7b-4204-8460-eec339f75c75.png)

**Additional context**
- As per discussion, This will happen whenever 3rd party rewrites the Google Fonts to the internal styles
- If we checked the home page, which contains some GF, we will find that we add `<link href='https://fonts.gstatic.com/' crossorigin rel='preconnect' />` beside keeping the one related to 3rd party `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />` => better we avoid duplication in this case

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
