### ISSUE TITLE
Delay JS - The Photonic plugin breaks 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4769]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ (`3.10.8`)
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When Defer JavaScript files is active galleries that are added with the [Photonic Gallery & Lightbox for Flickr, SmugMug, Google Photos & Others](https://wordpress.org/plugins/photonic/) plugin aren't loading.

Excluding the following resolved the issue:
```HTML
/photonic/include/js/front-end/nomodule/combo-slider/photonic-baguettebox.min.js
/photonic/include/js/front-end/module/combo-slider/photonic-baguettebox.min.js
```

**To Reproduce**
1. Install the plugin.
2. Add a gallery on a page.
3. Visit it.
4. See error.

**Expected behavior**

Photonic should work when Delay JavaScript Execution is active.

**Additional context**

Exclude `/photonic/include/js/front-end/` in the core by adding it in the `$excluded` array:
https://github.com/wp-media/wp-rocket/blob/b34218065e5935e7482c7c60721becc26e237c97/inc/Engine/Optimization/DelayJS/HTML.php#L26-L73

**Ticket:** https://secure.helpscout.net/conversation/1800351383/328613?folderId=273766

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@vmanthos Are you sure we should exclude all JS files under the `/photonic/include/js/front-end/`?

**Comment by vmanthos** [comment]
> Are you sure we should exclude all JS files under the /photonic/include/js/front-end/?

@piotrbak I had to exclude them when I checked this.

**Comment by vmanthos** [comment]
@piotrbak I checked this again because of the error mentioned in @Mai-Saad 's comment:
https://github.com/wp-media/wp-rocket/pull/4772#issuecomment-1099955599

Using the latest version of the Photonic plugin,  the issue was resolved by excluding the following file:
`/photonic/include/js/front-end/nomodule/photonic-baguettebox.min.js`

I'll update my PR to reflect this.

For the gallery to be displayed without user interaction, the following have to be excluded:
```HTML
/photonic/include/ext/baguettebox/baguettebox.min.js
/photonic/include/js/front-end/nomodule/photonic-baguettebox.min.js
/photonic/include/js/front-end/module/photonic-baguettebox.min.js
```

We'll need to update our [exclusions](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions) doc.
