### ISSUE TITLE
wp-rocket slows down WordPress dashboard.

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4775]
**Describe the bug**

From the beginning, the installed plugins section opened very slowly. Even on websites where I used only 5 plugins. This slowness was seen even in WooCommerce products. But the slowness of the installed plugins was more than normal and really boring. I even removed all plugins except elementor and Rocket, but there was still a slow speed. I did not even imagine it, but when I disabled wp-rocket, the speed of the installed plugins section increased dramatically. I tested this on two of my other websites and had a similar experience.
Please check this.

**Comment by sarangsss29** [comment]
True

**Comment by 79ho3ein** [comment]
It is true! I also had a problem with slowdowns in the installed plugins. I disabled the wp-rocket plugin and the speed problem was fixed.
After the rocket was deactivated, there was an increase in speed even in WooCommerce products. Overall, the speed of the WordPress dashboard increased.

**Comment by javiergutierrezchamorro** [comment]
Should be solved I see.
https://github.com/wp-media/wp-rocket/commit/2ba879eebfdf763667163530ca829879492f3754

**Comment by piotrbak** [comment]
@Michaelgimii are the things better after applying the above fix?

**Comment by javiergutierrezchamorro** [comment]
> @Michaelgimii are the things better after applying the above fix?

I think so.

**Comment by Michaelgimii** [comment]
@piotrbak , yes thank you
