### ISSUE TITLE
Getaway - Travel & Tourism Theme: Testimonials images not displayed when Delay JavaScript execution is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4779]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [Getaway - Travel & Tourism Theme](https://themeforest.net/item/getaway-an-upbeat-travel-and-tourism-theme/20719616) is installed and when Delay JavaScript execution is enabled the testimonials images are not displayed.

**To Reproduce**
1. Install [Getaway - Travel & Tourism Theme](https://themeforest.net/item/getaway-an-upbeat-travel-and-tourism-theme/20719616)
2. Add testimonial on a page
3. Enable Delay JavaScript execution
4. See Getaway testimonial images are not displayed

**Expected behavior**
Getaway theme testimonial images should be displayed when Delay JavaScript execution is enabled

**Screenshots**
![Getaway testimonial](https://user-images.githubusercontent.com/1954918/156532523-4db9b98c-a553-4a48-b82c-264cf346bb85.png)

**Additional context**
[helpscout issue](https://secure.helpscout.net/conversation/1729047535/314599/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
