### ISSUE TITLE
Add cache level setting to lower number of cache purges on high performance websites

### ISSUE THREAD

**Issue by foliovision** [wp-media/wp-rocket#478]
We run a website which gets 1 million pageviews every day and even 800,000 pageviews in a single hour during peak traffic. We choosed not to use Varnish but WP Rocket as we expected we will be able to debug or tweak its behavior better. It turned out to be just that - we are able to tweak WP Rocket behavior and we are thankful for that, but here is what we found and believe should be improved -

WP Rocket does way too many cache purges:

1) **Feeds are no longer cached** by WP Rocket since version 2.10.5 - this is a disappointment. Now we have to use some addon plugin to make sure the feeds are cached.

2) Full page cache is purged on **user registration** or user profile update - the last thing you need on a high performance website (as the server load just goes up when somebody registers). So we had to use the code  from here to stop these action from triggering rocket_clean_domain(): http://docs.wp-rocket.me/article/137-disable-all-automatic-cache-clearing

3) **New comments** to post also clear homepage and archive cache - this is to show accurate comment numbers, but in our case there is a new post or a post update every 15 minutes, so sooner or later these numbers are correct.

4) When post cache is cleared using rocket_clean_post() it also clears cache for:

* **next post**
* next post in same category
* previous post
* previous post in same category

I see it might make sense for some websites and to keep the next post link working. However wouldn't it be enough to do this when the post is first published or deleted only? Because currently when there is a new comment to the post, rocket_clean_post() is called and it clears all the adjacent posts as well.

------

While I see that your aim is to work well for 260k websites you should not forget about the high performance websites. I posted some emails to Caspar and it seems you want to keep your settings screens as simple as possible with few options available. So to provide some control over that cache level our suggestion would be for your to **add caching presets** like this:

* Normal (current plugin behavior)
* High (make sure feeds are cached (1) and (2) is automatically disabled along with (3) and (4))

I think such control would be very nice and make your plugin much more useful.

There could also be "Extreme" option which you limit the amount of cache purges done per minute by implementing some cache purge queue. Currenlty when our website gets 1 comment every 10 seconds, the homepage cache is cleared again and again (and the adjacent posts), so the server load is really an issue.

Thank you,
Martin

**Comment by GeekPress** [comment]
This helper plugin can be used to fine-tune how WP Rocket is purging cache:
https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-no-cache-auto-purge

I totally understand the need and the importance it can have for this kind of website. 
I guess we won't be able to make what is expected here. To keep our plugin easy to use we have to make choice like this one.

In all cases, what you want to achieve if possible by remove our default filter and recreate your own by using our functions.
