### ISSUE TITLE
Kava Theme: navigation header color not applied when scrolling down and when Delay JavaScript execution is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4780]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [Kava Theme](https://crocoblock.com/kava/) is installed and Delay JavaScript execution enabled, color on navigation is not applied on scroll down.

**To Reproduce**
1. Install [Kava Theme](https://crocoblock.com/kava/)
2. Set navigation to be fixed on scroll
3. Go to frontend and see that color is not applied on scroll down

**Expected behavior**
Color on navigation header should be applied when Delay JavaScript execution is enabled

**Screenshots**
Color is applied here in [this recording](https://jmp.sh/jzWAQbl) after `/themes/kava/assets/js/theme-script.js` was added in the Delay JavaScript execution > Excluded JavaScript Files

**Additional context**
[Helpscout issue](https://secure.helpscout.net/conversation/1767086783/321273/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Will be fixed with the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
