### ISSUE TITLE
Rey Theme: Rey slideshow not displayed when Delay JavaScript execution is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4781]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Rey slideshow is not displayed when Delay JavaScript execution is enabled

**To Reproduce**
1. Install [Rey theme](https://themeforest.net/item/rey-multipurpose-woocommerce-theme/24689383)
2. Add a slideshow to a page
3. Enable Delay JavaScript execution
4. See Rey slideshow is not displayed

**Expected behavior**
Rey slideshow should be displayed when Delay JavaScript execution is enabled

**Screenshots**

**Additional context**
[Helpscout ticket](https://secure.helpscout.net/conversation/1761661133/320226/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Will be fixed with the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
