### ISSUE TITLE
Progress Bar not working when Delay JavaScript execution is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4782]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Extra shortcodes Plugin is installed,  [Progress bar](https://getshortcodes.com/demo/extra-shortcodes/progress-bar/) is not working when Delay JavaScript execution is enabled

**To Reproduce**
1. Install [Extra shortcodes Plugin](https://getshortcodes.com/add-ons/extra-shortcodes)
2. Add a progress bar on a page
3. Enable Delay JavaScript execution
4. See that the progress bar is not working

**Expected behavior**
The progress bar should work when Delay JavaScript execution is enabled

**Screenshots**
Progress Bar working:
![Progress Bar working](https://user-images.githubusercontent.com/1954918/156568979-ab3b38e8-eba6-4525-8efe-61c0bb978f2e.png)

Progress Bar not working:
![Progress Bar not working](https://user-images.githubusercontent.com/1954918/156568901-80852c62-7fe7-418d-adf8-a7eae31fc3d1.png)

**Additional context**
[Helpscout issue](https://secure.helpscout.net/conversation/1778061762/324197/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
