### ISSUE TITLE
Console error when Combine JS is enabled with Avada theme

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4784]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
JS console error exists when enabling Combine JS with Avada theme

**To Reproduce**
precondition:
1- Avada active
2- Combine JS enabled

1. Go to home page i.e https://mega.wp-rocket.me/avada/
2. check the console error

**Expected behavior**
No console error

**Screenshots**
![Screenshot from 2022-03-03 19-37-13](https://user-images.githubusercontent.com/76941962/156620781-16cd7fa0-2666-43f8-8f1d-785686e2487e.png)

**Additional context**
other activated plugins
![Screenshot from 2022-03-03 19-38-04](https://user-images.githubusercontent.com/76941962/156620845-042493a9-3ac3-4dbc-99c7-70ec4197cfb4.png)
![Screenshot from 2022-03-03 19-37-56](https://user-images.githubusercontent.com/76941962/156620859-e5b41f50-e624-4236-b7d3-b1f62f6f0aaf.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
