### ISSUE TITLE
Sucuri API Key is deleted when change settings while key is hidden

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4785]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If we hide Sucuri API key using a filter then we change WPR settings, the API key will be deleted

**To Reproduce**
1. Enable Sucuri Addon
2. Add Sucuri API key
3. in wp-config.log add `define( 'WP_ROCKET_SUCURI_API_KEY_HIDDEN', true );` 
4. clear cache => Sucuri API key is hidden
5. Do any change in WPR settings and save
6. Validation error that Sucuri is not correct (if we removed hide filter, the API key will be empty)

**Expected behavior**
Sucuri API key is kept even after changing settings

**Screenshots**

**Additional context**
Using this filter to add the key will fix the problem `define('WP_ROCKET_SUCURI_API_KEY', 'put-your-API-key-here');`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
