### ISSUE TITLE
Plugin Twenty20 Image Before-After: images not displayed when Delay JavaScript execution is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4786]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript execution is enabled, Twenty20 Image Before-After plugin images are not displayed.

**To Reproduce**
1. Install [plugin Twenty20 Image Before-After](https://wordpress.org/plugins/twenty20/) 
2. Add Twenty20 shortcode in a page
3. Enable Delay JavaScript execution
4. See Twenty20 images are not displayed

**Expected behavior**
Twenty20 Image Before-After images should be displayed when Delay JavaScript execution is enabled 

**Screenshots**
Twenty20 Image Before-After image displayed:
![Twenty20 Image Before-After image displayed](https://user-images.githubusercontent.com/1954918/156754844-c0faf887-439a-4a67-ad8e-18f98a96ca26.png)

Twenty20 Image Before-After image not displayed:
![Twenty20 Image Before-After image not displayed](https://user-images.githubusercontent.com/1954918/156754848-9b0ba57b-117b-4ed0-a4a9-6be86abd82ca.png)

**Additional context**
[Helpscout issue](https://secure.helpscout.net/conversation/1804574392/329385/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
