### ISSUE TITLE
Plugin US MAP colors not displayed when Delay JavaScript execution is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4787]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

US MAP Colors are not displayed when Delay JavaScript execution is enabled

**To Reproduce**

1. Install [Plugin US MAP](https://www.wpmapplugins.com/)
2. Add [us_map] shortcode on a page
3. Visit the page and see that colors on the map are not displayed

**Expected behavior**

US MAP Colors should be displayed when Delay JavaScript execution is enabled

**Screenshots**

US MAP colors not displayed with Delay JavaScript execution enabled:
![US MAP not working](https://user-images.githubusercontent.com/1954918/156877100-10f4449c-e317-47e6-a0e6-bab1073c96cf.png)

US MAP colors are displayed with `us_config` in the Excluded JavaScript files text area, under the Delay JavaScript execution feature:
![US MAP working](https://user-images.githubusercontent.com/1954918/156877097-880d8199-4c94-44a9-ad74-5412df6ee80c.png)

**Additional context**

- [Helpscout issue](https://secure.helpscout.net/conversation/1806479166/329764/)
- Elementor Pro is installed
- Replicate with and without elementor to see if this issue is related to elementor PRO
- Adding `us_config` in the Excluded JavaScript files text area, under the Delay JavaScript execution feature fixes the issue

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the issue :heavy_multiplication_x:
The plugin is not free and the free version doesn't have the problem. It is impossible for me to reproduce the issue.
## Scope a solution :white_check_mark:
As us_config is a name that is quite generic, I propose  to create a Thirdparty class for USMap that check in  `get_subscribed_events` check if the plugin is active and add:
`$events['rocket_delay_js_exclusions'] = 'exclude_from_delay_js';`
```PHP
public function exclude_from_delay_js( array $exclusions = [] ) {
	$exclusions[] = 'us_config';
	return $exclusions;
}
```
## Estimate effort :white_check_mark:
Effort `S`

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
