### ISSUE TITLE
In the new version, css requests are increased.

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4788]
**Describe the bug**

Before updating to 3.10.9, the number of css requests on my website was 2. But after the update, it increased to 10 requests. I tested this on 3 other websites and this increase in css request occurred.

Doesn't that seem unusual?

**Comment by piotrbak** [comment]
Hello @79ho3ein in 3.10.9 we excluded very few Elementor CSS files from combination, you can see it here:
https://github.com/wp-media/wp-rocket/pull/4760

If that's not related, please contact our Support Team for help and further investigation
