### ISSUE TITLE
Feeds caching isn't working

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4789]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔ `3.10.9`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Caching the feeds isn't working at the moment for two reasons:
1. The [WP Rocket Cache Feed](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-feed) helper plugin had the wrong feed URI pattern (latest change on [Sep 4, 2020](https://github.com/wp-media/wp-rocket-helpers/commit/03cbf5834f47e7428a6572f0801f707bbd39b9d0)). 
In the meantime, we changed the pattern to fix #2852. I've updated the helper plugin to match this.
2. Even with the fixed helper, caching won't take place because of the check for a `</html>` here:
https://github.com/wp-media/wp-rocket/blob/d7c3f04dc217b2c98f5cd16a9da119406c68c517/inc/classes/Buffer/class-tests.php#L355-L365

**To Reproduce**

1. Install the updated WP Rocket Cache Feed helper plugin.
2. Visit the URL of the feed.
4. Check the cache folder for the feed folder. It won't be there.

**Expected behavior**

Feeds caching should work when the respective helper is installed/activated.

**Additional context**

We can fix this by adding a new `is_feed_uri()` method in `WP_Rocket\Buffer\Tests`:
```PHP
function is_feed_uri(){
		global $wp_rewrite;
		$feed_uri = '/(?:.+/)?' . $wp_rewrite->feed_base . '(?:/(?:.+/?)?)?$';
		return (bool) preg_match( '#^(' . $feed_uri . ')$#i', $this->get_clean_request_uri() );
}
```

and use it when checking for the `</html>` element like this:
```PHP
if (
			$this->has_test( 'is_html' )
			&&
			! $this->is_html( $buffer )
			&&
			! defined( 'REST_REQUEST' )
			&&
			! $this->is_feed_uri()
		) {
			// Don't process if there isn't a closing </html>.
			$this->set_error( 'No closing </html> was found.' );
			return false;
		}
```
@piotrbak Maybe this should be tackled in the same release with #4133.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Unfortunately we can't use the global because at that point it's not defined yet

**Comment by vmanthos** [comment]
@Tabrisrp I've tested this on my local site and I got the following:
```PHP
[ 2022-03-28 05:14:08 ] /(?:.+/)?feed(?:/(?:.+/?)?)?$
```

when I logged the value of `$feed_uri`:
```PHP
error_log( date('[ Y-m-d H:i:s ] ', $_SERVER['REQUEST_TIME'] ) ."$feed_uri\n", 3, dirname( __FILE__ ) . "/my_log.log" );
```

**Comment by CrochetFeve0251** [comment]
## Scope a solution :white_check_mark:
After checking the global variable is effectively present at this level of the code and is usable as it returns the right value.
However we can improve the solution readability by changing a bit the code proposed by @vmanthos.

An RSS file doesn't have to pass an `is_html` test and this could be confusing for the developer.

That why I propose this solution:
Add a new method `is_feed_uri` on the `WP_Rocket\Buffer\Tests` class that check  if the page is a feed using its uri.
```php
function is_feed_uri(){
		global $wp_rewrite;
		$feed_uri = '/(?:.+/)?' . $wp_rewrite->feed_base . '(?:/(?:.+/?)?)?$';
		return (bool) preg_match( '#^(' . $feed_uri . ')$#i', $this->get_clean_request_uri() );
}
```

In the method  `can_process_buffer` call the method `is_feed_uri`  and check if the constant `REST_REQUEST` is defined to decide if we need to run the test `is_html` on the page.
```php
$this->tests['is_html'] = ! $this->is_feed_uri() && ! defined( 'REST_REQUEST' );
```
In the condition remove the check from the constant `REST_REQUEST`:
https://github.com/wp-media/wp-rocket/blob/d7c3f04dc217b2c98f5cd16a9da119406c68c517/inc/classes/Buffer/class-tests.php#L360-L360
## Effort [XS]
