### ISSUE TITLE
External relative URL image inside minified external CSS file is not displayed on page

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4791]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.9
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enable minify CSS while having an image with relative URL inside external CSS, the image is not displayed on the page

**To Reproduce**
Precondition:
- Having page template using external CSS which contains relative URL image
- Enable Minify CSS

1. Open the page incognito 
2. Image is not displayed

**Expected behavior**
Image is normally displayed 

**Additional context**
- Sample test page https://new.rocketlabsqa.ovh/minifycss_relativeurl/
- As per team discussion, after modification, the image URL request is using site domain instead of the external domain i.e `https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/testing1.png` instead of `https://rocketlabsqa.ovh/wp-content/rocket-test-data/images/testing1.png` in our test page
- it needs to be tested on minify js if possible

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
