### ISSUE TITLE
Remove unused javascript programmatically

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4797]
**Is your feature request related to a problem? Please describe.**
Similar to remove unused CSS removing unused code, this would remove unused javascript code. Some javascript files cannot be delayed without breaking functionality, but those files still have a bunch of unused code in them, which slows the page down by adding unnecessary extra weight, as well as longer javascript execution time.

**Describe the solution you'd like**
Remove unused javascript code from inline javascript as well as javascript js files programmatically.

**Describe alternatives you've considered**
I've searched for an automated way to remove unused javascript code, I have been completely unable to find an optimization plugin that does this. As far as I know, there isn't an alternative available.

**Comment by GeekPress** [comment]
Hi @jazir5 

Thanks for your suggestion.

If you didn't find any solutions to do this, it's not a surprise.

Why?
Remove Unused JavaScript automatically isn't something that can be done without breaking your website and being accurate. It's totally different than the CSS where we can guarantee to work most of the time.

This is why we decided to fix that problem by delaying JavaScript execution. We plan to totally revamp the UI of this feature to make it easier to use.
