### ISSUE TITLE
When Remove Unused CSS is activated, the database table size created by remove unused css is very large(8+ GB)

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4798]
**Describe the bug**
Remove unused css causes a massive database table to be created. The size of this table is interfering with the backup process for one of our sites due to the backup process timing out. This even happens on server level backups on AWS sometimes, its not just plugin based backups. It also costs us more money in S3 storage.

**To Reproduce**
1. Activate remove unused CSS on a large site
2. Wait for unused CSS to finish processing
3. Check database table that remove unused css creates
4. The database table size should be gigantic.

**Expected behavior**
A much smaller database table size that is not in the gigabytes, or that is in the very low gigabytes.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@jazir5 We already have two separate issues related to this topic:
1. https://github.com/wp-media/wp-rocket/issues/4802
2. https://github.com/wp-media/wp-rocket/issues/4161

The second one will be fixed very soon, for the first one we're considering the possible solutions.
