### ISSUE TITLE
Page-specific settings aren't being duplicated by WPML Advanced Editor

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#4801]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The page-specific settings aren't duplicated. According to WPML support :

> This bug is happening because of a compatibility conflict with WP Rocket. We are getting the expected after adding the following code in functions.php of the theme and updating the page & its translations. After that *Never cache this page* option is synced to secondary language. Please try it after a site backup and let us know your feedback. We will update the WP Rocket team shortly about this.

**To Reproduce**
1) Create a Page X with some dummy content
2) Define page-specific settings on the Page X like "Never cache this page" for instance
3) Translate the page with Advanced Editor

**Expected behavior**
WPML's Advanced Editor should be able to also duplicate the page-specific settings.

**Screenshots**
N/A

**Additional context**
(https://wpml.org/forums/topic/page-specific-settings-arent-being-duplicated-by-wpml-advanced-editor/)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by JerissCloudCenter** [comment]
https://wpml.org/forums/topic/page-specific-settings-arent-being-duplicated-by-wpml-advanced-editor/#post-10718373

Please have a look at this code, it's been provided by WPML themselves and it solves the issue.
Can you fix this in your plugin? Thanks

```
function wpml_rocket_save_metabox_options() {
    if (current_user_can('rocket_manage_options') &&
        isset($_POST['post_ID'], $_POST['rocket_post_exclude_hidden'], $_POST['_rocketnonce'])) {
 
        check_admin_referer('rocket_box_option', '_rocketnonce');
 
        // No cache field.
        if (isset($_POST['post_status']) && 'publish' === $_POST['post_status']) {
            $new_cache_reject_uri = $cache_reject_uri = get_rocket_option('cache_reject_uri');
            $rejected_uris = array_flip($cache_reject_uri);
            $translations = apply_filters('wpml_get_element_translations', null, apply_filters('wpml_element_trid', NULL, $_POST['post_ID'], 'post_' . get_post_type(get_post($_POST['post_ID']))));
            if (!empty($translations)) {
                foreach ($translations as $translation) {
                    if ($translation->element_id != $_POST['post_ID']) {
                        $path = rocket_clean_exclude_file(get_permalink($translation->element_id));
 
                        if (isset($_POST['rocket_post_nocache'])) {
                            if (!isset($rejected_uris[$path])) {
                                array_push($new_cache_reject_uri, $path);
                            }
                        } else {
                            if (isset($rejected_uris[$path])) {
                                unset($new_cache_reject_uri[$rejected_uris[$path]]);
                            }
                        }
                    }
                }
                 
                if ($new_cache_reject_uri !== $cache_reject_uri) {
                    // Update the "Never cache the following pages" option.
                    update_rocket_option('cache_reject_uri', $new_cache_reject_uri);
                    // Update config file.
                    rocket_generate_config_file();
                }
            }
        }
    }
}
 
add_action('save_post', 'wpml_rocket_save_metabox_options', 99);
```

**Comment by jbroeker-etron** [comment]
We have a similar issue: When duplicating a page with WPML to another/secondary language, WP Rocket's page-specific settings are not duplicated/applied to the duplicated page.

Steps to reproduce the behavior:
1. Create a Page X with some dummy content
2. Duplicate Page to secondary language
3. Define page-specific settings on the Page X like disabling "Remove Unused CSS" for instance
4. Settings are not applied to duplicated page (secondary language)

The fix above does not seem to fix the problem.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on WPML compatibility

**Comment by JerissCloudCenter** [comment]
Seriously? The code is ready, already providee to you. You only need to test it and paste it in your plugin...

**Comment by piotrbak** [comment]
@JerissCloudCenter Yes, we need to check the code, add it to the codebase, test it with different WPML use cases. We'll get back to it, no worries. It's just more optimal to take care of it while implementing different issues related to WPML, so we're focused on one topic at the same time. Thanks for understanding.

**Comment by webtrainingwheels** [comment]
Another case: https://secure.helpscout.net/conversation/3010427141/575400?viewId=377611
