### ISSUE TITLE
Adding missing image dimensions for SVG is excluded in FR docs but not in EN

### ISSUE THREAD

**Issue by Klemart3D** [wp-media/wp-rocket#4803]
Who's right? Why documentations are not updated together?

![fr](https://user-images.githubusercontent.com/7419525/157683405-235a55c3-b6c3-4f25-ab81-0fd789ed30a9.jpg)

![en](https://user-images.githubusercontent.com/7419525/157683399-85f0eca4-bb4a-44aa-ab93-a677be23b862.jpg)

Sources:
- FR: https://fr.docs.wp-rocket.me/article/1369-ajouter-les-dimensions-dimage-manquantes
- EN: https://docs.wp-rocket.me/article/1366-add-missing-image-dimensions

**Comment by piotrbak** [comment]
Thank you @Klemart3D
