### ISSUE TITLE
Apply CDN rewrite in CSS files without requiring minification

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4806]
Currently we apply the CDN rewrite on assets within CSS files (e.g. background images) only when CSS minification is enabled. 

Ideally the CDN shouldn't depend on this and could be applied whether or not there is minification.

For example, we recently [excluded some specific Elementor files from minification](https://github.com/wp-media/wp-rocket/pull/4760), so some customers will be directly affected by that and assets will no longer be served from the CDN.

Example: https://secure.helpscout.net/conversation/1809674817/330338?folderId=377611

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/1920225480/348464?folderId=2675957

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
