### ISSUE TITLE
Display a warning when WooCommerce Pixel Manager plugin is detected.

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4812]
[WooCommerce Pixel Manager plugin](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/) is excluding several scripts from a lot of WP Rocket's features: https://i.vgy.me/9YvC4M.jpg

It's all of these:
```
optimize.js
googleoptimize.com/optimize.js
jQuery
jQuery.min.js
jquery.js
jquery.min.js
wpm
wpm-js
wpmDataLayer
window.wpmDataLayer
wpm.js
wpm.min.js
wpm__premium_only.js
wpm__premium_only.min.js
wpm-public.p1.min.js
wpm-public__premium_only.p1.min.js
polyfill-io
polyfill.min.js
window.dataLayer
gtag
gtm.js
fbq
fbevents.js
twq
static.ads-twitter.com/uwt.js
platform.twitter.com/widgets.js
uetq
ttq
events.js
snaptr
scevent.min.js
```

**Describe the solution you'd like**
Displaying a warning box in File optimization tab when this plugin is detected telling to the user that some of their JS files might be excluded from our optimization due to this plugin.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1647005941154889

**Comment by alewolf** [comment]
Hi 

I'm the author of the WooCommerce Pixel Manager. 
All those file exclusions have been removed in the newest versions of the WooCommerce Pixel Manager. 

Regards
Aleksandar
