### ISSUE TITLE
Taxonomies cache are not cleared when Cloudflare Cache Everything is activated via page rules

### ISSUE THREAD

**Issue by dreamjobma** [wp-media/wp-rocket#4814]
**Before submitting an issue please check that you’ve completed the following steps:**
- Yes
- Yes

**Describe the bug**
Taxonomies cache are not cleared when Cloudflare Cache Everything is used via page rules. Homepage cache is cleared and article cache is cleared

**To Reproduce**
1. Activate cloudflare cache everything
2. Update article
3. Article and homepage cache are cleared
4. Related taxonomies cache are not cleared

**Expected behavior**
Related taxonomies cache should be cleared

**Screenshots**

**Additional context**
Using cloudflare cache everything with page rules with 200 USD cloudflare plan and bypass cache on cookies.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by sarangsss29** [comment]
Same here. Any update on this WP-Rocket team?
Edit: Also, the sidebar and footer.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1889582751/343834?folderId=3864740

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1967812788/359694?folderId=3864740

**Comment by dreamjobma** [comment]
Hello, any update on this? Thanks.

**Comment by Plinpod** [comment]
Any progress here?

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on Cloudflare
