### ISSUE TITLE
UI: Change "Note: None of these options will be applied..." in WP Rocket Rocket Options Metabox

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#4815]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
In Posts/Pages WP Rocket Rocket Options Metabox, the Note under options is:
> Note: None of these options will be applied if this post has been excluded from cache in the global cache settings.

But these options won't be applied even if this post/page has been excluded from cache in these settings, by ticking "Never cache this page" option. This can be confusing for users.

**Expected behavior**
We could replace it by:
> Note: None of these options will be applied if this post/page has been excluded from cache in the global cache settings **or here above**.

**We could even grey out and deactivate all options** when the "Never Cache this page" option has been ticked, to be more clear on how it works.

**Screenshots**

- [screenshot of how it works now](https://jmp.sh/gGNalTK)
- [screenshot of how it could be more clear](https://jmp.sh/OopjHfq)

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1815407169/331504?folderId=1213662

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
