### ISSUE TITLE
Improve regex cleaning HTML before processing images lazyload

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4816]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.9`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In the presence of a faulty closing `</script>`, for example `</script-->`, the regex that cleans up HTML before looking for images might prevent processing a good portion of the content. 

​​https://github.com/wp-media/wp-rocket/blob/d7c3f04dc217b2c98f5cd16a9da119406c68c517/inc/Dependencies/RocketLazyload/Image.php#L26
​
Example: 

If the following code is present on the page: 

`​​<script src="/path/to/file-1.js"></script-->`
​
​The faulty ending `</script-->` will force the regex `/<script\b(?:[^>]*)>(?:.+)?<\/script>/Umsi` to look for the next `</script>` closing tag and remove most of the content on the page.

```
​<script src="/path/to/file-1.js"></script-->
<img src="/path/to/img-1.jpg" />
<img src="/path/to/img-2.jpg" />
<img src="/path/to/img-3.jpg" />
​<script src="/path/to/file-2.js"></script>
```

As a result, lazyload for images won't be working since it couldn't find any images to process. 

Updating the regex to `/<script\b(?:[^>]*)>(?:.+)?<\/script\b(?:[^>]*)>/Umsi` should fix the issue.

**To Reproduce**
1. Go to add a faulty closing script tag on the top of a document + some images between the faulty closing tag and the next script tag.
2. Enable lazyload for images
3. See that any images between the closing faulty script tag and the next script tag won't be lazyloaded

**Expected behavior**
N/A

**Screenshots**

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1816030364/331601/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
