### ISSUE TITLE
Compatibility with Animate plugin (defer exclusion)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4818]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.9`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the [Animate plugin](https://en-gb.wordpress.org/plugins/animate/) is used with Defer JavaScript, the following console error show up: 

```
ReferenceError: WOW is not defined
    at <anonymous>:3:17
    at t.activateScript (https://oxygen.adame.io/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:11855)
    at https://oxygen.adame.io/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:11052
    at t.run (https://oxygen.adame.io/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:11259)
    at https://oxygen.adame.io/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:2907
    at https://oxygen.adame.io/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:8117
```

Excluding the following from JavaScript defer fixes the issue: 

```
/wp-content/plugins/animate/js/app.js
```

**To Reproduce**
1. Install the Animate plugin
2. Activate JS Defer
3. See error

**Expected behavior**
The Animate plugin should work out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1816109959/331633?folderId=3864735
The plugin itself is very old and has very low installs. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
@piotrbak Plugin with 800 installs and not updated since 6 years, maybe we don't need an automatic compatibility for it?

**Comment by piotrbak** [comment]
@Tabrisrp You are totally right, sorry for that.

@DahmaniAdame Closing it since the plugin is not maintained anymore.
