### ISSUE TITLE
Compatibility with Bookly (conditional defer + delay exclusions)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4819]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.9`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the [Bookly plugin](https://www.booking-wp-plugin.com/) is used with Defer JavaScript and `jQuery` is already differed, the following console error show up: 

```
Uncaught ReferenceError: Hammer is not defined
    at jquery.hammer.min.js?ver=20.4:7:25
    at jquery.hammer.min.js?ver=20.4:9:2
```

Excluding the following from JavaScript defer fixes the issue: 

```
/bookly-responsive-appointment-booking-tool/frontend/resources/js/hammer.min.js
```

The same issue happens with Delay JavaScript Execution. 

It requires excluding the same file as well.

**To Reproduce**
1. Install Bookly plugin
2. Activate JS Defer and exclude `jQuery` (same test with Delay JavaScript Execution)
3. See error

**Expected behavior**
The Animate plugin should work out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1816109959/331633?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
I was about to create a GitHub issue for the same plugin.

On the customer's website that I worked on when `jQuery` was delayed, the following had to be excluded from Delay JavaScript Execution for the Bookly form to work:
```HTML
/bookly-responsive-appointment-booking-tool/frontend/resources/js/bookly.min.js
/bookly-responsive-appointment-booking-tool/frontend/resources/js/intlTelInput.min.js
/bookly-responsive-appointment-booking-tool/frontend/resources/js/picker.js
/bookly-responsive-appointment-booking-tool/frontend/resources/js/picker.date.js
window.bookly
```

I didn't have to exclude the `hammer.min.js` file.
On my own test site, excluding just this 👆fixed the console error though.

@piotrbak This is one of the cases where the feature works fine when `jQuery` is not excluded from Delay JS but requires exclusions when it is.

**Ticket:** https://secure.helpscout.net/conversation/1812053732/330797/
