### ISSUE TITLE
Page Caching is disabled on pages where a Bookly form is used

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4820]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When:
1. [WordPress Online Booking and Scheduling Plugin – Bookly](https://wordpress.org/plugins/bookly-responsive-appointment-booking-tool/) is installed.
2. One of their forms is added to a page.

page caching and optimizations are not applied there. They do this by setting the `DONOTCACHEPAGE` to `true`.

This is handled by an option to disable caching on pages that include their forms (Bookly > Settings > Prevent caching of pages with booking form).

![](https://i.vgy.me/4Y2KGW.jpg)

**To Reproduce**
1. Install the plugin.
3. Add a form to a page.
4. Visit the page and check for WP Rocket's caching/optimizations.

**Expected behavior**

Page caching/optimizations can/should be applied to Bookly-related pages.

**Additional context**

We can display a notice when the plugin is detected to ask our common customers to change the culprit setting.
There is already a doc where we can link to, and which includes the necessary info:
https://docs.wp-rocket.me/article/99-pages-not-cached-or-minify-cssjs-not-working#donotcachepage

**Ticket:** https://secure.helpscout.net/conversation/1812053732/330797/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
