### ISSUE TITLE
Owl Carousel lazy load compatibility (Firefox only)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4829]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.9`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Owl Carousel is used with Lazyload on Firefox, the carousel will stop working properly. 

![image](https://user-images.githubusercontent.com/1289174/159111680-06d3f280-820c-40da-9e97-6f2f60aae2fa.png)

No other feature is used. Just enabling WP Rocket and the lazyload feature. And it happens only on Firefox. 

**To Reproduce**
1. Add an owl carousel 
2. Enable lazy load
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1816029346/331600/

Firefox renders the `<noscript>` images on the code vs. Chrome does. 

To exclude this as a potential cause, I tested by dissociating the `<noscript>` images from the main images by manipulating the buffer. 

The outcome is still the same. The carousel doesn't work properly. 

It's likely a conflict between the JS to switch the image from the lazyload state and owl carousel building its carousel.

Sample carousel: 

```
<div class="owl-carousel">
<img src="https://dummyimage.com/300x300/000/fff" alt="">
<img src="https://dummyimage.com/300x300/000/fff" alt="">
<img src="https://dummyimage.com/300x300/000/fff" alt="">
<img src="https://dummyimage.com/300x300/000/fff" alt="">
<img src="https://dummyimage.com/300x300/000/fff" alt="">
<img src="https://dummyimage.com/300x300/000/fff" alt="">
</div>
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by butchero** [comment]
I have the same problem! WP-Rocket Lazy Load + owl carousel. The problem is present only on Firefox.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
