### ISSUE TITLE
Delay JavaScript Execution compatibility with Bridge theme's Page Transition

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4831]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.9`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the Bridge theme uses the `Page Transition` feature with Delay JavaScript Execution, the following error console is generated: 

```
Uncaught SyntaxError: Identifier 'RocketLazyLoadScripts' has already been declared
    at b (jquery.min.js:2:866)
    at Function.globalEval (jquery.min.js:2:2905)
    at HTMLScriptElement.<anonymous> (ajax.min.js:1:8498)
    at Function.each (jquery.min.js:2:3003)
    at s.fn.init.each (jquery.min.js:2:1481)
    at slideInNewPage (ajax.min.js:1:8479)
    at d (ajax.min.js:1:16886)
```

The reason why it's happening is that the Page Transition feature loads the new page using Ajax.

![image](https://user-images.githubusercontent.com/1289174/159121156-9c6d635e-6c17-4bd8-bd74-a8c1c34486a0.png)

The browser seems to keep a record that `RocketLazyLoadScripts` was previously declared and will generate the error on the console. 

**To Reproduce**
1. Enable the Page Transition feature
2. Enable Delay JavaScript Execution
3. See error

**Expected behavior**
The `Page Transition` feature on the `Bridge theme` shouldn't generate any console errors. 

**Screenshots**
Page transition setting: 

![image](https://user-images.githubusercontent.com/1289174/159120925-8a856203-7af5-410e-939f-3dcea40da269.png)

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1813590467/331079

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Was it possible to resolve this problem with any exclusion?

**Comment by DahmaniAdame** [comment]
@piotrbak unfortunately, no. As long as the page is loaded using AJAX, regardless of the exclusions used, it will still show the error. 

It will add the second `class` `RocketLazyLoadScripts`, and the browser will consider it as a duplicate of the previously declared class. 

Maybe we could safeguard the script using: 

```
if (typeof RocketLazyLoadScripts !== 'function') { class RocketLazyLoadScripts ... }
```

The previous declaration should still be able to handle the Delay JavaScript Execution mechanics. But it will need to be tested though.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
