### ISSUE TITLE
Delay JavaScript Execution Option to delay only certain scripts

### ISSUE THREAD

**Issue by PaulSchiretz** [wp-media/wp-rocket#4832]
**Before submitting an issue please check that you’ve completed the following steps:**

Made sure you’re on the latest version ✅
Used the search feature to ensure that the bug hasn’t been reported before ✅

**Description**

Hi there,

I got a short feature request.

Wouldn't it be more practical to offer a feature to delay only certain scripts, that acts like it was before you changed it to delay all and than exclude certain scripts?

Like perfmatters has it? Maybe a simple setting to choose from like:

**Expected behavior**

Delay behavior
There are two different methods you can choose from to delay JavaScript execution:
- Only delay specified 
- Delay all scripts

Delay all basically works like it is now, delay all scripts and add exclusions.

Only delay specified works like before, delay none and add inclusions

**Additional Context**
I think this would be very helpful, cause right now i find myself constantly adding scripts to the exclusion settings(i noted you also have constant requests for exclusions) i recently just moved to not use the feature at all, cause i don't want to hassle everytime i add something.... but for some scripts i know it's fine so i still want to be able to defer them, thats where this option would be handy. I'm sure you discussed this internally but i just wanted to add my 2 cents as a quite frequent user.... Any thoughts?

All the best,
Paul

**Comment by GeekPress** [comment]
Hi,

We won't change our minds about how our Delay JS feature is working. We plan to revamp the UI to make it easier to use.
