### ISSUE TITLE
Cloudflare optimal settings compatibility with FacetWP

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4837]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (N/A)
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
FacetWP uses an HTML comment as part of its functionality `<!--fwp-loop-->`. 

When the Cloudflare add-on is activated with the `HTML Auto Minify` option, the comment will be deleted causing one of the main FacetWP main functionalities to fail. 

[Reference from the FacetWP documentation](https://facetwp.com/help-center/using-facetwp-with/cloudflare/)

**To Reproduce**
1. Go to use FacetWP
2. Enable `Optimal Settings` on our Cloudflare add-on
3. See the `<!--fwp-loop-->` removed

**Expected behavior**
FacetWP must work properly when using the Cloudflare add-on with the `Optimal Settings` sub-option.

We shouldn't set the `HTML Auto Minify` when setting the `Optimal Settings` if FacetWP is active on the website.

**Screenshots**
N/A

**Additional context**
Discovered randomly - no current case tied to this issue.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
