### ISSUE TITLE
Defer JS - Inline JS excluded from defer if non-matched pattern in use

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4841]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

 Inline JS excluded from defer if non-matched pattern in exclude list

**To Reproduce**
1. Install rocket and enable Load JavaScript deferred

Exclude list:
```
x/wp-includes/js/jquery/jquery.min.js
x/wp-includes/js/jquery/jquery-migrate.min.js
```
Demo code added by a plugin: https://snippi.com/s/dfb4kjj

After adding above exclusion list that inline js auto excluded from defer although it's a wrong pattern as i used **`x/`** , this is not expected, for making sure it's a bug, i added same exclusion to "Delay JS", but it's not excluded from delay.

**Expected behavior**
This inline JS shouldn't be excluded from defer

**Screenshots**
N/A

**Additional context**
Inline JS excluded because it's matched with  `jquery/jquery.min.js` **jquery** here, but it shouldn't be matched like "Delay JS"

> Why this is important?
Because every user need to test keyword/path, now removing/adding everytime it's not ideal, so i prefer to keep it invalid 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
