### ISSUE TITLE
WP-CLI cron empty Error

### ISSUE THREAD

**Issue by Rahe** [wp-media/wp-rocket#4845]
**Describe the bug**
Hello,

There is a weird bug that doesn't occurs everytime but is generating errors on our website, but this was hard to see what's plugin was doing this.
The cron event "rocket_partial_preload_cron" is generating errors on WP-CLI and stop the exection when launching throught the cron event task.

We have this error on single site and multisite.

```
Error: 
``` 
No errors displayed, nothing on php logs, nothing into the console, just the process stops here.

**To Reproduce**
Add into the crontab a script like this for multisite :

```bash
for url in $(wp site list --field=url --url="mulsiitei URL");
do
  # Add The current site to the process message
  m="$m $url
  "

  # Get all the events
  for hook in $(wp cron event list --next_run_relative=now --fields=hook --format=ids --url=${url});
  do
    m="$m $hook
    "
    m="$m $(wp cron event run --no-color "$hook" --url=${url} 2>&1 )
    "
    return=$?;
    if [ $return -gt 0 ]
      then
        echo $m;
        exit;
    fi
  done
done
```

**Expected behavior**
To not bug with just and "Error:" and nothing after this.

**Screenshots**
No screenshot, but the actions log 
```
2022-03-23T01:10:01+01:00
     https://site2.fr
   cerber_bg_launcher
     Executed the cron event 'cerber_bg_launcher' in 0.013s.
Success: Executed a total of 1 cron event.
     facetwp_indexer_cron
     Executed the cron event 'facetwp_indexer_cron' in 0.01s.
Success: Executed a total of 1 cron event.
     action_scheduler_run_queue
     Executed the cron event 'action_scheduler_run_queue' in 0.014s.
Success: Executed a total of 1 cron event.
     beapi_missed_scheduled_event
     Executed the cron event 'beapi_missed_scheduled_event' in 0.017s.
Success: Executed a total of 1 cron event.
     rocket_partial_preload_cron
     Error: 
```

**Comment by pluspol** [comment]
We experience the same issue and dug into the code.
The error seems to come from this file:
https://github.com/wp-media/wp-rocket/blob/develop/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php

The cron call `handle_cron_healthcheck()` passes some code (in the same file) which may result in `wp_die()` or `exit()` being called.
Therefore the cron exits prematurely and an unknown error is thrown.

It may also prevent later cron events from being run.

Therefore it may not only be a nuissance but could have other impacts.

**Comment by Mahjouba91** [comment]
Hello, I have the same bug in a multisite installation, I actually use the same piece of code that @Rahe shared.

After digging a bit, the only cron event that throws an empty error is that one for me: `rocket_rucss_warmup_scanner_cron` I'm not sure if it happens for other ones as well

**Comment by piotrbak** [comment]
@Mahjouba91 @pluspol @Rahe We changed the way how the Preload/RUCSS feature work in the 3.12 version of WP Rocket.

Please let us know if you're still experiencing this problem after the update.

**Comment by pluspol** [comment]
@piotrbak Thanks for the update. I can confirm that the empty error messages no longer occur.

**Comment by piotrbak** [comment]
@pluspol Thank you for the feedback. I'm going to close the issue, if someone still experiences it, feel free to reopen.

**Comment by Rahe** [comment]
It seems that this is not bugging anymore, thank you :)
