### ISSUE TITLE
rocket_minify_process regex bug

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#485]
in `$buffer = preg_replace( '/<head(.*)>/', '<head$1>' . $google_fonts . $css . $js, $buffer, 1 );` you need to use the U (ungreedy) flag. Debugging a page that was injecting google fonts into a script tag shows that the U processes it correctly.

**Comment by Tabrisrp** [comment]
Thanks for the feedback!

I will modify that for the next minor version, we indeed have seen this issue reported by customers before.
