### ISSUE TITLE
Delay JS - TuneFindForFans script exclusion

### ISSUE THREAD

**Issue by Alex43515** [wp-media/wp-rocket#4851]
**Before submitting an issue please check that you’ve completed the following steps:**

- [ ]  Made sure you’re on the latest version: 3.10.8
- [ ] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the Delay JavaScript Execution feature is on and the TuneFindForFans script is added to the site the player and ads are not showing up on the page:

https://i.imgur.com/PQuM9du.png

After adding the following script to the exclusion the ads and the player are showing up: 

`apricots.js`

**To Reproduce**
1. Add the following script to the page: 

`<script>
/* TFP - lyricsfa */
cf_page_artist = document.head.querySelector('[property="cf:artist"]').content;
cf_page_song = document.head.querySelector('[property="cf:song"]').content;
cf_page_genre = document.head.querySelector('[property="cf:genre"]').content;
cf_adunit_id = "100001747";
</script> <script src="//srv.tunefindforfans.com/fruits/apricots.js"></script>`

3. Enable Delay JS
4. Navigate to the page
5. See that the ads and player are not showing up

**Expected behavior**
Ads and player to show up

**Screenshots**
https://imgur.com/caXmkoJ

**Comment by htl-james** [comment]
That's because this script uses document.write.  If you want to delay it, you should put it in an iframe.  It's designed to be inserted by an adserver like Google Ad Manager.  This isn't necessarily an issue with wp-rocket, the script isn't designed to be loaded asynchronously.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
