### ISSUE TITLE
[3.11] Fatal error due to incorrect `woocommerce/action-scheduler` installation

### ISSUE THREAD

**Issue by codepuncher** [wp-media/wp-rocket#4859]
**Before submitting an issue please check that you’ve completed the following steps:**
- ~~Made sure you’re on the latest version~~
- ~~Used the search feature to ensure that the bug hasn’t been reported before~~

**Describe the bug**
Installation of v3.11 requires `woocommerce/action-scheduler` as a dependency in [`composer.json`](https://github.com/wp-media/wp-rocket/blob/develop/composer.json#L44).
WP Rocket loads this dependency with a hardcoded path, expecting it to be bundled into the plugin itself.
https://github.com/wp-media/wp-rocket/blob/v3.11/inc/main.php#L26
Since the `action-scheduler` [package type](https://github.com/woocommerce/action-scheduler/blob/trunk/composer.json#L5) is a `wordpress-plugin` it will mean for most sites configured with Composer the package will be installed to the plugins directory instead.
As a result, WP Rocket is using `require_once` on a non-existent file.

**To Reproduce**
1. Install WP Rocket v3.11 in a Composer-based environment
	1. `composer require wp-media/wp-rocket:3.11`
	2. This also happens when downloading the latest release asset from GitHub
3. Activate the WP Rocket plugin

**Expected behavior**
To not throw a fatal PHP error.

**Log entry**
```log
PHP Fatal error:  require_once(): Failed opening required '/path/to/site/plugins/wp-rocket/vendor/woocommerce/action-scheduler/action-scheduler.php' (include_path='.:/usr/local/Cellar/php@7.4/7.4.28_1/share/php@7.4/pear') in /path/to/site/plugins/wp-rocket/inc/main.php on line 26
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/wp-cli/2.6.0/bin/wp:0
PHP   2. include() /usr/local/Cellar/wp-cli/2.6.0/bin/wp:4
PHP   3. include() phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/php/boot-phar.php:11
PHP   4. WP_CLI\bootstrap() phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process($state = class WP_CLI\Bootstrap\BootstrapState { private $state = ['context_manager' => class WP_CLI\ContextManager { ... }] }) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:78
PHP   6. WP_CLI\Runner->start() phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:28
PHP   7. WP_CLI\Runner->run_command_and_exit($help_exit_warning = *uninitialized*) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1237
PHP   8. WP_CLI\Runner->run_command($args = [0 => 'plugin', 1 => 'activate', 2 => 'wp-rocket'], $assoc_args = [], $options = *uninitialized*) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:440
PHP   9. WP_CLI\Dispatcher\Subcommand->invoke($args = [0 => 'wp-rocket'], $assoc_args = [], $extra_args = []) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:417
PHP  10. call_user_func:{phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491}($function_name = class Closure { public $static = ['callable' => [...]]; public $parameter = ['$args' => '<required>', '$assoc_args' => '<required>'] }, ...$parameters = variadic([])) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
PHP  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure:phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:97-104}($args = [0 => 'wp-rocket'], $assoc_args = []) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
PHP  12. call_user_func:{phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100}($function_name = [0 => class Plugin_Command { protected $item_type = 'plugin'; protected $upgrade_refresh = 'wp_update_plugins'; protected $upgrade_transient = 'update_plugins'; protected $obj_fields = [...]; protected $fetcher = class WP_CLI\Fetchers\Plugin { ... }; protected $chained_command = FALSE; private ${WP_CLI\CommandWithUpgrade}map = [...] }, 1 => 'activate'], ...$parameters = variadic([])) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100
PHP  13. Plugin_Command->activate($args = [0 => 'wp-rocket'], $assoc_args = []) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100
PHP  14. activate_plugin($plugin = 'wp-rocket/wp-rocket.php', $redirect = '', $network_wide = NULL, $silent = *uninitialized*) phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php:333
PHP  15. plugin_sandbox_scrape($plugin = 'wp-rocket/wp-rocket.php') /path/to/site/wp-admin/includes/plugin.php:659
PHP  16. include_once() /path/to/site/wp-admin/includes/plugin.php:2288
PHP  17. require() /path/to/site/plugins/wp-rocket/wp-rocket.php:130
```

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Workaround**
https://github.com/wp-media/wp-rocket/issues/4859#issuecomment-1079046763

**Comment by tombroucke** [comment]
All my continuous deployments are also failing cause of this issue. They are running the latest versions of WooCommerce & WP Rocket. Dependencies & plugins are installed through composer (Bedrock).

**Comment by codepuncher** [comment]
Update:
I have narrowed this down to being caused by an overriding `installer-paths` property in our `composer.json`.

We are using Bedrock (as is @tombroucke), and our `composer.json` instructs all packages of `type` `wordpress-plugin` to be **moved** into `web/app/plugins/`.

As a result, `woocommerce/action-scheduler` will be moved here.

The workaround is to add another overriding installer path for the specific `woocommerce/action-scheduler` package.

```diff
-"web/app/plugins/{$name}/": ["type:wordpress-plugin"],
+"web/app/plugins/wp-rocket/vendor/{$vendor}{$name}/": ["woocommerce/action-scheduler"],
+"web/app/plugins/{$name}/": ["type:wordpress-plugin"],
```

This will ensure that the package is installed into the expected directory.
Note: the new installation path **must** be before the `type:wordpress-plugin` line.

**Comment by remyperona** [comment]
We're going to move a copy of Action Scheduler into our repository instead of depending on composer, that will avoid any pathing issue.

**Comment by codepuncher** [comment]
Great, thanks.
Is there an ETA yet for the bug fix?
