### ISSUE TITLE
Improve "Cache lifespan" setting to only delete cache entries older than set number of minutes/hours/days

### ISSUE THREAD

**Issue by foliovision** [wp-media/wp-rocket#486]
I checked how the `rocket_purge_time_event` WP cron event works and it just calls `rocket_clean_domain()`. So it purges the entire cache.

It would be great if this could be improved to only purge old cache entries. So if the "Cache lifespan would be set to 4 hours it would only clear the entries which were not regenerated in last 4 hours. So it would have to check that every 5 minutes or so.

It certainly makes more sense to me that way - why purge the entries which are frequently accessed?

Thanks,
Martin

**Comment by arunbasillal** [comment]
When we implement this, we could also consider preloading the deleted cache folder right then and there. 

A dear customer suggested: 

> It would be great if there was a progressive preload feature. where it keeps the cached pages until they are being preloaded. so i dont have to clear the whole site and then preload everything

Ticket: https://secure.helpscout.net/conversation/733566120/90520?folderId=273766
