### ISSUE TITLE
Compatibility with Fluent Forms Pro file upload (JS defer and Delay JavaScript Execution)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4865]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.9`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JavaScript Execution is used with Fluent Forms, it won't submit until the jQuery library is excluded from deferring. 

```
/wp-includes/js/jquery/jquery.min.js
```

If the form contains an upload field, the upload field won't work without producing any errors. 

Excluding the following from Delay JavaScript Execution fixed the issue: 

```
/wp-includes/js/jquery/jquery.min.js
/fluentform/public/js/(.*).js
/fluentformpro/public/js/(.*).js
```

**To Reproduce**
I couldn't reproduce it in a dev environment for both cases.

**Expected behavior**
Submission and file upload fields should work out of the box when Delay JavaScript Execution is used. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1824297900/333270/
Added to GitHub to track similar cases if any.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - [https://secure.helpscout.net/conversation/1825669355/333515/](https://secure.helpscout.net/conversation/1825669355/333515/)

Excluding jQuery fixed this one.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1828068443/333927?folderId=3864740

**Comment by girlie** [comment]
Related: https://secure.helpscout.net/conversation/1854098448/338317/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1892862162/344371?folderId=3864740

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1913831985/347319/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/1945266979/355056/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/1945266979/355056/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1948000627/355719/

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue (9 tickets in general). We might reopen this in the future.
