### ISSUE TITLE
WordPress database error / Duplicate key name 'queue_name_index'

### ISSUE THREAD

**Issue by simkoG** [wp-media/wp-rocket#4866]
**Before submitting an issue please check that you’ve completed the following steps:**
- <del>Made sure you’re on the latest version</del> ✔ v3.11.0.1
- <del>Used the search feature to ensure that the bug hasn’t been reported before</del> ✔ 0 open / 0 closed

**Describe the bug**
There are plenty of error entries that have been written in my site's LOG file about the WP-Rocket Used CSS feature. 

**Expected behavior**
No error LOG entry. 

**Additional context**
```
[28-Mar-2022 09:11:12 UTC] WordPress database error Duplicate key name 'queue_name_index' for query ALTER TABLE wp_wpr_rucss_used_css ADD INDEX 'queue_name_index' ('queue_name')  made by require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Dependencies\Database\Table->maybe_upgrade, WP_Rocket\Dependencies\Database\Table->upgrade, WP_Rocket\Dependencies\Database\Table->upgrade_to, call_user_func, WP_Rocket\Engine\Optimization\RUCSS\Database\Tables\UsedCSS->make_status_column_index
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by simkoG** [comment]
FYI: the "REMOVE UNUSED CSS (BETA)" function **is not used** on this site.

**Comment by Glifaus** [comment]
Hi! i have the same database error. The error log is plenty of this. I dont have the remove unused css(beta) but try it for a moment. 

-   Latest Version: 3.11.0.1

Here's and error example:![image](https://user-images.githubusercontent.com/34657530/160449192-bd676112-facf-41e9-8c63-17ac99bcbe6a.png)

**Comment by remyperona** [comment]
@engahmeds3ed Do you have an idea how this issue could happen, and how to replicate it? Could it be the table version not updated in the DB?

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1829860304/334208/

I requested credentials to investigate this. I'll update the thread with my findings.

**Comment by engahmeds3ed** [comment]
I tried too many scenarios but I'm not able to reproduce it.
We can guard against it by checking if the `queue_name_index` index exists before creating it and bailout if it exists.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1834647242/335224/

**Comment by MaximGavd** [comment]
try: define( 'WP_MEMORY_LIMIT', '2048M' );
