### ISSUE TITLE
Change the deactivation intent UI

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4867]
**Is your feature request related to a problem? Please describe.**
Right now we display a short poll but answers are not useful at all. Moreover, we had a discussion about the usage of mixpanel:
https://github.com/wp-media/wp-rocket/issues/1959

**Describe the solution you'd like**
We'd like to redesign the deactivation intent poll based on the following graphics:
![Popin - Snooze - 2](https://user-images.githubusercontent.com/26767037/160390023-4de422b5-dfb0-4ef5-9e2e-b8f02af56059.png)
![Popin - Safe Mode](https://user-images.githubusercontent.com/26767037/160390026-9f4d2021-3a1e-429b-9057-f237c4259060.png)
![Popin - Snooze](https://user-images.githubusercontent.com/26767037/160390029-0c7091e0-8e66-4489-b991-86ceee85ae50.png)

More detailed view can be seen here:
https://www.figma.com/file/KmIoTbM0he4XaaoRrWiko9/WP-Rocket-HP?node-id=0%3A1

**Additional context**
It'll be possible to snooze the message for specific time.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
- Move the class `classes/admin/deactivation/class-render.php` to `Engine/Admin/Deactivation/Render.php`
- Update the instantiation of the class in `Engine/Admin/ServiceProvider`

in `Engine/Admin/Deactivation/DeactivationIntent`
- Remove the mixpanel function and remove the entry in the subscribed events array
- Add a new method to enqueue the CSS/JS for the modal on the plugins page. The code needs to be extracted from https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/admin/ui/enqueue.php#L52-L56

For the snooze, we will have to use a different approach depending on the case:
- Use a transient for the 1/7/30 days, `rocket_hide_deactivation_form`
- Use an option for the `forever` choice, `wp_rocket_hide_deactivation_form`, with a value `1`

Then we can use those values in the methods adding the assets and the form to the plugins page, to check if one of them is set.

Add/Update tests corresponding to this class and methods

in `views/deactivation-intent/form.php`
- Update the HTML to correspond to the new content for the deactivation popup

in `assets/js/wpr-modal.js`
- Refactor the code to not depend on jQuery, remove all that is no longer necessary

in `src/scss/modal.css`
- update the CSS to fit with the new UI

### Estimate the effort ✅
Effort `[M]`
