### ISSUE TITLE
CDN exclusions are not reflected in Used CSS

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4868]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using CDN and RUCSS, CDN exclusions are not taken into the consideration.

**To Reproduce**
1. Enable CDN for all files
2. Enable RUCSS
3. Exclude URL from CDN (URL existing in used CSS) i.e /test.svg
4. visit the page and check used CSS

**Expected behavior**
Excluded URL not rewritten to the CNAME

**Additional**
Moving it from private repo:
https://github.com/wp-media/nodejs-treeshaker/issues/46

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Do we have a concrete example of this issue? The code to handle CDN rewrite in the used CSS didn't change in 3.11.

Was it reported before we modified the code to regenerate the used CSS after changing CDN values?

**Comment by remyperona** [comment]
### Scope a solution ✅ 
As discussed during the standup, we can modify the moment we apply CDN on the used CSS to avoid this issue, and also avoid having to clear the used CSS when changing one of the CDN options.

To do so, we need to move the `apply_filters( 'rocket_usedcss_content', $css );` from `check_job_status()` to `get_used_css_markup()`.

We also can remove the `clean_used_css_with_cdn()` method in `RUCSS/Admin/Subscriber` and the associated entry in the subscribed events.

### Estimate the effort ✅
Effort `[XS]`

**Comment by CrochetFeve0251** [comment]
@Tabrisrp While solving this issue I discovered that there are no tests for the class Optimization\RUCSS\Controller, should I create some to test that case?
