### ISSUE TITLE
Delay JS - WP Google Map Pro compatibility

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4870]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.10.9`
- Used the search feature to ensure that the bug hasn’t been reported before ✅
The plugin is a different version - "Gold", from the one in #4481.

**Describe the bug**

When:

1. A map is added using the [WP Google Map Pro](https://www.wpmapspro.com/) plugin.
2. Delay JavaScript Execution is enabled.

Google maps are not displayed.

Excluding the following fixed the issue:
```HTML
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
maps.google.com/maps/api/js
/wp-includes/js/masonry.min.js
/wp-google-map-gold/(.*)
```

**To Reproduce**

1. Install the [WP Google Map Pro](https://www.wpmapspro.com/) premium plugin.
4. Add a map to a page.
5. Activate Delay JavaScript Execution.
6. See error.

**Expected behavior**

Google Maps should be displayed when using Delay JavaScript Execution.

**Additional context**

We can use the `WPGMP_Google_Maps_Pro` class used by the plugin to create a compatibility file.

**Ticket:** https://secure.helpscout.net/conversation/1828932167/334080?folderId=273766

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
