### ISSUE TITLE
Inline script is rewritten to CNAME in certain cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4871]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.0.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using certain markup for the inline script and NoScript, the URL is written to CNAME also it shouldn't

**To Reproduce**
1. Enable CDN
2. Access the page containing the following script (make sure used image exists on your site)
```
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function(){ jQuery("#footer-info").text(' '); jQuery("<p align='center'><img src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/test.png' HEIGHT='500'/></p>").insertAfter("#footer-info"); });
// ]]></script>

<noscript type="text/javascript">// <![CDATA[
jQuery(document).ready(function(){ jQuery("#footer-info").text(' '); jQuery("<p align='center'><img src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/test.png'  /></p>").insertAfter("#footer-info"); });
// ]]></noscript>
```
3- Check page source 

**Expected behavior**
CDN is not applied to the inline script without a filter

**Screenshots**
![Screenshot from 2022-03-29 16-36-58](https://user-images.githubusercontent.com/76941962/160636727-969e436a-7ff6-4d9b-9062-b6e62be033fd.png)

**Additional context**
- Test page: https://new.rocketlabsqa.ovh/image_template_scripts/
- If the URL wasn't the same in NoScript => URL won't be written to CNAME

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
The same URL is present in a regular image in this template HTML. When we rewrite to the CDN, we rewrite all occurrences of the matched URL in the HTML, wherever it is (because an URL could be repeated multiple times for some reasons).

So this is expected to happen here.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
