### ISSUE TITLE
Allow Delay JS script fallback to previous version

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4874]
**Is your feature request related to a problem? Please describe.**
When changes are done to the Delay JS script, issues might arise that will require to use of the previous version of WP Rocket to temporary fix them. 

This might lock users on an old version of WP Rocket if the issue doesn't have yet a solution. Or force them to disable Delay JS to use the latest version of WP Rocket. 

**Describe the solution you'd like**
The possibility to pick the version of the DJE to use as a fallback when needed. 

The feature should ideally be implemented on the UI to allow customers to fallback to the previous version on their own as part of self-diagnosis and temporary fixing until a ticket is opened for further investigation.

A filter will also do, but it will limit its use to tech-savvy customers and the support team.  

This will also make diagnosing DJE issues faster as the support can quickly check if the latest version is the culprit without having to replace the script manually. 

**Describe alternatives you've considered**
Manually replace the DJE script. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1820111756/332448/
Where I had to go back and forth from `3.10.8` to `3.10.9` to run tests that I could simply do by switching the DJE script version.

**Comment by GeekPress** [comment]
This isn't something we will do. We must fix the problem, instead of using another version of the script. it will benefit everybody.
