### ISSUE TITLE
Varnish's cache isn't cleared when clearing page-specific used CSS 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4875]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.0.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When clearing the used CSS for a specific URL, the cache of the URL is properly cleared:
https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/Engine/Cache/PurgeActionsSubscriber.php#L54

However, if Varnish is used, e.g. on Cloudways, the cache of the URL won't be cleared at that time, and:
- the page won't be preloaded - the `wp_remote_get()` request will never reach WordPress
- Remove Unused CSS won't be created/applied there, until the specific URL's cache is cleared using the admin bar menu item, or the whole cache is cleared

**To Reproduce**

1. In an environment where Varnish is used, clear page-specific used CSS using the admin bar menu item.
2. Check the `age` header of the Varnish. That will be larger than `0`.

**Expected behavior**

 Varnish's cache should be cleared when using the "Clear used CSS of this URL" button.

**Additional context**

We should hook `clean_file` to `rocket_rucss_after_clearing_usedcss` here:
https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/Addon/Varnish/Subscriber.php#L41-L47

**Ticket:** https://secure.helpscout.net/conversation/1828951060/334087/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
As Vasilis stated, we need to hook `clean_file()` on `rocket_rucss_after_clearing_usedcss` action

### Estimate the effort ✅
Effort `[XS]`
