### ISSUE TITLE
Compatibility with AffiliateWP

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4882]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
AffiliateWP requires pages where their shortcodes were used to be excluded from cache. 

The [Affiliate Area page](https://docs.affiliatewp.com/article/693-affiliatearea) - the page where the `[affiliate_area]` shortcode was used.
The [affiliate registration page](https://docs.affiliatewp.com/article/100-affiliateregistration) (if separate from the Affiliate Area) - the page where the `[affiliate_registration]` was used.
The [affiliate login page](https://docs.affiliatewp.com/article/98-affiliatelogin) (if separate from the Affiliate Area) - the page where the `[affiliate_login]` was used.
Any pages using shortcodes from the [Affiliate Area Shortcodes](https://docs.affiliatewp.com/article/726-affiliate-area-shortcodes-setup) add-on - all pages where any of their additional shortcodes were used.

They also require to exclude pages from caching when any of the following cookies are stored: 

- `affwp_ref`
- `affwp_ref_visit_id`
- `affwp_campaign`

Reference - https://docs.affiliatewp.com/article/1745-does-affiliatewp-work-with-caching

**To Reproduce**
N/A

**Expected behavior**
WP Rocket should be able to exclude the required pages and apply the needed cookies exclusions when it detects AffiliateWP. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1833689557/335041/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by camilamadronero** [comment]
New request https://secure.helpscout.net/conversation/2597327646/491495/

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
