### ISSUE TITLE
Automatically clear the _wpr_rucss_resources table after updating WP Rocket to > 3.11

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4883]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a site was running WP Rocket 3.10.9, the table `_wpr_rucss_resources` is not cleared after an update to 3.11 version

**To Reproduce**
1. On a site running 3.10.9, check the contents of `_wpr_rucss_resources`
2. Update WP Rocket to the latest version 3.11.0.1 
3. Check the contents of `_wpr_rucss_resources` again, the table will keep the previous entries

**Expected behavior**
We could truncate the `_wpr_rucss_resources` table after the update. Since those contents won't be used unless there is a rollback. This might help all customers having the #4161  

**Screenshots**
after updating to 3.11 the contents of the table are untouched: https://i.imgur.com/2CkZcml.png

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
It was requested from the product team that we don't truncate the table on update, in case the user rollback and returns to the previous RUCSS system.

The table will be cleaned-up by the cron task that is deleting resources not accessed since 30 days, so that should be solved automatically after some time on 3.11.

**Comment by GeekPress** [comment]
We will keep it as it is to anticipate a rollback to 3.10. If we truncate the table, the user will have to clear the used CSS to regenerate it. And they won't know they have to do this action.

This table will be removed in 3.12.
