### ISSUE TITLE
remove unused image feature in wp-rocket

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4887]
**Describe the solution you'd like**

hi

In WordPress, if we delete an image from the media section, that image will still remain in the uploads folder. The reason for this is that after uploading each image, WordPress automatically creates several different sizes of that image. When we delete an image from the media section, only the original version of that image is deleted. But the image versions created by WordPress itself remain in the upload folder And this will rarely be a problem. Currently some plugins ([like this](https://fa.wordpress.org/plugins/media-cleaner/)) do this. But they have many bugs. But if you localize it on wp rocket it is really great.

thank you

**Comment by piotrbak** [comment]
Hello @79ho3ein thank you for creating the issue.

This sounds like an issue with the WordPress core itself. Were you able to create a ticket on the official repo?
https://core.trac.wordpress.org/

**Comment by 79ho3ein** [comment]
hi @piotrbak , thanks for your response. I will definitely do that. Thank you!
