### ISSUE TITLE
Prevent rocket_clean_post from processing excluded pages to avoid cache clearing loops

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4892]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [x]
- Used the search feature to ensure that the bug hasn’t been reported before [x]

**Describe the bug**
We are not checking if the item processing by rocket_clean_post() is excluded from cache. 

This will create a cache clearing loop when preload is active on certain conditions: 

1. A theme/plugins are calling our rocket_clean_post() (in this case, the [Used Registration](https://wordpress.org/plugins/user-registration/) plugin on registration pages)
2. While the trigger post is excluded from cache

Both conditions should happen to create the loop. 

The problem is that `rocket_clean_post()` will end up sending a preload request to `preload_after_clean_post()`. 

When the page is preloaded, it will re-trigger `rocket_clean_post()` causing to go on a loop and clear the post, related posts, and the homepage.

This results in high CPU usage.

A possible fix is to save guard`rocket_clean_post()` from processing excluded pages by adding a check at the top of the function:

https://github.com/wp-media/wp-rocket/blob/e49355167e75f1d3cf51ee65c429b75f3e28682e/inc/common/purge.php#L165

Just like we do when processing Sitemap and Homepage items to preload. 

**To Reproduce**
1. Enable preload
2. Set a page that can trigger the `rocket_clean_post()`
3. Exclude that page from cache
4. Trigger that page
6. See that the page will be continuously purged and preloaded, and having the homepage and related pages doing the same behavior (purged and preloaded continuously) 

**Expected behavior**
We shouldn't trigger `rocket_clean_posts()` for pages that are excluded from cache. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1826803217/333710

A temporary fix can be using [wp-rocket-cache-no-purge-urls](https://github.com/wp-media/wp-rocket-helpers/tree/4b4b97f397741930d9edb2e2adf8cf38f513672c/cache/wp-rocket-cache-no-purge-urls) helper plugins to exclude excluded files from purge. But it won't fix the homepage being purged whenever the trigger page is visited.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/1841939716/336557

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
