### ISSUE TITLE
Minify JS - usercentrics cookie banner isn't displayed

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4898]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.0.2`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The [usercentrics](https://usercentrics.com/) cookie banner is not displayed when Minify JavaScript files is active, and the file is stored locally (no errors in the console).

Excluding the following from JavaScript minification fixes the issue:
`usercentrics.eu`

**To Reproduce**

1. Add the following JavaScript to a page: https://snippi.com/s/6a31phm
2. Enable Minify JavaScript files.
3. Visit a page.
4. The pop-up cookie banner (https://i.vgy.me/VSMOPZ.jpg) will not be displayed.

**Expected behavior**

Usercentrics should work with our JavaScript minification feature.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1835965874/335471/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by camilamadronero-zz** [comment]
Will close https://github.com/wp-media/wp-rocket/issues/4734 too
