### ISSUE TITLE
Preload is not creating CSS files properly mainly everytime with Unused CSS option

### ISSUE THREAD

**Issue by cooltronicpl** [wp-media/wp-rocket#4902]
I have a 3.10.9 WP Rocket newest to my configuration.
Only one of 100 executions CSS files are created properly with the Unused CSS option. It is created without Render Blocking and Unused CSS errors in Pagespeed after preloading periodically (1 to 100).
Affected website: https://cooltronic.pl

**Comment by GeekPress** [comment]
Hi @cooltronicpl 

Please contact our support here: https://wp-rocket.me/support/ 

We will be happy to help you.
