### ISSUE TITLE
RUCSS - <link> elements with rel="preload" aren't removed

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4907]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.0.2`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

After tree-shaking we remove all `<link>` elements:
https://github.com/wp-media/wp-rocket/blob/be49310eb009ecef984a68bd0465453463a95782/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L309-L318

However, we don't remove `<link>` with `rel="preload"` like these:
```HTML
<link rel="preload" styleshet as="style" href="https://tatbekat.net/wp-content/themes/appynnew/rtl.css?ver=2.0.10"/>
```

because of this conditional:
https://github.com/wp-media/wp-rocket/blob/be49310eb009ecef984a68bd0465453463a95782/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L311

**To Reproduce**

1. Add a `<link>` element like the one provided earlier.
2. Enable Remove Unused CSS.
3. Check the source code. The `<link>` will not have been removed.

**Expected behavior**

According to @engahmeds3ed ([Slack thread](https://wp-media.slack.com/archives/G01AMD70N7P/p1648499649744179))

We have two cases:
1. The page contains both `rel="preload"` and `rel="stylesheet"` for the same stylesheet
Here the SaaS will process the `rel="stylesheet"` so in this case, we need to delete the preloaded one as this file will not be loaded on the page anymore.
2. The page contains only `rel="preload"` and JavaScript is used to change this preload to the stylesheet as we do with OCD. In this case, I'm not sure what should happen here, not sure about the puppeteer code coverage if will catch them or not.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1837121277/335702/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@vmanthos Isn't this a duplicate of?
https://github.com/wp-media/wp-rocket/issues/4284

**Comment by vmanthos** [comment]
Yes, it is. I missed it. 😅
