### ISSUE TITLE
Enable rewrite rules on multisite

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4910]
**Is your feature request related to a problem? Please describe.**
WP Rocket disables rewrite rules on multisite environments. 

https://github.com/wp-media/wp-rocket/blob/be49310eb009ecef984a68bd0465453463a95782/inc/functions/htaccess.php#L169-L172

https://github.com/wp-media/wp-rocket/blob/be49310eb009ecef984a68bd0465453463a95782/inc/functions/htaccess.php#L294-L297

In some cases, the overhead to deliver a response from the server took up to 1 second, which will add up to the performance and score audit (PSI shows the reduce server response recommendation).

**Describe the solution you'd like**
Ideally, the rewrite rules should be preserved on multisite.

**Describe alternatives you've considered**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1832076151/334618/

**Comment by GeekPress** [comment]
It's not something we will do as it's very complex to add rewrites rules for multisite. Each site can have its own rules and lead to a big htaccess. It will also have a bad impact on performance.

Based on our data, multisite users are less than 1%. We will not complexify our rewrite rules for this % of users.
