### ISSUE TITLE
Disable testing if cached files exist on hosting services where WP Rocket doesn't handle page cache

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4915]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On hosting services where page cache is not handled by WP Rocket, we are still checking if the cache exists. 

This might result in warnings when the URL visited is not a valid URL ([Ticket #334843](https://secure.helpscout.net/conversation/1832575266/334843/) is an example)

**To Reproduce**
N/A

**Expected behavior**
We shouldn't check the cache on hosting services where page cache is not handled to avoid any issues. To do that, we can build compatibility with each hosting service we support fitting that profile where the cache is disabled as [discussed here](https://wp-media.slack.com/archives/C43T1AYMQ/p1649651913916459?thread_ts=1649232683.035779&cid=C43T1AYMQ). 

Alternatively, we can set a different process to check if cache exists in these cases. For example, checking if the cache header specific to the hosting service is returning a HIT ([like mentioned here](https://github.com/wp-media/wp-rocket/issues/1847#issuecomment-1078848971)).

**Screenshots**

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1832575266/334843/
Slack convo - https://wp-media.slack.com/archives/C43T1AYMQ/p1649651913916459?thread_ts=1649232683.035779&cid=C43T1AYMQ

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
