### ISSUE TITLE
Defer JS prevents FacetWP from working when debug mode is active

### ISSUE THREAD

**Issue by remcokalf** [wp-media/wp-rocket#4916]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
The FacetWP plugin is not working when **Load JavaScript deferred** is active and FacetWP's **debug mode** is active.

I'm on the FacetWP team, and in support all our users must have the FacetWP setting 'debug mode' on. When debug mode is on, and WPRocket's Load JavaScript deferred is active, there is JSON in the page that includes this (from another FacetWP setting): "load_jquery":"yes". 
WPRocket's inline defer tries to 'defer' our JSON because it is containing the word 'jquery'. 
This is causes a `Uncaught ReferenceError: FWP_JSON is not defined` JS error, and FacetWP not working, and support questions and confusion. 

**To Reproduce**
1. Install FacetWP, 
2. Enable debug mode in settings
3. Enable WPRocket's Load JavaScript deferred
4. See `Uncaught ReferenceError: FWP_JSON is not defined` JS error in console when loading a page

**Expected behavior**
WPRocket should not try to 'defer' JSON that contains the word 'jquery'.

If possible, we would like to request  'FWP_JSON' to be added to the $inline_exclusions array in DeferJS.php

**Screenshots**
This is FacetWP's code that generates the JSON. The word jquery is in FWP_JSON.
https://d.pr/i/oJoAgo

The exact wording of the setting in FWP_JSON that triggers the defer: "load_jquery":"yes"

We tested adding 'FWP_JSON' to the defer inline exclusion by adding the following to functions.php, whichs fixes the problem:

add_filter( 'rocket_defer_inline_exclusions', function( $exclusions ) {
    $exclusions[] = 'FWP_JSON';
    return $exclusions;
});

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
