### ISSUE TITLE
Undefined $actionsheduler_* properties lead to database error

### ISSUE THREAD

**Issue by twwn** [wp-media/wp-rocket#4917]
**Describe the bug**
Log is now full of
>PHP Warning:  Undefined property: wpdb::$actionscheduler_actions in /srv/wp-includes/wp-db.php on line 740
>PHP Warning:  Undefined property: wpdb::$actionscheduler_groups in /srv/wp-includes/wp-db.php on line 740
>Wordpress database error Table 'db.a' doesn't exist for querry SELECT a.action_id FROM  a LEFT JOIN  g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='rocket-rucss' AND a.hook='rocket_rucss_pending_jobs_cron' AND a.args='[]' AND a.status IN ('in-progress', 'pending') LIMIT 0, 1 von shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Optimization\RUCSS\Admin\Subscriber->schedule_rucss_pending_jobs_cron, WP_Rocket\Engine\Optimization\RUCSS\Controller\Queue->is_pending_jobs_cron_scheduled, WP_Rocket\Engine\Common\Queue\AbstractASQueue->is_scheduled, as_has_scheduled_action, ActionScheduler_Store->query_action, ActionScheduler_DBStore->query_actions

**To Reproduce**
1. Update v3.11.0.2 → [v3.11.0.3](https://github.com/wp-media/wp-rocket/pull/4912)
2. Preload

**Expected behavior**
No errors

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1846462723/337203/

I have asked for credentials to investigate this.

**Comment by NataliaDrause** [comment]
Same case: https://secure.helpscout.net/conversation/1845318410/337077?folderId=3864740

**Comment by santiagopuerta** [comment]
I reported the same yesterday after update to V3.11.0.3 but it's only a warning :)

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1846750557/337281?folderId=3572159

**Comment by remyperona** [comment]
We found that this issue happened on calls to `?wc_ajax=get_refreshed_fragments`, and our method in the WC subscriber to serve a cache of the empty cart.

Because the method is hooked on `after_setup_theme` and then dies, `init` is not fired, so the AS tables are not added to `$wpdb`. But the `shutdown` action is still fired, so the scheduling method is trying to read from something that was not initialized.

PR #4924 is going to fix the issue.

**Comment by twwn** [comment]
I'm still seeing the exact same message, but only once now per run (and not immediately, it seems).

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2008793724/368352/
@piotrbak issue is still happening.
