### ISSUE TITLE
2.10.7 breaks .htaccess

### ISSUE THREAD

**Issue by pascalroget** [wp-media/wp-rocket#492]
Update to 2.10.7 resulted in all rules except WP-Rocket rules being wiped from .htaccess.

I'm unable to reproduce this on staging.

For now, I chattr +i .htaccess and dismissed the error that WPR cannot write to the file.

Any ideas? How would you like me to go about attempting to figure out what's going on?

**Comment by Tabrisrp** [comment]
Hi,

You should open a support ticket, we don't do support on GitHub: https://wp-rocket.me/support/
