### ISSUE TITLE
Remove Unused CSS is not processing CSS served as a query string

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4920]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some themes generate CSS on the fly and serve a query string (not a PHP file with a query string, literally a query string). 

Example from the ProPhoto theme: 
```
https://domain.ext/?pp_route=%2Fsite-custom-css&version=1649323597
```

That file is not processed by Remove Unused CSS  and might cause issues similar to https://github.com/wp-media/wp-rocket/issues/3887 as well as FOUCs and render-blocking notifications because the stylesheet uses the server resources and might take time to be processed.

**To Reproduce**
1. Use CSS generated by a query string
2. Add it as a stylesheet
3. Enable Remove Unused CSS 
4. See that the CSS file is not processed

**Expected behavior**
We should process all CSS files to avoid style overriding and possible consequences as described above.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1823074181/332991/

Sample code to generate a CSS file using the `?css` query string for testing: 

```
function callback($buffer) {
    if ( isset($_GET['css']) ){
     header('Content-Type: text/css');
     return "h1 { color: red;}";
    } else {
        return $buffer;
    }
}

function buffer_start() { ob_start("callback"); }
function buffer_end() { ob_end_flush(); }
add_action('wp_loaded', 'buffer_start');
add_action('shutdown', 'buffer_end');
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Could you tell me which scenario is happening exactly?
1. The `https://domain.ext/?pp_route=%2Fsite-custom-css&version=1649323597` is not removed from the source but its CSS is in the Used CSS
2. The `https://domain.ext/?pp_route=%2Fsite-custom-css&version=1649323597` is not removed from the source and its CSS is **not** in the Used CSS

**Comment by DahmaniAdame** [comment]
@piotrbak it's **not added to the Used** and **not removed from the page**.
It's like it's just ignored.

**Comment by remyperona** [comment]
Currently the code on the plugin side to remove CSS from HTML only match when the `.css` is used

**Comment by CrochetFeve0251** [comment]
## Reproduce the issue
After trying to reproduce the issue and a talk with @DahmaniAdame. This is issue has been resolved by a PR solving another issue: https://github.com/wp-media/wp-rocket/pull/4995
