### ISSUE TITLE
RUCSS completely ignores dynamically inserted content

### ISSUE THREAD

**Issue by androidacy-user** [wp-media/wp-rocket#4925]
**Describe the bug**
When RUCSS is enabled, it only says css is "used" if it's used on completely static content. Content inserted via JavaScript dynamically is ignored. For our use case, "just add the classes to the ignore list" isn't feasible - between Font Awesome and Bootstrap 5, there's quite the handful of classes we add that do not get picked up by RUCSS.

**To Reproduce**
1. Enable RUCSS
2. Let it warm up
3. Navigate to a page that's primarily generated on the frontend.
4. Notice that all the dynamic content is not correctly displayed.

**Expected behavior**
All the CSS actually used on the page, not just the CSS used on initial load, is there.

**Screenshots**
n/a

**Additional context**
n/a

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @androidacybot thank you for creating the issue.

`Content inserted via JavaScript dynamically is ignored.`
This is not actually true, we're parsing the JavaScript on the websites too. Of course, there's always a place for improvements.

Have you already contacted our support team regarding your issue? We're investigating each case carefully to see if there's something we can do to improve our JS parsers.

**Comment by sriharsha-y** [comment]
I am also observing this from 3.11 version. I rolled back to 3.10.9. There is something that went wrong in 3.11 version all the dynamically added css is broken through out my website.

**Comment by cooltronicpl** [comment]
I have an issue with my theme Jevelin.
I have many IDs like: `heading-***`
I used safelist `#heading-(.*)` in 3.10.9, but on 3.11 it is broken :(
Now it is not working anymore. This ID is dynamically created through site loading. I tried to add (.*) .inner-class after the ID but also it is not working properly.

**Comment by piotrbak** [comment]
@cooltronicpl The solution here is to use this [filter](https://github.com/wp-media/wp-rocket/blob/63f649200fa3b5b81ec83812d3448eeeea28e464/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L345) like [this](https://github.com/wp-media/wp-rocket/blob/63f649200fa3b5b81ec83812d3448eeeea28e464/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L75), to preserve the whole block of dynamic CSS (CSS that changes on each page load).
Have you already contacted our support team? We'd like to test things on our end and create compatibility for each case.

@sriharsha-y @androidacybot We're treating each case separately, have you already contacted our support team and shared with them all details? Only then we'll be able to investigate your specific case and possible provide with a solution.

**Comment by androidacy-user** [comment]
> Hello @androidacybot thank you for creating the issue.
> 
> `Content inserted via JavaScript dynamically is ignored.` This is not actually true, we're parsing the JavaScript on the websites too. Of course, there's always a place for improvements.
> 
> Have you already contacted our support team regarding your issue? We're investigating each case carefully to see if there's something we can do to improve our JS parsers.

No I haven't but i don't think your parser is properly executing the JavaScript. The JS in question gets data from our API and renders it in an user friendly form. Some of the classes are preserved, but modals, font awesome icons, etc, are no longer rendering with RUCSS on. Excluding .modal-* and .modal classes doesn't seem to help either,

**Comment by piotrbak** [comment]
@androidacybot 
**>No I haven't but i don't think your parser is properly executing the JavaScript.**
Without the URL of your site we won't be able to investigate, and either improve our parser or resolve your problem with safelists.

**Comment by piotrbak** [comment]
@cooltronicpl [compatibility with Jevelin](https://github.com/wp-media/wp-rocket/issues/5018) will be built-in most likely starting from 3.11.3. Till then you can use filter shared by me before.

@androidacybot @sriharsha-y I'm closing the issue, since it's very generic. If you're experiencing issues with treeshaker, please contact our support team and we'll fix problems immediately. Moreover, our fix will be also valid for other users that are experiencing the same issue.
