### ISSUE TITLE
Minify JS - tarteaucitron.io cookie bar is not displayed 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4926]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.10.0.3`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When tarteaucitron.io's script is stored locally their cookie notification bar isn't displayed.

Here is an example of that script: https://snippi.com/s/r85sxqd

Adding the following in WP Rocket's UI (Excluded JavaScript files) resolves the issue:
`/load.js`

It should have been:
* `tarteaucitron.io/load.js` OR
* `tarteaucitron.io`

These two aren't working because of #4231.

Adding either of them to WP Rocket's core:
https://github.com/wp-media/wp-rocket/blob/8d3b551b2ca4a546c795d16e4e75989d2b077cb6/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L155-L263

still doesn't exclude the script from being stored locally because of the same issue.

**To Reproduce**

1. Add the snippet provided previously to a page.
2. Enable JavaScript minification.
3. Check the front end.
4. The cookie bar (https://i.vgy.me/tHJxZd.jpg) will not be there.

**Expected behavior**

The cookie bar should be displayed even when JavaScript minification is active.

**Additional context**

This won't be able to be resolved until #4231 is fixed.

**Related ticket:** https://secure.helpscout.net/conversation/1835380625/335338/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Excluded `tarteaucitron.io/load.js` from JS Minification
