### ISSUE TITLE
There is a problem with the Customize Query String Caching 

### ISSUE THREAD

**Issue by fancyric** [wp-media/wp-rocket#4927]
I want to implement the following function。The number following the key keyword is indeterminate。

example.com/about-us/?key123456
example.com/about-us/?key456412

// will BOTH receive the cache file from:
example.com/about-us/

I use the tutorial of the url below, it can only implement the cache of key=xxx, but not the cache of keyxxxxx.
https://docs.wp-rocket.me/article/1281-customize-query-string-caching

I am from China, the above content relies on Google Translate, thank you.

**Comment by piotrbak** [comment]
Hello @fancyric and thank you for creating the issue. Have you already contacted our support team?

**Comment by fancyric** [comment]
> 您好 @fancyric ，感谢您提出这个问题。 您是否已经联系过我们的支持团队？

not yet

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
