### ISSUE TITLE
New preload: cron & scheduled action

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#4932]
- Scheduled action every minute, getting a 100 rows of pending URLs in the DB
- for each URL, create a non-blocking get request for it, for desktop (and mobile version if separate cache for mobile is enabled)
- Add cron job to delete not accessed URLs since x amount of time (to be defined)

**Comment by CrochetFeve0251** [comment]
@Tabrisrp I talked about the logic with @engahmeds3ed some weeks ago and we figure out that there could be a problem if the cache was already loaded on some pages as PHP won't be runned.
This resulting in some page jobs never completing.

For that we figure out a simple solution: check in the cache file if the cache already exists for the page before the get request.
If the file is already here they pass the status of the job to complete.
