### ISSUE TITLE
Disable google fonts optimization helper no longer works

### ISSUE THREAD

**Issue by cafecafe** [wp-media/wp-rocket#4935]
**Describe the bug**
Hello. Uses CSS feature automatically adds the fonts to preloading. I used to skip this feature on multiple websites with _wp-rocket-disable-google-font-optimization_ helper plugin. Unfortunately, since the last couple of updates, it doesn't work anymore, even though it's still listed in the help documents.

Is there any way to disable font preloading while keeping used CSS in place?

**To Reproduce**
Generate Used CSS with wp-rocket-disable-google-font-optimization. You will still have fonts preloaded, unlike in earlier versions.

**Expected behavior**
Font optimization should be skipped, including the preloading.

**Additional context**
Helper plugin seems to be not doing what it's supposed to do

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
Related to #4729 

I don't like this feature, but they added filter to stop this, you can try

`add_filter( 'rocket_enable_rucss_fonts_preload', '__return_false' );`

**Comment by cafecafe** [comment]
@mehedihasanziku it worked. Thank you so much!

I guess they still need to update the helper plugin, as other users might be experiencing the same issue.

**Comment by piotrbak** [comment]
Hello @cafecafe thanks for the question.

As @mehedihasanziku mentioned (thank you!), the preload fonts when RUCSS is active is related to the RUCSS, not to the Google Font Optimization. Filter provided is correct and it'll work.

We'll update our documentation soon.
