### ISSUE TITLE
elementor maintenances mode & wp rocket cache

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4937]
**Describe the bug**

When enabling elementary maintenances mode, we must clear the wp rocket cache to apply the maintenances mode. Please resolve this issue.
In such a way that after activating the maintenances mode, it is applied immediately and there is no need to clear the cache. The current situation is very annoying. Many times we activate the maintenances mode and forget to clear the cache. Therefore, maintenances mode is not enabled for users. 
Maintenances mode will not be applied until we clear the cache.

**Comment by Michaelgimii** [comment]
Are there any plans to fix this?

**Comment by DahmaniAdame** [comment]
@piotrbak hooking to `elementor/maintenance_mode/mode_changed` to the Elementor compatibility file to trigger `clear_cache`.

https://github.com/elementor/elementor/blob/fab0d46aac98a4b09a92b7a0a7bf4fcbe1942b46/includes/maintenance-mode.php#L317

Added a PR for it. 

@Michaelgimii you can use the following code on your functions file as a temporary fix: 
```
add_action("elementor/maintenance_mode/mode_changed", function () {
    if (function_exists("rocket_clean_domain")) {
        rocket_clean_domain();
    }
});
```

**Comment by DahmaniAdame** [comment]
@piotrbak any update on this one?

**Comment by piotrbak** [comment]
@DahmaniAdame Thanks, I missed your comment. I'll add it to the sprint as the change is ready.

**Comment by Michaelgimii** [comment]
> @Michaelgimii you can use the following code on your functions file as a temporary fix:
> 
> ```
> add_action("elementor/maintenance_mode/mode_changed", function () {
>     if (function_exists("rocket_clean_domain")) {
>         rocket_clean_domain();
>     }
> });
> ```

thanks @DahmaniAdame
