### ISSUE TITLE
Allow scripts to be excluded from Delay JavaScript Execution preconnect

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4938]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

Delay JavaScript Execution `preconnect` to external resources.

This might occasionally trigger a recommendation on Lighthouse/PSI if the resource is not immediately used:

![image](https://user-images.githubusercontent.com/1289174/163664317-bb075622-b924-4005-a6f7-17c61b05922a.png)

In this case, it was the Google Tag Manager.

The audit is passed, but the recommendation is still shown in the details of the passed audit. 

**To Reproduce**
1. Add googletagmanager.com code and make sure it's not excluded from Delay JavaScript Execution
2. See error

**Expected behavior**
No recommendation should show when using Delay JavaScript Execution. 

Ideally, we could add an attribute on delayed scripts that will trigger the recommendation, `nopreconnect` for example. 

That attribute can be used by the Delay JavaScript Execution script to skip these scripts from `preconnect`.

**Screenshots**
Added to the description. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1845454620/337100/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
