### ISSUE TITLE
Allow disabling the automatic clearing of used CSS

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4942]
**Is your feature request related to a problem? Please describe.**

A customer requested a way to prevent the automatic clearing of used CSS given that the site doesn't change often.

**Describe the solution you'd like**

We can have a filter that will prevent used CSS from being automatically cleared.

We should preserve the ability to clear the used CSS globally or on a per-page basis using the admin bar menu item.

**Describe alternatives you've considered**

We can use a helper plugin like the following to do this already:
https://drive.google.com/uc?id=1JDPFtXUBzYfFWlgDbkBxA64xKriWqZD6

The downside is that we would need to update the helper plugin in the future if we decide to add/remove triggers for the automatic removal of used CSS.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1849389806/337707/

**Comment by CrochetFeve0251** [comment]
### Scope a solution
Tables are deleted when they are too old (1 month) but also when we change a post:
As a solution I propose to add a 2 filters:
- One controlling the time when values are too old with a default value of 1 (1 month).
If this filter return 0 or less then the deleting function gonna be deactivated.
- One controlling deletion from RUCSS when an entity is updated with a default value of true.

For first hook, we will need :
- To call the filter in the `cron_clean_rows` method in `RUCSS\Admin\Subscriber` class.
- Check if the value is superior to 0 and if it is not the case exit the function.
- Pass the value to `delete_old_used_css` and `delete_old_resources` methods from `Optimization\RUCSS\Admin\Database` class.
- Pass the value to `delete_old_used_css` and `delete_old_resources` methods from `RUCSS\Database\Tables\Resources` class.
- Use it in SQL queries.

For second hook, we will need:
- To call the filter at the beginning from `truncate_used_css` method  in `RUCSS\Admin\Subscriber` class and exit the function if the value is false.
- To call the filter at the beginning from `delete_used_css_on_update_or_delete` method  in `RUCSS\Admin\Subscriber` class and exit the function if the value is false.
- To call the filter at the beginning from `delete_term_used_css` method  in `RUCSS\Admin\Subscriber` class and exit the function if the value is false.
- Change tests to match the new code

### Estimate effort
Effort `S`

**Comment by piotrbak** [comment]
@Tabrisrp this should be regroomed considering the move to the filesystem, right? 🤔

**Comment by vmanthos** [comment]
Related request: https://secure.helpscout.net/conversation/1912981398/347148/

**Comment by CrochetFeve0251** [comment]
@piotrbak  I got some review from @Tabrisrp 25 days ago but I think we will have to adapt the solution anyway as this is not clearing files.

@piotrbak do we wait the PR with the filesystem to be merged?
