### ISSUE TITLE
Prevent duplicated cache file/folder from being created

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#4947]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (yes - 3.11.0.4)
- Used the search feature to ensure that the bug hasn’t been reported before (Yes)

**Describe the bug**
A duplicated cache file/folder is created if uppercase is used instead of lowercase when visiting a page/post URL.

**To Reproduce**
1. Create a post/page. For example: domain.com/test.
2. Visit the URL domain.com/test so it gets cached.
3. Visit domain.com/TEST
4. There are 2 cache file/folders created for the same page, one for each URL.

**Expected behavior**
WP Rocket should not be case sensitive and only one file/folder cache should be created for each URL, no matter what has been added in the browser.

**Screenshots**
[https://share.getcloudapp.com/yAuKnbWj](https://share.getcloudapp.com/yAuKnbWj)

**Additional context**
Related ticket: [https://secure.helpscout.net/conversation/1850624082/337863](https://secure.helpscout.net/conversation/1850624082/337863)
Slack thread: [https://wp-media.slack.com/archives/C08N8J6VC/p1650376509880619](https://wp-media.slack.com/archives/C08N8J6VC/p1650376509880619)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.

**Comment by rosamillan** [comment]
related: https://secure.helpscout.net/conversation/2861809791/543037?viewId=7406897
