### ISSUE TITLE
Compatibility with LegalBlink Policy (optimizations not processed + dynamic cookie)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4950]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When LegalBlink Policy plugin is enabled, none of the optimizations is processed. 

Page cache is built.

Very likely a buffer conflict. 

The plugin also has a cookie notice where we can add compatibility for using our dynamic cookie system. 

The target cookie is `lbp_cookie_accepted`

**To Reproduce**
1. Enable LegalBlink Policy
2. Enable some of the file optimizations

**Expected behavior**
The site should be optimized after enabling the LegalBlink Policy plugin.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1848003365/337463

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
