### ISSUE TITLE
Remove Unused CSS doesn't work on new instalation

### ISSUE THREAD

**Issue by Dalias96** [wp-media/wp-rocket#4953]
**Describe the bug**
When instaling first time after update to 3.11 (more specificly, [PR#4897](https://github.com/wp-media/wp-rocket/pull/4897/files)) with no history of usage (don't know if thats important, but due to no reports of that issue it might be) of WP Rocket before, Remove of Unused CSS doesn't work. Visited website appear in database in table `wpr_rucss_used_css` but they are stuck with `pending` status.

**To Reproduce**
1. Create clean install of WP. (for my team it was an old website with old, really expanded bridge theme, with no WP Rocket usage before). I didn't check it with clean install, but should work as well.
2. Add some function that would produce a PHP Notice.
3. No WP CRON jobs are registered, and thus there is no UsedCSS generated.

**Expected behavior**
After enabling Remove Unused CSS feature should work.

**Screenshots**
n/a

**Additional context**
I found a fix, will attach it in comment as a PR.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Dalias96** [comment]
PR is [here](https://github.com/wp-media/wp-rocket/pull/4954)

**Comment by piotrbak** [comment]
Hello @Dalias96 thank you for your issue and PR. We already have a ready PR too, please take a look at it here:
https://github.com/wp-media/wp-rocket/pull/4941

Let me know if you have any questions about it.

**Comment by Dalias96** [comment]
Ouch i didn't look into PR's, only into issues 😄 Do you know when this will be released?

**Comment by piotrbak** [comment]
It's in the QA phase, should be live tomorrow in the 3.11.0.5 version. Going to close the issue, feel free to comment if you have any questions though.
