### ISSUE TITLE
Remove Unused CSS Transforming Certain Characters

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#4955]
Was working on a client site and found a fun bug. When using remove unused CSS the bullets for the carousel made with this plugin -> https://wordpress.org/plugins/carousel-block/ were being transformed in the CSS being output on the page. 
This is the CSS as it appears before using remove unused CSS. 

`.slick-dots li button:before {
    font-size: 6px;
    line-height: 20px;
    position: absolute;
    top: 0;
    left: 0;
    width: 20px;
    height: 20px;
    content: '•';
    text-align: center;
    opacity: .25;
    color: #000;
}
`

This is the same CSS after enabling remove unused CSS that is output into the document. 

`
.slick-dots li button:before {
    font-size: 6px;
    line-height: 20px;
    position: absolute;
    top: 0;
    left: 0;
    width: 20px;
    height: 20px;
    content: '&bull;';
    text-align: center;
    opacity: .25;
    color: #000;
}
`

As you can see the bullet for the CSS content value '•' is being transformed into '&bull;' breaking the layout.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
