### ISSUE TITLE
Defer JS compatibility with WooCommerce Product Filter (Themify)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4957]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The [WooCommerce Product Filter](https://themify.me/themify-product-filter) plugin defers its own script. 

When jQuery and some required scripts are deferred as well, the following error shows up: 

```
Uncaught ReferenceError: wpf is not defined
    at load_autocomplete (wpf-public.js?ver=1650537564:32:61)
    at wpfInit (wpf-public.js?ver=1650537564:52:155)
    at window.addEventListener.once (wpf-public.js?ver=1650537564:56:1)
load_autocomplete @ wpf-public.js?ver=1650537564:32
wpfInit @ wpf-public.js?ver=1650537564:52
window.addEventListener.once @ wpf-public.js?ver=1650537564:56
load (async)
(anonymous) @ wpf-public.js?ver=1650537564:54
(anonymous) @ wpf-public.js?ver=1650537564:56
```

The issue is happening because the plugin is calling some additional libraries: 

```
var jquery_ui_path = wpf.includes_url + 'js/jquery/ui/';
var scripts = [[jquery_ui_path + 'core.min.js', function() {
    return typeof $.ui === 'object'
}
```
Here [/plugins/themify-wc-product-filter/public/js/wpf-public.js](https://www.marvel-mania.fr/wp-content/cache/min/1/wp-content/plugins/themify-wc-product-filter/public/js/wpf-public.js?ver=1650537564:formatted)

Excluding the following from defer scripts fixes the issue: 

```
/wp-includes/js/jquery/jquery.min.js
/js/jquery/ui/(.*)
```

**To Reproduce**
1. Enable [WooCommerce Product Filter](https://themify.me/themify-product-filter)
2. Enable defer JS without any exclusions 
3. Go to an archive page with a filter

**Expected behavior**
There shouldn't be any console errors when WooCommerce Product Filter is used.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1853916463/338300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
Reproduced on local environment

### Identify the root cause ✅
This is happening because `wpf-public.js` requires some libraries like @DahmaniAdame mentioned and these libraries are jquery dependent but jquery is defered.

### Scope a solution ✅
Create a Thirdparty compatibility class for WC Product Filter that excludes jQuery and js/jquery/ui/(.*) from being defered and corresponding tests too.

Estimate the effort ✅
[S]

**Comment by engahmeds3ed** [comment]
@jeawhanlee do u think we need to exclude also `/js/jquery/ui/(.*)` as @DahmaniAdame  Mentioned? or excluding jquery only solve the issue?

If u want to conditionally exclude those so u need to create thirdparty compatibility class and add tests for it.

I'd suggest changing the effort to `[S]` instead of `[XS]`

**Comment by jeawhanlee** [comment]
@engahmeds3ed Excluding just jQuery solved the issue but we can  also add `/js/jquery/ui/(.*)` this to the exclusion list.

**Comment by engahmeds3ed** [comment]
Calling @piotrbak @DahmaniAdame

**Comment by piotrbak** [comment]
@engahmeds3ed @jeawhanlee @DahmaniAdame We need to be sure that excluding jQuery solves the problem described. If so, we'll exclude only it in a thirdparty compatibility class.

Ideally only on pages when the filter is displayed, but probably it won't be possible.

**Comment by jeawhanlee** [comment]
@piotrbak @engahmeds3ed For me, excluding just jQuery on WPR solved the problem...

**Comment by piotrbak** [comment]
@jeawhanlee Okay, let's do it and validate this later with @DahmaniAdame + @wp-media/qa 

If things still won't be working, adding another exclusion will be very fast

**Comment by DahmaniAdame** [comment]
@piotrbak @jeawhanlee I just retested. Only jQuery needs to be excluded. 
Pretty sure not excluding `/js/jquery/ui/(.*)` still triggered the issue though when I tested the first time. But right now, it's consistently working just by excluding jQuery alone. 
Let's see what @wp-media/qa team finds out.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2029011456/372988/

**Comment by viobru** [comment]
Likely related: https://secure.helpscout.net/conversation/2077061628/384051

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
