### ISSUE TITLE
Remove Unused CSS makes elementor pro menu dropdown submenu indicator HUGE 

### ISSUE THREAD

**Issue by berkmh** [wp-media/wp-rocket#4962]
**Describe the bug**
When activating remove unused CSS elementor pro header submenus chevron indicators (SVG) across the site become gigantic. 

**To Reproduce**
1. Using elementor pro build a menu with dropdown and submenu indicator
2. turn on remove unused CSS
3. go back to site
4. indicators are now HUGE

**Expected behavior**
to not become huge

**Additional context**
I have tried adding to safelist and does not work. 

```
.fa-(.*):before
.fa-(.*)
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @berkmh I wasn't able to reproduce this problem. Could you please clear the RUCSS and try again?

If you're still experiencing this issue, please be in touch with our Support Team, we'll take care of further investigation and apply the fix immediately.
