### ISSUE TITLE
Rocket interference with elementor flex box

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4963]
**Describe the bug**

Many colleagues reported that the rocket interfered with the elementor flex box. This interference naturally occurs when the website is built with an elementor flex box. Has anyone had a similar experience?
It would also not be bad if Rocket optimizes more css files in elementor. In previous versions, Rocket banned a number of css files in elementor from optimization.
thanks

**Comment by piotrbak** [comment]
@Michaelgimii thank you for being in touch. We use GitHub for development purposes, also for bugs reporting we have a dedicated template which should be used.

Your ticket doesn't seem like be a confirmed bug that we can fix. If you'd like to share your opinion and ask some questions to other users, I'd suggest posting on our Facebook group (named WP Rocket Users). On the other hand, if you prefer us to invesigate your case specifically, please reach our Support Team.

Thank you!
