### ISSUE TITLE
Remove Warnings for  the Minification Features

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4966]
**Is your feature request related to a problem? Please describe.**

With Remove Unused CSS and Delay JavaScript execution as the key optimization features, the **Minify CSS files** and **Minify JavaScript files**  features should be enabled in one click, without this warning:

![image](https://user-images.githubusercontent.com/23031592/165156064-93098252-f797-4585-a70a-df5df029200b.png)

Thanks!

**Comment by GeekPress** [comment]
Why should it be removed? These options could still break websites.

**Comment by camilamadronero-zz** [comment]
Minification can still break things, yes. However, if we remove the minification/combine warnings, then:

- CSS optimizations: Remove Unused CSS feature will be the only one with the warning, thus, it will have more weight.
- JavaScript optimizations: Delay JavaScript execution could start using one warning instead.

In my opinion, only the most aggressive File Optimization features could have a warning: Remove Unused CSS and Delay JavaScript execution. All the others are relatively safe by now: Minify CSS files, Minify JavaScript files and Load JavaScript deferred. And, combine options are often replaced by Remove Unused CSS and Delay JavaScript execution, too.

As a side note, Preload is a quite risky feature and there's no warning. Also is LazyLoad. So, that makes me wonder if we even need any warnings at all.

**Comment by jeawhanlee** [comment]
@piotrbak What is the AC here, do we need this notice removed for just Minify CSS & js,  Also do we need to modify the notice for RUCSS?

**Comment by piotrbak** [comment]
Only for Minify CSS and Minify JS
