### ISSUE TITLE
Remove Google Fonts CSS when Remove Unused CSS is enabled

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4967]
**Is your feature request related to a problem? Please describe.**
When Remove Unused CSS is enabled, we are not removing the Google Fonts CSS call, and that can trigger the Remove Unused CSS warning in PSI results.

In some cases, even our own **wpr-usedcss** is going to be listed together with the Google fonts, because any safelistings or automatic compatibility in our SaaS can make the used CSS a few Kbs bigger, and it will still be listed within the global audit.

**Describe the solution you'd like**
Since the fonts should be already referenced in the Used CSS, we can remove the Google Fonts stylesheets by default. And have a filter to reverse the removal if there are issues.

**Describe alternatives you've considered**
Or, it could be the opposite, we can have a filter to remove the font CSS for those cases where it is flagged in the PSI audit

**Additional context**
ticket: https://secure.helpscout.net/conversation/1856608038/338712/
slack convo: https://wp-media.slack.com/archives/C029G1B5HD2/p1650483560291209

Example audit
![slack-imgs](https://user-images.githubusercontent.com/229406/165158146-2461c880-5951-4faf-9a80-fdf1f1d98157.png)

**Comment by CrochetFeve0251** [comment]
### Scope a solution
A solution would be to add to the default safelist in the [`treeshake` method](https://github.com/wp-media/wp-rocket/blob/6f905396f43c1831c370848e9c36bf14e72ab545/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L192) from the `UsedCSS` class.

For that we need to add the value to the [default array](https://github.com/wp-media/wp-rocket/blob/6f905396f43c1831c370848e9c36bf14e72ab545/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L192).

### Estimate effort
Effort `XS`

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1867973721/340586?folderId=2135277
