### ISSUE TITLE
Delay JavaScript Execution compatibility with Thrive Comments

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4968]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Thrive Comments is used with Delay JavaScript Execution, the comment form is not displayed. 

No console error is showing. 

The issue is that the `.thrive-comments-content` element is not toggled to be displayed after user interaction. 

This is happening using the following code: 

```
ThriveComments.util.tcm_hide_loader = function() {
    a(".tcm-dot-loader").hide(),
    a(".thrive-comments-content").show()
}
```

And it's happening on the following file: [/wp-content/plugins/thrive-comments/assets/js/frontend.min.js](https://gist.github.com/DahmaniAdame/16b68fcff7c3c9244fb6c1d2336b8de4)

Excluding the following from Delay JavaScript Execution fixes the issue: 

```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/jquery-migrate(.min)?.js
/thrive-leads/
window.TL_Const
var ml=
/thrive-comments/assets/js/
ThriveComments
/wp-includes/js/underscore.min.js
/wp-includes/js/backbone.min.js
```

Excluding Thrive Leads is also required for the exclusions to work. 

```
/thrive-leads/
window.TL_Const
var ml=
```

**To Reproduce**
1. Enable Thrive Comments
2. Enable Delay JavaScript Execution 
3. See the comment box not showing on pages with comments enabled

**Expected behavior**
Thrive Comments should work out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1853077201/338163

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Do we have any staging for that? If not, I believe we should reproduce this and be in touch with Gael

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
