### ISSUE TITLE
Allow filtering the CSS files added with <link> before they are removed by RUCSS

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4969]
**Is your feature request related to a problem? Please describe.**
In some cases, we might need to exclude CSS files from being removed by RUCSS. 
When for any reason, removing them causes issues and we cannot properly safelist them.
This might simplify the troubleshooting of some edge cases (safelisting doesn't work, CSS links are using media queries that we cannot cover, etc)

**Describe the solution you'd like**
Add a filter to manipulate the array of stylesheet files we grab at [$link_styles](https://github.com/wp-media/wp-rocket/blob/151cb6257e69c6832c4354b3a09be1a32eb1c521/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L298-L302) 

**Additional context**
related ticket: https://secure.helpscout.net/conversation/1853433495/338231?folderId=2683093
slack thread: https://wp-media.slack.com/archives/C029G1B5HD2/p1650551460727419

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1848228658/337520/

@piotrbak This one is the consequence of preserving the `divi-style-parent-inline-inline-css` to fix this - https://github.com/wp-media/wp-rocket/issues/4598

The preserved inline style will override the child theme's style in this case `/wp-content/themes/divi-child/style.css`. 

If we had a filter, we could preserve that stylesheet as well in order to prevent the overriding.

**Comment by NataliaDrause** [comment]
Related:
https://secure.helpscout.net/conversation/1864391207/340028/

We are not able to process this stylesheet: https://cdn.ampproject.org/amp-story-player-v0.css?ver=v0 due to a [comment line](https://i.imgur.com/8LC5iG1.png).
It is not possible to edit the file, so preserving it entirely would be a workaround.

**Comment by alfonso100** [comment]
In the initial case, https://secure.helpscout.net/conversation/1853433495/338231/

Excluding the 3 responsive stylesheets from being removed solved the responsive layout issue, without impacting the PSI report in this case

```
<link data-minify="1" rel="stylesheet" type="text/css" media="screen and (max-width: 960px)" href="https://site.dev/wp-content/cache/min/1/wp-content/themes/maya/css/lessthen960.css?ver=1651246028" />
  <link data-minify="1" rel="stylesheet" type="text/css" media="screen and (max-width: 600px)" href="https://site.dev/wp-content/cache/min/1/wp-content/themes/maya/css/lessthen600.css?ver=1651246028" />
  <link data-minify="1" rel="stylesheet" type="text/css" media="screen and (max-width: 480px)" href="https://site.dev/wp-content/cache/min/1/wp-content/themes/maya/css/lessthen480.css?ver=1651246028" />
```

**Comment by piotrbak** [comment]
> Related - https://secure.helpscout.net/conversation/1848228658/337520/
> 
> @piotrbak This one is the consequence of preserving the `divi-style-parent-inline-inline-css` to fix this - #4598
> 
> The preserved inline style will override the child theme's style in this case `/wp-content/themes/divi-child/style.css`.
> 
> If we had a filter, we could preserve that stylesheet as well in order to prevent the overriding.

@DahmaniAdame In this case, https://github.com/wp-media/wp-rocket/issues/4792 should fix the problem.



> In the initial case, https://secure.helpscout.net/conversation/1853433495/338231/
> 
> Excluding the 3 responsive stylesheets from being removed solved the responsive layout issue, without impacting the PSI report in this case
>

@alfonso100 Why we had the problems with responsive layout? Separate Cache for Mobiles didn't help here?

> Related: https://secure.helpscout.net/conversation/1864391207/340028/
> 
> We are not able to process this stylesheet: https://cdn.ampproject.org/amp-story-player-v0.css?ver=v0 due to a [comment line](https://i.imgur.com/8LC5iG1.png). It is not possible to edit the file, so preserving it entirely would be a workaround.

@NataliaDrause Thanks, let's see if @mostafa-hisham will be able to fix the root cause.

**Comment by alfonso100** [comment]
@piotrbak Separate cache for mobiles didn't help in this case, nor did adding the metatag.
slack thread for reference: https://wp-media.slack.com/archives/C029G1B5HD2/p1650551460727419

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1877221883/341924?
@piotrbak in this case, the customer is using Advanced Ads to serve Elementor templates. 
When the ad is rotated on the page, it won't have any reference for its CSS on the page. 
The style is added using `/wp-content/uploads/elementor/css/post-###.css`
Ticket - https://secure.helpscout.net/conversation/1877221883/341924

**Comment by mostafa-hisham** [comment]
> @piotrbak Separate cache for mobiles didn't help in this case, nor did adding the metatag.
slack thread for reference: https://wp-media.slack.com/archives/C029G1B5HD2/p1650551460727419

I checked this issue before the client was switching from device-width to other by window resizing without refresh 
we are caching separate CSS for mobile and desktop need to refresh to serve the correct one

> Related:
> https://secure.helpscout.net/conversation/1864391207/340028/
> 
> We are not able to process this stylesheet: https://cdn.ampproject.org/amp-story-player-v0.css?ver=v0 due to a [comment line](https://i.imgur.com/8LC5iG1.png).
> It is not possible to edit the file, so preserving it entirely would be a workaround.

@NataliaDrause is this issue still exist? also, the CSS file URL is not working

**Comment by mostafa-hisham** [comment]
## Scope a solution :white_check_mark:
- Add a new filter to preserve URLs of links href 
`$preserve_link_styles_urls = apply_filters( 'rocket_rucss_preserve_link_styles_url', [] );`
- create new function in`inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php` to check if the link should be preserved i the cache based on the filter
```
private function maybe_preserve_url( $link_url, $preserved_urls ) {
		$preserve = false;
		foreach ( $preserved_urls as $url ) {
			$preserve = (bool) preg_match( '/' . preg_quote( $url, '/' ) . '/is', $link_url );
			if ( $preserve ) {
				break;
			}
		}
		return $preserve;
	}
```
-  update the condition that removes styles from HTML 
https://github.com/wp-media/wp-rocket/blob/9a587553bd8c3f887c42dd8fb51fc4ac204cd708/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L314-L328

```
$preserve_link_styles_urls = apply_filters( 'rocket_rucss_preserve_link_styles_url', false );
		foreach ( $link_styles as $style ) {
			if (

				! (bool) preg_match( '/rel=[\'"]stylesheet[\'"]/is', $style[0] )
				&&
				! ( (bool) preg_match( '/rel=[\'"]preload[\'"]/is', $style[0] ) && (bool) preg_match( '/as=[\'"]style[\'"]/is', $style[0] ) )
				||
				( $preserve_google_font && strstr( $style['url'], '//fonts.googleapis.com/css' ) )
				||
				( $preserve_link_styles_urls && $this->maybe_preserve_url( $style['url'], $preserve_link_styles_urls ) )
			) {
				continue;
			}
			$html = str_replace( $style[0], '', $html );
		}
```
- update tests

## Estimate effort :white_check_mark:
Effort `S`

**Comment by alfonso100** [comment]
Another case: 
https://secure.helpscout.net/conversation/1894560161/344647/

**Cloudways** + **Varnish** in this case, since the **Separate cache for mobile devices** doesn't work properly on this environment, the following is not preserved as expected/is producing unexpected results: 

`<link rel='stylesheet' id='woocommerce-smallscreen-css'  href='https://example.com/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css?ver=6.5.1' type='text/css' media='only screen and (max-width: 768px)' /> `

Re-adding the stylesheet using the `rocket_buffer` filter solved the issue
