### ISSUE TITLE
Update Broken Link in Plugin's Deactivation Form

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4970]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
There is a 404 error in the [correctly-measure-websites-page-load-time](https://wp-rocket.me/blog/correctly-measure-websites-page-load-time/?utm_source=wp_plugin&utm_medium=wp_rocket) link in the deactivation form.

**To Reproduce**
1. Click on Deactivate WP Rocket from the plugins page
2. Click on "My PageSpeed or GT Metrix score did not improve"
3. Click on the https://wp-rocket.me/blog/correctly-measure-websites-page-load-time/?utm_source=wp_plugin&utm_medium=wp_rocket link.
4. See 404 error: https://jmp.sh/6EXX9yW

**Expected behavior**
We should use the right link, probably at https://github.com/wp-media/wp-rocket/blob/94bfacd2122ed61def7ef3f780ba17e0cd920022/views/deactivation-intent/form.php#L116.

It seems the query string breaks the link/redirect because when visiting https://wp-rocket.me/blog/correctly-measure-websites-page-load-time, the redirect to https://wp-rocket.me/blog/how-to-test-wordpress-site-performance-measure-speed-results/ works. Props to @webtrainingwheels for noticing this!

Maybe the link for `Why you should not be chasing a PageSpeed score` link can be updated too.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1861605510/339371/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
I think this one can be handled in https://github.com/wp-media/wp-rocket/pull/4880

**Comment by piotrbak** [comment]
@camilamadronero What @engahmeds3ed wrote is correct, I'm closing it.
