### ISSUE TITLE
Remove Unused CSS compatibility with Flatsome dynamic #image_ selector

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4971]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Flatsome adds a highly dynamic selector for their images wrappers - `#image_`. 

That selector has a corresponding inline style added just below the element. 

```
<div class="img has-hover x md-x lg-x y md-y lg-y" id="image_1904539379">
    <div class="img-inner dark">
        <img width="150" height="150" src="/path/to/img/image-150x150.png" class="attachment-thumbnail size-thumbnail wvs-attachment-image" alt="Dodos" srcset="/path/to/img/image-150x150.png 150w, /path/to/img/image-247x247.png 247w, /path/to/img/image-100x100.png 100w, /path/to/img/image-135x135.png 135w" sizes="(max-width: 150px) 100vw, 150px">
    </div>

    <style>
        #image_1904539379 {
            width: 25%;
        }

        @media (min-width:550px) {
            #image_1904539379 {
                width: 10%;
            }
        }
    </style>
</div>
```

The issue is fixed by excluding the selector using the `rocket_rucss_inline_content_exclusions` filter. 

**To Reproduce**
1. Use Flatsome
2. Use their image element with a custom style
3. See error

**Expected behavior**
Flatsome `#image-` inline styles should be preserved to avoid missing their style when the Used CSS is used.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1856472620/338688/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Add the selector `#image_` to the preserved pattern in `WP_Rocket\ThirdParty\Themes\Flatsome::preserve_patterns`

### Estimate the effort ✅
[xs]

**Comment by GeekPress** [comment]
@piotrbak Can this be included in 3.11.1? We don't really need any QA process here, and doesn't worse to have one.

**Comment by piotrbak** [comment]
@GeekPress Yes, we could do that. I'll check if there are any similar issues more.

@engahmeds3ed Could you do a CR and merge it to develop so it passes the smoke tests?
@Mai-Saad FYI

**Comment by engahmeds3ed** [comment]
Done
