### ISSUE TITLE
Remove Unused CSS to preserve inline CSS for the WP Recipe Maker

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4972]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Recipe Maker has a class used to style recipe list items that change over time: `.wprm-advanced-list-`.

This will result in its corresponding style being outdated overtime when Remove Unused CSS is used.

![image](https://user-images.githubusercontent.com/1289174/165445665-51bd2b86-c870-4d7a-a2d7-3c4e5c0a0903.png)

```
<ul class="wprm-advanced-list wprm-advanced-list-reset wprm-advanced-list-9367 wprm-recipe-instructions"></ul>
<style type="text/css">ul.wprm-advanced-list-9367 li:before {background-color: #006344;color: #ffffff;width: 1.8em;height: 1.8em;font-size: 12px;line-height: 12px;}</style>
```

Excluding `.wprm-advanced-list-` using `rocket_rucss_inline_content_exclusions` fixes the issue.

**To Reproduce**
1. Use the WP Recipe Maker + RUCSS
2. Wait for a while
3. See the class change and the missing style if the cache is regenerated

**Expected behavior**

**Screenshots**

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1848224170/337518/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@piotrbak should I add a PR for this one, or does it need grooming?

**Comment by remyperona** [comment]
I don't think we need grooming for it, the classname seems specific enough

**Comment by piotrbak** [comment]
@DahmaniAdame if you can, please do the PR 😁 If not, no worries.

**Comment by DahmaniAdame** [comment]
@piotrbak done!
