### ISSUE TITLE
RUCSS - Vamtam's Health Center breaks because dynamic selectors aren't preserved 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4975]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.10.0.5`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Vantam's [Health Center](https://themes.vamtam.com/?theme=health-center) theme is using dynamic selectors in `<style>` elements:
`#wpv-expandable-da6b839703edd389903f0dc840c305d8`

The last part changes on every "uncached" load and because of that pages with used CSS break.

**To Reproduce**

1. Install/activate the theme - it's a premium one.
2. Create a new page and add an "Expandable Box" (https://i.vgy.me/hgqYVI.jpg).
3. Activate Remove Unused CSS.
4. After used CSS has been created for the page clear the cache.
5. The expandable box will be broken.

**Expected behavior**

The "Expandable Box" shouldn't break with Remove Unused CSS.

**Additional context**

We need to add `#wpv-expandable` to the following array:
https://github.com/wp-media/wp-rocket/blob/95d608d4cd5de892341b19f06cdd76190073c985/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L76-L79

**Ticket:** https://secure.helpscout.net/conversation/1862494598/339691/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@vmanthos Could you make a PR for this?

**Comment by vmanthos** [comment]
I'm already doing that. 😉

**Comment by piotrbak** [comment]
@engahmeds3ed We need a CR and a merge here too 🙏 
@Mai-Saad FYI

**Comment by engahmeds3ed** [comment]
Done
