### ISSUE TITLE
RUCSS - Kinsta's cache isn't cleared after successfully creating the used CSS

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4980]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.0.5`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

After the successful creation of the used CSS we are purging the URLs cache:
https://github.com/wp-media/wp-rocket/blob/b1d16b7bd8ddfb0a998330fea09cd3fd687fb92f/inc/Engine/Cache/PurgeActionsSubscriber.php#L53

When a site is hosted on Kinsta the cache purging will not take place automatically, and used CSS will be applied only during the next cache purging.

**To Reproduce**

1. On a Kinsta website enable Remove Unused CSS.
2. Make sure that used CSS has been created for a URL.
3. Check the URL. The used CSS will not have been applied.
4. Clear the cache and check again. Used CSS should be there.

**Expected behavior**

On Kinsta, a URL's cache should be cleared after the used CSS has been created.

**Additional context**

In Kinsta's compatibility file, we should hook `rocket_clean_kinsta_post_cache()` to:
* `rocket_rucss_complete_job_status`
* `rocket_rucss_after_clearing_usedcss`

**Ticket:** https://secure.helpscout.net/conversation/1862503536/339693/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Mai-Saad** [comment]
For retest: the same problem exists with the WP Engine test site

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1863208289/339825?folderId=2135277

**Comment by CrochetFeve0251** [comment]
@vmanthos I need a test server on Kinsta  to reproduce the issue (waiting for support to see if they have a server otherwise we will have to create one)

**Comment by remyperona** [comment]
Note: we should take the opportunity to move the Kinsta compatibility code to the new architecture

**Comment by CrochetFeve0251** [comment]
### Reproduce the issue
As I don't have Kinsta I wasn't able to reproduce the issue.

### Scope a solution
First we will have to move the old code to the new architecture:
We will have first to move the old code to `ThirdParty\Hostings\Kinsta`.
For that we will implement the interface `Subscriber_Interface` and add each action to the events.
Then we will need to add Kinsta to the `HostSubscriberFactory`

In a second time we will need to fix the issue by itself:
In the new Kinsta class we will have to add two new events:
```php
$events= [
   'rocket_rucss_complete_job_status' => 'rocket_clean_kinsta_post_cache',
   'rocket_rucss_after_clearing_usedcss' => 'rocket_clean_kinsta_post_cache'
```

In a last time we need to create tests for the new class.
### Estimate effort
Effort `S`
