### ISSUE TITLE
CDN exclusions are not reflected when resource is inside the CSS file

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4982]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Content Delivery Network is enabled, font awesome Icons are not displayed when caching for mobile devices is enabled.
While excluding a font file from the CDN, that keeps being rewritten when it's referenced in CSS files. 
If the file is excluded, it should not be served at all.

**To Reproduce**

1. Disable all WPR options but caching for mobile devices
2. Enable CDN (rocketcdn)
3. Check the cart icon on desktop (screenshot below) -> The cart icon is not displayed correctly
4. Check the cart icon and the hamburger icon on mobile (screenshot below) -> The cart and hamburger icons are not displayed correctly

**Expected behavior**
Font awesome icons should be displayed correctly on desktop and mobile if caching for mobile devices and Content Delivery Network are enabled 

**Screenshots**
mobile:
![Screenshot 2022-04-28 at 09 45 16](https://user-images.githubusercontent.com/1954918/165742447-b61bc57e-1e58-431a-88c1-b0de87958f18.png)

desktop:
![Screenshot 2022-04-28 at 13 27 24](https://user-images.githubusercontent.com/1954918/165742417-811a5015-2fef-4f81-ad3f-33648983d6db.png)

**Additional context**

- WPR version 3.11.0.5
- CDN enabled (rocketcdn)
- caching for mobile devices enabled
- Related issue https://secure.helpscout.net/conversation/1862559697/339702
- Thread https://wp-media.slack.com/archives/C08N8J6VC/p1651131403301409

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Comment by mattpramschufer** [comment]
I too have just run into this. I have tried using the WP Rocket Plugin for No CORS for fonts, and I have tried to exclude the font files from the CDN but neither seem to work when the resource is being imported via CSS.  This is specific with the icon fonts using the Newspaper X theme.
