### ISSUE TITLE
Remove Unused CSS compatibility with ConvertPlug dynamic .content-

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4984]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
ConvertPlug adds popups with dynamic IDs with their respective style added inline just below them. 

```
<div class="content-626b819000a4c" ... ></div>
<style type="text/css" class="cp-form-css">
  .content-626b819000a4c ... {
  }
</style>
```

When the cache is regenerated, the above class will change. 

Excluding `cp-form-css` using `rocket_rucss_inline_atts_exclusions` fixes the issue. 

We can permanently exclude it from https://github.com/wp-media/wp-rocket/blob/9f68883a4c3468359bcc3fd7b9779b8bf7f72380/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L60-L69 to prevent the issue from happening. 

**To Reproduce**
1. Use ConvertPlug
2. Add a popup opt-in form on the page
3. Generate Used CSS
4. Clear the cache
5. See error

**Expected behavior**
ConvertPlugin style should be retained even after clearing the cache when Remove Unused CSS is used. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1863092210/339787

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@piotrbak Can't these kinds of compatibility be done from the back-end?

**Comment by piotrbak** [comment]
@GeekPress In the future, with the new backend for other features

**Comment by DahmaniAdame** [comment]
@piotrbak should I add a PR for this one, or does it need grooming?

**Comment by piotrbak** [comment]
@DahmaniAdame `.content-` doesn't seem to be unique, we'll need a separate compatibility class for this plugin.

**Comment by CrochetFeve0251** [comment]
### Reproduce the problem
As the plugin is not free it is not possible to reproduce the problem.
### Scope a solution
A solution would be to create a third party classs for the plugin that check if the plugin is activated before registering filters.
On this class we will create a method that will register to the filter `rocket_rucss_inline_atts_exclusions` and add `cp-form-css` to the exclusion list:
```php
public function excluded_from_rucss($excluded) {
  $excluded{] = 'cp-form-css'; 
  return $excluded;
}
```
Create tests for that class.
### Estimate efforts
Effort `S`

**Comment by CrochetFeve0251** [comment]
@DahmaniAdame I just realize that without the plugin I can't know how to detect when it is activated.
As it is paid plugin I can't have it easily that's why I would like to know if you have it?
