### ISSUE TITLE
Add one.com logo when the account has been created from one.com

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4987]
**Is your feature request related to a problem? Please describe.**
One.com is going to release its reseller plan. They would like to let the user know they bought WP Rocket from One.com.

**Describe the solution you'd like**
In the dashboard, next to the license name, we will One.com logo if we detected the user bought the license from One.com.

[Screenshot](https://share.getcloudapp.com/OAu6ynGQ)

**Additional context**
To detect if a user bought the license from One.com, we added new info in the user data `has_one-com_account`: https://github.com/wp-media/wp-rocket.me/blob/trunk/wp-content/mu-plugins/woocommerce-rocket/inc/classes/class-redis.php#L180

**Comment by jeawhanlee** [comment]
### Scope a solution ✅

- Add one.come logo in the root assets/img folder.
- Validate `has_one-com_account` in inc/Engine/Admin/Settings/Page:customer_data and add new element to returned array if true.
- Do a conditional check in views/settings/page-sections/dashboard.php and add one.com logo
