### ISSUE TITLE
Update Delay JS script to latest version

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4988]
**Is your feature request related to a problem? Please describe.**
We have 3 fixes left on the Delay JS script:
- https://github.com/wp-media/delay-javascript-loading/pull/18
- https://github.com/wp-media/delay-javascript-loading/pull/21
- https://github.com/wp-media/delay-javascript-loading/pull/24

**Describe the solution you'd like**
Merge all PR to create a new version of the script.

**Additional context**
PR 24 needs some change inside WP Rocket too.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In addition to merging the 3 PRs and minifying the script, the following needs to happen in the `Engine\Optimization\DelayJS\HTML`:

In `replace_scripts()`, we also need to transform the `src` attribute to `data-rocket-src` if it is present in the attributes of the matched script.

The related automated tests will need to be updated to match the changes.

### Estimate the effort ✅
Effort [S]

**Comment by Mai-Saad** [comment]
We need to fix https://github.com/wp-media/delay-javascript-loading/issues/34

**Comment by gmetais** [comment]
Hello,

I've added a commit (https://github.com/wp-media/delay-javascript-loading/pull/24/commits/ead18c3586b344c2da70f72aa0f61086ab51e0a9) on the branch `fix-layout-slowness-2` that fixes the bug reported in https://github.com/wp-media/delay-javascript-loading/issues/34.

Can you please merge it with the rest?

(Thanks for the bug detection @Mai-Saad & @piotrbak !)

**Comment by piotrbak** [comment]
@jeawhanlee Could you update the script and the plugin's branch?

@gmetais Thank you! 🥇

**Comment by jeawhanlee** [comment]
@piotrbak Ok

**Comment by piotrbak** [comment]
Blocking the issue till we have an answer here:
https://github.com/wp-media/delay-javascript-loading/pull/32#issuecomment-1260857280
