### ISSUE TITLE
Multi-site: Network deactivation not working probably

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4990]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clicking network deactivate  for wpr, not working unless we open the NW deactivate link in another tab and the deactivation form won't be displayed

**To Reproduce**

Precondition:
- WPR installed and network activated on multisite

1. Go to the plugins page in the network admin
2. Click on network deactivate for wpr
3. no popup is displayed and no deactivation occurs

**Expected behavior**
Network deactivate display the deactivation form and deactivation works with no need to open in new tab

**Screenshots**

**Additional context**
- Working fine on multisite if we activate/deactivate per site
- Was working fine for NW on 3.11.0.5

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1872950941/341320/

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1887050808/343407

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1923573665/349066?folderId=377611

**Comment by camilamadronero-zz** [comment]
Related: https://secure.helpscout.net/conversation/2003119492/367148/

**Comment by girlie** [comment]
Related: https://secure.helpscout.net/conversation/2044929569/376381/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2064983254/381010?folderId=3864735

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
