### ISSUE TITLE
Flatsome: RUCSS compatibility with dynamic elements like  #row- , #text-

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4991]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Dynamic styles added by Flatsome aren't preserved 

**To Reproduce**
1. Flatsome active theme
2. Add a page with row, styled text using UX builder i.e http://mega.wp-rocket.me/flatsome/image-test/
3. Enable RUCSS
4. Open the page template and compare it to ?nowprocket

**Expected behavior**
Dynamic elements are preserved i.e `#row-` and `#text-`

**Screenshots**
With nowprocket
![Screenshot from 2022-04-29 20-09-00](https://user-images.githubusercontent.com/76941962/165999633-6a7c3239-5872-4a40-b4ae-2530e1447126.png)

With RUCSS
![Screenshot from 2022-04-29 20-08-47](https://user-images.githubusercontent.com/76941962/165999721-e561d758-5854-485a-859f-5bc06769af59.png)

**Additional context**
- Preserve `#row-` and `#text-` as we did [here](https://github.com/wp-media/wp-rocket/pull/4979) will fix the problem

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@piotrbak We have more and more exclusion to do like this one. I'm wondering if we should automatically keep all the time CSS IDs located in an inline CSS to avoid having to maintain a huge list of compatibility.

**Comment by piotrbak** [comment]
@GeekPress I think we're still fine there. The current situation is:
1. 6 exclusions related to dynamic CSS of Flatsome
2. 2 exclusions related to dynamic CSS of Gutenberg
3. 1 exclusion related to dynamic CSS of another plugin

There are also a couple of exclusions related to plugins/themes that need specific CSS ID in the source to work correctly (7).

I believe that the list won't grow much more, at least until other themes and plugins won't start using that kind of technique. For now, I'd just keep an eye on this as preserving all IDs will mean much more CSS in the source.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Add the selector `#row-` & `#text-` to the preserved pattern in WP_Rocket\ThirdParty\Themes\Flatsome::preserve_patterns

### Estimate the effort ✅
[xs]

**Comment by DahmaniAdame** [comment]
Related: https://secure.helpscout.net/conversation/1889616387/343840/

This case requires preserving `#banner-grid-`. 

At this point, it's clear that we are likely to have more of these cases. 

What makes us miss it so far is that the elements need to be customized in order for their accompanying style to show up.

Flatsome declares the dynamic IDs when it processes the shortcodes as follows:

```
'_id'             => 'image_' . rand(),
'_id'             => 'map-' . wp_rand(),
```

All the IDs currently excluded on https://github.com/wp-media/wp-rocket/blob/42cb23f01f5ee7def30b8827b5e77e7ae913b391/inc/ThirdParty/Themes/Flatsome.php#L29-L46 are located on the shortcodes directory `flatsome/inc/shortcodes/`.

It's safe to assume this is the pattern that creates the issues with RUCSS.

Searching through Flatsome, I found the full list of all dynamic IDs. 

```
#banner-
#banner-grid-
#cats-
#col-
#gallery-
#gap-
#image_
#instagram-
#map-
#page-header-
#pages-
#panel-
#portfolio-
#product-flip-
#product-grid-
#row-
#section_
#slider-
#stack-
#text-
#text-box-
#timer-
#title-
```

Adding a PR directly for the missing ones as they follow the same pattern: 

```
#banner-grid-
#cats-
#col-
#gallery-
#instagram-
#map-
#page-header-
#pages-
#panel-
#portfolio-
#product-flip-
#product-grid-
#stack-
#timer-
#title-
```

**Comment by DahmaniAdame** [comment]
@piotrbak regarding @GeekPress suggestion, maybe we can do as Jo said, but restrict that to specific themes. 

That would be one array referencing themes/plugins where we need to preserve inline style with IDs referencing a rand string or a timestamp. With a filter to control that array for flexibility.

It won't require individual compatibility files.

**Comment by piotrbak** [comment]
@DahmaniAdame Are you sure that after each of those strings we have `rand` functions?

**Comment by DahmaniAdame** [comment]
@piotrbak yes, 100% sure. I checked them all individually. They are all appended by either `rand()` or `wp_rand()` like the two examples I mentioned. I tested a few to make sure they behave the same as the others we are already listing (when personalized, the inline style is added to the page below the element).

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1894114754/344564/

Inline styles with `#col-` selectors needed to be preserved. 
Used this helper to resolve the problem: https://docs.wp-rocket.me/article/1694-prevent-inline-styles-from-being-removed-by-remove-unused-css

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1904615210/345963/

Preserved these selectors:
```
#text-
#col-
#gallery-
#section_
#stack-
#gap-
```
