### ISSUE TITLE
Serve images stored in url of inline style as WebP

### ISSUE THREAD

**Issue by njhowarth** [wp-media/wp-rocket#4993]
In situations where a background-image is stored in url of an inline style, e.g: 

<span style="background-image: url('https://www.mywebsite.com/wp-content/uploads/2020/09/image.jpg')" ></span>

It is not picked up by the RegEx used by WP Rocket that expects an =" or =' before the URL of the image. As a consequence, the WebP version of the image will not be loaded.

Request to include images stored in URL to be served as WebP images (where they exist.)

**Comment by piotrbak** [comment]
@njhowarth It seems to be a duplicate of https://github.com/wp-media/wp-rocket/issues/3511

If that's not, please reopen the issue with some more details.
