### ISSUE TITLE
An important bug in clear cache (Sometimes the logo and favicon are removed)

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#4994]
**Describe the bug**
Ever since opcache is removed, when I clear [clear cache](https://prnt.sc/brxIbc8wYIHo)(Or maybe [clearing the database](https://prnt.sc/8P_QuyxSxqzg)), sometimes the logo or favicon is deleted!
Please check this item. I have this problem on all my websites. There is such a problem even for colleagues. This problem has occurred exactly since opcache was removed. There was no such problem before.

**Two points :**
1-This bug sometimes occurs. Maybe once every 2 days. When I either clear the cache or clear the database
2- When the logo or icon is removed, it is not removed from within the WordPress media section. I have to re-select them from within the WordPress website identity section to display them again.
I hope you are aware of this bug. thanks

**Friends who experience this bug like me, please inform**

**Comment by piotrbak** [comment]
@Michaelgimii Please contact our Support Team, we'll be happy to investigate this further and find a solution.

**Comment by piotrbak** [comment]
No similar requests have been reported since one year. Going to close the issue
