### ISSUE TITLE
Enhance Heartbeat Control Plugin Conflict Notice

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4997]
**Is your feature request related to a problem? Please describe.**
When Heartbeat Control is enabled in WP Rocket and the standalone Heartbeat Control plugin is activated, we show a red conflict notice: https://jmp.sh/v8jfS4P

This is a bit confusing and in some cases customers have even deactivated WP Rocket instead of the Heartbeat plugin. 
In reality, the standalone plugin can be used, they just have to deactivate the Heartbeat feature in WP Rocket. 

**Describe the solution you'd like**
A less scary notice which educates the customer to deactivate the option in WP Rocket if they need to use the standalone plugin. We could include a link to the tab for convenience, or a button that deactivates the feature. 

**Additional context**
Related tickets: 
https://secure.helpscout.net/conversation/1867877436/340578/
https://secure.helpscout.net/conversation/1754858140/318863/
https://secure.helpscout.net/conversation/1742544395/316560/
https://secure.helpscout.net/conversation/1826610020/333653/
https://secure.helpscout.net/conversation/1744914912/316894/

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/2873371305/545496?viewId=377611
