### ISSUE TITLE
Varnish's cache of URL isn't cleared when UsedCSS generation is "complete"

### ISSUE THREAD

**Issue by ZnimonB** [wp-media/wp-rocket#4998]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :white_check_mark: 3.11.1
- Used the search feature to ensure that the bug hasn’t been reported before :white_check_mark:

**Describe the bug**

When UsedCSS is successfully generated (reaches "complete" status in Database), the cache of the URL is properly cleared:

https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/Engine/Cache/PurgeActionsSubscriber.php#L53

However, if Varnish is used, the cache of the URL won't be cleared at that time and the full CSS stays in Varnish Cache.

**To Reproduce**

1. In an environment where Varnish is used and RUCSS ist activated clear all UsedCSS and Cache in WP Backend (admin bar Buttons)
2. Open Database Table `wp_wpr_rucss_used_css`
3. Call Random URL (Your Status: Not logged in in WP backend)
4. See first entry of URL in `wp_wpr_rucss_used_css` with status `pending`
5. Wait for Cron and API doing its 'magic' until "status" is `complete` and UsedCSS is generated
6. Call the URL of point "3." again (Your Status: Not logged in in WP backend)
7. Url still is delivered from Varnish-Cache without UsedCSS and stays this way
8. Varnish gets not "cleared" in this case

**Expected behavior**

Varnish's cache should be cleared when UsedCSS generation is `complete` for this URL.

**Additional context**

You should hook `clean_file` to `rocket_rucss_complete_job_status` here:

https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/Addon/Varnish/Subscriber.php#L41-L47

It's pretty much the same like this one, just with another Hook: https://github.com/wp-media/wp-rocket/pull/4929

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by ZnimonB** [comment]
I'm using those two Hooks on our Websites and it works fine :). Would be great to have this in the Product, just to be save for Updates.

![image](https://user-images.githubusercontent.com/25100809/166437998-13562f4f-b70c-4dd8-976b-6033eb243657.png)

**Comment by remyperona** [comment]
Hi @ZnimonB,

Thank you for the report, we're going to add the missing hook to the existing PR to completely fix the issue. I'm going to close this issue as it's very similar to https://github.com/wp-media/wp-rocket/issues/4875

**Comment by ZnimonB** [comment]
Hi @Tabrisrp,

perfect. Thank you! :smiley:
