### ISSUE TITLE
bad link to "heartbeat.js"

### ISSUE THREAD

**Issue by andrii-bakulin** [wp-media/wp-rocket#4999]
In file `inc/Engine/Heartbeat/HeartbeatSubscriber.php` you have a bad link to `heartbeat.js` file

Need to remove the path in the asset folder. On frontend pages have bad link to this file.

PS: in the last version 3.11.1

**Comment by webtrainingwheels** [comment]
Another customer is reporting the same problem: https://secure.helpscout.net/conversation/1870486230/341007?folderId=377611

**Comment by alfonso100** [comment]
Another case here: https://secure.helpscout.net/conversation/1872230178/341231?folderId=2683093

**Comment by alfonso100** [comment]
Seems related to this line: 
https://github.com/wp-media/wp-rocket/blob/7c388fedbeb262485127b095edd27eabdc16b5d4/inc/Engine/Heartbeat/HeartbeatSubscriber.php#L69

**Comment by worldwildweb** [comment]
related https://secure.helpscout.net/conversation/1873200124/341359?folderId=5547167
