### ISSUE TITLE
 CDN on images with new Royal Slider remove all images

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#50]
When you enable CDN on images with Royal Slider enabled, it removes all the content of the div where there are usually the images.
Plugin is attached to the bug
Source : https://secure.helpscout.net/conversation/118475315/6471/

**Comment by webdados** [comment]
I can confirm this

![image](https://user-images.githubusercontent.com/6853605/31500286-ee344618-af5e-11e7-87d9-b13a872b4cb5.png)
