### ISSUE TITLE
Essential grid not updating when scheduled post is published

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#500]
Posts displayed in essential grid are not updated when a scheduled post is published, even if the page containing the grid is set to be always purged.

**Comment by piotrbak** [comment]
@Tabrisrp Do you remember which page builder was used for this issue?

**Comment by piotrbak** [comment]
@Tabrisrp I think we can close the issue, I don't think it's reproducible for now. If you think opposite, please feel free to reopen it. 🙏
