### ISSUE TITLE
[WIP] PHP Fatal error: Uncaught InvalidArgumentException: Unidentified action ... in ActionScheduler_DBStore.php on line 451

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5005]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

We have reports of PHP Fatal errors like the following one:
```
PHP Fatal error: Uncaught InvalidArgumentException: Unidentified action 222898 in /home/path/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php:451
Stack trace:
#0 /home/path/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php(120): ActionScheduler_DBStore->cancel_action()
#1 /home/path/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php(148): as_unschedule_action()
#2 /home/path/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php(152): as_unschedule_all_actions()
#3 /home/path/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php(61): WP_Rocket\Engine\Common\Queue\AbstractASQueue->cancel_all()
#4 /home/path/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controlle in /home/path/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php on line 451
```

This is likely happening because the action we are trying to cancel doesn't exist.

**To Reproduce**
N/A

**Expected behavior**

No PHP fatal errors should appear in the log.

**Additional context**

**Tickets:**
https://secure.helpscout.net/conversation/1869827503/340859/
https://secure.helpscout.net/conversation/1869687348/340842
https://secure.helpscout.net/conversation/1871435728/341107/
https://secure.helpscout.net/conversation/1871414605/341105/

**Slack Convo:** https://wp-media.slack.com/archives/C43T1AYMQ/p1651558351479639

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1871459805/341115/
it is `E_Error` in this case.

**Comment by alfonso100** [comment]
another case: https://secure.helpscout.net/conversation/1871543254/341131/
`Fatal error` in this case

**Comment by NataliaDrause** [comment]
Related:
Fatal error here:
https://secure.helpscout.net/conversation/1875479948/341684?folderId=3864740

**Comment by NataliaDrause** [comment]
Related:
https://secure.helpscout.net/conversation/1876112016/341764/
https://secure.helpscout.net/conversation/1875810385/341739

**Comment by vmanthos** [comment]
**Related:** https://secure.helpscout.net/conversation/1880861679/342468?folderId=2135277

**Comment by NataliaDrause** [comment]
Related:
https://secure.helpscout.net/conversation/1884162535/342969?folderId=3864740
https://secure.helpscout.net/conversation/1884016662/342948

**Comment by alfonso100** [comment]
related https://secure.helpscout.net/conversation/1886047187/343257?folderId=273766

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1896277937/344907/

**Comment by DahmaniAdame** [comment]
Possibly related - https://secure.helpscout.net/conversation/1947687050/355595?folderId=3864735
