### ISSUE TITLE
Add integration with StackPath CDN

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5007]
**Is your feature request related to a problem? Please describe.**
When using StackPath CDN, the StackPath's network cache can't be cleared directly from our CDN tab.

**Describe the solution you'd like**
Add a button to clear StackPath CDN cache when we detect (in the CDN CNAME) a site is using their CDN service. This would allow customers to easily clear the CDN cache within WP Rocket, similar to what's possible with Cloudflare.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1868754208/340692?folderId=2675957

Useful resource shared by customer: https://stackpath.dev/docs/stackpath-api-quick-start.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
