### ISSUE TITLE
Remove WP Rocket's options from Elementor templates

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5010]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (3.11.1)
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
Elementor has an option to create/use templates, but we are not creating any cache file/folder for them since this content is not publicly visible and thus, displaying the WP Rocket options on the _Edit_ screen and the _Clear this cache_ button doesn't apply.

**To Reproduce**
-

**Expected behavior**
The _Clear this cache_ button and the WP Rocket options from the _Edit_ screen of Elementor templates should **not** be displayed.

**Screenshots**
Clear this cache button: https://share.getcloudapp.com/YEur9X9D
WP Rocket options: https://share.getcloudapp.com/rRu1ekZ5

**Additional context**
Having these options available creates confusion to our customers.
Related ticket: https://secure.helpscout.net/conversation/1870181424/340939

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
Hello everyone 👋 🥰

Can we also extend this to other post types with `public` and/or `publicly_queryable` as `false`? 

Example: WooCommerce coupons.

![image](https://user-images.githubusercontent.com/5751474/174004500-7f972092-b555-4ea5-bd57-9890dd7d0895.png)

The following is a screenshot from a custom post type for emails where `'public' => false,` and `'publicly_queryable' => false,`

![image](https://user-images.githubusercontent.com/5751474/174004948-35f71c7a-2e65-48e0-859b-3dfa286beb9f.png)

**Comment by piotrbak** [comment]
Hey @arunbasillal thanks for your comment! That sounds good, I'll create a new issue to cover it.

**Comment by aaryandeveloper** [comment]
@viobru Please tell me How to find WP Rocket Options on Template page
