### ISSUE TITLE
RUCSS compatibility with Jevelin theme

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5018]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We need a comptibility with Jevelin theme. When it's activated, dynamic inline stylesheets containing `#heading-` should be preserved in the source.

Jevelin code can be found for example [here](https://github.com/michaelnas84/renatastreit.com.br/trunk/wp-content/themes/jevelin).

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/167126834-d9b63488-a218-4698-8e56-9fc4d138d88a.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Create a ThirdParty class for Jevelin theme to preserve dynamic selector `#heading-`
Add tests too.

### Estimate the effort ✅
[s]
