### ISSUE TITLE
Missing $component in function args

### ISSUE THREAD

**Issue by mnemotiv** [wp-media/wp-rocket#502]
https://github.com/wp-media/wp-rocket/blob/8ba5d822fee18e006b84d8253a2adf3574e7f2bc/inc/functions/formatting.php#L195

Missing $component in function args?

**Comment by mnemotiv** [comment]
@Tabrisrp

**Comment by Tabrisrp** [comment]
thank you you're correct, it's fixed

**Comment by mnemotiv** [comment]
@Tabrisrp even if you expect $component arg always be provided like now, in your case I'd default it to = -1, like child function does it. In case if it will be always used in future as back-compat replacement for (wp_)parse_url, otherwise you'd get: WARNING Missing argument 2 for rocket_extract_url_component()

**Comment by mnemotiv** [comment]
as I see on 2.11 you're still using wp_parse_url ...

**Comment by Tabrisrp** [comment]
We're using `wp_parse_url()` directly when we don't need to extract one specific component of the URL
