### ISSUE TITLE
CDN feature is rewriting .cfm URls

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#5020]
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When a .cfm url is present in the page, like: https://webdev3.regent.edu/support/give/online.cfm it is rewritten to: https://CDNURL.com/support/give/online.cfm

Maybe we should add it here: https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/CDN/CDN.php#L281-L285

**To Reproduce**
1. Add a .cdm URL in the site, like an anchor element.
2. Enable CDN feature
3. See error

**Expected behavior**
This kind of URLs shouldn't be rewritten.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/167187117-651212e6-50a0-485c-9e13-77c46e4c9f9b.png)
----- VS -----
![image](https://user-images.githubusercontent.com/13713107/167187032-9aeefd9f-3e94-4d91-808d-c3729b5fd08c.png)

**Additional context**
Relevant case: [https://secure.helpscout.net/conversation/1873668670/341421?folderId=3963184](https://secure.helpscout.net/conversation/1873668670/341421?folderId=3963184)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
Add `cfm` to the `$excluded_extensions` array in `CDN::is_excluded()` method

### Estimate the effort ✅
Effort `[XS]`
