### ISSUE TITLE
Action Scheduler missing tables notice may show up incorrectly

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5021]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
The [missing action scheduler warning](https://github.com/wp-media/wp-rocket/blob/d6ac32fa837a6446ae788fe6c9640a0d5cf39928/inc/Engine/Optimization/RUCSS/Admin/Settings.php#L291) is showing up persistently on a customer's site. 

The tables are in fact in the database, but there are also duplicates (source unknown), which seem to trigger the warning:
https://jmp.sh/coWsNUk
(I have removed the db prefix)

**To Reproduce**
1. Activate WP Rocket
2. Create duplicate action scheduler tables
3. See error message

**Expected behavior**
WP Rocket should only show the warning when the required tables are really not there. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1869443219/340827?folderId=377611

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by poolet08** [comment]
Experiencing the same issue on our site this morning after the latest update. We were a few updates behind but everything seems to be working but that error is persistent at the top.

**Comment by DahmaniAdame** [comment]
The extra tables seem to be backups. They will always contain a number. 

If we replaced the SQL we do here - https://github.com/wp-media/wp-rocket/blob/1e4ad9da4e138dc018d9d29eee9eab20fb409abe/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L126-L128

with: 

```
"SHOW TABLES FROM ".DB_NAME." WHERE Tables_in_".DB_NAME." LIKE '%actionscheduler%' AND Tables_in_".DB_NAME." NOT REGEXP '[0-9]+'";
```

This will grab any table containing `actionscheduler` and will exclude any table with numbers from the results. 

We should get an accurate number of tables, even if backups are present on the database.

**Comment by alfonso100** [comment]
related: https://secure.helpscout.net/conversation/1937660459/351837/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1925806544/349562/

**Comment by manfredinicolas** [comment]
We still have the issue with new version

**Comment by mapsteps** [comment]
+1. I just updated to version 3.12.1 and this pops up on all of my sites 😮

**Comment by oscarwerther** [comment]
updated to version 3.12.1 and this pops up on all of my sites -> here too
rolled back to 3.11.5 and no errors -> please fix that

**Comment by AriGolden** [comment]
Same problem here with 3.12.1.

**Comment by piotrbak** [comment]
@manfredinicolas @MapSteps @oscarwerther @AriGolden Please follow the following issue:
https://github.com/wp-media/wp-rocket/issues/5440

The message doesn't affect how WP Rocket works, it's an UI problem only.
