### ISSUE TITLE
Umami.js needs to be excluded from Minification by default

### ISSUE THREAD

**Issue by d19dotca** [wp-media/wp-rocket#5024]
**Describe the bug**
When Minification is enabled, Umami.js (an analytics tracker, alternative to Google Analytics & Matomo) fails to run properly. I must exclude it on each site from WP Rocket Minification in order for it to work properly. Requesting that the umami.js script be excluded by default as this will surely affect all customers using Umami for data collection / website analytics.

Umami script looks something like this:

<script async defer data-website-id="<UUID>" src="https://<UmamiHostname>/umami.js"></script>

When minification is enabled, it of course adds the data-minify="1" to it too.

Can learn more about Umami here: https://umami.is/docs/collect-data

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a Umami tracker script to a website2. 
2. Run WP Rocket to clear cache and enable Minification
3. Preload cache, and test if script is running (can confirm if analytics show up in Umami server)
4. You should see that no data is collected using the script.
5. Exclude umami.js from Minification, then clear and preload cache again and test - you should now see it works correctly

**Expected behaviour**
Umami analytics script should work without needing to modify WP Rocket, as it'd require every site under management by an admin to have to exclude that script, and any mistakes in missing it will be a loss of important website metrics.

**Screenshots**
N/A

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @d19dotca and thank you for the PR. When it passes the CR and QA, it'll be released in the new minor version.

**Comment by d19dotca** [comment]
Hi @piotrbak - I noticed this doesn't seem to be included in the WP Rocket update on June 30th... any reason why this wasn't included? Judging based on the changelog at least.
