### ISSUE TITLE
The delay javascript option interferes with the menu cart elementor widget.

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5025]
**Describe the bug**
The menu cart elementor widget does not open properly when I enable this option. After the first click on it, a # is added to the url. 

**To Reproduce**
1- Use the menu cart elementor widget
2- Make sure the hello elementor template is enabled
3- Enable the delay javascript option and then try to open the menu cart.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
