### ISSUE TITLE
RUCSS - Preloaded fonts are not rewritten to the CDN

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5028]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.2`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

During tree-shaking we preload fonts that we find in the used CSS:
https://github.com/wp-media/wp-rocket/blob/3a5b9b11dbda004854d54a4f07dc4ddc95bf2dbc/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L254

If CDN rewriting is activated, we are not rewriting the URLs of the preloaded fonts. This leads to duplicate loading of font files:
![](https://i.vgy.me/IfVqhy.jpg)
Full-Scale image > https://i.vgy.me/IfVqhy.jpg

**To Reproduce**

1. Enable Remove Unused CSS.
2. Enable CDN rewriting.
3. Check the source code of the page. The preloaded fonts will not point to the CDN.

**Expected behavior**

Preloaded fonts should be rewritten to the CDN if that's activated.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1874123205/341463?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
### Scope a solution
To fix this issue there was to way:
- Change the priority from the CDN action. However i didn't found anyway to make this solution possible.
- Replace the font url when adding it.

For that we will call the filter `rocket_asset_url` at the [line 655](https://github.com/wp-media/wp-rocket/blob/3a5b9b11dbda004854d54a4f07dc4ddc95bf2dbc/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L655) from the `UsedCSS` class to remplace the font url with the cdn one.

### Estimate effort
Effort `XS`
