### ISSUE TITLE
Create a possibility to define RUCSS environment in constant

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5029]
**Is your feature request related to a problem? Please describe.**
In Imagify, when we want to use develop environment we can easily define it in the constant. We should do the same for RUCSS

**Describe the solution you'd like**
Add that kind of check:
```
if ( ! defined( 'WP_ROCKET_CACHE_ROOT_URL' ) ) {
	define( 'WP_ROCKET_CACHE_ROOT_URL', WP_CONTENT_URL . '/cache/' );
}
```
here:
https://github.com/wp-media/wp-rocket/blob/81e5b989f9f4af1d7933c9637a3ca8e444578099/inc/Engine/Optimization/RUCSS/AbstractAPIClient.php#L14

**Additional context**
It'll allow us to test the changes quicker.

**Comment by CrochetFeve0251** [comment]
You can use `WP_ROCKET_SAAS_API_URL` to change this url.
