### ISSUE TITLE
Load CSS files asynchronously compatibility with Flatsome Theme

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#503]
Load CSS files asynchronously can't be compatible with Flatsome theme on mobile. I follow the tutorial "Render-blocking Javascript and CSS " but still broken on mobile. I excluded the css files but didn't work out. Can you guys test it and make sure it works with Flatsome.

**Comment by piotrbak** [comment]
We haven't heard about this issue for some time already. The Load CSS Asynchronously changed during this time too. Please feel free to repoen this issue with more details if needed.
