### ISSUE TITLE
RUCSS - Automatically allowlist the SaaS in Cloudflare Bot Fight Mode

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5032]
**Is your feature request related to a problem? Please describe.**

In some cases Remove Unused CSS cannot be created because Cloudflare Bot Fight Mode blocks our SaaS.

Currently, only paying Cloudflare customers can[ bypass restrictions](https://developers.cloudflare.com/bots/get-started/pro/).

**Describe the solution you'd like**

Automatically allowlist the SaaS in Cloudflare Bot Fight Mode.

**Describe alternatives you've considered**

Connect with Cloudflare and ask them to automatically allowlist our SaaS in Cloudflare Bot Fight Mode.

**Additional context**

**Related:** #5030
**Slack Convo:** https://wp-media.slack.com/archives/C029G1B5HD2/p1652177676248359

**Comment by engahmeds3ed** [comment]
We would need to fill Cloudflare Bot safelisting form here: https://docs.google.com/forms/d/e/1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA/viewform

I'm discussing with JB and Mostafa the details to be provided and will subit the form once I get all required info.

**Comment by engahmeds3ed** [comment]
For @piotrbak action:

@mostafa-hisham Changed the user-agent header from the SaaS to be a real browser and this solved the issue and I believe he confirmed that with @vmanthos 

I think we don't need to submit the form above, what do u think?

**Comment by vmanthos** [comment]
Just a note on my part. 

Yesterday with Mostafa we couldn't replicate the Bot Fight Mode issues, i.e. BFM blocking used CSS generation, on my test site. 

In retrospect, the only thing that was different yesterday compared to when I checked this on my own was that I installed the official Cloudflare plugin after the checks.

I'm adding this detail here in case we need to revisit this in the future.

**Comment by mostafa-hisham** [comment]
in my opinion this issue should be closed
the fix we implemented 20days ago worked fine
and i don't think we faced it again

**Comment by piotrbak** [comment]
Okay, let's close it and get back to it if reoccurs
