### ISSUE TITLE
Polylang and the mandatory cookie enhancement

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5035]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Rocket sets the mandatory cookie `pll_language` when Polylang uses the browser language detection feature. 

Browser language detection only works on the homepage to allow language redirection.

If you visit an inner page, Polylang sets the cookie to have the language of the link. This is not an issue. It's done by design. 

According to Polylang, a direct visit to the inner page indicates that the user is searching the site in a particular language - https://wordpress.org/support/topic/automatic-page-redirect-to-language-based-on-location/

Because of the mandatory cookie, inner pages will skip caching if they are the entry point to the site.

Caching the mandatory cookie on inner pages has no benefit, since there will not be a redirection to the browser's language, and the inner page in question will only have one version. 

Ideally, we should limit the mandatory cookie check for the homepage only on Polylang. 

Testing without the mandatory cookie, Polylang manages to process the redirection if the following setting is unchecked: 

```
URL Modification > Hide URL language information for default language
```

As an alternative, we could just watch for this setting, and do the mandatory cookie for the main language homepage only in this scenario while disabling it in all other cases.

**To Reproduce**
1. Use Polylang
2. Enable browser language detection
3. See that the cookie is set to the page's language and not the browser's language, which nullifies the need of using the mandatory cookie for inner pages

**Expected behavior**
Inner pages shouldn't require getting the uncached version of the page when visited first. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1877286393/341942?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
A somewhat related ticket here: https://secure.helpscout.net/conversation/2078306898/384539?folderId=2675957

This site is using Varnish and Polylang and this is causing issues with Used CSS generation. Varnish is not respecting mandatory cookie and cache is being served immediately while WP Rocket cache is not until the cookie is set. Secondary visit to the same page will keep hitting Varnish until that one is cleared. So this is not triggering Used CSS generation.
Used CSS is generated only when a page is accessed while the cookie is set and varnish cache is not present for that page. This happens during normal site browsing after varnish is cleared.
Customer is not seeing Used CSS applied until a while later after clearing varnish.

Limiting mandatory cookie to the main homepage only may help to avoid issues like this.

Slack: https://wp-media.slack.com/archives/C08N8J6VC/p1669648458858489

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
