### ISSUE TITLE
After the recent update, the database size decreased

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5036]
hi @piotrbak , After the recent update, the volume of my website database was reduced from 36 to 10 mb. I wanted to ask if this was due to the wp-rocket update? thanks

**Comment by piotrbak** [comment]
@Michaelgimii Hello, thanks for creating the issue. Please remember that we use GitHub for development purposes. Your question should go directly to our beloved Support Team. To answer your question, yes, our update most likely casued this.

Thank you.
