### ISSUE TITLE
Backend safelist for RUCSS exclusions

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5038]
**Is your feature request related to a problem? Please describe.**
It's a plugin part of the following issue:
https://github.com/wp-media/rucss-backend/issues/5

**Describe the solution you'd like**
WP Rocket needs to fetch specific exclusions from the remote server. It's about `inline_atts_exclusions`, `inline_content_exclusions` arrays.

**Additional context**
We need to make sure:
1. Fallback is used when there's no connection between site and our servers
2. Make sure that the exclusions are updated when they were fetched from the servers and then the connection is lost
3. Easy way to refetch the data from server (cleaning transients?)

**EDIT**
@Tabrisrp is right, Jo prepared the epic card for it before, it can be seen here:
https://github.com/wp-media/wp-rocket/issues/3602

**Comment by mostafa-hisham** [comment]
**Initial solution discussed with @piotrbak** 

- when RUCSS starts connecting with the backend API to fetch the updated exclusion list
- create a Transient that will store the RUCSS exclusion list, and save the list in a JSON file as a backup if we cannot reach the backend api.
- on the next RUCSS request going to check if there is data in the Transient and use it
- after the Transient is expired fetch backend API to get the latest exclusion list OR fetch it from JSON file as a fallback

**Cons**
- Users can accidentally remove the fallback JSON file 
- getting the data from two different sources (Transient, JSON) it will make the code very complicated 

**Bigger Picture Problem**
If we are going to implement this solution with the other exclusion lists in the other optimizations (defer js, delay js,.....)
we are going to do the same thing over and over for each active optimization which will create more load on the database
and trying to connect to the server to fetch the data will slow things down 

**Other solution**
- in the backend when we update in execution list or anything that the plugin is going to use we can create an API that returns the `last update` as a timestamp
- Create a cron job that checks if the `last update `stored in the plugin does not match the backend `last update`  (we can set interval as we see fit)
- Save the exclusion lists in DB (WP options) and then use them on each optimization

**Comment by remyperona** [comment]
Shouldn't the implementation of this be very similar to https://github.com/wp-media/wp-rocket/issues/3602 but simplified for just those parts?

**Comment by piotrbak** [comment]
Related PR from backend repo:
https://github.com/wp-media/rucss-backend/pull/6
