### ISSUE TITLE
RUCSS - Inline Related Posts widget breaks due to dynamic inline selector

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5041]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
The Inline Related Posts plugin adds inline style with a selector like this `.u7cb7434f55ddbc61829903e3a7b5fb85`. 
The numeric-letter value is dynamic and the layout breaks when cache is refreshed, but Used CSS is still referencing an old selector.

There is unfortunately no unique `content` we can trigger. The style tag doesn't have any `id` or `attribute`.

The inline style looks like this:
![image](https://user-images.githubusercontent.com/60236665/168095244-b800d188-2621-4f2e-9371-0da92b7614f8.png)
Screenshot: https://i.imgur.com/EtuGf2Q.png

`.ctaText` is probably the only `content` we could use, but it is not unique.

**To Reproduce**
1. Install and activate **Inline Related Posts** plugin;
2. Save settings for the plugin - can be used default;
3. Create a post and add Related Posts module with a block;
4. Enable Remove Unused CSS option;
5. Used CSS will include the initial dynamic selector.
6. After cache is cleared the selector will change and styling will be missing.

**Expected behavior**
The style for the Related Posts module needs to be preserved.

**Additional context**
Plugin: Inline Related Posts https://wordpress.org/plugins/intelly-related-posts/
80 000 installations

Ticket: https://secure.helpscout.net/conversation/1875506582/341695/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Yes, we'll need a separate class for that one.

**Comment by mostafa-hisham** [comment]
After checking the plugin code
there are no filters or options provided in the plugin that we can use to preserve the style in a good way
the solution implemented by @NataliaDrause in the [ticket](https://secure.helpscout.net/conversation/1875506582/341695/) 
is the only thing that we can do to keep the dynamic styles

**Scope a solution**
- create Third-party compatibility  `InlineRelatedPosts` in  `/inc/ThirdParty/Plugins`
- check if plugin is installed defined( 'IRP_PLUGIN_SLUG' )
- subscribe to filter 'rocket_rucss_inline_content_exclusions' and preserve '.centered-text-area'
- create unit and integration tests

**Estimate the effort** 
Effort [S]

**Comment by NataliaDrause** [comment]
Only the Pro version had the `.centered-text-area` selector, so this might be specific for that site only.

`.ctaText` is present in both: pro and free versions. So this one might be a better one.
