### ISSUE TITLE
Defer inline scripts

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5042]
**Is your feature request related to a problem? Please describe.**
It's possible to defer inline JavaScript code by transforming it to the following data scheme `data:text/javascript`. 

This should help preserve the order of execution and less dependency on exclusions since everything will be deferred at once. 

It will benefit more websites with extensive exclusions from Delay JavaScript Execution and Defer JS.

The more scripts deferred, the faster the painting process will be. 

**Describe the solution you'd like**
Extend JavaScript deferring to inline scripts. 

**Describe alternatives you've considered**
N/A

**Additional context**
R&D. No case or direct request for that.
@piotrbak sending you a working prototype hooked to the buffer on Slack if you want to test it!

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future if planned to implement it
