### ISSUE TITLE
Delay JavaScript Execution compatibility with Ajax Search Pro

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5045]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
[Ajax Search Pro](https://ajaxsearchpro.com/) plugin doesn't work if jQuery is excluded from Delay JavaScript Execution. 

No console error is showing. But when trying to search, no results are showing.

The issue is not there if jQuery is not excluded from Delay JavaScript Execution. 

Excluding the following fixes the issue: 

```
ajax-search-pro
```

**To Reproduce**
1. Use Ajax Search Pro
2. Exclude jQuery from Delay JavaScript Execution 
3. See error

**Expected behavior**
Ajax Search Pro should work out of the box even if jQuery is excluded from Delay JavaScript Execution. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1880959611/342473

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by benorfaz** [comment]
No more jQuery dependency with this plugin
