### ISSUE TITLE
Automatic preloading of fonts

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5047]
**Describe the solution you'd like**

We can now manually put the desired font links in wp-rocket to be preloaded. But it would be great if the fonts were preloaded automatically. In fact, this feature will save time as well as better performance.

**Comment by JerissCloudCenter** [comment]
I'm not part of the WP Rocket team but how do you expect to implement this? Some times need preloading some fonts, some not at all. If you mean that we should automatically preload all fonts, then absolute no on my side as it would give worse performance (too many requests blocking the first paint/rending of the page).

**Comment by piotrbak** [comment]
@Michaelgimii @jeriss-cloud-center Automatic preload of the fonts is implemented within the new Remove Unused CSS feature. You can read more about it here and learn how to disable it, etc.:
https://docs.wp-rocket.me/article/1529-remove-unused-css#preload-fonts
