### ISSUE TITLE
RUCSS to preserve inline CSS for the Ultimate Addons for WPBakery Page Builder

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5051]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The Ultimate Addons for WPBakery Page Builder uses dynamic selectors by setting a random string: 

```
$id = uniqid( wp_rand() );
```
![image](https://user-images.githubusercontent.com/1289174/168765792-7d2a7754-1902-487a-9036-a2f5068de63d.png)

When cache is regenerated, the string will change, causing the RUCSS to miss some style.

The following selectors are affected by that mechanism: 

```
#ultib3-
.uvc-wrap-
```

Excluding `rocket_rucss_inline_content_exclusions` fixes the issue.

**To Reproduce**
1. Use a Ultimate Addons for WPBakery Page Builder
2. Add an Element from their list and change CSS
3. Use RUCSS

**Expected behavior**
Elements using dynamic selectors should look properly.

**Screenshots**
Added to the description. 

**Additional context**
https://secure.helpscout.net/conversation/1882744112/342781/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@piotrbak this one is straightforward and won't need grooming. Should I add the PR directly?

**Comment by piotrbak** [comment]
@DahmaniAdame yes please, great

**Comment by DahmaniAdame** [comment]
@piotrbak PR added.
