### ISSUE TITLE
WP Rocket Rollback not working

### ISSUE THREAD

**Issue by dreamjobma** [wp-media/wp-rocket#5057]
When trying to rollback WP Rocket from 3.11.2 to 3.10.9, we have the following message:

<img width="707" alt="wp rocket rollback error" src="https://user-images.githubusercontent.com/49077367/169031189-60ddb033-eb6c-41cc-a830-f5e521d810aa.png">

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/1888476610/343643/

**Comment by GeekPress** [comment]
It's fixed.
