### ISSUE TITLE
Add Missing Dimensions doesn't work when XCurrent plugin is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5059]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 3.11.2
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
Add Missing Dimensions doesn't work when XCurrent plugin is enabled

**To Reproduce**
1. Install and activate [XCurrent](https://xwp.co/)
2. Enable WPR Add Missing Image Dimensions
3. WP Rocket Add Missing Dimensions does not work
4. Deactivate XCurrent
5. WP Rocket Add Missing Dimensions works

**Expected behavior**
WP Rocket Add Missing Dimensions should work when the plugin XCurrent is activated

**Screenshots**

**Additional context**
helpscout ticket: https://secure.helpscout.net/conversation/1883600886/342908

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
