### ISSUE TITLE
Add Missing Dimensions doesn't work when JetPacks Speed up image load times is enabled

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5060]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅  3.11.2
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 
 
**Describe the bug**
Add Missing Dimensions doesn't work when JetPacks Speed up image load times is enabled

**To Reproduce**

1. Install and activate [JetPacks](https://wordpress.org/plugins/jetpack/)
2. Enable JetPacks Speed up image load times /wp-admin/admin.php?page=jetpack#/performance
3. Enable WPR Add Missing Image Dimensions
4. WP Rocket Add Missing Dimensions does not work

**Expected behavior**
WP Rocket Add Missing Dimensions should work when the JetPacks option Speed up image load times and XCurrent are enabled

**Screenshots**
![Screenshot 2022-05-19 at 11 34 25](https://user-images.githubusercontent.com/1954918/169262538-fb7abc74-74c0-4a6a-b84b-fea6d7022851.png)

**Additional context**
helpscout ticket: https://secure.helpscout.net/conversation/1883600886/342908
The issue can also be fixed by using the [WP Rocket | Image Dimensions for picture and external images helper plugin](https://github.com/wp-media/wp-rocket-helpers/raw/master/various/wp-rocket-media-image-dimensions-picture-external-images/wp-rocket-media-image-dimensions-picture-external-images.zip)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1896903503/344999

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
