### ISSUE TITLE
Fusion Form 403 Error with Delay JavaScript execution

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5062]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
When Delay JavaScript execution is enabled, and even after user interaction, the Fusion Builder form will throw a 403 error when submitting the form.

**To Reproduce**
1. With Delay JavaScript execution enabled, go to a page with a Fusion Builder form. Example: https://akoestiekspecialist.nl/contact/.
2. Fill the form and submit the info
3. From will show a "There was an error sending your message. Try again later" error and a 403 error in admin-ajax.php
![image](https://user-images.githubusercontent.com/23031592/169347574-dac35248-789f-42af-8e74-859bbfff32b8.png)

Only if you exclude the following, the form sending will work:
`/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js`
`/jquery-migrate(.min)?.js`
`/fusion-builder/assets/js/min/general/fusion-form.js`
`/fusion-builder/assets/js/min/general/fusion-form-logics.js`
`/Avada/includes/lib/assets/min/js/library/cssua.js`
`/Avada/includes/lib/assets/min/js/general/fusion.js`
`/Avada/includes/lib/assets/min/js/library/modernizr.js`

**Expected behavior**
The exclusions are set in Avada's compatibility file: /inc/ThirdParty/Themes/Avada.php

**Additional context**
@alfonso100 saw that the fusion-builder/assets/js/min/general/fusion-form.js script is dynamically inserting a nonce, which value is included in the response payload. When this script is delayed, the nonce is not set, even after interaction, the payload will include `undefined` instead of the nonce value, and the 403 error will happen.

See without error: https://jmp.sh/tgg8stj - When the error happens `fusion_form_nonce:` value is
`undefined`.

Related ticket: https://secure.helpscout.net/conversation/1885949041/343242?folderId=2675957

Thanks!

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Will be fixed with the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
