### ISSUE TITLE
Enable Separate cache for mobile devices when JetMenu is used

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5063]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
JetMenu recommends using the Separate cache files for mobile devices to avoid responsive issues for their Megamenu. 

https://crocoblock.com/troubleshooting/articles/cannot-make-jetmenu-mega-menu-mobile-responsive/

This can be confirmed by diffchecking mobile vs. desktop.

![image](https://user-images.githubusercontent.com/1289174/169477315-88bc4353-1aee-4e01-b941-6a0a6c06a154.png)

To prevent the issue, we should add: 
```
jet-menu/jet-menu.php
```
to: 
https://github.com/wp-media/wp-rocket/blob/c2e2a2405cc03ff5a8cc6873325dc81b8647de4a/inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php#L331-L352

**To Reproduce**
1. Enable JetMenu
2. Check the difference in markup between mobile and desktop

**Expected behavior**
JetMenu should be cached properly.

**Screenshots**
Added to the description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1888674702/343703/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
Note: I did test before, separate cache will not cover all cases.

In one case i need to set separate cache as tablet instead of mobile [WP Rocket | Set Tablets As Mobile](https://github.com/wp-media/wp-rocket-helpers/blob/50ba7f182b531db302bf793f0d622ac1069a1f77/cache/wp-rocket-cache-tablet/wp-rocket-cache-tablet.php)

Extra Info: separate cache can be avoided if user decided to duplicate that menu for mobile and desktop

**Comment by DahmaniAdame** [comment]
@mehedihasanziku thank you for your feedback. 

> In one case i need to set separate cache as tablet instead of mobile WP Rocket | Set Tablets As Mobile

This is more of an edge case and is likely related to the responsive breakpoints set by the theme and how the menu fits in the layout. 

> Extra Info: separate cache can be avoided if user decided to duplicate that menu for mobile and desktop

That would be an action/decision required from the user. We try to make things work out of the box as much as possible.

**Comment by vmanthos** [comment]
@DahmaniAdame Do you happen to have a copy of the JetMenu plugin? I need to use that for QA.

**Comment by DahmaniAdame** [comment]
@vmanthos no, I don't. But I can ask the customer if they can provide the plugin for testing.

**Comment by vmanthos** [comment]
>  I can ask the customer if they can provide the plugin for testing.

I "fake-installed" JetMenu by creating an empty `jet-menu/jet-menu.php` plugin. As long as that's the correct file for the plugin we should be good.

But it would be best to test this with the actual plugin. If you don't mind, please ask for it.
