### ISSUE TITLE
RUCSS wrong home_url detection with WPML enabled

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#5065]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
With RUCSS we have SaaS dedicated queue for home pages so we need to detect if the current page is the home page and send this info to SaaS to operate it quickly.
We send this info in two requests:-
1. POST request to add the url to the queue and get the job details here: https://github.com/wp-media/wp-rocket/blob/3a5b9b11dbda004854d54a4f07dc4ddc95bf2dbc/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L215-L222
2. GET request to get the job/url details here: https://github.com/wp-media/wp-rocket/blob/3a5b9b11dbda004854d54a4f07dc4ddc95bf2dbc/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L500

When WPML is enabled, let's assume that we have two languages (EN/DE) with the following urls:-
**Default EN home:** https://example.org/
**DE home:** https://example.org/de

The problem will happen with the `DE home`, so when visiting this page for the first time, `home_url()` will return true as the page is opened and WPML hooks are applied on it so this condition will return true https://github.com/wp-media/wp-rocket/blob/3a5b9b11dbda004854d54a4f07dc4ddc95bf2dbc/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L434

But with the GET request, this check returns `false` and to make it works we need to use the following filter
```
apply_filters( 'wpml_home_url', home_url() )
```

**To Reproduce**
1. Activate WPML
4. Add two languages as mentioned above
5. Visit the secondary language home page.
6. This page will not have the used_css and will reach the failed status after three retries

**Expected behavior**
Used CSS should be available for this page.

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1887544004/343505/

**Comment by engahmeds3ed** [comment]
As a temporary solution, we can use the following code to disable connecting to home SaaS queue
```
add_filter( 'http_request_args', function( $args, $url ) {
	if (  'https://saas.wp-rocket.me/rucss-job' !== $url ) {
		return $args;
	}

	if ( isset( $args['body'] ) && isset( $args['body']['is_home'] ) ) {
		$args['body']['is_home'] = false;
	}
	if ( isset( $args['body'], $args['body']['config'], $args['body']['config']['is_home'] ) ) {
		$args['body']['config']['is_home'] = false;
	}

	return $args;
}, 10, 2 );
```

**Comment by engahmeds3ed** [comment]
# Grooming

## Reproduce the problem
Yes I saw this issue on the customer's site.

## Identify the root cause
As mentioned in the issue, the whole problems comes from `is_home` request parameter.

## Scope a solution
We have two options here:-
1. **Hard option:** Add a new column in the DB usedcss table called `is_home` and when getting the job_id from SaaS we need to set it and use it on the other GET request to check the job status. This will make this request argument identical for each url.
2. **Easy option:** add new filter here: 
https://github.com/wp-media/wp-rocket/blob/3a5b9b11dbda004854d54a4f07dc4ddc95bf2dbc/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L434

like that:
```
return apply_filters( 'rocket_rucss_is_home_url', ( untrailingslashit( $url ) === untrailingslashit( home_url() ) ), $url );
```

and then in the third party compatibility 
https://github.com/wp-media/wp-rocket/blob/aeecf2a5ce679124f65dd37305571770c305113c/inc/3rd-party/plugins/i18n/wpml.php#L12-L11

we can add callback on this new filter:
```
add_filter( 'rocket_rucss_is_home_url', function( $is_home, $url ){
    $home_url = apply_filters( 'wpml_home_url', home_url() );
    return untrailingslashit( $url ) === untrailingslashit( $home_url );
}, 10, 2 );
```

and here we need to refactor the WPML thirdparty compatibility file to the new architecture.

and I'm with the second easy option.

## Estimate the effort
[S] for the easy option.
[M] for the hard one.

**Comment by alfonso100** [comment]
another case: https://secure.helpscout.net/conversation/1894560161/344647?folderId=2683093
the [filter](https://github.com/wp-media/wp-rocket/issues/5065#issuecomment-1133745028) fixed the problem thank you Ahmed!

**Comment by NataliaDrause** [comment]
Likely related: https://secure.helpscout.net/conversation/1921362375/348655?folderId=3864740

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1922725461/348914

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1929109608/350179/
