### ISSUE TITLE
Exclude WooCommerce cookies from cache

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5069]
**Describe the bug**
hi wp-rocket team!
I use the recently viewed WooCommerce query on my website. This query no longer works properly when I enable wp-rocket.
So I removed the cookie (woocommerce_recently_viewed) from the cache and the problem was solved.
If possible, please exclude this cookie from the cache by default in wp-rocket. This is really a very small task that can be solved in the next version.

**To Reproduce**

If you use a recently viewed query on your WooCommerce website, enable wp-rocket at the same time, this query will have trouble displaying products.
If you enter **woocommerce_recently_viewed** in Advanced Rules > Never Cache Cookies, the problem will be resolved. So, please exclude this cookie from cache by default in wp rocket. thanks a lot

**Comment by Joliamendi** [comment]
+1
I also experience this problem with installing rockets.
hi @piotrbak, Please check this issue , thanks!

**Comment by piotrbak** [comment]
Hello @Michaelgimii thanks for creating the issue. 

Could you tell me which plugin are you referring to?

Basically, to get it to work with full caching properly, you'd need to update that kind of widgets with ajax, there's no other way (of course except preventing the cache from beign generated with the cookie is present).

Your solution is not perfect, as the cookies are stored for some time and the browser with that cookie won't receive cached page for this period of time.

**Comment by Michaelgimii** [comment]
hi @piotrbak, thanks for the reply.
I'm using the jet woobuilder plugin, and with this plugin I can display recently viewd products. This plugin exactly follows WooCommerce and uses the woocommerce_recently_viewed cookie. Therefore, caching this cookie in wp-rockrt causes a problem. So I think if you exclude this cookie from the cache, the problem will be solved.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
