### ISSUE TITLE
Drop RUCSS resources table completely with old RUCSS shutdown date

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#5075]
**Is your feature request related to a problem? Please describe.**
With old RUCSS shutdown at 30th of May 2022, we need to completely delete the resources table.

**Describe the solution you'd like**
With update we need to run raw query to drop this table and delete all related table class and schema from the code.
Don't forget the delete the table version row from options table that's added by BerlinDB.

**Describe alternatives you've considered**
Even if for any reason the user rolled back to older version, this table will be created (not to trigger any error on the customer's site) but the feature itself will not work.

**Additional context**
None

**Comment by remyperona** [comment]
I think we should do that in 3.12, this kind of actions fit better in a major release
