### ISSUE TITLE
Clear RUCSS after a while when the feature is deactivated

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5076]
**Is your feature request related to a problem? Please describe.**

Currently, the only auto-clearing mechanism we have is `rocket_rucss_clean_rows_time_event` which we turn off after the feature is deactivated. I assume the same logic will remain when we move to the filesystem (data will still be kept in that scenario as well).

We are not clearing RUCSS data to make sure the Used CSS will still be there if the feature is re-used after being deactivated. 

We don't cover the scenario where the feature will be turned off long-term or if the customer decides to stop using it (low CSS on original files, seeing that CPCSS is enough, issues that will need time to be fixed).

**Describe the solution you'd like**
We could have a background process that prompts a message after let's say 3 days to confirm why the feature was deactivated:
- If it's temporary, we can ask them to open a ticket if there is an issue or need help
- If they don't need/feel like using the feature, we can ask them to clear RUCSS stored data (database/filesystem), and maybe collect their reasons

Alternatively, we can keep the `rocket_rucss_clean_rows_time_event` alive when the RUCSS is disabled by: 
- Adding conditions to check if the database still has Used CSS on it.
- Shortening the `delete_old_items()` life cycle (set to 1 month) as it makes sense to get clear the data sooner. A Week for example.

**Describe alternatives you've considered**
N/A

**Additional context**
Slack convo - https://wp-media.slack.com/archives/G01AMD70N7P/p1653459048671429

**Comment by piotrbak** [comment]
@wp-media/php It would make sense to keep `rocket_rucss_clean_rows_time_event` enabled when the function is deactivated. It should not cause any issues, what do you think? 🤔
