### ISSUE TITLE
RUCSS to preserve inline CSS for the Unlimited Elements plugin

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5085]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.2
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
I am creating this GH issue to collect all the dynamic selectors issues related to the [Unlimited Elements](https://nl.wordpress.org/plugins/unlimited-elements-for-elementor/) plugin. Possibly we can see a common pattern in these cases.

Current case has Post Carousel widget which styles are added with a dynamic id selector like `#uc_uc_card_post_carousel_elementor13280`:
![image](https://user-images.githubusercontent.com/60236665/170439530-18975d07-c876-4405-9865-6f07cfe628f8.png)

Unlimited Elements plugin may have many other widgets that use dynamic selectors.

This case has a trigger: `/wp-content/plugins/unlimited-elements-for-elementor/assets_libraries/owl-carousel-new/owl.carousel.min.js`

Another case [here](https://github.com/wp-media/wp-rocket/issues/5083) is similar but has no file trigger, there is only inline script.

We had more reports of the dynamic selector here:
https://github.com/wp-media/wp-rocket/issues/4166#issuecomment-901855725
https://github.com/wp-media/wp-rocket/issues/4166#issuecomment-999334465

**To Reproduce**
Reproduced on customer's site that uses the widget.
Example in the ticket: https://secure.helpscout.net/conversation/1896704647/344944/#thread-5610986172

**Expected behavior**
Preserved dynamic styles.

**Additional context**
Issue is resolved by preserving `#uc_uc_card_post_carousel_elementor` with `rocket_rucss_inline_content_exclusions` filter.

Ticket: https://secure.helpscout.net/conversation/1896704647/344944/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
@piotrbak I could submit another PR for the current case as done [here](https://github.com/wp-media/wp-rocket/pull/5084). 
But let me know if maybe we should approach it differently, since this plugin may have a big variety of dynamic selectors.

**Comment by piotrbak** [comment]
@NataliaDrause We don't have any other way so far. I was trying to find in the PHP the pattern to locate all dynamic classes, but I wasn't able so far. Do you happen to know that?

**Comment by piotrbak** [comment]
Okay, after investigation we need a separate class for this plugin.

If it's enabled, or its pro version is enabled, we need to preserve the styles that contain:
`#uc_`

**Comment by jeawhanlee** [comment]
Checked the plugin to see if I could find other selectors with prefix having dynamic suffixes that we could also preserve alongside `#uc_` but couldn't find any.

### Scope a solution
So going with @piotrbak. We will Create a Thirdparty Class, check if plugin is installed `UNLIMITED_ELEMENTS_INC` then hook to `rocket_rucss_inline_content_exclusions` and preserve `#uc_` and finally add tests.

### Estimate the effort
Effort [S]

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1922007950/348761/
