### ISSUE TITLE
Preload Fonts: Change Preload Font Order

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#5088]
**Is your feature request related to a problem? Please describe.**
Preload Fonts using `wp_head` hook doesn't look good (it's parsing later) , it's not improving CLS significantly.

**Describe the solution you'd like**
It should be added right after `</title>`

**Describe alternatives you've considered**
Maybe a filter to control it's position, but ultimately not needed, it should be right after `</title>` . This thing considered on various plugins like Autoptimize/Perfmatters etc

**Additional context**
Easy to test by hooking css in `wp_head` and observe fonts loading.

Preload font added right after `</title>` if RUCSS is activated. but i don't like this feature though, that's another conversation, but for depthness of requested feature i mentioned it here.

I know it's not flagged in PSI, but it will improve CLS for sure.

**Comment by mehedihasanziku** [comment]
@piotrbak sorry, I know lots of critical issue ongoing, but this should be considered to Improve CLS

**Comment by piotrbak** [comment]
@mehedihasanziku Helllo and thanks for creating this one. We'll check the real impact of this change, I'll let you know.

**Comment by piotrbak** [comment]
Fixed in the 3.13.1:
https://github.com/wp-media/wp-rocket/issues/4215
