### ISSUE TITLE
CDN rewrite URL query string in certain cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5093]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
CDN rewrite URL query string which contains domain part

**To Reproduce**
1. Use the following script with your domain name `<script type="text/javascript" src="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/minify_js_issues.js?domain=https://new.rocketlabsqa.ovh&uuid=a334ff7567f29a1047ddb578baf4dc230689285d"></script> `
2. Enable CDN
3. Check source => domain query string is rewritten to CNAME

**Expected behavior**
Query string part from the URL is not changed

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
