### ISSUE TITLE
Custom Polylang flags can display too big on the frontend

### ISSUE THREAD

**Issue by wp-seopress** [wp-media/wp-rocket#510]
Custom flags in admin bar need some CSS to restrict height/width to avoid this (see screenshot)
![rocket](https://user-images.githubusercontent.com/30056254/30127758-9c5249d8-9340-11e7-8ee2-69c495815499.jpg)

**Comment by wp-seopress** [comment]
Doesn't work if admin bar is displayed on frontend

**Comment by Tabrisrp** [comment]
Reopening per previous comment. We don't want to load any CSS on the front-end, so we probably need to edit the image markup directly to force a max-width/height everywhere

**Comment by piotrbak** [comment]
Closing it for now until we'll have information about the specific themes or situation where it happens
