### ISSUE TITLE
Update Broken Link in Plugin's First Activation Notice

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5102]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
There is a 404 error in the [correctly-measure-websites-page-load-time](https://wp-rocket.me/blog/correctly-measure-websites-page-load-time/?utm_source=wp_plugin&utm_medium=wp_rocket) link in the first activation notice. in the plugins page

**To Reproduce**

1. Install and activate WP Rocket for the first time 
2. Click on "Test your load time" in the notice:
![image](https://user-images.githubusercontent.com/23031592/171295378-9be101a6-1f16-4c42-9cab-3f13f47917e4.png)
Link:  https://wp-rocket.me/blog/correctly-measure-websites-page-load-time/?utm_source=wp_plugin&utm_medium=wp_rocket link.
3. Get a 404 error: https://jmp.sh/6EXX9yW.

**Expected behavior**
We should use the right link, [probably here.](wp-rocket/views/deactivation-intent/form.php](https://github.com/wp-media/wp-rocket/blob/94bfacd2122ed61def7ef3f780ba17e0cd920022/views/deactivation-intent/form.php#L116)

@webtrainingwheels noticed the query string breaks the link/redirect because when visiting https://wp-rocket.me/blog/correctly-measure-websites-page-load-time, the redirect to https://wp-rocket.me/blog/how-to-test-wordpress-site-performance-measure-speed-results/ works. 

Additional context
Ticket:  https://secure.helpscout.net/conversation/1904522975/345946/

Thanks!

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@GeekPress Can we resolve this on the website's side? Or should it be corrected in WP Rocket code?

**Comment by GeekPress** [comment]
> @GeekPress Can we resolve this on the website's side? Or should it be corrected in WP Rocket code?

Sorry I missed the notification.

Better to fix from the plugin to avoid a redirection.
