### ISSUE TITLE
Clear cache when Brooklyn theme enables/disables their maintenance mode

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5106]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the Brooklyn theme toggles its maintenance mode, it doesn't trigger cache clearing on our side. 

This will create a stalling page showing the wrong maintenance state. 

**To Reproduce**
1. Enable Brooklyn maintenance mode
2. Visit the site and see we are still sending the non-maintenance page
3. The same applies if the cache is cleared after the maintenance mode is enabled. Once disabled, we will still be sending the maintenance page

**Expected behavior**
WP Rocket should reflect the maintenance mode change on the front end.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1899555969/345357

I couldn't find any public documentation with possible actions that could be used to trigger cache clearing on WP Rocket's side when maintenance mode is enabled/disabled.

Asked the customer if the Brooklyn team can add the integration on their side by using our `rocket_clean_domain()` function is changed or to provide an action that might help with detect that - https://github.com/wp-media/wp-rocket/blob/95d626766fe72bdb1a49f39070bd9846598181d9/inc/functions/files.php#L710-L785

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
