### ISSUE TITLE
Lazyload compatibility with Masonry grids

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5107]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When lazyload is used with a masonry grid, the grid doesn't render properly: 

The grid will render as: 

![image](https://user-images.githubusercontent.com/1289174/171570718-d609405f-d8c0-4324-a698-d10d88b99347.png)

Instead of: 

![image](https://user-images.githubusercontent.com/1289174/171570766-3e09c76c-8366-40e8-bff7-cc6e5a73606d.png)

This is caused by the placeholder. It doesn't have an explicit height and width. Consequently, images' position calculations will make them overlap. 

Using the `add missing images dimensions` feature fixes the issue. 

However, we should have an alternative in case the `add missing images dimensions` is not needed on the website and to make sure lazyload works properly in this scenario out of the box. 

Explicitly adding to the placeholder should fix the issue. 

We already adding them as part of the `viewBox` in some cases, but this is not taken into consideration while building the masonry grid. 

https://github.com/wp-media/wp-rocket/blob/95d626766fe72bdb1a49f39070bd9846598181d9/inc/Dependencies/RocketLazyload/Image.php#L609-L624

The following should fix the issue: 

```
$placeholder = str_replace( ' ', '%20', "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='$width' height='$height' viewBox='0 0 $width $height'%3E%3C/svg%3E" );
```

We still need to always report the `height` and `width` as it's sometimes retuned as `0`, which won't help fix the issue automatically. 

**To Reproduce**
1. Use a masonry grid without images dimensions
2. Enable lazyload
3. See error

**Expected behavior**
The grid should render properly without having to do further actions. 

**Screenshots**
Added to description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1899173846/345318

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
