### ISSUE TITLE
Minify JS compatibility with Sparxpres for WooCommerce

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5108]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version `3.11.2`
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
[Sparxpres for WooCommerce](https://wordpress.org/plugins/sparxpres-for-woocommerce/) widget is not properly displayed on the product page when Minify JS files is enabled.

This pattern exclusion is necessary:
`/sparxpres-for-woocommerce/assets/js/(.*)
`

**To Reproduce**
1. Add a widget to a product page + minify JS without any exclusions
2. See error

**Expected behavior**
The widget should work without requiring any exclusions.

**Screenshots**
Display issue:
![Image 2022-06-01 at 3 50 33 PM](https://user-images.githubusercontent.com/26235782/171620480-b20fc3c2-1874-4639-b688-f07ea2c70358.jpg)
Full-size image: https://share.getcloudapp.com/yAu1W0bR

How it should look like:
![Image 2022-06-02 at 1 21 22 PM](https://user-images.githubusercontent.com/26235782/171620576-71c3e993-bd2b-49b6-93b9-23d616f5c122.jpg)
Full-size image: https://share.getcloudapp.com/yAu1o8Q6

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1896992111/345019/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1654163358298909

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closing it in favor of:
https://github.com/wp-media/wp-rocket/issues/5109
