### ISSUE TITLE
Files modified with filemtime are not getting processed

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#5112]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Customer is using [Imperva cache](https://www.imperva.com/products/cdn-caching/), and to clear the cache on Imperva they have to use .filemtime function during enqueue_style, because the filename must be different, parameter after URL ?ver= is not enough.

Code used to add a .filemtime during enqueue_style:

$t_shiva = '.'.filemtime(get_theme_file_path().'/assets/css/shiva.css');
wp_register_style('shiva-style', get_template_directory_uri().'/assets/css/shiva'.$t_shiva.'.css', array(), null); wp_enqueue_style('shiva-style');

generates : `<link rel="stylesheet" id="shiva-style-css" href="https://www.shiva.fr/wp-content/themes/shiva-hd/assets/css/shiva.1652347674.css" type="text/css" media="all">
`

With htaccess rewrite rules: RewriteRule ^(.*)\.[\d]+\.(css|js)$ $1.$2 [L]
it redirect to https://www.shiva.fr/wp-content/themes/shiva-hd/assets/css/shiva.css.

When .filemtime function is used WP Rocket produce the following error in debug log: Couldn’t get the file path from the URL.
It happens both for JS, and CSS files, and WP Rocket can't minify those files or optimize them using Remove unused CSS

**To Reproduce**

**Expected behavior**
Files to be optimized by WP Rocket.

**Screenshots**
Screenshot of the errors are available in this ticket: https://secure.helpscout.net/conversation/1887273282/343463/

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1887273282/343463/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
