### ISSUE TITLE
Minify CSS whitespace removal affects calc()

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5118]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
When CSS minification is enabled, some whitespace is removed in `calc` functions which breaks them. 
This is known to affect the popular Total theme (50 000 sales on themeforest)

Here is the code diff between unminified and minified files: 
https://www.diffchecker.com/UEJPlszI

The result is that padding spacing is not as expected - compare the widths of the text areas here: 
correct: https://jmp.sh/uZs7k4k
incorrect: https://jmp.sh/bZClc9E

**To Reproduce**
1. Use Total theme or apply the following CSS: 
`.wpex-vc-full-width-row--centered {
 padding-left:calc((((100vw - var(--wpex-vc-full-width-offset, 0px) - 100%) / 2) - (var(--wpex-vc-gutter) / 2) - (var(--wpex-vc-column-gap) / 2)));
 padding-right:calc((((100vw - var(--wpex-vc-full-width-offset, 0px) - 100%) / 2) - (var(--wpex-vc-gutter) / 2) - (var(--wpex-vc-column-gap) / 2)))
}`
2. Activate Minify CSS
3. Observe the difference in padding spacing

Note on the ticket contains link to the theme and sample HTML for testing: 
https://secure.helpscout.net/conversation/1898589236/345252?folderId=377611#thread-5663415911

**Expected behavior**
calc functions which are sensitive to whitespace should not be touched by minification

**Additional context**
Seems similar to this issue - https://github.com/wp-media/wp-rocket/issues/1554 which was previously resolved.
Slack conversation: https://wp-media.slack.com/archives/C43T1AYMQ/p1654541849673169
Ticket: https://secure.helpscout.net/conversation/1898589236/345252?folderId=377611
The related file in Total is: `/themes/Total/assets/css/wpex-wpbakery.css`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by eriktdesign** [comment]
I believe I'm experiencing the same issue on one of our client's sites.

Here's a snippet from the SASS:
`--hero-bottom: calc(var(--hero-bottom-height, #{rem(100px)}) + #{rem(40px)});`

Rendered out to CSS:
`--hero-bottom: calc( var(--hero-bottom-height, 100px) + 40px );`

And here is what happens when WP Rocket tries to minify:
`--hero-bottom:calc(var(--hero-bottom-height,100px)+40px);`

This breaks the css `calc` function as noted above -- the `+` operator requires a space on either side. I'm unable to use Minify CSS until this is resolved.

Thanks!

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
