### ISSUE TITLE
Cancel RocketCDN subscription

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#5121]
**Is your feature request related to a problem? Please describe.**

There are 2 ways to stop a RocketCDN subscription: 
- from the WP Rocket plugin, CDN tab
- from the account pages of WP Rocket, RocketCDN Billing tab

We would like to keep only one of these 2 ways. 

**Describe the solution you'd like**

In the WP Rocket plugin, CDN tab, remove the `Manage Subscription` link.

![Capture d’écran 2022-06-08 à 15 32 19](https://user-images.githubusercontent.com/48359715/172629368-ad4c164c-3e20-40ff-a20a-b6ccd33180be.png)

**Comment by jeawhanlee** [comment]
We can remove this method `WP_Rocket\Engine\CDN\RocketCDN\AdminPageSubscriber::display_manage_subscription` and also remove related tests here `WP_Rocket\Tests\Integration\inc\Engine\CDN\RocketCDN\AdminPageSubscriber`
