### ISSUE TITLE
Usage of rocket_use_native_lazyload filter breaks some images when LazyLoad is enabled

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5126]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
In some cases when our filter `rocket_use_native_lazyload` is used and our LazyLoad is enabled, we apply double lazy-load on images.
The attribute `loading=lazy` is present as well as LazyLoad attributes.

Screenshot from the customer's site:
![image](https://user-images.githubusercontent.com/60236665/172856634-56f5b335-0905-4242-ba6f-9763e8ad5b82.png)

This breaks some images:
![image](https://user-images.githubusercontent.com/60236665/172856940-fa92062c-9224-4f77-9277-897d60191797.png)

and some cases are already mentioned here: https://github.com/wp-media/wp-rocket/issues/4961

**To Reproduce**
It was reproduced on a customer's site where theme was using `rocket_use_native_lazyload` filter and LazyLoad for images was enabled. 
I was not able to reproduce the issue on my test site.

**Expected behavior**
Images should not break. There should not be a duplicative lazy-load applied to images.

**Additional context**
Slack thread with more details and screenshots: https://wp-media.slack.com/archives/C43T1AYMQ/p1654777415067329
Ticket: https://secure.helpscout.net/conversation/1913047242/347171/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Possibly related: https://secure.helpscout.net/conversation/1914004737/347338?folderId=3864740

`loading=lazy` attribute is present along with our LazyLoad

**Comment by endcoreCL** [comment]
Is there any quickfix for this issue? We do not use the filter `rocket_use_native_lazyload`.

*edit*

adding `add_filter( 'rocket_use_native_lazyload', '__return_true' );` will fix the issue for us.

**Comment by remyperona** [comment]
First screenshot is as expected when native lazyload is enabled.

Second screenshot is using background image on a div element, which is going to use the JS lazyload always. The code looks ok, but possibly since it looks like a kind of carousel, it's not working correctly?

**Comment by remyperona** [comment]
Looking at the JS library repo, enabling use native prevents background images lazyload from working with our current code implementation: https://github.com/verlok/vanilla-lazyload/issues/439

We will need to update the code to make it work based on the proposed solution in this issue.
