### ISSUE TITLE
Limiting critical CSS to the latest item is not sufficient

### ISSUE THREAD

**Issue by smerriman** [wp-media/wp-rocket#5128]
When WP Rocket generates critical CSS for posts, it creates it solely based on the most recent post - same for pages, categories, etc.

Our site displays posts from a particular category in a different style to posts in other categories.

When critical CSS is regenerated, this results in completely wrong critical CSS being applied to a large set of posts.

It appears the only option is to disable critical CSS generation entirely, and manually create it - as well as recreating it every time a change is made to the theme.

WP Rocket's code doesn't even include a single filter that lets me append information to the existing critical CSS to make sure it covers both categories.

What is the recommended solution here?

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future, RUCSS is recommended feature.
