### ISSUE TITLE
Defer JS compatibility with LayerSlider

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5131]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Layer Slider is used with Defer JS, the following error shows up: 

```
ReferenceError: lsjQuery is not defined
    at https://domain.ext/:3206:1
ReferenceError: lsjQuery is not defined
    at https://domain.ext/:3244:1
```

The issue is coming from the inline script declaring `lsjQuery`. 

```
<script data-cfasync="false" type="text/javascript">window.addEventListener('DOMContentLoaded', function() {var lsjQuery = jQuery;});</script>
```

Since it's not deferred, it will cause a dependency error.

Excluding jQuery from defer fixes the issue. 

We need a compatibility file for that.

**To Reproduce**
1. Use LayerSlider
2. Enable Defer JS
3. See error

**Expected behavior**
LayerSlider should work out of the box.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1913530507/347269

Deferring inline scripts fixed that dependency issue: https://github.com/wp-media/wp-rocket/issues/5042

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
