### ISSUE TITLE
Preload website images automatically in wp rocket

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5134]
**Is your feature request related to a problem? Please describe.**
no, Request a new feature

**Describe the solution you'd like**

Preloading images has a tremendous effect on increasing the loading speed of the website. So great if you add this feature. I do not know, maybe you already have a plan for it. If yes, is it clear in which version this feature will be added?
Thank you in advance for your answer

**Comment by lukecav** [comment]
https://docs.wp-rocket.me/article/1494-preload-largest-contentful-paint-image

**Comment by piotrbak** [comment]
Hello @Michaelgimii and @lukecav automatically preloading images and excluding them from lazy load is on our roadmap and it'll be implemented this year.

**Comment by Michaelgimii** [comment]
hello @piotrbak ,I am very excited about this feature. Is the release version of this feature specified? A good news?

**Comment by Michaelgimii** [comment]
Hi @piotrbak, Any news on this feature?
