### ISSUE TITLE
Enhancing browser cache for pages

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5135]
**Is your feature request related to a problem? Please describe.**
We currently use `max-age=0` on cached pages. 

This forces the browser to always revalidate the page before using it from cache.

Though the overhead is not much (involves only the headers), it is still a request that shouldn't necessarily be sent on every revisit of the page.

**Describe the solution you'd like**

We can use `max-age=60` in addition to `stale-while-revalidate=540` instead.

What this does is:

- If the page is revisited within 60 seconds, it will be returned directly from the browser cache.
- If the page is revisited between 1 and 10 minutes timeframe, the first visit will be directly returned from the browser cache. At the same time, the browser will send a request to revalidate in the background.
- 10+ minutes will go directly to revalidation.

This won't compromise how cache operates while sparing the continuous check for the page's freshness.

Ideally, we could have a filter controlling that part to give the ability to control pages `cache-control` to suit the website's needs. 

For mostly static websites, the `max-age` and `stale-while-revalidate` pair can be set for a longer period. 

For highly dynamic websites, the `max-age` and `stale-while-revalidate` pair can be set for a shorter period or switched to `max-age=0`.

The filter can also be used to set different `cache-control` for specific pages if needed (can be easily translated to `htaccess` rules if needed).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by thekendog** [comment]
So if I'm testing something and purge the URL from the cache, I have to wait 60 seconds to see my change?

**Comment by DahmaniAdame** [comment]
@thekendog this is just a concept yet to be tested and validated.
The idea is to limit unnecessary requests to origin to revalidate the content when content is static and revisited in a short period of time.
If it behaves as expected and proves to enhance things, there will likely be a filter to change the figures. Possibly a testing mode now that you brought that detail to the table.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
