### ISSUE TITLE
Clear cache for additional categories when %category% is used in permalinks

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5148]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a site is using this permalink structure: ` /%category%/%postname%/`
and a post is added into 2 categories, WordPress will allow to visit the post using any category as follows:
```
https://example.com/cat-1/post
https://example.com/cat-2/post 
https://example.com/cat-3/post 
```
WP Rocket will generate a different cache for each one of these: https://i.imgur.com/FHg5dRO.png

However, when the post is updated, we will clear only the cache of the 1st category, but not any additional cached slugs leading to outdated contents for such additional cached files.  

**To Reproduce**
1. Change the permalinks structure to be ` /%category%/%postname%/`
2. Create a post, and assign it to two or more categories
3. Visit each category of the post to generate the cache: **https://example.com/cat-1/post** , **https://example.com/cat-2/post** etc 
4. We will create a different cache for each URL.
5. Update the post. Only the cache of the 1st category will be cleared.
 
**Expected behavior**
We should clear every cached category when this kind of permalinks structure is used

**Screenshots**
![FHg5dRO](https://user-images.githubusercontent.com/229406/173928308-ea7a6eac-0c86-4bea-acb4-7233b4697c21.png)

https://i.imgur.com/FHg5dRO.png

**Additional context**
ticket: https://secure.helpscout.net/conversation/1918504989/348129
slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1655144941735589

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue (3). We might reopen this in the future.
