### ISSUE TITLE
Remove WP Rocket's options from not public post types

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5149]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the post type is not `public` we should not display:
1. `Clear this cache` button on the view listing all CPT entries
2. `Clear This Post` button from top menu while editing the post
3. `Purge this URL` button from the top menu while viewing the post when logged-in as admin

Per:
https://github.com/wp-media/wp-rocket/issues/5010#issuecomment-1157295620

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
Thanks for opening this @piotrbak.

- If post type is not `public`, the post will not have a view when logged-in as admin. So point 3 will not exist for these posts. 

- If the post type uses classic editor, then these posts will still have the `Clear Cache` button in the `Publish` meta box. (Screenshot available in https://github.com/wp-media/wp-rocket/issues/5010#issuecomment-1157295620)
