### ISSUE TITLE
Hardcode lazyload placeholder single quotes to avoid conflicts

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5150]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We use the following placeholder when lazyloading images: 

```
data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2029%2027'%3E%3C/svg%3E
```

The single quotes holding the values might conflict if an image is added inside a JavaScript function using single quotes. 

Here is an example:

```
jQuery(".single-product .custom_cart_button_cls .button").html('<img width="29" height="27" src="/path/to/image/1.png" alt="" style="margin-right: 10px;"> X');
```

Will result in the following: 

```
jQuery(".single-product .custom_cart_button_cls .button").html('<img width="29" height="27" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2029%2027'%3E%3C/svg%3E" alt="" style="margin-right: 10px;" data-lazy-src="/path/to/image/1.png"><noscript><img width="29" height="27" src="/path/to/image/1.png" alt="" style="margin-right: 10px;"></noscript> X');
```

The code is closed in the wrong location, causing a console error and breaking the JavaScript code.

Relacing: https://github.com/wp-media/wp-rocket/blob/3dbcee1ebc09f0d92d13db7677139abad87bc37a/inc/Dependencies/RocketLazyload/Image.php#L613

With: 

```
$placeholder = str_replace( array(' ', "'"), array('%20', '&quot;'), "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 $width $height'%3E%3C/svg%3E" );
```

Tested by using the `rocket_lazyload_placeholder` filter. 

Note: There is an entity for single quotes `&apos;` but it doesn't seem to be valid. Thus picking the `&quot;` which will be interpreted by the browser and shouldn't cause any issue even if it's inside a double quote.

**To Reproduce**
1. Enable lazyload
2. Use a JavaScript function that holds an image inside single quotes
3. See error

**Expected behavior**
Lazyload shouldn't create conflicts if the image is located inside single quotes.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1915321489/347568

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
