### ISSUE TITLE
Varnish add-on doesn't purge when Polylang is set up to work with multiple domains

### ISSUE THREAD

**Issue by reuhno** [wp-media/wp-rocket#5152]
Hello,

On multilanguage site with multiple domains set up with Polylang and Cloudflare, clean cache don't send purge request to secondary domain.

When flushing cache for individuals page, eg `/wp-admin/admin-post.php?action=purge_cache&type=post-1234&_wpnonce=xxx` this does not work either. Every request is sended with this header :

```
Array
(
    [method] => PURGE
    [blocking] => 1
    [redirection] => 0
    [headers] => Array
        (
            [host] => www.my-main-domain.fr
            [X-Purge-Method] => regex
        )

)
```

_Since cloudflare is enabled, the localhost address is used as the purge url (which is correct)._ 

**To Reproduce**

1. Install polylang and set 2 domains: one domain per language
2. Install Cloudfare
3. Enable WP Rocket Varnish Addon
4. On WP Rocket / WordPress admin bar, click on **"Clear cache" > "All languages"** or on **"Clear cache" > "EN"** (if your main site is FR)

**Expected behavior**
Flush command should be triggered for all domain names but `$parse_url['host']`  (_inc/Addon/Varnish/Varnish.php_ in `rocket_varnish_purge_headers` filter) always has the value of the main domain.

As a temporary and incomplete fallback solution I made this function to trigger flush when using this menu :

```
add_filter( 'rocket_varnish_purge_headers', 'custom_purge_for_en' );

function custom_purge_for_en($params) {
  if(function_exists('pll_current_language')){
    $lang = pll_current_language('slug');
    if ($lang =="en"){
      $params['host'] ='www.other-domain.com';
    }
  }
  
  return $params;
}
```

This solution works for individual flush (page, post) and for global flush (click on **"Clear cache" > "EN"**) but it doesn't work for 
**"Clear cache" > "All languages"** 

Can you understand the problem I have? It is not easy to explain.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future. We might get back to it at some point though.
