### ISSUE TITLE
Delay JavaScript Execution compatibility with Divi's fake jQuery

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5153]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When Divi's jQuery Body feature is enabled, it adds the following script on the page: 

```
<script type="text/javascript">
			let jqueryParams=[],jQuery=function(r){return jqueryParams=[...jqueryParams,r],jQuery},$=function(r){return jqueryParams=[...jqueryParams,r],$};window.jQuery=jQuery,window.$=jQuery;let customHeadScripts=!1;jQuery.fn=jQuery.prototype={},$.fn=jQuery.prototype={},jQuery.noConflict=function(r){if(window.jQuery)return jQuery=window.jQuery,$=window.jQuery,customHeadScripts=!0,jQuery.noConflict},jQuery.ready=function(r){jqueryParams=[...jqueryParams,r]},$.ready=function(r){jqueryParams=[...jqueryParams,r]},jQuery.load=function(r){jqueryParams=[...jqueryParams,r]},$.load=function(r){jqueryParams=[...jqueryParams,r]},jQuery.fn.ready=function(r){jqueryParams=[...jqueryParams,r]},$.fn.ready=function(r){jqueryParams=[...jqueryParams,r]};</script>
```

When used with Delay JavaScript Execution, the following error:

```
Uncaught SyntaxError: Identifier 'jQuery' has already been declared
    at (index):4:5344
    at new Promise ()
    at RocketLazyLoadScripts._transformScript ((index):4:5036)
    at async RocketLazyLoadScripts._loadScriptsFromList ((index):4:5437)

VM50:2 Uncaught ReferenceError: jqueryParams is not defined
    at :2:1
    at (index):4:5344
    at new Promise ()
    at RocketLazyLoadScripts._transformScript ((index):4:5036)
    at async RocketLazyLoadScripts._loadScriptsFromList ((index):4:5437)
```

Excluding `jqueryParams` from Delay JavaScript Execution fixes the issue. 

The file adding that script is the following: 

```
/wp-content/themes/Divi/includes/builder/feature/JQueryBody.php
/**
	 * Fake jQuery in head when jQuery body option is true.
	 */
	public function add_jquery_sub() {
		global $shortname;

		$jquery_compatibility_enabled = 'on' === et_get_option( $shortname . '_enable_jquery_compatibility', 'on' ) ? true : false;

		if ( $this->should_move_jquery() && $jquery_compatibility_enabled ) {
			echo '<script type="text/javascript">
			let jqueryParams=[],jQuery=function(r){return jqueryParams=[...jqueryParams,r],jQuery},$=function(r){return jqueryParams=[...jqueryParams,r],$};window.jQuery=jQuery,window.$=jQuery;let customHeadScripts=!1;jQuery.fn=jQuery.prototype={},$.fn=jQuery.prototype={},jQuery.noConflict=function(r){if(window.jQuery)return jQuery=window.jQuery,$=window.jQuery,customHeadScripts=!0,jQuery.noConflict},jQuery.ready=function(r){jqueryParams=[...jqueryParams,r]},$.ready=function(r){jqueryParams=[...jqueryParams,r]},jQuery.load=function(r){jqueryParams=[...jqueryParams,r]},$.load=function(r){jqueryParams=[...jqueryParams,r]},jQuery.fn.ready=function(r){jqueryParams=[...jqueryParams,r]},$.fn.ready=function(r){jqueryParams=[...jqueryParams,r]};</script>';
		}
	}
```

The feature can be checked if enabled using: 

```
global $shortname;
et_get_option( $shortname . '_enable_jquery_body' );
```

It can be used to selectively do the exclusion.

**To Reproduce**
I couldn't trigger the script to show up on a test website. 
I might be missing something. 
Part of the condition to show the script is enabled "Defer jQuery And jQuery Migrate" on Divi > Divi Theme Options > General > Performance. 

That covers `$jquery_compatibility_enabled`. 

I couldn't find a way to satisfy that part - `should_move_jquery()`. 

Will leave it to QA to check.

**Expected behavior**
There shouldn't be any console error when Delay JavaScript Execution is used and the fake jQuery script is injected by Divi. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1916981466/347884/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by MokterHossan89** [comment]
<script type="text/javascript">
			let jqueryParams=[],jQuery=function(r){return jqueryParams=[...jqueryParams,r],jQuery},$=function(r){return jqueryParams=[...jqueryParams,r],$};window.jQuery=jQuery,window.$=jQuery;let customHeadScripts=!1;jQuery.fn=jQuery.prototype={},$.fn=jQuery.prototype={},jQuery.noConflict=function(r){if(window.jQuery)return jQuery=window.jQuery,$=window.jQuery,customHeadScripts=!0,jQuery.noConflict},jQuery.ready=function(r){jqueryParams=[...jqueryParams,r]},$.ready=function(r){jqueryParams=[...jqueryParams,r]},jQuery.load=function(r){jqueryParams=[...jqueryParams,r]},$.load=function(r){jqueryParams=[...jqueryParams,r]},jQuery.fn.ready=function(r){jqueryParams=[...jqueryParams,r]},$.fn.ready=function(r){jqueryParams=[...jqueryParams,r]};</script>

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
