### ISSUE TITLE
There has been a critical error on this website. Please check your site admin email inbox for instructions.

### ISSUE THREAD

**Issue by nmohanan** [wp-media/wp-rocket#5156]
php(89): WP_Rocket\\ThirdParty\\Plugins\\ModPagespeed->has_pagespeed_with_cache(),wp-includes/class-wp-hook.php(307): 
WP_Rocket\\ThirdParty\\Plugins\\ModPagespeed->show_admin_notice('')\n#5 wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#6 
WP-Rocket plugin showing critical error on the WordPress admin. can you please check.

**Comment by piotrbak** [comment]
Hello @nmohanan thanks for creating the issue.

Have you already contacted our support team so we could take a look at the problem?

**Comment by nmohanan** [comment]
Not yet, please provide an email id to contact.

**Comment by piotrbak** [comment]
Please contact us here and would be great to mention that it's related to this specific issue:
https://wp-rocket.me/support/

**Comment by stefanoginella** [comment]
I recently started getting this error message on a client site hosted on WP Engine.
Now I can't open the settings page. I just noticed today.


```
PHP Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /<redacted>/wp-includes/functions.php:5834\nStack trace:
#0 /<redacted>/wp-includes/functions.php(5834): in_array('mod_pagespeed', NULL, true)
#1 /<redacted>/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/ModPagespeed.php(52): apache_mod_loaded('mod_pagespeed', false)
#2 /<redacted>/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/ModPagespeed.php(37): WP_Rocket\\ThirdParty\\Plugins\\ModPagespeed->has_pagespeed()
#3 /<redacted>/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/ModPagespeed.php(89): WP_Rocket\\ThirdParty\\Plugins\\ModPagespeed->has_pagespeed_with_cache()
#4 /<redacted>/wp-includes/class-wp-hook.php(307): WP_Rocket\\ThirdParty\\Plugins\\ModPagespeed->show_admin_notice('')
#5 /<redacted>/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 /<redacted>/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#7 /<redacted>/wp-admin/admin-header.php(303): do_action('admin_notices')
#8 /<redacted>/wp-admin/admin.php(239): require_once('/nas/content/li...')
#9 /<redacted>/wp-admin/options-general.php(10): require_once('/nas/content/li...')
#10 {main}\n thrown in /<redacted>/wp-includes/functions.php on line 5834, referer: https://<redacted>.com/wp-admin/
```

**Comment by piotrbak** [comment]
@stefanoginella please reach our support, we need to have more data to investigate and fix this problem.

**Comment by gayanchandrab** [comment]
So it is not recommended to install WPRocket on a WPEngine site currently?

**Comment by engahmeds3ed** [comment]
> So it is not recommended to install WPRocket on a WPEngine site currently?

Hello,
No for sure, You can install it on WP Engine for the following reasons:-
1. Even if you faced this error, you will see it in WP Rocket's admin page only, will not affect the whole site.
2. Any plugin uses the WP Core function `apache_mod_loaded` will throw this fatal error in WP Engine with php8 or above environment.
3. The solution is very simple and already done and will be patched this week ASAP.

If you still afraid of having this kind of issues, you can change the php version to be before php8

We can help you if u faced any issue by contacting us at support[at]wp-rocket.me

**Comment by gayanchandrab** [comment]
@engahmeds3ed Thank you very much for the detailed answer.

**Comment by engahmeds3ed** [comment]
We are here to help.

We also created a ticket in WordPress Core here: https://core.trac.wordpress.org/ticket/56010 and will contribute to fix this in the Core as well ASAP.
