### ISSUE TITLE
RUCSS to preserve inline CSS for the XStore theme slider

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5164]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Slider layout has dynamic CSS selectors added in the inline style:
![image](https://user-images.githubusercontent.com/60236665/174743391-29b127bd-9759-4e69-9595-33aeea62d37d.png)
The layout breaks when a wrong numeric value is preserved.

Preserving inline styles that contain `.slider-item-` with `rocket_rucss_inline_content_exclusions` filer resolves the issue.

**To Reproduce**
Reproduced on customer's site that uses XStore theme with a slider on the home page.
Enable Remove Unused CSS to reproduce the problem: slider content alignment is broken.

**Expected behavior**
Inline CSS with dynamic selectors should be preserved.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1924164941/349215/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Adding a PR for automatically preserving `.slider-item-` seems a bit too generic.
@piotrbak what do you think is the best approach here?

**Comment by piotrbak** [comment]
@NataliaDrause Yes, I think you're right. We'll need a separate compatibility class for this theme.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
Reproduced this issue with xstore 8.2

### Scope a solution ✅
- Create a 3rd party class for xstore
- Check if current theme is `xstore`
- Hook to the `rocket_rucss_inline_content_exclusions` and preserve `[ '.slider-', '.slider-item-' ]`
- Update related ServiceProvider as per https://github.com/wp-media/wp-rocket/pull/5099#discussion_r890151607
- Add tests too

### Estimate the effort ✅
[S]
