### ISSUE TITLE
wpr link preloading does not work for logged-in users

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5165]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 3.11.3 ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
WP Rocket Preload links feature does not work for logged-in users

**To Reproduce**
1. Enable caching for logged-in WordPress users
2. Enable link preloading
3. link preloading is not working

**Expected behavior**
WP Rocket Preload links should work when caching for logged-in WordPress users is enabled

**Screenshots**

**Additional context**
[HS ticket](https://secure.helpscout.net/conversation/1923596911/349083)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
This was done on purpose, see https://github.com/wp-media/wp-rocket/issues/4711

**Comment by piotrbak** [comment]
@Tabrisrp I tested this on my website yesterday, preload links feature was able to generate user specific cache 🤔 What do you think??

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1981010378/362246?folderId=377611

**Comment by girlie** [comment]
https://secure.helpscout.net/conversation/2388069243/447953/

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue (3). We might reopen this in the future.
