### ISSUE TITLE
Interactive geo map compatibility with Delay JS 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5174]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The map is not displayed when Delay JS is enabled with default exclusions

**To Reproduce**
1. Use [interactive geo map](https://wordpress.org/plugins/interactive-geo-maps/)
3. Create a map and use it on any page i.e https://new.rocketlabsqa.ovh/interactive-map/
4. Enable delay js with default exclusion
5. Open the page => map is not displayed

**Expected behavior**
The map is displayed successfully

**Screenshots**
![Screenshot from 2022-06-22 09-42-31](https://user-images.githubusercontent.com/76941962/174973252-cc1345b2-cbe1-48d5-8e8b-76d04accedad.png)

**Additional context**
- As per discussion with @vmanthos 

> The following has to be excluded:
[cdn.amcharts.com](http://cdn.amcharts.com/) from Delay JavaScript Execution when /interactive-geo-maps/assets/public/map-service/app.js is excluded. I think in order to fix this we would need to add a compatibility file

- using exclusions mentioned [here](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#interactive-geo-maps) is working fine in this case

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
