### ISSUE TITLE
Enable 3.9.5 version in outdated PHP/WordPress version banner

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5177]
**Is your feature request related to a problem? Please describe.**

When a customer is using an outdated WordPress or PHP version, the banner will suggest using 3.9.4 but since this version is no longer available, downloading the 3.9.4 version throws a PCLZIP_ERR_BAD_FORMAT error.

![image](https://user-images.githubusercontent.com/23031592/175052472-4ad42531-bebd-4e9d-b3ab-7ac5e18aa009.png)
![image](https://user-images.githubusercontent.com/23031592/175052509-49a37363-1c57-46cb-bee5-c59197ed349f.png)

**Describe the solution you'd like**
Replace any 3.9.4 download links with the 3.9.5 version.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1926613439/349694/#modal

Thanks!

**Comment by remyperona** [comment]
We won't be able to fix that on the plugin side

**Comment by joejoe04** [comment]
Related - https://secure.helpscout.net/conversation/1948913704/355889

**Comment by engahmeds3ed** [comment]
@piotrbak @GeekPress 

May I add the `won't fix` label here?

Like @Tabrisrp mentioned, this can't be fixed from the plugin side.

So the only option here is to have 3.9.4 zip files uploaded to our site with the files from 3.9.5 not to have such errors, what do u think?
