### ISSUE TITLE
RUCSS jobs are created even if the used-css folder cannot be created

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5178]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.4`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the `used-css` folder cannot be created, e.g. because of restricting permissions, we still generate RUCSS jobs, which if the permissions issue isn't fixed have their status set to `failed`:
![](https://i.vgy.me/AIzMWG.jpg)

Even if the permission issue is fixed, for the `failed` URLs the used CSS will be generated when:
1. used CSS is automatically cleared `OR`
2. used CSS in manually cleared.

**To Reproduce**

1. Install a fresh copy of WP Rocket `>=3.11.4`.
4. Change the permissions of the `/cache/` directory to `444`
5. Enable **Remove Unused CSS** while **Preload** is enabled as well.
6. Check the `wpr_rucss_used_css` table. It will have jobs like in the screenshot I provided.

**Expected behavior**

We should bail out early in the RUCSS generation process if we can't write to the `used-css` folder.

**Additional context**

**Related discussion:** https://github.com/wp-media/wp-rocket/pull/5171#pullrequestreview-1015278212

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
We can do a check on L156 https://github.com/wp-media/wp-rocket/blob/90e3efde30df36a03a7f4e54c7062181be8cce49/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L131-L156 with `$this->filesystem->is_writable_folder()` 
I don't think we need to update tests, so I'll roll a PR for this as the effort is `[XS]`
