### ISSUE TITLE
Gravity Forms attachments conflict with htaccess gzip rules

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5182]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When using the file upload on a Gravity Forms form, the file is properly uploaded and added to entries. 

It's then accessible using a URL similar to this one: 

```
https://domain.ext/index.php?gf-download=2022/06/file.pdf&form-id=1&field-id=27&hash=21e86874313f57562fb0cb7f9ba948fe52081ad69e1739358f152877fcb994f7
```

On Apache servers, the file fails to load on browsers and will show the following error: 

<img width="267" alt="image" src="https://user-images.githubusercontent.com/1289174/175471884-0149cd05-b6f3-48d0-9e09-7ec53bdb0824.png">

Removing the mod_deflate rules using the helper plugin [WP Rocket | Remove GZIP (mod_deflate) rules](https://github.com/wp-media/wp-rocket-helpers/tree/master/htaccess/wp-rocket-htaccess-remove-gzip) fixes the issue. 

It should be also be possible to remove the gzip on specific paths. In this case, when the file is being browsed. 

```
<Files index.php>
   <If "%{QUERY_STRING} =~ /gf-download/">
       SetEnv no-gzip 1
   </If>
</Files>
```
Important: From my testing, the issue is inconsistent. 

I could experience it a couple of times while testing with the helper plugin. But after a while, the issue didn't happen even without the helper plugin.

I will leave it to QA to see if they can consistently replicate it. 

**To Reproduce**
1. Use a Gravity Forms form with an attachment on Apache environment
2. Upload an attachment
3. Check the attachment file in the GF entries section

**Expected behavior**
Attachements should be accessible with no errors.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1926765482/349755

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
