### ISSUE TITLE
Control Load CSS Asynchronously visits interval

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5187]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
CPCSS sends consecutive requests to websites in order to generate pages and process them. 

In rare cases where there are a lot of sample pages to check and hosted in a low-end/shared server, this might overload the server at the time CPCSS is generated. 

Having a way to control the pace of CPCSS visits should help in these cases. 

This looks like an edge cache. 

Adding for tracking purposes. 

Discussed on Slack - https://wp-media.slack.com/archives/C08N8J6VC/p1656068553551849

**To Reproduce**
N/A

**Expected behavior**
Server overload should be prevented if possible. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1929212839/350213/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
