### ISSUE TITLE
Compatibility with One.com (CDN and page cache)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5189]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When One.com is used with WP Rocket's minification, none of the assets are minified (not created). 

The debugged is returning: 

```
Couldn’t get the file path from the URL.
```

Tracking back the error, `$file_path` is returning empty: 

https://github.com/wp-media/wp-rocket/blob/635769c38d685916b97f8184bd7f9219baddefca/inc/Engine/Optimization/Minify/JS/Minify.php#L213-L224

The remaining possible compatibilities are listed in the following comments - https://github.com/wp-media/wp-rocket/issues/5189#issuecomment-1167274538

It would be good to implement compatibility class with `One.com` hosting:
1. If their CDN is enabled
- Grey out our CDN input and fill it with the CNAME value
- Either exclude /wp-includes/(.*) or confirm with One.com why it's handled like this on their end
2. If their Page Caching is enabled
- Clear cache when needed
- Clear our cache when action happens in One.com plugin
- Grey out our Varnish add-on

```
X-VC-Enabled: true | false
X-VC-Cacheable: NO | Yes
X-VC-TTL: seconds (30 days)
X-VC-Purge-Key : timestamp
X-VC-Purge-Host : $_SERVER['SERVER_NAME']
X-VC-Purge-Method:
```
**To Reproduce**
1. Use One.com
2. Use JS or CSS minfication
3. See that all links using `usercontent.one` are not minified

**Expected behavior**
We should minify all assets served by One.com. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1929106271/350176

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Could you confirm that adding CNAME to the CDN section doesn't help?

**Comment by piotrbak** [comment]
@DahmaniAdame I've been in touch with One.com Team and clarified a couple of things:
```
1. CDN
- Rewritten are only assets from `wp-content`
- Fonts are not rewritten at all, it works when WP Rocket rewrites it
For now, the solution is to enable our CDN feature, provide the correct CNAME and exclude `/wp-includes/(.*)` 
2. Page caching
- Varnish is available for all customers, One.com has its own plugin to clear the Varnish
- There's no partial purging available, any content update forces Varnish to be purged completely
```
It would be good to implement compatibility class with `One.com` hosting:
1. If their CDN is enabled (oc_cdn_enabled option set to true)
- Grey out our CDN input and fill it with the CNAME value
- Either exclude `/wp-includes/(.*)` or confirm with One.com why it's handled like this on their end

2a. If their Page Caching is enabled
- Clear one.com cache when needed (partial purge + rocket_clean_domain)
- Grey out our Varnish add-on
- Clear our cache when action happens in One.com plugin **(this is not possible for now)**

2b. If their Page Caching is disabled
- WP Rocket working as usual

```
X-VC-Enabled: true | false
X-VC-Cacheable: NO | Yes
X-VC-TTL: seconds (30 days)
X-VC-Purge-Key : timestamp
X-VC-Purge-Host : $_SERVER['SERVER_NAME']
X-VC-Purge-Method: 'regex'
```

**Comment by DahmaniAdame** [comment]
@piotrbak I can confirm that the issue is fixed if the CDN feature is used.

Thanks for checking with One.com. In light of your findings, should we turn this issue to broader compatibility with One.com? Or keep it that way and only automate enabling the CDN + add `https://usercontent.one/wp/domain.ext/` as a CNAME to it when we detect One.com CDN being used?

**Comment by piotrbak** [comment]
```
In light of your findings, should we turn this issue to broader compatibility with One.com?
```

Yes, let's do it!

**Comment by DahmaniAdame** [comment]
@piotrbak changed the title and included your comment on the description.

**Comment by piotrbak** [comment]
Hey @sebssingh ! I have some questions related to the compatibilities:
1. Is Varnish always enabled? If not, do you have any entry in the $_SERVER array to determine if it's enabled?
2. How we could determine if the CDN option is enabled and also get the CNAME of the CDN?

**Comment by sebssingh** [comment]
Hi @piotrbak Apologies for the delay in my response.

1. Yes, Varnish is always enabled by default for all one.com customers.
2. In order to check if a customer is using the CDN option via our Performance Cache plugin you can make use of the database option oc_cdn_enabled that is either set to true (CDN) or false (no CDN). The CNAME of the CDN would be https://usercontent.one/wp/www.domain.tld/ if the installation is on the root or www. If the installation is on a subdomain such as subdomain.domain.tld the CNAME would be https://usercontent.one/wp/subdomain.domain.tld/ . For installations on subfolder format such as domain.tld/subfolder, the CDN feature will not work.

**Comment by girlie** [comment]
FYI, regarding the CDN compatibility, one of our mutual customers was recently told this by someone on the One.com team:

> The CDN should be reserved for images and not all files.

This came about because I noticed that having it activated (and applied to **All files**) on the customer's site resulted in a significant number of bad request errors.

Related: https://secure.helpscout.net/conversation/1959988243/358134/
