### ISSUE TITLE
'Load CSS files asynchronously' causes preload links to fail

### ISSUE THREAD

**Issue by ablears** [wp-media/wp-rocket#519]
With all WP Rocket settings disabled, I enable 'Load CSS files asynchronously'. 

Links with rel=preload don't work because they are malformed. This affects CSS and even the  jQuery script reference as seen in these examples.

`<link rel="preload" href="//mysite.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=3.1.2" <link="" as="style" onload="this.rel='stylesheet'" media="only screen and (max-width: 768px)">`

`<link rel="preload" href="//mysite.com/wp-content/plugins/woocommerce/assets/css/woocommerce.css?ver=3.1.2" <link="" <script="" type="text/javascript" src="/wp-includes/js/jquery/jquery.js?ver=1.12.4">`

WP Rocket 2.10.7 on WP 4.8.1.

**Comment by Tabrisrp** [comment]
Please open a support ticket for your issue, and we'll have a look at your website and what's causing the issue.

We don't do support on GitHub
