### ISSUE TITLE
Charset handle isnot working probably in certain cases with Delay JS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5197]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If we have commented charset in the source, it will be used before the Delay JS script.
If we have multiple charset i.e one commented and the other is not commented => we will use the 1st one even if it's commented

**To Reproduce**
- Having template with 2` charset `definition, 1st one is commented i.e http://snippi.com/s/2llhh00
```
<!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> -->
<meta charset="UTF-8"/>
```
1. Enable Delay JS
2. Open the page template and check the source
3. Commented Charset is used before Delay JS and the valid one is removed from the source

**Expected behavior**
Only uncommented Charset is used

**Screenshots**
For the mentioned example:
![Screenshot from 2022-06-29 11-51-48](https://user-images.githubusercontent.com/76941962/176407757-dcf7af39-2588-4e4a-ab90-bbeaca71933d.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
