### ISSUE TITLE
Potential redirect loop when using 3.11.4, trailing slash redirection

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5207]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When permalinks are set to be without `/` and website is in the subdirectory we might experience redirect loop. 

**To Reproduce**
1. Use website placed in subdirectory (could be multisite)
2. Change the permalinks to be without `/`
3. Visit frontend in incognito

**Expected behavior**
No redirect loop

**Additional context**
Still not sure if there are any other factors needed to reproduce.

**Temporary solution**
Change the permalinks settings to be with `/`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Related tickets:
https://secure.helpscout.net/conversation/1937096734/351722?folderId=273761
https://secure.helpscout.net/conversation/1937085805/351717?folderId=273761

**Comment by alfonso100** [comment]
related
https://secure.helpscout.net/conversation/1937407389/351806?folderId=273761

**Comment by piotrbak** [comment]
@wp-media/qa PR5215 is the one ready for tests

**Comment by jcatello** [comment]
Not sure if this should be in a separate bug report but it is also forcing a trailing slash on ads.txt

```
[22:07][root@8231.bigscoots-wpo.com plugins]# wp plugin status wp-rocket 2>/dev/null
Plugin wp-rocket details:
    Name: WP Rocket
    Status: Active <-------
    Version: 3.11.4 <--------
    Author: WP Media
    Description: The best WordPress performance plugin.


[22:07][root@8231.bigscoots-wpo.com plugins]# curl -ILs https://domain.com/ads.txt |grep location
location: https://aseasyasapplepie.com/ads.txt/ <----------
location: https://ads.adthrive.com/sites/123/ads.txt



[22:08][root@8231.bigscoots-wpo.com plugins]# wp plugin deactivate wp-rocket
Success: Deactivated 1 of 1 plugins.
[22:08][root@8231.bigscoots-wpo.com plugins]# curl -ILs https://domain.com/ads.txt |grep location
location: https://ads.adthrive.com/sites/123/ads.txt
