### ISSUE TITLE
Check if Google Fonts URLs are valid before combining them to avoid issues

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5208]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If one of the Google Fonts URL is not valid, it will break the combined Google Fonts URL as well. 

We can check if individual URLs are valid before parsing them by adding:
```
if( ! strpos( get_headers($url, 1)[0], '200' ) ) {
    return;
}
```

Before: 

https://github.com/wp-media/wp-rocket/blob/47593e03ec09e72f7690a1b6304d90d19c67a29b/inc/Engine/Optimization/GoogleFonts/Combine.php#L109

And: 

https://github.com/wp-media/wp-rocket/blob/47593e03ec09e72f7690a1b6304d90d19c67a29b/inc/Engine/Optimization/GoogleFonts/CombineV2.php#L104

**To Reproduce**
1. Add a faulty Google Fonts URL - like `https://fonts.googleapis.com/css?family=Raleway:300|:|Raleway:400|ABeeZee:100|ABeeZee:300`
2. Check if the combined file is working

**Expected behavior**
We should safeguard the combined Google Fonts from breaking if one of the URL is not valid.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1936213679/351534/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
