### ISSUE TITLE
Preload does not occur after comment approval from WPAdmin moderation

### ISSUE THREAD

**Issue by small-fork** [wp-media/wp-rocket#5210]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before  ✅ (not that I could find at least)

**Describe the bug**
When a comment is approved and replied to from the WPAdmin comment interface in Wordpress, WPRocket will purge the post, home page, and related taxonomies, but they are not preloaded afterwards.

However, if a comment is posted without moderation, the purge/preload occurs as expected and the home page, post, and related taxonomies are immediately preloaded as desired.

**To Reproduce**
1. Have "preload" on in WPRocket (sitemap method)
2. Have a comment submitted that enters moderation (my site is set for all comments to be held for moderation aside from those with previously-approved comments)
3. Go into the comment admin interface and reply to the comment, then click "Approve and Reply"
4. Check in SFTP --> the home page, post and related taxonomies will purge, but will not preload.

**Expected behavior**
When I approve and reply to a comment that's in moderation, I expect everything WPRocket purges upon approval to be preloaded. (As occurs if the comment is posted without moderation)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @small-fork thanks for creating the issue. This problem will be fixed in the next major version 3.12.
