### ISSUE TITLE
.htm and .html files are preloaded by the preload links feature

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5211]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.4`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When there are URLs of `.html` or `.htm` files on a page, WP Rocket `prefetch`es them when the **Preload Links** feature is enabled.

Adding those to `$images_ext` resolved this issue:
https://github.com/wp-media/wp-rocket/blob/47593e03ec09e72f7690a1b6304d90d19c67a29b/inc/Engine/Preload/Links/Subscriber.php#L134

**To Reproduce**

1. Add URLs to `.html` and `.htm` files on a page.
2. Enable **Preload links**.
3. Visit the page and hover with the mouse over the URLs.
4. In Chrome Dev tools those will appear in the **Network** tab and the `prefetch` hint will be added in the **Elements** tab.

**Expected behavior**

Files with `.html` and `.htm` extensions should not be `prefetch`ed when **Preload links** is enabled.

**Additional context**

Found during QA of https://github.com/wp-media/wp-rocket/pull/4946.

It seems that `fileExt` isn't taken into consideration when checking if we should preload a link:
https://github.com/wp-media/wp-rocket/blob/85bbdd895c80665f5cd5b9f87846c14a807b3218/assets/js/preload-links.js#L217-L235

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
