### ISSUE TITLE
RUCSS to preserve inline CSS for the Smart Slider 3

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5219]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Slider layout has dynamic CSS selectors added in the inline style:
![image](https://user-images.githubusercontent.com/60236665/177569410-9e79abe2-382d-495c-bb80-e32ec4c6cc6a.png)
Full-screen image: https://i.imgur.com/Tm84aHb.png

The layout breaks when a wrong numeric value is preserved.

Preserving inline styles that contain `.n-uc-` with `rocket_rucss_inline_content_exclusions` filer resolves the issue.

But we can also target the attribute like `data-related="n2-ss-6"` by preserving `n2-ss-` with `rocket_rucss_inline_atts_exclusions` filter. The number at the end is changing.

**To Reproduce**
Reproduced on customer's site on category pages.
Enable Remove Unused CSS to reproduce the problem: slider images will have the wrong size.

**Expected behavior**
Inline CSS with dynamic selectors should be preserved.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1941173263/354154/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
I can submit PR, but not sure which approach is better:

-  preserving `.n-uc-` with `rocket_rucss_inline_content_exclusions` filter,
- or `n2-ss-` with `rocket_rucss_inline_atts_exclusions` filter.

@piotrbak what do you think?

**Comment by piotrbak** [comment]
@NataliaDrause Let's go with `n2-ss-`, just in case someone adds additional CSS somewhere, so we won't safelist unnecessarily whole script.

**Comment by mehedihasanziku** [comment]
@piotrbak Do you know/have any reason why all inline css are not excluded by default? every two days i have seen thread regarding inline css issues. Every Unused CSS Removal plugin I know they are excluding this by default. including them is an experimental feature. I really don't see issues if you exclude all inline css by default, normally by default inline css added by users/plugins/theme, they are important one not really much. and even you can't promise 100% rucss removal, psi also doesn't flag inline css then what's the purpose of it. I really want to understand insights behind this.

**Comment by piotrbak** [comment]
Hello @mehedihasanziku thanks for your comment

`psi also doesn't flag inline css then what's the purpose of it. I really want to understand insights behind this.`
It's not triggering the warning, that's true. However, other metrics are worsened and it's blocking the render. We're looking for the best performing solution that is good for everyone.
