### ISSUE TITLE
Modify Cache Options Meta Box for non-public CPTs

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#522]
When a CPT is not designated for front-end use, the Cache Options Meta Box should not be used.
Maybe we can detect non-public CPTs and grey-out or modify (with a message) our meta box so that it cannot be used.

**Comment by GeekPress** [comment]
We already try to display the meta boxe only on public CPT => https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/admin/ui/meta-boxes.php#L27

But as for CPCSS, this method can't guarantee at 100% that a CPT isn't really public. Sometimes the CPT declaration is missing some parameters, and we can't control them.
