### ISSUE TITLE
RUCSS - Revolution theme - Multiple elements break because dynamic CSS inline selectors

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5229]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The [Revolution Theme, by fuelthemes](https://themeforest.net/item/revolution-creative-multi-purpose-theme/21758544) uses dynamic inline selectors. 

So, our Used CSS won't contain the appropriate value after the cache is cleared to insert the used css.

Adding `#thb-` to `rocket_rucss_inline_content_exclusions` solves the issue

**To Reproduce**
1. Using the Revolution Theme or this HTML template https://tinyurl.com/2jjty6vl
4. Enable Remove Unused CSS
5. See the issue. 

**Expected behavior**
We should preserve these dynamic inline declarations.

**Screenshots**
The number changes on every page load:
![vh34b3k](https://user-images.githubusercontent.com/229406/178026349-20f826f6-956f-40d9-95dc-8214bee90b31.png)

https://i.imgur.com/vh34b3k.png

**Additional context**
ticket:  https://secure.helpscout.net/conversation/1940409215/353995?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
I can do a PR to add `#thb-` to our [automatic exclusions](https://github.com/wp-media/wp-rocket/blob/25f42089e03da6f43e391bdcac108bb707ab6bb3/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L89)

But I don't know if it'd be too generic and cover many other cases. 
So I'm not doing the PR until we can decide if that's the best way, or doing a compat file is better

The heme prepends that in many elements: 

```
#thb-slidetype-62c84f9ad56dc
#thb-team-37
#thb-fancy-box-62c84f9ad232f
#thb-iconbox-62c8556dcd310
#thb-row-overlay-62c8556dcd7c6
```

etc

**Comment by engahmeds3ed** [comment]
@alfonso100 

Thanks for taking time to get the whole selectors.

I believe we don't need to have the generic one `#thb-` and only add the ones that we can see because I can see that this prefix is used in the whole elements even the not timestamed ones!

We can start with the ones u mentioned and once we see another items we can open another issue and resolve them there.

The good thing behind having a prefix is that we don't need to make third party compatibility file for it and only add those selectors to the list.

**Comment by piotrbak** [comment]
@alfonso100 Is that list a complete one or we need further investigation?

**Comment by piotrbak** [comment]
This is the complete list of dynamic elements:
```
#thb-empty-space-
#thb-testimonials-
#thb-image-
#thb-image-slider-
#thb-slidetype-
#thb-autotype-
#thb-posts-shortcode-
#thb-fancy-box-
#thb-row-overlay-
#thb-iconbox-
#thb-icon-
#thb-awards-
#thb-client-logos-
#thb-counter-
#thb-fadetype-
#thb-flip-box-
#thb-gradienttype-
#thb-stroketype-
#thb-styled-header-
#thb-team-
```

@engahmeds3ed You remember where did you see the `#thb-` in internal style that's not dynamic? 🤔

**Comment by engahmeds3ed** [comment]
Thanks for the full list @piotrbak 

I meant that `thb` prefix is used in all elements but for the IDs, in the customer's page, you are right, all dynamic IDs are prefixed with `#thb-`.

Also bear in mind that we have checked only this site, but we can give it a try, this theme has about 4000 purchases and last update was from more than 1 year so I believe we are in the safe side to use `#thb-`

**Comment by piotrbak** [comment]
@engahmeds3ed Great, let's do it then!

**Comment by alfonso100** [comment]
Cool, Should I do the PR?

**Comment by piotrbak** [comment]
@alfonso100 Yes, please!

**Comment by piotrbak** [comment]
Fixed with dynamic backend
