### ISSUE TITLE
Presslabs - Homepage's cache isn't cleared when using the admin bar menu item

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5231]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.4.2`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On Presslabs, when using the **Purge this URL** admin bar menu item, the cache of the homepage isn't cleared.

This is happening because our code is returning here:
https://github.com/wp-media/wp-rocket/blob/499eaf1bcfa79ef66191f287e3a63ea13851e378/inc/3rd-party/hosting/presslabs.php#L50

This is working fine for posts, e.g. example.com/hello-world.

**To Reproduce**

1. On Presslabs, visit the homepage and note down the value of the "refresh in" of the `x-presslabs-stats` header.
```
x-presslabs-stats: HIT; 0.133s; 7 queries; desktop; ttl 18000s; refresh in 17769s
```
2. Visit the homepage in the backend and click on the **Purge this URL** button.
3. Visit the homepage on the front end and note down the same value as in step 1.
4. The value will be lower meaning that Presslabs cache wasn't cleared.

**Expected behavior**

The specific admin bar menu item should clear the homepage's cache.

**Additional context**

Discovered during QA of #5228. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
