### ISSUE TITLE
Compatibility with The Events Calendar plugin (counter widget) and Load JavaScript deferred

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5234]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - YES
- Used the search feature to ensure that the bug hasn’t been reported before - YES

**Describe the bug**
Load JavaScript deferred breaks the counter widget from [The Events Calendar plugin (pro version)](https://theeventscalendar.com/products/wordpress-events-calendar/)

**To Reproduce**
1. Create and event and set the countdown widget
2. Enable Load JavaScript deferred
3. Visit the page with the widget
4. The countdown values are not set. The default placeholders (`DD HH MM SS`) aren't replaced by the respective custom values:  https://jmp.sh/sPmiZ8S 

The following are the required exclusions on customer's and test site:

```
/events-calendar-pro/src/resources/js/views/widget-countdown.js
/the-events-calendar/common/src/resources/js/tribe-common.min.js
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
```

**Expected behavior**
The scripts from Events Calendar plugin (counter widget) are automatically excluded from the Load JavaScript deferred feature.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1940496276/354006/#thread-5758150093
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1657297379333049

On customer's site, the following had to be excluded from Minify JavaScript files too:
`/events-calendar-pro/src/resources/js/views/widget-countdown.js`
This exclusion wasn't needed on the test site.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
