### ISSUE TITLE
LazyLoad causes PHP Warning: preg_replace(): Compilation failed: regular expression is too large at offset 75520...

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5241]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.4.2
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
This might be an edge case, but creating this GH to monitor issues like the following:
When `<img>` has a lengthy attribute, it will throw the following error:

`PHP Warning:  preg_replace(): Compilation failed: regular expression is too large at offset 75520 in .../wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php on line 312`

**To Reproduce**
1. Add a sample HTML code found in the [note of the ticket](https://secure.helpscout.net/conversation/1946824073/355428/) to a post as an HTML block to a post and save.
2. Enable LazyLoad for Images in WP Rocket.
3. Visit or preload the page.
4. The page will load white screen.
5. Check debug.log for the error.

**Expected behavior**
No warning and no white screen.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1946824073/355428/

`$safe_img` is large due to the attributes.
I logged [$safe_img](https://github.com/wp-media/wp-rocket/blob/8d418174f0759a096418a6ab159557b10b648ce4/inc/Dependencies/RocketLazyload/Image.php#L311) and the result of the variable is saved in the log attached to a note of the ticket.

Possibly we could skip any lengthy images that would cause the warning.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Seems like the same mechanism failing as here - https://github.com/wp-media/wp-rocket/issues/3996

**Comment by LSshopmacher** [comment]
We are one the latest version 6.1.1 and have the same problem. If I activate lazy loading of JS and add this to the exclude list:

```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/jquery-migrate(.min)?.js
.dipi_preloader_wrapper_outer
/Divi/js/scripts.min.js
/Divi/js/custom.unified.js
/js/mediaelement/(.*)
mejs
/Divi/includes/builder/feature/dynamic-assets/assets/js/sticky-elements.js
var DIVI
/Divi/includes/builder/feature/dynamic-assets/assets/js/easypiechart.js
window.econda
ecn-ldr.de
l.ecn-ldr.de
```

we start to have white pages in the cache (only some sub pages as it seems). We have the latest WordPress (6.1) and the latest Divi (4.19.1).

Error:
> PHP Warning: preg_replace(): Compilation failed: regular expression is too large at offset 43794 in [...]wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 147

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
