### ISSUE TITLE
RUCSS - jnews Theme - Navigation Bar/Search Icon Not working

### ISSUE THREAD

**Issue by jammy26** [wp-media/wp-rocket#5244]
**Describe the bug**
When using RUCSS method for CSS Optimization, neither Hamburger Icon nor search icon works on Mobile in jnews theme. Those icons shows up but don't work. They work just fine with Method "Load CSS Asynchronously"

**To Reproduce**
I have setuped a staging website just for this.
1. Go to https://dobermannclub.net/ with actual mobile browser
2. Click on Either Hamburger Icon or Search Icon

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
Add below selectors in rucss safelist box, here is the guideline https://docs.wp-rocket.me/article/1529-remove-unused-css#css-safelist

```
(.*).jeg_show_menu(.*)
(.*).jeg_bg_overlay(.*)
```

**Comment by piotrbak** [comment]
Hello @jammy26 thanks for creating the issue. We'll try to reproduce the problem and then we'll make sure that things are resolved on our end without the need of safelisting CSS classes on your end.

Could you reach our Support Team and provide access to the staging site?

**Comment by piotrbak** [comment]
Thank you @mehedihasanziku for your answer.
