### ISSUE TITLE
Increased loading time of wc-fragments

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#5245]
**Describe the bug**
When wp-rocket is active, POST ?wc-ajax=get_refreshed_fragments&elementor_page_id=20 takes at least 2 seconds to load. 
screenshot : https://prnt.sc/Kbbc9entnHGx
After I disabled wp-rocket, the load speed of this request improved greatly, dropping to 678ms.
A number of users who use wp-rocket have this problem. Because a large part of the loading time of the website is devoted to loading this request.
We first discussed this issue with the elementor developers, but apparently this is a wp-rocket issue. If you want, please see [this link](https://github.com/elementor/elementor/issues/18675).

I hope there is a solution for that. thank you!

**Comment by JanWebofka** [comment]
Thank you for opening this ticket @79ho3ein ! Waiting for fix

**Comment by Michaelgimii** [comment]
+1

**Comment by piotrbak** [comment]
Hello @79ho3ein from the thread you shared, it looks like a couple of factors are involved. From WP Rocket's end, I'd suggest checking if using this helper plugin resolves the problem:
https://github.com/wp-media/wp-rocket-helpers/tree/master/compatibility/wp-rocket-compat-wc-cart-fragments

**Comment by 79ho3ein** [comment]
thank you @piotrbak  Yes, much better than before.
Before installing this plugin: 1.6s
after installing this plugin: 741ms

**Comment by Michaelgimii** [comment]
It worked great for me. Do we always need to install this plugin? Or will it be added to wp-rocket in future updates?

**Comment by piotrbak** [comment]
@Michaelgimii This plugin **disables** our optimization related to cart fragments. You can read more about it here:
https://docs.wp-rocket.me/article/1100-optimize-woocommerce-get-refreshed-fragments

Probably adding the page ID to request changes something in the native WC function and makes our optimization (and some features of other plugins mentioned in the above thread) not working correctly. We'll investigate this.

**Comment by louiswol94** [comment]
> Probably adding the page ID to request changes something in the native WC function and makes our optimization (and some features of other plugins mentioned in the above thread) not working correctly. We'll investigate this.

@piotrbak Were you able to find anything regarding adding the page ID to the request?

**Comment by piotrbak** [comment]
The issue is not relevant anymore. If it reappears, we'll reopen it.
