### ISSUE TITLE
Avada carousel not working when DJE is enabled + jQuery is excluded

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5247]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Avada's carousel element is used with DJE + jQuery is excluded, the carousel doesn't show up. 

No console error is showing. 

Excluding the following in addition to the already excluded jQuery library fixes the issue. 

```
/Avada/includes/lib/assets/min/js/general/fusion.js
/Avada/includes/lib/assets/min/js/general/fusion-carousel.js
/Avada/includes/lib/assets/min/js/library/jquery.carouFredSel.js
/Avada/includes/lib/assets/min/js/library/modernizr.js
fusionCarouselVars
```

**To Reproduce**
1. Add a carousel (Avada)
2. Enable DJE + exclude the jQuery library
3. See error

**Expected behavior**
The carousel should work properly even if the jQuery library is excluded. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1947760920/355619?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This ons is in the backend already. The exclusions are matching what we have here:
https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#avada-fusion-carousel
