### ISSUE TITLE
LazyLoad - Update to latest version of Vanilla Lazyload

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5250]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
The latest version of [Vanilla Lazyload](https://github.com/verlok/vanilla-lazyload) is `17.8.2` and we still use the `17.5`:
https://github.com/wp-media/wp-rocket/blob/63f649200fa3b5b81ec83812d3448eeeea28e464/inc/Engine/Media/Lazyload/Subscriber.php#L21

**Additional context**
[Slack thread](https://wp-media.slack.com/archives/C08N8J6VC/p1658145646752699)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Scope a solution
Add a new folder 17.8.2 in `assets/js/lazyload` and add it the last version of the script.
Change constant `SCRIPT_VERSION` to `17.8.2` inside [Media subscriber](https://github.com/wp-media/wp-rocket/blob/63f649200fa3b5b81ec83812d3448eeeea28e464/inc/Engine/Media/Lazyload/Subscriber.php#L21).
## Estimate the effort
Effort `XS`

**Comment by Mai-Saad** [comment]
@piotrbak can see the [latest version](https://github.com/verlok/vanilla-lazyload/releases) now is 17.8.3, shall we use this instead?

**Comment by piotrbak** [comment]
@Mai-Saad @CrochetFeve0251 Yes, let's update to the latest one.
