### ISSUE TITLE
Remove « Beta » from Remove Unused CSS feature

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#5255]
**Describe the solution you'd like**
We would like to remove the « Beta » mention on the « Remove Unused CSS » selector into the « Optimize CSS Delivery ». option.

The current text displayed once the option is selected will be replaced by the warning notice we have for Minify or Combine CSS options.

**Comment by CrochetFeve0251** [comment]
## Scope a solution

For this we will have to remove the beta mention on the [title](https://github.com/wp-media/wp-rocket/blob/ff6d8014d7736c140fde328215d6aa58128db70b/inc/Engine/Admin/Settings/Page.php#L723).
Another part we need to remove this the warning [section](https://github.com/wp-media/wp-rocket/blob/ff6d8014d7736c140fde328215d6aa58128db70b/inc/Engine/Admin/Settings/Page.php#L727).

## Estimate effort

Effort `XS`
