### ISSUE TITLE
If WP Rocket is on one.com environment, Varnish add-on should be enabled upon activation

### ISSUE THREAD

**Issue by sebssingh** [wp-media/wp-rocket#5258]
Hi!
Once https://github.com/wp-media/wp-rocket/issues/5235 is in production, I would like to request that we enable the Varnish add-on (available in the WP Rocket add-on settings) by default for customers activating the plugin on a one.com environment, since one.com uses Varnish caching.

**Comment by piotrbak** [comment]
Hello @sebssingh thanks for creating the issue. While ago we've created an issue similar to this one but also including the CDN feature compatibility:
https://github.com/wp-media/wp-rocket/issues/5189#issuecomment-1167274538

The above issue contains more details, what do you think about closing this one and continue the work there?

I also have two questions about the compatibilities:
1. Is Varnish **always** enabled? If not, do you have any entry in the **$_SERVER** array to determine if it's enabled?
2. How we could determine if the CDN option is enabled and also get the CNAME of the CDN?

We can easily continue our discussion there.

**Comment by piotrbak** [comment]
Closing it in favour of 5189
