### ISSUE TITLE
RUCSS: Cookie Notice plugin stylesheet is skipped during Remove Unused CSS process

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5259]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.4.2
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When RUCSS is enabled, all Cookie Notice styles are missing. The Cookie Notice bar looks broken.
The Cookie Notice stylesheet is skipped during the Remove Unused CSS process and safelisting does not resolve the issue.

As per @mostafa-hisham investigation, this is happening due to our implementation of the safe crawler in Cloudflare.
WP Rocket adds `WPRBot` to the userAgent header while we visit pages from the Remove Unused CSS nodejs. But [Cookie Notice & Compliance for GDPR / CCPA](https://wordpress.org/plugins/cookie-notice/) plugin has a `Cookie_Notice_Bot_Detect` class that does not add `cookie-notice` files to the page if we add `WPRBot` to the userAgent header.

Currently, the issue can be fixed with the following code snippet added to functions.php:
```
add_filter( 'rocket_rucss_external_exclusions', function ( $exclusions ){
	$exclusions[] = 'plugins/cookie-notice/';
	return $exclusions;
} );
```
Reference on how to add the code: https://docs.wp-rocket.me/article/1332-add-code-snippets

**To Reproduce**
1. Install and activate [Cookie Notice & Compliance for GDPR / CCPA](https://wordpress.org/plugins/cookie-notice/) plugin
2. Make sure the cookie notice is displayed when page is visited.
3. Enable Remove Unused CSS option;
4. Check the page - the Cookie Notice will be broken.

**Expected behavior**
Cookie Notice styles should be preserved.

**Additional context**
Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1658331833907439
Ticket: https://secure.helpscout.net/conversation/1951655386/356385/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
Fix in sass side with the correct user agent
