### ISSUE TITLE
PHP deprecated notice when converting boolean to array for Yoast SEO

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5261]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version N/A
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

With:
* WP Rocket `3.9.5.1`
* PHP `8.1.x`

the following is displayed in the `debug.log`:
```PHP
PHP Deprecated:  Automatic conversion of false to array is deprecated in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/3rd-party/plugins/seo/yoast-seo.php on line 10
```

It's about this line:
https://github.com/wp-media/wp-rocket/blob/8ef7ca349532f454dae3c63000db56b898f042af/inc/3rd-party/plugins/seo/yoast-seo.php#L10

**To Reproduce**

1. Install WP Rocket `3.9.5.1`: https://github.com/wp-media/wp-rocket/tree/v3.9.5.1
2. Enable WordPress's debugging.
3. Install [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/).
4. Activate Sitemap Preloading and select Yoast there.
5. Run preloading.
6. Check the `debug.log` for the notice.

**Expected behavior**

No deprecation notices should be displayed in the `debug.log` when Yoast's sitemap is used with WP Rocket's preload.

**Additional context**

This will affect the new preload feature as well:
https://github.com/wp-media/wp-rocket/blob/33c67aac0319eda785aadd6ea26a9d00d36f5ca5/inc/ThirdParty/Plugins/SEO/Yoast.php#L88

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
@piotrbak @vmanthos I don't think we will need to make any changes on the new preload because this notice is triggered when we are converting a var to an array on the fly and since we are already taking care of this here by setting a default, I think we are good. 
https://github.com/wp-media/wp-rocket/blob/33c67aac0319eda785aadd6ea26a9d00d36f5ca5/inc/ThirdParty/Plugins/SEO/Yoast.php#L84
