### ISSUE TITLE
Lasyloading does not seem to work properly when testing on chrome responsive mode with devtools.

### ISSUE THREAD

**Issue by thesquaremedia** [wp-media/wp-rocket#5265]
When I view the devtools elements on desktop mode the images lazy load on the browser tab appropriately but when I switch to responsive mode it does not work. if I set the user agent to a chrome Mac or windows then it works correctly. is wp rocket checking user agents to apply lazy loading?

**Comment by piotrbak** [comment]
Hello @thesquaremedia thanks for creating the issue. WP Rocket's lazyload should work correctly on all UAs.

If you're still experiencing this problem, please contact our Support Team and we'll try to address your concerns
