### ISSUE TITLE
Divi delayed variable causing corresponding feature to not work

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5266]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If a variable declaration in Divi is delayed, its corresponding feature doesn't work properly. 

In this case, it's the `et_link_options_data` used to map modules links wrapper (when an element is clickable but it's not an actual `a` tag). 

![image](https://user-images.githubusercontent.com/1289174/180369599-6ea2cf1e-148c-4659-8e7e-9c22216c9463.png)

```
var et_link_options_data = [{"class":"et_pb_text_20","url":"https:\/\/domain.ext\/enkeltrejseforsikring\/","target":"_self"},{"class":"et_pb_text_21","url":"https:\/\/domain.ext\/enkeltrejseforsikring\/","target":"_self"},{"class":"et_pb_text_22","url":"https:\/\/domain.ext\/familierejseforsikring\/","target":"_self"},{"class":"et_pb_text_23","url":"https:\/\/domain.ext\/enkeltrejseforsikring\/","target":"_self"},{"class":"et_pb_text_24","url":"https:\/\/domain.ext\/ungdomsrejseforsikring\/","target":"_self"},{"class":"et_pb_text_25","url":"https:\/\/domain.ext\/studierejseforsikring\/","target":"_self"},{"class":"et_pb_text_30","url":"https:\/\/domain.ext\/enkeltrejseforsikring\/","target":"_self"},{"class":"et_pb_text_32","url":"https:\/\/domain.ext\/aarsrejseforsikring\/","target":"_self"},{"class":"et_pb_text_34","url":"https:\/\/domain.ext\/ungdomsrejseforsikring\/","target":"_self"},{"class":"et_pb_text_36","url":"https:\/\/domain.ext\/skirejseforsikring\/","target":"_self"},{"class":"et_pb_text_38","url":"https:\/\/domain.ext\/studierejseforsikring\/","target":"_self"},{"class":"et_pb_text_40","url":"https:\/\/domain.ext\/familierejseforsikring\/","target":"_self"}];
```

In this case, it results in links not being clickable. No console error. 

Excluding `et_link_options_data` fixes the issue. 

This was reported on - https://github.com/wp-media/wp-rocket/issues/4014 - but was not excluded. 

**To Reproduce**
1. Enable Delay JavaScript Execution 
2. Use a link in a module
3. See error

**Expected behavior**
Links should work properly when Delay JavaScript Execution is used.

**Screenshots**
Added to the description. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1953840771/356894/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by worldwildweb** [comment]
related: https://secure.helpscout.net/conversation/2000805280/366688/
