### ISSUE TITLE
Need a hook (action) on Clear cache

### ISSUE THREAD

**Issue by AleksBaikalsky** [wp-media/wp-rocket#5281]
**Is your feature request related to a problem? Please describe.**
I need to execute my function when user clicks 'Clear cache' button.

**Describe the solution you'd like**
Some action hook, e.g. 'after_rocket_clear_cache'.

**Describe alternatives you've considered**
Workarounds, and that's not an acceptable solution. Looking through WP Rocket codebase in had no results, maybe I looked in the wrong place. 

**Additional context**
The hook I request is handy in cases when some actions should be fired only on cache update, not on every wp init.

**Comment by piotrbak** [comment]
Hello @AleksBaikalsky there's a hook when the whole cache is getting cleared:
https://github.com/wp-media/wp-rocket/blob/850621a6fd88e1c3ec47f92de55a78d7e4ae2cf6/inc/functions/files.php#L781

In the same file you'll see some other hooks related to cache clearing. Does it answer your question?

**Comment by AleksBaikalsky** [comment]
Hello,
> Does it answer your question?

Yes, thank you @piotrbak
