### ISSUE TITLE
Accessibility issue - DJE with recommended Elementor exclusions duplicates element with the same ID

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#5282]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version -3.11.4
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When using Delay JavaScript execution with recommended Elementor exclusions, it causes the duplication of `<span id="elementor-device-mode" class="elementor-screen-only"></span>` element. Duplicate `id` values can degrade both functionality and accessibility. Most importantly, it creates an issue for sites that have to meet government issued  Accessibility requirements and regulations.

**To Reproduce**
1. With installed Elementor enable Delay JavaScript execution
2. Add [recommended Elementor exclusions](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#elementor-pro)
3. Visit the site and check the code in DOM inspector

**Expected behavior**
Delay JavaScript execution shouldn't duplicate the element with the same ID and cause the issue with the Accessibility. 

**Screenshots**
https://i.imgur.com/7M4b10l.png

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1949143754/355955/
Slack: https://wp-media.slack.com/archives/C08N8J6VC/p1658495777408619

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The solution is proposed in the linked issue from Delay JS Script repo

**Comment by Mai-Saad** [comment]
Note for testing: reproducible on https://rocketlabsqa.ovh/ using 3.13.1, when enable DJS with/without Elementor exclusions
