### ISSUE TITLE
We cleared the WP Rocket cache. But website always loads from previous cache data.

### ISSUE THREAD

**Issue by mobiledevres** [wp-media/wp-rocket#5286]
We are using WP Rocket Version 3.10.8. After we make changes in Insert Headers and Footers section that changes will not reflect in original website. But when i try to view my website with (www.domain.com/?nocache=true) then i can able to see my new changes. I tried all caching clearing options provided by WP Rocket. But nothing works. Can you please suggest some good option to clear and verify caches used in WP Rocket?

**Comment by piotrbak** [comment]
Hello @mobiledevres and thank you for creating the issue. 

It sounds like you have another layer of cache present on your website (server-side, browser cache, maybe Cloudflare or Sucuri, etc.). This is rather a support request than a real bug or enhancement that we could work on GitHub. Please reach our Support Team here, we'll be happy to help you:
https://wp-rocket.me/support/
