### ISSUE TITLE
"?nowprocket" is cached when it's used with a cacheable query string

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5288]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
`?nowprocket` is sending back a cached page when used with a cacheable query string. 

![image](https://user-images.githubusercontent.com/1289174/182553423-8944fa64-b8dd-4df1-98c2-c524d8c7d358.png)

This behavior is more problematic on pages that have an automatic redirection, like WooCommerce Geotargeting for example (adding `?v=###`). 

It will prevent quickly testing by bypassing the cache.

**To Reproduce**
1. Cache query string `test=1` for example
2. Check a page using ?nowprocket&test
3. Check WP Rocket's footprint will be there on the bottom of the page + the cache folder will hold a filter called `#nowprocket=&test=1`

**Expected behavior**
Cache should be bypassed on all cases when `nowprocket` is used.

**Screenshots**
Added to the description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1966589643/359443/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2001306081/366806

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2079190820/384799/
Issue happens when the WooCommerce localization `v` query string is used.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
