### ISSUE TITLE
Cached page display jetpack related posts JSON

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#529]
When jetpack related posts is activated, very randomly the cached content will be the JSON returned for the related posts instead of the actual content of the page.

Tagging @jeherve on this you might be able to help

**Comment by jeherve** [comment]
Do you currently cache pages that include query strings, like the ones used by Jetpack Related Posts, `?relatedposts=1`?

If so, could you add a rule to never cache or serve from cache when a URL includes this query string?

**Comment by Tabrisrp** [comment]
Query strings are not cached by default, and `relatedposts` is not among the ones we serve the default cache too

**Comment by jeherve** [comment]
In this case, the problem is most likely not caused by WP Rocket. It might be worth checking if caching could happen somewhere else (Varnish maybe?).

**Comment by Tabrisrp** [comment]
There is indeed Varnish on the last case we had

**Comment by haleeben** [comment]
Hi

I am having the same issue, but I am not running Varnish

**Comment by jeherve** [comment]
@haleeben Could you clarify a few things? 

- Do Related Posts work when you deactivate WP Rocket?
- Do you see any errors, or a list of related post information when you load one of your posts, and add `?relatedposts=1` to the URL?
- What's your site URL?

**Comment by haleeben** [comment]
Hi @jeherve 

Yes the related posts work when WP Rocket is deactivated.
No errors when adding `?relatedposts=1` to the URL
https://ajp.com.au

As @Tabrisrp said, its a very random issue, I can't find any rhyme or reason for this. Doesn't happen on all posts, just some and only very occasionally.

**Comment by jeherve** [comment]
It would be interesting to check for JavaScript errors on the page when this happens; I wonder if another WP Rocket setting (maybe js concatenation) may cause a js error on some of your pages, thus breaking other functionality that relies on js, like Related Posts.

**Comment by mintaras** [comment]
Once in a while, more often then I would want, new published post on my blog shows some custom strange JSON code instead of post content. After a while it goes away. I have Googled it and there are 10 pages of sites with same issue.

My site: https://ibb.co/gYHexR
Other sites with same problem: https://ibb.co/ea2CHR

**Comment by jeherve** [comment]
@mintaras Do you use the latest version of Jetpack and WP Rocket? What are your WP Rocket settings set to?

**Comment by jeherve** [comment]
In the "Advanced" tab, could you try to add `/(.*)/?relatedposts=1` to the list of things that should never get cached, and see if it helps?

Could you also let us know if you use Varnish on your server? I can't tell when taking a quick look:

```
server: nginx/1.9.12
date: Wed, 17 Jan 2018 14:06:41 GMT
content-type: text/xml; charset=UTF-8
vary: Accept-Encoding
x-application: Blog
x-host: itviec.com
x-scheme: http
x-upstream: unix:/var/run/php-fpm.socket
x-upstream-response-time: 1516198001.235
```

**Comment by mintaras** [comment]
I have added `/(.*)/?relatedposts=1` to Advanced tab but when I save it, this line becomes `/(.*)/` (parameter "?relatedposts=1" disappears). 

No, we do not use Varnish.

Thanks

**Comment by jeherve** [comment]
@Tabrisrp Could you run some tests on your end to make sure that URLs with query strings are not being cached?

**Comment by mintaras** [comment]
@jeherve Any updates on this issue? Thanks

**Comment by jeherve** [comment]
@tabrisrp did you have the chance to look at this?

**Comment by Tabrisrp** [comment]
@jeherve the `relatedposts` query string is never cached by WP Rocket

**Comment by jeherve** [comment]
Then in this case, , @mintaras I would recommend looking at other things that may cache things on your site, as it appears that neither Jetpack nor WP Rocket are caching that response.

**Comment by GeekPress** [comment]
@webtrainingwheels Do we still have users reporting this issue?

**Comment by webtrainingwheels** [comment]
Haven't seen this one come up in a loooong time :) Probably not relevant anymore.

**Comment by GeekPress** [comment]
> Haven't seen this one come up in a loooong time :) Probably not relevant anymore.

Ok, so let's close it for now ^^
