### ISSUE TITLE
Lazyload: Background images added directly as code are removed from the HTML

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#5293]
**Before submitting an issue please check that you’ve completed the following steps:**
- ✅ Made sure you’re on the latest version
- ✅ Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
For background images we seem to expect for a URL in the style attribute, but the image can also be added as code:

Example: 

`<div class="awb-background-mask" style="background-image:  url(data:image/svg+xml;utf8,%3Csvg%20width%3D%221920%22%20height%3D%22954%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cg%20clip-path%3D%22url%28%23prefix__clip0_58_745%29%22%20fill%3D%22rgba%28254%2C245%2C238%2C1%29%22%3E%3Cpath%20d%3D%22M250.018-408.977c69.019-18.494%20142.66%201.238%20193.185%2051.763L718.31-82.107c50.525%2050.525%2070.258%20124.167%2051.764%20193.185L669.378%20486.881c-18.493%2069.019-72.403%20122.928-141.421%20141.422L152.154%20728.999c-69.019%2018.493-142.66-1.239-193.186-51.764l-275.106-275.107c-50.525-50.525-70.258-124.167-51.764-193.185l100.696-375.803c18.493-69.018%2072.403-122.928%20141.421-141.421l375.803-100.696zM1646.73%201264.15c33.13%208.88%2068.48-.59%2092.73-24.84l147.89-147.89a96.031%2096.031%200%200024.85-92.732l-54.13-202.022a96.012%2096.012%200%2000-67.89-67.882l-202.02-54.132c-33.13-8.877-68.47.595-92.73%2024.847l-147.89%20147.89a95.994%2095.994%200%2000-24.84%2092.729l54.13%20202.022a95.967%2095.967%200%200067.88%2067.88l202.02%2054.13zM1572.48%20252.659a23.996%2023.996%200%200023.18%206.211l50.5-13.533a23.97%2023.97%200%200016.97-16.97l13.54-50.506a24.004%2024.004%200%2000-6.21-23.182l-36.98-36.973a23.993%2023.993%200%2000-23.18-6.211l-50.5%2013.533a24%2024%200%2000-16.98%2016.97l-13.53%2050.506a24.004%2024.004%200%20006.21%2023.182l36.98%2036.973z%22%2F%3E%3C%2Fg%3E%3Cdefs%3E%3CclipPath%20id%3D%22prefix__clip0_58_745%22%3E%3Cpath%20fill%3D%22%23fff%22%20d%3D%22M0%200h1920v954H0z%22%2F%3E%3C%2FclipPath%3E%3C%2Fdefs%3E%3C%2Fsvg%3E);opacity: 1 ;">`

It is converted to:
`<div data-bg="" class="awb-background-mask rocket-lazyload" style="opacity: 1 ;">`
data-bg is empty in this case.

Here we use `esc_url()`, but `data:` doesn't seem to be a valid protocol for it, so, the image won't be valid.
https://github.com/wp-media/wp-rocket/blob/63f649200fa3b5b81ec83812d3448eeeea28e464/inc/Dependencies/RocketLazyload/Image.php#L74 

**To Reproduce**
1. Have a background image `style="background-image:  url(data:...)`
2. Enable Lazyload
3. Image won't appear in the page

**Expected behavior**
This kind of images must be excluded, because in any case, it doesn't make any sense to lazyload an already loaded image.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by sandyfzu** [comment]
Related case: https://secure.helpscout.net/conversation/1967487595/359615/

**Comment by mostafa-hisham** [comment]
### Reproduce the problem
I was able to reproduce the problem locally.

### Identify the root cause
we are lazyloading base64 images (i don't think we need to do that)

### Scope a solution
we can add a condition to stop lazy load background-image with `data:image`
```
			if ( preg_match( '#data:image#is', $url['url'], $img ) ) {
				continue;
			}
```
after
https://github.com/wp-media/wp-rocket/blob/5afc9584b9e57e550231f5a8bfe8ae91fbd0b0cf/inc/Dependencies/RocketLazyload/Image.php#L60-L85

### Estimate the effort
[xs]
