### ISSUE TITLE
Compatibility with Bullet Proof Security plugin

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#53]
When a customer activates the BPS plugin and uses their htaccess option, BPS automatically removes everything from the htaccess file and replaces it with their own stuff. So the customer needs to manually paste WP Rocket rules in the custom area of BPS. Even though this is stupid by BPS, is there a way we can detect and automatically place our rules in the necessary place to make it easy for the customer?
example: https://secure.helpscout.net/conversation/110133796/5685/

**Comment by Screenfeed** [comment]
Confirmed.
Rocket .htaccess rules disappear when BPS is installed.

Side note: WP rules and Move Login rules stay in place.

**Comment by ScottTravisHartley** [comment]
Version 3.1 of BPS looks like it resolved this issue. 

https://forum.ait-pro.com/forums/topic/bps-changelog/

BugFix: Setup Wizard AutoFix: WP Rocket htaccess code and Custom Code check and code removal fix. Remove/delete the WP Rocket plugin skip/bypass rule htaccess code from Custom Code text box: 10. CUSTOM CODE PLUGIN/THEME SKIP/BYPASS RULES when the WP Rocket plugin is deactivated or deleted.

**Comment by arunbasillal** [comment]
I just tested this and the latest version of BPS 3.7 and the issue no longer exists. Our .htaccess rules are preserved.
