### ISSUE TITLE
What is NitroPack doing that WP-Rocket is not doing?

### ISSUE THREAD

**Issue by rodentooth** [wp-media/wp-rocket#5302]
**Is your feature request related to a problem? Please describe.**
The problem is that NitroPack drastically improves my sitespeed (from 10-20 score to 70-80 Score), while wp-rocket only increases it mediocre. (30-40 Score).

**Describe the solution you'd like**
What is NitroPack doing in order to speed up my site so good?

I have checked the manual settings of NitroPack and applied every rule to wp-rocket, including deferred and delayed JS, minified source files and other. Still, under NitroPack, my site reaches around 70-80 Pagespeed scores, and with WP-Rocket only about 30-40. 

**Is there a way to check what else NitroPack is doing in the DevConsole and to apply these settings to WP-Rocket? Or is there some general difference between the methods these two plugins are offering?**

I have connected WP-Rocket to Cloudflare, NitroPack is using Cloudflare cdn as well. 

I think that with the right configuration, the same results are possible with WP-Rocket, as I like WP-Rocket way more. But how? Can you help me find out how I can see deeper inside of the functionality of the methods of these 2 plugins?

**Comment by GeekPress** [comment]
Please open ticket on our support page to get help from our engineers: https://wp-rocket.me/support/

Our Github repository is used to discuss issues related to WP Rocket, and nothing else.

Thanks
