### ISSUE TITLE
DJE compatibility with Impreza datepicker (used on forms)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5304]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When DJE is used with Impreza's form date picker, the following error shows up on the browser's console: 

```
jquery.min.js:2 Uncaught TypeError: $input.datepicker is not a function
    at HTMLInputElement.<anonymous> (us.core.min.js:151:573)
```

The date picker popup doesn't show up.

Excluding the following from Delay JavaScript Execution fixes the issue: 

```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/wp-includes/js/jquery/ui/datepicker.min.js
```

Not adding a PR as this one will require adding a compatibility file for Impreza. 

**To Reproduce**
1. Use Impreza + a form with a date picker
2. Enable DJE without any exclusion
3. See error

**Expected behavior**
No error should happen if the form uses the date picker.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1973373781/360876/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
