### ISSUE TITLE
RUCSS better compatibility with Elementor's elements delivered using webpack.runtime

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5305]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Elementor on some occasions will dynamically inject elements using JavaScript the RUCSS SaaS won't be able to catch the resulting markup and add it to the Used CSS. Manual safe listing is required.

Elementor will usually add an empty wrapper on the DOM. 

Because Elementor manages injecting scripts using the `webpack-pro.runtime.min.js` script, we can't set accurate conditions to safelist missing elements in this scenario. 

We will be forced to use `webpack-pro.runtime.min.js` as the first condition before checking the DOM to see if an element is there or not. 

Both potential conditions are used on all Elementor's pages.

That will impact the speed of processing Elementor pages and potentially the overall SaaS performance.

A possible fix is adding hints about these elements' presence in a way that SaaS can easily process. 

There is an action on Elementor - `elementor/frontend/the_content` to filter the frontend content - ([hook doc](https://developers.elementor.com/docs/hooks/frontend-content/)).

We can use it to add our own hints to cover cases where there is no possible condition specific to the element to safelist. So we don't be forced to use a broader condition + DOM condition to make the safelist happen.

A quick implementation can use a fake CSS file that will only show up if `?nowprocket` is used.

We can add the following as part of our Elementor's compatibility file: 

```
function add_element_hint($content)
{
    if (!isset($_GET["nowprocket"])) {
        return $content;
    }
    $conditions = [];
    $conditions["elementor-icon"] = '<div class="elementor-icon-wrapper">';
    $conditions["elementor-toc"] = '<div class="elementor-toc__body">';
    foreach ($conditions as $condition_key => $condition_value) {
        if (strpos($content, $condition_value) !== false) {
            $content =
                '<link rel="stylesheet" href="/path/to/fake/css.css?' .
                $condition_key .
                '">' .
                $content;
        }
    }
    return $content;
}
add_action("elementor/frontend/the_content", "add_element_hint");
```

This will add `<link rel="stylesheet" href="/path/to/fake/css.css?elementor-icon">` when it notices a DOM target we want to use as a condition. In this example, `elementor-icon-wrapper`. 

Safelisting on SaaS would use `css.css?elementor-icon` as the only condition without requiring DOM conditions (as we already did the check on the server-side), and then uses the safelist pattern needed for this case.

**To Reproduce**
N/A

**Expected behavior**
We should have a more accurate way to safelist injected elements.

**Screenshots**
N/A

**Additional context**
Example of case where it can help - https://github.com/wp-media/nodejs-treeshaker/issues/116
Slack convo - https://wp-media.slack.com/archives/C029G1B5HD2/p1660220873137639

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
