### ISSUE TITLE
DJE skips urls with type= parameter in the query string

### ISSUE THREAD

**Issue by gayanchandrab** [wp-media/wp-rocket#5307]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :white_check_mark: 3.11.5
- Used the search feature to ensure that the bug hasn’t been reported before  :white_check_mark:

**Describe the bug**
DJE excludes delaying JavaScript requests with urls that have a parameter 'type=' in the query string which are not specifically added to DJE exclusions in plugin settings.

**To Reproduce**
N/A

**Expected behavior**
Enable DJE for JavaScript urls containing 'type' parameter in the query string.

**Screenshots**
![dje_bug_2022-08-14 09_50_58-Window](https://user-images.githubusercontent.com/38464697/184524137-ae1b0c36-78d7-48ad-bd47-5ed65dc15ea6.png)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
