### ISSUE TITLE
WP Rocket | Enforce Trailing Slash on URLs isnot working probably on single site with subdirectory while WPR is activated

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5310]
**Before submitting an issue please check that you’ve completed the following steps:**
- Make sure you’re on the latest version => 3.11.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When accessing the post URL in a subdirectory i.e domain/dir/post, we automatically redirected to domain/post while Enforce Trailing Slash on URLs is activated

**To Reproduce**
Precondition:
1- WPR installed and activated on Apache server with subdirectory i.e https://mega.wp-rocket.me/avada/
2- Install and activate https://github.com/wp-media/wp-rocket-helpers/raw/master/htaccess/wp-rocket-htaccess-trailing-slash/wp-rocket-htaccess-trailing-slash.zip

1. As a guest user, open post URL without / i.e https://mega.wp-rocket.me/avada/hello-world => auto redirection occurs to https://mega.wp-rocket.me/hello-world/

**Expected behavior**
A trailing slash is added to the URL without changing it

**Screenshots**

https://user-images.githubusercontent.com/76941962/184876277-f2cbacd0-6507-438c-8b26-447f8efe0e9c.mp4

**Additional context**
- If we deactivate WPR or the helper plugin, the URL will be accessed correctly without auto redirection
- Same occurs to the guest user if permalinks with/without /
- If permalinks without /, it will occur to logged in user as well (also cache for logged in is disabled)
- The same problem exists on multisite if we used https://github.com/wp-media/wp-rocket-helpers/raw/master/htaccess/wp-rocket-htaccess-trailing-slash-multisite/wp-rocket-htaccess-trailing-slash-multisite.zip
- The same problem exists when using https://github.com/wp-media/wp-rocket-helpers/raw/master/htaccess/wp-rocket-htaccess-remove-trailing-slash/wp-rocket-htaccess-remove-trailing-slash.zip on single site using Apache while permalinks are without `/` like https://mega.wp-rocket.me/avada/hello-world/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
