### ISSUE TITLE
3.12-alpha3 Database error - Specified key was too long

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5318]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On 3.12-alpha3 I get these database errors logged https://snippi.com/s/rtdv3fw

**To Reproduce**
It happens as soon as WP Rocket is activated. It's on a local site. 
Server info:
https://jmp.sh/lO8p5PP
https://jmp.sh/IpTQLiS

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The issue is there also on `alpha4`, confirmed with @webtrainingwheels

**Comment by piotrbak** [comment]
Working solution is to limit number of characters:
`UNIQUE(url(150))"`
https://github.com/wp-media/wp-rocket/blob/c53d551c38788c3ac1e171cf60b52af4c777c204/inc/Engine/Preload/Database/Tables/Cache.php#L47-L54

We've already done this for RUCSS and haven't seen issues so far:
https://github.com/wp-media/wp-rocket/blob/df46486ccb8cf5358f8b4ec4883672ab791e4dcd/inc/Engine/Optimization/RUCSS/Database/Tables/UsedCSS.php#L65

**Comment by Tabrisrp** [comment]
the url is not a KEY though for the cache table. The other values used as KEY are the same (id, modified, last_accessed)

**Comment by remyperona** [comment]
We can increase the value of the url column to 2000, and use a maximum of 191 for the unique key

**Comment by piotrbak** [comment]
```
We can increase the value of the url column to 2000, and use a maximum of 191 for the unique key

```
Confirmed with @webtrainingwheels that those values are not generating error. @wp-media/php please update whenever you can 🙏

**Comment by xaquinr** [comment]
Sorry, english is not my natural language...

In table _wpr_rucss_used_css change ROW_FORMAT to DYNAMIC
