### ISSUE TITLE
Fatal error when updating to 3.12

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5328]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When updating to 3.12 we can see the following fatal error:
https://snippi.com/s/mfbn9j1
https://snippi.com/s/4il048x

**To Reproduce**
1. Update from 3.11.5 to 3.12
2. See error

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by magnoliaman** [comment]
Same fatal error: https://share.businesswright.com/GGuzP7Oo
