### ISSUE TITLE
WPR can be deleted on multisite although it is active on a sub-site

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5335]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WPR can be deleted from multisite although it is active at subsite + `define( 'WP_CACHE', true );` not changed to false

**To Reproduce**
1. Install WPR on multisite
2. Activate WPR on subsite
3. Delete WPR from multisite

**Expected behavior**
Can't delete WPR if it's active on any site of multisite

**Screenshots**

https://user-images.githubusercontent.com/76941962/186151748-bba6f199-5ccf-48e9-9aa6-c6af9db37612.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
I can't reproduce this issue on my local multisite installation.

The delete link only appears at the network level when the plugin is deactivated on all sub-sites. If the plugin is active on at least one sub-site, the link doesn't show.

**Comment by remyperona** [comment]
After further investigation, this is an issue coming directly from WP core. A plugin enabled on a sub-site that is not the main sub-site can be deleted from the network without warning.

There is multiple tickets related to this:
- https://core.trac.wordpress.org/ticket/53255
- https://core.trac.wordpress.org/ticket/31673
- https://core.trac.wordpress.org/ticket/53132
