### ISSUE TITLE
Too many URLs in the Never Cache URL(s) will break that feature

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5339]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: 3.11.4.2
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Too many URLs in the Advanced Rules>Never Cache URL(s) will break the feature and generate an error in the WordPress log:

`[24-Aug-2022 08:41:05 UTC] PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 43057 in /var/www/clients/client1/web8/web/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-tests.php on line 604`

This will cause this feature to not work at all.  
Cache will be generated for all URLs added in the Never Cache URL(s) option.

**To Reproduce**
1. Go to Advanced Rules>Never Cache URL(s)
2. Add 1200+ URLs
3. Save changes
4. Check WordPress log
5. Check /wp-content/cache/wp-rocket?example.com -> Never Cache URL(s) are generated.

**Expected behavior**
WP Rocket should display a message when the limit of Never Cache URL(s) is reached or WP Rocket should not limit the Never Cache URL(s) at all.

**Screenshots**

**Additional context**
related: https://secure.helpscout.net/conversation/1985690155/363229/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Related issue:
https://github.com/wp-media/wp-rocket/issues/5339

**Comment by GeekPress** [comment]
It's an edge case here. If you have 1200 URLs to exclude, you must have a pattern to be able to use a regex and reduce the list.

I don't think it is worth working on that fix.

**Comment by piotrbak** [comment]
Yes, 1200+ is indeed and edge case. We should use a pattern in this case.
