### ISSUE TITLE
Auto-detect host from URL instead of fixed character limit for domain endings

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#534]
https://github.com/wp-media/wp-rocket/blob/fdee41ec2db637d2d4afc1dbd75f5b739b73661f/inc/functions/formatting.php#L122-L153

Since `rocket_get_domain()` is only used to detect host for our Cloudflare integration, there probably is no need to use a fixed character limit for the domain extension for extra validation?

The inline docs only mention “edge cases”, but not which type of. On the other end, this regularly causes customers with newer (longer) domain extensions to file support requests.

We should either remove the extra RegEx for the domain ending, or set the character limit to a value that covers modern domain endings.

**Comment by mnemotiv** [comment]
IMO should be used in conjunction with `rocket_extract_url_component( ... , ... )` on upcomming 2.11

**Comment by Tabrisrp** [comment]
function is not used anymore
