### ISSUE TITLE
Essential Addons login failure and page cache

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5340]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The [Essential Addons](https://wordpress.org/plugins/essential-addons-for-elementor-lite/) plugin manages the login/registration process. 

When a login fails, it will return a notification about it.

![image](https://user-images.githubusercontent.com/1289174/186416119-b2f47183-c621-40f5-a722-bd346ded80a1.png)

If the page is cached, the notification won't show.

This is caused by the fact that the Essential Addons adds the notification using PHP on the following method on their end: 

[/includes/Elements/Login_Register.php#L4395-L4408](https://github.com/WPDevelopers/essential-addons-for-elementor-lite/blob/63302a5226a289f6baadb498c0696b171e951b83/includes/Elements/Login_Register.php#L4395-L4408)

```
protected function print_login_validation_errors() {
    $error_key = 'eael_login_error_' . $this->get_id();
    if ( $login_error = apply_filters( 'eael/login-register/login-error-message', get_option( $error_key ) ) ) {
        do_action( 'eael/login-register/before-showing-login-error', $login_error, $this );
        ?>
        <p class="eael-form-msg invalid">
            <?php echo esc_html( $login_error ); ?>
        </p>
        <?php
        do_action( 'eael/login-register/after-showing-login-error', $login_error, $this );

        delete_option( $error_key );
    }
}
```

If the page cache is there, the notification won't show up. 

They have the following action `eael/login-register/before-showing-login-error` that fires before they add the notification. 

But it might not be usable in this specific case as we will return a cache response to the request.

Ideally, the Essential Addons should manage that notification using AJAX. 

**To Reproduce**
1. Use the Essential Addons
2. Use Elementor's popup on link click (so we stay on the same page to login)
3. Login with erroneous credentials

**Expected behavior**
Cache should ideally be cleared when the popup login fails. 

**Screenshots**
Added to the description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1987363595/363603/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
