### ISSUE TITLE
URLs with error 404, deleted, and trashed posts aren't removed from the wpr_rocket_cache table

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5346]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.0.3`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When:
* the status code of a URL is `404`
* a post of any post type is trashed and deleted

their URLs are not removed from the `wpr_rocket_cache` table. In fact, they are removed and readded with a different ID.

They remain there in an `in-progress` status. When `rocket_preload_revert_old_in_progress_rows` runs the status is changed to `pending` and then `in-progress` again creating a loop.

**To Reproduce**

1. Select a cached post whose status is `completed`.
2. Delete the post and checked the database.
3. It will be there as `pending` with a different `id`.

**Expected behavior**

URLs with an error 404 and posts that are deleted/trashed should be removed from the database.
Undeleting a valid URL should add it back.

**Additional context**

The ` delete_url_on_not_found()` is not currently used:
https://github.com/wp-media/wp-rocket/blob/bb4ab38d0c2f551259bce097d77d7efa4f16fc37/inc/Engine/Preload/Subscriber.php#L201-L205

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by CrochetFeve0251** [comment]
##  Identify the root cause
Problem comes from the fact the filter `pre_handle_404` is missing in the [Preload subscriber.](https://github.com/wp-media/wp-rocket/blob/bb4ab38d0c2f551259bce097d77d7efa4f16fc37/inc/Engine/Preload/Subscriber.php#L201-L205)
## Scope a solution
Add the filter `pre_handle_404` to the list of filters from the class with the following code:
```php
'pre_handle_404'  => 'delete_url_on_not_found',
```
##  Estimate the effort
Effort `XS`
