### ISSUE TITLE
Database guard when cache table is not created

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5351]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We have one ticket related to the `cache` table not being created:
https://snippi.com/s/uqa7zrn

**To Reproduce**
We're not sure how it's possible that this error happened. We can force it to happen manually:
1. Install WP Rocket 3.12.0.x
2. Go to db manager and remove the `wpr_rocket_cache` table
3. Run the preload
4. See error in logs

**Expected behavior**
We should:
1. Make sure that preload is not running and nto adding entries in the logs
2. Try to recreate the table
3. Display the error message:
**WP Rocket:** We detected missing database table related to Preload feature. We're trying to fix this problem automatically, if you're still seeing this message after refreshing the page, please contact our support team.

**Additional context**
Similar:
https://github.com/wp-media/wp-rocket/pull/4897/files

Related ticket:
https://secure.helpscout.net/conversation/1990501756/364243

We need to check:
1. The update process with/without the cache table in previous version
2. Manual removal of the table

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Scope a solution
We can prevent to execute logic by doing a check on the table class [`Cache`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Database/Tables/Cache.php) with the method `exists` and bail out if it returns `false` in each of the callback from the [Preload Subcriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Subscriber.php) and his [Front Subcriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Frontend/Subscriber.php).

Concerning the Notice we can add it in the [Settings](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Admin/Settings.php) class from the preload and hook it in the [Admin Subscriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Admin/Subscriber.php).
For the logic we can just use the table class [`Cache`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Database/Tables/Cache.php) with the method `exists`.

Finally to recreate automatically the table, we can register the `init` action in the Preload Subscriber and check the table exists with the table class [`Cache`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Database/Tables/Cache.php) using the method `exists` and it is not the case call the method `install` on the same class.

##  Estimate the effort
Effort `S`

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed could you double my grooming on that issue?

**Comment by alfonso100** [comment]
related https://secure.helpscout.net/conversation/1991884662/364557/

**Comment by engahmeds3ed** [comment]
Thanks @CrochetFeve0251 

In BerlinDB we already check if table exists with `admin_init` hook, and create/upgrade it when needed.

The problem may happen only when the CRON or frontend tries to deal with the table and it's not there, and the code to create the table isn't there as it's not the admin interface that triggers `admin_init`

Also we don't need to add admin notice because as mentioned, the table will be recreated once the admin panel is opened.

We have two options here:
1. Only guard the places that can be accessed from non-admin areas by using table exists method.
2. Hook the table creation with `init`

I prefer the first solution over the second one as it's better from performance perspective.

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed when I try in local and open admin if the table is deleted but not the option then it doesn't recreate the table.
This was to address this problem that we would like to display a notice when the table is missing.

**Comment by engahmeds3ed** [comment]
I believe this is not a real case, and I think we talked about this before that we may provide the users a button in the database tab in our settings to make like site health and have a button to recreate the missed tables if found.

the main issue was talking about the table not being created so there is no way to create the option without creating the table itself!

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1998433981/365950/

```
[02-Sep-2022 12:28:57 UTC] WordPress database error Table 'yosiga_NljdIjoq.w47fa_wpr_rocket_cache' doesn't exist for query SELECT  COUNT(*) FROM w47fa_wpr_rocket_cache wpr_cache WHERE wpr_cache.url = 'https://domain.ext/en/research-methods-in-anthropology' AND wpr_cache.status = 'in-progress' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ob_end_flush_all, ob_end_flush, WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer, do_action('rocket_after_process_buffer'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->update_cache_row, WP_Rocket\Engine\Preload\Database\Queries\Cache->is_preloaded, WP_Rocket\Dependencies\Database\Query->query, WP_Rocket\Dependencies\Database\Query->get_items, WP_Rocket\Dependencies\Database\Query->get_item_ids
```

I've seen it in the past targeting different plugins as well. It might be a server configuration issue. In this case, WP Rocket's table was the only one prompting the error though.
