### ISSUE TITLE
RocketCDN tab - Misspelled word bandwidth

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#5353]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In WP Rocket settings, on the CDN tab, the word bandwidth is misspelled. The word "bandwith" should be corrected to "bandwidth".
This text string is [located here](https://github.com/wp-media/wp-rocket/blob/dafdbedd6d30bb7d2eb74e622f178e100a723a47/inc/Engine/CDN/RocketCDN/views/cta-big.php#L42).

**To Reproduce**
1. Go to WP Rocket settings
2. Click on CDN tab
3. If you don't see RocketCDN banner with information about subscription, click on the **Learn More** button

**Expected behavior**
Use correctly spelled word

**Screenshots**
https://i.imgur.com/kRtyrfy.jpeg

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
@Tabrisrp 
Do we need to fix it [module-rocketcdn](https://github.com/wp-media/module-rocketcdn/blob/trunk/views/cta-big.php) too?
