### ISSUE TITLE
About the new preloader engine

### ISSUE THREAD

**Issue by fidoboy** [wp-media/wp-rocket#5357]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is related to the situation that happens when the new preloader (>= 3.12) engine takes the same time to warm up than the number maximum hours that Wordpress allows, that is, 10 hours to invalidate the nonces.

**Describe the solution you'd like**
There are many approaches to solve the issue, but I believe that the most obvious and easier could be to allow a list of URLs to be excluded from being preloaded BUT not from being cached. For example, in a big site where there is, let's say, 3000 different tags, it's a nonsense to generate all the time 3000 x 2 archives, so by using: /tag/(.*) all tags could be excluded from the warm up, but some of them could be cached when they have visits. The previous version were only using the sitemaps, but it seems that now are preloading also taxonomies and other pages not in sitemap.

**Describe alternatives you've considered**
One is the previous one, and also a less agressive engine that doesn't eat all CPU resources, by checking the average CPU usage and only doing the job when the value is under a certain number stablished by the user (like some plugins, like Duplicator Pro, does). Doing that way, if there isn't time to complete the whole cache, at least the CPU will not be overloaded. That way the preloader engine will not overload the CPU making the site unusable while working.

**Additional context**
Always test the plugin with the worst conditions, and not thinking only in servers with a lot of cores and thousands of Gb of RAM.

**Comment by DahmaniAdame** [comment]
That could benefit cases like this one where an attack pattern (URLs ending with `],`) were preloaded + had RUCSS jobs created and failed because they timed out.

Ticket - https://secure.helpscout.net/conversation/1985597795/363204/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1995477991/365332

**Comment by fidoboy** [comment]
Thanks @DahmaniAdame 

All of these issues are related but the problem still exists. It could be easy to accomplish and easy to use, a new text area into settings page to allow a list of URLs to be excluded from preload (but not from cache) as I suggested. There are sites with thousands of posts and tags and it has no sense to include them all into the initial preload. Under my point of view it has sense to give users some options to choose that. For example preloading pages first and then posts and finally taxonomies or other types. But it could be useful to have a interface to configure that if the user likes a different order.

Also I believe that considering the CPU usage when executing the cron could help to mantain server stable and to avoid unnecessary overloads. As I've said before, there are plugins that are using this method when doing intense file and DB operations to avoid collapsing the server. And it's a matter of having an option to stablish the desired value. A value that acts as a traffic light, under which the preload engine is inhibited from running

**Comment by paulherzlich** [comment]
There needs to be some control of the scope of caching and it needs to reflect the site structure. There are whole areas of my site that are not frequently visited and don't need to be preloaded. Not preloading them ensures that I don't overload the server and abuse my shared hosting contract. Previously I could select parts of my site by selecting only some of the sitemaps (generated by Rank Math). These sitemaps are hierarchical and reflect the WordPress permalink structure. In my case, we list 100's of properties, but they don't all need to be cached. Imagine a site with 1000's of products. The problem will be worse. The new initial preload is done based on the sitemaps. Why not restore the possibility to limit the sitemaps used as the basis of a preload? Why not allow users to specify the sitemap(s) to include or exclude in the preload. There is a secondary question I'd like to understand whether the new preload scheme precludes caching pages on the fly that were not in the initial preload, i.e. a page not found in the sitemap for SEO reasons, for example.

**Comment by etoc-ro** [comment]
We have almost 32000 url to preload including tags, categories and attributes, excluding attributes save us almost 3000 pages and excluding outofstock products almost 6000 and now we only need to preload 23000 pages but even then it would not finish preloading because is slow (don’t know why) and the server is a 32 cores with 128gb ram and nvme storage with avarage load 6.

A new option useful would be the order of preloading like pages, tags, posts, category, instock products, attributes and so on OR preload urls with the most traffic first (this info i think is in rankmath).

**Comment by piotrbak** [comment]
Hello everyone, since this issue is very overall, I'm about to close it.

I opened one related to regex exclusion from the preload:
https://github.com/wp-media/wp-rocket/issues/5394

Handling high CPU was improved a lot in the 3.12.0.5 and we'll be focused on that even further during upcoming minor releases. Due to the fact that we use Github for development purposes, each improvement will be described in the separate issue.
