### ISSUE TITLE
Action Scheduler crashed table causes fatal error

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5358]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Action Scheduler table is corrupted, enabling WP Rocket is not possible, as it causes fatal error:
https://snippi.com/s/eorhryc
https://snippi.com/s/gjwbowh

**To Reproduce**
1. Make sure that actions table is crashed
2. Enable WP Rocket
3. See error

**Expected behavior**
If possible, we should guard against it.

**Additional context**
It looks like the problem was also present with RUCSS before.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
For some reason the snippi links with errors are not opening for me.

There seems to be a related issue in the ticket here: https://secure.helpscout.net/conversation/1992023959/364575/

Error:
```
Fatal error: Uncaught RuntimeException: Error saving action: Table './XXXXXX/XXXXXXactionscheduler_actions' is marked as crashed and last (automatic?) repair failed in /MultiSite/XXXX.fr/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php:86 
Stack trace: 
#0 /wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action)) 
#1 /wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ActionFactory.php(69): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) 
#2 /wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php(19): ActionScheduler_ActionFactory->async('rocket_preload_...', Array, 'rocke in /wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php on line 86
```

**Comment by engahmeds3ed** [comment]
@piotrbak 
How can I make the DB table crashes?

From what I understand the table crashes from one of the following reasons:-
1. Hard disk failure.
2. Sudden server reboot.

or any other thing that may lead to those two reasons, so the only solution here is to repair the table.

So I can't find a way to detect the corrupted/crashed tables, also WP tried to automatically repair it as in the second message and failed also in that, right?

**Comment by piotrbak** [comment]
@engahmeds3ed Not sure, in the example I shared I had to manually repair the table from PHPMyAdmin, and it worked. I assume WP is doing something different. 

The repaired table was full of old actions including former RUCSS.

**Comment by alfonso100** [comment]
related https://secure.helpscout.net/conversation/1995486700/365334?folderId=273766

**Comment by vmanthos** [comment]
@engahmeds3ed I got the same error with a fresh install of the current `trunk` when no AS tables existed in the database.

In an existing `3.12.*` installation, deleting the `wp_actionscheduler_actions` table should through the fatal error: https://snippi.com/s/v7iu8lz

This is happening with `3.12.*` but not with `3.11.5` where we display the notice to create the missing tables.

**Comment by piotrbak** [comment]
@vmanthos This sounds like a different problem, could you create a new issue about this, so we could guard early?

**Comment by piotrbak** [comment]
Closing as we won't be able to find the corrupted tables.
