### ISSUE TITLE
CDN rewrite doesn't run for custom WP Media upload path

### ISSUE THREAD

**Issue by foliovision** [wp-media/wp-rocket#536]
We don't like the default /wp-content/uploads WP Media Library directory, we use /images.

Since WP Rocket 2.10 (I think) this stopped to work with WP Rocket CDN rewrite.

Here's a quick fix which we created to help our websites stay in CDN: #535

Could you please rewrite it and merge?

Thanks,
Martin

**Comment by foliovision** [comment]
Hello,

could you please let us know about the above?

Thanks,
Martin

**Comment by Tabrisrp** [comment]
It is a valid enhancement suggestion, as the uploads folder can be modified pretty easily.

I commented on the PR as I think it can be improved
