### ISSUE TITLE
Conflict between Monolog 1.x and 2.x

### ISSUE THREAD

**Issue by daigo75** [wp-media/wp-rocket#5366]
**Describe the bug**
In a recent update (version 3.12.0.3), WP Rocket seems to have started using version 2.x of the Monolog library. This causes conflicts with plugins that still use version 1.x (all of mine, for example). 

Although the interface of the two versions is compatible, the code in itself is not. Due to that, when the autoloader fetches some files from version 1.x and some from version 2.x, that triggers a fatal error. Example:
```
Fatal error: Uncaught Error: Undefined class constant 'Monolog\Utils::DEFAULT_JSON_FLAGS' in /path/to/plugins/wc-aelia-foundation-classes/src/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php on line 194
Call stack:
#0 Monolog\H\AbstractHandler::getDefaultFormatter() wp-content/plugins/wc-aelia-foundation-classes/src/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php:113
#1 Monolog\H\AbstractHandler::getFormatter() wp-content/plugins/wc-aelia-foundation-classes/src/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:37
#2 Monolog\H\AbstractProcessingHandler::handle() wp-content/plugins/wc-aelia-foundation-classes/src/vendor/monolog/monolog/src/Monolog/Logger.php:344
#3 Monolog\Logger::addRecord() wp-content/plugins/wc-aelia-foundation-classes/src/vendor/monolog/monolog/src/Monolog/Logger.php:642
```
The error refers of files loaded from Monolog 1.x, located at `/wc-aelia-foundation-classes/src/vendor/monolog/monolog`. For some reason, when the class `AbstractHandler` loads, it loads a line formatter from Monolog 2.x, such as `NormalizerFormatter` or `HtmlFormatter`. These reference constant `Utils::DEFAULT_JSON_FLAGS`, which doesn't exist in Monolog 1.x, thus causing a fatal error.

**To Reproduce**
1. Install and activate WP Rocket with Monolog 2.x.
2. Install and activate a plugin that runs Monolog 1.x. Our Aelia Foundation Classes and the Currency Switcher (the latter is not public, but I can provide a copy of it).
3. Open a page on the frontend that triggers the logging of some operation. In the case of the Currency Switcher, a simple currency selection using the widget can do the trick.

**Expected behavior**
There shouldn't be a fatal error caused by conflicting versions of the Monolog library.  This could be achieved in two ways:

1. Rolling back the Monolog library in WP Rocket to 1.x. The older version works like 2.x, in terms of calls, therefore you wouldn't have to make changes to your code.
2. Namespacing the Monolog library used WP Rocket, with a tool like [Mozart](https://github.com/coenjacobs/mozart), so that it doesn't conflict with the root namespace. This would allow you to keep Monolog 2.x in your code, without affecting any other plugin that uses version 1.x.

**Additional context**
The issue occurs whenever pieces of two incompatible versions of the Monolog library are loaded at the same time. We can't move to version 2.x because we must maintain compatibility with PHP 7.1 for a while longer. Also, there are other plugins that could be using Monolog 1.x, for the same reason, and upgrading to 2.x would simply "shift" the conflict onto them.

**Comment by daigo75** [comment]
I sent an email to your support contact, with a link to download the latest Currency Switcher. That should allow you to reproduce the issue easily.

**Comment by NataliaDrause** [comment]
This is the ticket: https://secure.helpscout.net/conversation/1993213637/364883?folderId=3864740

**Comment by daigo75** [comment]
**Additional note**
A client reported that the conflict apparently doesn't arise with PHP 8.0, whereas it occurs with PHP 7.4. However, we can't explain why.

I wouldn't rely on this information as a possible solution. I just added it to this conversation to speed up the testing, as the error might not occur with some PHP versions.

**Comment by piotrbak** [comment]
@daigo75 thank you for creating the issue. Could you check if `PHP8.x` is available on the server while WordPress is using `PHP7.x`?

**Comment by piotrbak** [comment]
Potentially related issue:
https://github.com/wp-media/wp-rocket/issues/5306

**Comment by daigo75** [comment]
The client indicated that, on a staging site, the issue occurred with PHP 7.4. When they switched to PHP 8.x, it didn't occur. However, it also didn't occur anymore with PHP 7.4 after switching back. There wasn't a mix of PHP versions, WordPress used the one configured on the system.

I'm afraid that we can't rely on PHP to load all the files from one location to avoid mixing up files. As long as two incompatible packages exist within the same namespace, the autoloader could pick up files "here and there" and cause the conflict. 

I don't think that issue #5306 is related. That seems to be linked to PHP requirements present in some package, or dependency. In the case I reported, the issue that pieces of two different versions of Monolog are loaded by the autoloader.

**Comment by piotrbak** [comment]
@Tabrisrp Your feedback here would be very valuable, could you take a look?

**Comment by daigo75** [comment]
If I may add a personal note, this issue is not particularly rare, nor necessarily difficult to address. It's a know fact that WordPress lacks any sort of dependency management, and plugins that bundle different versions of the same libraries may introduce clashes.

I came across a similar issue with the Bundles plugin, about a year ago. That plugin also bundled Monolog 2.x, but it turned out that it was added as a dependency of a dependency of another dependency (very quirky). The Bundles plugin didn't need it at all, so they found a way to remove it and only keep what they needed.

Overall, namespacing the dependencies, like one does with functions in the global scope (e.g. `my_name_get_price()`, rather than a generic `get_price()`) sounds like a good long term solution.

**Comment by remyperona** [comment]
While we don't particularly need v2 in our plugin usage, we upgraded the version because we had users requests for it, and conflicts with other plugins or systems who already updated to v2, notably when using composer installation.

We considered using Mozart to namespace Monolog within our code, but that means bringing hundreds of classes into our committed repository when we use a very small subset of them.

**Comment by daigo75** [comment]
@Tabrisrp unfortunately, I'm afraid that the only ways to prevent conflicts are the two ones I described. With Monolog 2.x, you risk conflicts with plugins using 1.x. With 1.x, you risk conflicts with 2.x (which, based on the past 9 years of experience, are less common).

From our side, I confirm that we won't move to Monolog 2.x yet, so that's not an option. 

Adding a namespace is not too bad. You don't have to store the whole library in your repository, it can be installed with Composer during the development or build phase. Our plugin also use three or four files from it, and not a single one is stored in the repo. You have to bundle the whole library in the distribution, anyway, so there's no change from that perspective. 

Unless you can find a third option, I believe that namespacing is the best option in the long term.

**Comment by daigo75** [comment]
From my specific side, in addition to the technical aspect, there's also the user experience factor. I've been recommending WP Rocket to dozens of customers, for the past 8 years, because it includes native support for our solutions, out of the box. Unlike alternative plugins, which require some tinkering, WP Rocket just works. However, if the users were to switch to WP Rocket and see a crash, which is actually due to an **incompatibility**, that could damage the credibility of both brands. 

That's why I've prioritised this issue from our side as well. I needed to find a permanent solution quickly, before the user base gets "panicky".

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/1995774773/365380?folderId=2683093

With https://wordpress.org/plugins/wp-piwik/ (60k installs)
error log and environment information is in the ticket

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/1999666497/366226/

With https://wordpress.org/plugins/matomo/ (60k installs)

error in the ticket:

```2022-09-05 09:22:24 'Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=1.=day&date=2022-09-05&format=json&trigger=archivephp. Response was \'PHP Fatal error: Declaration of Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::handle(array $record) must be compatible with Monolog\\Handler\\AbstractProcessingHandler::handle(array $record): bool in $abs_path/wp-content/plugins/matomo/app/vendor/symfony/monolog-bridge/Symfony/Bridge/Monolog/Handler/ConsoleHandler.php on line 88```

**Comment by WordPresseur** [comment]
Another case here: https://secure.helpscout.net/conversation/1996450797/365527/

With [Thrive Architect page builder plugin](https://thrivethemes.com/architect/)

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/2001124249/366767?folderId=3572159

unknown plugin

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/2029244386/373087/

plugin: https://wordpress.org/plugins/wp-simple-firewall/

**Comment by worldwildweb** [comment]
related https://secure.helpscout.net/conversation/2056760031/379142/

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/2074615401/383342?folderId=3864740
plugin: "Next Active Directory Integration"

**Comment by CrochetFeve0251** [comment]
For this issue we have two potential solutions:
- Include Monolog into mozart protected libraries.
- Stop shipping the logger into WP-Rocket and ship it in an helper plugin.

The first solution is the most simple but it will had lot of classes to wp-rocket sources which is not optimal.
The second solution would have less drawbacks. However we need to check if it is in fact possible.

A more detail version of the second solution is available here: https://wp-media.slack.com/archives/GUT7FLHF1/p1681826700475929

**Comment by daigo75** [comment]
I've done both (namespacing Monolog and using a helper plugin), the latter for the past 10 years. If my experience can be of any help, please let me know and I will be happy to talk about my "journey".

**Comment by ethanclevenger91** [comment]
The same issue is turning up when installed alongside [Event Tickets](https://wordpress.org/plugins/event-tickets/) (and any of their other plugins that use the `tribe-common` library. 

They seem to be using a Mozart fork called [Strauss](https://github.com/BrianHenryIE/strauss), FWIW.

**Comment by piotrbak** [comment]
`Related` - https://secure.helpscout.net/conversation/2241671075/419738?folderId=273766
`Slack` - https://wp-media.slack.com/archives/C43T1AYMQ/p1684220567379279?thread_ts=1684217755.309949&cid=C43T1AYMQ

**Comment by CrochetFeve0251** [comment]
## Scope a solution
To solve that issue we can create a custom monolog package where we keep only classes that we use.
For that we need to keep theses classes and their dependencies:
```
Monolog\Logger
Monolog\Registry
Monolog\Processor\IntrospectionProcessor;
Monolog\Handler\StreamHandler
Monolog\Formatter\LineFormatter
Monolog\Formatter\HtmlFormatter
Monolog\Handler\StreamHandler
```
Then we will have rename the package to `wp-media/monolog` and include it as dev dependency into the project.
And protect it with mozart using the 'extra': 'mozart':' packages' field in `composer.json`.

Finally we will remove the Monolog package from the dependencies and add to each Monolog import the prefix `WP_Rocket\Dependencies\`

Finally we will have to change the content from[ `advanced-cache.php`](https://github.com/wp-media/wp-rocket/blob/develop/views/cache/advanced-cache.php) and replace :
```php
			$file = $rocket_path . 'vendor/monolog/monolog/src/' . str_replace( '\\', '/', $class ) . '.php';
```
by 
```php
			$file = $rocket_path . 'inc/Dependencies/WPMedia/Monolog//' . str_replace( '\\', '/', $class ) . '.php';
```

Then we will have to update `advanced-cache.php` on update from wpr inside [`PurgeActionsSubscriber`](https://github.com/wp-media/wp-rocket/blob/7273ea63aa9ababb3448ef532bb11d6d19a7d529/inc/Engine/Cache/PurgeActionsSubscriber.php):
```php
public function on_update( $new_version, $old_version ) {
		if ( version_compare( $old_version, '3.12', '>=' ) ) {
			return;
		}
		rocket_generate_advanced_cache_file();
	}
```
## Estimate effort
Effort `S`
