### ISSUE TITLE
No selective preloading?

### ISSUE THREAD

**Issue by mcmito** [wp-media/wp-rocket#5368]
Thanks to sitemaps, it was previously possible to keep certain areas of a website from being preloaded and thus avoid long processing times. Unfortunately, this is no longer the case.

I wish there was a way to specify which areas (e.g. through selecting post types, taxonomies or even an url range) should be cached but not automatically preloaded. 

My website has over 30k posts of which I only want to have about 2000 preloaded. The long processing time for preloading is really not reasonable in my case at the moment. 
The only emergency solution I can think of is to exclude the url area from the cache :-/

**Comment by piotrbak** [comment]
Hello @mcmito and thanks for creating the issue. We already have that kind of feedback from [customer](https://github.com/wp-media/wp-rocket/issues/5357), I'm marking it as a duplicate then.
