### ISSUE TITLE
Improve is_already_cached function to cover webp

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5374]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
`is_already_cached` function is the one that wasn't touched for a while. We're not looking for `-webp` files there.

**To Reproduce**
1. Enable webp addon, separate cache for mobiles on a website that contain webp images
2. Enable preload and visit page with webp image on desktop
3. The cache file is created
4. When the page is processed, we'll be looking for wrong path without `-webp` and do 2 requests, since it's not found.

**Expected behavior**
We should detect the `-webp` cache files to prevent additional requests in specific conditions.

**Additional context**
We also need to cover the scenario when webp addon is enabled, but on there are no webp images on the page. Then the filename will be just a regular one `index-https.html` or `index-mobile-https.html` and small `.no-webp` file will be present in the directory.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
### Scope a solution
In the `is_already_cached` method from `PreloadUrl` :
- Check if the option `cache_webp` is enabled.
- If it is not the case keep the original process.
- If it is not the case then:
    - Create a path to search for `$webp_path  = rocket_get_constant( 'WP_ROCKET_CACHE_PATH' ) . $url['host'] . strtolower( $url['path'] . $url['query'] ) . 'index' . $mobile . $https . '-webp.html'`
    - Create a path for `$path = rocket_get_constant( 'WP_ROCKET_CACHE_PATH' ) . $url['host'] . strtolower( $url['path'] . $url['query'] ) . 'index' . $mobile . $https . '.html'`
    - Create a path for `$no_webp_path = rocket_get_constant( 'WP_ROCKET_CACHE_PATH' ) . $url['host'] . strtolower( $url['path'] . $url['query'] ) '.no-webp'`
- Then we need to apply the following condition to check if the file exists:
`$this->filesystem->exists( $webp_path ) || ($this->filesystem->exists( $no_webp_path ) && $this->filesystem->exists( $path ))`

### Estimate effort:
Effort `S`
