### ISSUE TITLE
Decrease the usage of CPU when preload is used

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5376]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
For the preload we use a separate queue runner in Action Scheduler. However, the default behaviour of AS is that whenever default runner is idle, it takes the next free action from the queue. We can end up with 2 queue runners running at the same time.

**To Reproduce**
1. Use WP Rocket 3.12+, Separate Cache for Mobiles is enabled
2. Log the requests that are sent [here](https://github.com/wp-media/wp-rocket/blob/3aee06a4fd1a4a9a40a7514e0b03ba97ad20c2ae/inc/Engine/Preload/Controller/PreloadUrl.php#L130).
3. Check what's logged
4. You'll see that between the requests to the same URL (mobile and desktops), there are requests from another runner

**Expected behavior**
We need to:
1. Use separate RUCSS queue runner for RUCSS only
2. Make sure there's no Preload specific queue runner and use the default one instead

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Scope a solution
First thing we will have to do is do  delete the queue runner [`PreloadQueueRunner`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Common/Queue/PreloadQueueRunner.php) and places where it is used:
- In the service provider: https://github.com/wp-media/wp-rocket/blob/6be2f4ffb2968262aaa096c5ce9f6517297f2aab/inc/Engine/Preload/ServiceProvider.php#L121
- In the Cron  Subcriber: https://github.com/wp-media/wp-rocket/blob/6be2f4ffb2968262aaa096c5ce9f6517297f2aab/inc/Engine/Preload/Cron/Subscriber.php#L241

Then inside the [`PreloadUrl` controller](https://github.com/wp-media/wp-rocket/blob/6be2f4ffb2968262aaa096c5ce9f6517297f2aab/inc/Engine/Preload/Controller/PreloadUrl.php#L140) we need to reduce the default value from `5000` to `4000`.

Finally we need to detect if more than one queue runner exist for that.



## Estimate the effort
Effort `S`

**Comment by remyperona** [comment]
is it possible to know how many queue runners exists? I can see we can know about concurrent batches, but that's not the same thing

**Comment by CrochetFeve0251** [comment]
> is it possible to know how many queue runners exists? I can see we can know about concurrent batches, but that's not the same thing

@Tabrisrp Yes I can't find anything on that and I was thinking asking @engahmeds3ed on that point.

**Comment by engahmeds3ed** [comment]
I don't think we can detect the number of queue runners but we can detect the default concurrent batches as u mentioned.

@piotrbak I believe detecting the default concurrent batches is what we need here, so when the filter for the default queue runner is used to change the concurrent batches we can show a notice or at least change the sleep time, what do u think?

**Comment by piotrbak** [comment]
@engahmeds3ed sounds good. We should display notice I believe

**Comment by engahmeds3ed** [comment]
but the end user won't be able to do anything about it and will not know which plugin is changing this concurrent

**Comment by GeekPress** [comment]
Displaying a notice should provide an easy solution to the user. If they can't resolve the issue themself easily, the notice won't be helpful.

**Comment by GeekPress** [comment]
>  or at least change the sleep time

@engahmeds3ed What will be changing here? And what will be the consequences?

**Comment by piotrbak** [comment]
@GeekPress 
```
Displaying a notice should provide an easy solution to the user. If they can't resolve the issue themself easily, the notice won't be helpful.
```
I was aiming to give information about this. 
1. If they're modificating the settings, I believe that they should now that it affects Preload.
2. If the settings are modified by 3rd-party, they don't know about that and have CPU problems. I was thinking it would be good to let them know, so they can find possible root cause quickly and contact us.
