### ISSUE TITLE
RUCSS to preserve inline CSS for the Divi range slider

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5378]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.5
- Used the search feature to ensure that the bug hasn’t been reported before - ues

**Describe the bug**
Range slider (filter) is missing some styling due to the dynamic inline CSS rules like `.et_pb_de_mach_search_posts_item_471437 .irs-bar`.
Numeric value is changing on each page load.

Inline style
![image](https://user-images.githubusercontent.com/60236665/187702856-e611ca1d-3449-4b3d-b1ef-fd33175af67e.png)

Solution is to preserve these inline styles with `rocket_rucss_inline_content_exclusions` filter.
However, preserving `.et_pb_de_mach_search_posts_item_` would preserve other non-dynamic styles, so this one should not be used.
For the current example, I preserved `.irs-bar`, so only the inline CSS with dynamic selectors are preserved.

I am opening this issue, so we can monitor similar cases and find the best content to preserve automatically.

**To Reproduce**
Reproduced on the customer's site.

**Expected behavior**
The range slider should have correct styles applied. Inline styles with dynamic CSS need to be preserved.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1989616299/364063/
Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1661547246172039

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria similar to the https://github.com/wp-media/wp-rocket/issues/4792:

1. We need to make sure `rocket_rucss_inline_content_exclusions` accepts regex
2. When adding  `.content-(.*) .inside` to the filter (or to the backend), content of the following internal CSS should be preserved in the HTML source:
```
<style>
.content-12356789 .inside{
	color:blue;
}
</style>
```
3. When adding  `.content-[0-9]* .inside` to the filter (or to the backend), content of the following internal CSS should be preserved in the HTML source:
```
<style>
.content-12356789 .inside{
	color:blue;
}
</style>
```
4. No regression in the existing cases. Adding `.content-` to the filter (or to the backend), will preserve the following internal CSS in the HTML source:
```
<style>
.content-12356789 .inside{
	color:blue;
}
</style>
```
5. When adding `.content-(.*) .inside` to the filter (or to the backend), the content of the following internal CSS should **not** be preserved:
```
<style>
.content-12356789 .outside{
	color:blue;
}
</style>
```

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
The usage of RegEx patterns is not currently working because the values passed are quoted before being used, so they are interpreted as normal characters instead.

### Scope a solution ✅ 
The solution would be to remove the usage of `preg_quote()` in the validation function, and replace it by an escaping for the `/` character as it's the one used as delimiter for the regular expression.

The downside of this is that usage of strings passed to the filter will have to be carefully done, as any error in patterns is going to create an error when parsing.

### Estimate the effort ✅
Effort [S]

**Comment by piotrbak** [comment]
At the end we'll just preserve the `.irs-bar`. We'll monitor situation for the need of grooming implementation.
