### ISSUE TITLE
Skipped tests because of missing data provider

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#5379]
We have some skipped tests because there is no data provider for them. The corresponding fixtures files are missing.

- ` WP_Rocket\Tests\Unit\inc\Engine\Common\Queue\PreloadQueueRunner\Test_Init`
- `WP_Rocket\Tests\Unit\inc\Engine\Preload\Admin\Settings\Test_MaybeDisplayAsMissedTablesNotice`
- `WP_Rocket\Tests\Integration\inc\Engine\Preload\Admin\Subscriber\Test_MaybeDisplayAsMissedTablesNotice`

**Comment by jeawhanlee** [comment]
Tests for 2 & 3 are now added [here](https://github.com/wp-media/wp-rocket/pull/5230).

**Comment by CrochetFeve0251** [comment]
Look like test 1 disappeared too on develop (surely @engahmeds3ed that removed it when he removed the preload queue runner)

**Comment by jeawhanlee** [comment]
@CrochetFeve0251 True! Closing issue as Test 1 will not be needed since the preload queue runner was removed [here](https://github.com/wp-media/wp-rocket/pull/5381) and also Tests 2 & 3 have moved [here](https://github.com/wp-media/wp-rocket/pull/5230)
