### ISSUE TITLE
Fatal error when install/activate WPR while WPR debug mode

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5386]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.0.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When activating WPR while `define( 'WP_ROCKET_DEBUG', true); ` , Fatal error is there
`[02-Sep-2022 05:16:55 UTC] PHP Fatal error:  Uncaught Error: Interface "Psr\Log\LoggerInterface" not found in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/vendor/monolog/monolog/src/Monolog/Logger.php:34
Stack trace:
#0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/advanced-cache.php(51): require()
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php(187): {closure}()
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php(83): WP_Rocket\Logger\Logger::get_logger()
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-abstract-buffer.php(120): WP_Rocket\Logger\Logger::info()
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php(62): WP_Rocket\Buffer\Abstract_Buffer->log()
#5 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/advanced-cache.php(75): WP_Rocket\Buffer\Cache->__construct()
#6 /var/www/new.rocketlabsqa.ovh/htdocs/wp-settings.php(95): include('...')
#7 /var/www/new.rocketlabsqa.ovh/wp-config.php(119): require_once('...')
#8 /var/www/new.rocketlabsqa.ovh/htdocs/wp-load.php(55): require_once('...')
#9 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/admin.php(34): require_once('...')
#10 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/options-general.php(10): require_once('...')
#11 {main}
  thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/vendor/monolog/monolog/src/Monolog/Logger.php on line 34
`

**To Reproduce**
1. Clone and install as per [doc](https://docs.wp-rocket.me/article/1301-wp-rocket-installation-from-github-using-composer)
2. Activate WPR
3. Fatal error

**Expected behavior**
No error when using WPR debug mode

**Additional context**
- Tested with PHP 8.1.8, WP 6.0.2
- Working fine without WPR debug mode

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
@Mai-Saad already answered to a similar issue [there](https://github.com/wp-media/wp-rocket/issues/5306).
