### ISSUE TITLE
trying to access array offset on value of type null in js_composer

### ISSUE THREAD

**Issue by atabakmorghi** [wp-media/wp-rocket#5390]
hi dear

when i want to edit every product my wp panel become very slow 
and when i enable dibug display i see this eror 

/home/myusernamesite/public_html/wp-content/plugins/js_composer/include/autoload/vc-shortcode-autoloader.php on line 64

line 64 is this : 

		if ( self::$config['classmap'] ) {
		
		
my wp panel for write article or another page don't have any problem and this problem only for edit product page.		
how solve this ?

**Comment by piotrbak** [comment]
Hello @atabakmorghi could you reach our support team and send us administrator access to your website? We'd love to debug this problem further.

**Comment by piotrbak** [comment]
We didn't have any further complain related to this one. Feel free to reopen with proper steps to reproduce if needed.
