### ISSUE TITLE
Selective max age for cache

### ISSUE THREAD

**Issue by fidoboy** [wp-media/wp-rocket#5395]
**Is your feature request related to a problem? Please describe.**
Problem happens specially on sites where 99% of pages and posts doesn't relies on use of nonces but there is a 1% that will need it.

**Describe the solution you'd like**
It could be useful to have an option to allow selective max age for only certain URLs. For example I set 48 hours as default, but for a a small list of URLs I want to set the max age to 10 hours (max allowed time for nonces in Wordpress)

**Describe alternatives you've considered**
The only alternative is to keep it as it is, having 10 hours for max age cache in all URLs.

**Additional context**
None

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
