### ISSUE TITLE
Update texts and banners for users with an expired license

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#5397]
The  messages for users with an expired license need to be updated:

- to inform users about the optimize CSS features that will/have disappear/ed
- to display the correct renewal price

Conditions and messages are available [here.](https://docs.google.com/spreadsheets/d/1Zu1MbsVNkOWCsW0CmVRuY69I0t3vtTLG4ykhuOI3YVI/edit?usp=sharing)

**Comment by CrochetFeve0251** [comment]
@Agathemed from  what I saw in the code we need to add new cases for the licence, am I right?

Just want to confirm before grooming.

**Comment by Agathemed** [comment]
I believe the only case that is not in place yet is the "not grand-fathered user" scenario.

**Comment by CrochetFeve0251** [comment]
@piotrbak look like the API doesn't provides us the information if an user is grand-fathered.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
We need to update all the banners to update the part related to the price + discount that is going to be offered.

In Engine\License\Renewal:
- Update `display_renewal_soon_banner()` method to check for grandfathered and change the message returned
- Update `display_renewal_expired_banner()` method to check for grandfathered and change the message returned
- Update the renewal views to display the new message from the variable
- Update the related tests

### Estimate the effort ✅
Effort `[S]`
