### ISSUE TITLE
 Iframes LazyLoad creates extra page when clicking "back"

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#54]
example - When you have iframes lazyload enabled and you click from a page onto another that has a video in it, then you click "back" on the browser, it adds an extra page, so you have to click twice to go back. video: https://infinit.io/_/R8TqHYD
ticket: https://secure.helpscout.net/conversation/132786690/7786/

**Comment by glueckpress** [comment]
Here’s another case with the same behavior:
* page with 2 iFrames
* for each iFrame a click “back” removes a previously lazy-loaded iFrame from the page, but doesn’t actually get us back to the previous _page_

![](http://g.recordit.co/arLf3cCfx7.gif)
