### ISSUE TITLE
Recent Woo change breaks logged in cache

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#540]
See https://github.com/woocommerce/woocommerce/commit/af1dce35446e6b3fbdf3006d25f9730bb85e1e01#diff-c0310299cb522d1c9add22898d47f915

Need to unhook WC_Cache_Helper::set_nocache_constants.

**Comment by Tabrisrp** [comment]
Thank you for reporting.

I opened an issue on their GitHub since the change is probably not meant to set `DONOTCACHEPAGE` for all logged-in users and it's an oversight on their part. To follow: https://github.com/woocommerce/woocommerce/issues/17210

**Comment by Tabrisrp** [comment]
This will be fixed with version 3.2.2 of WooCommerce with https://github.com/woocommerce/woocommerce/pull/17244
