### ISSUE TITLE
The more info link under Minify CSS>Excluded CSS Files leads to Excluding External JavaScript from Combine?

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5405]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 3.12.0.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The "more info" link under Minify CSS>Excluded CSS Files leads to [Excluding External JavaScript from Combine](https://docs.wp-rocket.me/article/39-excluding-external-js-from-concatenation)

**To Reproduce**
1. Go to [File Optimization](https://wpr.willychataigner.com/wp-admin/options-general.php?page=wprocket#file_optimization)
2. Enable Minify CSS Files
3. Click the link "more info" under Minify CSS>Excluded CSS
4. See that the link leads to [Excluding External JavaScript from Combine](https://docs.wp-rocket.me/article/39-excluding-external-js-from-concatenation)

**Expected behavior**
The "more info" link under Minify CSS>Excluded CSS Files should be [Resolving Issues with Minify CSS & Combine CSS](https://docs.wp-rocket.me/article/1131-resolving-issues-with-css-minify-combine)

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/1954918/189087222-0a701ae2-9f74-4c07-8f80-9e7a16b5776f.png)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Can we have the ID for the article, and the ID + URL for the FR versions?
