### ISSUE TITLE
Enhance preloading when there are additional layers of cache

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5406]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.0.5`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Currently, when one or more additional layers of cache are _not_ cleared in sync with WP Rocket, preloading URLs that are already cached in the extra layer will result in not storing a cached file to `/cache/wp-rocket/`. This is because the preload request is "intercepted" by that layer and WordPress doesn't load.

**To Reproduce**

1. Use an additional layer of cache, e.g. NGINX, Varnish, Cloudflare's "cache everything" (disabled Cloudflare add-on)
2. Make sure there are several URLs cached there (`cache: HIT` ).
3. Clear and preload the cache.
4. For URLs that are in the additional layer no cache file will be created on the server's disk and the `status` in `wpr_rocket_cache` will remain `in-progress`.

**Expected behavior**

Ideally, we should sync cache clearing with all additional layers of cache. Since this may not always be possible, we should be able to preload the cache effectively even when such layers exist.

**Additional context**

This came up after a discussion with @engahmeds3ed about how an additional layer of cache can negatively affect the preload speed with #5393, and it's meant to be used as a place to discuss potential solutions.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
@wp-media/php @piotrbak Following up on the idea of using a dedicated, cacheable query string to bypass additional layers of cache, we could make the query string dynamic to tackle cache layers that are caching query strings.

For example, we could append `cachewprocket_{dynamic part}` to the preload requests. The dynamic part could be a hash of the URL + `time()` to ensure query strings will not match.

We should modify the `can_process_query_string()` method to add  `cachewprocket` and process `$params` to remove the dynamic part:
https://github.com/wp-media/wp-rocket/blob/a0f61c8209462e2ce6abcc825c6d735e9591d145/inc/classes/Buffer/class-tests.php#L525-L568

To preserve the current functionality of preloading compatible additional layers of cache, e.g. Varnish, we can probably make the specific type of requests whenever we detect that we are _not_ in such environments.

**Comment by camilamadronero-zz** [comment]
related https://secure.helpscout.net/conversation/1982701968/362568/

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
