### ISSUE TITLE
Preload increases CPU and database memory

### ISSUE THREAD

**Issue by hoahieu655** [wp-media/wp-rocket#5408]
In my Action Scheduler generated over 300,000 preload links and the same log file since upgrading to you 3.11.5 (I have now upgraded to 3.12). Can I delete it?
My Database Action Schedule grows to almost 500MB

Image : https://i.imgur.com/SNp0Toq.jpeg

I have Yoast seo installed but in WP Rocket it doesn't automatically display compatible with Yoast sitemap link

**Comment by piotrbak** [comment]
Hello @hoahieu655 and thank you for creating the issue. We are using Github for development purposes, could you reach our 
support team to investigate the issue further?

>Can I delete it?
Yes, but please include URL of this issue in the support ticket.
