### ISSUE TITLE
WebP Cache bug when the UPLOADS constant is defined

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5409]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When a custom uploads file is defined using `define( 'UPLOADS', 'custom-wp-uploads' )`, building the WebP cache will fail at the following location: 

https://github.com/wp-media/wp-rocket/blob/c53d551c38788c3ac1e171cf60b52af4c777c204/inc/classes/subscriber/Media/class-webp-subscriber.php#L598-L601

And

https://github.com/wp-media/wp-rocket/blob/c53d551c38788c3ac1e171cf60b52af4c777c204/inc/classes/subscriber/Media/class-webp-subscriber.php#L559-L562

The reason for that `$src_path_webp` and `$asso_url` will reference the default `wp-uploads` instead of the new value `custom-wp-uploads`. 

This forces adding the `.no-webp` hidden file and for the WebP cache to not be generated or served. 

Changing the value before checking the condition fixes the issue. 

Respectively, just before the condition is done: 

```
if (defined('UPLOADS')) {
  $src_path_webp = str_replace('wp-content', UPLOADS, $src_path_webp);
}
```

And

```
if (defined('UPLOADS')) {
  $asso_url = str_replace('wp-content', UPLOADS, $asso_url);
}
```

**To Reproduce**
1. Used a custom uploads folder using `define( 'UPLOADS', 'custom-wp-uploads' )`
2. Enable WebP Cahce
3. See error

**Expected behavior**
WebP Cache should work even after using a custom Uploads folder. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1996911926/365623?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I was able to reproduce the issue.
## Identify the root cause
The root cause is the the custom path is outside the wp-content folder leading to not replace it.
 
## Scope a solution
The solution would be to add the folder upload mapping when it is not included inside the wp-content one.
For that we need to add the following logic after [this line](https://github.com/wp-media/wp-rocket/blob/fb6c1b30ed5d27f744b3c07ee754f7545fe436cc/inc/classes/subscriber/Media/class-webp-subscriber.php#L693):
```php
		$upload = wp_upload_dir();
		$upload_dir = trailingslashit($upload['basedir']);
		
		if( strpos($content_dir, $upload_dir) === false ) {
			$upload_url = preg_replace( '@^https?:@', '', trailingslashit($upload['baseurl']) );
			$list[$upload_url]  = $upload_dir;
		}
```
## Estimate the effort
Effort `XS`
