### ISSUE TITLE
Eliminate render-blocking resources and v3.12.0.5 September 1, 2022

### ISSUE THREAD

**Issue by privatedevops** [wp-media/wp-rocket#5415]
Hello,

Seems after WP rocket release version 3.12.0.5 September 1, 2022, there is some issue with "Eliminate render-blocking resources", after I revert back to older version, in my case  3.11.5 everything is ok.

**Comment by privatedevops** [comment]
The issue occur with both REMOVE UNUSED CSS or  LOAD CSS ASYNCHRONOUSLY

**Comment by piotrbak** [comment]
Hello @hostingidol thanks for creating the issue. We didn't change anything that could cause that kind of issue. Please reach our Support in order to investigate what has happened to your site. Thank you!
