### ISSUE TITLE
RUCSS - generatepress Theme - Navigation Bar/Search Icon Not working

### ISSUE THREAD

**Issue by jammy26** [wp-media/wp-rocket#5417]
**Describe the bug**
When using the RUCSS method for CSS Optimization, neither Hamburger Icon nor search icon works on Mobile in generatepress theme. The search icon also doesn't work on the Desktop.

Those icons show up but don't work. They work just fine with Method "Load CSS Asynchronously"

**To Reproduce**
My test website is online.

Go to with actual mobile browser
Click on Either Hamburger Icon or Search Icon

**Comment by piotrbak** [comment]
Hello @jammy26 thanks for creating the issue.

I wasn't able to reproduce any of the mentioned issues with GeneratePress:
1. Hamburger menu works fine and search icon is present on mobile
2. Search icon works just fine on desktops

Have you tried enabling Separate Cache for Mobile devices already?

If you're still experiencing the issue, please reach our Support Team for further investigation.
