### ISSUE TITLE
Adjust Preload notice 

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5423]
**Is your feature request related to a problem? Please describe.**
The [Preload notice](https://jmp.sh/CtTXxBi) is currently shown in when [clearing the cache](https://docs.wp-rocket.me/article/78-how-often-is-the-cache-updated#full-cache-deletion) and it has a [re-appearing behavior](https://wp-media.slack.com/archives/GUKB44GNN/p1663011215372739). This doesn't go inline with the continuous nature of the new Preload, and it's causing questions.

**Describe the solution you'd like**

1- Since Preload is now an ongoing and continuous process, almost infinite, the notice could be shown only:

- After enabling the plugin/Preload 
- When using the `Clear and preload cache` option (top bar and Quick Actions).

Customers can trust WP Rocket is already doing it smartly, and we'll have a clearer settings page.
We already do something similar by not showing the "Cache cleared" notice when changing themes, for example.

2 - Additionally, the notice should be dismissible.

**Additional context**
Slack discussions: https://wp-media.slack.com/archives/G8L4EE8N9/p1663089999191189 and https://wp-media.slack.com/archives/GUKB44GNN/p1663011215372739.

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/2017147213/370362/

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/2022286927/371469?folderId=2135277
