### ISSUE TITLE
Detect usage of Autoptimize's RapidLoad Used CSS  

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5424]
**Is your feature request related to a problem? Please describe.**
Currently, customers can enable [RapidLoad Power-Up for Autoptimize]( https://wordpress.org/plugins/unusedcss/) at the same time as WP Rocket's Remove Unused CSS, causing layout issues or stuck Used CSS generation problems.

**Describe the solution you'd like**
WP Rocket could detect the usage of RapidLoad Remove Unused CSS and gray out Remove Unused CSS in WP Rocket, showing a notice similar to [the one shown when Autoptimize's minification is detected](https://d33v4339jhl8k0.cloudfront.net/docs/assets/5415e7bfe4b01e2a68fe8243/images/5ab0e897042863478ea7b0cc/file-LmFLCODRoP.png).

Maybe we can also target any specific Asset CleanUp setting, but I'm not sure.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1973225238/360828 - RapidLoad was enabled, and the whole layout broke when WP Rocket's Remove Unused CSS was applied.

**Comment by GeekPress** [comment]
@piotrbak Can we split this issue in two? One for Perfmatter, and another one for Rapidload?

**Comment by jeawhanlee** [comment]
We can use the same logic here https://github.com/wp-media/wp-rocket/issues/5533#issuecomment-1369771735 by creating a Thirdparty class for Rapidload Used CSS and check if plugin is active `defined( 'UUCSS_VERSION' )`.
Then hook to the new filter `rocket_maybe_disable_rucss`
