### ISSUE TITLE
Load CSS Async to generate a separate CPCSS For Author pages

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5425]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Load CSS Async is used, specific CPCSS for the archives pages is not generated. The frontpage CPCSS is added to that type of pages.

That creates a FOUC if the layout is different from the frontpage, which is generally the case.

**To Reproduce**
1. Enable CPCSS and generate it
2. Build an author page different from the front page
3. See error

**Expected behavior**
The Author page is part of the default archive pages. It should have its own CPCSS generated and used for it.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2006553943/367867/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/2066937311/381397/

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
