### ISSUE TITLE
PHP fatal error on activating RUCSS when there aren't Action Scheduler tables in the database

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5426]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.05`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the Action Scheduler (AS) tables are not in the database, activating Remove Unused CSS is causing a PHP fatal error:
http://snippi.com/s/2uqtuy1

Refreshing the settings page after the fatal error works fine and the tables are created when clicking on the respective URL.

**To Reproduce**

1. Drop Action Scheduler tables from the database.
2. Enable Remove Unused CSS.
3. PHP fatal error occurs and it's logged in the `debug.log`.

**Expected behavior**

No PHP fatal error should occur when activating Remove Unused CSS and the AS tables are missing.

**Additional context**

**Slack convo:** https://wp-media.slack.com/archives/GUT7FLHF1/p1663145963473499

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
Closing this in favour of https://github.com/wp-media/wp-rocket/issues/5440
