### ISSUE TITLE
[WIP] Action Scheduler: lots of past-due rocket_preload_job_preload_url actions found

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5431]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
@webtrainingwheels noticed a trend: 
On some sites using **3.12.0.5** the `rocket_preload_job_preload_url` starts piling up. (6k, 70k, 80k entries)
Users are mentioning the entries are being created really fast.

Some cases are using **Rank Math SEO** as a common factor, but I can't confirm it is related

`Action Scheduler: 70197 past-due actions found; something may be wrong. Read documentation »" In clicking through, there are indeed many many "Rocket Preload" actions in Pending in Scheduled actions.
`
In one case where we have access, the only `action_scheduler_queue_runner_concurrent_batches` is ours, and set to 1
there are under 5k posts, but over 60k `rocket_preload_job_preload_url`

**Additional context**
Related tickets: 
https://secure.helpscout.net/conversation/2009676957/368580/
https://secure.helpscout.net/conversation/2009655193/368571/
https://secure.helpscout.net/conversation/2006498141/367846
https://secure.helpscout.net/conversation/2009599555/368564
https://secure.helpscout.net/conversation/2009599415/368563

Slack convo:
https://wp-media.slack.com/archives/C43T1AYMQ/p1663195462029489

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
The warning is related to this Action Scheduler change on Action Scheduler `3.5.0`.
https://github.com/woocommerce/action-scheduler/releases

![image](https://user-images.githubusercontent.com/1289174/190315036-bc4e1904-e6ab-441e-9ec6-3e08ed633481.png)

Other plugins relying on Action Scheduler are getting similar warnings as well - https://wordpress.org/support/topic/action-scheduler-4-past-due-actions-found-something-may-be-wrong/

Jobs are past-due when there is a CRON issue - https://actionscheduler.org/faq/#my-site-has-past-due-actions-what-can-i-do

> My site has past-due actions; what can I do?
> Actions that are past-due have missed their scheduled date; because of how WP Cron works, it is normal to have some past-due actions.
> If there are several past-due actions more than one day old, there may be something wrong with your site.

We need to confirm by logging the CRON on these cases and go from there.

**Comment by worldwildweb** [comment]
probably related: https://secure.helpscout.net/conversation/2006999241/367997/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2007775038/368118/

**Comment by iuzairjan** [comment]
<img width="1272" alt="Screenshot at Sep 15 22-22-02" src="https://user-images.githubusercontent.com/25842257/190462533-cdeb4103-e9e3-48df-9c91-764e11832066.png">
The same is happening with me I have 40k Post

<img width="1437" alt="Screenshot at Sep 15 22-14-42" src="https://user-images.githubusercontent.com/25842257/190461548-e0605b5f-8ec9-4a01-8faf-f5528d2de2fc.png">

**Comment by making8** [comment]
I'm using Rankmath without WP Rocket active and seeing the issue. It's definitely way worse when WP Rocket is on though.

**Comment by RudyRodriuez** [comment]
A headache, we have already deactivated the "preload" now the box is like this. We hope that the next update will be fixed without problems.

![1](https://user-images.githubusercontent.com/38331144/190629339-51a6a084-f75e-40f2-adf8-32f1cd7921e6.png)

**Comment by DahmaniAdame** [comment]
Past-due jobs are expected to happen. And there seem to be two main reasons: 

- The consistency of the CRON jobs. Having a server-side CRON helps. 
- Frequent `deadlocks` on the database ([reference](https://github.com/woocommerce/action-scheduler/issues/530#issuecomment-904674211)). This one seems to be a mix of [Race conditions affecting ActionScheduler_QueueRunner::maybe_dispatch_async_request() #793](https://github.com/woocommerce/action-scheduler/issues/793) and the database performance.

In WP Rocket's case, the more actions added to the AS, the higher deadlocks happen (#5375, #4042), and the higher past-due warnings will show up to reach up to all pending actions count.

It will look alarming when seeing the number of past-due actions, especially on large websites. 

All past-due actions will be ultimately re-processed. 

I believe finding a way to fix https://github.com/woocommerce/action-scheduler/issues/793 should help.

As a side note, there is a filter to disable the Past Due tab: 

```
add_filter( 'action_scheduler_pastdue_actions_check_pre', '__return_false' );
```

This is not a fix. It's more like reverting back to how things were before `3.5.0`.

**Comment by Michaelgimii** [comment]
+1
This error is constantly displayed in the counter.

![wp](https://user-images.githubusercontent.com/88034902/190980461-7239c307-ad99-49a5-85bd-9dbe87242105.png)

It doesn't disappear no matter what I try. Is there a solution for that?

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/2011973090/369100/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2007118146/368019/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2010617770/368798/

**Comment by alfonso100** [comment]
related: https://secure.helpscout.net/conversation/2000637515/366629/

**Comment by vmanthos** [comment]
related: https://secure.helpscout.net/conversation/2012366332/369180

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/2012869136/369297

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/2013379749/369429/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2014444588/369651/

**Comment by joejoe04** [comment]
Possibly related: https://secure.helpscout.net/conversation/2015667303/369947/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2016931710/370309

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2018336284/370597

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/2018036796/370549/
