### ISSUE TITLE
Compatibility with JetEngine custom posts

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5432]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When custom post types are added using the JetEngine plugin, purging one of the posts will include multiple root URLs from other post types to our `$purge_urls`. 

https://github.com/wp-media/wp-rocket/blob/c53d551c38788c3ac1e171cf60b52af4c777c204/inc/common/purge.php#L217

This purges all custom posts cache even if an unrelated post is purged. 

The following entries are found there: 

- https://domain.ext/custom-post-a/something/
- https://domain.ext/custom-post-a/index-https.html
- https://domain.ext/custom-post-a/index-https.html_gzip
- https://domain.ext/custom-post-a/
- https://domain.ext/custom-post-b/
- https://domain.ext/custom-post-c/

Not sure why the extra URL to purge are added, but ideally, and assuming the root URL for the other folders should be purged for some reason, we should limit the purge to the additional folders' contents and not go for purging the folder in full. 

- https://domain.ext/custom-post-a/something/
- https://domain.ext/custom-post-a/index-https.html
- https://domain.ext/custom-post-a/index-https.html_gzip
- https://domain.ext/custom-post-b/index-https.html
- https://domain.ext/custom-post-b/index-https.html_gzip
- https://domain.ext/custom-post-c/index-https.html
- https://domain.ext/custom-post-c/index-https.html_gzip

**To Reproduce**
1. Use JetEngine post types
2. Add multiple post types
3. Purge one post of any of the post types

**Expected behavior**
We need to digging first about why the additional post types are added to the purge, and then decide what would be the expected behavior. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1998585419/365985/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
