### ISSUE TITLE
Remove the cache directory size check feature

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5438]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

We should consider removing the cache directory size check feature since:
* We haven't been using this feature for a long time. 
* With the use of Delay JavaScript Execution, which disables Combine JavaScript files, we rarely have cache directory size issues reported.

**Additional context**

The feature was added a long time ago to check weekly the size of the `/cache/min/` directory:
https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/HealthCheck/CacheDirSizeCheck.php

If that was over 10GB we would get a notification so we could investigate it and proactively add exclusions for the Combine JavaScript files feature.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
+1
