### ISSUE TITLE
Improve detection of missing AS tables

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5440]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In the current approach we have a bug related to the not expected characters in the database name. Our query here is not using `` causing fail of the check and displaying false message:
https://github.com/wp-media/wp-rocket/blob/ba69c9365ac25fe9eb3c09d6910799bdfa13e225/inc/Engine/Preload/Activation/Activation.php#L117

**Expected behavior**
We should check the existence of the tables only in the specific conditions:
1. When activating the plugin, before Preload do any operation on the tables
2. When enabling RUCSS
3. When enabling Preload
4. During each update of the plugin

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This will resolve the following issue:
https://github.com/wp-media/wp-rocket/issues/5426

**Comment by remyperona** [comment]
Are we removing the existing notice?

**Comment by piotrbak** [comment]
Yes, the notice won't be needed anymore.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
I propose creating a new class and subscriber in https://github.com/wp-media/wp-rocket/tree/develop/inc/Engine/Admin
```
use ActionScheduler_StoreSchema;
use ActionScheduler_LoggerSchema;

public function maybe_recreate_as_tables() {
	if ( is_valid_as_tables() ) {
           return;
        }

	$store_schema  = new ActionScheduler_StoreSchema();
	$logger_schema = new ActionScheduler_LoggerSchema();
	$store_schema->register_tables( true );
	$logger_schema->register_tables( true );
}

private function is_valid_as_tables() {
        $cached_count = get_transient( 'rocket_rucss_as_tables_count' );
	if ( false !== $cached_count && ! is_admin() ) { // Stop caching in admin UI.
		return 4 === (int) $cached_count;
	}

	global $wpdb;

	$exp = "'^" . $wpdb->prefix . "actionscheduler_(logs|actions|groups|claims)$'";
	// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
	$found_as_tables = $wpdb->get_col(
		// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
		$wpdb->prepare( 'SHOW TABLES FROM `' . DB_NAME . '` WHERE `Tables_in_' . DB_NAME . '` LIKE %s AND `Tables_in_' . DB_NAME . '` REGEXP ' . $exp, '%actionscheduler%' )
	);

	set_transient( 'rocket_rucss_as_tables_count', count( $found_as_tables ), rocket_get_constant( 'DAY_IN_SECONDS', 24 * 60 * 60 ) );

	return 4 === count( $found_as_tables );
}
```
### When activating the plugin, before Preload do any operation on the tables
In the new subscriber hook a new method to `rocket_activation` that calls `maybe_recreate_as_tables()`
- remove https://github.com/wp-media/wp-rocket/blob/3584bcca26fdee58f81269708218b48dfc9ddad8/inc/Engine/Preload/Activation/Activation.php#L9-L10 and  https://github.com/wp-media/wp-rocket/blob/3584bcca26fdee58f81269708218b48dfc9ddad8/inc/Engine/Preload/Activation/Activation.php#L110-L121

### When enabling RUCSS
in new subscriber hook a new method to 
`$slug = rocket_get_constant( 'WP_ROCKET_SLUG', 'wp_rocket_settings' );`
`'update_option_' . $slug` and check if RUCSS is enabled then call `maybe_recreate_as_tables()`

### When enabling Preload
in new subscriber hook a new method to 
`$slug = rocket_get_constant( 'WP_ROCKET_SLUG', 'wp_rocket_settings' );`
`'update_option_' . $slug` and check if preload is enabled then call `maybe_recreate_as_tables()`

### During each update of the plugin
in new subscriber hook a new method to `wp_rocket_upgrade` that calls `maybe_recreate_as_tables()`

- Remove https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Admin/Notices.php and https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Admin/NoticesSubscriber.php as we don't want to display the notice anymore.
- Update https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Admin/ServiceProvider.php and https://github.com/wp-media/wp-rocket/blob/develop/inc/Plugin.php
- Remove this orphan method here also, something I skipped again. https://github.com/wp-media/wp-rocket/blob/3584bcca26fdee58f81269708218b48dfc9ddad8/inc/Engine/Optimization/RUCSS/Admin/Settings.php#L306-L323
- Remove related tests
- Add new tests

### Estimate the effort ✅
[S]

Can you validate this grooming @Tabrisrp 🙏

**Comment by remyperona** [comment]
that sounds good to me 👍🏼

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/2013558411/369507/

**Comment by worldwildweb** [comment]
related: https://secure.helpscout.net/conversation/2016408467/370146

**Comment by vmanthos** [comment]
related: https://secure.helpscout.net/conversation/2017851035/370501?folderId=2135277
