### ISSUE TITLE
Allow to stop a preload in process

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5442]
**Is your feature request related to a problem? Please describe.**
It'd be good if we can allow to stop the preload process.
It was an old request from customers and we just got a new question about this.

**Describe the solution you'd like**
Add a button to stop an ongoing preload, without clearing the cache. 
Just pausing the process and allowing to resume it.

**Additional context**
https://secure.helpscout.net/conversation/2006483621/367843?folderId=273766

**Comment by piotrbak** [comment]
As discussed, this is not currently planned. We'll improve the deactivation process instead.
