### ISSUE TITLE
RUCSS compatibility with Popups for Divi

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5443]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When RUCSS is used with [Popups for Divi](https://wordpress.org/plugins/popups-for-divi/), the inner popup style is missing.

The style is not prefixed and uses common Divi tags.
​​
​​I had to preserve the following inline styles in order to maintain the popup style: 
​
​By attribute: 
​
`​et-builder-module-design-tb-###-###-cached-inline-styles`
`et-divi-customizer-global-cached-inline-styles`

This is likely due to how the Popups for Divi works.​
​
​By selector (two <style> tags related to Mailerlite): 

`​.ml-form`

​This one shouldn't be an issue under normal circumstances. It's behaving the same way as the popup because the code was added inside it.

I will leave this one to the QA team to check.

**To Reproduce**
1. Use Divi + Popups for Divi + Mailerlite (preferably)
2. Add a popup
3. Use RUCSS

**Expected behavior**
The popup should work properly when RUCSS is used.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2007788273/368121/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue (1). We might reopen this in the future.
