### ISSUE TITLE
action_scheduler_run_queue_rucss is late to run

### ISSUE THREAD

**Issue by kulterryan** [wp-media/wp-rocket#5444]
**Describe the bug**
After updating to v3.12.1, the error appears in the site health.

**Expected behavior**
Resolves after clearing Unused CSS but appears right after 5 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/36154235/190866983-fddddb87-e7c1-472a-9110-2eba4de5c958.png)

**Additional context**
Rolling back to v3.12.0.5 resolves the issue.

**Comment by Michaelgimii** [comment]
+1
Please fix this issue. This error is constantly displayed in the counter.

![wp](https://user-images.githubusercontent.com/88034902/190980461-7239c307-ad99-49a5-85bd-9dbe87242105.png)

It doesn't disappear no matter what I try. Is there a solution for that?

**Comment by piotrbak** [comment]
@kulterryan The warning is related to this Action Scheduler change on Action Scheduler, you can read more and follow the thread in this issue:
https://github.com/wp-media/wp-rocket/issues/5431

@Michaelgimii It's only an UI problem that doesn't affect the functionality. It usually happen when database name contains `.` or special character. You can check the details here:
https://github.com/wp-media/wp-rocket/issues/5440

The workaround would be to change the line mentioned in the GitHub issue to:
https://snippi.com/s/owgwz8s

I'd suggest waiting for 3.12.1.1 though.

**Comment by Michaelgimii** [comment]
hi @5431 , Thanks for the great information. So will the error display problem in the counter be solved in the next version?

**Comment by Michaelgimii** [comment]
hi @piotrbak  , Thanks for the great information. So will the error display problem in the counter be solved in the next version?
