### ISSUE TITLE
URLs excluded from caching are still using the Action Scheduler 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5445]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When a URL is excluded from caching, e.g. it has been added to the **Never Cache URL(s)** (Advanced Rules tab) it will not be cached but still be processed by the Action Scheduler, and an entry will be added to the `wp_actionscheduler_actions` table.

That URL will have the `in-progress` status and we'll be reprocessed when `rocket_revert_old_in_progress_rows` runs.

**To Reproduce**

1. Add a URL that's already in the `wpr_rocket_cache` table to the **Never Cache URL(s)** text area.
2. Let the preload process be completed.
3. Check the `wp_actionscheduler_actions` table.
4. A `rocket_preload_job_preload_url` entry will have been added there.

**Expected behavior**

Do not process such URLs.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/2011973090/369100?folderId=273766

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/2022334719/371503/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/2027787640/372714?folderId=377611

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/2029385423/373136
