### ISSUE TITLE
Brick builder support

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5448]
**Describe the solution you'd like**

Please add brick builder page builder support to wp rocket.

**Comment by piotrbak** [comment]
Hello @Michaelgimii thanks for creating the issue.

Do you have any specific problems with that builder?

**Comment by Michaelgimii** [comment]
Hi @piotrbak 
No, I just wanted you to keep that in mind.

**Comment by piotrbak** [comment]
@Michaelgimii I checked our support history, we have only one ticket related to Remove Unused CSS feature and we're working on it. Besides that, nothing was reported.

I'm going to close the issue and if we see any problems, we'll create a new one with detailed description. Thank you!
