### ISSUE TITLE
Add .myraidbox.de to our allowed list of staging environments

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#5457]
**1) Is your feature request related to a problem? Please describe.**

Raidboxes provides their customers with an option to setup "demo-boxes" for testing (one per customer, lasts 14 days) using `*.myraidbox.de`.

**2) Describe the solution you'd like**

Add this domain to our list of staging domains, e.g., same as the others on this list:
https://docs.wp-rocket.me/article/109-can-i-run-wp-rocket-on-localhost

**3) Additional context**

https://secure.helpscout.net/conversation/2011636475/369041/

**Comment by Mingendahl** [comment]
It's 14 days for the minimum setup (1 core) and 4 days for all others.
After this period of time, the machines get deleted.
