### ISSUE TITLE
Minify JS breaks Podigee podcast player

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5459]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.0.5
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Minification of the `https://player.podigee-cdn.net/podcast-player/javascripts/podigee-podcast-player.js` breaks the podcast iframe.

Excluding `podigee-podcast-player.js` from _Minify JavaScript_ option resolves the issue.

No issues were caused by the Defer JS and Delay JS options on the given site. 

**To Reproduce**
Reproduced on the customer's site.

**Expected behavior**
The podcast iframe should be displayed correctly.

**Additional context**
Related tickets:
https://secure.helpscout.net/conversation/2015676355/369955/
https://secure.helpscout.net/conversation/1752476987/318399

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Excluded `podigee-podcast-player.js` from JS Minification
