### ISSUE TITLE
Critical Css Generation service ignores stylesheets with media attribute

### ISSUE THREAD

**Issue by Kilbourne** [wp-media/wp-rocket#5462]
**Describe the bug**
If a page contains a link tag with a media attribute assigned to a media-query (ex. media="(min-width: 1024px)" ), Critical generation service ignores that stylesheet even if it is applicable to viewport.

**Expected behavior**
The stylesheet should be used if applicable to viewport

**Comment by Kilbourne** [comment]
Hi!
It seems that the code of CPCSS generation service is not opensourced. Could you reveal it you are using a dependency to extract the css? Maybe the issue should be opened on the upstream dep.
This issue is causing a layout shift and so webvitals score goes down.
( Also could be a regression because i didn't notice the issue until recent)

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
