### ISSUE TITLE
JavaScript Execution compatibility with Gravity conditions 

### ISSUE THREAD

**Issue by aronikakume1211** [wp-media/wp-rocket#5465]
Uncaught ReferenceError: gform is not defined
    at conditional_logic.min.js?ver=2.4.21:1:7400

Not disply gravity form automatically , but while user mouse hover or enter to the page , the form visible

**Comment by piotrbak** [comment]
Hello @mebratukumera thanks for creating the issue. Could you specify steps that are needed to reproduce the issue? 

If not, please reach our support and then we'll be happy to investigate the problem.

**Comment by piotrbak** [comment]
Closing it since we haven't heard from you and there are no complains about this problem
