### ISSUE TITLE
Filter to add Delay JS Exec. exceptions on the required page

### ISSUE THREAD

**Issue by pedddro** [wp-media/wp-rocket#5470]
**Is your feature request related to a problem? Please describe.**
Since WP Rocket delays all JS by default with Delay JS and many users on Wordpress use different plugins, pages may have different conflicts, and therefore adding it to the UI expectation would not net the max potential as a filter to add delay js exception by page would offer.

**Describe the solution you'd like**
Filter to add Delay JS Exec. exceptions on the required page.

**Describe alternatives you've considered**
There's no alternative.

**Additional context**
I had a website that had two different JS conflicts on different pages when using Delay JS.

**Comment by mehedihasanziku** [comment]
WP Rocket provides filter to do this, 
Full Guideline: https://docs.wp-rocket.me/article/1645-exclude-js-scripts-from-delay-js-only-at-some-urls

**Comment by piotrbak** [comment]
Hello @pedddro thanks for creating the issue.

As @mehedihasanziku mentioned, we don't provide UI field for this, but it's of course, possible. Thank you @mehedihasanziku for your input here 🙏
