### ISSUE TITLE
PHP Notice:  getimagesize(): Read error! when preload with missing image dimensions in certain cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5477]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.1.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Read error notice exists in logs, when clear and preload while using invalid CDN

**To Reproduce**
Precondition:
- Fresh install for WPR on mega/divi
1. Enable missing image dimensions
2. Enable CDN with CNAME `z3g7b3k3.stackpathcdn.com`
3. Click clear and preload then access home
4. Check debug.log

`[26-Sep-2022 16:52:28 UTC] PHP Notice:  getimagesize(): Read error! in /home/wpquicki/mega/divi/wp-content/plugins/wp-rocket/inc/Engine/Media/ImageDimensions/ImageDimensions.php on line 483`

**Expected behavior**
Guard from invalid CNAME (no Read error)

**Additional information**
- It was working fine on new.rocketlabs env
- Even if we didn't add CNAME at all, the same warning is there on /divi

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Note: even after disabling CDN/ remove CName then clear and preload then access the home page => the same error is added to logs using 3.14.4

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
