### ISSUE TITLE
PHP Fatal error when Template is used in a parent theme

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5481]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the header of a parent theme incorrectly includes a `Template` a PHP Fatal error occurs:
```PHP
PHP Fatal error:  Uncaught TypeError: strtolower() expects parameter 1 to be string, null given in /home/example.com/wp-content/plugins/wp-rocket/inc/ThirdParty/Themes/Flatsome.php:75
Stack trace:
#0 /home/example.com/wp-content/plugins/wp-rocket/inc/ThirdParty/Themes/Flatsome.php(75): strtolower(NULL)
#1 /home/example.com/wp-content/plugins/wp-rocket/inc/ThirdParty/Themes/Flatsome.php(15): WP_Rocket\ThirdParty\Themes\Flatsome::is_flatsome()
#2 /home/example.com/wp-content/plugins/wp-rocket/inc/classes/event-management/class-event-manager.php(38): WP_Rocket\ThirdParty\Themes\Flatsome::get_subscribed_events()
#3 /home/example.com/wp-content/plugins/wp-rocket/inc/Plugin.php(144): WP_Rocket\Event_Management\Event_Manager->add_subscriber(Object(WP_Rocket\ThirdParty\Themes\Flatsome))
#4 /home/example.com/wp-content/plugins/wp in /home/example.com/wp-content/plugins/wp-rocket/inc/ThirdParty/Themes/Flatsome.php on line 75
```
here:
https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/ThirdParty/Themes/Flatsome.php#L72

This is because `$theme->get_template()` returns `NULL`.

**To Reproduce**

1. Add `Template: folder-name-of-the-theme` in the header of the `style.css` of the active theme.
2. Try to activate WP Rocket.
3. Look into the `debug.log` for the fatal error.

**Expected behavior**

No fatal errors should occur even if the `Template` is added to a parent theme.

**Additional context**

We should guard the check for the template and do the same in other theme compatibility files, e.g. Avada, Jevelin, Xstore where we are using the same check.

**Ticket:** https://secure.helpscout.net/conversation/2019395931/370792/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Scope a solution
Like @vmanthos  said we need to convert null to string so we don't generate the TypeError

we can use to convert null to empty string to avoid the problem
` 'flatsome' === strtolower( $theme->get_template() ?? '' )`

we need to update all files that uses `strtolower( $theme->get_template() ?? '' )` Jevelin, Xstore
### Estimate effort:
Effort `xs`
