### ISSUE TITLE
Duplication in preload DB table when sitemap contains query strings

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#5482]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
If the sitemap contains urls with query strings, for example: https://example.org/?post_type=test&id=5 we save this url into the database without query strings to be like https://example.org/ and when we have multiple urls like that, we insert those with the same url so the DB has duplication.

**To Reproduce**
1. Install and activate RankMath SEO plugin.
2. Install and activate Thrive Theme Builder Version: 3.11.1
3. Make sure that those post types are enabled in sitemap
![thrive](https://user-images.githubusercontent.com/15707971/192988410-8723396c-444b-4dc6-84cd-3f04d7358171.jpg)

4. Enable the preload and start preloading from sitemap.
5. Check the cache database table, you will find the duplication there.

**Expected behavior**
We should make the cache table rows unique by urls.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by worldwildweb** [comment]
related: https://secure.helpscout.net/conversation/2014343438/369630

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed we suppose to have a check on the db before adding the URL at this line: https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L188
Maybe there is an issue on the check from the database (maybe another issue from the cache?).

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed I found the issue and it is in our code.
I will publish the grooming and fix the issue as it will be XS one.

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
Reproduced it successfully.

## Identify the root cause
The root cause is due to the fact on [this line ](https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L190) we need to use the variable `$url` to apply previous operations on the url.
## Scope a solution
On [this line ](https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L190) we need to use the variable `$url`.
## Estimate the effort
Effort `XS`

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/2032221344/373721/
There was duplicate URLs added `_wpr_rocket_cache` table at the same time. 
The first one was process while all remaining duplicate entries were marked as `pending`. 
The fix mentioned on the scope worked.
Regarding the fix, shouldn't we replace `$resource['url']` by `$url` on the `logger` as well? 
Line [#L149](https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L149) and [#L212](https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L212) on the same file.

**Comment by engahmeds3ed** [comment]
> Related - https://secure.helpscout.net/conversation/2032221344/373721/ There was duplicate URLs added `_wpr_rocket_cache` table at the same time. The first one was process while all remaining duplicate entries were marked as `pending`. The fix mentioned on the scope worked. Regarding the fix, shouldn't we replace `$resource['url']` by `$url` on the `logger` as well? Line [#L149](https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L149) and [#L212](https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Engine/Preload/Database/Queries/Cache.php#L212) on the same file.

Thanks @DahmaniAdame for your suggestion, but I believe no need to do that because we need to log the full url with query strings.
