### ISSUE TITLE
JavaScript minification breaks Prism.js when that's served from a CDN

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5484]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.12.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When [Prism.js](https://prismjs.com/index.html) is loaded from a CDN and JavaScript minification is enabled, storing the files locally breaks the script and the following console error occurs:
```
GET https://example.com/wp-content/cache/min/1/ajax/libs/prism/1.23.0/components/prism-clike.min.js net::ERR_ABORTED 404
```

Excluding the following fixes the error:
`https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/autoloader/prism-autoloader.min.js`

**To Reproduce**

1. Use the following template:
https://github.com/wp-media/rocket-test-data/blob/master/templates/prism_js.php

**Expected behavior**

No console errors should occur.

**Additional context**

We should add `cdnjs.cloudflare.com/ajax/libs/prism/` here:
https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L162

**Ticket:** https://secure.helpscout.net/conversation/2021162449/371216?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Going to be handled on the backend
