### ISSUE TITLE
Advanced Ads Pro PHP placement positioning prevents optimizations from being applied

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5486]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.12.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

No optimizations are applied when the "Placement positioning" (Advanced Ads > settings > Pro) is set to "Before page load using PHP."

With that option, WP Rocket's buffer is cleared while caching is working properly.

Switching the "Placement positioning" to "After page load using JavaScript" fixes the issue:
![](https://i.vgy.me/nHHAx4.jpg)
Full-Scale image > https://i.vgy.me/nHHAx4.jpg

**To Reproduce**

1. Install the [plugin](https://secure.helpscout.net/conversation/2017840919/370495/#thread-6011229175) 
2. Select "Before page load using PHP." in `Advanced Ads > settings > Pro > Placement positioning`.
3. Clear the cache and visit a page.
4. WP Rocket's optimizations, e.g. minification won't be applied there.

**Expected behavior**

We should display a warning when the specific option is used. 

**Additional context**

There is a copy of the plugin here:
https://secure.helpscout.net/conversation/2017840919/370495/#thread-6011229175

**Ticket:** https://secure.helpscout.net/conversation/2017840919/370495/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webzunft** [comment]
Thomas from Advanced Ads here. We are happy users of WP Rocket. Since so many WP Rocket users choose Advanced Ads Pro, I wanted to mention that we are happy to assist you. If your devs found the reason for the conflict, we would prefer a solution instead of a warning. I could imagine this being related to output buffering.

**Comment by piotrbak** [comment]
Hello @webzunft thanks for being in touch with us! Could you send me the license for your plugin to piotr[at]wp-media.me? We'll try to check what's going on and will let you know.

**>I could imagine this being related to output buffering.**
Yes, I'm pretty sure it's about that, indeed.

**Comment by CrochetFeve0251** [comment]
Trying to check the bug I don't see anything going wrong on my local. Minification is applied to both CSS and JS and other optimizations seems to work.

**Comment by vmanthos** [comment]
I tried to reproduce this as well but I couldn't. ¯\_(ツ)_/¯

Closing this. We'll re-open it if anything comes up in the future.
