### ISSUE TITLE
Duplicate queries detected in WP Rocket

### ISSUE THREAD

**Issue by kulterryan** [wp-media/wp-rocket#5490]
**Describe the bug**
After updating the plugin to v3.12.1.1, there's an issue with the Duplicate query in the Action Scheduler. 
**To Reproduce**
The issue can be easily detected using Query Monitor.

**Screenshots**
![image](https://user-images.githubusercontent.com/36154235/193408610-bdf9ca9f-4b91-4e96-997d-82a8fe01044f.png)

**Comment by piotrbak** [comment]
Hello @kulterryan thanks for creating the issue.

@wp-media/php What do you think about that? We're checking for AS tables only when:
1. Activating the plugin
2. Updating the plugin
3. Enabling features that are related to AS
Right? 🤔

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
