### ISSUE TITLE
Refactor Delay JavaScript feature

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5493]
In 3.13 version of the plugin we'll update the way how Delay JavaScript feature is displayed in the dashboard and how the exclusions are being handled.

We'll use backend to provide 3rd-party exclusions.

All the details are described and discussed here:
https://docs.google.com/document/d/1UbYybn-SaRjhqPz2qwZpwJlOglfUTAuRHlLNQcCGkAM/edit?usp=sharing

**Comment by engahmeds3ed** [comment]
# Admin part
  - We will have a CRON job that runs weekly to get the latest changes from the API: https://staging-sass-backend.wp-rocket.me/api/delay-js-exclusions/list
  
  - We will save the data into the json file and also cache it for one week in transient (What do u think if we only get the items related to this site so here we can only get the active theme and active plugins?).

* For the settings page, We need to show all items from the cache or from the json file with the following structure (if we didn't filter in the previous point we need to filter here):
- Plugins
  - plugin_1
    - first title
    - second title
  - plugin_2
    - third title
- Theme
  - Theme Name
    - First title
    - Second title
- Scripts
  - First title
  - Second title
  
* This means that we have plugin_1 and plugin_2 plugins activated also `Theme Name` is the active theme.
  
* we will save the selected items to be excluded from delay JS

* We will have another hidden field to save the exclusions for those selected items or at least cache it in transient so it can be easily called in frontent part while generating the cache file

* When we have some changes in the API for the exclusions we will need to regenerate the exclusions that are mentioned in the previous point based on the selected items and the data from the API, for example:
    If u have plugin_1 that has an item that is selected which has three exclusions, the next time we get the list from the API we got that it has only one exclusion (or four exlusions) so here we will regenerate this list as the saved one is obsolute.

# Frontend Part
  - We will use the filter `rocket_delay_js_exclusions` to add the exclusions from the option/transient mentioned above.

# Devops Part
  - With deployment we will get and save the json file into the plugin's code, so we need to edit the old GitHub workflow here to be more generic and deals with both lists:
  https://github.com/wp-media/wp-rocket/blob/d5504dbe87397f15711a30761ece630f97af8920/.github/workflows/deploy_dynamic_lists_fallback.yml#L1
  - Create a dedicated json file for this delay JS exclusion list.
  - I hope we can make a dedicated directory for those json files to be more organized

**Comment by piotrbak** [comment]
@engahmeds3ed 
```
What do u think if we only get the items related to this site so here we can only get the active theme and active plugins?
```
I believe that this scenario might fail when there's no connection to our servers, we won't be able to create a website-specific fallback file in plugin's archive.

**Comment by engahmeds3ed** [comment]
> I believe that this scenario might fail when there's no connection to our servers, we won't be able to create a website-specific fallback file in plugin's archive.

No, as we always will fallback to the json file which is added with deployment so at first start we will have the full list but then we will only get ours.
Anyway, it was just an idea but in the following point we can do that, then cache them.

**Comment by piotrbak** [comment]
Let's brainstorm this, to find the best solution. @Tabrisrp what do you think? This is the case I mentioned during the standup.

**Comment by remyperona** [comment]
in my opinion it's better to get all the data all the time, it's not going to get so big that the data is unusuable, and that way we are safer whenever there is a change

**Comment by engahmeds3ed** [comment]
Ok, agreed, doing the grooming now and creating sub-tasks.

**Comment by engahmeds3ed** [comment]
# Sub-Tasks

#5525
#5529
#5530
