### ISSUE TITLE
Don't serve cache for specific users

### ISSUE THREAD

**Issue by LarsKerff** [wp-media/wp-rocket#5495]
I want to be able to bypass the cache to be served for specific users. 
We have paid content on our website which we would like to be crawled by Google. This content is only visible for a google bot (or logged in user). I've tried the following, inspired by https://github.com/wp-media/wp-rocket-helpers/blob/master/cache/wp-rocket-no-cache-for-admins/wp-rocket-no-cache-for-admins.php

```
/**
 * Prevent caching if it's a google bot.
 * @return false|void
 */
function bypass_cache_for_google_bot() {

    if (! is_google_bot()) {
        return false;
    }

    add_action( 'template_redirect', 'disable_cache', 1 );
}

add_action( 'init', 'bypass_cache_for_google_bot' );

/**
 * Disable cache
 * @return bool
 */
function disable_cache() {

    if ( ! defined( 'DONOTCACHEPAGE' ) ) {
        define( 'DONOTCACHEPAGE', true );
    }

    if ( ! defined( 'DONOTROCKETOPTIMIZE' ) ) {
        define( 'DONOTROCKETOPTIMIZE', true );
    }

    return true;
}
```

The constant DONOTCACHEPAGE  is working and won't cache the page. However, as soon as there is cache made (e.g. by a user), the cache will be served before it will reach the init action. Is there a hook that will be triggered before cache is served? 

**Describe the solution you'd like**
A hook /filter before cache is served if possible. Eg: `add_filter( 'do_rocket_query_caching_files', .... );`

**Comment by piotrbak** [comment]
Hello @LarsKerff and thank you for creating the issue. I'm not sure if I understand the problem correctly, wouldn't adding Google Bot's user agent here resolve your problem?
https://docs.wp-rocket.me/article/1389-never-cache-user-agents

**Comment by LarsKerff** [comment]
Hi @piotrbak, thanks for your response. Yeah that's kinda what I want but than for specific pages. Is this possible?
However, this could work as well. Thanks

**Comment by piotrbak** [comment]
@LarsKerff You can use this filter in combination with specific conditionals, it should be possible:
https://github.com/wp-media/wp-rocket/blob/62de7d8ccab5dd3257bfcd4479581b0c233d4ad6/inc/functions/options.php#L357
