### ISSUE TITLE
facade image for DIVI

### ISSUE THREAD

**Issue by jits04** [wp-media/wp-rocket#5500]
Lazyload -> Enable for iframes and videos
-> Replace youtube iframe and videos

If I use code module to insert the iframe, can it works with my THEME? I can not enable it to test. Can I update wordpress database directly just to test?

<iframe width="1268" height="713" src="https://www.youtube.com/embed/myvideo" title="mytitle" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by piotrbak** [comment]
Hello @jits04, yes, it can work like this.

If you have any problems with that feature, please check our documentation article:
https://docs.wp-rocket.me/article/1488-replace-youtube-iframe-with-preview-image

If you still have any concerns, you can always reach our support.
