### ISSUE TITLE
More info French broken links

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5502]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.1.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Clicking more info link for Combine JS exclusion or Delay JS for fr profile displays nothing in the beacon

**To Reproduce**
1. Use Francais language on admin
2. Enable Minify JS and click more info for Combine JS exclusion
3. Click more info for Delay JS exclusion

**Expected behavior**
Relative doc displayed 
- As per the [slack discussion](https://wp-media.slack.com/archives/C02QL83AYUT/p1665576566188149)
For Minify JS file exclusions fr doc https://fr.docs.wp-rocket.me/article/243-exclure-js-externe-minification
For Combine JS inline exclusions fr doc https://fr.docs.wp-rocket.me/article/1109-exclure-les-js-inline-de-la-combinaison
For Delay JS fr https://fr.docs.wp-rocket.me/article/1626-reporter-l-execution-du-javascript 

**Screenshots**
![Screenshot from 2022-10-12 09-06-10](https://user-images.githubusercontent.com/76941962/195375905-2d176deb-b92b-4ecf-9f48-a07d4a2ee82e.png)

![Screenshot from 2022-10-12 09-06-05](https://user-images.githubusercontent.com/76941962/195375928-6d02bcf2-394a-4d79-b041-1b1f9031b15f.png)

![Screenshot from 2022-10-12 16-58-12](https://user-images.githubusercontent.com/76941962/195389916-2c4d9992-13f8-4105-be26-0e114cbb3177.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
We also need docs IDs for each article

**Comment by GeekPress** [comment]
@WordPresseur Can you please share the right IDs?

**Comment by WordPresseur** [comment]
- For Minify JS file exclusions fr doc https://fr.docs.wp-rocket.me/article/243-exclure-js-externe-minification : ID = [56967eebc69791436155e649](https://secure.helpscout.net/docs/568e92e39033603f7da2e88a/article/56967eebc69791436155e649)
- For Combine JS inline exclusions fr doc https://fr.docs.wp-rocket.me/article/1109-exclure-les-js-inline-de-la-combinaison : ID = [5b4dd9290428631d7a89023c](https://secure.helpscout.net/docs/568e92e39033603f7da2e88a/article/5b4dd9290428631d7a89023c)
- For Delay JS fr https://fr.docs.wp-rocket.me/article/1626-reporter-l-execution-du-javascript : ID = [60e5b05605ff892e6bc2e86c](https://secure.helpscout.net/docs/568e92e39033603f7da2e88a/article/60e5b05605ff892e6bc2e86c)
