### ISSUE TITLE
Delay JavaScript Execution compatibility with Ivory Search

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5507]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [Ivory Search](https://wordpress.org/plugins/add-search-to-menu/) (90k installs on the official repo) is used with Delay JavaScript Execution + jQuery is excluded, the search box won't popup. 

No console error is showing. 

Remove the jQuery library from exclusions fixes the issue. 

Excluding the following fixes the issue as well: 
```
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/add-search-to-menu/public/js/ivory-search.min.js
```

Reproduced on a fresh install.

**To Reproduce**
1. Install Ivory Search
2. Enable Menu Search under `Ivory Search > Menu Search > Tick active menus`
3. Add the jQuery as exclusion on Delay JavaScript Execution 

**Expected behavior**
The search box should show up out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2031558676/373612/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
