### ISSUE TITLE
Compatibility with WP Discourse cache purging

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5508]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.1.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Discourse is bridging a popular discussion platform to WordPress. 

Their interaction allows reflecting the comments on the platform with their specific WordPress counterpart. 

When a comment is added, WP Rocket's cache is not purged. 

They recently added an action `wpdc_after_webhook_post_update` that fires when comments are updated and passes an array of updated posts `$post_ids`.

https://github.com/discourse/wp-discourse/blob/c49b5098ce9e32543774b1662538b85953faf1f8/lib/sync-discourse-topic.php#L107

We can add a compatibility file to help clear the cache of any post with updated comments.

Something like the following should work. 

```
if( function_exists( 'rocket_clean_post' ) ){
	add_action( 'wpdc_after_webhook_post_update', 'bulk_rocket_clean_post');
}

function bulk_rocket_clean_post(array $ids){
    foreach ($ids as $id) {
        rocket_clean_post($id);
    }
}
```

The plugin has only 1k installs on the official repo, but the [Discourse](https://github.com/discourse/discourse) platform is quite popular. 

Adding for tracking.

**To Reproduce**
N/A

**Expected behavior**
When a post/page updates comments, we should clear its cache.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2026241576/372417/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
