### ISSUE TITLE
Compatibility with the ThemeREX Add-on plugin

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5514]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.1.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the feature `Move styles to the head` under `General settings` is enabled, it produces an output buffer issue that leads to be page turning blank or cut off most parts of its code. 

**To Reproduce**
1. Use ThemeREX Add-on
2. Enable `Move styles to the head` under `General settings`
3. See error

**Expected behavior**
There shouldn't be any output buffer conflicts when the feature is enabled.

There is a filter `trx_addons_filter_options` can control options and that might be used to disable the feature when WP Rocket is use: 

https://gist.github.com/DahmaniAdame/4f981521179c5fed3553c42cc76539e6

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2033333575/373948/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
