### ISSUE TITLE
Perfmatters' Local Google Fonts are preloaded when RUCSS is enabled

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5520]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (3.12.1.1)
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Perfmatters is set to host the Google font files locally, and the fonts are there in the server, but fonts are served from `fonts.gstatic.com` on the cached version of the page when having RUCSS enabled.

**To Reproduce**
1. Set Perfmatters to host the Google font files locally
2. Enable RUCSS
3. Open the developer console and you'll see the fonts are loaded from `fonts.gstatic.com`

**Expected behavior**
Perfmatters' Local Google Fonts should NOT be loaded from `fonts.gstatic.com` when RUCSS is enabled.

**Screenshots**
![Image 2022-10-21 at 11 09 34 AM](https://user-images.githubusercontent.com/26235782/197159567-24d6a982-da35-462b-961b-fa10ed236a47.jpg)

![image](https://user-images.githubusercontent.com/26235782/197161078-de055a9b-4ce9-47c1-9546-95aedbaf10ff.png)

![image](https://user-images.githubusercontent.com/26235782/197161145-bdb1273a-b993-4573-b4f6-15d3b2c970f7.png)

**Additional context**
HS ticket: https://secure.helpscout.net/conversation/2041673845/0/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1666279940338069

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Scope a solution ✅
We can disable RUCSS fonts preload when the local google fonts option 
`$perfmatters_options['fonts']['local_google_fonts']`is enabled in perfmatters
using `rocket_enable_rucss_fonts_preload`

it is going to depend on this [PR](https://github.com/wp-media/wp-rocket/pull/5669) as [perfmatters third-party class](https://github.com/wp-media/wp-rocket/blob/54e2108b26f58e0be62cf323de4d938491745e56/inc/ThirdParty/Plugins/Optimization/Perfmatters.php) is created there

we can fix this in the old PR 
@jeawhanlee @engahmeds3ed what do you think?

### Estimate the effort ✅
[xs]

**Comment by jeawhanlee** [comment]
@mostafa-hisham I talked with @piotrbak and we can create a new branch off the perfmatters [PR](https://github.com/wp-media/wp-rocket/pull/5669) branch and open a new PR that will merge into it.

**Comment by vmanthos** [comment]
@viobru We weren't able to reproduce this. 

I'll close the issue and PR #5686. If anything comes up in the future we can re-open both.
