### ISSUE TITLE
Avoid injecting Delay JavaScript Execution on the wrong <head> tag

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5523]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.1.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The Delay JavaScript Execution script is injected on any tag starting with `<head`. Which will cause issues in some cases.

The problem is the regex `'/<head[^>]*>/i'` used here: 

https://github.com/wp-media/wp-rocket/blob/5ad8bf6c429e3ca8d527d8fa0dfa5e78121b8aa3/inc/Engine/Optimization/DelayJS/Subscriber.php#L104

It will match anything starting with `<head`. Example, `<header>.` 

If the `<head>` is missing from the page, we will inject the tag on the wrong location. 

This may or might not create issues depending on if any <script> is used before the `<header>` tag. But in most cases, it will. 

The `<header>` tag is usually added to the `<body>` and we are likely to find `<script>` tag before it. 

Changing the regex to `'/<head+(?!er)[^>]*>/i'`

The improvement is meant to avoid issues by not adding Delay JavaScript Execution at all if the `<head>` is missing rather than risking breaking the website.

**To Reproduce**
1. Add `<header>` before `<head>`
2. Enable Delay JavaScript Execution 
3. See error

**Expected behavior**
We should only inject the Delay JavaScript Execution script if the `<head>` tag is present. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2041404362/375629?folderId=2952229

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
