### ISSUE TITLE
Allow serving webp for all browsers

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5524]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Seems like some browsers are not including the `webp` in HTTP_ACCEPT header. It can cause our preload not being 100% effective. Part of the solution is having control over the HTTP_ACCEPT in the preload request headers:
https://github.com/wp-media/wp-rocket/pull/5521

The second part is to serve webp version of the cache for all browsers, possibly, this enhancement should be available as a filter (if that's possible)

### Expected behavior version 1
**Creating the cache when the filter is enabled**
1. All browsers, no matter if they send HTTP_ACCEPT with `webp` or not should create the `webp` version of the cache in the `-webp` file
2. If there's no `webp` image on the page, we should create the normal cache file and a `nowebp` file, just like on the trunk:
https://github.com/wp-media/wp-rocket/blob/ae07a02932a32df08918f3ff5c89b44d5195d03d/inc/classes/Buffer/class-cache.php#L486

**Serving the cache when the filter is enabled**
1. If there's a `-webp` cache file present in the filesystem, it should be served for all browsers
2. If there's a `nowebp` file present, we should serve the normal cache for all browsers

### Expected behavior version 2
**Creating the cache when the filter is enabled**
1. All browsers, no matter if they send HTTP_ACCEPT with `webp` or not should the cache file with webp images. **We'd use just a normal name for this file, without appending the `-webp`**
2. If there's no webp image on the page, we'll also create just a regular cache file

**Serving the cache when the filter is enabled**
1. We'll always serve the regular cache file for all browsers, there'll be no use of `nowebp` file

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mingendahl** [comment]
Are both versions aiming at always serving a webp html-file independently whether the browser is capable of rendering webp or not?

This approach would immediately require us to disable the webp-addon immediately.
We must be able to serve the pages according to the browser's capabilities.
We make business with it and cannot afford to serve pages being perceived as broken, even if it is only relevant for 10% of the clients.

We rather server jpg-only than always webp.

Or did I get that wrong?

NGINX is able to detect the browser's capability correctly, also for Safari.
Maybe it might help to 'steal' some good ideas from them ;-)

**Comment by Mingendahl** [comment]
Please check #5654 - I did some research and it is dead-simple (basically one additional line) to detect 98% of the browsers capabilities correctly.

For the others, the non-webp-version can be served

**Comment by Mingendahl** [comment]
Hi @piotrbak ,
which solution has now been implemented?
Will it come with the next release?
Thanks
Markus
