### ISSUE TITLE
Warning: Attempt to read property "action" on null in /inc/functions/admin.php on line 476

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#5526]
After updating to 3.12.2, some customers have reported this warning:

- https://secure.helpscout.net/conversation/2047528856/376938/ 
- https://secure.helpscout.net/conversation/2047894871/377024/
- https://secure.helpscout.net/conversation/2047984346/377064/
- https://secure.helpscout.net/conversation/2048004068/377072/

And another customer reported seeing this _notice_ about the same line of code:

`Notice: Trying to get property 'action' of non-object`

- https://secure.helpscout.net/conversation/2048013912/377077/

**Comment by CrochetFeve0251** [comment]
### Scope a solution
We can add a check to verify if the return of the function `get_current_screen` is null on the [line 476](https://github.com/wp-media/wp-rocket/blob/918577c39f314bffd7ea0b24d672483249be8a64/inc/functions/admin.php#L476).
```php
	if ( function_exists( 'get_current_screen' ) && get_current_screen() && 'add' === get_current_screen()->action ) {

```

### Estimate effort
Effort `XS`

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/2049036666/377334

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2049095817/377356/

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2049097750/377357/
