### ISSUE TITLE
Remove Unused CSS - Detect usage of Perfmatters' Used CSS

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5533]
**Is your feature request related to a problem? Please describe.**
Whenever Perfmatters' Used CSS is used together with our RUCSS, it leads to the problems with layout.

**Describe the solution you'd like**
WP Rocket could detect the usage of Perfmatter's Used CSS and gray out Remove Unused CSS in WP Rocket, showing a notice similar to [the one shown when Autoptimize's minification is detected](https://d33v4339jhl8k0.cloudfront.net/docs/assets/5415e7bfe4b01e2a68fe8243/images/5ab0e897042863478ea7b0cc/file-LmFLCODRoP.png).

**Additional context**
Should be fixed together with: 
https://github.com/wp-media/wp-rocket/issues/5424

Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1663078682187319 - User was using Perfmatter's Remove Unused CSS, causing WP Rocket's Used CSS generation to get stuck on `failed`.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
We can create a new filter for this that will filter RUCSS disabled state. 
`apply_filters( 'rocket_maybe_disable_rucss', 'false', 'warning' )`
Then create a Third party class for Perfmatters that will hook to this new filter and check if perfmatters RUCSS option is active.
`if ( ! empty( get_option('perfmatters_options')['assets']['remove_unused_css'] ) )`
First we need to check if perfmatters plugin is active.
`PERFMATTERS_VERSION`

We can also hook to this same filter for RapidLoad Power-Up for Autoptimize https://github.com/wp-media/wp-rocket/issues/5424

Maybe update tests too...

### Estimate the effort ✅
[S]
