### ISSUE TITLE
WP Rocket doesn't flush Kinsta's caches in a Bedrock install

### ISSUE THREAD

**Issue by ethanclevenger91** [wp-media/wp-rocket#5534]
**Describe the bug**
The integration to flush Kinsta's cache does not work on Bedrock or other Composer-driven WordPress setups

**To Reproduce**
1. Set up a Bedrock install on Kinsta hosting
2. Configure their mu-plugin using the Composer instructions [found here](https://kinsta.com/help/kinsta-mu-plugin/#installing-via-composer)
3. Install WP-Rocket
4. Inspect the `$kinsta_cache` var in the Kinsta hosting subscriber interface [here](https://github.com/wp-media/wp-rocket/blob/v3.12.2.1/inc/ThirdParty/Hostings/Kinsta.php#L16)
5. Note it is null, short-circuiting event subscription

**Expected behavior**
Flushing the WP-Rocket cache flushes the Kinsta cache

**Additional context**
That variable is null because Kinsta doesn't explicitly declare that variable as global in their mu-plugin. It just happens to be available in the global scope in a vanilla WordPress install. I haven't dug into exactly why that is.

Kinsta doesn't seem to offer a cache flush log, so there's no good way to flush the WP Rocket cache and then inspect whether or not the Kinsta cache was actually flushed. So it's possible I'm misinterpreting how this code works.

Oddly enough, the expected admin notice doesn't show up, even though that does get added to the events returned by the subscriber.

You'll probably have to coordinate with the Kinsta team to make this work, since they aren't using a singleton pattern for this class. I've mentioned it to their support but there hasn't been any movement.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
