### ISSUE TITLE
Notify the customer that ProfilePress is preventing page cache

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5541]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.2.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When ProfilePress is enabled, it adds `DONOTCACHEPAGE` to all pages and prevents page cache. 

We must notify customers of such behavior to avoid tickets related to that specific conflict. 

**To Reproduce**
1. Enable ProfilePress

**Expected behavior**
Customers should be notified about the behavior. 

**Screenshots**
N/A

**Additional context**
Tickets: 
- https://secure.helpscout.net/conversation/2048969338/377308/
- https://secure.helpscout.net/conversation/2042517973/375862/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
https://wordpress.org/support/topic/fix-cache-prevent-excluding-issue/
https://wordpress.org/support/topic/profilepress-seems-to-prevent-cached-pages/

They know about this issue, but not sure why not agree to look on it.

**Comment by w3guy** [comment]
Collins from ProfilePress team here.

We only set the DONOTCACHEPAGE constant when viewing login, registration and checkout pages and not on every page.

See https://prnt.sc/FPxq9tbMDayt

If you, however want to disable this completely, you can use the filter below.

``` php
add_filter('ppress_no_cache', '__return_false');
```

**Comment by DahmaniAdame** [comment]
@w3guy thanks for your feedback. 

The `DONOTCACHEPAGE` in the couple of cases we recently had was applied to all pages. 

> login, registration and checkout pages

Our default exclusions cover these. 

Would forcing page cache on pages other than the 3 your mentioned cause any issues?

**Comment by w3guy** [comment]
@DahmaniAdame

>Our default exclusions cover these.

Note that these are our plugin specific login, registration and checkout pages. And not WP/Woo ones hence the need for us to exclude them from cache in our plugin.

> Would forcing page cache on pages other than the 3 your mentioned cause any issues?

The `is_page()` should return false hence causing the DONOTCACHEPAGE not to be set on other pages. Don't believe me, goto ../wp-user-avatar/src/Membership/Controllers/FrontendController.php

Add a var_dump like so `var_dump($page_ids, is_page($page_ids));`

<img width="745" alt="image" src="https://user-images.githubusercontent.com/4140659/199704695-1dcf7cca-6ab1-4fd3-8029-8952ce3aea15.png">

The result is a false returned value when viewing other pages.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/4140659/199704863-be202ab3-ec3d-4688-b388-34ed66f485ef.png">

**Comment by DahmaniAdame** [comment]
The website didn't set any pages. 

Using the filter to disable the page cache worked. 

@w3guy Can you confirm that the only pages that need to be excluded from page cache? 

```
$page_ids = array_filter([
        ppress_settings_by_key("set_login_url", false, true),
        ppress_settings_by_key("set_registration_url", false, true),
        ppress_settings_by_key("checkout_page_id", false, true),
        ppress_settings_by_key("payment_success_page_id", false, true),
        ppress_settings_by_key("edit_user_profile_url", false, true),
    ]);
```

We can selectively exclude them from our page cache while keeping optimizations if that's the case.

Something like the following would work in a compatibility file:

```
if (
    function_exists("ppress_settings_by_key") &&
    is_plugin_active("wp-rocket/wp-rocket.php")
) {
    add_filter("ppress_no_cache", "__return_false");
    $page_ids = array_filter([
        ppress_settings_by_key("set_login_url", false, true),
        ppress_settings_by_key("set_registration_url", false, true),
        ppress_settings_by_key("checkout_page_id", false, true),
        ppress_settings_by_key("payment_success_page_id", false, true),
        ppress_settings_by_key("edit_user_profile_url", false, true),
    ]);
    if (is_page($page_ids)) {
        add_filter("do_rocket_generate_caching_files", "__return_false");
    }
}
```

**Comment by w3guy** [comment]
@DahmaniAdame correct. That’s the only page that shouldn’t be cached.

but I am genuinely curious as to why this is happening. If the user had none of the pages set, the is_page condition would return false and thus, nocache header would be set.

can you explain or help us find out why the is_page condition is returning true?

**Comment by DahmaniAdame** [comment]
@w3guy found the culprit. 

The problem only happens if there are no pages added to ProfilePress. 

The issue is this condition's results on `/wp-user-avatar/src/Membership/Controllers/FrontendController.php`

```
is_page($page_ids);
```

It will return true if the `$page_ids` is empty - [reference](https://developer.wordpress.org/reference/functions/is_page/#notes)

This is the correct test that needs to be performed:

```
$do_not_cache = apply_filters('ppress_no_cache', (! empty($page_ids)) ? true : false);
```

The second issue is the scope of where the exclusion should happen. 

You are basing the exclusion on `$do_not_cache` results. So, if it's true, this exclusion will apply to all pages and not just pages within the `$page_ids` array (which would be the logical thing to do).

You need to check for `$do_not_cache && is_page($page_ids)`.

Here is the full check:

```
$do_not_cache = apply_filters('ppress_no_cache', (!empty($page_ids)) ? true : false);
if ($do_not_cache && is_page($page_ids)) {
    add_filter('nocache_headers', [$this, 'additional_nocache_headers'], 99);
    ppress_maybe_define_constant('DONOTCACHEPAGE', true);
    ppress_maybe_define_constant('DONOTCACHEOBJECT', true);
    ppress_maybe_define_constant('DONOTCACHEDB', true);
    nocache_headers();
    $this->exclude_page_from_wpe_server_cache();
    remove_filter('nocache_headers', [$this, 'additional_nocache_headers'], 99);
}
```

**Comment by w3guy** [comment]
@DahmaniAdame let me investigate and get back to you please.

**Comment by w3guy** [comment]
@DahmaniAdame thank you so much for your help. The next update nextweek will include this fix.

I'll let you know when the update is live so you can close this issue.

**Comment by w3guy** [comment]
@DahmaniAdame the update is now live. https://wordpress.org/plugins/wp-user-avatar/#developers

Many thanks for your help.

**Comment by w3guy** [comment]
@DahmaniAdame shouldn't we close this ticket?

**Comment by DahmaniAdame** [comment]
@w3guy Sorry, I didn't have time to test the latest update. 

Just tested. Working as expected now 👍

@piotrbak fix confirmed on the plugin's end. So, no further action is needed on our side. 

Closing this one.

**Comment by w3guy** [comment]
@DahmaniAdame please you and your team should remove ProfilePress from this page https://docs.wp-rocket.me/article/99-pages-not-cached-or-minify-cssjs-not-working

**Comment by DahmaniAdame** [comment]
@w3guy updated!
