### ISSUE TITLE
Preload - Treat Redirected URLs status as redirected

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#5543]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
I tested preload feature on a complicated website. so far i found an issue.

When a page discovered inside sitemap and it has 301 redirection, this redirection never cleared from in-progress, a never ending preload process here.

**sql queries to check,**
Total **stats:**  
```sql
SELECT status, count(1) FROM `wp_wpr_rocket_cache` group by status 
```
Filter URLs **in-progress :** 
```sql
SELECT * FROM `wp_wpr_rocket_cache` WHERE status = "in-progress" 
```
This part causing issues with preload batch  `45 URLs per minute.` it's filling some quota of 45, let's assume if one website has 20 redirection in-progress everytime, it will be 25 URLs per minute, and preload is slow.

**To Reproduce**
1. create 301 redirection and make sure that page listed inside sitemap and monitor inside database

**Expected behavior**
Expected 301 redirection url will be marked as redirected, and original page will be cached, as it will be discovered inside sitemap again.

**Screenshots**
N/A

**Additional context**
This site using HTTPS, But redirection using for such pages **https > http** ,  I know not good, but still preload should not be busy with such urls.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
