### ISSUE TITLE
Preload - disable preload for pagination pages by default

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5544]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Pagination pages will be added to the `wpr_rocket_cache` table, and since WordPress allows accessing "fake" pagination pages like these: http://mega.wp-rocket.me/cf-7/page/124 it might be problematic on some sites.
 
**To Reproduce**
1. Go to http://mega.wp-rocket.me/cf-7/page/124
2. change the page number several times  `/page/127`, `/page/245, etc`
4. See all these unexistent pages being added to the `wpr_rocket_cache` table

**Expected behavior**
We should exclude these pagination pages from preload by default

**Screenshots**
![vjw36yT-1](https://user-images.githubusercontent.com/229406/199766191-eb2c1452-1db2-4bbc-9972-ef556767f089.png)
Full image here:  https://i.imgur.com/vjw36yT.png

On some sites, this might become quite problematic: 
https://i.imgur.com/veLGv6U.png

**Additional context**
ticket: 
https://secure.helpscout.net/conversation/2029385423/373136?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
After discussing this with @piotrbak we decided to only not add pagination URLs to the `wpr_rocket_cache`
### Scope a solution ✅
We can add this Regex pattern `'/$wp_rewrite->pagination_base/\d+' ` by default in `rocket_preload_exclude_urls` array
it will exclude pagination URLs 

https://github.com/wp-media/wp-rocket/blob/6b45039ddac481a58f5ce4a4f55d5d9815600b2c/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L25-L31

tests also.
### Estimate the effort ✅
[XS]

**Comment by piotrbak** [comment]
@mostafa-hisham It's possible to change the pagination base from `/page/` to something different. We may possibly want to cover this case too, what do you think?
