### ISSUE TITLE
Avoid SecuPress "Trying to access array offset on value of type bool"

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5546]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.2.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Under unknown circumstances, the `$bases` - which stores the result of `secupress_get_rewrite_bases()` - might return a `bool` instead of an `array` and that produces the following alert: 

```
Trying to access array offset on value of type bool
/path/to/wp-rocket/inc/3rd-party/plugins/security/secupress.php, ligne 31
```

https://github.com/wp-media/wp-rocket/blob/eb73496a507310054e342431eacc2860e7e5bc50/inc/3rd-party/plugins/security/secupress.php#L31

We must safeguard that line to only be processed if `$bases` is indeed an `array`. 

**To Reproduce**
N/A

**Expected behavior**
There shouldn't be any errors handling the `secupress_get_rewrite_bases()` results. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2055765192/378935/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by JulioPotier** [comment]
Hello, SecuPress dev here, if you need us to change something, we can. Returning a bool here is not a good idea and we don't need it too. See you!

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
