### ISSUE TITLE
Unnecessary SetEnvIfNoCase in .htaccess?

### ISSUE THREAD

**Issue by dvershinin** [wp-media/wp-rocket#5548]
The `.htaccess` file by WP Rocket has the following parts:

```apache
SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
```

The pattern in the `SetEnvIfNoCase` makes little sense:

* Which, if any, browsers, incorrectly sends things like `X-cept-Encoding` ?
* Why there's a need to "normalize" incoming header `XXXXXXXXXXXXXXX` to `Accept-Encoding` (trying to check it as such)

[Here's a regex test to try makes sense of it...](https://regex101.com/r/mNqgVP/1). Can you please elaborate? Otherwise it seems like unnecessary performance hit to check all incoming headers via regular expressions.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
