### ISSUE TITLE
Empty the wpr_rocket_cache table after a domain migration 

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5549]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a site changes the domain, for example when moving from Staging to Production, the `wpr_rocket_cache` table will carry entries referencing the old domain. Attempting to preload these URLs add extra CPU usage

Deactivating/reactivating the Preload option won't clear these URLs

**To Reproduce**
1. Stagecoach a website with Preload enabled. Doesn't matter if WP Rocket is active or not
2. Disable, Enable the preload, and check the `wpr_rocket_cache` table again. It will contain the old ULRs
3. Start browsing some URLs, these will be added to the cache table
4. See the cache table containing Old and New URLs

**Expected behavior**
After a domain change, the `wpr_rocket_cache` table should be cleared. 

**Screenshots**
![TqA8wnY](https://user-images.githubusercontent.com/229406/200348976-33b5cf9d-63af-43a1-9a48-d65818a64d3e.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The AC:
When clicking on the banner from the [notice](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Admin/DomainChange/Subscriber.php) we should:
1. Purge the cache table, purge the RUCSS table, purge the OCI table
2. Schedule the sitemap/homepage link fetching for the preload (if enabled)
3. Schedule the prewarmup for the OCI (if enabled and it's dependent on the 3.16.1, since the process will be async)

**Comment by remyperona** [comment]
### Scope a solution ✅ 
- Purging the RUCSS & OCI tables are already handled

#### Engine\Preload\Admin\Settings
- Add new dependencies `CacheTable` and `LoadInitialSitemap`
- Add a new method `clear_and_preload()` that will truncate the cache table, and initiate the sitemap/homepage preload if the preload option is enabled

#### Engine\Preload\Admin\Subscriber
- Update the callback on `rocket_domain_options_changed` to the new method `clear_and_preload()`


#### Engine\Preload\Database\Tables\Cache
- Add a method to check if the table exists, and truncate it

#### Engine\Media\AboveTheFold\Warmup\Subscriber
- Add callback `warm_up` on `rocket_domain_options_changed`

### Estimate the effort ✅ 
Effort S
