### ISSUE TITLE
Minify/Combine CSS optimization isnot working on URL containing Media query string

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5551]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.2.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If a page contains CSS file with a media query string, it won't be minified or combined

**To Reproduce**
1. Use style file containing media i.e 
```
<link id='styles-aqua-bg-relative' rel='stylesheet' href="/wp-content/minifycss_style_3.css?test=123&test2=123&media=123">
<link id='styles-absolute-test' rel='stylesheet' href='https://new.rocketlabsqa.ovh/minifycss_style.css?test=123&test2=123&media=123'>
```
2. Enable Minify CSS
3. Access the page with mentioned style
4. Repeat step 3 but after enabling Combine CSS

**Expected behavior**
CSS with a media query string is Minified/ Combined

**Additional context**
- As per discussion with @piotrbak 

> it looks that our:
[https://github.com/wp-media/wp-rocket/blob/eb73496a507310054e342431eacc2860e7e5bc5[…]/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php](https://github.com/wp-media/wp-rocket/blob/eb73496a507310054e342431eacc2860e7e5bc50/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php#L124)
Is excluding it. That's supposed to exclude the files that use media query etc.But we accidentally exclude it because of media query string.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
