### ISSUE TITLE
Exclude /wordpress-miniature-earth/miniature.earth.loader.js from JS Minification and Combine

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5553]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using **[Miniature Earth](https://codecanyon.net/item/miniature-earth-interactive-3d-globe-for-javascript/23390670)** plugin, and JS minification and/or combine is enabled, the script: `/wp-content/plugins/wordpress-miniature-earth/miniature.earth.loader.js`  causes a 404 error when it to inject another javascript file called `miniature.earth.js` because it cannot find it in the same /min folder.

This breaks the plugin functionality

**miniature.earth.loader.js** contents: https://snippi.com/s/5awqm57

**To Reproduce**
1. create an empty plugin folder, and upload both scripts: **miniature.earth.loader.js** with the contents from  https://snippi.com/s/5awqm57 and **miniature.earth.js**, this second script can be empty.
2. enqueue the` /wp-content/plugins/wordpress-miniature-earth/miniature.earth.loader.js` to the theme, 
4. enable JS minification, and/or JS combine
5. see the 404 error related to miniature.earth.js 
6. Excluding `/wordpress-miniature-earth/miniature.earth.loader.js` from minification and combine fixes the error

**Expected behavior**
the 404 error shouldn't happen, we need to exclude /wordpress-miniature-earth/miniature.earth.loader.js` from JS minification and combine

**Additional context**
ticket https://secure.helpscout.net/conversation/2059913415/379831?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@alfonso100 That would be a good candidate for backend exclusion, right? 🤔

**Comment by alfonso100** [comment]
This one cannot be added to the backend, we'd need a new field to exclude JS files from minify/combine
I have opened a GH issue about this https://github.com/wp-media/wp-rocket/issues/6024

for now, the only option would be to do a normal PR as we did in the past
