### ISSUE TITLE
Delay JS - PHP fatal error when the HTML of a page is null

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5555]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.2.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When parsing the HMTL of a page here:
https://github.com/wp-media/wp-rocket/blob/6ca9b29e29d71bd0a783f8b797cb54b18357549f/inc/Engine/Optimization/DelayJS/HTML.php#L135-L150

if `$html` is `null` the following PHP fatal error is logged:

```PHP
PHP Fatal error:  Uncaught TypeError: preg_replace(): Argument #3 ($subject) must be of type array|string, null given in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php:147
Stack trace:
#0 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php(147): preg_replace()
#1 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php(88): WP_Rocket\Engine\Optimization\DelayJS\HTML->parse()
#2 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/Subscriber.php(85): WP_Rocket\Engine\Optimization\DelayJS\HTML->delay_js()
#3 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\DelayJS\Subscriber->delay_js()
#4 /var/www/example.com/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters()
#6 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer()
#7 /var/www/example.com/htdocs/wp-includes/functions.php(5279): ob_end_flush()
#8 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(308): wp_ob_end_flush_all()
#9 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#10 /var/www/example.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /var/www/example.com/htdocs/wp-includes/load.php(1124): do_action()
#12 [internal function]: shutdown_action_hook()
#13 {main}
  thrown in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 147
```
**To Reproduce**

1. Hardcode `$html = null` in the `parse()` method.
2. Enable Delay JavaScript Execution.
3. Check the `debug.log`.

In my case, the issue occurred for `/cart` and `/checkout` because `/cart-2` and `/checkout-2` existed and were set in WooCommerce as the cart and checkout page respectively.

**Expected behavior**

No PHP fatal should occur if `$html` is `null`. We should safeguard our code for this.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/2071323578/382433?folderId=3864740

The error is causing error 500 on customer's site.

**Comment by mostafa-hisham** [comment]
## Scope a solution
we need to safeguard  the HTML variable like @vmanthos  said 
## Estimate the effort
Effort `XS`
