### ISSUE TITLE
Enforce Trailing Slash

### ISSUE THREAD

**Issue by skrlance** [wp-media/wp-rocket#5556]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when your are not allowing us to choose if we like to enforce trailing slash on URLs or not from the plugin options itself.

**Describe the solution you'd like**
Keep an option to enforce trailing slash

**Describe alternatives you've considered**
Currently, I have enforce trailing slash redirect rules setup on my nginx configuration but using another rule for wp-json gives problem on the WordPress.

**Additional context**
Please keep an option for us whether or not to enforce trailing slash on URLs from plugin.

**Comment by piotrbak** [comment]
Hello @skrlance thanks for creating the issue.

In terms of trailing slash, we're working on the solution to respect the trailing slash that's used in WP settings. That's a complicated topic in many different aspects.

Could you tell me what benefits do you see when combining and delaying JS in the same time?

**Comment by skrlance** [comment]
I just want to have control of settings to on myself. I mean let us choose what we like to do! You can suggest but can't force!!

**Comment by vladyslav-storozhenko** [comment]
@piotrbak Hello, are there any news about trailing slash enforcement? As it is something that is giving us a lot of trouble with WP Rocket

**Comment by piotrbak** [comment]
Hello @vladyslav-storozhenko it's planned for 3.13:
https://github.com/wp-media/wp-rocket/pull/5215

**Comment by skrlance** [comment]
Finally trailing slash problem is going to get solved on upcoming version! Thank you WP-Rocket team!!

**Comment by skrlance** [comment]
Also, it was my mistake asking for both combine and delay the entire js because I saw that it will create error on the website and I should have done what wp-rocket allows me to do! Please ignore that topic!!
