### ISSUE TITLE
Cache clearing not working on a per-post basis in conjunction with WPML (non-encoded URL / special chars?)

### ISSUE THREAD

**Issue by E-VANCE** [wp-media/wp-rocket#5561]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We're using WP Rocket in conjunction with WPML and I have noticed a faulty behaviour when it comes to saving a (translated) post – WP Rocket doesn't automatically clear the cache for the corresponding post and the cached file also persists when actively using the `purge_cache`-action from the top bar menu.

Clearing the whole language cache via `purge_cache&type=all&lang=fr` works fine though so there must be 

What I've gathered from looking at the scheduled actions logs is, that the URL passed via arg differ and I suspect the handling of the special chars / the non-encoded URL to be the culprit...

The single calls pass

`/fr/équipes/dr-eberhard-koch`

while the full cache rebuild uses

`/fr/%C3%A9quipes/dr-eberhard-koch`

Thus it could be related to the missing URL encoding...?

Would appreciate if you could take a look here – thanks!

**Additional context**
- WordPress Core @ 6.1
- WPML @ 4.5.13
- WP Rocket @ 3.12.2.1

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@E-VANCE this issue should be fixed in 3.13.4. Feel free to reopn if you're still experiencing this problem.
