### ISSUE TITLE
Allow to ignore all query strings

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#5566]
**Is your feature request related to a problem? Please describe.**
From time to time, we get questions about how to ignore all query strings.

Right now we have this helper plugin: https://github.com/wp-media/wp-rocket-helpers/tree/2e5347b364a717be323d06a411036146574ac450/cache/wp-rocket-cache-ignore-query-strings

But it only allows to add known query strings to the array, also, an approach like:

```
foreach($_GET as $key => $value)
{
$params[$key] = 1;
}

return $params;

```

It is difficult to use, because the config file needs to be regenerated every time.

**Describe the solution you'd like**
It may be a good idea to accept a wildcard or to have a filter (That doesn't need the file to be regenerated) to be able to modify the array of ignored query strings programmatically.

**Describe alternatives you've considered**
* Accepts wildcard
* Have a filter that doesn't need the config file to be regenerated

**Additional context**

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
