### ISSUE TITLE
Fatal error while activating WP Rocket - Argument 2 passed to WP_Rocket\Logger\Logger::error() must be of the type array, string given

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5567]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.2.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Activating WP Rocket directly through the following error: 

```
Fatal error: Uncaught TypeError: Argument 2 passed to WP_Rocket\Logger\Logger::error() must be of the type array, string given, called in /home/domains/domain.ext/public_html/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php on line 30 and defined in /home/domains/domain.ext/public_html/wordpress/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php:127 Stack trace: #0 /home/domains/domain.ext/public_html/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php(30): WP_Rocket\Logger\Logger::error('Error saving ac...', 'Action Schedule...') #1 /home/domains/domain.ext/public_html/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/Queue.php(24): WP_Rocket\Engine\Common\Queue\AbstractASQueue->add_async('rocket_preload_...') #2 /home/domains/domain.ext/public_html/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Preload/Activation/Activation.php(68): WP_R in /home/domains/domain.ext/public_html/wordpress/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php on line 127
```

Changing: 

https://github.com/wp-media/wp-rocket/blob/7249d2ea66c41e7b6905ea42bd64f0657ed0ffc1/inc/Engine/Common/Queue/AbstractASQueue.php#L30

To: 

```
Logger::error( $exception->getMessage(), ['Action Scheduler Queue'] );
```

to satisfy the expected type fixed the issue.

It's unclear what triggers the issue. I suspect it has something to do with the PHP version used.

Some additional info: https://gist.github.com/DahmaniAdame/65a223e4b71a66914a7ecc819e15cdc1

https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Common/Queue/AbstractASQueue.php has a lot of the same Logger method used `Logger::error()`, feeding the second parameter with the wrong data type. 

They will surely trigger the same error as well whenever they are executed. 

All of them should be made to use an array as the second parameter.

**To Reproduce**
Tried to reproduce it locally using different PHP and using the default theme without success. 
I couldn't check with the specific PHP version `7.4.32`.

**Expected behavior**
There shouldn't be any errors resulting from using WP Rocket.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2063272971/380620/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :heavy_multiplication_x: 

### Scope a solution
I think this will happen in versions >= PHP 8 and this function `as_enqueue_async_action` has to fail 
i don't know how to make it fail
But 
changing the code as @DahmaniAdame said will fix it

`Logger::error( $exception->getMessage(), ['Action Scheduler Queue'] );
`
### Estimate effort
Effort `XS`
