### ISSUE TITLE
CDN isnot applied to relative URL with query string

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5568]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.2.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Relative URLs with query string aren't rewritten to CNAME

**To Reproduce**
1. Having a relative URL on the page with query string i.e `<script type='text/javascript' src='/wp-content/print-helloworld-v3.js?test=3'></script>`
2. Enable CDN and add CNAME
3. Save settings
4. Visit the URL and check the source

**Expected behavior**
URL is rewritten to CNAME as same as for relative URL without query string

**Screenshots**
![Screenshot from 2022-11-15 09-13-19](https://user-images.githubusercontent.com/76941962/201853520-62bafcb5-30f7-4156-b437-c6e18986eb90.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
