### ISSUE TITLE
[WIP] 500 error after updating to 3.12.3 preg_replace() at /DelayJS/HTML.php on line 147

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5570]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A fatal error lading to 500 errors after updating to **WP Rocket 3.12.3.**

happening at the `preg_replace` function, Delay Javascript Execution HTML.php  [here](https://github.com/wp-media/wp-rocket/blob/7249d2ea66c41e7b6905ea42bd64f0657ed0ffc1/inc/Engine/Optimization/DelayJS/HTML.php#L147)

```
Stack trace:
#0 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php(147): preg_replace('#\\<script data\\...', '<script data-no...', NULL, 1)
#1 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php(88): WP_Rocket\Engine\Optimization\DelayJS\HTML->parse(NULL)
#2 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/Subscriber.php(85): WP_Rocket\Engine\Optimization\DelayJS\HTML->delay_js('<!DOCTYPE html>...')
#3 /wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\DelayJS\Subscriber->delay_js('<!DOCTYPE html>...')
#4 /wp-includes/plugin.php(205): WP_Hook->apply_filters('<!DOCTYPE html>...', Array)
#5 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters('rocket_buffer', '<!DOCTYPE html>...')
#6 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer('<!DOCTYPE html>...', 9)
#7 /wp-includes/functions.php(5279): ob_end_flush()
#8 /wp-includes/class-wp-hook.php(308): wp_ob_end_flush_all('')
#9 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#10 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /wp-includes/load.php(1124): do_action('shutdown')
#12 [internal function]: shutdown_action_hook()
#13 {main}
thrown in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 147
```

**To Reproduce**
still under investigation

**Additional context**
tickets: 
https://secure.helpscout.net/conversation/2068464090/381768
https://secure.helpscout.net/conversation/2068392123/381744
https://secure.helpscout.net/conversation/2068464090/381768

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/2068276771/381688?folderId=3864740

**Comment by alfonso100** [comment]
related https://secure.helpscout.net/conversation/2068660366/381815?folderId=273761

**Comment by juricazuanovic** [comment]
Related: https://secure.helpscout.net/conversation/2068052258/381643/
