### ISSUE TITLE
Mobile Menu does not work with Soledad Theme

### ISSUE THREAD

**Issue by spk100** [wp-media/wp-rocket#5576]
[Soledad Theme](https://themeforest.net/item/soledad-multiconcept-blogmagazine-wp-theme/12945398) has a built-in [speed optimization ](https://soledad.pencidesign.net/soledad-document/#speed-optimization) that is recommended by the theme developer.

When I enable those options and disable the ones inside WP Rocket, the page speed scores are not that great as I have other plugins as well.

When I enable both the options and use the remove unused css in WP Rocket, the mobile menu does not work.
I tried disabling/enabling each feature one by one and figured out the "remove unused css" is causing the issue .

Disabling this solves the menu issue but the page speed numbers go down :(

**To Reproduce**

Enable all speed optimization features as mentioned by the theme developer. 
Enable the cache in WP Rocket including a separate cache for mobile devices
check the menu on mobile and it does not pop out see that its broken

**Comment by GeekPress** [comment]
Hi @spk100 ,

You must not use two speed optimization tools at the same time. I really recommend only using WP Rocket to optimize your website.

All CSS options from this theme are totally useless by using WP Rocket and our Remove unused CSS feature.

Using both will be at your own risk.
