### ISSUE TITLE
Update jQuery Migrate regex

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5583]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We use the following regex in order to exclude jQuery migrate: 
```
jquery-migrate(.min)?.js
```

It matches: 

```
/jquery-migrate.js
/jquery-migrate.min.js
```

But it doesn't match:

```
/jquery-migrate-1.4.1.min.js
```

The following regex fixes that: 

```
/jquery-migrate((.*?)(.min?)?).js
```

**To Reproduce**
1. Use Delay JavaScript Execution with the jQuery migrate exclusion pattern
2. Use `/jquery-migrate-1.4.1.min.js` or something similar
3. See that the file is not excluded from Delay JavaScript Execution

**Expected behavior**
We should exclude all patterns of jQuery Migrate when the regex is used.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2068172775/381657/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This should be fixed with the newest regex:
```
\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?( |'|"|>)
js-(before|after)
(?:/wp-content/|/wp-includes/)(.*)
```
