### ISSUE TITLE
Google Adwords Redirect Conflict

### ISSUE THREAD

**Issue by bradleymoore111** [wp-media/wp-rocket#559]
When a youtube video is embedded into a page that has ads, sometimes WP-Rocket (issue disappeared when plugin was disabled, immediately appeared after reactivation) will serve a 302 Redirect directly to the advertisement, any idea where this could be coming from?

**Comment by arunbasillal** [comment]
@bradleymoore111 Can you still experiencing the problem? We do not have any further reports of the same. 

When you mean ads, do you mean Adsense ads? 

If you still experience the issue please write to our support team directly and we will help you out - https://wp-rocket.me/support
