### ISSUE TITLE
Clear the cache of certain language will clear the whole cache in some cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5590]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.3.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Clearing the cache of one language will clear the whole cache 

**To Reproduce**
Precondition:
- WPML language format using qs i.e Language name added as a parameter (https://rocketlabsqa.ovh?lang=ar - Arabic)
- Website has 3 languages
- The shop page is set
1. Install and activate WPR
2. Visit the Product and shop page in 3 different languages => pages are cached and completed in preload table
3. Clear cache of 1 language i.e AR
4. All cache was cleared

**Expected behavior**
Clear only affected language and not clear the whole cache

**Screenshots**

https://user-images.githubusercontent.com/76941962/203273059-99a869fb-cb2e-47e2-b1f3-6c052487864d.mp4

https://user-images.githubusercontent.com/76941962/203283666-0e564b6f-adef-4113-8811-339d1a76add5.mp4

**Additional context**
- Same happened on 3.11.5 
- Sometimes, after step 3, the shop page gets unset automatically when we edit the product
- Other setups for WPML shall be validated
- WPML Version 4.5.8, WooCommerce Version 7.1.0, WCML Version 5.0.2

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
We are ignoring query strings when clearing the cache and keep only the path:
https://github.com/wp-media/wp-rocket/blob/5ddfb40f083765f1df50398efba339571ce82bc7/inc/functions/files.php#L758

So:
* https://vasilis.rocketlabsqa.ovh/?lang=el
* https://vasilis.rocketlabsqa.ovh/?lang=en
are treated like https://vasilis.rocketlabsqa.ovh/

We will likely need to change how the cache is stored when `$lang` is used. For example:
* `cache/wp-rocket/example.com/#lang=el` should store all the `el` URLs.
* `cache/wp-rocket/example.com/#lang=en` should store all the `en` URLs, etc.

Things will be more complicated when more than one query string is used/cached, e.g. `/about-us?lang=el&location=Greece`.
In such a case, we could store the cache like this:
* `cache/wp-rocket/example.com/#lang=el/about-us#location=Greece`

To make things worse there is inconsistent behavior depending on whether permalinks have a trailing `/` or not.
For `/about-us?lang=el `:
* with a `/` we'll store its cache in a subfolder of the page to `cache/wp-rocket/example.com/about-us/#lang=el`
* without a `/` the cache will be stored to: `cache/wp-rocket/example.com/about-us#lang=el`

This likely needs to be tackled as well.

**Comment by Mai-Saad** [comment]
Some exploratory test note(s) on the same env (may need new GH):
1- After a fresh install of WPR, language qs folders are fetched only for the home page by strange names (while Home is set to the latest posts or specific page), if we clear and preload the cache, it will be removed
 => on 3.12.3.1 and 3.12.2.1 but not on 3.11.5 
![Screenshot from 2022-11-22 13-15-50](https://user-images.githubusercontent.com/76941962/203328131-fe02e73c-220d-4816-8958-15807fe23956.png)
2- Even on newlabs (without WPML), visiting URLs with in-progress status while a separate mobile cache is enabled, will result in completed status although no mobile version of the cache exists in the cache folder
3- Preload is not changing the status of paginated pages after editing any post inside it although, the edited post, home, and page folder were already deleted from the cache (not only prev/next pagination)

**Comment by piotrbak** [comment]
To consider when fixing:
- https://github.com/wp-media/wp-rocket/issues/2983
- https://github.com/wp-media/wp-rocket/issues/3444

**Comment by Mai-Saad** [comment]
on 3.15.2, Can see that clearing the cache of a specific language, will clear the whole cache except for this language (to the home page) and will change the language switch at admin to that specific language

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
