### ISSUE TITLE
[RUCSS] Bad json & Browser can't open new page

### ISSUE THREAD

**Issue by CyrilDesch** [wp-media/wp-rocket#5591]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.2.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The bug occur when used css be generated. Saas job failed very often. have two errors send by saas :
- 400 : Bad JSON (most often)
- 408 : Browser couldn't open new page
```
Error: Browser couldn't open new
at PuppeteerManager.getPageResources (/var/www/rucss/libs/puppeteer-manager.js:92:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async RUCSSManager.startPurge (/var/www/rucss/libs/rucss-manager.js:15:34)
at async module.exports (/var/www/rucss/processor.js:43:22)
at async /var/www/rucss/node_modules/bullmq/dist/cjs/classes/child-processor.js:69:33
```

**To Reproduce**
1. Start Remove unused CSS & Preload
2. Wait
3. See error on WP Rocket Debug report (wp-rocket-debug.log.html)

**Expected behavior**
Remove unused css

**Additional context**
- Elementor & Woocommerce
- No other special plugin
- Try to reduce the speed of RUCSS & Preload with helper plugin, but no change

URL : https://plantedesgraines.fr

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Paktas** [comment]
How did you fix the above errors with "Bad JSON" errors on RUCSS? We're having similar issue.

**Comment by Periago4** [comment]
Any solution? I have the same problem.

**Comment by MSzwandt88** [comment]
Yep, same issue on both of my websites using WP Rocket. My wpr_rucss_used_css table is just full of failed statuses due to Bad JSON 400 errors.

**Comment by Periago4** [comment]
Yo he escrito a WP Rocket y de momento no me han solucionado nada tras una semana de trabajos

**Comment by bilbofrodo** [comment]
Hi all, 

Don't know if this will work for everyone. Spoke to WP Rocket as I was experiencing the same. They suggested increasing php sizes. 

I cleared used css, emptied wp_wpr_rucss_used_css and increased php sizes the next one up to 512MB from 256MB. This worked.

But then I saw that the URLs in wp_wpr_rucss_used_css were also listing all archives, tags etc resulting in hundreds of additional URLs that didn't need this. I therefore used advanced rules and a wildcard to stop these URLs from having their remove unused CSS. This allowed me to return my php settings back to where they were (256MB). While still having my remaining URLs (under 400) have completed RUSS and with no bad json. 

I appreciate this won't work for everyone. Just hope it helps.

**Comment by slamachul** [comment]
Hej @bilbofrodo 

I'm  experiencing the same issues as you had. I mean 400 and 408 as statuses in wp_wpr_rucss_used_css table.
Please let us know what exact "php sizes" you set up after which you got correct used css caching?

Thanks a lot!

**Comment by bilbofrodo** [comment]
Hi @slamachul 

Apologies, for not including these originally. Just updated my original comment. Increased php memory size from 256 to 512. But when I realised it was also removing unused CSS for tag pages etc, and I stopped this, it no longer needed the increase. But prior to that the increase worked.

**Comment by armancse-dev** [comment]
I am facing the same issue on my website

**Comment by slamachul** [comment]
Thank you @bilbofrodo for a response. 
Yeah. We rised up hour server settings: nginx - buffers, php fpm pools concerning spawning new threads. Also We rised php settings like timeouts and memory to 512. Timeouts in nginx. We do not see it helped. We still experience an issue. 
I understand you turned off "Remove unused CSS" functionality in File Optimization -> Optimize CSS Delivery section?

**Comment by slamachul** [comment]
Hi @armancse-dev Please ping in case you find out soloution. I will ping too.

**Comment by abdobasha2004** [comment]
> Hi all,
> 
> Don't know if this will work for everyone. Spoke to WP Rocket as I was experiencing the same. They suggested increasing php sizes.
> 
> I cleared used css, emptied wp_wpr_rucss_used_css and increased php sizes the next one up to 512MB from 256MB. This worked.
> 
> But then I saw that the URLs in wp_wpr_rucss_used_css were also listing all archives, tags etc resulting in hundreds of additional URLs that didn't need this. I therefore used advanced rules and a wildcard to stop these URLs from having their remove unused CSS. This allowed me to return my php settings back to where they were (256MB). While still having my remaining URLs (under 400) have completed RUSS and with no bad json.
> 
> I appreciate this won't work for everyone. Just hope it helps.

This worked for me
