### ISSUE TITLE
Add Missing Image Dimensions modifies other attributes in some cases

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5595]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.2.1
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
After **Add Missing Image Dimensions** option is applied, `alt` attribute is replaced with `data-alt`.

**To Reproduce**
1. Create a post (I used TwentyTwentyOne theme) and add an HTML block with the following HTML:
`<img src="https://example.com/image.png" data-height="189" alt="your alt tag text">`
You need to replace `https://example.com/image.png` with a valid image on your server.
3. Enable **Add Missing Image Dimensions** option in WP Rocket settings.
4. Check the optimized page and you will find the `img` tag is replaced by the following:
`<img width="571" height="189" src="https://example.com/image.png" data-alt="your alt tag text">`

**Expected behavior**
`alt` attribute and other attributes should not be modified.

**Additional context**

This is happening on this line https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L327 where RegEx is extracting the `height` attribute but leaves `data-` out:
![image](https://user-images.githubusercontent.com/60236665/204148409-27d9e0dc-22bd-4dab-b183-755b769e76d3.png)

After `preg_replace()` is executed we are left with the following:
`<img src="https://example.com/image.png" data-alt="Online Casino Österreich"/>`
and then we add the `width` and `height` attributes.

Ticket: https://secure.helpscout.net/conversation/2072685876/382720/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Duplicate:
https://github.com/wp-media/wp-rocket/issues/5818
