### ISSUE TITLE
The /feed/ url is cached and optimized by default

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5599]
**Before submitting an issue please check that you’ve completed the following steps:**
yes- Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On WP Rocket 3.12.3.2 `/feed/` is cached and optimized by default. rolling back to 3.11.5 fixes the issue.
this might be affecting `/wp-json/` too and probably other paths. (untested)

**To Reproduce**
1. Install 3.12.3.2
2. Visit the /feeds URL and see caching and optimization applied
3. Rollback to 3.11.5 and clear the cache
4. Visit the /feeds URL again,  caching and optimization are NOT applied

**Expected behavior**
Feeds should not be cached unless the user opts for this. And optimizations shouldn't be applied in any case.

**Screenshots**
![IM3zjAV](https://user-images.githubusercontent.com/229406/204639150-8d73c844-fd06-4eca-a1ac-0512dea824b4.jpg)

https://i.imgur.com/IM3zjAV.jpg

**Additional context**
ticket where /feed/ is cached https://secure.helpscout.net/conversation/2079965213/385018/
probably related, about /wp-json/: https://secure.helpscout.net/conversation/2082507658/385784?folderId=273761

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment]
related commit https://github.com/wp-media/wp-rocket/commit/c0fb3c9da98e4db258b94254e4deb9df036d4552 in 3.12.3.2

**Comment by remyperona** [comment]
the user_trailingslashit() should only be applied to user added patterns, instead of applying it in the get_rocket_cache_reject_uri(), to avoid adding extra slash to some of the patterns.

This could be done by using this function before saving the value to the database with the pre_update hook for example, or during sanitize of the option

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/2083011318/385873?folderId=3864740

`wp-json` are being cached.

**Comment by alfonso100** [comment]
related https://secure.helpscout.net/conversation/2083458937/386040?folderId=273766

**Comment by jeawhanlee** [comment]
We will need to take out these lines: https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/functions/options.php#L238-L243 so as to stop trailing slash being appended to non user added patterns.

### Match only user added patterns to permalink structure
**When settings is saved**
We will hook a method to `pre_update_option_{$option}` that returns the updated pattern values of `cache_reject_uris` after matching with permalink structure in https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Cache/Config/ConfigSubscriber.php so as for this to also reflect in the UI as per discussion with @Tabrisrp.

**When Permalink structure changes**
We will add a new filter to `get_rocket_cache_reject_uri` function on this [line](https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/functions/options.php#L195) that will filter the uris with the permalink structure, then hook to the same method above in https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Cache/Config/ConfigSubscriber.php that way when `permalink_structure_changed` hook fires and `rocket_generate_config_file()` is called, `get_rocket_cache_reject_uri` will also be called [here](https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/functions/files.php#L126) and new filter will be applied.

We also need to update the cache_reject_uris that uses the new permalink structure to reflect in the UI , to do that we will edit this method https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/Engine/Cache/Config/ConfigSubscriber.php#L27 to update the cache_reject_uri option to use the current permalink structure just before we call the `rocket_generate_config_file()` function.

**Comment by engahmeds3ed** [comment]
I think we need to make it simpler, I believe the first point is not needed, using the hook `get_rocket_option_cache_reject_uri` and apply the code on its value like the following code, this will reflect in the UI also:
```
add_filter( 'get_rocket_option_cache_reject_uri', function( $value ){
	if ( empty( $value ) ) {
		return $value;
	}
    
	return array_map(
		function ( $uri ) {
			return user_trailingslashit( $uri );
		},
		$value
	);
} );
```

what do u think?

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
### Scope a solution ✅
Regarding @engahmeds3ed comment above and discussion with @Tabrisrp to address the UI, We will need to take out these lines:

https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/functions/options.php#L238-L243 then update `WP_Rocket\Engine\Cache\Config:: ConfigSubscriber` and add a new call back that will hook to `get_rocket_option_cache_reject_uri` that way, non user added pattern will be preserved and changes will reflect in the UI also.

### Estimate the effort ✅
[XS]

**Comment by remyperona** [comment]
This solution won't be reflecting the correct value in the DB when a value was first added then saved. That's why it needs to happen before saving the value, not later

**Comment by engahmeds3ed** [comment]
After a discussion with @Tabrisrp we agreed on that using `get_rocket_option_cache_reject_uri` will reflect on the UI and in every place we get this option and it won't hurt to reflect that on the database also.

So in the same class `WP_Rocket\Engine\Cache\Config:: ConfigSubscriber` we will need to add a callback for the pre_update hook:

```
'pre_update_option_' . WP_ROCKET_SLUG     => [ 'change_cache_reject_uri_with_permalink', 10, 2 ],
```

then

```
public function change_cache_reject_uri_with_permalink( $value, $old_value ) {
    if ( $old_value['cache_reject_uri'] === $value['cache_reject_uri'] ) {
        return $value
    }
    return $this->match_pattern_with_permalink_structure( $value['cache_reject_uri'] );
}
```

what do u think @jeawhanlee ?

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/2085793083/386604?folderId=377611
FYI, this is affecting some other scenarios as well. 
The customer is trying to exclude `/index.php(.*)` to solve [this issue](https://docs.wp-rocket.me/article/1434-home-page-content-displayed-on-all-pages), and it no longer works.

**Comment by worldwildweb** [comment]
/wp.serviceworker was also affected 3.12.3.3 fixes the issue.
