### ISSUE TITLE
Cloudflare URL purge not working on some hosting compatibilities

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5600]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.2.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Rocket unhooks the following actions as part of compatibility with some of the hosting services where our plugin does not handle cache: 

- `wp_trash_post`
- `delete_post`
- `clean_post_cache`
- `wp_update_comment_count`

This results in `rocket_clean_post` not firing and `after_rocket_clean_post` as a result and, consequently, the Cloudflare add-on not being able to execute `auto_purge_by_url`. 

https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Addon/Cloudflare/Subscriber.php#L65

Affected compatibilities: 
- Kinsta
- Pressalabs
- Flywheels

**To Reproduce**
1. Use the Cloudflare add-on
2. Add remove_action( 'clean_post_cache', 'rocket_clean_post' ) to simulate what happens on the affected environments
3. Log if [`auto_purge_by_url`](https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Addon/Cloudflare/Subscriber.php#L173) gets executed
4. Update a page and see the result

**Expected behavior**
Cloudflare purging should work on environments where `clean_post_cache

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2080749951/385334/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Plinpod** [comment]
Seeing identical issue

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
