### ISSUE TITLE
Feature request: Log critical CSS generation errors

### ISSUE THREAD

**Issue by simkoG** [wp-media/wp-rocket#5602]
**Is your feature request related to a problem? Please describe.**
You should log the errors that prevent the "Regenerate Critical CSS" from running. I have seven post types on my site. Sometimes the Critical CSS generation could not be complete because of some type of error. It is hard to find out what causes the problem.

**Describe the solution you'd like**
When the "Regenerate Critical CSS" fails to run, you should log what can cause the problem. 

**Describe alternatives you've considered**
[You have a post regarding this issue](https://docs.wp-rocket.me/article/1267-troubleshooting-critical-css-generation-issues) where users can check what can cause the problem, but it would be very helpful to see the actual error that prevents the CSS generation. 

**Additional context**

![Screenshot 2022-11-30 110540](https://user-images.githubusercontent.com/10430702/204767481-22e89de6-8ef7-4c41-b3ac-de69d812f1bf.jpg)

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
