### ISSUE TITLE
Support custom htaccess location (like Bedrock)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5603]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WordPress is deployed using Bedrock + using Multisite, WP Rocket looks for the `htaccess` file using the following: 

[`$htaccess_file = get_home_path() . '.htaccess';`](https://github.com/wp-media/wp-rocket/blob/bfc0d3eafa7e6a401672f42124d94fce502b171f/inc/functions/htaccess.php#L680)

This results in checking `/web/wp/.htaccess` instead of the default location `/web/.htaccess` (outside of the WordPress installation. 

```
├── composer.json
├── config
│   ├── application.php
│   └── environments
│       ├── development.php
│       ├── staging.php
│       └── production.php
├── vendor
└── web
    ├── .htaccess
    ├── app
    │   ├── mu-plugins
    │   ├── plugins
    │   ├── themes
    │   └── uploads
    ├── wp-config.php
    ├── index.php
    └── wp
```
We need to have a filter to allow altering the path where we check for the `htaccess`. 

Ideally, we can detect if WordPress is using Bedrock and use the filter to apply the correct location.

The customer shared the following info about how we can detect if Bedrock is being used: 

- Check the existence of the MU Plugin `Bedrock Autoloader` - `/mu-plugins/bedrock-autoloader.php` - [reference](https://github.com/roots/bedrock/blob/master/web/app/mu-plugins/bedrock-autoloader.php)
It can be done using [get_mu_plugins()](https://developer.wordpress.org/reference/functions/get_mu_plugins/)
- Check if `wp-config.php` loads `config/application.php`

**To Reproduce**
1. Use Bedrock
2. Check the issue

**Expected behavior**
We should be able to set the right location for the `htaccess`. 

**Screenshots**
N/A

**Additional context**
https://secure.helpscout.net/conversation/2080611881/385227

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
