### ISSUE TITLE
.kml URLs shouldn't be cached

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5606]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.3.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Accessing the URL with .kml extension while permalinks using .kml will result in caching the .kml in caching folder although it is not in caching table

**To Reproduce**
1. Set permalinks to `/%postname%.kml/`
2. Access any post i.e domain/post.kml/
3. Check caching folder

**Expected behavior**
URL is not cached 

**Screenshots**
![Screenshot from 2022-12-02 07-52-20](https://user-images.githubusercontent.com/76941962/205224576-5bed0138-0e26-4223-84b5-9651519ba9d3.png)

**Additional context**
- Other extensions mentioned [here](https://github.com/wp-media/wp-rocket/pull/5427/files#diff-30a46cf1cdbb73aeb3f9cc7171e0088ad71307d47bd27d32e548e2aab0f1d540R519) aren't cached i.e php, xsl, xml
- Already exists on 3.12.2

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Having permalinks with .kml is probably never going to happen in a real world scenario

**Comment by piotrbak** [comment]
Agree with @Tabrisrp it's very edgy, I'd close it and reopen if we have any feedback.
