### ISSUE TITLE
Clear root folder when WPML uses a directory for the default language

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5611]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WPML uses the option `use directory for default language`, the root folder is inaccessible by any of our cache-purging function. 

![image](https://user-images.githubusercontent.com/1289174/205887406-1a4cef59-b805-4099-b923-76843f47fd1d.png)

The default language will have a separate folder from the root in this scenario.

We are doing that kind of check when WPML is enabled: 

https://github.com/wp-media/wp-rocket/blob/8c603e242ed0d5b192711380504a4cc658812208/inc/functions/files.php#L711-L713

We need compatibility with WPML to detect that the sub-option is enabled and include the root folder in actions.

Temporarily fixed by clearing files from root using: 

```
function rocket_remove_root_cached_files( $post, $purge_urls, $lang ) {
	$cache_folder_path = _rocket_get_wp_rocket_cache_path() . $_SERVER['SERVER_NAME'] . "/";
	$cache_folder_directory = dir($cache_folder_path);
	while ($file = $cache_folder_directory->read()) {
		if (!strpos($file,'.html')) continue;
		unlink($cache_folder_path . $file);
	}
}
add_action( 'after_rocket_clean_home', 'rocket_remove_root_cached_files', 10, 3 );
add_action( 'after_rocket_clean_domain', 'rocket_remove_root_cached_files', 10, 3 );
```

**To Reproduce**
1. Use WPML and enable `use directory for default language`
2. Make sure the root homepage is cached
3. Try to purge cache

**Expected behavior**
All caches should be accessible to purge regardless of what options are enabled on WPML. 

**Screenshots**
Added to decription.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2071911982/382573/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
I think it's the same as this one? 
https://github.com/wp-media/wp-rocket/issues/1890

**Comment by DahmaniAdame** [comment]
@webtrainingwheels, it's the same issue, indeed.
@piotrbak we can close #1890 since this one is more recent and has more details.

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I reproduced the issue locally.
## Identify the root cause
The root problem is mentionned by @DahmaniAdame.
## Scope a solution
For the solution in the [WPML](https://github.com/wp-media/wp-rocket/blob/develop/inc/ThirdParty/Plugins/I18n/WPML.php) subscriber we will add the following callback:
```php
public function remove_root_cached_files() {
		$site_url = home_url();
		$host_name = parse_url( $site_url, PHP_URL_HOST );
		$cache_folder_path = _rocket_get_wp_rocket_cache_path() . $host_name . "/";
		$cache_folder_directory = $this->filesystem->dirlist($cache_folder_path);
		foreach (array_keys($cache_folder_directory) as $entry) {
			if ($this->filesystem->is_dir($entry)) {
				continue;
			}
			$this->filesystem->delete($cache_folder_path . $entry);
		}
	}
```

That we will  subscribe to the events:
- `after_rocket_clean_home`
- `after_rocket_clean_domain`

## Estimate the effort
Effort `S`

PS: Thank you for the base template @DahmaniAdame
