### ISSUE TITLE
Failed to execute 'setAttribute' on 'Element': '};' is not a valid attribute name.

### ISSUE THREAD

**Issue by jt196** [wp-media/wp-rocket#5612]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version `Version 3.12.3.2` 

**Describe the bug**
With JS delay turned on, I have a hamburger menu break. I've excluded the necessary js script files (theme custom.js, jquery) but still getting the issue. 

The error message is 

```
(index):3 Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '};' is not a valid attribute name.

    at https://www.<our_site>.com/:3:5192
    at Array.forEach (<anonymous>)
    at https://www.<our_site>.com/:3:5112
    at new Promise (<anonymous>)
    at RocketLazyLoadScripts._transformScript (https://www.<our_site>.com/:3:5036)
    at async RocketLazyLoadScripts._loadScriptsFromList (https://www.<our_site>.com/:3:5437)

```

And seems to relate to the injected jquery code in the header. It works in Firefox as this code isn't there. 

It looks like it relates to the following code in the header:

```JQUERY
    async _transformScript(e) {
        return await this._littleBreath(), new Promise((t => {
            const n = document.createElement("script");
            [...e.attributes].forEach((e => {
                let t = e.nodeName;
                "type" !== t && ("data-rocket-type" === t && (t = "type"), n.setAttribute(t, e.nodeValue))
            })), e.hasAttribute("src") ? (n.addEventListener("load", t), n.addEventListener("error", t)) : (n.text = e.text, t());
            try {
                e.parentNode.replaceChild(n, e)
            } catch (e) {
                t()
            }
        }))
    }
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @jt196 and thanks for creating the issue. Issues on our Github are supposed to collect confirmed bugs with exact steps to reproduce. I'd suggest contacting our Support Team to find the root cause, and if the change should happen on the WP Rocket core side, we'll reopen the issue and fix it.

**Comment by Muskan109** [comment]
Iam getting this error in DOM no error showin
![Uploading image.png…]()
 g in IDE . What it indicate and how to deal wirth it ?
