### ISSUE TITLE
Update Minify dependency with latest changes

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5617]
**Is your feature request related to a problem? Please describe.**
We should update the minification library. 

[It'll](https://github.com/matthiasmullie/minify/commit/d8993df3953c2db59c12a713e9e5c927fe4c5426) fix the following issues:
- https://github.com/wp-media/wp-rocket/issues/2083

**Additional context**
We need to make sure we won't introduce regression described here:
- https://github.com/wp-media/wp-rocket/issues/2974

**Comment by jeawhanlee** [comment]
We can simply update the pattern in https://github.com/wp-media/wp-rocket/blob/1f30942192514822d57f319a5cef05adc42aba62/inc/Dependencies/Minify/CSS.php#L743 to `/(?<=^|[;}{])\s*(--[^:;{}"\'\s]+)\s*:([^;{}]+)/m` which is the current [change](https://github.com/matthiasmullie/minify/commit/d8993df3953c2db59c12a713e9e5c927fe4c5426) that fixes this [issue](https://github.com/matthiasmullie/minify/issues/397).
I don't think this little change should introduce any regression.
