### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function when activate WPR with Plugin using old AS (v2.2.5)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5620]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.3.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A fatal error exists when activating WPR on the website when other active plugin use old AS i.v2.2.5

**To Reproduce**
1.WooCommerce 3.8.3 installed and activated (used AS 2.2.5)
2. Install WPR 3.12.3.3
3. Activate WPR
```
[12-Dec-2022 14:10:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WP_Rocket\Engine\Common\Queue\as_enqueue_async_action() in /home/wpquicki/mega/enfold/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php:28
Stack trace:
#0 /home/wpquicki/mega/enfold/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/Queue.php(24): WP_Rocket\Engine\Common\Queue\AbstractASQueue->add_async('rocket_preload_...')
#1 /home/wpquicki/mega/enfold/wp-content/plugins/wp-rocket/inc/Engine/Preload/Activation/Activation.php(68): WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_load_initial_sitemap_async()
#2 /home/wpquicki/mega/enfold/wp-includes/class-wp-hook.php(307): WP_Rocket\Engine\Preload\Activation\Activation->preload_activation('')
#3 /home/wpquicki/mega/enfold/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(false, Array)
#4 /home/wpquicki/mega/enfold/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /home/wpquicki/mega/enfold/wp-content/plugins/wp-rocket/inc/Engine/Activation/Activation.php(7 in /home/wpquicki/mega/enfold/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php on line 28
```

**Expected behavior**
No fatal error when activating WPR 

**Additional context**
- Similar problem was handled [here](https://github.com/wp-media/wp-rocket/pull/4879) from AS v3.3 and above
- Updating WC to the latest or activating WPR before WC shall fix the problem

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
@GeekPress We have [PR](https://github.com/wp-media/wp-rocket/pull/5718) by @engahmeds3ed that will relatively solve this issue.

**Comment by piotrbak** [comment]
Closing it since it'll be solved by the above PR.
