### ISSUE TITLE
Compatibility with WP Webhooks Pro (post status change hooked to rocket_clean_domain)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5629]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Webhooks Pro provides webhooks that will fire actions on WordPress. 

They do have an integration with WP Rocket to trigger `rocket_clean_post`, but it doesn't seem to behave as expected when part of what needs to be done involves changing the post status, specifically when moving a post to `trash`. 

Logging our purged URL, WP Rocket will try to purge the trashed post: 
```
https://domain.ext/test__trashed/
```
It should be:
```
https://domain.ext/test/
```
This means that rocket_clean_post() was fired after the status changed. 

The WP Webhooks recently added two filters that might be helpful to help fix that: 
- https://wp-webhooks.com/integrations/wordpress/triggers/wp_apply_filters_fired/
- https://wp-webhooks.com/integrations/wordpress/triggers/wp_do_action_fired/

**To Reproduce**
1. Use the WP Webhooks Pro
2. Create a flow that changes the post status
3. Attach `rocket_clean_post` to it as an action
4. See that the post cache was not cleared when the flow triggers (post status changes, but the post cache remains)

**Expected behavior**
The post cache should be cleared regardless of how the post status changes.

**Screenshots**

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2095104826/388521/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
