### ISSUE TITLE
Cached files in /wp-content/cache/wp-rocket/ directly accessibly

### ISSUE THREAD

**Issue by benique** [wp-media/wp-rocket#5641]
The Cached files in /wp-content/cache/wp-rocket/ are directly accessibly.

This is a huge problem. It creates duplicate content among other issues.

**Comment by piotrbak** [comment]
Hello @benique and thanks for creating the issue. I don't think this is something that can be done by WP Rocket directly, that kind of rules should be set up on a web server level.

Moreover, to prevent this from happening, you could also implement canonical tags or exclude the content using robots.txt file.
