### ISSUE TITLE
Revealing hidden query string on Debug

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5643]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If `$_GET` is customized for whatever reason, it will force WP Rocket to exclude pages from cache and optimizations. 

The only clue we get when `WP_ROCKET_RUCSS_DEBUG` is the cause of the rejection but no hint about what is the offending query string. 

Support will need that information to: 

- Help the customer to find where it comes from. 
- Make the found query string(s) cacheable by manually adding them to `Cache Query Strings` if the root cause can't be fixed.

This can be done by changing https://github.com/wp-media/wp-rocket/blob/58784bd05e3919595ed453870f69aeb3f580e8b2/inc/classes/Buffer/class-tests.php#L200 to: 

```
$this->set_error( 'Query string URL is excluded:' . PHP_EOL . print_r( $_GET, true ) );
```

This will output something like the following on the debugger: 

```
Query string URL is excluded:
Array
(
    [hidden-query-string] => query-string-value
)
```

**To Reproduce**
N/A

**Expected behavior**
Support should have more information about the possibly offending query strings. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2104097765/390446/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
I will skip the gromming part as the change and its reasons are clearly explained inside the issue.
