### ISSUE TITLE
Fatal issue: Fatal error: Uncaught Error: Class 'WP_Rocket\Buffer\Cache' not found....

### ISSUE THREAD

**Issue by pkiula** [wp-media/wp-rocket#5644]
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Updating to the latest version 3.12.3.3 as of 24 Dec 2023.. the caching was not working at all. When I deactivate and try to reactivate, the following error is seen: 

`Fatal error: Uncaught Error: Class 'WP_Rocket\Buffer\Cache' not found in /home/DOMAIN/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:134 Stack trace: #0 /home/DOMAIN/wp-content/plugins/wp-rocket/inc/functions/htaccess.php(55): get_rocket_htaccess_marker() #1 /home/DOMAIN/wp-content/plugins/wp-rocket/inc/Engine/Activation/Activation.php(77): flush_rocket_htaccess() #2 /home/DOMAIN/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Activation\Activation::activate_plugin('') #3 /home/DOMAIN/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 /home/DOMAIN/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/DOMAIN/wp-admin/plugins.php(194): do_action('activate_wp-roc...') #6 {main} thrown in /home/DOMAIN/wp-content/plugins/wp-rocket/inc/functions/htaccess.php on line 134
`

**To Reproduce**
Just deactivate and reactivate. WP is latest version. 

**Expected behavior**
Plugin should activate without issues. And cache should work, as it was. Nothing has been changed. Only plugin auto-updated itself.

**Comment by engahmeds3ed** [comment]
Hi @pkiula ,

I believe something wrong happened while updating, can you plz verify that the following file is there:
`wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php`
and has valid content inside?

Otherwise plz reach WP Rocket's Support to help you fixing this issue.

**Comment by pkiula** [comment]
Thank you. I just reuploaded the plugin forcefully. Deactivated, reactivated. Works now. Thanks.
