### ISSUE TITLE
Enhance the Handling of WWW/non-WWW Updates

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5647]
**Is your feature request related to a problem? Please describe.**
Let's say you change your site URL from non-WWW to WWW, and visit the non-WWW URL:

- **WordPress without WP Rocket:**  You'll be automatically redirected to the WWW URL. 
- **WordPress with WP Rocket:** WP Rocket will serve the non-WWW cache, **if the old WP Rocket configuration file exists**.
The non-WWW cache will be outdated, with broken links, and it's not purgeable.

While we have a [guide for domain changes](https://docs.wp-rocket.me/article/705-changing-domains-migrating-sites-with-wp-rocket), and having two configuration files is not always happening, making an automatic check+update will be useful.

**Describe the solution you'd like**
WP Rocket should detect the URL update or [General options](/wp-admin/options-general.php) update, and purge its paths and configurations accordingly.

**Describe alternatives you've considered**
- Unless the [WP Rocket | Multiple Config Files](https://github.com/wp-media/wp-rocket-helpers/tree/master/various/wp-rocket-multiple-config-files) helper is detected, WP Rocket should allow only one config file to exist.
- Detect the URL change and display an admin notice to purge config files.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/2097115953/388901?folderId=377611.
Slack thread: https://wp-media.slack.com/archives/G8L4EE8N9/p1671136542516399.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
