### ISSUE TITLE
Lazyload compatibility with the new Avada background markup

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5649]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Avada changed their markup for backgrounds inside an element to look like: 
```
<div class="fusion-equal-height-columns" style="--awb-background-image:url("path/to/image.jpg");--awb-background-size:cover;" ></div>
```
Instead of: 
```
<div class="fusion-equal-height-columns" style="background-image:url("path/to/image.jpg");--awb-background-size:cover;" ></div>
```

When lazyload is enabled, what happens is that our regex will catch `background-image:url("path/to/image.jpg");` and remove it, leaving the `--awb-` to be glued to whatever comes after it. 

In the above example, the end markup added to the page when lazyload is triggered will look like: 
```
<div class="fusion-equal-height-columns" style="--awb---awb-background-size:cover;background-image:url("path/to/image.jpg");" ></div>
```
Which will alter how the `background-size` property operates. 

Changing the following regex:

```
background-image\s*:\s*(?<attr>\s*url\s*\((?<url>[^)]+)\))\s*;?
```

found here: https://github.com/wp-media/wp-rocket/blob/58784bd05e3919595ed453870f69aeb3f580e8b2/inc/Dependencies/RocketLazyload/Image.php#L70 to: 

```
(--awb-)?background-image\s*:\s*(?<attr>\s*url\s*\((?<url>[^)]+)\))\s*;?
```

should fix the issue.

The new regex will look for `--awb-` as an optional string. 

We can use the same logic to accommodate themes/plugins prefixing the CSS background property. 

**To Reproduce**
1. Use the latest Avada
2. Add a background to an element
3. Enabled lazyload

**Expected behavior**
Lazyload on inline background shouldn't affect how the element is styled.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2106293204/390879/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Did you see any problems when trying to lazyload the new markup?

**Comment by DahmaniAdame** [comment]
@piotrbak yes. In the case that I had, it changed how a property should look like:

`--awb-background-size:cover;` turned to `--awb---awb-background-size:cover;` because of the `--awb-` leftover. 

That made the `background-size: cover` not processable by the browser and changed how the background filled the space.

**Comment by piotrbak** [comment]
@DahmaniAdame No no, I meant, after doing the changes in regex, so we'd catch the `--awb` correctly. Did you see any issues then?
`--awb-background-image` is not a correct CSS property, Avada needs to be doing something to display the background. I'm wondering if it's not conflicting with what we're doing while lazyloading.

**Comment by CrochetFeve0251** [comment]
## Scope a solution
@DahmaniAdame as  `--awb-background-image` is not a valid CSS attribute I propose we can add a filter on the regex and add a calback inside the 3rd party class from Avada to add what you proposed to the regex. On one hand it would solve the issue for Avada users and on another hand we won't change the logic for non-Avada users as there is no usage to add this rule for them.
For that we can apply a filter on the value on [this line](https://github.com/wp-media/wp-rocket/blob/58784bd05e3919595ed453870f69aeb3f580e8b2/inc/Dependencies/RocketLazyload/Image.php#L70):
```php
$regex = apply_filters( 'rocket_lazyload_bg_images_regex', 'background-image\s*:\s*(?<attr>\s*url\s*\((?<url>[^)]+)\))\s*;?' );
if(! is_string( $regex ) ) {
    $regex =  'background-image\s*:\s*(?<attr>\s*url\s*\((?<url>[^)]+)\))\s*;?' ;
}
			if ( ! preg_match( "#$regex#is", $element['styles'], $url ) ) {
```
And add this logic in [Avada thirdparty class](https://github.com/wp-media/wp-rocket/blob/58784bd05e3919595ed453870f69aeb3f580e8b2/inc/ThirdParty/Themes/Avada.php) and subscribe it to the event `rocket_lazyload_bg_images_regex`:
```php
public function fix_regex_lazyload_bg_images( $regex ) {
   return '(--awb-)?' . $regex;
}
```


## Estimate effort
Effort `XS`

**Comment by DahmaniAdame** [comment]
@piotrbak not tested. The customer won't give access to staging, and we don't have the latest version of Avada around. 
I tested the same code without using Avada. The regex worked and I couldn't see any issue while testing.
Here is a quick template for QA to validate if the latest Avada can't be tested: 
```
<div style="--awb-background-image:url('https://picsum.photos/500/500');--awb-background-size:cover;" ></div>
<div style="background-image:url('https://picsum.photos/500/500');--awb-background-size:cover;" ></div>
```
@CrochetFeve0251 sounds good 👍

> Avada needs to be doing something to display the background.

About the markup, they are using variables and making them look like prefixed properties.
