### ISSUE TITLE
Add a filter to disable the removal of non accessed URLs from the wpr_rocket_cache table

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5657]
**Is your feature request related to a problem? Please describe.**
The case is a customer who wants to keep all the URLs in the cache, even if they are not accessed during the past 30 days

**Describe the solution you'd like**
Add a boolean filter to turn on/off this feature here
https://github.com/wp-media/wp-rocket/blob/301916893739f108e87b181b52485a917df7abe2/inc/Engine/Preload/Cron/Subscriber.php#L227

or here:
https://github.com/wp-media/wp-rocket/blob/301916893739f108e87b181b52485a917df7abe2/inc/Engine/Preload/Database/Queries/Cache.php#L290

**Describe alternatives you've considered**
- A cron-triggered snippet to update the `last_accessed` row to the current DateTime to all `completed` URLs.
But this is an overkill and requires too much writing into the database 
- unhook rocket_preload_clean_rows_time_event / remove_old_rows
-
**Additional context**
ticket; https://secure.helpscout.net/conversation/2096924274/388876?folderId=2683093

**Comment by small-fork** [comment]
I hope it's okay to add a note here. I'm okay with randomly-visited URLs dropping off after 30 days, but wanting to be sure that all the URLs in specified sitemaps (which I've listed using the function **wprocket_preload_only_sitemaps_multiple()** ) never disappear from the cache database and are thus always preloaded.

However, if it's too complicated to parse that, then disabling the 30 day removal for _everything_ is workable. I can always manually exclude any that are outside of the sitemaps that I do want to have "expire."

If this comment/addition isn't appropriate to have added here, feel free to remove! Thank you!

**Comment by CrochetFeve0251** [comment]
## Scope a solution
To fix this we could make the period variable. for that we could add  filter that returns a string. 
If the string is empty or wrong then we disable the cleaning.

To implement  that we would do the following:
- In the class [CRON Subscriber](https://github.com/wp-media/wp-rocket/blob/301916893739f108e87b181b52485a917df7abe2/inc/Engine/Preload/Cron/Subscriber.php#L226) we will add the following logic: 
```php
	public function remove_old_rows() {
                 $delay = (string) apply_filters( 'rocket_preload_delay_delete_non_accessed'  , '1 month');
		if( $delay === "" ) {
                   return;
               }
                $this->query->remove_all_not_accessed_rows( $delay );
	}
```
- The Query class from Cache  we will add the following logic:
```php
	/**
	 * Remove all completed rows one by one.
	 *
	 * @return void
	 */
	public function remove_all_not_accessed_rows( string $delay ) {
		$rows = $this->get_old_cache( $delay );
```
and
```php

	/**
	 * Get all preload caches which were not accessed in the last month.
	 *
	 * @return array
	 */
	public function get_old_cache(string $delay) : array {
		// Get the database interface.
		$db = $this->get_db();

		// Bail if no database interface is available.
		if ( empty( $db ) ) {
			return [];
		}

		$prefixed_table_name = $db->prefix . $this->table_name;
		$query               = "SELECT id FROM `$prefixed_table_name` WHERE `last_accessed` <= date_sub(now(), interval $delay)";
		$rows_affected       = $db->get_results( $query );

		return $rows_affected;
	}
```
## Effort

Effort `S`

**Comment by thinkjarvisdesignandmarketing** [comment]
This thread seems to focus on changing the value. How do we disable this feature completely?

rocket_preload_delay_delete_non_accessed set to infinite? So that it doesnt remove anything.
