### ISSUE TITLE
Add a filter to control DB_NAME use in WP Rocket

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5658]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some database implementations, like [LudicrousDB](https://github.com/stuttter/ludicrousdb), will remove `DB_NAME` from WordPress. 

This will cause features on WP Rocket relying on it to fail (Preload, Remove Unused CSS, and Database optimization). 

To cover these cases, we can use a custom constant for the `DB_NAME`, like `WP_ROCKET_DB_NAME` that we declare in our configuration with a filter to make it possible to change when needed, shipped with `DB_NAME` as the default value.

**To Reproduce**
1. Remove `DB_NAME` from `wp-config.php`
2. See error

**Expected behavior**
We should make it possible to use customized database implementation that don't use `DB_NAME` to declare the database name.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2110764130/392349/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
