### ISSUE TITLE
Mandatory Cookie is missing in a specific scenario

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5659]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.3.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Mandatory Cookie is not set when activating WCML (while using Geolocation mode) after Activating WPR

**To Reproduce**
- WCML set to Geolocation and plugin disabled
1. Install and activate WPR
2. Activate WCML
3. Check the config file => Only Dynamic cookie is set

**Expected behavior**
Mandatory cookie shall be set as same as with Dynamic cookie

**Additional context**
- It was already mentioned [here](https://github.com/wp-media/wp-rocket/pull/4462#issue-1037704557)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
