### ISSUE TITLE
Cached pages reference files in the cache/busting folder that do not exist as they are not dynamically created

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#5661]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
Yes, 3.12.4 is installed
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a JS or CSS file is dynamically created, a version is stored in the cache/busting directory, but when the file is not dynamically created, i.e. the original file is a .js or a .css it is not copied into this directory but the cache files, even in this case refer to the file in the cache/busting directory generating a 404 error. 

**To Reproduce**
I've created a Stagecoach site to reproduce the issue, credentials to access the Stagecoach site are in the ticket: https://secure.helpscout.net/conversation/2110300150/391550?folderId=2952229
Steps to reproduce the issue: 

1. On WP Rocket dashboard on Advance rules, remove the exclusion from cache of the page /articles/create
2. Logged in WordPress go to tropical.wpsc.dev/articles/create
3. Click on Article content you will see an 404 error trying to access the file /wp-content/cache/busting/1/wp-includes/js/tinymce/themes/modern/theme.min.js but this file is not created dynamically. 

**Expected behavior**

1. Logged in WordPress go to tropical.wpsc.dev/articles/create
2. Click on Article content (sometime you have to click several times there are some 404 errors, these are also present on not cached version and customer is aware of that). 
3. After some time the Tinymce editor will load with an error, but it will load. Image: https://i.imgur.com/Ikr2ywh.png

**Screenshots**
On ticket's note is a video showing the issue. 

**Additional context**
Caching for logged-in WordPress users must be enabled

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We won't fix this one.

 The customer is using very old legacy file that should not be used anymore:
`wp-includes/js/tinymce/wp-tinymce.php?ver=2.0.0-dev1`

In this file we can see:
```
/**
 * Not used in core since 5.1.
 * This is a back-compat for plugins that may be using this method of loading directly.
 */
 ```
Excluding it using this plugin solves the issue:
https://docs.wp-rocket.me/article/927-prevent-static-file-creation-for-dynamic-css-js

And customer is doing it on his own with the functions.php file:
```
wp_enqueue_script( 'tinymce_js', includes_url( 'js/tinymce/' ) . 'wp-tinymce.php', array( 'jquery' ), '2.0.0-dev1', true );
```
