### ISSUE TITLE
Apply filter to optionally prevent /cache/.htaccess

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#567]
https://github.com/wp-media/wp-rocket/blob/0981f97abcb694b2f5fc3e7974735b22ea583efa/inc/functions/files.php#L257-L264

Apparently `Options -Indexes` can cause issues on some hosting environments. One customer says his host does not support Apache options, but has indexes disabled globally instead.

So we could apply a filter inside the `if` statement in order to enable customers with this issue to prevent WP Rocket from generating the .htaccess file in the cache folder:

```php
if ( $is_apache && apply_filters( 'rocket_init_cache_dir_generate_htaccess', true ) ) {
    // etc.
}
```

Customers who had issues with that file could then continuously prevent it with a simple MU plugin setting above filter to `false`:

```php
add_filter( 'rocket_init_cache_dir_generate_htaccess', '__return_false' );
```

**Comment by GeekPress** [comment]
We can use this code to fix it easily without needed to use a filter => https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess#L508

**Comment by glueckpress** [comment]
@GeekPress / @Tabrisrp Just FYI, according to customer feedback, Host Europe have a service plan where `mod_autoindex ` is enabled, but options are still not allowed, so our .htaccess file still causes an error 500.
