### ISSUE TITLE
Cancel AS preload pending jobs after truncating cache table

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5674]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are not canceling AS pending jobs with actions that truncate the Cache table i.e change permalinks

**To Reproduce**
Precondition:
- Set preload batch size to 300 for example to notice the problem
```
add_filter( 'rocket_preload_cache_pending_jobs_cron_rows_count', function( $urls ){
return 300;
} );
```

1. Enable preload on large site => many preload pending jobs are there in the actions table
2. Clear and preload the cache
3. Use a custom sitemap
```
function add_my_sitemap() {
return ['https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/files/custom-sitemap.xml'];
}
```
add_filter( 'rocket_sitemap_preload_list', 'add_my_sitemap', PHP_INT_MAX );
6. change permalinks
7. check the cache table and AS actions table => URLs of pending AS are added once completed with completed status

**Expected behavior**
Cancel AS preload pending jobs when truncating the cache table

**Screenshots**

https://user-images.githubusercontent.com/76941962/211803860-18216d0e-22f7-4751-afa7-636949635c2d.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
### Identify the root cause ✅
Like @Mai-Saad stated, we are not cancelling pending AS jobs.
### Scope a solution ✅
We can simply add `$this->queue->cancel_pending_jobs();` in https://github.com/wp-media/wp-rocket/blob/1f3262948c55ef8c5e01c11e4221ae554e5d5735/inc/Engine/Preload/Subscriber.php#L234
### Estimate the effort ✅
[XS]
