### ISSUE TITLE
Improve WPX hosting compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5675]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
For WPX hosting we're removing the expires rules for HTML. That's not the best we could do, as it introduces some side effects (HTML content not refreshed)

**To Reproduce**
1. Go to WPX website
2. Check the headers for HTML request
3. It's set to 1 month

**Expected behavior**
The best we can do for compatibility is to make sure that HTML document will have the following headers:
- public
- max-age=0
- s-maxage=3600
- stale-while-revalidate=21600

**Additional context**
At this point we can easily remove the part that's deleting our expires rules:
https://github.com/wp-media/wp-rocket/blob/5ca5716ea7452077c8c4d784619bb8950d4019da/inc/ThirdParty/Hostings/WPXCloud.php#L48-L53
The browsers will use the correct max-age header again.

We also need to add the following Cache-Control headers:
- s-maxage=3600
- stale-while-revalidate=21600
So their CDN can take advantage of it. The values were consulted with Aleksandar, their Systems Administrators Team Lead.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Like @piotrbak stated, we will remove the method:
https://github.com/wp-media/wp-rocket/blob/5ca5716ea7452077c8c4d784619bb8950d4019da/inc/ThirdParty/Hostings/WPXCloud.php#L48-L53 and replace the hook - `rocket_htaccess_mod_expires` with `rocket_htaccess_files_match` then hook a new method to return the updated headers:

```
$headers = 'Header append Cache-Control "s-maxage=3600, stale-while-revalidate=21600, public"' . PHP_EOL;
$headers .= 'Header unset Last-Modified';
preg_replace( '@Header append Cache-Control "public"\nHeader unset Last-Modified@', $headers, $rules );
```
Update tests

### Estimate the effort
[S]
