### ISSUE TITLE
The Update button is active on the Edit screen in Gutenberg when no changes were made to page/post

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#5679]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.4
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
When WP Rocket is enabled, the Update button is "active" on the Edit screen in Gutenberg when no changes were made to the page/post. This is because the `aria-disabled` attribute is set to `false`.

The default value when WP Rocket is not enabled is `aria-disabled="true"`. 

This is confusing at times, when the user wants to rely on the "update" button telling them, whether they changed (accidentally) the page contents or not.

**To Reproduce**
1. Make sure the WP Rocket is installed and active
2. Open page/post in default block (Gutenberg) editor
3. See the issue

**Expected behavior**
The Update button in Gutenberg editor shouldn't be "active" if no changes were made to the post/page.

**Screenshots**
https://i.imgur.com/wXIEZ0L.png

**Additional context**
Related Ticket: https://secure.helpscout.net/conversation/2115477983/393220

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
