### ISSUE TITLE
ONE - RocketCDN's CTA banner is displayed in the CDN tab

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5682]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.12.5`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

In `3.12.5` and for customers on ONE's network we still display RocketCDN's banner:
![image](https://user-images.githubusercontent.com/193660/212838204-8bf56c31-1fb5-4f76-b711-f64a2a1763ba.png)

**To Reproduce**

1. Install WP Rocket `3.12.5` on our ONE test site.
2. Go to the CDN tab.
3. See the banner.

**Expected behavior**

RocketCDN's banner should not be displayed; the same goes for its subscription status in WP Rocket's dashboard.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
We can add a filter that will filter the display of the banner here:
https://github.com/wp-media/wp-rocket/blob/6b45039ddac481a58f5ce4a4f55d5d9815600b2c/inc/Engine/CDN/RocketCDN/NoticesSubscriber.php#L173
`if ( ! apply_filters( 'rocket_display_rocketcdn_cta', true ) )`
Then we use this new filter in the one.com thirdparty class https://github.com/wp-media/wp-rocket/blob/develop/inc/ThirdParty/Hostings/OneCom.php

Add tests also.
### Estimate the effort ✅
[XS]
