### ISSUE TITLE
When I adding params on URL with JS code, lazyload (image, js) not working

### ISSUE THREAD

**Issue by HuynhLeQuocBao** [wp-media/wp-rocket#5683]
**Before submitting an issue please check that you’ve completed the following steps:**
- My version:  3.12.4
- Used the search feature to ensure that the bug hasn’t been reported before: Yes

**Describe the bug**
This issues happen when I add params on the URL with JS code, lazyload (image, js) is not working. I use window.history.pushState() to add params on the URL. But when I remove it, this feature worked normal.

**Expected behavior**
This feature woking normally.

**Screenshots**
![without params](https://user-images.githubusercontent.com/88766396/212877850-0d982b31-ab11-428b-874d-9048ad90ac7b.png)
![with params](https://user-images.githubusercontent.com/88766396/212878136-e8b7a555-2ea5-4cca-a4c9-e68c712b01c4.png)
![my code](https://user-images.githubusercontent.com/88766396/212878649-79c7bef3-1d70-4476-ad9c-20e006d0a6b8.png)

**Comment by WordPresseur** [comment]
@HuynhLeQuocBao Pages with Query strings are excluded by default from cache and optimizations. Please [check this documentation for more details](https://docs.wp-rocket.me/article/971-caching-query-strings). If it's not this case, please [contact our support team](https://wp-rocket.me/support/) to help you with this.
