### ISSUE TITLE
Blank admin after updating to 3.12.5

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5685]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
There is a small trend of tickets where customers get a blank admin page, or loading admin, after updating to 3.12.5

One of them mentioned a 504 gateway timeout error.

Tickets: 
https://secure.helpscout.net/conversation/2127435436/395540
https://secure.helpscout.net/conversation/2127451155/395543
https://secure.helpscout.net/conversation/2127497243/395557

Asked for credentials. 

**To Reproduce**
_To be defined_

**Expected behavior**
_To be defined_

**Screenshots**
_To be defined_

**Additional context**
_To be defined_

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by sergiobellini** [comment]
Same here!

**Comment by alfonso100** [comment]
Hi @sergiobellini
Can you please open a support ticket so we can investigate it?

thanks

**Comment by nanedi** [comment]
+1 Same here!

**Comment by DahmaniAdame** [comment]
Fix tested and working in one case.
