### ISSUE TITLE
Chinese letters (bushes) after enable WP-ROCKET

### ISSUE THREAD

**Issue by futurowebpl** [wp-media/wp-rocket#5690]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When I enable WP-ROCKET, Chinese characters appear - similar to coded modules (IonCube) if IonCube is disabled...

The problem exists on the stores where I have the plugin installed:
https://wordpress.org/plugins/complianz-gdpr/

Maybe modules are conflicting?

**To Reproduce**
1. Install WP-ROCKET
2. Install Complianz
3. Enable WP-ROCKET
4. Go to Homepage (as a user, not as an administrator)
5. See Chinese letters (bushes).

**Expected behavior**
Working plugin

**Screenshots**
![chinese-letters](https://user-images.githubusercontent.com/43948137/213123291-0445b001-e9a7-406e-afe0-5e99b636d70f.png)

**Additional context**
I reported the problem through support but no one is responding.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by girlie** [comment]
_Closing as it's already being handled by the support team._
