### ISSUE TITLE
Preload - Old sitemaps are still preloaded

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5692]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: ✅
- Used the search feature to ensure that the bug hasn’t been reported before: ✅

**Describe the bug**
Changing/delete a sitemap won't affect what is preloaded if the items are already stored on the preload table. The issue is worsened when using a database caching like Memcached or Object Cache.

**To Reproduce**
1. Create Sitemaps in Yoast plugin
2. Launch the preload
3. Delete some of these sitemaps
4. Launch the preload again
5. Old sitemap still preloaded

**Expected behavior**
Old sitemaps which might include media links, tags, categories, etc. shouldn't be preloaded anymore because they can really put a load on the server and preloads pages that don't need to be preloaded at all.

In order to re-fetch the sitemap, we can change permalinks so cache table is truncated and new map is used or maybe consider adding a button to flush the preload table without having to change the permalink again.

We should also flush Memcached or Object Cache accordingly.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1673863634402199
Tickets: 
- https://secure.helpscout.net/conversation/2111259948/392432?folderId=1213662
- https://secure.helpscout.net/conversation/2119756156/394081?folderId=1213662

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
