### ISSUE TITLE
Can't add the @Keyframes animation in css into safe list in the feature Remove Unused CSS

### ISSUE THREAD

**Issue by HuynhLeQuocBao** [wp-media/wp-rocket#5693]
**Before submitting an issue please check that you’ve completed the following steps:**
- Version: 3.12.4
- Used the search feature to ensure that the bug hasn’t been reported before: Yes

**Describe the bug**
The feature Remove Unused CSS removed animation on my website and I want to add @Keyframes animation in css into safe list in this feature but it not working.

**Expected behavior**
I want the animation to work normally as before applying the feature Remove Unused CSS.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @HuynhLeQuocBao thanks for creating the issue. Have you already contacted our support team to investigate this further?

**Comment by HuynhLeQuocBao** [comment]
Hello @piotrbak , I fixed the problem. I write keyframe CSS inline, not using CSS files.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
