### ISSUE TITLE
Relative path aren't concatenated with new minification process

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#570]
Issue can be viewed in live here:
http://smashingcoding.com/

with the file: `<script type='text/javascript' src='/wp-content/themes/uncode/library/js/min/ai-uncode.min.js' id='uncodeAI' data-home='/' data-path='/' data-breakpoints-images='258,516,720,1032,1440,2064,2880'></script>`

**Comment by Tabrisrp** [comment]
Fixed in alpha1
