### ISSUE TITLE
Preload - Re-fetch the sitemap in different scenarios

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5703]
**Is your feature request related to a problem? Please describe.**

This is to discuss future enhancements of the Preload feature about cases where re-fetching the site's sitemap would offer an overall better experience with the feature.

1. There are occasions where we'll need to re-fetch the site's sitemap and preload any URLs that are there but are not in the `wpr_rocket_cache` table.

Currently, when removing exclusions from "Never Cache URLs" the "affected" URLs will be preloaded when they are accessed by visitors, i.e. they won't be preloaded. When using `(.*)` to exclude several URLs this has an even greater impact.

2. In cases, like the one in #5692, we would need to fetch the sitemap and remove the URLs that aren't there.

3. When sitemap-generating plugins, e.g. Yoast, regenerate the sitemap.

4. When adding/removing URLs to/from the preload exclusion text area.

**Describe the solution you'd like**

We could:
1. Re-scan the sitemap on specific occasions, e.g. when "Never Cache URLs" change.
3. Add missing URLs to the `wpr_rocket_cache` table. In cases such as #5692 we should remove the additional URLs and "ban" them from being preloaded.
5. Preload the missing URLs.

**Describe alternatives you've considered**

To avoid having to create plugin-specific compatibility, e.g. with Yoast, for re-fetching the sitemaps on specific occasions, we could run a cron job daily or weekly (this could be filterable) to fetch the sitemap. Then either add or remove URLs from the cache table.

**Comment by Mai-Saad** [comment]
Sometimes re-fetching the sitemap after changing permalinks is not working. (needs further investigation with WP sitemap , home page URLs, SEO plugin, custom sitemap)

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
