### ISSUE TITLE
Add Option to Remove the Delay JavaScript execution's Internet Explorer Compatibility Inline Script

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#5705]
**Is your feature request related to a problem? Please describe.**
Delay JavaScript execution's Internet Explorer compatibility script may be slightly problematic. So far, customers have mentioned SEO preferences, HTML size/tidiness, and Internet Explorer minimum usage as reasons.

**Describe the solution you'd like**
Add an option or filter to remove this inline script from the source code. 

**Describe alternatives you've considered**

- Automatically remove the inline code if Internet Explorer is excluded from the cache with Never Cache User Agent(s).
- Add an option to move the position of the inline script in the HTML, to the place customer prefers.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2129269917/395933?folderId=2675957
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1674226165466019

**Comment by DahmaniAdame** [comment]
> Add an option or filter to remove this inline script from the source code.

It should be the other way around: 
- Deactivating it by default
- Add a filter for the few customers that might need it back for whatever reason

There is no need to add it to the UI for simplicity and to avoid it being re-enabled back for the wrong reasons (mainly for the "more boxes checked, more performance mindset" 😅).

**Comment by GeekPress** [comment]
This is a typical «Decision, not options ». A UI is overkill for this need.

**Comment by jeriss-cloud-center** [comment]
Could we at least get a "filter" for those who want to override this by code, while waiting for a deeper code change?

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
