### ISSUE TITLE
Defer JS compatibility with a mailchimp script

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5706]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A JS error caused by Defer JS triggers other issues on several elements on the page.

```
<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js" defer></script><script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[6]='SALUTATION';ftypes[6]='radio';fnames[3]='FIRSTNAME';ftypes[3]='text';fnames[5]='NAMEPREFIX';ftypes[5]='text';fnames[2]='LASTNAME';ftypes[2]='text';fnames[1]='ACCOUNTID';ftypes[1]='text';fnames[4]='SIGNUP';ftypes[4]='text'; /*
 * Translated default messages for the $ validation plugin.
 * Locale: NL
 */
    $.extend($.validator.messages, {
        required: "Dit is een verplicht veld.",
        remote: "Controleer dit veld.",
        email: "Vul hier een geldig e-mailadres in.",
        url: "Vul hier een geldige URL in.",
        date: "Vul hier een geldige datum in.",
        dateISO: "Vul hier een geldige datum in (ISO-formaat).",
        number: "Vul hier een geldig getal in.",
        digits: "Vul hier alleen getallen in.",
        creditcard: "Vul hier een geldig creditcardnummer in.",
        equalTo: "Vul hier dezelfde waarde in.",
        accept: "Vul hier een waarde in met een geldige extensie.",
        maxlength: $.validator.format("Vul hier maximaal {0} tekens in."),
        minlength: $.validator.format("Vul hier minimaal {0} tekens in."),
        rangelength: $.validator.format("Vul hier een waarde in van minimaal {0} en maximaal {1} tekens."),
        range: $.validator.format("Vul hier een waarde in van minimaal {0} en maximaal {1}."),
        max: $.validator.format("Vul hier een waarde in kleiner dan of gelijk aan {0}."),
        min: $.validator.format("Vul hier een waarde in groter dan of gelijk aan {0}.")
    });}(jQuery));var $mcj = jQuery.noConflict(true);</script><!--End mc_embed_signup-->
```

The related console error is the following:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'messages')
    at (index):1848:26
    at (index):1866:9
(anonymous) @ (index):1848
(anonymous) @ (index):1866
```

Issue fixed by excluding:
```
/wp-includes/js/jquery/jquery.min.js
s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js
```
It requires jQuery to be excluded as a dependency. Which will require a compatibility file.

**To Reproduce**
1. Add Mailchimp form with the validation scripts
2. Use Defer JS
3. See the error

**Expected behavior**
The validation scripts should work out of the box.

**Screenshots**

**Additional context**
Related HS: https://secure.helpscout.net/conversation/2129738437/396023

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@worldwildweb Is it related to any plugin or it's a manually added script?

**Comment by lukecav** [comment]
It looks like it is related to this Mailchimp plugin.
MC4WP: Mailchimp for WordPress
https://wordpress.org/plugins/mailchimp-for-wp/

**Comment by worldwildweb** [comment]
@piotrbak 
> @worldwildweb Is it related to any plugin or it's a manually added script?

no Mailchimp plugins installed

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
