### ISSUE TITLE
Defer JS compatibility with Ashade theme masonry gallery

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5707]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version (unrelated to a specific version)
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the Ashade theme masonry gallery is used while Defer JS is used, the dependency related to the Masonry library is not met. 

![image](https://user-images.githubusercontent.com/1289174/213861822-2bba89d8-238c-4b48-b2d2-a39e117a9b92.png)

It results in the following error: 

```
Uncaught TypeError: $this.masonry is not a function
    at HTMLDivElement.<anonymous> (core.js?ver=1674148543:190:179)
    at Function.each (jquery.min.js?ver=3.6.1:2:3003)
    at s.fn.init.each (jquery.min.js?ver=3.6.1:2:1481)
    at ashade.init (core.js?ver=1674148543:190:56)
    at HTMLDocument.<anonymous> (core.js?ver=1674148543:314:42)
    at e (jquery.min.js?ver=3.6.1:2:30038)
    at t (jquery.min.js?ver=3.6.1:2:30340)
```

And for the gallery to not load images.

Excluding the following fixes the issue: 

```
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/masonry.min.js 
```
**To Reproduce**
1. Use Ashade theme "Albums Listing" template
2. Enabled Defer JS without any exclusions
3. See error

**Expected behavior**
The gallery should work out of the box. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2114966099/393119/

This one will require excluding the jQuery library as well which will require a compatibility file. 

We can look for if the template `Ashade Albums Listing` is being used using the `get_page_template_name()` function. 

Alternatively, `get_page_template_slug()` can be used to check if `page-albums.php` is being used. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
