### ISSUE TITLE
Compatibility between One.com CDN and security plugins

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5708]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
One.com's CDN is limited in rewriting directories different than `wp-content`. When using security plugins that are changing default `wp-content` path, files won't be hosted on the edges while we'll still rewrite them. It can cause broken layout.

**To Reproduce**
1. Go to One.com website 
2. Install WP Hide plugin or similar and change `wp-content` path
3. See error

**Expected behavior**
Until this is handled properly on One.com's end, we'll disable our CDN compatibility when detecting that `wp-content` directory path is changed.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
@piotrbak 
So here we need to completely disable our CDN when wp-content directory is changed? or do u think it'd be better to only exclude this new directory from our CDN?

**Comment by piotrbak** [comment]
We need to disable it completely. It's an edge case and most likely nothing will be rewritten correctly anyways
