### ISSUE TITLE
wpDiscuz needs a separate cache for mobile

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5719]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.5.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
wpDiscuz uses `wp_is_mobile()` to control adding some assets to the front end. 

Here is an example related the Rick Editor settings:

![image](https://user-images.githubusercontent.com/1289174/214810903-4b99fdfc-7990-44bd-b304-04162aaf0331.png)

File: `/class.WpdiscuzCore.php:1235`.

Extend of the customizations done depending on the setting:

```
$loadQuill = $this->options->form["richEditor"] === "both" || (!wp_is_mobile() && $this->options->form["richEditor"] === "desktop");
if (!$loadQuill) {
    $combo_js = "-no_quill";
    $combo_css = "-no_quill";
}
if ($loadQuill) {
    wp_add_inline_script("wpdiscuz-combo-js", $this -> options -> editorOptions(), "before");
}
if ($loadQuill) {
    wp_register_style("quill-css", plugins_url(WPDISCUZ_DIR_NAME. "/assets/third-party/quill/quill.snow$suf.css"), null, "1.3.6");
    wp_enqueue_style("quill-css");
    wp_register_script("quill", plugins_url("/assets/third-party/quill/quill$suf.js", __FILE__), ["wpdiscuz-cookie-js"], "1.3.6", true);
    wp_enqueue_script("quill");
    wp_add_inline_script("quill", $this -> options -> editorOptions(), "before");
    wp_register_script("wpd-editor", plugins_url("/assets/js/wpd-editor$suf.js", __FILE__), ["quill"], "1.3.6", true);
    wp_enqueue_script("wpd-editor");
}
if (!$loadQuill && $this -> options -> form["enableQuickTags"]) {
    wp_enqueue_script("quicktags");
    wp_register_script("wpdiscuz-quicktags", plugins_url("/assets/third-party/quicktags/wpdiscuz-quictags.js", __FILE__), [$this -> options -> general["loadComboVersion"] ? "wpdiscuz-combo-js" : "wpdiscuz-ajax-js"], $this -> version, true);
    wp_enqueue_script("wpdiscuz-quicktags");
}
```

There are other occurrences controlling the output depending on if `wp_is_mobile()` is set or not. 

This could break features on the page and render the wrong style.

Plugin URI - `wpdiscuz/class.WpdiscuzCore.php`.

I will leave it to QA to see if we should target locating specific features through a compatibility file or just add `wpDiscuz` as part of the [get_mobile_plugins()](https://github.com/wp-media/wp-rocket/blob/1246d406f0523799a5d084a94e61fabf33b3405f/inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php#L331-L353) list.

**To Reproduce**
1. Enable wpDiscuz
2. Enable the above-mentioned setting as an example
3. Compare the output of a page desktop vs. mobile to see that different assets are loaded

**Expected behavior**
We should accommodate scenarios where wpDiscuz will output additional or different assets on the frontend. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2132824521/396631?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@piotrbak [get_mobile_plugins()](https://github.com/wp-media/wp-rocket/blob/1246d406f0523799a5d084a94e61fabf33b3405f/inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php#L331-L353) can be a good candidate to move to the Dynamic Lists. We can keep plugins requiring further conditions, like the `Jetpack`, either there or on their respective compatibility files when applicable. 
Should open a GH request for that?

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The problem was easy to reproduce.

## Identify the root cause
The root issue is that we need force `do_caching_mobile_files` when the plugin is activated to prevent having same cache for mobile and desktop.

## Scope a solution
A solution would be to create a new Thirdparty class that will add callback if it detects the constant `WPDISCUZ_DIR_NAME`.
We will create a callback to `'option_' . rocket_get_constant( 'WP_ROCKET_SLUG' )` and link it with the following logic:
```php
public function force_mobile_cache( $options ) {
$value['do_caching_mobile_files']    = true;
return $options;
}
```
## Estimate the effort
Effort `S`
