### ISSUE TITLE
Specially named background images are not loaded when lazyload is applied

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5721]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark:  `3.12.5.2` 
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

Background images with a filename like `(plaska)+ziemia_xD flat earth (lol).PNG` are not picked up correctly when lazyload is applied to them. In the previous example, only this `(plaska` is used as the filename which results in an error 404.

**To Reproduce**
1. Upload an image named `(plaska)+ziemia_xD flat earth (lol).PNG` on the site. _Do not use the Media Library._
2. Use it as a `background-image` to a `div`.
3. Enable lazyload.
4. See the error `404` on the front end.

**Expected behavior**

Images including characters such as `()+` should be properly detected.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Duplicated with https://github.com/wp-media/wp-rocket/issues/4443

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
