### ISSUE TITLE
remove <noscript> tag automatically generated for each image

### ISSUE THREAD

**Issue by balrogmedia** [wp-media/wp-rocket#5723]
Hello everyone,

I've tried to find a solution online but I didn't find one.

I use wp-rocket with lazyload, but I don't want the <noscript> tag automatically generated for each image
![image](https://user-images.githubusercontent.com/98542232/215092373-7a615403-f8bb-4dea-82e5-383d39037174.png)

is there a way of removing it, please?
Thank you in advance for your precious help!

**AC**
1. Add filter to remove the `<noscript>` tag from the lazyload markup

**Comment by piotrbak** [comment]
@balrogmedia Hello and thanks for creating the issue. We don't have any clean way of doing that, could you tell us what's the reason behind removing compatibility code?

**Comment by balrogmedia** [comment]
I think it is unnecessary and just makes the site heavier, but mainly because web accessibility evaluation tools don't like it, for example https://wave.webaim.org/, so I think there is an accessibility issue with the noscript tag.

**Comment by sandyfzu** [comment]
The user opened a ticket, and it was closes in favor of this feature request

They provided this to check the results of their website's test: https://wave.webaim.org/report#/https://casinoonlinesoldiveri.it/
Screenshot: https://prnt.sc/hBH51ZR7tJPk


I think it should be fine to provide at least a filter (if possible) for the users who want to disable this, since it can save some HTML size if the site has a lot of images.

**Comment by DahmaniAdame** [comment]
Normally, if the original image is accessible, that same image wrapped inside the `noscript` tag would be accessible as well. 

Checking the site on Chrome and Firefox accessibility audits didn't show any issues with the `noscript` tag related to the fallback images. 

Using an actual screen reader like `NVDA` doesn't show the issue as well.

Checking the error on Wave, the `noscript` inner code is not rendered correctly, while it is for other faulty elements: 

```
<img src="https://placehold.jp/3d4070/ffffff/150x150.png" alt="Image description">
<noscript>
&lt;img src=&quot;https://placehold.jp/3d4070/ffffff/150x150.png&quot; alt=&quot;Image description&quot;&gt;
</noscript>
<img src="https://placehold.jp/3d4070/ffffff/150x150.png">
Noscript element
<noscript>
&lt;img src=&quot;https://placehold.jp/3d4070/ffffff/150x150.png&quot;&gt;
</noscript>
```

It's turned into HTML entities. Possibly what prompts Wave to think the content is not accessible as it doesn't see the image's markup correctly.

Removing the `noscript` will guarantee that images will go missing on browsers with JavaScript disabled. 

If that's an acceptable risk, having a filter will make sense. 

Otherwise, turning on the native lazyload would be a wiser option if passing the Wave audit specifically is a must, as other audits seem to be fine with how the fallback image is implemented inside the `noscript` tag - https://docs.wp-rocket.me/article/1292-chrome-native-lazyload

**Comment by balrogmedia** [comment]
Thank you for your answer!

is it correct to have this first quotation marks here?
![image](https://user-images.githubusercontent.com/98542232/215427093-d2a67a2c-6880-4ee4-af38-fde8bcb95f0e.png)

If it is correct, then shouldn't the quotation marks " within the tags be replaced by apostrophes '?

That would fix i guess?

**Comment by DahmaniAdame** [comment]
> is it correct to have this first quotation marks here?

Yes. But it's Chrome's doing, not WP Rocket :) 

When JavaScript is enabled, Chrome adds the `"` on the inner HTML of the `noscript` tag.

If you check the source code, test with JavaScript deactivated, or test on Firefox, you will notice that the `"` marks are not there. 

> If it is correct, then shouldn't the quotation marks " within the tags be replaced by apostrophes '?

We don't control the `"` mark added by Chrome. And on the browser itself, it's not an issue. 

But it could be problematic if Wave parses the content of the `noscript` as text, which it seems like it does (it turns everything into HTML entities).

**Comment by balrogmedia** [comment]
I understand.

I'm not sure what to do. I would like my site to be 100% accessible on Wave, but Lazy load is also important.

Thank you anyway!

**Comment by DahmaniAdame** [comment]
@balrogmedia keep the lazyload on, and use the following helper plugin to enable the browser's native lazyload :)

Images will be lazyloaded, there won't be any `noscript` added, and it will work in all browsers regardless of whether JavaScript is deactivated.

**Comment by balrogmedia** [comment]
Which plugin Dahmani?

**Comment by DahmaniAdame** [comment]
@balrogmedia this one - https://github.com/wp-media/wp-rocket-helpers/raw/master/lazyload/wp-rocket-enable-native-lazyload/wp-rocket-enable-native-lazyload.zip

Reference - https://docs.wp-rocket.me/article/1292-chrome-native-lazyload

**Comment by vladyslav-storozhenko** [comment]
Hello, I would also like to add to this conversation, as we also had similar request from our SEO specialists to remove this noscript tag, as it makes search bots think that the image is duplicated (it's alt attribute is saved in cache, that's what triggered SEO specialists). Given that there is no way at all to control this part of lazyload's behavior, we were forced to use another plugin

**Comment by balrogmedia** [comment]
hi,

I seem to have removed the >noscript> tag by removing the following lines

private function noscript( $element ) {
		return '<noscript>' . $element . '</noscript>';

on file wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php

I have no idea if I shouldn't, but it seems working. 

What do you think about it? thanks

**Comment by balrogmedia** [comment]
Nah, forget that. It was giving some issues.

Any chance to have a disable button form the WProcket team?

**Comment by justingolden21** [comment]
We would also like this for our website. We have some pages with many images, and have an excessive DOM size partially due to these tags. We're trying to improve performance and ideally wouldn't choose between excessive DOM size and compressed images. Thanks!

**Comment by iserejatoje** [comment]
You need to add a filter in `functions.php` to disable these tags:

`
    // Lazyload fix
    function nonoscript_lazyload($in) {
        return str_replace( '<noscript><style>.lazyload{display:none;}</style></noscript>', '', $in ) ;
    }
    add_filter( 'autoptimize_filter_imgopt_lazyload_cssoutput', 'nonoscript_lazyload');
`

**Comment by balrogmedia** [comment]
Thank you!
 
I've tried but I see no difference in the code.
 
Your code is beyond my skills so I dont know what is the issue. But if in future you get it working don't hesitate to let me know please
 
Thank you!

**Comment by hanna-meda** [comment]
@Tabrisrp, thank you for this. 
Testing the safeguard of the filter, we get a fatal error when using `null` as the wrong input value on filter. Bringing it back into in-progress. 
 

>  [30-Jul-2024 11:02:08 UTC] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Dependencies\RocketLazyload\Image::noscriptEnabled(): Return value must be of type bool, null returned in /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:553
> Stack trace:
> #0 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(41): WP_Rocket\Dependencies\RocketLazyload\Image->noscriptEnabled()
> #1 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(343): WP_Rocket\Dependencies\RocketLazyload\Image->lazyloadImages()
> #2 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Media\Lazyload\Subscriber->lazyload()
> #3 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/plugin.php(205): WP_Hook->apply_filters()
> #4 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters()
> #5 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer()
> #6 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/functions.php(5420): ob_end_flush()
> #7 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/class-wp-hook.php(324): wp_ob_end_flush_all()
> #8 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
> #9 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/plugin.php(517): WP_Hook->do_action()
> #10 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/load.php(1270): do_action()
> #11 [internal function]: shutdown_action_hook()
> #12 {main}
>   thrown in /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php on line 553

**Comment by hanna-meda** [comment]
@Tabrisrp, we now have this kind of error only by simply activating the filter with either valid bool values `true` or `false`
Branch currently on rocketlabsqa. To reproduce this enable LL feature, activate filter and visit any page with LL images (i.e https://rocketlabsqa.ovh/imgs-all-kind-ll/)

> [31-Jul-2024 08:28:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WP_Rocket\Dependencies\RocketLazyload\wpm_apply_filters_typed() in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:553
Stack trace:
#0 /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(41): WP_Rocket\Dependencies\RocketLazyload\Image->noscriptEnabled()
#1 /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(343): WP_Rocket\Dependencies\RocketLazyload\Image->lazyloadImages()
#2 /var/www/rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Media\Lazyload\Subscriber->lazyload()
#3 /var/www/rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters()
#5 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buf in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php on line 553

**Comment by remyperona** [comment]
Did you run `composer update` to add the new dependency to your installation?

**Comment by hanna-meda** [comment]
I did not. That was it. Thank you!
