### ISSUE TITLE
Cleanup failed RUCSS after a short period of time

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5724]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.5.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When RUCSS fails for a specific URL after 3 retries, the only scenario where it will be renewed is when: 
- RUCSS table is truncated in full
- When the page the page Used CSS is manually cleared
- When the old Used CSS is deleted after 1 month taking `last_accessed` as a reference

If none of the action is taken, the page will remain without RUCSS for a long time for no specific reason. 

Here is an example: 

![image](https://user-images.githubusercontent.com/1289174/215260651-71bb1522-7373-4e6a-bc0a-5283ce58ab68.png)

The URL didn't have its Used CSS renewed after 7 days, and still going without taking any action.

Having a background process that clears failed RUCSS in a shorter period, like in 3 days, for example, will give a better RUCSS ratio.

The 3 days should be enough to get the reason why it failed for a specific URL when debugging. 

A temporary fix is creating a cron and make it trigger the following file on the root folder of a WordPress installation: 
https://gist.github.com/DahmaniAdame/3a2a550b4a201ad39516d842207c884e

**To Reproduce**
1. Push RUCSS to fail in a URL
2. See how long it takes for it to be cleared if no action was done

**Expected behavior**
We should clear failed RUCSS in a shorter period of time to get a better RUCSS ratio. 

**Screenshots**

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2135056677/397038/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Thanks for creating this one. 

Let's go with the 3-days cron approach, we'll need to make sure set the item to pending and reset all necessary columns like we do when purging Used CSS for the URL [manually](https://github.com/wp-media/wp-rocket/blob/55847cedd8a6085b251ced952a1f31e8977da626/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L765).

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
The problem was reproduced.

### Identify the root cause ✅
We are not clearing failed RUCSS

### Scope a solution ✅
We can add a new interval for 3 days after this line https://github.com/wp-media/wp-rocket/blob/136d94b9ea6eb33ba33c3e2143a623b4b37d86cc/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L147-L150

```
$schedules['rocket_clear_rucss_failed_jobs'] = [
	'interval' => 259200,
	'display'  => esc_html__( 'WP Rocket clear Remove Unused CSS failed jobs', 'rocket' ),
];
```

Then hook cron schedule method to init https://github.com/wp-media/wp-rocket/blob/136d94b9ea6eb33ba33c3e2143a623b4b37d86cc/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L49
`wp_schedule_event( time(), 'rocket_clear_rucss_failed_jobs', 'rocket_clear_rucss_failed_jobs' );`

Next we'll create a new method to delete all rows with failed status in `WP_Rocket\Engine\Optimization\RUCSS\Database\Tables::UsedCSS`.
```
public function remove_failed_rows() {
    $db = $this->get_db();
 
    if ( empty( $db ) ) {
	    return false;
    }
   
    $prefixed_table_name = $this->apply_prefix( $this->table_name );
    return $db->query( "DELETE FROM `$prefixed_table_name` WHERE status = 'failed'" );
}
```
Next we'll add a new method to delete all failed rows using this new method in `WP_Rocket\Engine\Optimization\RUCSS\Admin::Database`
```
public function remove_failed_rows() {
    if ( ! $this->rucss_usedcss_table->exists() ) {
	    return false;
    }

    return $this->rucss_usedcss_table->remove_failed_rows();
}
```

Then finally we create the new method that we will hook to the new cron event - `rocket_clear_rucss_failed_jobs`.
```
public function cron_remove_failed_jobs() {
    $this->database->remove_failed_rows();
}
```

### Estimate the effort ✅
[S]

**Comment by engahmeds3ed** [comment]
> @DahmaniAdame Thanks for creating this one.
> 
> Let's go with the 3-days cron approach, we'll need to make sure set the item to pending and reset all necessary columns like we do when purging Used CSS for the URL [manually](https://github.com/wp-media/wp-rocket/blob/55847cedd8a6085b251ced952a1f31e8977da626/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L765).

@piotrbak 
May I know why do u need to make the cron interval to be 3 days? I believe having this interval to be 1 day would be better if the site has too much failures.

Also another thing, in this PR we made the CRON interval changeable using a filter but the deletion interval is static to be 3 days here: 
https://github.com/wp-media/wp-rocket/pull/5739/files#diff-c7548ff352554baf25f17c8c079956c2d4a67683e52bae90ba1fb451db4e72faR423
do we need to make it filterable also?

**Comment by DahmaniAdame** [comment]
3 days will help give us enough time to see if there is an issue. But one day will do as well. 

Regardless of the default value we will go for, a filter to control the value is needed to help set it to a short period to speed up the clearing process or set an extended period to monitor and investigate issues when needed.
