### ISSUE TITLE
Expiring soon users from 2022 see incorrect auto-renewal price on dashboard banner

### ISSUE THREAD

**Issue by adinaWP** [wp-media/wp-rocket#5734]
**Bug details:** 
Customer has the latest version of the plugin installed - 3.12.5.2 . 
The license was purchased on February 10th 2022 and it will expire soon - on the 10th of February 2023. 

The auto-renewal banner with the countdown timer on the plugin dashboard is displaying an incorrect renewal rate for the customer: $59 instead of $49. 

Customer profile: https://wp-rocket.me/wp-admin/user-edit.php?user_id=230864

![image](https://user-images.githubusercontent.com/66075301/216031046-5e04c8dd-a2b1-4b42-9f5a-2038bba5c6ab.png)

**To Reproduce**
Steps to reproduce the behavior (if it's a general issue - to be confirmed!):
1. Install a license registered in 2022 on a website; 
2. Adjust the license's expiration date to expire in the next few days days;
3. Check the expiring soon banner on the plugin dashboard to observe incorrect renewal price. 

**Expected behavior**
The renewal rates for customers registered in 2022 should be $49 for Single, $99 for Plus and $249 for Infinite. 

**Additional context and related issues**
- The translations for the pricing line are missing as well: https://github.com/wp-media/wp-rocket/issues/5735
- The banner should not be displayed if the customers have auto-renewal on: https://github.com/wp-media/wp-rocket/issues/4641

**Comment by piotrbak** [comment]
It looks like we received incorrect data from the API:
![image](https://user-images.githubusercontent.com/26767037/216604510-5cbb9a20-c72e-4bf2-8c79-1f13a876ed38.png)

We need to make sure that the banner **is not** displayed if the data is malformed:
1. `date_created` is 0
2. `has_auto_renew` is empty

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
We can use the `WP_Rocket\Engine\License\API\UserClient` class in `WP_Rocket\Engine\License\Renewal` and do a check in https://github.com/wp-media/wp-rocket/blob/60b76bc8bc9a366bf5b9644894df8203bba103fd/inc/Engine/License/Renewal.php#L56 to bail out if `date_created` returns `0`

```
if ( 0 === $this->user_client->get_user_data()->date_created ) {
    return;
}
```

### Estimate the effort ✅
[XS]

Do we need to flush the transient in case this is a randomly malformed data from the API? @piotrbak

**Comment by piotrbak** [comment]
@jeawhanlee no, we don't need to remove it. It would cause unnecessary load on our licensing server

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the PR, works fine for a valid date of expiring soon user (single/plus/infinite) GF/GM/NGF. However, if the auto-renew is empty while the creation date is valid, we still display the banner => it shouldn't be displayed in this case as per discussion with @piotrbak . can you please check?
