### ISSUE TITLE
Missing translation for the pricing mentioned on the expiring soon countdown banner

### ISSUE THREAD

**Issue by adinaWP** [wp-media/wp-rocket#5735]
**Bug details:** 
A countdown timer is displayed on an expiring soon banner for customers when the license is about to expire (30 days). The last line of the banner mentions the price, but this was displayed in English, not in German, so our DE translation is missing (possibly others as well).

![image](https://user-images.githubusercontent.com/66075301/216031046-5e04c8dd-a2b1-4b42-9f5a-2038bba5c6ab.png)

Customer has the latest version of the plugin installed - 3.12.5.2 . 
The license was purchased on February 10th 2022 and it will expire soon - on the 10th of February 2023. 

**To Reproduce**
1. Install a license registered in 2022 on a website; 
2. Adjust the license's expiration date to expire in the next few days days;
3. Check the expiring soon banner on the plugin dashboard to observe the missing translation in available languages. 

**Expected behavior**
"Renew before it is too late, you will only pay [PRICE]!" should be translated to the available languages.  

**Additional context and related issues**
- The renewal price displayed is incorrect as well: https://github.com/wp-media/wp-rocket/issues/5734
- The banner should not be displayed if the customers have auto-renewal on: https://github.com/wp-media/wp-rocket/issues/4641

**Comment by Presskopp** [comment]
Looks like the string just was not translated at that point of time. Should not happen again.
