### ISSUE TITLE
Broken layout caused by Themify Ultra performance optimization and RUCSS

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#5736]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 3.12.5.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The Themify Ultra theme has a file performance optimizations built in. The _Concate CSS_ optimization in the theme does the same thing as _Combine CSS files_ in WP Rocket.

When this optimization is used with Remove Unused CSS, it causes broken layout on the front-end, and safe listing CSS doesn't resolve the issue.

The only solution is to disable Concate CSS in Themify theme settings https://i.imgur.com/0sz5zCc.png

**To Reproduce**
1. Install Themify Ultra theme. The _Concate CSS_ optimization is enabled by default in theme settings.
2. Enable Remove Unused CSS, and check the broken layout after Used CSS is generated

**Expected behavior**
The _Concate CSS_ optimization in Themify Ultra theme should be disabled when Remove Unused CSS is enabled.

**Screenshots**
The _Concate CSS_ optimization in the theme [https://i.imgur.com/cyEU0OI.png](https://i.imgur.com/cyEU0OI.png).

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. When RUCSS is enabled, their concatenation can't happen on the frontend for mobiles and desktops
2. When RUCSS is disabled, their concatenation work correctly for all devices
3. It needs to be reflected in the UI (making sure that `Disable Concate CSS` is checked)

**Comment by CrochetFeve0251** [comment]
## Scope a solution
To disable the Concat CSS when RUCSS is enabled we will have to create a thirdparty class.
We will load event from the 3rd party class when the theme active or the parent is `Themify Shoppe`.
Then we will check if RUCSS is disabled with`rocket_disable_rucss_setting`.
If it enabled then we will define the constant `THEMIFY_DEV` and then use the filter with the following logic to disable contac CSS:
```php
add_filter('themify_save_data', function ($value, $old) {
    $value['setting-dev-mode-concate'] = false;
    return $value;
}, 10, 2);
```
 Edit: I saw I forgot the initial state in my grooming.

To fix the initial state we can add a callback to `admin_init`: 
```php
function change_inital_state() {
   $data = themify_get_data();
   if(key_exists('setting-dev-mode-concate', $data) || ! $data['setting-dev-mode-concate'] ) {
     return;
   }
   $data['setting-dev-mode-concate'] = false;
   themify_set_data($data);
}
```

## Estimate the effort
Effort `S`

**Comment by armanogan** [comment]
Hey @CrochetFeve0251,

I am developer from Themify. The solution you have added is breaking our themes and don't allow users to disable dev mode. How can I help you to solve the conflict,maybe add some filters that you can use to solve it?

**Comment by piotrbak** [comment]
@armanogan Sorry for the troubles.

We need to make sure that whenever our Remove Unused CSS feature is enabled, CSS features on your end are disabled. Could you please provide us the latest version of your theme (if so, please reach me here piotr[at]wp-media.me)?

We'll recheck what's going on there.

**Comment by armanogan** [comment]
Hey @piotrbak,

Sorry for delay response, could you please share the email where to send the latest version of the theme?

Enabling "Dev mode" has performance penalty for our theme, we can't do it, even if "Remove Unused CSS" feature is enabled  on your end.

Our theme logic is that it's loading only that css modules ,that are used in the page, which is similiar your feauture, that is why maybe you will ignore it?

**Comment by piotrbak** [comment]
Hello @armanogan please use piotr[at]wp-media.me.

@CrochetFeve0251 mentioned that it's not possible to disable your CSS features without enabling the dev mode. Could you confirm that?
