### ISSUE TITLE
background-image: url() resulting in 404 error

### ISSUE THREAD

**Issue by Eroan** [wp-media/wp-rocket#5737]
When combining/minifying a CSS file that includes a background-image with an empty url() value, WP Rocket rewrites the path to something like background-image: url(/path/to/my/theme). While an empty url() does not trigger any error, this is not the case with a path like the one rewritten.

This leads to a 404 error when files are combined/minified.

1. Add a CSS declaration with an empty url() value in the theme or plugin file called in frontend
2. Activate combination/minification in WP Rocket
3. Check the 404 error in the Devtools network tab or console

Expected behavior:
The CSS declaration should simply be copied as it is or even better, removed since not useful and extra bytes of CSS.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
