### ISSUE TITLE
Limit where Mixpanel loads in the admin

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5738]
We had a case where there was a conflict with Mailpoet due to their use of Mixpanel conflicting with ours. 
Ideally we would avoid loading Mixpanel everywhere. We may need to use their API instead. 

The original case is documented here: 
https://github.com/mailpoet/mailpoet/issues/4712

Slack conversation with more specifics: 
https://wp-media.slack.com/archives/C43T1AYMQ/p1675284268690819

Original ticket: 
https://secure.helpscout.net/conversation/2140281494/398104?folderId=377611

**Comment by engahmeds3ed** [comment]
https://github.com/mailpoet/mailpoet/issues/4712 is fixed and merged today and I believe this will be released in their next release.

**Comment by piotrbak** [comment]
@engahmeds3ed What would be your proposal for enhancement here? 🤔

**Comment by engahmeds3ed** [comment]
this is released here: https://github.com/mailpoet/mailpoet/releases/tag/4.7.0
I don't think that we need to do anything from our side, just ask affected customers to update to this release or above.
We can't control their code.

**Comment by piotrbak** [comment]
Thanks @engahmeds3ed closing it then.
