### ISSUE TITLE
Additional Delay JavaScript Execution exclusions for Uncode theme

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5743]
When Delay JavaScript Execution is active, Uncode's AJAX product filter does not work, even after interaction.
There is no console error, but the overlay doesn't work when clicked. In the ticket we had, the issue was specifically on mobile. 

These are the additional files which need to be excluded: 
/wp-content/themes/uncode/library/js/app.min.js
/wp-content/themes/uncode/library/js/plugins.min.js

Ticket: https://secure.helpscout.net/conversation/2141854867/398426?folderId=377611
Example of how it should work: https://jumpshare.com/j/UA7amWkv4ojlmE5ioFxh
Without exclusions, the overlay did not appear when clicked.

**Comment by piotrbak** [comment]
We'll need to make sure that both of them are not combined/minified and not delayed.

As per ticket, Defer JS exclusion isn't necessary, but it should be tested.

**Comment by CrochetFeve0251** [comment]
## Scope a solution

For that we will have to create a new third party subscriber for that theme using the string `uncode` to know if the current theme is that one.
Then if it the case it will register to the `rocket_delay_js_exclusions` filter with the following callback:
```php
public function exclude_delay_js($excluded) {
$excluded[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/app.min.js' );
$excluded[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/plugins.min.js' );
return $excluded;
}
```
Then we will have to create tests related to that class.

## Estimate effort
Effort `S`
