### ISSUE TITLE
Compatibility with Master Popups

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5744]
Master Popups: 
https://codecanyon.net/item/masterpopups-multipurpose-popup-plugin-for-wordpress-with-easy-email-marketing-integration/20142807

Exclusions are needed for Delay JavaScript Execution and Load JavaScript Deferred. 

This console error appears:
```
Uncaught ReferenceError: MppCountdown is not defined
    at HTMLDocument.<anonymous> (master-popups-countdown.js?ver=3.8.7:1:175)
    at e (jquery.min.js?ver=3.6.1:2:30038)
    at t (jquery.min.js?ver=3.6.1:2:30340)
```

Requires Defer JS exclusion:

/wp-includes/js/jquery/jquery.min.js
/wp-content/plugins/master-popups/assets/public/js/master-popups-libs.min.js

And Delay JavaScript Execution exclusion:

/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
/wp-content/plugins/master-popups/assets/public/js/master-popups-libs.min.js

Ticket: 
https://secure.helpscout.net/conversation/2141854867/398426?folderId=377611

**Comment by piotrbak** [comment]
Added Delay JS exclusion to backend
