### ISSUE TITLE
Compatibility with Ohio theme's dark mode

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5745]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When RUCSS is used with the [Ohio theme](https://ohio.clbthemes.com/) while their dark mode is enabled and their `Color Mode Switcher`, the change of the color scheme is not persistent. 

![image](https://user-images.githubusercontent.com/1289174/217175709-255022be-49d1-423d-9c07-59d99b2983a6.png)

The theme will add the following cookie that holds the current state 

`ohio-switcher-state`

It can be used with our Dynamic Cookie cache to allow a persistent color when the color is switched. 

If RUCSS is enabled, the following will need to be safelisted: 
```
(.*).dark-scheme
```
They have the following method that will return true if the `Color mode switcher` is enabled:

```
OhioOptions::get('page_dark_mode_switcher', false)
```

**To Reproduce**
1. Enable Ohio dark mode + color mode switcher
2. See that the color scheme won't be persistent if the color is changed on cached pages

**Expected behavior**
WP Rocket should not prevent switching color schemes from staying persistent.

**Screenshots**
Added to the description.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2141213673/398294?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by cerkes78** [comment]
Color switcher option is not valid for frontpage.
i have disabled switcher but it still there.

![Image](https://github.com/user-attachments/assets/72fefe39-90c1-4c46-957f-4ad05808046c)
