### ISSUE TITLE
Compatibility with Blocksy Theme

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#5748]
**Before submitting an issue please check that you’ve completed the following steps:**
✅ Made sure you’re on the latest version (3.12.5.3)
✅ Used the search feature to ensure that the bug hasn’t been reported before

Compatibility with Blocksy Theme:
https://wordpress.org/themes/blocksy/

Many things don't work including menu popups and mini cart slider, and had 'WP is not defined' console error. I'm not completely sure if the console error is related specifically to Blocksy or not.

Exclusions needed for the Delay JavaScript Execution option to resolve the issues:

```
/wp-content/themes/blocksy/static/bundle/main.js
/wp-includes/js/dist/api-fetch.min.js
/wp-includes/js/dist/hooks.min.js
/wp-includes/js/dist/i18n.min.js
```

With the above exclusions, the user confirmed everything worked okay.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@joejoe04 I wasn't able to reproduce it on clean Blocksy theme

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
