### ISSUE TITLE
Missing "Need Help?" beacon links in the Add-ons tab

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5750]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.12.5.3`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

On WP Rocket's settings page, we are using HelpScout's beacon URLs to link to our documentation:
![image](https://user-images.githubusercontent.com/193660/218022985-2b057147-0586-4759-ba03-dfe1e634e992.png)

 This is not the case for the Add-ons tab. 

For the Varnish and WebP add-ons, there are inline links to our documentation.
For the Cloudflare and Sucuri add-ons, we display beacon doc links after they have been activated and their specific settings are accessed.

**To Reproduce**

1. Visit the add-ons tab.
2. No beacon links will be there.

**Expected behavior**

For consistency throughout the plugin and to make the discovery of docs easier for our customers the "Need Help?" links should be added in the Add-ons tab as well.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
