### ISSUE TITLE
Delays JS - Console error when Avada's lazyload is enabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5752]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.12.5.3`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When Avada's lazyload feature is enabled alongside Delay Javascript Execution a `jQuery not defined` error appears in the JavaScript console.

Their `lazysizes.js` library is excluded from Delay JS execution. That depends on `jQuery` and if this is delayed the error will occur.

**To Reproduce**

1. Enable Avada's lazyload feature (Avada > Options > Performance).
2. Enable WP Rocket's Delay JS Execution.
3. Visit the front end and check the console for the error.

**Expected behavior**

No console error should appear when Avada's lazyload is used with Delay JS Execution.

**Additional context**

In our Avada compatibility file, we can exclude the `jQuery` library from Delay JS Execution when either of the following two features is enabled:
![image](https://user-images.githubusercontent.com/193660/218080240-199d7b02-6d06-4e6a-8510-f7baa636eaeb.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@vmanthos This sounds like a duplicate of:
https://github.com/wp-media/wp-rocket/issues/5294

There were a lot of problems after excluding jQuery:
https://github.com/wp-media/wp-rocket/issues/5294#issuecomment-1210253786

What do you think?

**Comment by vmanthos** [comment]
It is! 
I'm sorry I missed that. :sweat_smile: 

> There were a lot of problems after excluding jQuery

Closing this one and we can discuss this in https://github.com/wp-media/wp-rocket/issues/5294
