### ISSUE TITLE
Switch post to draft will run rocket_clean_home_feeds() also feeds cache is disabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5753]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.5.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
clean home's feed runs although cache feeds isnot enabled

**To Reproduce**
Precondition:
- enable WPR debug `define( 'WP_ROCKET_DEBUG', true); `
1. Install  and activate WP Rocket - feeds caching is disabled by default.
2. Add log statements in `rocket_clean_home_feeds()` here `inc/functions/files.php`
3. edit any page and switch it to draft
4. Check the log.

**Expected behavior**
We shouldn't run `rocket_clean_home_feeds() ` while feeds caching is disabled 

**Additional context**
- If instead of step 3 we clear post cache or edit the content in it, we won't run `rocket_clean_home_feeds() ` which is correct
- Thanks to @engahmeds3ed for listing the parts using `rocket_clean_home_feeds()`  function 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
## Reproduce the problem :heavy_check_mark: 

## Identify the root cause
in `rocket_clean_home_feeds` we need to check first if `cache_feed` option is active or not first

## Scope a solution
add the `cache_feed` check in  `rocket_clean_home_feeds`
```
	if ( ! get_rocket_option( 'cache_feed', false ) ) {
		return;
	}
```

create tests

## Estimate the effort
Effort `S`
