### ISSUE TITLE
Missing admin notifications when Redis Object cache plugin is enabled

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5754]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✓ (3.12.5.3)
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
[Redis Object Cache](https://wordpress.org/plugins/redis-cache/#description) plugin is preventing the admin notifications we display after changes have been applied to the WPR’s settings from being displayed.

Regarding the DB optimization, the details are not listed after optimizing, but also ROC seems to prevent any transient from being cleared.

**To Reproduce**
1. Install Redis Object cache.
2. Apply changes to the WP Rocket’s settings and/or optimize the database.
3. See that there is no “settings saved” message nor the details of the database optimization displayed.

**Expected behavior**
Admin notifications should be dissplayed no matter if object cache or Redis Object Cache is enabled.

**Screenshots**
Screencast for reference: https://share.getcloudapp.com/NQu46OY4
As you can see, Redis is not even connected on my testing site, but still the issue appears.

**Additional context**
@DahmaniAdame has confirmed this doesn’t only affect WP Rocket’s notifications: _other notifications from other themes/plugins were hidden, too, until the Object Cache was flushed or the ROC is deactivated._

Related ticket: https://secure.helpscout.net/conversation/2132737204/396617

Similar cases:
https://secure.helpscout.net/conversation/1463301776/250418
https://secure.helpscout.net/conversation/1030621131/136407

Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1676038156794189

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
