### ISSUE TITLE
If <title> tag is missing from the source, Used CSS code is not delivered, causing broken layout

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#5755]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :white_check_mark: 
- Used the search feature to ensure that the bug hasn’t been reported before :white_check_mark: 

**Describe the bug**
We had [an edge case](https://secure.helpscout.net/conversation/2151142819/400302/) where site was broken. After checking the source code, we noticed there is no CSS code/files at all. Also, the <title> tag was missing from the source.

We need <title> tag in order to know where to add Used CSS code. This kind of situations prevents us to do that.

Checking W3's Validator and HTML specs, it might [not be obligated](https://html.spec.whatwg.org/multipage/semantics.html#the-head-element) to have <title> tag in the head, so we might have more cases like this.

**To Reproduce**
1. Make sure you don't have <title> tag defined in the source code
2. Activate "Remove Unused CSS" feature in WP Rocket Settings (Files Optimization tab)
3. Check pages as not logged in user.
4. See error, page should be broken and there should not be any CSS code/files in the source

**Expected behavior**
Used CSS should be generated and delivered to the source code.

**Comment by mostafa-hisham** [comment]
We are using the end of title tag `</title>` to make Used CSS load first in case the customer wants to override it
for example, using our filter to exclude CSS files from RUCSS and load it directly.

we also use the end of the title tag `</title>` in Combine CSS and google fonts optimizations

I checked the [head specs document](https://html.spec.whatwg.org/multipage/semantics.html#the-head-element) and 
and I think the only case that a head tag can be without a title tag is 

> If the document is an iframe srcdoc document or if title information is available from a higher-level protocol

I also but an HTML document without a title and got an error in the w3 validator

![image](https://user-images.githubusercontent.com/29744252/219532389-4d432983-2f0d-4f7a-bfde-214e5d9b87d2.png)

**Comment by piotrbak** [comment]
@mostafa-hisham Not sure what's the use case for ` if title information is available from a higher-level protocol`. Would preventing from removal CSS from the source when `</title>` is missing add much complexity?

**Comment by engahmeds3ed** [comment]
I discussed this with @mostafa-hisham few days ago and we agreed on that we simply need not to remove styles from the page if there is no title tag there and this will solve the issue of broken layout without touching the html itself, what do u think @piotrbak ?

**Comment by piotrbak** [comment]
@engahmeds3ed Yes, this is perfect solution
