### ISSUE TITLE
PHP Warning:  Undefined array key when rollback any theme

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5762]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.5.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When rollback any theme while WPR is enabled, we will get the following warning
`[15-Feb-2023 09:08:58 UTC] PHP Warning:  Undefined array key "themes" in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/common/purge.php on line 563`

**To Reproduce**
1.[ Rollback ](https://wordpress.org/plugins/wp-rollback/)plugin is enabled
2. WPR is enabled
3. Try to rollback any theme
4. Check debug.log

**Expected behavior**
No warning when rollback

**Additional context**
- tested on Nginx/Apache 
- same warning exists with 3.11.5

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
## Reproduce the problem :heavy_check_mark: 

## Identify the root cause
`$hook_extra` array can not hold a `theme` key

## Scope a solution
We need to check if the hook array contains 'theme' key

```
	if ( ! isset ($hook_extra['themes']) || ! is_array( $hook_extra['themes'] ) ) {
		return;
	}
```

## Estimate the effort
Effort `XS`
