### ISSUE TITLE
Sanitize rocket_clean_user path the same way as we create the path when caching

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5764]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.5.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When User Cache is used, and the username is an email, or uses capital letters as part of the username, purging the cache using `rocket_clear_user` will result in the user cache not getting cleared. 

The reason why it's happing is the sanitization we use while creating the user cache folder: 

https://github.com/wp-media/wp-rocket/blob/332e28b3d0439a02b538c54c2abe550016509e3c/inc/classes/Buffer/class-cache.php#L540

We are only allowing letters, numbers, and `_` and `-` on the following regex: 

https://github.com/wp-media/wp-rocket/blob/332e28b3d0439a02b538c54c2abe550016509e3c/inc/classes/Buffer/class-cache.php#L743

We are not doing the same here: 

https://github.com/wp-media/wp-rocket/blob/332e28b3d0439a02b538c54c2abe550016509e3c/inc/functions/files.php#L891

Which results in a mismatch here: 

https://github.com/wp-media/wp-rocket/blob/332e28b3d0439a02b538c54c2abe550016509e3c/inc/functions/files.php#L907

**To Reproduce**
1. Enable User Cache
2. Use a user with an email as a username
3. See if the user cache is cleared when calling `rocket_clean_user`.

**Expected behavior**
We should sanitize the User Cache folder the same way everywhere as required. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2154203299/400843/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by alfonso100** [comment]
An update from this customer: 

>  It's not a problem just with uppercase in username but also with **email as username**, because it's not sanitizing and not removing cache at all for these users.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
The problem was reproduced easily

### Identify the root cause ✅
Exactly like @DahmaniAdame stated, The sanitization we apply when we create the user cache folder is not being applied when we retrieve the folder to be deleted, causing an invalid path.

### Scope a solution ✅
We can simply replicate the same sanitization used in creation by replacing https://github.com/wp-media/wp-rocket/blob/332e28b3d0439a02b538c54c2abe550016509e3c/inc/functions/files.php#L891 with the below:
```
$cache_dir = $parse_url['host'] . '-' . $user_key . '*' . $parse_url['path'];
$cache_dir = preg_replace( '/[^a-z0-9_\-]/', '', strtolower( $cache_dir ) );
$root           = rocket_get_constant( 'WP_ROCKET_CACHE_PATH' ) . $cache_dir;
```

### Estimate the effort ✅
[XS]
