### ISSUE TITLE
WebP addon better keep previous status when deactivate compatibility plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5774]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.6
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When deactivating compatibility plugin that serves WebP, our addon isn't dimmed but in off mode even if it was on mode before serving WebP at compatibility plugin

**To Reproduce**
1. Site has WebP versions of images using imagify (not served by imagify)
2. Enable WebP Addon
3. Serve WebP from imagify
4. deactivate imagify or disable serving WebP there

**Expected behavior**
WebP addon is on as it was before serving from the other plugin

**Additional context**
- Already the same on 3.12.5

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
