### ISSUE TITLE
Exclude the `canonical` `link` from the "Relative protocol" setting to avoid SEO issues

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5781]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.5.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the setting under the Cloudflare add-on `Relative protocol` is used, we change the canonical URL from: 

`<link rel="canonical" href="https://domain.ext/">`

to

`<link rel="canonical" href="//domain.ext/">`

This will result Lighthouse to prompt the following recommendation when auditing the SEO part: 

```
Document does not have a valid rel=canonicalIs not an absolute URL (//domain.ext/)
```

Changing the following regex found here: 

https://github.com/wp-media/wp-rocket/blob/0dd1e1f144947ddded9d00b4a27f431d9b7d1848/inc/front/protocol.php#L28

to exclude the `canonical` `rel` will fix the issue. 

Something like the following should work: 

```
/(<(script|link|img|form)(?!.*?\bcanonical\b)([^>]*)(href|src|action)=[\"'])https?:\\/\\//i
```

**To Reproduce**
1. Enable the "Relative protocol" under Cloudflare add-on
2. Do an SEO audit on Lighthouse
3. See error

**Expected behavior**
There shouldn't be any results when the Relative protocol setting is enabled. 

**Screenshots**
N/A 

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
Ok
## Identify the root cause
Done by @DahmaniAdame 
## Scope a solution
The solution from @DahmaniAdame is valid but @piotrbak do you think we should make the regex more precise with a regex checking for `rel="canonical"` to prevent exclusion from `img` that possibly have a class contaning canonical?
## Estimate the effort
Effort `xs`
