### ISSUE TITLE
CSS / JS files not being combined

### ISSUE THREAD

**Issue by alvarotrigo** [wp-media/wp-rocket#5782]
Version 3.12.5.3 

**Describe the bug**

I'm using the default theme in WordPress: 
Twenty Twenty-Three 

And I've activated the checkboxes to combine CSS and JS:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1706326/221238424-becffae7-4dc6-4668-bec9-96c069a5f028.png">

However,  I can still see multiple files being present in my new blog posts:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/1706326/221238510-27293af7-4426-4883-9e97-aad7684ed2a8.png">

Can this be because this is a test blog living inside a password-protected filter with access?
Can this conflict with WP-Rocket permissions to write files inside this folder where WP lives?

**Expected behavior**
I would expect to see a single JS and CSS file being loaded to reduce the number of HTTP requests. 
(Although I'll A/B test this after, to see if parallel downloads are faster))

**Additional context**

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1706326/221239244-c7022520-89fc-4570-a131-8bdaf5eb676d.png">

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alvarotrigo** [comment]
Alright, I moved the blog outside the password protected folder and now it seems to be working just fine:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/1706326/221244422-8568fa69-d3c9-4b49-8c7b-6bdd8f5ce8e3.png">

It'd be nice to have this somewhere on the docs perhaps?

**Comment by camilamadronero** [comment]
Hello, @alvarotrigo.
Thanks for updating your issue!

We have [this article](https://docs.wp-rocket.me/article/99-pages-not-cached-or-minify-cssjs-not-working) you can use as reference for these cases. If you were using a different [Password Protected](https://wordpress.org/plugins/password-protected/) plugin, please contact the support team using the form in [our support page](https://wp-rocket.me/support). 

Thanks!
