### ISSUE TITLE
Ignore new Pinterest query string: ssp_iabi

### ISSUE THREAD

**Issue by blogtutor** [wp-media/wp-rocket#5783]
In the past ~2 weeks, Pinterest has started adding the `ssp_iabi` query string to some links.  They appear to be adding a Unix timestamp, so it'll look something like this, with the value changing every time:

https://domain.com/postname/?ssp_iabi=1677345794868

This is causing WP Rocket not to cache, and we're seeing high load (including some overload!) on some sites because of it. (It's also cluttering up Google Analytics reports...)

Can this query string be added to [the list of automatically ignored parameters](https://docs.wp-rocket.me/article/971-caching-query-strings#ignored-parameters) (along with Pinterest's `epik` and `pp`)?

**Comment by blogtutor** [comment]
Here are some examples from my GA: 

![image](https://user-images.githubusercontent.com/24479276/221371983-44148e95-91bb-4eae-af53-f434f5b6c2b6.png)

**Comment by ssaliimz** [comment]
Seen too. But I'm wondering if it  is the one causing my earnings to go down

**Comment by bboxfan57** [comment]
blogtutor, I noticed the query string as well, but I didn't know it was causing any cache issues. Thanks for posting this. Hopefully, this isn't a permanent change from Pinterest.

**Comment by bboxfan57** [comment]
> Seen too. But I'm wondering if it is the one causing my earnings to go down

Any reason this would cause earnings to decrease?

**Comment by Woorooo** [comment]
I have the same problem and my solution was to automatically strip urls from all ssp_iabi parameters via htaccess. 

This new parameters made Adsense earnings indeed drop because most of those urls are accessed only once. Adsense treats them as totally new urls and doesn't serve adds on them for at least a few views of the page. Not sure why, but that's how it works.

The real question is why that ssp_iabi parameter is being added in the first place and whether it is indeed being added by Pinterest. I couldn't find any information on this. If someone knows more please let me know.

**Comment by ssaliimz** [comment]
> automatically strip urls from all ssp_iabi parameters via htaccess.

How do you do that

**Comment by Woorooo** [comment]
```
RewriteCond %{QUERY_STRING} (.*)(^|&)ssp_iabi=([^&]+)(&|$)(.*)
RewriteRule ^ %{REQUEST_URI}?%1%5 [R=301,L]
```

You'll need to add this code to your htaccess file, however make sure you know what you're doing as editing htaccess can cause problems if not done right. Also, it may cause problems with Pinterest in case it's actually them adding this parameter.

**Comment by ssaliimz** [comment]
> ```
> RewriteCond %{QUERY_STRING} (.*)(^|&)ssp_iabi=([^&]+)(&|$)(.*)
> RewriteRule ^ %{REQUEST_URI}?%1%5 [R=301,L]
> ```
> 
> You'll need to add this code to your htaccess file, however make sure you know what you're doing as editing htaccess can cause problems if not done right. Also, it may cause problems with Pinterest in case it's actually them adding this parameter.

I did has you said, but still no change

**Comment by Woorooo** [comment]
> > ```
> > RewriteCond %{QUERY_STRING} (.*)(^|&)ssp_iabi=([^&]+)(&|$)(.*)
> > RewriteRule ^ %{REQUEST_URI}?%1%5 [R=301,L]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You'll need to add this code to your htaccess file, however make sure you know what you're doing as editing htaccess can cause problems if not done right. Also, it may cause problems with Pinterest in case it's actually them adding this parameter.
> 
> I did has you said, but still no change

Try using Chatgpt for troubleshooting, as it depends on your server setup, where you place the code and so on. It will point you in the right direction.

**Comment by ssaliimz** [comment]
> 

I used the [WP Htaccess Editor] to add the code, but have just checked again when the code is not there. I have no knowledge of coding that why I'm failing

**Comment by ssaliimz** [comment]
![Screenshot](https://user-images.githubusercontent.com/126371034/221766996-e7bff5d6-292a-49a4-a84b-c6823cecc1fb.png)

**Comment by Woorooo** [comment]
Try adding this code at the end of the page. DO NOT put it before the # END Wordpress

```
RewriteEngine On
<IfModule mod_rewrite.c>

RewriteCond %{QUERY_STRING} (.*)(^|&)ssp_iabi=([^&]+)(&|$)(.*)
RewriteRule ^ %{REQUEST_URI}?%1%5 [R=301,L]

</IfModule>
```

**Comment by hohomcmanaman** [comment]
> Try adding this code at the end of the page. DO NOT put it before the # END Wordpress
> 
> ```
> RewriteEngine On
> <IfModule mod_rewrite.c>
> 
> RewriteCond %{QUERY_STRING} (.*)(^|&)ssp_iabi=([^&]+)(&|$)(.*)
> RewriteRule ^ %{REQUEST_URI}?%1%5 [R=301,L]
> 
> </IfModule>
> ```

IS that safe?

**Comment by BradFD** [comment]
Seeing the same thing so I used a Cloudflare transform rule to strip it off. If you use Cloudflare APO that is way to do it, don't use an .htaccess rule or ignore at the WP Rocket level only, WP Rocket should definitely add it to the ignore list though.

**Comment by piotrbak** [comment]
The query string is added to the backend. Please update the lists to see get it inside the plugin:
https://docs.wp-rocket.me/article/1716-dynamic-exclusions-and-inclusions

**Comment by zoco1** [comment]
It seems that the fix is not working. The google analytics is full of ssp_iabi containing queries again. Any info on why this is still happening ? Thanks.
