### ISSUE TITLE
Prefetch DNS: Replace the relative protocol by https

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5785]
**Is your feature request related to a problem? Please describe.**
WP Rocket still Prefetch DNS with relative protocol because when the feature was released on X-Mas 2013, HTTP was the rule. 
HTTPS is now the rule and it is used [by 82% of websites](https://w3techs.com/technologies/details/ce-httpsdefault) and [95% of websites on Google use HTTPS](https://serpwatch.io/blog/ssl-stats/#https-usage-statistics). 
Users always use this feature to prefetch domains in HTTPS, so wouldn't it be better and safer to set HTTPS by default from now on?

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2165306244/404513?folderId=1213662

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
