### ISSUE TITLE
Add Delay Javascript Execution to WP_ROCKET_DEBUG log output

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5786]
**Is your feature request related to a problem? Please describe.**
Delay Javascript Execution optimization is not present in the WP_ROCKET_DEBUG, logger class output. 

**Describe the solution you'd like**
Add some log information to the WP_ROCKET_DEBUG output, this will be useful for the support team, to know which scripts are optimized by Delay Javascript Execution, if something is excluded per backend compatibility, admin UI , etc

**Additional context**

related slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1677693339218869

**Comment by piotrbak** [comment]
@alfonso100 Do you have in mind what exactly would be useful for Support Team?

**Comment by alfonso100** [comment]
I think could be useful to have something similar to the minify JS output.

If possible: 
- the list of scripts we detected. External and inline

and then

- delayed
- excluded by default exclusions (the ones from our backend)
- excluded by filter (the ones using our UI, or using the hook)

**Comment by CrochetFeve0251** [comment]
## Scope a solution
For excluded from  back end and filter with the current architecture that gonna be hard to detect.
However I can propose to show which exclusion applied for that script.

To create that solution we would need first to add the Logger as the dependency from the class and inject in from the ServiceProvider.

Then in the if [at line 198](https://github.com/wp-media/wp-rocket/blob/cf3fe446a6dcfd08c60c5b19907662c860f0cdff/inc/Engine/Optimization/DelayJS/HTML.php#L198) we would add the following logic to log excluded scripts:
```php
$this->logger->debug("Script {$matches[0]} excluded by $pattern");
```

On the [line 202](https://github.com/wp-media/wp-rocket/blob/cf3fe446a6dcfd08c60c5b19907662c860f0cdff/inc/Engine/Optimization/DelayJS/HTML.php#L202) we would add the following logic to log delayed scripts:

```php
$this->logger->debug("Script {$matches[0]} delayed");
```
## Estimate effort
Effort `XS`
