### ISSUE TITLE
Bad performance for Show tables on multisite

### ISSUE THREAD

**Issue by Rahe** [wp-media/wp-rocket#5792]
**Describe the bug**

You are calling "show tables" 3 times in a row on database.
On a large mutlisite database (1600 sites), this generates 1,5seconds of lag on **each** page load.

**To Reproduce**
1. Create a multisite with 1600 sites
2. Activate wp-rocket on each site
3. Activate preload feature
4. Load a page

**Expected behavior**
Show tables not called 3 times in a row on **each** page.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @Rahe and thanks for creating the issue.

Could you confirm that the problem is related to the following queries specifically?
![image](https://user-images.githubusercontent.com/26767037/222685609-7b4e46ed-862f-44bb-a850-f6bb49a4d015.png)

**Comment by Rahe** [comment]
Hello,

Exactly !

Nicolas,

**Comment by piotrbak** [comment]
This is not something that can be implemented in upcoming quarter. We'll reopen it when working on multisite.
