### ISSUE TITLE
WP Rocket break all websites on a multisite with subfolders configuration on all websites where WP Rocket isn't activate

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#58]
https://secure.helpscout.net/conversation/106524192/5319/

**Comment by Screenfeed** [comment]
Tested on a multisite containing 3 sites (as sub-folders, not sub-domains).
WP Rocket activated on the network, then on site 1, then on site 2: I couldn't reproduced the issue in those 3 cases.
