### ISSUE TITLE
PHP Deprecated: notices with PHP 8.2.3

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5801]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.6.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
PHP Deprecated notice  (count 150+) exists in debug.log while site is using PHP 8.2.3
`[08-Mar-2023 14:51:05 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 253`
`[08-Mar-2023 14:51:09 UTC] PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$id is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 266
`
**To Reproduce**
1. Website using PHP 8.2.3
2. Install and activate WPR
3. check debug.log

**Expected behavior**
no deprecated notice in debug.log

**Additional context**
- This doesn't exist with PHP 8.1.14

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@Mai-Saad Did you enable all WP Rocket's options + performed some operations like clearing the cache, etc.?

It would be good to resolve as many deprecations as possible here.

**Comment by Mai-Saad** [comment]
@piotrbak After enable all options and play around with admin bar, the deprecation logs will be 7K + (mostly for preload)
![Screenshot from 2023-03-14 08-57-56](https://user-images.githubusercontent.com/76941962/224920671-b2171f17-86d7-42df-b74d-42ac71b0d019.png)

**Comment by jeawhanlee** [comment]
Opened a [PR](https://github.com/berlindb/core/pull/155) at berlinDB that should fix this.

**Comment by vmanthos** [comment]
I got the same on a Multisite (8.2.1):
```
[27-Mar-2023 10:07:52 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /shared/httpd/multisite/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 254
[27-Mar-2023 10:07:52 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /shared/httpd/multisite/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 264
[27-Mar-2023 10:07:52 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /shared/httpd/multisite/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 273
```

There are more occurrences of the `${var}` pattern in  `wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php`.

**Comment by piotrbak** [comment]
@jeawhanlee In this PR let's update the berlinDB version.

**Comment by piotrbak** [comment]
@vmanthos Moved your comment to the new issue:
https://github.com/wp-media/wp-rocket/issues/5862

**Comment by piotrbak** [comment]
@jeawhanlee How it's going with this one?

**Comment by codemonkeynorth** [comment]
adding in case these have been missed

(Current version of WP Rocket: 3.8.2)

thanks
J

---

`Deprecated: Creation of dynamic property WP_Rocket\Engine\Preload\SitemapPreloadSubscriber::$options is deprecated in /wp-content/plugins/wp-rocket/inc/Engine/Preload/SitemapPreloadSubscriber.php on line 26`

`Deprecated: Creation of dynamic property WP_Rocket\Engine\Preload\SitemapPreloadSubscriber::$sitemap_preload is deprecated in /wp-content/plugins/wp-rocket/inc/Engine/Preload/SitemapPreloadSubscriber.php on line 27`

`Deprecated: Automatic conversion of false to array is deprecated in /wp-content/plugins/wp-rocket/inc/3rd-party/plugins/seo/yoast-seo.php on line 10`

**Comment by webenadam** [comment]
any news? still getting the same errors

**Comment by piotrbak** [comment]
@webenadam Please reach our Support Team to investigate further
