### ISSUE TITLE
Delay JavaScript execution not working on firefox

### ISSUE THREAD

**Issue by charls637** [wp-media/wp-rocket#5802]
Main menu is not working when activating that function on firefox, but it works on other browser.

**Comment by DahmaniAdame** [comment]
@charls637 would you mind opening a ticket so we can have a closer look?

**Comment by charls637** [comment]
@DahmaniAdame  I just did in https://wp-rocket.me/

**Comment by piotrbak** [comment]
@charls637 I'm going to close the issue. If it's still valid and not known one, we'll reopen it with all necessary details.
