### ISSUE TITLE
Add a compatibility with SiteGround CDN

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5803]
**Is your feature request related to a problem? Please describe.**
[SiteGround CDN](https://www.siteground.com/blog/siteground-cdn-is-now-officially-here) is a reverse proxy and set by default a 12 hours `max-age` header to the HTML document. This is incompatible with WP Rocket page caching. This value [can be over-written]( https://www.siteground.com/kb/siteground-dynamic-caching-configuration/#Supported_Caching_Headers) and WP Rocket's htaccess mod_expires rules force a `max-age:0` header.

But SiteGround CDN could keep this max-age and benefits if it would be also purged accordingly to WP Rocket's purge: https://www.siteground.com/kb/siteground-dynamic-caching-configuration/#Purging_the_Dynamic_Cache

**Describe the solution you'd like**
Purge SiteGround CDN along WP Rocket's cache without forcing a `max-age:0` header.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
