### ISSUE TITLE
Add a custom filter to add extra args to parse_sitemap for wp_safe_remote_get()

### ISSUE THREAD

**Issue by alexandre-tobia** [wp-media/wp-rocket#5804]
Hi !

**Is your feature request related to a problem? Please describe.**
My website is behind an nginx basic authentification with a login/password. When using the preload feature, the sitemap is not accessible with ```wp_safe_remote_get``` used in your code.

**Describe the solution you'd like**
In the file /inc/Engine/Preload/Frontend/FetchSitemap.php, function "parse_sitemap"  it would be awesome if you add a filter to add custom $args  to look like this 
```php $reponse = wp_safe_remote_get($url, $custom_args);```

This is what in want to achieve :
```
        $argsFromFilter = [
            'headers' => [
                'Authorization' => 'Basic ' . base64_encode("USER" . ':' . "PASSWORD")
            ]
        ];
        
        $response = wp_safe_remote_get($url, $argsFromFilter);
```
        
i'm not familiar how to create custom filter, so i've simulated the $argsFromFilter

Thanks a lot for your help !

**Comment by remyperona** [comment]
You can use the existing [http_request_args](https://developer.wordpress.org/reference/hooks/http_request_args/) filter to add basic auth to the already existing headers.

This will work for all requests, not only preload.

**Comment by alexandre-tobia** [comment]
Thanks a lot it works ! 

Have a nice day :)
