### ISSUE TITLE
WooCommerce pages not handled properly with preload in some cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5805]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.6.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Sometimes cart URL is added to cache table and isnot removed once processed but fail then switch to pending and so on.

**To Reproduce**
These Plugins were enabled:
![Screenshot from 2023-03-09 11-34-13](https://user-images.githubusercontent.com/76941962/224132655-f145f732-1597-4076-b49f-51dbff63e190.png)
![Screenshot from 2023-03-09 11-34-08](https://user-images.githubusercontent.com/76941962/224132663-c04bf355-91de-4400-aa6c-7add7d35f33e.png)

1. Using custom sitemap filter 
`function add_my_sitemap() {
return ['https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/files/custom-sitemap-query-strings.xml'];
}
add_filter( 'rocket_sitemap_preload_list', 'add_my_sitemap', PHP_INT_MAX );`
2. Fresh install and activation of WPR
3. Wait till preload is completed
4. Refresh admin or update dynamic list 
5. Check database => URLs added to cart  (the actual page set at WC), My account (not the actual set one), checkout (not the actual set one) , author and home is set to pending

**Expected behavior**
Any page that can't be cached shouldn't be added to cache table or shall be removed once processed

**Additional context**
- Same was happening on 3.12.5.3 but without adding Cart page
- At 3.12.6.1, accessing Author page was auto redirecting to maintenance page (so this page was never completed at cache table)
- After disable some plugins and re-enable them again, the issue didn't happen 
- As per @engahmeds3ed 

> https://github.com/wp-media/wp-rocket/blob/ef300cf2d46e837789f9ad42ff8166c832a47dc3/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L14-L18
we are bailing out if the option is empty and this is the case with fresh install.
then after some lines we are getting the rejected urls
https://github.com/wp-media/wp-rocket/blob/ef300cf2d46e837789f9ad42ff8166c832a47dc3/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L23
and there woocommerce pages are added

- As per @vmanthos , the issue wasn't on a fresh install but on an existing one, `/cart` , `/checkout` , and `/my-account` are in `wpr_rocket_cache` with a failed status. They all exist in the`wp-sitemap.xml`. I removed all URLs from the table and deactivated/activated preload. Although preload finished, for those URLs the status is still in-progress. I'm guessing this will become failed at some point. This is related to https://github.com/wp-media/wp-rocket/pull/5628. 

>We are excluding URLs that the user has added in the preload exclusion text area or ones that have been excluded using the rocket_preload_exclude_urls filter, e.g. :
https://github.com/wp-media/wp-rocket/blob/ec4d2a301321de6854fff722472d284913f3f050/inc/ThirdParty/Plugins/TheEventsCalendar.php#L22
We are not doing the same for WooCommerce URLs which are automatically excluded:
[https://github.com/wp-media/wp-rocket/blob/ec4d2a301321de6854fff722472d284913f3f050/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L[…]7](https://github.com/wp-media/wp-rocket/blob/ec4d2a301321de6854fff722472d284913f3f050/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L198-L207).
I think we should change the WooCommerce subscriber to do that.

- Slack discussion: https://wp-media.slack.com/archives/GUT7FLHF1/p1678373010624449

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Mentioned WooCommerce pages are excluded from the cache. It means we should not make any requests and removed them from the database while processing pending items (it's expected behaviour for excluded URLs).

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I reproduced it successfully.

## Identify the root cause
The root cause is a difference in the filter used in the preload and woocommerce third party classs:
- `rocket_cache_reject_uri`
- `rocket_preload_exclude_urls`

## Scope a solution
Add the callback `exclude_pages` to `rocket_preload_exclude_urls` event into WooCommerce thirdparty class and create tests.

## Estimate effort 
Effort `XS`
