### ISSUE TITLE
WebP Cache compatibility with the Email Encoder plugin

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5806]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.6.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WebP cache is used with the Email [Encoder plugin](https://wordpress.org/plugins/email-encoder-bundle/), and their Full-page scan, their plugin will convert `webp images` from: 

```
image-@-something-603x1024.webp
``` 

to 

```
<span id="eeb-40107-401044"></span><script type="text/javascript">document.getElementById("eeb-40107-401044").innerHTML = eval(decodeURIComponent("%27%69%6d%61%67%65%2d%40%2d%73%6f%6d%65%74%68%69%6e%67%2d%36%30%33%78%31%30%32%34%2e%77%65%62%70%27"))</script><noscript>*protected email*</noscript>
```

![image](https://user-images.githubusercontent.com/1289174/224288316-09d37ffe-0327-4594-a7ed-eaf898f46c9e.png)

The issue is not caused by WP Rocket, but it's triggered by the presence of WebP images on the page.

Notified the plugin authors about the issue: https://github.com/Ironikus/email-encoder-bundle/issues/1

Their plugin has a filter that controls the regex. It can be used to adjust it to exclude images if necessary using a compatibility file (updated filter from the plugin's devs, they have a filtrable array for images): 

```
apply_filters( 'eeb/validate/excluded_image_urls', 'eeb_customize_image_file_types', 20, 1 );
function eeb_customize_image_file_types( $excludedList ){

	if( ! in_array( '.webp', $excludedList ) ){
		$excludedList[] = '.webp';
	}

	return $excludedList;
}
```

Update: the plugin's devs will add `webp` as part of their exclusions on their next release. 

**To Reproduce**
1. Enable Email Encoder Full-page scan
2. Use an image with `@` part of its name
3. Convert it to `webp` and use the WebP Cache option
4. See the image will break

**Expected behavior**
WebP Cache should render images correctly. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2178283320/406987/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
