### ISSUE TITLE
Separate cache for mobile compatibility with SiteGround Optimizer

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5808]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the separate cache for mobile is enabled, it's mandatory for the other cache layers should also handle the separate cache as well. 

On SiteGround's cache, and if the SiteGround Optimizer is activated, they have an option called `Browser-specific Caching`, that allows enabling a separate cache for mobile.

![image](https://user-images.githubusercontent.com/1289174/224476514-5dfe2383-a087-4200-b47a-4012944af54f.png)

It's managed using REST API using the following method: 

```
public function manage_user_agent_header( $request ) {
	// Validate rest request and prepare data.
	$data = $this->validate_rest_request( $request, array( 'user_agent_header' ) );

	// Disable the option.
	if ( 0 === $data['value'] ) {
		Options::disable_option( 'siteground_optimizer_user_agent_header' );

		$this->htaccess->enable( 'user-agent-vary' );

		// Send the response.
		self::send_json_success(
			self::get_response_message( true, 'user_agent_header', 0 ),
			array(
				'user_agent_header' => 0,
			)
		);
	}

	$cache_option = Helper_Service::is_siteground() ? 'enable_cache' : 'file_caching';

	// Enable the cache.
	Options::enable_option( 'siteground_optimizer_' . $cache_option );

	// Enable Automatic Purge.
	Options::enable_option( 'siteground_optimizer_autoflush_cache' );

	// Enable Browser-specific Caching.
	Options::enable_option( 'siteground_optimizer_user_agent_header' );

	$this->htaccess->disable( 'user-agent-vary' );

	if ( Options::is_enabled( 'siteground_optimizer_file_caching' ) ) {
		File_Cacher::get_instance()->purge_everything();
	}

	// Send the response.
	self::send_json_success(
		self::get_response_message( true, 'user_agent_header', 1 ),
		array(
			$cache_option       => 1,
			'autoflush_cache'   => 1,
			'user_agent_header' => 1,
		)
	);
}
```

Located on the following file: 

```
sg-cachepress/core/Rest/Rest_Helper_Cache.php
```

It should be possible to toggle the option on and off when required. 

Heads up, when SiteGround enables `Browser-specific Caching`, it will force enabling their `File-Based Caching` setting, which will temporarily override WP Rocket's `advanced-cache.php` rules. Once WP Rocket's cache is cleared, we restore the `advanced-cache.php` overtake back. 

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**
Added to the description

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2179444959/407279?folderId=2008123

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
