### ISSUE TITLE
Safeguard Used CSS from incomplete CSS

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5809]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In some occasions, Remove Unused CSS SaaS will receive a locked version of the page that will try to check if the visit is not from a bot, and will try to restrict if it is. 

The page received by SaaS will look like this:

```
<html><meta http-equiv="refresh" content="0;/.well-known/captcha/"></meta></head></html>
```

And it will generate the following Used CSS that will be sent back to WP Rocket: 

```
body{margin:0;padding:0 0 20px;font:16px/24px 'Open Sans',sans-serif;color:#666;background-color:#fff;text-rendering:optimizeLegibility}
```

That CSS will break the page.

**To Reproduce**
N/A

**Expected behavior**
We shouldn't allow using a known not working CSS. 
The check can be done on SaaS when the request returns HTML or on WP Rocket while receiving a response from SaaS with the Used CSS. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2179444959/407279?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@mostafa-hisham That should be handled on the saas side, right?

**Comment by mostafa-hisham** [comment]
@piotrbak I think we can fix it in sass. but I need a particular string or HTML that I can use to detect this.
@DahmaniAdame Could you please provide me with URLs with this issue?

**Comment by DahmaniAdame** [comment]
@mostafa-hisham the `captcha` one is random. 

It will look like: 
```
<html><meta http-equiv="refresh" content="0;/.well-known/captcha/"></meta></head></html>
```
You experienced it yourself here: https://wp-media.slack.com/archives/C029G1B5HD2/p1661149412150209?thread_ts=1660869607.370839&cid=C029G1B5HD2

Would it be possible to look for `0;/.well-known/captcha/`? That should be a constant regardless of the that particular HTML is returned. 

The second case is if the page returns a fatal error while still returning a `200` response code. I will PM you a sample link for you to test. 

We need something that would prevent generating the Used CSS in that case as well. 

In this case, the Used CSS was generated, but empty: 

```
{
    "code": 200,
    "status": "completed",
    "elapsed_time": "7962ms",
    "coverage_time": "7958ms",
    "purge_time": "4ms",
    "message": "Treeshaked successfully!",
    "contents": {
        "success": true,
        "shakedCSS": "",
        "shakedCSS_size": 0,
        "orginalCSS_size": 0
    },
    "server_ip": "141.94.254.72"
}
```

Not sure if it's still sent. 

Targeting `<b>Fatal error</b>` should work as well.

**Comment by mostafa-hisham** [comment]
@DahmaniAdame @piotrbak 
In the second case, Adame mention a 200 response code with empty used CSS should be handled here on the plugin side
https://github.com/wp-media/wp-rocket/blob/ffac5d90e5a83bcb5a29b8e43f059a31adfae629/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L607

For the first case the captcha one  
checking the HTML for each page to search for `content="0;/.well-known/captcha/"` will not be efficient if we have some URLs with this case it is better to check the response headers if it has something we can use intend of searching the whole HTML content

**Comment by DahmaniAdame** [comment]
@mostafa-hisham @piotrbak we could maybe add a minimum for `shakedCSS_size` as a condition here?

https://github.com/wp-media/wp-rocket/blob/1f8dfc9660a112a2a937e2fb90e51cad0b9572a5/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L620-L626

We have a sample resulting CSS from that specific case.
```
body{margin:0;padding:0 0 20px;font:16px/24px 'Open Sans',sans-serif;color:#666;background-color:#fff;text-rendering:optimizeLegibility}
```
We can either set a specific count to be denied or a threshold for the CSS to be considered valid.

**Comment by piotrbak** [comment]
We'd need to be very careful there, but let's try with deny option. @mostafa-hisham Could you create a PR with a filter?
