### ISSUE TITLE
WooCommerce: $rocket_cache_reject_uri and draft mode

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#581]
WP Rocket currently doesn’t update its config file to reflect when dedicated WooCommerce pages are set from draft to published. This can lead to those pages being cached while they should not.

## Test

-  activate WP Rocket
- activate WooCommerce
- make sure dedicated pages are set up correctly (`cart`, `checkout`, `my-account`)
- open `{wp content dir}/wp-rocket-config/{site.url}.php`
- cache reject var includes those pages (example: `my-account`):
   ```php
   $rocket_cache_reject_uri = '(.*)/feed/?|/wp-json/(.*)|/checkout/(.*)|/cart/|/my-account/(.*)';
   ```
- deactivate WP Rocket
- set WooCommerce’s `my-account` page to draft mode
- activate WP Rocket
- open `{wp content dir}/wp-rocket-config/{site.url}.php`
- cache reject does not include `my-account` (correct, since it is not a published page):
   ```php
   $rocket_cache_reject_uri = '(.*)/feed/?|/checkout/(.*)|/cart/|/wc-api/v(.*)|/wp-json/(.*)';
   ```
- set `my-account` page to `published`
- open `{wp content dir}/wp-rocket-config/{site.url}.php` again
- cache reject var should now include `/my-account/(.*)`, but it does not

**Comment by Tabrisrp** [comment]
That would mean we would check the IDs of the WC pages against the current page ID each time we clear cache of a page. I'm not sure it's worth the trade-off.

**Comment by glueckpress** [comment]
Can’t we tackle this from the post status side of things?

```php
add_action( 'transition_post_status', function ( $new_status, $old_status, $post ) {

	// Only selected WooCommerce pages.
	if ( absint( get_option( 'woocommerce_cart_page_id' ) )      !== $post->ID
	  && absint( get_option( 'woocommerce_checkout_page_id' ) )  !== $post->ID
	  && absint( get_option( 'woocommerce_myaccount_page_id' ) ) !== $post->ID ) {
		  return false;
	}

	// Execute when post status is changed from draft or pending to publish.
	if ( 'publish' !== $old_status  &&  'publish' === $new_status ) {
		// add page to $rocket_cache_reject_uri
	}
}, 10, 3 );
```

**Comment by emlebrun** [comment]
➤ Lucy Beer commented:

This isn't working. The behaviour is different than before, but still incorrect. In fact, what's happening now is that even when the WooCommerce pages are correctly set in WC settings, and published, the WP Rocket config file is not updated with any exclusions:
https://jmp.sh/SJ9N1iz
Have tested on 3 sites, included our mega site, to confirm.
(screenshot shows 3 of the 4 wc pages set. It doesn't make a difference if all or some are set, behaviour is the same).

Draft mode no longer has any impact - so the entire site is not excluded from the cache as it was before. 
(tester=Lucy)

**Comment by emlebrun** [comment]
➤ Remy Perona commented:

This should be fixed in alpha 3
