### ISSUE TITLE
403 URLs arenot removed from caching table

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5810]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.6.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Using Ultimate Member plugin, will add URL to cache table like `https://new.rocketlabsqa.ovh/void(0);`, this URL isnot removed once processed 

**To Reproduce**
- Ultimate Member plugin is activated
- WP sitemap is disabled (URLs fetched from home page)
1. install and activate WPR
2. Check cache table => mentioned URL is added and once processed will fail

**Expected behavior**
403 URLs shall be removed as same as 404 URLs

**Screenshots**
![Screenshot from 2023-03-13 11-55-03](https://user-images.githubusercontent.com/76941962/224674691-e42717f7-0e29-4b64-ab89-47f322e63fd2.png)

**Additional context**
![Screenshot from 2023-03-13 12-25-17](https://user-images.githubusercontent.com/76941962/224675174-5363a03e-dac6-4664-9cee-0972ba0eee3f.png)
We shouldn't fetch this kind of URL.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by mehedihasanziku** [comment]
#5543 maybe it should tackle also with this case

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce this issue on NGINX.

### Identify the root cause ✅
We are not removing urls that don't have status of `200`

### Scope a solution ✅
We can make a request to get the response status of the url and bail out if not 200 in preload_url
https://github.com/wp-media/wp-rocket/blob/ce9d862f279ee636503fa8367cc4ce6d09812be9/inc/Engine/Preload/Controller/PreloadUrl.php#L61
```
$response = wp_remote_get( $url );

if ( is_wp_error( $response ) ) {
	$this->query->delete_by_url( $url );
	return;
}

$response_code = wp_remote_retrieve_response_code( $response );

if ( 200 !== $response_code ) {
	$this->query->delete_by_url( $url );
	return;
}
```
### Estimate the effort ✅
[S]

**Comment by jeawhanlee** [comment]
> ### Reproduce the problem ✅
> I was able to reproduce this issue on NGINX.
> 
> ### Identify the root cause ✅
> We are not removing urls that don't have status of `200`
> 
> ### Scope a solution ✅
> We can make a request to get the response status of the url and bail out if not 200 in preload_url
> 
> https://github.com/wp-media/wp-rocket/blob/ce9d862f279ee636503fa8367cc4ce6d09812be9/inc/Engine/Preload/Controller/PreloadUrl.php#L61
> 
> ```
> $response = wp_remote_get( $url );
> 
> if ( is_wp_error( $response ) ) {
> 	$this->query->delete_by_url( $url );
> 	return;
> }
> 
> $response_code = wp_remote_retrieve_response_code( $response );
> 
> if ( 200 !== $response_code ) {
> 	$this->query->delete_by_url( $url );
> 	return;
> }
> ```
> 
> ### Estimate the effort ✅
> [S]

Following a point from @mostafa-hisham, the above grooming might be resource consuming on the customer site as we will be doing 2 requests to each url:
- one to check for status code.
- and if response code is 200 another again to preload.

As suggested by @mostafa-hisham we can also have a compatibility class for ultimate members and exclude urls like that `void(0);`
or I'm thinking we can utilize this request [here](https://github.com/wp-media/wp-rocket/blob/ce9d862f279ee636503fa8367cc4ce6d09812be9/inc/Engine/Preload/Controller/PreloadUrl.php#L139) and check the response code and perform necessary actions, don't know how well that will work.

@piotrbak @wp-media/php what do you think?

**Comment by piotrbak** [comment]
@jeawhanlee I believe that both options are not good enough:
1. As Mostafa mentioned, it'll create additional request
2. We're sending not-blocking request, it means that we're not waiting for the response

Maybe it's good time to move this array to the backend?
https://github.com/wp-media/wp-rocket/blob/f20c8f3d139553fa828ccafd8c813f334d8e765c/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L33

Pinging @mostafa-hisham
