### ISSUE TITLE
Update delay JS script to the latest version

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5811]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
This update faces the problem when a script calls this kind of jQuery syntax with the on() function:
```
$(element).on({
    mousedown: function() {...},
    mouseup: function() {...}
});
```

Problem was related, for example, to sticky and transparent layouts in Elementor.

**Additional context**
The following, [develop](https://github.com/wp-media/delay-javascript-loading/blob/develop/delay-js.js) branch of Delay JS script should be used.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by gmetais** [comment]
More precisely, in case you need to reproduce, the bug does not happen on **any kind** of element, only on `window`. For example:

```
$(window).on({
    scroll: function() {...},
    resize: function() {...}
});
```

The classical `$(window).on('scroll', function() {...})` syntax is working correctly.
