### ISSUE TITLE
Adjust image dimensions regex to not delete the wrong `height` and `width` attributes

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5818]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.6.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

In the following method: 

https://github.com/wp-media/wp-rocket/blob/d9c8d3cd1a2f3fc0e450dae67d51962522bbbee6/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L325-L335

The following regex is not considering `data-` or custom attributes ending `height` or `width` as part of their names: 

```
$changed_image = preg_replace( '/(height|width)=[\'"](?:\S+)*[\'"]\s?/i', '', $image );
```

Using markup like the following: 

```
<img class="logo-main scale-with-grid svg" src="/path/to/img.ext" data-retina="" data-height="" alt="Porty Cleaning Services" data-no-retina="">
```

This will result in the following: 

```
<img class="logo-main scale-with-grid svg" src="/path/to/img.ext" data-retina="" data-alt="Porty Cleaning Services" data-no-retina="">
```
In this specific case, there will be an SEO impact as the remaining `data-` portion will stick to `alt`, changing it's function. 

In other cases, the next attribute will lose its function, which might cause anything relying on it to break. Example, if JavaScript is looking for a specific attribute to change DOM.

Changing the following: 

```
$changed_image = preg_replace( '/(height|width)=[\'"](?:\S+)*[\'"]\s?/i', '', $image );
```

to: 
```
$changed_image = preg_replace( '/\s(height|width)=[\'"](?:\S+)*[\'"]\s?/i', ' ', $image );
```
will fix the issue. 

We will be looking for `height` and `width` attributes preceded by a space, and then replaced by as space. 

That should give an accurate replacement.

We should do the same to: 

https://github.com/wp-media/wp-rocket/blob/d9c8d3cd1a2f3fc0e450dae67d51962522bbbee6/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L275-L276

By limiting the regex to `height` or `width` attributes only by requesting the existence of a space before them.

This can be done by changing:

```
preg_match( '/<img.*height=[\'\"](?<height>\S+)[\'\"].*>/i', $image, $initial_height );
preg_match( '/<img.*width=[\'\"](?<width>\S+)[\'\"].*>/i', $image, $initial_width );
```
to:
```
preg_match( '/<img.*\sheight=[\'\"](?<height>\S+)[\'\"].*>/i', $image, $initial_height );
preg_match( '/<img.*\swidth=[\'\"](?<width>\S+)[\'\"].*>/i', $image, $initial_width );
```

**To Reproduce**
1. Use the Image Dimensions feature
2. Use an image with a custom attribute ending with either `height` or `width`, example: `custom-height=500`
3. See that `custom-` will be preserved on the markup and stuck to the next attribute

**Expected behavior**
Images markup should break when using the Image Dimensions feature

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2183072962/407989/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the problem ✅

### Identify the root cause ✅
Like @DahmaniAdame Explain above the regex will replace custom height and  width attrs and may lead to problems

### Scope a solution ✅
The same fix he mentioned add a space before `height` and  `width` attr in Regex.
and update tests

### Estimate the effort ✅
[XS]

**Comment by devonto** [comment]
Hello,

Just looking to find out an update on this issue, as I see it has been removed from the 3.13.2 milestone.
This is affecting quite a few of my sites, where PageSpeed is flagging the issue up as an accessibility issue.
![image](https://user-images.githubusercontent.com/6807236/236693854-08b70b91-f4ea-47a7-9578-e35410df3a8c.png)
