### ISSUE TITLE
Preload rocket_preload_completed returns wrong device type for tablets in some occasions

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5825]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.12.6.1`
- Used the search feature to ensure that the bug hasn’t been reported before: :heavy_check_mark: 

**Describe the bug**

The `rocket_preload_completed` action fires after the cache has been created: 
https://github.com/wp-media/wp-rocket/blob/498e405a9eb0a7bc0aaf8f27e01406bf9470030e/inc/Engine/Preload/Subscriber.php#L197

If the [WP Rocket | Set Tablets As Mobile](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-tablet) helper is used to change how WP Rocket treats tablets from `desktop` (default setting) to `mobile`, for a tablet request the action will mistakenly return desktop instead of mobile.

**To Reproduce**

**Preconditions**

- Enable the **Separate cache files for mobile devices** feature.
- Add the following snippet to log the preload URL and device type:
```PHP
add_action( 'rocket_preload_completed', function( $url, $detected ){
	if( ! defined( 'WP_ROCKET_VERSION' ) ) return;
	error_log( "URL: $url\tDevice: $detected\tUser Agent: " . $_SERVER['HTTP_USER_AGENT']. "\n", 3, ABSPATH . 'PRELOAD_COMPLETED.log');
}, 10, 2);
```

1. Visit an uncached URL using an iPad simulator in Chrome Dev Tools. You'll get this in the log:
```
 https://wprocketest.test/blog	Device: **desktop**	User Agent: Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1
```
2. Install/activate the [WP Rocket | Set Tablets As Mobile](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-tablet) helper plugin.
3. Repeat step 1. Instead of getting `Device: mobile` in the log, you'll get the same device type as previously.

**Expected behavior**

The tablet devices should be detected as mobile devices when the [WP Rocket | Set Tablets As Mobile](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-tablet) helper plugin is installed.

**Additional context**

This came up after investigating #5777.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
