### ISSUE TITLE
Add Smartframe.io on Minify JS default exclusions

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#5827]
**Is your feature request related to a problem? Please describe.**
The issue with Minify JavaScript is related in this ticket: 
https://secure.helpscout.net/conversation/2188570390/409119?folderId=2952229

**Describe the solution you'd like**
Add Smartframe.io on default exclusions on Minify JavaScript

**Describe alternatives you've considered**

**Additional context**
All the context in the ticket: 
https://secure.helpscout.net/conversation/2188570390/409119?folderId=2952229

**Comment by alfonso100** [comment]
added `smartframe.io` to Minify/combine exclusions in SaaS
