### ISSUE TITLE
Issues with headers in LiteSpeed.php

### ISSUE THREAD

**Issue by luanluta** [wp-media/wp-rocket#5830]
Two issues in the LiteSpeed.php file:

1. [Here](https://github.com/wp-media/wp-rocket/blob/d1fc8854869892b4ec5c061f88af98e49c6e450d/inc/ThirdParty/Hostings/LiteSpeed.php#L94-L95), we are supposed to send two headers, but instead, we only send one because the second call to `send_header` checks if headers have already been sent and doesn't actually send anything. 
2. `$headers` property isn't defined.
3. The `litespeed_send_headers` isn't being used.

Original conversation [here](https://wp-media.slack.com/archives/C43T1AYMQ/p1679494142503129?thread_ts=1679491230.902049&cid=C43T1AYMQ)

> I believe we have two problems with the current code that we need to look into.
First:
[here](https://github.com/wp-media/wp-rocket/blob/d1fc8854869892b4ec5c061f88af98e49c6e450d/inc/ThirdParty/Hostings/LiteSpeed.php#L94-L95) we send two headers but actually we send one because in the first one we call header function and in the second call we check if headers are sent so bailout.
This can be solved by removing calling the function header from send_header method and after calling send_header twice we call call the method litespeed_send_headers
Second:
We need to create headers property initialized with empty array

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
