### ISSUE TITLE
Cache is served for multisite subsites even after WP Rocket was deactivated there

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5831]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

On subsites of a subfolder multisite, cache, if it exists, will be served even if WP Rocket is deactivated there as long as it's activated on the main site.

For example, if the main site is `example.com` and the subsite `example.com/green`, and WP Rocket is deactivated on the second, the cache will still be served for `example.com/green/*` URLs assuming it was there before the deactivation.

This is because we don't have a way to check if a URL belongs to a subsite and therefore exclude it from caching. 

**To Reproduce**

1. Enable WP Rocket on the main site and a subsite of a multisite.
2. Make sure cached pages exist for the subsite.
3. Deactivate WP Rocket on the subsite and check the pages of the subsite.
4. Those that were previously cached will be served from the cache.

**Expected behavior**

The cache should _NOT_ be served for subsites if WP Rocket is deactivated there.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
