### ISSUE TITLE
CORS headers are incorrectly removed from the htaccess on multisites

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5832]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

We automatically add CORS headers rules to the `.htaccess` site when enabling the CDN feature. We are doing the same on multisites when the CDN is enabled for the main site and/or subsites.

Disabling the CDN feature on a subsite or the main site will remove the CORS headers regardless of whether the option is enabled on other sites of the network.

**To Reproduce**

1. Enable the CDN feature on the main site and the subsite of a multisite network.
2. Confirm that the CORS rules were added to the `.htaccess`.
3. Disable the CDN feature on a subsite and check the `.htaccess` file.
4. The CORS rules will not be there.

**Expected behavior**

CORS headers should not be removed from the `.htaccess` if the CDN option is activated on any of the sites of the network.

**Additional context**

Changing any option that triggers the `.htaccess` regeneration, e.g. excluding URLs from caching in the Never Cache URLs, on a site that has the CDN feature enabled will re-add the CORS rules.

The opposite, i.e. the CORS rules will be removed, will happen if such a change takes a place on a site where the CDN is disabled.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
