### ISSUE TITLE
PHP fatal error when passing an integer or float to rocket_post_purge_urls

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5833]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

If an integer or a float is passed to `rocket_post_purge_urls`:
https://github.com/wp-media/wp-rocket/blob/cf3fe446a6dcfd08c60c5b19907662c860f0cdff/inc/common/purge.php#L237

a fatal error is thrown from `WP_Rocket\Engine\Preload\Subscriber::clean_partial_cache()` which expects an array :
```
PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Preload\Subscriber::clean_partial_cache(): Argument #2 ($urls) must be of type array, float given, called in /shared/httpd/wprocketest/htdocs/wp-includes/class-wp-hook.php on line 308 and defined in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Subscriber.php:294
Stack trace:
#0 /shared/httpd/wprocketest/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Preload\Subscriber->clean_partial_cache(Object(WP_Post), 2.5, false)
#1 /shared/httpd/wprocketest/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /shared/httpd/wprocketest/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/common/purge.php(259): do_action('after_rocket_cl...', Object(WP_Post), 2.5, false)
#4 /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/common/purge.php(493): rocket_clean_post(788)
#5 /shared/httpd/wprocketest/htdocs/wp-includes/class-wp-hook.php(308): do_admin_post_rocket_purge_cache('')
#6 /shared/httpd/wprocketest/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#7 /shared/httpd/wprocketest/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /shared/httpd/wprocketest/htdocs/wp-admin/admin-post.php(85): do_action('admin_post_purg...')
#9 {main}
  thrown in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Subscriber.php on line 294
```

**To Reproduce**

Preconditions:
- Preload should be enabled

1. Use the following snippet:
```PHP
add_filter('rocket_post_purge_urls',function( $purge_urls ){
	$purge_urls = 15;
	return $purge_urls;
});
```
2. Update a post or clear its cache from the posts page.
3. See the error in the `debug.log`.

**Expected behavior**

We should safeguard what is returned from the filter so no fatal error should occur if the value passed to the filter is an integer or a float.

**Additional context**

The filter is used here as well:
https://github.com/wp-media/wp-rocket/blob/cf3fe446a6dcfd08c60c5b19907662c860f0cdff/inc/common/purge.php#L309

We should safeguard it there as well. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
