### ISSUE TITLE
Change the way how we recognize One.com hosting

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5834]
**Is your feature request related to a problem? Please describe.**
All hostings from the group will be using the same variable in the `$_SERVER` array.

Instead of looking for this variable:
https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/ThirdParty/Hostings/HostResolver.php#L34

We'll look for `$_SERVER['GROUPONE_BRAND_NAME']`, and for One.com its value will be `one.com`.

Please note that in the next minor versions we'll add another hosting from the group, its `$_SERVER['GROUPONE_BRAND_NAME']` value will be different.

**Describe the solution you'd like**
We need to check for existence of this variable in `$_SERVER` array and then decide on which hosting we're based on the value.

**Comment by remyperona** [comment]
What about the detection in the CDN compatibility? should it still use the old server variable or the new one?

**Comment by piotrbak** [comment]
@Tabrisrp You mean `$_SERVER['ONECOM_DOMAIN_NAME']`?
It should still be there, we just can't use it to detect One.com hosting anymore. It'll be also present on the servers with different settings soon, while this new one is 100% unique.
