### ISSUE TITLE
Uncaught Error: Call to undefined function trailingslashit()

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5836]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A fatal error started in WordPress `6.1` when using `trailingslashit()` early. The same happens for `untrailingslashit()`.

It's happening because of a missing dependency to `formatting.php` when called via `wp_load_translations_early()`,

https://core.trac.wordpress.org/ticket/57218

A fix is meant to be released in `6.1.2` if plans don't change. 

We are calling that function in many locations. This makes using WP Rocket with `6.1` up to whatever version will have the fix, potentially causing the site to break. 

One way to fix that is to break off the dependency for `trailingslashit()` and `untrailingslashit()` by adding our own similar functions. 

https://github.com/WordPress/WordPress/blob/9caf1c4adeddff2577c24d622ebbbf278a671271/wp-includes/formatting.php#L2770-L2787

**To Reproduce**
I couldn't replicate it. But based on https://core.trac.wordpress.org/ticket/57218, the issue there, and would trigger whenever `formatting.php` is not yet loaded.

**Expected behavior**
WP Rocket shouldn't trigger fatal error because of 3rd party functions when possible. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2185421585/408497

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Do we have any actual case in the plugin where the function is not loaded yet?

**Comment by DahmaniAdame** [comment]
The same ticket - https://secure.helpscout.net/conversation/2185421585/408497
But it seems random. It works for a while, then the site breaks. Once WP Rocket is deactivated, the issue is fixed.

**Comment by piotrbak** [comment]
That was fixed in WP 6.2
