### ISSUE TITLE
Update SEOPress integration for sitemap preloading

### ISSUE THREAD

**Issue by wp-seopress** [wp-media/wp-rocket#5839]
https://github.com/wp-seopress/wp-rocket/tree/feat/seopress-sitemap-preloading

**Comment by piotrbak** [comment]
We'll need to fix some tests there

**Comment by CrochetFeve0251** [comment]
@piotrbak we would have to handle old and new version for this one, right?
I mean check the version from the plugin and then call our old logic or the new one they provided us.

**Comment by piotrbak** [comment]
@wp-seopress Could you confirm that this change is backward compatible on your side?

**Comment by wp-seopress** [comment]
@piotrbak Yes absolutely.
