### ISSUE TITLE
Offload storing CPCSS fallback to a file

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5841]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.6.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a fallback for CPCSS is added, it's stored in `wp_rocket_settings` entry on the database. This causes it to increase the options request size considerably.

We are setting `wp_rocket_settings` to `autoload`, forcing the excess to be loaded into the memory unnecessarily. 

If the CPCSS fallback weights 1Mb, we will take that 1Mb for no valid use. 

Since the CPCSS fallback will be static, storing it in a file would make more sense. 

**To Reproduce**
N/A

**Expected behavior**
We should avoid storing data in memory when there is no valid need for it.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2193423863/410082?folderId=273761

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
