### ISSUE TITLE
PRO ISP hosting compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5844]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We need to make sure we're able to detect and clean Varnish on this specific platform.

**To Do**
1. We can detect the hosting using `$_SERVER['GROUPONE_BRAND_NAME']` value:
`proisp.no`
https://github.com/wp-media/wp-rocket/blob/1f8dfc9660a112a2a937e2fb90e51cad0b9572a5/inc/ThirdParty/Hostings/HostResolver.php#L35

2. We'll detect the Varnish **in the same way** as we detect it for One.com servers:
https://github.com/wp-media/wp-rocket/blob/1f8dfc9660a112a2a937e2fb90e51cad0b9572a5/inc/ThirdParty/Hostings/OneCom.php#L149

3. If Varnish is active, we'll enable our add-on, grey out the settings and display the message:
https://github.com/wp-media/wp-rocket/blob/1f8dfc9660a112a2a937e2fb90e51cad0b9572a5/inc/ThirdParty/Hostings/OneCom.php#L128
https://github.com/wp-media/wp-rocket/blob/1f8dfc9660a112a2a937e2fb90e51cad0b9572a5/inc/ThirdParty/Hostings/OneCom.php#L118

**Expected behavior**
WP Rocket should detect the platform, if Varnish is enabled using their plugin we should force our addon with message and clear the server cache when needed.

For QA, it's very likely that sending `/` to the Varnish will clear the whole cache. That's the same behaviour as for One.com

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
We will create a 3rd party compatibility class to detect if varnish is active just as we do for one.com like @piotrbak stated.

Also add tests.

### Estimate the effort ✅
[S]
