### ISSUE TITLE
[2.11-alpha2]: PHP Notices in /inc/front/async-css.php

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#585]
PHP Notice:  Undefined index: home in ../inc/front/async-css.php on line 111
PHP Notice:  Undefined index: post_tag in ../inc/front/async-css.php on line 115

Maybe it will be the same with all other type of content (categories, post types, page, etc)

**Comment by Tabrisrp** [comment]
Fixed by a392c0e
