### ISSUE TITLE
[WIP] __trashed URLs inserted in Cache and RUCSS tables

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5853]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
I have noticed some cases where  **trashed** URLs are inserted in the Cache and RUCSS tables:

**Rucss**
![QH38YlE](https://user-images.githubusercontent.com/229406/229608973-f075bd27-f290-416e-9075-f3c4f23f7520.png)
https://i.imgur.com/QH38YlE.png

**Preload**
![KhKpi5T](https://user-images.githubusercontent.com/229406/229609102-bd8fcd04-0ca2-4b44-9ded-44f83dcf3795.png)
https://imgur.com/KhKpi5T.png

these will be failed when we try to process it

**To Reproduce**
- Haven't been able to reproduce __trashed URLs going into our tables. 

**Expected behavior**
We should exclude **__trashed** URLs from the Cache and RUCSS tables.

**Additional context**
Related slack thread:
https://wp-media.slack.com/archives/C43T1AYMQ/p1678472380185699

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
another case where a customer is mentioning these __trashed URLs
https://secure.helpscout.net/conversation/2183026997/407972?folderId=2683093

**Comment by alfonso100** [comment]
after a discussion with @vmanthos and @piotrbak we are adding `(.*)__trashed(.*)` to the cache exclusions in the backend

**Comment by webtrainingwheels** [comment]
I am seeing these URLS in this case: https://secure.helpscout.net/inboxes/5de4805abf96951b/views/377611
An automatic exclusion would be nice for us to implement.
