### ISSUE TITLE
Defer JS compatibility with WooCommerce AJAX Products Filter (BeRock)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5856]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.13`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When jQuery is excluded from Defer, WooCommerce AJAX Products Filter (BeRock) no longer works as expected. 

When clicking on any filter checkbox, no filtering will happen, and the checkbox will be automatically unchecked. 

No error will show.

Without excluding jQuery, all runs well. 

After excluding jQuery, it requires excluding an additional script for it to work: 

```
/woocommerce-ajax-filters/assets/frontend/js/main.min.js
```

**To Reproduce**
1. Enable WooCommerce AJAX Products Filter (BeRock)
2. Enable Defer JS and exclude the jQuery library `/wp-includes/js/jquery/jquery.js`
3. Try to use a filter
4. See error (filter not responsive)

**Expected behavior**
The functionality of the filter shouldn't break if jQuery is excluded. 

**Screenshots**
[Screen recording](https://user-images.githubusercontent.com/1289174/230028991-e8151e6f-02c0-4014-bff1-81835f240bd2.mp4)

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2194346685/410236/

No adding to the backend as it will require a compatibility file. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
What about auto-excluding jQuery and the plugin JS file when the plugin is activated by using the plugin. It will avoid having to create a PHP file and maintain compatibility there.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
