### ISSUE TITLE
htaccess rules are not removed during deactivation when the configuration folder contains non-WP Rocket PHP files

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5857]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13.0.1`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When WP Rocket's configuration folder contains non-WP Rocket PHP files, we don't remove the `.htaccess` rules during deactivation.
If the rewrite rules are in the `.htaccess` file, for URLs that were previously cached we will still be serving cached content.

We aren't removing the rules because the `_rocket_get_php_files_in_dir()` function that's used here:
https://github.com/wp-media/wp-rocket/blob/5c37097b19ac4dcfdf8b44e772f2d0276479cae1/inc/Engine/Deactivation/Deactivation.php#L71-L76

to determine whether to flush htaccess or not is counting any `.php` file, i.e. not just WP Rocket's configuration files.

**To Reproduce**

1. Create a couple of `.php` files in WP Rocket's configuration folder. 
2. Deactivate WP Rocket. 
3. Check the `.htaccess` file.

**Expected behavior**

We should remove the htaccess rules even if the config folder contains PHP files.

**Additional context**

This came during the investigation of the following PR:
https://github.com/wp-media/wp-rocket/issues/5854

There was a similar issue that was addressed by this PR:
https://github.com/wp-media/wp-rocket/issues/5687?_ga=2.234276126.1040472067.1680500875-988333000.1671559654

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
