### ISSUE TITLE
DJE GUI -  add possibility to pair dependencies

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5860]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In some occasions, the referenced exclusions on the DJE GUI will have dependencies on other exclusions. 

For example, the `Astra - Pro addon` exclusion will cause the mini cart to not load the quantity button if not excluded with `WooCommerce - Cart Fragments`. 

We should start referencing dependencies on the backend when they apply.

On WP Rocket's side, the bare minimum is to exclude `WooCommerce - Cart Fragments` when `Astra - Pro addon` is excluded in the background. 

Ideally, ticking the `Astra - Pro addon` should also tick `WooCommerce - Cart Fragments` while graying it and adding a tooltip that mentions it was excluded because of a dependency.

This is the first case of such a dependency. 

Let's monitor if others exist and see if it will be necessary to add more complexity to the DJE GUI mechanism.

**To Reproduce**
Specific to this case:
1. Enable `Astra - Pro addon` + `WooCommerce`
2. Enable the `Astra - Pro addon` exclusion
3. See the cart is missing button

**Expected behavior**
Dependencies should be taken into account when using the DJE GUI.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2202518569/411771/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
