### ISSUE TITLE
Login and Register Piotnet Addons for Elementor

### ISSUE THREAD

**Issue by tw593ec** [wp-media/wp-rocket#5861]
**Describe the bug**
When a user is not logged in I could not see the internal page the problem is the following, when wp rocket is active everything works fine apparently, but when the user logs in the page reloads quickly and redirects him to the home page.

But instead of seeing the internal page only for users who are logged in, the user continues to see the page as if he had not logged in, if he reloads the page it still does not work, but if the browser cache is cleared it appears as if he is already logged in How can I solve this problem if the form is a piotnet addos for elementor form.

**NOTE:** I already tried to exclude the personalized login page and the registration page because the same thing happens when someone registers, it appears that they did not access, but even if it is excluded it does not work, it still appears as if they did not login.

**Expected behaviour**
When someone logs in or registers they should be able to see the home page with the internal information that only logged in users can see.

**Additional context**
The issue only seems to affect forms created with piotnet addos for elementor fields.

**Comment by piotrbak** [comment]
Hello @tw593ec thanks for creating the issue. Could you tell me if you've already contacted our Support Team about this issue? It'll allow us to find the root cause and eliminate any 3rd-party connections.

**Comment by tw593ec** [comment]
> Hello @tw593ec thanks for creating the issue. Could you tell me if you've already contacted our Support Team about this issue? It'll allow us to find the root cause and eliminate any 3rd-party connections.

So far, I haven't contacted support as I've been trying to find a solution on my own through this medium. I hope to be able to resolve the issue by myself, as I believe it may be simple and not require support intervention. However, if I'm unable to resolve it with their guidance through this medium, then I will contact them and present the problem.

I would appreciate your help at this time with this problem that appears to be related solely to the Piotnet Addons for Elementor plugin. I've tested Elementor's login form, and it works well, but Piotnet allows for creating fields to design my own form in a more personalized manner. That's why I'm interested in finding a solution to this problem.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
