### ISSUE TITLE
wp-config.php file permissions are changed after we make modifications to it

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5863]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When we write the **wp-config.php** file, we change the permissions to 0644. In some cases, customers might want to reset the permissions to their previous state. 

**To Reproduce**
1. With WP Rocket disabled
2. Set **wp-config.php** permissions to 0640
3. Enable WP Rocket
4. The permissions will be changed to 0644

**Expected behavior**
We could roll back to the previous permission.
As an alternative, we could just add an action hook after we finished writing the config files, where users can hook a function to change the permissions back to their desired value.

**Additional context**
Ticket: 
https://secure.helpscout.net/conversation/2198230757/410983?folderId=2683093

Slack convo:
https://wp-media.slack.com/archives/C43T1AYMQ/p1680524459988019

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.

**Comment by thekendog** [comment]
I submitted the original ticket.  I have wp-config.php set to 600 for security reasons.  When WP Rocket edits it the permissions are changed to 644.  It should first look at what the current permissions are.

**Comment by piotrbak** [comment]
Hello @thekendog 

Yes, since 10th of April 2023 we received only one feedback from our customers about this problem, which is yours. We're currently clearing our backlog a little bit by closing issues that will not be solved in the midterm. However, please keep in mind that it doesn't mean that the issue will never get resolved. We'll reopen it if we receive more feedback or we'll be releasing minor version oriented on the similar topic. Thanks for understanding.

**Comment by thekendog** [comment]
Well that's a bummer.  Most people don't know to look for this.

**Comment by piotrbak** [comment]
Whenever we'll be working on the minor related to the filesystem or htaccess itself, we'll be discussing this issue as a potential enhancement.
