### ISSUE TITLE
[2.11-alpha2]: Saving settings opts in to analytics

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#587]
Currently, when a person ignores the analytics prompt and just proceeds to edit their settings,  the first saving of settings seems to opt them in to analytics. (Thank-you notice displayed afterwards, option in _Tools_ tab is now checked.)

The expected behaviour instead would be that the analytics prompt just remains visible until a person would click any of the 2 buttons to accept or decline.

**Comment by glueckpress** [comment]
Update: Seems a glitch with the _Optimize CSS_ option. Whenever I activate that option, I’m opted in to analytics and see the thank-you message in addition to the status notice about critical CSS.

**Comment by Tabrisrp** [comment]
Fixed by PR #597
