### ISSUE TITLE
Add missing image dimensions isnot working probably with specific markup

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5878]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.13.0.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When image is having src and srcset, we are using src dimensions instead of srcset while displayed image is that at the srcset

**To Reproduce**
1. Having page template with img having src and srcset `<img src="<?php echo content_url().'/rocket-test-data/images/fixtheissue.jpg' ?>" height="" width="" srcset="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/783px-Test-Logo.svg.png">`
2. Enable add missing image dimensions
3. open the page template and compare to ?nowprocket

**Expected behavior**
Dimensions match with nowprocket (UI is as same as nowprocket)

**Screenshots**

**Additional context**
- Thanks to @mostafa-hisham for the root cause here
- Test page https://new.rocketlabsqa.ovh/image_template_001

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
