### ISSUE TITLE
Emphasize which feature are the scripts excluded from on each JS exclusions box

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5881]
**Is your feature request related to a problem? Please describe.**
Some users get confused about which is the right exclusions box of each JS feature.

**Describe the solution you'd like**
We could put part of the descriptive text in bold, like below:

![wpr-file-optimization-js](https://user-images.githubusercontent.com/26235782/233161904-097705bf-c4b6-496e-91c7-f5818a7b7f12.png)

**Describe alternatives you've considered**
N/A

**Additional context**
HS related ticket: https://secure.helpscout.net/conversation/2213996786/414428/

**Comment by camilamadronero** [comment]
This could be applied to the invalid patterns of exclusions notice:

![image](https://user-images.githubusercontent.com/122890317/235264932-e75cbb68-5bc9-4969-8bd8-dfb1f474e826.png)


Example of new texts:

- `Excluded JavaScript Files` To `Minify/Combine JavaScript files exclusion`
- `Excluded Inline JavaScript` To  `Combine JavaScript files inline exclusion`
- `Defer JavaScript Files` To `Load JavaScript deferred exclusion`
- `Excluded Delay JavaScript Files` To `Delay JavaScript execution exclusion`

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
