### ISSUE TITLE
Better Compatibility With SpinupWP

### ISSUE THREAD

**Issue by thekendog** [wp-media/wp-rocket#5882]
**Is your feature request related to a problem? Please describe.**

I just switched to SpinupWP for hosting.  In my existing code, I used the `rocket_clean_home` and `rocket_clean_post` functions to clear the cache for the home and certain pages after certain things happen.  Based on the info page on the WP Rocket website which states 'Cache purging is synchronized between WP Rocket and SpinupWP's cache', I assumed this would work.  However, it appears that the only function that is synchronized is the `rocket_clean_domain ` function.  Thus, my pages were not being cleared from the SpinupWP cache properly.

**Describe the solution you'd like**

Include the `after_rocket_clean_home` and `after_rocket_clean_post` action hooks in the compatibility and use the `spinupwp_purge_post` or `spinupwp_purge_url` functions to properly clear the page cache for the page.

**Comment by piotrbak** [comment]
Closing it in favour of:
https://github.com/wp-media/wp-rocket/issues/6033
