### ISSUE TITLE
Add To Cart and Checkout Sometimes Not Working While Preload Links enabled

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#5883]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When adding an item to the WooCommerce cart and then proceeding to checkout, the item added is no longer in the cart for checkout.

The user reports it must be an item you've not added before, and also that the issue only occurs sporadically.

Ahmed has already done some testing this and found that disabling the `Enable Link Preloading` is disabled, the issue no longer happens.

**To Reproduce**
1. Make sure Enable Link Preloading option is enabled
2. Go to a page like https://ueliexpress.ch/ueliestage/produkt-kategorie/apple-zubehoer/ (staging site is being used for testing because WP Rocket is disabled on production)
3. Hover over an item and click the cart icon to add to cart
4. Click 'KASSE' to go to check out
5. It doesn't happen every time, but when it does, you will be taken to a checkout page saying there are no items in the cart

**Expected behavior**
The checkout process should work normally with all the items a person has added.

**Active Theme**
Woodmart

**Active Plugins**
301 Redirects Pro
ATUM Inventory Management for WooCommerce
Barcode Label Printing for WooCommerce and others plugins - (basic)
Classic Widgets
Coinbase Commerce For WooCommerce
Contact Form 7
Converter for Media
Customer Reviews for WooCommerce
Customer Reviews for WooCommerce PRO
Disable Cart Fragments
Fraud Prevention For Woocommerce
GA Google Analytics
GTranslate
Loco Translate
mame TWINT for WooCommerce
mame WebStamp for WooCommerce
PDF Invoices & Packing Slips for WooCommerce
PixelYourSite PRO
PixelYourSite Super Pack
Product Feed PRO for WooCommerce
Purchased Items Column WooCommerce
Really Simple SSL
Really Simple SSL Pro
reCAPTCHA for WooCommerce
Slider Revolution
Slider Revolution Bubblemorph AddOn
Slider Revolution Mousetrap Add-On
Slider Revolution Transitionpack Add-On
UpdraftPlus - Backup/Restore
WooCommerce
WooCommerce Extra Fees Plugin
WooCommerce Orders & Customer exporter
WooCommerce PayPal Payments
WooCommerce Stripe Gateway
Woodmart Core
Wordfence Security
WP Downgrade | Specific Core Version
WP File Manager
WP Rocket
WP Rocket | Deactivate WooCommerce Refresh Cart Fragments Cache
WP Rollback
WPBakery Page Builder
Yoast SEO
Yoast SEO Premium
Yoast SEO: WooCommerce

**Additional context**
https://secure.helpscout.net/conversation/2160191527/401959/
https://wp-media.slack.com/archives/C43T1AYMQ/p1680589677084819
https://wp-media.slack.com/archives/C43T1AYMQ/p1681465535232939
https://wp-media.slack.com/archives/C43T1AYMQ/p1681998798196959

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria
- Cart - Checkout relation should be working correctly in all cases when using Preload Links feature
- Preload Links feature should be able to [exclude URLs](https://github.com/wp-media/wp-rocket/blob/98a11540dc19c3ae598d7361e0b7ecee79045df9/inc/Engine/Preload/Links/Subscriber.php#L197) without regression and don't preload 
- Preload Links feature should not preload `Never Cached URLs` and specific [extensions](https://github.com/wp-media/wp-rocket/blob/98a11540dc19c3ae598d7361e0b7ecee79045df9/inc/Engine/Preload/Links/Subscriber.php#L135)

**Comment by joejoe04** [comment]
User wrote back to let us know they needed to delete the staging site, but they also confirmed that the issue was resolved for them while the Preload Links option is disabled.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
