### ISSUE TITLE
Add gad to ignored parameters

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5888]
Google Ads has started to use a new parameter to track clicks from ads:
`gad`

**Describe the solution you'd like**
We could add this to our list of automatically ignored parameters

**Describe alternatives you've considered**
It can be done with our helper plugin, but this requires work from our users. 

**Additional context**
Reported by a customer here: 
https://secure.helpscout.net/conversation/2222987194/416132?folderId=377611

Google article: 
https://support.google.com/google-ads/answer/13327296

**Comment by piotrbak** [comment]
Done with he backend 👌
