### ISSUE TITLE
[2.11-alpha2]: Critical CSS notices on local site

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#589]
Am testing on a local .dev installation, but I was told that critical css was being generated:

![wp_rocket_ _wordpress_themes_ _wordpress](https://user-images.githubusercontent.com/1043076/33233465-1a79ef0a-d1cb-11e7-943f-2c884f9f80e1.jpg)

**Comment by Tabrisrp** [comment]
What would be the ideal behaviour from the plugin in this case?

**Comment by webtrainingwheels** [comment]
In general, notices should reflect what's actually happening. 
So in this case, something like 'critical css cannot be generated because the site is not publicly accessible. '
And in other cases, if it's not already like this,  the notice should reflect the issue....'your site is in a queue', 'the css service is down' etc.
