### ISSUE TITLE
Delay JavaScript Execution exclusions with a `(` as part of them are not working

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5898]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.13.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If an exclusion requires having something like `document.getElementById("comment")`, it won't match the target script. 

The reason for that is the entry is a regex, and should have the `(` and `)` escaped. 

And it's not taken into consideration when we sanitize the exclusions list: 

https://github.com/wp-media/wp-rocket/blob/8984fd0a8724ff8d5dd2d177e38cc50a7eab6b12/inc/Engine/Optimization/DelayJS/HTML.php#L115-L119

It could be complicated to just escape `(` and `)` as we propose to use `(.*)` as part of the exclusions pattern. 

We could maybe narrow it to problematic patterns by adding: 

`("`, `('`, `")`, `')` 

to be escaped: 

`\("`, `\('`, `"\)`, `'\)`

We can do the same for `[` and `]` and proceed with the same logic.

**To Reproduce**
1. Use a script containing something like `document.getElementById("comment")`
2. Try to exclude that specific pattern from Delay JavaScript Execution.
3. See that it was not excluded

**Expected behavior**
Using escapable characters shouldn't create any issues when used with Delay JavaScript Execution. 

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@DahmaniAdame Wouldn't proper documentation be enough in this case?

I remember we were dealing with this already when implementing UI for Delay JS. Some techniques were tried and we were always getting in troubles. Later on we had another try which caused reqgressions, as touching the sanitization of existing values is tricky. At the end we left it as it is.

Not sure how that impacts the support though.

**Comment by DahmaniAdame** [comment]
@piotrbak Most of our customer base is non-tech-savvy and would hit the support on the first challenge. 

Finding an exclusion is fairly challenging. What makes it doable is that there is no extra processing required. You just take a value as seen on the source code and add it. 

Asking them either through the UI or documentation to keep an eye on manually sanitizing specific values will be dissuasive even for them to try to start finding an exclusion. 

We should make it the easiest possible for customers to use exclusions.

Most exclusion will use a keyword. This effort is to ensure we do take into consideration escapable characters, and not just some of them, and prevent opening tickets if an escapable character is involved on the exclusion as it won't work.

If it proves too costly or risky to implement, we can leave it as it is without further instructions and review if we get more cases.

If we go that road, we should make sure support agents are aware of the limitation and keep an eye on escapable characters on patterns reported to not have an effect to quickly wrap related tickets. Ping @stathopoulosgeorge in such a case.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
