### ISSUE TITLE
[2.11-alpha2]: Critical CSS UI notices 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#590]
**1. Completion Notice**
current text: "Critical CSS generation finished: x of x critical CSS generated"
proposed change: "Critical CSS generation finished for x of x page types"

**2. Option text**
![wp_rocket_ _wordpress_themes_ _wordpress](https://user-images.githubusercontent.com/1043076/33233512-ca602d6c-d1cb-11e7-9798-0ccb0c22c37e.jpg)
Needs additional text such as: 
Critical path CSS will be automatically generated. More info [link to doc]

**Comment by webtrainingwheels** [comment]
"Currently running" notice. 
Current text: "Critical CSS generation is currently running: 0 of 4 critical CSS generated."

Proposed: "Critical CSS generation is currently running:  x of x page types completed. (Refresh this page to view progress)"

**Comment by Tabrisrp** [comment]
Fixed by d011add

**Comment by webtrainingwheels** [comment]
The text on Optimize CSS is missing the info link - can use this because we will just update this doc: 
http://docs.wp-rocket.me/article/108-render-blocking-javascript-and-css-pagespeed#critical-path-css
