### ISSUE TITLE
Trailingslash prevents WP Rest API from being cached

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#5900]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When using [our helper plugin](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-rest-api) which allows caching WP Rest API and permalinks has trailing slash so this blocks the following url from being cached at all:

```
http://example.com/wp-json/wp/v2
```

and to make it works we add the trailing slash for those RestAPI urls like:
```
http://example.com/wp-json/wp/v2/
```

the line that blocks it from being cached is:

https://github.com/wp-media/wp-rocket/blob/0300a74643a97932214478df4a49fee39fc37b2f/inc/classes/Buffer/class-cache.php#L79-L81

**To Reproduce**
1. Activate [our helper plugin](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-rest-api)
2. Visit any WP Rest API url like http://example.com/wp-json/wp/v2
3. Check the cache directory
4. You will not find this json url cached
5. Visit the same url but by adding trailing slash to it like http://example.com/wp-json/wp/v2/
6. Check cache directory
7. You will find it's cached

**Expected behavior**
I think WP Rest API needs to be excluded from this bailout so it can be cached if this helper is used

**Additional context**
Slack discussion: https://wp-media.slack.com/archives/C43T1AYMQ/p1682629639240929 

Through this discussion, @joejoe04 tried a good solution related to force redirect the urls from not trailingslash to the trailingslash one by using a helper plugin and this worked like a charm.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria
- When using the [helper plugin](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-rest-api) both versions, with and without `/` should be cached
- Other trailing slash redirections inside the plugin should not be affected
- Custom Rest API prefix is not redirected, the scope of this PR is only related to `/wp-json/`. If we see that setting custom Rest API route is being set often, we'll need to create option in our config file to store its value.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem

### Identify the root cause ✅
Exactly like @engahmeds3ed stated.

### Scope a solution ✅
We can simply do an early return when the helper plugin is activated and API urls like that are accessed in https://github.com/wp-media/wp-rocket/blob/3bd3350cd0cf95c5b0f124643d634d9e45f01c54/inc/classes/Buffer/class-cache.php#L752

```
if (! preg_match( '#wp\\-json#', $this->config->get_config( 'cache_reject_uri' ) ) && preg_match( '#wp-json/wp/v[0-9]+(/|)$#', $this->tests->get_request_uri_base() ) ) {
    return false;
}
```
### Estimate the effort ✅
[XS]

**Comment by vmanthos** [comment]
A comment for QA. 

The steps Ahmed described require a `/` to be there in the permalinks. If there isn't, REST API caching works as expected if the REST URI doesn't have a trailing `/`.

**Comment by piotrbak** [comment]
Yes, the problem is that before 3.13 both versions were cached, and WordPress doesn't offer redirection on its own :(

**Comment by DahmaniAdame** [comment]
Temporary fix for this one until the update is released - https://drive.google.com/file/d/19sFnP9NX5van86ZGI-nKmm8tlpVGYa9C/view?usp=sharing
