### ISSUE TITLE
[2.11-alpha2]: Minification + Remove query strings do not work together

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#591]
When either of CSS or JS minification is active at the same time as Remove query strings, this happens: 
![wordpress_themes_ _just_another_wordpress_site](https://user-images.githubusercontent.com/1043076/33233828-7cfb8912-d1d1-11e7-9cff-9533495e56bd.jpg)

In this screenshot JS is broken, but only CSS min is activated.

In the below, JS min is activated, not CSS: 

![wordpress_themes_ _just_another_wordpress_site](https://user-images.githubusercontent.com/1043076/33233845-d45855e6-d1d1-11e7-9ae3-5796ef9c4565.jpg)

**Comment by Tabrisrp** [comment]
Fixed by 476bff7
