### ISSUE TITLE
Sanitize alt text for Replace YouTube iframe with preview image

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#5910]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes, 3.13.2
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
The [new `alt` text](https://github.com/wp-media/wp-rocket/issues/5127) for the Replace YouTube iframe with preview image feature is not sanitized, and the markup can break if the title of the video contains characters 

**To Reproduce**
1. Enable **Replace YouTube iframe with preview image** on WP Rocket **3.13.2**
2. Post a YouTube video whose title includes `"`
3. The` img` tag will include an `alt` text with the `"` character, breaking the markup

**Screenshot:** https://jmp.sh/svdopINg
**Test URL:**  https://camila.com.co/chao/
**Video URL:** https://www.youtube.com/watch?v=L2HL-ZCst50&embeds_euri=https%3A%2F%2Fwphangar.com%2F&source_ve_path=MjM4NTE&feature=emb_title
Broken markup: 
```
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
	<div class="rll-youtube-player" data-src="https://www.youtube.com/embed/L2HL-ZCst50" data-id="L2HL-ZCst50" data-query="feature=oembed" data-alt="SURF CURSE - &quot;Untitled&quot; (Live in Coachella Valley, CA 2017) #JAMINTHEVAN"></div><noscript><iframe title="SURF CURSE - &quot;Untitled&quot; (Live in Coachella Valley, CA 2017) #JAMINTHEVAN" width="750" height="422" src="https://www.youtube.com/embed/L2HL-ZCst50?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></noscript>
	</div></figure>
```

**Expected behavior**
The title text should be sanitized before being added to the `alt` attribute.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1683575634732479

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
- We need to be sure that `'`, `"` and special characters inside the YouTube video title are not breaking the markup
