### ISSUE TITLE
Dynamic lists one-click list to check the same case to populate the UI

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5915]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.13.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WP Rocket builds the one-click DJE exclusions, we are testing a `lowercase` `$plugin->condition` entry without making sure the array `$active_plugins` contains only lowercase items as well.

```
foreach ( $this->get_plugins_from_list() as $plugin_key => $plugin ) {
	if ( ! in_array( strtolower( $plugin->condition ), $active_plugins, true ) ) {
		continue;
	}

	$full_list['plugins']['items'][] = [
		'id'    => $plugin_key,
		'title' => $plugin->title,
		'icon'  => $this->get_icon( $plugin ),
	];
}
```

We do that here: 

https://github.com/wp-media/wp-rocket/blob/408433f0e4615b6226711cd9d91df2228d70cf2e/inc/Engine/Optimization/DelayJS/Admin/SiteList.php#L223

And here:

https://github.com/wp-media/wp-rocket/blob/408433f0e4615b6226711cd9d91df2228d70cf2e/inc/Engine/Optimization/DelayJS/Admin/SiteList.php#L509

This causes plugins with capital names to not match `in_array` against `$active_plugins`. 

Like `Ultimate_VC_Addons/Ultimate_VC_Addons.php`

We can either drop `strtolower` from `strtolower( $plugin->condition )` or make sure `$active_plugins` has all lowercase items by wrapping it inside `array_map('strtolower', $active_plugins)`. 

Will leave it to QA to decide the best approach. 

**To Reproduce**
1. Use a plugins with a capital name as part of its folder/main file.
2. Use DJE and make sure it's part of the dynamic lists.
3. See that the plugin won't show up on the one-click exclusions UI.

**Expected behavior**
We should reflect accurately the activated plugins on the website.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2231417008/417832?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@piotrbak this should be prioritized. 
It can be fixed quickly and will avoid tickets and/or customers not seeing one-click exclusions when they should.

**Comment by piotrbak** [comment]
@engahmeds3ed Do you remember what was the reason to use `strtolower` here?

For themes I can see that we're comparing it correctly to lowered version:
https://github.com/wp-media/wp-rocket/blob/b2f0b8f870002148959cb3d28a62671489ac7228/inc/Engine/Optimization/DelayJS/Admin/SiteList.php#L171

@DahmaniAdame Do you think we should involve QA to make that kind of decisions? It would at least double the effort here.

**Comment by DahmaniAdame** [comment]
@piotrbak it looks straightforward. But let's hear what @engahmeds3ed comment about `strtolower` and decide.

There is another concern I just spotted. WordPress would activate the same plugin if using different folder case names. Assuming this is done and somehow doesn't trigger a fatal error, we will end up showing two of the same item if we pre-process things to lowercase. 

I wonder if using `strtolower` was somehow meant to tackle that?

**Comment by piotrbak** [comment]
@engahmeds3ed Whenever you have some time, could you please check this one?

**Comment by engahmeds3ed** [comment]
mainly we used `strtolower` because we found some data entry problems from our backend side so we needed a way to make it more consistent.

So we have three options here that I can think of:
1. As @DahmaniAdame mentioned above we can apply strtolower on all active plugins array items.
2. Convert active plugins array into a string concatenated by `|` and search using regex using the current plugin name here we will need to use `i` modifier.
3. Make sure that the data inside our backend are totally correct so we can remove this constraint from the code.

What do u think?

**Comment by DahmaniAdame** [comment]
@engahmeds3ed thanks for your feedback. 

Option `1` will have the following risk: 

> WordPress would activate the same plugin if using different folder case names. Assuming this is done and somehow doesn't trigger a fatal error, we will end up showing two of the same item if we pre-process things to lowercase.

Low occurrence, but it can still happen and will result in a ticket. 

Sounds like option `3` can be a good one, with a process for support agents to make sure entries on the backend are accurate, possibly a field validation for a specific pattern, to lower the risk of a mismatch.

That would make option `1` valid if we removed `strtolower` and tested the same case.

What do you think?

For this part: 

https://github.com/wp-media/wp-rocket/blob/408433f0e4615b6226711cd9d91df2228d70cf2e/inc/Engine/Optimization/DelayJS/Admin/SiteList.php#L221-L232

We go straight to iterate on the `$this->get_plugins_from_list()` using `foreach`. 

Wouldn't it be best to check if there is an intersection first, and then proceed with a `foreach` only for intersecting elements? 

Something like: 

```
$active_dynamic_matches = array_intersect_key(
    $this->get_plugins_from_list(),
    array_filter($this->get_plugins_from_list(), function ($value) use (
        $active_plugins
    ) {
        return in_array($value["condition"], $active_plugins);
    })
);

if ($active_dynamic_matches) {
    foreach ($active_dynamic_matches as $plugin_key => $plugin) {
        $full_list["plugins"]["items"][] = [
            "id" => $plugin_key,
            "title" => $plugin['title'],
            "icon" => $this->get_icon($plugin),
        ];
    }
}
```

**Comment by engahmeds3ed** [comment]
> Sounds like option 3 can be a good one, with a process for support agents to make sure entries on the backend are accurate, possibly a field validation for a specific pattern, to lower the risk of a mismatch.

This is the simplest solution for me :D but what is the specific pattern u meant here? u can't force it here to be lowercase again.

> Wouldn't it be best to check if there is an intersection first, and then proceed with a foreach only for intersecting elements?

We thought about that before and the problem is that `array_` are loops in themselves :D so in ur code we will do two loops but the current code will do it once and that's better.

References:

https://www.levijackson.xyz/posts/are-array_-functions-faster-than-loops/
https://www.jetbrains.com/help/phpstorm/php-array-filter-call-can-be-converted-to-loop.html

**The common rule is : Simple code, run faster (imply less check, less functionality, as long as it has all you need)**

**Comment by DahmaniAdame** [comment]
Got it 👍

> what is the specific pattern u meant here?

I was thinking of imposing that it doesn't start with a `/` and ends with a `.php`. This can be done with JS on the backend while adding an entry. 

Just to avoid that particular mismatch. 

The path case will remain as is, as existing on the excluded plugin. If it's capitalized, it will be entered on the backend as such. If it's lowercase, it will be added on the backend as such.

That will guarantee it matches the paths tested on `$active_plugins`.

**Comment by engahmeds3ed** [comment]
OK those are good constraints but the main problem will still there ( if we took the third solution of removing using strtolower at all for plugins and themes ) because it's case sensitive so if u wrote it in backend as `plugin` and it was `Plugin`.

So it's a final decision that we will take solution number 3, right? I'll groom based on that and add a critical bold comment that we need to make sure that all data entered in backend is valid from case sensitivity perspective.

Correct?

**Comment by DahmaniAdame** [comment]
Sounds good to me. 
@piotrbak what do you think?

**Comment by piotrbak** [comment]
Yes, I agree with the case sensitive solution. Data I was adding during the 3.13 is correct for sure, but I don't know about the ones that are added later. It needs to be confirmed.

I'll add a bolded reminder in the template of the issue.

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. We'll go with the 3rd option mentioned [here](https://github.com/wp-media/wp-rocket/issues/5915#issuecomment-1553074217).
2. WP Rocket will recognize capital letter plugin's condition from saas correctly (`Ultimate_VC_Addons/Ultimate_VC_Addons.php`)
3. WP Rocket will still recognize lower case plugin's condition from saas correctly

**Comment by remyperona** [comment]
@piotrbak If I understand correctly, we're going to remove the strtolower() usage in the plugin side, and do updates on the backend side?

**Comment by piotrbak** [comment]
@Tabrisrp Yes. I just saw that @engahmeds3ed created a PR for that. For any reason it was moved back to To-do

The PR seems to be touching what we need.
