### ISSUE TITLE
When user sign in and click homepage or go to another page, lost previous session

### ISSUE THREAD

**Issue by vanloc0301** [wp-media/wp-rocket#5917]
**WP Rocket 3.13.2:**

**Describe the bug**
User lost session was login when click to homepage or product page after sign in success.

**To Reproduce**
1. Open the new private Chrome or Edge or Firefox.
2. Go to 'https://xomkey.com/my-account'
3. Sign in with username: xomkey@gmail.com / pass: Xomkey.com@PIN20
4. After sign in success, click to homepage. The user information was login is lost session.

**Video test**
https://youtu.be/daB3vaQo9PQ

**Comment by piotrbak** [comment]
Hello @vanloc0301 Could you please contact our Support Team about this problem?
