### ISSUE TITLE
[2.11-alpha2]: plugins screen clear cache text

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#592]
After deactivating/ reactivating plugins, current text: 
One or more extensions have been enabled or disabled, clear the cache if necessary.

proposed change: 
One or more plugins have been enabled or disabled, clear the cache if they affect the front end of your site.

Basically, give some clue as to how to decide if you need to clear the cache or not.

**Comment by glueckpress** [comment]
I think the notice goes for themes and plugins which may be why it says “extensions”. I get the point, though, great feedback!

**Comment by webtrainingwheels** [comment]
I wondered about that too, but we automatically clear the cache when the theme is switched. Just tested updating a theme and we do not show a notice after that.

**Comment by Tabrisrp** [comment]
We know a switching theme will necessarily have an impact on the front, so it's cleared automatically, but for a plugin it depends. The wording change makes sense to be more explicit.

**Comment by Tabrisrp** [comment]
Update made in 0d61e1a
