### ISSUE TITLE
Shared Vision plugin doesn't load

### ISSUE THREAD

**Issue by matesv** [wp-media/wp-rocket#5921]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - DONE
- Used the search feature to ensure that the bug hasn’t been reported before - DONE

**Describe the bug**
When installing the Shared Vision plugin, the plugin works on the admin side, but it doesn't show up on the page.

**To Reproduce**
1. Install the Shared Vision plugin
2. Go to the frontend and nothing loads
3. If you add ?sharedvision to the URL, the script loads

**Expected behavior**
The plugin should load just as it does on sites without WP Rocket.
We'd like to request adding our plugin to the WP Rocket default exclusion list, so we don't have to pull our customers off of your otherwise great solution.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
