### ISSUE TITLE
Prevent loading the Logger classes if WP_ROCKET_DEBUG is not enabled

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5923]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.13.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Multiple `Logger` classes are loaded on the `advanced-cache.php` file. 

https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/views/cache/advanced-cache.php#L33-L52

Since logging WP Rocket only happens when the `WP_ROCKET_DEBUG`, we should make loading all related classes conditional to that. 

The impact on performance won't be significant, but it's still not 

**To Reproduce**
N/A

**Expected behavior**
WP Rocket shouldn't load code/libraries not being used.

**Screenshots**
N/A

**Additional context**
Slack - https://wp-media.slack.com/archives/C43T1AYMQ/p1684220879897639?thread_ts=1684217755.309949&cid=C43T1AYMQ

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. Logger classes loaded only if the constant is set
2. Logger working without regressions

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Load classes conditionally in https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/views/cache/advanced-cache.php:
`if ( rocket_get_constant( 'WP_ROCKET_DEBUG', false ) ) {`
      https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/views/cache/advanced-cache.php#L31-L58
`} `

### Estimate the effort ✅
[XS]

**Comment by remyperona** [comment]
`rocket_get_constant()` function is not available at the time advanced-cache.php is loaded. But the logic is the same, using the core PHP `defined()` function instead.

**Comment by jeawhanlee** [comment]
@Tabrisrp Many Thanks 🙏

**Comment by MathieuLamiot** [comment]
Following [the post-mortem](https://www.notion.so/wpmedia/Useless-implementation-for-wp-rocket-5923-8cf52b6c33d546bc80f7c36ffa43784a), we agreed to:
- drop the current implementation
- Put back the task to "Needs grooming"
- When grooming is started by a software engineer, it will be important to discuss added value vs. technical cost ie. is the added value worth the technical cost (like maintainability & codebase logic/quality)?

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
