### ISSUE TITLE
Lazyload: Uncaught TypeError: Assignment to constant variable when a constant with the same name as some variables is declared

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#5925]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
This issue is very similar to this other: #3976, but it is happening with other variables.

In this case the variables are: images, is_image, iframes, is_iframe.

Since they are not being explicitly declared, when there is any constant globally declared with the same name, an error occurs. In case there are any other variable globally declared with the same name, we simply overwrite it (it can cause different issues).

They can be found here: https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/inc/Dependencies/RocketLazyload/Assets.php#L142 

Proposed solution:

Since those variables are being used only in one context, they should be declared in the scope they are going to be used with the "let" keyword.

Something like this:

`

                            let images = mutation.addedNodes[i].getElementsByTagName(\'img\');
                            let is_image = mutation.addedNodes[i].tagName == "IMG";
                            let iframes = mutation.addedNodes[i].getElementsByTagName(\'iframe\');
                            let is_iframe = mutation.addedNodes[i].tagName == "IFRAME";
`

I tested this, and it fixes the issue without affecting the operation of the Lazyload feature.

**To Reproduce**
- Add a code as the example below to the website :
`<script> const images = []; </script>` (You can do the same for is_image, iframes, is_iframe)
- Activate Lazyload
- Clear the cache
- Check the browser's console

**Expected behavior**
Lazyload script shouldn't conflict with other scripts that use variables / constants with these names.

**Screenshots**
![image](https://github.com/wp-media/wp-rocket/assets/13713107/979516b8-93dc-427a-a18e-ec7ce00b01e1)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Comment by markonikolic985** [comment]
Related case - https://secure.helpscout.net/conversation/3195576841/614434?viewId=424682
