### ISSUE TITLE
Safeguard CPCSS from invalid `rocket_cpcss_items` items

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5928]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

The case was specific to taxonomies, but it can also be applied to custom post types as well. 

The items CPCSS is trying to get CPCSS for had an entry on the database, but somehow, they do not exist on the front end. 

When the item is passed to `get_cache_key_from_url` if it passes `$item_url` as `object` (expecting a `string`), which causes the following error: 

```
An error of type E_ERROR was caused in line 192 of the file /wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/DataManager.php. Error message: Uncaught TypeError: md5(): Argument #1 ($string) must be of type string, WP_Error given in /public_html/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/DataManager.php:192
```

https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/inc/Engine/CriticalPath/DataManager.php#L191-L199

And the CPCSS for these items is not created. 

For that specific case, we need a way to automatically get the next valid taxonomy term when running `get_public_taxonomies`. 

https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/inc/Engine/Optimization/ContentTrait.php#L76-L123

That way, we don't have a miss. 

**To Reproduce**
1. Use CPCSS
2. Make sure that the sampled taxonomy term is not valid
3. See the error

**Expected behavior**
We should automatically find the right items to process for CPCSS and skip invalid ones. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2240643134/419581/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
