### ISSUE TITLE
Check if assets have a valid CDN counterpart before rewriting the URL

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5937]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When we proceed to rewrite assets with the CDN CNAME, we don't check if the asset on the CDN is valid. 

Since WP Rocket is not the one doing the upload to the CDN, we need to check if the replacement URL either: 
- Returns a 200 response (faster)
- The file size is the same as the original URL (more accurate)

The check needs to be done here: 

https://github.com/wp-media/wp-rocket/blob/10e82c0af9670f20b48150a89d858108ee2834a1/inc/Engine/CDN/CDN.php#L125-L159

**To Reproduce**
1. Enable WP Rocket CDN
2. Make sure an asset is not uploaded to the CDN
3. See error

**Expected behavior**
Using WP Rocket shouldn't cause 404 errors if the asset doesn't exist yet on the CDN.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2247491187/420711/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by precisefuture** [comment]
I think checking that the image size is the same may be a problem. Any user using cdn where image optimization is done on the CDN will have different sizes of images

**Comment by piotrbak** [comment]
@DahmaniAdame Just to confirm:
1. For each resource that we're rewriting, we'll do a request to check headers.
2. If that's going to be a HEAD request, do you know how it combines with the PULL type of CDN? (what I mean here is, if making a HEAD request will pull the resource to CDN, so the next check will be 200?)

**Comment by DahmaniAdame** [comment]
@precisefuture These were just some possible ways to do the check I had on the top of my mind while checking the related ticket.

It's not final. 
 
But I agree that the size would be problematic to base the check on. 

@piotrbak 

1 - Yes. There is no way around it. 
2 - The `200` response might not be the best option as we don't control how things are configured on the CDN side. 

Comparing the size will not be a good option, as well as we can't know for sure if there is some kind of processing/minification on the CDN side.

I'm thinking of a HEAD request and checking the `content-type`. 

If the response contains one of these `['javascript', 'css', 'image']`, we give it a pass. If not, we don't do the CNAME replacement. 

It should be enough without having to test the specific extension with its specific content type (since we manage 3 types of assets), while still being fast and accurate and not depending on how CDNs process cached/missing assets. 

@engahmeds3ed might have a learner approach/way to handle that.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
