### ISSUE TITLE
Optimize CSS Delivery more info link when disabled on local site is broken

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5938]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.13.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clicking the more info link at OCD notice `Optimize CSS Delivery features are disabled on local environments. [Learn more]` => link is broken at beacon

**To Reproduce**
1. Install and activate WPR on a local site
2. open the file optimization tab and click the more info link for OCD

**Expected behavior**
The link is not broken

**Screenshots**
![Screenshot from 2023-05-23 12-03-39](https://github.com/wp-media/wp-rocket/assets/76941962/7a5a75f0-8b5d-4515-aa14-0659721ec74f)

**Additional context**
As per [Slack discussion](https://wp-media.slack.com/archives/C02QL83AYUT/p1684832747615649)
- En Link is https://docs.wp-rocket.me/article/1514-private-intranet-offline
- Fr Link is https://fr.docs.wp-rocket.me/article/1521-utiliser-wp-rocket-sur-un-intranet-prive-ou-hors-ligne

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
This was an issue with the Beacon configuration on Helpscout, I fixed it for both EN and FR versions.
