### ISSUE TITLE
[2.11-alpha2]: version number stripped from excluded css file

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#594]
Activate CSS and JS minification and Remove Query strings. 
Exclude a file from minification, e.g. 
http://www.lucybeer.com/sub/wp-content/themes/twentyfifteen/style.css?ver=4.8.3

Ends up as this on front end: 
http://www.lucybeer.com/sub/wp-content/themes/twentyfifteen/style.css

Only seems to be an issue with CSS, excluding a JS file worked as expected.

**Comment by Tabrisrp** [comment]
When the `ver` value is the same as the WP version, it's removed, this is the same behaviour since we added remove query strings option.

**Comment by webtrainingwheels** [comment]
Ah, my bad! Sorry about that
