### ISSUE TITLE
[2.11-alpha2]: Minify/ Combine options errors

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#595]
— When CSS minification is enabled, JS minification is applied

—  When JS minification is enabled, CSS minification is applied

— Combine CSS and JS not being applied if they are enabled individually (works if both are enabled)

— Files in cache/min folder not cleared on server after option is disabled or cache is cleared (not sure if this is default behavior of new library?)

**Comment by Tabrisrp** [comment]
This is fixed by 476bff7

Last point is the same behaviour as before
