### ISSUE TITLE
Invalid URLs are added to the cache table

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5950]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13.3`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark:

**Describe the bug**

When URLs like the following:
* `/`
* `https://example.com/#`

are passed to the Preload feature, they are added in the `wpr_rocket_cache` table and their status eventually becomes `failed`. When `rocket_preload_revert_old_failed_rows` fires this will be reverted to `pending` and then back to `failed` thus perpetuating their processing.

**To Reproduce**

1. Use the following snippet to add the URLs mentioned previously:
```PHP
add_filter('author_link', function( $link ) { return '/'; }, 99, 1 );
```
2. Clear a posts's cache.
3. Check the `wpr_rocket_cache` table.

**Expected behavior**

Invalid URLs like the ones mentioned should not be added to the `wpr_rocket_cache` table.

**Screenshots**
N/A

**Additional context**

Exploratory testing should take place to discover similar URLs that should not be added to the cache table.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
