### ISSUE TITLE
Compatibility with Cloudflare plugin to allow full APO synchronisation

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5951]
**Is your feature request related to a problem? Please describe.**
We need a full synchronisation with Cloudflare's APO.

**Describe the solution you'd like**
To achieve that, we decided to make a compatibility with official Cloudflare plugin.

**Additional context**
All the details needed for grooming are stored [here](https://www.notion.so/wpmedia/Cloudflare-APO-Plugin-Compatibility-2f20298bbeb3455da8bd78be6d08e8a4?pvs=4).

**Comment by piotrbak** [comment]
This is strictly related to this issue, but the approach is different:
https://github.com/wp-media/wp-rocket/issues/3180

Moving it to separate issue for keeping the order.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
**In `views/settings/fields/rocket-addon.php':**
- Use filter `apply_filters( 'rocket_display_input_' . $data['id'], true )` to conditionally display the activation radio button, Similar to what is used in the `one-click-addon.php` file
- Add new "helper" section to display the information related to APO
- Update the CSS to display the grey helper block

**in `inc/Engine/Admin/Settings/Page.php`:**
- Add a new filter `rocket_cloudflare_field_settings` around the settings array for cloudflare
- Add new helper key and value for the section related to APO

**in `inc/ThirdParty/Plugins/CDN/Cloudflare.php`:**
- Add new methods to disable the activation radio button, and change the Cloudflare Addon section content when the official Cloudflare plugin is enabled
- Add new method to check if the official CF plugin is enabled, and credentials are saved
- Add new method to disable WP Rocket Cloudflare option when the official Cloudflare plugin is enabled
- Add a method to check if CF APO is enabled (doing a request on the homepage and checking the headers added by APO)
- Add a method to display a notice if CF APO is enabled, and the arrays for mandatory/dynamic cookies are not empty
- Add a method to display a notice if CO APO is enabled, and we have a mismatch between APO cache by device value and the separate cache for mobile option value. Use the CF plugin classes to do the check for the APO cache by device value.
- Add a new callback method to add `after_rocket_clean_domain` to the array `cloudflare_purge_everything_actions`
- Add a new callback method to add URLs to purge to the array `cloudflare_purge_by_url`
- Add a new callback method to add `after_rocket_clean_post` to the array `cloudflare_purge_url_actions`

**in `inc/admin/ui/notices.php`:**
- Remove the conditional related to cloudflare plugin in `rocket_plugins_to_deactivate()`

**Add unit & integration tests**

### Estimate the effort ✅
[L]

**Comment by vmanthos** [comment]
I did exploratory testing and so far I found that when:
1. The Cloudflare plugin is installed/activated.
2. Credentials are set correctly.
3. APO is enabled in the plugin's settings.

we are still displaying the "Modify Options" button but we shouldn't:
![image](https://github.com/wp-media/wp-rocket/assets/193660/1867bbcc-64f1-4255-827b-9c5273cdb14e)

@CrochetFeve0251 Can you please look into this? :pray:
