### ISSUE TITLE
WPCode URLs added to cache table when we disable active snippet

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5952]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.13.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Whenever we disable snippet using WP Code Lite, we will add URL entry to the database (duplicated entry for 404 URL and author)

**To Reproduce**

**Precondition**
- Active theme 2020
- WPCode Lite 2.0.11 is activated
- Add some PHP snippets, enable some of them

**Steps to reproduce the behavior:**
1. Install and activate WPR 3.13.3
2. Disable one of the snippets and notice the cache table =>URL domain/wpcode/snippetName added to cache table twice and author link added twice

**Expected behavior**
- WPcode URLs not added to cache table and no duplicated entry for the author URL

**Screenshots**
![Screenshot from 2023-05-26 11-36-35](https://github.com/wp-media/wp-rocket/assets/76941962/3cf8ab61-bc41-41d9-8b39-6fc221cf8a36)

**Additional context**
- tested on https://newer.rocketlabsqa.ovh/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
They are registering a custom post type and custom taxonomies. All of them have `'public'  => false`.

Maybe we should check if the CPT or taxonomy URL is `public` before adding it to the `wpr_rocket_cache` table.

As far as the duplication goes, I wasn't able to reproduce it in my local environment. 

On the site Mai mentioned, `after_rocket_clean_post` fired once, but the `create_or_update()` method was called twice:
https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/Engine/Preload/Database/Queries/Cache.php#L124-L188

 The second comes from `after_rocket_clean_file`.

**Comment by Khadreal** [comment]
we are not checking for post_type public value in `rocket_clean_post_cache_on_status_change` method, create a PR [here](https://github.com/wp-media/wp-rocket/pull/6722)

**Comment by MathieuLamiot** [comment]
Steps on how to reproduce available: marking test by devs.

**Comment by MathieuLamiot** [comment]
@DahmaniAdame @piotrbak Is it OK to prevent adding private post types to the cache table? While it can solve the issue with WPCode URLs, it sounds like this could impacts other things as well, so is that an expected behavior? thanks

**Comment by piotrbak** [comment]
@MathieuLamiot We're good with this one 🙏 

https://developer.wordpress.org/reference/functions/register_post_type/
