### ISSUE TITLE
background image set by variable in CSS should not be lazyloaded

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5954]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version:  ✔️ 3.13.3
- Used the search feature to ensure that the bug hasn’t been reported before: ✔️

**Describe the bug**
WP Rocket removes the inline style that references the CSS variable --background-image as part of the lazyload here - https://i.imgur.com/ggcKDIu.png and when WP Rocket is adding it back, our code is adding it as background-image.

**To Reproduce**
1. create a post or a page
2. add the following HTML:
```
<div class="background-image one" style="background-image: url('/wp-content/uploads/image')"></div>

<div class="background-image two" style="--background-image: url('/wp-content/uploads/image')"></div>

<style>
.background-image{
width: 700px;
height: 800px;
}

</style>
```

3. replace /wp-content/uploads/image with an actual image

**Expected behavior**
div two should not be lazyloaded
--background-image should be preserved so the image is displayed as expected.
For properties depending on the variable still find it.
To not display an image that shouldn't be displayed.

**Screenshots**
![image](https://github.com/wp-media/wp-rocket/assets/1954918/d6c5a061-7a3c-43dd-87fc-52fa157c52f8)

![image](https://github.com/wp-media/wp-rocket/assets/1954918/d9808d9e-94ed-4e79-a605-f6da8560d0ac)

**Additional context**
related hs: https://secure.helpscout.net/conversation/2254863040/421882
slack: https://wp-media.slack.com/archives/C08N8J6VC/p1685177067548109

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue (1). We might reopen this in the future.

**Comment by johan-las** [comment]
related : https://onecomhelp.zendesk.com/agent/tickets/18734845
