### ISSUE TITLE
Remove unused css does not work with Generatepress Woocommerce extension

### ISSUE THREAD

**Issue by FunkyCss** [wp-media/wp-rocket#5955]
**Describe the bug**
Hallo there, this issue is from the start of you using this cool feature, which works perfectly fine with most cases.
But from the beggining is not working with one of the most used themes out there which is Generatepress.

The issue is simple, if you have used unused css with a Generatepress  theme which is a woocommerce store, and you have selected on mobile to have one column product per row, it will be displayed as three. so it does not read this part of css. 

**To Reproduce**

Go to a generatepress site which has the woocommerce extension on, go to the customizer - and select product columns for mobile to 1. 

**Expected behavior**
When you visit your site from a mobile device to be one column by row for product archives. 

I think I have also noticed the product long description to be missed with the unused css but I will open a new topic for this.

Please if you need more info let me know, as I believe this should be fixed asap, as GP is a famous theme that many use.

**Comment by piotrbak** [comment]
Hello @FunkyCss and thanks for creating the issue.

Could you confirm that you have enabled the `Separate Cache for Mobile Devices` feature? It's essential when dealing with different layouts for desktop/mobiles.

If that doesn't help you, please contact our Support Team, we'll be happy to investigate and resolve the problems then. If needed, we'll reopen this issue. Thank you!
