### ISSUE TITLE
WP Rocket's cache is cleared after every update 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5958]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13.3`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When updating WP Rocket the cache is cleared every time although this may not be the intended behavior. 
For example, we have code to clear the cache when updating from a version lower than 3.6:
https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/admin/upgrader.php#L272-L275

This is happening because `version` isn't part of the `$removed` array:
https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/admin/options.php#L25-L54

so the following conditional always evaluates to `true` and `rocket_clean_domain()` runs clearing the cache:
https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/admin/options.php#L91

**To Reproduce**

1. Install WP Rocket `3.13`.
2. After the cache is preloaded disable Preload.
3. Check the `/cache/wp-rocket/` folder.
4. Update to the latest WP Rocket version (`3.13.3` at the time this is written).
5. Repeat step 3. The cache will have been cleared.

**Expected behavior**

This issue should be seen as an opportunity to discuss whether we'll keep the current behavior, i.e. clear the cache after every update, or if we want to do that selectively, e.g. with specific versions.

**Screenshots**

N/A.

**Additional context**

N/A.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. WP Rocket cache should be cleared during the update when this is specified in the [wp-rocket/inc/admin/upgrader.php](https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/admin/upgrader.php#L272-L275)
2. WP Rocket cache should not be cleared during the update when not asked to

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
As noted by Vasilis, the `version` index of the array changes on update, and it's not part of the array of values to ignore, so the clean is triggered on every update

### Scope a solution ✅ 
- Add `version` to the `$removed` array in `rocket_after_save_options()`
- Add an additional test fixture to confirm this change

### Estimate the effort ✅
Effort `XS`
