### ISSUE TITLE
[2.11-alpha2]:Critical CSS is not generated for Front Page and pages 

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#596]
Critical CSS is not generated for Front Page and pages. 

(Critical CSS is generated for Blog page and posts, categories) 

Site details:

PHP: 5.6.21
Host: Media Temple
WP Version: 4.9
Theme: TwentySixteen/ Hueman
Type: Single Site
Domain: using sub-domain

**Comment by Tabrisrp** [comment]
Fixed by PR #597
