### ISSUE TITLE
Show a warning on sites that redirect all query strings to the no-query string version

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5966]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a site is redirecting all query strings to the no-query string version of the URL, it might cause issues for RUCSS.
Our SaaS will send a visit to the ?noncached version of a URL. 
This could be an issue for RUCSS if some CSS files are loaded by Javascript files that are delayed by Delay JavaScript Execution, for example

For example if this URL: 

`https://www.example.com/?any_string
`
gets redirected to 

`https://www.example.com/
`
 
**To Reproduce**
1. On a site, load a CSS via JS and delay that JS file.
2. redirect any query string, to the base URL
3. try to run RUCSS
4. See the error

**Expected behavior**
we should notify the User, and have some form of warning in the SaaS,  that the traffic to the noncached version is redirected and that might cause issues with the used CSS generation.

**Additional context**
ticket: https://secure.helpscout.net/conversation/2225420557/416624?folderId=2683093
slack https://wp-media.slack.com/archives/C029G1B5HD2/p1686051845560789

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Closing it in favor of:
https://github.com/wp-media/wp-rocket/issues/5982
