### ISSUE TITLE
Error with ShortPixel Critical CSS

### ISSUE THREAD

**Issue by Olwyne** [wp-media/wp-rocket#5972]
**Describe the bug**
When I have ShortPixel Critical CSS and WP Rocket activate both at the same tume, I have this error. I only have this when ShortPixel Critical CSS is activated. I use PHP 8.2.

```
Deprecated: Function rocket_clean_wpengine() is deprecated since version 3.6.1! Use \WP_Rocket\ThirdParty\Hostings\WPEngine::clean_wpengine instead. in /var/www/html/wp-includes/functions.php on line 5405

Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "rocket_clean_supercacher" not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php:310 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #1 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #2 /var/www/html/wp-content/plugins/wp-rocket/inc/functions/files.php(866): do_action('after_rocket_cl...', '/var/www/html/w...', '', '...') #3 /var/www/html/wp-content/plugins/wp-rocket/inc/common/purge.php(459): rocket_clean_domain('') #4 /var/www/html/wp-includes/class-wp-hook.php(308): do_admin_post_rocket_purge_cache('') #5 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #6 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #7 /var/www/html/wp-admin/admin-post.php(85): do_action('admin_post_purg...') #8 {main} thrown in /var/www/html/wp-includes/class-wp-hook.php on line 310
```

**To Reproduce**
1. Go to Plugins
2. Activate WP Rocket and ShortPixel Critical CSS
3. Clear cache with WP Rocket

**Expected behavior**
Clear cache without error

**Screenshots**

**Additional context**
PHP 8.2 and plugins in their lastest version

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
The error is coming from ShortPixel Critical CSS itself, they are using deprecated functions in their compatibility code: https://plugins.trac.wordpress.org/browser/shortpixel-critical-css/trunk/lib/ShortPixel/CriticalCSS/Integration/WPRocket.php

**Comment by piotrbak** [comment]
Added my comment here:
https://wordpress.org/support/topic/error-with-wp-rocket/#post-16938631
