### ISSUE TITLE
Provide a way to stop preloading visited urls

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5977]
**Is your feature request related to a problem? Please describe.**
We provide functionality to specify a dedicated sitemap to use for preloading:
https://docs.wp-rocket.me/article/1723-customize-preload-sitemaps-and-priority#preload-only-a-custom-sitemap

But visited URLs will still be added to the cache table, whether or not they are in this sitemap. 
Customers are using the sitemap snippet to have more control over how preloading works and possibly reduce CPU issues. But if we still add any visited URL to the table, it defeats the purpose a bit. The cache table can still grow really large this way if the site has a lot of pages. 

**Describe the solution you'd like**
Either automatically or by way of a dedicated filter, we should deactivate preloading visited urls when that snippet is in use. 
Having a dedicated filter could be helpful because sometimes "junk" urls get added to preload because they are visited and cacheable (URLs with multiple slashes in them, for example), and this isn't always desirable. So the ability to turn that off could also be useful for other cases. 

**Describe alternatives you've considered**
n/a

**Additional context**
Example ticket: https://secure.helpscout.net/conversation/2266082107/423673?folderId=377611

**Comment by piotrbak** [comment]
I think it was fixed here, right?
https://github.com/wp-media/wp-rocket/pull/6003

**Comment by webtrainingwheels** [comment]
@piotrbak Yes, I think #6003 takes care of it, so this issue could be closed.
