### ISSUE TITLE
Cache issue with VdoCipher

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5978]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using VdoCipher with page cache, embedded videos will no longer be playable after a while. 

Their playback video looks like: 

```
https://player.vdocipher.com/v2/?otp=RANDOMSTRING&playbackInfo=RANDOMSTRING
```

With the `RANDOMSTRING` part continuously changing. 

I assume there is an expiry timeframe once a specific link is generated. And it seems to be very short. 

Once expired, the video will show a black screen with the following written: 

```
Error 60072013
time expired
```

I contacted their support to see if they can consider Ajaxifying video embed to help it work without issues when page cache is involved. 

If that's not a possibility, we need to: 

- Have a dismissible notification to let customers know that `VdoCipher` is not compatible with page cache
- Possibly implement an auto-exclusion when their shortcode is used on a page

**To Reproduce**
1. Use VdoCipher
2. Cache the page
3. See if the page still works after a while

**Expected behavior**
We shouldn't break videos added to page, regardless if they are cache-friendly or not.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2257827527/422386?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by karombekHusanov** [comment]
everthing is working fine, followed instructions given above, but still in some cases time expired error shows

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future. The fix should happen on the 3rd-party side.
