### ISSUE TITLE
[2.11-alpha2]: White Screen when Combine Google Fonts enabled

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#598]
When Combine Google Fonts is enabled on my dev site, there is a white screen with the word 'Array' . When I disable it, the page renders. 

Image and WP Debug log contents attached.
[GF white screen debug log.log](https://github.com/wp-media/wp-rocket/files/1504811/GF.white.screen.debug.log.log)
![screen shot 2017-11-26 at 9 40 04 pm](https://user-images.githubusercontent.com/8108643/33252448-242d8218-d2f3-11e7-9a95-7d014c7a6370.png)

**Comment by Tabrisrp** [comment]
Which theme are you using?

**Comment by ernee** [comment]
Hueman: https://wordpress.org/themes/hueman/

**Comment by ernee** [comment]
Flatsome is another theme with a white screen after Combine Google Fonts: https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319

**Comment by Tabrisrp** [comment]
Found the bug, will be fixed in next version

**Comment by Tabrisrp** [comment]
Should be fixed in alpha4. Re-open if needed.
