### ISSUE TITLE
Conflict with Avada's Combination features and Remove Unused CSS

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#5980]
**Describe the bug**
When Avada's CSS combination features are enabled along with WP Rocket's RUCSS, page styles become broken before the Used CSS is even generated and/or applied to the page. The issues appear instantly upon activation of RUCSS.

Had a discussion in the Dev Escalation thread about this here:
https://wp-media.slack.com/archives/C056ZJMHG0P/p1685046492785519

And it appears to be related to the fix applied in this issue:
https://github.com/wp-media/wp-rocket/issues/4881

The temporary fix, in this case, was to apply the following:
`define( 'FUSION_DISABLE_COMPILERS', false );`

**To Reproduce**
1. Enable Avada's CSS combination features
2. Enable WP Rocket's RUCSS
3. Page styles are broken instantly before RUCSS generated and/or applied

**Expected behavior**
The styles should not be broken while these are both active. 

**Additional context**
https://secure.helpscout.net/conversation/2253659186/421675/

**Page where the issue occurred**
https://prettyinnoise.de/kritiken/kritik-kommando-kant-eklat/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
