### ISSUE TITLE
Prices by Country

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#5983]
Hello,
We are currently using the plugin https://booster.io/ in tandem with your plugin. We use this plugin to offer different prices to the customers based on their IP. However, with the caching feature on in your plugin, the prices are cached as well and we cannot display different prices for different customers. Is there any way to resolve this issue?
Depending on the size of the website we are in need of caching feature but unfortunately it doesn't work well with the above mentioned plugin.

**Comment by piotrbak** [comment]
Hello @psyhoz thanks for creating the issue. Please refer to the following documentation articles:
https://docs.wp-rocket.me/article/1524-using-geolocation-geotargeting-plugins
https://docs.wp-rocket.me/article/1545-using-multiple-currency-plugins
