### ISSUE TITLE
PHP Error when null is returned by the function get_rocket_parse_url

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#5985]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
In this line:

https://github.com/wp-media/wp-rocket/blob/97259a44c96c09bff39241cc31010776bef12650/inc/functions/formatting.php#L367-L369

When the condition is met, it returns null, but an array is expected to be returned causing errors like this:
`PHP Recoverable Error: Uncaught exception 'TypeError' with message 'rocket_maybe_find_right_trash_url(): Argument #1 ($parsed_url) must be of type array, null given, called in /app/web/wp-content/plugins/wp-rocket/inc/functions/files.php on line 593' in /app/web/wp-content/plugins/wp-rocket/inc/functions/files.php on line 513`

**Expected behavior**
We should return an array to guard against possible cases where the condition is met.

**Additional context**
Reference in this slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1686841710716299

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
AC is clear in the issue itself:
1. We need to guard against fatal error when forcing that kind of value

Steps to reproduce are available in the **Additional Context** section

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
