### ISSUE TITLE
API key error is displayed while it is set at config file

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5989]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.14
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Error is displayed when adding a valid email/ID while a valid API key is hidden

**To Reproduce**
1. Hide CF API keys by adding those lines in wp-config.php
`define('WP_ROCKET_CF_API_KEY', 'your key here);
define( 'WP_ROCKET_CF_API_KEY_HIDDEN', true );`
2. Fresh install and activation of WPR
4. Enable CF addon and click modify options then add a valid email/id
5. Save settings => error is displayed

**Expected behavior**
No error is displayed about API Key

**Screenshots**
![Screenshot from 2023-06-19 11-36-12](https://github.com/wp-media/wp-rocket/assets/76941962/95396741-920e-46d6-8547-e54fe4912cee)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. Defining Cloudflare credentials using constant should not cause any errors
2. Regular was of adding Cloudflare credentials should work as before

**Comment by jeawhanlee** [comment]
Closing as we were testing with an Incorrect API Key.
