### ISSUE TITLE
[2.11-alpha3]: Optimize CSS Delivery notices don't display when selecting option from Static Files Tab

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#599]
**Optimize CSS Delivery** notices don't display when selecting the option from Static Files tab. 

They do display when **Regenerate Critical Path CSS** is selected from tool bar.

**Comment by Tabrisrp** [comment]
Fixed in next version

**Comment by Tabrisrp** [comment]
Should be fixed in alpha4. Re-open if needed.
