### ISSUE TITLE
The notice for Cache by device type mismatch needs improvement (mobile view)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5990]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.14
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The button to enable Separate Mobile Cache in CF cache by device type notice, not fitting the mobile screen

**To Reproduce**
1. CF plugin is enabled and Cache by device type is on
2. Separate mobile cache is off at WPR
3. on Mobile, open WPR settings

**Expected behavior**
The button to activate the Separate mobile cache is fitting mobile screen

**Screenshots**
![Screenshot from 2023-06-19 11-44-16](https://github.com/wp-media/wp-rocket/assets/76941962/691ab984-5c7b-4853-8ca5-3219a0e6a527)

![Screenshot from 2023-06-19 11-50-35](https://github.com/wp-media/wp-rocket/assets/76941962/a6f85ec7-2a95-490b-8258-bfd4ce5efd50)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
