### ISSUE TITLE
Enhance notice wording and display when dynamic/mandatory cookies are used with Cloudflare APO

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5991]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.14`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

Currently, when we detect usage of dynamic/mandatory cookies we are displaying the following notice:
> You are using "Dynamic Cookies Cache". Cloudflare APO is not yet compatible with that feature.
You should either disable Cloudflare APO or check with the theme/plugin requiring the use of “Dynamic Cookies Cache” developers for an alternative way to be page-cache friendly. [More info](https://docs.wp-rocket.me/article/1444-using-cloudflare-apo-with-wp-rocket?utm_source=wp_plugin&utm_medium=wp_rocket)

This is generic, i.e. it will be displayed when:
1. Only dynamic cookie(s) are used.
2. Only mandatory cookie(s) are used.
3. Both dynamic and mandatory cookie(s) are used.

Also, if the configuration file, e.g. `/wp-rocket-config/example.com.php` isn't regenerated after using the filters, the notice will still be (falsely) displayed. 
This would be an edge case, e.g. if a plugin/theme isn't regenerating the configuration file after using our filters.

The reverse issue, i.e. we won't stop displaying the notice (falsely), will take place if the filters are removed without regenerating the config file.

**To Reproduce**

1. Use the following snippet to define a mandatory cookie:
```PHP
add_filter( 'rocket_cache_mandatory_cookies', 'cache_cookie' );
	function cache_cookie( $cookies ){
		$cookies[] = 'rocketqa';
		return $cookies;
}
```
2. Refresh WP Rocket's settings page and see the (generic) notice.
3. Visit the front end.
4. Cached/optimized content is served because the mandatory cookie hasn't yet been set in the config file.

**Expected behavior**

The notice should be specific to the kind of cookie that's set using our filters - dynamic, mandatory, or both. Maybe we can also display the cookies' names to make it easier for customers to find the culprit plugin/theme.

Also, do not display the notice until the cookies are set in the configuration file.

**Screenshots**

N/A

**Additional context**

N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/3051692914/582855?viewId=377611
