### ISSUE TITLE
Get rid of the Cache Tab

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5992]
**Is your feature request related to a problem? Please describe.**
This is a GitHub part of the enhancement that's described [here](https://www.notion.so/wpmedia/Get-rid-of-the-Cache-tab-e505d7b0ffc54cc8b0920cdfb4bdf853?pvs=4).

**Additional context**
Acceptanca Critera and details are present in the above document.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
`inc/Engine/Admin/Settings/Page`
- remove the `cache_section()` method
- move the `cache_mobile` and `do_caching_mobile_files` to the `hidden_fields()` method
- Add `cache_lifespan` to the `advanced_cache_section()` method
- Add user cache to the `addons_section()` as a one-click add-on
- Add method to display the enable mobile cache button on the tools section
- Add method to enable the mobile cache and separate cache for mobile options
- Add method to set `do_caching_mobile_files` to 1 on update if `cache_mobile` was enabled

`inc/Engine/Admin/Settings/Subscriber`
- Add method hooked to `rocket_settings_tools_content` to output the enable button
- Add method hooked to `wp_ajax_rocket_enable_mobile_cache` as callback
- Add method hooked to `wp_rocket_upgrade` as callback

`inc/admin/upgrader.php`
- change the default value of `do_caching_mobile_files` to 1

`src/js/global/ajax.js`
- Add AJAX method to enable mobile options

### Estimate the effort ✅
Effort [S]

**Comment by JerissCloudCenter** [comment]
Please stop this maddness of removing most of the features or options! You've removed "Combine CSS" (even if it's not recommended for HTTP2) and now all my pagespeed scores went down. Now you want to remove the entire "Cache" tab. Stop!

**Comment by piotrbak** [comment]
Hello @jeriss-cloud-center thanks for your comment. Removing Cache tab doesn't mean that all the options present there will disappear. Please keep in mind that we use GitHub for development purposes.

`You've removed "Combine CSS" (even if it's not recommended for HTTP2) and now all my pagespeed scores went down.`
As stated [here](https://github.com/wp-media/wp-rocket/issues/5909#issuecomment-1717534603), if you experienced any negative performance effect because of this change, please contact our Support Team with all data, we'll investigate your case carefully.

**Comment by JerissCloudCenter** [comment]
Yes but let me share another reason why removing this tab is an extremely bad decision. I'm hosting my websites on Cloudways, whose known to have had issue with Varnish not distinguishing type of devices (desktop, tablet, mobile) till recently when they just deployed this feature. This is even documented on your own website!

https://docs.wp-rocket.me/article/493-using-varnish-with-wp-rocket#varnish-mobile-cache

![image](https://github.com/wp-media/wp-rocket/assets/87424739/66295337-4900-4263-9a94-16ef7fb6bf8c)

Till then, I had to disable the setting "Separate cache for mobile" otherwise I'd have had big troubles displaying wrong files per device with Varnish. Now that Cloudways deployed this new feature to distinguish types of devices, I could enable this Separate cache for mobile. Before, no, so there is a real reason to keep this tab. It makes no sense to remove this tab.

So if such a case appears for another host or another type of issue regarding cache, how do you want your users to define the configuration that best suits them? You want them to have bigger troubles starting to use filters in custom code, making their experience worse than it was expected (thinking that removing this tab would make things easier/cleaner... no on the contrary!).

**Comment by sarangsss29** [comment]
Nginx fastcgi caching
Right when I was about to purchase the wp-rocket, the v3.16 was released and it may cause some problems with the new
Auto-enable Separate Cache Files for Mobile Devices and remove UI checkbox
My hosting has nginx fastcgi caching and it auto supports the rocket-nginx plugin which handles nginx and wp-rocket caching
https://github.com/SatelliteWP/rocket-nginx/
However, wp-rocket's new update auto-enables separate cache Files for Mobile Devices and remove UI checkbox.

The author of rocket-nginx plugin also has this question how nginx will handle the separate caching
https://github.com/SatelliteWP/rocket-nginx/issues/214
also listed on the plugin
Rocket-Nginx won't manage any request if you activate the Mobile cache feature.

> In today's world, we usually use a responsive theme that will adapt to your visitor's screen. Therefore, activating the 'cache for mobile device' to create a separate cache for mobile is not needed. It's useless as the same code will be cached twice. That being said, there are cases where the code is different and you might want to use that option. Unfortunately, knowing if the device is a mobile or not is as simple as you might think. There are so many devices and browsers to handle! The Nginx's scripting language is not powerful enough to achieve the validation correctly. Therefore, if you activate this feature, Rocket-Nginx will let WP Rocket handle the device validation and serve the cached page.

Why was this decision made? Separate caching does not make sense as most wordpress themes in 2024 are responsive.

**Comment by BradFD** [comment]
Why was this change made what is the justification for defaulting to separate caches when almost everyone is using a responsive theme theses days and separate caches are not needed? Did just one cache cause problems for lots of people, where is that documented? Did just one cache cause more support headache/tickets for WP Rocket staff? What is the explanation for the change or is it just random? Very frustrating when developers make unexplained changes that don't make much sense and they don't provide explanation for them. @piotrbak @Tabrisrp

**Comment by maximejobin** [comment]
I must agree that I don't understand the activation of the separate mobile cache by default.

As a business, I can understand your decision as it's one option less... so less support to do.

As a client (and author of Rocket-Nginx), I don't get the removal of the "Separate cache for Mobile device". I've worked on hundreds of websites and it was used maybe once or twice. That being said, I've seen tens of configuration where people activated it without reasons. It just makes your site not as fast as it could be when you generate the mobile cache for no reason. There is already detection about when to force activation.

**At the end of the day, I do not agree but can understand the activation by default. What I'm not agreeing with is the disappearance of the option. I want to be able to deactivate it on new websites without having to use a hack or a filter.**

I hope the execution can be reconsidered.

**Comment by foliovision** [comment]
Please bring back the setting.

In **most cases** we need the desktop and mobile HTML to be the same. Otherwise our server will have to work twice as hard creating a separate HTML version for mobile when there is no reason for it.

Thanks,
Martin

**Comment by ghost** [comment]
I had to roll back to version 3.15.10. It's complete nonsense, since when should the cache be different on mobile and desktop? My server has to work twice as hard when before it was working great. I'm getting worse Google Page Speed scores now (74 now / 94 before). Your product is terrible now.
