### ISSUE TITLE
PHP fatal error occurs when the used CSS SaaS doesn't return a job ID or queue name

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5994]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.14`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

The following PHP fatal error
```PHP
[19-Jun-2023 13:06:12 UTC] PHP Warning:  Undefined array key "jobId" in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 232
[19-Jun-2023 13:06:12 UTC] PHP Warning:  Undefined array key "queueName" in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 233
[19-Jun-2023 13:06:12 UTC] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::create_new_job(): Argument #2 ($job_id) must be of type string, null given, called in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 231 and defined in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:164
Stack trace:
#0 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(231): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->create_new_job()
#1 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Frontend/Subscriber.php(49): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->treeshake()
#2 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\RUCSS\Frontend\Subscriber->treeshake()
#3 /var/www/example.com/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters()
#5 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer()
#6 /var/www/example.com/htdocs/wp-includes/functions.php(5309): ob_end_flush()
#7 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(308): wp_ob_end_flush_all()
#8 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#9 /var/www/example.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /var/www/example.com/htdocs/wp-includes/load.php(1144): do_action()
#11 [internal function]: shutdown_action_hook()
#12 {main}
  thrown in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 164
```
occurs if the response from the SaaS doesn't have a `jobId` or a `queueName`:
https://github.com/wp-media/wp-rocket/blob/76031e933feeaf45162c904bab5f25043c985692/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L232-L233

**To Reproduce**

1. To simulate the error from the SaaS add the following code:
```PHP
unset( $add_to_queue_response['contents']['jobId']);
unset( $add_to_queue_response['contents']['queueName']);
```
here:
https://github.com/wp-media/wp-rocket/blob/76031e933feeaf45162c904bab5f25043c985692/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L228
2. Clear the used CSS.
3. Visit a few URLs on the front end.
4. Look into the `debug.log` for the fatal error.

**Expected behavior**

No PHP fatal error should occur if the SaaS doesn't provide a `jobId` or `queueName`.

**Screenshots**

N/A.

**Additional context**

This was discovered during the investigation of #5899 and was related to an error in the SaaS's code.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
The AC here is very simple and it's about:
1. RUCSS should work without regression in regular circumstances
2. We should guard our code against fatal errors when there's no correct response (including empty, etc.) inside mentioned `$add_to_queue_response`. This is about guarding plugin when theoretically something bad happens to the saas

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced following the steps provided

### Identify the root cause ✅ 
We are not checking if the indexes exists in the array before passing the values to the `create_new_job()` method.

### Scope a solution ✅ 
The solution would be to add an additional check using `isset( $add_to_queue_response['contents']['jobId'], $add_to_queue_response['contents']['queueName'] )`, and bail-out if they are not set.

### Estimate the effort ✅
Effort `XS`
