### ISSUE TITLE
 php-fpm + apache + cgi: headers won't be set for php files

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#60]
I'm experiencing some trouble with the server configuration of my hoster (Infomaniak). I can provide more infos but basically: - Apache 2.2.x - FPM/FastCGI
The problem is: headers set with .htaccess will work for static files, but not for php files. While this is not a problem when we deliver cached files to logged out users, it is when we activate "Cache for logged in users": in that case we use php, so fpm resets all headers. In that case, the only solution I know is to deal with headers via php (header()).
The question is, should we?

**Comment by Tabrisrp** [comment]
@Screenfeed You reported this initially if I remember correctly?

**Comment by piotrbak** [comment]
Closing it, since it doesn't seem to cause problems. We'll reopen if needed.
