### ISSUE TITLE
[2.11-alpha3]: Sitemap preload notices missing items

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#600]
Suggestion: Sitemap preload notice should also include “(Refresh this page to view progress)”. 

Did not see the  “complete” notice display.

**Comment by Tabrisrp** [comment]
Should be fixed in alpha4. Re-open if needed.

**Comment by webtrainingwheels** [comment]
Got this immediately after updating to Alpha-6
![wp_rocket_ _sub_ _wordpress](https://user-images.githubusercontent.com/1043076/33391136-f3f6b9d8-d4ec-11e7-833e-1be12963b346.jpg)
