### ISSUE TITLE
Make WP-Optimize not compatible plugin

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6005]
**Is your feature request related to a problem? Please describe.**
WP Optimize comes with features that are duplicated with ours. Especially starting from 3.15 it might be problematic

**Describe the solution you'd like**
We'll make WP Optimize plugin not compatible with WP Rocket, in general.

**Acceptance Criteria:**

1. We'll make WP Optimize not compatible with WP Rocket
2. Equivalent message should be displayed when both plugins are active:
![image](https://github.com/wp-media/wp-rocket/assets/26767037/cdc3831b-f616-4bbe-ad3d-2f60860b589a)
3. Dev Team: the confirmation of the fix should be presented using [video](https://github.com/wp-media/wp-rocket-e2e/issues/1)

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `inc/admin/ui/notices.php`

Function `rocket_plugins_to_deactivate()`

- Add wp-optimize to the plugins array, using this key value pair: `'wp-optimize' => 'wp-optimize/wp-optimize.php'`

### Estimate the effort ✅
Effort [XS]
