### ISSUE TITLE
Support Rank Math - plugins section

### ISSUE THREAD

**Issue by marija-nikolic** [wp-media/wp-rocket#6007]
Details about the task are [here](https://docs.google.com/document/d/1AmDBp6WGo6Z9EyxMN19pusX0W0vYxOHgs-phh5J-Uhk/edit).

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
`inc/admin/admin.php`
- use `rocket_add_imagify_api_result()` as a base to create a new method in the informationSubscriber class
- deprecate the function

`inc/Engine/Plugin/InformationSubscriber.php`
- Create a new method based on `rocket_add_imagify_api_result()`, refactor it to be used for both imagify and rankmath
- Add the new method as callback
- Add tests for the new method

### Estimate the effort ✅
[S]
