### ISSUE TITLE
File exclusion 

### ISSUE THREAD

**Issue by Vojjtosos** [wp-media/wp-rocket#6012]
Hi, I'm using wp-rocket delay javacript execution, and I need to exclude a file that affects a popup. The page is created using elementor. When the delay javacript execution is on it takes a second or two for the popup to open, which when the menu is on is quite unusable. I know I need to exclude the file that opens the popup, but I can't find it. Any advice please

**Comment by piotrbak** [comment]
Hello @Vojjtosos, thanks for creating the issue. I'd suggest contacting our Support Team:
https://wp-rocket.me/support/

We use GitHub for development purposes only.

**Comment by Vojjtosos** [comment]
@piotrbak cant because the license is expired, hope to find help there!
