### ISSUE TITLE
Fix rocket_cache_reject_uri value for excluding REST API JSON URLs From Cache for Multisite

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6014]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
In a multisite environment, the ` rocket_cache_reject_uri` value is incorrect in the WP Rocket config file. Here is the incorrect value:
`http://(/%5B/%5D+)?/(index.php/)?(.*)wp-json(/.*|$)`

And it causes the exclusion to miss URLs like this and they end up cached (example from the ticket linked below):
https://www.gogforce.com/wp-json/map/counties

We had a Slack discussion about it here:
https://wp-media.slack.com/archives/C08N8J6VC/p1687262924786589

And Ahmed determined that the value coming from here:
https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/3rd-party/plugins/wp-rest-api.php#L33

Is being processed by the `esc_url_raw` function here:
https://github.com/wp-media/wp-rocket/blob/56895a819512af1244920ffd5e6415efe796768c/inc/functions/options.php#L253

Which is resulting in the incorrect exclusion regex value shown above.

**To Reproduce**
1. Enable WP Rocket on a multisite setup
2. Check the WP Rocket config file
3. The `rocket_cache_reject_uri` value will not be correct

**Expected behavior**
The correct exclusion for `rocket_cache_reject_uri` should be added in the config file for both regular and multisite setups so REST API JSON URLs are excluded from cache in both cases.

**Screenshots**
![image](https://github.com/wp-media/wp-rocket/assets/45705494/ad980841-dffb-42e3-9201-c5ad90ab4372)

**Additional context**
https://secure.helpscout.net/conversation/2274759774/425135/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Comment by mifrero** [comment]
Related https://github.com/wp-media/wp-rocket/issues/8211
