### ISSUE TITLE
Add GA4 new parameters to the ignored query string parameters with standard caching

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#6015]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
With GA4, new parameters are coming and we should add them to [the ignored query string parameters with standard caching](https://docs.wp-rocket.me/article/971-caching-query-strings#ignored-parameters):
- utm_id
- utm_source_platform
- utm_creative_format
- utm_marketing_tactic

**Additional context**
[GA4 parameters
](https://support.google.com/analytics/answer/10917952?hl=fr&sjid=17660478707535021386-EU#parameters&zippy)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Done
