### ISSUE TITLE
LazyLoad 404 error on multisite after updating

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#602]
As we deleted the old LazyLoad script file and we just delete the cache during the update, on a multisite we clear the cache of the main domain only.

And then, it causes a 404 error on the LazyLoad file on all other websites from the network.

To avoid this issue, we can simply keep the old version (1.0.5) in the plugin.

**Comment by Tabrisrp** [comment]
Should be fixed in alpha4. Re-open if needed.
