### ISSUE TITLE
Add a new backend exclusion field for Minify/Combine JS

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6024]
**Is your feature request related to a problem? Please describe.**
As we did with other exclusions, we could move the JavaScript files array from `rocket_exclude_js` to the backend. 

The array: 
https://github.com/wp-media/wp-rocket/blob/c23eb7017ce24911f084771103b0beb495f3bf79/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L50C1-L57

**Describe the solution you'd like**
Add a new fields inside our backend under _Exclusions > Minify/Combine JS_ tab in the Backend called `JS Excluded Files` or similar 

**Additional context**
Per discussion with @piotrbak, we cannot resolve issues like this one unless we add that logic: 
https://github.com/wp-media/wp-rocket/issues/5553

Otherwise, we would need to do PRs for such exclusions as we did in the past.

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. Exclusions from Minify JS should work without regressions using the backend list

**Comment by piotrbak** [comment]
@mostafa-hisham are you on it?
