### ISSUE TITLE
Do integrity check when enabling Prelaod and Remove Unused CSS  

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6026]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are only checking if tables exist on both Preload and Remove Unused CSS when enabling them. 

In cases where the tables were manually modified, both features will just stop working without any notice, resulting in errors on logs if enabled.

We can do an integrity check each time a feature relying on a custom database table is enabled, and fix the structure when needed either: 

- Automatically (giving a worry-free experience)
-  or by promoting a message and requesting the user to click a `fix now` button (better for customer education, mentioning that the structure was manually altered, and why it shouldn't)

**To Reproduce**
1. Enable either Preload/Remove Unused CSS  
2. Alter the structure
3. See missing notification or auto mitigation

**Expected behavior**
Preload/Remove Unused CSS  features should make sure that their respective tables are operational.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2289462527/427935/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.

**Comment by webtrainingwheels** [comment]
we have numerous cases of database errors, it's why we made this doc: https://docs.wp-rocket.me/article/1780-database-error-unknown-column
- https://secure.helpscout.net/conversation/2601317211/492230/
- https://secure.helpscout.net/conversation/2569927389/486356/
- https://secure.helpscout.net/conversation/2569927389/486356/
- https://secure.helpscout.net/conversation/2517355481/476315/
there's actually quite a few more, but they are not tagged.
