### ISSUE TITLE
Separate cache for mobiles is not preloaded when a Mandatory cookie is set

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6027]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When **Separate cache files for mobile devices** is active and a Mandatory Cookie is set, the mobile cache won't be preloaded 

**To Reproduce**
1. Enable Separate Cache for Mobile Devices
2. Add a Mandatory Cookie
3. Run a preload, the desktop cache will be preloaded, but the mobile cache don't
4. add the mandatory cookie in the browser and reload the page
5. the mobile cache will be created

**Expected behavior**
We should preload the mobile cache too

**Additional context**

Slack thread
https://wp-media.slack.com/archives/C056ZJMHG0P/p1684944505077479

Specific @viobru and @engahmeds3ed msg. 
https://wp-media.slack.com/archives/C056ZJMHG0P/p1688565679815109?thread_ts=1684944505.077479&cid=C056ZJMHG0P

These are **Ahmed's findings** about the issue:

> when preload is visiting the page, we try to cache the page even when mandatory cookies are there because of this condition
> https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/classes/Buffer/class-tests.php#L228
> the method $this->is_speed_tool() returns true only with desktop preload request because of this line
> https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/classes/Buffer/class-tests.php#L941
> which matches the user agent and check if it starts with WP Rocket that we add with preload request for desktop but for the mobile request we change the user agent to be like real mobile visit here:
> https://github.com/wp-media/wp-rocket/blob/6463f2b8c327fe29c7a8451c387947a216b76f2d/inc/Engine/Preload/Controller/PreloadUrl.php#L85
> and exactly here:
> https://github.com/wp-media/wp-rocket/blob/6463f2b8c327fe29c7a8451c387947a216b76f2d/inc/Engine/Preload/Controller/PreloadUrl.php#L161
> so for mobile the method is_speed_tool returns false and the cache is failing with this message:
> https://github.com/wp-media/wp-rocket/blob/4b50481c4aae781f3ea70fd35ee04ffcf1e033d1/inc/classes/Buffer/class-tests.php#L229-L234

**Ahmed's possible solution:** 
> I think the mobile detection library is working also on headers so we can send mobile headers and keep the user agent to be `WP Rocket / Preload` as is.

> [https://github.com/wp-media/wp-rocket/blob/c9f0965156aabe55edbcbb249f4ff87eae7901c[…]ses/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php](https://github.com/wp-media/wp-rocket/blob/c9f0965156aabe55edbcbb249f4ff87eae7901ce/inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php#L324-L352)

> [Mobile_Detect.php](https://github.com/wp-media/wp-rocket/blob/c9f0965156aabe55edbcbb249f4ff87eae7901ce/inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. Preload should create mobile specific cache files also when mandatory cookie is used
2. Preloading desktop/mobile cache without mandatory cookie should work without regressions
3. Speed tools and bots should still be able to create mobile specific cache files

**Comment by engahmeds3ed** [comment]
## Reproduce the problem

Yes I can see the issue locally.

## Identify the root cause

Everything is mentioned in the issue itself.

## Scope a solution

We will go with @piotrbak 's suggestion to add `WP Rocket` as a prefix to the used mobile user agent.

## Estimate the effort
[XS]
