### ISSUE TITLE
Save html cache files directly to S3

### ISSUE THREAD

**Issue by hj-collab** [wp-media/wp-rocket#6032]
Hi,

Many people run websites in a cluster. It will be great for them if WP Rocket saves the generated cache files directly to S3 bypassing the file system. There are some plugins for media library but none for cache. CDN will cache the S3 files after first request ensuring fast loading the after first request.

Best regards,

**Comment by piotrbak** [comment]
Hello @hj-collab and thanks for creating the issue. To make the most of that kind of setup, the cache had to be served on the DNS level. I'd suggest using Cloudflare APO, Sucuri and that kind of providers to achieve that.
