### ISSUE TITLE
Compatibility with SpinupWP cache purging (indiviual URLs)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6033]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using WP Rocket with SpinupWP, we disable our cache, and only sync full site cache purging: 

https://github.com/wp-media/wp-rocket/blob/b11a9ef010188cdf41a1335819b0102fbc63c524/inc/ThirdParty/Hostings/SpinUpWP.php#L29

Individual pages cache purge is not synced. 

They do have a way to purge individual URLs are well: 

```
function spinupwp_purge_url( $url ) {
    return spinupwp()->cache->purge_url( $url );
}
```
https://github.com/spinupwp/spinupwp-plugin/blob/62ae3ec7c53f602f80cd10c742fae6c361c790f4/functions.php#L38-L40C6

We should hook to this method whenever `after_rocket_clean_post` is triggered.

**To Reproduce**
1. Use SpinupWP
2. Purge an individual page
3. See that the page is not purged from the server-side cache (it will still have `Fastcgi-Cache: HIT` response header returned)

**Expected behavior**
We should also sync individual pages cache when needed to ensure page content is always current.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2289462527/427935/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
In this PR we need to make sure that specific URL of their cache are cleared when:
1. Clicking on the `Purge URL` from the admin top bar
2. When Used CSS for specific URL is generated
3. The whole cache should not be cleared in the above scenarios

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In the SpinUpWP compatibility class, we can add methods to purge individual URLs, using the provided function by the host, with a check with `function_exists()` before using it.

We should use it for the following hooks:
- `after_rocket_clean_file`
- `rocket_rucss_after_clearing_usedcss`
- `rocket_rucss_complete_job_status`
- `after_rocket_clean_term`
- `rocket_after_clean_terms`

### Estimate the effort ✅
Effort `S`

**Comment by piotrbak** [comment]
Asked their Team to provide us with hosting plan

**Comment by BoyetDgte** [comment]
> Asked their Team to provide us with hosting plan

Just want to clarify that SpinupWP doesn't host any servers. Thank you.

>  you will need to bring your own server for SpinupWP to connect to
