### ISSUE TITLE
Do a silent check if files exists to avoid warnings when trying to handle cached files

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6034]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In some occasions, WordPress logs will refer to this kind of warning: 

```
PHP Warning: readgzfile(/cache/wp-rocket/domain.ext/index-https.html_gzip): Failed to open stream: No such file or directory in /wp-rocket/inc/classes/Buffer/class-cache.php on line 226'
```

Similar to this one in a way - https://github.com/wp-media/wp-rocket/issues/2441

It can happen randomly at different occurrences. 

While these warnings are not feature-breaking, they are still annoying to see on logs. 

It's basically a function that will try to handle a physical file, like `copy()`, `readgzfile()` or similar, but at the moment it executes, the file doesn't exist anymore. 

We should generalize doing a silent check if cache files handled by functions exist before proceeding. 

**To Reproduce**
Random, there is no specific steps to reproduce the behavior.

**Expected behavior**
We should give the least noise in logs whenever possible. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2294234535/429059/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/2881203101/547230?viewId=377611
https://secure.helpscout.net/conversation/2234229803/418365
https://secure.helpscout.net/conversation/1295946218/198440
