### ISSUE TITLE
Bricks builder Compatibility

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#6035]
Hi wp-rocket team,

Are you compatible with Bricks builder?
Because I didn't see anything about compatibility with Bricks builder on your official site.

**Comment by DahmaniAdame** [comment]
> Are you compatible with Bricks builder?

I can't see any issues reported so far. 

> Because I didn't see anything about compatibility with Bricks builder

That means there are no known conflicts or issues with Bricks specifically. And no accommodation is required :) 

Like the saying: No news is good news ;) 

If you have any issues, just open a  ticket, and we will be happy to have a look and help you sort it out.
