### ISSUE TITLE
Issue with transient rocket_get_refreshed_fragments

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#6036]
I cannot reproduce it but It seems lately that _transient_rocket_get_refreshed_fragments_cache is cached and every guest is showing the same mini cart.
Cart fragments plugins works correctly though.

When deleting _transient_rocket_get_refreshed_fragments_cache from wp_options, it's fixed.

**Comment by piotrbak** [comment]
Not all solution are compatible with our way of implementation. Please refer to this documentation article:
https://docs.wp-rocket.me/article/1436-mini-cart-cached-already-has-product-in-it

**Comment by seldimi** [comment]
That seems to be an issue when you set cache more than 10 hours. I think that was something that I used to know but there was documented, wasn’t it?
