### ISSUE TITLE
Clear APO cache upon WP Rocket deactivation

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6037]
**Is your feature request related to a problem? Please describe.**
Deactivating WP Rocket is a fairly common practice among customers that find issues with our optimizations. 
This "quick fix" doesn't have an automatic effect after 3.14 because WP Rocket doesn't clear its own cache, thus, APO cache is not cleared either, keeping the broken version of the site live until APO cache is manually cleared.

**Describe the solution you'd like**
Clear APO cache when deactivating WP Rocket, to make sure the site is synchronized with WP Rocket deactivated status.
May be useful to clear APO cache after activating WP Rocket too.
This can be "risky" in high-traffic sites where the site relies on having one set of cache files at least.

**Describe alternatives you've considered**
We can show a notice to tell customer to clear their APO cache.

**Additional context**
Slack thread here: https://wp-media.slack.com/archives/C08N8J6VC/p1689010919320849

**Comment by DahmaniAdame** [comment]
Not sure if not clearing cache on APO would cause any issues. 

There should only be two scenarios: 
- The page/its assets are cache on the edge pop
- Or not

Requests going to any of the two wouldn't cause the website to break. And there shouldn't be any intermediary state where page cache is delivered alone without the cached assets. 

It makes sense to clear APO cache to reflect the current state of the website. 

We should do the same for hosting services with edge cache as well.

The original issue should be investigated further to know if that's the actual issue.

**Comment by camilamadronero** [comment]
Here's a possible scenario where not clearing APO after deactivating WP Rocket would cause problems:

1. page with used css was only on the web server, apo wasn't synced
2. wpr was updated to 3.14
3. apo cache was cleared
4. page with used css (and layout issue) is now on the apo servers

or, the same but with the other optimizations, being stored only on the web server until finally apo was synced

**Comment by piotrbak** [comment]
In this issue we'll need to introduce a new conditional clearing process:
1. If condition is met, we need to clear the whole cache while deactivating the WP Rocket
2. The condition introduced here will be related to the official Cloudflare plugin, if it's enabled when deactivating WP Rocket, we'll clear the whole cache
3. Clearing the whole cache while deactivating WP Rocket won't happen if the condition is not met
4. The future conditions might look like: `if specific hosting is used`, `if specific plugin is used`, etc.

**Comment by remyperona** [comment]
Should the clearing be the APO cache clear, or the WP Rocket cache, or both?

**Comment by piotrbak** [comment]
It's about clearing the 3rd-party only. WP Rocket's won't be served anyways as the WP Cache will be set to false.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In ThirdParty/Plugins/CDN/Cloudflare
- Add the deactivation interface implementation
- Implement the `deactivate()` method, which will call the existing `purge_cloudflare()` method

In Engine/Deactivation/Deactivation
- Add cloudflare to the deactivators array

In Engine/Deactivation/ServiceProvider
- Instantiate the Cloudflare compatibility class and add it to the provides array

### Estimate the effort ✅
Effort XS
