### ISSUE TITLE
UpdraftPlus actionscheduler_actions table notification

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#6052]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: 3.14.1
- Used the search feature to ensure that the bug hasn’t been reported before: done

**Describe the bug**
UpdraftPlus notifies the user that the actionscheduler_actions table contains too many rows.

**Expected behavior**
Find a solution on our end to avoid this issue.

**Screenshots**

**Additional context**
related hs: https://secure.helpscout.net/conversation/2301290711/430560
slack: https://wp-media.slack.com/archives/C08N8J6VC/p1689674472291959

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Blocking the issue to see if it's still accurate after fixing the related ones

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
