### ISSUE TITLE
Any change in dynamic lists may affect our tests

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#6056]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When releasing a new release we grab the dynamic lists fallback json file and commit it to develop branch before running our tests (unit and integration), and our code/tests are depending on those data from json file so any change in json may affect the test results.

I fixed quickly some of those cases here:
https://github.com/wp-media/wp-rocket/pull/6051/commits/514daf0076899b6ab9afbacec452bcd916bc3869
https://github.com/wp-media/wp-rocket/pull/6051/commits/57f9f2ee1245677f6a06f0b6c05f7405fd79924a
https://github.com/wp-media/wp-rocket/pull/6051/commits/9f245db0a617f13d2a71f51bb60a2e9a5e639d37
https://github.com/wp-media/wp-rocket/pull/6051/commits/df1d529e6e311795579c7c09f5bf5d11986cc222
https://github.com/wp-media/wp-rocket/pull/6051/commits/fed10141c300dbf7278ead561369bda062f70c4f
https://github.com/wp-media/wp-rocket/pull/6051/commits/63948326bc3db0ce7691aa1bf8ff641b7c28139c

We need to find a better way not to depend on the fallback json at all because those tests are testing our code not the external code/data.

**To Reproduce**
1. Open dynamic-lists.json file and change its content to be
```
{"rucss_inline_atts_exclusions":[],"rucss_inline_content_exclusions":[],"js_excluded_inline":[],"preload_exclusions":[],"exclude_js_files":[]}
```
2. Run integration tests
3. You will see some failures.

**Expected behavior**
We shouldn't depend on the json file contents in our tests and instead mock its return value (maybe to empty)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Don't we use the value of the transient when getting the lists? Simulating the transient value should cover the test case without need of external request, what do you think?

**Comment by CrochetFeve0251** [comment]
@Tabrisrp I was thinking about the same creating a solution based on a filter we would set on each tests that use the Delay.
We could create a trait to make it easier to manage.

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The issue is easy to reproduce changing the content from the JSON file.
## Identify the root cause
The root issue is that we are using the value from he file which can change when we update it.
## Scope a solution
For me a simple solution would be to create a trait mocking the filter in each test using that value without directly testing the handling for the JSON file:
```
trait HandleDynamicList {

  protected $config;

   public function mock_rocket_exclude_js() {
        return key_exists('exclude_js', $this->config) ? $this->config['exclude_js'] : [];
   }

   public function mock_rocket_preload_exclude_urls() {
        return key_exists('exclude_urls', $this->config) ? $this->config['exclude_urls'] : [];
   }

   public function mock_rocket_plugins_to_deactivate() {
        return key_exists('plugins_to_deactivate', $this->config) ? $this->config['plugins_to_deactivate'] : [];
   }

   public function mock_rocket_excluded_inline_js_content() {
        return key_exists('excluded_inline_js_content', $this->config) ? $this->config['excluded_inline_js_content'] : [];
   }


   public function mock_rocket_move_after_combine_js() {
        return key_exists('move_after_combine_js', $this->config) ? $this->config['move_after_combine_js'] : [];
   }

   public function mock_rocket_minify_excluded_external_js() {
        return key_exists('minify_excluded_external_js', $this->config) ? $this->config['minify_excluded_external_js'] : [];
   }


   public function mock_rocket_cache_ignored_parameters() {
        return key_exists('cache_ignored_parameters', $this->config) ? $this->config['cache_ignored_parameters'] : [];
   }

   public function set_up_dynamic_list() {
	add_filter( 'rocket_cache_ignored_parameters', [ $this, 'mock_rocket_cache_ignored_parameters' ] );
	add_filter( 'rocket_minify_excluded_external_js', [ $this, 'mock_rocket_minify_excluded_external_js' ] );
	add_filter( 'rocket_move_after_combine_js', [ $this, 'mock_rocket_move_after_combine_js' ] );
	add_filter( 'rocket_excluded_inline_js_content', [ $this, 'mock_rocket_excluded_inline_js_content' ] );
	add_filter( 'rocket_preload_exclude_urls', [ $this, 'mock_rocket_preload_exclude_urls' ] );
	add_filter( 'rocket_exclude_js', [ $this, 'mock_rocket_exclude_js' ] );
	add_filter( 'rocket_plugins_to_deactivate', [ $this, 'mock_rocket_plugins_to_deactivate' ] );
   }

   public function tear_down_dynamic_list() {
	remove_filter( 'rocket_cache_ignored_parameters', [ $this, 'mock_rocket_cache_ignored_parameters' ] );
	remove_filter( 'rocket_minify_excluded_external_js', [ $this, 'mock_rocket_minify_excluded_external_js' ] );
	remove_filter( 'rocket_move_after_combine_js', [ $this, 'mock_rocket_move_after_combine_js' ] );
	remove_filter( 'rocket_excluded_inline_js_content', [ $this, 'mock_rocket_excluded_inline_js_content' ] );
	remove_filter( 'rocket_preload_exclude_urls', [ $this, 'mock_rocket_preload_exclude_urls' ] );
	remove_filter( 'rocket_exclude_js', [ $this, 'mock_rocket_exclude_js' ] );
	remove_filter( 'rocket_plugins_to_deactivate', [ $this, 'mock_rocket_plugins_to_deactivate' ] );
   }
}
```

Then we need to use that hook on each test failing after we changed the content from `dynamic-lists.json` and adapt tests to the new inputs.

## Estimate the effort

**Comment by engahmeds3ed** [comment]
Thanks @CrochetFeve0251, This would work but the problem is that we are still adding the values from the json file but ur code will remove them after that.

I like @Tabrisrp 's idea of mocking the return of the transient, so in integration tests we can add the following code to do that mock:

```
add_filter( 'pre_transient_XXX', '__return_empty_array' );
```

this will keep the current options values as is so if any compatibility is still adding some values, it will be as is, what do u think?

**Comment by CrochetFeve0251** [comment]
> Thanks @CrochetFeve0251, This would work but the problem is that we are still adding the values from the json file but ur code will remove them after that.
> 
> I like @Tabrisrp 's idea of mocking the return of the transient, so in integration tests we can add the following code to do that mock:
> 
> ```
> add_filter( 'pre_transient_XXX', '__return_empty_array' );
> ```
> 
> this will keep the current options values as is so if any compatibility is still adding some values, it will be as is, what do u think?

That could be a nice way too but I guess we could loose some flexibility using that way.
So I am quite unsure which would be the best way.

**Comment by engahmeds3ed** [comment]
> That could be a nice way too but I guess we could loose some flexibility using that way. So I am quite unsure which would be the best way.

Plz explain what is the flexibility that we will lose using this approach so we can all think together to reach the best approach.

**Comment by CrochetFeve0251** [comment]
> > That could be a nice way too but I guess we could loose some flexibility using that way. So I am quite unsure which would be the best way.
> 
> Plz explain what is the flexibility that we will lose using this approach so we can all think together to reach the best approach.

If we use only one value for the transient then we will have all filters that are linked to it using the same value based on the new transient that we added which means `rocket_cache_ignored_parameters`, `rocket_minify_excluded_external_js`, `rocket_move_after_combine_js`, `rocket_preload_exclude_urls` etc will be linked to the same filter.

**Comment by remyperona** [comment]
You can filter the value based on what you expect in each specific test, it's not necessary to have all tests using the same value.

**Comment by remyperona** [comment]
What do we think about this one?

**Comment by engahmeds3ed** [comment]
> You can filter the value based on what you expect in each specific test, it's not necessary to have all tests using the same value.

If I understand this well, we can set the filter return to empty array as I mentioned above and when needed we can change this empty array with the same filter to return whatever needed (I doubt that we will need that because as I mentioned above we need to test our code not the API return, but just in case we need it we can update it).

If my understanding is correct so I totally agree.

**Comment by CrochetFeve0251** [comment]
> > You can filter the value based on what you expect in each specific test, it's not necessary to have all tests using the same value.
> 
> If I understand this well, we can set the filter return to empty array as I mentioned above and when needed we can change this empty array with the same filter to return whatever needed (I doubt that we will need that because as I mentioned above we need to test our code not the API return, but just in case we need it we can update it).
> 
> If my understanding is correct so I totally agree.

What disturbs me is if we use the filter from the transient then the value from multiples values will be linked to that filter which seems to be not something clean.

**Comment by MathieuLamiot** [comment]
As discussed today at daily, @CrochetFeve0251 to summarize the selected solution/grooming and move it to ToDo

**Comment by CrochetFeve0251** [comment]
As discussed with @Tabrisrp we will mock the transient filter with an empty value as it will still be possible to manipulate other filters to adapt the output depending on the test when necessary.
