### ISSUE TITLE
Improve the relation between clearing the whole cache and the preload feature

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6057]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clearing the cache we're removing everything from the filesystem and also changing all DB entries to the `pending` state:
https://github.com/wp-media/wp-rocket/blob/416966802ff6d3943b8942ea900e4681592c600d/inc/Engine/Preload/Database/Queries/Cache.php#L522

What we're not doing, is either canceling all preload rellated Action Scheduler jobs or making sure that the state of `in-progress` jobs is not changed while clearing the cache.

Those circumstances might cause AS table to grow when:
- The preload is enabled
- `rocket_clean_domain` is called too often
- Cron is not reliable or not able to handle requests in timely manner
 
**To Reproduce**
1. Enable Preload
2. Change the batch size to be 100 or 200 to make problem more visible
3. Make sure that preload Actions are registered in the AS
4. Clear the Cache each minute a couple of times
5. Check the number of Preload actions registered in the AS

**Expected behavior**
We should either clear all PreloadURL-related actions when clearing the cache, or make sure that `in-progress` (or maybe even `failed` too) entries in the cache table are not changed to pending [here](https://github.com/wp-media/wp-rocket/blob/416966802ff6d3943b8942ea900e4681592c600d/inc/Engine/Preload/Database/Queries/Cache.php#L522).

We need a brainstorm about which of the above solutions is better before preparing AC for this issue.

**Additional context**
This problem might cause several issues, for example:
https://github.com/wp-media/wp-rocket/issues/6052

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Note for test: following the steps above, a URL may have more than one pending job at AS table
![AS_actions](https://github.com/wp-media/wp-rocket/assets/76941962/4e11f2de-e392-479a-9ef0-8d66cbd0e154)

**Comment by piotrbak** [comment]
The acceptance criteria will be more clear after choosing the solution. the main objective here is:
- Avoid as much as possible exceeding number of Preload Actions in the AS defined by the batch size filter.

Issue is strictly related to this one: https://github.com/wp-media/wp-rocket/issues/6058

And the PR will be shared between those two

**Comment by piotrbak** [comment]
Fixed by https://github.com/wp-media/wp-rocket/issues/6058
