### ISSUE TITLE
PHP 5.2 notice is too aggressive

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#606]
The actual PHP 5.2 notice is too aggressive for the customers. It will be very frustrated for a customer to do the update:

- view update in the admin
- update WP Rocket
- we auto-deactivate WP Rocket and display a message: 

> WP Rocket requires at least PHP 5.3 to function properly. Please upgrade to PHP 5.3 or higher to use the plugin. The Plugin has been auto-deactivated to prevent any issue.

The customer will have no way to go back with a previous version. And most important, we don't warn them that the update will auto-deactivate the plugin.

The main idea with this notice was to display the message and provide them a link to be able to rollback to the previous major version.

**Comment by GeekPress** [comment]
We should also provide more details about how to upgrade to PHP 5.3 or +

**Comment by glueckpress** [comment]
> The main idea with this notice was to display the message and provide them a link to be able to rollback to the previous major version.

Is a rollback still possible technically? If so, +1 for a helpful link.

> We should also provide more details about how to upgrade to PHP 5.3 or +

Something like _“Please ask your web host how to upgrade your server to PHP 5.3 or higher”_?

**Comment by Tabrisrp** [comment]
Alpha 7 provides an improved version of this, let me know what you think

**Comment by GeekPress** [comment]
It's perfect with the rollback! Tested and it works well.
