### ISSUE TITLE
Site health error after wp rocket activation

### ISSUE THREAD

**Issue by Joliamendi** [wp-media/wp-rocket#6060]
Hi

**After activating wp rocket, the following error is displayed in the site health section.**

Unable to detect page cache due to possible loopback request problem. Please verify that the loopback request test is passing. Error: cURL error 28: Resolving timed out after 5000 milliseconds (Code: http_request_failed)

Page cache enhances the speed and performance of your site by saving and serving static pages instead of calling for a page every time a user visits.

Page cache is detected by looking for an active page cache plugin as well as making three requests to the homepage and looking for one or more of the following HTTP client caching response headers:

**Comment by piotrbak** [comment]
Hello @Joliamendi it looks like a problem with your server configuration, or temporary hiccup.

I'd suggest contacting our Support Team if the problem is still there
