### ISSUE TITLE
Further reduction of calls being made to Cloudflare APO

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6061]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
This issue is continuation of:
https://github.com/wp-media/wp-rocket/issues/6043

We'd like to enhance the Cloudflare cache clearing by adding URLs to their request instead of sending additional one.

For now this is not possible and blocked by:
https://github.com/cloudflare/Cloudflare-WordPress/issues/345

**Acceptance Criteria**
1. When updating the post only one request should be sent to Cloudflare API
2. Request should contain all URLs coming from `rocket_clean_files` array
3. URLs in the array should not be duplicated
4. We need to make sure taht the whole cache is not cleared while updating the single post

**Additional context**
I don't think someone from Cloudflare will resolve the above issue, we'll need to make the PR on our own.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by ivptr** [comment]
But https://github.com/cloudflare/Cloudflare-WordPress/issues/345 issue is Closed? There is some workaround mentioned there.

**Comment by piotrbak** [comment]
@ivptr It was closed without adding a fix. We'll accomodate some time to contribute to their code in order to fix this.

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The problem was easy to reproduce.
## Identify the root cause
The root cause is that we are calling the method `purgeCacheByRelevantURLs` from `Hooks` which create a new API call.

## Scope a solution

To solve that we can remove the logic calling the `purgeCacheByRelevantURLs`  and replace it by a logic storing urls that are needed to clean:
```php
/**
         * Purges posts when using purge this URL button
         *
         * @param array $urls Array of URLs.
         *
         * @return void
         */
        public function purge_cloudflare_partial( $urls ) {
                if ( ! $this->is_plugin_active() ) {
                        return;
                }

                $this->url_to_clear = array_merge($this->url_to_clear, $urls);
        }


        /**
         * Purges CF after Used CSS generation or clean
         *
         * @param string $url URL to purge.
         *
         * @return void
         */
        public function purge_cloudflare_after_usedcss( $url ) {
                if ( ! $this->is_plugin_active() ) {
                        return;
                }

                $this->url_to_clear[] = $url;
        }



```
Then we can add a callback to `cloudflare_purge_by_url` event that add theses urls to the original clean from Cloudflare:
```php
public function clear_urls($urls) {
   $urls = array_merge($urls, $this->url_to_clear);
  $this->url_to_clear = [];
   $urls = array_unique($urls);
   return $urls;
}
```

## Estimate the effort
Effort `S`

**Comment by remyperona** [comment]
As far as I understand, the duplicate query is only when updating a post which calls `rocket_clean_post()`, this solution is not fixing that.

We tried to use the `cloudflare_purge_by_url` filter in [this PR](https://github.com/wp-media/wp-rocket/pull/5953/files#diff-d514ea2190181b28ccfc908bc367eef9bced2a22991fa7fe3012aeeb34509559), and then changed the approach because it was not working, neither the other filters.

**Comment by CrochetFeve0251** [comment]
@Tabrisrp I don't get why it doesn't solve the issue as with that solution yes we call trice your hooks but they won't call cf directly to clear the urls.
It is the cf request which happens later that will clear urls.

Also on the PR I see a discussion about `cloudflare_purge_everything_actions` filter which is a different one from `cloudflare_purge_by_url` which is runned each time cf clear urls: https://github.com/cloudflare/Cloudflare-WordPress/blob/4ad24c88c9a1ed58b2aa288ce3ca587ba873566c/src/WordPress/Hooks.php#L171

**Comment by CrochetFeve0251** [comment]
@Tabrisrp 
I see 2 ways to pass here:
- playing with `$wp_filter` to unregister the action from Cloudflare.
- Modifying CF plugin so we can get the instance from Hooks and unregister the filter with the event manager.

Once we done that then we should not have anymore duplucate calls on `rocket_clean_post` as only our clearing logic is remaining.

**Comment by CrochetFeve0251** [comment]
## Scope a solution

To solve that issue we will need to unregister the Cloudflare callback to event `deleted_post`.
For that we will have to add the following logic into the thirdparty class on the event `init`: 

```php
public function unregister_cloudflare_clean_on_post() {
 global $wp_filter;
  $original_wp_filter = $wp_filter[ 'deleted_post' ]->callbacks;

		foreach ( $original_wp_filter[ $priority ] as $key => $config ) {

			if ( substr( $key, - strlen( 'purgeCacheByRelevantURLs' ) ) !== 'purgeCacheByRelevantURLs' ) {
				continue;
			}

			unset($wp_filter['deleted_post' ]->callbacks[$key]);
		}

}
```

## Estimate the effort
Effort `S`

**Comment by MathieuLamiot** [comment]
@CrochetFeve0251 Process police! Hey, please make sure to add the effort tag so that we get clean data. Thanks!

**Comment by ivptr** [comment]
Our editors find this frustrating, it takes ages to save post. Any update?

**Comment by rfischmann** [comment]
Has this also been tested after updating a theme through the Customize area in WordPress? WP Rocket is killing my server every time I make a change there, it seems it sends multiple commands to clear everything in Cloudflare's cache.

**Comment by rfischmann** [comment]
Yeah, the issue remains on 3.15.1. It completely obliterated my server as soon as updating WP Rocket…
