### ISSUE TITLE
WooCommerce deprecating Cart Fragments api from 7.8

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6062]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
**Note:** _This one kinda falls on the themes side, I am opening the issue so we can investigate if there is something we can do on our end. Even when we are not _causing_ the error, it is visible only when using a cache plugin.
Themes will eventually update their code. But legacy customers will be affected._ 

Customers with a theme using the cart fragments API + Woocommerce 7.8 or newer + WP Rocket will have issues. A typical case is with **minicarts not being updated**. But there might be more issues. This also affects other caching plugins

Related Woocommerce doc about the change regarding **cart fragments** api: 
https://developer.woocommerce.com/2023/06/16/best-practices-for-the-use-of-the-cart-fragments-api/ 

Adding this snippet to bring the functionality back on the themes, fixes the issue:
```
function enqueue_wc_cart_fragments() { wp_enqueue_script( 'wc-cart-fragments' ); }
add_action( 'wp_enqueue_scripts', 'enqueue_wc_cart_fragments' );
```

**To Reproduce**
1. On a setup with: **Flatsome older than 3.17.4** (latest version has the issue) + **Woocommerce 7.8 or newer** + **WP Rocket**
2. Add a product to Cart, the minicart will update
3. Browse other cached pages
4. Minicart will keep previous values
5. See the lack of `/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js`

**Expected behavior**
We need to R&D to see if there is something we can do from our side.

**Additional context**
Slack
https://wp-media.slack.com/archives/C43T1AYMQ/p1689852423466669

Tickets: 
https://secure.helpscout.net/conversation/2306809566/431581?folderId=273766
https://secure.helpscout.net/conversation/2306938091/431609?folderId=273761
https://secure.helpscout.net/conversation/2297265269/429721

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue and it probably should be implemented on the theme's side. We might reopen this in the future.
