### ISSUE TITLE
Safari loads googletagmanager forever with enabled privacy

### ISSUE THREAD

**Issue by wizzyto12** [wp-media/wp-rocket#6063]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - I am
- Used the search feature to ensure that the bug hasn’t been reported before - I did a search for "privacy safari" and looked around "Safari" open/closed bug reports.

**Describe the bug**
I encountered a really nieche case running Safari on macOS. When I have all the privacy settings enabled in my browser, which hides my IP address and blocks trackers (like gtm and fb), the page waits forever for the GTM script to load (but it does not because its blocked by privacy settings) and further javascript loading is not executed.

**To Reproduce**
1. Turn on delay javascript execution
2. Turn on privacy settings in safari
3. Visit any page on your website
4. Make sure that in Network you see how "googletagmanager.com" loads forever and no further javascript is called

**Expected behavior**
Javascript loading should be loaded fully.

**Screenshots**
[<a href="https://ibb.co/xFw1gzm"><img src="https://i.ibb.co/phNfK4W/wprbug2.jpg" alt="wprbug2" border="0"></a>](https://i.ibb.co/phNfK4W/wprbug2.jpg)

**Additional context**
None

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
