### ISSUE TITLE
Fatal Error with WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by rvola** [wp-media/wp-rocket#6064]
**Describe the bug**
Since WP-Rocket 3.14. I get the following Fatal error:

`Fatal error: Declaration of WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\LoggerTrait::log($level, Stringable|string $message, array $context = []): void in /wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php online 58`

**To Reproduce**
Activate the 3 plugins in the following order:
1. WooCommerce `7.9.0` and earlier
2. WP-Rocket `3.14.2.1`
3. WooCommerce PayPal Payments `2.2.0`
4. BOOM 💣

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Can reproduce the error with the following steps:

1. WooCommerce 7.9.0 
2. WooCommerce PayPal Payments 2.2.0
3. Install and activate WPR 3.14.2.1 using [composer install](https://docs.wp-rocket.me/article/1301-wp-rocket-installation-from-github-using-composer)
`[25-Jul-2023 08:50:05 UTC] PHP Fatal error:  Declaration of WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\LoggerTrait::log($level, Stringable|string $message, array $context = []): void in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php on line 58`
Notes:
- PHP used is 8.2.8
- The same is happening using WPR 3.12.6 + composer install
- WPR debug is disabled
- Using the zip file of 3.14.2.1 is working fine without any fatal error

**Comment by remyperona** [comment]
I believe this will be fixed in WP Rocket 3.15 via the following: https://github.com/wp-media/wp-rocket/issues/5366

@piotrbak

**Comment by piotrbak** [comment]
@wp-media/qa Could you accomodate some time to test it against 5366 PR? (it's not a priority)

**Comment by CrochetFeve0251** [comment]
The grooming looks fine to me

**Comment by vmanthos** [comment]
@piotrbak I checked this with https://github.com/wp-media/wp-rocket/tree/branch-3.15 where #5949 is merged and the fatal error isn't there.

**Comment by piotrbak** [comment]
@vmanthos Thank you! 🙏

**Comment by Mai-Saad** [comment]
https://github.com/wp-media/wp-rocket/issues/6064#issuecomment-1649413687 Fixed on 3.15 using PHP 8.2.9 without WPR debug. (If WPR debug is enabled, fatal will be there even without 3rd parties, related to https://github.com/wp-media/wp-rocket/issues/5918)
