### ISSUE TITLE
Duplicate query when checking rucss table

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#6068]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
There is a duplicate query when we check if the RUCSS table exists. 
`SHOW TABLES LIKE 'wp\\_wpr\\_rucss\\_used\\_css`

**To Reproduce**
1. Enable Query Monitor plugin
2. View the Duplicate Queries
3. See the duplicate query: https://jumpshare.com/v/TDhTbgX5P5Wz3gb8ByiF

**Expected behavior**
No duplicate query

**Screenshots**
https://jumpshare.com/v/TDhTbgX5P5Wz3gb8ByiF

Per @engahmeds3ed :

> It easily can be fixed [here](https://github.com/wp-media/wp-rocket/blob/b2f0b8f870002148959cb3d28a62671489ac7228/inc/Engine/Optimization/RUCSS/ServiceProvider.php#L53)
> by replacing `add` with `share`
> this will create only one instance from the table class and share it with whatever class calls it.

Original Ticket: https://secure.helpscout.net/conversation/2305707443/431357?folderId=377611

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
Already groomed during escalation.

Effort [XS]

**Comment by MathieuLamiot** [comment]
https://wp-media.slack.com/archives/C056ZJMHG0P/p1690369830895799?thread_ts=1690329563.456729&cid=C056ZJMHG0P
