### ISSUE TITLE
Extra "?" added on minified CSS files which causes a 404 error

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#607]
Before activating the minified CSS option:

`<link rel="stylesheet" type="text/css" href="http://tuto-wordpress.dev/wp-content/themes/blogdrops/style.css" media="screen" />`

After

`<link rel="stylesheet" type="text/css" href="http://tuto-wordpress.dev/wp-content/cache/min/1/wp-content/themes/blogdrops/style.css?" media="screen" / data-minify="1">`

Same behavior for all CSS minified files

**Comment by Tabrisrp** [comment]
Should be fixed in alpha4. Re-open if needed.

**Comment by GeekPress** [comment]
I still have the issue with alpha5

**Comment by Tabrisrp** [comment]
tested on smashingcoding and fixed
