### ISSUE TITLE
Disable cache features for a specific amount of time

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#6071]
**Is your feature request related to a problem? Please describe.**
Some customers have reported disabling WP Rocket's cache while making changes to their sites and then reactivating it to rule out any issues generated by WP Rocket. 

If the customer forgets to reactivate the WP Rocket cache after completing changes to the site, this could result in the site being served as uncached for long periods of time.

**Describe the solution you'd like**
Some customers have reported disabling the WP Rocket cache while making changes to their site so that they can then reactivate it to rule out any issues generated by WP Rocket. 

If the customer forgets to reactivate the WP Rocket cache after completing changes to the site, this could result in the site being served as uncached for long periods of time.

**Describe alternatives you've considered**
Having an option similar to Cloudflare's developer mode, which disables caching for a certain period of time, would be useful in such cases. 

**Additional context**
Enabling this option, when available, should provide warnings that  if changes made during the cache deactivation period conflict with the cache or one of WP Rocket's optimisation features, then when the cache is automatically reset, the site may malfunction. 

Ticket related:  https://secure.helpscout.net/conversation/2314819250/432971?folderId=2952229

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
