### ISSUE TITLE
Interference of jet engine data stores with wp-rocket plugin

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#6073]
Hi,
When the wp-rocket plugin is active, the performance of jet engine data stores is disrupted. For example, I like a post as a guest user. In this case, the like count will not be updated for other users. Until the admin clears the wp-rocket plugin cache. Is there any quick fix for this problem?

**Comment by DahmaniAdame** [comment]
Jet Engine likely has a hook that fires when a post is submitted.

You should trigger a `rocket_clean_post($post_id)` whenever it's done. 

Reference - https://docs.wp-rocket.me/article/93-rocketcleanpost

Jet Engine support should help confirm the hook and if they can add `rocket_clean_post` on their end.
