### ISSUE TITLE
Display a loader when updating the dynamic lists

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6075]
**Is your feature request related to a problem? Please describe.**

When clicking the "UPDATE LISTS" button in the Tools tab it can take several seconds until the updates are fetched or return the message that the lists are up to date:
[Screencast from 2023-08-01 12-25-14.webm](https://github.com/wp-media/wp-rocket/assets/193660/8d8391af-b5df-45f4-aeae-b81d086f8094)

This can be confusing for the user as it seems nothing is happening and can lead to additional clicks on the button.

**Describe the solution you'd like**

After clicking the button, spin the icon that's in the "UPDATE LISTS" button and stop the spinning when the update messages are displayed.
We are doing something similar when clicking the "Refresh info" link in WP Rocket's dashboard.

**Describe alternatives you've considered**

We could add a notice that the update process can take a while and ask users to wait for a few seconds.

**Additional context**
N/A

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
