### ISSUE TITLE
Used CSS isnot automatically generated for home page when switch theme while preload is off

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6076]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.14.2.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When we switch theme while preload is off, we display a notice that used CSS was created for the home page although it was not 

**To Reproduce**
1. Disable preload
2. Enable RUCSS 
3. Visit the home page => used CSS is there
4. switch the theme and check the used CSS table

**Expected behavior**
Entry is added for the home page

**Additional context**
- It was working fine on 3.12.6.1

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Probably related, the Home page is displaying old styles when switching theme with the following steps on newlabs:
1- preload off, RUCSS on
2- visit the home page => used CSS is there
3- clear cache
4- switch theme
5- visit home => old CSS is displayed

Notes: 
- clear the whole cache then revisit home will work fine and the right CSS will be created
- using 2nd layer of cache, the same problem is there even without step 3

https://github.com/wp-media/wp-rocket/assets/76941962/4115783b-91d8-4841-9257-4b849cd1fa1e

**Comment by piotrbak** [comment]
@Tabrisrp I'm thinking, is this possible that we're doing a home request before removing the Used CSS data from DB?

**Comment by remyperona** [comment]
it's possible yes, we have a preload on `switch_theme` with the same priority as the truncate used CSS.

**Comment by piotrbak** [comment]
That would be a problem for all hosts that are using their own cache, do you think this is just a matter of simple changing the priority? If so, it would be good to handle it in this PR.

If not, I'll create a new issue to do proper grooming.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
