### ISSUE TITLE
The whole cache is cleared when the incompatible plugins dynamic list is the only one updated

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6077]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: 
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When:
1. Clicking the "UPDATE LISTS" button in the tools tab and 
2. the incompatible plugins list is the only one that has been updated 

the whole cache is cleared.

This isn't necessary since the content of the specific dynamic list doesn't affect the front end.

**To Reproduce**

1. Add or change an entry in the incompatible plugins list in the staging backend.
2. Make sure URLs are cached in the `/cache/wp-rocket/` folder.
3. Click on the "UPDATE LISTS" button in the tools tab.
4. Check the cache folder - the cache will be cleared.

**Expected behavior**

When the incompatible plugins list is the _only_ one updated we should not clear the whole cache.

The cache should still be cleared if any of the additional two lists are updated alongside the incompatible plugins list.

**Screenshots**

N/A

**Additional context**

**Slack discussion:** https://wp-media.slack.com/archives/CUT7FLHF1/p1690877516313079

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. The cache should not be cleared when the only updated list is related to Incompatible Plugins
2. The cache should be cleared when other lists are updated
3. The cache should be cleared when other lists + Incompatible Plugins list is updated

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the issue

### Identify the root cause ✅
We are purging the cache when there is a successful response after the request irrespective of the list that was updated.

### Scope a solution ✅
We can handle this behaviour from the backend and return back a different response when only the incompatible plugins list is updated but I don't think it's necessary since we have all the parameters to handle this on the plugin.

So to fix this on the plugin, we can start by adding a new property like this `list_exclusions_purge` to this class `Engine\Optimization::DynamicLists` This new property will hold the names of list that will not purge the cache when we update them.
```
private $list_exclusions_purge = [
    'Incompatible plugins Lists',
];
```
After this line we can have a variable with a default state of false;
`$purge = false;`

At this point:
https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L138-L143
We can do a simple check:
```
if ( ! in_array( $provider->title, $list_exclusions_purge ) {
    $purge = true;
}
```
Then pass `$purge` as an argument to the `rocket_after_save_dynamic_lists` action

Finally in `WP_Rocket\Engine\Cache::PurgeActionsSubscriber`
We will bail out just before this line if purge is false:
https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Cache/PurgeActionsSubscriber.php#L169

Estimate the effort ✅
[S]

**Comment by engahmeds3ed** [comment]
@jeawhanlee what if we added a new attribute to each provider array which needs the cache to be cleared here:
https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/ServiceProvider.php#L55-L74
something like:
```
$providers = [
	....
	'incompatible_plugins' =>
		(object) [
			'api_client'   => $this->getContainer()->get( 'dynamic_lists_incompatible_plugins_lists_api_client' ),
			'data_manager' => $this->getContainer()->get( 'dynamic_lists_incompatible_plugins_lists_data_manager' ),
			'title'        => __( 'Incompatible plugins Lists', 'rocket' ),
			'clear_cache' => true,
		],
];
```
Then here:
https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L107-L106
Create a new variable as u mentioned `$should_purge` with default value as `false`

Then here after this line:
https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L143

add the following line of code:
```
$should_purge |= $provider->clear_cache ?? false;
```

Then as u mentioned pass the `$should_purge` variable to the action here:
https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L152

Finally here:
https://github.com/wp-media/wp-rocket/blob/160a49ef1be880c8d88031e9fb421bcea29e5f58/inc/Engine/Cache/PurgeActionsSubscriber.php#L57

we need to create a new method for this action specifically as the current one is shared between some other actions. Then bailout if the first argument was not true.

**Comment by CrochetFeve0251** [comment]
> @jeawhanlee what if we added a new attribute to each provider array which needs the cache to be cleared here:
> 
> https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/ServiceProvider.php#L55-L74
> 
> something like:
> 
> ```
> $providers = [
> 	....
> 	'incompatible_plugins' =>
> 		(object) [
> 			'api_client'   => $this->getContainer()->get( 'dynamic_lists_incompatible_plugins_lists_api_client' ),
> 			'data_manager' => $this->getContainer()->get( 'dynamic_lists_incompatible_plugins_lists_data_manager' ),
> 			'title'        => __( 'Incompatible plugins Lists', 'rocket' ),
> 			'clear_cache' => true,
> 		],
> ];
> ```
> 
> Then here: https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L107-L106 Create a new variable as u mentioned `$should_purge` with default value as `false`
> 
> Then here after this line:
> 
> https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L143
> 
> add the following line of code:
> 
> ```
> $should_purge |= $provider->clear_cache ?? false;
> ```
> 
> Then as u mentioned pass the `$should_purge` variable to the action here:
> 
> https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L152
> 
> Finally here:
> 
> https://github.com/wp-media/wp-rocket/blob/160a49ef1be880c8d88031e9fb421bcea29e5f58/inc/Engine/Cache/PurgeActionsSubscriber.php#L57
> 
> we need to create a new method for this action specifically as the current one is shared between some other actions. Then bailout if the first argument was not true.

@engahmeds3ed that would be cool to have data classes that would formalize the shape of that providers and prevent us from checking the existence of the property later in the code.

**Comment by jeawhanlee** [comment]
> @jeawhanlee what if we added a new attribute to each provider array which needs the cache to be cleared here:
> 
> https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/ServiceProvider.php#L55-L74
> 
> 
> something like:
> ```
> $providers = [
> 	....
> 	'incompatible_plugins' =>
> 		(object) [
> 			'api_client'   => $this->getContainer()->get( 'dynamic_lists_incompatible_plugins_lists_api_client' ),
> 			'data_manager' => $this->getContainer()->get( 'dynamic_lists_incompatible_plugins_lists_data_manager' ),
> 			'title'        => __( 'Incompatible plugins Lists', 'rocket' ),
> 			'clear_cache' => true,
> 		],
> ];
> ```
> 
> Then here: https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L107-L106 Create a new variable as u mentioned `$should_purge` with default value as `false`
> 
> Then here after this line:
> 
> https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L143
> 
> add the following line of code:
> 
> ```
> $should_purge |= $provider->clear_cache ?? false;
> ```
> 
> Then as u mentioned pass the `$should_purge` variable to the action here:
> 
> https://github.com/wp-media/wp-rocket/blob/e307f7249ee2664e5e69def043a8720963b3c42e/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L152
> 
> Finally here:
> 
> https://github.com/wp-media/wp-rocket/blob/160a49ef1be880c8d88031e9fb421bcea29e5f58/inc/Engine/Cache/PurgeActionsSubscriber.php#L57
> 
> we need to create a new method for this action specifically as the current one is shared between some other actions. Then bailout if the first argument was not true.

You are right @engahmeds3ed, we can do it this way
