### ISSUE TITLE
Cloudflare: Date archive page shall be purged when add a post

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6078]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.14.2.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using CF cache everything or even CF APO, when we add a new post while preload is disabled, we arenot clearing the date archive page

**To Reproduce**
1. Website using CF APO or CF addon with optimal settings and cache everything
2. Create a post
3. Visit the date archive page i.e domain/2023/08/01 => cache header is hit
4. Add a new post
5. Refresh the page in step 3 and check the headers

**Expected behavior**
Headers shall be MISS (CF cache for archive page is cleared after add/edit/delete post)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
