### ISSUE TITLE
Add a hint on scripts deferred by WP Rocket

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6091]
**Is your feature request related to a problem? Please describe.**
This will help our internal WPR Front-end debugger find scripts deferred by WP Rocket from the ones processed by other plugins. That will help support agent process defer JS ticket with better efficiency and accuracy. 

**Describe the solution you'd like**
Add an attribute as a hint on JS scripts deferred by WP Rocket. Attribute naming protocol to be defined to be used in similar cases in the future requiring a hint in the future. 

**Describe alternatives you've considered**
N/A

**Additional context**
Discussed in support meeting (2/8/2023).

**Comment by piotrbak** [comment]
The attribute to be added to the deferred scripts by WP Rocket:
`data-rocket-defer`
