### ISSUE TITLE
WP rocket Only Caching URLs and pages with trailing slash. While my site displays no Slash.

### ISSUE THREAD

**Issue by jaynchou** [wp-media/wp-rocket#6093]
**Before submitting an issue please check that you’ve completed the following steps:**
Latest version- Check
No report- Check

**Describe the bug**
My wp rocket is only caching pages with trailing slash, while I use a plugin called permalink manager pro to remove all the trailing slash in the urls. So all my urls and pages without trailing slash are not cached. Now I want wp rocket to cache urls without slash.

**Comment by piotrbak** [comment]
Hello @jaynchou WP Rocket is caching pages according to the trailing slash settings in WordPress Core `Settings > Permalinks` if you want to see pages without trailing slash, please change it there.

If you have any further problems, please reach our Support Team.

**Comment by jaynchou** [comment]
I mean I can't remove the slash in the default WordPress Core Settings > Permalinks that's why I use plugins like permalink manager pro
