### ISSUE TITLE
Polylang - The cache isn't cleared when changing the setting for the default language to be part of the URL

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6094]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.14.3`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

By default, Polylang will _not_ display a language code for the default language, e.g. if English is the default language, the URLs will _not_ have `en` following the TLD.

This can change by unchecking the **Hide URL language information for default language** checkbox in their **URL Modification** settings `/wp-admin/admin.php?page=mlang_settings`. This action changes the permalinks for the default language from, e.g. https://example.com/hello-world to https://example.com/en/hello-world 

When this happens we are not clearing the cache for the English language which is still part of the main cache folder, e.g. `/cache/wp-rocket/example.com`. This **prevents navigating to the `/en/` URLs** until the cache is manually cleared.

Also, when clearing and preloading we are not taking into consideration the new permalink structure, i.e. old English URLs without `/en/` are still in the `wpr_rocket_cache` table.

**To Reproduce**
1. Install/activate Polylang and set at least 2 languages.
2. Let the cache be preloaded.
3. Uncheck the **Hide URL language information for default language** option.
4. Clear and preload cache for all languages. The non-default cache is cleared while that of the old default language URLs is not.

**Expected behavior**

When changing the **Hide URL language information for default language** option we should clear the default languages cache and remove the respective URLs from the database. 

**Screenshots**

N/A

**Additional context**

In my tests, the homepage, e.g. `/en/` and `/fr/` wasn't cached. This will need further investigation.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Even with `the Hide URL language information for default language option.` checked, the clear cache of ar isnot working while fr is working and en (main) will clear en and ar (tested on newlabs with wpr 3.15.7 and Polylang 3.5.3)

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
