### ISSUE TITLE
Conflict between WP Rocket, CookieBot, and Facebook for woocommerce

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#6103]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**

We need three plugins to be enabled in the same time:
1. WP Rocket
2. Facebook for woocommerce
3. CookieBot

So you need to only activate cookiebot after enabling woocommerce and Facebook For WooCommerce then go to cookiebot plugins page to enable the addon as in the attached image.

![image](https://github.com/wp-media/wp-rocket/assets/15707971/256a2d0e-a5ac-48be-b74b-ccc328b196c5)

**What is the error?**
```
PHP Fatal error:  ob_start(): Cannot use output buffering in output buffering display handlers in /www/xxx/public/wp-content/plugins/cookiebot/src/lib/buffer/Buffer_Output_Tag.php on line 101
```

**When this happened?**
This issue started with v3.14.1 specifically here:
https://github.com/wp-media/wp-rocket/pull/5920

**More technical details:**
In our buffer we are checking if the current url is excluded from preload (even when preload is disabled) and exactly [here](https://github.com/wp-media/wp-rocket/blob/d7660779161a9b51ce9c5abbabd30fc7ead5eecc/inc/Engine/Preload/Subscriber.php#L506) we are using WP_Query class to get all private urls so we can exclude the current url if it's a private url.

This WP_Query is firing the action [pre_get_posts](https://github.com/WordPress/wordpress-develop/blob/bf911a96a8a07f2158bc4093293724717130f618/src/wp-includes/class-wp-query.php#L1881) which is used inside cookiebot plugin (as an integration with facebook for woocommerce plugin), exactly [here](https://plugins.trac.wordpress.org/browser/cookiebot/trunk/src/addons/controller/addons/facebook_for_woocommerce/Facebook_For_Woocommerce.php#L49)

The problem happens because they use ob_start (buffer) [here](https://plugins.trac.wordpress.org/browser/cookiebot/trunk/src/lib/buffer/Buffer_Output_Tag.php#L101) and that's called inside our buffer so it fails with the previously mentioned error.

**Suggested Solutions:**
We can find another instead of wp_query to check the private urls (as we are inside the buffer so wordpress is being loaded so we can use the function get_post_status if the current page is singular - Maybe -)
disable their buffer exactly before our code  and enable it again after it, I think their code is not needed in that place but we can discuss that with them.

**To Reproduce**
Mentioned above.

**Expected behavior**
Three plugins should operate smoothly without a problem.

**Additional context**
We may also check with CookieBot team to see if they can fix that from their side or not. [product decision]

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Do we have an environment where we can reproduce the issue? I wasn't able to configure one

**Comment by engahmeds3ed** [comment]
After some discussions with the team, we have two ideas here:-
1. We can find a way to remove the callback for the action [pre_get_posts](https://plugins.trac.wordpress.org/browser/cookiebot/trunk/src/addons/controller/addons/facebook_for_woocommerce/Facebook_For_Woocommerce.php#L49) before we call `WP_Query` and return it back after finishing.
2. Move this `wp_query` outside our buffer in one of two ways:
    1. Replace `wp_query` with another way to get private posts.
    2. Use this `wp_query` inside init hook to set a transient with post IDs so we can use those ids directly in the buffer without problems and I think init is running before our buffer, right? but in this case we will need to carefully choose the transient lifespan also we need to handle the case of changing posts status from private to any status (remove this IP from transient) and changing post status to private (add this ID to the transient)

## Direct questions to CookieBot team:
1. For the first solution I provided, will this affect u in any way? I mean removing the action's callback and adding it again.
2. If it'll not affect u, what is the best way to get the instance of class that is being used in registering this callback to be used with `remove_action` core function?
3. Is there any way for you not to use this action that has a buffer inside?

Thanks.

**Comment by UCjatamayo** [comment]
@piotrbak @engahmeds3ed new version of Cookiebot was released today that changes the action causing the error.
