### ISSUE TITLE
"?" missing after file extension on URL with CDN which causes 404 error

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#611]
Without CDN:

`<script type='text/javascript' src='http://tuto-wordpress.dev/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>`

With CDN:

`<script type='text/javascript' src='http://cdn.tuto-wordpress.dev/wp-includes/js/jquery/jquery.jsver=1.12.4'></script>`

The ? is missing after the .js which cause a 404 error

**Comment by Tabrisrp** [comment]
Fixed in latest alpha. Re-open if needed.
