### ISSUE TITLE
Tiktok (ttclid) and touch() File name too long

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#6113]
Hello
Recently we are noticing big query string due to tiktock click IDs, and touch fails
touch(): Unable to create file ..... because File name too long

Is there any way to skip the ID or rename it to something smaller, so it can fit?

**Comment by piotrbak** [comment]
It's a duplicate of this issue:
https://github.com/wp-media/wp-rocket/issues/2440

**Comment by danieliser** [comment]
@piotrbak Please see my comments on #2440, this should not even be an error, and is simple enough to check for before you try writing to a specific path. Please for the love of clean logs just add a check on the lenght of a path before attempting to write it. Max 255 bytes on `NIX.
