### ISSUE TITLE
When are we getting Brotli support and rules for HTACCESS

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [wp-media/wp-rocket#6117]
**Is your feature request related to a problem? Please describe.**
Feature request. https://github.com/wp-media/wp-rocket/issues/1524
Please can we have an update. Raising this feature request to prompt an official response from WP-Rocket

**Describe the solution you'd like**
Brotli headers for HTACCESS and full compatibility with NGINX and Brotli

**Describe alternatives you've considered**
Not renewing WP-Rocket in favour of a solution that supports Brotli

Please provide an update it has been 4 years since the issue was raised!

**Comment by piotrbak** [comment]
Hello @thinkjarvisdesignandmarketing thanks for creating the issue. I'm not able to provide you with the exact estimation, this is the duplicate of https://github.com/wp-media/wp-rocket/issues/1524

**Comment by thinkjarvisdesignandmarketing** [comment]
@piotrbak several others are asking about this.
When will we get Brotli headers for Wp-Rocket? I assume all that is needed is an updated header to include Brotli so some fairly minor changes to HT.access?
