### ISSUE TITLE
Fatal error:  mysqli_fetch_object(): Cannot use output buffering in output buffering display handlers

### ISSUE THREAD

**Issue by davefx** [wp-media/wp-rocket#6118]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version *Yes*
- Used the search feature to ensure that the bug hasn’t been reported before 
  *Yes. This is probably related with #6103, but I'm experiencing the problem after deactivating all plugins and with a standard theme (no other plugins involved)*

**Describe the bug**
In one of our sites, accessing some pages return a blank page for guest users.

Checking the logs, I can see the error `PHP Fatal error:  mysqli_fetch_object(): Cannot use output buffering in output buffering display handlers in /www/thehealthymummyblogau_207/public/wp-includes/class-wpdb.php on line 2425` every time the affected pages are visited.

To see if the bug was related to any other existing plugin or theme, I've deactivated all of them except WP-Rocket, and I've activated a standard theme (twentyfourteen), but with no luck: the error is still there when accessing these pages.

I'm getting this error in the logs also if I click on the "[Clear and preload cache]" button, in the WP-Rocket.

**To Reproduce**
1. Activate WP-Rocket
2. Visit the affected page from an Incognito window
3. See error (blank page).

**Expected behavior**
The page should be viewed without any involved fatal error.

**Screenshots**

**Additional context**
This is happening in a site hosted in Kinsta. Not sure if this is related, as we have other sites hosted there that are not affected by this bug.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
Hello @davefx have you already contacted our Support Team? We'd definitely need to have access to the website to ivnestigate this further.

**Comment by davefx** [comment]
Indeed! We are waiting for a response from them.
--
David Marín Carreño ***@***.***>

**Comment by piotrbak** [comment]
We didn't have any feedback about this issue for a long time now. Feel free to reopen if it still exists
