### ISSUE TITLE
Woodmart dynamic css files are not reflected in cache

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6134]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Woodmart theme is using dynamic url for CSS files which change whenever we save settings at Woodmart theme. This results in a CSS console error when hard-refreshing the cached page

**To Reproduce**
1. Woodmart theme is active
2. Cache the home page
3. Go to Woodmart-> settings and save 
4. Hard refresh the home page

**Expected behavior**
No console error when visiting the FE

**Screenshots**
![Screenshot from 2023-09-01 16-09-28](https://github.com/wp-media/wp-rocket/assets/76941962/c8d994bb-080f-477d-b1df-f25802f77da2)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
That could be caused by outdated version of WoodMart theme. I've just contacted their team to receive the newest one

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
