### ISSUE TITLE
Blank page when pressing clear cache after the last update.

### ISSUE THREAD

**Issue by nicutor** [wp-media/wp-rocket#6135]
Hi there,

A blank page is shown when pressing "Clear and preload cache"
The same is when I am trying to rollback or export settings so I am unable to downgrade to a previous version.
I cannot deactivate the plugin as the same empty page is shown.

I found no errors on nginx or php logs.
There are no issues when DEBUG is enabled on wordpress.

What is missing? What should I do to fix this?
The issue started after the last wp-rocket update on 29 Aug.

Thank you!

I am using:

wp-rocket version: 3.14.4.2
wordpress version: 6.3.1
nginx: 1.24.0
php: 7.4
os: ubuntu 18.04

**Comment by nicutor** [comment]
Anyone please?

I've tried with php 8.1, wp-rocket 3.13.x in all combinations with and without cloudflare, object caching and opcache.
I've also disabled all wp-rocket options and the result is the same.

Is there something else I am missing?

**Comment by piotrbak** [comment]
@nicutor Thanks for creating the issue. Have you already reached our Support Team? Our GitHub is a place for confirmed issues with correct steps to reproduce them in clean environment.

Please be in touch with our Support Team and we'll investigate this.
