### ISSUE TITLE
Lazyload for CSS background images unnecessary exclusions are in WP Rocket's code 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6137]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.15`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

For the JavaScript code handling the lazyload of CSS background images, we added exclusions from the JavaScript-handling features in WP Rocket's core:
https://github.com/wp-media/wp-rocket/blob/6417d8f8ce6d465c9430934fcbb60b3fb8e45567/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L147-L149

Those should have been added in the back end (dynamic lists) when we were using the JavaScript file.

Currently, after changing the file to an inline script, we only need to keep the Delay JS Execution exclusion which has already been added to the back end. (Kudos to @Mai-Saad for finding that the inline script was delayed).

**To Reproduce**
N/A

**Expected behavior**

We need to remove the part of the code related to the exclusions.

**Screenshots**
N/A

**Additional context**
N/A

**Acceptance Criteria (for WP Media team use only)**
- Both Lazy Load scripts are excluded from Delay JS, Defer JS and Combine JS using the backend 
- The scripts are not excluded within our codebase
- No JS errors in the console error when activating each feature together with LazyLoad Background CSS Images

**Comment by Miraeld** [comment]
## Scope a solution
To remove the part of the code related to the exclusions we can remove references in :
https://github.com/wp-media/wp-rocket/blob/6417d8f8ce6d465c9430934fcbb60b3fb8e45567/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L147-L149

Without forgetting removing these functions : 
https://github.com/wp-media/wp-rocket/blob/6417d8f8ce6d465c9430934fcbb60b3fb8e45567/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L568

https://github.com/wp-media/wp-rocket/blob/6417d8f8ce6d465c9430934fcbb60b3fb8e45567/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L583

https://github.com/wp-media/wp-rocket/blob/6417d8f8ce6d465c9430934fcbb60b3fb8e45567/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L598

and their respectives tests : 

https://github.com/wp-media/wp-rocket/blob/develop/tests/Integration/inc/Engine/Media/Lazyload/CSS/Subscriber/addLazyloadScriptRocketExcludeDeferJs.php

https://github.com/wp-media/wp-rocket/blob/develop/tests/Unit/inc/Engine/Media/Lazyload/CSS/Subscriber/addLazyloadScriptRocketExcludeDeferJs.php

https://github.com/wp-media/wp-rocket/blob/develop/tests/Unit/inc/Engine/Media/Lazyload/CSS/Subscriber/addLazyloadScriptRocketDelayJsExclusions.php

https://github.com/wp-media/wp-rocket/blob/develop/tests/Integration/inc/Engine/Media/Lazyload/CSS/Subscriber/addLazyloadScriptRocketDelayJsExclusions.php

https://github.com/wp-media/wp-rocket/blob/develop/tests/Unit/inc/Engine/Media/Lazyload/CSS/Subscriber/addLazyloadScriptExcludeJs.php

https://github.com/wp-media/wp-rocket/blob/develop/tests/Integration/inc/Engine/Media/Lazyload/CSS/Subscriber/addLazyloadScriptExcludeJs.php

## Effort Estimation:
XS
## Development steps:
- [] Delete the test
- [] Delete the mention of these functions

## Can be peer-coded: No
