### ISSUE TITLE
Wrong order of features in the Edit Page widget

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6138]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In the edit page widget the order of features is not correct:
![image](https://github.com/wp-media/wp-rocket/assets/26767037/f8568b9c-9f77-4b35-aa80-50bcd13defb7)

Lazyload for background CSS images [should be under the](https://www.notion.so/wpmedia/Lazy-Load-CSS-background-images-da1ddff526d34b0ca307af440cc7db36?pvs=4#2c4601803161403bb7a7a1dcea6e453c) `LazyLoad for iframes/videos`.

**To Reproduce**
1. Go to Edit Page
2. See the order of the features on the right
3. See error

**Acceptance Criteria (for WP Media team use only)**
1. Lazyload for background CSS images should be under the `LazyLoad for iframes/videos` in the Edit Page widget.
2. We should accomodate what's stated [here](https://github.com/wp-media/wp-rocket/issues/6138#issuecomment-1706199353).
3. Current order of features should be preserved
4. Deactivation of the feature form the editor point of view should deactivate it **only** for specific page, not site-wide

**Comment by camilamadronero** [comment]
Hi, just looping in here to suggest two extra changes:

1. Use the full name of the features. Ex: change `Defer JS` for `Load JavaScript deferred`.
2. Use the same order as in the settings page tabs. Ex: Features from the Media tab first, then CSS optimizations, then JavaScript and lastly, CDN.

**Comment by piotrbak** [comment]
Hey @camilamadronero The name for the new feature was discussed within the Epic. If we use the full name here, it'll move part of the name to the new line, which looks extremely bad.

For the rest @DahmaniAdame opinion will be needed.

**Comment by jeawhanlee** [comment]
### Reproduce the issue ✅
The issue was easily reproduced

### Identify the root cause ✅
We are adding the Lazyload CSS Background option via a filter which makes the option come last.

### Scope a solution ✅
To fix this, we move all field options to their respective subscribers:
https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/admin/ui/meta-boxes.php#L102-L112
The same way we are already doing here:
https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Media/Lazyload/CSS/Admin/Subscriber.php#L32

Then we will order their display with priorities.
Pretty much exactly the same thing @CrochetFeve0251 stated [here](https://github.com/wp-media/wp-rocket/issues/6138#issuecomment-1706199353)
### Estimate the effort ✅
[S]

**Comment by camilamadronero** [comment]
Thanks, @piotrbak ! I understand!
Then maybe we can only change the `Minify CSS files` and `Load JavaScript deferred`, and re-order them.
Thanks!

**Comment by DahmaniAdame** [comment]
We can take that opportunity and tidy up the naming protocol used there. 

The current longest name on the list is 27 characters. We should be safe for any name equal or below that. 

We are also using `JS` and `JavaScript` at the same time. For consistency, let's stick with `JavaScript` as long as it's below the 27 threshold characters. 

We can proceed with switching: 
- `Defer JS` to `Load JavaScript deferred` 
- `Minify/combine JS` to `Minify/combine JavaScript`

Regarding switching `Minify CSS` to `Minify CSS files`, it will result in switching to `Minify/combine JavaScript files`, which will go beyond the safe threshold on the characters count. Let's revisit that when the combination is deprecated and align.

About the features apparition order, I agree with @camilamadronero. It makes sense to reflect the same order on the options panels. 

Adaptation to the updated order might cause friction for some users in the short term, but it will give a more intuitive user experience in the long run.

@piotrbak Let's go with that and make it the norm when adding new features to the meta box going forward.

**Comment by CrochetFeve0251** [comment]
> ### Reproduce the issue ✅
> 
> The issue was easily reproduced
> ### Identify the root cause ✅
> 
> We are adding the Lazyload CSS Background option via a filter which makes the option come last.
> ### Scope a solution ✅
> 
> We remove this event and callback function responsible for this here:
> 
> https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Media/Lazyload/CSS/Admin/Subscriber.php#L32
> 
> https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Media/Lazyload/CSS/Admin/Subscriber.php#L44-L47
> 
> Then add the option directly after `lazyload_iframes` element in the array
> 
> ```
> $fields = [
>     'lazyload'          => __( 'LazyLoad for images', 'rocket' ),
>     'lazyload_iframes'  => __( 'LazyLoad for iframes/videos', 'rocket' ),
>     'lazyload_css_bg_img' => __( 'LazyLoad CSS backgrounds', 'rocket' ),
>     'minify_css'        => __( 'Minify CSS', 'rocket' ),
>     'remove_unused_css' => __( 'Remove Unused CSS', 'rocket' ),
>     'minify_js'         => __( 'Minify/combine JS', 'rocket' ),
>     'cdn'               => __( 'CDN', 'rocket' ),
>     'async_css'         => __( 'Load CSS asynchronously', 'rocket' ),
>     'defer_all_js'      => __( 'Defer JS', 'rocket' ),
>     'delay_js'          => __( 'Delay JavaScript execution', 'rocket' ),
> ];
> ```
> 
> ### Estimate the effort ✅
> 
> [XS]

@jeawhanlee I would go the opposite way.
As stopping using the filter gonna force us to edit that file again and that would spread the logic and come back to the old technical debt.
The idea behind that filter is to have all the logic concerning a feature in one point which is a way easier for the developer.
Due to that I would refactor the other options to add them to their respective subscribers in the code and play with priorities to have the order that we want.

On short term it is a little bit longer solution but on long term it will make us gain tons of time.

**Comment by engahmeds3ed** [comment]
Totally agree with @CrochetFeve0251 that'd be a clean solution.
OR
You can sort the array inside the filter callback to insert this specific one after the lazyload_iframes one, that'd be a quick solution till we refactor that part.

I'm OK with both solutions.

**Comment by remyperona** [comment]
I agree with Cyrille, I think the small refactor is pretty quick to do, and will make sure we can sort things as we want to

**Comment by piotrbak** [comment]
Okay, sending it back to the grooming then.

**Comment by piotrbak** [comment]
As per @jeawhanlee, the grooming is updated. Sending it back to Grooming Review, thanks Mike! 🦸

**Comment by engahmeds3ed** [comment]
let's make it easier by adding also the fields' corresponding subscribers:

- **lazyload & lazyload_iframes =>** https://github.com/wp-media/wp-rocket/blob/484263349028b50fc1c87891e1912d49102c2e36/inc/Engine/Media/Lazyload/AdminSubscriber.php#L13-L18
- **lazyload_css_bg_img =>** https://github.com/wp-media/wp-rocket/blob/9e21dc499f1922efeac32cf3ad0cefe23bfc5b3b/inc/Engine/Media/Lazyload/CSS/Admin/Subscriber.php#L30-L36
- **minify_css =>** https://github.com/wp-media/wp-rocket/blob/499e311b86e5c10227c1d9c7827cc0bd9bbb6141/inc/Engine/Optimization/Minify/CSS/AdminSubscriber.php#L20-L28 OR https://github.com/wp-media/wp-rocket/blob/0d4e859959f64457cea005d6947f7b6d284024b3/inc/Engine/Optimization/Minify/AdminSubscriber.php#L31-L35
- **remove_unused_css =>** https://github.com/wp-media/wp-rocket/blob/92330e8bd803d05e696f06e21a5085e2cc90e4be/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L62
- **minify_js =>** https://github.com/wp-media/wp-rocket/blob/0d4e859959f64457cea005d6947f7b6d284024b3/inc/Engine/Optimization/Minify/AdminSubscriber.php#L31-L35
- **cdn =>** there is no admin subscriber for cdn, we need to create one.
- **async_css =>** https://github.com/wp-media/wp-rocket/blob/7ec9d996f004707a57c4c8476090d5bd943051f0/inc/Engine/CriticalPath/Admin/Subscriber.php#L47-L63
- **defer_all_js =>** https://github.com/wp-media/wp-rocket/blob/4519cd525d875f990c102e8c4e062c5b5adf9683/inc/Engine/Optimization/DeferJS/AdminSubscriber.php#L30-L35
- **delay_js =>** https://github.com/wp-media/wp-rocket/blob/d95ff93bf3cc563d24d800dc966620cea6b9dfda/inc/Engine/Optimization/DelayJS/Admin/Subscriber.php#L41-L58
