### ISSUE TITLE
FOUC while critical CSS doesn’t finish generating

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#614]
This is WP Rocket **2.11-beta2**.

When I activate _Optimize CSS delivery_, Critical CSS generation seems to keep running indefinitely (at least the admin notice keeps showing). 

Meanwhile, the stylesheet on the front-end already gets loaded asynchronously. This causes a FOUC, as no critical CSS is present on the page yet.

Switching off _Optimize CSS delivery_ does not make the notice go away. I’m not sure if critical CSS generation is _still_ running, even though I turned off the feature, or if it’s just the admin notice being displayed without reason.

This is a Multisite, though WP Rocket is only active on the [main site](https://glueckpress.com/).
The theme loads some inline CSS for fonts early on.

**Comment by glueckpress** [comment]
Tested on another site (single site this time), same behaviour.

**Comment by glueckpress** [comment]
After de-/re-activating the plugin, I triggered critical CSS via toolbar, and it completed within ~5min:

> Critical CSS generation finished for 7 of 7 page types …

A manual cache clearing is required before critical CSS appears on the front-end.

**Comment by Tabrisrp** [comment]
I'm going to add an automatic cache clear when the generation process is complete to prevent the FOUC issue.

I can also stop all process and remove the notices when you deactivate the option, is it something we should have?

**Comment by ernee** [comment]
I'm thinking yes...but I'll let other chime in too ;)

**Comment by glueckpress** [comment]
@Tabrisrp Yes, I think so.

**Comment by glueckpress** [comment]
Confirm the FOUC is fixed in 2.11-beta6. 👍
