### ISSUE TITLE
Only ver query strings are removed

### ISSUE THREAD

**Issue by TheZoker** [wp-media/wp-rocket#615]
When I look at my pingdome score, then there are some query version strings left:
![screenshot!UNITO-UNDERSCORE!2017 12 03!UNITO-UNDERSCORE!23h32m14s!UNITO-UNDERSCORE!003_](https://user-images.githubusercontent.com/1368405/33530625-9a026ad2-d882-11e7-94b5-605260e02db5.png)

It would be nice if `v` and `version` strings are also removed. Maybe you could add a filter, to add these strings manually to the detector. 
Like:

```php
function wp_rocket_query_strings( $query_strings = array() ) {
$query_strings[] = 'v';
$query_strings[] = 'version'
return $query_strings;
}
add_filter( 'rocket_query_strings', 'wp_rocket_query_strings' );
```

**Comment by Tabrisrp** [comment]
Adding a filter to add more query strings is a good idea. Note that we currently only remove query strings on CSS and JS files, so the query string on your webfont will not be removed.

**Comment by TheZoker** [comment]
Can you also remove them from the webfont?

**Comment by Tabrisrp** [comment]
Closing this as we are in the process of removing the option to remove query strings from static resources.
