### ISSUE TITLE
Add license type to what is reported to Mixpanel

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6152]
This will help see how representative is the current sample from opted-in users vs our current users and how reliable data collected from them to help with product decisions.

**Comment by piotrbak** [comment]
**Acceptance Criteria:**
- WP Rocket's license type (Single, Plus, Infinite) should be reported to Mixpanel's Website Environment board

**Comment by jeawhanlee** [comment]
### Scope a solution ✅

We will get the customer data in https://github.com/wp-media/wp-rocket/blob/9cb64a3aa3f7d5d22f855e228d07d11cfbe1082b/inc/admin/admin.php#L276
`$customer_data = get_transient( 'wp_rocket_customer_data' );`

We need to get the license type in string format, we are already doing that here:
https://github.com/wp-media/wp-rocket/blob/9cb64a3aa3f7d5d22f855e228d07d11cfbe1082b/inc/Engine/Admin/Settings/Page.php#L271-L281
We can create a new function so we can share and reuse this block.
```
function get_license_type($customer_data) {
    $type = '';
    if ( false === $customer_data || ! isset( $customer_data->licence_account ) ) {
	    return $data;
    }

    if ( 1 <= $customer_data->licence_account && $customer_data->licence_account < 3
    ) {
	    $type = 'Single';
    } elseif ( -1 === (int) $customer_data->licence_account ) {
	    $type = 'Infinite';
    } else {
	    $type = 'Plus';
    }

    return $type;
}
```
and we can update the `customer_data` method with the new function for getting license type in strings

Finally we will update: https://github.com/wp-media/wp-rocket/blob/9cb64a3aa3f7d5d22f855e228d07d11cfbe1082b/inc/admin/admin.php#L276
```
$customer_data = get_transient( 'wp_rocket_customer_data' );
if ( false !== $customer_data ) {
  $data['license_type] = get_license_type($customer_data);
}
```

### Estimate the effort ✅
[XS]

**Comment by CrochetFeve0251** [comment]
That  seems good to me
