### ISSUE TITLE
CSS Container Queries prevent RUCSS from generating correctly.

### ISSUE THREAD

**Issue by billerickson** [wp-media/wp-rocket#6153]
CSS container queries are [supported in all major browsers now](https://caniuse.com/css-container-query-units), but if a theme or plugin includes them in their CSS and WP Rocket has "Remove Unused CSS" enabled, no CSS loads.

[This site](https://lilluna.com/) is using a container query ([CSS](https://lilluna.com/wp-content/themes/lilluna-2023/blocks/cookbook-banner/style.css?ver=1694201198)) for the Cookbook CTA after the site header. 

With RUCSS disabled, the page loads correctly:

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/E0um2koB/5e2c8527-ad1f-452c-94ab-585e3dfc2657.jpg?source=viewer&v=38781b86f6b42044ab7e675f28864097)

With RUCSS enabled, all CSS is missing:

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/nOuQzj87/692483e3-5924-488e-9bc2-0fb41612f99c.jpg?source=viewer&v=ab4dfe4a7a6fa17027cb33bc3c9b8441)

To reproduce the error, [add this CSS](https://lilluna.com/wp-content/themes/lilluna-2023/blocks/cookbook-banner/style.css) to a theme's stylesheet, or enqueue it as a separate stylesheet. Then enable "Remove Unused CSS".

**Comment by richardbuff** [comment]
Would love to see this resolved! I've had to remove container queries on multiple sites when the client uses WP Rocket.

**Comment by mostafa-hisham** [comment]
@piotrbak 
I don't see a Container query in the provided CSS

I tested it using this template and `couldn't reproduce` it
I got the template from the mozilla [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries)

```HTML
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>COntainer demo</title>

<style>
.post {
    container-type: inline-size;
}
/* Default heading styles for the card title */
.card h2 {
    font-size: 1em;
}

/* If the container is larger than 700px */
@container (min-width: 700px) {
    .card h2 {
        background: red;
        font-size: 2em;
    }
}
</style>
  </head>
  <body>
    <h1 class="bg-white">Hello, world!</h1>
    <div class="post">
      <div class="card">
        <h2>Card title</h2>
        <p>Card content</p>
      </div>
    </div>
  </body>
</html>
```

**Comment by piotrbak** [comment]
We'll reopen when we're able to reproduce the issue
