### ISSUE TITLE
cach jquery with ver

### ISSUE THREAD

**Issue by FaridBeiranvand** [wp-media/wp-rocket#6155]
hello i have a problem with jQuery for caching because it has a "ver" at the end end of the URL:
/wp-includes/js/jquery/jquery.min.js?ver=3.7.0
because WP rocket doesn't cache files with ver. please let jQuery files cache with ver. thank you

**Comment by piotrbak** [comment]
Hello! That looks like a support request. Please reach our Support Team to find solution to your problem:
https://wp-rocket.me/support/
