### ISSUE TITLE
Improve Pressidium hosting compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6157]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Our current compatibility covers only the following cases:
1. Clearing our whole cache when their cache is purged
2. Clearing their whole cache when our is purged
3. Hide Varnish Config fields

**Expected behavior**
It's possible to clear only the specific URL(s) too, we should handle that.

**Screenshots**
[Documentation](https://github.com/wp-media/wp-rocket/files/12576277/Integrating.with.Pressidium.Manually.invalidating.cache.pdf)

**Acceptance Criteria (for WP Media team use only)**
1. Their cache should be cleared when using `Purge this URL` option from the top menu
2. Their cache should be cleared when updating the post (post itself + related URLs)
3. No regression compared to the current compatibility described in the **Describe the bug** section
4. Specific URLs should be cleared when RUCSS data is injected

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
- First and foremost, we need to move the pressidium compatibility to the new architecture.
- **To purge individual page with purge this url**:
    We can create a private method to get paths:
    ```
    private function get_paths( $urls ) {
        $urls = (array) $urls;
        $paths = [];
        
        foreach( $urls as $url ) {
            $parsed_url = get_rocket_parse_url( $url );
            $paths[] = $parsed_url['path'];
            
            return $paths;
        }
    }
    ```
    We will hook a call back to `after_rocket_clean_file`
    ```
    public function purge_url( $url ) {
        $paths = $this->get_paths( $url );
    
        NinukisCaching::get_instance()->purge_cache($paths);
    }
    ```

- **Their cache should be cleared when updating the post (post itself + related URLs)**:
    For this, we will hook another callback to `after_rocket_clean_post` action
```
    public function clean_post( $post, $purge_urls ) {
        $cache = NinukisCaching::get_instance();
        $cache->purge_page_cache($post->ID);

        // Purge related urls
        $paths = $this->get_paths( $purge_urls );
        $cache->purge_cache( $paths );
    }
```
### Estimate the effort ✅
[S]

**Comment by CrochetFeve0251** [comment]
That seems good to me
