### ISSUE TITLE
Improve WP Rocket LazyLoad compatibility with Jetpack

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6159]
**Is your feature request related to a problem? Please describe.**
Usually customers try to exclude Jetpack lazyloaded images using WP Rocket's LazyLoad exclusion box. This naturally won't work, and customers will open a ticket with us, even if we [have a doc](https://docs.wp-rocket.me/article/1733-excluded-images-are-still-being-lazyloaded).

**Describe the solution you'd like**
Create compatibility with Jetpack inside WP Rocket's UI to avoid the problem, and to avoid the ticket. 
Some ideas: 
* Gray out WP Rocket's LazyLoad when Jetpack is active, showing a notice telling customers that lazyloading is being handled by Jetpack (similar to what we do with Autoptimize).
* Allow WP Rocket even if Jetpack is active (if we're complementary to each other, for example) and just show the notice to warn customers.
* Detect both features are active and show an admin notice, recommending customer to disable Jetpack's lazyloading.
* Show the admin notice but as a warning only.

**Additional context**
Rel ticket: https://secure.helpscout.net/conversation/2358040876/442079/

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
