### ISSUE TITLE
Don't cache admins

### ISSUE THREAD

**Issue by Cyberdemon87** [wp-media/wp-rocket#616]
Hello.
This is not really an issue, but I was wondering about this little addon:

https://github.com/wp-media/wp-rocket-helpers/tree/master/wp-rocket-no-cache-for-admins

It's a great option and I'm surprised that it's not a part of WP-Rocket and only available as a separate helper here on GitHub.

Is there any chance you can implement it inside WP-Rocket?

**Comment by Tabrisrp** [comment]
We try to limit the number of options we have in the plugin to prevent any information overload, that's why this kind of specific things are offered as an helper instead of being in WP Rocket core.

**Comment by Cyberdemon87** [comment]
Thanks for the reply.

This is a pretty handy feature, so I think it will only give more to WP-Rocket :)

Maybe you could just add it in the Advanced section.
