### ISSUE TITLE
Improve UX if LazyLoad for CSS background images and Elementor's Lazy Load Background Images are active at the same time

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6163]
**Is your feature request related to a problem? Please describe.**
If customers are using Elementor's **Lazy Load Background Images option** and enable WP Rocket's **LazyLoad for CSS background images** feature, the background images will not be displayed.

**Describe the solution you'd like**
Detect when Elementor's **Lazy Load Background Images** option and WP Rocket's **LazyLoad for CSS background images** option are active at the same time, and show an **admin notice** suggesting to disable Elementor's one.
Using WP Rocket's feature should be the recommended because our LazyLoad can be applied in "non-Elementor" background images too.
This should prevent layout issues and tickets.

**Describe alternatives you've considered**
Detect when Elementor's **Lazy Load Background Images option** is active, and show a warning below our **LazyLoad for CSS background images** feature.

**Additional context**
Rel ticket: https://secure.helpscout.net/conversation/2358662930/442226/

Thanks!

**Comment by piotrbak** [comment]
@camilamadronero It's not reproducible. Elementor LazyLoad Background Images doesn't see to be conflicting with ours 🤔

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
