### ISSUE TITLE
Update Default Exclusion for jQuery to work for both Delay JavaScript Execution and Load JavaScript Deferred

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6164]
Opening this as a continuation of these previous issues:
https://github.com/wp-media/wp-rocket/issues/4371#issuecomment-1513415742
https://github.com/wp-media/wp-rocket/issues/5970

Despite the recent updates, the new regex to exclude jQuery and jQuery Migrate from DJE does not work for LJD, and we noticed some users trying to use it in the LJD exclusions box.

This is the current default exclusion that works for DJE but not LJD:
`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?( |'|"|>)`

This is the exclusion that works for LJD:
`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?$`

To reduce confusion, a proposed solution is to change the default exclusion shown in the settings page UI so it will work for both DJE and LJD as follows:
`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?( |'|"|>|$)`

When matching is being done for DJE, the entire script contents are included in the test, but for LJD, only the `src` attribute URL is included, which explains why the current DJE default exclusion doesn't work for LJD.

The new regex proposed above should work to exclude jQuery and jQuery Migrate scripts from both DJE and LJD, while also not having any false positives for scripts like `jquery.jslint.js`.

Here is a regex101 test showing the results:
https://regex101.com/r/2ZPNuP/1

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We'll not fix it in upcoming quarter
