### ISSUE TITLE
The notice when activate WPR first time isnot displaying on subsite of multisite

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6168]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.0.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When activating WPR on a subsite of multisite, the notice is not displayed 
![Screenshot from 2023-09-15 13-42-43](https://github.com/wp-media/wp-rocket/assets/76941962/934998a1-1a8d-4910-a534-8fa6ffd4f2a9)

**To Reproduce**
1. Go to multisite i.e https://newmulti.rocketlabsqa.ovh/wp-admin/
2. install WPR
3. Activate on subsite => 1st time notice not displayed

**Expected behavior**
Notice displayed on both main and subsite

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
