### ISSUE TITLE
Add a warning in the cache preload option

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#6169]
**Is your feature request related to a problem? Please describe.**
Many customers when activating the cache preload get a CPU overload, they usually disable WP Rocket completely and open a ticket, which in turn is answered with documentation with the necessary steps to check and fix it. Resulting in a waste of time that can be avoided. 

**Describe the solution you'd like**
Many customers often get a CPU overload when enabling cache preloading, having a message warning about the possibility of this happening and of perhaps a link to documentation similar to the one in Minify JavaScript could save time and perhaps a ticket. https://i.imgur.com/IbwxO1d.png

**Describe alternatives you've considered**

**Additional context**
Suggested by a customer here: 
https://secure.helpscout.net/conversation/2360774632/442623?folderId=2952229

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
