### ISSUE TITLE
[Beta 2]: Sitemap Preload Notice Issue

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#617]
1. I didn't do anything to trigger the sitemap preload. I activated the plugin on a customer's site and immediately got this notice: 
![screenshot-monarchhousing org-2017-12-04-19-02-18-531](https://user-images.githubusercontent.com/1043076/33584614-d413c2f4-d925-11e7-9d49-1f94634ef124.jpeg)

2. I check the cache folder and files are populating but the notice doesn't update even after reloading the page. 

3. The wording is confusing. 
Current: "x pages not yet cached have been preloaded."
Proposed: "x pages have been preloaded"

**Comment by Tabrisrp** [comment]
Number 1 was on a new install or a re-activation?

Number 3 I tried to pass the information that they might see a difference between the number here and the number of URLs in their sitemaps, because I added a function to check if the cache file already exists, so the counter won't increment in that case.

Shall we still communicate that?

**Comment by ernee** [comment]
Just adding to this. I don't have sitemap preload enabled and I'm getting the notice in our settings page. See attached.
![screen shot 2017-12-05 at 7 53 53 am](https://user-images.githubusercontent.com/8108643/33610807-10d939e6-d992-11e7-930b-c3960b701981.png)

**Comment by webtrainingwheels** [comment]
Number 1 was a re-activation. 

Number 3 - ok I understand now :) 
Trying to think of a good way to communicate it without having a super-wordy notice. 
Maybe: "x uncached pages have now been preloaded"  ?

Ping @glueckpress @ernee for inspiration?

**Comment by Tabrisrp** [comment]
@ernee Was it never activated before or was it activated, a preload was running, and then you deactivated it?

**Comment by ernee** [comment]
From what I recall, it was activated when I tested on the alpha originally. I upgraded to beta and then deactivated all the options.

**Comment by glueckpress** [comment]
> Trying to think of a good way to communicate it without having a super-wordy notice.
> Maybe: "x uncached pages have now been preloaded" ?

+1, but prefix with `Sitemap preload:`? Like:

```
Sitemap preload: %d uncached pages have now been preloaded.
```

**Comment by glueckpress** [comment]
```
Sitemap preload complete: %d pages not yet cached have been preloaded.
```
should be updated accordingly. Like so?
```
Sitemap preload: %d pages have been cached.
```

**Comment by ernee** [comment]
@Tabrisrp  experienced similar initial issue that @webtrainingwheels reported: When I install and activate the new version, Sitemap preload notice displays with without the option checked:

![screen shot 2017-12-07 at 2 23 43 pm](https://user-images.githubusercontent.com/8108643/33741829-cb672de4-db5a-11e7-80d2-a598faa605a9.png)
