### ISSUE TITLE
Please make "Remove Unused CSS" an on-the-fly functionality

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#6171]
**Is your feature request related to a problem? Please describe.**
RUSS currently requires to be processed ahead and cached, which is not a good way of working.

**Describe the solution you'd like**
RUCSS should become an "on-the-fly" feature (just like Minify or Combine or Delay...), that just runs whenever a page is loaded. Therefore, we avoid relying on a cache and we avoid using CPU ahead (or even regularly due to cron)

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by mehedihasanziku** [comment]
That's a good feature, but don't know why rocket loves to keep it online, probably it’s because quick fixes related to this.

anyways, you can use freebie, that's do same as well https://wordpress.org/plugins/debloat/

**Comment by piotrbak** [comment]
This is not something that can be implemented.
