### ISSUE TITLE
Merge all the cache clearing / regenerating action buttons into the main "Clear and preload all cache files"

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#6172]
**Is your feature request related to a problem? Please describe.**
In the Quick Actions area, we have all these types of clearing cache buttons :
- Clear All Cache Files
- Clear Critical Images Cache
- Clear Used CSS Cache
- Regenerate Critical Path Cache

This is really getting messy ! Please keep only 1 button "Clear All Cache Files" that clears and regenerates everything.

**Describe the solution you'd like**
Simplify the user interface by merging all the quick actions buttons.

**Describe alternatives you've considered**
/

**Additional context**
![image](https://github.com/wp-media/wp-rocket/assets/87424739/30c2a4cc-e5c6-4fcd-a1de-78f961d5cbbe)

**Comment by JerissCloudCenter** [comment]
I've updated this ticket, as it's getting even worse. Now we have 1 more button "Clear Critical Images Cache". Please make things easy, and just keep only just 1 button to clear all cache, that's it.

**Comment by piotrbak** [comment]
There will be rework related to this part of the plugin. We'll create the needed issues
