### ISSUE TITLE
Make the "All languages" button the first option inside the "Clear cache" menu 

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6174]
**Is your feature request related to a problem? Please describe.**
Customers using multilingual plugins need to hover on the "Clear cache" option, and scroll down to the bottom to reach and click on the "All languages" button, when apparently, that's the most common to use.

**Describe the solution you'd like**
The "All language" button should be easier to access by being the top link under the "Clear cache" option.

**Additional context**
Ticket request: https://secure.helpscout.net/conversation/2357195073/441899?folderId=2675957

**Comment by Miraeld** [comment]
## Scope a solution
To implement this feature, we must change the order between the `if` and the `foreach` in here: 
https://github.com/wp-media/wp-rocket/blob/610a225799002c6bc3747db2f54cb7fbb0075ae9/inc/common/admin-bar.php#L125-L146
Once done, the `All Languages` option should be on top of the each individual language.


## Effort estimation:
XS

## Can be peer-coded: 
No

## Is a refactor needed in that part of the codebase?
No
