### ISSUE TITLE
Fatal error related to Logger

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6175]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling debug mode, fatal error is triggered:
```
[18-Sep-2023 08:17:04 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_Rocket\Dependencies\Monolog\Logger' not found in /home/zambvtks/public_html/wp-content/plugins/wp-rocket/inc/Logger/Logger.php:187
```
When tracing [this part of advanced cache](https://github.com/wp-media/wp-rocket/blob/68f736bec61b8b544fece6f59c81393c832fd985/views/cache/advanced-cache.php#L63-L67) the following values are found:
```
[18-Sep-2023 09:05:26 UTC] $class = WP_Rocket\Dependencies\Monolog\Logger
[18-Sep-2023 09:05:26 UTC] $file = /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/Monolog/WP_Rocket/Dependencies/Monolog/Logger.php
```
The path is not correct.

**To Reproduce**
1. Enable debug mode
2. Check the error log

**Expected behavior**
No fatal errors happening

**Additional context**
https://wp-media.slack.com/archives/CUT7FLHF1/p1695028743176139

**Acceptance Criteria (for WP Media team use only)**
1. Debug mode should work correctly only when enabled
2. No regressions related to https://github.com/wp-media/wp-rocket/issues/5366 we should still be guarded against fatal errors that were fixed there

**Comment by briceTouck** [comment]
Hi,

same issue,

<img width="1716" alt="Capture d’écran 2023-09-22 à 10 37 57" src="https://github.com/wp-media/wp-rocket/assets/25413031/61e042f7-c6f9-4842-98ee-06dd57a22976">

<img width="1370" alt="Capture d’écran 2023-09-22 à 10 38 43" src="https://github.com/wp-media/wp-rocket/assets/25413031/a92e63d8-1136-4f44-b398-bb45f071231d">

Thank you

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
Just add the constant `define('WP_ROCKET_DEBUG', true);` and you should see it.

## Identify the root cause
The root cause is due to the prefix added by Mozart which makes the autoload search in the wrong file.

## Scope a solution
To solve that issue we will have to change the [`advanced-cache.php`](https://github.com/wp-media/wp-rocket/blob/develop/views/cache/advanced-cache.php) file:
```php
} elseif ( strpos( $class, 'WP_Rocket\\Dependencies\\Monolog\\' ) === 0 ) {
                        $class = str_replace('WP_Rocket\\Dependencies\\Monolog\\', '', $class);

			$file = $rocket_path . 'inc/Dependencies/Monolog/' . str_replace( '\\', '/', $class ) . '.php';
			if ( ! file_exists( $file ) ) {
				$file = $rocket_path . 'vendor/monolog/monolog/src/' . str_replace( '\\', '/', $class ) . '.php';
			}
		} elseif ( strpos( $class, 'WP_Rocket\\Dependencies\\Psr\\Log\\' ) === 0 ) {
                      $file = $rocket_path . 'inc/Dependencies/Psr/Log/' . str_replace( '\\', '/', $class ) . '.php';

			$file = $rocket_path . 'inc/Dependencies/Psr/Log/' . str_replace( '\\', '/', $class ) . '.php';
			if ( ! file_exists( $file ) ) {
				$file = $rocket_path . 'vendor/psr/log/' . str_replace( '\\', '/', $class ) . '.php';
			}
		} else {

```

Then we will have to update `advanced-cache.php` on update from wpr inside [`PurgeActionsSubscriber`](https://github.com/wp-media/wp-rocket/blob/7273ea63aa9ababb3448ef532bb11d6d19a7d529/inc/Engine/Cache/PurgeActionsSubscriber.php):
```php
public function on_update( $new_version, $old_version ) {
		if ( version_compare( $old_version, '3.12', '>=' ) ) {
			return;
		}
		rocket_generate_advanced_cache_file();
	}
```
## Estimate the effort
Effort `S`

**Comment by engahmeds3ed** [comment]
@CrochetFeve0251 plz make sure that we regenerate advanced-cache.php file upon update.

Also do we need to do the same added str_replace to the psr/log package?

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed true I gonna add the logic to regenarate the `advanced-cache.php`.

Concerning the `psr/log` yes we do.
