### ISSUE TITLE
[2.11-beta1] - and Mobile_Detect

### ISSUE THREAD

**Issue by apsolut** [wp-media/wp-rocket#618]
We have included Mobile_Detect in a starter theme (we had that before...) , but after latest update of wp-rocket, when we click **Cache on mobile:**  the Fatal error:
`Cannot redeclare class Mobile_Detect in /usr/www/users/aaaa/wp-content/themes/themename/inc/Mobile_Detect.php on line 28`

before it was **Rocket_Mobile_Detect** right now it looks like you are calling it with original name **Mobile_Detect** from: inc/vendors/Mobile_Detect.php

**Comment by Tabrisrp** [comment]
We'll revert back to Rocket_Mobile_Detect, but you should also include on your side a check to preven trying to load the class if the class already exists to prevent this kind of issue with other plugins.
