### ISSUE TITLE
Allow disabling generating compressed files

### ISSUE THREAD

**Issue by calind** [wp-media/wp-rocket#6182]
**Is your feature request related to a problem? Please describe.**
I'm using WP Rocket in a system where gzip/brotli compression is already handled and generating a `.gz` file is unnecessary.

**Describe the solution you'd like**
Adding an eg. `rocket_generate_compressed_file` filter which controls generating compressed versions would be very useful.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Comment by zevilz** [comment]
@piotrbak, we have a lot of cache files (approximately 2TB). Of these, compressed cache files are approximately 10% (200GB). In fact, this is garbage when using brotli compression. Also, intensive cache creation uses more server resources. Disabling compressed cache creation would save disk space and server resources. It would be enough to simply add a filter.

**Comment by doblejou** [comment]
I think the same. Creating the .gz version of each cached file should be an optional thing.

**Comment by webtrainingwheels** [comment]
Another request: https://secure.helpscout.net/conversation/2985077738/570776?viewId=377611

**Comment by shane-clickingmad** [comment]
What would it take for this to be considered? This would save a huge amount of resources for us also.

**Comment by mifrero** [comment]
Another request: https://onecomhelp.zendesk.com/agent/tickets/17093035

**Comment by rosamillan** [comment]
related https://onecomhelp.zendesk.com/agent/tickets/18432569
