### ISSUE TITLE
Most rucss end up failing

### ISSUE THREAD

**Issue by nilo-byte** [wp-media/wp-rocket#6185]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :white_check_mark:
- Used the search feature to ensure that the bug hasn’t been reported before :white_check_mark:

**Describe the bug**
I can't generate used CSS for all my posts. After clicking the Purge CSS button it starts generating. After about 300 `completed` jobs I only get status `failed`. I then have a few thousand `pending` jobs that all end up in status `failed` after a some time waiting.

From the wpr_rucss_used_css table I can see that most status codes are `500` with error 'Cannot read properties of null (reading 'newPage')'. Also I find a few status codes with `400` 'bad json'. 

I use Cloudflare Cache and checked all points in the troubleshoot article. I also set up a page rule for URL parameters '?nowprocket=1&no_optimize=1' to bypass the CF-Cache.

**To Reproduce**
1. Click 'Purge used CSS' in WP-Rocket Plugin page
2. Check status messages in phpmyadmin

**Expected behavior**
Status completed for most of the used CSS jobs.

**Comment by CBrach** [comment]
We have the same issue on our site (also behind Cloudflare):

CSS for 3690 pages was generated correctly, 998 failed with `Cannot read properties of null (reading 'newPage')`. We also got some `400 bad json`, but those are all paginated pages that we don't really care about.

**Comment by DahmaniAdame** [comment]
It's hard to tell without having a closer look. 
Cloudflare (or a firewall) is just one possible reason for it to fail. 
@nilo-byte @CBrach would you mind opening support tickets for further investigation?

**Comment by piotrbak** [comment]
Each specific case should be reproted to our Support Team. We'll be able to investigate your site and find the root cause then.
