### ISSUE TITLE
Update Delay JavaScript script to the latest version.

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6186]
**Is your feature request related to a problem? Please describe.**
Delay JS script should be updated to the latest version.

**Changelog**
- Fix a problem when click event might not working correctly with Elementor Pro dropdown menu [#46](https://github.com/wp-media/delay-javascript-loading/pull/46)
- Make sure not to interpret nomodule elements [#76](https://github.com/wp-media/delay-javascript-loading/pull/76)
- Make sure that scripts are preconnected correctly [#82](https://github.com/wp-media/delay-javascript-loading/pull/82) 
- Improve handling triggers [#93](https://github.com/wp-media/delay-javascript-loading/pull/93) 

**Additional context**
The script should be merged when all above PRs are merged into the develop branch.

**Comment by jeawhanlee** [comment]
We will update this Delay js script [here](https://github.com/wp-media/wp-rocket/blob/develop/assets/js/lazyload-scripts.min.js) with [this](https://github.com/wp-media/delay-javascript-loading/blob/develop/delay-js.js)

Update related test:
https://github.com/wp-media/wp-rocket/blob/cea21cde7f09292bf6295047b319c7f9ea09ba17/tests/Fixtures/inc/Engine/Optimization/DelayJS/Subscriber/addDelayJsScript.php#L10

**Comment by CrochetFeve0251** [comment]
Seems good too.

**Comment by Mai-Saad** [comment]
@piotrbak @jeawhanlee shouldn't we use v1.3 instead? https://github.com/wp-media/delay-javascript-loading/blob/update-1.3/delay-js.js

**Comment by jeawhanlee** [comment]
@Mai-Saad  The [one](https://github.com/wp-media/delay-javascript-loading/blob/develop/delay-js.js) on the develop branch seem to have all the PRs mentioned in the [changelog](https://github.com/wp-media/wp-rocket/issues/6186#issue-1910323349) merged to it last week [here](https://github.com/wp-media/delay-javascript-loading/pull/96) as opposed to the update-1.3 branch

**Comment by Mai-Saad** [comment]
With the current PR: 
- Fix a problem when the click event might not working correctly with Elementor Pro dropdown menu https://github.com/wp-media/delay-javascript-loading/pull/46 => partially fixed, better than before, as mentioned here https://github.com/wp-media/delay-javascript-loading/issues/29#issuecomment-1733994228
- Make sure not to interpret nomodule elements https://github.com/wp-media/delay-javascript-loading/pull/76 =>fixed
- Make sure that scripts are preconnected correctly https://github.com/wp-media/delay-javascript-loading/pull/82 => still under discussion https://github.com/wp-media/delay-javascript-loading/issues/79#issuecomment-1539778184 and can see the warning at page speed by default, is there any filter to use for exclusion?? do we have any examples for the other 2 fixes added to same PR?
- Improve handling triggers https://github.com/wp-media/delay-javascript-loading/pull/93 => still not fixed, do we need to fix that or document it?  @piotrbak https://github.com/wp-media/delay-javascript-loading/pull/93#issuecomment-1744873303

**Comment by gmetais** [comment]
Hello @Mai-Saad,

Regarding https://github.com/wp-media/delay-javascript-loading/pull/82, my point of view stays the same: we should not add filters nor exclusions, we need to **document** and **inform** webmasters that those warning are not harmful, they help speeding up pages and speed is the priority over the warnings.

Regarding https://github.com/wp-media/delay-javascript-loading/pull/93 => yes it is fixed in PSI. Trying to reproduce the issue by faking the user agent is **a different issue** that is **NOT** harmful. It only occurs in Firefox when the page is refreshed with the devtools open and without interacting with the page, which is extremely rare in real world.

**Comment by gmetais** [comment]
Hello @Mai-Saad,
Can you please scan my answers (above and [here](https://github.com/wp-media/delay-javascript-loading/pull/93#issuecomment-1762887990)) when you have some time?
So that v1.2.4 can move to production next week.

**Comment by piotrbak** [comment]
@gmetais @Mai-Saad Looks like we're good there in terms of preconnect and also the Firefox case.

**Comment by piotrbak** [comment]
@gmetais @Mai-Saad The points mentioned are fine. Moving it back to QA
