### ISSUE TITLE
Using stream wrappers for storing cache items break generated urls

### ISSUE THREAD

**Issue by calind** [wp-media/wp-rocket#6187]
**Describe the bug**
When setting the `WP_ROCKET_CACHE_ROOT_PATH` to a stream wrapper location, eg. `media://wp-content/wp-rocket-cache/` and `WP_ROCKET_CACHE_ROOT_URL` to `https://www.homeofficebits.com/wp-content/wp-rocket-cache/` the generated URLs for cached assets are broken and look like: 

https://www.homeofficebits.com/wp-contentmedia:/wp-content/wp-rocket-cache/background-css/www.homeofficebits.com/wp-content/wp-rocket-cache/min/1/wp-content/plugins/twentig/dist/css/twentytwentyone/theme-style.css?ver=1695283819&wpr_t=1695662167.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future when fixing things related to this feature.
