### ISSUE TITLE
Correct text for LazyLoad Youtube option

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#619]
Current: Replace Youtube iframe by preview image
Fixed: Replace Youtube iframe with preview image

**Comment by ernee** [comment]
@Tabrisrp some small string update suggestions on this option (notice capitalization of "T" in YouTube and addition of "time"):

Current: Replace Youtube iframe with preview image
Fixed: Replace YouTube iframe with preview image

Current: This can significantly improve your loading if you have a lot of Youtube videos on a page.
Fixed: This can significantly improve your loading time if you have a lot of YouTube videos on a page.
