### ISSUE TITLE
de.docs.wp-rocket.me is not working anymore

### ISSUE THREAD

**Issue by rosamillan** [wp-media/wp-rocket#6193]
**Description**
The warning for missing writing permissions is redirecting to a broken documentation link and ERR_CONECTION_TIMED_OUR appears. 
Broken Link: https://de.docs.wp-rocket.me/article/1042-fehlende-schreibrechte-fuer-system-dateien-beheben-htaccess-wp-configphp?utm_source=wp_plugin&utm_medium=wp_rocket

Screenshot: https://prnt.sc/GgjcQjAv0Mnl

**To Reproduce**

1. Go to a website without writing permissions and activate WP Rocket.
2. The warning for missing writing permissions will appear.
3. click on the documentation link. Screenshot: https://prnt.sc/O0r5zWzgtKKn
4. ERR_CONECTION_TIMED_OUR appears. Screenshot: https://prnt.sc/GgjcQjAv0Mnl

Note: the error appears for Deutsch and Spanish languages.

**Expected behavior**
The help link redirects to an active address. For example: https://docs.wp-rocket.me/article/626-how-to-make-system-files-htaccess-wp-config-writeable?utm_source=wp_plugin&utm_medium=wp_rocket

Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1695763701441119

**Comment by nicomollet** [comment]
Docs are only available in FR + EN.
https://docs.wp-rocket.me/
https://fr.docs.wp-rocket.me/

Every other language should **not** have a link to https://LANG.docs.wp-rocket.me/

**Comment by piotrbak** [comment]
Corrected this on Transifex. It'll be included when merging the translations.
