### ISSUE TITLE
"View details" isn't displayed on the Plugins page after installation

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6196]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.15.1`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

After installing WP Rocket, the "View details" link isn't displayed in WP Rocket's row on the Plugins page (`/wp-admin/plugins.php`). 
![Screenshot from 2023-09-28 10-23-08](https://github.com/wp-media/wp-rocket/assets/193660/14924b8e-7374-4229-ba71-5b04456edff2)
This is because the respective piece of information isn't in the `update_plugins` transient and the following condition isn't met:
https://github.com/WordPress/WordPress/blob/11f30a677a1095778bdcec61ad838d097d5e6b14/wp-admin/includes/class-wp-plugins-list-table.php#L1074-L1087

We are adding the plugin information when  `plugins_api_result` fires:
https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Plugin/InformationSubscriber.php#L59

It seems that the plugin's info isn't added to the `update_plugins` transient after the installation of our plugin. It will happen the next time  `plugins_api_result` fires. Until then, only the "Visit plugin site" is displayed. This links to https://wp-rocket.me.

**To Reproduce**

1. Install WP Rocket from scratch.
2. Visit the Plugins page.
3. "View details" will be missing.

**Expected behavior**

Display the "View details" link after installation.

**Additional context**

Installing any other plugin will make the "View details" link appear.
This isn't an issue per se but it would be great if we could make it work the way it does for WordPress repo plugins.

**Acceptance Criteria (for WP Media team use only)**

Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
