### ISSUE TITLE
Add vgo_ee (Active Campaign) parameters to the ignored query string parameters

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#6201]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
The `vgo_ee` parameter is used for Site Tracking, one of the features of Active Campaign.
Basically, the value of the parameters is the encrypted email address of the user who clicked on the link in the newsletter. That value is read by a JS script you add to your website, and that lets ActiveCampaign know what your subscribers do on your site and, beyond that and most importantly, it allows you to automatically create personalized experiences for each of your contacts as they interact with your website.

**Additional context**
https://help.activecampaign.com/hc/en-us/articles/221542267-An-overview-of-Site-Tracking#an-overview-of-site-tracking-0-0

slack thread: https://wp-media.slack.com/archives/C8L4EE8N9/p1695806840247069

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by joejoe04** [comment]
I've added this exclusion, so closing the issue.
