### ISSUE TITLE
Refine RUCSS error reporting with meaningful messages and timestamps

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6204]
**Context**
We use "bad json" and code "400" as defaults for returns from the SaaS RUCSS feature. This prevents us and the support team to efficiently identify what went wrong, or which step failed. Also, we lack timing information to understand the lifecycle of the jobs from the plugin side.

**Expected behavior**
- Add a `submitted_at` field in the RUCSS table. This field is set to null by default, and filled with the current timestamp when a job is sent (or re-sent) to the SaaS (`used_css_query->reset_job`, `used_css_query->create_new_job`).
- Store in the row of the job, in the "message" column: the response & message from Saas & timestamp when getting job status that is not a 200. And concatenate those. For instance, if the first try return a 400 bad json at 2:15PM, store: `YY-MM-DD-14:12:30 400: Bad Json` Then, 10 minutes later, another 400 bad json, store: `YY-MM-DD-14:12:30 400: Bad Json;YY-MM-DD-14:22:45 400: Bad Json`. If the final try is also a failure, continue to concatenate.
Be careful with max size of the string: truncate if needed?
- Replace "Bad Json" in get_queue_job_status by: "No message. Defaulted in get_queue_job_status"
- Replace "Bad Json" in add_to_queue by: "No message. Defaulted in add_to_queue"

**Comment by mostafa-hisham** [comment]
## Scope a solution
- ### Create `submitted_at` field in the RUCSS table

1. update
inc/Engine/Optimization/RUCSS/Database/Row/UsedCSS.php
inc/Engine/Optimization/RUCSS/Database/Schemas/UsedCSS.php
inc/Engine/Optimization/RUCSS/Database/Tables/UsedCSS.php
to add a nullable timestamp column `submitted_at`

**FYI**: similar to what was done in this [PR](https://github.com/wp-media/wp-rocket/pull/5480/commits/dbe4cf576d8e2c6e1b00329b7d0ae13705e2f936)

2. set the new column value to the current timestamp in
https://github.com/wp-media/wp-rocket/blob/8f94841f4a2767cf6860232dff2a0b086185efff/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php#L164
and
https://github.com/wp-media/wp-rocket/blob/8f94841f4a2767cf6860232dff2a0b086185efff/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php#L209


- ### store more info in the `message` column

the `message` column is a `longtext` so it will hold a lot of data.
in `make_status_failed` we need to concatenate to the previous value and formate it like the suggestion above
`Y-m-d H:i:s {status_code}: {error_message};`
  
https://github.com/wp-media/wp-rocket/blob/8f94841f4a2767cf6860232dff2a0b086185efff/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php#L236


- ### Replace "Bad Json"

1. Replace "Bad Json" in get_queue_job_status by: "No message. Defaulted in get_queue_job_status"
https://github.com/wp-media/wp-rocket/blob/56895a819512af1244920ffd5e6415efe796768c/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#L76

2. Replace "Bad Json" in add_to_queue by: "No message. Defaulted in add_to_queue"
https://github.com/wp-media/wp-rocket/blob/56895a819512af1244920ffd5e6415efe796768c/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#L25
##  Estimate effort

Effort `S`

**Comment by MathieuLamiot** [comment]
Looks good, thanks.
Just an additional point for the concatenation in message: 
`make_status_failed` is only called `if retries >=3` in `check_job_status`. So in order to store messages for intermediary retires, we would need to add an else logic:

```
if ( $row_details->retries >= 3 ) {
				Logger::debug( 'RUCSS: Job failed 3 times for url: ' . $row_details->url );
				/**
				 * Unlock preload URL.
				 *
				 * @param string $url URL to unlock
				 */
				do_action( 'rocket_preload_unlock_url', $row_details->url );

				$this->used_css_query->make_status_failed( $id, strval( $job_details['code'] ), $job_details['message'] );

				return;
			}
else{
    $this->used_css_query->update_message($id, strval( $job_details['code'] ), $job_details['message'])
}
```
With `update_message` that is a new method that concatenates new data to the existing message.

**Comment by mostafa-hisham** [comment]
thanks, @MathieuLamiot  I totally missed this one.
in that case, I suggest updating the message with the retries increment to cover the 408 cases too
https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L692

**Comment by MathieuLamiot** [comment]
Sounds good, either in the increment_retries method, or in a dedicated method next to it. 👍
