### ISSUE TITLE
Updates takes long time after Uninstall

### ISSUE THREAD

**Issue by igecorner** [wp-media/wp-rocket#6209]
Hi

I have been using the WP Rocket plugin for a long time. Due to various reasons, I decided to uninstall the plugin, and I did so.

However, after uninstalling WP Rocket, I am facing some problems on my website:

1. Whenever I publish a new post,  it takes some time to reflect on the home page
2. Wordpress Admin Editor menu is not appearing, but if I add /?nowprocket to the URL,  then editor menu is appears.

I am sure that WP Rocket has not been completely uninstalled. Please guide me on how to overcome the above-mentioned issues.

Thanks
Rajesh

**Comment by piotrbak** [comment]
Hello @igecorner thanks for creating the issue.

If the problem happens after uninstalling WP Rocket, it sounds like another layer of cache. I'd suggest checking it with your hosting provider.

**Comment by igecorner** [comment]
Hi @piotrbak 

I dont have any other cache plugin, i have been using cloudflare CDN only, even after I purge cache from Cloudflare, it remains same

Its really frustrating, please help me 

Thanks

**Comment by piotrbak** [comment]
If WP Rocket was uninstalled from UI and is not visible there anymore, it's not possible for it to do caching for your website.
