### ISSUE TITLE
Missing href for critical path CSS docs link

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#622]
https://github.com/wp-media/wp-rocket/blob/39805efe7304be5a68115d2f19d3ba917a0a8299/inc/admin/ui/modules/optimization.php#L315

~~This issue is mostly a note to self, since the doc that should be linked here doesn’t exist yet. As soon a draft exists, the URL should be added.~~

**Update:** URL should be added and made translatable. English default should be:
http://docs.wp-rocket.me/article/108-render-blocking-javascript-and-css-pagespeed#critical-path-css

**Comment by webtrainingwheels** [comment]
Should be the same URL as our current doc,  since we're just updating it?

**Comment by glueckpress** [comment]
@webtrainingwheels Ah, this one?
http://docs.wp-rocket.me/article/108-render-blocking-javascript-and-css-pagespeed#critical-path-css

**Comment by webtrainingwheels** [comment]
Yes, that's what I was assuming we'd use

**Comment by glueckpress** [comment]
Fixed, thanks @Tabrisrp!
