### ISSUE TITLE
Auto clearing the cache for the homepage after publishing new content

### ISSUE THREAD

**Issue by parpluch** [wp-media/wp-rocket#6220]
**Is your feature request related to a problem? Please describe.**

Trigger - new content 
"When you publish new content or update/edit existing content, the cache for that post/page, the homepage, as well as related content (e.g. taxonomy archives) will be cleared."

**Describe the solution you'd like**

I want to disable auto clearing the cache for the homepage after publishing a new post. Is it possible?

**Comment by piotrbak** [comment]
Hello!

You'd need to remove it from this array:
https://github.com/wp-media/wp-rocket/blob/b613a0d95e9b04cb2e2688483485f2da77be3e6e/inc/common/purge.php#L242

If you need any further help, please reach our Support Team.

**Comment by skyfly24** [comment]
Hello, can you post your finished solution? I have the same problem.
Thanks
