### ISSUE TITLE
Weglot compatibility in some scenarios

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6223]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
1- If Weglot is activated after WPR, the translated URL is not added to the cache folder nor to the cache table 
2- If Weglot is activated before WPR, the translated URL is not added to the cache table although it is added to the cache folder
3- While Weglot and WPR are on, if we clear and preload the cache and then manually visit any pending URL, it won't be added to the cache folder nor completed in the table till after some time it is processed by preload (the main language URL)

**To Reproduce**
1. Fresh install/activate of WPR
2. Activate Weglot
3. Add new page
4. Visit the page and switch language 
5. Notice cache folder/table => no entry for translated URL
6. Reactivate WPR
7. repeat step 4 => translated URL added to cache folder but not to cache table

**Expected behavior**
Cache and preload are working correctly with Weglot

**Screenshots**

**Additional context**
- Used Free version of Weglot 4.2.1
- Clear cache for URL shall be fixed here https://github.com/wp-media/wp-rocket/issues/5279
- Cache of translated URL of home page not added to cache folder while permalinks without / (tested while preload is off)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- Manual visit to a page shall add an entry in the cache folder and the entry is completed at the cache table
- Clear and preload shall preload both main and translated URL 
- Clear used CSS of this URL shall clear the URL of the intended URL
 <strike>- Clear cache of this URL from page list / purge this URL from page view shall clear only the related URL (Note: now clear cache from page list is clearing cache of home as well, this is out of scope and can be added to the GH if needed by @wp-media/productrocket ) </strike>

**Comment by piotrbak** [comment]
@Mai-Saad the last point can be removed from AC 🙏

**Comment by Mai-Saad** [comment]
When editing a post, only the main language is deleted from the cache. @piotrbak I think we clear all translations as well. What do you think? Do we need a separate GH for this?

**Comment by Mai-Saad** [comment]
Note: https://github.com/wp-media/wp-rocket/pull/6280#issuecomment-1829733448

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.

**Comment by camilamadronero** [comment]
New related ticket: https://secure.helpscout.net/conversation/2923074672/557337?viewId=2675957

Weglot's translated URLs were **not** in the tables as reported above, the optimizations were partially/randomly applied, but this was specially affecting the Remove Unused CSS feature.
