### ISSUE TITLE
WPML compatibility issue with LL BG image in specific scenarios

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6224]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version =>3.15.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
1- Console error for external absolute URL CSS files in scenario 1 
2- A console error is there when trying to switch language in scenario 2

**To Reproduce**
 Scenario1:
1- WPML activated on domain base setup
2- install /activate WPR, then cache LL BG template (containing absolute URL of CSS file)
3- enable LL BG I then access the sub language FE and hard refresh => We will have a console error for some CSS files 

Scenario 2:
1- WPML is domain base, WPR LL BG image enabled
2- cache the page in both languages
3- WPML changed to a directory
4- access the main language page and click on language switch to sub-lang => console error

**Expected behavior**
No console error when accessing page/switching language with WPML while LL BG image is enabled

**Screenshots**
scenario1:
![274500362-c8974b91-3307-44df-bf5f-5a8091fc1779](https://github.com/wp-media/wp-rocket/assets/76941962/3afea1c3-0944-4adb-a0a4-ea34843f4ea4)

scenario 2:
![274507056-a2d5a5db-1f85-4ec9-ab08-f91fb78a1f7c](https://github.com/wp-media/wp-rocket/assets/76941962/571fde4b-99bf-4611-b82c-6ed0355c5c19)

**Additional context**
- Using Rocketlabs env
- For scenario 2, if we clear the cache and then repeat step 4, we will have no console error => shall we automatically clear the cache when changing the WPML setup? @wp-media/productrocket 

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- No console error for main/sub language using domain base setup /directory setup and string setup
- Switch language is working with no console error 
- Lazy load BG images working correctly with CDN on a regular and on a WPML environments
- No regressions to regular environment LL BG images feature

**Comment by CrochetFeve0251** [comment]
rocketlabs is using WPML and the issue is repoducable there.

**Comment by CrochetFeve0251** [comment]
## Reproduce the issue
I cannot reproduce the second scenario.

## Root issue
For the first scenario is due to that line https://github.com/wp-media/wp-rocket/blob/cfc26a39c9c42378e20acbdfdd99a998c5c34460/inc/Engine/Optimization/Minify/AbstractMinifySubscriber.php#L131 which add the new host url in all occurence in the url instead of just the domain leading to a extension added twice to the ll css generated file.

 ## Scope a solution

We should change `str_replace` by `preg_replace` with the parameter one to stop at the first occurence.

## Estimate effort
Effort  `XS`

**Comment by remyperona** [comment]
Fix for first scenario looks good to me
