### ISSUE TITLE
LazyLoad CSS BG: Errors when multiple </head> tags exist

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#6227]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Console error appears when the HTML includes more than one `</head>` exists

**To Reproduce**
1. Enable LazyLoad for CSS Background Images
2. Add an extra `</head>` to the HTML
3. Observe the console error: `Uncaught SyntaxError: redeclaration of const rocket_pairs`

**Expected behavior**
No error. 

**Additional context**
[Ticket](https://secure.helpscout.net/conversation/2378722292/446257/)
[Slack thread](https://wp-media.slack.com/archives/C43T1AYMQ/p1697232694689969)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.

**Comment by jekayode** [comment]
Another case: https://secure.helpscout.net/conversation/2740112082/518867/

**Comment by alfonso100** [comment]
another case https://secure.helpscout.net/conversation/2855019950/541783?viewId=2683093

**Comment by mifrero** [comment]
Another case: https://secure.helpscout.net/conversation/2852835286/541377

**Comment by Adrianadla** [comment]
A new ticket for this one:
https://secure.helpscout.net/conversation/2862165033/543143?viewId=8127822

**Comment by johan-las** [comment]
New ticket: https://secure.helpscout.net/conversation/2900123814/551509?viewId=8127840

**Comment by jekayode** [comment]
New ticket: https://secure.helpscout.net/conversation/2910625185/554759

**Comment by camilamadronero** [comment]
New case: https://secure.helpscout.net/conversation/3093568422/589632?viewId=2675957
Screenshot: https://jmp.sh/q8izlnkg

**Comment by markonikolic985** [comment]
Relevant ticket - https://secure.helpscout.net/conversation/3196716365/614675?viewId=424682

**Comment by suzoutlet** [comment]
Related: https://onecomhelp.zendesk.com/agent/tickets/16427493
