### ISSUE TITLE
Cache problem in elementor and bricks builder

### ISSUE THREAD

**Issue by Joliamendi** [wp-media/wp-rocket#6228]
**Describe the bug**

Hi wp rocket team,

I wanted to display the **post modified date** using the human readable format. But the problem is that when the page is reloaded in the front end, the **post modified date** is not updated. But when I disable wp rocket the problem goes away. Is there a solution to this issue? I am facing this problem in both elementor and bricks.

**To Reproduce**

1- In Elementor, add a heading widget and select the **post modified date** dynamic tag.
2- Set the date display format to human readable.
3- Reload the page in the front end. The post modified date is displayed. If you reload many times, the post modified date will not be updated.
4- If you clear the wp rocket cache and reload the frontend again, the post modified date will be updated, but if you reload the page again, it will not be updated.

If you disable wp-rocket, the problem is completely solved.

**Comment by alfonso100** [comment]
Hi @Joliamendi , thanks for reaching us. 
The issues on repository are used by the development team to work on WP Rocket features and bugs.

I am closing this issue, could you please open a Support Ticket with your question? 
https://wp-rocket.me/support/

One of our Support teammates will be able to help more accurately with your specific question: 

thanks!
