### ISSUE TITLE
Delay JS not handling specific markup correctly

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6232]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Delay JS is enabled, the following markup (where the URL file is not between `' '` nor `" "` is causing a warning in the console, and js is not executed
`<script src=https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/jquery.js ></script>`
After applying the Delay JS, it will be
`<script type="rocketlazyloadscript" src=https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/jquery.js></script>`

**To Reproduce**
1. Enable Delay JS
2. Open a page with an external script like the one above (without ' or ") and move the mouse
3. Notice the page source and page console

**Expected behavior**
JS is executed correctly after user interaction and no console error

**Screenshots**
with nowprocket
![Screenshot from 2023-10-18 08-20-13](https://github.com/wp-media/wp-rocket/assets/76941962/44438522-bd82-4252-b2e0-d47f68b6f912)
With Delay JS
![Screenshot from 2023-10-18 08-19-41](https://github.com/wp-media/wp-rocket/assets/76941962/ded7daf8-afa4-4d31-b2c1-431cecc2cc3f)
![Screenshot from 2023-10-18 08-50-41](https://github.com/wp-media/wp-rocket/assets/76941962/092393cf-e519-4da9-9ca3-9b808f69517b)

**Additional context**
- Same on WPR 3.12.5

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- `src ` changes to `data-rocket-src` for all formats of URLs i.e with/without ', "
- No console error when Delay JS is enabled before/after user interaction

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
