### ISSUE TITLE
Optimized fallback fonts not integrated within RUCSS rules

### ISSUE THREAD

**Issue by Eroan** [wp-media/wp-rocket#6237]
**Describe the bug**
When using optimized fallback fonts like this : 
`body {
  font-family: "Poppins", "Poppins-fallback", Arial, sans-serif !important;
}
@font-face {
    font-family: "Poppins-fallback";
    size-adjust: 112.50%;
    ascent-override: 110%;
    src: local("Arial");
}`

The font-face declaration is not integrated within Used CSS.

**To Reproduce**
1. Add a custom fallback font-face declaration and integrate it in your font-stack in second position
2. Activate RUCSS
3. Search for "-fallback" in the generated usedcss <style>
4. You will only see it in the font-family declaration, but nowhere else

**Expected behavior**
Optimized fallback fonts should be automatically integrated un usedcss since they offer precious gains regarding CLS metric.

**Additional context**
Bug can be corrected by manually excluding the font-face declaration in the admin field.

**Acceptance Criteria (for WP Media team use only)**

**Comment by piotrbak** [comment]
@mostafa-hisham What do you think about this one?

**Comment by mostafa-hisham** [comment]
@piotrbak the fallback font is not loaded because it was not used by default.
I think it safe listing the fallback font like this `@Poppins-fallback` will solve the issue.
we can automatically safelist fonts that contain `-fallback` but I don't think it is a CSS standard

**Comment by Eroan** [comment]
@mostafa-hisham @piotrbak 
Hello, a fallback font is, by definition, not the used font.
But in the same time, this is exactly why it exists.

Like I said, it can be whitelisted manually but most users will forget it and won't even be able to tell the difference.
But it will degrade web performance, especially the CLS metric.

Safelisting "-fallback" is not the way to go, this is a rule we are using at Agence Web Performance, but not a standard. It could potentially be any name.

The way to go is, in my opinion, to safelist the @font-face declarations for all the fonts declared in the font stacks.
Most of the time, only the first font will have one, the others being safe fonts (Arial, Verdana...) or generic fonts like sans-serif.

Thanks.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future if we receive more feedback.

**Comment by Eroan** [comment]
Of course you didn't, this is not what site owners typically deploy.
Anyway, I added a manual php overriding of default RUCSS exclusion list, it does the job.
Thanks.
