### ISSUE TITLE
RUCSS submitted_at field is incorrect

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6242]
Context
Follow-up on this https://github.com/wp-media/wp-rocket/issues/6204 which has a bug.
Submitted_at should be the timestamp at which we send the job to the SaaS. So, it should be set to null when putting the job in "to-submit" and set to current timestamp when putting the job "pending".

**Bug reproduction**
Start a lot of  RUCSS jobs from the plugin and limit the number of pending jobs to a small number. Some jobs will remain in to-submit for a while but they already have a submitted_at date.
**How to fix**
Set `submitted_at` to `null` in `create_new_job` and `reset_job`. Set it to current timestamp in `make_status_pending`

**Comment by Mai-Saad** [comment]
@MathieuLamiot I have some questions
1-  When retries change, Shall we update the submitted_at timestamp or it's just mapping the 1st request?
2-  At 6204, there was no `to_submit` status yet, and a timestamp was added once adding the URL to the table with the `pending status`. So here we need it to be added with `pending `status or `inprogress`?

> set to current timestamp when putting the job "pending"

3- When `failed` switched to` to-submit` shall we set `submitted_at` to NULL in this case?

**Comment by MathieuLamiot** [comment]
@Mai-Saad Sorry I missed your questions. `submitted_at` should always capture the last time we sent a job to the SaaS:
1- During retries, we don't send a new job so we don't touch submitted_at.
2- We send the job when switching from to-submit to pending, so we should set submitted_at when reaching the pending state in this transition.
3- No need to erase submitted_at: it remains relevant as it is still the last time we sent the job to the SaaS.
