### ISSUE TITLE
Updating a taxonomy in a language doesn't clear this same taxonomy in other languages in Polylang

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#6243]
**Is your feature request related to a problem? Please describe.**
Updating a taxonomy in a language doesn't clear this same taxonomy in other languages in Polylang

**Describe the solution you'd like**
Updating a taxonomy in a language should clear this same taxonomy in other languages in Polylang

**Additional context**
[Slack thread
](https://wp-media.slack.com/archives/C43T1AYMQ/p1697209478300319)

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
