### ISSUE TITLE
WPML: Partial cache clearing isnot working correctly when delete a post

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6246]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version =>3.15.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When deleting a post, We are only cleaning the main language of that post and home and we are not removing the other languages

**To Reproduce**
1. WPML directory setup or domain base setup
2. Preload is disabled
3. Cache home, home with cached qs, post, post with cached qs with all translations 
4. While admin is using the main language, delete the post => only the main language of home and posts with/without qs are removed from the cache folder

**Expected behavior**
Cache clear for home and post in all languages with/without qs

**Screenshots**

**Additional context**
- If we add a post, only the main language of the home will be deleted but once adding translation for that post, the home translation will be deleted (same when editing) 
- Purge this URL and clear this cache will also clear only the language matching the admin language

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- When deleting/trash a post, we Shall  clear the cache of that post, home , prev/next with /without qs for all languages

**Comment by Mai-Saad** [comment]
Note: the same is happening with Weglot when deleting a post, only the main language is removed from the cache

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
