### ISSUE TITLE
Conflict with Sirdata "data-cmp-src" attribute with Delay JS

### ISSUE THREAD

**Issue by Eroan** [wp-media/wp-rocket#6249]
**Describe the bug**
When using scripts conditionned by sirdata CMP (replacement of <script src=""></script> by <script data-cmp-src=""></script>), WP Rocket replaces attribute by adding its "data-rocket-..." and ignoring the "data-cmp-" prefix.

**To Reproduce**
1. Go to any editable content (template, widget...)
2. Add a conditionned script like <script data-cmp-src="https://www.googletagmanager.com/gtag/js"></script>
3. Activate WP Rocket Delay JS optimization, with or without exclusions
4. Check the generated html on public pages : there will be undesired "data-cmp-data-rocket-src" attributes, naturally ignored and scripts are not loaded

**Expected behavior**
data-cmp-src should not be replaced by data-cmp-data-rocket-src.

**Additional context**
Seen multiple times, and generally solved by adding "data-cmp-src" to exclusion list.
What would be really really nice is to be able to delay JS execution on this conditionned scripts too. But I think it's probably too specific to be prioritized in the roadmap.

**Acceptance Criteria (for WP Media team use only)**

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
