### ISSUE TITLE
Data URI SVG quand css compressé

### ISSUE THREAD

**Issue by LIJE** [wp-media/wp-rocket#625]
Les data URI d'image comme background image ne fonctionnent pas pour les svg avec la compression des fichiers css (car les espaces dans les paths des svg sont supprimés). (2.10.12)

**Comment by Tabrisrp** [comment]
On change de bibliothèque de minification avec la version 2.11 qui arrive demain, normalement ça devrait fonctionner mieux.

Si ce n'est pas le cas, je veux bien un retour et un exemple de avant/après, afin de pouvoir rapporter le bug au développeur de la bibliothèque.

**Comment by LIJE** [comment]
Je n'ai plus de licence sous la main pour la 2.11. Je ne peux pas te dire si ça passe ou non à moins que tu me la forward malheureusement. Je suis en 2.10.12 au mieux.
