### ISSUE TITLE
WP Rocket Caching plugin gets disabled on code deployment.

### ISSUE THREAD

**Issue by NKNdevs** [wp-media/wp-rocket#6251]
Here's our setup: WP Rocket is working and caching pages on our site. If we make a code update to the site, the following things happen:

- The code is pulled from git into a temporary directory. The code coming from git includes the wp-content/wp-rocket-config/ directory. 
- Various changes are made to the temp dir: some directories are mounted in place and some files are changed depending on various environmental factors eg dev or live.
- In particular, the correct advanced-cache.php to match the environment is copied into the wp-content folder. 
- The old web root directory is moved out of the way and the new web-root directory is moved into place. 

After a code update WP rocket is no longer caching pages. In order to start it again, the plugin needs to be disabled and re-enabled, at which point cacheing will resume. 

Originally the setup was that the wp-content/cache directory was pulled from git, and therefore moreorless empty. 
We have also tried pointing the cache directory somewhere outside of the webroot using advanced-cache.php settings, so that it isn't emptied on a code update. This also causes cacheing to pause. 

Maybe this is expected behavior. But we'd like to find a way to deploy code that doesn't mean manually restarting the cache plugin.  Are there extra configuration files that we're not accounting for? Is there a workaround?

**Comment by girlie** [comment]
Hi there, please reach out to our support team through our help center (while signed into your WP Rocket account) so they can assist you further: https://wp-rocket.me/support/

Thanks!
