### ISSUE TITLE
WP Rocket installed from Packagist: can't validate a license 

### ISSUE THREAD

**Issue by WillyReyno** [wp-media/wp-rocket#6253]
**Describe the bug**

"License validation failed: This license key is not recognized" error when trying to set up WP Rocket installed from packagist `wp-media/wp-rocket` 

**To Reproduce**
1. `composer require wp-media/wp-rocket`
2. Add `WP_ROCKET_EMAIL` & `WP_ROCKET_KEY` credentials to wp-config.php
3. Go to plugin page & enable WP-Rocket
4. Go to WP Rocket plugin page
5. See error

**Expected behavior**

Be able to install WP Rocket & validate license from a packagist installation.

**Screenshots**

![Capture d’écran 2023-10-27 à 18 06 11](https://github.com/wp-media/wp-rocket/assets/5576482/131a8643-ff07-49e8-90a5-c79edf87ee7c)

**Additional context**

I would like to automate the deployment process of my WordPress website including plugin installation. Until now I was able to do everything thanks to WP Packagist which allows me to install almost all my plugins through composer. No need to install them manually when deploying. Now I'm trying to do the same with premium plugins which requires specific installations and are not available on WP Packagist. I found a solution for [ACF Pro](https://www.advancedcustomfields.com/resources/installing-acf-pro-with-composer/) and now I want to do something similar with WP Rocket.

I found out that WP Rocket was available on Packagist thanks to this [issue](https://github.com/wp-media/wp-rocket/issues/479#issuecomment-368961818), so I wanted to try using it.

However, the license doesn't seem to be validated while my credentials are correct.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by girlie** [comment]
Hi there, please reach out to our support team through our help center (while signed into your WP Rocket account) so they can assist you with this issue: https://wp-rocket.me/support/

Thanks!
