### ISSUE TITLE
Please can you add this fix to the next version of the plugin

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [wp-media/wp-rocket#6255]
Another open issue with a proposed solution here: I really need this in the next WP-Rocket release.

https://github.com/wp-media/wp-rocket/pull/4523

I am desperate for this to be implimented. It has improved my import times 10-fold on a large website when I manually added it to WP-Rocket with a script in WPALLIMPORT to clear the cache at the end of an import instead of the start.

**Please can you add this in the next Wp-Rocket release. Its a brilliant idea and works.**

**Comment by piotrbak** [comment]
Closing as duplicated
