### ISSUE TITLE
Media page caching issue

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6262]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version =>3.15.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are caching media pages i.e https://new.rocketlabsqa.ovh/full-4-jpg. but when editing that page cache isnot cleared.

**To Reproduce**
1. Install and activate WPR
2. Visit the media page 
3. Check cache
4. Edit the media page and check the cache again

**Expected behavior**
As per QA discussions, either not caching those pages or applying partial cache clearing if it will be cached. @wp-media/productrocket What do you think?

**Additional context**
- The same is on WPR 3.11.4

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by hanna-meda** [comment]
QA Note: Sending media to trash won't clear cache either. Keeping this in mind when retesting the fix.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
