### ISSUE TITLE
Improve the rocket_is_mobile_plugin_active notice

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6264]
**Is your feature request related to a problem? Please describe.**
It's not clear which plugin is active when the `"We detected you use a plugin that requires a separate cache for mobile, and automatically enabled this option for compatibility."` text is displayed under the `Separate cache files for mobile devices` feature.

**Describe the solution you'd like**
The admin notice should include the name of the plugin that requires the option to be active. This would give customers the complete information about why WP Rocket settings are "forced active", it can help avoid tickets, and it would help save time figuring it out.

**Describe alternatives you've considered**
NA

**Additional context**
Rel ticket: https://secure.helpscout.net/conversation/2411755445/452789/
Thanks!

**Comment by webtrainingwheels** [comment]
I believe it's a duplicate of: https://github.com/wp-media/wp-rocket/issues/5100

**Comment by camilamadronero** [comment]
Ah, that's right. Thanks, Lucy!
