### ISSUE TITLE
Footprint causes problems with Social media Cards

### ISSUE THREAD

**Issue by ZiroNL** [wp-media/wp-rocket#6267]
**Is your feature request related to a problem? Please describe.**
Yes. Twitter cards (and maybe other social media cards) has problems with the footprint. When we remove the footprint, the card always works.
The problem is the footprint after the </html> tag

**Describe the solution you'd like**
Please consider to place the footprint within the <html></html> tags.

**Comment by piotrbak** [comment]
@ZiroNL Could you elaborate on what kind of problem do you have with the social media cards? Screenshots would be appreciated.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
