### ISSUE TITLE
Minify JS - Exclude Cloudflare Turnstile JS file by default

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#6268]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Our Minify JS feature modifies: 
`https://challenges.cloudflare.com/turnstile/v0/g/xxxxxxxxxx/api.js`
into:
`https://www.example.com/wp-content/cache/min/1/turnstile/v0/api.js`

It breaks the Cloudflare feature.

Excluding `https://challenges.cloudflare.com/turnstile/` addresses the issue.

**Expected behavior**
[Cloudflare Turnstile](https://www.cloudflare.com/fr-fr/products/turnstile/) should work with no issue

**Additional context**
[HS Ticket](https://secure.helpscout.net/conversation/2410772558/452616/)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
@WordPresseur Wouldn't it go directly to the backend?

**Comment by benorfaz** [comment]
@WordPresseur @piotrbak Why is this issue still open? Can we proceed to add to the backend to close it?

**Comment by benorfaz** [comment]
Was added, closing ticket.
