### ISSUE TITLE
[2.11-beta6] Critical CSS: missing condition for blog home page

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#627]
https://github.com/wp-media/wp-rocket/blob/2337034d8784bffdc6843129fd797a782325637f/inc/classes/class-rocket-critical-css.php#L315-L320

There’s a part missing here to cover the case where the home page is not explicitly set, but defaults to list recent blog posts ([`is_home()`](https://developer.wordpress.org/reference/functions/is_home/)):

```php
else {
	$this->items[] = array(
		'type' => 'home',
		'url'  => home_url( '/' ),
	);
}
```

Without this part, critical CSS doesn’t get inserted on a default home page, whereas it’s inserted alright on all other page types.

When the `else` statement is appended, though, critical CSS is also inserted on the home page.

**Comment by Tabrisrp** [comment]
Are you talking about when the option is set to "your latest posts", or when the option is set to a static page and no page is selected for the homepage?

**Comment by glueckpress** [comment]
@Tabrisrp Option set to “your latest posts”.
