### ISSUE TITLE
RUCSS rows are not failed when they can't be added to the queue

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6271]
**Context**

In 3.15.3, the to-submit status was introduced for RUCSS table. When a row can't be sent to the SaaS (for any reasons, 401, unreachable API, etc...) the row remains in `to-submit` and is retried at the next cron interval. This can result in infinite loops for unauthorized users, or high CPU usage when a website can't reach the RUCSS API for instance, even if the feature is de-activated.

**Expected behavior**

- If a 'to-submit' row can't be sent to the SaaS, then it should be set to a `failed` status.
- To-submit jobs should not be processed if the RUCSS feature is not activated.

**Acceptance Criteria**
- No regressions with the nominal behavior (no error case).
- Force the failure of an API call from the plugin to the SaaS to register a job from a 'to-submit' row. The row should go to the status 'failed' with an error_message and error_code filled.
- Activate the RUCSS feature and purge the RUCSS table, wait for some rows to be added in 'to-submit'. Deactivate the feature. The jobs in to-submit must remain in that state forever. No API call to the SaaS should be performed.

**Suggestion**

- Add a check at the beginning of process_on_submit_jobs as in process_pending_jobs https://github.com/wp-media/wp-rocket/blob/cb55163b93f7df7d665eab91b17443f2cbe9e234/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L476-L480
- Instead of doing noting if can the send_api method did not return as expected, use the method make_status_failed: https://github.com/wp-media/wp-rocket/blob/cb55163b93f7df7d665eab91b17443f2cbe9e234/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L1013

**Comment by CrochetFeve0251** [comment]
@MathieuLamiot adding a guarding at the entance of `process_on_submit_jobs` won't be useful at we already disabled it there if RUCSS is not enabled: https://github.com/wp-media/wp-rocket/blob/cb55163b93f7df7d665eab91b17443f2cbe9e234/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L209
