### ISSUE TITLE
Exclude js scripts with type="module" from JS minification

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6273]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the option “Minify JavaScript files” is enabled, and scripts with `type="module"` are moved to the min folder, is likely to cause 404 errors because a a JS file with this type is likely to have import statemets, and changing the path where the expected module is located will break these links

Per customer feedback: 
> 2. JavaScript with type=“module” will always have “import” statements in it that references to a files, which location or existence WP Rocket cannot detect. So if WP Rocket changes and moves the file, the paths to these files are interrupted by WP Rocket.

Example code. the files `./localization.d6c03d4a.js`, `./selectors.e37ac126.js` and `./vue.16a54326.js` with cause 404:
```
import{_ as i,a as n,b as s,c as e,d as a,e as r,f as l,g as C,h as b,i as d,j as c,k as w,l as k}from"./localization.d6c03d4a.js";import{_ as t,a as g}from"./selectors.e37ac126.js";import"./vue.16a54326.js";class _{IABTCF(){return{currentTCString:"",hasWhichConsents:function(){return{}},isTCStringUpToDate:function(){return!1},signalDoNowShowUI:function(){},saveConsentAll:function(){}}}}const p=new _;i.init(window.borlabsCookieConfig.contentBlockers);n.init(window.borlabsCookieConfig.providers);s.init(window.borlabsCookieConfig.serviceGroups);e.init(window.borlabsCookieConfig.services);t.init(window.borlabsCookieConfig.settings);a.init(window.borlabsCookieConfig.globalStrings);window.borlabsCookiePrioritized===void 0&&(window.borlabsCookiePrioritized={},window.borlabsCookiePrioritized.optInCodesUnblocked={});r.optInCodesUnblocked=window.borlabsCookiePrioritized.optInCodesUnblocked;const f={Cookie:C,ContentBlocker:i,Consents:b,ConsentHistory:d,Providers:n,ScriptBlocker:c,ServiceGroups:s,Services:e,CookieLibrary:w,Settings:t,Log:g,Unblock:r,Tools:k,Adapter:p};window.BorlabsCookie=f;window.__toBorlabsPluginAssetUrl=o=>window.borlabsCookieConfig.settings.pluginUrl+"/assets/"+o;l.init();
```

**To Reproduce**
1. Enqueue a JS script with the above code.
2. create some import scripts at the same location for example: `./localization.d6c03d4a.js`, `./selectors.e37ac126.js` and `./vue.16a54326.js`
3. test the page without JS minification, it will be fine. 
4. Enable JS Minification
5. See the 404 error on the imported files
6. Exclude the origin file form JS minification
7. see the errors fixed

**Expected behavior**
we should exclude `type="module"` from minification

**Screenshots**
![cleanshot-2023-11-08-at-15-50-49-2x](https://github.com/wp-media/wp-rocket/assets/229406/18aba7a0-765d-4bcf-9269-eda45cee5e2d)

**Additional context**
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1699483184373919
ticket: https://secure.helpscout.net/conversation/2414653718/453464?folderId=2683093

**Acceptance Criteria (for WP Media team use only)**
- The exclusion should be part of the backend
- It's blocked by https://github.com/wp-media/rucss-backend/issues/83

**Comment by CrochetFeve0251** [comment]
@piotrbak I am just wondering how we can handle the order of the execution with that.
Imagine we have in that order:
- `moduleA`
- `regularJsA`
- `moduleB`
- `regularJsB`
Is it possible that changing it to : 
- `moduleA`
- `moduleB`
- `minifyA+B`
Could break something?

**Comment by BenBornschein** [comment]
If you leave JavaScripts of type module untouched, nothing should break. And there should be no JavaScript that is not of type module that depends on JavaScript of type module.

**Comment by piotrbak** [comment]
Moving it back to `To do`, so we can take advantage of the backend. Waiting for @mostafa-hisham to move forward with https://github.com/wp-media/rucss-backend/issues/83

**Comment by MathieuLamiot** [comment]
@piotrbak The back-end part should be completed this sprint.

**Comment by piotrbak** [comment]
Based on this PR:
https://github.com/wp-media/rucss-backend/pull/129

We need to move this part of the code to the backend:
https://github.com/wp-media/wp-rocket/blob/3abb772b945c7154348a44a0e6d13e51f64c9a2c/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L100-L104

To test:
1. JS files with `data-minify=` argument are not minified
2. JS files with `data-no-minify=` argument are not minified
3. JS files with `type="module"` argument are not minified

**Comment by Khadreal** [comment]
Do you mean we shouldn't handle this from WPR?

**Comment by piotrbak** [comment]
It's present in this file:
https://github.com/wp-media/wp-rocket/blob/develop/dynamic-lists.json
as:
`exclude_js_template`

**Comment by remyperona** [comment]
I don't think this is an XS task, it's likely to be more of an S, as it will require new tests and class construction update. Please do a proper grooming on it.
