### ISSUE TITLE
Prevent infinite loop for RUCSS jobs returning 408 consistently.

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6275]
**Context**
Following 3.15.3 and also the rework of [the retry strategies in RUCSS](https://github.com/wp-media/wp-rocket/issues/6222), an edge case has been introduced for jobs returning a 408 where a new job is sent everytime, and if the page consistently returns 408, then the plugin will always keep trying with a new job.

**Expected behavior**
When receiving a 408 from the RUCSS SaaS, the plugin must retry with a new job, up to a few times. A maximum of up to 3 different successive jobs would be a good target (but can be discussed).
Each new job must be considered as a new one by the retry strategies, except for the strategy dealing with 408 to avoid an infinite loop.

**Acceptance criteria**
- Force a URL to return 408 jobs twice, then to return another code (valid, or error). The plugin must try three times and the third job must have the correct status.
- Force a URL to always return 408 jobs. At some point, the plugin must stop trying and put the row to failed. 

**Notes**
Once this is implemented, notify @mostafa-hisham or @MathieuLamiot to plan for re-enabling the 408 in case of timeout on the SaaS part.

**Comment by mostafa-hisham** [comment]
## Scope a solution

- To avoid the loop problem that we had with 408
we can create a new job like we normally do but only do the reset on the first time we get 408 from RUCSS
if the `last error_code!= 408` then follow the same retry strategy 

After merging the Rework [PR](https://github.com/wp-media/wp-rocket/issues/6222)

we can add the condition to check the last error code before this line
https://github.com/wp-media/wp-rocket/blob/8fe4b78252a3e50f8915e9ed60cbc3266f9bd87b/inc/Engine/Optimization/RUCSS/Strategy/Strategies/ResetRetryProcess.php#L41

## Effort estimation: 
S

**Comment by CrochetFeve0251** [comment]
> ## Scope a solution
> 
>     * To avoid the loop problem that we had with 408
>       we can create a new job like we normally do but only do the reset on the first time we get 408 from RUCSS
>       if the `last error_code!= 408` then follow the same retry strategy
> 
> 
> After merging the Rework [PR](https://github.com/wp-media/wp-rocket/issues/6222)
> 
> we can add the condition to check the last error code before this line
> 
> https://github.com/wp-media/wp-rocket/blob/8fe4b78252a3e50f8915e9ed60cbc3266f9bd87b/inc/Engine/Optimization/RUCSS/Strategy/Strategies/ResetRetryProcess.php#L41
> 
> ## Effort estimation:
> 
Seems good to me but @mostafa-hisham  how will you do that check ? last error_code!= 408
We will store it into the db?

**Comment by mostafa-hisham** [comment]
@CrochetFeve0251 I think we should have the last `error_code` in `$row_details` object here
https://github.com/wp-media/wp-rocket/blob/8fe4b78252a3e50f8915e9ed60cbc3266f9bd87b/inc/Engine/Optimization/RUCSS/Strategy/Strategies/ResetRetryProcess.php#L35

**Comment by MathieuLamiot** [comment]
@mostafa-hisham I have several issues with this idea: 
- The first time we get a 408, we would go into `reset_job`. When resetting the job, we clear the error_code, so if another 408 appears, then we would not know it is the 2nd one.
- This solution does not offer flexibility about the number of retries we can use.
For point 1, we could of course keep the previous error_code, but it would be stacking up new logic into something that was not designed for this initially.

The following approach sounds more scalable, future-proof and cleaner to me, WDYT?
- Add a column "successive_failed_jobs" to the DB, storing int, default to 0.
- In `make_status_fail`, add logic to increment `successive_failed_jobs` by one.
- In 'reset_job', add logic to increment `successive_failed_jobs` by one.
- In make_status_completed, add logic to reset `successive_failed_jobs` to 0.
**-> We now have a counter of successive failed jobs for a given URL.**
- Upon receiving a 408, instead of calling `ResetRetryProcess`, call `JobSetFail`
**-> Whatever the code, a row will always be failed when a job failed.**
- Rework the `get_failed_rows` method and integrate a strategy design pattern into it: For each defined strategy, there will be one query. The CRON handling failed jobs will run each query (so one query per strategy) and the union of the results will be the failed jobs to retry. We can then design strategies:
   - default strategy: all failed rows older than 3 days (current behavior)
   - 408 strategies: all failed rows with error_code = 408, successive_failed_jobs = n, older than `$408_retry_backoff[n-1]`
   
I believe introducing such a system could also help us refine the behavior of failed jobs (currently we retry every 3 days, we could have back-off there as well, etc.)

I am putting back in Grooming todo

**Comment by mostafa-hisham** [comment]
@MathieuLamiot 
from what I understand from this part maybe I missed something.

> - Upon receiving a 408, instead of calling `ResetRetryProcess`, call `JobSetFail`
**-> Whatever the code, a row will always be failed when a job failed.**
>- Rework the `get_failed_rows` method and integrate a strategy design pattern into it: For each defined strategy, there will be one query. The CRON handling failed jobs will run each query (so one query per strategy) and the union of the results will be the failed jobs to retry. We can then design strategies:
>   - default strategy: all failed rows older than 3 days (current behavior)
>  - 408 strategies: all failed rows with error_code = 408, successive_failed_jobs = n, older than `$408_retry_backoff[n-1]`
   
the cron that goes through failed jobs runs every 3 days by default which means we will retry the 408 jobs every 3 days too.
https://github.com/wp-media/wp-rocket/blob/cfc26a39c9c42378e20acbdfdd99a998c5c34460/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L174

if this is intended I think we don't need to send back 408 anymore we can send back 500 instead and wait for the `rocket_remove_rucss_failed_jobs` cron to remove them.

we already [doing this for the past two weeks](https://github.com/wp-media/nodejs-treeshaker/pull/506) for navigation timeout, we can check with the support team and see how much this impacted them last 2 weeks.

**Comment by MathieuLamiot** [comment]
> the cron that goes through failed jobs runs every 3 days by default which means we will retry the 408 jobs every 3 days too.

This would have to be changed. I am not sure I understand why we run this CRON only once every 3 days TBH. We already have a 3 day limit implemented when querying for the failed jobs... So it means some jobs remain failed for up to 5 or 6 days currently.

> if this is intended I think we don't need to send back 408 anymore we can send back 500 instead and wait for the rocket_remove_rucss_failed_jobs cron to remove them.

This is the behavior we want to avoid now. Having to wait so long for a 408 is not right.

**Comment by MathieuLamiot** [comment]
@piotrbak any idea why we run the Failed cron job every 3 days + when it runs, we only take jobs failed for more than 3 days?

**Comment by piotrbak** [comment]
@MathieuLamiot It's a leftover from early implementation, since the cron will have more responsabilities, we can change it I believe.

**Comment by MathieuLamiot** [comment]
Ok, clear thanks :)
Then @mostafa-hisham, @CrochetFeve0251, what do you think of the suggested approach + running the failed_cron_job more frequently? (Maybe every few hours)

**Comment by mostafa-hisham** [comment]
@MathieuLamiot 
I think it is good and will give us flexibility in handling failed jobs.
my only concern is the increase in the number of records that we will query to process  500 + 408.

@wordpressfan can this lead to problems with clients on week servers? (you dealt with cron problems a lot) :grin:

**Comment by wordpressfan** [comment]
I believe we are fine here and after a discussion with @mostafa-hisham we have some points that will help on grooming:

- We need to differentiate between the failed [cron schedule](https://github.com/wp-media/wp-rocket/blob/a23c147b38baeb51d6a0039e190dc514ec994605/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L174) (3 days) and the [offset interval](https://github.com/wp-media/wp-rocket/blob/da051125ed36c6a9ee263696771b1eda75078059/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L718) that is used in the query that gets the failed jobs (and 408 ones here)
- For the strategy pattern, I don't know how do u want to use it, maybe you need to create one CRON and inside it you will handle the statuses u want? I don't think this is a strategy pattern because there is no condition to decide with, anyway when adding a code to handle the 408 case like failed we need to consider using a direct query to reset them directly in the database, instead of having a query and loop into results like what we do with failed rows.

**Comment by MathieuLamiot** [comment]
Following the technical audit, we figured a better approach in the long run would be to manage the retry mechanism in the backend directly. This will give us more flexibility and simplify the logic on the plugin side.

Therefore, this won't be changed for now in the plugin and related issues on the backend side will replace this.
