### ISSUE TITLE
Cache is cleared multiple times when switching theme

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6276]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
The discussion was started here: https://github.com/wp-media/wp-rocket/pull/6263#issuecomment-1818623315

Now when switching the theme we are clearing the cache three times but we need to clear it once, this is because we add the callback `rocket_clean_domain` with different hooks as mentioned in the link above, will state them here too:

**First location:**
https://github.com/wp-media/wp-rocket/blob/afef3b6bc067af18de183a10e337e17eef5707db/inc/common/purge.php#L16

**Second location:**
https://github.com/wp-media/wp-rocket/blob/afef3b6bc067af18de183a10e337e17eef5707db/inc/common/purge.php#L8

**Third and main location:**
https://github.com/wp-media/wp-rocket/blob/afef3b6bc067af18de183a10e337e17eef5707db/inc/common/purge.php#L6

So we opened this issue to investigate the first two locations ad why they are firing with switch theme and in all cases we need the cache clear happens only once.

**To Reproduce**
1. Cache some pages
2. Add a log inside here: https://github.com/wp-media/wp-rocket/blob/7d56c419ff2834988b233a3558210587da0dad50/inc/functions/files.php#L806
3. Switch theme from backend
4. Check the log file, you will find the log message repeated three times.

**Expected behavior**
Cache clear should happen only once with switching theme.

**Acceptance Criteria (for WP Media team use only)**
1. Cache should be cleared only once when switching the theme
2. It should work without regression when activating theme via WP CLI

**Comment by mostafa-hisham** [comment]
@wp-media/php-team 
I am not sure what should we do here
based on the WP code here
https://github.com/WordPress/wordpress-develop/blob/1029dde1bc8b8c94dd502c294de51c41c79f741a/src/wp-includes/theme.php#L784
the actions
```
add_action( 'update_option_sidebars_widgets', 'rocket_clean_domain' );  // When you change the order of widgets.
add_action( 'update_option_category_base', 'rocket_clean_domain' );  // When category permalink is updated.
```
will fire at the beginning of the function before the `switch_theme` is fired 
and there is no `before_switch_theme` action and I couldn't find any workaround for it.

Could you please have a look at it?
(moving it back to grooming)

**Comment by jeawhanlee** [comment]
rocket_clean_domain is fired `2x` on my end for the following hooks:
`update_option_theme_mods_{$name}`
`switch_theme`
and the first is executed in switch_theme function here:
https://github.com/WordPress/wordpress-develop/blob/1029dde1bc8b8c94dd502c294de51c41c79f741a/src/wp-includes/theme.php#L803 or here: https://github.com/WordPress/wordpress-develop/blob/1029dde1bc8b8c94dd502c294de51c41c79f741a/src/wp-includes/theme.php#L864C1-L864C1
which will fire at the beginning before `switch_theme` is fired as @mostafa-hisham stated above.
I tried the possibility of using transients with timestamps after the first time `rocket_clean_domain` is fired but we might be clearing too early and bail out before switch_theme is fired.

Moving back to needs grooming as well...

**Comment by vmanthos** [comment]
How about checking if `1 !== did_action( 'after_rocket_clean_domain' )` and only then run the other two actions?

**Comment by remyperona** [comment]
The `did_action()` check could be something we add in each function, so that we avoid cleaning multiple times.

Each callback makes sense individually, but there is some context where they will all fire one after the other.

**Comment by Miraeld** [comment]
I've tried to take a look at it about the `did_action()` check, but I couldn't make it work on my side, I still had multiple. 
I couldn't find another fix that would work. 

It's possible that I did something wrong with the `did_action()`...

**Comment by Miraeld** [comment]
If we add a bail-out within this function 
https://github.com/wp-media/wp-rocket/blob/ea5ae60c0b2dd2f9b7cb3ae97c23b4db330ba4f1/inc/functions/files.php#L805
such as 
```php
	if (1 === did_action( 'after_rocket_clean_domain' )) {
		return;
	}
```

I can get down to 2 calls instead of 3. Not there yet, and I can't figure out where the 2 are from ..

**Comment by hanna-meda** [comment]
@piotrbak , tested this and it is as @Miraeld described:

> I can get down to 2 calls instead of 3. Not there yet, and I can't figure out where the 2 are from ..

Can you confirm if this is acceptable for now, with 2 entries?

**Comment by piotrbak** [comment]
Yes, that's already an improvement
