### ISSUE TITLE
Do not add URLs to the wpr_rocket_cache table if Preload is disabled

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#6278]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
Currently, any URL that is visited by a real user is added to the `wpr_rocket_cache` table and automatically assigned a “Complete” status even when the Preload is disabled. This causes the DB to grow too large in some cases.

**To Reproduce**
1. Make sure the Preload is disabled
2. Visit some URLs while not logged-in
3. Check the `wpr_rocket_cache` table in the DB and you'll find those visited URLs added to it with a "Complete" status

**Expected behavior**
The table itself is not necessary for the caching process to run effectively, so no URLs should be added to it when the Preload is disabled.

Temporary fix - The snippet below will prevent all URLs from being added to the table if the preload is disabled:

```
// prevents adding URL to the wpr_rocket_cache table if Preload is disabled
function stop_adding_top_preload( array $regexes ) : array {

	$new_regex = $_SERVER['REQUEST_URI'];
	
	$options = get_option('wp_rocket_settings', []);

	//only if preload is disabled
	if( $options['manual_preload'] == 0) {

		// add the currently visited URL to the exclusions array
		$regexes[] = $new_regex;

	}

return $regexes;
}

add_filter( 'rocket_preload_exclude_urls', 'stop_adding_top_preload');
```

**Screenshots**
N/A

**Additional context**
HS ticket: [https://secure.helpscout.net/conversation/2405513676/451397/](https://secure.helpscout.net/conversation/2405513676/451397/)
Slack thread: [https://wp-media.slack.com/archives/C08N8J6VC/p1698938940269529](https://wp-media.slack.com/archives/C08N8J6VC/p1698938940269529)

**Acceptance Criteria (for WP Media team use only)**
1. When preload is disabled, we should not add URLs to the cache table
2. When enabling preload, there should not be any regression with fetching the sitemaps
3. When the preload is enabled, URLs should be added to the table without regression

**Comment by Miraeld** [comment]
## Reproduce the problem
To reproduce the issue, follow the described steps in the issue. 

## Identify the root cause
The issue is that we are not checking if the manual preload is `true` or `false` here:
https://github.com/wp-media/wp-rocket/blob/4c024ba271e7f6d45f859af8e6392816c41b8ffd/inc/Engine/Preload/Subscriber.php#L449-L457


## Scope a solution
To solve the issue, we could add this: 
```php
$request_uri = filter_var( wp_unslash( $_SERVER['REQUEST_URI'] ), FILTER_SANITIZE_URL );

if( (bool) !get_rocket_option( 'manual_preload', true ) ) {
	// add the currently visited URL to the exclusions array
	$regexes[] = $request_uri;
}
```
to the mentioned function.

## Effort estimation: 
S

## Is a refactor needed in that part of the codebase?
No
