### ISSUE TITLE
LCP & Above the Fold: Refactor the RUCSS API, Queue and CRON

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6281]
**Is your feature request related to a problem? Please describe.**
Refactor the RUCSS API, Queue and CRON so that one request is done per page for all SaaS optimizations

**Comment by jeawhanlee** [comment]
## Scope a solution ✅
- We will need to start by abstracting some methods in `WP_Rocket\Engine\Optimization\RUCSS\Controller::UsedCSS` that should be shared between the 2 features.
  - `add_url_to_the_queue`
  - `process_pending_jobs`
  - `check_job_status`
  - `process_on_submit_jobs`
  - `send_api`
- Add New class in `Common` for the methods above.
- Update methods to also save lcp jobs and process pending and `to-submit` lcp jobs in the atf table using the same job_id and queue_name.
- Abstract the API Client.
- Update the API Client methods to deactivate lcp with 401 code and mock updated SaaS response for the default return.
- Abstract the new Retry Strategy to be shared between these 2 features as well.
- Abstract the Cron subscriber that is currently in the RUCSS Module.
- Update the current [lcp](https://github.com/wp-media/wp-rocket/blob/7c8869d237f5b50f9260d303546561280d962b7e/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L55) method we have on the 3.16 front-end branch to check for job status and create new jobs when needed.

Estimate the effort ✅
[M]

**Comment by MathieuLamiot** [comment]
@jeawhanlee Hey, what do you think is the remaining time for this? Thanks!

**Comment by jeawhanlee** [comment]
> @jeawhanlee Hey, what do you think is the remaining time for this? Thanks!

@MathieuLamiot By Friday
