### ISSUE TITLE
Stop firing WP CRON when it's disabled

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6282]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When the constant `DISABLE_WP_CRON` is true, we need to stop calling the method spawn_cron here:

https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L616

This was a suggestion from Kinsta not to fire the CRON because this may cause CPU issues.

**To Reproduce**
1. Add the following line in wp-config.php `define( 'DISABLE_WP_CRON', true )`
2. Activate RUCSS
3. Wait in WPR settings page for 90 seconds
4. Ajax request will be sent to our backend to fire the CRON

**Expected behavior**
CRON should not be called at all when this constant is set.

**Additional context**
Slack convos:

https://wp-media.slack.com/archives/CUT7FLHF1/p1700469134274159
https://wp-media.slack.com/archives/C056ZJMHG0P/p1700248478315299

**Acceptance Criteria (for WP Media team use only)**
1. When the CRON is disabled, we should run our functions manually to make sure that Used CSS for homepage is generated
2. We should not spawn CRON if it's disabled

**Comment by wordpressfan** [comment]
## Reproduce the issue
Yes

## Root cause
As mentioned in the issue, we force the cron to run once the RUCSS option is activated and wait for 90 seconds, this ajax request will be sent to backend to fire the CRON.

## Scope a solution
We need to fix this from both sides (the js part and the php part)

**JS part:**
Here

https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Optimization/RUCSS/Admin/Settings.php#L368

We need to add a new key for `cron_disabled` which has the value as below:
```
$data['cron_disabled'] = rocket_get_constant( 'DISABLE_WP_CRON', false );
```

Then in JS [here](https://github.com/wp-media/wp-rocket/blob/c2172cab84abbd3dff54bf5ac07a77880867eaeb/assets/js/wpr-admin.js#L354) add new condition to check on this new attribute `rocket_ajax_data.cron_disabled`

**PHP Part:**
[Here](https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L608) we need to add the following check:
```
if ( rocket_get_constant( 'DISABLE_WP_CRON', false ) ) {
    return;//Bailout and don't fire the CRON.
}
```

#Effort
[S]

**Comment by Miraeld** [comment]
Seems good to me :)

**Comment by piotrbak** [comment]
Changed the Acceptance Criteria here.
