### ISSUE TITLE
LCP & Above the Fold: admin part

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#6284]
### Scope a solution ✅ 
- Add a Controller and Subscriber for the admin part
- Load them in the service provider
- Add the admin subscriber to the Plugin loader
- Add the dependencies to the controller
- Add methods to delete specific row(s) or all the rows (similar to RUCSS)
- Add the controller as a dependency to the subscriber
- Add hooks and callbacks in the subscriber (similar to RUCSS)

### Estimate the effort ✅
Effort [M]

**Comment by MathieuLamiot** [comment]
@Tabrisrp, is there a PR to link there and maybe to put to review?

**Comment by MathieuLamiot** [comment]
@Tabrisrp kind reminder

**Comment by remyperona** [comment]
It's linked, it's currently not good to review because it also contains the changes from the frontend part. We would need to merge this part first.

**Comment by MathieuLamiot** [comment]
Ok thanks. @Tabrisrp, @jeawhanlee can [this PR](https://github.com/wp-media/wp-rocket/pull/6244) be merged into the 3.16 branch then? That would unlock the flow I think without impacting develop nor preventing tests from the QA team I guess.
