### ISSUE TITLE
Removing combine CSS is the worst decision ever by Wp-rocket

### ISSUE THREAD

**Issue by luckyankit** [wp-media/wp-rocket#6286]
Removing the combine CSS option has proved that wp-rocket has gone into dictator mode. In the race of making it simple, it has taken away so many options that they think they are doing it right, but it is not. 

So much relying on the UCSS generator and I have seen it numerous times that their UCSS generator just simply fails in extracting correct UCSS even if all the whitelist properly defined which has worked fine in the past. 

This UCSS generator has gone so bad for a few sites that I had to remove the wp-rocket and shift to a different cache plugin. 

Wp-rocket must bring back the combine CSS option and fix their UCSS generator or its a completely deal breaker thing now.

**Comment by piotrbak** [comment]
Hello @luckyankit and thank you for your honest opinion. Please read this topic to learn more about this decision:
https://github.com/wp-media/wp-rocket/issues/5909#issuecomment-1706398016

Moreover, as stated in the above issue, if you experience any performance decrease because of the lack of CSS Combination feature, please reach our Support Team with real data or example, we'll be more than happy to analyze that and find a proper solution. Each decision made is preceded by research and benchmarks.

**Comment by luckyankit** [comment]
I have read that previously, that's not a justification for removing the feature. Also, you stay muted on the UCSS generator part which shows you clearly know about the issues related to it. 

It should be user decision whether to use it or not. If it doesn't work properly, they can keep it off, but removing it is just absolute nonsense, nothing else.

**Comment by piotrbak** [comment]
We're constantly working on improving the tool. 

We'll be more than happy to see any example of the website where CSS Combination is giving any value and investigate this case. Keeping the feature just to keep it, when it doesn't impove the performance is not a good approach.

**Comment by luckyankit** [comment]
The example, that on many pages, the wp-rocket simply extracts wrong UCSS and with a site of 15K 40K URLs, it is not possible to find where it failed and extracted wrong UCSS and where not. 

This reason is good enough to prove that combined CSS is a required feature and must not be removed.

**Comment by luckyankit** [comment]
This ticket should be marked back as open, combine CSS is absolutely required feature and it is the user decision whether they should use it or not.
