### ISSUE TITLE
rocket_init() very slow making the page rendering slow

### ISSUE THREAD

**Issue by fidoboy** [wp-media/wp-rocket#6287]
I've noticed that on every bootstrap of the frontpage renders the worst performance is from WP Rocket plugin. 

`rocket_init()                                                     | 0.5411s | wp-rocket/inc/main.php:25`

The rocket_ini() function takes 0.5411s so it's clearly causing a slowdown to the outputs.

**Comment by piotrbak** [comment]
Hello @fidoboy could you contact our Support Team, so we could investigate your website there?

@wp-media/php-team what's your opinion on that?

**Comment by fidoboy** [comment]
I've discovered that it was a issue with the TagDiv Composer CSS Compiler in Newspaper theme. It always gives many problems

**Comment by piotrbak** [comment]
Thank you for your follow-up. Looks like this is outside of our scope then, feel free to reopen the issue if you feel there's something that should be don on our side.
