### ISSUE TITLE
Manually delete cache files not automatically generate new cache files

### ISSUE THREAD

**Issue by winardi-morefire** [wp-media/wp-rocket#6288]
**Before submitting an issue please check that you’ve completed the following steps:**
- WP Rocket version: 3.13.4

**Describe the bug**
After doing manually delete the minified and and gzip cache files, WP Rocket not automatically create a new minified and gzip files.

We use this WP Rocket settings:
- Minify JavaScript files (enable)
- Cache Lifespan (30 days)
- Active Preloading (enable)
- Not using add-ons and CDN

**To Reproduce**
1. Go to 'wp-content/cache/min/1/wp-content/themes/mywebsite/js'
2. Delete both minified and gzip files

**Expected behavior**
There should be files with the new updated minified and gzip files

**Comment by piotrbak** [comment]
Hello @winardi-morefire thanks for creating the issue.

This is actually expected, you need to visit specific URL for WP Rocket to generate all assets that are needed for its display. I'd suggest not removing manually any of the files, rather use built-in functionalities:
https://docs.wp-rocket.me/article/1135-when-does-wp-rocket-delete-which-files

**Comment by winardi-morefire** [comment]
Hi @piotrbak, thank you for your fast respond. If I manually triggering of Clear Cache (from the WP Rocket admin toolbar, or WP Rocket Dashboard tab), did it make the file to be 404 (not found)? And If I update the existing JavaScript files, how long supposed WP Rocket scheduler until it generate the new minified and gzip files?

**Comment by piotrbak** [comment]
The files will be regenerated when visiting the specific URL. The only possibility to have 404 is while having not synchronised Varnish or other layer of cache.

If that's happening, please check our docs or contact our support team.
