### ISSUE TITLE
Error code when RUCSS API can't be reached

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6289]
**Context**
Related to this GH issue: https://github.com/wp-media/wp-rocket/issues/6222
QA team notices that part of the specification was missing in [this thread](https://wp-media.slack.com/archives/CUT7FLHF1/p1700747827387389): if the API can't be reached (not responding, timeout, ...) and that we don't have an HTTP answer, it is not clear how the plugin behaves. For instance, see [this possible issue](https://wp-media.slack.com/archives/CUT7FLHF1/p1700752455087559).
This means that we don't know exactly what happens in case the API can't be reached and we would not be able to identify the issue when debugging a user for instance.

**Expected behavior**
As mentioned in this [GH issue](https://github.com/wp-media/wp-rocket/issues/6222), we would need a specific error_code and/or error_message to be stored into the RUCSS table in the DB, in case the API can't be reached.

**Acceptance Criteria**
- If the API can be reached (normal case) there is no change of behavior (see https://github.com/wp-media/wp-rocket/issues/6222)
- Have a pending entry in RUCSS table. Disconnect from the internet or prevent the "fetch result" call to reach the API. Once the fetch has been tried, check the RUCSS table. The specific error_code and/or message should be registered for this job.

**Comment by CrochetFeve0251** [comment]
## Root cause
The root cause is due to the fact WordPress returning an empty response when not reaching the endpoint.

## Scope a solution
A simple solution would be to add a default error message when we are getting a empty result at this level inside [the client](https://github.com/wp-media/wp-rocket/blob/89d66aa96e926b873a3b07ca5b6c55cf5647f759/inc/Engine/Optimization/RUCSS/AbstractAPIClient.php#L128).

## Estimate effort
Effort `XS`

**Comment by MathieuLamiot** [comment]
@CrochetFeve0251 Sounds good for the error message. 

About the error code, it is handled just above it seems: https://github.com/wp-media/wp-rocket/blob/89d66aa96e926b873a3b07ca5b6c55cf5647f759/inc/Engine/Optimization/RUCSS/AbstractAPIClient.php#L121

What I am afraid of is that sometime, the HTTP Response code returned here could match one of the code we use within the payload. For instance, the HTTP Response code could be 408 because of API timeout. We would store a error_code 408 in the RUCSS DB and trigger the retry mechanism, which is not what we want. To make sure we don't have conflict, WDYT of something like:
In the API client, if HTTP Response Code != 200, then force 
- $this->response_code to 504 (or another value that you see fit)
- $this->error_message = "API Client Error: " .  
                                              is_array( $response )? wp_remote_retrieve_response_code( $response ): $response->get_error_code() .
                           
				is_array( $response )
				? wp_remote_retrieve_response_message( $response )
				: $response->get_error_message();

This would avoid collision on "code" stored in the RUCSS DB + to keep the complete information for debug purposes.

**Comment by MathieuLamiot** [comment]
After discussion with @CrochetFeve0251, we will keep this fix here very simple and not tackle the HTTP code / RUCSS code collision in this issue. As a result, the proposed solution is OK.
https://github.com/wp-media/wp-rocket/issues/6293
