### ISSUE TITLE
Refine the RUCSS retry strategy for edge-cases of the backoff retries

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6290]
**Context**
Based on [this GH issue](https://github.com/wp-media/wp-rocket/issues/6222), and from feedbacks from [this thread](https://wp-media.slack.com/archives/CUT7FLHF1/p1700747827387389), some enhancements have been identified: compelted jobs are kept 30 minutes on the SaaS and the very last interval of retries in the plugin is 30 minutes. This means a very bad timing could lead to miss the result.

**Expected behavior**
- For [the very last retry of the backoff retry strategy](https://github.com/wp-media/wp-rocket/blob/89d66aa96e926b873a3b07ca5b6c55cf5647f759/inc/Engine/Optimization/RUCSS/Strategy/Strategies/DefaultProcess.php#L37), it should be set to something lower than 30 minutes so that bad timing can't happen. Taking into account some ActionScheduler and Cron latency, 25 minutes is probably a good candidate.

**Comment by MathieuLamiot** [comment]
No grooming needed. This is a one-liner.

**Comment by MathieuLamiot** [comment]
@wp-media/qa-team Might not need tests. I'll let you advise :)

**Comment by vmanthos** [comment]
Given that the functionality is working with the previous value, I don't see any reason why it won't with the new one.

I'd say this should be approved and merged without further testing.
