### ISSUE TITLE
RUCSS Enabled But Still Some Errors on Google PageSpeed

### ISSUE THREAD

**Issue by AghaFarokh** [wp-media/wp-rocket#6291]
Hi Dear
sorry for this issue, I've searched a lot but couldn't find something so I'm writing this right now
I'm using WP Rocket Version 3.13.3 and have this problem since from first that I've using WP Rocket
I've enabled RUCSS, nothing has been excluded, and checked the cron jobs are running successfully, everything is working fine on my website but the errors 1. Eliminate render-blocking resources and 2. Reduce unused CSS are still in my pagespeed results
I've tried many settings but coulnd't fix this this errors
that was my last hope to ask about this problem from the developers
thank you in advance

**Comment by piotrbak** [comment]
Hello @AghaFarokh thanks for the contact. That sounds more like a Support enquiry. Please reach our amazing team here, they'll be more than happy to assist you:
https://wp-rocket.me/support/
