### ISSUE TITLE
Translate press compatibility issue with Lazyload BG image while using relative URL 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6296]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling LL BG Image with Translate press 2.6.7, a relative URL is written to domain/lang  which results in 404

**To Reproduce**
1. Translate press 2.6.7 enabled (having 2 languages)
2. Page template with relative URL i.e https://rocketlabsqa.ovh/ll-bg/ has 
`  .internal-css-background-image0{
            width: 100%;
            height: 400px;
            background-image: url("/wp-content/rocket-test-data/images/test_internal0.webp");
            background-color: #cccccc;
        }`
3. Enable LL BG image then Open the page template incognito
4. Check console and page UI => some images are not displayed giving 404 in the console
The Url became `url('https://rocketlabsqa.ovh/en/wp-content/rocket-test-data/images/test_internal0.webp')` while the valid URL is `https://rocketlabsqa.ovh/wp-content/rocket-test-data/images/test_internal0.webp`

**Expected behavior**
All images are displayed correctly with relative/absolute URL without console error

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
