### ISSUE TITLE
WPML console error when switch language after change WPML setup while WPR is enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6297]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When switching language on FE for cached pages after changing the WPML setup, a console error will be there.

**To Reproduce**
1- WPML is domain base (2 languages are there), WPR enabled
2- cache the page (page template containing bg images) in both languages i.e https://rocketlabsqa.ovh/ll-bg/
3- WPML changed to a directory
4- access the main language page and click on language switch to sub-lang => console error

**Expected behavior**
No console error when switching language and language switched successfully

**Screenshots**
[screen-capture (70).webm](https://github.com/wp-media/wp-rocket/assets/76941962/54b76793-dd0c-4a62-8a5a-0eb913be6733)
![Screenshot from 2023-11-29 09-26-33](https://github.com/wp-media/wp-rocket/assets/76941962/b31d053a-b94b-4b0a-bf6a-884126744fe1)

**Additional context**
- if we clear the cache and then repeat step 4, it will work fine so may be we just need to clear the cache when changing the WPML setup. @piotrbak what do you think?
- The same is happening even if LL BGI is disabled

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
