### ISSUE TITLE
Exluding classes from USED CSS wpr-usedcss

### ISSUE THREAD

**Issue by lukapaunovic** [wp-media/wp-rocket#6298]
I do not know am I missing something.

<img width="673" alt="Screenshot 2023-11-29 at 11 33 37" src="https://github.com/wp-media/wp-rocket/assets/23408913/0400ff4f-fa0f-4c73-bcc0-edc5f3685c9d">

I have excluded from both features:

<img width="627" alt="Screenshot 2023-11-29 at 11 34 00" src="https://github.com/wp-media/wp-rocket/assets/23408913/1b4c6da5-ee05-442f-aa7a-f410840337f2">

This is untouched code from the page (uncached):

`<a href="https://www.mysite.hr/zdravlje/kumkvat-uzgoj-8-zdravstvenih-prednosti/" rel="bookmark" class="td-image-wrap " title="Kumkvat – 8 zdravstvenih dobrobiti čudesnog voća">
                                        <style>@media only screen and (min-device-pixel-ratio:1.5),only screen and (min-resolution:192dpi){.td-thumb-css.tdi_81{background-image:url("https://www.mysite.hr/wp-content/uploads/2023/11/kumkvat.jpg")!important}}</style>
                                    <span class="entry-thumb td-thumb-css tdi_81" style="background-image: url('https://www.mysite.hr/wp-content/uploads/2023/11/kumkvat.jpg')"></span></a>`

After WP Rocket "does its thing" i am left with <style></style>
and CSS is aggregated inside <style id="wpr-usedcss">

So there is no feature to exclude USED css from aggregation?

**Comment by piotrbak** [comment]
Hello @lukapaunovic thanks for creating the issue, it looks like a support request though. As far as I understand you want to leave CSS files or content of the style tags untouched. Please refer to this documentation articles:
https://docs.wp-rocket.me/article/1714-prevent-css-files-from-being-removed-by-remove-unused-css
https://docs.wp-rocket.me/article/1694-prevent-inline-styles-from-being-removed-by-remove-unused-css

If you need further help, please reach our Support Team.
