### ISSUE TITLE
Automatic config files regeneration when pushing from development to production environments

### ISSUE THREAD

**Issue by mviniciosbarreto** [wp-media/wp-rocket#6299]
**Is your feature request related to a problem? Please describe.**
In some host environments such as Kinsta, when a push is made from dev to prod environments, there's a dev container which is deployed which replaces the entire production container. WP Rocket still detects the change and trigger a notice for the configuration files regeneration, however, it requires some manual intervention, for example some WordPress admin dashboard activity.

**Describe the solution you'd like**
Instead of relying on some manual intervention, for such cases, it could be considered to trigger the regeneration automatically.

**Describe alternatives you've considered**
We considered some hooks from the Kinsta (or any similar host env) side. However, there's any PHP function called involved in the process.

**Additional context**
https://secure.helpscout.net/conversation/2415467183/453594?folderId=273766

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
