### ISSUE TITLE
Preload Fonts: installation subfolder name is stripped from URLs

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#6302]
When saving URLs to Preload Fonts, the domain name is stripped automatically -- but in the case of a subdirectory installation, the **subfolder name** is also being removed, which results in an invalid URL being preloaded on the front end.

1. Must have WordPress Site URL located in a subfolder, e.g., https://example.com/sub/
2. Need at least one font URL to test, e.g., https://example.com/sub/wp-content/themes/twentytwenty/assets/fonts/inter/Inter-upright-var.woff2
3. Add the URL to the _Preload Fonts_ field, then save the change.
4. See that the subfolder has also been removed from the URL:

<img width="529" alt="Screen Shot 2023-12-02 at 11 12 31 AM" src="https://github.com/wp-media/wp-rocket/assets/44367/0bab0471-4373-430f-b1f7-68643ab0f5cf">

5. On the front end, the domain will be added back, but not the subfolder:
 
`<link rel="preload" as="font" href="https://example.com/wp-content/themes/twentytwenty/assets/fonts/inter/Inter-upright-var.woff2" crossorigin>`

6. Thus, the font's URL is invalid and it cannot actually be preloaded.

Related: https://secure.helpscout.net/conversation/2438758491/461019/

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
