### ISSUE TITLE
Make sure that the used CSS is generated withing 90 seconds from enabling the RUCSS option

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6304]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When we were fixing this issue (#6282) we found that the success message that appear after 90 seconds from enabling the RUCSS option shows that the used CSS is generated for homepage but at this point we are not sure about it.

As agreed on the [slack discussion](https://wp-media.slack.com/archives/CUT7FLHF1/p1701701764925529?thread_ts=1701684109.350099&cid=CUT7FLHF1):

> once RUCSS is enabled, we will have a dedicated code to create the job for home page in SaaS and after the 90 seconds pass we will send ajax request to a dedicated code to check the status and save the used CSS and then show the success message.

**To Reproduce**
1. Go to WPR settings page
2. Disable CRON to make sure that the used css will not be generated (add `define( 'DISABLE_WP_CRON', true )` in `wp-config.php`)
3. Enable RUCSS or clear used CSS if RUCSS is already enabled.
4. Wait for 90 seconds (till the counter finishes)
5. You will see the success message but the used CSS is not generated for homepage as mentioned in the message.

**Expected behavior**
We need to make sure that used CSS is really generated before showing the success message.

**Additional context**
Slack discussion: https://wp-media.slack.com/archives/CUT7FLHF1/p1701684109350099

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
