### ISSUE TITLE
Possible conflict with Page Optimize

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6308]
Task submitted by camila through TBTT.

**Description of the issue:**
Page Optimize plugin forces the deactivation of WP Rocket.

As soon as both plugins are active, WP Rocket's deactivation pop-up will be displayed, forcing users to deactivate WP Rocket. Clicking on Cancel won't work (deactivation pop-up will be reloaded).

See: https://jmp.sh/jxmq3xWB.

**Investigation performed:**
On my test site, I installed Page Optimize, activated it, and that triggered the deactivation pop up.

**How to reproduce:**
Steps:
Install and activate Page Optimize while WP Rocket is active.

Helpscout link:https://secure.helpscout.net/conversation/2428849438/456437?folderId=2675957
Slack link:https://wp-media.slack.com/archives/C8L4EE8N9/p1700847677234489

**Comment by piotrbak** [comment]
@DahmaniAdame What do you think about this one? Not sure what approach we could take here.

**Comment by DahmaniAdame** [comment]
@piotrbak to avoid adding a compatibility file on our side, we can add a PR to their `page_optimize_css_exclude_list_default` to add `wpr-modal`. 

https://github.com/Automattic/page-optimize/blob/82e97904c14f0fc113720f8adef33602475cd66c/page-optimize.php#L170-L174

**Comment by wordpressfan** [comment]
I don't think that this repo is active enough to check our PR there, I can see some issues/PRs there for years.
but we can try.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
