### ISSUE TITLE
String update: “Cloudflare’s integration requires PHP …”

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#631]
https://github.com/wp-media/wp-rocket/blob/0d60c8e91e916a5652fc3607b13ee411a85e4839/inc/admin/ui/modules/cdn.php#L24

Feedback from a translating volunteer on Transifex: 
> This string is kind of confusing, it informs that my PHP is lower than 5.4 and I need 5.6. I believe it should say “Your PHP version is lower than 5.6 …”

In fact, Cloudflare’s minimum requirement is PHP 5.4 here (which is also what we check for), so the string should be modified into this:

```php
'description' => __( 'Your PHP version is lower than 5.4. Cloudflare’s integration requires PHP 5.4 or greater and therefore is not available for you currently. We recommend you contact your web host in order to upgrade to a PHP 5.4 or greater.', 'rocket' ),
```

**Comment by glueckpress** [comment]
It still says:
> contact your web host in order to upgrade to a *PHP 5.6* or greater.

Should say:
> contact your web host in order to upgrade to a *PHP 5.4* or greater.

**Comment by Tabrisrp** [comment]
recommending to upgrade to at least PHP 5.6 is in fact a conscious choice. We don't want people to _just_ upgrade to 5.4 since it's old and unsupported.

**Comment by glueckpress** [comment]
Ay, in that case we should reword the string, though. Referring to a min requirement of 5.4, and then recommending 5.6 will come across confusing.

How about this?

> Your PHP version is lower than 5.4. Cloudflare’s integration requires PHP 5.4 or greater and therefore is not available for you currently. We recommend you contact your web host in order to upgrade to the latest PHP version.
