### ISSUE TITLE
Update DelayJS to 1.2.5

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6310]
The DelayJS version is available on the develop branch here: https://github.com/wp-media/delay-javascript-loading/tree/develop
This version should be added into WP Rocket.

The version contains these 3 fixes (+introduces Playwright automated tests):
[#104](https://github.com/wp-media/delay-javascript-loading/pull/104): Fix window onload and pageshow order
[#106](https://github.com/wp-media/delay-javascript-loading/pull/106): Fix for some double click issues
[#107](https://github.com/wp-media/delay-javascript-loading/pull/107): Compatibility with the CookieYes banner

Those individual PRs are also provided added to the board for QA to review them individually.

(cc @piotrbak)

**Comment by Mai-Saad** [comment]
waiting feedback on slack thread https://wp-media.slack.com/archives/CUT7FLHF1/p1703582813727789

**Comment by MathieuLamiot** [comment]
Missing parts of the code reported by @piotrbak : being investigate with @jeawhanlee -> Could be explaining the behavior issue
