### ISSUE TITLE
It's not possible to exclude the YouTube thumbnail from LazyLoad

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6312]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
It's not possible to exclude the YouTube thumbnail (applied with the **Replace YouTube iframe with preview image** feature) from the **LazyLoad for images**.

- This is not how the `LazyLoad` and `Excluded images or iframes` should work. 
- But it's really problematic when the YouTube thumbnail is the LCP element, because the LazyLoad triggers the `Preload Largest Contentful Paint image` audit of PageSpeed.

**To Reproduce**
1. Create a page with a YouTube video on the viewport.
2. Enable LazyLoad, LazyLoad for iframes and videos and Replace YouTube iframe with preview image features.
3. Try to exclude the thumbnail using the Excluded images or iframes box.
4. The thumbnail is still lazyloaded, even if you use `i.ytimg.com`, `hqdefault.jpg`.

In customer's case, the thumbnail is the LCP element and the is triggered.
**Screenshot:** https://jmp.sh/BCwtJlHz
**PageSpeed report:** https://pagespeed.web.dev/analysis/https-getgoally-com-blog-neurodiversopedia-neurotypical-vs-neurodivergent/e3l1k327s9?utm_source=psi&utm_medium=redirect&form_factor=mobile
**URL:** https://getgoally.com/blog/neurodiversopedia/neurotypical-vs-neurodivergent/
**Ticket:** https://secure.helpscout.net/conversation/2441540551/461496?folderId=2675957

**Expected behavior**
The thumbnail generated with the Replace YouTube iframe with preview image feature should be exclude-able from LazyLoad.

**Additional context**
**Slack thread:** https://wp-media.slack.com/archives/C43T1AYMQ/p1701812279936699

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by remyperona** [comment]
I'm not sure how we can handle this, the script generating the thumbnail is a dynamic one that will handle all Youtube videos on the page, so it's not possible to exclude a specific one. In the script there is no reference to the full thumbnail URL.

**Comment by vmanthos** [comment]
How about introducing a new `shouldReplaceYoutubeThumbnail()` method here:
https://github.com/wp-media/wp-rocket/blob/fb65f675bf69ba50e40918c57312e20dec0ddc87/inc/Dependencies/RocketLazyload/Iframe.php#L53

which would determine whether we'll `$this->replaceYoutubeThumbnail( $iframe )` or `continue` to `$this->replaceIframe( $iframe )`

For that, we'll need to introduce a new filter, e.g. `rocket_exclude_youtube_thumbnail_replacement` in a new `isYoutubeThumbnailExcluded()` method, which will accept the URL or array of YouTube video URLs we shouldn't add YouTube thumbs for, and bail-out early in the `replaceYoutubeThumbnail()` method.

That way it will be possible to:
1. Completely exclude a YouTube video from the lazyload feature using the exclusion text area in the UI.
2. Lazyload the `iframe` while not lazyloading the thumbnail using the filter.

It will also be possible to use the filter to prevent replacing the thumb of a YouTube video that is in the viewport (the SaaS should return this info) to avoid warnings related to lazyloading the LCP.

**Comment by remyperona** [comment]
We could do something like that yes, maybe using the ID instead of the URL (there is a number of different URL formats for youtube links). This would have to be done in the lazyload common library repository.

**Comment by markanthonybanong** [comment]
Hi guys thank you so much for working on this, I work for getgoally. We were wondering when, can we have this implemented?

**Comment by markanthonybanong** [comment]
hi guys what is the update on this?

**Comment by remyperona** [comment]
### Scope a solution ✅ 
#### In `RocketLazyload/Iframe` library
- Introduce a new method `is_youtube_excluded( $iframe )`, which will check if the `$iframe` contains one of the value of the array `rocket_lazyload_exclude_youtube_thumbnail`
- Use this method in `lazyloadIframes()`, to check it before using `replaceYoutubeThumbnail()`, fallback to the default iframe lazyload if excluded

- Update the dependency in WP Rocket

### Estimate the effort ✅
Effort [S]

**Comment by markanthonybanong** [comment]
Thank you so much for working on this, can you guys have a documentation on how to implement this feature.

**Comment by Miraeld** [comment]
Seems okay to me

**Comment by dancielos** [comment]
I understand the issue is already being worked on. 

So, anyway, thanks to [Google's update last December](https://developers.google.com/search/blog/2023/12/video-is-the-main-content), I assume more website owners, myself included, will place the videos above the fold. Hence, I believe this feature has become more crucial.

P.S. Thought this could be handy info for the WPRocket team.
