### ISSUE TITLE
import settings isnot working with themify builder plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6313]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.6
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
error is displayed at admin when importing settings while the Themify builder plugin is enabled

**To Reproduce**
1. Themify builder version 7.0.5 installed and activated
2. WPR activated
3. from tools -> import settings file => error displayed "Settings import failed: incorrect filetype."

**Expected behavior**
import Settings works successfully (applied and saved)  without any error 

**Screenshots**
![Screenshot from 2023-12-11 12-50-20](https://github.com/wp-media/wp-rocket/assets/76941962/da0e095e-cfc0-4f24-936d-09d60988f729)

**Additional context**
- tested on https://new.rocketlabsqa.ovh/
- if we disabled themify plugin, import will work successfully
- Slack discussion and technical root cause thanks to @wordpressfan https://wp-media.slack.com/archives/CUT7FLHF1/p1702289748615129?thread_ts=1702281311.365109&cid=CUT7FLHF1

> By default json is not in the allowed mime types, so we are adding it with [this filter](https://github.com/wp-media/wp-rocket/blob/c2172cab84abbd3dff54bf5ac07a77880867eaeb/inc/admin/admin.php#L413).
We have two main issues here:
First issue:
[Here](https://github.com/wp-media/wp-rocket/blob/c2172cab84abbd3dff54bf5ac07a77880867eaeb/inc/admin/admin.php#L409) we are using the function sanitize_file_name which uses the function get_allowed_mime_types inside it which applies the filter mime_types so we need to move the [previously mentioned callback](https://github.com/wp-media/wp-rocket/blob/c2172cab84abbd3dff54bf5ac07a77880867eaeb/inc/admin/admin.php#L413) above this line that calls sanitize_file_name function.
Second issue:
Conflict with Themify plugin when fileinfo extension is loaded.
[Here](https://plugins.trac.wordpress.org/browser/themify-builder/trunk/themify/themify-fw-filters.php#L14) they are registering the callback to the filter upload_mimes which is defined inside get_allowed_mime_types function which overrides our [previous filter](https://github.com/wp-media/wp-rocket/blob/c2172cab84abbd3dff54bf5ac07a77880867eaeb/inc/admin/admin.php#L413) because it runs after it.
Their code:
function themify_upload_json_mime_types( $existing_mime_types = array() ) {
    $existing_mime_types['json'] = extension_loaded( 'fileinfo' )?'text/plain':'application/json';
    return $existing_mime_types;
}
So if the fileinfo extension is loaded they change the application/json to be text/plain so this fails [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L3262-L3265) because the file type is application/json not text/plain.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
