### ISSUE TITLE
Used CSS won't be added to a page if there is a space in the closing title tag

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6320]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: 
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

We rely on detecting `</title>` to add the used CSS on a page:
https://github.com/wp-media/wp-rocket/blob/7c8869d237f5b50f9260d303546561280d962b7e/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L398-L399

If instead of `</title>` the theme adds `</title >`, which is still valid, we won't add the used CSS to the page.

That kind of scenario would be possible for themes that don't use `add_theme_support( 'title-tag' );` and are adding the `<title></title>` on their own, or for specific templates.

**To Reproduce**

1. Use the following template to create a page: https://github.com/wp-media/rocket-test-data/blob/master/templates/title_tag_with_space.php
2. Enable Remove Unused CSS.
3. Check the source code of the page.
4. Used CSS will be there but added after the `</title>` tag that was added by the theme, i.e. not after the template `</title >` tag that precedes it.

**Expected behavior**

We should be able to correctly append the used CSS to `</title >`

**Additional context**

This is an edge case and should prioritized as such.

**Acceptance Criteria (for WP Media team use only)**

Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
