### ISSUE TITLE
Is there a way to use Cloudflare "User API Tokens" instead of "Global API Tokens"?

### ISSUE THREAD

**Issue by secretwebmaster** [wp-media/wp-rocket#6327]
**Is your feature request related to a problem? Please describe.**
I saw the article on https://docs.wp-rocket.me/article/18-using-wp-rocket-with-cloudflare .It mentioned that "Note: the Cloudflare Add-on works only with the  Global API key, other [Cloudflare API tokens](https://developers.cloudflare.com/api/tokens/) are not supported."
Is there any way to use custom API Token that specific for one domain and retricted permissions?

Some of my wordpress sites have multiple admins but not every admin should have the access to the Cloudflare Global API Token. Having access to Global API means you could access other domains in the same Cloudflare account.

Here is a simplified example. Each domain is managed by me and another admin:
```
example1.com: Me and Admin1
example2.com: Me and Admin2
...
...
example100.com: Me and Admin100
```
All these domain use the same Global API Key but with a different Zone ID. Each Admin should only have access to the domain he managed. However, as Admin1, who manage example1.com, has the Global API Key. Then he can actually access example2.com and do anything he wants such as changing the DNS of example2.com.

**Describe the solution you'd like**
Allow usage of custom API Token or any other ways that could limit the access.

**Comment by piotrbak** [comment]
It's a duplicate of old issue:
https://github.com/wp-media/wp-rocket/issues/2366
