### ISSUE TITLE
Deprecate old hooks for RUCSS

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6329]
**Is your feature request related to a problem? Please describe.**
Deprecate old hooks used by RUCSS.

**Comment by MathieuLamiot** [comment]
@piotrbak Is this OK to proceed this way? Also, this might impact the support team and their tooling.

**Comment by piotrbak** [comment]
@MathieuLamiot @jeawhanlee Which hooks are we talking about here?

**Comment by CrochetFeve0251** [comment]
> @MathieuLamiot @jeawhanlee Which hooks are we talking about here?

@piotrbak all RUCSS hooks that where here to configure the queue are renamed to SaaS prefix which gonna break our customers configurations.

For example:
`rocket_rucss_pending_jobs_cron_interval`  -> `rocket_saas_pending_jobs_cron_interval`

**Comment by piotrbak** [comment]
@CrochetFeve0251 But deprecating them would mean that the currently used filters would still work, no?

**Comment by CrochetFeve0251** [comment]
> @piotrbak Is this OK to proceed this way? Also, this might impact the support team and their tooling.

@MathieuLamiot with the current implementation the support will be already impacted. This is here to reduce the impact

**Comment by MathieuLamiot** [comment]
@jeawhanlee @CrochetFeve0251 This is what I want to clarify here. We (@piotrbak and myself) don't have exact visibility on what the current implementation is, so we can't know what to prioritize and if there is an impact or not.
When seeing an issue like this one, without having more details or context, it just triggers an alert that something has to be clarified. So, what is the behavior with the current branch and what is the intent of this issue? Thanks

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 But deprecating them would mean that the currently used filters would still work, no?

@piotrbak yes now they are broken.
The idea is to add a bridge between old ones and new ones inside the deprecated folder in wpr and show a message in the log as we usually do so they will be working.

**Comment by piotrbak** [comment]
@CrochetFeve0251 @jeawhanlee @MathieuLamiot Support Team during the last year was slowing down the generation of RUCSS to prevent High CPU cases. We need to make sure that this is preserved.

**Comment by CrochetFeve0251** [comment]
> @jeawhanlee @CrochetFeve0251 This is what I want to clarify here. We (@piotrbak and myself) don't have exact visibility on what the current implementation is, so we can't know what to prioritize and if there is an impact or not.
> When seeing an issue like this one, without having more details or context, it just triggers an alert that something has to be clarified. So, what is the behavior with the current branch and what is the intent of this issue? Thanks

With the current branch old hooks are broken.
The intent from that issue is to make a link between old ones and new ones inside the deprecated part of wpr so the users configurations won't be broken.

**Comment by MathieuLamiot** [comment]
Thanks, then @piotrbak I think we'd have to warn the support team when preparing the release so that they can adapt their helper plugins at some point and have the correspondance for potential questions from users.

**Comment by MathieuLamiot** [comment]
Blocked by the ["add test" branch for the CRON/LCP refactor](https://github.com/wp-media/monies/issues/73). Should be back on track tomorrow:
First, let's complete the implementation of tests linked to CRON refactor for LCP/ATF. Then, tests for this issue can be added to the PR.

**Comment by MathieuLamiot** [comment]
Putting back this task to ToDo: To consider if needed or not for the new 3.16

**Comment by CrochetFeve0251** [comment]
@MathieuLamiot if we reuse the same code basis in the 3.16 as before this will be needed

**Comment by MathieuLamiot** [comment]
Bringing back to In Progress pending 
- Verification that everything has been covered as discussed here: https://wp-media.slack.com/archives/CUT7FLHF1/p1713595042938999
- list of hooks that have been set to deprecated and what is there replacement
