### ISSUE TITLE
The fetchpriority attribute isn't set for the LCP image

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6330]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: 
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

The following were tested with the https://github.com/wp-media/wp-rocket/pull/6324 PR.

The SaaS returns the full URL of the LCP's `src`. If the LCP image is added to the page using a relative URL, for example:
```html
 <img src="/wp-content/rocket-test-data/images/istockphoto-1184692500-612x612.webp"  class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" >
```
the following pattern will not pick it up:
https://github.com/wp-media/wp-rocket/blob/e7f95423e7cb5179b5ed9b5ea2723954fc658138/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L137

Even if a full URL is used, the RegEx still doesn't pick up the URL. Adding the `m` option fixes this:
```PHP
/<img[^>]*\s+src=[\'"]' . $url . '[\'"].+>$/m
```

**To Reproduce**

1. Use the following template to create a page: https://github.com/wp-media/rocket-test-data/blob/master/templates/lcp_no_fetchpriority.php
2. Have the SaaS find the LCP.
3. Check the source code of the processed page.
4. `fetchpriority="high"` will not be added to the LCP image.

**Expected behavior**

The RegEx should :
1. Pick LCP images that are added with relative URLs.
2. Pick LCP images that are added with full URLs.

**Screenshots**
N/A

**Additional context**
N/A

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by jeawhanlee** [comment]
@vmanthos I discovered this earlier while working on this [PR](https://github.com/wp-media/wp-rocket/pull/6307) and it's fixed there.

**Comment by jeawhanlee** [comment]
Can be tested with this [branch](https://github.com/wp-media/wp-rocket/tree/feature/lcp-above-the-fold-optimization)

**Comment by vmanthos** [comment]
@jeawhanlee Thank you for pointing me to the correct branch. I confirm that both issues are fixed there. :+1: 

I'll close the issue.

**Comment by Mai-Saad** [comment]
Can see LCP not found in database here although it's on [page speed](https://pagespeed.web.dev/analysis/https-new-rocketlabsqa-ovh-lcp_no_fetchpriority-2/uwwxk9r66m?form_factor=desktop) https://new.rocketlabsqa.ovh/lcp_no_fetchpriority-2 and here https://new.rocketlabsqa.ovh/lcp_no_dimensions_svg
