### ISSUE TITLE
The value of the pre-existing fetchpriority attirbute is ignored when preloading the LCP

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6332]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: Tested with the https://github.com/wp-media/wp-rocket/pull/6324 PR
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

We are setting the `fetchpriority` for the LCP in two places:
1. When preloading the LCP:
https://github.com/wp-media/wp-rocket/blob/e7f95423e7cb5179b5ed9b5ea2723954fc658138/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L214
2. To the LCP image's markup:
https://github.com/wp-media/wp-rocket/blob/e7f95423e7cb5179b5ed9b5ea2723954fc658138/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L146

While in the second case, we are checking and respecting any pre-existing `fetchpriority` value, we don't do the same for the first case. If the pre-existing value is one of `low`, `medium`, or `auto` we'll force the `high` value because of that being "hardcoded" in the `<link>` preload.

**To Reproduce**
1. Add an image with `fetchpriority="low"`.
4. Visit the page on the front end.
5. Check the priority of the image in the Network tab (Chrome Developer tools).
6. It will be `high`.

**Expected behavior**

We should respect the pre-existing value of the `fetchpriority` attribute. 

**Screenshots**

N/A

**Additional context**

@wp-media/productrocket Would it be useful to provide a filter to override respecting a pre-set `fetchpriority` value for the `<link>` preload?

I'm thinking of a case where a plugin or the theme is setting an incorrect value for the `fetchpriority` of the LCP image. With the current behavior (when the current issue is fixed), that image will be flagged in PSI. 

Although this wouldn't be coming from us and my suggestion sounds like fixing the mistake another party made, from a user's perspective it may be easier to override WP Rocket's default behavior and set the value to `high`. That could even be fine-grained per page using the filter and page-specific conditionals.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
@DahmaniAdame What do you think about that?

**Comment by DahmaniAdame** [comment]
@piotrbak @vmanthos yes, I agree. 

We should:
- Respect pre-existing values assuming they were put there for a reason
- Have a filter to override it to provide a quick fix for support/site owners to use when needed in case the value is counterproductive
