### ISSUE TITLE
Pages with LCP/ATF not found although it exists on PSI/view port

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6337]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After activating the plugin, preloading some pages. pages have LCP/ATF not found in the database although it is there on PSI

Example pages:
- https://new.rocketlabsqa.ovh/ => PSI https://pagespeed.web.dev/analysis/https-new-rocketlabsqa-ovh/x2km48yvrb?form_factor=desktop
- https://new.rocketlabsqa.ovh/lcp_video_poster_template/ => PSI https://pagespeed.web.dev/analysis/https-new-rocketlabsqa-ovh-lcp_video_poster_template/sizpsnap4l?form_factor=desktop **(Note: for this no ATF as well)**
- https://new.rocketlabsqa.ovh/lcp-single-colon => no above-the-fold images
- https://new.rocketlabsqa.ovh/lcp-double-colon => no above-the-fold images
- https://new.rocketlabsqa.ovh/revolution-slider/ => no above-the-fold images (for this one, revolution slider shall be active)

**Expected behavior**
LCP/ATF is added to the database, especially the image is displayed in our dimensions

**Screenshots**
![Screenshot from 2023-12-18 09-13-25](https://github.com/wp-media/wp-rocket/assets/76941962/4348387c-2645-46dd-87e5-4304d9f87e80)

**Additional context**
- Active theme 2021
- [Saas](https://github.com/wp-media/nodejs-treeshaker/commit/fc9d9d62d9cac9dc6de01e9dd89e051d1ab9386d) commit fc9d9d62d9cac9dc6de01e9dd89e051d1ab9386d
- [PR](https://github.com/wp-media/wp-rocket/tree/feature/lcp-above-the-fold-optimization)  commit a8bef5a29ee49a0b499ba24174a16300b0cd5c37 

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Mai-Saad** [comment]
using 2017 theme on newlabs, images not having ATF also it exists in the viewport
![Screenshot from 2023-12-19 22-06-41](https://github.com/wp-media/wp-rocket/assets/76941962/a48f11c6-0fc6-42d0-97e3-b7bb51a283eb)
![Screenshot from 2023-12-19 22-14-36](https://github.com/wp-media/wp-rocket/assets/76941962/42b20632-7686-4c3a-8a5a-a7e708fd6994)
active plugins
![Screenshot from 2023-12-19 22-16-25](https://github.com/wp-media/wp-rocket/assets/76941962/bf4db499-b945-4297-a3cf-88d6b9415259)

PR commit 32b2a5c8fec1eb500a9ef08457e6c68cfb62a8cc

**Comment by Mai-Saad** [comment]
on commit `17130382feb3d706586415e9f35f19b8ae51c01f` of saas, this PR has no LCP although it exists on page speed while the theme is BeOnePage

**Comment by piotrbak** [comment]
Closing it, since it was related to the old version of the feature
