### ISSUE TITLE
Minification strips some custom url parameters

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#634]
original: https://freeyork.org/wp-content/uploads/dynamic-style.css?respondjs=no&#038;ver=5.2.4
minified: https://freeyork.org/wp-content/cache/min/1/wp-content/uploads/dynamic-style.css?respondjs=no&

**Comment by webtrainingwheels** [comment]
Also affecting Divi Booster plugin.

**Comment by danmossop** [comment]
Hi webtrainingwheels,

I've patched the upcoming version of Divi Booster (2.6.6) so that it shouldn't be affected by this any longer. It doesn't solve the issue in WP rocket itself, of course. 

Thanks,
Dan (author of Divi Booster)

**Comment by Tabrisrp** [comment]
In 2.11.2 the query string will be removed completely to prevent any issue. If the file really requires one of the parameter, the best action will be to exclude it from minification.
