### ISSUE TITLE
Conflict between WebToffee Cookie Consent plugin and WP Rocket 3.15.5 and later

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6343]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
User is getting this error when trying to enable WP Rocket 3.15.5 or later.

```
[15-Dec-2023 18:04:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function rocket_is_importing() in /home/zannierp/public_html/wp-content/plugins/wp-rocket/inc/functions/files.php:806
Stack trace:
#0 /home/zannierp/public_html/wp-content/plugins/webtoffee-gdpr-cookie-consent/third-party/scripts/wp-rocket/wp-rocket.php(81): rocket_clean_domain()
#1 /home/zannierp/public_html/wp-content/plugins/webtoffee-gdpr-cookie-consent/third-party/scripts/wp-rocket/wp-rocket.php(40): Cookie_Law_Info_Wp_Rocket::flush_rocket_data()
#2 /home/zannierp/public_html/wp-includes/class-wp-hook.php(324): Cookie_Law_Info_Wp_Rocket::activator()
#3 /home/zannierp/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /home/zannierp/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/zannierp/public_html/wp-admin/includes/plugin.php(693): do_action()
#6 /home/zannierp/public_html/wp-admin/plugins.php(58): activate_plugin()
#7 {main}
  thrown in /home/zannierp/public_html/wp-content/plugins/wp-rocket/inc/functions/files.php on line 806
```

The error seems to occur here:
https://github.com/wp-media/wp-rocket/blob/610a225799002c6bc3747db2f54cb7fbb0075ae9/inc/functions/files.php#L806

It seems to be a conflict with the [WebToffee Cookie Consent Plugin](https://www.webtoffee.com/product/gdpr-cookie-consent/).

And seems to be related to their code meant for compatibility with WP Rocket:

Ahmed said it seems like the problem happens while activating the cookie plugin because of this line:

`add_action('activate_wp-rocket/wp-rocket.php',array(__CLASS__,'activator'),11);`

Because the api.php file is not loaded with our activation.

He said the fix could be to load the api.php file here:
https://github.com/wp-media/wp-rocket/blob/7655b4dbdf2a5e50c63c54f5431359cc588e55d1/inc/Engine/Activation/Activation.php#L66

**To Reproduce**
1. Make sure the WebToffee Cookie Consent plugin is activated
2. Try to install WP Rocket version 3.15.5 or later. WP Rocket won't activate and the error above will be logged.

**Expected behavior**
WP Rocket should activate with no issue.

**Additional context**
https://wp-media.slack.com/archives/C43T1AYMQ/p1702673250105519
https://secure.helpscout.net/conversation/2452550268/463643

**Acceptance Criteria (for WP Media team use only)**
1. No fatal error when enabling WP Rocket if the related plugin is already enabled
2. No regressions in the compatibility with the plugin
3. No regressions in the compatibility with WPAI plugin, the import still shouldn't clear the cache.

**Comment by joejoe04** [comment]
The temporary fix is to disable the Cookie Consent plugin, activate WP Rocket, then re-activate Cookie Consent. The error only occurs during attempts to activate WP Rocket.

**Comment by Miraeld** [comment]
## Reproduce the problem
To reproduce the issue, we can install the plugin [WebToffee Cookie Consent Plugin](https://www.webtoffee.com/product/gdpr-cookie-consent/) but as it is a paid plugin, we can add this line within the `function.php` of the plugin:
```php
add_action('activate_wp-rocket/wp-rocket.php', function() {
    rocket_clean_domain();
},11);
```

Once done, if we activate the plugin wp-rocket, we will get a fatal error: 
```
[02-Jan-2024 08:47:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function rocket_is_importing() in /var/www/html/wp-content/plugins/wp-rocket/inc/functions/files.php:806
Stack trace:
#0 /var/www/html/wp-content/themes/twentytwentyfour/functions.php(209): rocket_clean_domain()
#1 /var/www/html/wp-includes/class-wp-hook.php(324): {closure}(false)
#2 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/html/wp-admin/includes/plugin.php(693): do_action('activate_wp-roc...', false)
#5 /var/www/html/wp-admin/plugins.php(58): activate_plugin('wp-rocket/wp-ro...', 'http://localhos...', false)
#6 {main}
  thrown in /var/www/html/wp-content/plugins/wp-rocket/inc/functions/files.php on line 806

```

## Identify the root cause
The issue is that, as mentioned in the original issue, we are calling a function which isn't included. 

## Scope a solution
To solve the issue, we must add `require WP_ROCKET_FUNCTIONS_PATH . 'api.php';`  here https://github.com/wp-media/wp-rocket/blob/7655b4dbdf2a5e50c63c54f5431359cc588e55d1/inc/Engine/Activation/Activation.php#L66


## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

**Comment by jeawhanlee** [comment]
Looks Ok to me
