### ISSUE TITLE
WProcket breaking AddSauce.com embed

### ISSUE THREAD

**Issue by mrjamesriley** [wp-media/wp-rocket#6348]
Hello all, I've created this PR here: https://github.com/wp-media/wp-rocket/pull/6292 3 weeks ago, to exclude addsauce.com from being impacted by WProcket, as we had done previously for when we were previously using the snapppt.com domain. Is there anything else needed in order to have this seen and actioned by someone? Would appreciate it being looked at, as it's impacted a few of our clients. Many thanks.

The PR: https://github.com/wp-media/wp-rocket/pull/6292

**Comment by piotrbak** [comment]
@mrjamesriley Thank for creating the issue. We're not editing the JSON files manually, it's being generated automatically.

Could you use share URL where we could see your scripts in action? Then we'll add the exclusion on our own.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
