### ISSUE TITLE
No replacement for PHP Function rocket_lazyload_images

### ISSUE THREAD

**Issue by inred-froehlich** [wp-media/wp-rocket#6350]
The PHP function rocket_lazyload_images is deprecated since version 3.3, there is currently no replacement function or static method.
The method \RocketLazyload\Images::lazyloadImages() is not available.

**Comment by piotrbak** [comment]
Thanks for creating the issue.

@wp-media/engineering-team What do you think about this request?

**Comment by wordpressfan** [comment]
I don't know the context that you need applying this method id but I think you have HTML that you need to apply lazyload on the found images there, correct?

If this is the case, Can u try the following:

```
function rocket_helper_apply_lazyload( $html ) {
    $rocket_container = apply_filters( 'rocket_container', [] );
    if ( empty( $rocket_container ) ) {
        return $html;
    }
    $lazyload_subscriber = $rocket_container->get( 'lazyload_subscriber' );
    if ( empty( $lazyload_subscriber ) ) {
        return $html;
    }
    return $lazyload_subscriber->lazyload( $html );
}
```

after declaring this, you can use it like:
```
$lazyloaded_html = rocket_helper_apply_lazyload( $html );
```

Plz don't use in production till you validate/test it in a dev/staging environment.

**Comment by piotrbak** [comment]
@inred-froehlich Does it answer your concerns?

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
