### ISSUE TITLE
Purging cache from post/page editor redirects to posts/pages list when using Avada builder

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#6352]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The issue is the same as this one - https://github.com/wp-media/wp-rocket/issues/6301
But occurring when using Avada. 

**To Reproduce**
1. Can be reproduced on our Avada test site
2. Go to the edit screen for a post
3. Click "Clear this post"
4. You will be redirected to the All Posts page, instead of staying on the edit screen for the specific post. 

**Expected behavior**
You should stay on the edit screen

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://jmp.sh/FfJBvyez)

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2463738851/465679?folderId=377611
Reproduced issue on version 3.15.6 of WP Rocket
doesn't happen with 3.14.4.2

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
