### ISSUE TITLE
Lazyload background CSS compatibility with Firefox and Safari 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6353]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Multiple console errors are displayed for 404 image when using Firefox or Safari 17

**To Reproduce**
1. Using page template with 404 image https://github.com/wp-media/rocket-test-data/blob/master/templates/lazyload_css_background_images.php
2. Enable LLBG image
3. Visit the page template in FE https://new.rocketlabsqa.ovh/new-ll-bg-images using Firefox or Safari 17
4. scroll in the page while the console is open

**Expected behavior**
Same console error as for nowprocket (single error for 404 image)

**Screenshots**
![Screenshot from 2024-01-01 12-05-28](https://github.com/wp-media/wp-rocket/assets/76941962/cd2eafc8-2b77-41bb-92f9-d24ba4cb4e5b)

**Additional context**
- Removing CSS using attributes as mentioned [here](https://github.com/wp-media/wp-rocket/pull/6300#issuecomment-1867697829), will fix the issue on Firefox but not on Safari

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
