### ISSUE TITLE
Add tests for RUCSS CRON Refactor

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6354]
Add automated tests for RUCSS API & CRON Refactor.

**Comment by MathieuLamiot** [comment]
Should be done by tomorrow.

**Comment by MathieuLamiot** [comment]
More tests than expected: End of week

**Comment by MathieuLamiot** [comment]
Putting back this task to ToDo: To consider if needed or not for the new 3.16
