### ISSUE TITLE
Unique UserAgent request

### ISSUE THREAD

**Issue by mgithb** [wp-media/wp-rocket#6359]
**Is your feature request related to a problem? Please describe.**
It would be nice to distinguish WP Rocket bots by UserAgent mark.

**Describe the solution you'd like**
If there is a certain string that a bot always include in WP Rocket set of tools for external requests, it would be nice to have one described in some public article.

**Describe alternatives you've considered**
wprocketbot doesn't appear to be the only one

**Additional context**
In combination with the list of IPs, the presence of UserAgent allows to pass such traffic by WAF

**Comment by piotrbak** [comment]
@mgithb Thanks for creating this issue. We're handling this in internal repository of our SaaS service. We're currently testing the impact, thanks.
