### ISSUE TITLE
As a QA Engineer, I want random and temporary fatal error related to deleting or upgrading the plugins not to be breaking automated E2E tests so that I can use the tool for smoke tests

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6361]
**Context**

The QA team sometimes report random and temporary errors during smoke tests right after deletion or upgrade of the plugin. They have been investigated and are not causing issues so they were simply discarded during manual tests. However, this prevents automated E2E tests to be validated in a replicable way.
Those errors appear more with automated tests.

**Expected behavior**
We must handle those errors in the plugin or, if too complicated, in the E2E test tool so that they don't make tests fail.

**Acceptance Criteria**
Run E2E smoke tests with the tool several times, they should always pass.

**Examples**
https://wp-media.slack.com/archives/CUT7FLHF1/p1701855031212929

**Comment by wordpressfan** [comment]
I tried to reproduce the issue 3 times but still can't see it:

![image](https://github.com/wp-media/wp-rocket/assets/146129302/ec05c5db-1dd4-447d-a7d8-44a36cd03e9c)

I'm using https://e2e.rocketlabsqa.ovh/ as a live site.

@Mai-Saad do u still see this issue?
