### ISSUE TITLE
WP Rocket "Minify JS" breaks Amelia Step Booking for logged-off visitors only

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#6379]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When you enable Minify JS in WP Rocket, the Amelia Step Booking (v2) doesn't load anymore.

**To Reproduce**
1. Install Amelia Enterprise
2. Add Step Booking (v2) in a Page
3. Enable WP Rocket Minify JS
4. Plugin won't load in frontend as logged-off visitors.

**Expected behavior**
WP Rocket Minify JS shouldn't break the Amelia plugin for logged-off visitors.

**Screenshots**
/

**Additional context**
/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by StenderIternum** [comment]
Also stops working if you Delay JS execution.

**Comment by piotrbak** [comment]
@JerissCloudCenter @StenderIternum please contact our Support Team in order to find the correct exclusions. We'll then make them added to the core.
