### ISSUE TITLE
Review uses of WP_Query and consider using no_found_rows , update_post_term_cache and update_post_meta_cache to speed up processing and reduce SQL workload

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6392]
**Context**
A user suggested the following through the Support: 

> Your query on line 245 of /inc/functions/posts.php can be made 5-10x faster with no_found_rows => true being added. Since you are no totals needed or pagination occurring you will skip the expensive SQL_CALC_FOUND_ROWS that query translates to.

Referring to [this](https://github.com/wp-media/wp-rocket/blob/dc721cd3cda91bae2d483345f6c231e32730a4ff/inc/functions/posts.php#L82C11-L82C31)

The use of WP Query implies a few steps on top of the query requested. More details [here](https://wordpress.stackexchange.com/questions/315369/is-no-found-rows-a-silver-bullet-for-wp-query-optimization-when-getting-all-po).

**To do**
Review our usage (at least the main ones) of WP Query and consider the use of the following option: no_found_rows, update_post_term_cache and update_post_meta_cache

**Comment by MathieuLamiot** [comment]
Reported [here](https://wp-media.slack.com/archives/C43T1AYMQ/p1704899422341579). @Tabrisrp to have a second look 🙏

**Comment by remyperona** [comment]
Adding those make sense in this case, We are doing a query to get the ID of a single post, and don't need anything else.

This is the only case where we do a direct WP_Query in the code.
