### ISSUE TITLE
Change the Image Optimization Comparison Link in the Image Optimization Tab

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6393]
User reports that it's confusing that we link to a page that is very similar in name to Imagify (Imagely) in the Image Optimization Tab here:
https://www.imagely.com/image-optimization-plugin-comparison/

![image](https://github.com/wp-media/wp-rocket/assets/45705494/05d69fde-c6f7-483a-ad35-fc8c9097718a)

They say this almost caused them to accidentally subscribe to Imagely instead of Imagify.

To avoid any possible confusion, we could instead link to Imagify's comparison page here:
https://imagify.io/blog/best-image-compression-plugins/

If we'd prefer to use an independent or unbiased review, we could also find another one that has a name more distinct from Imagify.

Ticket:
https://secure.helpscout.net/conversation/2481790175/469310

Slack Discussion:
https://wp-media.slack.com/archives/C08N8J6VC/p1705584341114959

**Comment by remyperona** [comment]
@Miraeld You moved it to review, but there is no grooming nor PR?

**Comment by Miraeld** [comment]
## Scope a solution
To change the link we should modify it here:
https://github.com/wp-media/wp-rocket/blob/58b612d1a808917f2abc6e393f061026bdfb3ad7/views/settings/page-sections/imagify.php#L29

Here we can change it for https://imagify.io/blog/best-image-compression-plugins/ or any other link. 


## Effort estimation: 
XS
## Can be peer-coded: 
No
## Is a refactor needed in that part of the codebase?
No

**Comment by wordpressfan** [comment]
That's XS, I'll set it as `Good first issue`
