### ISSUE TITLE
Deleting all cache in draft save and Deleting all navigation pages when comment is approved

### ISSUE THREAD

**Issue by gevv** [wp-media/wp-rocket#6410]
Hi,

1- A new post is saved as a draft and all cache is cleared. (My setting; Cache Expiry 0-unlimited. )

2- Visitor comments are approved and all "site.com/page" pages are deleted.  Only the home or none of them page should be renewed (in my opinion)

**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
Thanks for creating the issue. Unfortunately, I wasn't able to recreate it, please contact our Support Team se we can investigate the problem and find the correct steps.
