### ISSUE TITLE
As a developer, I want to measure execution time of WP Rocket hooks so that I can identify bottlenecks and measure optimizations

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6414]
**Context**

In the effort to improve performances of the plugin at execution time, @wordpressfan suggested [here](https://wp-media.slack.com/archives/CUKB44GNN/p1706085299820819?thread_ts=1704908687.204569&cid=CUKB44GNN) to implement a systematic way to measure hook durations in debug mode.

We should think of a way to achieve this that could be easily included in the debut tools/helper plugins to have a quick way to spot issues and latencies root causes.

**Expected behavior**
- In debug mode, all WP Rocket hooks must have a profiling system measure: the execution time of each hook call, the number of times the hook is called.
- This system should be generic so that it is automatically applied to all hooks, even when a new one is implemented.

**Acceptance Criteria**
- When running without debug mode, nothing should be altered in the behavior of the plugin.
- When running in debug mode, after browsing a few uncached pages with WP Rocket activated, I must be able to retrieve the duration time and number of executions of all called hooks since the last reset.
- It must be possible to reset the data. It could be with a custom SQL script for instance, or deleting a given file, or included when clearing the cache for instance.

**Comment by MathieuLamiot** [comment]
@wp-media/engineering-plugin-team Here are some interesting findings: There is a plugin ([Debug Bar Slow Actions](https://wordpress.org/plugins/debug-bar-slow-actions/) ) that implements @wordpressfan's idea on Slack. You need to install Debug Bar as well and then for each page that you load as a logged user, you can access a panel like this with the most time-consuming actions:
![image](https://github.com/wp-media/wp-rocket/assets/15233030/3bd1fe17-af49-4428-b79d-19217b18e528)

The idea is quite simple: register a callback on all existing actions. This callback:
- starts a timer
- register another callback on the current filter with priority 9000.
This additional callback ends the timer and stores the data.

There are a few issues though:
- The Debug bar is accessible only for page loaded as a logged user. It prevents to observe `rocket_buffer` for instance. -> To fix this, we could store the output in a DB / a file rather than outputting it as HTML. This would also allow to measure time duration across several requests over time, including CRON jobs, etc. So, everytime the plugin is loaded, we would do the same thing as already done and, additionally, we would store the time data for each action (with a create or increment approach).
- The tool only keeps the 100 most time consuming actions. We could customize the sorting function to keep ~20 most consuming hooks with rocket in their name, and the other 80 most time-consuming hooks for instance.
- Some part of WP Rocket we want to measure don't have a dedicated action. For instance, rocket_buffer does, so that's great. But rocket_init() does not, hence we are not able to know how long rocket_init() itself takes. -> Would it make sense to rework a bit functions like rocket_init() by removing:

`add_action( 'plugins_loaded', 'rocket_init' );`

and adding:

```
function rocket_init_callback() {
	do_action( 'rocket_init_action' );
}
add_action( 'plugins_loaded', 'rocket_init_callback' );
add_action( 'rocket_init_action', 'rocket_init' );
```

I tested it and it allows the debug tool to measure rocket_init() execution time easily. @wordpressfan, @Tabrisrp, any inputs on this last point? We might want to do this only in debug mode 🤔

**Comment by remyperona** [comment]
It feels a bit like an awkward solution, but I don't see another way to be able to measure it independently.

**Comment by MathieuLamiot** [comment]
I tried something else that works well without having a weird action to introduce in WP Rocket. It adds more complexity on the debug tool but I prefer this than more complexity on WP Rocket.
Instead of encapsulating `rocket_init` in a dedicated action, I add the following `do_action` at the beginning of `rocket_init`:

```
function rocket_init() {
	// Nothing to do if autosave.
	if ( defined( 'DOING_AUTOSAVE' ) ) {
		return;
	}

	do_action( 'wp_rocket_before_load' );
```

Then, in the debug tool, I start a timer when `wp_rocket_before_load` action is called, and stop it when `wp_rocket_loaded` is called.

**Comment by piotrbak** [comment]
@MathieuLamiot This one can be closed, right?

**Comment by MathieuLamiot** [comment]
Correct, thanks. Closing it
