### ISSUE TITLE
LL CSS BG image isnot applied to images inside php styles (specific markup)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6417]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version=> 3.15.9
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using CSS BG image in php style, then enable LL image. those images won't be LL.

example:
`<link rel="stylesheet" id="dynamic_style" href="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/styles/dynamic_style_LLBG.php" media="all">
    <p  id="dynamic_style"> Image with dynamic style from php. vLorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut nulla ut lorem fringilla molestie ut non urna. Ut accumsan luctus lacinia. Praesent eleifend dolor leo. Ut erat risus, laoreet ac mi nec, varius efficitur sapien. In vitae sapien placerat,
     vestibulum ligula ac, vestibulum mi. Nulla eget scelerisque nisl.
      Aenean eu metus velit. Aliquam vel iaculis neque.</p>`

**To Reproduce**
1. Enable LL BG image
2. Visit page template containing the mentioned markup (below the fold)
3. Check page source and NW for images => images inside the PHP file arenot LL

**Expected behavior**
LL is applied to CSS BG images inside php file

**Screenshots**

**Additional context**
- This kind of markup will be LL
`
    <?php wp_enqueue_style('dymamic-php-styles',content_url()."/rocket-test-data/styles/dynamic_style_llbg2.php");
    wp_head() ?>`
- test page https://new.rocketlabsqa.ovh/llbgi-2024/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- LLCSS BG is applied to images inside PHP (both mentioned markup)
- Images in those markup can be excluded from LL using UI exclusion

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
