### ISSUE TITLE
LLBG isnot working probably with external PHP 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6421]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.9
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When LLBG image is enabled while having BG image inside an external PHP file, we will have a console error (file will be 403) and the related image(s) won't be displayed 

**To Reproduce**
1. Enable LL BG image
2. visit the page template with styles in the external PHP
i.e having this markup while page URL is rocketlabs or with multilingual ar.newlabs
```
<link rel="stylesheet" id="dynamic_style" href="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/styles/dynamic_style_LLBG.php" media="all">
    <p  id="dynamic_style"> Image with dynamic style from php. vLorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut nulla ut lorem fringilla molestie ut non urna. Ut accumsan luctus lacinia. Praesent eleifend dolor leo. Ut erat risus, </p>

```
**Expected behavior**
No console error and images are LL

**Screenshots**

**Additional context**
- Excluding the PHP file will fix the problem (no console error and related images displayed)
- Test page https://rocketlabsqa.ovh/llbg-2024/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
