### ISSUE TITLE
Non-WebP cache files arenot generated while using helper plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6423]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.8.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**To Reproduce**
1. Install/activate the following helper plugin: https://drive.google.com/uc?id=1JDqh9xV6zyLcD3OR_Njsxn8KW_PYGoac
2. Install and activate WPR
3. Clear the cache and preload it and once that finishes look in the /cache/wp-rocket/ folder for the URLs with WebP images.

**Expected behavior**
The Webp cached files should exist alongside the versions of the files that don't include WebP images.

**Screenshots**

**Additional context**
- It is working fine with WPR version 3.12.3 (generating both WebP and non WebP versions)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
