### ISSUE TITLE
AMP compatibility errors when activating WPR While WPML is active

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6425]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.9/ 3.15.8.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When activating WPR while AMP 2.5.2 is active (transitional mode)

**To Reproduce**
1. Activate AMP plugin 2.5.2
2. WPML is active (qs setup)
3. Activate WPR 
4.  Check Amp validation results

**Expected behavior**
No error for WPR with Amp (using different Amp setup)

**Screenshots**
3.15.9 after import settings
![After import settings](https://github.com/wp-media/wp-rocket/assets/76941962/1db90735-f8f1-46ed-aa3f-03d995942eff)
3.15.9 fresh activation
![fresh activation](https://github.com/wp-media/wp-rocket/assets/76941962/22538456-badf-4118-b4dd-8cedfae9295a)
3.14.4.2 after import settings
![3 14 4 2after import settings](https://github.com/wp-media/wp-rocket/assets/76941962/fd5c6e0a-29fa-4f01-8563-e61fc6dcf797)

**Additional context**
- Fresh activation is fine using WPR 3.14.4.2
- If we insert certain settings, and then reactivate WPR, we will have an error for the heartbeat (same error on 3.14.4.2)
- different setup of WPML needs to be checked

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- No error related to wpr with Amp (for different AMP setup i.e transitional, standard, reader => using fresh activation of WPR
- No error related to wpr with Amp (for different AMP setup i.e transitional, standard, reader => while all features on

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
