### ISSUE TITLE
3.16 - Inject beacon in the page

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket#6430]
### Context
As a Product team member, I want WP Rocket to inject a script when LCP/ATF information is missing on the page so that it can then identify those images. 
This issue has the goal to develop the blue part of this diagram:
<img width="1000" alt="Untitled" src="https://github.com/wp-media/wp-rocket/assets/14993267/17c2f11b-4ad8-4412-be14-bee89539d52d">

#### in `AboveTheFold\Frontend\Controller`
Update the [`lcp()`](https://github.com/wp-media/wp-rocket/blob/fcd6b467b45cd954b392f7cf7f728b94c42e0577/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L65) method to:
- check if the status is failed (in addition to the already existing checks)
- inject the beacon script in case  of no LCP data in the DB using a new method `inject_beacon()`
- The script needs to be added as an external script, in the footer, with an async attribute
- Update any related tests

### Acceptance Criteria
- Clear the LCP/ATF DB. Perform an uncached request. Check that the script is injected.
- Add valid/successful LCP/ATF data for a given page in the DB. Perform an uncached request to this page. Check that the script is not injected.
- Add LCP/ATF failed status for a given page in the DB. Perform an uncached request to this page. Check that the script is not injected.
From QA team:
- Check that the beacon script is a minified JS file.
- Check that the beacon script is excluded from WP Rocket JS optimizations.

###  Effort estimation:
Effort [S]

**Comment by MathieuLamiot** [comment]
From @Mai-Saad [here](https://www.notion.so/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?d=c799ac96fa6b45fc8de097e4e2f81fc0&pvs=4#4e4d9c1d3f694bd3941596ca1994c881): added the following AC, to be taken into account in the proposed solution: 
- Check that the beacon script is a minified JS file.
- Check that the beacon script is excluded from WP Rocket JS optimizations.

For this issue, a dummy script is enough. It does not need to perform any action. It could log something to ease testing for instance.
