### ISSUE TITLE
3.16 - Beacon script implementation

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket#6431]
## Context
As a user, I want WP Rocket to analyse and store LCP/ATF information of my pages so that those images can then be optimised. This issue has the goal to develop the green part of this diagram:
<img width="1000" alt="Untitled" src="https://github.com/wp-media/wp-rocket/assets/14993267/f3293d2c-4290-4369-9f15-c502631f33f1">

**Must be done after #6430 so that it can be tested**

## Scope a solution 
- To implement this, we need to create the beacon script in javascript that will run on pages to collect images.
- A prototype of the script can be found [here](https://gist.github.com/DahmaniAdame/038bdaa622313c8cde27ca60cb168924).
- The script can be created and placed [here](https://github.com/wp-media/wp-rocket/blob/3f7fa21018ff747a4c7ab90f18c37f1423e12f2b/src/js/global). 

The script needs to collect images of the page, and save them within the database through an AJAX call. 

If the script encounter an error, we should save it to the DB as well.

- Add a new Subdir `AJAX` with a controller and a subscriber
- The subscriber will have an event `wp_ajax_rocket_lcp`, with a callback `add_lcp_data()`
- The method will call the same named method in the controller
- This method will update the DB based on the result of the script (failed, error, no image, success), while performing security checks
- The controller will need to have a dependency with the DB query class to write in the table
- Add tests

## Acceptance Criteria
- Data is added to the DB once the AJAX call is made

##  Effort estimation:
 Effort [M]

**Comment by MathieuLamiot** [comment]
Some work is needed here on AC, to check with @Mai-Saad's [suggestion](https://www.notion.so/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?d=cbe4c7fc135e4a8eab8c8f451a1d698e&pvs=4#97cd585220bd43c0814fe0463185bbcf): 

> can be: save optimized images (all types mentioned above) to the database, if any error occurs i.e timeout, …etc, save the error in the database and start retries up to 3 then fail if the error is still there

**Comment by MathieuLamiot** [comment]
This issue includes security checks like SQL injection and payload size to avoid to big DB footprint.

**Comment by Mai-Saad** [comment]
smoke test is good here (security, different markups and error cases will be on different GH)
[testrail-report-592.pdf](https://github.com/wp-media/wp-rocket/files/15014850/testrail-report-592.pdf)
