### ISSUE TITLE
Apply missing dimensions to images on the query string version that will be visited by SaaS

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#6441]
#### `Engine\Media\ImageDimensions\Subscriber`
- Add a new callback method `start_buffer()` on `template_redirect` action (priority 3)
- The `start_buffer()` method will perform checks to validate if the buffering should start. This includes `is_admin()`, `is_preview()`, `REST_REQUEST`, and the presence of the query string `wpr_imagedimensions`. If everything pass, we can start the buffer with the following `ob_start( [ $this, 'specify_image_dimensions' ] );`. It will fall back to the existing method callback.
- Add tests

### Estimate the effort ✅
Effort `[S]`

**Comment by Miraeld** [comment]
Seems okay to me.

**Comment by MathieuLamiot** [comment]
Discussed here: https://wp-media.slack.com/archives/CUT7FLHF1/p1709822793531749
Bringing back to grooming for now to investigate if the PHP approach will cover all cases for the SaaS or not.
