### ISSUE TITLE
Compatibility with Nexcess plugin page caching

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6444]
**Is your feature request related to a problem? Please describe.**
The Nexcess plugin by [Nexcess hosting](https://www.nexcess.net/) has a `Page cache > Enable the site cache` option. This page caching is not synced at all with our page caching.

**Describe the solution you'd like**
To avoid issues, we can show a notice when it's active, deactivate WP Rocket's caching, etc.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2497847386/472527/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1707512690637129
Note: The plugin could also be available for Liquid Web hosted websites, as Nexcess is a Liquid Web brand, and I spotted there is a shared plugin (for sites migration) available in the WordPress repository.

**Comment by lukecav** [comment]
The Nexcess page cache has been phased out to go with W3 Total Cache. The Nexcess page cache used a forked version of the Cache Enabler plugin from KeyCDN.

It was only available for managed customers at Nexcess not for Liquid Web plans.

https://www.nexcess.net/help/how-to-use-the-nexcess-page-cache/
https://wordpress.org/plugins/cache-enabler/

**Comment by piotrbak** [comment]
It seems that it's not relevant anymore. Feel free to reopen otherwise
