### ISSUE TITLE
Double request is sent for video while LL video is on with Divi theme

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6450]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.15.9
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When LL video is enabled while active theme is divi, we send 2 requests while scrolling the page instead of 1 as on nowprocket

**To Reproduce**
1. Divi is activated
2. lazyload video is enabled at WPR
3. Access a page with video below the fold
4. Scroll while network tab is open

**Expected behavior**
Video related request is sent once as same as in nowprocket

**Screenshots**
![Screenshot from 2024-02-19 14-02-38](https://github.com/wp-media/wp-rocket/assets/76941962/85c7b8a9-eea2-41b1-8189-97f8d9a23403)

**Additional context**
- tested on rocketlabs https://rocketlabsqa.ovh/video-test/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
