### ISSUE TITLE
LL video - no focus on video moving with Tab if video below the fold

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6451]
WPR latest version  3.15.9 ✓

**Describe the bug**
When LazyLoad is enabled for videos only, using the Tab key to navigate a page won't focus on videos below the fold.

**To Reproduce**
1. On LazyLoad settings have "Enable for iframes and videos" checked 
2. Go to a page containing videos below the visible area
3. Use the Tab key to move between page elements
4. Notice that if videos are below the fold, using Tab won't get videos in focus. Page jump will occur only with Tab on the first element after video(s). 

**Expected behavior**
As a user using the Tab key to navigate between elements on a page, all elements, including videos located below the visible area, should be accessible without exceptions.

**Short video of the issue**
https://github.com/wp-media/wp-rocket/assets/93833759/7aaaadff-0b0f-465e-ab98-f50e3ab0cbf9

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Miraeld** [comment]
Umm, I'm having issue reproducing the problem. 
Please see the attached video, it works fine for me.


https://github.com/wp-media/wp-rocket/assets/14993267/1c9d0d28-ddcd-4b7f-92d6-73239449792e

**Comment by hanna-meda** [comment]
@Miraeld , I am able to reproduce it on rocketlabsqa.ovh
You can check on [this page](https://rocketlabsqa.ovh/ll-h)
Thank you.
[Later edit] It might be a compatibility issue, but checking on chrome browser (mac) issue is reproducing as in video when LL enabled for videos. Checking on page with nowprocket it doesn't.

**Comment by Miraeld** [comment]
It also works for me with Chrome (MacOS) on the URL you gave me

**Comment by hanna-meda** [comment]
Closing for now as this only occurs on my end and only for this page and only on Chrome. Creating a page from scratch with the same elements, moving with Tab, videos come to focus as expected.
