### ISSUE TITLE
HTML validation issue

### ISSUE THREAD

**Issue by tibelchior** [wp-media/wp-rocket#6457]
Hello, if I use the W3C Validator on my WP Rocket optimized page, I get this error: 

**Element script must not have attribute defer unless attribute src is also specified.**

Is it possible to remove the "defer" from the script elements? It makes no sense to have that if you are already deferring the loading by changing the src attribute to **data-rocket-src**.

Thanks.

**Comment by piotrbak** [comment]
Hello and thanks for creating the issue. WP Rocket adds `defer` attribute when `Load JavaScript deferred` feature is enabled. Disabling it would resolve the W3C Validator problem unless 3rd-party is adding the attribute.

**Comment by tibelchior** [comment]
Thanks for the answer, Piotrbak. But I do need it to be deferred, just that the way WP Rocket handles it it's a great solution in my opinion, that together with the "defer" attribute can be avoided.
I tested your solution and our Pagespeed test went from 99 to 53. So this is not really possible to use.

**Comment by piotrbak** [comment]
Delay Javascript and Load JavaScript Deferred are contemplatory features. Unfortunately, it's not possible to avoid the W3C Validation error at this point when using both of them.

**Comment by tibelchior** [comment]
Ok, then we have to ignore this validation at the moment. Thanks for the explanation.
