### ISSUE TITLE
Fatal errors related to :cancel_process() 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#646]
examples: 
https://secure.helpscout.net/conversation/487573943/55559?folderId=1050085
https://secure.helpscout.net/conversation/487742828/55595?folderId=273764

**Comment by Tabrisrp** [comment]
I believe it's related to OPCache too, one of the customer said it happened once and then it didn't happen again

**Comment by Tabrisrp** [comment]
We rely on a background processing library for preload and database optimization. This library contains a verification, to not load the class a second time if it’s already loaded.

It is also used in other plugins, but not updated. This old version doesn’t have the `cancel_process()` method.

If those other plugins are loaded before WP Rocket on the admin side,  it is their version of the library that is used.
