### ISSUE TITLE
3.16 - Clean-up irrelevant implementation from the previous version

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6461]
**Context**
On the LCP/ATF branch, some implementation has been done previously assuming the LCP/ATF computation would happen on the SaaS side. Since this is not the case anymore, some part of the implementation is not needed and should be cleaned up.

There are many small aspects at stake here. It will be important to break it down properly. Do not hesitate to create sub-tasks.

**Expected behavior**
- We must keep the CRON job refactor from https://github.com/wp-media/wp-rocket/pull/6307 in case, in the future, we want several features/tables to send jobs to the SaaS.
- The LCP/ATF table should not be used anymore to send job to the SaaS: the warm-up for the LCP/ATF should happen without the use of the DB (see https://github.com/wp-media/wp-rocket/issues/6429).
- The LCP/ATF table data model must be changed as we don't need SaaS related information anymore: https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#5bc857fa6c494a27af1ab5f8588dbcca
- LCP/ATF data maintenance is to be adapted as it differs from the one of the RUCSS: https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#c88ee13ad86342b9b771e990f9ee814c
- LCP/ATF feature should not be used anymore when scheduling Saas-related CRON (if it was the case?)
- Tests should be adapted as well (from https://github.com/wp-media/wp-rocket/issues/6354)

**Acceptance Criteria**
- No regression of the LCP/ATF feature.
- No regression of the RUCSS feature.
- Branch 6354 is closed.

**Comment by MathieuLamiot** [comment]
Some additional behaviors listed based on: https://wp-media.slack.com/archives/CUT7FLHF1/p1709914446593059
There is an important work of clarifications to be done on what is on the branch, and what is not.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
#### Engine\Media\AboveTheFold\ServiceProvider
- remove `atf_manager` and `atf_factory` from the `$provides` array
- remove instantiation of the ATF manager and ATF factory
- remove ATF manager dependency from the FrontController

#### Engine\Media\AboveTheFold\Database\Tables\AboveTheFold
For this part there is 2 approaches: one where we consider this has not been released at all, so we don't run an upgrade routine of the table (will have to do some manual stuff during testing to clean up the DB), or do an upgrade routine to update the table.

- in `$schema_data`, remove the column `error_code`, `retries`, `job_id`, `queue_name`, `submitted_at`, `next_retry_time`

If we do the upgrade routine, also do the following:
- update the `$version` number to the new date
- add a new upgrade method to remove the above column

#### Engine\Media\AboveTheFold\Database\Schemas\AboveTheFold
- remove the above columns

#### Engine\Media\AboveTheFold\Database\Rows\AboveTheFold
- remove the above variable

### Estimate the effort ✅ 
Effort [S]

**Comment by remyperona** [comment]
I split this into 2 parts, one part to clean-up the database implementation, and one for the maintenance implementation (https://github.com/wp-media/wp-rocket/issues/6474)

**Comment by Miraeld** [comment]
Seems okay to me.

**Comment by MathieuLamiot** [comment]
Pending https://github.com/wp-media/wp-rocket/issues/6474 to be merged, as both are dependent on each other.

**Comment by MathieuLamiot** [comment]
No QA for this, this is a technical task.
