### ISSUE TITLE
Age Verification Screen for WooCommerce cookie gets stripped in Never Cache Cookies

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#6467]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: 3.15.9 ✓
- Used the search feature to ensure that the bug hasn’t been reported before✓

**Describe the bug**
[Age Verification Screen for WooCommerce](https://de.wordpress.org/plugins/age-verification-screen-for-woocommerce/) plugin sets a cookie [hyaM0gU)i7](https://jmp.sh/mSGYLBoz). When hyaM0gU)i7 is added in the Never Cache Cookies, the **)** gets stripped.

**To Reproduce**
1. Go to Advanced Rules
2. Add hyaM0gU)i7 in Never Cache Cookies
3. Save
4. Notice hyaM0gU)i7 is now hyaM0gUi7

**Expected behavior**
hyaM0gU)i7 should be preserved entirely

**Screenshots**

**Additional context**
hs: https://secure.helpscout.net/conversation/2530557821/478653?viewId=5547167
slack: https://wp-media.slack.com/archives/C08N8J6VC/p1709792088466699?thread_ts=1709719643.903429&cid=C08N8J6VC

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by DahmaniAdame** [comment]
Tested adding it using a filter. 
It broke the rewrite rule line because of `)` and it doesn't look like there is a way to skip characters while still have the rewrite rule apply.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.

**Comment by webdeveloper10001** [comment]
Hello, 
I am using this plugin with WP Rocket. first time cookie name add in advanced rules.
cookie never cached but "age verification screen.." plugin hit on "Purge users' cookies" button.
new cookie name gererated. how to resolved the issues?
any one help me please?
