### ISSUE TITLE
Imagify update broke third compatibility

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket#6468]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After updating to 2.2 WP Rocket's WebP addon doesn't detect Imagify as a WebP plugin anymore

**To Reproduce**
1. Update Imagify to 2.2
2. On WP Rocket, go to the WebP addon
3. See the message:  `We have not detected any compatible WebP plugin!`

**Expected behavior**
we should detect Imagify as a WebP compatible plugin

**Screenshots**
![image](https://github.com/wp-media/imagify-plugin/assets/229406/df65f15b-c160-4bf3-bf7f-e5b94c858758)

**Additional context**
ticket https://secure.helpscout.net/conversation/2533421582/479330?folderId=273761

**Acceptance Criteria (for WP Media team use only)**
On WP Rocket's end, expectations are as follows:
1. Imagify is disabled the compatibility is not displayed, no matter what nextgen display options were set when it was active
2. When Imagify is enabled and nextgen display is enabled, we should display compatibility banner and disallow usage of webp addon
3. When imagify is enabled and nextgen is disabled, we should display the compatibility banner saying that Imagify is enabled but webp display is disabled

**Comment by hanna-meda** [comment]
@Miraeld, returned this to In Progress for point 3. under **Acceptance Criteria**, as discussed also in [slack thread](https://wp-media.slack.com/archives/CUT7FLHF1/p1709888214115489?thread_ts=1709842768.069589&cid=CUT7FLHF1) 
Thank you.

**Comment by MathieuLamiot** [comment]
Re-opening for:

Fix CI
Fix the warning (if easy to fix): https://github.com/wp-media/wp-rocket/pull/6469#issuecomment-1994164794

**Comment by MathieuLamiot** [comment]
Re-opening for:

Fix the warning (if easy to fix): https://github.com/wp-media/wp-rocket/pull/6469#issuecomment-1994164794
