### ISSUE TITLE
Fatal error related to minification (mobile?)

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#647]
https://secure.helpscout.net/conversation/487163117/55486?folderId=273764

full error log in ticket, but here's an example: 
PHP Fatal error:  require(): Failed opening required '/wp-content/plugins/wp-rocket/min/lib/Minify/CSS/UriRewriter.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in wp-content/plugins/wp-rocket/inc/functions/files.php on line 1046

(redacted some custom server paths)

**Comment by Tabrisrp** [comment]
The file doesn't exist anymore, and the code itself either. Might be some OPCache issue

**Comment by GeekPress** [comment]
@webtrainingwheels @Tabrisrp Can we close this issue if it's not related to WP Rocket itself?
