### ISSUE TITLE
3.16 - Send links fetched on homepage to the SaaS to trigger a visit so that LCP/ATF optimization has a warm-up

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6470]
**Context**
3.16 EPIC
Follow-up sub-task of #6429 : now that we fetch the links from the homepage when needed, they must be sent to the SaaS. 
Discussed on Slack : https://wp-media.slack.com/archives/CUT7FLHF1/p1709914446593059

**Expected behavior**
- All links fetched from the homepage (see #6429) must immediately be sent to the SaaS to trigger a visit. See [Postman Collection](https://www.notion.so/wpmedia/Postman-collections-883eac80b2e043d8969b36a8c08a219f?pvs=4) -> WP Rocket RUCSS Director -> Send LCP/ATF SaaS ; setting the optimization_list parameter to empty.
- The URL for each job sent to the SaaS must have the query parameters usually used for the SaaS, and an additional one related to adding the image dimensions: see https://github.com/wp-media/wp-rocket/issues/6441
- For test/QA/Debug purposes, the following logs must be added (see how to do it [here](https://www.notion.so/wpmedia/Logs-265376f5033343d8a2c4e0c19a8dcc55?pvs=4)): log when starting the fetch_link + sending process, log the list of fetched links, log the requests + answers to/from the SaaS, log if the sending process completed successfully.

**Acceptance Criteria**
- Enable the logs
- Trigger the fetch_link process by changing permalink structure for instance (other triggers are possible, check #6429).
- There must be a log mentionning the start of the process, a list of fetched links, a log for each link with the request and the successful response from the SaaS, and a log saying the process is completed.
- For each sent request, the url of the job must have the same query parameters as a RUCSS job and the additional one.

Now, change the URL of the SaaS in the plugin, to something wrong. Repeat above step. Logs must allow to see the requests failed and why.

**Additional information**
This warm-up process should not have any interaction with the WP Rocket LCP/ATF table in the DB.

**Comment by jeawhanlee** [comment]
### Scope a solution
To implement this feature, We need to use the `APIClient` from the `JobManager` Module and parse the necessary config to the `add_to_queue` method but we will need to update this method to accomodate the new query argument.

### Development steps:
In `WP_Rocket\Engine\Common\JobManager\APIHandler::APIClient`
- Use and implement the LoggerAwareInterface
- `add_to_queue`
  - Log the request body(config) and the response.

In `WP_Rocket\Engine\Media\AboveTheFold\WarmUp::Controller`
- [ ] Use the APIClient class
- `warm_up`
  - [ ] Prepare each url to add the query arg(wpr_imagedimensions) and send to the SaaS using the `add_to_queue` with config set to `optimization_list => ''`
  - [ ] Finally Log the process when it starts and when it ends.

### Effort estimation: S
### Can be peer-coded: No
### Is a refactor needed in that part of the codebase?
No

**Comment by jeawhanlee** [comment]
@MathieuLamiot To add to the a AC, shouldn't we bail out from this process when RUCSS is enabled?

**Comment by MathieuLamiot** [comment]
> shouldn't we bail out from this process when RUCSS is enabled?

Good point. If RUCSS is enabled, we should bail out even before fetching the links (to avoid a request to the homepage).
I feel like this bail out should be done at a different place than what is described in the grooming. Wouldn't it make sense to have a dedicated issue for this?

**Comment by jeawhanlee** [comment]
@MathieuLamiot What if we did the bail out in the PR for fetching the links?

**Comment by MathieuLamiot** [comment]
Sure, it would be more appropriate. I'll add the AC there and make bring back to in progress then. Thanks!

**Comment by wordpressfan** [comment]
Good job @jeawhanlee 

for this point:
> Update to accept a 3rd optional parameter and isolate the query args array and conditionally add wpr_imagedimensions to the array based on the value of the 3rd parameter.

I don't think that we need a new argument here, we can send this query string inside the url (first argument).
And you can create a new method there to prepare this and call `add_to_queue` directly, something like `add_lcp_to_saas_queue` (this is additional step to abstract), this is just not to touch the main `add_to_queue` because it handles other parts of code.

> In WP_Rocket\Engine\Media\AboveTheFold\WarmUp::Controller

Thanks @jeawhanlee for telling me that this class will be there once this PR #6465 is merged.

> Log the request body(config) and the response.

I think it'd be better not to log inside APIClient and make all logs inside controller.

Those points are just explanations and enhancements but your approach will work properly I believe, so what do u think?

**Comment by jeawhanlee** [comment]
> I think it'd be better not to log inside APIClient and make all logs inside controller.

@wordpressfan I did it this way because we would also be doing the same process for RUCSS, so it makes sense not to do the same thing 2x, you can check this [issue](https://github.com/wp-media/wp-rocket/issues/6471)

Meanwhile, I updated the grooming in regards to your first point, Thanks 🙏

**Comment by remyperona** [comment]
LGTM

**Comment by MathieuLamiot** [comment]
@hanna-meda 

Log when sending to a job to the SaaS : 'Add to queue request arguments'
Log API answer/error from sending to the SaaS: 'Add to queue request failure', 'Add to queue response body'
--> Those logs allow to list all URL sent to the SaaS. However, it does not capture anything if the wamr_up starts and is aborted, which might be needed for QA?

In which case, QA team can add logs in warm_up method of the controller.
