### ISSUE TITLE
3.16 - Remove treeshake parameters and provide logs of sent requests

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6471]
**Context**
Sub-task follow-up of #6429.
Now that the SaaS is used for different types of jobs, a new parameter has been added (optimization_list). For backward compatibility, when not set, the SaaS assumes it is a RUCSS job. But for clarity, we should avoid relying on this.

**Expected behavior**
- All requests to post a new job to the SaaS must have the config[optimization_list] parameter set in the payload. For LCP/ATF, it is left empty (handled in #6470). For RUCSS, it should be set to `rucss`. See [Postman Collection](https://www.notion.so/wpmedia/Postman-collections-883eac80b2e043d8969b36a8c08a219f?pvs=4) -> WP Rocket RUCSS Director -> Send RUCSS job.
- For debug/test purposes, logs must be added to capture all requests and answers send to the SaaS. This should be already the case from #6470  

**Acceptance Criteria**
- Activate RUCSS option.
- Enable debug mode.
- Clear the cache and trigger preload.
- Navigate & wait a bit, to make sure some jobs have been sent to the SaaS (you can check this in the DB directly ; there must be rows in the rucss table in state pending, with a job ID).
- Check the logs: you must find logs related to the jobs that have been sent, and the optimization_list must be set to "rucss".

**Comment by remyperona** [comment]
What about the `treeshake` parameter that is currently sent?

**Comment by MathieuLamiot** [comment]
It's nowhere to be found in the service doc, we don't use it in the Postman collection and I can't find it used in the code...
I think it's just unused ; probably a leftover from an old implementation?
Let's try to remove it as part of this issue then. Thanks, good catch!

**Comment by jeawhanlee** [comment]
@MathieuLamiot What I got from this is that `optimization_list` would hold a string such like in the case of RUCSS enabled, we would have `optimization_list => 'rucss'` but what about when we add more optimization on a single request later, doesn't this mean we would have to adjust the Saas again for this, shouldn't this `optimization_list` hold an array instead?

**Comment by MathieuLamiot** [comment]
@jeawhanlee optimization_list should be accepting array already. At least, with PostMan, I can send the 'rucss' value as the 1st value of the array optimization_list.

![image](https://github.com/wp-media/wp-rocket/assets/15233030/fb6b015b-30a5-46f4-9d3a-e92d0b01f5a3)

Here is the code where this is handled server-side (look for optimization_list): https://github.com/wp-media/nodejs-treeshaker/commit/ba7061a466a53828336935d8db7809f56e0e2c90

**Comment by jeawhanlee** [comment]
@MathieuLamiot Thanks for validating this, if it's already accepting an array, then I think we can close this issue as we currently have it this way from the previous 3.16 implementation, you can find it here: https://github.com/wp-media/wp-rocket/blob/1b55af56c573fdf0eef48a4954d766b791352cd3/inc/Engine/Optimization/RUCSS/Jobs/Manager.php#L200-L206
WDYT?

**Comment by MathieuLamiot** [comment]
Ok great! Is the 2nd bullet point already implemented as well (about getting logs for SaaS requests)?

**Comment by jeawhanlee** [comment]
We don't have that yet, I'll add a grooming for that here then

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
In `WP_Rocket\Engine\Common\JobManager\APIHandler::APIClient`
- Use and implement the LoggerAwareInterface
- In `add_to_queue` method, Log the request body(config) and the response.

In `WP_Rocket\Engine\Common\JobManager::JobProcessor`
- In `process_on_submit_jobs`, log the start and end process.
- In `send_api`, remove the `treeshake` param from the config array.

### Estimate the effort ✅
[S]

**Comment by remyperona** [comment]
LGTM, can we also handle the removal of the `treeshake` parameter since we don't use it anymore

**Comment by jeawhanlee** [comment]
Updated Grooming.
