### ISSUE TITLE
Wrong CSS generated when "lazyload background images" feature is enabled and stylesheet has `#` as `href` attribute

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6472]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When lazyload background images feature is enabled and there is a stylehseet has the url `#` as below:
```
<link rel='stylesheet' href="#" type='text/css' media='all' />
```

This will break all upcoming CSS by replacing `#` with a real url, that's because our code considers this `#` as a real url so it replaces it with a variable as in [here](https://github.com/wp-media/wp-rocket/blob/29697ac7363ad6b6c9da5ad1b63ec3bdfc135cb7/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L701) (this replaces all hashes in the whole content).

and this happens mainly with GDPR compliant plugins that converts the following stylesheet link:

```
<link rel='stylesheet' id='google-fonts-style-css' href='https://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600%2C700%7CRoboto%3A400%2C500%2C700%7CRoboto+Condensed%3A400%2C500%2C700%7COswald%3A400%7COpen+Sans%3A400&#038;display=swap&#038;ver=12.6.4' type='text/css' media='all' />
```

to be

```
<link data-service="google-fonts" data-category="marketing" rel='stylesheet' id='google-fonts-style-css' href="#" data-href='https://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600%2C700%7CRoboto%3A400%2C500%2C700%7CRoboto+Condensed%3A400%2C500%2C700%7COswald%3A400%7COpen+Sans%3A400&#038;display=swap&#038;ver=12.6.4' type='text/css' media='all' />
```

**To Reproduce**
1. Create a page template with the following HTML:
```
<?php
/**
 * Template Name: LLBG Template
 */
?>
<!doctype html >
<html>
<head>
    <title>Test</title>
    <link rel='stylesheet' href="#" type='text/css' media='all' />
</head>
<body>
<style>
    .tdi_35_rand_style{
        background-color: #ddb373 !important;
    }
</style>
</body>
</html>
```
2. Create a page with this template
3. Enable lazyload background images feature in WP Rocket plugin.
4. Check the page source and you will find this background-color attribute has a url.

**Expected behavior**
We shouldn't corrupt the page CSS.

**Screenshots**

**Additional context**
I believe we have many solutions here, like excluding `#` from the files when we extract them from the page [here](https://github.com/wp-media/wp-rocket/blob/29697ac7363ad6b6c9da5ad1b63ec3bdfc135cb7/inc/Engine/Common/ExtractCSS/Subscriber.php#L46)

For now, we can fix this by only excluding this `#` in media lazyload exclusion textarea:

![image](https://github.com/wp-media/wp-rocket/assets/146129302/b7b550e6-d3e7-44d4-a428-3c2c1df1662b)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
