### ISSUE TITLE
Update maintenance for LCP/ATF data storage

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#6474]
#### Engine\Common\JobManager\ServiceProvider
- remove `atf_factory` from the `$factories` array

#### Engine\Media\AboveTheFold\Cron\Controller
- Add a method `schedule_atf_cleanup()` to schedule the cleanup (daily), with the hook name `rocket_atf_cleanup`
- Add a method `atf_cleanup()` to perform the cleanup, removing the rows with failed status or not accessed since (1 month by default, filterable)
- Add a method `unschedule_atf_cleanup()` to unschedule the cleanup

#### Engine\Media\AboveTheFold\Cron\Subscriber
- Add callback `atf_cleanup()` for `rocket_atf_cleanup`
- Add callback `schedule_atf_cleanup()` for `init`
- Add callback `unschedule_atf_cleanup()` for `rocket_deactivation`

#### Engine\Media\AboveTheFold\Database\Queries\AboveTheFold
- Add a method to delete failed and not accessed rows

#### Engine\Media\AboveTheFold\ServiceProvider
- Add the cron controller and subscriber to the instantiation

### Estimate the effort ✅
Effort [M]

**Comment by Miraeld** [comment]
Looks ok to me
