### ISSUE TITLE
3.16 Add inline JS data for current URL and device

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#6479]
**Context**
To be able to save the current URL and the device to the DB along the LCP data, we need to add it inline as JS variable data on the page.

To do so, we can update the `inject_beacon()` method, to add an inline script containing an array that will have the following:
- the current URL
- if current device is mobile or not (using the existing `is_mobile()` method)

**Expected beavhior**
The required data is injected to the page along the beacon script

**Acceptance Criteria**
- current URL is in the JS variable array
- mobile value changes depending on the device

**Comment by MathieuLamiot** [comment]
Technical tasks, no QA.
