### ISSUE TITLE
3.16 - R&D - Beacon script compatibility with LazyLoad

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6486]
**Context**

@Tabrisrp identified that the current implementation does not correctly identify ATF/LCP images as Lazyload features can interfere with the beacon script: it catches lazyload placeholders instead of the proper image and stores it in the DB. This prevents the front-end optimization to be successfully applied.
There are several approaches to work around this ; the goal of this task is to provide the Product Team with a first prototype with a possible work-around, based on their suggestion.

Slack: https://wp-media.slack.com/archives/CUT7FLHF1/p1710536832224719

**Expected behavior**

- Delay the execution of the Beacon Script by 500ms so that lazyload scripts had time to run and so that the Beacon script works on a properly loaded above the fold content.

**Acceptance Criteria**
- This may not fix the original issue observed by @Tabrisrp, as this is an R&D task to discover possible work-around, and what won't work. So there is no acceptance criteria related to the 3.16 functionality.
- Endure that the script execution is delayed.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
I believe this is relatively simple to implement, by using `setTimeout(function, delay)` in the script file

### Estimate the effort ✅
effort XS

**Comment by remyperona** [comment]
I implemented it on my current branch, and it works with a timeout of 500ms
