### ISSUE TITLE
Elementor Builder - LL BG images added on ulterior edits will be visible only after a clear cache

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6496]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: 3.15.10 ✓
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
Editing a page created with the Elementor Builder, and adding background images below the fold, these images won't be visible until manually triggering a clear cache of the page. 

**To Reproduce**
1. Have WPR's Lazyload feature enabled for background images.
2. Using the Elementor builder plugin, create a new page & publish.
3. Reopen page in Edit and add any element with a background image (to be below the fold).
4. Save and visit page in Incognito mode.
5. Scroll to the newly added content with background images.
6. Notice that the background images are not present in UI. 
    > Background images will show after manually clearing the cache.

**Expected behavior**
Background images added on ulterior edits should show right from the start (without cache clearing).

**Screenshots**

**Additional context**
https://github.com/wp-media/wp-rocket/assets/93833759/c560c09f-05dc-4d6c-af8d-53f0275321ea

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
