### ISSUE TITLE
Old/Failed rows are not deleted due to incorrect table name

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6500]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
While running integration tests, The action hooked to the CRON event to delete old or failed rows does not work as expected.

**To Reproduce**
1. Error is visible on 

**Expected behavior**

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
@jeawhanlee Can this one be closed?
