### ISSUE TITLE
Generatepress Elements and Remove Unused CSS

### ISSUE THREAD

**Issue by winnersmedia** [wp-media/wp-rocket#6505]
I have some featured items at the top of every page except the homepage.  I have implemented this using the GeneratePress theme and it's Elements feature.  With "remove unused CSS enabled" the css for these featured items doesnt get included on a mobile device.  The layout itself is no different between desktop and mobile, featured sites appears on all pages except the homepage albeit on a mobile the featured items are swipeable/scrollable because of the overflow-x:auto.

- Create an element that appears on all pages except the homepage using generatepress.
- Add the custom style for the element in the customize css area of the theme.
- view on a mobile

**Comment by piotrbak** [comment]
Hello @winnersmedia that sounds more like a Support Request, to be honest. Please make sure to enable Separate Cache for Mobiles feature. If that doesn't help please take a look at our documentation article:
https://docs.wp-rocket.me/article/1718-troubleshoot-remove-unused-css-issues

If you'll still be struggling with problems, please contact our Support Team.

**Comment by winnersmedia** [comment]
It does fix it but there is no difference between the layout, the featured items appear on both mobile and desktop.  Perhaps the help text should be different.  "Most modern themes are responsive and should work without a separate cache. Enable this only if you have a dedicated mobile theme or plugin. "

I don't have a dedicated mobile theme or plugin.  Thanks.

**Comment by piotrbak** [comment]
@winnersmedia It means that some CSS classes or HTML elements are different on the mobile than on the desktop.

**Comment by winnersmedia** [comment]
can you explain what you mean by "are different".  The css is responsive and the same between desktop and mobile and the html is the same between desktop and mobile.  Are you saying "looks different"?
