### ISSUE TITLE
3.16 - In some cases `DOMContentLoaded` is already fired before loading our beacon script

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6511]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes, lcp feature branch**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
In some cases our beacon script is not firing correctly leads to not saving images into the database.

I think this is because `DOMContentLoaded` event that we use here:
https://github.com/wp-media/wp-rocket/blob/ca4a55b7fc2a1f287a57c98b105d2639e969e0fe/assets/js/lcp-beacon.js#L148-L152

is already fired (maybe because we are using async way to load the script file itself, but I'm not sure) So to fix this we need to replace this part with the following:

```
if (document.readyState !== 'loading') {
	setTimeout(main, 500);
} else {
	document.addEventListener("DOMContentLoaded", async function () {
		console.time("extract");
		setTimeout(main, 500);
		console.timeEnd("extract");
	});
}
```

This will check if the `DOMContentLoaded` event is fired or not and fire our code in both cases.

**To Reproduce**
1. Create a simple theme page template like below:

```
<?php
/**
 * Template Name: Above the fold
 */
?>
<!doctype html >
<html>
<head>
    <title>Test</title>
    <?php wp_head(); ?>
</head>
<body>
<img src="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/kotł.PNG" alt="Nature">
<?php wp_footer(); ?>
</body>
</html>
```
2. Create a page with this template.
3. Clear cache
4. Visit the page in incognito mode

**Expected behavior**
1. You should see some console debug logs from lcp beacon script.
2. You should have a new row in the above the fold database table.
3. With next cache clear you shouldn't have the beacon script in the page at all.

**Screenshots**

**Additional context**
Really I don't know why exactly we are using this event `DOMContentLoaded` and not the window `load` event that fires after the whole page loads.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by remyperona** [comment]
There was no intention in choosing `DOMContentLoaded` specifically, it could be changed to another event. The script itself is in a very rough state right now, and would need someone very good with JS to improve it.

**Comment by MathieuLamiot** [comment]
Moving the `DOMContentLoaded` vs `load` discussion [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1711450993039189).

About the grooming/PR itself, this is the recommendation from the DOMContentLoad documentation so I'd say we should add this, indeed. The PR looks good, we should try to merge to the feature branch @wordpressfan I htink
