### ISSUE TITLE
3.16 - Beacon to cover more element types

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6513]
**Context**
Sub-task of #6449 
The current beacon script comes from a prototype that is not covering all type of elements. @mostafa-hisham provided a list of elements that we should cover as well [here](https://github.com/wp-media/nodejs-treeshaker/pull/579/files). 

**Expected behavior**
The beacon script must account for the following types of elements when computing the LCP and ATF contents:
- video poster attribute
- picture
- img srcset
- background images in :after, :before pseudo-elements
- image-set in background images

**List of subtasks**
- #6530
- #6531 
- #6532 
- #6534 
- #6535 

**Acceptance Criteria**
For each of the above elements:
- (Check with the QA team if available, or do it) Create a page with one of the new elements to cover in the viewport, and another image a bit smaller next to it (both in the viewport).
- Clear cache & LCP/ATF Data.
- Visit the page.
- Check in the DB that the LCP/ATF data is correct: the LCP must be the first element (as it is bigger).
- Repeat with the first element being a bit smaller than the image.
- The first element must be ATF but not LCP.

**Additional information**
In the current version, ATF elements are only taken from "img" elements: `var above_the_fold_images = document.querySelectorAll("img");`. This hsould not be the case: LCP and ATF candidates should come from the same list of elements. Actually, LCP is part of ATF, so we first find ATF, and then pick the LCP inside them.

A version generated by GitHub Copilot is available here as a possible inspiration to adapt the existing script:
```javascript
function getElementInfo(element) {
    const nodeName = element.nodeName.toLowerCase() ;
    const parentName = element.parentElement.nodeName.toLowerCase() ;
    const element_info = {
        // type: "img" | "img-srcset" | "picture" | "bg-img" | "bg-img-set".
        type: "",
        // src: image src (if type is img nad only has src attr).
        src: "",
        // srcset: image srcset (if type is img-srcset).
        srcset: "",
        // sizes: image sizes (if type is img-srcset).
        sizes: "",
        // sources: array picture sources (if type is picture) contain object {srcset:,media:}.
        sources: [],
        // bg_set: array of background images (if type is bg-img or bg-img-set).
        bg_set: [],
        // current_src: current image src (if type is img or img-srcset) get the current used image src in case the <img> is responsive.
        current_src: ""
    };

    const css_bg_url_rgx = /url\(\s*?['"]?\s*?(\S+?)\s*?["']?\s*?\)\s*?([a-zA-Z0-9\s]*[x|dpcm|dpi|dppx]?)/ig;

    if (nodeName === "img") {
        element_info.type = "img";
        element_info.src = element.src;
        element_info.current_src = element.currentSrc;

        if (element.srcset) {
            element_info.type = "img-srcset";
            element_info.srcset = element.srcset;
            element_info.sizes = element.sizes;
        }

        if (parentName === "picture") {
            element_info.type = "picture";
            element_info.sources = Array.from(element.parentElement.querySelectorAll("source")).map(source => ({
                srcset: source.srcset,
                media: source.media
            }));
        }
    } else if (nodeName === "video" && element.poster) {
        element_info.type = "img";
        element_info.src = element.poster;
        element_info.current_src = element.poster;
    } else {
        const computed_style = window.getComputedStyle(element, null);
        const bg_props = [
            computed_style.getPropertyValue("background-image"),
            getComputedStyle(element, ":after").getPropertyValue("background-image"),
            getComputedStyle(element, ":before").getPropertyValue("background-image")
        ];

        const full_bg_prop = bg_props.filter(prop => prop !== "none").join("");
        element_info.type = "bg-img";
        if (full_bg_prop.includes("image-set(")) {
            element_info.type = "bg-img-set";
        }
        if (!full_bg_prop || full_bg_prop === "") {
            return null;
        }

        const matches = [...full_bg_prop.matchAll(css_bg_url_rgx)];
        element_info.bg_set = matches.map(m => ({ src: m[1] || "", size: m[2].trim() || "" }));

        if (element_info.bg_set.length <= 0) {
            return null;
        }

        if (element_info.bg_set.length <= 0) {
            return null;
        }
    }

    return element_info;
}
```

**Comment by piotrbak** [comment]
Added subtasks:
https://github.com/wp-media/wp-rocket/issues/6535
https://github.com/wp-media/wp-rocket/issues/6534
https://github.com/wp-media/wp-rocket/issues/6532
https://github.com/wp-media/wp-rocket/issues/6531
https://github.com/wp-media/wp-rocket/issues/6530
