### ISSUE TITLE
3.16 improvement - Avoid looping twice over all elements in the 

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6514]
**Context**
Sub-task of #6449.
This is not needed for 3.16 to work properly, but it is a performance enhancement.
On the prototype beacon script, @mostafa-hisham identified that we loop several times on all the candidates for LCP/ATF. This could be avoided to increase performance of the script.

**Expected behavior**
- Refactor the beacon script to minimize looping over the different elements:
    -  `potentialCandidates.forEach((element) => { `
    -  `for (let i = 0; i < above_the_fold_images.length; i++) { `
   
**Acceptance Criteria**
- NRT of the 3.16 feature: check with QA for the 3.16 test plans and run Rocket-E2e if available.

**Additional information**
As discussed with the product team, LCP elements are above the fold. So candidates to LCP can be taken from the ATF list, which can help to rework the script.

**Comment by Miraeld** [comment]
Umm there is something I don't really get in this issue. 
`potentialCandidates.forEach((element) => {` is looping within 
``` javascript
const potentialCandidates = document.querySelectorAll(
        "img, video, p, main, div"
    ); // Adjust selectors as needed
```

while `for (let i = 0; i < above_the_fold_images.length; i++) { ` is only looping within `var above_the_fold_images = document.querySelectorAll("img");`

so it's a `"img, video, p, main, div"` versus `"img"`. Do we want either of them to loop on the same selectors ?

**Comment by MathieuLamiot** [comment]
> candidates to LCP can be taken from the ATF list, which can help to rework the script.

My understanding is that there is no reason to querySelectorAll on different tags for LCP and ATF in the first place. We will get more knowledge once 3.16 covers all content types (issues before this one in the backlog), so probably at that time we can see what the script looks like and how to enhance it.

Note that this is out of the scope for 3.16, but rather an enhancement after.

**Comment by MathieuLamiot** [comment]
Will be fixed [here](https://github.com/wp-media/wp-rocket/issues/6537)
