### ISSUE TITLE
3.16 improvement - Consider using the Intersection Observer API instead of doing the calculation manually

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6515]
**Context**
Subtask of #6449
The current version of the beacon script identifies "manually" above the fold content (see `var intersecting`). This could be done with the Observer API directly, and probably be more efficient / accurate.
This is not needed for 3.16 but it is a performance enhancement.

**Expected behavior**
- Rework the computation of ATF images based on the Observer API instead of a manual check.

**Acceptance Criteria**
- NRT of the 3.16 feature: check with QA for the 3.16 test plans and run Rocket-E2e if available.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
