### ISSUE TITLE
3.16 bug - Beacon is not injected on URLs visited by the SaaS

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6518]
**Context**

When visited, the URL passed to the SaaS for the warm-up of LCP/ATF does not contain the beacon script, nor any WP Rocket optimization.

**To reproduce**

- Install WP Rocket 3.16 (alpha)
- Clear Critical Images and Purge the cache for one URL.
- Visit the page of the above URL with the following query string: `?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1`. For instance: `https://rocketlabsqa.ovh/?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1`
- Open the dev tool: the beacon script is not in the list of elements loaded. You can actually see that no WP Rocket optimization is applied. You can easily see it with [WPR Inspector](https://www.notion.so/wpmedia/WPR-Inspector-Extension-4693da1647da459b8b4e45b5b61443f9?pvs=4) also.

**Expected behavior**

- URLs with the query string `wpr_imagedimensions=1` must not be excluded from the beacon script injection.
- URLs with the query string `nowprocket=1` must be excluded from the LCP/ATF front-end optimization.
- URLs visited by the SaaS must not get a cached page version.

**Acceptance Criteria**
Check wpr_imagedimensions & nowprocket behavior
- Do the "How to reproduce" above. The beacon must be injected in the page `https://rocketlabsqa.ovh/?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1`.
- Visit the same page with no query string. LCP/ATF Front-end optimization must be applied (LCP/ATF excluded from LL and fetch priority set to high). The beacon must not be injected.
- Visit the same page with query string wpr_imagedimensions=1 and nowprocket=1. LCP/ATF Front-end optimization must not be applied. the beacon must not be injected.
- Visit the same page with query string nowprocket=1. LCP/ATF Front-end optimization must not be applied. the beacon must not be injected.
- Visit the same page with query string wpr_imagedimensions=1. LCP/ATF Front-end optimization must be applied. The beacon must not be injected.

Check cache behavior
- Visit in incognito `https://rocketlabsqa.ovh/?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1`. IT should not be a cached version (you can check with WPR inspector for instance).
- Visit in incognito it again. It should not be cached.
- Visit in incognito `https://rocketlabsqa.ovh/?nowprocket=1&no_optimize=1`. IT should not be a cached version (you can check with WPR inspector for instance).
- Visit in incognito it again. It should not be cached.

**Comment by MathieuLamiot** [comment]
- I was able to reproduce the issue on https://rocketlabsqa.ovh/
 ---
⚠️ OLD GROOMING: TO DISCARD FOLLOWING THIS [DISCUSSION](https://wp-media.slack.com/archives/CUT7FLHF1/p1711526909214479?thread_ts=1711479812.267259&cid=CUT7FLHF1). NEW GROOMING BELOW.
There are several issues here:
- The first one is that the beacon script is not injected in pages with query string wpr_imagedimensions=1. I was able to fix this by adding `'wpr_imagedimensions' => 1` in the list of allowed query string [here](https://github.com/wp-media/wp-rocket/blob/8c3159546cf07f5cdcc495114da20252cb2d4711/inc/classes/Buffer/class-tests.php#L543). Otherwise, the buffer processing is bypassed. This allows to trigger the buffer processing, otherwise I could not get the beacon injected. To check with @wordpressfan why this has not been done in the original PR about wpr_imagedimensions?
- Once this issue is fixed, we need to bail out of the front-end LCP/ATF optimization in case the query string `nowprocket=1` is there. This is usually done with an is_allowed() method in the subscriber. Here, we would need it at the controller level, in `WP_Rocket\Engine\Media\AboveTheFold\Frontend`: `preload_lcp` to be renamed `maybe_preload_lcp` and first thing in this method is to check rocket_bypass().

⚠️ The issue with this solution seems to be that https://rocketlabsqa.ovh/?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1 gets cached. But it should not. Discussing with the product team [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1711526234407559?thread_ts=1711479812.267259&cid=CUT7FLHF1).
---

NEW GROOMING (thanks @wordpressfan):
To avoid the cache issue and make sure pages visited by the SaaS are not cached, we won't make `wpr_imagedimensions` an accepted query string for buffer processing.
Instead, we can:
- Duplicate [specify_image_dimensions](https://github.com/wp-media/wp-rocket/blob/63b724fbb3e1b8b19db2310414627861227eb7f1/inc/Engine/Media/ImageDimensions/Subscriber.php#L59) to a method `prepare_critical_image_saas_visit` with the following differences:
     - the bail out condition is _`wpr_imagedimensions` is not set_
     - the method fires an action `rocket_critical_image_saas_visit_buffer` (with `$buffer` as argument) and then `return $this->dimensions->specify_image_dimensions( $buffer );`
- In `start_image_dimensions_buffer`, ob_start should call `prepare_critical_image_saas_visit` instead of `specify_image_dimensions`.
- [Here](https://github.com/wp-media/wp-rocket/blob/274e72a9af625170f06feb2f093e3e8670a9c046/inc/Engine/Media/AboveTheFold/Frontend/Subscriber.php#L30), subscribe to `rocket_critical_image_saas_visit_buffer` to trigger `lcp` method.
- In `preload_lcp`, add a bail out based on rocket_bypass() so that SaaS visit can't have the LCP/ATF optimizations.

Effort: [S]

**Comment by remyperona** [comment]
LGTM

**Comment by MathieuLamiot** [comment]
@Miraeld Have you performed basic checks to ensure the code does not break on happy path and that the reported failing cases are fixed? In which case, we can merge so that we only have to work on the feature branch. OK? Thanks 🙏

**Comment by Miraeld** [comment]
@MathieuLamiot Yea I've tested it, and it worked fine.

**Comment by MathieuLamiot** [comment]
I manually validated the acceptance criteria on new.rocketlabsqa.ovh + triggered SaaS visists with PostMan and the beacon was there as expected.
