### ISSUE TITLE
russ increase html size, bing web master report: warning the html size is too long

### ISSUE THREAD

**Issue by wind1up** [wp-media/wp-rocket#6523]
russ add a large amount of code in the head, about 180kb.
bing web master tool report: warning: the html size is too long(limit to 125kb).

is there any way to resolve this?

**Comment by piotrbak** [comment]
Hello @wind1up, RUCSS is adding used CSS to the head. To see why it's that big, I'd suggest checking what kind of CSS is added there, maybe you have a lot of things safelisted?

You could contact our Support Team if you need an advice or help. Thanks!
