### ISSUE TITLE
3.16 enhancement - Images intersecting the viewport should be considered as LCP candidates

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6527]
**Context**
The current LCP detection only keeps images fully in the viewport as candidates. As discussed [here](https://wp-media.slack.com/archives/C06CQPWEJSK/p1711650334582609?thread_ts=1711580400.684789&cid=C06CQPWEJSK), this is excluding potential candidates that we should keep.

**Expected behavior**
- The LCP must be selected as the largest image in terms of area visible in the viewport among all images in the viewport or intersecting it.

**Acceptance Criteria**
- Prepare a page with two images: ImageA (size: 200x200, fully in the viewport) and ImageB (size:300x300, only 300x1 visible in the viewport).
- Clear the cache and critical image data for this page.
- Visit this page.
- Check in the DB that the LCP is image A.

- Repeat with  ImageA (size: 200x200, fully in the viewport) and ImageB (size:300x300, only 300x250 visible in the viewport). Check in the DB that the LCP is image B.

**Comment by MathieuLamiot** [comment]
### About keeping intersecting images:

The issue comes from the beacon script in the `LCPCandidates`: https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/assets/js/lcp-beacon.js#L9C1-L16C12
This condition is checking that the image is fully in the viewport. Instead, we should check that it is intersecting only. We have such a check already for the ATF images [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/assets/js/lcp-beacon.js#L88).
- **We should make a dedicated function `isIntersecting(rect)` returning a boolean based on the check already existing, and use this in both [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/assets/js/lcp-beacon.js#L9) and [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/assets/js/lcp-beacon.js#L88).**

### About accounting only for the visible area for LCP "score"

The area to account for is computed [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/assets/js/lcp-beacon.js#L17). It is currently accounting for the complete image size.
**To account for the visible part only, we should do:**
```
const visibleWidth = Math.min(rect.width, (window.innerWidth || document.documentElement.clientWidth) - rect.left));
const visibleHeight = Math.min(rect.height, (window.innerHeight || document.documentElement.clientHeight) - rect.top))
const area = visibleWidth * visibleHeight;
```

For the testing part, TBC with @jeawhanlee but it might be more suited to test this with Rocket-E2E.

Effort: [XS] (test scenarios are outside the scope as they are already on Rocket-E2E, if we will use Rocket-E2E).

**Comment by MathieuLamiot** [comment]
Should this be moved to Ready for Review?

**Comment by MathieuLamiot** [comment]
@Miraeld @wp-media/qa-team Do we have test scenarios, maybe on Rocket-E2E to validate this? Maybe similar to the acceptance criteria?

**Comment by Miraeld** [comment]
@MathieuLamiot not from what I am aware of.

**Comment by hanna-meda** [comment]
@MathieuLamiot , @Miraeld just pushed these 2 templates on /wp-media/rocket-test-data:
[lcp_images_intersecting_viewport_A.php](https://github.com/wp-media/rocket-test-data/blob/master/templates/lcp_images_intersecting_viewport_A.php)
[lcp_images_intersecting_viewport_B.php](https://github.com/wp-media/rocket-test-data/blob/master/templates/lcp_images_intersecting_viewport_B.php)
that should cover the AC. 
Will provide you with pages created on e2e as well, in a moment.

**Comment by hanna-meda** [comment]
@MathieuLamiot , @Miraeld 
on e2e, scenario 1
> ImageA (size: 200x200, fully in the viewport) and ImageB (size:300x300, only 300x1 visible in the viewport)

we have page [link](https://e2e.rocketlabsqa.ovh/lcp_images_intersecting_a/)) 

and for scenario 2
> ImageA (size: 200x200, fully in the viewport) and ImageB (size:300x300, only 300x250 visible in the viewport)

we have page [link](https://e2e.rocketlabsqa.ovh/lcp_images_intersecting_b/)

TC [link](https://wpmediaqa.testrail.io/index.php?/cases/view/15358).

**Comment by MathieuLamiot** [comment]
@Miraeld Have you performed basic checks to ensure the code does not break on happy path and that the reported failing cases are fixed? In which case, we can merge so that we only have to work on the feature branch. OK? Thanks 🙏

**Comment by MathieuLamiot** [comment]
Kind reminder @Miraeld: can this be merged?

**Comment by Miraeld** [comment]
I did basic check yea, and it worked. 
I think it can be merged yes.
