### ISSUE TITLE
Preload the responsive image markup

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6531]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
As a part of 3.16 scope we need to preload the responsive image when it's detected as LCP.

https://web.dev/articles/preload-responsive-images#imagesrcset-and-imagesizes

**Expected behavior**
Input markup:
```
 <img src="wolf.jpg" srcset="wolf_400px.jpg 400w, wolf_800px.jpg 800w, wolf_1600px.jpg 1600w" sizes="50vw" alt="A rad wolf">
```

Output markup:
```
<link rel="preload" as="image" href="wolf.jpg" imagesrcset="wolf_400px.jpg 400w, wolf_800px.jpg 800w, wolf_1600px.jpg 1600w" imagesizes="50vw" fetchpriority="high">
```

**Acceptance Criteria (for WP Media team use only)**
**LCP**
1. Image is preloaded using the image URLs from `srcset` attribute and becomes `imagesrcset`
2. `sizes="50vw"` attribute is moved to the preload markup and becomes ` imagesizes="50vw"`
3. `fetchpriority="high"` is added to the preload markup
4. Image is excluded from LL feature

**Above the fold**
1. All Images within responsive markup are excluded from LL feature

**Comment by Mai-Saad** [comment]
Note for e2e: we need to check if all images within responsive markup will be added to DB or all images there and update e2e expected ATF accordingly https://e2e.rocketlabsqa.ovh/lcp_responsive_image/

**Comment by remyperona** [comment]
PHP part is handled for this case.

**Comment by jeawhanlee** [comment]
### Expected data structure in DB for LCP:
```
   {
     "type": "img-srcset",
     "src": "wolf.jpg",
     "srcset": "wolf_400px.jpg 400w, wolf_800px.jpg 800w, wolf_1600px.jpg 1600w",
     "sizes": "50vw"
   }
```
Same will apply for ATF.
