### ISSUE TITLE
Preload the single background images markup

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6532]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
As a part of 3.16 scope we need to preload the background images when they're detected as LCP.

**Expected behavior**
We'll need to handle 3 different markups, this issue is related to the basic one:

Input:
```
 background-image: url("background.jpg");
```
Output:
```
<link rel="preload" as="image" href="background.jpg" fetchpriority="high">
```

**Acceptance Criteria (for WP Media team use only)**
**LCP**
1. Image is preloaded using the image URL from the declaration
2. `fetchpriority="high"` is added to the preload markup
3. Image is excluded from LL Background Images feature

**Above the fold**
1. Image is excluded from LL Background Images feature

**Comment by remyperona** [comment]
PHP part is handled for this case.

**Comment by jeawhanlee** [comment]
### Expected data structure in DB for LCP:
The same [here](https://github.com/wp-media/wp-rocket/issues/6534#issuecomment-2056264880) but only with one element in the `bg_set` array
