### ISSUE TITLE
Preload the layered background images markup

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6534]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
As a part of 3.16 scope we need to preload the layered background images when they're detected as LCP.

**Expected behavior**
Input:
```
background-image: url("img.jpg"), url("img2.jpg");
```
Output:
```
<link rel="preload" as="image" href="img.jpg" fetchpriority="high">
<link rel="preload" as="image" href="img2.jpg" fetchpriority="high">
```

**Acceptance Criteria (for WP Media team use only)**
**LCP**
1. Images are preloaded separately using the image URL from the declaration
2. `fetchpriority="high"` is added to the preload markup
3. Images are excluded from LL Background Images feature

**Above the fold**
1. Images are excluded from LL Background Images feature

**Comment by remyperona** [comment]
PHP part is handled for this case.

**Comment by jeawhanlee** [comment]
### Expected data structure in DB for LCP:
```
   {
     "type": "bg-img",
     "bg_set": [
       {"src": "img.jpg"},
       {"src": "img2.jpg"}
     ]
   }
```
Same will apply for ATF.
