### ISSUE TITLE
Preload the image-set background images

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6535]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
As a part of 3.16 scope we need to preload the image-set background images when they're detected as LCP.

**Expected behavior**
Input:
```
background-image: image-set( "cat.png" 1x, "cat-2x.png" 2x);
background-image: image-set( url("cat.png") 1x, url("cat-2x.png") 2x);

```
or
```
background-image: -webkit-image-set( "cat.png" 1x, "cat-2x.png" 2x);
background-image: -webkit-image-set( url("cat.png") 1x, url("cat-2x.png") 2x);
```
Output:
```
<link rel="preload" as="image" imagesrcset="cat.png 1x, cat-2x.png 2x" fetchpriority="high">
```

**Acceptance Criteria (for WP Media team use only)**
**LCP**
1. Images are preloaded using the image URL from the `image-set` declaration, they'll be added to the `imagesrcset` attribute
2. `fetchpriority="high"` is added to the preload markup
3. Images are excluded from LL Background Images feature

**Above the fold**
1. Images are excluded from LL Background Images feature

**Comment by piotrbak** [comment]
@DahmaniAdame @benorfaz There's also another background `image-set` to be handled:
`-webkit-image-set`

There's a possible edge case when `image-set` and `-webkit-image-set` are different images, then we'll preload both of them while without WP Rocket it'll load only one. I guess this is acceptable one.

CC @Mai-Saad

**Comment by Mai-Saad** [comment]
Note: related test page on e2e
https://e2e.rocketlabsqa.ovh/lcp_bg_reponsive_imgset_template
https://e2e.rocketlabsqa.ovh/lcp_bg_responsive_webkit_template

**Comment by remyperona** [comment]
PHP part is handled for this case.

**Comment by jeawhanlee** [comment]
### Expected data structure in DB for LCP:
```
   {
     "type": "bg-img-set",
     "bg_set": [
       {"src": "cat.png 1x"},
       {"src": "cat-2x.png 2x"}
     ]
   }
```
Same will apply for ATF.
