### ISSUE TITLE
Combine JS is removing some JS files

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#654]
https://secure.helpscout.net/conversation/488107312/55633/?folderId=273764
https://secure.helpscout.net/conversation/487954561/55620?folderId=377611

In this example, this JS file is removed: 
`<script data-cfasync="false" src="//surgeprice.com/display/ads/4YmS2zhgTKfdC47fe/ariel.js"></script>
`

Without Combine JS: 
![external_js](https://user-images.githubusercontent.com/1043076/34075568-8a295074-e27f-11e7-9bec-bed490771388.jpg)

With Combine JS: 
![view-source_www_ihaveapc_com_2017_10_halloween-giveaway-click-to-catch-a-ghost-to-win-a-license-of-iotransfer-pro_](https://user-images.githubusercontent.com/1043076/34075573-b88467e2-e27f-11e7-9888-4e99c5fa2974.jpg)

UPDATE: not limited to external JS, it's actually removing many other files, similar to the Combine CSS issue.

**Comment by Tabrisrp** [comment]
I found a bug that removes external files when combine + defer JS is active.

I don't understand for the combine part, do you mean files are removed and not added to the minified+combined files?

**Comment by webtrainingwheels** [comment]
Sorry again for the lack of specifics. The issue is that JS files are removed and **no** JS files end up being loaded - not the originals and not minified/combined. 
As with the CSS issue, CDN seems to the condition that causes it. 
https://secure.helpscout.net/conversation/488400418/55680?folderId=377611
