### ISSUE TITLE
Images not displaying in UI with certain image markups (Irregular polygon, nested, or transformed images) when LL is enabled

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6547]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.16-alpha1 ✓
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
Images not showing in UI for certain image markups (Irregular polygon, nested, or transformed images) when Lazyload for images feature is enabled.

**To Reproduce**
1. Have page template(s) created with the following image markups:
- irregular polygon, using CSS clip-path property, https://rocketlabsqa.ovh/lcp_irregular_polygon ([template](https://github.com/wp-media/rocket-test-data/blob/master/templates/lcp_irregular_polygon_template.php))
- image as nested element, child elements partially overlap parent elements, https://rocketlabsqa.ovh/lcp_nested_images ([template](https://github.com/wp-media/rocket-test-data/blob/master/templates/lcp_nested_images_template.php))
- image as transformed element, CSS transformations such as rotate, scale, https://rocketlabsqa.ovh/lcp_transformed_images ([template](https://github.com/wp-media/rocket-test-data/blob/master/templates/lcp_transformed_images_template.php))

2. Have Lazyload enabled for images.
3. Visit the page templates from step 1.
4. Notice that images are not visible in UI.

**Expected behavior**
Images should be correctly displayed in UI.

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
