### ISSUE TITLE
Frontend optimization applied for the wrong element in some cases

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6553]
**Before submitting an issue please check that you’ve completed the following steps:**
- Using 3.16-pre-alpha
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a background image is identified as the LCP, the type in the DB reads `img` instead of `bg-img` (To be addressed in this issue: https://github.com/wp-media/wp-rocket/issues/6552) and because of this we try to look for img element in the markup [here](https://github.com/wp-media/wp-rocket/blob/ca50f74cb829a369ba863e71543b00c7f9c22930/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L144) which does not exist but then we have a malformed REGEX and it catches the first match of `<img>`

**To Reproduce**
1. Use a background image as the LCP with 2-3 <img> elements as ATF
2. Visit the page
3. See in DB that lcp type is captured as `img` instead of `bg-img`
4. Clear cache
5. Then check source and see that the fetchpriority attr is added to the first img tag.

**Expected behavior**
We should not add fetchpriority attr when there is no matching img element in cases like this.

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
@jeawhanlee Have you performed basic checks to ensure the code does not break on happy path and that the reported failing cases are fixed? In which case, we can merge so that we only have to work on the feature branch. OK? Thanks 🙏

**Comment by MathieuLamiot** [comment]
@jeawhanlee kind reminder. Since the QA process is still to be done on checking if we apply LCP/ATF correctly, could we just merge this and consider it done so that we'll only test once on the feature branch that LCP/ATF is correctly applied?
