### ISSUE TITLE
LCP/ATF is not found for images loaded by ajax

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6560]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => enhancement/preload-background-image (9801579ea9e69c6d217ea40d4474bcbc97c474f2)  and feature/lcp-above-the-fold-optimization commit 1c4062ac9be975d0086fae98a8af1642ba08d83b

- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Images loaded via ajax aren't added to LCP/ATF (LCP is there at page speed insights)

**To Reproduce**
1. Having page with images loaded via ajax
2. visit the page 
3. check ATF table => lcp not found and atf []

**Expected behavior**
LCP/ATF are added to images loaded by ajax

**Screenshots**

**Additional context**
- Test page https://new.rocketlabsqa.ovh/lcp_image_load_via_ajax

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
