### ISSUE TITLE
Clear critical images shouldn't be in admin bar while not having valid license

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6561]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => feature/lcp-above-the-fold-optimization commit https://github.com/wp-media/wp-rocket/commit/1c4062ac9be975d0086fae98a8af1642ba08d83b
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Clear critical images is displayed in admin bar while not validating license

**To Reproduce**
1. Install WPR using CLI
2. Don't add license data in wp-config
3. Activate WPR and try to access settings then hover on admin bar

**Expected behavior**
Clear critical images is not displayed as same as  for clear cache

**Screenshots**
![Screenshot from 2024-04-16 10-06-53](https://github.com/wp-media/wp-rocket/assets/76941962/fa8750a7-a1d4-4a9c-8472-db3828015e87)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Miraeld** [comment]
Hello, 
I've tested this PR, and I can say that it's working fine. 
Here are two screenshots: 
1. The provided license is invalid, so we don't get the `Clear crititcal data` options within WP Rocket.
<img width="1687" alt="Screenshot 2024-05-06 at 02 11 06" src="https://github.com/wp-media/wp-rocket/assets/14993267/0565a3f7-fa91-4c83-a222-d166c0f8a3ad">
2. The license is valid, we do get the options
<img width="1758" alt="Screenshot 2024-05-06 at 02 11 23" src="https://github.com/wp-media/wp-rocket/assets/14993267/b792cd71-28c1-4da4-a2e4-b332b062ff70">
