### ISSUE TITLE
3.16 - Secure LCP/ATF data from the AJAX endpoint and DB

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6564]
**Context**
https://wp-media.slack.com/archives/CUT7FLHF1/p1713283119489009?thread_ts=1713277169.038639&cid=CUT7FLHF1

**Expected behavior**
- Consider escaping URLs before storing them
- Consider limiting the size storable in the lcp and viewport columns to prevent overloading the DB (up to 1k characters? per field?)
- Add unit tests on the AJAX endpoint and front-end LCP optimization to test against malformed URLs, including tentative of XSS, SQL injection, and too large data.

**Acceptance Criteria**
- Modify the beacon script to try and send ill-intentioned data to the LCP and ATF fields (XSS, SQL Injection). Launch the beacon script ; the data must either not be stored or sanitized/escaped before entering the DB. In debug mode, a log must be created to explain the data has been discarded because of this.
- Manually add ill-intentioned data to the LCP and viewport columns in the DB (XSS typically). Load the page with the LCP/ATF optimization. The ill-intentioned/corrupted URLs must not appear in the HTML (either sanitized/escaped, or optimization not applied). In debug mode, a log must be created to explain the data has been discarded because of this.
- Modify the beacon script to try and send very long data to the LCP and ATF fields. Trigger the beacon script. The long data must not be stored. In debug mode, a log must be created to explain the data has been discarded because of this.
- Those cases must be covered in built-in tests.

**Additional information**
The expected behavior might be reworked if we think about something else to protect against during the implementation. This has a bit of R&D.

**Comment by remyperona** [comment]
### Scope a solution ✅
#### Engine\Media\AboveTheFold\AJAX\Controller
in `add_lcp_data()`
- use `esc_url_raw()` on the lcp/viewport `src` values
- update tests

#### Engine\Media\AboveTheFold\Frontend\Controller
in `generate_lcp_link_tag_with_sources()`
- use `esc_url()` for the `src` values in the `href`
- update tests
 
For the long date for LCP/ATF, I'm not sure how we could limit by character. The string is generated using JSON encoding of an object, so we can't truncate the string itself (it would be malformed).

### Estimate the effort ✅
Effort `[S]`

**Comment by Miraeld** [comment]
Looks good to me
