### ISSUE TITLE
Commented URLs at home page shouldn't be sent to saas

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6566]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16 commit 7947b657d900abad7425e2aa7770779e04559072
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If we have a commented URL in the home page (from 1st 10 URLs), it will be sent to saas

**To Reproduce**
1. Home page is set to a page template with a commented URL
2. WPR debug is enabled
3. install and activate 3.16 
4. check WPR log => commented URL is added to queue to saas

**Expected behavior**
Commented URLs aren't added to the queue to saas

**Screenshots**

**Additional context**
- test template https://new.rocketlabsqa.ovh/lcp_mixed_urls_commented/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
