### ISSUE TITLE
3.16 - When RUCSS & LCP/ATF are both enabled, URLs sent to the SaaS should have the wpr_imagedimensions=1 query string

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6569]
**Context**
For SaaS visits to get the beacon script injected, the query string wpr_imagedimensions=1 must be present.
When both RUCSS & LCP/ATF are enabled, jobs sent to the SaaS are expected to do both the RUCSS optimization and trigger the beacon script.

**Issue**
On the current version of LCP/ATF, when RUCSS & LCP/ATF are enabled, URLs sent to the SaaS have this query string: ?nowprocket=1&no_optimize=1. wpr_imagedimensions=1 is missing so SaaS visits don't get the beacon script injected.

**Expected behavior**
- [x] When LCP/ATF and RUCSS are both deactivated, no URL must be sent to the SaaS
- [x] When LCP/ATF is on and RUCSS is off, URLs are sent to the SaaS as part of the pre-warm-up (can be triggered with "Clear Critical Images"). The query string must be `?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1`.
- [x] When LCP/ATF is off and RUCSS is on, URLs are sent to the SaaS as part of the RUCSS process (can be triggered with "Clear Used CSS"). The query string must be `?nowprocket=1&no_optimize=1`.
- [ ] When LCP/ATF is on and RUCSS is on, URLs are sent to the SaaS as part of the RUCSS process (can be triggered with "Clear Used CSS"). The query string must be `?wpr_imagedimensions=1%2F&nowprocket=1&no_optimize=1`.

The last point is not working as expected.

**Acceptance Criteria**
- Replace the API_URL in the namespace WP_Rocket\Engine\Common\JobManager\APIHandler by the URL of our staging RUCSS server (you can ask on Slack to get it). This will allow you to check the URLs processed by the SaaS [on Metabase](https://data.wp-media.me/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNCwicXVlcnkiOnsic291cmNlLXRhYmxlIjo1NTAsIm9yZGVyLWJ5IjpbWyJkZXNjIixbImZpZWxkIiwxNDM4OSxudWxsXV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==).
- Check the 3 last expected behaviors by setting the right LCP/ATF & RUCSS configuration, and triggering the warm-up or the RUCSS process with the "Clear xxx" button from the admin bar. Check the URLs processed by the SaaS.
- In all cases where RUCSS is on, the optimization_list parameters must be set to ['rucss'] in the request to the SaaS.
- If RUCSS is off and LCP/ATF is on, then optimization_list must be set to ''. (empty string).  

**Additional information**
The issue seems to be that `wpr_imagedimensions` is set in `add_to_atf_queue` which is a method only used by the warm-up LCP/ATF process, not the RUCSS one. Since `wpr_imagedimensions` should not be restricted to the warm-up, maybe it could be handled in the `add_to_queue` method of APIClient? We could either check there if lcp/Atf is enabled and add the wpr_imagedimensions if it is, or we could use a filter to maybe add query parameters, and have the LCP/ATF service subscribe to it to handle the addition of wpr_imagedimensions?

**Comment by remyperona** [comment]
### Scope a solution ✅ 
#### Engine\Common\JobManager\APIHandler\APIClient
- Add a new filter `rocket_saas_api_queued_url` in `add_to_queue()`
```
$url = add_query_arg(
			[
				'nowprocket'  => 1,
				'no_optimize' => 1,
			],
			user_trailingslashit( $url )
		);

		$url = apply_filters( 'rocket_saas_api_queued_url', $url );

		$args = [
			'body'    => [
				'url'    => $url,
				'config' => $options,
			],
			'timeout' => 5,
		];
```

#### Engine\Media\AboveTheFold\WarmUp\Controller
- Add a new method `add_wpr_imagedimensions_query_arg()`, to add the arg to the SaaS queued URL if the feature is allowed (using the context to check)
- Add test

#### Engine\Media\AboveTheFold\WarmUp\Subscriber
- Add new callback on `rocket_saas_api_queued_url` with `add_wpr_imagedimensions_query_arg()`

### Estimate the effort ✅
Effort `[S]`

**Comment by Miraeld** [comment]
Looks good to me

**Comment by hanna-meda** [comment]
Related Test Run [Here](https://wpmediaqa.testrail.io/index.php?/runs/view/840&group_by=tests:status_id&group_order=asc)
