### ISSUE TITLE
3.16 - Error & timeout handling of Beacon Script

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6570]
**Context**
https://wp-media.slack.com/archives/CUT7FLHF1/p1713349928163759?thread_ts=1713250509.830419&cid=CUT7FLHF1

Currently, if the script throws an error, or if it never completes, then we will keep injecting it and it could keep failing/timing out forever.
We have not encountered a case where this happened, so this is a bullet-proofing approach and there is no way to naturally reproduce this without enforcing an error/time-out in the script itself.

**Expected behavior**
- If the beacon script throws an error, it must be handled this info must be sent to the AJAX endpoint.
- If the beacon script takes longer than 10s to execute, this info must be sent to the AJAX endpoint.
- The AJAX endpoint must handle failure payloads (error thrown and timeout) and register this in the DB, similarly to a valid payload but with the failure status and the related error message.

As a result, if the row related to the current URL has status failed, then the beacon script won't be injected and if it is already injected, it will bail out early in the process.

**Acceptance Criteria**
- Modify the script to throw an error.
- Clear critical images and cache, enable cache.
- Visit a page. The beacon must be injected, and the critical image table must store a row with a failed status and the error_message.
- Re-visit the page. The beacon must be there but it should not throw any errors as it bails out early.
- Clear the cache. Re-visit the page. The beacon must not be injected.

- Modify the script to enter an infinite loop..
- Clear critical images and cache, enable cache.
- Visit a page. The beacon must be injected, and the critical image table must store a row with a failed status and the error_message mentioning time out, after ~10 seconds.
- Re-visit the page. The beacon must be there but it should not throw any errors as it bails out early.
- Clear the cache. Re-visit the page. The beacon must not be injected.

**Additional information**
- @gmetais, could you check this issue, how to implement it or review the grooming if already done?

Implementation suggestions:
- For error handling, I think we could:
    - add try/catch to wrap-up all the logic in the beacon script.
    - In the catch, send a payload to the AJAX endpoint with status "failed" and the error_message.
    - In the AJAX endpoint, handle this case to store it in the DB
- For time out, we could use setTimeout at the beginning of the script, and closeTimeout at the end of it. In case the timeout is triggered, we'd send an AJAX call with the failed status.

- One case won't be covered here: if the error happens when sending the failure data to the AJAX, or if we bail out in the AJAX endpoint itself. I think this is acceptable.

**Comment by gmetais** [comment]
Your approach seems correct to me. 

If think we should be more precise here: 

> "If the beacon script takes longer than 10s to execute, this info must be sent to the AJAX endpoint."

A JS script rarely _executes_ for more than 100ms. Except if the script waits for something else. So I presume you mean it waits a maximum of 10s for the LCP image to be detected. Is it what you meant? Unfortunately, it is very common that users on bad networks wait the LCP for more than 10s, so a timeout here could trigger quite often and prevent future LCP optimizations on the page. Can you please add details?


I would also suggest the following adjustments:

1. In addition to sending a new AJAX request, error catching should probably write an explicit error in the console, stating that the error comes from the WPR LCP optimizer. It should not fail silently (or display a JS error that nobody understands such as the typical "Cannot read properties of undefined") so that webmasters spend less time debugging.
2. Error catching should also detect if a network error or server error (404, 40X, 50X, etc.) occurs on the AJAX request itself and should probably NOT send another AJAX request containing that error, as the same route has a high risk to fail a second time.
3. We should specify a failure rate above which the beacon would not be injected on the page anymore, so that rare errors don't disable the beacon for 100% of the following users.
4. Maybe the new AJAX route could be tested from within the WPR admin interface, once the webmaster activates the LCP optimizer, and instantly display a message if the browser can't reach the endpoint for any reason.

Hope it can help.

**Comment by MathieuLamiot** [comment]
Thanks @gmetais.
About the timeout, I mean if there is more than x seconds between the first and the last line of the script are executed. We don't have a precise use-case in mind, it is for bullet-proofing. It could be an "almost" infinite loop, AJAX request hanging, ... Of course there is always a risk of false positive, it's a trade-off between taking the risk to have a script hanging for everyone, or being too cautious and failing too often pro-actively. What could change a bit my thinking:  am not sure about what you describe: does the beacon script actually "waits" for images to be loaded? I am not sure about this, can you confirm that our script implementation behaves like this? If it does, false positives will be more likely in case of bad network typically yes. If it does not wait for the content to be loaded (after all, it just needs image position & dimensions), false positive will be very unlikely.
I would be surprised that it waits for the content as it the script performs as expected even when blocking requests to fetch media content.

Thank you also for the valuable suggestions ; they are definitely worth considering for future enhancements.
Point 1, 3 & 4 would be possible enhancements, but more for a product decision @piotrbak & @DahmaniAdame as they would make the feature less "transparent". 1 could bring more support requests for minor issues, we usually avoid this. 3 was discussed but removed from the spec in the process if I recall correctly.
Point 2 could be a possible enhancement but it seems a bit overkill for an initial release.

**Comment by gmetais** [comment]
Thank you, I better understand your point of view about the timeout. You are right, the script doesn't wait for images to load and the whole "main" function is synchronous. Except for the AJAX request. I think we should specify if we include the AJAX request response time in the timeout.

And I would suggest not to include it, as the AJAX response time depends on factors such as network conditions and network concurrency with other requests with a higher HTTP/2 priority. Then, if we don't include it, having a script executing for 10s is HUGE! I means that it blocks the main browser's process and nothing else can happen on the page for 10 seconds. I would already be worried if that script, supposed to improve perf, was running on the main process for more than 100ms.

I've started to review the beacon's script and I have a few suggestions, on which PR or channel should I write them?

**Comment by MathieuLamiot** [comment]
Maybe it's best not to include the AJAX call in the try/catch: if it fails, then the call to tell the plugin that there was a failure is likely to fail as well, so overall, maybe just not try it.
We can of course lower the 10s suggestion. I would not go too low however because the script (when successful) runs once and bails out early for future visits (or is not injected at all). So I think we'd rather avoid false positive even if it means having the very first visit possibly a bit slow.
We could start with 500ms, make it filterable, and assess.

About the beacon script implementation, it is being actively reworked so chances are its implementation will highly change in the upcoming days. Maybe you can share your thoughts directly with @Miraeld and @wordpressfan?
