### ISSUE TITLE
Should fetch up to 10 valid (internal) links from Homepage and expand search for valid links  beyond the 1st 10 if needed

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6573]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 5.16-alpha1 ✓
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
Currently, if we use a template with external URLs between the first 10 URLs, we will fetch only the ones that are not external, so from the first 10 we end up fetching less than 10 URLs.

**To Reproduce**

1. On new.rocketlabsqa.ovh set  "homepage_ext_int_relative_absolut_URLs" as Homepage.
2. Clear Critical Images to trigger link fetching.
3. Check the "Add to queue request arguments" logs in wp-rocket-debug.log.html.
4. Only 4 links are fetched (as only 4 are internal valid links from the 1st 10), even though there are plenty of valid URLs beyond the first 10. 

**Expected behavior**
Up to 10 internal links should be fetched and checking for valid ones should go beyond the 1st 10 links if the case. 

**Screenshots**
For the homepage in step 1, only 4 links are fetched, the ones highlighted in the screenshot below:
![Screenshot 2024-04-18 at 15 51 58](https://github.com/wp-media/wp-rocket/assets/93833759/cb84e9a3-5e94-40e8-9fc4-c12031194242)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by jeawhanlee** [comment]
@hanna-meda I think this behaviour is expected, going by your screenshot, the other links will not be added as they are duplicates of https://new.rocketlabsqa.ovh/cover-galleries/ which has already been added with the 4 so there's no point sending it to the SaaS more than once. I hope I got your scenario clear.

@MathieuLamiot Do I block this issue till @hanna-meda is available.

**Comment by MathieuLamiot** [comment]
@jeawhanlee You should directly discuss the scenario & screenshot with @hanna-meda to get a clear understanding, yes.

To make sure this issue does not occur again, what you could do is pro-actively check in the codebase if we have a test case covering this scenario (homepage with external URLs before the 10th internal URL-> 10 internal URLs should be warmed-up) so that, not only we ensure there is no issue to fix and we don't have to test this manually ever again.

**Comment by jeawhanlee** [comment]
We already have tests for this but the scenario in question here is not handled, I'll open a PR on test that covers this.

**Comment by hanna-meda** [comment]
@jeawhanlee , @MathieuLamiot Apologies for this oversight. I'm at fault—I tested multiple scenarios and overlooked updating the template on the server with the correct URLs. After rectifying this, everything now behaves as expected.

**Comment by MathieuLamiot** [comment]
🙏 At least we got a meaningful test scenario in our integration test added 👍
