### ISSUE TITLE
WPR Settings page fatal error when debug file is so large even though debug mode is disabled

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6581]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
When we leave our debug mode enabled for some time, we find that the file grows rapidly and in some cases it exceeds 500MB without a limit.
We expect when we disable this debug mode, that this large size of the log file won't affect the site at all, but I found that we load the file in our Settings page (exactly in tools section) and this is loaded even when we disable the debug mode.

In a customer's site, this led to full memory consumption.

The code is here:
https://github.com/wp-media/wp-rocket/blob/cc3edc25191b69fa7d90ce6744c010d83415f4f8/views/settings/page-sections/tools.php#L15-L28

and this code is only used in a commented area here:
https://github.com/wp-media/wp-rocket/blob/cc3edc25191b69fa7d90ce6744c010d83415f4f8/views/settings/page-sections/tools.php#L99-L118

**To Reproduce**
1. Enable our debug mode by setting the constant `WP_ROCKET_DEBUG` to true in `wp-config.php`
2. Enable the preload and wait some time till preload finishes and the log file is large.
3. Keep doing point 2 till the log file exceeds the memory limit in WP (or u can fill the file manually if u don't want to wait)
4. Visit the settings page
5. You will see a fatal error because of full memory consumption.

**Expected behavior**
We should remove this code completely because it's not used anymore and is affecting the memory consumption.

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.


It might be the part of #6618
