### ISSUE TITLE
LCP/ATF Warm up process not blocked on local env

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6589]
**Is your feature request related to a problem? Please describe.**
We are fetching links to send for warm up even on local

**Describe the solution you'd like**
We need need to check the env (local or not) before sending for warm up.

**Describe alternatives you've considered**

**Acceptance Criteria**
1. If we detect the local environment the whole prewarmup process should be deactivated
2. The manual visits should still create the LCP/ATF data on local environment
3. Buttons that are clearing data related to this feature should still be present on local environment
4. No regressions related to the prewarmup process on life environments

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
  I was able to reproduce this on local
  - Set WP_ROCKET_DEBUG to true
  - Perform any of the actions that triggers the warmup(activate, clear critical images, upgrade to 3.16)
  - See logs

### Identify the root cause ✅
  We don't bail out [here](https://github.com/wp-media/wp-rocket/blob/34c55e91f438361f95714a4be50f15ac59c3baff/inc/Engine/Media/AboveTheFold/WarmUp/Controller.php#L61) when env is local.

### Scope a solution ✅
  In `Engine\Media\AboveTheFold\WarmUp::Controller`
    - Add a condition in this [method](https://github.com/wp-media/wp-rocket/blob/34c55e91f438361f95714a4be50f15ac59c3baff/inc/Engine/Media/AboveTheFold/WarmUp/Controller.php#L61) to bail out when env is local.

  Update tests.

### Estimate the effort ✅
[XS]

**Comment by remyperona** [comment]
LGTM
