### ISSUE TITLE
Warmup needs to generate desktop and mobile data

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6590]
**Context**
In 3.16 pre-warmup for LCP/ATF images optimization will be introduced. We need to make sure that both, desktop and mobile versions are generated.

**Expected beavhior**
When sending requests to the SaaS, we need to make sure to ask for desktop and mobile data (when Mobile Cache is enabled).

**Acceptance Criteria**
1. When RUCSS is enabled, we're not sending the pre-warmup requests. No regression here, both desktop and mobile (if Mobile Cache is enabled) are generated during the real visits only
2. When RUCSS is disabled + Separate Mobile Cache is disabled, we'll send requests related to desktop data
3. When RUCSS is disabled + Separate Mobile Cache is enabled, we'll send requests related to desktop and mobile data
4. For both points 2 and 3 after some time, relevant requests from the SaaS will be made.
5. Requests from the SaaS are supposed to generate the data. The visits need to happen on the query string URL that allows WP Rocket to add dimensions to the images.

**Additional information**
Make sure to test it with https://github.com/wp-media/wp-rocket/issues/5992

**Comment by remyperona** [comment]
### Scope a solution ✅ 
#### Engine\Media\AboveTheFold\WarmUp\Controller
- add private method to check if mobile options are enabled
- in `warm_up`, check if mobile, and add an additional `send_to_saas()` request, with the is_mobile parameter
- in `fetch_links()`, pass a new parameter `is_mobile`, and if true, change the user agent to a mobile value
- in `send_to_saas()`, pass a new parameter `is_mobile`, and pass the value to `add_to_atf_queue()`
- Update related tests

#### Engine\Media\AboveTheFold\Warmup\APIClient
- in `add_to_atf_queue()`, pass a new parameter `is_mobile`, and add its value to the `config` array with a `is_mobile` key
- Update related tests

### Estimate the effort ✅
Effort [S]

**Comment by MathieuLamiot** [comment]
Blocked pending merge with Get rid Of Cache tab

**Comment by hanna-meda** [comment]
Related Test Run [HERE](https://wpmediaqa.testrail.io/index.php?/runs/view/850&group_by=tests:assignedto_id&group_order=asc)
