### ISSUE TITLE
LCP/ATF data is malformed when no LCP is found by the beacon

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6591]
**Before submitting an issue please check that you’ve completed the following steps:**
- From feature/lcp-above-the-fold-optimization on commit 91077f9ce8caa90e4c062661620d5eea48d69c21

**Describe the bug**
When no LCP is found by the beacon, the LCP value in the DB is `null` instead of `not found`. This makes the `has_lcp` check not working as expected and as a result, the PHP code throws some errors and warning, trying to call some stuff on null.

**To Reproduce**
See video [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1714046628790889?thread_ts=1714044259.441869&cid=CUT7FLHF1)
- Go on your E2E website.
- Add this in your wp-config.php (to target staging SaaS, might work without it too): `define( 'WP_ROCKET_SAAS_API_URL', 'https://rucss-director-staging.public-default.live2-k8s-cph3.one.com/' );`
- Install the plugin (or do Clear Critical Images).
- Visit http://xxx.e2e.rocketlabsqa.ovh/category/uncategorized/ to gather the LCP/ATF. There is no LCP.
- check in the DB, the LCP for this page is null
- Clear the cache.
- Re-visit the page in incognito. The error should be in the log.

debug logs:

```
[25-Apr-2024 11:58:30 UTC] PHP Warning:  Undefined property: stdClass::$type in /var/www/html/mathieu.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/AJAX/Controller.php on line 103
[25-Apr-2024 11:58:30 UTC] PHP Warning:  Undefined property: stdClass::$type in /var/www/html/mathieu.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/AJAX/Controller.php on line 105
```

**Expected behavior & AC**
- No errors should be thrown when re-visiting the page.
- When LCP is not found, in the DB, it should be 'not found' instead of null. 
- When no WTf found, in the DB, it should be []. (Currently seems OK)
- We must have a test (maybe E2E if integration can't run the JS?) on template without LCP.

**Additional context**
The issue seems to be with recent merges in the beacon script. I suspect there are 2 blocks of code handling LCP and one should not be here:

```
	// Filter the array based on the condition imageURL is not null
	const filteredArray = LCPCandidates(1)
	if (filteredArray.length !== 0) {
		console.log("Estimated LCP element:", filteredArray);
		performance_images = filteredArray.map((item) => ({
			src: item.imageURL,
			label: "lcp",
		}));
	} else {
		console.log("No LCP candidate found.");
	}

	// Use LCPCandidates function to get all the elements in the viewport
	const above_the_fold_images = LCPCandidates(Infinity);

	const firstElementWithInfo = above_the_fold_images.find(item => item.elementInfo !== null);

	if (firstElementWithInfo) {
		performance_images = [{
			...firstElementWithInfo.elementInfo,
			label: "lcp",
		}];
	} else {
		console.log("No LCP candidate found.");
```

*MOVED BACK TO TODO WITH A DEEPER INVESTIGATION, SEE BELOW*

**Comment by MathieuLamiot** [comment]
Bringing back to ToDo as this is not fixed: I still have errors when re-visiting the page and the LCP value in case of not found is not "not found" but null.
There are several issues:

1. the beacon script sends an "image" with lcp label, even if there is no element.
To fix this, I modified "topCandidates" in the beacon by adding a filter to take out items where the getElementInfo did not find anything relevant:
```
	const topCandidates = potentialCandidates.map(element => {
		const rect = element.getBoundingClientRect();
		return {
			element: element,
			rect: rect,
		};
	}).filter(item => {
		return (
			item.rect.width > 0 &&
			item.rect.height > 0 &&
			isIntersecting(item.rect)
		);
	})
	.map(item => ({
		item,
		area: getArea(item.rect),
		elementInfo: getElementInfo(item.element),
	}))
	.filter(item => {
		return (
			item.elementInfo !== null && 
			item.elementInfo.type !== ""
		);
	})
	.sort((a, b) => b.area - a.area)
	.slice(0, count);
```

The issue is that, even if getElementInfo does not find anything, it returns an elementInfo with a dummy structure. Hence, the check later on `const firstElementWithInfo = above_the_fold_images.find(item => item.elementInfo !== null);` seems useless! There will always be a elementInfo ; but a dummy one sometimes.
It might not be the right way to do it, but the 1st issue is here: notice that without this fix, we don't have the log "No LCP element found" on http://mathieu.e2e.rocketlabsqa.ovh/ for instance. This shows that the beacon thinks there is an LCP becasue it does not filter out empty/irrelevant elements.

2. Once this is fixed, instead of null in the DB, I get `"not found"`. Be careful, the `"` are actually in the string! This leads to the following warning logs:

```
[25-Apr-2024 16:53:58 UTC] PHP Warning:  Attempt to read property "type" on string in /var/www/html/mathieu.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 250
[25-Apr-2024 16:53:58 UTC] PHP Warning:  Attempt to read property "type" on string in /var/www/html/mathieu.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 143
```

The issue is: the check in `has_lcp` `$lcp !== 'not found' ` is true because `'"not found"' !== 'not found'`
I think the additional " comes from the use of `wp_json_encode` in `'lcp'           => wp_json_encode( $lcp ),`
two choices here: either change how we write into the DB in case $lcp = 'not found' to avoid adding the additional ", or change the `has_lcp` check.

After this, it seems working as expected, without logs.

One should check this, fix and ensure the modifications don't break tests on Rocket-E2E.

**Comment by Mai-Saad** [comment]
Note: other page template without images on e2e https://e2e.rocketlabsqa.ovh/lcp_no_images/
