### ISSUE TITLE
Update build script to generate production scripts individually

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#6601]
**Context**
The current build command generates multiple production scripts at the same time.

**Expected beavhior**
We should have a command to build each script individually, and one command to build everything.

**Comment by wordpressfan** [comment]
I created this PR: #6625 to validate the idea with you before completing the code there.

As u can see, I created a new directory for gulp inside `src/js` with the following structure:

![image](https://github.com/wp-media/wp-rocket/assets/146129302/179f1bc4-9f6c-4e49-82da-53050511dbf2)

and as an example, I created a simple task module `css` which defines gulp tasks based on the data passed from the `gulpconfig.js` file.

We can do another task module for `js`, also I need to enhance the watch and build params so if we built the code many times to only get one version without any other changes until a change in the source file happens.

**Comment by Miraeld** [comment]
Looks ok to me
