### ISSUE TITLE
3.16 - Display a notification after 3.16 update

### ISSUE THREAD

**Issue by benorfaz** [wp-media/wp-rocket#6606]
Changes we are introducing in 3.16 are either not visible or disturbing:
- LCP/ATF is not a visible feature in UI, and you don't read changelog or missed our communications you're not aware of it
- Removing cache tab can be disturbing

To avoid this we should display a permanent banner on the 3.16 version or a notification after plugin update with following content:

**WP Rocket:** the plugin has been updated to the 3.16 version. Our brand new feature [Optimize critical Images ](https://docs.wp-rocket.me/article/1816-optimize-critical-images?preview=662c1a144c3ddc1d4e7a1d25) is automatically activated now! Also, the Cache tab was removed but the existent features will remain working, [see more here](http://link-to-the-blog-post/).

**Comment by piotrbak** [comment]
@benorfaz should this be a non-dimissible notice, or should we allow customers to dismiss it?

What about potential hotfix releases, 3.16.0.1, etc?

**Comment by piotrbak** [comment]
**Acceptance Criteria**
1. We'll display a blue notice with the wording present at the bottom of AC
2. The message will not have the `x` on the right side to close it
3. The message will have a button called `Dismiss this notice` which will dismiss it and don't show again
4. The message will be displayed only when updating from the version lower than 3.16. (3.15.x to 3.16 displayed; 3.16 to 3.16.0.1 not displayed; 3.15.x to 3.17 displayed;)
5. The message will not be displayed for fresh installations
6. When it's QA'd, we need to send it to translation

**The message:**

```
**WP Rocket:** the plugin has been updated to the 3.16 version. Our brand new feature Optimize critical images is automatically activated now! Also, the Cache tab was removed but the existent features will remain working, see more here.
```
`Optimize Critical Images` will link to: English: https://docs.wp-rocket.me/article/1816-optimize-critical-images (662c1a144c3ddc1d4e7a1d25); French: https://fr.docs.wp-rocket.me/article/1819-optimiser-images-essentielle (6634e9fe0cfcb4508af6b290)
`see more here` will link to: English: https://docs.wp-rocket.me/article/1817-removal-of-the-cache-tab
(6633b5df1009cb439ac6a432); French: https://fr.docs.wp-rocket.me/article/1818-suppression-onglet-cache (6634e9b21009cb439ac6a6fb)

Ping @benorfaz @MathieuLamiot @DahmaniAdame

**Comment by remyperona** [comment]
Could you provide the IDs for the docs, and same for the FR versions?

Also, I'm not sure how we can handle the old version check, because we're not in the update process, so that value is no longer available, as we don't store it.

Same for the fresh install, we don't have an indication that the current installation is new.

**Comment by piotrbak** [comment]
@Tabrisrp I added missing data
