### ISSUE TITLE
Form Autofill not working in wordpress when WPROCKET enable.

### ISSUE THREAD

**Issue by azim0106** [wp-media/wp-rocket#6616]
Hello All,

Please someone help me regarding Form Autofill, when WProcket enable then Value not filled in form on this link https://www.khaish.com/saree-made-to-measure-form/?Id=23683&v=c86ee0d9d7ed, but if i deactivated wprocket in plugins then first 4 field came auto filled. I am using Contact Form 7 Plugin.

I have enable Minify Js and JS deferred in wprocket

Thanks

**Comment by piotrbak** [comment]
Hello, this sounds like a question to the Support Team. Please use the following URL:
https://wp-rocket.me/support/
