### ISSUE TITLE
Increase PHPStan to rule level to 1

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#6621]
#6541  introduced PhpStan and started with level 0 conformance. Now we can increase the rule to further improve the codebase.

Once this is resolved, another issue should be created to bump the rule level again.

**Comment by piotrbak** [comment]
@MathieuLamiot WDYT?

**Comment by MathieuLamiot** [comment]
This is a must have! But it belongs to cooldown, not impacting the product itself.
