### ISSUE TITLE
Warmup URLs in database not matching those in WPR debug

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6624]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clear critical images , URLs in WPR debug (12 , 6 desktop and 6 mobile) while in the database only 3 URLs (1 mobile and 2 desktop => numbers here may vary but never = that in debug)

**To Reproduce**
1. WPR debug is on
2. Home page is set to page with certain URLs
3. 3.16 installed and activated
4. Clear critical images and notice ATF table compared to URLs in `Add to queue request arguments` in WPR debug and metabase

**Expected behavior**
URLs added to ATF like that in WPR debug (12 URLs, half mobile and half desktop)

**Screenshots**

**Additional context**
- in this case, only 5 entries added to metabase including home and 2 of them have net::ERR_TOO_MANY_REDIRECTS 
- tested on newlabs
**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.

**Comment by hanna-meda** [comment]
Here are a few more notes on this matter, for when this issue gets to be addressed:
- If XSS attack and commented URLs are between the first 10 links from homepage, they will be skipped, so present in `wpr debug` file but will not reach DB, which is correct, BUT no other URLs are picked up for warmup in their place. **Expected:** Should pick up other valid URLs, next in line, in their place, for warmup.
- URLs that never reach DB or only partially, on warmup:
              - https://rocketlabsqa.ovh/lcp_bg_multimage/ > while both desktop and mobile in `wpr debug` log file, only desktop version reaches DB - ATF table
              - https://rocketlabsqa.ovh/lcp_circular > while both desktop and mobile in `wpr debug` log file, no entries in DB
              - (home set to latest posts) https://rocketlabsqa.ovh/est-placeat-ex-minus-ut-voluptatibus > while both desktop and mobile in `wpr debug` log file, no entries in DB
