### ISSUE TITLE
Add section to `lcp_atf_elements`

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6631]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Sections are a likely element to hold the LCP element on semantic themes/page builders. 

Currently, the `section` element is not checked.

**To Reproduce**
N/A

**Expected behavior**
LCP elements set a background for a `section` element should be detected. 

**Screenshots**
N/A

**Additional context**
N/A

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by DahmaniAdame** [comment]
@piotrbak next minor 🙏

**Comment by MathieuLamiot** [comment]
To make sure we correctly target the expected behavior, would you be able to provide templates/pages or ways to create those pages to use for testing and validating? This could be used for Acceptance Criteria. Thanks.

**Comment by DahmaniAdame** [comment]
For testing/validation, any large `section` with a CSS background image will do. It's a technique overused on Elementor.
Eg. https://feli-site.willychataigner.com/
The LCP element return empty. After adding `section` to `rocket_lcp_data.elements` array, it returns a value.

**Comment by Khadreal** [comment]
This was a quick fix, created a PR here https://github.com/wp-media/wp-rocket/pull/6648

**Comment by MathieuLamiot** [comment]
Thanks! Can you ensure with the @wp-media/qa-team that we  add a test for this? I'm guessing a template for Rocket-E2E?
If it needs a dedicated issue, please create it. Otherwise, it can be done as part of QA for this issue.

**Comment by hanna-meda** [comment]
@Khadreal, @MathieuLamiot added page https://e2e.rocketlabsqa.ovh/lcp_bg_img_in_section/ using `lcp_bg_img_in_section_template.php` template on Rocket-E2E

**Comment by MathieuLamiot** [comment]
So fast! Awesome :)
Adding the "test by devs" label then, if we can rely on E2E
