### ISSUE TITLE
Image Optimization Tab Update

### ISSUE THREAD

**Issue by marija-nikolic** [wp-media/wp-rocket#6632]
We would like to update the content for the Image Optimization Tab in the WP Rocket plugin. 

Current content:
<img width="595" alt="image" src="https://github.com/wp-media/wp-rocket/assets/68050407/ed01fb45-6dfc-4a90-8869-02d8e1680801">

New content for users who don't have Imagify:
<img width="579" alt="image" src="https://github.com/wp-media/wp-rocket/assets/68050407/afccc622-4e4d-4431-b320-d357d1167e1c">

New content for users who have Imagify plugin installed but not activated:
<img width="575" alt="image" src="https://github.com/wp-media/wp-rocket/assets/68050407/15857b4a-e331-43e9-b92a-26df87a01354">

👉 [Mocflow doc](https://wireframepro.mockflow.com/editor.jsp?editor=off&perm=Owner&projectid=MtikZt9NJh&publicid=f7eae94ccd71483c96e30142ef52864f&space=default#/page/De096a4d4ec5f8943a2493ebc18f5e3be/mode/design)

**Comment by remyperona** [comment]
Is the imagify banner expected to have dynamic data for the score, number of review and active installation?

**Comment by marija-nikolic** [comment]
> Is the imagify banner expected to have dynamic data for the score, number of review and active installation?

Yes, please, if possible :)
