### ISSUE TITLE
3.16: Hebrew letters break preload URL

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#6639]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On a site using Hebrew characters, we added the following preload element. The first `href` is incorrect, note `---.webp` in the filename:
`<link rel="preload" as="image" href="https://atr-law.co.il/wp-content/uploads/2023/01/---.webp" imagesrcset="https://atr-law.co.il/wp-content/uploads/2023/01/עדי-רידלמן-ראשי-ארוך.webp 558w, https://atr-law.co.il/wp-content/uploads/2023/01/עדי-רידלמן-ראשי-ארוך-200x300.webp 200w" imagesizes="(max-width: 558px) 100vw, 558px" fetchpriority="high">`

**To Reproduce**
1. Use the attached HTML, from the site in question: https://jmp.sh/81P3K2sa
2. Enable WPR 3.16

**Expected behavior**
The preload href should  have the correct image url

**Screenshots**

**Additional context**
Slack: https://wp-media.slack.com/archives/C072P5EU5DF/p1715963740147689
Ticket: https://secure.helpscout.net/conversation/2598441023/491689/?folderId=377611

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Khadreal** [comment]
@piotrbak , @webtrainingwheels please do we have a template to test this with. Couldn't replicate it, tried using the image url `wp-content/uploads/2023/01/עדי-רידלמן-ראשי-ארוך-200x300.webp` but couldn't

**Comment by webtrainingwheels** [comment]
@Khadreal Maybe you mean something different by template, but the original HTML is included in the issue - that didn't work?

**Comment by Khadreal** [comment]
Yes, that didn't work.
I saved the image with the same filename and extension and run it locally, I could see the `link` href showing the right filepath, let me try this on one of rocketlabs site

**Comment by mehedihasanziku** [comment]
![image](https://github.com/wp-media/wp-rocket/assets/48652123/65856833-5fff-405d-a9e3-2320a8328c9e)

right filename `/wp-content/uploads/2024/05/ציוד-סנפלינג-1-1.avif`
converted: `/wp-content/uploads/2024/05/----1-1.avif`

it's a big bug

**Comment by gizmond1982** [comment]
Hi @webtrainingwheels 
Is the fix is in new WP Rocket version 3.16.1.1 ?
