### ISSUE TITLE
Enable mobile cache button is not working in some cases

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#6643]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**

In this PR:
https://github.com/wp-media/wp-rocket/pull/6600/files#diff-808154db979cdc470bb9d67f22f47c3b27529476df03f52d1f3b9b39ab7dddd0

We removed part of the JS script from the minified version of wpr-admin script, exactly here:

![image](https://github.com/wp-media/wp-rocket/assets/146129302/3614efbd-d4f0-4956-9805-daf9879545ad)

It's exactly this part:

https://github.com/wp-media/wp-rocket/blob/0aed49be05580f0315570fc5afdd064d934881df/src/js/global/ajax.js#L199-L227

but it still there in the not minified version of the script here:

https://github.com/wp-media/wp-rocket/blob/afe019d352c153c1cfefbf73be51c000ff28b87f/assets/js/wpr-admin.js#L185-L207

This makes the button of enabling the mobile cache is not working by default and works only if we changed the value of the constant `SCRIPT_DEBUG` to be `true`.

**To Reproduce**
1. Open any WPR version lower than 3.16 and disable mobile cache.
2. Update to 3.16 and visit tools page in our WPR settings page.
3. Make sure that the constant `SCRIPT_DEBUG` is not added to `wp-config.php` file or set as `false`
4. Click on the button to enable mobile cache and notice the network tab
5. No request will be sent to enable that option.
6. Change the `SCRIPT_DEBUG` constant's value to be true and try again.
7. You should see the request sent in network tab and once refreshed, you will not see that button again.

**Screenshots**

https://github.com/wp-media/wp-rocket/assets/146129302/29aeae3c-abbe-4c18-bae2-ffc0b4f51c6f

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by wordpressfan** [comment]
Here we just need to rebuild the `wpr-admin.min.js` again using gulp `bundleJsWithoutWatch`

**Comment by Tatilomelino** [comment]
Hi, I'm having this same problem. Watch the video you posted here to follow the instructions, but I don't know how to open the screen you use in wp-config.php (see the attached screen). Could you please explain it to me?
Thank you very much in advance!
![Screen Shot 2024-05-23 at 15 41 40](https://github.com/wp-media/wp-rocket/assets/170666835/92ba8f40-4fd8-4682-809a-05bf63fe80c9)

**Comment by gpapazac** [comment]
Im opening the wp_config file and there is no SCRIPT_DEBUG line. i also updated the code you changed in assets/js/wpr-admin.min.js and assets/js/wpr-admin.js.min.map and nothing happened. The button is still there. a little help would be aprecciated

**Comment by simoclicks** [comment]
> Same problem here. I followed your instructions, but it didn't work.

**Comment by simoclicks** [comment]
It works Thank you

**Comment by omgwhatcanido** [comment]
3.16 WP Rocket version, no SCRIPT_DEBUG line, and the mobile cache button still does not work, still can't create mobile cache. I feel upset.

**Comment by clmnsm** [comment]
The button still does not work, even when adding the SCRIPT_DEBUG setting. 

Is there a fix that doesn't require downgrading?

**Comment by hasanaras8** [comment]
Weird but I can not downgrade and also see no debug code I am just stuck with plug in.
