### ISSUE TITLE
WP-Rocket/SaaS Crawl speed too fast

### ISSUE THREAD

**Issue by Greg4040** [wp-media/wp-rocket#6644]
Hi,
WP-Rocket/SaaS made 114,944 request in few minutes from 11 IP addresses. This is much too fast. 
Is our customer can slow down this crawl speed ?
Regards.

**Comment by piotrbak** [comment]
Hello @Greg4040 please open a ticket to our Support Team, that should not happen.
https://wp-rocket.me/support/

Thanks,
Piotr

**Comment by Greg4040** [comment]
Thank you for your response but I am not a WP-rocket customer (I am the hosting company).
No topic seems relevant to me in the list of https://wp-rocket.me/support/ form select.
Is there a support email address?
