### ISSUE TITLE
Optimize Critical Images - loading="lazy" attribute should be removed for the critical images

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#6657]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
WP Rocket will exclude the images from its own LazyLoad feature, and it also should remove the `loading="lazy"` attribute when it's being added. The critical images shouldn't be LazyLoaded in any case.

WP Rocket is just skipping whatever can't be lazyloaded with no extra processing: 
https://github.com/wp-media/wp-rocket/blob/38775324e680d7358bf0e60280abefffeb2f056e/inc/Dependencies/RocketLazyload/Image.php#L357-L360

Maybe WP Rocket should be removing `loading=lazy` when making any LazyLoad exclusions

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1716532054481149

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by benorfaz** [comment]
@piotrbak Please double-check with OG ticket support. If the user has explicitly disabled lazy loading on an image from the editor, we should consider following this instruction and not overwriting things in the background. This could be very misleading.

**Comment by remyperona** [comment]
Has a decision been made on this topic? If yes, can we have the ACs?

**Comment by piotrbak** [comment]
@Tabrisrp In this case we should be consistent in what we're doing for our lazyload:
1. If the image above the fold is excluded from our lazyload, we should also exclude it from the native lazyload
2. If it's LCP image which is also excluded from our lazyload, we should also exclude it from the native lazyload
3. The ATF/LCP exclusions should work without regression for our lazyload

@benorfaz This is just a ping to confirm that your comment is outdated, we discussed this one during the meeting.

**Comment by benorfaz** [comment]
> @Tabrisrp In this case we should be consistent in what we're doing for our lazyload:
> 
> 1. If the image above the fold is excluded from our lazyload, we should also exclude it from the native lazyload
> 2. If it's LCP image which is also excluded from our lazyload, we should also exclude it from the native lazyload
> 3. The ATF/LCP exclusions should work without regression for our lazyload
> 
> @benorfaz This is just a ping to confirm that your comment is outdated, we discussed this one during the meeting.

Yes, ignore it

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In the RocketLazyload library, `Image.php`
- method `lazyloadImages()`, if the image can't be lazyloaded, instead of bailing-out directly, add a `preg_replace()` to remove occurrence of `loading="lazy"`
- update fixture to add test case

### Estimate the effort ✅ 
Effort `XS`
