### ISSUE TITLE
Picture markup with media isnot handled correctly

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6660]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using page template with picture markup, not all the images are there in preload

**To Reproduce**
1. 3.16 installed and activated
2. Page template with picture markup i.e https://e2e.rocketlabsqa.ovh/lcp_picture_template2/
```
<picture class="picture_test2"> 
			<source srcset="<?php echo content_url().'/rocket-test-data/images/paper.jpeg' ?>" media="(max-width: 400px)"> 
			<source  srcset="<?php echo content_url().'/rocket-test-data/images/lcp/testjpeg.jpeg' ?>" media="(max-width: 800px)"> 
			<img src="<?php echo content_url().'/rocket-test-data/images/lcp/testwebp.webp'?>"> 	
		</picture>
```
4. Visit the page template
5. Clear cache and revisit the page template then check source
preload will be:
```
<link rel="preload" as="image" href="https://e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/paper.jpeg" media="(max-width: 400px)" fetchpriority="high"><link rel="preload" as="image" href="https://e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testjpeg.jpeg" media="(min-width: 400.1px) and (max-width: 800px)" fetchpriority="high"><link rel="preload" as="image" href="" media="(min-width: 800.1px)" fetchpriority="high">

```

**Expected behavior**
Preload has all images of the picture as mentioned here https://github.com/wp-media/wp-rocket/issues/6530

**Screenshots**

**Additional context**
- If picture with media min, we won't preload all images (agreed as edge case) https://wp-media.slack.com/archives/CUT7FLHF1/p1715951823499619?thread_ts=1715950164.201159&cid=CUT7FLHF1

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Miraeld** [comment]
Should be fixed with https://github.com/wp-media/wp-rocket/pull/6659
