### ISSUE TITLE
When the feature "CSS Background Images" is disabled, don't show the quick action button "Clear Critical Images"

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#6663]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Quick action "Clear Critical Images" is still shown despite disabling the feature "CSS Background Images".

**To Reproduce**
1. Disable CSS Background Images.
2. Save settings
3. Check quick actions button.

**Expected behavior**
We should not see the button "Clear Critical Images" if the feature "CSS Background Images" is disabled.

**Screenshots**
https://github.com/wp-media/wp-rocket/assets/87424739/59f14337-c4db-4327-acbe-ddb334827463

**Additional context**
/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
Hello @JerissCloudCenter and thanks for creating the issue.

"Clear Critical Images" button is not related to the CSS Background Images feature, it's rather related to the newly introduced feature in 3.16 that's enabled by default:
https://wp-rocket.me/blog/wp-rocket-3-16/
