### ISSUE TITLE
Lazyload background CSS isnot working correctly to relative BG images inside section

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6665]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16 , 3.15.10
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the background image inside the section markup has a relative URL, And lazyload background image is enabled. then images will be hidden.

**To Reproduce**
1. WPR 3.15.10 or 3.16 installed and activated
2. Enable LLBG image
3. Visit page template with the following markup
```
 <style>
    section {
      width: 100%;
      padding: 0 7%;
      display: table;
      margin: 0;
      max-width: none;
      background-color: #373B44;
      height: 50vh;
      background-image: url('/wp-content/rocket-test-data/image/test3.webp');}

      section:nth-of-type(2n) {
        background-color: #FE4B74;
        /*this will overwrite the other background image for your 2n sections*/
        background-image:url("/wp-content/rocket-test-data/images/lcp/testjpg.jpg");
      }
      </style>
```

**Expected behavior**
Images are displayed and lazyloaded if it wasn't LCP/ATF since 3.16+ of WPR

**Screenshots**
After enabling LLBG
![Screenshot from 2024-05-27 10-25-43](https://github.com/wp-media/wp-rocket/assets/76941962/510a6ed2-0ef4-435e-aefa-9db2a87323e0)
Before enabling LLBG
![Screenshot from 2024-05-27 10-23-38](https://github.com/wp-media/wp-rocket/assets/76941962/aa9b34df-b894-413f-8e1b-d2f4be7e14b4)

**Additional context**
- Test page with relative URL: https://new.rocketlabsqa.ovh/lcp_section_template_relative/
- Since 3.16+, if critical images were created before enable LLBG CSS, images will still be displayed till we clear critical images
- Test page with absolute URL: https://new.rocketlabsqa.ovh/lcp_section_template2/
- Manually excluding affected images will make the images displayed

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- Lazyload background image is working on bg images in section (relative /absolute URL) using single or multi-image markup
- If BG image is LCP/ATF, once preload is added to the source, the LCP/ATF images will be excluded from LL

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
