### ISSUE TITLE
href attribute and min-width and max-width properties are not handled properly when using the media attribute

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6669]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Y
- Used the search feature to ensure that the bug hasn’t been reported before - Y

**Describe the bug**
The `min-width` and `max-width` properties, and the `href` attribute, are not handled properly when using the `media` attribute

**To Reproduce**
1. Add this original markup to a page:
```
<figure class="figure-core-image post-featured single-image title-wrap">
	<picture class="core-image">
		<source type="image/webp" media='(max-width: 500px)' srcset="https://variance.pl/wp-content/uploads/2024/05/Kwiatowy-Ksiezyc-400x600.webp">
		<source type="image/webp" media='(min-width: 501px) and (max-width: 768px)' srcset="https://variance.pl/wp-content/uploads/2024/05/Kwiatowy-Ksiezyc-768x513.webp">
		<img class="skip-lazy" src="https://variance.pl/wp-content/uploads/2024/05/Kwiatowy-Ksiezyc-1348x900.webp" alt="Kwiatowy księżyc" title="Kwiatowy księżyc">
	</picture>
</figure>
```
2. Wait until OCI is applied
3. See the error, as the markup has turned into:
```
<link rel="preload" as="image" href="https://variance.pl/wp-content/uploads/2024/05/Kwiatowy-Ksiezyc-400x600.webp" media="(max-width: 500px)" fetchpriority="high">
<link rel="preload" as="image" href="https://variance.pl/wp-content/uploads/2024/05/Kwiatowy-Ksiezyc-768x513.webp" media="(min-width: 500.1px) and (min-width: 501px) and (max-width: 768px)" fetchpriority="high">
<link rel="preload" as="image" href="" media="(min-width: 768.1px)" fetchpriority="high">
```

Note how the `(min-width: 501px)` is duplicated, and how the `href=""`  is empty

**Expected behavior**
To keep the right markup for the images.

**Additional context**
Slack: https://wp-media.slack.com/archives/C072P5EU5DF/p1716817705159419
Ticket: https://secure.helpscout.net/conversation/2608014439/493689/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
The second part is related to this one:
https://github.com/wp-media/wp-rocket/issues/6660

**Comment by Miraeld** [comment]
Should be fixed with https://github.com/wp-media/wp-rocket/pull/6659
