### ISSUE TITLE
Delay JS removes HTML when a combination of meta and script -containing a charset- tags is used

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6678]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Our DJE optimization removes a portion of the HTML when a `<meta>` tag is followed by a  `<script>` tag containing a **charset utf-8** declaration.

Per @joejoe04 findings, it could be happening here: 
https://github.com/wp-media/wp-rocket/blob/0a34f3e049fade9fea057909c33665b92c707f88/inc/Engine/Optimization/DelayJS/HTML.php#L253

**To Reproduce**
1. On a template, add the following code: 
```
<meta name="generator" content="Site Kit by Google 1.121.0" />
<!-- Start of Sleeknote signup and lead generation tool - www.sleeknote.com -->
<script id="sleeknoteScript" type="text/javascript">
	(function () {
		var sleeknoteScriptTag = document.createElement("script");
		sleeknoteScriptTag.type = "text/javascript";
		sleeknoteScriptTag.charset = "utf-8";
		sleeknoteScriptTag.src = ("//sleeknotecustomerscripts.sleeknote.com/xxxx.js");
		var s = document.getElementById("sleeknoteScript"); 
		s.parentNode.insertBefore(sleeknoteScriptTag, s); 
	})();
</script>
<!-- End of Sleeknote signup and lead generation tool - www.sleeknote.com -->
```

2. Enable Delay JavaScript Execution
3. See the code being stripped, only the last comment will remain.
4. Remove the line: `sleeknoteScriptTag.charset = "utf-8";`
5. The code will be correctly optimized
6. rollback the previous change in step 4, 
7. remove the meta tag
8. the code will be correctly optimized 

**Expected behavior**
we should not remove HTML code

**Screenshots**

![MM6tQPe](https://github.com/wp-media/wp-rocket/assets/229406/c8aea8c4-fb05-4b0c-b9bf-b235d61e336a)
https://i.imgur.com/MM6tQPe.png

**Additional context**
**Ticket** https://secure.helpscout.net/conversation/2607038270/493519?folderId=8127822
**Slack thread 1**: https://wp-media.slack.com/archives/C43T1AYMQ/p1716900971061789
**Slack thread 2**: https://wp-media.slack.com/archives/C43T1AYMQ/p1716930920081289

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future. We might reopen it when fixing things related to Delay JS
