### ISSUE TITLE
Create lcp-beacon.js.map file to prevent 404 errors

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6679]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
User reported over a thousand 404 requests to the following file:
`/wp-content/plugins/wp-rocket/assets/js/lcp-beacon.js.map`

We do not create an `lcp-beacon.js.map` file, but we do create `lcp-beacon.js.min.map`.

Per Adame, this happens because we are linking directly to the `lcp-beacon.js.map` file from within `lcp-beacon.min.js` here:
`https://github.com/wp-media/wp-rocket/blob/develop/assets/js/lcp-beacon.min.js`

**Expected behavior**
We should either create the `/wp-content/plugins/wp-rocket/assets/js/lcp-beacon.js.map` file as well, or change the link to point to `lcp-beacon.js.min.map` to prevent these errors, regardless of the browser being used.

**Screenshots**
http://imageshack.com/a/img924/5278/4XnIfw.png

**Additional context**
Slack discussion - https://wp-media.slack.com/archives/C43T1AYMQ/p1716998481474829
Ticket - https://secure.helpscout.net/conversation/2610627585/494251

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by DahmaniAdame** [comment]
The other browser is Firefox dev.

```
Source map error: request failed with status 404
Resource URL: https://snabb.press/wp-content/plugins/wp-rocket/assets/js/lcp-beacon.min.js
Source Map URL: lcp-beacon.js.map
```

The issue is that we are linking the wrong source map to check :sweat_smile:

```
//# sourceMappingURL=lcp-beacon.js.map
```

It either needs to be:

```
//# sourceMappingURL=lcp-beacon.min.js.map
```

To target the source we have already created.

Or keep it as is, and name the source map `lcp-beacon.js.map` and stop creating the other one.

There is no naming convention. Both would work. The source map just needs to exist whatever its name is.
