### ISSUE TITLE
https://gr.example.com/wp-content/cache/background-css/gr.example.com/wp-content/cache/min/17/wp-content/themes/savoy/style.css?ver=1716839715&wpr_t=1716992982  not found

### ISSUE THREAD

**Issue by azwhale** [wp-media/wp-rocket#6680]
The files in the /wp-content/cache/background-css directory disappear after clearing the cache, causing many styles to be missing after some time. What is the reason for this?

**Comment by piotrbak** [comment]
Hello @azwhale this is a duplicate of:
https://github.com/wp-media/wp-rocket/issues/6340

**Comment by azwhale** [comment]
> Hello @azwhale this is a duplicate of: #6340

 thanks
