### ISSUE TITLE
Lazyload for CSS Background fails when there are multiple </head> elements in the HTML

### ISSUE THREAD

**Issue by rosamillan** [wp-media/wp-rocket#6686]
**Before submitting an issue, please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the HTML of a website has more than a <head>, WP Rocket prints the rocket_pairs code as many times as there are heads.

**To Reproduce**
1. Go to a website with 3 <heads> for example https://djalkemy.co.uk/promosignup/
2. Click on "view source code"
3. Scroll down to  rocket_pairs and it will be repeated as many times as there are heads.

**Expected behavior**
WP Rocket could do the replacement only for one (even if detects more than one <head>), to prevent this kind of issues,

Notes: https://secure.helpscout.net/conversation/2611222729/494361/
https://wp-media.slack.com/archives/C08N8J6VC/p1717167391101739

**Screenshots**
1. three (3) heads: https://prnt.sc/_at0R6xcfaEd
2. three (3) rocket_pairs code: https://prnt.sc/53_qKlT1f9x5

**Additional context**
This issue appears also with RUCSS: https://wp-media.slack.com/archives/C029G1B5HD2/p1716319555207749
Screenshots: https://prnt.sc/nlw8Sek7FWVD- https://prnt.sc/iVPNozgKFs9A

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by webtrainingwheels** [comment]
I think this issue is the same as this one?
https://github.com/wp-media/wp-rocket/issues/6227

**Comment by piotrbak** [comment]
Yes, it's a duplicate. We might revisit it when fixing things related to LL for BG CSS images
