### ISSUE TITLE
I need to setup WP-Rocket to work with multiple domain ( Not Multi Site )

### ISSUE THREAD

**Issue by AghaFarokh** [wp-media/wp-rocket#6687]
Hey
I know this is not an issue I'm sorry to ask it here but only devs can help me with this ( I've searched the whole net and this repo and couldn't find anything about this, so answering this may be helpful for others too who looking for this )
Here is what I need to be done
I'm pointing two domains on a single WordPress and rewriting urls using a conditional SITE_URL and HOME_URL in wp-config based on HOST
now I need to make WP-Rocket work with both domains
I have the domain Example.Com which is my main domain and I have Example.Net which is my secondary domain
I'm redirecting users from .Com to .Net based on geo location 
Now Wp rocket is working fine on my main domain can u help me what should I change to make my secondary domain work too ?
due to some problem I can't use WordPress Multisite so I need to make it on single site way
thank you in advance

**Comment by AghaFarokh** [comment]
I need to add this the both domains are loading the same pages and everything are same in both domains
the only difference is 
1. the domain
2. second domain has noindex, nofollow tags 

I've done this because I needed to redirect my country users to another domain to pervent filtering
so everything is the same on both domain I think it's not a big problem to make Wp-Rocket work on both domains

**Comment by AghaFarokh** [comment]
Btw , when I logged in via my second domain Wp-Rocket created a file under wp-content/wp-rocket-config
and showing a message on admin dashboard that " the domain has been changed " and since I dont press the button from the notification the both domain php files under wp-content/wp-rocket-config are exist and both domain is working fine
is it enough ? should I just ignore the warning message from wp rocket ? 
because now it's working fine

**Comment by piotrbak** [comment]
Hello, you might want to check this helper plugin:
https://github.com/wp-media/wp-rocket-helpers/tree/2fc42f191836740bbb2479ca22fe283b78f74b4c/various/wp-rocket-multiple-config-files
