### ISSUE TITLE
Warmup fetch links - Mobile version missing from DB (ATF table) for Homepage URL on fresh installs

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6697]
**Before submitting an issue please check that you’ve completed the following steps:**
 ✅ Made sure you’re on the latest version - 3.16.1
 ✅ Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The Mobile version of Homepage URL is missing from DB - ATF table when activating plugin after a fresh install.

**To Reproduce**
(Make sure the filter to disable the Separate Mobile Cache is not active)
1. Install WPR 3.16.1 & activate plugin
2. Inspect the DB - above_the_fold table
3. Notice that for Homepage URL there is only one entry, for Desktop

**Expected behavior**
Both Mobile and Desktop versions should be added in DB for home, on fresh install.

Other notes:
- Link requests sent to SaaS are fine. Both mobile and desktop for Home URL are present in logs.
- Trying out suggestion discussed in [thread](https://wp-media.slack.com/archives/CUT7FLHF1/p1717587455861739?thread_ts=1717587272.951999&cid=CUT7FLHF1) we get only Mobile and missing Desktop URL for home.
- All works fine for other actions that trigger the warmup process, i.e Clear Critical Images. 

**Screenshots**
![Screenshot 2024-06-05 at 15 18 33](https://github.com/wp-media/wp-rocket/assets/93833759/657312f1-9899-4995-bed1-6eebc7dc932c)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by remyperona** [comment]
Did we check on the SaaS side that the mobile request to the website happened?

If the request going to the SaaS is fine (as per note in the issue), it seems that it could be coming from there instead of the plugin.

**Comment by MathieuLamiot** [comment]
To check, I'd advise to use the SaaS Staging and check processed jobs on Metabase as explained here: https://www.notion.so/wpmedia/SaaS-testing-on-WP-Rocket-s-side-5cfe0ed5321f4263b4b8ffa32b9bb818?pvs=4#5581e2d6ef7f4b7c9f48bc939dc2cedd
