### ISSUE TITLE
Identify content-related HTML markups so that they can be precisely identified back when re-building the same page

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6698]
**Context**
For 3.17, we will need to identify some HTML markups with the beacon script during a visit, and then at the next page build, to apply some attribute to those exact markups.
We don't have a way to identify markups reliably across different page builds currently. This issue aims at providing prototypes to do this, with various approaches.

**Expected behavior**
When building several times the same WordPress page in the same configuration, we must be able to add an "identifier" attribute to the HTML markups we want. 
- It must be a reliable way so that, across different page builds on the same page, the markups must always get the same identifier.
- We must limit as much as possible adding identifiers to markups we don't care about (based on the EPIC card criteria: up to 3rd child-level of body, and specific markup types only). Depending on the approach, we are OK not to be very precise on this requirement.

**Additional information**
The identifier could be a hash, but depending on the approach, we might not have something unique to hash (typically with regex). An ID, number, or whatever is reproducible would be OK.

To tackle this R&D, we should build and add a callback to `rocket_buffer` that processes the HTML and adds the 'identifer' to the targeted markups. The callback must be able to perform this with the following different approaches:

- Using DOMDocument: We know it will fail in some cases and we won't be able to do anything to fix it. But that's a good first step as we already have most of the code available in the EPIC Card. We should add a "fail safe" too, in case DOMDocument does not work.
- Using the WP HTML Parser: we don't know the features of this Parser and if it could do what we need. We don't know either if it will be more resilient than DOMDocument. To investigate and try.
- Using Regex: Go through all the markups matching our list, and add an ID to them (the order of match in the regex?). We will need to check this against large templates to see how CPU usage behaves. To do this, we would need a log measuring and returning the time it takes to run the callback.

**Comment by MathieuLamiot** [comment]
@Tabrisrp Hello, can you share an update on this?
There is a Product strategy meeting on Wednesday, it would be great if we can share an update on this, and maybe a draft PR allowing us to test & measure on some test websites. Thanks!

**Comment by remyperona** [comment]
Currently 3 different solutions are implemented:
- with DOMDocument
- with Regex (caveat on this one, the attribute is added on every matching element, no limit on the children tree)
- with HTMLDomParser library

There is also a measuring timer that will write in the error log the time it took for each execution.

The prototype is available on https://github.com/wp-media/wp-rocket/tree/prototype/lazyload-content-html-parsing branch, I'll create a PR right away.

**Comment by MathieuLamiot** [comment]
Moving back to In-Progress based on this report: https://wp-media.slack.com/archives/CUKB44GNN/p1720092702854049
Should investigate why hashes are the same.

**Comment by MathieuLamiot** [comment]
https://wp-media.slack.com/archives/CUKB44GNN/p1720196732934469

@Tabrisrp @hanna-meda We'll need to double check on new.rocketlabs and try to understand what can cause such a difference with rocketlabs for the regex approach 🤔

**Comment by hanna-meda** [comment]
@MathieuLamiot , @Tabrisrp on new.rocketlabs it does not reproduce. The same [template](https://github.com/wp-media/rocket-test-data/blob/master/templates/largehtmldiv_template.php) has been used across both envs.
After comparing the two setups, I've eliminated differences in wp-config.php, theme, and active plugins. Local testing with WP 6.5.5 and PHP 7.4.3 (to match rocketlabs) also didn't reproduce the issue.
I don't know what else to check further. If you can have a look, thank you. :pray:

**Comment by MathieuLamiot** [comment]
I can't think of something that would cause such a difference 🤔 
@Tabrisrp Unless you have another idea, maybe we can start by adding a few logs in the `foreach ( $matches as $child ) {` of the Regex method and reproduce the issue? I'm wondering if something makes each regex slow, or if the process just gets stuck?

**Comment by MathieuLamiot** [comment]
So I played a bit with the issue reported by @hanna-meda:
- On new.rocketlabs, the processing time reported for regex on the large template seems fast because the template is not processed actually. When using the "regex" processor, on [this template ](https://new.rocketlabsqa.ovh/largehtmldiv/), there are no changes applied to the HTML (after clearing the cache of course). I added logs and could see that the PHP code bails out in `add_locations_hash_to_html` (`if ( ! $result ) {`) @Tabrisrp 
- On [rocketlabs](https://rocketlabsqa.ovh/1ook_divs), the code does not bail out (I don't know why / what is different between the two HTML files). So on rocketlabs, the regex processor works. I added logs there too and optimized the code (see the branch prototype/lazyload-content-html-parsing-optimization-regex) a bit. Even with this, it processes ~200 markup per second which is very slow for what we want to do.

So for me, this disqualifies regex as a good candidate for this. @wp-media/qa-team, we would need you to confirm that
-  for the other processors (dom and simple dom), the results [here](https://wp-media.slack.com/archives/CUKB44GNN/p1720092702854049) and [here](https://wp-media.slack.com/archives/CUKB44GNN/p1720196732934469) are correct and that **they are measured on pages that are actually processed** (ie. on which the HTML is modified and we can see the new hash added to the markups, to avoid false measurements like on new.rocketlabs with regex).
- you have not been able to break the dom version (ie. markups are correctly processed on the templates you tested) even with "bad" HTML: missing closing tags for body and/or html? multiple header/body, etc.

**Comment by MathieuLamiot** [comment]
Based on [this discussion](https://wp-media.slack.com/archives/CUKB44GNN/p1720196732934469), DOM seems the suited approach here. We can stop working in this R&D for now, and pick up the branch/issue once we implement the front-end controller of the LCR feature.
