### ISSUE TITLE
[Optimize Critical Images] - Warning: preg_replace_callback(): Compilation failed: regular expression is too large at offset XXX when the URL is too long

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#6701]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
In this line: https://github.com/wp-media/wp-rocket/blob/38775324e680d7358bf0e60280abefffeb2f056e/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L151

When `$url` is too big, a warning is logged. Something like:

```
 [error] 104769#104769: *799886 FastCGI sent in stderr: "PHP message: PHP Warning: preg_replace_callback(): Compilation failed: regular expression is too large at offset 46859 in /www/eccouncilorg_350/public/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php
```

This is specially happening with base64 images.

**Shouldn't we exclude base64 images?**

**To Reproduce**
1. Set an LCP with a "src" that exceeds the amount of data that `preg_replace_callback` can manage (Depending on `pcre.backtrack_limit`).
2. Make sure above_the_fold table is clean for the specific page of the test
3. Visit the test page with the correct screen size
4. Clear the cache
5. See the error in logs

**Expected behavior**
This warning shouldn't appear

**Screenshots**

**Additional context**
https://wp-media.slack.com/archives/C072P5EU5DF/p1716994881749689

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by remyperona** [comment]
@DahmaniAdame @piotrbak Can you confirm if base64 images should be added as LCP image + preload link or not?

**Comment by piotrbak** [comment]
@Tabrisrp they can't be preloaded

**Comment by Khadreal** [comment]
I think this[ PR](https://github.com/wp-media/wp-rocket/pull/6677) should have fixed this, will try to reproduce on trunk and revert

**Comment by Khadreal** [comment]
We don't currently add base64 image to LCP, the next release would fix this
