### ISSUE TITLE
Cloudflare is deprecating their feature "Auto Minify"

### ISSUE THREAD

**Issue by JerissCloudCenter** [wp-media/wp-rocket#6705]
****Is your feature request related to a problem? Please describe.****

Cloudflare is deprecating their feature "Auto Minify" which is linked to WP Rocket when we enable the "Optimal Settings" in the Cloudflare Addon. WP Rocket could face issues when trying to enable these settings in Cloudflare if they do not exist anymore.

****Describe the solution you'd like****

Deprecate these features in the WP Rocket Cloudflare Addon "Optimal Settings".

****Additional context****

![image](https://github.com/wp-media/wp-rocket/assets/87424739/1b18ae99-225f-4628-8e5a-2eb1610611a5)

**Comment by piotrbak** [comment]
AC:
1. We'll need to remove the Auto Minify option from the Optimal Settings while enabling it
2. We'll need to remove the Auto Minify option from the Optimal Settings while disabling it
3. We'll need to confirm during the testing on the Cloudflare account that the Auto Minify settings are not changed
