### ISSUE TITLE
Is there any issue with license server and website?

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#6711]
Hello
Website is not loading and some websites time out due to license check.
Is there any issue with your server?

**Comment by piotrbak** [comment]
Hello @seldimi 

That rather sounds like a request for the Support Team, could you reach us and send the affected URLs?

**Comment by seldimi** [comment]
https://wp-rocket.me
Yes, seems the website is dead, so that was the only place i could post :)
So all websites that do license search (80 in my occasion), timeout on 5s

**Comment by E-VANCE** [comment]
Same here – license server & website are down...

Please investigate this & post a status update @piotrbak

**Comment by urbels** [comment]
Same here. Deactivated plugin for now.

**Comment by piotrbak** [comment]
We're actively working on the solution. The https://status.wp-rocket.me will be updated when done.

**Comment by E-VANCE** [comment]
Status page says "_All Systems Operational_" but I am still getting an error:

`cURL error 28: Failed to connect to wp-rocket.me port 443 after 10002 ms: Timeout was reached`
