### ISSUE TITLE
WP-Rocket outage today - Makes the plugin unusable

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [wp-media/wp-rocket#6713]
The outage with WP Rocket 10th June 2024 has highlighted a huge problem with how WP-Rocket works.

There appears to be a server connection request made on every uncached page by WP-Rocket - So during your outage. All 100+ websites we have running WP-Rocket are extremely slow.

**Describe the bug**
Without an active connection to WP-Rockets servers - WP-Rocket hangs during uncached page loads - Defeating the point of having it enabled.

**To Reproduce**

1. Load any wp-rocket website right now during your outage
2. Watch as both admin and front end are extremely slow because WP-Rocket requires a server connection

**Expected behavior**
In the event that your servers fall over - WP-Rocket shouldnt have to do a license check or check in with your servers to generate page cache. This is unacceptable for a premium plugin.

**Recommended solution**
Remove the check or connection to WP-Rocket made when any wp-admin, front end, back end page is viewed and when cache is generated - Especially when all functions that require a connection to wp-rocket are disabled (like critical css generation).

Please advise on how you propose on preventing WP-Rocket from failing to work during an outage again? We cannot have our entire pool of websites become slow because your server is down!

**Comment by JanThiel** [comment]
Totally agree. 
The 5s timeout added to each and every call is unacceptable.

**Comment by CyberCr33p** [comment]
As a web hosting provider, we have received numerous requests regarding this issue. We urge you to make the necessary changes to ensure it does not recur in the future.

**Comment by damienfinck** [comment]
Same problem for me

**Comment by bwafels** [comment]
Same here. The issue lasted a rather long time  tbh.

**Comment by Thibugs** [comment]
We also had this issue, making our website unavailable until we disabled the plugin

**Comment by thinkjarvisdesignandmarketing** [comment]
Following my original message - If it is checking the license or running a service that requires an external connection this is adding latency to cache generation and RUCSS services,

Once the server is back up and running we need a fix for this to prevent the repeated requests to connect to wp-rocket.

**Comment by kskonovalov** [comment]
Any updates here? Where's the wprocket team?

**Comment by piotrbak** [comment]
WP Rocket's team is working hardly to resolve the problem. We're sorry for the inconvenience, the final update will be sent here:
https://status.wp-rocket.me

**Comment by piotrbak** [comment]
Just to give you an update, since this morning we're receiving a huge DDoS attack. Thousands of different IP's (probably infected computers) are doing loop requests in the same time. We're working hardly to filter this traffic.

**Comment by JanThiel** [comment]
@piotrbak Thank you very much for the update. It still highlights that the dependency of your servers for all your customers to just run the Plugin is an unacceptable operational risk.

Please allow me a suggestion: As we were in the same position some time ago: Just move your origin servers behind Cloudflare, change your origin IPs and you are done with annoying DDOS attacks once and for all. We spent a week with targeted DDOS attacks but they were unable to penetrate Cloudflare.

**Comment by JanThiel** [comment]
Just for whoever is interested in reducing the impact of this without disabling the plugin. 
The API call uses the default WordPress timeout of 5s. It can easily be reduced to 1s by explicitly setting the timeout.

Patch `wp-rocket/inc/Engine/License/API/UserClient.php`
Add the `timeout => 1` after the body argument.

```
                $response = wp_safe_remote_post(
                        self::USER_ENDPOINT,
                        [
                                'body' => 'user_id=' . rawurlencode( $customer_email ) . '&consumer_key=' . sanitize_key( $customer_key ),
                                'timeout' => 1,
                        ]
                );
```

**Comment by omniacode** [comment]
> @piotrbak Thank you very much for the update. It still highlights that the dependency of your servers for all your customers to just run the Plugin is an unacceptable operational risk.
> 
> Please allow me a suggestion: As we were in the same position some time ago: Just move your origin servers behind Cloudflare, change your origin IPs and you are done with annoying DDOS attacks once and for all. We spent a week with targeted DDOS attacks but they were unable to penetrate Cloudflare.

The fact that they weren't already on Cloudflare is frightening, but it does look like they have made that move. Getting Cloudflare status pages now when trying to access their site(s).

This issue has bogged us down quite a bit today, hope there is a resolution soon.

**Comment by Mil1** [comment]
@piotrbak  Hi, maybe bad idea i don't know but...

Repond to all request validation to true, with simple static file for 1 or 2 days, to absorb the self-DDOS and when you see that ok, you can make normal validation. 

Good luck and I hope you find a solution.

**Comment by BowFarmer** [comment]
WP-Rocket servers came back online after being down for over 13 hours. They do need to change how their plugin validates licenses. They don't store license information locally for a long time. Just in transient records which expire after 24 hours. And then if their servers are down, your license expires and your site just crawls until their servers are up and running again.
Hopefully they will change that. Their plugin not functioning well if their servers are down is not a viable way to have a plugin that speeds up websites to work.

**Comment by thinkjarvisdesignandmarketing** [comment]
@piotrbak 
What a nightmare! Sounds like you need a better WAF!
I have to say from a Plesk point of view Imunify360 does an extremely good job at blocking DDOS. But I imagine your system will be more complex than that.

I run a busy agency as a sole trader with some contractors - I really shouldnt have to disable page caching because your server has issues. As a paying customer on a studio license this will render WP-Rocket not fit for purpose.

**Solution required**

1. Key functions in the plugin - using anything **THAT SHOULD NEVER DO A LICENSE CHECK** like standard page caching - Everything else off - 100% should not be making any calls to WP-Rockets server.
2. If RUCSS or any service that requires a connection to WP-Rocket to work - **Do a license check**
3. The license check should be every 30 days NOT every connection to improve the response time from your servers.
4. The license check timeout should be as small as possible make it 0.2 seconds lets say not 5 seconds
5. The license check **Should only run when looking at the WP-Rocket Settings screen in admin NOT EVERYWHERE**
6. The licesne check should never run when a visitor hits an uncached page - This means we are literally at your mercy. If your server doesnt respond our TTFB scores go down! This is absolutely stupid and counter-productive!
7. If point 5 in particular is not addressed as a direct response to this DDOS attack - WP-Rocket can no longer be seen as fit for purpose.
8. We only use the more advanced features of WP-Rocket on a handful of sites. So for us we could easy swap to WP3 Total Cache, AutoOptimize, Wp-Optimize, WP Super Cache, WP Fastest Cache, Breeze, Flying Pages **and get the same service for free**. We use WP-Rocket because of the extra tools that are useful on some of the more poorly coded sites we inherit. On sites we build free caching plugins would be more than adequate for our well optimised web system.
9. Following point 7 - Make me stay as a customer please. WP-Rocket when it works properly is a very good caching engine, none of the sites I have actually require RUCSS or CSS optimisation to pass web vitals. I want to make this clear - I use WP-Rocket because those extra settings are available for difficult sites. Therefore stop checking my F-ING license for everything when I am just using page caching for 90% of my projects!

I am hoping this helps provide clarity on what is required here. Too many connections to WP-Rocket. You cannot run your licensing like that.

**Comment by thinkjarvisdesignandmarketing** [comment]
**Guys - Please subscribe to the ticket below. The devs are asigned to this ticket:**
https://github.com/wp-media/wp-rocket/issues/6715

**Comment by mindctrl** [comment]
Please make license validation requests non-blocking. `wp_remote_get` / `wp_remote_post` support this. Also please consider caching errors/timeouts for some small period of time, so that sites don't go down or get very slow, while DDoS'ing your servers. Caching errors or timeouts for 5 mins would make all the difference in the world.
