### ISSUE TITLE
Avoid requests to wp-rocket.me to negatively impact site performances during downtime

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#6715]
### Is your feature request related to a problem? Please describe.
When WP Rocket (website) is down or slow, which can unfortunately happen, this creates slowness on every website checking for updates and license validity. 
The requests go in timeout (5 seconds). 

This creates multiple side effects : 
- Websites not in the cache are impacted
- Admin is impacted
- This potentially generates self-DDos as websites are constantly trying to validate the license 

We've discussed this issue each time we had downtime without tackling it. 
It's time to tackle before another upcoming issue.

### Describe the solution you'd like

1. **Checks for updates and license** are run at Rocket init (like today)
    - on all admin pages
    - on uncached pages
    - if DB says the check was already performed and was a success for the validity period (24h), it is skipped
2. Output of this check (in the plugin):
    - If successful:
        - No changes in actual behavior (db updated, and next check will occur in the next 24 hours)
    - If it fails:
        - For technical reasons:
            - Case 1: Too long to answer — Timeout
                - new non-aggressive retry strategy:
                    - retry every 3h for 72h
                        - then stop checking
                        - and display a message:
                            - ```License validation has failed for 3 days in a row. Please check the documentation for more information or contact support.```
            - Case 2: Response is 500
                - same strategy as timeout
3. Timeout is set to 5s, and a filter to change it is available
4. Clicking on "Refresh info" from My Account in Dashboard page performs the check

### Notes
This could be further improved and considered a minimum viable fix. In addition to changes made server-side, it is good enough to prevent this issue from happening in case of a new major outage.

**Comment by MathieuLamiot** [comment]
https://wp-media.slack.com/archives/CUT7FLHF1/p1718050008990249?thread_ts=1701270181.205299&cid=CUT7FLHF1

**Comment by trendymail** [comment]
Same problem here: https://wp-rocket.me/ is down.

Under Linux, you can "reject" immediately WP Rocket API queries:

`# cat /etc/hosts`
`127.0.0.1  wp-rocket.me`

Just make sure there is no service listening on port 443 on localhost.

**Comment by thinkjarvisdesignandmarketing** [comment]
@piotrbak  @jbma
Please can you consider only running the license check when WP-Rocket Settings are accessed? This reduces the burden massively.
This is how other premium plugins work. You cannot check the license server every X Hours. Just set it to check when WP-Rocket settings are accessed.

Please can you confirm what settings cause a license check?
Can you confirm if turning off certain settings stops connections to WP-Rocket's servers?

If you have RUCSS, Optimise CSS Delivery and Preload services turned off. The standard page caching features should NEVER do a license check. Because the actions all take place on the clients server. This is why it makes sense to only do a license check on the WP-Rocket Settings page when logged in as an admin or with permissions to access the WP-Rocket Settings page.

**Comment by BowFarmer** [comment]
Another option is to run the license check as a wp-cron job. Once someone has purchased WP-Rocket and received a license store the license locally. Licenses are good for a year. Why check them constantly? Have a cron job doing the check once a day at most or weekly.
In any case don't make the plugin dependent on whether your servers are up. And don't revoke the license locally until you get a valid response from WP-Rocket that the license is no longer valid or the license's expiration date has passed.

**Comment by thinkjarvisdesignandmarketing** [comment]
> Another option is to run the license check as a wp-cron job. Once someone has purchased WP-Rocket and received a license store the license locally. Licenses are good for a year. Why check them constantly? Have a cron job doing the check once a day at most or weekly. In any case don't make the plugin dependent on whether your servers are up. And don't revoke the license locally until you get a valid response from WP-Rocket that the license is no longer valid or the license's expiration date has passed.

This would be even more optimal than my suggestion - An extremely good point - Licenses are yearly. It only needs to check once on entry of a valid license and once after the expiry to reconfirm the subscription is still active.

**Comment by BowFarmer** [comment]
Another thing that needs to be clarified is in the license information that I saw stored in the transient wp_rocket_customer_data were settings for is_blacklisted, is_staggered, is_blocked. How do these get triggered?

**Comment by terpentyn** [comment]
In total I must say the response of the WP-rockets guys is almost non-existent. This way they’ll loose a lot of users.

**Comment by jbma** [comment]
@terpentyn I created that issue yesterday. 
Product development isn't done in a day, we've a roadmap and some features we are already working on. 
We've been quite busy in the latest hours making sure our website is live as soon as possible. 

I'm locking the conversation, as this Github issue should be used by Product and Developers of WP Rocket to scope a solution and implement it in an upcoming minor version

**Comment by MathieuLamiot** [comment]
Plugin team, to whoever picks this grooming:
- [Here](https://www.notion.so/wpmedia/Avoid-requests-to-wp-rocket-me-to-negatively-impact-site-performances-during-downtime-036ac16f9b464f72b04de58cf06647f5?pvs=4) is the notion page (mostly identical to the GH issue description).
- [Here](https://wp-media.slack.com/archives/CUT7FLHF1/p1718893053062419?thread_ts=1701270181.205299&cid=CUT7FLHF1) is a Slack discussion for an update on endpoint lists and existing mitigations, etc.
