### ISSUE TITLE
FetchPriority should ignore inline images (e.g. encoded SVgs)

### ISSUE THREAD

**Issue by giedrius** [wp-media/wp-rocket#6726]
Hello, 
set_fetchpriority should ignore above the fold images that are inline encoded in src data  (<img src=“[data:image/svg+xml;base64,PCFET0NUWVBF](data:image/svg+xml;base64,PCFET0NUWVBFIHN2Zy ..... ", as this neither needs fetching nor it will work correctly due to size limit of regular expressions in PHP. 

"PHP message: PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller::set_fetchpriority(): Return value must be of type string, null returned in /var/www/site_files/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php:166
Stack trace:
#0 /var/www/site_files/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(114): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller->set_fetchpriority()
#1 /var/www/site_files/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(86): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller->preload_lcp()
#2 /var/www/site_files/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Subscriber.php(46): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller->lcp()
#3 /var/www/site_files/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Subscriber->lcp()
#4 /var/www/site_files/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 /var/www/site_files/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters()
#6 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer()
#7 /var/www/site_files/wp-includes/functions.php(5373): ob_end_flush()
#8 /var/www/site_files/wp-includes/class-wp-hook.php(324): wp_ob_end_flush_all()
#9 /var/www/site_files/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /var/www/site_files/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /var/www/site_files/wp-includes/load.php(1260): do_action()
#12 [internal function]: shutdown_action_hook()
#13 {main}

**Comment by piotrbak** [comment]
It'll be solved in upcoming 3.16.1. If you'll still experience it, please reopen the issue
