### ISSUE TITLE
404 file mini file CSS & JS (When using Nginx Cache + Wp Rocket)

### ISSUE THREAD

**Issue by appstoreapk** [wp-media/wp-rocket#6731]
**Before submitting an issue please check that you’ve completed the following steps:**
- i use on the latest version

**Describe the bug**
- Nginx Cache is caching fully page html. But Wp rocket delete js & css min file daily. => And visitor visit page caching => can not display layout css js.

** Sugest to fix:
Add 1 Textbox is:  filename when merging compile
Example: 
https://domain.com/wp-content/cache/min/1/fd0898f54869f5eaa491afc755fef4b0.js
https://domain.com/wp-content/cache/min/1/fd0898f54869f5eaa491afc755fe1111.js
=> Convert into: 
https://domain.com/wp-content/cache/min/1/domain_0.js?t=${timeFileCreated}
https://domain.com/wp-content/cache/min/1/domain_1.js?t=${timeFileCreated}
or 
https://domain.com/wp-content/cache/min/1/${filename}_0.js?t=${timeFileCreated}
https://domain.com/wp-content/cache/min/1/${filename}_1.js?t=${timeFileCreated}

=> & All is fixed easy ^^ This is fix BUG 404 about Nginx Cache & WP Rocket

Please update add this feature into next version :D

**Comment by piotrbak** [comment]
Hello @appstoreapk 

WP Rocket is not deleting combined JS/CSS files daily, that sounds like a misconfiguration between your NGINX cache and WP Rocket. The easiest way to configure our plugin with NGINX cache is to use and set up 
https://wordpress.org/plugins/nginx-helper/
