### ISSUE TITLE
Not compatible with PHP 8.1

### ISSUE THREAD

**Issue by YasserDivaR** [wp-media/wp-rocket#6734]
I have this problem on my website with PHP version 8.1
WP-Rocket Tabs do not work properly
![2024-06-21_221740](https://github.com/wp-media/wp-rocket/assets/20362188/2c9cb0e9-8910-473f-8fbf-eb8365d4a3f3)

**Comment by benorfaz** [comment]
@YasserDivaR Not able to reproduce it. Please provide more information about the environment or contact the support team.
