### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, null given in /www/mysite_815/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RegexTrait.php:151

### ISSUE THREAD

**Issue by Venkat-gists** [wp-media/wp-rocket#6740]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
Yes 3.16.1.1
- Used the search feature to ensure that the bug hasn’t been reported before
Yes, this error was not reported earlier
**Describe the bug**
PHP message: PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, null given in /www/mysite_815/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RegexTrait.php:151
Stack trace:
#0 /www/mysite_815/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RegexTrait.php(151): str_replace(Array, Array, NULL)
#1 /www/mysite_815/public/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(188): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller->restore_html_comments(NULL)
#2 /www/mysite_815/public/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(119): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller->set_fetchpriority(Object(stdClass), NULL)
#3 /www/mysite_815/public/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(86): WP_Rocket\Engine\Media\AboveTheFold\Frontend\Controller->prel" while reading response header from upstream, client: xx.xxx.xx.x, server: www.mysite.com, request: "GET /mysite-level1/mysite-level2/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm-mysite
**To Reproduce**
I am able to see the error on site log when loading a page on mobile device

**Expected behavior**
No PHP Fatal error

**Screenshots**
NA

**Additional context**
NA

**Acceptance Criteria (for WP Media team use only)**
NA

**Comment by piotrbak** [comment]
Hello @Venkat-gists coud you plaese contact our Support Team and share access to your website, so we can investigate this issue and then we'll create new one with more details

**Comment by alfonso100** [comment]
I had a recent case where this error was triggered.
for internal reference: https://secure.helpscout.net/conversation/2650493328/502355?folderId=2683093

it also produces a 500 error only on the browser console, but without causing the site to go down (the pages load as expected with just the console error)
it was related to an incorrect LCP detection when a 3rd party lazyload was applied (Themify in my case)

We detected the SVG element and the LCP element was saved in this: 

`{"type":"img","src":"data:image\/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%221920%22%20height%3D%22700%22%3E%3Cg%20fill%3D%22%2346563d%22%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%236b6c5f%22%20x%3D%22640%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%237a6f61%22%20x%3D%221280%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23c1c8cf%22%20y%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23b0bfcd%22%20x%3D%22640%22%20y%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23dcd4c4%22%20x%3D%221280%22%20y%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%238eb295%22%20y%3D%22466%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23b2c1d1%22%20x%3D%22640%22%20y%3D%22466%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%237facc6%22%20x%3D%221280%22%20y%3D%22466%22%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E"}`

clearing teh LCP table and disabling the lazyload fixed the issue
