### ISSUE TITLE
Adjust lcp-beacon.min.js timeout to be relative to `rocket_lcp_data.delay`

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6741]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [x]
- Used the search feature to ensure that the bug hasn’t been reported before [x]

**Describe the bug**
If `rocket_lcp_delay` is superior to 10 seconds, that might be needed if a page has a heavy script that controls the layout, the beacon will return the right LCP but with a `failed` status. 

That failed status will prevent the buffer from adding OCI optimizations. 

This is caused by the `10` timeout limit located here:

https://github.com/wp-media/wp-rocket/blob/a8da7ae5fc1d1f524c4a9b625dc18456af176d7a/assets/js/lcp-beacon.js#L294-L296

Adjusting it to be relative to `rocket_lcp_data.delay` fixed the issue: 

```
window.rocket_lcp_data.delay + 10
```

**To Reproduce**
1. Add `rocket_lcp_delay ` with a value superior to 10
2. Check the beacon's AJAX request

**Expected behavior**
The timeout should take into consideration the LCP delay.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2615431939/495123?folderId=2952229

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Mai-Saad** [comment]
Reproducible by:
1- Add timeout at lcp_beacon.js
```
 _getFinalStatus() {
      setTimeout(() => {
        console.log("Delayed for 15 second.");
        if ("" !== this.errorCode) {
          return this.errorCode;
        }
       
  
        const scriptTime = (/* @__PURE__ */ new Date() - this.scriptTimer) / 1e3;
        if (10 <= scriptTime) {
          return "timeout";
        }
        return "success";
        
      }, "15000");
     
    }
```
2- enable script_debug at wp-config so non-min file is used
3- clear critical images then check DB => URLs are failed also data is there
4- visit uncached page of failed status and check the source => no script and no optimization is applied

For retest:
- while the filter rocket_lcp_delay is set to 15 secs , it shall work (status is completed) and add optimization to the page

**Comment by MathieuLamiot** [comment]
PR on rocket-scripts to merge then PR in WP Rocket with updated script files to create, review and merge.
