### ISSUE TITLE
Uncaught TypeError JobProcessor::send_api()

### ISSUE THREAD

**Issue by FlashFwd** [wp-media/wp-rocket#6744]
This error is in WooCommerce's Fatal error logs during the latest days. I don't know more context than the log provides. Everything is the latest version.

Uncaught TypeError: WP_Rocket\Engine\Common\JobManager\JobProcessor::send_api(): Argument #1 ($url) must be of type string, null given, called in /chroot/home/a44fd4a5/1bc4ad8411.nxcli.io/html/wp-content/plugins/wp-rocket/inc/Engine/Common/JobManager/JobProcessor.php on line 293 and defined in /chroot/home/a44fd4a5/1bc4ad8411.nxcli.io/html/wp-content/plugins/wp-rocket/inc/Engine/Common/JobManager/JobProcessor.php:339 CONTEXT: {"error":{"type":1,"file":"\/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-content\/plugins\/wp-rocket\/inc\/Engine\/Common\/JobManager\/JobProcessor.php","line":339},"backtrace":["","#0 \/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-content\/plugins\/wp-rocket\/inc\/Engine\/Common\/JobManager\/JobProcessor.php(293): WP_Rocket\\Engine\\Common\\JobManager\\JobProcessor->send_api(NULL, false, 'all')","#1 \/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-content\/plugins\/wp-rocket\/inc\/Engine\/Common\/JobManager\/Cron\/Subscriber.php(111): WP_Rocket\\Engine\\Common\\JobManager\\JobProcessor->process_on_submit_jobs()","#2 \/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-includes\/class-wp-hook.php(324): WP_Rocket\\Engine\\Common\\JobManager\\Cron\\Subscriber->process_on_submit_jobs()","#3 \/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#4 \/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-includes\/plugin.php(565): WP_Hook->do_action(Array)","#5 \/chroot\/home\/a44fd4a5\/1bc4ad8411.nxcli.io\/html\/wp-cron.php(191): do_action_ref_array('rocket_saas_on_...', Array)","#6 {main}","thrown"]}

**Comment by piotrbak** [comment]
Hello @FlashFwd we use Github for development purposes only. To take care of the bug we'd need to have the exact steps.

If you don't know the context, please contact our Support Team, so your site can be investigated and then we'll be able to create the issue with all needed details.
