### ISSUE TITLE
Relative paths to fonts in CSS file are minifed (or "busted") and included in the critical CSS

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#676]
When CSS files have relative paths to font assets they are:

-- Being minified/combined
-- Remove Query String option applied ("busted")
-- Being included critical CSS in the minified structure. See the following: https://gist.github.com/ernee/42eb0411e994ea2aacbc81e6a23194f8

Issue seen in this ticket: https://secure.helpscout.net/conversation/492274366/56215?folderId=1391600

**Comment by piotrbak** [comment]
Closing it until receiving more feedback from customers.
