### ISSUE TITLE
E_ERROR in 3.16.2: Argument #1 ($microseconds) must be of type int. In line 164 of PreloadUrl.php 

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6760]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We spot two cases of the following error: 

`An error of type E_ERROR was caused in line 164 of the file /home/nginx/domains/desiblitz.com/public/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php. Error message: Uncaught TypeError: usleep(): Argument #1 ($microseconds) must be of type int, float given in /home/---/public/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php:164
`

Case 1: https://secure.helpscout.net/conversation/2643362172/500880/
Case 2: https://secure.helpscout.net/conversation/2643668871/501005/

if `rocket_preload_delay_between_requests` is not an integer it will fail here https://github.com/wp-media/wp-rocket/blob/14040c58c6bfeb3786112f2e372309a2c4dd2b69/inc/Engine/Preload/Controller/PreloadUrl.php#L164

**To Reproduce**
1. Pass a non integer value via rocket_preload_delay_between_requests
2. See the error logged

**Expected behavior**
we should safeguard the value

**Additional context**
Slack convo: 
https://wp-media.slack.com/archives/C072P5EU5DF/p1720107216412569

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
While on this, the docblock for the filter must be fixed too. It says @param float. Bit we need an int.

**Comment by Mai-Saad** [comment]
Reproducible when updating/installing WPR while the filter `rocket_preload_delay_between_requests` is float

**Comment by sandyfzu** [comment]
Related: https://secure.helpscout.net/conversation/2644228223/501142/
