### ISSUE TITLE
3.17 - Beacon Script Implementation

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket#6780]
# Description

This issue requires the refactor of the beacon script to be done. In this issue, we will implement the `RocketLrcBeacon` class from `wpr-beacon.js` . The `RocketLrcBeacon` class is responsible for the Lazy Render Content (LRC) feature. The class will contain methods to handle the specific logic for the LRC process, including checking if an element is in the viewport, skipping certain elements based on specific conditions, and calculating the distance of an element from the top of the viewport. The prototype code provided will serve as a basis for the implementation.

# Scope a solution

- Create the `RocketLrcBeacon` class in the `wpr-beacon.js` file.
- Implement the constructor for the `RocketLrcBeacon` class, which will take a config object as a parameter.
- Implement the `run` method in the `RocketLrcBeacon` class. This method will contain the main process for the LRC feature.
- If not done already, implements generic helper methods in the `RocketBeacon` class based on the prototype code otherwise re-use them. These methods include `isElementInViewPort`, `getDepthAndDistance`, `getLocationHash` , `skipElement`
    - The `isElementInViewport` method will check if an element is in the viewport.
    - The `getLocationHash` method will get the location hash of an element.
    - The `skipElement` and `shouldSkipElement` methods will determine whether to skip certain elements based on specific conditions.
    - The `getDepthAndDistance` method will calculate the distance of an element from the top of the viewport.
- Remove any unnecessary code related to `XPath` from the prototype.
- Ensure that the `RocketLrcBeacon` class is properly integrated with the RocketBeacon class.
- Thoroughly test the `RocketLrcBeacon` class to ensure it works as expected.

# Additional

Prototype code: 

```jsx
function isElementInViewport(el) {
    const rect = el.getBoundingClientRect();
    return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        rect.right <= (window.innerWidth || document.documentElement.clientWidth)
    );
}

function getLocationHash(element) {
  // Check if the element has the 'data-rocket-location-hash' attribute
  if (element.hasAttribute('data-rocket-location-hash')) {
    // Get and return the value of the 'location-hash' attribute
    return element.getAttribute('data-rocket-location-hash');
  } else {
    // Return null or an appropriate value if the attribute doesn't exist
    return 'No hash detected';
  }
}

function getXPath(element) {
    if (element.id !== "") {
        // If the element has an ID, return the XPath with the ID
        return '//*[@id="' + element.id + '"]';
    }

    // Function to get the position of the element among its siblings of the same type
    function getElementPosition(element) {
        let pos = 1;
        let sibling = element.previousElementSibling;
        while (sibling) {
            if (sibling.nodeName === element.nodeName) {
                pos++;
            }
            sibling = sibling.previousElementSibling;
        }
        return pos;
    }

    // Recursively build the XPath string
    function getElementXPath(element) {
        if (element === document.body) {
            return '/html/body';
        }
        
        const position = getElementPosition(element);
        const xpath = getElementXPath(element.parentNode) + '/' + element.nodeName.toLowerCase() + '[' + position + ']';
        return xpath;
    }

    return getElementXPath(element);
}

function skipElement(element) {
    if (!element || !element.id) return false; // If element has no ID, don't skip it
    // Check if element's ID contains specific strings to skip
    const skipStrings = ['memex']; // Add more strings to skip as needed
    return skipStrings.some(str => element.id.toLowerCase().includes(str));
}

function shouldSkipElement(element, exclusions) {
    if (!element) return false;
    // Check if the element matches any of the exclusion patterns
    for (let i = 0; i < exclusions.length; i++) {
        const [attribute, pattern] = exclusions[i];
        const attributeValue = element.getAttribute(attribute);
        if (attributeValue && new RegExp(pattern, 'i').test(attributeValue)) {
            return true;
        }
    }

    return false;
}

function getDepthAndDistance(element, depth, viewportHeight) {
    if (depth > 3 || !element) return;
    
    const exclusions = [
	    ['id', 'memex'],  // Skip elements with id containing 'memex'
	    ['class', 'grecaptcha-badge']
	];

    const tagName = element.tagName;
    if (!['BODY', 'DIV', 'MAIN', 'FOOTER', 'SECTION', 'ARTICLE', 'HEADER'].includes(tagName) || shouldSkipElement(element, exclusions)) return; // Only process some specific tags, and skip elements with specific attributes

    const rect = element.getBoundingClientRect();
    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
    let distanceFromViewportTop = rect.top + scrollTop - viewportHeight;

    // Ensure distance is non-negative
    distanceFromViewportTop = Math.max(0, distanceFromViewportTop);

    // Apply styling based on distance
    let style = '';
    if (distanceFromViewportTop > 1800) {
        style = 'color: green;';
    } else if (distanceFromViewportTop === 0) {
        style = 'color: red;';
    }

    console.log(`%c${'\t'.repeat(depth)}${tagName} (Depth: ${depth}, Distance from viewport top: ${distanceFromViewportTop}px)`, style);

    const xpath = getXPath(element);
    console.log(`%c${'\t'.repeat(depth)}Xpath: ${xpath}`, style);
    
    const locationhash = getLocationHash(element);
    console.log(`%c${'\t'.repeat(depth)}Location hash: ${locationhash}`, style);
    
    console.log(`%c${'\t'.repeat(depth)}Dimensions Client Height: ${element.clientHeight}`, style);

    // Check if parent distance exceeds 2500 pixels, then skip processing children
    if (distanceFromViewportTop <= 2500) {
        const children = Array.from(element.children);
        children.forEach(child => {
            getDepthAndDistance(child, depth + 1, viewportHeight);
        });
    }
}

window.onload = function () {

    const viewportHeight = window.innerHeight || document.documentElement.clientHeight;

    // Print elements and their distances
    getDepthAndDistance(document.body, 1, viewportHeight);
}

```

**Comment by Miraeld** [comment]
As we've been moving the development of the beacon out of WP Rocket, please follow this issue: 
https://github.com/wp-media/rocket-scripts/issues/7

**Comment by MathieuLamiot** [comment]
@Miraeld @jeawhanlee 

> Ensure that the RocketLrcBeacon class is properly integrated with the RocketBeacon class.

This would need a bit more details: One would need to add something like

```
        if (!isGeneratedBefore.lcr) {
            this.LCRBeacon = new BeaconLCR(this.config, this.logger);
            await this.LCRBeacon.run();
        }
```

here

```
        const isGeneratedBefore = await this._isGeneratedBefore();

        if (!isGeneratedBefore.lcp) {
            this.lcpBeacon = new BeaconLcp(this.config, this.logger);
            await this.lcpBeacon.run();
        }
```

and `_saveFinalResultIntoDB` must be adapted to:

- send LCR results if they exist
- don't send anything if no results (nor OCI nor LCR) are available

correct?

---
Another point seems missing: what happens if the user deactivate one of the feature, let's say LCR. It would be best if the script could avoid running LCR in that case. Maybe this is the intent of config.status.atf here? In which case logic must be adapted?

```
        if (BeaconUtils.isPageCached() && ( this.config.status.atf && generated_before.lcp )) {
            this.logger.logMessage('Bailing out because data is already available');
            return false;
        }
```

 Or maybe the script would get this information through the check_data? (if the feature is off, check_data returns false for this feature?).
If this is indeed missing, maybe add it as a dedicated GH issue?

This needs some clarifications.
----
For AC purposes, maybe consider adding logs in _isGeneratedBefore to get the answers? 
Also, we might need a first version that is not depending on the result of _isGeneratedBefore for LCR. Otherwise, we won't be able to test without the AJAX endpoints implemented, which will create too much dependencies. @Miraeld & @jeawhanlee I would suggest to clearly state in this issue that LCR must run even if _isGeneratedBefore.lcr is true ; and add in the AJAX issue that this condition must be added then.

Regarding ACs, this issue does not need any others issues right?
@wp-media/qa-team @wp-media/product ACs would mostly be testign against templates as per [here](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#cb49f3ef60a2401ba456cca6a1a0099d)

**Comment by Miraeld** [comment]
Closing this issue as https://github.com/wp-media/rocket-scripts/issues/7 have been created.
