### ISSUE TITLE
WP - Rocket / Cloudflare Turnstile / Elementor PopUp

### ISSUE THREAD

**Issue by Pierre-Lavoine** [wp-media/wp-rocket#6791]
Hi Guys,

I'm wondering how you manage to use Cloudflare Turnstile on forms displayed in an Elementor Pop-Up.

My form can't be validated because "the Turnstile Widget seems to have crashed: xxx."

Consequently, the captcha is not validated, and the form can't be sent.

From what I've researched, it seems to be related to caching issues.

This pop-up is called on every page of my website, so deactivating the cache for the entire site isn't feasible.

Since it's an Elementor pop-up, there's no specific link that I can use to deactivate caching in custom rules.

I've also tried to preload or defer all resources from this domain: //challenges.cloudflare.com, but it seems not to work.

Any suggestions?

**Comment by piotrbak** [comment]
Hello @Pierre-Lavoine this sounds like a support request. Please be in touch with our Team and we'll be more than happy to investigate and find a solution for you.

**Comment by manyoumc** [comment]
@Pierre-Lavoine Did you find any solution for this?

**Comment by Pierre-Lavoine** [comment]
> @Pierre-Lavoine Did you find any solution for this?

Not yet,

I send this message on private facebook group of wp-rocket but still haven't replies

**Comment by piotrbak** [comment]
If you're experiencing this problem, please be in touch with the Support Team. We'll investigate the issue and reopen the GitHub with necessary data.
