### ISSUE TITLE
WP Rocket delay JS and Sentry integration compatibility.

### ISSUE THREAD

**Issue by zimdin12** [wp-media/wp-rocket#6792]
I am not sure which of these plugins is causing this. 

Problem: On Android and IOS links do not work. I press on the link, it gets focused, JS loads and nothing happens even when I click on it again, it won't work. basically you cannot use that button anymore (other links / buttons work). I spent too much time to figure out what is going on. 

Conditions for me: It happens when i have latest WP sentry integration and WP Rocket installed with WP Rocket having delay JS turned on. 

I did add wp-sentry-browser to defer JS exclusion list. that helped and it works again.
It seems that it doesn't happen out of the box. something triggers it and I am not sure what it is.

On another site I build and manage it does not happen, but that site is much newer and everything is basicly on latest version.
Site that it does happen does have some deprecation warnings etc.

I wish I would have more information, but I don't
Mb it will help somebody at least :)

Since I am not sure where this bug comes from then I posted it also under Sentry integration issues:
https://github.com/stayallive/wp-sentry/issues/200

**Comment by piotrbak** [comment]
Hello @zimdin12 could you share with us a staging environment where we could see the issue, so we can work on it?

You can send it to our Support Team and we'll check what's going on

**Comment by zimdin12** [comment]
Hello. @piotrbak 

I did change htaccess and made this problem to repro again.
Staging site url: staging.balticlei.ee
htaccess user: tempUser
htaccess pass: tempPass

Let me know when you are done. I plan keep it 1 week semipublic.

**Comment by piotrbak** [comment]
We are not able to reproduce it
