### ISSUE TITLE
Update "can't create rucss_used_css table" admin notice

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#6807]
**Is your feature request related to a problem? Please describe.**
We show this notice when we can't create the rucss tables in the database: 
![image](https://github.com/user-attachments/assets/fa20dd83-d5a4-4c1a-99a5-e615054f810e)

Currently the action step is to contact Support. 

At this point we have identified a couple of possible causes for this notice and we have an article: 
https://docs.wp-rocket.me/article/1828-could-not-create-the-rucss-usedcss-table

I propose updating the notice to link to that article as the action step. Based on the documentation, the customer might be able to solve it themselves, or at least they may be able to find helpful information they can send us in their ticket, to make resolution faster.

**Comment by MathieuLamiot** [comment]
Moving back to In Progress following new specification https://github.com/wp-media/wp-rocket/pull/6815#issuecomment-2260091208
