### ISSUE TITLE
Dynamic cookie functionality does not work due to browser cache headers / if-modified-since check

### ISSUE THREAD

**Issue by eyetractive** [wp-media/wp-rocket#6812]
**Describe the bug**
Using the dynamic cookie functionality, WP Rocket creates two different cache versions of the page. However, when the page is loaded from cache, WP-Rocket incorrectly checks the if-modified-since header with the last-modified property of the cache file, disregarding a possible difference in the cookie value. 

**To Reproduce**
Let's say the cookie has values A and B:
- This means that the user would visit the page with value A set. This page (variant A) is now cached in their browser.
- They switch the cookie to value B and visit the page again. This time, WP-Rocket check the if-modified-since header and returns a '304 Not modified'. The user now sees their disk cache version of the page (variant A), when it should have been the page with value B.

**Expected behavior**
Expect WP-Rocket to serve the correct page and ignore the if-modified-since header and check, since it cannot be relied upon when using the dynamic cookie functionality.

**Additional context**
Related to this problem, best description:
https://github.com/wp-media/wp-rocket/issues/3348

Also related, a possible fix would be to implement a filter:
https://github.com/wp-media/wp-rocket/issues/1423

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by webtrainingwheels** [comment]
This was resolved with this helper plugin:
https://github.com/wp-media/wp-rocket-helpers/raw/master/htaccess/wp-rocket-htaccess-custom-rules-no-store-html/wp-rocket-htaccess-custom-rules-no-store-html.zip

For internal use: https://secure.helpscout.net/conversation/2660959659/504331?folderId=377611

**Comment by piotrbak** [comment]
@eyetractive Hello, before serving 304 status code we're checking for the cache filepath that respects the value of dynamic cookie:
https://github.com/wp-media/wp-rocket/blob/905d862d2f8bf50afa9ef264a8cf7dc40f37f83a/inc/classes/Buffer/class-cache.php#L95
https://github.com/wp-media/wp-rocket/blob/develop/inc/classes/Buffer/class-cache.php#L402

That sounds like a browser is serving the disk cache with 304 status, not WP Rocket itself. We'll revisit your problem and try to fix it together with mentioned issues.
