### ISSUE TITLE
Exclude defering inline scripts with no identifier

### ISSUE THREAD

**Issue by bhba-coder** [wp-media/wp-rocket#6818]
Is there a good way to exclude defering an inline script with no identifier? No src, no id, nothing, just the html within the <script> tag. I was able to find the inline script by using ?nowprocket in the url but some of these scripts have nothing to identify them uniquely. Here is an example - 

<script>
    /(trident|msie)/i.test(navigator.userAgent) && document.getElementById && window.addEventListener && window.addEventListener("hashchange", function() {
        var t, e = location.hash.substring(1);
        /^[A-z0-9_-]+$/.test(e) && (t = document.getElementById(e)) && (/^(?:a|select|input|button|textarea)$/i.test(t.tagName) || (t.tabIndex = -1),
        t.focus())
    }, !1);
</script>

There are a few more that I will   need to exclude and some of them are just like the above. What is the best way to go about? I definitely do not want to include every inline script cause there are quite a few. 

Thanks

**Comment by bhba-coder** [comment]
I was able to exclude the following because it had an id and I just entered the id in the exclusion box and that did the trick - 

<script id="wp-i18n-js-after">
    wp.i18n.setLocaleData({
        'text direction\u0004ltr': ['ltr']
    });
</script>

But the one I mentioned before and a few more that I will like to exclude does not have any identifier. I was able to trace one of them to the following file that is generating it - "/wp-includes/script-loader.php". Do you think its a good idea to modify it and add an identifier when it is generated so I can use that later for the exclusion? That sounds a little risky and might be hard to keep up with updates and I might quickly find myself having a hard time trying to keep a track of all of these local changes, so I was wondering if there is a better way of doing it than hacking the script generation itself.

**Comment by bhba-coder** [comment]
Sorry, I posted rather too early. I guess here is my answer: 

https://docs.wp-rocket.me/article/1657-invalid-patterns-of-exclusions

But still my previous concern holds and I would love to have an opinion identifier at a higher level that is less likely to change with future versions. A slight code change here will break the exclusion and the website, so I will still be interested to know if there is a better way to do it.

**Comment by piotrbak** [comment]
Hello @bhba-coder this sounds like a support request, we use Github for development purposes only.

Please be in touch with our Support Team and we'll be more than happy to help you.
