### ISSUE TITLE
Apply CDN in stylesheet URL when CSS minify option is activated

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#682]
We don't apply the CDN cnames in URL which are in a stylesheet.

To improve our users websites, we could apply the CDN to CSS files during our minification process.

For example:

src:url("/Fonts/my-fonts.eot?#iefix");

to

src:url("https://my-cdn.com/Fonts/my-fonts.eot?#iefix"); 

Autoptimize has this enhancement.

**Comment by Tabrisrp** [comment]
We already do that in fact. I tested on my test installation and it works. Did you encounter a customer case where it didn't?

**Comment by GeekPress** [comment]
Yes on this ticket recently => https://secure.helpscout.net/conversation/496760518/56661?folderId=273768

I've just asked the access and I will assign you the ticket when it will be received.
