### ISSUE TITLE
Add `span` to processable items by the beacon for OCI

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6821]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [x]
- Used the search feature to ensure that the bug hasn’t been reported before [x]

**Describe the bug**
Some themes might have the LCP element as a `span`, like the Newspaper theme.

Test case: https://demo.tagdiv.com/newspaper_pro/

LCP element for desktop - `//*[@id="tdi_53"]/div[1]/div/div[1]/div/a/span`
LCP element for mobile - `//*[@id="tdi_25"]/div[1]/div/div[1]/div/a/span`

** To Reproduce
N/A

**Expected behavior**
Pick up the right LCP element on themes with possible `span` LCP elements

**Screenshots**
N/A

**Additional context**
Part of - https://wp-media.slack.com/archives/C08N8J6VC/p1722007104694209?thread_ts=1721723747.920689&cid=C08N8J6VC

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
@DahmaniAdame Can you check with @Mai-Saad to provide a reproducible way to see the issue and test the fix? Thanks

**Comment by DahmaniAdame** [comment]
@MathieuLamiot @Mai-Saad here is a template if you still need one for testing - https://gist.github.com/DahmaniAdame/8fbdbdaff83d45f0f9b52aeb359adfb2

**Comment by Mai-Saad** [comment]
Thanks @DahmaniAdame , can see it now for **BG** inside span and it's working on PR
