### ISSUE TITLE
500 error - PHP Warning: preg_replace_callback(): Compilation failed: regular expression is too large at offset [...] /inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 167

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6825]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a 3rd party lazyload (Themify in this case) applies an SVG placeholder it can lead to an incorrect LCP detection when Optimize Critical Images run. 

Our beacon detected the SVG element and the LCP element was saved in this:

`{"type":"img","src":"data:image\/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%221920%22%20height%3D%22700%22%3E%3Cg%20fill%3D%22%2346563d%22%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%236b6c5f%22%20x%3D%22640%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%237a6f61%22%20x%3D%221280%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23c1c8cf%22%20y%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23b0bfcd%22%20x%3D%22640%22%20y%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23dcd4c4%22%20x%3D%221280%22%20y%3D%22233%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%238eb295%22%20y%3D%22466%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%23b2c1d1%22%20x%3D%22640%22%20y%3D%22466%22%2F%3E%3Crect%20width%3D%22640%22%20height%3D%22233%22%20fill%3D%22%237facc6%22%20x%3D%221280%22%20y%3D%22466%22%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E"}
`

This leads to 500 errors in the console, but only on the browser console, without causing the site to go down—the pages load as expected with just the console error.

Clearing the LCP table and disabling the lazyload fixed the issue

**To Reproduce**
1. Add lazyload with a SVG placeholder image
2. Run OCI
3. see the SVG image stored as LCP element
4. Alternatively you can manually add the SVG code to the database
5. See error in the browser console

**Expected behavior**
We should skip those images or detect the lazyloaded image

**Additional context**
HS ticket:  https://secure.helpscout.net/conversation/2650493328/502355?folderId=2683093
Original GH report: https://github.com/wp-media/wp-rocket/issues/6740
Slack thread: https://wp-media.slack.com/archives/C072P5EU5DF/p1722020640191349

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by alfonso100** [comment]
Another case here: 
https://github.com/wp-media/wp-rocket/issues/6825

User reports this: 

> It seems that the issue is similar. We have one quite big PNG in base 64 that is part of lottie animation that is on the top of the homepage.
> I tried to set up exclude for CSS class "uagb-lottie-inner-wrap" and it seems that error is not showing anymore. I will check it after a few days again, but I think it could be solved by this solution.

this is error: 
`[Thu Sep 05 13:34:46.137351 2024] [proxy_fcgi:error] [pid 2603003:tid 139814160455424] [client 185.175.87.31:59816] AH01071: Got error 'PHP message: PHP Warning: preg_replace_callback(): Compilation failed: regular expression is too large at offset 1162403 in /wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 167PHP message: PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, null given in /wp-rocket/inc/Engine/Optimization/RegexTrait.php:151\nStack trace:\n#0 /wp-rocket/inc/Engine/Optimization/RegexTrait.php(151): str_replace()\n#1 /wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(170): WP_Rocket\\Engine\\Media\\AboveTheFold\\Frontend\\Controller->restore_html_comments()\n#2 /wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(97): WP_Rocket\\Engine\\Media\\AboveTheFold\\Frontend\\Controller->set_fetchpriority()\n#3 /wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php(64): WP_Rocket\\Engine\\Media\\AboveTheFold\\Frontend\\Controller->preload_lcp()\n#4 /data/www/domeny/...'`


maybe we should check if we are excluding **base64** from being used as OCI images

**Comment by piotrbak** [comment]
It should have been fixed here:
https://github.com/wp-media/wp-rocket/pull/6677

Feel free to reopen if needed
