### ISSUE TITLE
3.17 - Add AJAX & Database for LRC

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket#6828]
# Description
The idea is to implement the data process once the AJAX call is sent by the beacon. As a reminder, we will have a unique call for both feature `Lcp` and `Lrc`. 
It would be better for the [`LrcBeacon`](https://github.com/wp-media/rocket-scripts/issues/7) to be implemented alongside or before this issue for testing purpose. 
For new classes structure, a look can be taken onto `AboveTheFold` classes as they will be also implementing/extending the `PerformanceHints` namespace. 

# Scope a solution
- If not created, a new table needs to be created `wpr_lazy_render_content` 
 - This table will have the following schema: 
```
id                              -  bigint(20)
url                             -  varchar(2000)
is_mobile                 -  boolean (tinyint(1))
below_the_fold	-  longtext
error_message	-  longtext
status			-  varchar(255)
modified		        -  timestamp
last_accessed	        -  timestamp
created_at		-  timestamp
```

- Create a `LazyRenderContent` class within `WP_Rocket\Engine\Optimization\LazyRenderContent\Database\Queries`, `WP_Rocket\Engine\Optimization\LazyRenderContent\Database\Rows`, `WP_Rocket\Engine\Optimization\LazyRenderContent\Database\Schemas` & `WP_Rocket\Engine\Optimization\LazyRenderContent\Database\Tables`.

- Create a `Controller` within `WP_Rocket\Engine\Optimization\LazyRenderContent\AJAX` namespace that will implements `WP_Rocket\Engine\Common\PerformanceHints\AJAX\ControllerInterface` 
- Implement the function `add_data()` and `check_data()` 

# Acceptance Criteria

-   on install/update of the plugin, the new table must be created
-   when running the script on a page without data stored yet:
    -   the script must run the check_data and add_data calls with LCR data (can be seen with logs in PHP and/or in the script)
    -   the data is correctly stored in the DB
    -   must validate that when running on desktop, even if there is data for mobile stored on this URL already.
    -   must be validated when running on a page with already OCI data, but no LCR data yet in DB.
-   when running the script on a page with already data for LCR, and OCI activated:
    -   the script must run the check_data and add_data, but nothing related to LCR must be sent in the add_data call.
    -   no data changes in DB for LCR
-   when running the sript on a page with already data for LCR, and OCI deactivated:
    -   the script must run the check_Data and stop after. No add_data call must be triggered.
    -   no data changes in DB for LCR

**Comment by MathieuLamiot** [comment]
@Miraeld @jeawhanlee 
- Is the data model [here](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#756b1752a99348f98e84a4bb465181e1) OK?
- Is check_data() exactly the same as the one for OCI?
- For add_data(), based on the data model, should we:
    - Re-use the same checks/sanity than OCI on common fields
    - Have a dedicated sanitizer for the array of hashes and a limit of elements in the array to avoid flooding the DB.

@wp-media/product @wp-media/qa-team For ACs: this can be validated after the script implementation.
- on install/update of the plugin, the new table must be created
- when running the script on a page without data stored yet:
    - the script must run the check_data and add_data calls with LCR data (can be seen with logs in PHP and/or in the script)
    - the data is correctly stored in the DB
    - must validate that when running on desktop, even if there is data for mobile stored on this URL already.
    - must be validated when running on a page with already OCI data, but no LCR data yet in DB.
- when running the script on a page with already data for LCR, and OCI activated:
    - the script must run the check_data and add_data, but nothing related to LCR must be sent in the add_data call.
    - no data changes in DB for LCR
- when running the sript on a page with already data for LCR, and OCI deactivated:
    - the script must run the check_Data and stop after. No add_data call must be triggered.
    - no data changes in DB for LCR

**Comment by Miraeld** [comment]
I've edited the grooming to add the schema, which I forgot in the first version. 

Also, I've added ACs based on your feedback. 

then to answers some of your questions, The data model seems fine to me as we get everything we need to get the feature working. 
Then, about `check_data()`, it will be the same as OCI, except the table used to check. of course. 
Finally, about `add_data`, on common fields, we can re-use the same sanitizer. While for the `below_the_fold` field, we can implement a dedicated one as adapting the one from OCI would make it far more complex than it is right now.

**Comment by MathieuLamiot** [comment]
Should be ready for review tomorrow

**Comment by MathieuLamiot** [comment]
There are 2 defects preventing to happily run the LRC Beacon and related AJAX calls (so impacting #6874 & #6828). @jeawhanlee mentioned it should be a quick fix, he'll open a PR to fix this and ultimately allow testing of those 2 GH issues. (cc @wp-media/qa-team )

**Comment by Mai-Saad** [comment]
- on install/update of the plugin, the new table must be created => on fresh install , table is created immediately with activation. while when update, interaction must happen on BE/or FE so the LRC table be created (acceptable as long as no error when visit FE while table is not there)
- when running the script on a page without data stored yet:
the script must run the check_data and add_data calls with LCR data (can be seen with logs in PHP and/or in the script)
=> the data is correctly stored in the DB :heavy_check_mark: 
=> must validate that when running on desktop, even if there is data for mobile stored on this URL already. :heavy_check_mark: 
 => must be validated when running on a page with already OCI data, but no LCR data yet in DB. :heavy_check_mark: 
- when running the script on a page with already data for LCR, and OCI activated:
the script must run the check_data and add_data, but nothing related to LCR must be sent in the add_data call.
=> no data changes in DB for LCR :heavy_check_mark: 
- when running the sript on a page with already data for LCR, and OCI deactivated:
the script must run the check_Data and stop after. No add_data call must be triggered.
=>no data changes in DB for LCR :heavy_check_mark:
