### ISSUE TITLE
3.17 - LRC Activation & Context

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket#6829]
# Description
This issue adds the `Activation` process and `Context` to `LRC`.

# Scope a solution 
For all `apply_filters`, please make sure to use our new safetype version of `apply_filters` [here](https://github.com/wp-media/apply-filters-typed/blob/ba4e7864f354582a28eedf8ddac99034b2ea6915/functions.php#L3-L13)
- Create a `ActivationFactory` class within `/WP_Rocket\Engine\Optimization\LazyRenderContent\Activation` namespace that will looks like: 
``` php
<?php

declare(strict_types=1);

namespace WP_Rocket\Engine\Optimization\LazyRenderContent\Activation;

use WP_Rocket\Engine\Common\PerformanceHints\ActivationFactoryInterface;
use WP_Rocket\Engine\Common\Context\ContextInterface;

class ActivationFactory implements ActivationFactoryInterface {

	/**
	 * Context instance.
	 *
	 * @var ContextInterface
	 */
	protected $context;

	/**
	 * Instatiate the class.
	 *
	 * @param ContextInterface $context LRC Context instance.
	 */
	public function __construct( ContextInterface $context ) {
		$this->context = $context;
	}

	/**
	 * Provides a Context object.
	 *
	 * @return ContextInterface
	 */
	public function get_context(): ContextInterface {
		return $this->context;
	}
}
```
- Update the `inc/Engine/Common/PerformanceHints/Activation/ServiceProvider.php` to add this new class. 
- Create a new `Context` class extending `WP_Rocket\Engine\Common\Context\ContextInterface` within `/inc/Engine/xxx/LazyRenderContent/Context` that will look like: 
``` php
<?php
declare(strict_types=1);

namespace WP_Rocket\Engine\Optimization\LazyRenderContent\Context;

use WP_Rocket\Engine\Common\Context\ContextInterface;

class Context implements ContextInterface {
	/**
	 * Determine if the action is allowed.
	 *
	 * @param array $data Data to pass to the context.
	 * @return bool
	 */
	public function is_allowed( array $data = [] ): bool {

		if ( get_option( 'wp_rocket_no_licence' ) ) {
			return false;
		}

		/**
		 * Filters to manage lazy render content optimization
		 *
		 * @param bool $allow True to allow, false otherwise.
		 */
		$is_lrc_enabled = apply_filters( 'rocket_lazy_render_content_optimization', true );

		if ( ! is_bool( $is_lrc_enabled ) ) {
			return true;
		}

		return $is_lrc_enabled;
	}
}
```

# Acceptance Criteria
- OCI & LCR activated -> injected
- -> OCI or LCR activated -> injected
- OCI & LCR deactivated -> not injected
- Warmup for Home & Home links should happen when plugin is Activated with OCI/LRC enabled
- Warmup for Home & Home links should not happen when Activated with OCI & LRC disabled
- Warmup for Home & Home links should not happen on LOCAL env with OCI/LRC enabled (Currently this is not the case for warmup for home)
- Warmup for Home & Home links should not happen when RUCSS is enabled.

**Comment by MathieuLamiot** [comment]
Please use the safetype version of apply_filters

@jeawhanlee @Miraeld @wp-media/qa-team 

Regarding ACs, is it correct to validate this by checking that the beacon is injected when it is supposed to be?
- OCI & LCR activated -> injected
-> OCI or LCR activated -> injected
- OCI & LCR deactivated -> not injected

Or should other ACs be covered here?

**Comment by Miraeld** [comment]
As I created the draft of this PR before the presentation of the new apply_filter method, I did not use it at this moment. I've added a comment in the grooming to tell using it.

Also, I've added ACs, I'm not sure we have any other thing that should be covered here.

**Comment by jeawhanlee** [comment]
I updated the ACs on this one
