### ISSUE TITLE
3.17 - After update UI  - DUPLICATE 6845

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6843]
Just like for 3.16 we'll add the message after the update from the previous version.

1. We'll remove the 3.16 [message](https://github.com/wp-media/wp-rocket/pull/6608/files) 
2. We'll display a green notice with the wording present at the bottom of AC
3. The message will not have the `x` on the right side to close it
4. The message will have a button called `Dismiss this notice` which will dismiss it and don't show again
5. The message will be displayed only when updating from the version lower than 3.17. (3.16.x to 3.17 displayed; 3.17 to 3.17.0.1 not displayed; 3.16.x to 3.18 displayed;)
6. The message will not be displayed for fresh installations

Wording:
`New feature: Lazy Render Content. Check out our documentation to learn more about it.`

**Comment by piotrbak** [comment]
@benorfaz I don't think it makes sense to keep the 3.16 notice, if someone updates from 3.15 we'd display two notices, which doesn't make sense 🤔

**Comment by benorfaz** [comment]
Yes lets keep only the last version message

**Comment by piotrbak** [comment]
ENG doc
https://docs.wp-rocket.me/article/1835-lazy-render-content
66b11e26a62a7505fcf339e7

FR doc 
https://fr.docs.wp-rocket.me/article/1836-rendu-differe-automatique
66ba0e8e082392452a0773ea
