### ISSUE TITLE
Compatibility with Termly

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6863]
**Is your feature request related to a problem? Please describe.**
[Termly](https://termly.io/) has an `auto blocking` mode that requires their script to be loaded early without any loading strategy applied. Otherwise, it will interfere with the plugin's functionality (intercept 3rd party scripts and decide if they can be executed or not depending on consent).

The indicator for this setting is stored on the options table under `termly_display_auto_blocker` set to `on`. 

The need is to exclude their main script `app.termly.io` (https://app.termly.io/resource-blocker/website-hash-identifier) from `defer` and `delay` when applicable.

**Describe the solution you'd like**
Have a compatibility file that will skip `defer` and `delay` when `termly_display_auto_blocker` is set to `on`

**Describe alternatives you've considered**
N/A

**Additional context**
Conversation with the Termly team - https://group-onecom.slack.com/archives/C07FUEY1939/p1723453296721739

**Comment by bwafels** [comment]
are there any similar issues with other privacy plugins (e.g.: iubenda)? Iubenda also auto blocks scripts.

**Comment by baniwafels** [comment]
This is the consol error I am getting. I had a meeting with Google about the GTM and everything is correctly setup.
![Image](https://github.com/user-attachments/assets/712a6221-597b-4199-9041-2968e7916f69)

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
In WP_Rocket\ThirdParty\Plugins\Security 
- Create a new compatibility file for termly.
  - Add new events ( `rocket_exclude_defer_js`, `rocket_delay_js_exclusions` ), bail out if Termly is not installed: check if  `TERMLY_VERSION` is defined
  - Add a method `should_exclude` to check if exclusions is allowed by checking the value of `termly_display_auto_blocker`
  - Add another method to return exclusion(`termly(.*)resource-blocker`) to both events above depending on `should_exclude` return

Add test.

### Estimate the effort ✅
[S]

**Comment by wordpressfan** [comment]
Look good to me, just a few small comments to consider:

1. We can check the option as they do in their plugin:
```
$auto_block = get_option( 'termly_display_auto_blocker', 'off' );
```
2. I think we can exclude the url without wild characters, their url is mentioned here:
https://plugins.trac.wordpress.org/browser/uk-cookie-consent/trunk/includes/controllers/class-frontend.php#L92
3. Also, we may consider adding this new third-party into a dedicated directory for Cookies like in the old structure:
https://github.com/wp-media/wp-rocket/tree/06381b8860eb46e570911b2812652f54a676dd6d/inc/3rd-party/plugins/cookies
