### ISSUE TITLE
Lazyload causes increase in thumbnail size with certain CSS 

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#687]
Lazyload is causing some thumbnail images to load in with an increased size with certain **width** and (maybe **height**) values defined in the theme. 

Seen in these tickets:

https://secure.helpscout.net/conversation/497639713/56764/

https://secure.helpscout.net/conversation/497067373/56703?folderId=273766

**Comment by GeekPress** [comment]
As this problem hasn't been reported for a while, we can suppose we don't have the problem anymore.

@wp-media/supportrocket Feel free to re-open it if a new ticket will be related to this problem.
