### ISSUE TITLE
Create a New Tab in WP Rocket

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#6877]
Description and assets available [here](https://docs.google.com/document/d/1lNfOB2dUg4FtDeW8OInwKP5GIExBNGgHXenqdJ8hFa8/edit#heading=h.wdkofbwe72cn)

**Comment by JerissCloudCenter** [comment]
Just out of curiosity as a user : what is this about ?

**Comment by Khadreal** [comment]
## Scope a solution

In this [file](https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/inc/Engine/Admin/Settings/Subscriber.php#L43) we should add a new method for the new section title and add that newly created method here  [file](https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/inc/Engine/Admin/Settings/Subscriber.php#L43) 

Create a new page in `views/settings/page-sections/ `and add this page to the Render class 
https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/inc/Engine/Admin/Settings/Render.php#L178

Add the method created in Render class to this section https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/views/settings/page.php#L52


Estimation
[M]

**Comment by MathieuLamiot** [comment]
Chances are we will want to have similar tabs in other plugins. Can we think of a solution that would be easily sharable and maintainable across repos?

**Comment by remyperona** [comment]
Most of the implementation should be re-usable definitely, as we already have the same thing for Imagify planned: https://github.com/wp-media/imagify-plugin/issues/895

**Comment by hanna-meda** [comment]
Thank you, @Khadreal, for your work on this one. These are the initial findings:
1. Clicking on Install from Imagify modal, the page breaks, with error:      
`       GET https://rocketlabsqa.ovh/wp-admin/admin-post.php?action=install_imagify_from_partner_wp-rocket&_wpnonce=cdb2406366&_wp_http_referer=https%3A%2F%2Frocketlabsqa.ovh%2Fwp-admin%2Foptions-general.php%3Fpage%3Dwprocket 400 (Bad Request) `
2. From [documentation](https://docs.google.com/document/d/1lNfOB2dUg4FtDeW8OInwKP5GIExBNGgHXenqdJ8hFa8/edit?tab=t.0), Expected: Clicking the Learn More link will open a new tab with the URL. Currently: Links open in same tab
3. Activating Termly while BackWPup is still not installed, the  Install button from BackWPup will show broken:
![Image](https://github.com/user-attachments/assets/b1b5a632-0d27-4adf-aa0f-686a0b720150)
4. These 2 are logging in the debug.log:
`[24-Oct-2024 13:18:48 UTC] PHP Warning:  Undefined array key "cta" in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/views/settings/page-sections/plugins.php on line 56
[24-Oct-2024 13:18:48 UTC] PHP Warning:  Trying to access array offset on null in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/views/settings/page-sections/plugins.php on line 56`

**Comment by hanna-meda** [comment]
@Khadreal, After checking the latest commits, please find below my testing updates:

1. Behavior changed > 
I. First time clicking the "Install" from under Imagify, the plugin is installed and activated ~(but not activated as we need to provide a valid API key)~
II. ~User activates with a valid API key~
III. BUT on Our Plugins screen, CTA from under Imagify keeps showing "Install". 
IV. Hit "Install" button again => same page break and error
2. ✅ 
3. ❌ 
4. ❌ 
5. Based on [documentation](https://docs.google.com/document/d/1lNfOB2dUg4FtDeW8OInwKP5GIExBNGgHXenqdJ8hFa8/edit?tab=t.0), the default order should be:
Optimize Performance
Boost Traffic
Protect & Secure
Current default order is: 
Boost Traffic
Protect & Secure
Optimize Performance
![Image](https://github.com/user-attachments/assets/6e3ff3b3-c197-4f21-b163-f60bd98d8f23)

**Comment by Agathemed** [comment]
@hanna-meda About this:

> First time clicking the "Install" from under Imagify, the plugin is installed (but not activated as we need to provide a valid API key)

On WP Rocket `Image Optimization` tab, when clicking `Install Imagify`, we install AND activate the Imagify plugin. Then, the user needs to create an account or to add their API key. 
I would expect the same behavior here.

**Comment by MathieuLamiot** [comment]
@Khadreal if the above request from @Agathemed can not be done quickly (typically less than a day), then we'll move this to another Github issue. We must find a way to wrap up this PR quickly to avoid further delaying the release. Let me know how you see things on this. Thanks

**Comment by hanna-meda** [comment]
@Khadreal, @MathieuLamiot, I re-checked (with the latest commits on plugin-family, thank you @jeawhanlee) and can confirm that all 5 points have been fixed. I still have a few cases to verify, but overall this looks good. 

cc @Agathemed

**Comment by hanna-meda** [comment]
@Khadreal, there might be 2 more tweaks to be fixed. The first point seems actionable, while for the second, we’ll need input from @Agathemed. Could you please take a look at the second point?

1. For all plugins except BackWPup, clicking the “Install” button installs and activates the plugin while keeping the user on the “Our Plugins” screen. However, with the BackWPup plugin, the user is redirected to the BackWPup dashboard (wp-admin/admin.php?page=backwpup). Expected: The user should still be on the "Our Plugins" tab, with BackWPup showing as activated.

2. The CTAs from BackWPup & Termly plugins (Protect & Secure section) are not aligned. Should we have them aligned? P.S. They don't appear aligned in the [Mockup](https://drive.google.com/file/d/1x4ls2Uj3ndhuO-BQDAf1ZDweFfdxbOjY/view) either.
![Image](https://github.com/user-attachments/assets/9522da48-60e7-4450-88f4-8fc115b890e7)

**Comment by Agathemed** [comment]
Good point @hanna-meda, yes they should be aligned.

**Comment by hanna-meda** [comment]
Then, @Khadreal, can you take care of both points? Thank you!

**Comment by jeawhanlee** [comment]
@hanna-meda For the first point, I don't know if there's much that can be done on our side as this is a default behaviour of backwpup, they automatically redirect to a welcome page on activation. 
https://github.com/wp-media/backwpup/blob/37d6020719d15e0cabb88d915c54c68886e4296c/inc/class-install.php#L139
So we might need to provide compatibility directly on backwpup for our plugins. Is this something we want to work on? @MathieuLamiot

**Comment by Khadreal** [comment]
@hanna-meda fixed the button alignment and the first points has been answer by @jeawhanlee

**Comment by MathieuLamiot** [comment]
thanks @jeawhanlee. I'll follow up with Laurent about this for a later version of BackWPUp then. Thanks for the details about this behavior 🙏

**Comment by wpgaurav** [comment]
It's great to see this new tab. Is there a way to remove your recommended plugins from /plugin-install.php?
