### ISSUE TITLE
3.17 - Activation/Deactivation with the filters

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6878]
**Context**
We need to have filters to enable/disable both OCI and LRC features

**Acceptance Criteria**
- When both features are enabled
  - We'll display the [clearing buttons and clearing sections](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#58b13c04c0ff4f94a0d37c3afd606db7)
  - We'll clear the data as [specified in the Epic Card](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#550a738c5dd54e0f8f4ba31d62fac421)
- When one of the features is disabled and the second one is enabled
  - We'll display the [clearing buttons and clearing sections](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#58b13c04c0ff4f94a0d37c3afd606db7)
  - We'll clear the data as [specified in the Epic Card](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#550a738c5dd54e0f8f4ba31d62fac421)
  - In both of the above points the data will be cleared for both features
- When both features are disabled
  - We'll **not** display the [clearing buttons and clearing sections](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#58b13c04c0ff4f94a0d37c3afd606db7)
  - We'll clear the data as [specified in the Epic Card](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#550a738c5dd54e0f8f4ba31d62fac421)
  - In the above point, the data will be cleared for both features

**Comment by Miraeld** [comment]
Hello hello, 

It seems to me the AC #1 is already covered. 

For AC #2, @piotrbak could you confirm something: If one of these features: LRC *OR* OCI is disabled, we still display the clearing button for both features?

Thank you

**Comment by Miraeld** [comment]
Otherwise, for AC 3, 

## Scope a solution

In https://github.com/wp-media/wp-rocket/blob/1f82fa0db92a7166e4a4cb8be7326f65e530606c/inc/Engine/Common/PerformanceHints/Admin/AdminBar.php#L95, we would need to add the following: 
``` php
		$all_not_allowed = true;

		foreach ($this->factories as $factory) {
			if ($factory->get_context()->is_allowed()) {
				$all_not_allowed = false;
				break;
			}
		}

		if ($all_not_allowed) {
			return;
		}

``` 
In this case, if every factories return `false` to `is_allowed()` we will not display the option to clear the data. 

Also, for AC 2, it will shows the option if at least one feature is enabled.

**Comment by Khadreal** [comment]
The `factories` are loaded if the context is true, so we could just check if it's empty at this point. Also, the `lrc_factory` context check is missing there.

https://github.com/wp-media/wp-rocket/blob/1f82fa0db92a7166e4a4cb8be7326f65e530606c/inc/Engine/Common/PerformanceHints/ServiceProvider.php#L75

[Edit]
The dashboard button trait class already check for this https://github.com/wp-media/wp-rocket/blob/1f82fa0db92a7166e4a4cb8be7326f65e530606c/inc/Engine/Admin/Settings/AdminBarMenuTrait.php#L134-L136. What we need to do will be to load the `lrc_factory` in the serviceprovider class

**Comment by piotrbak** [comment]
@Miraeld `If one of these features: LRC OR OCI is disabled, we still display the clearing button for both features?`

Yes, that's correct

**Comment by Khadreal** [comment]
@Miraeld I can see factories is being added, what we need to do will be to test this scenarios esp AC 3 to confirm everything is fine

**Comment by Miraeld** [comment]
Yes, 

For AC 1 & 2, its already working like we want. 
However for 3 we need to implement what I've recommended earlier. 

Also, for all three scenarios, we need to implement tests to make sure it's working as expected.

**Comment by jeawhanlee** [comment]
@Miraeld @Khadreal I don't think we have issues with the clear button displays whether on the dashboard or the admin bar menu.
What I think we need to check is if we clear the data as expected for those 3 ACs

**Comment by Khadreal** [comment]
@jeawhanlee spot on. I think we're good on that. The data cleared as expected. Moving this to QA

**Comment by Khadreal** [comment]
Video recording showing the filter activation and deactivation
https://www.loom.com/share/f02029def0e84c3d94a331de489f5b8b?sid=509959fd-2729-4bd7-b7af-4174fea70afb
