### ISSUE TITLE
Update Action scheduler to 3.8.1 to prevent warning in specific scenario

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6882]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When visiting the scheduled actions page after triggering LCP fetch, we will have a warning 
`[21-Aug-2024 10:18:17 UTC] PHP Warning:  A non-numeric value encountered in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ListTable.php on line 400`

**To Reproduce**
1. Only WPR installed and activated
2. Change permalinks
3. Open the scheduled actions page
4. Check debug.log and fetched URLs

**Expected behavior**
No warning is displayed in debug.log and fetching works

**Additional context**
- This is not happening when using the latest AS 3.8.1 plugin with WPR so we need to update AS in WPR 
- slack https://wp-media.slack.com/archives/CUT7FLHF1/p1724235857206149?thread_ts=1719475724.930769&cid=CUT7FLHF1

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
As mentioned by @Tabrisrp, should be a quick fix by updating AS in composer.
@Tabrisrp, should we also update [inc/Engine/Common/Queue/Cleaner.php](https://github.com/wp-media/wp-rocket/pull/6836/files#diff-f6c889f6adbe29567b4fa1770f5f2f36930e3e9b050e1003cf3f12e3fc34b545) (exactly like you did in [this PR](https://github.com/wp-media/wp-rocket/pull/6836/files#diff-f6c889f6adbe29567b4fa1770f5f2f36930e3e9b050e1003cf3f12e3fc34b545))?

**Comment by remyperona** [comment]
Yes it's necessary to match with the new structure of the parent method

**Comment by Miraeld** [comment]
It works fine with me. 

I don't have anything in debug.log, it works as expected. 

My testing process is reproducing the steps that were used to reproduce the issue [here](https://github.com/wp-media/wp-rocket/issues/6882#issue-2477686314)
