### ISSUE TITLE
Lazyload YouTube preview image on mobile devices: must tap twice to play video

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#689]
When using the "Replace YouTube iframe with preview image" option, on a mobile device you have to tap the arrow button twice to actually get the video to play.

Lots of videos on this page if you want to see it in action on mobile:
http://rocket.wpgirlie.com/testing-videos/

**Comment by Tabrisrp** [comment]
In fact after researching that a bit, this is normal behaviour, autoplay is deactivated on iOS and Android
