### ISSUE TITLE
 Attempt to read property "id" on bool [...] AbstractQueries.php on line 63

### ISSUE THREAD

**Issue by jas8522** [wp-media/wp-rocket#6892]
Using 3.16.4, cron reports:
```
PHP Warning:  Attempt to read property "id" on bool in /wp-content/plugins/wp-rocket/inc/Engine/Common/PerformanceHints/Database/Queries/AbstractQueries.php](/wp-content/plugins/wp-rocket/inc/Engine/Common/PerformanceHints/Database/Queries/AbstractQueries.php) on line 63
```
Using PHP 8.1.

**Comment by piotrbak** [comment]
Hello @jas8522 thanks for creating the issue. Could you contact our support team so we could check what's going on with your website?

If not, we'll need an exact steps to reproduce the issue. Please reopen the issue with steps, or after investigating we'll create a new one with instructions for developers.

**Comment by jas8522** [comment]
Do you have an idea how I can provide exact steps to reproduce when I only see the error in my email when cron runs? I get the exact same error repeated 15 times within the email. Happens once a day. There is no additional info in the cron report (except the part of the path to the web root that I removed for website anonymity). 

Seems to me someone forgot to check if the `$item` value is set properly and line 63 should be wrapped with a check for that:

```
foreach ( $items as $item ) {
	if ( is_object($item) ){ 
	   $deleted = $deleted && $this->delete_item( $item->id );
	}
}
```

**Comment by piotrbak** [comment]
@wp-media/engineering-plugin-team Would need your feedback here, should it be investigated further or the guard is just enough?

@jas8522 Thanks for your input

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2731864747/517355/

**Comment by jas8522** [comment]
Thanks all!
