### ISSUE TITLE
3.17 - SaaS visits generate LRC entries in DB but without hashes

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6894]
**Context**
To be done after #6909 

https://wp-media.slack.com/archives/CUT7FLHF1/p1724319751032379?thread_ts=1724257215.870589&cid=CUT7FLHF1
When triggering a SaaS warmup of Performance Hints (clear the LRC & ATF tables, and trigger a warmup by changing permalinks for example, or clicking the button to clear perf. hints), after a while, LRC table is populated but all entries have no hashes.

See the first investigation below: there is one issue that prevents the SaaS visits from working at all, and then probably a 2nd issue that make the feature inconsistent. Consider working on Issue n°1 first, and then circling back to identify the issue n°2 to do it step by step.

This GH issue is to cover issue n°2 (inconsistency), once issue n°1 is fixed (in #6909)

**Expected behavior**
SaaS visits should consistently produce the same results in the DB as a manual visit with a similar viewport size.

**Acceptance Criteria**
Trigger a Performance Hints warmup. After a while, LRC table must be filled with entries that have the same hashes as a manual visit on this page. Repeat 10 times.

**Additional information**
See the thread. @mostafa-hisham can help for the SaaS side investigation.

**Comment by MathieuLamiot** [comment]
What I tested: Clearing all PerformanceHints tables manually (not triggering the warm-up) and then going to the URL visited by the SaaS ([http://mathieu.e2e.rocketlabsqa.ovh?nowprocket=1&no_optimize=1&wpr_imagedimensions=1](http://mathieu.e2e.rocketlabsqa.ovh/?nowprocket=1&no_optimize=1&wpr_imagedimensions=1)), I could see the hashes not added. So :
### Issue n°1 
is that the add_hashes callback is not triggered when we visit this URL. I think a fix is to add:

'rocket_critical_image_saas_visit_buffer' => [ 'add_hashes', 16 ],

in `inc/Engine/Optimization/LazyRenderContent/Frontend/Subscriber.php` so that hashes are added if needed on SaaS visits.

----
### Issue n°2
Then, I could see some rows in the DB getting LRC values after SaaS visits (after doing "Clear Performance Hints). But, it is not super consistent. Someone else should try to confirm but it seems the row is often empty, and sometimes has LRC data.

https://github.com/user-attachments/assets/056926ee-4c64-4105-94fe-69af5042ad7b

@mostafa-hisham We had issues with cache on SaaS, re-using old JS files. Could it be the case here? We updated the wpr-beacon.js file but did not change its name. Could it be that the SaaS executes an old version of the script on some pods? I rolled-out the pods on both us and eu staging, the issue still occurs so I am not so sure about this.

**Comment by mostafa-hisham** [comment]
@MathieuLamiot 
the cache issue is fixed on the SaaS side, if you redeploy the staging that means that all browser files are deleted so there is no cache and you visit the page for the first time using this browser, I am not sure what is wrong exactly.

I checked the url you provided
http://mathieu.e2e.rocketlabsqa.ovh/?nowprocket=1&no_optimize=1&wpr_imagedimensions=1
and I cannot find the `wpr-beacon.js` file, maybe the feature is disabled. Should it be enabled by default?


https://github.com/user-attachments/assets/7832bfaa-d2b3-4795-8f88-b0de68dbcb98


> We had issues with cache on SaaS, re-using old JS files

That was not the case after all. The issue was Super PWA plugin was creating a service worker for the website to store resources on the browser and then load them, it wasn't the default browser caching.

I don't see the Super PWA installed on `mathieu.e2e.rocketlabsqa.ovh ` or a similar plugin.
and now we bypassing the service worker so we are good from this side too. :thinking:

**Comment by MathieuLamiot** [comment]
Ok thanks, so probably not related.
It's a bit hard to test with manual visits because the hashes and beacon are added only if there is no data in the DB, so for one visit. Then they are not added to the page until someone clears the DB. That's why you don't see them.

Anyway, based on the messages above, therr is a bit of work plugin side already, and we can investigate plugin side if all SaaS visits get the hashes and beacon we we to clearing as I did in the video.
Thanks Mostafa for your inputs

**Comment by mostafa-hisham** [comment]
To help test this
I created a [branch](https://github.com/wp-media/nodejs-treeshaker/tree/test/wpr-beacon-cache) on RUCSS that checks if the beacon script was found and returns the first 50 chars from the file as a snippet

- so we can add a version number or any text at the beginning of the `wpr-beacon.min.js ` 
- log response from endpoints to be sure that the beacon file is there and  is updated

- ### response nav only
```JSON
{
    "code": 200,
    "status": "completed",
    "elapsed_time": 5352,
    "coverage_time": 0,
    "purge_time": 0,
    "message": "Navigate to page successfully!",
    "contents": {
        "success": true,
        "shakedCSS": "",
        "shakedCSS_size": 0,
        "orginalCSS_size": 0,
    },
        "beaconInfo": {
            "message": "wpr-beacon is found",
            "url": "http://mathieu.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/assets/js/wpr-beacon.min.js",
            "snippet": "(()=>{var u=class{static isNotValidScreensize(e,i)"
        }
    "server_ip": "192.168.1.104"
}
```

- ### reponse with RUCSS
```JSON
{
    "code": 200,
    "status": "completed",
    "elapsed_time": 3014,
    "coverage_time": 2757,
    "purge_time": 257,
    "message": "Treeshaked successfully!",
    "contents": {
        "success": true,
        "shakedCSS": "@charset \"UTF-8\";.gb-block-spacer{margin:0 0 1.2em;position:relative} /**MORE CSS HERE**/",
        "shakedCSS_size": 46802,
        "orginalCSS_size": 293288,
    },
    "server_ip": "192.168.1.104"
        "beaconInfo": {
            "message": "wpr-beacon is found",
            "url": "http://mathieu.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/assets/js/wpr-beacon.min.js",
            "snippet": "(()=>{var u=class{static isNotValidScreensize(e,i)"
        }
}
```
- ### No script found
```JSON
{
    "code": 200,
    "status": "completed",
    "elapsed_time": 1809,
    "coverage_time": 0,
    "purge_time": 0,
    "message": "Navigate to page successfully!",
    "contents": {
        "success": true,
        "shakedCSS": "",
        "shakedCSS_size": 0,
        "orginalCSS_size": 0,
    },
    "server_ip": "192.168.1.104"
        "beaconInfo": {
            "message": "No wpr beacon script found"
        }
}
```

If you want I can deploy [it](https://github.com/wp-media/nodejs-treeshaker/commit/e4b252d73739d620e76913b615fce63c4320d4be) to the staging

**Comment by Mai-Saad** [comment]
Note: This is affecting LRC warmup +RUCSS visits if LRC wasn't generated yet

**Comment by MathieuLamiot** [comment]
Created #6909 to cover issue n°1. Then we can circle back on this one for further investigation.

**Comment by MathieuLamiot** [comment]
After #6909, I can't reproduce the issue n°2 on mathieu.e2e: I consistently have hashes for all entries except contact-us on mobile, which seems normal.
