### ISSUE TITLE
DNS Prefetch is still applied on uncached page

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#690]
but it shouldn't be :)

**Comment by GeekPress** [comment]
Is there any reason / issue to not insert DNS prefetch on uncached page? As this option can't generate issues, why should we remove it to uncached page?

**Comment by webtrainingwheels** [comment]
1. For support debugging purposes we need all optimizations removed. For example, to demonstrate to a customer the difference between using prefetch and not using it (this is how I discovered the issue), by comparing with the ?nocache version of the URL. 
2. I think this optimization is not allowed on AMP pages,  so if a customer wants to exclude their amp  pages from the cache (for example if they are not using the plug in we have compatibility with)  it must also remove prefetch otherwise they could have a validation issue.
