### ISSUE TITLE
 URLs are not fetched when updating from 3.16+ to 3.17

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6914]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.17-alpha1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
Fetched URLs are not added to the LRC table upon plugin update from 3.16+ to 3.17.

**To Reproduce**
1. Have any of the 3.16 versions of the plugin installed.
2. Check the ATF table. => table contains warmup links.
3. Update plugin to 3.17-alpha1 version.
4. Check the LRC table for fetched URLs. => Table created but empty, no fetched URLs are added.

Note: Checking the wp-rocket-debug.log file, the fetched URLs are missing from there, too.

**Expected behavior**
Updating from 3.16+ to 3.17+:
- Should not affect the already fetched URLs from ATF table (timestamp/status didn't change) ✅ 
- Should add the warmup URLs under the LRC table ❌ 

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming.

**Comment by Khadreal** [comment]
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
The version in https://github.com/wp-media/wp-rocket/blob/7999ed2618d11d7fa9b63fc78a7810789072d4b9/inc/Engine/Common/PerformanceHints/WarmUp/Subscriber.php#L78 needs to be updated.

### Scope a solution ✅ 
Change the version from `3.16` to `3.17`

### Estimate the effort ✅ 
[XS]

**Comment by jeawhanlee** [comment]
LGTM

**Comment by hanna-meda** [comment]
Related Test Plan [HERE](https://wpmediaqa.testrail.io/index.php?/runs/view/892&group_by=cases:section_id&group_order=asc).
