### ISSUE TITLE
srstlid query string needs to be ignored

### ISSUE THREAD

**Issue by tullibo** [wp-media/wp-rocket#6927]
Hey guys, Google Shopping is appending the query string ?srstlid to organic Google Shopping traffic is this isn't ignored by default in WPRocket

Details on it here
https://support.google.com/analytics/answer/11479699?hl=en

Can we get this query string added to the default ignore list?

**Comment by DahmaniAdame** [comment]
@tullibo thanks for reporting it. 
Sounds indeed like something we should added into the ignore list. 
Added. 
You can either: 
- Update it manually by going to Tools > Update Inclusion and Exclusion Lists > Update lists
- Wait for it to happen in the background
