### ISSUE TITLE
3.17 - Consider the viewport while calculating `_getElementDistance`

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6933]
**Is your feature request related to a problem? Please describe.**
Consider the viewport size when calculating element's distance to the viewport to avoid misuse of filtering the threshold. 

```
    _getElementDistance(element) {
      const rect = element.getBoundingClientRect();
      const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
      return Math.max(0, rect.top + scrollTop - (window.innerHeight || document.documentElement.clientHeight));
    }
```

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A 

**Additional context**
Related to PR - https://github.com/wp-media/wp-rocket/pull/6929

**Comment by wordpressfan** [comment]
@DahmaniAdame So here we will keep the threshold to be 1800px after the viewport? I also need to make sure that this value will be exactly the same in mobile and desktop or not.

I have a scenario that I don't know if it'll affect the approach here or not,
Think of a page without lrc data in the database and a visitor opened that page from a tablet so it'll calculate the lrc based on that screen then save it in database as mobile version of lrc and then a small mobile device visited the page, will this affect anything here to have the lrc of tablet to be used on mobile?

**Comment by DahmaniAdame** [comment]
Yes, it will be 1800px. 
For now, the value is the same for both mobile and desktop (`content-visibility` is triggered around that point for both). 
The scenario you shared is possible and acceptable for now. If it proves to be an issue (if it is, it would be for any feature dependent on device size, like RUCSS and OCI), we can consider adding a 3rd cache specific for tablets to increase accuracy.

**Comment by piotrbak** [comment]
The risk is the same also for OCI where it's probably more negative impact

**Comment by wordpressfan** [comment]
Awesome, many thanks @DahmaniAdame @piotrbak

**Comment by wordpressfan** [comment]
@wp-media/product 
When we have a parent element and its top is 1800px and that's exactly the threshold value should we consider saving this parent hashes or only consider children?

**Comment by DahmaniAdame** [comment]
> When we have a parent element and its top is 1800px and that's exactly the threshold value should we consider saving this parent hashes or only consider children?

@wordpressfan it will be quite rare to have something in the precise point of the threshold. But if it does, we should collect only the parent's hash for now.
