### ISSUE TITLE
PHP Notice after 2.11.4 update caused by wrongly named variable

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#695]
```
Notice: Undefined variable: tag 
in /…/wp-content/plugins/wp-rocket/inc/functions/posts.php on line 142
```

`$tag` should be `$post`

**Comment by glueckpress** [comment]
`$tag` occurs in [line 142](https://github.com/wp-media/wp-rocket/blob/v2.11.4/inc/functions/posts.php#L142) and [line 134](https://github.com/wp-media/wp-rocket/blob/v2.11.4/inc/functions/posts.php#L134) within the same function.

We have received multiple support requests about this notice.

**Comment by arunbasillal** [comment]
Same at my end too. BuddyPress users especially are affected. Example here: https://secure.helpscout.net/conversation/506931156/57837/

**Comment by mensmaximus** [comment]
The bug occurs with Tribe Events Calendar Pro and Tribe Event Tickets Pro, too. No events can be created any more.
