### ISSUE TITLE
OCI & LRC optimizations should not be applied, even if available, on SaaS visits

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6964]
**Context**
As part of https://github.com/wp-media/wp-rocket/issues/6944, we saw that on SaaS visits (`?nowprocket=1&no_optimize=1&wpr_imagedimensions=1`), LRC and OCI optimizations are applied if possible. This is not needed. We could save some CPU usage on this.

This is due to this line: https://github.com/wp-media/wp-rocket/blob/8b030d399e178aa078d12958cbef47b2285cbc89/inc/Engine/Common/PerformanceHints/Frontend/Subscriber.php#L44

Instead of running the whole `maybe_apply_optimizations` and therefore, maybe call the optimize methods of the factories, we should only maybe inject the beacon, and bypass the calls to optimize.

**Expected behavior**
On SaaS visits (`?nowprocket=1&no_optimize=1&wpr_imagedimensions=1`):
- if one of the PerformanceHints data is not in DB, then the beacon must be injected.
- otherwise, the beacon must not be added. the LRC and OCI optimization must not be applied.
On visits with `wpr_lazyrendercontent` and not wpr_imagedimensions, the beacon must not be injected (already the case) and the LRC hashes must be added (already the case).

**Acceptance Criteria**
On a page with no data stored in DB for OCI/LRC:
- visit the normal page (no query string): hashes are added, beacon is injected.
- visit ?nowprocket=1&no_optimize=1&wpr_imagedimensions=1: hashes are added, beacon is injected.
- visit ?wpr_lazyrendercontent: hashes are added, beacon is not injected.

On a page with data stored in DB for OCI/LRC:
- visit the normal page (no query string): hashes are not, beacon not injected, OCI/LRC optimizations added..
- visit ?nowprocket=1&no_optimize=1&wpr_imagedimensions=1: hashes are not added, beacon is not injected, OCI/LRC optimizations not added.
- visit ?wpr_lazyrendercontent: hashes are added, beacon is not injected, OCI/LRC optimizations not added.

**Comment by Khadreal** [comment]
@MathieuLamiot the accepted criteria is what's currently happening or maybe I'm missing something here

**Comment by MathieuLamiot** [comment]
@Khadreal reproduced here: http://mathieu.e2e.rocketlabsqa.ovh/?nowprocket=1&no_optimize=1&wpr_imagedimensions=1

**Comment by Khadreal** [comment]
### Grooming

in this method https://github.com/wp-media/wp-rocket/blob/8b030d399e178aa078d12958cbef47b2285cbc89/inc/Engine/Common/PerformanceHints/Frontend/Subscriber.php#L56
we can add a logic check before optimization process begin, check if `nowprocket && no_optimize && wpr_imagedimensions` is set.

```
if( isset( $_GET['wpr_imagedimensions'] ) && isset( $_GET['no_optimize'] ) ) {
...
}
OR
if( isset( $_GET['wpr_imagedimensions'] ) && isset( $_GET['no_optimize'] ) && isset( $_GET['nowprocket'] )) {
...
}
```
Add same logic to add_hashes method here
https://github.com/wp-media/wp-rocket/blob/8b030d399e178aa078d12958cbef47b2285cbc89/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L129

## Estimation
[S]

PS -- I think we can make the logic a method that can be reused for other sass visit, can't think of any at the moment.

**Comment by Miraeld** [comment]
Looks good to me.
