### ISSUE TITLE
Typo in French translation

### ISSUE THREAD

**Issue by sebastienserre** [wp-media/wp-rocket#6970]
Hello

When we activate the "unused CSS" feature we have an admin notice which in French is:

`WP Rocket : Veuillez patienter 73 scrondes. La Suppression des ressources CSS inutilisées traite vos pages, le plugin optimise le LCP et les images au-dessus de la ligne de flottaison.`

You can see the typo in `secondes`.

Also
https://youtu.be/g_UjIaYixqM?si=2DJHo_XqdEV3Y1Dy

**Comment by CrochetFeve0251** [comment]
@WordPresseur I saw you were working on translations recently. You might be interested by that.

**Comment by piotrbak** [comment]
@CrochetFeve0251 Already communicated that, it should be part of 3.17, will close the issue when confirmed

**Comment by WordPresseur** [comment]
Fixed in [Transifex](https://app.transifex.com/wp-media/wp-rocket/translate/#fr_FR/rocket-pot--transifex?q=translation_text%3Asecondes) ✅
