### ISSUE TITLE
Update the Lazy Render Content strings with Automatic Lazy Rendering

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6974]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We need to update the Lazy Render Content strings with Automatic Lazy Rendering. 

It looks like the only mention in the UI is present here:
https://github.com/wp-media/wp-rocket/blob/dbcea9f9763d2f6cbfbf5e3e05571cbb1b33b5fd/inc/Engine/Admin/Settings/Page.php#L2251

**Acceptance Criteria (for WP Media team use only)**
1. Strings 'Lazy Render Content' in UI changed with 'Automatic Lazy Rendering' (note the capitalization)
2. No changes to filters
3. No changes to quick actions, clearing data notices

**Comment by wordpressfan** [comment]
We forgot to compile translation files with the release of 3.17 so we need to include this also in that fix.
