### ISSUE TITLE
LRC content-visibility can affect mobile menus when the HTML container of the menu is below the fold

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6979]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The mobile menu does not work if `data-wpr-lazyrender` is set to the HTML DOM element containing the menu.

The menu container id is `**#rhslidingMenu**`, @joejoe04 found it is located below the fold:
![slack-imgs](https://github.com/user-attachments/assets/dbb09de2-a495-4821-9e6b-48ffd7a67574)

This element comes from the **Rehub Theme**, They are loading the menu inside the **rhslidingMenu** div, by using jQuery from this file:
https://sravniceni.com/wp-content/cache/min/1/wp-content/themes/rehub-theme/js/custom.js?ver=1726652057

**To Reproduce**
1. Ue this template: https://jmp.sh/JTe726Mr
2. Enable mobile view, see the menu not working
3. in the source code, using the Elements tab, find `<div data-wpr-lazyrender="1" id="rhslidingMenu">`
4. remove `data-wpr-lazyrender="1"` so it is `<div id="rhslidingMenu">`
5. See the menu working

**Additional context**
ticket: https://secure.helpscout.net/conversation/2710901338/512846?folderId=424682
slack: https://wp-media.slack.com/archives/C07LKLTKBG8/p1726665309176039?thread_ts=1726606365.110269&cid=C07LKLTKBG8

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by DahmaniAdame** [comment]
Related to - https://github.com/wp-media/wp-rocket/issues/6959

**Comment by alfonso100** [comment]
closing in favor of https://github.com/wp-media/wp-rocket/issues/6959
