### ISSUE TITLE
Remove critical CSS once the page is fully loaded

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#698]
To prevent display issues, we should remove the critical CSS `<style>` block once the page is fully loaded, since at that point the stylesheets are loaded the critical CSS is no longer needed.

**Comment by GeekPress** [comment]
I re-open this issue as it hasn't been implemented.

**Comment by GeekPress** [comment]
Duplicate of https://github.com/wp-media/wp-rocket/issues/2635
