### ISSUE TITLE
Follow-up on BerlinDB update and questions

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6986]
**Context**
https://wp-media.slack.com/archives/CUT7FLHF1/p1726744353109299?thread_ts=1726053914.810439&cid=CUT7FLHF1
https://github.com/berlindb/core/pull/166#issuecomment-2362022743

With our recent contribution to BerlinDB, we should keep the discussion going to ensuer we won't break website compatibility with the DB read access on information_schema, and leverage the opportunity to discuss BerlinDB unit testing.

**Expected outcome**
- Get information if possible about use cases of read-access restrictions on information_schema, from JJJ possibly.
- Update BerlinDB in WP Rocket based on the latest changes and possiblty the above discussion.
- Keep the discussion about unit testing going (see https://github.com/berlindb/core/pull/166#issuecomment-2362022743 and https://github.com/berlindb/core/issues/104)

**Comment by MathieuLamiot** [comment]
I could not find specific discussions related to possible issues with accessing information_scheme with WordPress, and WordPress Core does it itself, so let's try to move forward.
@wp-media/engineering-plugin-team Can someone take care of the 2nd bullet point, using this issue for tracking? We should update our dependency to benefit from the latest BerlinDB update. Thanks.

**Comment by hanna-meda** [comment]
Related Test Plan [HERE](https://wpmediaqa.testrail.io/index.php?/runs/view/906&group_by=cases:section_id&group_order=asc).

**Comment by remyperona** [comment]
Should this be in 3.17.1 or 3.17.2? @piotrbak

**Comment by piotrbak** [comment]
@Tabrisrp since it's already tested we can move it into 3.17.1, thanks for asking!
