### ISSUE TITLE
New backend section to handle the Automatic Lazy Rendering exclusions

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6987]
**Is your feature request related to a problem? Please describe.**
We have some different issues related to the layout problems with Automatic Lazy Rendering:
https://github.com/wp-media/wp-rocket/issues/6959

**Describe the solution you'd like**
We'd like to be able to define HTML elements which will not receive hashes during the process (exclude from the feature). It'd allow us to exclude elements before the real fix is applied.

It should work with regex.

**Another approach**
Prevent from adding `data-wpr-lazyrender` attribute to the elements

**Additional context**
We should have a new backend section to handle it

**Comment by MathieuLamiot** [comment]
Discussed with @piotrbak: this would be released as a hotfix, so not including other changes already on develop. To take into account for branch management.

**Comment by Miraeld** [comment]
> We should have a new backend section to handle it

Where is it supposed to be in the backend ?

**Comment by MathieuLamiot** [comment]
From what I understand, there will be a new dedicated section: https://github.com/wp-media/rucss-backend/issues/140

**Comment by wordpressfan** [comment]
## Grooming

Add new method here:

https://github.com/wp-media/wp-rocket/blob/504c5ae5c26164b96c9047c83da12ed2df140993/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L304

```
/**
 * Get the lazy rendered exclusions.
 *
 * @return array
 */
public function get_lrc_exclusions(): array {
	$lists = $this->providers['defaultlists']->data_manager->get_lists();

	return $lists->lazy_rendering_exclusions ?? [];
}
```

Then we need to get those exclusions and use them inside each processor class (Currently we will start with the Dom processor class only)

In Dom class, exactly here:

https://github.com/wp-media/wp-rocket/blob/4b9193bc96b46fd1e8a5db6f3a9bf4126a155eb5/inc/Engine/Optimization/LazyRenderContent/Frontend/Processor/Dom.php#L30

Add the following lines:

```
private $exclusions = [];

public function set_exclusions( $exclusions = [] ) {
	$this->exclusions = $exclusions;
}

private function get_exclusions() {
	return $this->exclusions;
}
```

and exactly here:

https://github.com/wp-media/wp-rocket/blob/4b9193bc96b46fd1e8a5db6f3a9bf4126a155eb5/inc/Engine/Optimization/LazyRenderContent/Frontend/Processor/Dom.php#L108

Loop on the exclusions list if found and use the pattern like the one here:

https://github.com/wp-media/wp-rocket/blob/b16aa79507f8df69f7b79c46968822b78ab087aa/inc/Engine/Optimization/DeferJS/DeferJS.php#L265-L292

to be used in preg_match and bailout if no match.

When setting processor, exactly here:

https://github.com/wp-media/wp-rocket/blob/4b9193bc96b46fd1e8a5db6f3a9bf4126a155eb5/inc/Engine/Optimization/LazyRenderContent/Frontend/Processor/Processor.php#L21

We can apply a new filter like:
```
$exclusions = wpm_apply_filters_typed( 'string[]', 'rocket_lrc_exclusions', [] );
```

Then below the Dom instantiation line, we can call:

```
$this->processor->set_exclusions( $exclusions );
```

Then we need to add a callback for that new filter to get the exclusions from the dynamic list, we can do that here:

https://github.com/wp-media/wp-rocket/blob/7cab3aa6e7a3d8566e4f8abb7e575f7f9d4c4a50/inc/Engine/Optimization/DynamicLists/Subscriber.php#L45

```
'rocket_lrc_exclusions' => 'add_lrc_exclusions'
```
Then create this new method:

```
public function add_lrc_exclusions( $exclusions ) {
	return $this->dynamic_lists->get_lrc_exclusions();
}
```

### Effort: 

S to M including tests time.

**Comment by Miraeld** [comment]
Looks good to me

**Comment by MathieuLamiot** [comment]
Then, do not hesitate to move it to "Todo" @Miraeld ;)
