### ISSUE TITLE
Tutorials Tab Update - INP video

### ISSUE THREAD

**Issue by Agathemed** [wp-media/wp-rocket#6997]
Remove the FID video from the Core Web Vitals section and replace it with the INP one:

**Title:**
How to improve INP with WP Rocket

**Video:**
Available [here](https://wp-rocket.wistia.com/medias/s599wdduu1)(credentials available in bitwarden)

`<script src="https://fast.wistia.com/embed/medias/s599wdduu1.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><span class="wistia_embed wistia_async_s599wdduu1 popover=true videoFoam=true" style="display:inline-block;height:100%;position:relative;width:100%">&nbsp;</span></div></div>`

**Comment by piotrbak** [comment]
Related past issue:
https://github.com/wp-media/wp-rocket/issues/4541

Video to be removed (replaced with the new, provided one):
![image](https://github.com/user-attachments/assets/73be5d33-6a2e-4f22-866e-66e229e2f0b2)

**Comment by Miraeld** [comment]
## Scope a solution
Pretty simple, [here](https://github.com/wp-media/wp-rocket/blob/7cb98ada823004df2174267dcd73a4fe35c47c6c/views/settings/page-sections/tutorials.php#L26), change the key `krqb7ckugp` by `s599wdduu1` & change the text to `How to improve INP with WP Rocket` 
Should get this at the end: 
``` php
			's599wdduu1' => __( 'How to improve INP with WP Rocket', 'rocket' ),
```

## Effort 
XS
