### ISSUE TITLE
JS minification breaks WP Recipe Maker pro plugins

### ISSUE THREAD

**Issue by smerriman** [wp-media/wp-rocket#7000]
With Minify JS on and WP Recipe Maker Pro active, minification is breaking JS files by deleting large parts of the script.

**To Reproduce**
Install WP Recipe Maker Pro
Visit a page with a recipe where the public-pro.js is output
Notice that the minified script is cut off after `{test:[/\sedg\//i`

**Expected behavior**
The script should not be broken by the minifier.

**Additional context**
I did notice an old thread about this - https://github.com/wp-media/wp-rocket/issues/2974 - but it was from 4 years ago and marked as closed. WP Recipe Maker is a very popular plugin, so I've had to go through all of my clients sites and add exclusions - but this will be affecting a lot of people.

**Comment by webtrainingwheels** [comment]
This is a related case: https://secure.helpscout.net/conversation/2719039223/514571?folderId=377611 (for internal use only)
Excluding `/wp-content/plugins/wp-recipe-maker-premium/dist/public-premium.js` fixed multiple issues.

**Comment by piotrbak** [comment]
@webtrainingwheels That one could go directly to the backend, right? 🤔

**Comment by webtrainingwheels** [comment]
@piotrbak This has been added to the backend!

**Comment by piotrbak** [comment]
Thanks @webtrainingwheels closing the issue as it'll be handled automatically now
