### ISSUE TITLE
Issue with the LazyLoad After Ajax Request Done

### ISSUE THREAD

**Issue by kartikpotenza** [wp-media/wp-rocket#7007]
**Describe the bug**
I have set the lazy load enable and due to that having the issue for product images after ajax request, What is happing's is when I go to product single page that contains one tag which basically anchor tag which contains the query string with which filter the product for same type and redirects to shop page with filter selected. Now when I click on clear filters it clears the filters and generates new ajax request which is basically shop page which I replace with old shop listing content. In which most of images still black, not loaded.

**To Reproduce**
1. Go to https://woocommerce-762794-2848808.cloudwaysapps.com/shop/
2. Click on  any product
3. Click on tags like this one - https://prnt.sc/iq9rbucgwFLs
4. Now Click on clear filter - https://prnt.sc/3Aj2D4Isyedx

**Expected behavior**
It should load images properly

**Screenshots**

![image](https://github.com/user-attachments/assets/a942557e-07fb-40b1-ae96-9a51cce0f216)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 129.0.6668.90 (Official Build) (64-bit)

**Additional context**
I am using the latest version of the WP Rocket - 3.17.0.2

**Comment by piotrbak** [comment]
Hello @kartikpotenza could you tell me which filters plugin is used to handle this?

**Comment by kartikpotenza** [comment]
Everything is Custom created no plugin has been used for the filters, Basically it's fetching the entire page using get request

jQuery.get( new_url ).success( function( data ) {});

Here "new_url" is the shop page URL with query string for filter out data, and layout get replaced for shop listing after success and complete of ajax call. Let me know if you need further details.

**Comment by piotrbak** [comment]
I understand. We do not have any other feedback from our customers related to this problem, it means that we'll not be able to implement any kind of enhancement for it in the nearest future.

However, as your site is custom, you'll be able to fix it on your own. Please check the documentation related to the lazyload library we use, there's a section for Ajax also:
https://github.com/verlok/vanilla-lazyload

**Comment by kartikpotenza** [comment]
It's Clearly an  issue not an enhancement, I thought you will give some solution or idea about why it's happing at least, Any way I fixed it my self. It's happening due to uncached page loading the cached version of the of the page, And lazy load not initializing after that.
