### ISSUE TITLE
rocket_init extremely slow

### ISSUE THREAD

**Issue by shane-clickingmad** [wp-media/wp-rocket#7016]
While we are enjoying the cached response times of pages I noticed that anything uncached is substantially slower with the wp-rocket plugin enabled adding roughly 200ms to the response time.

For context, out admin dashboard response time is 140ms total without wp-rocket

Doing some digging it appears that rocket_init is accounting for over over 115ms of this.

This was also replicated with a fresh install of WordPress and default theme, again adding 200ms to admin response times. (36ms to 230ms)
Here is a screenshot from the profiler of said test

![Image](https://github.com/user-attachments/assets/45eb9fb5-6413-4e70-865f-ab3bb35bb21f)

rocket_init doesnt account for the full 200ms we are seeing, but it is a big portion and way more then any of our other plugins for sure

**Comment by piotrbak** [comment]
Hello @shane-clickingmad thanks for creating the issue. We're continously working on improving the performance of the plugin, including the `rocket_init`. 

Please keep in mind that we're using GitHub for development purposes. It means that the issues need to have proper instructions for developers about what should be the output of the increment. 

We'll continue doing improvements in that part. If you have a specific idea or request related to `rocket_init` please share it and we'll consider and investigate.
