### ISSUE TITLE
code displayed on page when optimize css delivery is active

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#702]
e.g. https://secure.helpscout.net/conversation/503578489/57497?folderId=273761
https://wp-media.slack.com/archives/C43T1AYMQ/p1515701835000125

**Comment by glueckpress** [comment]
There are a couple more reports about this, for example the closing `>` of a link element gets cut off by an inline style element:

```
<link rel='preload' href='example.css' type='text/css' media='only screen and (max-width: 768px)' /<style id='example-inline-css' type='text/css'>.woocommerce-checkout .shop_table{background-color:#eee}</style>
```
