### ISSUE TITLE
PHP Notice:  Undefined property: stdClass::$table_name when enable database options on apache server

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#7028]
**Describe the bug**
When enabling database options and saving, many entries like this appear in debug.log
`[11-Oct-2024 05:14:07 UTC] PHP Notice:  Undefined property: stdClass::$table_name in /home/wpquicki/mega/avada/wp-content/plugins/wp-rocket/inc/Engine/Admin/Database/OptimizationProcess.php on line 131`

**To Reproduce**
1. fresh install of WPR 3.17.1 or 3.17.0.2 on apache server i.e https://mega.wp-rocket.me/divi/
2. Enable database options and save
3. Check debug.log

**Expected behavior**
No undefined notice added to debug when enabling DB options at WPR

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome Version 125.0.6422.141
 - site https://mega.wp-rocket.me/divi/

**Additional context**
- not happening on ngnix server ex: e2e.rocketlabsqa.ovh
- slack thread https://wp-media.slack.com/archives/CUT7FLHF1/p1728624908143909

**Comment by piotrbak** [comment]
Related:
https://github.com/wp-media/wp-rocket/issues/5572

**Comment by Khadreal** [comment]
The query in https://github.com/wp-media/wp-rocket/blob/e780e828e7b447559c6b6939218401bdbc39bc9a/inc/Engine/Admin/Database/OptimizationProcess.php#L127 is returning the column names in upper case(this is likely from the mysql/pdo setup of the server). 
To solve this we can add an alias to the columns in the query.

**Comment by Khadreal** [comment]
Created a [PR](https://github.com/wp-media/wp-rocket/pull/7031) here for review

**Comment by Mai-Saad** [comment]
For testing:
- Please follow steps in the main issue and confirm that it's working fine on apache i.e mega/avada , ngnix i.e new.rocketlabsqa and multisite   for both main and subsites (credentials on BW for mega multisite ) https://wpmediaqa.testrail.io/index.php?/cases/view/16694
