### ISSUE TITLE
Infinite HTTP 302 requests after upgrading to 3.17.0.2

### ISSUE THREAD

**Issue by robd003** [wp-media/wp-rocket#7030]
Currently I cannot access the WP-Rocket plugin settings page.

I get an infinite loop of HTTP 302 Location responses all to 'https://{my-domain}/wp-admin/options-general.php?page=wprocket'

Not sure how to debug this, nothing shows up in my PHP error log.

**Comment by piotrbak** [comment]
Hello @robd003 that sounds like a support request. Could you reach our Support Team using our website?
https://wp-rocket.me/support/
