### ISSUE TITLE
Consider adding support for Git Updater and RepoMan

### ISSUE THREAD

**Issue by jessuppi** [wp-media/wp-rocket#7043]
Hello there,

Please consider adding support for Git Updater and RepoMan by adding these lines to your plugin header:

```
GitHub Plugin URI: wp-media/wp-rocket
Primary Branch: trunk
```

Ref: https://github.com/wp-media/wp-rocket/blob/develop/wp-rocket.php

More info:

https://github.com/littlebizzy/repoman

**Comment by piotrbak** [comment]
@MathieuLamiot @Tabrisrp Might need your input here 🙏 

@jessuppi Thanks for creating the issue

**Comment by piotrbak** [comment]
Hello @jessuppi please feel free to add a PR to handle this. We'll discuss it further internally then.

Thanks

**Comment by jessuppi** [comment]
I am contacting hundreds of plugin authors to spread awareness of using GitHub to install new WordPress plugins so I would rather avoid getting involved in PRs as it takes time to learn every single plugin's workflow and branches.

If possible I would encourage you to reopen this while you consider it, especially since your plugin is not on WP.org. Cheers!

**Comment by MathieuLamiot** [comment]
@jessuppi Reading the description of RepoMan, it is mentioned it is for free plugins. WP Rocket requires a license to run, can you elaborate on how this would be handled?

**Comment by jessuppi** [comment]
Hello @MathieuLamiot For RepoMan it simply allows any WordPress user to search and install plugins from GitHub repos, so any user could search "WP Rocket" and find your plugin and install it directly from GitHub. If they are required to input a license key after that in order to get the full features of the plugin, they should be able to do that as normal after the installation.
