### ISSUE TITLE
Add auto JS exclusions for Cookie Yes

### ISSUE THREAD

**Issue by addedlovely** [wp-media/wp-rocket#7044]
**Is your feature request related to a problem? Please describe.**
Can you add default exclusions for the cookieyes cookie banner service. 
Currently when JS minification is enabled and changes made on the cookie yes webapp don't get applied to the site. 

The cookie banner still works, so it's not super obvious that a breaking change occurs, just the listing of cookies in the 'settings' page of the cookie banner do not update.

**Describe the solution you'd like**
Script patterns to be excluded:
```
client_data/(.*)/script.js
cookie-law-info
_ckyGcm
```

Reference:
[https://www.cookieyes.com/documentation/exclude-cookieyes-script-from-wp-rocket-plugin/#:~:text=Steps%20to%20exclude%20CookieYes%20script%20from%20the%20WP%20Rocket%20plugin,-Step%201.&text=Log%20in%20to%20your%20WordPress,to%20the%20JavaScript%20Files%20section.
](https://www.cookieyes.com/documentation/exclude-cookieyes-script-from-wp-rocket-plugin/#:~:text=Steps%20to%20exclude%20CookieYes%20script%20from%20the%20WP%20Rocket%20plugin,-Step%201.&text=Log%20in%20to%20your%20WordPress,to%20the%20JavaScript%20Files%20section.
)

**Additional context**
Plugin has 1+ million installs so feel a default exclude would be beneficial

**Comment by alfonso100** [comment]
Added the suggested exclusions to our SaaS backend
