### ISSUE TITLE
Add method to define server software

### ISSUE THREAD

**Issue by crobbinsdg** [wp-media/wp-rocket#7048]
**Is your feature request related to a problem? Please describe.**
The WP global php vars $is_apache, $is_IIS, $is_iis7, $is_nginx, $is_caddy are not always accurate.  I'm often running into issues where wp-rocket is not adding/updating its htaccess rules on Apache environments where the var $is_apache is not accurate.  

Those WP globals are defined by looking for strings in the Server header.  However it is common now to remove that header for compliance and/or have them replaced with custom values when using a proxy caching service. 

**Describe the solution you'd like**
I know it is big lift as those globals are used in many places to define functionality in the plugin.  For my specific needs I am mostly dealing with Apache.  Something like a filter hook to define a wp-rocket's variable version of $is_apache would be great.

**Describe alternatives you've considered**
Current work around is to add `$_SERVER["SERVER_SOFTWARE"] = "Apache";` to the wp-config.php file.

**Additional context**
I also totally understand if this is really something that should be fixed in the WP core and not at the plugin level.  I recently added to the 9yr old ticket to get those global variable definitions updated. https://core.trac.wordpress.org/ticket/36486

**Comment by piotrbak** [comment]
Hello @crobbinsdg this is not something that could be shipped into WP Rocket anytime soon. Basically, we don't have customers asking for it and the general product outcome would have low value.

I'll close it for now to remove it from the backlog of the items that we plan to fix in the mid term. It's not said that we'll not fix it at all though.

If you'd like it to be inside the core and you will to contribute, feel free to add a PR.
