### ISSUE TITLE
Performance issue with table existence query

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#7049]
**Describe the bug**
In the PR #6968 we started using `information_schema.tables` to detect the existence of our tables, exactly here:
https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/inc/Engine/Common/Database/Queries/AbstractQuery.php#L523

Then we got a report that this query will return values for all databases on the server even for databases that the user doesn't have access to.

**To Reproduce**

I don't have a clear way to reproduce the issue on our local sites but seems like we may need to create two mysql users on the same server and for each user, create a database, and see if the query will return values from all databases.

**Expected behavior**
We should only detect the table existence on the current database that we have proper access to.

**Possible solution**

we already use the same concept in database optimization query, here:
https://github.com/wp-media/wp-rocket/blob/73488699424f726bef28dbf2c934340efcab8e47/inc/Engine/Admin/Database/Optimization.php#L101

**Comment by chrisdavidmiles** [comment]
Hey original reporter here, seeing the issue for Bluehost, Hostgator, and a few others.

To add some context, the query will make an attempt to gather values for all databases on a server, even for databases it doesn't own. While it doesn't get the data, checking permissions and failing on every DB is time consuming and resource intensive, especially on Shared hosting environments. The result is performance impact not only for the site the plugin is running on, but for every site across the server.

More details around this behavior (and optimization recommendations) can be found at https://dev.mysql.com/doc/refman/5.7/en/information-schema-optimization.html

To replicate, as far as I can tell, this needs to be tested with an user that doesn't have 'SUPER' privileges. (With SUPER it doesn't do the same). 

Or if your test environment only had a few users for testing each with just a few DBs, it would be difficult to see the issue.

**Comment by chrisdavidmiles** [comment]
The issue only started on the latest version 3.17.1 but it's causing enough performance degradation in shared hosting environments with many users and DBs that we're looking at patching existing sites ourselves. I suspect other hosts may take more aggressive remediation efforts.


For reference:
```
3.17.0.2 (previous version, no issue)
wp-content/plugins/wp-rocket/inc/Engine/Admin/Database/Optimization.php:        $count = $wpdb->get_var( "SELECT COUNT(table_name) FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "' and Engine <> 'InnoDB' and data_free > 0" );
wp-content/plugins/wp-rocket/inc/Engine/Admin/Database/OptimizationProcess.php:        $query = $wpdb->get_results( "SELECT table_name, data_free FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "' and Engine <> 'InnoDB' and data_free > 0" );
```
```
3.17.1 (latest version, creating performance issues)
wp-content/plugins/wp-rocket/inc/Engine/Admin/Database/Optimization.php:        $count = $wpdb->get_var( "SELECT COUNT(table_name) FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "' and Engine <> 'InnoDB' and data_free > 0" );
wp-content/plugins/wp-rocket/inc/Engine/Admin/Database/OptimizationProcess.php:        $query = $wpdb->get_results( "SELECT table_name, data_free FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "' and Engine <> 'InnoDB' and data_free > 0" );
wp-content/plugins/wp-rocket/inc/Engine/Common/Database/Queries/AbstractQuery.php:    $query    = 'SELECT table_name FROM information_schema.tables WHERE table_name = %s LIMIT 1';
wp-content/plugins/wp-rocket/inc/Engine/Common/PerformanceHints/Database/Queries/AbstractQueries.php:    $query    = 'SELECT table_name FROM information_schema.tables WHERE table_name = %s LIMIT 1';
```

**Comment by piotrbak** [comment]
Hello @chrisdavidmiles, thanks for your input here. Do you see any possibility to test this PR on your environment? Just to confirm that it fixes the problem on your end.

In the meantime we'll be running our tests, of course.

**Comment by chrisdavidmiles** [comment]
We will test with v3.17.2 and report back. Thanks!

**Comment by chrisdavidmiles** [comment]
We will test this patch and report back. Thanks!

**Comment by chrisdavidmiles** [comment]
A few hours after the performance issue was introduced in v3.17.1, Bluehost created a patch and rolled it out to their sites to maintain performance. The proposed wp-rocket patch here https://github.com/wp-media/wp-rocket/commit/9f3b827f9af22ede62454ed308343828828e4477 seems to take the same approach as we did. The idea being that if db is wrong, the query would just fail at that point, and it wouldn't do the expensive permission checking. The only difference is that the wp-rocket patch seems to pass the DB name in a probably more robust manner. 

Your patch looks good! Thanks for responding to this and providing a solution to our mutual customers. Looking forward to seeing this in v3.17.2.

**Comment by chrisdavidmiles** [comment]
Thank you @piotrbak. A few hours after the performance issue was introduced in v3.17.1, Bluehost created a patch and rolled it out to their sites to maintain performance. The proposed wp-rocket patch here https://github.com/wp-media/wp-rocket/commit/9f3b827f9af22ede62454ed308343828828e4477 seems to take the same approach as we did. 

Your patch looks good! Thanks for responding to this and providing a solution to our mutual customers. Looking forward to seeing this in v3.17.2.

**Comment by arekm** [comment]
There is a big room for improvement still.

Querying information schema is very, very slow compared to just SHOW TABLES LIKE.
 
Example, mysql (percona) 5.7 server with over 5k databases, over 300k tables, over 16k users:

````
23:24:22 mysql{1}> SELECT table_name FROM information_schema.TABLES WHERE table_name = 'wp_wpr_preconnect_external_domains' LIMIT 1;
+------------------------------------+
| table_name                         |
+------------------------------------+
| wp_wpr_preconnect_external_domains |
+------------------------------------+
1 row in set (22,02 sec)
````

vs

````
23:24:54 mysql{2}> SHOW TABLES LIKE 'wp_wpr_preconnect_external_domains';
+----------------------------------------------------------+
| Tables_in_testdb (wp_wpr_preconnect_external_domains) |
+----------------------------------------------------------+
| wp_wpr_preconnect_external_domains                       |
+----------------------------------------------------------+
1 row in set (0,00 sec)
````

Any specific reason for querying information_schema for this in current code?
