### ISSUE TITLE
Caching not working because of port number in HTTP_HOST

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#706]
**Problem: WP Rocket not caching anything.**

**Cause:**
`HTTP_HOST` is not being processed correctly in [inc/front/process.php#46](https://github.com/wp-media/wp-rocket/blob/9ff3285580fda031d961be908eb863c258b19ab2/inc/front/process.php#L46). 

When `HTTP_HOST` contains a port number, the value of the host variable is something like `example.com:443`, instead of just `example.com`. Hence, caching doesn’t work as intended.

**Solution:**
The port number needs to be removed in order to load WP Rocket’s config file correctly.

A customer suggested to add the following after line 46:

```php
$host = preg_replace('/:\d+$/', '', $host);
```

The entire code block replacing [inc/front/process.php#L46-L48](https://github.com/wp-media/wp-rocket/blob/v2.11.4/inc/front/process.php#L46-L48) would look like this:

```php
$host = ( isset( $_SERVER['HTTP_HOST'] ) ) ? $_SERVER['HTTP_HOST'] : time();
$host = preg_replace('/:\d+$/', '', $host);
$host = trim( strtolower( $host ), '.' );
$host = rawurlencode( $host );
```

**Comment by TBarregren** [comment]
I can confirm both the bug and the fix. I'm running a WP on port 8080 behind a reverse proxy. I noticed that the /wp-content/cache/wp-rocket/www.example.com/  directory always was empty. Found this ticket and applied the fix, and voilà. Everything works as expected after the fix.
