### ISSUE TITLE
3.18 -  Enhancement on saving and reading the font files

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#7067]
**User Story**
As a user, I want to use the same local font files for pages using the same set of fonts, even declared in a different order.

**Acceptance Criteria**
- If the requested font file exits in the filesystem, we should reuse it instead of downloading and overwriting
- If the requested font file doesn't exist in the filesystem, we should download it
- The above points should be compatible with multisite

**Additional information**
- Since [7175](https://github.com/wp-media/wp-rocket/issues/7175) became a requirement for the release, we'll need to have this one too

**Comment by Khadreal** [comment]
@piotrbak please can we get the acceptance criteria so we can groom this

**Comment by piotrbak** [comment]
@Khadreal This is an enhancement proposed by @MathieuLamiot 

Do you feel we should take care of the grooming right away, or we can treat it as an enhancement and tackle this later on during the development process?

**Comment by MathieuLamiot** [comment]
It won't be needed for initial release, I think we can start implementing what we have already and circle back on this one later on

**Comment by piotrbak** [comment]
Since [7175](https://github.com/wp-media/wp-rocket/issues/7175) became a requirement for the release, we'll need to have this one too

**Comment by remyperona** [comment]
This was handled in https://github.com/wp-media/wp-rocket/pull/7166
