### ISSUE TITLE
wp-rocket-config is generated when it shouldn't in certain scenario

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#7082]
**Describe the bug**
While WPR debug is enabled, and rocket config path is set , the wp-rocket-config folder is created for WPR log instead of using the one defined in config path

**To Reproduce**
1. Change rocket config path  in config file 'define( 'WP_ROCKET_CONFIG_PATH', $_SERVER['DOCUMENT_ROOT'] . '/new-path/' );'
2. Enable WPR debug in config file 'define( 'WP_ROCKET_DEBUG', true);'
3. Install and activate WPR 
4. Note that new-path is created in root and wp-rocket-config is created in wp-content
5. deactivate and uninstall WPR => wp-rocket-config is not removed

**Expected behavior**
use new folder too while WPR debug is enabled and not creating wp-rocket-config

**Screenshots**

**Additional context**

**Comment by piotrbak** [comment]
Pausing it for now as we'll not be able to prioritise this soon. We might revist this while fixing things related to filesystem.
