### ISSUE TITLE
3.17.2 Blank page in paginated WooCommerce product category pages when WebP add-on is enabled

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#7088]
**Describe the bug**
When using the WP Rocket WebP addon, the paginated WooCommerce product categories are displayed as a blank page. 
the HTML is empty, the only visible content is this comment: 

`
`

**To Reproduce**

1. on 3.17.2
2.  Enable WebP addon
3. Visit a paginated product category example `/product-category/catname/page/2/`
4. See the blank page, check the source code
5. rollback to 3.17.1, refresh the page, the issue is gone

**Additional context**
Slack convo
https://wp-media.slack.com/archives/C07LKLTKBG8/p1730713053010039

tickets: 
https://secure.helpscout.net/conversation/2752903312/521120?folderId=273761
https://secure.helpscout.net/conversation/2752671702/521087?folderId=273766
https://secure.helpscout.net/conversation/2753376773/521243?folderId=273766

**Comment by johan-las** [comment]
Related case : https://secure.helpscout.net/conversation/2752835599/521110/

Exact same symptom and work on previous version, but with pages generated by the _Brands for WooCommerce_ plugin

**Comment by jekayode** [comment]
Related ticket: https://secure.helpscout.net/conversation/2752973886/521136?folderId=8127831

Some redirected Custom Post type archive pages are blank.

**Comment by hawilkins** [comment]
Seeing WSOD on paginated (standard WordPress) category archive pages across multiple sites on various themes as well.

Paginated pages are not broken while logged in or with ?nowprocket. Rolling back resolves the issue.

**Comment by jekayode** [comment]
Related: 

https://secure.helpscout.net/conversation/2754414270/521439?folderId=8127831
https://secure.helpscout.net/conversation/2754532611/521466/

**Comment by suzoutlet** [comment]
Related case: https://secure.helpscout.net/conversation/2753900666/521310/

**Comment by jekayode** [comment]
Related case: https://secure.helpscout.net/conversation/2755314209/521609?folderId=8127831
