### ISSUE TITLE
WordPress 6.7 Compatibility - Translations loading too early

### ISSUE THREAD

**Issue by vlaskiz** [wp-media/wp-rocket#7102]
**Describe the bug**

"Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the rocket domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)"

As per the notice on WP 6.7.0, translations are being loaded too early and should be moved to another (init or later) hook.

**Comment by piotrbak** [comment]
Hello @vlaskiz thanks for creating the issue.

We've been trying to replicate the issue but we were not able to. Could you provide us steps or environment that's needed in order to move forward?

If you're not sure about that, it'd be great if you could share with us access to your website.

**Comment by remyperona** [comment]
@piotrbak I'm able to reproduce the issue with WP 6.7 locally

**Comment by piotrbak** [comment]
@remyperona Any particular steps? 🤔 

CC @wp-media/qa-team

**Comment by vlaskiz** [comment]
Hello,

It's a PHP notice, so you would need to check if you can see those. Can be easily detected with Query Monitor.

But you are right, looking at it, on some websites it generates the notice among a few other plugins, and on some it does not (with same other plugins present, that do not generate the notice either).

Either way, you are hooking translations into plugins_loaded hook, while the notice recommends 'init' or later.

**Comment by remyperona** [comment]
I looked into what was triggering the warning, there is 3 files to update to prevent it. And we should also update the hook on which we load the translations like said above.

I can create a quick PR for this change

**Comment by piotrbak** [comment]
Yes, let's do it since it'll be flooding the support team. We'll need to have a way to reproduce it for the QA team tests though.

**Comment by mircobabini** [comment]
In core, the check is against `after_setup_theme` action already run or not.

**Comment by leodassma** [comment]
how to solve this problem ?? if anyone tell me how to solved .

**Comment by mircobabini** [comment]
Wait for a release. In the meanwhile, be sure to have WP_DEBUG_LOG = false or use a filter to temporarily suppress doing-it-wrong notices.

`add_filter( 'doing_it_wrong_trigger_error', '__return_false' );`

Temporary but effective.

**Comment by mmariom** [comment]
define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);
define('WP_DEBUG_LOG', false);

Then don't forget to restart your server and purge the cache if you use some!

**Comment by vijetaR** [comment]
Could someone please help with a test case to check locally, or provide any helpful steps? I did check using Query Monitor, but no notices were shown.

**Comment by leodassma** [comment]
> Could someone please help with a test case to check locally, or provide any helpful steps? I did check using Query Monitor, but no notices were shown.

add_filter( 'doing_it_wrong_trigger_error', '__return_false' );   use this bro .

**Comment by leodassma** [comment]
> Wait for a release. In the meanwhile, be sure to have WP_DEBUG_LOG = false or use a filter to temporarily suppress doing-it-wrong notices.
> 
> `add_filter( 'doing_it_wrong_trigger_error', '__return_false' );`
> 
> Temporary but effective.

thank you so much bro...👍 It works ...

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2764307572/523591/

**Comment by supertrooper2** [comment]
I am unsure into which file the following code should be inserted:

add_filter( 'doing_it_wrong_trigger_error', '__return_false' );

Should it ne inserted into the functions.php file?

Please advise.

**Comment by mircobabini** [comment]
@supertrooper2 Create the mu-plugins folder into wp-content if it does not exist. Then create a `disable-doing-it-wrong-notice.php` into it and paste this.

```php
<?php
/**
 * Plugin Name: Disable Doing It Wrong Notice (Load Textdomain)
 * Description: Disables the "Doing it wrong" notice that appears when a textdomain is loaded just in time.
 */
add_filter( 'doing_it_wrong_trigger_error', function ( $doing_it_wrong, $function_name ) {
	if ( '_load_textdomain_just_in_time' === $function_name ) {
		return false;
	}

	return $doing_it_wrong;
}, 10, 2 );
```

**Comment by supertrooper2** [comment]
Hi Mirco


The mu-plugins folder does exist. I am not a coding expert.

Could you please send me the disable-doing-it-wrong-notice.php file?

Thanks in advance

**Comment by supertrooper2** [comment]
Hi Mirco, I managed to create the disable-doing-it-wrong-notice.php file and it works perfectly.

Many thanks for the great support.

**Comment by Wesley-Carnicle** [comment]
I added the file and haven't seen it do anything yet

**Comment by richstandbrook** [comment]
I've got the latest version installed and it appears to have the `add_action( 'init', 'rocket_load_textdomain' );` fix – yet I'm still getting `_load_textdomain_just_in_time was called incorrectly. Translation loading for the rocket domain was triggered too early`
