### ISSUE TITLE
3.17.2 - Product Category not cached for permalink containing letters in non-latin alphabets

### ISSUE THREAD

**Issue by johan-las** [wp-media/wp-rocket#7106]
**Describe the bug**
Since WP Rocket version **3.17.2**, Product Categories with permalink containing letters in non-latin alphabets are not cached.

This seems the consequence to this modification: https://github.com/wp-media/wp-rocket.me/issues/4164

Tested rolling back to version **3.17.1**, and the Product Categories are being cached.
 

**To Reproduce**
1. Go on a WordPress with Woocommerce and Cyrillic URLs.
2. Have WP Rocket version **3.17.2** installed.
3. Visit a category page.
4. Verify the cache folder.

**Expected behavior**
The cached files should appear in the cache folder.

**Additional context**

Slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1731498835653169
Related ticket: https://secure.helpscout.net/conversation/2759701726/522550?folderId=8127840

Probably related modification : https://github.com/wp-media/wp-rocket.me/issues/4164

**Comment by wordpressfan** [comment]
The issue only happens with websites that changes the permalink base (WP Admin >> Settings >> Permalinks) for any taoxnomy like `WooCommerce Product Category`, `Posts Category`, `Posts Tags`, ...etc.

There is a WP Core ticket talking about the same issue here:
https://core.trac.wordpress.org/ticket/16839
and here:
https://core.trac.wordpress.org/ticket/39873

I'm trying to find a quick solution from our side...
