### ISSUE TITLE
Preloaded LCP link not updated when new post published

### ISSUE THREAD

**Issue by rennewpeter** [wp-media/wp-rocket#7118]
**Describe the bug**
I have a news site that is updated quite often. The LCP element is preloaded by WPRocket and it is fine until a new post appears. In this case the preload link is not updated and the image of the previous news remains preloaded. I can override this by manually clearing Priority Elements in the dashboard. Is it possible to make this automatic but only on the homepage? I don't want to clear the entire cache for this.

**To Reproduce**
If the prelod lcp is created, just publish a new post. A preload link not updated

**Expected behavior**
If i post a new post update the preloaded LCP.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by piotrbak** [comment]
Hello @rennewpeter 

Please find this helper useful, you can easily adapt it to your needs.
https://github.com/wp-media/wp-rocket-helpers/tree/master/priority-elements/wp-rocket-clear-priority-elements-specific-pages

Thanks
