### ISSUE TITLE
Select Youtube Preview Thumbnail Resolution

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#712]
Currently we default to: hqdefault.jpg for the preview image, but that can provide a poor quality image, e.g. https://prnt.sc/i1p9bo
Could we have a way to default to, or allow the user to select maxresdefault.jpg instead?

Sample tickets: 
https://secure.helpscout.net/conversation/507363009/57890?folderId=273761
https://secure.helpscout.net/conversation/487570189/55558/?folderId=273766

**Comment by Tabrisrp** [comment]
We can add a filter to modify the thumbnail URL
