### ISSUE TITLE
Unnecessary preconnect links

### ISSUE THREAD

**Issue by rennewpeter** [wp-media/wp-rocket#7140]
**Describe the bug**
Google Tag Manager and Google Analytics javascript is delayed, but still adds domains link with preconnect.

**To Reproduce**
Enable delay

**Expected behavior**
If these javascripts is delayed remove preconnect link

**Screenshots**
![Image](https://github.com/user-attachments/assets/d2a6b964-6039-4d28-9f24-a231df5c6f7c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by piotrbak** [comment]
@gmetais Does it come from the preconnects inside the script itself? 🤔

**Comment by gmetais** [comment]
Yes @piotrbak, this is DelayJS preconnecting delayed 3rd parties.
It consumes just a few bytes of bandwidth, but helps a lot accelerating those resources on first user interaction.
I think we should not remove those despite the warnings, what do you think?

**Comment by piotrbak** [comment]
@rennewpeter There's no performance reason to deactivate this preconnect that's happening inside the script. We might revisit this in the future while redesigning part of the Delay JS script itself though.

@gmetais Thanks!
