### ISSUE TITLE
3.18 Host google fonts locally while optimize Google font is disabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#7144]
Currently, we are hosting Google fonts locally while optimize google fonts is disabled. 
![Image](https://github.com/user-attachments/assets/94ffa417-c52c-4b25-94e7-55695d47c33a)

@wp-media/product what is the expected here? shall we disable the option or enable optimization if checked?

**Comment by piotrbak** [comment]
It's expected behaviour for now. We might reopen this in the future.
