### ISSUE TITLE
Adding more measurements for fonts download

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#7170]
**Is your feature request related to a problem? Please describe.**
From last discussion with @DahmaniAdame we found that the measurement logs that we added are not enough because currently we count the number of google fonts CSS files but we need to count the number of fonts inside each CSS file because we download them one by one.

**Describe the solution you'd like**
Here:
https://github.com/wp-media/wp-rocket/blob/c57f2f9c65417603c63bb934e711ccdac894dc01/inc/Engine/Media/Fonts/Filesystem.php#L86

We have the main css font url and the matched fonts inside it so we can log the followings:
1. Number of fonts inside each css file
2. Time taken to download all fonts found inside this specific css file
3. The average of download time for one font file
4. The exact real download time for each specific font file.

**Describe alternatives you've considered**
This will cover all what is needed to take a decision if we have a timing problem or not.

**Additional context**
Slack discussion: https://wp-media.slack.com/archives/C015FT0RBKQ/p1733392204790519?thread_ts=1733165956.129749&cid=C015FT0RBKQ

@wp-media/product do u need to add anything here more than that?

**Comment by DahmaniAdame** [comment]
Looks good. Nothing to add on my side.
