### ISSUE TITLE
Add CNAME button and "reserved for" missing once the RocketCDN subscription is validated

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#7171]
**Describe the bug**
Once the user successfully validates the RocketCDN subscription, the `Add CNAME` button and `"reserved for"` dropdown are no longer present in UI. 

**To Reproduce**
1. Install & activate WP Rocket on a site linked to a valid RocketCDN plan.
2. On the  CDN tab, add multiple CDN CNAMEs with different file types for`reserved for`.
3. Check "Enable Content Delivery Network" and save changes.
4. Click "Get Started" on the RocketCDN pricing banner and log in to validate the subscription. 
5. Refresh the page.
6. Inspect the CDN CNAME(s) section:
     ===> Notice that `Add CNAME` button and `"reserved for"` dropdown are missing.

Note:
Selecting only a certain type, i.e. image, before validating the subscription, then only images paths will be rewrritten to the CDN path. So, although the option is not in UI it is still effective. 

**Expected behavior**
@wp-media/product to give direction considering that, at one point, the plan was to drop multiple CDN CNAME choices (#3417).

**Screenshots**
Video [LINK](https://github.com/user-attachments/assets/546b50cd-524c-4212-9270-88b88d80441f)

![Image](https://github.com/user-attachments/assets/b41c4662-bd74-4bd4-9104-256967646278)

**Comment by remyperona** [comment]
If I remember correctly, it was a choice that when using RocketCDN, you can only use one cname, and it applies to all files.

**Comment by piotrbak** [comment]
Yes, this was not specified I believe, but we wanted to get rid of this possibility
