### ISSUE TITLE
Multi Tiers upgrade new structure - part 2 - UI in settings page

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/wp-rocket#7177]
**Is your feature request related to a problem? Please describe.**
Part of this issue: https://github.com/wp-media/wp-rocket.me/issues/4326 we need to show the upgrades section in WP Rocket settings page based on the data passed from that issue #7176 

**Describe the solution you'd like**
Here we need to show the sections as it's now but depending on the data passed from #7176 with this new multi stacked items (inside select dropdown).

As initial state of this dropdown select box, we will show the first item details (name, price, and upgrade link on the CTA) and once we change the selected item, we will update (name, price, and upgrade link on the CTA) to reflect the selected item.

We will try to use the current UI, just change the source of data and add this select dropdown which will require some JS code changes.

**Additional context**
No

**Comment by Khadreal** [comment]
### Scope a solution ✅
In this file [upgrade-popin](https://github.com/wp-media/wp-rocket/blob/dd33f7bebe6db79b5c4cff9609a2e9a1480173dc/inc/Engine/License/views/upgrade-popin.php#L1) we would need to refactor a bit of it, since the data from [this](https://github.com/wp-media/wp-rocket/blob/dd33f7bebe6db79b5c4cff9609a2e9a1480173dc/inc/Engine/License/Upgrade.php#L326) is changing based on this task [here](https://github.com/wp-media/wp-rocket/issues/7176)
We would adding a new view(upgrade-item.php) to handle the license type and not hardcoding anything.
Based on the proposed data structure, we would refactored this section in [upgrade-popin.php](https://github.com/wp-media/wp-rocket/blob/dd33f7bebe6db79b5c4cff9609a2e9a1480173dc/inc/Engine/License/views/upgrade-popin.php#L30-L61)

```
<div class="wpr-Popin-flex">
   <?php foreach( $data['upgrades'] as $type => $rocket_upgrade ) : ?>
     <div class="wpr-Upgrade-<?php echo esc_attr( $type ); ?>">
          <?php echo $this->generate( 'upgrade-item', [
					'type' => $type,
					'item' => $rocket_upgrade,
					'is_promo_active' => $data['is_promo_active']
				] ); ?>
     </div>
    <?php endforeach; ?>			
</div>
```
In the new view (upgrade-item.php)
```
<?php
/**
 * Upgrade item template.
 *
 */

defined( 'ABSPATH' ) || exit;

$initial_item = $data['type'] === 'stacked' ? reset($data['item']) : $data['item'];
?>

<h3 class="wpr-upgrade-title"><?php echo esc_html( $initial_item['name'] ); ?></h3>

<div class="wpr-upgrade-prices"><span class="wpr-upgrade-price-symbol">$</span> <?php echo esc_html( $initial_item['price'] ); ?>
	<?php if ( true === $data['is_promo_active'] ) : ?>
		<del class="wpr-upgrade-price-regular">$ <?php echo esc_html( $initial_item['regular_price'] ); ?></del>
	<?php endif; ?>
</div>

<?php if( $data['type'] === 'stacked' ) : ?>
	<select id="multi-upgrade-plan">
		<?php foreach ( $data['item'] as $id => $stacked ) : ?>
			<option data-price="<?php echo esc_html( $stacked['price'] )?>" value="<?php echo esc_html( $id )?>"><?php echo esc_html( $stacked['websites'] ); ?></option>
		<?php endforeach; ?>
	</select>
<?php else : ?>
	<div class="wpr-upgrade-websites">
		<?php
		// translators: %s = number of websites.
		printf( esc_html__( '%s websites', 'rocket' ),  esc_html( $initial_item['websites'] ) );
		?>
	</div>
<?php endif; ?>
<a href="#" class="wpr-upgrade-link" target="_blank" rel="noopener noreferrer">
	<?php
	// translators: %s = license name.
	printf( esc_html__( 'Upgrade to %s', 'rocket' ), esc_html( $initial_item['name'] ) );
	?>
</a>
```

We would need to improve the UI(not sure if there's a design available for this and in the js file, we would have an event that would change the price and upgrade url on change of the multi plan

Something like this would do for the js 
```
document.addEventListener("DOMContentLoaded", function() {
            const multiSelects = document.querySelectorAll(".js-multi-upgrade-plan");

            multiSelects.forEach(function(select) {
                select.addEventListener("change", function() {
                    const priceDisplay = this.closest('.wpr-Popin-flex').querySelector('.js-multi-price');
                    priceDisplay.textContent = this.value;
                });
            });
        });
``` 

### Estimate the effort ✅
S-M

**Comment by wordpressfan** [comment]
I have a few quick comments here:
1. We have HTML duplication here, I was thinking of moving the upgrade item into another view file and load it here using the generate (but I'm not sure if this will work to call generate method inside the view that is called using also the same generate method), can u plz try this? or even call this generate method inside the Upgrade class then pass the html back to the main generate, this will make the code more maintainable without any duplication.
2. We don't need to hardcode any license type like `Multi` so as I mentioned before we can use the first element details (price and name) inside stacked array, this will be the initial value for the first selected item from the select options.
3. We don't have a specific UI so we won't play with this, just small CSS to make sure that the select is showing properly (or maybe we have a CSS class to be added to the select)

What do u think @Khadreal ?

**Comment by wordpressfan** [comment]
Awesome @Khadreal

**Comment by Khadreal** [comment]
Can we go ahead with this while waiting for #7176 or it should be pick up after ?
We can mock the data though

**Comment by wordpressfan** [comment]
Yes I was thinking of mocking the data, I know that u r busy what u r doing so I'll pick this one and may ask ur help when u finish what u do, @Khadreal

**Comment by wordpressfan** [comment]
@marija-nikolic attaching here how it looks like, please note that I mocked the prices and just added a few license types just for testing, so here we need a feedback on just the UI plz.

Without active promo campaign:
https://github.com/user-attachments/assets/11624c6f-75c6-4fcc-84aa-b4ddfd528d06

With active promo campaign:
https://github.com/user-attachments/assets/3396f180-2c67-4f2e-8df9-8ad260f33a51

Let me know if u see any UI issue that needs to be fixed.
Thanks.
