### ISSUE TITLE
3.18 - Exclusions part enhancement

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#7189]
User Story
As a user, I’d like to be able to exclude CSS file with the fonts from the feature by typing its argument into the filter

**Acceptance Criteria**
Having following input:
```
`<link rel='stylesheet' id='astra-google-fonts-css' href='https://fonts.googleapis.com/css?family=Noto+Sans%3A400%2C700%7CMontserrat%3A700&#038;display=fallback&#038;ver=4.7.0' media='all' />`
```
- The following filter entries would exclude the CSS file from the GF Combination and from rewriting the paths: `astra-google-` `astra-google-(.*)-css` `astra-google-fonts-css`
- We could apply it only to `id` or `class` attributes, but if it makes things easier, it can be applied to all
- Fonts which are inside the excluded file will not be rewritten

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
`In WP_Rocket\Engine\Media\Fonts\Frontend\Controller::rewrite_fonts`
- Add a new name to the capturing group for `id` & `class` [here](https://github.com/wp-media/wp-rocket/blob/fd63357830d168b51d7248efe8c8071feca5ec7e/inc/Engine/Media/Fonts/Frontend/Controller.php#L86-L87)
- Parse the font array instead [here](https://github.com/wp-media/wp-rocket/blob/fd63357830d168b51d7248efe8c8071feca5ec7e/inc/Engine/Media/Fonts/Frontend/Controller.php#L102) & [here](https://github.com/wp-media/wp-rocket/blob/fd63357830d168b51d7248efe8c8071feca5ec7e/inc/Engine/Media/Fonts/Frontend/Controller.php#L109)

`In WP_Rocket\Engine\Media\Fonts\FontsTrait::is_excluded`
- Update the method to match with id.

Update tests.

### Estimate the effort ✅
[XS]

**Comment by Khadreal** [comment]
LGTM

**Comment by remyperona** [comment]
Wouldn't it be simpler to match against the whole HTML tag instead of creating new capture groups?

**Comment by piotrbak** [comment]
@remyperona Fine from my side. I remember there wwere some concerns about the dots in the URL and the regex though.

**Comment by jeawhanlee** [comment]
> We could apply it only to id or class attributes, but if it makes things easier, it can be applied to all

@remyperona We could do that as well, going by the AC it looked like it needed to be matched against id or classes if it could be done. 
in my view whichever is easier to implement and test without a regression to what we already have.

**Comment by piotrbak** [comment]
`in my view whichever is easier to implement and test without a regression to what we already have.`
Exactly
