### ISSUE TITLE
<style amp-boilerplate> cannot be found when Critical Path CSS is set

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#738]
AMP HTML documents must contain the following boilerplate in their `head` tag. When Critical Path CSS is set but our _Optimize CSS Delivery_ feature, the snippet cannot be fetch anymore to validate the AMP document. 

Ref: https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

**Comment by Tabrisrp** [comment]
I can't replicate the issue on a test site with WP Rocket and AMP from Auttomatic.

The `style amp-boilerplate` tag is correctly present in the document.

**Comment by WordPresseur** [comment]
Also tested with AMP from Automattic : [https://wordpress.org/plugins/amp/](https://wordpress.org/plugins/amp/)

The  `style amp-boilerplate` is present but cannot be fetched by Google when testing the page with https://search.google.com/test/amp

![capture d ecran 2018-01-31 a 08 54 30](https://user-images.githubusercontent.com/11939512/35611410-295b0904-0665-11e8-8b06-ecc89123a4e7.png)

This issue disappear when Optimize CSS Delivery option is off.

**Comment by Tabrisrp** [comment]
Ok tested and confirmed, happens only with combine CSS active. Will be fixed in next minor version.

**Comment by beeriz** [comment]
I just created a support thread for this issue, before stumbling on this. 
Critical Path CSS should be disabled on AMP.
