### ISSUE TITLE
Compatibility with non latin alphabets URLs

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#740]
As characters from non latin alphabets are allowed in URLs, we need to do testing to ensure everything is working correctly with them, notably:
- cache creation
- cache deletion
- exclusion (from cache and minification)

**Comment by GeekPress** [comment]
I'm going to close this one as we don't seem to have tickets about this potential problem. We could re-open it if we notice an issue from a customer.
