### ISSUE TITLE
htaccess

### ISSUE THREAD

**Issue by m0sagal** [wp-media/wp-rocket#743]
After updating to the latest version, the htaccess file doesn't have any wp rocket rules, so gtmetrix result is dropped, the htaccess permission is 644

**Comment by Keomoniroath** [comment]
Have the same issue, the htaccess file have the rules of the old version and not the latest one

**Comment by m0sagal** [comment]
i don't have even the rules of old version :(

**Comment by Tabrisrp** [comment]
It's better to open a support ticket for this kind of cases, you can do this from the plugin or from our website.
