### ISSUE TITLE
Notice: Undefined index: web_server in /www/wp-content/plugins/wp-rocket/inc/functions/admin.php on line 446

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#744]
Add a generic else to this: 

```
	if ( $is_nginx ) {
		$data['web_server'] = 'NGINX';
	} elseif ( $is_apache ) {
		$data['web_server'] = 'Apache';
	} elseif ( $is_iis7 ) {
		$data['web_server'] = 'IIS 7';
	} elseif ( $is_IIS ) {
		$data['web_server'] = 'IIS';
	}
```
Ticket: https://secure.helpscout.net/conversation/518333800/59457?folderId=273761

**Comment by Tabrisrp** [comment]
@arunbasillal you want to do the fix for it? We could send a value `unknown` in the case of the detection failing

**Comment by arunbasillal** [comment]
@Tabrisrp I was just doing it. Added `unknown`. Will send the PR shortly.
