### ISSUE TITLE
Critical CSS broken for WP Touch Three

### ISSUE THREAD

**Issue by foliovision** [wp-media/wp-rocket#748]
WP Rocket 2.11 automated Critical CSS works, but it doesn't consider a separate mobile template, such as WPTouch or others. Until recently we were able to put in our custom critical CSS for the mobile theme like this:

```
<?php

add_filter( 'pre_get_rocket_option_critical_css', 'fv_touch_three_critical_css' );

function fv_touch_three_critical_css( $value ) {
global $wptouch_pro;
if( isset($wptouch_pro) && isset($wptouch_pro->is_mobile_device) && $wptouch_pro->is_mobile_device ) {
$value = <<<CSS
...
...
CSS;
}
return $value;
}


```

Could you please add a filter which we created in #747 so that we can put in our critical CSS that way? We are using this code currently which changes the CSS content to "fallback" which makes it load from the same option as before.

```
<?php
add_filter( 'wp_rocket_critical_css_content', 'fv_rocket_critical_css_force_fallback');

function fv_rocket_critical_css_force_fallback( $force_css ) {
if( isset($wptouch_pro) && isset($wptouch_pro->is_mobile_device) && $wptouch_pro->is_mobile_device ) {
return 'fallback';
}
return false;
}
```

Thanks,
Martin

**Comment by foliovision** [comment]
Hello,

could you please have a look and let us know if you can accept our changed?

Thanks,
Martin

**Comment by arunbasillal** [comment]
@foliovision CPCSS for mobile was added in WP Rocket 3.6 #2378
I hope that solved the issue for you. We are working on something better, so things will look even better soon.
