### ISSUE TITLE
Mobile Cache Not Enabled Automatically When Mobile Plugins Are Active

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#751]
When WPtouch is enabled Mobile cache is enabled by default or so it seems. 

If mobile cache was unchecked before enabling WPtouch, LazyLoad does not work on the WPtouch mobile theme for some reason. 

The way to fix this now is to disable WPtouch, go to WP Rocket > Basic tab and make sure "Enable caching for mobile devices" and "Separate cache files for mobile devices" are enabled. Then enable WPtouch.

Something to look into if we decide to enable LazyLoad with WPtouch in the WP Rocket core. 

---[ Update on 23.Februrary.2018 ]---

Turns out, its not just related to WP touch, but in all cases where the Mobile cache option in Basic settings tab is enabled automatically by `rocket_is_mobile_plugin_active()` function, even if the setting says its active, cache isn't generated or served on mobile devices. 

Of course, if mobile cache is enabled before activating any of these plugins, then mobile cache works as expected. 

The setting is saved to database in the sanitizing function `rocket_settings_callback()` the next time any of the settings page is saved and then mobile cache is truly enabled. But when the mobile plugin is disabled, the setting stays in the database and mobile cache isn't disabled. 

Plugins that we consider: 
```
'wptouch/wptouch.php',
'wiziapp-create-your-own-native-iphone-app/wiziapp.php',
'wordpress-mobile-pack/wordpress-mobile-pack.php',
'wp-mobilizer/wp-mobilizer.php',
'wp-mobile-edition/wp-mobile-edition.php',
'device-theme-switcher/dts_controller.php',
'wp-mobile-detect/wp-mobile-detect.php',
'easy-social-share-buttons3/easy-social-share-buttons3.php'
```

Notes to self: 
* .htaccess is not regenerated when mobile caching is enabled so rewrite rules do not change. When settings are saved after enabling one of these plugins, then .htaccess is regenerated of course. 
* Possible solution is to add `cache_mobile` and `do_caching_mobile_files` settings to database when any of the above plugins are activated. i.e. if these settings aren't enabled already. 
* Also regenerate the .htaccess file if needed. 
* Deactivation is a bit of a pickle because we do not know the original state (unless we save it separately). But this isn't handled right now anyways. One settings are saved, the sanitizing function writes these to the database and forgets the original state anyways. 
* Should any of the other files be regenerated? 
* Best place to add the activation and deactivation functions: Maybe they can be added as compatibility file in the `3rd-party/plugins/mobile/` folder? If so, a common file for all of them (`common.php` in mobile folder)? Or separate files?

**Comment by webtrainingwheels** [comment]
related / duplicate: https://github.com/wp-media/wp-rocket/issues/730
