### ISSUE TITLE
Test compatibility with AMP for WP plugin

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#753]
So far we tested compatibility with the official AMP plugin: But another plugin, AMP for WP has gained popularity:
https://wordpress.org/plugins/accelerated-mobile-pages/

Since we've been receiving tickets about it, it could be useful to work on compatibility also with this plugin.

**Comment by arunbasillal** [comment]
Related ticket: https://secure.helpscout.net/conversation/519056014/59539/?folderId=1724284

Helper plugin: https://www.dropbox.com/s/d5t1muxcy1t6zsy/wp-rocket-helper-compat-amp-for-wp.zip?dl=0

**Comment by ernee** [comment]
per this convo, our compatibility for official AMP plugin may work for this plugin already: https://wp-media.slack.com/archives/C08N8J6VC/p1527679059000057

**Comment by alfonso100** [comment]
A customer asked about this compatibility again. it looks like everything is working fine  using **AMP for WP**  and **WP Rocket 3.3.3** 
this is the website: https://naijacenter.com/

Slack combo: https://wp-media.slack.com/archives/C08N8J6VC/p1558023393140000

This is the HS ticket, https://secure.helpscout.net/conversation/852919423/107903?folderId=2683093

**Comment by GeekPress** [comment]
Closing this as we have a new issue with more details opened recently about this compatibility https://github.com/wp-media/wp-rocket/issues/2498
