### ISSUE TITLE
Minification & Concatenation doesn't work anymore on relative URLs

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#755]
If a website contains relative URLs for CSS & JS files, minification & concatenation doesn't work anymore since 2.11.

Here an example:
http://www.lakeshoreent.com/

**Comment by cedrox** [comment]
Hello, 
Any update on this ?

**Comment by arunbasillal** [comment]
Possibly related to issues #757

**Comment by Keomoniroath** [comment]
I took a look at the issue #757, but in our case we don't have any minification and concatenation

**Comment by cedrox** [comment]
We are currently premium and seriously considering other solutions. Too much trouble on docker on azure / ubuntu / apache...

**Comment by cedrox** [comment]
Here the docker image https://hub.docker.com/r/cedrox/apps/

**Comment by Tabrisrp** [comment]
@arunbasillal If you're able to test minification/concatenation with relative URLs, to confirm whetever it works correctly or not

**Comment by cedrox** [comment]
Ticket open just now on premium support.
Thanks

**Comment by Tabrisrp** [comment]
Confirmed, issue is that the function `rocket_url_to_path()` expect the URL passed to be an absolute one, which is not the case.

To fix it, we need to add the scheme and host to the relative path before doing the url to path replacement.

**Comment by arunbasillal** [comment]
Related tickets: 
- https://secure.helpscout.net/conversation/577996919/67723/

**Comment by GeekPress** [comment]
back since 3.1.4 on JS/CSS files + Remove Query String options
