### ISSUE TITLE
Relative URLs without leading slash (folder relative instead of root relative) replaced incorrectly during minification

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#757]
Relative references like this: `background: url(images/break-f.png) right repeat-y;`

Instead of `background: url(/images/break-f.png) right repeat-y;` <-- root-relative with leading `/`

Minification turns it into `/xxxxx/wp-content/themes/DynamiX/images/break-f.png`
Folder named `xxxxx` is the folder in the server where the WordPress is installed. 

Related tickets: 
- https://secure.helpscout.net/conversation/488092939/55631/
- https://secure.helpscout.net/conversation/596683842/70638/?folderId=273766
- https://secure.helpscout.net/conversation/619863450/73838/?folderId=273764

**Comment by webtrainingwheels** [comment]
Related ticket: https://secure.helpscout.net/conversation/520710142/59769?folderId=377611
In this case,references in the original code are like this: 
`url(../images/box_shadow_button.png)`

**Comment by webtrainingwheels** [comment]
Also affects Remove Query Strings. 
Related ticket: https://secure.helpscout.net/conversation/538361125/62074?folderId=273761

Font is included like this: `url('../fonts/fontawesome-webfont.woff2?v=4.7.0')`
When Remove Query Strings is active, it ends up as: 
`url('/www/wp-content/themes/suisen/fonts/fontawesome-webfont.woff2?v=4.7.0')`
/www/ shouldn't be there

**Comment by arunbasillal** [comment]
#NoteToSelf 

I was trying to see if I could figure it out, no dough so far. 
Was able to recreate this on my local install. Need to sit on it another time. 

Not 100% sure, but it doesn't look like the path converter here: https://github.com/matthiasmullie/path-converter/blob/master/src/Converter.php has a case where this is considered.

**Comment by arunbasillal** [comment]
Possibly related: https://secure.helpscout.net/conversation/667561962/80577?folderId=1724284

**Comment by Tabrisrp** [comment]
I believe it's caused when `DOCUMENT_ROOT` mismatch with the actual path of the origin CSS file. This can happen with virtual hosts and VirtualDocumentRoot configurations.

The ideal solution would be to get rid of the MinifyCSS_Rewriter class, and use the PathConverter class instead.

It will require a bit of work to make it work, but it's better as PathConverter uses a source and target paths to perform the conversion, so we will be relying on fixed values instead of server configurations.

**Comment by webtrainingwheels** [comment]
https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/250924/conversations/19731797575
