### ISSUE TITLE
 LazyLoad Iframe/Video Breaks Responsiveness of Videos

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#76]
Definitely when using Avada's video shortcode, but maybe elsewhere as well, when Iframe LazyLoad is active, it seems to hardcode video player dimensions, therefore breaking the responsiveness.
Without LazyLoad: https://www.evernote.com/l/ACIh1E0G8oJKzbk-Om1g9wnNg7TcpPfZee0
With LazyLoad: https://www.evernote.com/l/ACJyymw0iilJxaOo9smN3zmivSHcKQtB4bk width and height of iframe are now present in the HTML

Happens in other themes when using Oembed: 
https://secure.helpscout.net/conversation/269740985/25353/?folderId=377611

**Comment by sadjad1** [comment]
Is there any temporary cheat-fix for this? It seems that this problem occurs when you have Avada and combine YouTube Shortcodes with other shortcodes. Becuase the YouTube player only breaks on this page for me(http://dev.shapebysharam.se/products/markers/) but not on other pages like(http://dev.shapebysharam.se/).

**Comment by sadjad1** [comment]
One way to approach this is to set fixed height and width in pixels instead of relaying on the "responsiveness" of the player.

But this doesn't work for the vimeo player :(
