### ISSUE TITLE
File combination not working with WPML's directory per language option

### ISSUE THREAD

**Issue by ictbeheer** [wp-media/wp-rocket#760]
Problem
----
When using WPML with the option _Different languages in directories_ combining files by WP Rocket fails. 

Cause
---
I think this is caused by the following line in the function `rocket_realpath`  in `\inc\functions\formatting.php`:
`$file      = str_replace( $site_url, $home_path, rocket_set_internal_url_scheme( $file ) );`

The str_repace will fail because `$site_url` will contain the language directory (e.g. _www.example.com/nl_) whereas `$file` will not (e.g. _http://www.example.com/wp-content/themes/twentysixteen/js/functions.js_)

**Comment by Tabrisrp** [comment]
Thank you for opening the issue.

I written more details in #788 and fixed in PR #789.
