### ISSUE TITLE
Resolve Conflict Between LazyLoad Script And RequireJS Loader

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#763]
Related ticket: https://secure.helpscout.net/conversation/517301302/59303?folderId=1724284

Issue seems to be: http://requirejs.org/docs/errors.html#mismatch

Showed up since 2.11 and is okay in 2.10.12

**Comment by ernee** [comment]
another related ticket: https://secure.helpscout.net/conversation/528844586/60847?folderId=1391600

**Comment by GeekPress** [comment]
I have checked both websites which are using 3.4.4 and 3.7.5 . Both websites have LazyLoad working properly.

I'm closing this issue as it seems to be fixed and nobody reported a bug for a while.
