### ISSUE TITLE
Prefetch DNS requests - dont work (dont add rel="dns-prefetch" to links)

### ISSUE THREAD

**Issue by ambrosso** [wp-media/wp-rocket#764]
Feature Prefetch DNS requests dont work.
Dont add rel="dns-prefetch" to links,
even if I add for example //fonts.googleapis.com in settings manually.

**Comment by Tabrisrp** [comment]
This should go to our [support](https://wp-rocket.me/support/?utm_source=github&utm_medium=wp_rocket_profile) system, we don't handle support request on github.
