### ISSUE TITLE
Minify HTML - dont minify inline JS

### ISSUE THREAD

**Issue by ambrosso** [wp-media/wp-rocket#766]
Option Minify HTML files minifies HTML on page, but dont minify inline JavaScript in HTML.

**Comment by Tabrisrp** [comment]
This is a choice we made. You can activate inline JS minification using the `rocket_minify_html_options` filter like this: https://gist.github.com/Tabrisrp/b5ef03e8d4bcfcd11adc32b8907ef66d

**Comment by ambrosso** [comment]
I have error in this code snippet:
syntax error, unexpected '=>' (T_DOUBLE_ARROW) at line 4

**Comment by Tabrisrp** [comment]
I updated the snippet to fix the issue.
