### ISSUE TITLE
External monitoring systems may not detect site down if WP Rocket is installed

### ISSUE THREAD

**Issue by stevenmunro** [wp-media/wp-rocket#769]
WP Rocket version 2.11.3
WordPress version 4.9.4
Webserver NGINX 1.13.6

I decided to purposely put some garble into my theme functions.php to test the status code output. As everyone should know, status codes are important for monitoring systems to pick up downed sites and send out alerts.

With the WP Rocket plugin DISABLED, I forced the site to be down by inserting some rubbish into functions.php. In the browser, the site returned error 500. https://httpstatus.io/ also returned error 500. This works as expected.

I then removed the rubbish and returned the site to normal.

Now I ACTIVATE the WP Rocket Plugin. I browse to the front page to ensure the cache is generated.

I then reinsert the rubbish into functions.php, and the site immediately goes offline showing error 500 in the browser. However the result from https://httpstatus.io/ still shows 200. This response would incorrectly throw off the monitoring systems.

After manually removing index-https.html and the corresponding gzip file from the cache directory, the status returned from https://httpstatus.io/ is now 500.

I understand that we must provide the cached files as soon as possible to really speed things up, but perhaps there needs to be a check to instantly invalidate these if there is an error somewhere. In any case one would expect the cached files to still display the front page regardless even if there was a backend problem, so I believe there is an issue with the ordering of things here.

**Comment by Tabrisrp** [comment]
If the cache file exists, it will be served even though the website isn't working correctly. It's probably better to check the status of the website on a page you know will never be cached, for example `wp-admin/` or `wp-login.php`
