### ISSUE TITLE
 Feature proposal: Detect potentially problematic left-over files of other caching plugins and warn user

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#77]
Detect whether SuperCache or W3TC are installed—active, or not.
If one of them is active, ask user for permission to automatically deactivate them and clean up the file system. Fallback: Stop WP Rocket from being activated, so user can clean up manually first. In this case: provide detailed info from our docs.
If neither of those other plugins is active, but one or more is installed, ask user for permission to automatically clean up the file system. Fallback: see above.
General fallback: Prompt admin to open a support ticket, so WP Rocket support agents can do it for them.
This will potentially prevent a huge support case where sites crash, because other plugins have not cleaned up after themselves when they were deactivated.

**Comment by GeekPress** [comment]
With the ton of caching plugins available, it's going to be hard to maintain this. Also, is it our job to clean what other plugin missed to do after their deactivation?

We already display a notice when another plugin is detected to ask the user to deactivate the conflicted plugin. In most of cases, it's enough.

Closing it.
