### ISSUE TITLE
File Autoload.php not found

### ISSUE THREAD

**Issue by Keomoniroath** [wp-media/wp-rocket#774]
When installing WP Rocket version 2.11.6, I have these errors in my php-error.log : 

- PHP Warning:  require(/home/site/wwwroot/wp-content/plugins/wp-rocket/vendor/autoload.php): failed to open stream: No such file or directory in /home/site/wwwroot/wp-content/plugins/wp-rocket/wp-rocket.php on line 177
- PHP Fatal error:  require(): Failed opening required '/home/site/wwwroot/wp-content/plugins/wp-rocket/vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/site/wwwroot/wp-content/plugins/wp-rocket/wp-rocket.php on line 177

**Comment by arunbasillal** [comment]
@Keomoniroath Did you install WP Rocket you downloaded from GitHub or your account - https://wp-rocket.me/account/ ?

**Comment by Keomoniroath** [comment]
I downloaded it from GitHub

**Comment by arunbasillal** [comment]
@Keomoniroath While we use GitHub as a public repo to share our code with anyone who is interested, WP Rocket being a premium plugin we have to be fair to our paying customers. For this reason, some non-critical files are excluded. 

You are welcome to adapt from our code, but if you want to use WP Rocket on your website, please purchase a license from http://wp-rocket.me/

Also kindly note that product support is limited to customers with an active license. Thank you!

**Comment by Keomoniroath** [comment]
I downloaded WP Rocket from our premium account and it work fine. Thank you !

**Comment by arunbasillal** [comment]
Glad to hear that @Keomoniroath 

If you ever have a question, do not hesitate to write to us via the Support tab of WP Rocket or at `support@wp-rocket.me`
