### ISSUE TITLE
Enhance rocket_clean_user() to use current user id if no $user_id is passed

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#782]
If no user ID is passed, use `wp_get_current_user()` to get the current user. 

Makes the function more useful and leads to cleaner code in some [cases like this](https://secure.helpscout.net/conversation/526948531/60579/?folderId=1724284). 

A better more intuitive way would be to write a wrapper for `rocket_clean_user()` named `rocket_clean_current_user()`. Something to think about.

**Comment by Tabrisrp** [comment]
The first thing to check in this case is the clear cache lifespan value. Since they use nonce on the front, the value should be equal or inferior to 10 hours.

The new function would not be used anywhere in the current core codebase too, which is not good.

**Comment by arunbasillal** [comment]
Closing this, thanks for your feedback @Tabrisrp :+1:
