### ISSUE TITLE
Handling edge cases where DONOTCACHEPAGE is set to (string)FALSE instead of (bool)FALSE

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#786]
On a user website, cache files were not being generated. I debugged in `process.php` and it finally came down to this line (L249) 

https://github.com/wp-media/wp-rocket/blob/master/inc/front/process.php#L249

`&& ( ! defined( 'DONOTCACHEPAGE' ) || ! DONOTCACHEPAGE || $rocket_override_donotcachepage ) // Don't cache template that use this constant.`

Debug helper gave me this:
```#################################################### 
## WP ROCKET DEBUG ##
Note: Minify HTML is dynamically disabled, so this debug notice can be displayed.

## Constants

- constant WP_CACHE is: TRUE
- constant DONOTCACHEPAGE is: FALSE
- constant DONOTMINIFY is: not defined
- constant DONOTMINIFYCSS is: not defined
- constant DONOTMINIFYJS is: not defined

## Filters
Note: Filter `rocket_override_donotcachepage` gets set by WP Rocket core in certain environments.

- filter do_rocket_generate_caching_files is: not set
- filter rocket_override_donotcachepage is: default ('rocket_override_donotcachepage_on_thrive_leads')


####################################################
```

The reason I found is that `DONOTCACHEPAGE` evaluates to true. Maybe it is set as a string `"FALSE"`?
`var_dump((bool) "false");` is `bool(true)` apparently.

The solution I think is to check for the value explicitly as in:
`&& ( ! defined( 'DONOTCACHEPAGE' ) || ! ( DONOTCACHEPAGE === true ) || $rocket_override_donotcachepage ) // Don't cache template that use this constant.`

I have [contacted Cloudways](https://secure.helpscout.net/conversation/532151206/61243/?folderId=1724284) to see if we could have a look at their code. It seems to be coming from the server as DONOTCACHEPAGE is not set in PHP 5.6

Related ticket: https://secure.helpscout.net/conversation/529951330/60967?folderId=1724284

**Comment by GeekPress** [comment]
@wp-media/plugins If you can have a look to this and share your thoughts :)

**Comment by GeekPress** [comment]
It seems to be a very rare edge case. as we didn't have any report in 3 years, I'm closing it.
