### ISSUE TITLE
Multisite - Update notification not received unless plugin active on main site

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#79]
When WP Rocket is only active in a sub-site of a network, not on the main site, then the update notification is never shown.

**Comment by WordPresseur** [comment]
A case here: https://secure.helpscout.net/conversation/1175973379/168093?folderId=1213662

**Comment by camilamadronero** [comment]
New case: https://onecomhelp.zendesk.com/agent/tickets/17487781

**Comment by Adrianadla** [comment]
New case https://onecomhelp.zendesk.com/agent/tickets/18601059
