### ISSUE TITLE
Compatibility with Facebook Instant Articles

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#792]
When a site uses **Facebook Instant Articles**

* **LazyLoad** is enabled, Facebook validation fails and the post can't be published.
The developers of Facebook Instant Articles are aware of the incompatibility, somebody already opened a GitHub issue on their side: [here](https://github.com/Automattic/facebook-instant-articles-wp/issues/877
)
One of our customers proposes the following fix, adding the following code to line 139 in _wp-rocket/inc/front/lazyload.php_ :

`|| isset( $_GET[ 'ia_markup' ] )
`
so the line becomes

`if ( ! get_rocket_option( 'lazyload' ) || ! apply_filters( 'do_rocket_lazyload', true ) || is_feed() || is_preview() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) || ( defined( 'DONOTROCKETOPTIMIZE' ) && DONOTROCKETOPTIMIZE ) || empty( $html ) || ( defined( 'DONOTLAZYLOAD' ) && DONOTLAZYLOAD ) || wp_script_is( 'twentytwenty-twentytwenty', 'enqueued' ) || isset( $_GET[ 'ia_markup' ] ) ) {
return $html;
}`

Ref. [HS ticket](https://secure.helpscout.net/conversation/535917797/61757?folderId=628132
)

**Comment by piotrbak** [comment]
Closing it as it's fixed already:
https://github.com/Automattic/fb-instant-articles/pull/905/files
