### ISSUE TITLE
Partial LazyLoad Reference Causes 404 error in Google Search Console 

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#795]
Google search console for some reason picks up the partial file reference from our LazyLoad JS and throws a 404 error saying the following file is missing:

`http://example.com/wp-content/plugins/wp-rocket/inc/front/js/lazyload-`

This is a false positive and can be ignored. But we get tickets regarding this and it bothers some of our users. 

Possible solution - Include a dummy file with the file name. Worked for a user. 

Related tickets: 

- https://secure.helpscout.net/conversation/518136970/59429?folderId=1724284
- https://secure.helpscout.net/conversation/576537433/67559?folderId=273761

**Comment by arunbasillal** [comment]
Explore how this can be resolved using `robots_txt` filter instead of a dummy file - https://developer.wordpress.org/reference/hooks/robots_txt/

**Comment by glueckpress** [comment]
Blocking the broken URL via robots.txt doesn’t seem to be reliable. One customer [reported](https://secure.helpscout.net/conversation/566766577/66116/#thread-1564279422) the URL got “indexed though blocked by robots.txt”.

**Comment by Tabrisrp** [comment]
I like this better yes
