### ISSUE TITLE
Exclude Avada IE styles from CPCSS

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#798]
I believe we could incorporate Caspar's fix from over here - https://github.com/wp-media/criticalpath-css-generator/issues/72 - into the plugin. 

That is, excluding: /wp-content/themes/Avada/assets/css/ie.css 

I had another ticket where the customer says the fix worked:
https://secure.helpscout.net/conversation/536884534/61881?folderId=377611

**Comment by GeekPress** [comment]
It's fixed since the CPCSS tool is automatically excluded IE files:
https://github.com/wp-media/criticalpath-css-generator/issues/72
