### ISSUE TITLE
 Auto-Detect Themify Builder Plugin?

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#80]
The cache option within Themify's Builder plugin conflicts with WP Rocket, producing this issue: http://docs.wp-rocket.me/article/52-fix-for-weird-characters-displaying-on-your-web-page
Could we auto-detect it and display a warning to the user telling them to disable the Builder cache?

**Comment by arunbasillal** [comment]
I tested this with their plugin on the WordPress repo - https://wordpress.org/plugins/themify-builder/

Cache is disabled by default:
![image](https://user-images.githubusercontent.com/5751474/82031639-cc5c3d00-96b7-11ea-9ac7-dff361ec84ff.png)

And we do not have very many tickets about this - https://secure.helpscout.net/search/?query=tag%3Athemify%20builder%20cache

- Auto-compatibility is not required right now I think. 
- Most we could do is write to them to disable these things at their end when they detect WP Rocket. 
- For now we can just tell customer to disable the conflicting option.

@GeekPress Please note.

**Comment by GeekPress** [comment]
@arunbasillal It could be good to contact their team and ask them to make an auto-compatibility with caching plugins.

@webtrainingwheels Can you take the lead to contact them?

**Comment by webtrainingwheels** [comment]
@kierantaylorio has contacted them here: https://secure.helpscout.net/conversation/1178151436/168605/

**Comment by kierantaylorio** [comment]
@arunbasillal Themify have responded and are happy to look into this with you: https://secure.helpscout.net/conversation/1178151436/168605

**Comment by piotrbak** [comment]
I can see that `Cache` option is not available there anymore and all performance settings (browser caching and gzip) are disabled by default. The plugin is just 10k installs and we have 4 tickets related to it during a couple of years. We can easily close the ticket.
