### ISSUE TITLE
Add HTTP Headers for cached pages with PHP

### ISSUE THREAD

**Issue by ambrosso** [wp-media/wp-rocket#801]
How to add custom HTTP Headers for cached pages with PHP hook?
When server is not Apache, and thereis no access to NGINX server configuration.

For not cached pages HTTP Headers can be added with PHP in Plugin/functions.php/MU Plugin, but not for cached pages.
For all site, including cached pages, they can be added in wp-config.php file.

Is it possible to add HTTP Headers with some function or hook to WP Rocket plugin?
And how to add custom HTML content only to cached pages?

**Comment by carstenwawer** [comment]
Hi @ambrosso ,

did you have success in adding custom http headers to the cache?

I would like to add specific Content Security Policys on specific pages and searching a way to do that.

Thank & Best Regards!
Carsten

**Comment by arunbasillal** [comment]
@GeekPress @Tabrisrp This seems very specific and wouldn't apply to the bulk of our customers. Shall we close this?

If someone wants to do this: 
- Remove rewrite rules from .htaccess / Nginx config
- Add the headers to `wp-config.php` (since this is executed before loading `advanced-cache.php`)

**Comment by GeekPress** [comment]
@arunbasillal You're right, let's closing this issue.

**Comment by BradFD** [comment]
Maybe this should be revisited in some form. Custom headers are needed to integrate with Cloudflare APO and likely similar offerings from other services in the future.  #3180 

Would also be nice to be able to add push headers for example for a logo to improve FCP.   WP Rocket should also have the option to send a push header for its own concatenated/minified CSS and JS.

**Comment by TokyoJump** [comment]
WP Rocket user can not use 103 early hints in Cloud Flare.
We can not add custom link header.
This is issue, bug i guess.

It is not so cool.
