### ISSUE TITLE
DNS-Prefetch dont work if 'wp_resource_hints' was disabled with hook in WP 4.7+

### ISSUE THREAD

**Issue by ambrosso** [wp-media/wp-rocket#805]
DNS-Prefetch dont work if 'wp_resource_hints' was disabled with hook in new WP 4.7+ (where this function exists by default).

WP-Rocket dont add its own function to replace default WP 'wp_resource_hints' in this case.

**Comment by Tabrisrp** [comment]
which hook can be used to disable the function?

**Comment by ambrosso** [comment]
`remove_action( 'wp_head', 'wp_resource_hints', 2 );`
