### ISSUE TITLE
3.0 Alpha - File optimization - Excluded CSS Files option is missing

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#806]
When Minify CSS Files is enable, Excluded CSS Files option field should appear.

**Comment by GeekPress** [comment]
It's the same for JS option.

**Comment by GeekPress** [comment]
3.0 Alpha5

When options are already checked, the excluded CSS files is still doesn't displayed => https://cl.ly/0Z0X1M1F1P12
