### ISSUE TITLE
3.0 Alpha - Dashboard - Improvements on "My Status" section

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#808]
- Add an uppercase on first letter of the License
- Reduce spaces between the label and value to be like the mockup => https://cl.ly/082C3p1A2D0D

**Comment by Tabrisrp** [comment]
Capitalized the licenses name

**Comment by Thomasgeisen** [comment]
fixed with commit 1ddc110

**Comment by GeekPress** [comment]
This commit doesn't seem to be present in alpha3. I don't get the update.

**Comment by Tabrisrp** [comment]
I do have the changes on my install, is it only for the spacing issue or also the capitalize?

**Comment by GeekPress** [comment]
Both
