### ISSUE TITLE
3.0 Alpha - Dashboard - Don't display the "Save changes" button

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#810]

**Comment by Tabrisrp** [comment]
How does a user save the rocket tester/rocket sharer options without the save changes button?

**Comment by GeekPress** [comment]
In AJAX like on the Add-on tab where we shouldn't have the "Save Changes" button too.

**Comment by arunbasillal** [comment]
Thought it was a bug when tester / sharer options were not being saved (without hitting "Save Changes").
