### ISSUE TITLE
3.0 Alpha - Deactivation Intent - The pop-in is displayed even we click "Deactivate" from other plugins

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#818]
Our Deactivation Intent pop-in must be displayed only if we click on "Deactivate" from WP Rocket, not all.

**Comment by markonikolic985** [comment]
Short video to show how it looks like - https://www.screencast.com/t/yS28P6ub

I tried to deactivate WooCommerce, but can't do that as WP Rocket is getting deactivated instead.
