### ISSUE TITLE
3.0 Alpha - File Optimization - Improvements on "Fallback critical CSS" option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#819]
- "Provides a fallback if auto-generated critical path CSS is incomplete. More info" must be in gray and italic
- "More info" doesn't work
- The textarea with & height aren't good. It must like this => https://cl.ly/1S2B0j0A0s1D
- The space between the option label and the textarea is to high.
- All the section must be aligned to the parent option, like other sub-option.
- Remove ":" on "Fallback critical CSS:"

**Comment by GeekPress** [comment]
These things are still not updated:

- The textarea with & height aren't good. It must like this => https://cl.ly/1S2B0j0A0s1D
- Remove ":" on "Fallback critical CSS:"

**Comment by Thomasgeisen** [comment]
I already fixed textarea height to 100px, as requested by @edenpulse in Slack channel.
And for the width, who will have the last word ? Width 100% ou fixed value in pixel ?

**Comment by GeekPress** [comment]
It's more about the margin / padding than the width.
