### ISSUE TITLE
3.0 Alpha - Database - "Save Changes" must be renamed "Optimize"

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#820]

**Comment by Tabrisrp** [comment]
How does the user saves the change on this tab without the save changes button?

**Comment by markonikolic985** [comment]
We had Save and Optimize in previous version, could be the same?

**Comment by Tabrisrp** [comment]
@GeekPress What should we do about that?

Without the save changes button, the options won't be saved. Or are they supposed to be all saved using AJAX, and in that case they need to be changed to on/off switch?

**Comment by GeekPress** [comment]
We don't want to delete the button, just to rename it "Optimize" instead of "Save Changes".

When we click on "Optimize" it will save the options and optimize the database

**Comment by Tabrisrp** [comment]
ok! so @Thomasgeisen just renaming the button is enough
