### ISSUE TITLE
3.0 Alpha - Add-on - Logo are missing (Varnish / CloudFlare)

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#822]

**Comment by Tabrisrp** [comment]
Fixed by https://github.com/wp-media/wp-rocket/commit/7f6ce9f73f28c44361d6b122d59df487f3b10385

**Comment by markonikolic985** [comment]
This will be implemented after v3.0-alpha2, right? Since it still can be seen on this version.
