### ISSUE TITLE
3.0 Alpha - Beacon - The icon must also have the label "Need Help"

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#826]
The actual Beacon icon doesn't respect the mockup, it must be like that => https://cl.ly/0f410X3b3j0O

**Comment by Tabrisrp** [comment]
Beacon 1.0 API doesn't allow this currently. Beacon 2.0 does but it's still closed beta.

**Comment by GeekPress** [comment]
Ok, then we have to wait :(
