### ISSUE TITLE
3.0 Alpha - A couple of PHP notices

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#829]
PHP version used: 7.1.12

- PHP Notice:  Undefined index: enable_xml_sitemap in ../inc/3rd-party/plugins/seo/yoast-seo.php on line 9
- PHP Notice:  Object of class WP_Post could not be converted to int in ../inc/classes/class-rocket-background-database-optimization.php on line 77
- PHP Notice:  Undefined offset: 1 in ../inc/classes/admin/settings/class-settings.php on line 441
- PHP Notice:  Undefined index: wl_plugin_name in ../inc/admin/options.php on line 1103
- PHP Notice:  Undefined index: wl_plugin_name in ../inc/admin/options.php on line 1107

**Comment by arunbasillal** [comment]
PHP Version 7.04 on localhost fresh WordPress install.
WP Rocket 3.0 alpha 2

PHP Notice:  Undefined index: default in C:\xampp\htdocs\wpr3\wp-content\plugins\wp-rocket\inc\classes\admin\settings\class-settings.php on line 119

**Comment by GeekPress** [comment]
PHP Version 7.1.12
WP Rocket 3.0 alpha 3

- PHP Notice:  Undefined index: description in ../views/settings/page-sections/cloudflare.php on line 30
- PHP Notice:  Undefined index: file in ../inc/admin/admin.php on line 528
- PHP Notice:  Undefined index: file in ../inc/admin/admin.php on line 540
- PHP Notice:  Undefined index: file in ../inc/admin/admin.php on line 541

**Comment by webtrainingwheels** [comment]
WP Rocket 3.0 alpha 3
PHP 5.5
Notice: Undefined index: automatic_cleanup_frequency in /plugins/wp-rocket/inc/classes/admin/settings/class-settings.php on line 374

**Comment by GeekPress** [comment]
WP Rocket 3.0 Alpha4
PHP 7.1.12

PHP Notice:  Object of class WP_Post could not be converted to int in ../inc/classes/class-rocket-background-database-optimization.php on line 77

**Comment by Tabrisrp** [comment]
I'm having a hard time replicating any of these

**Comment by webtrainingwheels** [comment]
I no longer have the notices I reported - seems to be fine for me!

**Comment by arunbasillal** [comment]
Probably an edge case. Rolled down to 2.11.7 and then upgraded to 3.0 beta-4. Got this

`Notice: Undefined index: automatic_cleanup_frequency in /home/wpquicki/mega/wp-content/plugins/wp-rocket/inc/classes/admin/settings/class-settings.php on line 379`

https://github.com/wp-media/wp-rocket/blob/branch-3.0/inc/classes/admin/settings/class-settings.php#L379
