### ISSUE TITLE
3.0 Alpha - Dashboard - With new activation, current analytics opt-in displays above dashboard

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#831]
It probably needs further discussion/ validation, but with a new activation our current opt-in displays above the dashboard where we already have the opt-in switch "Rocket Analytics" - should we have both? 
![screen shot 2018-03-13 at 6 39 07 pm](https://user-images.githubusercontent.com/8108643/37378952-8b8e7fc6-26ee-11e8-8151-7d09d6f554d2.png)

**Comment by Tabrisrp** [comment]
This one is displayed only one time, so I believe we should keep it. It should not show everything though, the info data should be collapsed

**Comment by arunbasillal** [comment]
> the info data should be collapsed
The data was always open for me on multiple installs. 

Its probably too late into this release, but I think we need to find a better way to integrate the Imagify banner. Maybe add it to the sidebar for File Optimization or even as a mini banner inside the File Optimization tab (as that is exactly what Imagify does). Having the banner and the question takes a lot of the beauty away from the dashboard.

**Comment by Tabrisrp** [comment]
Data is correctly collasped now

**Comment by GeekPress** [comment]
@arunbasillal On 3.1 we will remove the Imagify banner to introduce a "Images Optimization" new tab where we will promote Imagify.

**Comment by arunbasillal** [comment]
@GeekPress Sounds exciting!
