### ISSUE TITLE
3.0 Alpha- Dashboard- Text corrections

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#832]
My account ---> My Account
Expiration date ---> Expiration Date
My status  ---> My Status
Rocket Sharer ---> Rocket Analytics
Still can not find a solution? ---> Still can't find a solution?

**Comment by Tabrisrp** [comment]
> Still can't find a solution?

I'm trying to not use contraction in translatable strings, else I have to escape the quote with a backslash.

**Comment by ernee** [comment]
Oh I see. Perhaps say this instead:

> Still cannot find a solution?
