### ISSUE TITLE
3.0 Alpha- All Tabs (except Database) - "SAVE CHANGES" button should be "SAVE OPTIONS"

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#833]
Buttons say "SAVE CHANGES" when mockups have "SAVE OPTIONS" where they are present.

(applies to all except the Database)

**Comment by GeekPress** [comment]
You should keep "Save Changes" as it the default value everywhere on the WordPress admin. In fact "Save Options" isn't correct in the mockup. 

Will ask to Matthieu if there was any reason for the update. If not, I will recommend to keep like WP does on its own options page, I mean "Save Changes"

**Comment by Tabrisrp** [comment]
Closed as invalid since we keep `Save Changes`
