### ISSUE TITLE
3.0 Alpha - File Optimization - Text Corrections

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#834]
**Tab Title**

File optimization ---> File Optimization 

**Basic Settings**

• Combine Google fonts files --> 

  Combine Google Fonts files

• Combining Google fonts will reduce the number of HTTP requests.---> 

   Combining Google Fonts will reduce the number of HTTP requests. 

• Removes the version query string from static files (e.g. style.css?ver=1.0 and encodes it into the filename instead (e.g. style-1.0.css. Can improve your GTMetrix score. More info -----> 

 Removes the version query string from static files (e.g. style.css?ver=1.0) and encodes it into the filename instead (e.g. style-1.0.css). Can improve your GTMetrix score. More info

**CSS Files**

• Minify CSS Files --->

  Minify CSS files

• Combine CSS Files (Enable minify CSS files to select) ---> 

   Combine CSS files _(Enable Minify CSS files to select)_

**JavaScript Files**

• (section title) JS Files  ---> 

  JavaScript Files

• Combine JavaScript Files (Enable minify JS files to select) --->

  Combine JavaScript files _(Enable Minify JavaScript files to select)_

• Excluded JS Files ---> 

  Excluded JavaScript files 

• Specify URLs of JS files to be excluded from minification and concatenation. --->  

  Specify URLs of JavaScript files to be excluded from minification and concatenation. 

• (Safe Mode, per mockup should be on its own line) 
Deactivating may result in broken functionality, test thoroughly! ---> 
   
_Deactivating may result in broken functionality, test thoroughly!_

**Comment by ernee** [comment]
Remaining corrections:

• Removes the version query string from static files (e.g. style.css?ver=1.0 and encodes it into the filename instead (e.g. style-1.0.css). Can improve your GTMetrix score. More info ––>

Removes the version query string from static files (e.g. style.css?ver=1.0) and encodes it into the filename instead (e.g. style-1.0.css). Can improve your GTMetrix score. More info

**(needs closing parenthesis on "e.g. style.css?ver=1.0" )**

• Combine CSS files _(Enable minify CSS files to select)_ -->

Combine CSS files _(Enable Minify CSS files to select)_

**(captitalize "Minify")**

• _Combine CSS merges all your files into 1, reducing HTTP requests. Not recommended if your site uses HTTP/2. More info_--->

_Combine CSS condenses all your files into 1, reducing HTTP requests. Not recommended if your site uses HTTP/2. More info_

**(replace _merges_ with _condenses_)**

• Combine JavaScript files _(Enable minify JS to select_) --->

Combine JavaScript files _(Enable Minify JavaScript files to select)_

**(capitalize "Minify" and replace "JS" with "JavaScript")**

**Comment by Tabrisrp** [comment]
> (replace merges with condenses)
Didn't we agree on slack that merges is better wording than condenses? ping @webtrainingwheels

**Comment by webtrainingwheels** [comment]
Yes, we decided on "merges" in the end

**Comment by ernee** [comment]
Sorry! That's correct. Maybe I was thinking the opposite when viewing the mockups.

**Comment by ernee** [comment]
One last thing:

Combine JavaScript files _(Enable Minify JavaScript to select)_ -->
Combine JavaScript files _(Enable Minify JavaScript files to select)_

**(add "files" )**
