### ISSUE TITLE
3.0 Alpha - CDN - Separation between 2 blocs

### ISSUE THREAD

**Issue by edenpulse** [wp-media/wp-rocket#839]
There's a separation between the option : 
- Enable Content delivery 
- CDN Cname(s)

like screenshot
<img width="682" alt="capture d ecran 2018-03-14 a 10 14 48" src="https://user-images.githubusercontent.com/433393/37393221-cae11940-2770-11e8-840c-52454c391451.png">

**Comment by Tabrisrp** [comment]
@Thomasgeisen can you do this with the current fields and containers?

**Comment by Thomasgeisen** [comment]
@Tabrisrp No, i need another fieldset `.wpr-fieldsContainer-fieldset` to make two separate blocks.

**Comment by Tabrisrp** [comment]
@Thomasgeisen I did it directly by changing small stuff

**Comment by edenpulse** [comment]
good.
