### ISSUE TITLE
3.0 Alpha - All Tabs - Menu Order

### ISSUE THREAD

**Issue by edenpulse** [wp-media/wp-rocket#842]
Add-ons menu should be under Tools

- CDN
- Tools
- Add-ons

**Comment by Tabrisrp** [comment]
This is a code constraint for me. The tools tab is not part of the options form (there is no options in it), but there is a different form to import the settings. The add-ons section and sub-sections do have options for the main form.

It's not possible in HTML to nest forms, so I need to close the options forms before opening the import form. Hence the add-ons tab needs to be before the tools tab for the code to work.

**Comment by GeekPress** [comment]
I had the same reflexion but in fact it's seem even more "logical" to have the Tool tab in last. 

Everything which is before is related to performance when the actions we can do in Tools aren't related to performance.

**Comment by Tabrisrp** [comment]
Agree on keeping it like this then?

**Comment by GeekPress** [comment]
Yes!
