### ISSUE TITLE
3.0 Alpha - All tabs - Save changes button layout on Windows

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#847]
This is how "Save changes" button looks like on Windows - https://www.screencast.com/t/O8G8LnZZrcLt

Pretty much as default button where borders are not defined (for me at least).

@edenpulse can you confirm this is good/bad?

**Comment by edenpulse** [comment]
@markonikolic985 This is not good.

**Comment by Thomasgeisen** [comment]
fixed with commit 6566c0c

**Comment by markonikolic985** [comment]
Works like a charm :D Fixed.
