### ISSUE TITLE
 Access to HTTPS when no SSL certificate is present - check on the URLs inside the cache files

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#85]
f a user accedes to a page using HTTPS when no SSL certificate is active on the website, WP Rocket creates the usual cache file but it will add the HTTPS in the URLs. This can produce a broken layout when a new user visits the site. At the moment we can avoid this adding a redirection rule from HTTPS to HTTP in the htaccess, in order to prevent visitors to access the HTTPS pages.
Should we add an additional check in the plugin in order to avoid this behaviour?
Reference ticket: https://secure.helpscout.net/conversation/206025778/15881/?folderId=628132

**Comment by Tabrisrp** [comment]
Reading the ticket, it's super edge case and more an issue with the website config than with WP Rocket.
