### ISSUE TITLE
3.0 Alpha - Dashboard - Rocket Sharer Popup doesn't show up

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#851]
Video - https://youtu.be/MC30JYPjSVU
Tested on Firefox and Chrome.

As per the testing doc, the pop-up is supposed to show up as soon as `Rocket Sharer` is turned on. The popup doesn't show up automatically. 

It shows up when I click `What info will we collect?`, but the `Activate Rocket Analytics` button does nothing.

**Comment by ernee** [comment]
When making the test, perhaps this was my assumption that the "Rocket Analytics" pop-up should show up when the user turns on "Rocket Analytics" (correct wording). As @arunbasillal mentions, the pop-up has a button to "Activate WP Rocket Analytics":  

![screen shot 2018-03-14 at 9 28 33 am](https://user-images.githubusercontent.com/8108643/37416060-1aa8657a-276a-11e8-8805-82726a290d82.png)

This is what made me question the need for the old opt-in here: https://github.com/wp-media/wp-rocket/issues/831

**Comment by GeekPress** [comment]
Where is the testing doc? Because, it wasn't plan to have the pop-in displayed after turned on the Rocket Analytics option like actually with the checbox.

The pop-in is displayed only by clicking on "What info will we collect?". Other behavior wasn't planned.

**Comment by ernee** [comment]
@GeekPress this was my assumption since I wasn't fully aware of the UX around this.  I'm sorry if I assumed incorrectly. I was confused by the button.

**Comment by arunbasillal** [comment]
@GeekPress It was probably a confusion, but the issue with the `Activate Rocket Analytics` button still stands as it does nothing in `3.0 Alpha 3`

The word `Rocket Sharer` is corrected to `Rocket Analytics` in `Alpha 3`. So part of the confusion is now cleared :+1:

**Comment by ernee** [comment]
On our live test site, it doesn't look to be working in 3.0 Alpha4 (Firefox, Chrome, Safari):

http://g.recordit.co/RDFPIVsCIZ.gif

**Comment by Tabrisrp** [comment]
it's not included in alpha 4

**Comment by ernee** [comment]
oh ok, no problem. Thought it was since in "To Review."
