### ISSUE TITLE
Admin Bar Quick Links - No notice for Purge OPcache

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#852]
Clicking Purge OPcache from Quick Links or from the Tools tab of WP Rocket doesn't show a notice. 

Turns out there is no notice in `2.11.6` either, so this should probably be filed as a general issue rather than as a 3.0 issue? - http://mega.wp-rocket.me/newspaper/wp-admin/options-general.php?page=wprocket

**Comment by Tabrisrp** [comment]
I don't think we ever displayed a notice for that
