### ISSUE TITLE
3.0 Alpha - White Label - Update notification showed up on a white labelled website

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#853]
Test Process: 
- Set WP Rocket account to `2.11.7`
- Install `2.11.7` on a test website 
- Opt-in to Beta so that `alpha` update notifications show up.
- Enable white label.
- Update WP Rocket account to `WP Rocket 3.0 alpha 3`
- Check for notifications in the white labelled website.

And the notification did show up.

**Comment by Tabrisrp** [comment]
Is the update block for whitelabel already in place?

**Comment by GeekPress** [comment]
It must be => https://github.com/wp-media/wp-rocket.me/blob/master/check_update.php#L89

I'm wondering if because of the -alpha in the version number it causes an issue during the validation

**Comment by GeekPress** [comment]
Ah ok, after checking the code, it's only for the stable version.

**Comment by GeekPress** [comment]
I fixed it by totally stop sending update notification for all white label which are under an Infinite License. Most of them doesn't update the plugin and are still on 2.9.
