### ISSUE TITLE
3.0 Alpha - Improve mobile / tablet version

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#854]
Until working on a dedicated mobile version, we can still improve the mobile version to be usable, which isn't now.

To start we can on mobile:
- remove the sidebar
- reduce the menu to icons + replace the WP Rocket logo by our favicon (the W)
- remove all "Need Help" and Beacon icon. In fact Beacon doesn't seem to work well on WP mobile admin

And on tablet:
- remove the sidebar

**Comment by Thomasgeisen** [comment]
If i follow WordPress breakpoints : 
- Mobile < 763px
- Tablet < 960px

But with the WordPress admin bar, the main content of the plugin is very small when page width < 1200px... Should i remove the sidebar too ? Another idea ?

**Comment by Tabrisrp** [comment]
I think so, the most important thing is to keep the main content usable
