### ISSUE TITLE
3.0 Alpha - Add-ons - Remove Save Changes?

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#858]
The UI of the Add-ons screen is confusing. If an add-on can be activated only with the toggle, then the Save Changes button should be removed. 

If the add-on requires clicking Save Changes, then it should not have a toggle. 

I think my confusion is because in either case,  whether after toggling or saving,  there is no visual feedback or confirmation that anything actually happened.

**Comment by Tabrisrp** [comment]
duplicate of #825
