### ISSUE TITLE
CSS minification breaks calc(), vendor update required

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#86]
When CSS minification is enabled, calc() values will be minified as well, but need to be separated by spaces.
Current behavior: calc(1.5rem+2.5px)
Expected behavior: calc(1.5rem + 2.5px)

Reported by customer: https://secure.helpscout.net/conversation/210133386/16324/?folderId=714999
Original bug in lib fixed in February: https://github.com/mrclay/minify/issues/503

**Comment by glueckpress** [comment]
✅  Spaces inside of `calc()` expressions are being preserved as expected with the current 2.9 branch. This goes for CSS files as well as for inline CSS.

Unrelated to the `calc()` issue, but maybe be worth noting because possibly (?) related to a vendor update: CSS files are not 100% minified, I see a lot of hard line-breaks being preserved, or new ones added. A properly minified file would usually be expected to contain only 1 long line of CSS.

**Comment by eugenem** [comment]
Hi! Some of calc() are still broken at 2.9.11
If you try to minify this file, for example: https://timetostepitup.com/wp-content/themes/aton-child/style.css

**Comment by Tabrisrp** [comment]
The remaining issues should be fixed in 2.10

**Comment by eugenem** [comment]
Thanks!

**Comment by shivampaw** [comment]
This still seems to exist in 2.10

**Comment by der-krueger** [comment]
Same here in 2.10.3

**Comment by Tabrisrp** [comment]
If you still have the issue, disable, save settings & re-enable CSS minification. It should work after.

**Comment by shivampaw** [comment]
@Tabrisrp not working.
https://www.shivampaw.com/ is the site. Scroll to bottom where the contact form is. The budget dropdown CSS isn't working - spaces in the calc function aren't there.

**Comment by Tabrisrp** [comment]
open a support ticket in that case, we'll look into it.

**Comment by JiveDig** [comment]
2.10.4 - We're still experiencing this issue.

**Comment by adamlaki** [comment]
2.10.12 - Unfortunately still an issue.

**Comment by glueckpress** [comment]
Can’t reproduce with 2.10.12, `calc()` is handled correctly:

<img width="735" alt="screen shot 2017-12-11 at 09 39 31" src="https://user-images.githubusercontent.com/308422/33822405-b26dcb04-de57-11e7-818d-766481e5c901.png">

Same in 2.11 (current development branch), spaces are preserved:

<img width="664" alt="screen shot 2017-12-11 at 09 41 21" src="https://user-images.githubusercontent.com/308422/33822477-f62ed856-de57-11e7-932e-2c5eb011310c.png">

@adamlaki, @JiveDig Please [open a support ticket](https://wp-rocket.me/support/) if your issue can be reproduced. Thanks

**Comment by CobbleWebDevUser** [comment]
HI there. 
I reproduce on my side. 
```
padding-top: calc(150px + 10vw);
```
becomes 
```
padding-top:calc(150px+10vw);
```

But it occurs only with the "+" sign. 

I found a work around which work for me by wrapping the code with a
```
@media all {
}
```
When the calc() is into a media query, the spaces around "+" sign are not removed.

**Comment by mkstix6** [comment]
Same here I think:

Original…

`height: calc(3.25rem + 2px);`

…is minified to…

`height: calc(3.25rem+2px);`

…without the spaces it breaks.

**Comment by zumek** [comment]
Issue still present in v 3.4.0.5

Is the plugin using yuicompressor? - https://github.com/yui/yuicompressor/issues/59
