### ISSUE TITLE
3.0 Alpha - Add-ons - Varnish - WP Engine

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#861]
Updated on a WP Engine site (where Varnish purge is automatically enabled) and this is how the add-ons screen looks: 

![wp_engine_add-ons_page](https://user-images.githubusercontent.com/1043076/37446179-f3b35492-27d8-11e8-9fb4-385568743be9.jpg)

Not sure what's expected - I think I would assume Varnish add-on should be displayed and toggled on. No point hiding it from the customer - better to show them what we have done for them automatically.

**Comment by GeekPress** [comment]
Agree with Lucy. As we won't have any other one-click add-sons for the 3.0, we must totally remove the One-click section if we have to remove Varnish.

**Comment by Tabrisrp** [comment]
Which way do we go?

- Remove all the one-click block
- Show it but with the option always turned on

@webtrainingwheels @GeekPress

**Comment by webtrainingwheels** [comment]
For me, we should show it and make sure it's always turned on. 
Bonus: add text to say why. 

My reason: We only hid the Varnish tab before to avoid having a useless tab and make a more streamlined interface. 
In 3.0 we have a more streamlined interface and hiding the add-on doesn't make anything better for the customer. 
I think it's more valuable to show the customer what we are doing for their benefit and why.

**Comment by GeekPress** [comment]
> I think it's more valuable to show the customer what we are doing for their benefit and why.

Totally agree with you.

> Bonus: add text to say why.

What will be the text? Will we have a context? I mean the hosting name for example.

**Comment by GeekPress** [comment]
> For me, we should show it and make sure it's always turned on.

For that, we could remove the "On / Off" button. We will be sure it won't possible to deactivate it, except by using our filter.

**Comment by webtrainingwheels** [comment]
Text suggestion: "We have detected Varnish and have enabled auto-purge for compatibility."

If we want to specify the host we could say: "Your site is hosted on [WP Engine], we have enabled Varnish auto-purge for compatibility."

**Comment by GeekPress** [comment]
@webtrainingwheels Thanks for your suggestion.

@Tabrisrp will it be easy to implement the suggestion with the hostname?

**Comment by Tabrisrp** [comment]
I have to create a new filter to handle all that, but it's probably doable

**Comment by Tabrisrp** [comment]
It's a bit more complicated than that though. Not all hostings we have compatibility built-in with use Varnish. Some use NGINX fastcgi instead for example, in which case the Varnish block doesn't mean anything.

**Comment by webtrainingwheels** [comment]
At least for this version I think we only need to deal with the cases where we would currently (i.e. 2.11 and less) remove the Varnish tab. 
For me personally, it's fine to keep the generic (not hosting-specific) text if it's easier. 

Currently, for hosts that use fastcgi, presumably the Varnish tab is still visible? If so, we can keep the same behaviour in 3.0. If we do some auto-purge for fastcgi then in the future we'll need a fastcgi add-on I guess.

**Comment by Tabrisrp** [comment]
For Kinsta which uses fascgi, we remove the Varnish tab, and we do a purge of their cache when WP Rocket clear cache action is triggered.

For some other compatibilities, I'm not even sure what caching system they use

**Comment by webtrainingwheels** [comment]
I don't know what's possible in our current timeline. Would one of these be the easiest? 
-- Either, leave Varnish add-on as normal (i.e. present as if there were no special compatibility) - if the user activates it, it won't do anything anyway.
-- Or, hide it on Kinsta until we have a Fast cgi add-on we can show instead.

**Comment by GeekPress** [comment]
To resume on 2.11 we hide the tabs for:

- Varnish hosting (like WP Engine)
- Fast CGI hosting (like Kinsta)
- Other hosting which can hide the tab by using our filter

Am I right?

**Comment by Tabrisrp** [comment]
Yes. The concern really is with hostings we have compatibility code in core:

- WP Engine
- WP Serveur
- Savii
- Kinsta
- GoDaddy
- Flywheel

Kinsta is the only one (I think) that uses fastcgi instead of Varnish. For them, it doesn't make sense to show them the add-on at all.

For the others, we can show the add-on, with the option on + disabled, and modify the text inside the add-on block.

**Comment by GeekPress** [comment]
Ok then, we can confirm that we totally remove the One click add-on block for Kinsta users (until to have a new add-on not related to Varnish).

We can also remove it for SiteGround which are using NGINX cache now, and not Varnish.

For other we want to keep the Varnish add-on, we will remove the "on/off" button as it must be on all the time and add the sentence "Your site is hosted on [WP Engine], we have enabled Varnish auto-purge for compatibility."

**Comment by GeekPress** [comment]
> We can also remove it for SiteGround which are using NGINX cache now, and not Varnish.

With beta4, it's not displayed on SiteGround even if SG Optimizer is activated.

**Comment by GeekPress** [comment]
If SG Optimizer plugin is activated or $GLOBALS['sg_cachepress_supercacher'] exists, we can consider the user is on SiteGround.

**Comment by Tabrisrp** [comment]
I updated the code directly on smashingcoding, you can test with/without dynamic caching enabled
