### ISSUE TITLE
3.0 Alpha - Advanced Rules - The description of the section isn't complete

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#867]
The sub description "Read the documentation..." is missing

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2E3Z091n1u2n3w0d2K2w/Capture%20d%E2%80%99e%CC%81cran%202018-03-16%20a%CC%80%2000.01.52.png?X-CloudApp-Visitor-Id=4e40cd4ef35c7263dc46f05d24ccdaef&v=bfe77837)

**Comment by Tabrisrp** [comment]
@ernee @webtrainingwheels which docs should that point to?

**Comment by webtrainingwheels** [comment]
I don't think we need any of this description at all. The other tabs don't have it, and in this case it doesn't add anything. Can we just remove it?

**Comment by GeekPress** [comment]
We also have a description on the Database tab.

So if you want to remove the sub-description on Advanced rules, it must be also on Database.

Also the "These settings are for advanced cache management" has to be removed. Keep it alone doesn't make sense. (same for Database)

**Comment by webtrainingwheels** [comment]
Agree, don't know why there is the sub-description on Database either. 

This text  is useful but should be more like an alert at the top of the page. 
To be clear,  this is the text I'm referring to: "Backup your database before you run a cleanup!
Once a database optimization has been performed, there is not way to undo it."

Maybe styled like the below and placed above Post Cleanup?
![wp_rocket_ _wordpress_themes_ _wordpress](https://user-images.githubusercontent.com/1043076/37513939-ad711bd6-28c3-11e8-98a8-e037ba5a0d2b.jpg)

**Comment by GeekPress** [comment]
In fact Matthieu integrated the actual text => https://cl.ly/0f46370d1A0e

We could insert the warning text just before or after the "Optimize" button. To be sure that the text will have a better position to be read.

**Comment by webtrainingwheels** [comment]
True... it  just gave a weird experience for only 2 tabs to have a sub description. 

Near the 'Optimize' button makes sense!
