### ISSUE TITLE
3.0 Alpha - Advanced Rules - Text

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#868]
_"Sensitive pages like custom login/logout URLs should be excluded from cache.
Cart, checkout and "my account" pages set in WooCommerce (and some other ecommerce plugins) will be detected and never cached by default."_

In our current interface we only show the text about WooCommerce when that plugin is active. 

So the text should be updated as follows. 
Keep: ""Sensitive pages like custom login/logout URLs should be excluded from cache."

When WooCommerce is active show: 
"Cart and checkout pages set in WooCommerce will be detected and never cached by default. No need to enter them here."

**Comment by Tabrisrp** [comment]
In fact we detect a bunch of ecommerce plugins and only display the text if one of them is present. I'll add that back
