### ISSUE TITLE
3.0 Alpha - Deactivation Intent - Text color

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#877]
The color isn't the good one.

Now:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1Q1Q0r1U1z354331240k/Capture%20d%E2%80%99e%CC%81cran%202018-03-16%20a%CC%80%2010.13.37.png?X-CloudApp-Visitor-Id=4e40cd4ef35c7263dc46f05d24ccdaef&v=5c163e94)

VS

Mockup: 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1u0z3H0F2e3w2D1v343C/Capture%20d%E2%80%99e%CC%81cran%202018-03-16%20a%CC%80%2010.13.31.png?X-CloudApp-Visitor-Id=4e40cd4ef35c7263dc46f05d24ccdaef&v=8d3286db)

**Comment by GeekPress** [comment]
I still don't the difference in text.

Maybe there is a misunderstood as in the commit it seems to be fixed only the <a>. But I talk about the text (the content color).

**Comment by Thomasgeisen** [comment]
Yes, i thought it was for the <a> tags.
My bad, i will update the content color !

**Comment by edenpulse** [comment]
Good for me
