### ISSUE TITLE
 Improve database optimization to allow keeping a fixed number of revisions

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#88]
Some customers would prefer to keep a number of revisions and not clean them all when optimizing the database

**Comment by alfonso100** [comment]
a similar case, a customer is asking if it would be possible to keep the latest 7 days of revisions
https://secure.helpscout.net/conversation/1090086240/147371?folderId=2683093

**Comment by GeekPress** [comment]
This is something which can be already done by using the `WP_POST_REVISIONS` constant into the wp-config.php file. 

Adding an option to do that will be just be a way to update the `WP_POST_REVISIONS` from WP Rocket directly.

As it's pretty easy to make the update and a ton of tutorials exists about « How to limit post revisions », we aren't going to do that.

Another reason is we can potentially break website by editing the wp-config.php file.

**Comment by blogtutor** [comment]
@GeekPress You're missing a very common scenario. If someone has been publishing for a long time, and hasn't had `WP_POST_REVISIONS` set, they may have many more revisions on old posts. (For many of our clients, this can tally up to many thousands, or even tends of thousands of revisions.)

Excess revisions don't get pruned if someone _later_ adds the `WP_POST_REVISIONS` constant -- unless they happen to go back to a given post and update it (but then it only prunes those revisions for that one post). In other words, there's no built-in process to go back to old/existing posts and prune the revisions to that max limit.

We use the "Optimize Database After Deleting Revisions" plugin for this, and it works great. We can cull the number of revisions, while still leaving enough in place to keep our clients happy.

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2808956707/533173

**Comment by joejoe04** [comment]
Related: https://secure.helpscout.net/conversation/2915920724/555779
