### ISSUE TITLE
3.0 Alpha - Dashboard - Color the expiration date in red (or something else) when the license is expired

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#880]
Now if we have an expired license, the date is displayed with the green color

![%20d%E2%80%99e%CC%81cran%202018-03-15%20a%CC%80%2016.23.59.png?X-CloudApp-Visitor-Id=4e40cd4ef35c7263dc46f05d24ccdaef&amp;v=ede31ab8](https://d3vv6lp55qjaqc.cloudfront.net/items/0Y3D0J14030w0B0r203k/Capture)

So we must change the color to red or something less agressive but more neutral

**Comment by Tabrisrp** [comment]
That was not on the mockup.

Need @edenpulse feedback on the color to use

**Comment by edenpulse** [comment]
**I think we can do many things.**
- Show it like it's disabled. (so in grey #80888F )
- Show it like it needs your attention (so in red #D60E5B ) 

**Improvement idea** 
Add an icon showing the licence status (adds context)
![licence-status](https://user-images.githubusercontent.com/433393/37530135-34054b66-2939-11e8-94b8-d1f6ebf1c5ec.png)

My choice : **1 and 2.**

**Comment by GeekPress** [comment]
Let's for 1 & 2 ;)

Thanks @edenpulse

**Comment by edenpulse** [comment]
it misses the small icons in front of the red texts
![capture d ecran 2018-03-19 a 15 35 45](https://user-images.githubusercontent.com/433393/37601802-3afad48c-2b8b-11e8-9e16-3e684d0a8973.png)

**Comment by Thomasgeisen** [comment]
I did it in my last commit c488fac, 1 min before your comment !

**Comment by GeekPress** [comment]
The red color and icon must be applied only on the expiration date.

The license still stay the same.

License : *Unlimited*
Expiration Date :  :x: *january 16, 2010*

**Comment by Thomasgeisen** [comment]
An user without license can't access to dashboard, right ?
So, what color i need to apply for license ? Always green ?

**Comment by GeekPress** [comment]
A user with an expired license can access to the plugin and still using it.

The license expiration is for receiving new updates and get support.

For license, we should keep the green all the time.
