### ISSUE TITLE
 Uncaught Error: Class 'Rocket_Sitemap_Preload_Process' not found

### ISSUE THREAD

**Issue by Kleindberg** [wp-media/wp-rocket#883]
I'm trying to activate downloaded WP-Rocket plugin from GitHub (master branch) on Wordpress 4.9.4 and get next error:

> **Fatal error:** Uncaught Error: Class 'Rocket_Sitemap_Preload_Process' not found in /home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/wp-rocket.php:246 
> Stack trace: 
> #0 /home/taradajk/golovolomka.in.ua/opt/wp-includes/class-wp-hook.php(286): rocket_init('') 
> #1 /home/taradajk/golovolomka.in.ua/opt/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
> #2 /home/taradajk/golovolomka.in.ua/opt/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
> #3 /home/taradajk/golovolomka.in.ua/opt/wp-settings.php(327): do_action('plugins_loaded') 
> #4 /home/taradajk/golovolomka.in.ua/opt/wp-config.php(31): require_once('/home/taradajk/...') 
> #5 /home/taradajk/golovolomka.in.ua/opt/wp-load.php(37): require_once('/home/taradajk/...') 
> #6 /home/taradajk/golovolomka.in.ua/opt/wp-admin/admin.php(31): require_once('/home/taradajk/...') 
> #7 /home/taradajk/golovolomka.in.ua/opt/wp-admin/plugins.php(10): require_once('/home/taradajk/...') 
> #8 {main} thrown in **/home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/wp-rocket.php** on line **246**
> 

and when installing 3.0 alpha:

> **Fatal error:** Uncaught Error: Class 'WP_Rocket\Plugin' not found in /home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/inc/main.php:36 Stack trace: #0 /home/taradajk/golovolomka.in.ua/opt/wp-includes/class-wp-hook.php(286): rocket_init('') #1 /home/taradajk/golovolomka.in.ua/opt/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /home/taradajk/golovolomka.in.ua/opt/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/taradajk/golovolomka.in.ua/opt/wp-settings.php(327): do_action('plugins_loaded') #4 /home/taradajk/golovolomka.in.ua/opt/wp-config.php(31): require_once('/home/taradajk/...') #5 /home/taradajk/golovolomka.in.ua/opt/wp-load.php(37): require_once('/home/taradajk/...') #6 /home/taradajk/golovolomka.in.ua/opt/wp-admin/admin.php(31): require_once('/home/taradajk/...') #7 /home/taradajk/golovolomka.in.ua/opt/wp-admin/plugins.php(10): require_once('/home/taradajk/...') #8 {main} thrown in **/home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/inc/main.php** on line **36**

or 

> **Fatal error:** Uncaught Error: Class 'WP_Rocket\Admin\Options' not found in /home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/inc/functions/options.php:18 Stack trace: #0 /home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/inc/functions/options.php(491): get_rocket_option('secret_key') #1 /home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/inc/main.php(196): rocket_valid_key() #2 /home/taradajk/golovolomka.in.ua/opt/wp-includes/class-wp-hook.php(286): rocket_activation('') #3 /home/taradajk/golovolomka.in.ua/opt/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /home/taradajk/golovolomka.in.ua/opt/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/taradajk/golovolomka.in.ua/opt/wp-admin/plugins.php(174): do_action('activate_wp-roc...') #6 {main} thrown in **/home/taradajk/golovolomka.in.ua/opt/wp-content/plugins/wp-rocket/inc/functions/options.php** on line **18**

WP-Rocket never used on this site before. Using PHP 7.2.

**Comment by Tabrisrp** [comment]
You need to install the composer dependancies when you use the github version.

So you need to have composer, and do `composer install --no-dev` in WP Rocket folder.

**Comment by sushyant** [comment]
I have composer and --no-dev is installed but can't active this plugin
