### ISSUE TITLE
3.0 Alpha - UTM story

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#885]
Add ?utm_source=wp_plugin&utm_medium=wp_rocket on all wp-rocket.me and docs.wp-rocket.me links

**Comment by Tabrisrp** [comment]
I already have this in the plugin in some places `?utm_source=wp-rocket&utm_medium=wp-admin&utm_term=doc-support&utm_campaign=plugin`

Do you want to keep this one or the one you provided?

**Comment by GeekPress** [comment]
Yes you can replace old utm, we are going to follow our UTM guide => https://docs.google.com/document/d/1KJ5pHTq0_5plStCTEowq6lWJ06g3OuvwpcLDapKRxuo/edit
