### ISSUE TITLE
3.0 Alpha - Right Column (sidebar) - Text question

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#887]
@webtrainingwheels and I have been questioning the need for the question mark in the title "How to correctly measure your website's loading time?": 

![screen shot 2018-03-19 at 8 50 09 am](https://user-images.githubusercontent.com/8108643/37606511-dcfcf5c8-2b52-11e8-934c-788440629c87.png)

It is not necessarily a question the way it is phrased. 

I think a proper question would be "How do you correctly measure your website's loading time?"

However, should we update the text to the above or should we remove the question mark? 

open to thoughts @GeekPress @edenpulse @Tabrisrp

**Comment by GeekPress** [comment]
I have no thoughts about that. It's like you want ^^

**Comment by ernee** [comment]
Let's just remove the question mark. 

Updated text: 

`How to correctly measure your website's loading time`
