### ISSUE TITLE
 Possibility to add filters for sitemap preload

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#89]
Adding a filter or, depending on how the sitemap is created, allow the user to add individual sitemaps in the textfield. i.e. if the sitemaps is generated by Yoast (that is a sitemap of sitemaps), adding the possibility to select only the preferred sitemaps in the list instead of loading the global on

**Comment by arunbasillal** [comment]
@GeekPress I think we can close this. We do not have this as a feature request from customers. The text are we have is good enough for this I suppose. Please re-open if you disagree.
