### ISSUE TITLE
3.0 Alpha- Deactivation Intent- Update response text for "broke my layout"

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#890]
Suggested update to the response for the "broke my layout" option:

_This type of issue can usually be fixed by deactivating some options in WP Rocket. Click "Apply Safe Mode" to quickly disable LazyLoad, File Optimization, Embeds and CDN options. Then check your site to see if the issue has resolved._

`Apply Safe Mode`

_Is the issue fixed? Now you can reactivate options one at a time to determine which one caused the problem. More info._

@Tabrisrp could you verify if those are all the options disabled ?

@GeekPress @webtrainingwheels  does this update read better?

**Comment by Tabrisrp** [comment]
Yes they are the correct options

**Comment by ernee** [comment]
Another side request, can the text to replace the button when Safe Mode is applied be in **bold** or stand out another way? Currently, it blends into the text already present:

![screen shot 2018-03-19 at 11 44 16 am](https://user-images.githubusercontent.com/8108643/37615586-e8458ba8-2b6a-11e8-8b26-b2ef2abea964.png)

The text I'm referencing:  `Safe mode applied. Review your site in a private/logged out browser window.`

@edenpulse if you have thoughts too?

**Comment by GeekPress** [comment]
@ernee The update text is better thanks :)

For your button replacement suggestion, it's a good idea too. We should also ask to @edenpulse to design it ^^

**Comment by GeekPress** [comment]
@edenpulse is going to design something for the button which will be replace by a sentence.

**Comment by edenpulse** [comment]
Here's my proposition.
![capture d ecran 2018-03-26 a 10 31 25](https://user-images.githubusercontent.com/433393/37895183-db622d62-30e0-11e8-9d6b-93c5a0eabe4a.png)

**Comment by GeekPress** [comment]
Very nice, thanks @edenpulse

**Comment by ernee** [comment]
looks great @edenpulse !
