### ISSUE TITLE
3.0 Alpha - Ad blocker notification - Text suggestion

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#891]
Below are suggestions for notifications based on the detection and deactivation of the ad blocker. Please let me know if it needs to be updated if the implementation is different @GeekPress @Tabrisrp 

For detection:

`WP Rocket: Ad blocker detected. Disable it on your site to access all our available features.
`

For deactivation: 

`WP Rocket: Thanks for turning off your ad blocker. Optimize away! `

@webtrainingwheels feel free to let me know if you have feedback on text as well.

**Comment by webtrainingwheels** [comment]
Text is good for me!

**Comment by GeekPress** [comment]
I'm not sure about the "our available features" as it concerns only the support part. 

Even if you have a ad blocker you will have access to all features.

**Comment by ernee** [comment]
@GeekPress 

I was thinking of the "features" of beacon not being available to them.

Perhaps another suggestion for detection:

`WP Rocket: Ad blocker detected. Disable it on your site to access our support features.`

**Comment by GeekPress** [comment]
@ernee What about adding tutorials link to help people to know how to whitelist their own domain?

Example:
uBlock Origin => https://www.youtube.com/watch?v=7SGFoyvl_k4
AdBlock => https://www.youtube.com/watch?v=BJaR4SMShhE

**Comment by ernee** [comment]
sounds good @GeekPress, does the below sound good? 

A link from the text `Learn more.` to a short doc (it's easier for us to update content/ links there):

`WP Rocket: Ad blocker detected. Disable it on your site to access our support features. [Learn more.](https://docs.wp-rocket.me/article/1080-disable-ad-blocker-for-support-integration) 
`
Future document link: https://docs.wp-rocket.me/article/1080-disable-ad-blocker-for-support-integration

**Comment by GeekPress** [comment]
@ernee Do you confirm that the doc will be ready for the release date?

@edenpulse Do you have enough text to make the banner?

**Comment by ernee** [comment]
@GeekPress yeah it's ready to go here: https://docs.wp-rocket.me/article/1080-disable-ad-blocker-for-support-integration?preview=5ab91537042863794fbe9bfa

We would just need to publish it with our other doc updates.

**Comment by ernee** [comment]
This will be the final link for the French doc if it is needed: https://fr.docs.wp-rocket.me/article/1081-desactiver-bloqueur-publicite-integration-support

**Comment by GeekPress** [comment]
Ok thanks for the confirmation :)

**Comment by edenpulse** [comment]
What do you think about this?
![alert-adblock](https://user-images.githubusercontent.com/433393/38017287-e9199598-3271-11e8-953d-d4b329e053a7.png)

**Comment by GeekPress** [comment]
@Thomasgeisen You can integrate this version :)
