### ISSUE TITLE
Polylang language detection compatibility to allow homepage caching

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#892]
Polylang since version 2.3 sets a `DONOTCACHEPAGE` on the homepage if the language detection option is active.

As discussed here: https://github.com/polylang/polylang/issues/236, we can use our mandatory cookie feature to serve the cache only once the language cookie is set, removing the need for the `DONOTCACHEPAGE`

**Comment by arunbasillal** [comment]
Repetition of what Remy already said, but adding for bit more clarity. 

Temporary solution is to disable `Detect browser language` in Polylang settings: `https://example.com/wp-admin/admin.php?page=mlang_settings`

**Comment by arunbasillal** [comment]
Related tickets: 

- https://secure.helpscout.net/conversation/567572129/66241/?folderId=1724284
- https://secure.helpscout.net/conversation/576497066/67551?folderId=1724284

**Comment by siblanco** [comment]
@arunbasillal thank you for the clarification. Unfortunately, disabling 'Detect browser language' in polylang doesn't fix the frontpage caching issue for me. Also, with Polylang activated, I am facing TTFBs of 4-5 seconds on every page. Once deactivated, the TTFB goes to a few ms. 

Any idea how to solve my issue?
