### ISSUE TITLE
3.0 Alpha - File Optmization - Exclusion field location

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#893]
I realize the mockup was already validated so this could be actually considered a feature request for 3.1. 

The position of the exclusion field for JS and CSS on the File Optimization tab could be confusing .

It's placed below Load JS deferred and Optimize CSS respectively. To the casual user who doesn't read, this suggests that files entered will be excluded from all JS -related options or all CSS -related options. Would be a bit clearer if the field was moved up, directly underneath the minify/combine options. 

![wp_rocket_ _wordpress_themes_ _wordpress](https://user-images.githubusercontent.com/1043076/37635043-89a63510-2bb6-11e8-92e0-88bd37e2a0d5.jpg)

==
The next level would be if one exclusion area for each of JS/CSS did in fact allow the user to choose which options to exclude the file from. Then we could get rid of helper plugins for excluding from defer js, async css, remove query strings. :) :) :)

**Comment by ernee** [comment]
This was also a question we raised @GeekPress and @edenpulse

**Comment by Tabrisrp** [comment]
This needs some active discussion to move forward

**Comment by GeekPress** [comment]
Before to discuss about Lucy's suggestion about having an area for each of JS/CSS, we have to respect the mockup to avoid confusions for our customers.

The exclude CSS and JS fields has to be moved below the concatenation options.
