### ISSUE TITLE
Add support to detect sitemap from “The SEO Framework”

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#899]
We could add support for the sitemap of this plugin: 

https://wordpress.org/plugins/autodescription/

**Comment by sybrew** [comment]
_Author of The SEO Framework here..._

What are the compatibility issues found? I might be able to resolve it from my side.

**Comment by glueckpress** [comment]
@sybrew Thanks for chiming in, we appreciate it! 

In this case, no real issue. I suggested to add integrated support of WP Rocket’s _Sitemap Preload_ feature for the sitemap generated by your plugin. We [do that for Yoast](https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/plugins/seo/yoast-seo.php#L12-L98) and a [couple of others](https://github.com/wp-media/wp-rocket/tree/master/inc/3rd-party/plugins/seo).

If you’re interested in getting your plugin supported, feel free to send a pull request from your end, that could speed things up. 😉 

However, it’s not that currently there would be an incompatibility. People just need to add their sitemap URL manually if they use your plugin.
