### ISSUE TITLE
3.0 Beta - First Installation error

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#902]
On a new website, in local mode (with Local by Flywheel), when I install for the very first time WP Rocket 3.0 (without having before WP Rocket other versions), I have an error when I click on activate (Chrome)

then I refresh the page and the plugin is ok and activated
Jonathan had the same issue on another website

![capture d ecran 2018-03-22 a 10 12 28](https://user-images.githubusercontent.com/24562283/37763458-70d03ada-2dbf-11e8-9ffe-fa166d6251ea.png)

**Comment by GeekPress** [comment]
Emilie confirmed it has been fixed.
