### ISSUE TITLE
3.0 beta - Localization issues

### ISSUE THREAD

**Issue by AliceOrru** [wp-media/wp-rocket#904]
This is the list of i8n issues for ES + IT: 

1. FAQ on the Dashboard not translated: (both IT and ES): http://jmp.sh/PqmgwuW
1. Account info strings not translated: (both IT and ES) http://jmp.sh/KaS3rfP
1. Only for ES: this button is redirecting to English docs instead of Spanish: http://jmp.sh/ZSHGIij
1. Remove query strings description not translated (ES + IT): [http://jmp.sh/KvXT9g2](http://jmp.sh/KvXT9g2
)
1. All "_More info_" links redirect to EN docs instead of ES or IT, i.e.: http://jmp.sh/tDtkAhz
(basically almost all internal links to docs redirect to the EN version instead of the localized docs)
1. All descriptions in the #advanced_cache tab are not translated (IT + ES): http://jmp.sh/YtwddA5
1. CDN tab: ”_CSS&JavaScript_” item in the menu is repeated 3 times: http://jmp.sh/APAUYyj
1. CDN tab: ”_Exclude files from CDN_” string and field description are not translated (IT+ES): http://jmp.sh/GjMIuSA
1. Tools tab: ”_Export Settings_” string not translated: http://jmp.sh/DnTj11n

**Comment by Tabrisrp** [comment]
2 and 9 had an incorrect text domain in the code, it will be fixed.

For 1, 3, 5, I believe it is a conscious choice, we only provide EN & FR versions for those (ping @GeekPress @ernee)

For 4, 6, 8, it's because the string itself changed between the moment you did the translation and now, so it needs to be updated (you can do it on transifex)

For 7, I'm not sure how this is happening. Is it displaying the same string 3 times in place of just CSS and JS?

**Comment by AliceOrru** [comment]
If we don't plan to localize docs with 3.0, we can leave the FAQ section in English.

But do we have any idea about if/when we're going to localize them? It's a pity to not profit from the new UI, which makes documentation so easy to read. 
From a customer point of view, if I use the plugin in one of our 5 official languages, I expect to be able to access localized docs as well. Otherwise the whole experience might feel a bit incomplete.

**Comment by Tabrisrp** [comment]
@AliceOrru for n°7, it's a translation issue in the es_ES file, the same translation is used for the 3 lines. It can be fixed quickly in transifex.

**Comment by AliceOrru** [comment]
Thanks, going to work on Transifex right now.

**Comment by arunbasillal** [comment]
For number 8 - there is an extra space in the text-domain for "Exclude files from CDN" that is preventing translation - https://github.com/wp-media/wp-rocket/blob/branch-3.0/inc/classes/admin/settings/class-page.php#L1527
