### ISSUE TITLE
3.0 Beta - All Tabs - Be sure our CSS rules on color text can't be override by another plugin

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#905]
A customer had the issue => https://downloads.intercomcdn.com/i/o/52743235/70b5ad2b3112f62e3662a6c6/image.png

**Comment by Thomasgeisen** [comment]
All CSS classes are prefixed with `wpr-`.
In that case, `wpr-menuItem` is overwritten... So another plugin use the same prefix ?

I will force white color on `wpr-menuItem` children, but it's strange...

**Comment by GeekPress** [comment]
I have no idea how it's possible. I reported an issue that an user had.

**Comment by GeekPress** [comment]
I'm waiting the customer confirmation to be able to valid this fix.

**Comment by GeekPress** [comment]
Issue has been confirmed fixed by the user :)

**Comment by GeekPress** [comment]
Je ré-ouvre l'issue, le client est revenue avec d'autres soucis de CSS surchargés 

> En fait il y a encore le bouton "mon compte" et il passe en rouge avec le hover (idem pour le bouton télécharger les réglages du menu outils ) et les boutons du menu de droit qui ont le text noir qui passent aussi en rouge avec le hover

**Comment by GeekPress** [comment]
I forgot the screenshot from the customer => https://downloads.intercomcdn.com/i/o/53043588/f0ac6be574351adeffcd1dd9/image.png

**Comment by GeekPress** [comment]
Waiting for customer confirmation

**Comment by GeekPress** [comment]
Confirmation about the fix from the customer :)
