### ISSUE TITLE
3.0 beta - Missing Learn more link in Cloudflare settings description

### ISSUE THREAD

**Issue by mobby2561** [wp-media/wp-rocket#907]
Here in Cloudflare add-on is missing some Learn more link https://github.com/wp-media/wp-rocket/blob/branch-3.0/inc/classes/admin/settings/class-page.php#L1751

**Comment by Kleindberg** [comment]
It's true.

**Comment by Tabrisrp** [comment]
Thank you for your report it will be fixed in the next beta
