### ISSUE TITLE
YouTube lazy loading doesn't work with cookieless domain

### ISSUE THREAD

**Issue by barisunver** [wp-media/wp-rocket#911]
Hi guys. Quick bug report: YouTube generates the iframe with a different domain at "youtube-nocookie.com" when "privacy mode" is selected while generating the iframe. Your lazy loader doesn't recognize that domain, thus fails to replace the iframe with your script.

**Comment by Tabrisrp** [comment]
Hi @barisunver,

To clarify, you're talking about the option to replace the Youtube video by the image thumbnail, correct?

Is the iframe directly loaded instead of being replaced?

**Comment by barisunver** [comment]
Yes, replace-embed-with-clickable-thumbnail thingy. I don't know much regex and I don't know how to suggest a patch in GitHub, but line 526 of inc/front/lazyload.php should be like this:

`$pattern = '#^(?:https?://)?(?:www\.)?(?:youtu\.be/|youtube\.com|**youtube-nocookie\.com**(?:/embed/|/v/|/watch\?v=))([\w-]{11})#iU';`

**Comment by Tabrisrp** [comment]
indeed, thank you for the feedback, we can implement that in a future minor version
