### ISSUE TITLE
Edge Case - Trimming for %2F returns incorrect path

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#914]
If you process this line of process.php - https://github.com/wp-media/wp-rocket/blob/master/inc/front/process.php#L57 with value of $path as /dev2/ instead of the expected result of `dev2`, you get `dev`. 

The `2` is trimmed off.

**Comment by Tabrisrp** [comment]
Solution is to replace the trim by

`preg_replace( '/^(?:%2F)*(.*?)(?:%2F)*$/', '$1', rawurlencode( $path ) )`
