### ISSUE TITLE
3.0 - Display all tab's content if no JS 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#923]
Since new design, if we don't have JS activated or a JS error is triggered by an other plugin, we can't switch on our tabs which is very problematic to configure the plugin.

To avoid that, we must display the content of all tabs by default and hide them in JS if it's activated.

**Comment by GeekPress** [comment]
Thomas finished his work on the 3.0 since the release and he isn't available. So now we can't ask him to make new updates on CSS & JS part. We have to make it.

**Comment by Tabrisrp** [comment]
who in the team has the JS skills to handle that?
