### ISSUE TITLE
3.0 - Serve Beacon JS/CSS from wp-rocket.me server to bypass ad-blockers

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#924]
As Beacon from HelpScout is blocked by ad-blockers, we added a notice to ask our users to white list their own website.

This notice seems to be confused for some customers who don't understand why we are asking them to disable their ad-blocker.

To avoid that, we can fix the issue by storing the JS & CSS files from beacon ourself. I tried something quickly which work well.

In inc/classes/admin/settings/class-page.php we replace "https://djtflbt20bdde.cloudfront.net/" by our own JS file located on our website. Currently it's in tools/wp-rocket/helpscout/beacon.js but it can be moved somewhere else.

To avoid browser caching issue, we must add a random query string at the end, like ?ver=timestamp

There is also a beacon.css file which should be in the same folder than beacon.js. In the JS file, the CSS file depending on our beacon account settings is loaded. So the call to old distant domain has been replaced by beacon.css

When we will have more time, we can make a cron job on the website which will update the Beacon JS & CSS file to be sure to always have the last update.

**Comment by Tabrisrp** [comment]
Seems good to me, doing it like this makes the change easy in the plugin itself

**Comment by Tabrisrp** [comment]
From my experience doing support the last couple of days, not once Beacon was blocked by my adblocker (uBlock Origin).

As far as I know, the support team experience is the same. It looks like we can remove the adblocker notification and be done with it.

**Comment by GeekPress** [comment]
I've just tried and I still get the notice => https://cl.ly/0k3932201c3s

If I got it, it mean that customers can do too.

**Comment by Tabrisrp** [comment]
I do have the notice displayed with uBlock Origin, but Beacon is still available and working.

Do you not see Beacon with your adblocker, even with the notice displayed? (and which one is it)

**Comment by GeekPress** [comment]
I'm using AdBlock (Chrome)

**Comment by Tabrisrp** [comment]
Closing as Beacon 2.0 is not blocked by adblockers.
