### ISSUE TITLE
Force caching file generation when SG Optimizer is detected

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#925]
Sometimes and for an unknown reason, the NGINX cache from SiteGround doesn't work.

And it's a big problem for us as SG Optimizer auto-disable our caching file generation. It means that when SG NGINX cache doesn't work, our users can't have a fallback to be cached.

The bad thing is our user think that WP Rocket isn't working. And we can understand this reaction.

I already talk about this issue with Hristo from SiteGround and he confirmed me that they will remove our filter to block the caching generation in their next update.

On our side, to be sure it will also work with their old version, we can override the filter to force the caching file generation.

**Comment by Tabrisrp** [comment]
We override their override then 😆

**Comment by Volnus** [comment]
I like this idea from a personal experience I would say my average cache hit rate on Siteground even when its using a fairly static website / blog is about 50% because it can't precache pages and it seems to flush them quite often ~

**Comment by Tabrisrp** [comment]
@arunbasillal For that, you can add code in the siteground compatibility file, check the current version of the SG Optimizer plugin, and only force the cache creation if the version is under 4.0.5.

Use `add_filter( 'do_rocket_generate_caching_files', '__return_true, 11 );` to force the cache creation
