### ISSUE TITLE
Cloudflare  - No validation of API info when saving

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#934]
When inputting the Cloudflare email/API key, there is no validation or other messaging when you save. So you can save incorrect information and you won't know. 
Only if you try and clear the Cloudflare cache will some kind of error be displayed.

**Comment by arunbasillal** [comment]
Related conversation - https://wp-media.slack.com/archives/CFSCRLVGB/p1569863861001500
