### ISSUE TITLE
CDN: Selected file types for CNAME missing in admin UI

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#935]
When you add a new Cname in the settings, the `reserved for` value is not displayed next to the Cname URL. As we can't expect our users to remember which Cnames is set for which type of files, this data should also be displayed.

Tagging you @edenpulse on it so that you can think about the design of it.

![cnames](https://user-images.githubusercontent.com/3465180/38456491-2b0cfb32-3a53-11e8-8781-8ef099712834.jpg)

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;80565aa2807d47e8a6d3ab9626e69bad:F60554154.A2009246&#x2F;cdn.png">cdn.png</a>

**Comment by glueckpress** [comment]
(edited title for clarity/findability)

**Comment by edenpulse** [comment]
![cdn](https://user-images.githubusercontent.com/433393/39986625-88b3a12e-5762-11e8-985d-71d2489cc784.png)
This is my prop. Reverted back to the 2.x UX.

**Comment by emlebrun** [comment]
➤ Matthieu Bousendorfer commented:

Responded in issue.
