### ISSUE TITLE
No successful licence check when installing via Composer

### ISSUE THREAD

**Issue by goaround** [wp-media/wp-rocket#938]
Hi,

I install & update WP Rocket from this git repository through Composer on my WordPress installation. With the latest version  3.0.3 I always get an error message saying that the licence could not be automatically checked and the API-Key & Email-Adress fields are deactivated.

When I install WP Rocket through the zip-file, I have no problems with that licence check.

**Comment by Tabrisrp** [comment]
Hi,

The reason is detailed here: https://github.com/wp-media/wp-rocket/issues/479#issuecomment-368961818

To be 100% composer ready we need to update this part of the code

**Comment by goaround** [comment]
Hi Tabrisrp,

alright, thank you. Would be great to define WP_ROCKET_WEB_MAIN in wp-config.php or just set it default to https://wp-rocket.me/

**Comment by koendoit** [comment]
> Hi Tabrisrp,
> 
> alright, thank you. Would be great to define WP_ROCKET_WEB_MAIN in wp-config.php or just set it default to https://wp-rocket.me/

Would be great indeed! 👍
