### ISSUE TITLE
Warning: Illegal offset type in isset or empty in inc/functions/i18n.php on line 271

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#939]
`Warning: Illegal offset type in isset or empty in /www/htdocs/w0136f66/casida.de/wp-content/plugins/wp-rocket/inc/functions/i18n.php on line 271`

https://github.com/wp-media/wp-rocket/blob/master/inc/functions/i18n.php#L271

Ticket: https://secure.helpscout.net/conversation/557392038/64786/

**Comment by Tabrisrp** [comment]
Line doesn't match anymore compared to when the issue was opened. Do you remember what it was refering to, and if it still exists in the current code?

**Comment by arunbasillal** [comment]
This was the original line I believe (customer's WP Rocket version was 3.0.2) - https://github.com/wp-media/wp-rocket/blob/2cf0dc4db66a2d425a97d421d4c44037514e0c48/inc/functions/i18n.php#L271

I believe the equivalent now is this - https://github.com/wp-media/wp-rocket/blob/35533b0069b2f1313e30c2b310856daf47fd9880/inc/functions/i18n.php#L308

I tried multiple instances but couldn't replicate it. Since we do not have other customers reporting it, we could think of it as one off and ignore this. 

I have sent the customer a note to see if it happened again.
