### ISSUE TITLE
Restore default placeholders in text areas (small text update for DNS prefetch)

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#941]
Restore default placeholders in 2.11 that were not carried over to 3.0. These help model for the user how to correctly use the text areas (use wildcard exclusions, etc.)

**File Optimization Tab:** 

-- Placeholders for Excluded CSS and JS

![screen shot 2018-04-09 at 6 07 10 pm](https://user-images.githubusercontent.com/8108643/38543027-b7b6950a-3ca3-11e8-9bbb-e0cb18dc3421.png)

**Preload Tab:**

-- Placeholder for Sitemap Preload:

![screen shot 2018-04-09 at 6 09 57 pm](https://user-images.githubusercontent.com/8108643/38543715-9e8d5030-3ca5-11e8-9a03-96ff1761e76c.png)

-- Placeholder for Prefetch DNS Requests
-- Add back the line _(no `http:` , one per line)_ 

![screen shot 2018-04-09 at 6 09 12 pm](https://user-images.githubusercontent.com/8108643/38543299-8575b6ba-3ca4-11e8-9c04-f6f1fc82e769.png)

**Advanced Rules Tab:**

-- Placeholder for Never Cache URL(s)

![screen shot 2018-04-09 at 6 08 34 pm](https://user-images.githubusercontent.com/8108643/38543771-c77e90ee-3ca5-11e8-97cb-34c6950b79c6.png)

-- Placeholder for Never Cache User Agent(s):

![screen shot 2018-04-09 at 6 08 52 pm](https://user-images.githubusercontent.com/8108643/38543919-3c0c8eac-3ca6-11e8-9fae-4bbdd3cb0cec.png)

**CDN Tab:** 

-- Placeholder for Exclude files from CDN

![screen shot 2018-04-09 at 6 08 18 pm](https://user-images.githubusercontent.com/8108643/38544075-b7cfa7e0-3ca6-11e8-9feb-e2021aba09b5.png)

Some initial customer and support experiences without the placeholders:

https://wp-media.slack.com/archives/C08N8J6VC/p1523268265000110
https://secure.helpscout.net/conversation/557363449/64780/?folderId=1724284
https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/250924/conversations/15638953421

@GeekPress and @edenpulse feedback is welcome

**Comment by GeekPress** [comment]
100% agree with you, we must re-introduce the placeholders.
