### ISSUE TITLE
Sumo Me plugin prevents settings page working correctly

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#943]
When the Sumo Me plugin is active, the tabs on our page don't work properly. You have to refresh the page to get the content to load. Can we stop Sumo Me loading its assets on our screen as @arunbasillal did for some other plugins in the past? 
https://wordpress.org/plugins/sumome/
HS tags: `sumome`, `settings page`

**Comment by arunbasillal** [comment]
Helper plugin is ready - https://www.dropbox.com/s/ky1h1yotndxgnre/wp-rocket-helper-compat-sumome.zip?dl=0

Will add directly to core instead of adding to our helper plugin repo. Next minor release hopefully. 
Installed on Main mega site if you want to give it a quick test.

**Comment by Tabrisrp** [comment]
@arunbasillal You can implement what you did directly in the WP Rocket

**Comment by arunbasillal** [comment]
#NoteToSelf - Test this on admin after SumoMe is configured to see if anything new comes up.
