### ISSUE TITLE
3.0 - CDN does not respect file types choice

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#946]
Note from customer

> In the new version of WP Rocket, when I add a URL path and specify it is reserved for scripts only (or images only), Rocket disregards my choice and implements the CDN path for ALL scripts and images.

Video: https://cl.ly/290u1c1F063k
Ticket: https://secure.helpscout.net/conversation/558733513/65012?folderId=273761

I tested this on another install and noticed the same. 

Related UI issue (not sure if this should be another GH issue). In the past, our UI specified the type the CNAME was associated with:

![wp rocket wordpress 1](https://user-images.githubusercontent.com/5751474/38600321-65b09c54-3d81-11e8-8f74-a0afac90f161.png)

Now it just shows the CNAME without the associate file type. 

![wp rocket mega wp rocket test wordpress](https://user-images.githubusercontent.com/5751474/38600334-72b7a7a8-3d81-11e8-9c68-3aa97dbd2c51.png)

**Comment by arunbasillal** [comment]
Another related ticket: https://secure.helpscout.net/conversation/558789948/65019?folderId=273761

**Comment by ernee** [comment]
Another ticket where the file reservations don't work: https://secure.helpscout.net/conversation/560677106/65291/

**Comment by AliceOrru** [comment]
Another one: https://secure.helpscout.net/conversation/562786822/65572?folderId=273761

**Comment by emmtre** [comment]
Any updates when 3.0.5 will be released with this fix?

**Comment by arunbasillal** [comment]
@emmtre We are testing 3.0.5 internally and should be available shortly.
