### ISSUE TITLE
Update automatic full cache deletion implementation

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#949]
Our current system to trigger automatic full cache deletion on specific WordPress action hooks is useful and relatively well thought-out, but it is causing a number of side issues. Some examples:

**Cache deletion on creation/update/delete of a not public term**

This one was brought up by Kinsta, coupled with Yoast SEO Premium, where they create terms on the fly for one of their features. This was creating quick and successive cache clear calls for nothing, as the taxonomy is not public.

**PHP errors because of the parameters passed to the action**

`rocket_clean_domain()` expect a `$lang` parameter, but the actions it is hooked on are passing very different parameters. This has been the cause of various PHP errors on customers' websites, notably with Polylang and WPML.

**How to improve**

`rocket_clean_domain()` should not be the callback function for the actions. We should introduce specific functions for group of related actions, that would in turn call `rocket_clean_domain()` if necessary.

**Main drawback**

Doing this change will require that all our customers who disabled the automatic full cache deletion (via mu-plugin or our helper) to update to the new code, since the callbacks will change.

**Comment by Tabrisrp** [comment]
#283 is related to this too

**Comment by Tabrisrp** [comment]
#1180 related

**Comment by piotrbak** [comment]
Closing it until receiving more feedback from customers or partners.
