### ISSUE TITLE
Create way for users to exclude CDN from SSL

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#950]
Although we removed the option in 3.0 version settings, some users still would like to have the option to exclude the CDN from SSL (for example if their CDN doesn't support SSL like this case: https://secure.helpscout.net/conversation/560718690/65299?folderId=1391600)

i.e helper plugin or code snippet

**Comment by arunbasillal** [comment]
Helper plugin ready here: https://www.dropbox.com/s/dwa1isb9zg9dwd4/wp-rocket-helper-disable-cdn-on-https.zip?dl=1

Sent to user as well. 

#NoteToSelf - Once user confirms, adapt it to the helper repo boilerplate and add to helper repo.

**Comment by arunbasillal** [comment]
Helper plugin added: https://github.com/wp-media/wp-rocket-helpers/tree/master/various/wp-rocket-disable-cdn-on-https
