### ISSUE TITLE
Convert Jetpack Custom CSS to a static file 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#955]
Jetpack enables their Custom CSS module by default _(and_ makes it hard to find in order to turn off ). 

The file that it creates takes ages to load: 
![website_speed_test](https://user-images.githubusercontent.com/1043076/38894279-a07af8ba-4241-11e8-825e-5a5b04e9e0f8.jpg)

![jetpack](https://user-images.githubusercontent.com/1043076/38894347-cda97d98-4241-11e8-96e9-ea29bd0f5610.jpg)

Could we convert it to a static file and timestamp it, like we did with the simple custom css plugin?

**Comment by Tabrisrp** [comment]
I have to check Jetpack code for this, but it's very likely we can do the same

**Comment by piotrbak** [comment]
@webtrainingwheels is this still accurate? I wasn't able to get the `custom-css=` in the DOM. Added CSS as described here:
https://jetpack.com/support/custom-css/
was an inline one

**Comment by webtrainingwheels** [comment]
@piotrbak I haven't seen it in a while.... maybe they changed something since 2018 😬

**Comment by piotrbak** [comment]
Not able to reproduce it anymore.
