### ISSUE TITLE
rocket_serve_cache_file() Last-Modified header clashes with dynamic cookies

### ISSUE THREAD

**Issue by electrokit** [wp-media/wp-rocket#963]
Consider this scenario
* Cookie test_cookie is set as a dynamic cookie (via 'rocket_cache_dynamic_cookies' hook). Possible values are 'on' and 'off'.
* example.com/somepath is cached for both cookie values (somepath-on.html and somepath-off.html).
* User browser visits example.com/somepath with cookie value 'off'.
* User browser visits example.com/somepath, now with cookie value 'on'.
The following code will now check somepath-on.html file date and send a 304 status code, which makes the browser show the page corresponding to cookie value 'off'.
https://github.com/wp-media/wp-rocket/blob/06739233dce65ebd4ade719e40354bed3150056e/inc/front/process.php#L365-L370
Maybe we should not send a 304 when a dynamic cookie is set? This wrongly sends 304 on requests after unsetting a cookie, but it may be an acceptable compromise.
If we don't want any erroneous 304s, I think we have to disable 304s when dynamic cookies setting is not empty.

**Comment by electrokit** [comment]
Seems that way, read it a little to hastily. Any easy way to make sure they don't get created at the same second? It happens quite a lot during testing, and will probably happen when we start using a preloader. Trying to make sure they don't get the same mtime will probably be a pain.

**Comment by piotrbak** [comment]
It looks like this one is related:
https://secure.helpscout.net/conversation/718054372/88214?folderId=2415573

**Comment by piotrbak** [comment]
Closing it until receiving more feedback from customers.
