### ISSUE TITLE
Proposal: Simulate a visit to the homepage after clearing the whole cache

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#967]
When we click on "Clear cache" from the admin bar or the dashboard button, we purge all kind of caches: page, busting, minification/concatenation.

To avoid waiting a first visitor to generate the busted and minified files, we could simulate a visit on the homepage after the "Clear cache" action purged the homepage. It will help us to generate the files in "background".

**Comment by arunbasillal** [comment]
This sounds essentially like preloading but just for the homepage to me. 

The fact that WP Rocket doesn't automatically start preloading when we clear the cache manually is very helpful during testing. 

Since normal users do not have to clear the entire cache manually, do you think this would be useful to a lot of people? I guess most of the time we hit clear cache manually is for some sort of testing.

**Comment by arunbasillal** [comment]
@Tabrisrp / @GeekPress In the light of recent developments that were done to preload, maybe we can revisit this? 

I remember in a call I mentioned this and I said what I said in my previous comment ( https://github.com/wp-media/wp-rocket/issues/967#issuecomment-384642524 ). But I couldn't come up with a use case for this. 

So maybe it's a good idea to do this after all.

**Comment by arunbasillal** [comment]
I just encountered a use case where Preload not auto-starting after a cache clear is helpful. When you are logging some thing and do not want the log to be filled up before you have a chance to inspect it. 

Of course, this is just a minor case and during testing, we can disable pre-loading temporarily.

**Comment by arunbasillal** [comment]
Let's finalize this during our dev call. 

JB mentioned that having the homepage preloaded might make checking to see if "Cache is cleared" bit more harder and confusing for customers. There might be other cases (as in my previous comment) where not having this will be helpful.

An idea is to not do this if `WP_ROCKET_DEBUG` is defined as `true`.

**Comment by arunbasillal** [comment]
In the 3.3.6 meeting we decided to go ahead with the check for `WP_ROCKET_DEBUG` and to go ahead with this.
