### ISSUE TITLE
Compatibility with Ginger – EU Cookie Law plugin

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#970]
Plugin: https://wordpress.org/plugins/ginger/
Ticket: https://secure.helpscout.net/conversation/569052539/66450?folderId=1724284

7000+ active installs, something we can add to WP Rocket core hopefully.

**Comment by camilamadronero** [comment]
Another ticket: https://secure.helpscout.net/conversation/818204030/102718?folderId=2675957.

**Comment by arunbasillal** [comment]
@camilamadronero and I did some tests together and the results are as follows: 

From Ginger's settings

`Do you have a cache system?` = Yes | No (same result for both)
`Cookie confirmation Type` = Opt-Out
`Force reload page` = Yes | No (same result for both)
Before accepting notice = Cached version. After accepting notice = Cached version. 

====

`Do you have a cache system?` = Yes
`Cookie confirmation Type` = Opt-In
`Force reload page` = Yes | No (same result for both)
Before accepting notice = No cache. After accepting notice = No cache.

====

`Do you have a cache system?` = No
`Cookie confirmation Type` = Opt-In
`Force reload page` = No | Yes (If set to no, refresh manually for the following result)
Before accepting notice = No cache. After accepting notice = Cache.

====

Also refer: https://wp-media.slack.com/archives/C60QX4FC1/p1554476423003100

**Comment by arunbasillal** [comment]
The original plugin has been removed from WordPress repo. Closing this one.
