### ISSUE TITLE
Seems to be broken with new Enfold 4.3 Performance Options

### ISSUE THREAD

**Issue by warhost** [wp-media/wp-rocket#971]
Hey,

I just updated WP-rocket to 3.0.4 and also the Enfold Theme to 4.3, which introduces new Performance Options, basically minification+combination of CSS and JS. So I enabled both in Enfold Options, and disabled these 2 in WP-Rocket.
Now, Google Pagespeed shows that there is no expiration set for any file, be it JS, CSS, or images.
Also, HTML Minfication does not seem to work anymore.

Any ideas?

**Comment by Tabrisrp** [comment]
Hi,

You should contact our support for this kind of issues, we don't do support on github: [support](https://wp-rocket.me/support/?utm_source=github&utm_medium=wp_rocket_profile)
