### ISSUE TITLE
Better handling of huge sitemaps for preload

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#973]
On websites with a lot of posts, pages and products, our sitemap based preload fails. An example I handled had over 43k items in the sitemap. Using a sub-sitemap with much lesser links worked though. 

This was reported by @girlie also where the sitemap had over 66k items.

**Comment by arunbasillal** [comment]
Related ticket: 
- https://secure.helpscout.net/conversation/565749480/65991/

**Comment by arunbasillal** [comment]
Hey @Tabrisrp, just thinking out loud. You probably already did think of this. 

For the preloading with super high number of posts. 

- Assuming that sitemap generators split sitemaps into smaller chunks. Like Yoast splitting it into 1000 or so links per sitemap.
- We save the list of sitemaps in a db instead of the urls themselves. 
- Pick the first sitemap, process its links, push to queue, delete the sitemap.
- Process the queue as we do now. 
- When the queue is empty, check if there are more sitemaps, if so repeat.

**Comment by Volnus** [comment]
I am gonna give some insight on this as well. I recently worked on / still am working on a site with over 40k products from woocommerce the sitemap. The major issue I see in this case is I had started the manual preload option at about 8 am my time it's about 3:30 PM now. It's only processed about 11k items so far to go into the cache. (site is running Yoast SEO as well).

On a normal website where the default global cache expires in 10 hours these sitemaps would essentially never be fully processed and would be cleared out by the time they finished. Now, if the preload process restarts its self after clearing the cache, you would be left with the process running almost continuously. Now, knowing this and the application of the website I simply set the global cache to last forever.

Food for thought. The website was using, WooCommerce more for a product gallery as all products need to have a quote given to the user by them calling, I didn't develop the site but thought the input would be insightful. I figure sometime tomorrow the cache should be fully generated.

**Comment by webtrainingwheels** [comment]
Related: https://secure.helpscout.net/conversation/829974034/104669?folderId=377611

also check the tags: `max_allowed_packet` and `max_input_vars` for further examples.

**Comment by naurissteins** [comment]
Still waiting for this....

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1494470275/259070/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1535656337/269712/

**Comment by viobru** [comment]
Likely related: https://secure.helpscout.net/conversation/1790670091/326833/

**Comment by piotrbak** [comment]
The issue is not relevant anymore, since we changed the way how we're dealing with URLs that are supposed to be preloaded.
