### ISSUE TITLE
Detecting CSS from non-standard stylesheet <link> tags

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#974]
Our current regex to match the CSS stylesheets does not match stylesheets if they are present in a non-standard way. 

Current regex: https://github.com/wp-media/wp-rocket/blob/78983800bca72b536b5958697ad4fdf47bdd801e/inc/functions/minify.php#L21

Does not match this ( https://regex101.com/r/XaZIl5/1 ): 

```
<link rel="stylesheet" href="https://www.example.com/wp-includes/css/dashicons.min.css?ver=4.9.5">
```

but will match this (a space before the closing `>` ) ( https://regex101.com/r/O2F5L0/1 ):

```
<link rel="stylesheet" href="https://www.example.com/wp-includes/css/dashicons.min.css?ver=4.9.5" >
```

Related ticket: https://secure.helpscout.net/conversation/572735455/67032?folderId=628132

**Comment by Tabrisrp** [comment]
The current pattern used to matche the CSS links uses (.+) after the href attribute, asking for 1 or more characters.

In some cases, the link tag doesn't contain anything after the href, so the tag is not matched, and not minified/combined.

Example : `<link rel="stylesheet" href="/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.0.1">`

Very edge case as it is not WordPress default output for CSS links at all. In the case encountered, it is the Soil plugin by Roots that is doing aggressive to the output for styles/scripts.

**Comment by webtrainingwheels** [comment]
HS tag: `css regex`

**Comment by arunbasillal** [comment]
Recently noticed two themes that does this in the page source. This caused issues with query string removal, minification and possibly combining of CSS.

It looks like both these are based on the roots.io/sage starter theme that ships with this code for "cleanup" - https://github.com/roots/sage/blob/d095c6eb588da5b39b878cfb4f9531528407cfac/inc/cleanup.php#L606-L614

Fix is to unhook these filters.
- For Ronneby theme - http://snippi.com/s/qinaru2
- For Bellevuex theme - http://snippi.com/s/ugbdj6l

**Comment by arunbasillal** [comment]
Helper plugin by @glueckpress until a solution is available in core: https://www.dropbox.com/s/vvmi188tvk8ebfh/wp-rocket-static-minify-regex.zip?dl=1

**Comment by glueckpress** [comment]
> Very edge case as it is not WordPress default output for CSS links at all.

@Tabrisrp Agreed, but it can cause [unnecessary support](https://secure.helpscout.net/conversation/604113634/71881?folderId=714999). 

Wouldn’t it be low-hanging fruit to push a minor update to the regex pattern, as outlined in #1030?

**Comment by Tabrisrp** [comment]
In 3.1, we won't be using regex anymore to collect all the CSS files in the HTML content, but a DOM selector directly, so this will in fact become invalid.

The new solution should be way more reliable, reducing unnecessary support.

**Comment by arunbasillal** [comment]
Test to see if @emlebrun's bot will comment every time I comment as well.
