### ISSUE TITLE
Load svg files via CDN

### ISSUE THREAD

**Issue by TheZoker** [wp-media/wp-rocket#975]
Currently my SVG files are not loaded via CDN.

I'm aware, that often there is a SVG reference, that should not be loaded via CDN, but an image like
```
<img src="logo.svg" alt="">
```
can also be loaded via CDN

**Comment by Tabrisrp** [comment]
If the SVG file path contains the content dir or wp-includes dir, it should be rewritten as any other image type.

**Comment by RichardUUU** [comment]
> If the SVG file path contains the content dir or wp-includes dir, it should be rewritten as any other image type.

That's not the case for me. Does wp-rocket see SVG as an image file?
