### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mugurcagdas** [wp-media/wp-rocket#984]
Dear Sir/Madam,

I am computer engineer and graphic designer. I use your plugin in my customers' websites. I appreciate that.
I am writing you because I want to design a logo for this plugin.
May I ask, do you need a logo for this plugin?

Kindly waiting your answer.

Best Regards,
Musa Ugur Cagdas
Computer Engineer/Graphic Designer

**Comment by pothi** [comment]
Not the best place to ask such questions. Please do not waste the time of everyone who watches this repo. Good luck!
