### ISSUE TITLE
rocket_clean_post() no longer callable

### ISSUE THREAD

**Issue by tewfik-dj** [wp-media/wp-rocket#987]
Hi,

Wordpress : 4.9.5
WP Rocket : 3.0.4
License Infinite

Calling rocket_clean_post()  from another plugin no longer works.
Checked that WP Rocket was indeed loaded before our plugin (it was the case)
We believe this is a bug introduced in this version, as it appears the new update caused this issue (last working version seems to be WP Rocket 2.11.7)

From wp-rocket/inc/main.php file , on line : 58, the inc/common/purge.php file is loaded only if a valid license is present

Any workaround before a proper fix ?

Thanks

**Comment by girlie** [comment]
​So, it seems that the issue in this case is not with the _rocket_clean_post()_ function itself, but rather, that an XML-RPC call is involved.
​
In 2.11.7, we didn't halt the execution of WP Rocket when doing a XML-RPC call -- but in 3.0.4, we do halt it -- so none of its functions would work in that case.
​
​However, this wasn't planned behavior, so Remy expects to correct this in the 3.0.5 release.
​

**Comment by tewfik-dj** [comment]
Issue solved, thanks !
